
## TOSS-UP  


1) Physics – Short Answer How many ways are there to position 5 equal positive charges so that they are in a stable configuration?  


ANSWER: 0  


## BONUS  


1) Physics – Short Answer Viraj is walking up a downward-moving escalator at a speed of 10 meters per second relative to the lab frame. However, the escalator is moving down at 4 meters per second. If Viraj weighs 60 kilograms, how much power does Viraj use to climb for 10 seconds, given that \(g\) equals 10 meters per second squared?  


ANSWER: 8400 WATTS  


## TOSS-UP  


2) Math – Multiple Choice \(f\) of \(x\) is a function that is continuous and differentiable over the reals, \(f\) of 0 equals 7, and \(f\) of 5 equals \(-3\) . \(f\) prime of \(x\) must have what value at at least one point on the interval between \(x\) equals 0 and \(x\) equals 5?  


W)- 4 X)- 2 Y)0 Z)2  


ANSWER: X)- 2  


## BONUS  


2) Math – Short Answer Let \(P\) of \(x\) equal \(x\) squared minus \(90 x\) plus two thousand and twenty-one. What is the greatest common denominator of \(P\) of 50 and \(P\) of 54?  


ANSWER: 7
## TOSS-UP  


3) Biology – Multiple Choice What type of speciation occurs within the original population and niche [NEESH] without relying on geographical isolation?  


W) Sympatric 
X) Peripatric [pair-EE-patric] 
Y) Allopatric 
Z) Parapatric [pair-UH-patric]  


ANSWER: W) SYMPATRIC  


## BONUS  


3) Biology – Short Answer Order the following four steps in the signal amplification of epinephrine [EP-uh-nef-rin] to trigger glycogen breakdown: 1) cyclic AMP [A-M-P] activates protein kinase A; 2) G proteins convert adenylyl [uh-den-uh-LEEL] cyclase into its active form; 3) Epinephrine binds to a cell-membrane receptor; 4) Phosphorylase [fos-for-il-ASE] kinase [KAI-nayse] is activated.  


ANSWER: 3, 2, 1, 4  


## TOSS-UP  


4) Earth and Space – Short Answer Wolframite [WOLF-ruh-mite], scheelite [SHE-lite], and [fer-buh-RIGHT] ferberite are ore minerals of what element?  


ANSWER: TUNGSTEN  


## BONUS  


4) Earth and Space – Short Answer Justin is doing field work for his college geology class. He notices a peculiar green rock and notes that it is coarse-grained and is largely composed of olivine [AW-live-een] and pyroxene [pie-ROCKS-een]. What rock that is common in the Earth’s mantle has he just stumbled upon?  


ANSWER: PERIDOTITE
## TOSS-UP  


5) Chemistry – Multiple Choice A molecule of butane is in the gauche [GOWSH] conformation. Which of the following could be the dihedral angle in degrees between its methyl groups?  


W) 0 
X) 60 
Y) 120 
Z) 180  


ANSWER: X) 60  


## BONUS  


5) Chemistry – Multiple Choice Given that the solubility constant for a binary ionic compound \(\mathrm{AX}_2\) is 1.08 times 10 to the \(-22\) , what is the solubility, in moles per liter, of this compound?  


W) 6.23 times 10 to the \(-3\) X) 3 times 10 to the \(-8\) Y) 9 times 10 to the \(-8\) Z) 1.08 times 10 to the \(-11\)  


ANSWER: X) 3 TIMES 10 TO THE \(-8\)  


## TOSS-UP  


6) Energy – Short Answer Using the Spallation [sph-LAY-shun] Neutron Source and High Flux Isotope Reactor, researchers at Oak Ridge Laboratory discovered that particles called phasons [FAZE-ons] induce the rearrangement of atoms, leading to the ability of heat to travel faster than what speed that was previously assumed to be a limiting factor in heat conduction?  


ANSWER: SPEED OF SOUND  


## BONUS  


6) Energy – Short Answer Scientists at Pacific Northwest National Laboratories are working on commercializing carbon capture and storage technologies. One method they are working on is sequestering carbon dioxide in rock formations. What commonly occurring rock did the carbon dioxide form after reacting with the basalt?  


ANSWER: LIMESTONE
## TOSS-UP  


7) Math – Short Answer What is the area under the curve of the normal distribution, commonly used in statistics?  


ANSWER: 1  


## BONUS  


7) Math – Short Answer What is the percentile, to the nearest integer, of a person whose height is 5 feet and 11 inches, given that the distribution of heights is approximately normal with a mean of 5 feet and 6 inches and a standard deviation of 2.5 inches?  


ANSWER: 98  


## TOSS-UP  


8) Earth and Space – Short Answer What is the term for a mass of igneous rock that has been intruded between rock strata, causing uplift in the shape of a dome?  


ANSWER: LACCOLITH  


## BONUS  


8) Earth and Space – Multiple Choice Which of the following driving forces is most responsible for seafloor spreading?  


W) Magma pressure at the center of a mid-ocean ridge  
X) Slab pull at subduction zones  
Y) Geomagnetic reversal  
Z) Ridge push at rifts  


ANSWER: X) SLAB PULL AT SUBDUCTION ZONES
## TOSS-UP  


9) Chemistry – Multiple Choice For the reaction with rate law rate equals \(k\) times the concentration of A, which of the following quantities would form a straight line when plotted against time?  


W) The concentration of A 
X) One over the concentration of A 
Y) The natural logarithm of the concentration of A 
Z) The concentration of A squared  


ANSWER: Y) THE NATURAL LOGARITHM OF THE CONCENTRATION OF A  


## BONUS  


9) Chemistry – Short Answer Calculate the half-life of a zero-order reaction with single reactant X if the initial concentration of X is 1 molar and if the final concentration of X is 0.2 molar after 8 seconds have elapsed.  


ANSWER: 5 SECONDS  


## TOSS-UP  


10) Physics – Short Answer To the nearest integer and in meters per second, at what upward velocity should a ball be thrown in order to reach an elevation of 20 meters?  


ANSWER: 20  


## BONUS  


10) Physics – Short Answer Observations show that when a neutron decays, protons and electrons produced don’t move in perfectly opposite directions. This observation notes the existence of what particle?  


ANSWER: NEUTRINO
## TOSS-UP  


11) Biology – Short Answer How many copies of the DNA template strand would be produced after seven cycles of PCR?  


ANSWER: 128  


## BONUS  


11) Biology – Short Answer What gland is responsible for producing prolactin?  


ANSWER: PITUITARY GLAND (ACCEPT: ANTERIOR PITUITARY GLAND)  


## TOSS-UP  


12) Energy – Short Answer Superconductors are generally classified as materials that can conduct electricity or transport electrons from one atom to another with no resistance. What type of superconductor is usually an alloy and has a more complex diamagnetism?  


ANSWER: Type II  


## BONUS  


12) Energy – Short Answer At Fermilab, researchers are using new kinds of superconductors to explain the behaviors of types of magnetic fields at low temperatures. One type of superconductor they are using is the Type I superconductor. Identify all of the following four superconductors that are Type I superconductors: 1) Aluminum; 2) YBCO; 3) Zinc; 4) Cuprate perovskite [puh-ROV-skitel].  


ANSWER: 1 AND 3
## TOSS-UP  


13) Physics – Short Answer By name or number, identify all of the following four quantities that are state functions: 1) Internal energy; 2) Density; 3) Work; 4) Entropy.  


ANSWER: 1, 2, AND 4  


## BONUS  


13) Physics – Multiple Choice Which of the following processes requires the most heat to be passed into the system given that they all have the same change in internal energy?  


W) Adiabatic cooling  X) Isochoric [iso- KORE- ic] expansion  Y) Adiabatic expansion  Z) Isobaric expansion  


ANSWER: Z) ISOBARIC EXPANSION  


## TOSS-UP  


14) Chemistry – Multiple Choice Which of the following is commonly used as a solvent in SN2 reactions?  


W) Methyl alcohol  X) Toluene [tall- YOO- een]  Y) Dimethyl sulfoxide  Z) Liquid ammonia  


ANSWER: Y) DIMETHYL SULFOXIDE  


## BONUS  


14) Chemistry – Short Answer Order the following three molecules by decreasing melting point: 1) Pentane; 2) Propionic [pro- PIE- onic] Acid; 3) Butanal.  


ANSWER: 3, 2, 1
## TOSS-UP  


15) Earth and Space – Multiple Choice The belt of prevailing global winds over the midlatitudes is known as the  


W) Westerlies 
X) Doldrums 
Y) Jet stream 
Z) Easterlies  


ANSWER: W) WESTERLIES  


## BONUS  


15) Earth and Space – Multiple Choice Which of the following best describes why two earthquakes might get the same score on the Richter [RICK-tuhr] scale but different scores on the Mercalli [mer-CA-lee] intensity scale?  


W) One earthquake occurred in an area built on solid bedrock, and the other occurred on loose sediments.  


X) One earthquake occurred in an area more prone to earthquakes, and the other occurred in an area less prone to earthquakes.  


Y) One earthquake occurred closer to the equator, and the other occurred closer to the poles.  


Z) One earthquake occurred in a subduction zone, and the other occurred in a transform boundary.  


ANSWER: W) ONE EARTHQUAKE OCCURRED IN AN AREA BUILT ON SOLID BEDROCK, AND THE OTHER OCCURRED ON LOOSE SEDIMENTS.  


## TOSS-UP  


16) Math – Short Answer Two chords of a circle intersect at a point inside the circle such that the first chord is split into segments of lengths 6 and 3, and the second chord is split into segments of lengths 4 and \(x\) . What is the value of \(x\) ?  


ANSWER: 4.5  


## BONUS  


16) Math – Short Answer Compute the sum from \(i\) equals 1 to 7 of the sum from \(j\) equals 1 to 7 of \(i\) times \(j\) .  


ANSWER: 784
## TOSS-UP  


17) Biology – Multiple Choice Which of the following reactions is not catalyzed in the Golgi apparatus?  


W) Phosphorylation 
X) Glycosylation 
Y) Sulfation 
Z) Hydroxylation  


ANSWER: Z) HYDROXYLATION  


## BONUS  


17) Biology – Short Answer What name is given to the stimulus response governing the action of plants that wrap around objects they come in contact with, such as vines wrapping around a building?  


ANSWER: THIGMOTROPISM  


## TOSS-UP  


18) Energy – Short Answer Scientists at SLAC National Accelerator Lab are studying the various causes of catalyst poisoning. One way this happens is when a molecule is so tightly bound to the surface of a catalyst that it inhibits the catalyst's ability to speed up a reaction. What is this phenomenon, where a species gets adhered to a surface?  


ANSWER: ADSORPTION  


## BONUS  


18) Energy – Short Answer Scientists at Sandia National Labs are working toward getting certain solar cells to commercialization. These solar cells have a crystal structure similar to bridgmanite [BRIJ-muh-night] and ipoartite [I-O-par-tight], which both follow the general chemical formula ABX3. What class of materials is named after the mineral calcium titanium oxide?  


ANSWER: PEROVSKITE
## TOSS-UP  


19) Math – Multiple Choice A right triangle has legs of lengths 12 and 16. Which of the following is the circumradius of this triangle?  


W) 6 
X) 8 
Y) 10 
Z) 12  


ANSWER: Y) 10  


## BONUS  


19) Math – Short Answer How many positive integers less than or equal to 200 are divisible by exactly two of 3, 5, and 7?  


ANSWER: 26  


## TOSS-UP  


20) Chemistry – Multiple Choice Which of the following compounds will dissolve better in \(n\) -heptane than in sulfuric acid?  


W) Sulfur hexafluoride 
X) Hydrogen Sulfide 
Y) Nitrogen Dioxide 
Z) Phosphoryl chloride  


ANSWER: W) SULFUR HEXAFLUORIDE  


## BONUS  


20) Chemistry – Short Answer Order the following four conformations of cyclohexane by increasing stability: 1) Half-chair; 2) Boat; 3) Chair; 4) Twist-boat.  


ANSWER: 1, 2, 4, 3
## TOSS-UP  


21) Earth and Space – Multiple Choice Which of the following types of supernovae [soo- pur-NO-vee] occurs when a white dwarf in a binary system exceeds the Chandrasekhar [chuhn- druh-SAY-kuhr] limit, causing a runaway fusion event?  


W) Type Ia 
X) Type Ib 
Y) Type Ic 
Z) Type II  


ANSWER: W) TYPE IA  


## BONUS  


21) Earth and Space – Short Answer Identify all of the following three statements that are FALSE about supernovae: 1) Type Ia supernovae are more luminous than Type II supernovae; 2) Type I supernovae have spectra containing hydrogen lines; 3) Type Ia supernovae form neutron stars or black holes.  


ANSWER: 2 AND 3  


## TOSS-UP  


22) Biology – Multiple Choice Which of the following plant hormones is incorrectly paired with its function?  


W) Gibberellin; stem elongation 
X) Auxin; apical dominance 
Y) Abscisic acid; promote leaf senescence [suh-NESS-ince] 
Z) Cytokinins [sai-toh-KAI-nins] ; fruit growth  


ANSWER: Z) CYTOKININS - FRUIT GROWTH  


## BONUS  


22) Biology – Short Answer As opposed to gradualism, what evolutionary hypothesis proposes that development in history is marked by isolated episodes of rapid speciation followed by long periods of little change?  


ANSWER: PUNCTUATED EQUILIBRIUM
## TOSS-UP  


23) Physics – Short Answer What principle states that a change in pressure will permeate throughout a liquid and onto the walls of the container of the liquid?  


ANSWER: PASCAL'S PRINCIPLE  


## BONUS  


23) Physics – Short Answer Water is flowing up a pipe with velocity 5 meters per second. At a height of 2.5 meters, the pipe narrows to half its original diameter. If the pressure of the water at the ground is 250 kilopascals, find the pressure of the water 4 meters above the ground in kilopascals to the nearest integer, given that the density of water is 1000 kilograms per meter cubed.  


ANSWER: 23