
## TOSS-UP  


1) Earth and Space – Multiple Choice Magma underneath a volcano forms basalt and gabbro when cooled. Which of the following features is the volcano most likely to have?  


W) Cinder cone 
X) Shield volcano 
Y) Stratovolcano 
Z) Lava dome  


ANSWER: X) SHIELD VOLCANO  


## BONUS  


1) Earth and Space – Short Answer What silicate group has a base structural unit of \(\mathrm{Si}_2\mathrm{O}_6^{4 - }\) [S-I-two-O-six-four-minus], contains chains of silicates, and includes the amphiboles and pyroxenes?  


ANSWER: INOSILICATES  


## TOSS-UP  


2) Chemistry – Short Answer Rank the following three absorptions by increasing wavenumber in Infrared Spectroscopy: 1) N–H stretch; 2) aldehyde C–O stretch; 3) N–O asymmetric stretch.  


ANSWER: 3, 2, 1  


## BONUS  


2) Chemistry – Short Answer Given that the standard oxidation potential for the Silver (I) [ONE] ion is \(-0.80 \mathrm{~V}\) , and the standard reduction potential for the Thallium (III) [THREE] ion is \(+0.72 \mathrm{~V}\) , calculate the voltage of a galvanic cell which reduces \(\mathrm{Ag}^+\) [A-G-plus] at the cathode and oxidizes \(\mathrm{Ti}^{3 + }\) [T-L-three-plus] at the anode.  


ANSWER: \(+0.08 \mathrm{~V}\)
## TOSS-UP  


3) Biology - Short Answer Chronic myelogenous [mai-uh-LOW-juh-nis] leukemia [loo- KEE-mee-uh] occurs when a reciprocal translocation swaps a large portion of chromosome 22 with a small fragment of chromosome 9. What is the name for the new small chromosome 22?  


ANSWER: PHILADELPHIA CHROMOSOME  


## BONUS  


3) Biology - Short Answer Justin has run out of vegetables that taste good to him, so he wants to bioengineer a new one. In order to do this, he uses what technique in which plant cells of different species have their cell walls removed and are then combined to form hybrid cells that grow in a culture?  


ANSWER: PROTOPLAST FUSION  


## TOSS-UP  


4) Math - Multiple Choice What is the value of the integral from 0 to infinity of the fraction with numerator e and denominator open parentheses pi times x close parentheses dx?  


W) 0 X) pi to the power of e Y) e to the power of pi Z) It diverges  


ANSWER: Z) IT DIVERGES  


## BONUS  


4) Math - Short Answer What is the indefinite integral of sine of x times the square root of open parentheses 1 plus tangent of x squared close parentheses with respect to x?  


ANSWER: - ln(cos(x)) + C (ACCEPT: - ln(cos(x)) + C)
## TOSS-UP  


5) Physics – Multiple Choice Which of the following actions will double the gravitational binding energy of a spherical planet?  


W) Doubling its mass 
X) Doubling its radius 
Y) Halving its mass 
Y) Halving its radius  


ANSWER: Z) HALVING ITS RADIUS  


## BONUS  


5) Physics – Short Answer What magnetic state is commonly referred to in quantum chaos theory and contains spins that are completely random, making it analogous to the random positional disorder in amorphous materials?  


ANSWER: SPIN GLASS  


## TOSS-UP  


6) Energy – Short Answer Scientists at Lawrence Berkeley National Lab have recently been investigating quantum computers. Pure states of the quantum bit, or qubit, can be represented on the surface of what 3-D geometric model?  


ANSWER: BLOCH SPHERE  


## BONUS  


6) Energy – Short Answer Researchers at Idaho National Lab have been attempting to create new nanotechnologies using conducting plates with small separation. They’ve been trying to apply what effect, in which the space between two conducting plates will have restrictions on virtual particle frequencies, causing a negative energy density?  


ANSWER: CASIMIR EFFECT
## TOSS-UP  


7) Chemistry – Multiple Choice Which of the following statements is true regarding carbocation [carbo-CAT-ion] rearrangements?  


W) Hydride shifts favor the formation of secondary carbocations because they are more stable than tertiary carbocations 
X) Methyl shifts favor the formation of secondary carbocations because they are more stable than tertiary carbocations 
Y) A hydride shift can occur that moves a tertiary carbocation to the vinylic position, creating a resonance-stabilized carbocation 
Z) A hydride shift can occur that moves a tertiary carbocation to the allylic position, creating a resonance-stabilized carbocation  


ANSWER: Z) A HYDRIDE SHIFT CAN OCCUR THAT MOVES A TERTIARY CARBOCATION TO THE ALLYLIC POSITION, CREATING A RESONANCE- STABILIZED CARBOCATION  


## BONUS  


7) Chemistry – Short Answer Order the following three isotopes by increasing binding energy per nucleon: 1) Tin-119; 2) Uranium-238; 3) Iron-56.  


ANSWER: 2, 1, 3
## TOSS-UP  


8) Biology - Multiple Choice Which of the following statements pertaining to chromatin and its modifications is FALSE?  


W) Telomeres [TEE-low-meers] are more likely to be composed of euchromatin [YOO-kromuh-tin] than heterochromatin [HET-ero-kro-muh-tin]  


X) Euchromatin has a dispersed arrangement when compared to heterochromatin 
Y) Euchromatin can be easily used to transcribe genes, while heterochromatin cannot 
Z) According to the histone code hypothesis, methylation and phosphorylation of neighboring residues on a histone tail should cause loosening of chromatin  


ANSWER: W) TELOMERES ARE MORE LIKELY TO BE COMPOSED OF EUCHROMATIN THAN HETEROCHROMATIN  


## BONUS  


8) Biology - Short Answer Identify all of the following four statements regarding piwi [PEE- wee]-associated RNAs that are true: 1) They induce the conversion of euchromatin to heterochromatin via acetylation [uh-SEE-tuh-lay-shun] of lysine residues on histone tails; 2) They inhibit transposon expression; 3) They can be found in both animals and plants; 4) They are a type of noncoding RNA.  


ANSWER: 2 AND 4  


## TOSS-UP  


9) Math - Short Answer If \(f\) of \(x\) , \(y\) equals \(x\) squared times \(y\) , what is the partial derivative with respect to \(x\) of the partial derivative with respect to \(y\) of \(f\) plus the partial derivative with respect to \(y\) of the partial derivative with respect to \(x\) of \(f\) ?  


ANSWER: \(4x\)  


## BONUS  


9) Math - Short Answer Let \(f\) be a function that removes the leftmost and rightmost digits of a positive integer and outputs the new, shortened number. For example, \(f\) of 1234 equals 23, and \(f\) of 12 equals 0. X is a positive integer with all nonzero digits such that X is divisible by 12, \(f\) of X is divisible by 45, and \(f\) of \(f\) of X equals 0. How many possible values of X are there?  


ANSWER: 6
## TOSS-UP  


10) Earth and Space – Short Answer What is the term for a geologic structure where the strata have an uniform dip in the same direction and approximately the same angle?  


ANSWER: HOMOCLINE  


## BONUS  


10) Earth and Space – Short Answer By name or number, identify all of the following four types of faults that are characteristic of a detachment fault: 1) Reverse fault; 2) Thrust fault; 3) Megathrust fault; 4) Normal fault.  


ANSWER: 4 ONLY  


## TOSS-UP  


11) Physics – Multiple Choice A strip is made of two metals, zinc and copper, which have linear expansion coefficients of 2.6 times 10 to the minus 5th power and 1.7 times 10 to the minus 5th power, respectively. Which of the following best describes what happens when the strip is heated?  


W) The strip will bend toward the copper.  


X) The strip will bend toward the zinc.  


Y) The strip will not bend.  


Z) More information about the amount that the strip is heated is needed in order to determine how the strip will behave.  


ANSWER: W) THE STRIP WILL BEND TOWARD THE COPPER.  


## BONUS  


11) Physics – Short Answer A container of water of mass 12 kilograms has a temperature 20 degrees Celsius. A hot 2-kilogram metal with temperature 150 degrees Celsius is placed inside the water to cool down. To the nearest degree, what is the temperature of the metal after it reaches thermal equilibrium with the water if the heat capacity of the water is 4200 Joules per kilogram Celsius and if the heat capacity of the metal is 126 Joules per kilogram Celsius?  


ANSWER: 21 DEGREES CELSIUS (ACCEPT: 294 KELVIN)
## TOSS-UP  


12) Energy - Short Answer Researchers at Oak Ridge National Lab are modelling the flow of water through plants to better understand resource distribution pathways. What hypothesis, the prevailing theory regarding plant nutrient transport, claims that xylem sap rises due to transpiration?  


ANSWER: COHESION- TENSION HYPOTHESIS  


## BONUS  


12) Energy - Short Answer Scientists at Argonne National Laboratory are using the Advanced Photon Source to study the primordial atmosphere of Earth. Molecules released from the outgassing process eventually react with crustal rocks to form what class of minerals?  


ANSWER: CARBONATES  


## TOSS-UP  


13) Earth and Space - Short Answer At Cape Cod, a spring tide is measured on the morning of September 5th. At what month and date is the next neap tide most likely to occur?  


ANSWER: SEPTEMBER 12TH  


## BONUS  


13) Earth and Space - Short Answer The tropical atmosphere fluctuates on 30-to-90-day intervals. This fluctuation is responsible for the inverse relationship between the tropical activity in the Western North Pacific basin and the North Atlantic basin, as well as Pineapple Express events in California. What phenomenon dictates these weather patterns?  


ANSWER: MADDEN- JULIAN OSCILLATION (ACCEPT: MJO)
## TOSS-UP  


14) Physics – Short Answer What name is given to a wave that maintains its shape while it moves as a result of the cancellation of dispersion?  


ANSWER: SOLITON  


## BONUS  


14) Physics – Short Answer Identify all of the following three statements about solitons that are true: 1) They are localized to a specific region; 2) Combining two solitons results in a bion; 3) They are unaffected in collisions with other solitons.  


ANSWER: 1 AND 2  


## TOSS-UP  


15) Biology – Short Answer Identify all of the following four drugs that are commonly used to treat breast cancer of the subtype Luminal A: 1) Herceptin; 2) Taxol; 3) Tamoxifen; 4) Lapatinib.  


ANSWER: 2 AND 3  


## BONUS  


15) Biology – Short Answer Identify all of the following three statements that are NOT true regarding the pentose phosphate pathway: 1) The first step is the reduction of glucose 6-phosphate as it accepts an electron from NADPH; 2) It occurs in the cytosol in mammals; 3) A reversal of its nonoxidative phase is essentially the Calvin Cycle.  


ANSWER: 1 ONLY
## TOSS-UP  


16) Chemistry – Multiple Choice Which of the following is closest to the bond angle in \(\mathrm{NO}_2\) ?  


W) 106 degrees  X) 118 degrees  Y) 134 degrees  Z) 162 degrees  


ANSWER: Y) 134 DEGREES  


## BONUS  


16) Chemistry – Multiple Choice One mole of a real gas at 0 degrees Celsius occupies 1 liter of volume. If the van der Waals parameters are \(a\) equals 10 atmosphere liters-squared per molesquared and \(b\) equals .05 liters per mole, which of the following is closest to the pressure of the gas?  


W) 6.5 atmospheres  X) 13 atmospheres  Y) 26 atmospheres  Z) 52 atmospheres  


ANSWER: X) 13 ATMOSPHERES  


## TOSS-UP  


17) Math – Multiple Choice Which of the following is the closest to the value of the integral from 1 to 400 of the natural log of \(x\) dx minus the natural log of 400 factorial?  


W)- 100  X) 0  Y) 100  Z) 10000  


ANSWER: X) 0  


## BONUS  


17) Math – Short Answer If \(f\) of \(x, y, z\) equals \(x\) times \(y\) minus \(y\) times the natural log of \(z\), find the Laplacian of \(f\).  


ANSWER: \(y / z^2\)
## TOSS-UP  


18) Energy – Multiple Choice Scientists at Argonne National Lab are studying nickel–bismuth compounds using the Advanced Photon Source to research the interactions between ferromagnetic and diamagnetic materials. Diamagnetic materials are defined to have what values for magnetic susceptibility?  


W) negative X) zero Y) positive Z) imaginary  


ANSWER: W) NEGATIVE  


## BONUS  


18) Energy – Short Answer Scientists at Oak Ridge National Laboratory are studying the impact of energy production on aquatic ecosystems. Recently, climate change has caused coral to bleach. What organisms are expelled from the coral polyp when bleaching occurs?  


ANSWER: ALGAE  


## TOSS-UP  


19) Chemistry – Short Answer Two pentane molecules are separated at a certain distance. If the distance between the molecules is halved, by what factor does the attractive force between them change?  


ANSWER: 128  


## BONUS  


19) Chemistry – Short Answer Identify all of the following three statements that are true regarding molecular orbitals: 1) All sigma bonding orbitals have zero nodal planes crossing the internuclear axis; 2) Bonding orbitals are constructed more from atomic orbitals of an electropositive element, and antibonding orbitals are constructed more from atomic orbitals of an electronegative element; 3) The molecular orbitals in a carbon-carbon triple bond create a region of electron density that lacks cylindrical symmetry due to pi molecular orbitals.  


ANSWER: NONE
## TOSS-UP  


20) Physics - Short Answer Sid kicks a ball into the air at an angle of 60 degrees at 20 meters per second. When the ball is at its highest point, what is the radius of curvature of its trajectory in meters, given that \(g = 10\) meters per second squared?  


ANSWER: 10  


## BONUS  


20) Physics - Short Answer Three spherical shells of masses 5, 10, and 15 kilograms that have inner radii and outer radii of 1 and 2 meters, 2 and 3 meters, and 3 and 4 meters, respectively, are placed inside each other, with the small shell being placed in the middle shell, which is then placed in the large shell. A torque of 17 newton meters is applied tangent to the outer shell. Find the acceleration at a point on the outer surface of the largest shell in meters per seconds squared.  


ANSWER: 1  


## TOSS-UP  


21) Math - Short Answer If log of 2 equals 0.301 and if log of 3 equals 0.477, what is log of 15?  


ANSWER: 1.176  


## BONUS  


21) Math - Short Answer Let \(a\) and \(b\) be the two distinct roots of \(x\) squared plus \(20x\) plus 21. Compute \(a\) squared minus \(20b\) .  


ANSWER: 379
## TOSS-UP  


22) Biology - Short Answer In prokaryotes, what sequence serves as the ribosomal binding site for mRNA, as opposed to the 5 prime cap in eukaryotes?  


ANSWER: SHINE- DALGARNO SEQUENCE  


## BONUS  


22) Biology - Short Answer Identify all of the following three monosaccharides that are aldoses: 1) glucose; 2) ribose [RAI- bose]; 3) fructose.  


ANSWER: 1 AND 2  


## TOSS-UP  


23) Earth and Space - Short Answer The optical depth decreases as an observer looks toward the edges of the Sun in the sky as opposed to the center of the disk. This leads to what phenomenon where the central part of the disk appears to be brighter than the edges?  


ANSWER: LIMB DARKENING  


## BONUS  


23) Earth and Space - Short Answer A star is 16 times as massive as the Sun. What factor of the Sun's lifetime will this star's lifetime be?  


ANSWER: 1/1024