sub_title[[455, 137, 541, 155]]
## TOSS-UP  

text[[115, 169, 866, 206]]
1) Biology – Short Answer What name is given to the small, bean-shaped structures that can capture circulating cancer cells and help fight infections?  

text[[115, 221, 351, 239]]
ANSWER: LYMPH NODES  

sub_title[[462, 257, 534, 276]]
## BONUS  

text[[115, 292, 846, 312]]
1) Biology – Short Answer Microtubules are composed of repeating units of what protein?  

text[[115, 328, 297, 346]]
ANSWER: TUBULIN  

sub_title[[455, 381, 541, 399]]
## TOSS-UP  

text[[115, 413, 857, 451]]
2) Chemistry – Short Answer Order the following three compounds by decreasing covalent character: 1) Beryllium chloride; 2) Rubidium fluoride; 3) Potassium fluoride.  

text[[115, 466, 261, 485]]
ANSWER: 1, 3, 2  

sub_title[[462, 502, 535, 520]]
## BONUS  

text[[115, 536, 837, 574]]
2) Chemistry – Short Answer Order the following molecules in terms of increasing bond angle: 1) \(\mathrm{NH_3}\) ; 2) \(\mathrm{CO_3^{2 - }}\) ; 3) \(\mathrm{SF_6}\) ; 4) \(\mathrm{H_2O}\) .  

text[[115, 589, 281, 608]]
ANSWER: 3, 4, 1, 2sub_title[[456, 84, 541, 101]]
## TOSS-UP  

text[[113, 117, 870, 153]]
3) Earth and Space – Multiple Choice Which of the following planets has an atmosphere that is primarily composed of carbon dioxide?  

text[[115, 170, 215, 241]]
W) Mercury 
X) Venus 
Y) Uranus 
Z) Neptune  

text[[115, 257, 301, 275]]
ANSWER: X) VENUS  

sub_title[[463, 293, 533, 311]]
## BONUS  

text[[115, 328, 876, 364]]
3) Earth and Space – Multiple Choice Which of the following correctly matches a layer of the atmosphere with how the temperature changes there?  

text[[115, 381, 350, 450]]
W) Troposphere; increasing 
X) Stratosphere; increasing 
Y) Mesosphere; increasing 
Z) Thermosphere; decreasing  

text[[115, 466, 515, 485]]
ANSWER: X) STRATOSPHERE; INCREASING  

sub_title[[456, 521, 540, 539]]
## TOSS-UP  

text[[115, 554, 870, 606]]
4) Physics – Multiple Choice Two rocks are thrown from a building at the same velocity, but one is shot upward while the other is thrown downward. Ignoring air resistance, which of the following best describes their velocities when they hit the ground?  

text[[115, 624, 699, 641]]
W) The rock thrown up has a smaller velocity when it reaches the ground.  

text[[115, 642, 680, 659]]
X) The rock thrown up has a larger velocity when it reaches the ground.  

text[[115, 660, 640, 677]]
Y) Both rocks have the same velocity when they reach the ground.  

text[[115, 678, 695, 695]]
Z) The masses of the rocks must be known in order to make a conclusion.  

text[[115, 711, 860, 746]]
ANSWER: Y) BOTH ROCKS HAVE THE SAME VELOCITY WHEN THEY REACH THE GROUND.  

sub_title[[463, 765, 533, 783]]
## BONUS  

text[[115, 800, 875, 852]]
4) Physics – Short Answer A ball is dropped from a height \(h\) meters. It takes \(t\) seconds for the ball to drop the first \(h\) over two meters. In terms of \(t\) and to one significant figure, how long does it take for the ball to drop the remaining \(h\) over two meters?  

text[[115, 871, 241, 888]]
ANSWER: 0.4tsub_title[[456, 83, 541, 101]]
## TOSS-UP  

text[[114, 118, 847, 154]]
5) Math – Short Answer Dylan walks 3 miles north, 4 miles east, and 1 mile south. To the nearest whole number of miles, how far is he from his original location?  

text[[115, 171, 221, 188]]
ANSWER: 4  

sub_title[[463, 207, 533, 224]]
## BONUS  

text[[115, 242, 864, 278]]
5) Math – Short Answer The number of diagonals in a regular polygon is equal to five times the number of sides. How many sides does this polygon have?  

text[[115, 294, 230, 312]]
ANSWER: 13  

sub_title[[456, 348, 540, 365]]
## TOSS-UP  

text[[115, 380, 868, 417]]
6) Energy – Multiple Choice Scientists at Fermilab are studying the effects of superoxides in mice. Which of the following is equal to the oxidation state of oxygen in its superoxide form?  

text[[115, 433, 175, 504]]
W)- 4 X)- 2 Y)- 1 Z)- 1/2  

text[[115, 521, 270, 539]]
ANSWER: Z)- 1/2  

sub_title[[463, 557, 533, 575]]
## BONUS  

text[[115, 592, 872, 628]]
6) Energy – Multiple Choice Scientists at Oak Ridge National Lab are isolating Thorium-288 and Actinium-227 as potential treatments to what general group of diseases?  

text[[115, 645, 253, 715]]
W) Meningitis X) Pneumonia Y) Cancer Z) Common cold  

text[[115, 732, 316, 750]]
ANSWER: Y) CANCERsub_title[[456, 83, 541, 101]]
## TOSS-UP  

text[[114, 115, 874, 153]]
7) Earth and Space – Short Answer Order the following winds in terms of increasing distance from the equator: 1) Trade winds; 2) Polar winds; 3) Westerlies.  

text[[115, 169, 260, 187]]
ANSWER: 1, 3, 2  

sub_title[[463, 205, 533, 223]]
## BONUS  

text[[114, 240, 876, 277]]
7) Earth and Space – Multiple Choice In which of the following atmospheric circulation cells, with latitudes between 30 and 60 degrees, are westerlies found?  

text[[114, 293, 230, 364]]
W) Polar cell 
X) Ferrel cell 
Y) Hadley cell 
Z) Phillip cell  

text[[115, 379, 363, 398]]
ANSWER: X) FERREL CELL  

sub_title[[456, 432, 541, 450]]
## TOSS-UP  

text[[112, 465, 872, 485]]
8) Chemistry – Multiple Choice Which of the following hydroxides is most soluble in water?  

text[[114, 501, 323, 573]]
W) Calcium hydroxide 
X) Copper (II) hydroxide 
Y) Ammonium hydroxide 
Z) Barium hydroxide  

text[[114, 590, 473, 608]]
ANSWER: Y) AMMONIUM HYDROXIDE  

sub_title[[463, 625, 533, 643]]
## BONUS  

text[[114, 660, 822, 697]]
8) Chemistry – Short Answer Order the following four elements by increasing electron affinity: 1) Oxygen; 2) Chlorine; 3) Sodium; 4) Phosphorus.  

text[[115, 713, 280, 731]]
ANSWER: 3, 4, 1, 2sub_title[[456, 84, 541, 101]]
## TOSS-UP  

text[[114, 116, 875, 170]]
9) Physics - Short Answer The force between two charges is 27 Newtons. The distance between the charges is tripled, and one of the charges is doubled. What is the new force between the charges?  

text[[115, 187, 321, 204]]
ANSWER: 6 NEWTONS  

sub_title[[463, 223, 533, 241]]
## BONUS  

text[[115, 258, 868, 312]]
9) Physics - Short Answer A particle moves from a potential of 34 Volts to 62 Volts. If the charge on the particle is 13 coulombs, what is the magnitude of the change in the kinetic energy of the particle in joules?  

text[[115, 328, 461, 346]]
ANSWER: 364 (DO NOT ACCEPT: - 364)  

sub_title[[456, 380, 541, 398]]
## TOSS-UP  

text[[115, 413, 859, 450]]
10) Biology - Short Answer A white cow mates with a red cow to produce a cow with both red and white spots. What is the name given to this inheritance pattern?  

text[[115, 466, 358, 484]]
ANSWER: CODOMINANCE  

sub_title[[463, 502, 533, 520]]
## BONUS  

text[[115, 537, 823, 573]]
10) Biology - Short Answer Often being grasses or lichens [LIE-kins], what species is defined as a hardy species that is the first to colonize an ecosystem?  

text[[115, 590, 375, 607]]
ANSWER: PIONEER SPECIES  

sub_title[[456, 643, 540, 660]]
## TOSS-UP  

text[[115, 675, 822, 694]]
11) Chemistry - Short Answer What is the molecular geometry of xenon tetrafluoride?  

text[[115, 711, 373, 728]]
ANSWER: SQUARE PLANAR  

sub_title[[463, 747, 533, 764]]
## BONUS  

text[[115, 781, 835, 818]]
11) Chemistry - Short Answer Rank the following three compounds by decreasing mass percentage of carbon: 1) hexane; 2) cyclopentadiene; 3) propanal.  

text[[115, 834, 260, 852]]
ANSWER: 2, 1, 3sub_title[[456, 84, 540, 101]]
## TOSS-UP  

text[[115, 118, 864, 154]]
12) Math - Short Answer A sphere has a radius of 12, and another sphere has a radius of 18. What is the ratio of the volume of the smaller sphere that of the larger sphere?  

text[[115, 170, 415, 189]]
ANSWER: 8 TO 27 (ACCEPT: 8/27)  

sub_title[[463, 207, 533, 224]]
## BONUS  

text[[115, 242, 879, 278]]
12) Math - Short Answer The area between two concentric circles is 13pi. If both circles have integer radii, find the area of the smaller circle.  

text[[115, 294, 248, 312]]
ANSWER: 36PI  

sub_title[[456, 348, 540, 365]]
## TOSS-UP  

text[[115, 381, 870, 434]]
13) Energy - Short Answer Scientists at Oak Ridge National Lab are working hard on developing new, efficient methods to create energy for nuclear fission reactors. What isotope of uranium are they looking for that is necessary in small quantities for nuclear fission reactors?  

text[[115, 451, 340, 468]]
ANSWER: URANIUM- 235  

sub_title[[463, 486, 533, 504]]
## BONUS  

text[[115, 520, 868, 625]]
13) Energy - Short Answer Scientists at Brookhaven National Lab are working toward optimizing energy storage devices by determining how certain substances respond to an applied voltage. One example of an energy storage device is a capacitor. Identify all of the following three statements that are true regarding capacitors: 1) Capacitors store electrical energy; 2) The capacitance of a capacitor only depends on its physical properties; 3) Capacitors add linearly in series.  

text[[115, 642, 283, 660]]
ANSWER: 1 AND 2sub_title[[456, 83, 541, 101]]
## TOSS-UP  

text[[115, 116, 840, 153]]
14) Physics - Short Answer What law states that the change in internal energy of a gas is equal to the sum of the heat added to the gas and the work done on the gas?  

text[[115, 168, 787, 205]]
ANSWER: FIRST LAW OF THERMODYNAMICS (DO NOT ACCEPT: LAW OF THERMODYNAMICS)  

sub_title[[463, 223, 533, 241]]
## BONUS  

text[[115, 258, 872, 294]]
14) Physics - Short Answer A gas has a constant pressure heat capacity of 22 R over 7. What is the adiabatic index of this gas?  

text[[115, 310, 256, 328]]
ANSWER: 22/15  

sub_title[[456, 362, 541, 380]]
## TOSS-UP  

text[[115, 395, 867, 432]]
15) Biology - Short Answer What is the name for the ball-shaped mixture of food and saliva formed in the mouth that is ultimately pushed down the esophagus?  

text[[115, 448, 275, 466]]
ANSWER: BOLUS  

sub_title[[463, 484, 533, 502]]
## BONUS  

text[[115, 519, 860, 555]]
15) Biology - Short Answer In the Cori cycle, lactate produced by the muscles is converted into what molecule in the liver, which is later converted back into lactate by the muscles?  

text[[115, 572, 300, 590]]
ANSWER: GLUCOSEsub_title[[456, 83, 541, 101]]
## TOSS-UP  

text[[115, 115, 870, 153]]
16) Earth and Space – Multiple Choice Where on the Hertzsprung-Russell diagram are white dwarf stars found?  

text[[115, 170, 245, 241]]
W) Top right 
X) Top left 
Y) Bottom right 
Z) Bottom left  

text[[115, 257, 368, 276]]
ANSWER: Z) BOTTOM LEFT  

sub_title[[463, 293, 533, 310]]
## BONUS  

text[[115, 325, 825, 345]]
16) Earth and Space – Multiple Choice Which of the following is a metamorphic rock?  

text[[115, 360, 308, 431]]
W) Dacite [DA-site] 
X) Schist [SHIST] 
Y) Chert [CHURT] 
Z) Coquina [CO-keena]  

text[[115, 447, 304, 465]]
ANSWER: X) SCHIST  

sub_title[[456, 501, 540, 519]]
## TOSS-UP  

text[[115, 534, 804, 572]]
17) Math – Short Answer Rushil flips a coin 10 times and gets all heads. What is the probability that he gets another 10 heads in a row?  

text[[115, 587, 266, 605]]
ANSWER: 1/1024  

sub_title[[463, 622, 533, 640]]
## BONUS  

text[[115, 657, 872, 695]]
17) Math – Short Answer Find the number of positive integers less than 168 that are divisible by 6 and 7 but not 8.  

text[[115, 711, 220, 729]]
ANSWER: 3sub_title[[456, 83, 541, 101]]
## TOSS-UP  

text[[115, 116, 866, 170]]
18) Physics - Short Answer A force of 12 Newtons acts on a 3-kilogram mass at an angle of 60 degrees from the horizontal. If the force pulls the mass a distance of 8 meters horizontally, what is the work applied on the mass?  

text[[115, 186, 305, 204]]
ANSWER: 48 JOULES  

sub_title[[463, 222, 533, 240]]
## BONUS  

text[[115, 257, 879, 329]]
18) Physics - Short Answer A rock of mass 1 kilogram is sliding on a smooth surface when it starts sliding on a rough patch of grass with a coefficient of kinetic friction of 0.4. Taking g as 10 meters per seconds squared, if the rock enters the patch of grass with a velocity of 12 meters per second, what distance does it travel before it stops?  

text[[115, 345, 313, 363]]
ANSWER: 18 METERS  

sub_title[[456, 398, 540, 416]]
## TOSS-UP  

text[[115, 431, 878, 451]]
19) Chemistry - Multiple Choice Which of the following reactions will produce a precipitate?  

text[[115, 466, 556, 538]]
W) Calcium chloride reacted with potassium chlorate 
X) Potassium bromide reacted with barium chloride 
Y) Aluminum nitrate reacted with sodium carbonate 
Z) Hydrogen fluoride reacted with potassium hydroxide  

text[[115, 553, 794, 572]]
ANSWER: Y) ALUMINUM NITRATE REACTED WITH SODIUM CARBONATE  

sub_title[[463, 589, 533, 607]]
## BONUS  

text[[115, 624, 809, 660]]
19) Chemistry - Multiple Choice Which of the following sets of quantum numbers is impossible for an electron to possess?  

text[[115, 676, 352, 749]]
W) \(\mathrm{n} = 1\) , \(\mathrm{L} = 0\) , m sub \(\mathrm{s} = - 1\) X) \(\mathrm{n} = 3\) , \(\mathrm{L} = 2\) Y) \(\mathrm{n} = 4\) , \(\mathrm{L} = 2\) , m sub \(\mathrm{L} = - 2\) Z) \(\mathrm{L} = 0\) , m sub \(\mathrm{L} = 0\)  

text[[115, 765, 463, 784]]
ANSWER: W) \(\mathrm{N} = 1\) , \(\mathrm{L} = 0\) , M SUB \(\mathrm{S} = - 1\)sub_title[[456, 83, 541, 101]]
## TOSS-UP  

text[[115, 118, 875, 172]]
20) Energy - Multiple Choice The DOE's Summit supercomputer at Oak Ridge National Lab was recently used to model protein binding interactions. Which of the following statements regarding protein binding is false?  

text[[115, 188, 761, 260]]
W) In most cases, only a specific enantiomer of a molecule can bind to a protein 
X) Some proteins have stretches of amino acids responsible for protein binding 
Y) Muscle contraction relies largely on successful protein binding 
Z) Water molecules are ignored because they do not play a role in protein binding  

text[[115, 276, 869, 312]]
ANSWER: Z) WATER MOLECULES ARE IGNORED BECAUSE THEY DO NOT PLAY A ROLE IN PROTEIN BINDING  

sub_title[[463, 328, 533, 346]]
## BONUS  

text[[115, 362, 847, 415]]
20) Energy - Short Answer Researchers at Sandia National Labs are studying enzymatic responses to enantiomers of their substrates. If a substrate molecule has 5 chiral centers, how many stereoisomers does it have?  

text[[115, 432, 231, 450]]
ANSWER: 32  

sub_title[[456, 485, 540, 503]]
## TOSS-UP  

text[[115, 519, 848, 555]]
21) Math - Short Answer Two prime numbers add to 25. What is the product of these two numbers?  

text[[115, 572, 231, 589]]
ANSWER: 46  

sub_title[[463, 607, 533, 625]]
## BONUS  

text[[115, 642, 853, 696]]
21) Math - Short Answer The midpoints of the sides of a triangle are all connected to each other so that they form a smaller, similar triangle inside the original triangle. If the area of the original triangle is 72, what is the area of the smaller triangle?  

text[[115, 713, 231, 730]]
ANSWER: 18sub_title[[456, 83, 540, 101]]
## TOSS-UP  

text[[113, 116, 830, 152]]
22) Biology - Short Answer What is the final electron acceptor in the electron transport chain?  

text[[115, 168, 422, 187]]
ANSWER: OXYGEN (ACCEPT: O2)  

sub_title[[463, 205, 533, 222]]
## BONUS  

text[[115, 240, 867, 277]]
22) Biology - Short Answer Identify all of the following three amino acids that are chiral: 1) Lysine; 2) Valine; 3) Phenylalanine.  

text[[115, 293, 340, 311]]
ANSWER: ALL OF THEM  

sub_title[[456, 346, 540, 364]]
## TOSS-UP  

text[[115, 379, 843, 415]]
23) Earth and Space - Short Answer At which type of tectonic plate boundary is the most damage from a future earthquake expected to occur?  

text[[115, 431, 446, 450]]
ANSWER: TRANSFORM BOUNDARY  

sub_title[[463, 485, 533, 503]]
## BONUS  

text[[115, 520, 874, 590]]
23) Earth and Space - Short Answer Naveen takes a visit down under to Nullarbor [Null- ARE-bore] Plain in Australia as part of a geology trip. While he is there, he notices a substantial amount of limestone, with many sinkholes and caves. What kind of topography is he likely viewing?  

text[[115, 607, 275, 625]]
ANSWER: KARST