
## TOSS-UP  


1) Math – Multiple Choice Which of the following vectors is perpendicular to the plane defined by the equation \(x\) minus \(2y\) plus \(3z\) equals \(6\) ?  


W) \(2\mathrm{j}\) minus k 
X) \(3\mathrm{i}\) minus \(2\mathrm{j}\) plus \(4\mathrm{k}\) Y) \(- 2\mathrm{i}\) plus \(4\mathrm{j}\) minus \(6\mathrm{k}\) Z) i plus \(2\mathrm{j}\) plus \(3\mathrm{k}\)  


ANSWER: Y) \(- 2\mathrm{i}\) PLUS \(4\mathrm{j}\) MINUS \(6\mathrm{k}\)  


## BONUS  


1) Math – Short Answer Given a sphere with the equation \(x\) squared plus \(y\) squared plus \(z\) squared equals 9, what is the equation for a plane tangent to this sphere at the point (1, 2, 2)?  


ANSWER: \(x + 2y + 2z = 9\)  


## TOSS-UP  


2) Chemistry – Short Answer How many hydrogen atoms are in the molecule cyclohexanone [sai-klo-HEX-uh-nown]?  


ANSWER: 10  


## BONUS  


2) Chemistry – Short Answer Identify all of the following four species that are electrophiles: 1) Enolates [EE-no-lates]; 2) H plus; 3) Water; 4) Carbenium [car-BEE-nee-um].  


ANSWER: 2 AND 4
## TOSS-UP  


3) Physics – Short Answer An ammeter [AM-eter] of a low resistance of 0.1 ohms is used to measure the current through a 10 ohm resistor. The ammeter is placed with the resistor in series, and the system is then connected to an ideal battery of 100 volts. Find the current measured by the ammeter to the nearest tenth of an ampere.  


ANSWER: 9.9  


## BONUS  


3) Physics – Multiple Choice Which of the following is NOT a possible consequence of the third law of thermodynamics?  


W) There cannot exist any ideal gas as the temperature approaches 0 Kelvin  


X) It is impossible to reach absolute zero  


Y) Heat capacities must approach zero as temperature approaches zero  


Z) It requires the sign of the entropy of an object with a temperature greater than absolute zero to be non-negative  


ANSWER: Z) IT REQUIRES THE SIGN OF THE ENTROPY OF AN OBJECT WITH A TEMPERATURE GREATER THAN ABSOLUTE ZERO BE NON- NEGATIVE  


## TOSS-UP  


4) Biology – Short Answer What molecule serves as a co-repressor in the trp [trip] operon?  


ANSWER: TRYPTOPHAN  


## BONUS  


4) Biology – Short Answer What protein produced in the ileum [IL-ee-uhm] plays a pivotal role in appetite suppression?  


ANSWER: PEPTIDE YY
## TOSS-UP  


5) Earth and Space – Multiple Choice The Roche [RAWSH] lobe is the region of a star in a binary system where material inside the star is bound to it by gravity. If material from one star in a binary system passes the Roche lobe of another star, it will flow to that star. Which phenomenon is NOT likely to result from this type of interaction?  


W) Starquakes  X) Millisecond pulsars  Y) Soft x-ray transients  Z) Cataclysmic variables  


ANSWER: W) STARQUAKES  


## BONUS  


5) Earth and Space – Short Answer Rishab points his telescope toward an interesting star he noticed in the night sky. Equipped with a spectrometer, he analyzes the spectrum produced by the star and notices strong lines corresponding to the compound titanium oxide, or \(\mathrm{TiO_2}\) . Which of the following spectral classes can the star likely be classified as?  


W) O  X) A  Y) G  Z) M  


ANSWER: Z) M  


## TOSS-UP  


6) Energy – Short Answer Researchers at Sandia National Labs are studying commercial chemical processes that may be helpful in producing compounds that extinguish chemical fires. What is the term for the process by which esters can be converted into carboxylic acids after treatment with sodium hydroxide and an acid?  


ANSWER: SAPONIFICATION  


## BONUS  


6) Energy – Short Answer Researchers at Sandia National Labs are studying the molecular makeup of plasma membranes. What is the term for groups of lipids found in membrane regions where clusters of specialized proteins performing common functions congregate?  


ANSWER: LIPID RAFTS
## TOSS-UP  


7) Math - Short Answer Line \(l\) can be parameterized as \(x\) equals \(2t\) , \(y\) equals \(3t\) plus \(2\) , and \(z\) equals \(-5t\) plus \(8\) . In simplest radical form, what is the distance between the points on the line where \(t\) equals \(3\) and where \(t\) equals \(5\) ?  


ANSWER: 2 sqrt(38)  


## BONUS  


7) Math - Short Answer Find the number of solutions in the interval open bracket 0 to 2 pi close bracket such that the secant of \(x\) plus the tangent of \(x\) is equal to 2 times the cosine of \(x\) .  


ANSWER: 2  


## TOSS-UP  


8) Chemistry - Multiple Choice What is the net change in the number of pi-bonds in a cycloaddition?  


W)-2 X)-1 Y)1 Z)2  


ANSWER: W)-2  


## BONUS  


8) Chemistry - Multiple Choice Which of the following best explains why the d z squared atomic orbital does not have the normal clover shape that the rest of the d-orbitals have?  


W) d z squared has a radial wavefunction that is partly imaginary, while the other d-orbitals have completely real radial wavefunctions  


X) d z squared has a radial wavefunction that is completely real, while the other d-orbitals have partly imaginary wavefunctions  


Y) d z squared has an angular wavefunction that is partly imaginary, while the other d-orbitals have completely real radial wavefunctions  


Z) d z squared has an angular wavefunction that is completely real, while the other d-orbitals have partly imaginary wavefunctions  


ANSWER: Z) D Z SQUARED HAS AN ANGULAR WAVEFUNCTION THAT IS COMPLETELY REAL, WHILE THE OTHER d-ORBITALS HAVE PARTLY IMAGINARY WAVEFUNCTIONS
## TOSS-UP  


9) Earth and Space – Multiple Choice Dylan is studying the types of binary star systems using the Kepler telescope. He notices two main sequence stars orbiting each other in an elliptical path. After some observation, he realizes that the less massive star is more advanced in the stellar life cycle. What type of binary star system is this?  


W) Algol-type binary 
X) Cataclysmic variables 
Y) Symbiotic binary 
Z) X-Ray binary  


ANSWER: W) ALGOL-TYPE BINARY  


## BONUS  


9) Earth and Space – Short Answer Star A has an absolute magnitude of 4, while star B has an absolute magnitude of \(-6\). If star B's radius is five times that of star A, then to the nearest tenth, by what factor is star B's temperature larger than star A's temperature?  


ANSWER: 4.5  


## TOSS-UP  


10) Physics – Short Answer By name or number, identify all of the following four particles that are pseudoscalar mesons: 1) pion; 2) omega meson; 3) phi [FEE]/ meson; 4) eta meson.  


ANSWER: 1 AND 4  


## BONUS  


10) Physics – Short Answer In the hypothetical nuclear reaction where two up quarks and a strange quark turn into a proton and an electron antineutrino [an-tie-noo-TREE-no], identify all of the following four properties that are not conserved: 1) charge; 2) mass; 3) baryon number; 4) lepton number.  


ANSWER: 1 ONLY
## TOSS-UP  


11) Biology - Short Answer Order the following three solutions in order of increasing solute potential assuming that they all are at the same temperature: 1) 2 Molar Sucrose; 2) 1 Molar Sodium Phosphate; 3) 3 Molar Glucose.  


ANSWER: 2, 3, 1  


## BONUS  


11) Biology - Short Answer Assume round is dominant to wrinkled, and tall is dominant to short. A pea plant homozygous dominant for shape and height is crossed with a short and wrinkled pea plant. The offspring are allowed to self-pollinate. An F2 offspring contains two peas in a pod. What is the probability that one pea is round and tall and the other is short and wrinkled?  


ANSWER: 9/128  


## TOSS-UP  


12) Energy - Multiple Choice In order to manipulate silicon-based nanomaterials, researchers at Brookhaven National Lab have been studying the quantum confinement of the surface and bulk variants of what collective oscillations of electrons?  


W) Excitons X) Phonons [FO-nons] Y) Polaritons [po-LAI-ri-tauns] Z) Plasmons  


ANSWER: Z) PLASMONS  


## BONUS  


12) Energy - Short Answer Researchers at Sandia National Labs are studying how to switch on Iron three ions in the octahedral sheet of an iron-containing phyllosilicate. Identify which of the following three minerals are phyllosilicates: 1) mica; 2) chlorite; 3) biotite  


ANSWER: ALL
## TOSS-UP  


13) Earth and Space – Multiple Choice The Mississippi River’s discharge into the ocean is larger than the ocean’s input into the river. Which of the following features does the Mississippi River have as a result of this?  


W) Strong tidal currents 
X) Lack of vertical salinity gradient 
Y) Salt wedge 
Z) Thorough mixing of water horizontally  


ANSWER: Y) SALT WEDGE  


## VISUAL BONUS  


13) Earth and Space – Short Answer Answer the following three questions about this image: 
1) What process is shown in this image?; 
2) States such as Wisconsin, Michigan, and New York are greatly impacted by this process. Choosing from north, east, south, or west, what direction relative to a body of water receives the heaviest snowfall from this process in this region?; 
3) By name or number, identify all of the following that would be conducive to this process: 
1) atmospheric instability, 
2) directional shear, 
3) significantly colder air aloft  


ANSWER: 1) LAKE-EFFECT SNOW 2) EAST 3) 1 AND 3 ONLY  


## TOSS-UP  


14) Biology – Short Answer Bempedio [bem-pe-DOY-ic] acid is a non-statin compound that is used to inhibit the synthesis of LDL cholesterol by blocking ATP citrate lyase [LIE-ase], an enzyme that converts citrate to acetyl-CoA so that it can be used in the mevalonate pathway. However, statins act farther downstream in the pathway, blocking the conversion of what molecule into mevalonate?  


ANSWER: HMG- CoA  


## BONUS  


14) Biology – Multiple Choice Which of the following statements regarding hemoglobin oxygen dissociation curves is incorrect?  


W) High CO2 concentrations lead to a left-shifted curve 
X) High 2,3-BPG concentrations lead to a right-shifted curve 
Y) Use of Fetal Hemoglobin leads to a right-shifted curve 
Z) High temperature leads to a right-shifted curve  


ANSWER: Y) USE OF FETAL HEMOGLOBIN LEADS TO A RIGHT-SHIFTED CURVE
## TOSS-UP  


15) Chemistry - Short Answer Which statement in organic chemistry predicts that, in endergonic reactions, the geometry of the transition state will closely resemble the geometry of the product?  


ANSWER: HAMMOND'S POSTULATE  


## BONUS  


15) Chemistry - Multiple Choice Which of the following statements regarding the acid-catalyzed ring-opening of epoxides is false?  


W) Nucleophiles will preferentially attack a secondary carbon over a primary carbon 
X) When water is the nucleophile, sulfuric acid is a commonly used catalyst 
Y) The mechanism proceeds first through proton transfer and then via a nucleophilic substitution 
Z) There is stereochemical inversion about chiral centers  


ANSWER: W) NUCLEOPHILES WILL PREFERENTIALLY ATTACK A SECONDARY CARBON OVER A PRIMARY CARBON  


## TOSS-UP  


16) Math - Short Answer Akul wants to evaluate the Gaussian integral by switching from rectangular to polar coordinates. By what mathematical object should he multiply his integral in order to properly scale to the new coordinate system?  


W) Hessian [HESS- ee- in] matrix 
X) Jacobian [juh- KO- bee- in] determinant 
Y) Ricci [REE- chi] tensor 
Z) Scaling vector  


ANSWER: X) JACOBIAN DETERMINANT  


## BONUS  


16) Math - Short Answer Let \(\mathbf{F}\) be a 3-D vector field such that \(\mathbf{F}(x,y,z) = (y + z)\mathbf{i} + (x - z)\mathbf{j}+\) \((y - x)\mathbf{k}\) [F of x, y, z equals open parenthesis, y plus z, closed parenthesis times i, plus open parenthesis, x minus z, closed parenthesis times j, plus open parenthesis, y minus x, closed parenthesis times k]. Find the curl of \(\mathbf{F}\)  


ANSWER: \(2\mathbf{i} + 2\mathbf{j} + 0\mathbf{k}\)
## TOSS-UP  


17) Physics – Multiple Choice Water fills a cylindrical can to its top. The can is then rotated at some angular velocity about its center axis. If water is allowed to spill from the top of the can, which of the following best describes the shape of the surface of the water after a long time?  


W) Hyperboloid 
X) Ellipsoid 
Y) Paraboloid 
Z) Sphere  


ANSWER: Y) PARABOLOID  


## BONUS  


17) Physics – Short Answer A car travels around a curve with a radius of 98 meters. The car contains a container with some fluid in it. When it moves around the curve, the surface of the fluid makes a 45 degree angle with the horizontal. If g is 9.8 meters per seconds squared, at what speed, to the nearest integer, is the car travelling around the curve?  


ANSWER: 31 METERS PER SECOND  


## TOSS-UP  


18) Energy – Short Answer Scientists at Brookhaven National La’s Center for Functional Nanomaterials need precise equipment in order to study the binding of SARS-CoV-2 /sars-co-v- two/ to cells and find a way to inhibit it. In order to accomplish this, they are using what microscopic technique that uses a usually pyramidal-shaped tip attached to a cantilever /KAN- tuh-lee-ver/ that can very finely scan surfaces?  


ANSWER: ATOMIC FORCE MICROSCOPY (ACCEPT: SCANNING FORCE MICROSCOPY)  


## BONUS  


18) Energy – Short Answer Researchers at Lawrence Berkeley National Lab have been studying the binding ability of antibody-mimetic /mi-MET-ic/ peptoid nanosheets. For example, they created a gold-peptoid-gold composite that can serve as a miniature version of what electronic device utilized for its rapid charging and discharging ability?  


ANSWER: SUPERCAPACITOR
## TOSS-UP  


19) Earth and Space - Short Answer Jupiter's magnetic field is partially due to its liquid metallic hydrogen core. However, its moon, Io [I-0], more than doubles Jupiter's magnetic field strength by emitting large amounts of sulfur dioxide, which gets swept up in Jupiter's magnetic sphere to form what object that surrounds the planet?  


ANSWER: IO PLASMA TORUS (ACCEPT: IO TORUS OR PLASMA TORUS OR TORUS)  


## BONUS  


19) Earth and Space - Multiple Choice Jupiter has multiple gossamer [GAH-suh-mur] rings composed largely of dust from impacts on the moons Amalthea and Thebe. Originally, these dust particles had the same orbit as their moons. What process is responsible for their orbital decay?  


W) Extremely small gravitational waves 
X) Collision with other dust particles in the ring 
Y) Interactions with Jupiter's magnetic field 
Z) Drag from solar radiation  


ANSWER: Z) DRAG FROM SOLAR RADIATION  


## TOSS-UP  


20) Physics - Short Answer What shape is formed when light passes through an object where each infinitesimally thin layer of the object has an index of refraction that varies with the sine of the angle that light approaches it divided by the speed of the light at the instant?  


ANSWER: BRACHISTOCHRONE (DO NOT ACCEPT: CYCLOID)  


## BONUS  


20) Physics - Short Answer A diffraction grating with 50 slits has a distance of 12 centimeters between each slit. If light of wavelength 732 nanometers passes through the gratings, what is the angle between the central maximum and first maximum of the diffraction pattern in radians and scientific notation?  


ANSWER: 12.2 TIMES 10 TO THE NEGATIVE 8
## TOSS-UP  


21) Math - Short Answer Let a and b be three-dimensional vectors, where \((3\mathbf{a} + 2\mathbf{b})\mathbf{x}(-4\mathbf{a} - 7\mathbf{b}) = \mathbf{k}\mathbf{a}\mathbf{x}\mathbf{b}\) [the quantity three a + two b cross the quantity negative four a minus seven b equals k times a cross b], where k is a scalar. What is the value of k?  


ANSWER: - 13  


## BONUS  


21) Math - Short Answer Let A be a matrix such that A times the matrix with first row 2, second row 5, and third row 3 equal a matrix with first row -9, second row -2, and third row 4, and A times the matrix with first row -1, second row 5, and third row 2 equal a matrix with first row -10, second row 4, and third row 1. What is the sum of the entries in the matrix that is the result of A multiplied by the matrix with first row -3, second row 0, and third row -1?  


ANSWER: 2  


## TOSS-UP  


22) Biology - Short Answer In bacteria, as well as in mitochondria and chloroplasts, the compound that initiates protein synthesis, rather than methionine [meth- EYE- o- neen], is methionine attached to what group?  


ANSWER: FORMYL  


## BONUS  


22) Biology - Short Answer Identify all of the following that would increase an enzyme's activation energy: 1) Making the active site complementary to the substrate instead of the transition state: 2) Increasing temperature from 40 degrees Celsius to 70 degrees Celsius: 3) Decreasing catalyst concentration  


ANSWER: 1 AND 3
## TOSS-UP  


23) Chemistry – Short Answer What is the term for molecules that lack chiral centers but are optically active due to steric hindrance around a rotationally fixed bond?  


ANSWER: ATROPISOMERS  


## BONUS  


23) Chemistry – Short Answer Arrange the following three elements by increasing ionization energy: 1) Gallium [GA-lee-um]; 2) Indium; 3) Thallium [THA-lee-um].  


ANSWER: 2, 1, 3