sub_title[[450, 137, 536, 155]]
## TOSS-UP  

text[[115, 170, 864, 208]]
1) Physics – Short Answer How many ways are there to position 5 equal positive charges so that they are in a stable configuration?  

text[[115, 222, 222, 240]]
ANSWER: 0  

sub_title[[459, 258, 530, 277]]
## BONUS  

text[[115, 293, 857, 366]]
1) Physics – Short Answer Viraj is walking up a downward-moving escalator at a speed of 10 meters per second relative to the lab frame. However, the escalator is moving down at 4 meters per second. If Viraj weighs 60 kilograms, how much power does Viraj use to climb for 10 seconds, given that \(g\) equals 10 meters per second squared?  

text[[115, 380, 323, 400]]
ANSWER: 8400 WATTS  

sub_title[[450, 434, 536, 452]]
## TOSS-UP  

text[[115, 468, 872, 523]]
2) Math – Multiple Choice \(f\) of \(x\) is a function that is continuous and differentiable over the reals, \(f\) of 0 equals 7, and \(f\) of 5 equals \(-3\) . \(f\) prime of \(x\) must have what value at at least one point on the interval between \(x\) equals 0 and \(x\) equals 5?  

text[[115, 538, 168, 610]]
W)- 4 X)- 2 Y)0 Z)2  

text[[115, 626, 256, 645]]
ANSWER: X)- 2  

sub_title[[459, 662, 530, 681]]
## BONUS  

text[[115, 697, 816, 734]]
2) Math – Short Answer Let \(P\) of \(x\) equal \(x\) squared minus \(90 x\) plus two thousand and twenty-one. What is the greatest common denominator of \(P\) of 50 and \(P\) of 54?  

text[[115, 750, 220, 768]]
ANSWER: 7sub_title[[452, 83, 536, 101]]
## TOSS-UP  

text[[114, 118, 860, 155]]
3) Biology – Multiple Choice What type of speciation occurs within the original population and niche [NEESH] without relying on geographical isolation?  

text[[114, 172, 361, 244]]
W) Sympatric 
X) Peripatric [pair-EE-patric] 
Y) Allopatric 
Z) Parapatric [pair-UH-patric]  

text[[115, 260, 355, 278]]
ANSWER: W) SYMPATRIC  

sub_title[[459, 295, 530, 313]]
## BONUS  

text[[114, 330, 866, 419]]
3) Biology – Short Answer Order the following four steps in the signal amplification of epinephrine [EP-uh-nef-rin] to trigger glycogen breakdown: 1) cyclic AMP [A-M-P] activates protein kinase A; 2) G proteins convert adenylyl [uh-den-uh-LEEL] cyclase into its active form; 3) Epinephrine binds to a cell-membrane receptor; 4) Phosphorylase [fos-for-il-ASE] kinase [KAI-nayse] is activated.  

text[[115, 435, 280, 453]]
ANSWER: 3, 2, 1, 4  

sub_title[[452, 490, 536, 507]]
## TOSS-UP  

text[[113, 522, 870, 559]]
4) Earth and Space – Short Answer Wolframite [WOLF-ruh-mite], scheelite [SHE-lite], and [fer-buh-RIGHT] ferberite are ore minerals of what element?  

text[[115, 575, 314, 593]]
ANSWER: TUNGSTEN  

sub_title[[459, 610, 530, 628]]
## BONUS  

text[[115, 645, 857, 715]]
4) Earth and Space – Short Answer Justin is doing field work for his college geology class. He notices a peculiar green rock and notes that it is coarse-grained and is largely composed of olivine [AW-live-een] and pyroxene [pie-ROCKS-een]. What rock that is common in the Earth’s mantle has he just stumbled upon?  

text[[115, 732, 324, 750]]
ANSWER: PERIDOTITEsub_title[[452, 83, 536, 101]]
## TOSS-UP  

text[[114, 118, 872, 173]]
5) Chemistry – Multiple Choice A molecule of butane is in the gauche [GOWSH] conformation. Which of the following could be the dihedral angle in degrees between its methyl groups?  

text[[114, 190, 175, 260]]
W) 0 
X) 60 
Y) 120 
Z) 180  

text[[115, 279, 256, 297]]
ANSWER: X) 60  

sub_title[[459, 314, 529, 331]]
## BONUS  

text[[115, 349, 829, 402]]
5) Chemistry – Multiple Choice Given that the solubility constant for a binary ionic compound \(\mathrm{AX}_2\) is 1.08 times 10 to the \(-22\) , what is the solubility, in moles per liter, of this compound?  

text[[115, 418, 330, 490]]
W) 6.23 times 10 to the \(-3\) X) 3 times 10 to the \(-8\) Y) 9 times 10 to the \(-8\) Z) 1.08 times 10 to the \(-11\)  

text[[115, 506, 433, 523]]
ANSWER: X) 3 TIMES 10 TO THE \(-8\)  

sub_title[[452, 560, 536, 576]]
## TOSS-UP  

text[[115, 594, 864, 666]]
6) Energy – Short Answer Using the Spallation [sph-LAY-shun] Neutron Source and High Flux Isotope Reactor, researchers at Oak Ridge Laboratory discovered that particles called phasons [FAZE-ons] induce the rearrangement of atoms, leading to the ability of heat to travel faster than what speed that was previously assumed to be a limiting factor in heat conduction?  

text[[115, 682, 373, 699]]
ANSWER: SPEED OF SOUND  

sub_title[[459, 717, 529, 734]]
## BONUS  

text[[115, 752, 865, 822]]
6) Energy – Short Answer Scientists at Pacific Northwest National Laboratories are working on commercializing carbon capture and storage technologies. One method they are working on is sequestering carbon dioxide in rock formations. What commonly occurring rock did the carbon dioxide form after reacting with the basalt?  

text[[115, 840, 321, 857]]
ANSWER: LIMESTONEsub_title[[452, 84, 536, 101]]
## TOSS-UP  

text[[115, 108, 800, 144]]
7) Math – Short Answer What is the area under the curve of the normal distribution, commonly used in statistics?  

text[[115, 160, 220, 178]]
ANSWER: 1  

sub_title[[459, 196, 530, 214]]
## BONUS  

text[[115, 230, 838, 284]]
7) Math – Short Answer What is the percentile, to the nearest integer, of a person whose height is 5 feet and 11 inches, given that the distribution of heights is approximately normal with a mean of 5 feet and 6 inches and a standard deviation of 2.5 inches?  

text[[115, 300, 230, 318]]
ANSWER: 98  

sub_title[[452, 353, 536, 370]]
## TOSS-UP  

text[[115, 386, 872, 422]]
8) Earth and Space – Short Answer What is the term for a mass of igneous rock that has been intruded between rock strata, causing uplift in the shape of a dome?  

text[[115, 438, 322, 456]]
ANSWER: LACCOLITH  

sub_title[[459, 474, 530, 492]]
## BONUS  

text[[115, 508, 802, 545]]
8) Earth and Space – Multiple Choice Which of the following driving forces is most responsible for seafloor spreading?  

text[[115, 561, 546, 634]]
W) Magma pressure at the center of a mid-ocean ridge  
X) Slab pull at subduction zones  
Y) Geomagnetic reversal  
Z) Ridge push at rifts  

text[[115, 650, 572, 669]]
ANSWER: X) SLAB PULL AT SUBDUCTION ZONESsub_title[[452, 83, 536, 101]]
## TOSS-UP  

text[[115, 117, 850, 170]]
9) Chemistry – Multiple Choice For the reaction with rate law rate equals \(k\) times the concentration of A, which of the following quantities would form a straight line when plotted against time?  

text[[115, 189, 516, 259]]
W) The concentration of A 
X) One over the concentration of A 
Y) The natural logarithm of the concentration of A 
Z) The concentration of A squared  

text[[115, 276, 788, 295]]
ANSWER: Y) THE NATURAL LOGARITHM OF THE CONCENTRATION OF A  

sub_title[[459, 311, 530, 329]]
## BONUS  

text[[115, 346, 850, 400]]
9) Chemistry – Short Answer Calculate the half-life of a zero-order reaction with single reactant X if the initial concentration of X is 1 molar and if the final concentration of X is 0.2 molar after 8 seconds have elapsed.  

text[[115, 416, 315, 434]]
ANSWER: 5 SECONDS  

sub_title[[452, 470, 536, 488]]
## TOSS-UP  

text[[115, 503, 866, 539]]
10) Physics – Short Answer To the nearest integer and in meters per second, at what upward velocity should a ball be thrown in order to reach an elevation of 20 meters?  

text[[115, 556, 230, 573]]
ANSWER: 20  

sub_title[[459, 591, 530, 609]]
## BONUS  

text[[115, 626, 835, 679]]
10) Physics – Short Answer Observations show that when a neutron decays, protons and electrons produced don’t move in perfectly opposite directions. This observation notes the existence of what particle?  

text[[115, 697, 311, 714]]
ANSWER: NEUTRINOsub_title[[452, 83, 536, 101]]
## TOSS-UP  

text[[115, 117, 808, 153]]
11) Biology – Short Answer How many copies of the DNA template strand would be produced after seven cycles of PCR?  

text[[115, 169, 241, 187]]
ANSWER: 128  

sub_title[[459, 205, 530, 223]]
## BONUS  

text[[115, 240, 765, 260]]
11) Biology – Short Answer What gland is responsible for producing prolactin?  

text[[115, 275, 772, 295]]
ANSWER: PITUITARY GLAND (ACCEPT: ANTERIOR PITUITARY GLAND)  

sub_title[[452, 328, 536, 346]]
## TOSS-UP  

text[[115, 362, 840, 415]]
12) Energy – Short Answer Superconductors are generally classified as materials that can conduct electricity or transport electrons from one atom to another with no resistance. What type of superconductor is usually an alloy and has a more complex diamagnetism?  

text[[115, 431, 270, 450]]
ANSWER: Type II  

sub_title[[459, 467, 530, 485]]
## BONUS  

text[[115, 500, 870, 589]]
12) Energy – Short Answer At Fermilab, researchers are using new kinds of superconductors to explain the behaviors of types of magnetic fields at low temperatures. One type of superconductor they are using is the Type I superconductor. Identify all of the following four superconductors that are Type I superconductors: 1) Aluminum; 2) YBCO; 3) Zinc; 4) Cuprate perovskite [puh-ROV-skitel].  

text[[115, 605, 282, 622]]
ANSWER: 1 AND 3sub_title[[452, 83, 537, 101]]
## TOSS-UP  

text[[115, 116, 866, 154]]
13) Physics – Short Answer By name or number, identify all of the following four quantities that are state functions: 1) Internal energy; 2) Density; 3) Work; 4) Entropy.  

text[[115, 169, 308, 187]]
ANSWER: 1, 2, AND 4  

sub_title[[459, 205, 530, 223]]
## BONUS  

text[[115, 240, 865, 277]]
13) Physics – Multiple Choice Which of the following processes requires the most heat to be passed into the system given that they all have the same change in internal energy?  

text[[115, 293, 422, 366]]
W) Adiabatic cooling  X) Isochoric [iso- KORE- ic] expansion  Y) Adiabatic expansion  Z) Isobaric expansion  

text[[115, 381, 442, 400]]
ANSWER: Z) ISOBARIC EXPANSION  

sub_title[[452, 435, 537, 453]]
## TOSS-UP  

text[[115, 469, 857, 506]]
14) Chemistry – Multiple Choice Which of the following is commonly used as a solvent in SN2 reactions?  

text[[115, 523, 334, 595]]
W) Methyl alcohol  X) Toluene [tall- YOO- een]  Y) Dimethyl sulfoxide  Z) Liquid ammonia  

text[[115, 610, 454, 629]]
ANSWER: Y) DIMETHYL SULFOXIDE  

sub_title[[459, 646, 530, 664]]
## BONUS  

text[[115, 681, 850, 718]]
14) Chemistry – Short Answer Order the following three molecules by decreasing melting point: 1) Pentane; 2) Propionic [pro- PIE- onic] Acid; 3) Butanal.  

text[[115, 734, 259, 752]]
ANSWER: 3, 2, 1sub_title[[451, 83, 536, 101]]
## TOSS-UP  

text[[115, 116, 797, 152]]
15) Earth and Space – Multiple Choice The belt of prevailing global winds over the midlatitudes is known as the  

text[[115, 170, 231, 240]]
W) Westerlies 
X) Doldrums 
Y) Jet stream 
Z) Easterlies  

text[[115, 257, 361, 275]]
ANSWER: W) WESTERLIES  

sub_title[[459, 293, 530, 311]]
## BONUS  

text[[115, 327, 860, 381]]
15) Earth and Space – Multiple Choice Which of the following best describes why two earthquakes might get the same score on the Richter [RICK-tuhr] scale but different scores on the Mercalli [mer-CA-lee] intensity scale?  

text[[115, 397, 860, 431]]
W) One earthquake occurred in an area built on solid bedrock, and the other occurred on loose sediments.  

text[[115, 432, 860, 467]]
X) One earthquake occurred in an area more prone to earthquakes, and the other occurred in an area less prone to earthquakes.  

text[[115, 468, 844, 483]]
Y) One earthquake occurred closer to the equator, and the other occurred closer to the poles.  

text[[115, 485, 816, 519]]
Z) One earthquake occurred in a subduction zone, and the other occurred in a transform boundary.  

text[[115, 535, 808, 571]]
ANSWER: W) ONE EARTHQUAKE OCCURRED IN AN AREA BUILT ON SOLID BEDROCK, AND THE OTHER OCCURRED ON LOOSE SEDIMENTS.  

sub_title[[451, 608, 536, 625]]
## TOSS-UP  

text[[115, 642, 846, 695]]
16) Math – Short Answer Two chords of a circle intersect at a point inside the circle such that the first chord is split into segments of lengths 6 and 3, and the second chord is split into segments of lengths 4 and \(x\) . What is the value of \(x\) ?  

text[[115, 712, 235, 729]]
ANSWER: 4.5  

sub_title[[459, 747, 530, 765]]
## BONUS  

text[[115, 782, 872, 818]]
16) Math – Short Answer Compute the sum from \(i\) equals 1 to 7 of the sum from \(j\) equals 1 to 7 of \(i\) times \(j\) .  

text[[115, 854, 240, 871]]
ANSWER: 784sub_title[[452, 83, 536, 101]]
## TOSS-UP  

text[[115, 118, 872, 155]]
17) Biology – Multiple Choice Which of the following reactions is not catalyzed in the Golgi apparatus?  

text[[115, 171, 277, 243]]
W) Phosphorylation 
X) Glycosylation 
Y) Sulfation 
Z) Hydroxylation  

text[[115, 259, 405, 277]]
ANSWER: Z) HYDROXYLATION  

sub_title[[460, 294, 530, 311]]
## BONUS  

text[[115, 328, 839, 382]]
17) Biology – Short Answer What name is given to the stimulus response governing the action of plants that wrap around objects they come in contact with, such as vines wrapping around a building?  

text[[115, 398, 375, 416]]
ANSWER: THIGMOTROPISM  

sub_title[[452, 452, 536, 469]]
## TOSS-UP  

text[[115, 485, 844, 556]]
18) Energy – Short Answer Scientists at SLAC National Accelerator Lab are studying the various causes of catalyst poisoning. One way this happens is when a molecule is so tightly bound to the surface of a catalyst that it inhibits the catalyst's ability to speed up a reaction. What is this phenomenon, where a species gets adhered to a surface?  

text[[115, 573, 335, 590]]
ANSWER: ADSORPTION  

sub_title[[460, 608, 530, 625]]
## BONUS  

text[[115, 643, 848, 730]]
18) Energy – Short Answer Scientists at Sandia National Labs are working toward getting certain solar cells to commercialization. These solar cells have a crystal structure similar to bridgmanite [BRIJ-muh-night] and ipoartite [I-O-par-tight], which both follow the general chemical formula ABX3. What class of materials is named after the mineral calcium titanium oxide?  

text[[115, 748, 330, 765]]
ANSWER: PEROVSKITEsub_title[[452, 83, 537, 101]]
## TOSS-UP  

text[[115, 118, 833, 155]]
19) Math – Multiple Choice A right triangle has legs of lengths 12 and 16. Which of the following is the circumradius of this triangle?  

text[[115, 171, 163, 241]]
W) 6 
X) 8 
Y) 10 
Z) 12  

text[[115, 259, 257, 277]]
ANSWER: Y) 10  

sub_title[[459, 294, 530, 312]]
## BONUS  

text[[115, 329, 864, 366]]
19) Math – Short Answer How many positive integers less than or equal to 200 are divisible by exactly two of 3, 5, and 7?  

text[[115, 381, 231, 400]]
ANSWER: 26  

sub_title[[452, 435, 537, 453]]
## TOSS-UP  

text[[115, 469, 860, 506]]
20) Chemistry – Multiple Choice Which of the following compounds will dissolve better in \(n\) -heptane than in sulfuric acid?  

text[[115, 522, 301, 594]]
W) Sulfur hexafluoride 
X) Hydrogen Sulfide 
Y) Nitrogen Dioxide 
Z) Phosphoryl chloride  

text[[115, 610, 472, 629]]
ANSWER: W) SULFUR HEXAFLUORIDE  

sub_title[[459, 646, 530, 664]]
## BONUS  

text[[115, 681, 847, 718]]
20) Chemistry – Short Answer Order the following four conformations of cyclohexane by increasing stability: 1) Half-chair; 2) Boat; 3) Chair; 4) Twist-boat.  

text[[115, 733, 280, 752]]
ANSWER: 1, 2, 4, 3sub_title[[452, 83, 536, 100]]
## TOSS-UP  

text[[114, 117, 873, 170]]
21) Earth and Space – Multiple Choice Which of the following types of supernovae [soo- pur-NO-vee] occurs when a white dwarf in a binary system exceeds the Chandrasekhar [chuhn- druh-SAY-kuhr] limit, causing a runaway fusion event?  

text[[115, 188, 210, 257]]
W) Type Ia 
X) Type Ib 
Y) Type Ic 
Z) Type II  

text[[116, 274, 315, 292]]
ANSWER: W) TYPE IA  

sub_title[[459, 310, 530, 327]]
## BONUS  

text[[115, 344, 860, 414]]
21) Earth and Space – Short Answer Identify all of the following three statements that are FALSE about supernovae: 1) Type Ia supernovae are more luminous than Type II supernovae; 2) Type I supernovae have spectra containing hydrogen lines; 3) Type Ia supernovae form neutron stars or black holes.  

text[[116, 431, 283, 448]]
ANSWER: 2 AND 3  

sub_title[[452, 485, 536, 502]]
## TOSS-UP  

text[[115, 519, 860, 555]]
22) Biology – Multiple Choice Which of the following plant hormones is incorrectly paired with its function?  

text[[115, 572, 595, 643]]
W) Gibberellin; stem elongation 
X) Auxin; apical dominance 
Y) Abscisic acid; promote leaf senescence [suh-NESS-ince] 
Z) Cytokinins [sai-toh-KAI-nins] ; fruit growth  

text[[115, 660, 520, 678]]
ANSWER: Z) CYTOKININS - FRUIT GROWTH  

sub_title[[459, 696, 530, 713]]
## BONUS  

text[[115, 731, 812, 783]]
22) Biology – Short Answer As opposed to gradualism, what evolutionary hypothesis proposes that development in history is marked by isolated episodes of rapid speciation followed by long periods of little change?  

text[[115, 800, 475, 817]]
ANSWER: PUNCTUATED EQUILIBRIUMsub_title[[453, 83, 536, 100]]
## TOSS-UP  

text[[115, 117, 840, 152]]
23) Physics – Short Answer What principle states that a change in pressure will permeate throughout a liquid and onto the walls of the container of the liquid?  

text[[115, 169, 407, 186]]
ANSWER: PASCAL'S PRINCIPLE  

sub_title[[460, 205, 530, 223]]
## BONUS  

text[[115, 240, 872, 328]]
23) Physics – Short Answer Water is flowing up a pipe with velocity 5 meters per second. At a height of 2.5 meters, the pipe narrows to half its original diameter. If the pressure of the water at the ground is 250 kilopascals, find the pressure of the water 4 meters above the ground in kilopascals to the nearest integer, given that the density of water is 1000 kilograms per meter cubed.  

text[[115, 346, 230, 363]]
ANSWER: 23