sub_title[[455, 137, 541, 155]]
## TOSS-UP  

text[[115, 170, 857, 207]]
1) Math – Multiple Choice Which of the following is the shortest altitude of a right triangle with legs of length 9 and 12?  

text[[115, 223, 183, 293]]
W) 36/5 
X) 40/5 
Y) 44/5 
Z) 48/5  

text[[115, 310, 276, 328]]
ANSWER: W) 36/5  

sub_title[[463, 345, 533, 363]]
## BONUS  

text[[115, 379, 870, 451]]
1) Math – Short Answer Together, Rushil and Viraj can write a packet in 6 hours, Rushil and Rishab can write a packet in 4 hours, and Rishab and Viraj can write a packet in 6 hours. If \(x\) is the time it takes Viraj to write a packet and if \(y\) is the time it takes all 3 of them to write one, what is \(x\) divided by \(y\) ?  

text[[115, 467, 221, 485]]
ANSWER: 7  

sub_title[[455, 503, 541, 521]]
## TOSS-UP  

text[[115, 536, 877, 573]]
2) Biology – Short Answer Which two cations are primarily responsible for axon potentials in conducting neurons due to their differing concentrations inside and outside the cell?  

text[[115, 588, 672, 607]]
ANSWER: \(\mathrm{NA + }\) AND \(\mathrm{K + }\) (ACCEPT: SODIUM AND POTASSIUM)  

sub_title[[463, 624, 533, 641]]
## BONUS  

text[[115, 658, 850, 713]]
2) Biology – Short Answer In a population of 1440 animals, 250 are homozygous [ho- mo- ZAI-gis] dominant for a particular trait. How many animals are heterozygous [he-te-ro-ZAI- gis] for this trait?  

text[[115, 729, 241, 747]]
ANSWER: 700sub_title[[455, 100, 540, 118]]
## TOSS-UP  

text[[113, 136, 876, 173]]
3) Chemistry – Short Answer Rank the following 3 elements by increasing standard reduction potential: 1) lithium; 2) beryllium [bur-ILL-ee-uhm]; 3) sodium.  

text[[115, 189, 260, 207]]
ANSWER: 1, 3, 2  

sub_title[[463, 223, 533, 241]]
## BONUS  

text[[115, 258, 830, 294]]
3) Chemistry – Multiple Choice The inert pair effect would be strongest in which of the following elements?  

text[[115, 311, 202, 380]]
W) Lead 
X) Indium 
Y) Barium 
Z) Tin  

text[[115, 397, 293, 415]]
ANSWER: W) LEAD  

sub_title[[455, 450, 540, 467]]
## TOSS-UP  

text[[115, 484, 868, 536]]
4) Physics – Short Answer A ball of mass 12 kilograms is traveling at 5 meters per second to the east. If it collides perfectly inelastically with another ball of mass 4 kilograms that is at rest, find the velocity of both balls after the collision in meters per second.  

text[[115, 553, 384, 571]]
ANSWER: 3.75 (ACCEPT: 15/4)  

sub_title[[463, 589, 533, 606]]
## BONUS  

text[[115, 624, 869, 694]]
4) Physics – Short Answer There are 14 balls, each with a mass of 4 kilograms, all in a straight line. The first ball in the line is given an initial velocity of 12 meters per second toward the second ball. If all collisions are elastic, find the total kinetic energy, in joules, of all the balls after all collisions have occurred.  

text[[115, 712, 240, 729]]
ANSWER: 288sub_title[[456, 84, 541, 101]]
## TOSS-UP  

text[[114, 117, 872, 171]]
5) Earth and Space – Multiple Choice  Bode's Law approximates the spacing of planets in the Solar System. According to the hypothesis, planets beyond Saturn are approximately how many times as far from the Sun as the preceding planet?  

text[[114, 188, 157, 257]]
W) 2  X) 3  Y) 4  Z) 5  

text[[115, 275, 251, 292]]
ANSWER: W) 2  

sub_title[[463, 310, 533, 328]]
## BONUS  

text[[114, 344, 883, 398]]
5) Earth and Space – Short Answer  In 2006, astronomers assigned Pluto the status of “dwarf planet” due to discoveries of more celestial objects like it. One of the discoveries was what dwarf planet, the most massive dwarf planet in the solar system with one large known moon?  

text[[115, 414, 253, 431]]
ANSWER: ERIS  

sub_title[[456, 469, 540, 486]]
## TOSS-UP  

text[[114, 502, 880, 538]]
6) Math – Short Answer  What is the surface area of a rectangular prism with side lengths of 4, 5, and 6?  

text[[115, 555, 240, 572]]
ANSWER: 148  

sub_title[[463, 590, 533, 607]]
## BONUS  

text[[114, 624, 880, 660]]
6) Math – Short Answer  What is the area enclosed by a polar curve with equation \(r\) equals the square root of open parenthesis 5 times the sine of theta close parenthesis?  

text[[115, 676, 221, 694]]
ANSWER: 5sub_title[[456, 83, 540, 101]]
## TOSS-UP  

text[[115, 117, 840, 170]]
7) Energy - Short Answer Scientists at Lawrence Berkeley National Lab are looking into what group of porous compounds, possessing metal ions coordinated to organic ligands, as potential sponges for atmospheric carbon dioxide?  

text[[115, 187, 670, 205]]
ANSWER: METAL ORGANIC FRAMEWORKS (ACCEPT: MOFs)  

sub_title[[463, 222, 533, 240]]
## BONUS  

text[[115, 256, 876, 326]]
7) Energy - Short Answer Scientists at Brookhaven National Lab are working toward optimizing energy storage devices by determining how certain substances respond to an applied voltage. What are these substances that are known to be powerful solvents for organic molecules with very low vapor pressures?  

text[[115, 343, 349, 361]]
ANSWER: IONIC LIQUIDS  

sub_title[[456, 397, 540, 414]]
## TOSS-UP  

text[[115, 430, 877, 483]]
8) Physics - Short Answer After having finished a project at Viraj's house, Rushil decides to go back home on his new spaceship that travels at 0.7 times the speed of light. When Rushil flies the spaceship back home, what percent of its original size will Viraj see to the nearest ten?  

text[[115, 499, 230, 517]]
ANSWER: 70  

sub_title[[463, 534, 533, 552]]
## BONUS  

text[[115, 570, 875, 623]]
8) Physics - Short Answer A superconducting loop is placed inside a solenoid with 120 loops and a current of 2.5 amperes. The radius of the superconducting loop of 15 millimeters is significantly less than that of the solenoid. Find the magnetic flux through the loop.  

text[[115, 640, 221, 657]]
ANSWER: 0sub_title[[456, 84, 541, 101]]
## TOSS-UP  

text[[113, 117, 835, 153]]
9) Chemistry – Multiple Choice What is the correct expression for the solubility product constant of silver chromate?  

text[[114, 170, 515, 241]]
W) Ag plus squared times Cr O 4 2 minus squared 
X) Ag plus times Cr O 4 2 minus 
Y) Ag plus times Cr O 4 2 minus squared 
Z) Ag plus squared times Cr O 4 2 minus  

text[[114, 256, 625, 275]]
ANSWER: Z) AG PLUS SQUARED TIMES CR O 4 2 MINUS  

sub_title[[463, 292, 534, 310]]
## BONUS  

text[[113, 327, 770, 347]]
9) Chemistry – Multiple Choice Which of the following salts is the most acidic?  

text[[114, 363, 300, 433]]
W) Ammonium sulfate 
X) Ammonium acetate 
Y) Sodium chloride 
Z) Potassium formate  

text[[114, 450, 448, 469]]
ANSWER: W) AMMONIUM SULFATE  

sub_title[[456, 505, 540, 523]]
## TOSS-UP  

text[[114, 538, 860, 575]]
10) Earth and Space – Multiple Choice Gypsum often forms when hydrothermal anhydrite [an-HIDE-rite] is hydrated by groundwater. Why is gypsum rarely found in the form of sand?  

text[[114, 592, 602, 664]]
W) Gypsum dissolves in water over time. 
X) Gypsum is resistant to erosion. 
Y) Gypsum reverts back to anhydrite in the presence of water. 
Z) Crystals of gypsum are too large to form sand.  

text[[114, 679, 648, 698]]
ANSWER: W) GYPSUM DISSOLVES IN WATER OVER TIME.  

sub_title[[463, 715, 534, 733]]
## BONUS  

text[[114, 750, 858, 804]]
10) Earth and Space – Short Answer By name or number, order the following four rocks by increasing metamorphic grade: 1) Phyllite [FYE-lite]; 2) Gneiss [NICE]; 3) Slate; 4) Schist [SHIST].  

text[[114, 821, 280, 839]]
ANSWER: 3, 1, 4, 2sub_title[[456, 83, 540, 101]]
## TOSS-UP  

text[[115, 116, 850, 153]]
11) Biology – Short Answer What is the term for asexual reproduction that occurs without fertilization by sperm?  

text[[115, 169, 396, 187]]
ANSWER: PARTHENOGENESIS  

sub_title[[463, 205, 533, 222]]
## BONUS  

text[[115, 238, 780, 275]]
11) Biology – Short Answer What strong biopolymer is responsible for imparting sclerenchyma cells with their strength and rigidity?  

text[[115, 291, 279, 309]]
ANSWER: LIGNIN  

sub_title[[456, 345, 540, 362]]
## TOSS-UP  

text[[115, 378, 882, 450]]
12) Math – Short Answer Anant and Coby are located at the origin on a corner of a square-shaped track with two other vertices (0,4) and (4,0). Anant can run 16 times faster than Coby, and if they both begin running in the counterclockwise direction, how many units apart are Anant and Coby at the moment Anant has finished 9 laps?  

text[[115, 466, 220, 484]]
ANSWER: 5  

sub_title[[463, 502, 533, 519]]
## BONUS  

text[[115, 536, 870, 573]]
12) Math – Short Answer If \(x\) plus the fraction with numerator one and denominator \(x\) equals six, find the value of \(x\) to the fourth power minus \(34x\) squared plus one.  

text[[115, 588, 220, 606]]
ANSWER: 0sub_title[[456, 83, 541, 101]]
## TOSS-UP  

text[[115, 118, 835, 155]]
13) Chemistry – Short Answer Identify all of the following three compounds that have a nonzero degree of unsaturation: 1) \(\mathrm{C_3H_9N}\) ; 2) \(\mathrm{C_5H_9Br}\) ; 3) \(\mathrm{C_4H_8}\) .  

text[[115, 172, 283, 190]]
ANSWER: 2 AND 3  

sub_title[[463, 208, 533, 226]]
## BONUS  

text[[115, 243, 848, 314]]
13) Chemistry – Multiple Choice The left end of a 50-centimeter long glass tube initially contains methane gas, and the right end has oxygen gas. The tube is sealed, and the gases eventually react and combust under heat. Which of the following is closest to the distance, in centimeters, from the left end of the tube that the oxygen and methane react at?  

text[[115, 331, 171, 400]]
W) 17 X) 21 Y) 25 Z) 29  

text[[115, 418, 254, 437]]
ANSWER: Z) 29  

sub_title[[456, 473, 540, 490]]
## TOSS-UP  

text[[115, 505, 883, 542]]
14) Physics – Multiple Choice An uncharged particle initially moves at a 45 degree angle with respect to a uniform magnetic field. Which of the following best describes its trajectory?  

text[[115, 559, 216, 629]]
W) Linear 
X) Circular 
Y) Elliptical 
Z) Helical  

text[[115, 647, 313, 665]]
ANSWER: W) LINEAR  

sub_title[[463, 683, 533, 701]]
## BONUS  

text[[115, 718, 880, 771]]
14) Physics – Short Answer The escape velocity from a hypothetical planet is 1250 meters per second. If the radius is quadrupled, but the density stays constant, find the new escape velocity in meters per second.  

text[[115, 788, 250, 805]]
ANSWER: 5000sub_title[[456, 83, 541, 101]]
## TOSS-UP  

text[[115, 118, 855, 155]]
15) Biology – Multiple Choice Which of the following anatomical structures do sharks not possess?  

text[[115, 171, 604, 243]]
W) Opercula [oh- PER- cue- lah] 
X) Lateral lines 
Y) Ampullae [AMP- yoo- lay] of Lorenzini [lore- en- ZEE- nee] 
Z) Livers  

text[[115, 260, 345, 278]]
ANSWER: W) OPERCULA  

sub_title[[463, 295, 533, 313]]
## BONUS  

text[[115, 330, 883, 418]]
15) Biology – Short Answer Determine all of the following four statements that are true about soil bacteria in the nitrogen cycle: 1) Ammonifying bacteria convert amino acids into ammonium; 2) Nitrogen-fixing bacteria convert atmospheric nitrogen into nitrate; 3) Denitrifying bacteria convert ammonium into atmospheric nitrogen; 4) Nitrifying bacteria convert nitrite into nitrate.  

text[[115, 434, 240, 452]]
ANSWER: 1, 4  

sub_title[[456, 488, 541, 506]]
## TOSS-UP  

text[[115, 521, 860, 574]]
16) Energy – Short Answer Researchers at Pacific Northwest National Lab are trying to produce sulfuric acid. They're doing this using the contact process, which uses what transition metal oxide as a catalyst?  

text[[115, 591, 587, 610]]
ANSWER: VANADIUM PENTOXIDE (ACCEPT: V205)  

sub_title[[463, 627, 533, 645]]
## BONUS  

text[[115, 662, 876, 732]]
16) Energy – Short Answer Scientists at Oak Ridge National Lab are studying the mechanism of action of enzymes responsible for the biosynthesis of amino acids. They predict that a sigma molecular orbital donates electron density to a pi star molecular orbital on the substrate. What is the term for this stabilizing effect?  

text[[115, 750, 413, 768]]
ANSWER: HYPERCONJUGATIONsub_title[[456, 83, 541, 101]]
## TOSS-UP  

text[[115, 118, 833, 154]]
17) Math - Short Answer What is the derivative of the function \(4x\) cubed minus \(9x\) at \(x\) equals 2?  

text[[115, 170, 231, 188]]
ANSWER: 39  

sub_title[[463, 207, 533, 224]]
## BONUS  

text[[115, 241, 846, 278]]
17) Math - Short Answer An ice cream parlor has a selection of 13 different flavors. How many different ways are there to order 2 ice cream cones given that order does not matter?  

text[[115, 293, 230, 311]]
ANSWER: 91  

sub_title[[456, 347, 540, 365]]
## TOSS-UP  

text[[115, 380, 880, 416]]
18) Earth and Space - Short Answer In parsecs, what distance must a star be from the Earth in order to have the same apparent and absolute magnitude?  

text[[115, 432, 320, 450]]
ANSWER: 10 PARSECS  

sub_title[[463, 468, 533, 486]]
## BONUS  

text[[115, 503, 863, 574]]
18) Earth and Space - Short Answer Parallax can be used to measure the distance to nearby stars. However, for stars that are farther away, like those in other galaxies, the parallax angle is too small to measure. Henrietta Leavitt discovered what relationship of Cepheid variable stars that allowed astronomers to measure distances to other galaxies?  

text[[115, 590, 555, 608]]
ANSWER: PERIOD- LUMINOSITY RELATIONSHIPsub_title[[455, 84, 540, 101]]
## TOSS-UP  

text[[115, 117, 880, 154]]
19) Physics – Multiple Choice Which of the following particles has the same Compton and de Broglie [BOY] wavelengths?  

text[[115, 170, 240, 242]]
W) Electron 
X) Up quark 
Y) Photon 
Z) Higgs boson  

text[[115, 258, 316, 276]]
ANSWER: Y) PHOTON  

sub_title[[463, 294, 533, 311]]
## BONUS  

text[[115, 329, 874, 400]]
19) Physics – Short Answer One day, Rishab was at the bus stop when he heard the school bus that was coming to him make a sound of frequency 300 hertz. If the bus was travelling at 20 meters per second and if the speed of sound is 343 meters per second, to the nearest ten hertz, find the frequency of the sound in the reference frame of the bus.  

text[[115, 416, 308, 433]]
ANSWER: 280 HERTZ  

sub_title[[455, 470, 540, 487]]
## TOSS-UP  

text[[115, 504, 872, 541]]
20) Chemistry – Multiple Choice Which of the following pairs of elements combine to create an interstitial alloy?  

text[[115, 558, 330, 630]]
W) Iron and carbon 
X) Zinc and sulfur 
Y) Zinc and copper 
Z) Magnesium and oxygen  

text[[115, 646, 422, 664]]
ANSWER: W) IRON AND CARBON  

sub_title[[463, 682, 533, 699]]
## BONUS  

text[[115, 715, 879, 803]]
20) Chemistry – Short Answer Identify all of the following three statements that are true regarding the Joule-Thompson effect: 1) A real gas will have a higher temperature once given the opportunity to expand into a greater volume; 2) A refrigerator that applies this effect operates via an isenthalpic [eye-sen-THAL-pic] process; 3) At room temperature, helium does not exhibit the Joule-Thomson effect.  

text[[115, 821, 282, 838]]
ANSWER: 2 AND 3sub_title[[456, 83, 541, 101]]
## TOSS-UP  

text[[113, 117, 810, 153]]
21) Biology - Multiple Choice Which of the following statements regarding adaptive coloration is FALSE?  

text[[113, 170, 828, 260]]
W) The stripes of zebras are an example of disruptive coloration 
X) Cryptic coloration is used by both predators and prey 
Y) Aposematic coloration is exploited in Batesian [buh-TEE-see-uhn] mimicry but not in Müllerian [mew-LAIR-ian] mimicry 
Z) The bright neon colors of a poison dart frog are an example of aposematic coloration  

text[[115, 276, 875, 311]]
ANSWER: Y) APOSEMATIC COLORATION IS UTILIZED IN BATESIAN MIMICRY BUT NOT MÜLLERIAN  

sub_title[[464, 329, 533, 347]]
## BONUS  

text[[115, 364, 880, 400]]
21) Biology - Multiple Choice Cows are known for their four-chambered stomachs. Which of the following statements is TRUE regarding cows' stomachs?  

text[[115, 416, 777, 486]]
W) From the esophagus, food can go into either the omasum or the reticulum. 
X) Water is mainly removed from the cud in the abomasum. 
Y) The cow regurgitates food from the reticulum and then chews and swallows the cud. 
Z) The rumen is where the cow's own enzymes digest the cud.  

text[[115, 503, 864, 539]]
ANSWER: Y) THE COW REGURGITATES FOOD FROM THE RETICULUM AND THEN CHEWS AND SWALLOWS THE CUD.  

sub_title[[456, 575, 541, 592]]
## TOSS-UP  

text[[115, 608, 861, 678]]
22) Energy - Short Answer Scientists at Oak Ridge National Lab are studying interactions between the Moon and the Earth due to the Moon being a possible source of helium-3. What is the name of the phenomenon that is responsible for only one side of the moon facing the earth throughout its revolution?  

text[[116, 695, 363, 713]]
ANSWER: TIDAL LOCKING  

sub_title[[464, 731, 533, 749]]
## BONUS  

text[[115, 766, 881, 819]]
22) Energy - Short Answer Researchers at Los Alamos National Lab are studying the properties of twisted trilayer graphene sheets. Graphene sheets are attracted to each other through what noncovalent interactions, which are specific to their aromaticity?  

text[[115, 835, 759, 854]]
ANSWER: PI STACKING (ACCEPT: PI-PI STACKING, PI INTERACTIONS)sub_title[[456, 83, 540, 100]]
## TOSS-UP  

text[[115, 116, 882, 153]]
23) Earth and Space – Short Answer Order the following three regions of the solar atmosphere from coldest minimum temperature to hottest: 1) photosphere; 2) chromosphere; 3) corona.  

text[[115, 170, 260, 188]]
ANSWER: 1, 2, 3  

sub_title[[463, 206, 533, 223]]
## BONUS  

text[[115, 241, 875, 294]]
23) Earth and Space – Short Answer Aurora can be present in many colors. Two of the most common colors are red and green. What molecule in the atmosphere is most responsible for producing these two colors?  

text[[115, 310, 850, 346]]
ANSWER: OXYGEN (ACCEPT: OXYGEN MOLECULE) (DO NOT ACCEPT: OXYGEN ATOM)