sub_title[[455, 90, 540, 108]]
## TOSS-UP  

text[[114, 124, 844, 167]]
1) BIOLOGY – Multiple Choice What type of receptors are least likely to be found on the plasma membrane?  

text[[114, 181, 306, 262]]
W) Estrogen receptor 
X) Adrenergic receptor 
Y) Cholinergic receptor 
Z) Dopamine receptor  

text[[114, 275, 448, 294]]
ANSWER: W) ESTROGEN RECEPTOR  

sub_title[[461, 309, 533, 327]]
## BONUS  

text[[114, 341, 866, 403]]
1) BIOLOGY – Short Answer Psychoactive drugs that produce hallucinatory effects such as mescaline and psilocybin /sy-low-SY-bin/ typically mimic what neurotransmitter via activation of 5-HT receptors?  

text[[115, 416, 323, 435]]
ANSWER: SEROTONIN  

sub_title[[455, 483, 540, 500]]
## TOSS-UP  

text[[114, 515, 880, 557]]
2) MATH – Short Answer What is the coefficient of the \(\mathrm{x}^{3}\mathrm{y}^{2}\) term in the binomial expansion of \((2\mathrm{x} + \mathrm{y})^{5}\) ?  

text[[115, 570, 231, 588]]
ANSWER: 80  

sub_title[[461, 603, 533, 621]]
## BONUS  

text[[114, 635, 857, 698]]
2) MATH – Short Answer A 4 by 4 by 4 magic cube is constructed with the first 64 positive integers, such that the sum of each row, column, and diagonal is equal. What is the sum of the numbers in each row of the magic cube?  

text[[115, 711, 241, 729]]
ANSWER: 130  

sub_title[[455, 777, 540, 795]]
## TOSS-UP  

text[[114, 810, 880, 872]]
3) PHYSICS – Short Answer Catherine the goldfish is looking out the top of her fishbowl, which is filled with water with an index of refraction \(\mathrm{n} = 1.333\) . To two decimal places, what is the sine of the largest angle from vertical that she can look and see outside her fishbowl?text[[115, 91, 245, 108]]
ANSWER: 0.75  

sub_title[[462, 123, 533, 141]]
## BONUS  

text[[113, 155, 868, 196]]
3) PHYSICS – Multiple Choice According to the Yukawa model, which particle mediates the residual strong force?  

text[[114, 210, 222, 290]]
W) Gluons 
X) Pions 
Y) Neutrinos 
Z) Tachyons  

text[[115, 305, 293, 323]]
ANSWER: X) PIONS  

sub_title[[456, 370, 541, 389]]
## TOSS-UP  

text[[115, 403, 833, 444]]
4) EARTH AND SPACE – Short Answer What is the name of a body of water entrapped within an atoll or barrier islands, usually elongated parallel to the shore?  

text[[115, 458, 294, 476]]
ANSWER: LAGOON  

sub_title[[462, 492, 533, 510]]
## BONUS  

text[[115, 524, 877, 564]]
4) EARTH AND SPACE – Multiple Choice Which of the following is NOT true about Balmer lines?  

text[[115, 579, 825, 618]]
W) Cool stars exhibit weak Balmer lines because most of the hydrogen are found near the ground state  

text[[115, 620, 864, 640]]
X) Hot stars exhibit weak Balmer lines because most of the hydrogen are excited above n=2  

text[[115, 641, 864, 680]]
Y) Combined with the absorption lines of other elements, it allows for precise identification of spectral class  

text[[115, 682, 848, 721]]
Z) Combined with the emission lines of other elements, it allows for precise identification of spectral class  

text[[115, 735, 833, 776]]
ANSWER: Z) COMBINED WITH THE EMISSION LINES OF OTHER ELEMENTS, IT ALLOWS FOR PRECISE IDENTIFICATION OF SPECTRAL CLASS  

sub_title[[456, 823, 541, 841]]
## TOSS-UPtext[[114, 88, 854, 150]]
5) ENERGY – Multiple Choice Scientists at Brookhaven National Laboratory used electron microscopy to visualize what happens when phosphorus is exposed to oxygen at room temperature. Which thermodynamically stable allotrope of phosphorus did they use?  

text[[114, 164, 198, 245]]
W) White 
X) Red 
Y) Black 
Z) Violet  

text[[115, 260, 303, 279]]
ANSWER: Y) BLACK  

sub_title[[462, 293, 533, 311]]
## BONUS  

text[[114, 325, 875, 386]]
5) ENERGY – Multiple Choice Scientists at Los Alamos National Laboratory are studying the use of biocatalysts. One of the benefits of using biocatalysts is the ability to exclusively target one bond over another. What is this property called?  

text[[114, 400, 272, 481]]
W) Regiosepific 
X) Regioselective 
Y) Enantiosepific 
Z) Enantioselective  

text[[115, 496, 384, 514]]
ANSWER: W) REGIOSPECIFIC  

sub_title[[455, 550, 541, 567]]
## TOSS-UP  

text[[114, 582, 877, 643]]
6) CHEMISTRY – Short Answer The Coulomb equation can be modified with what parameter to derive the Born-Meyer equation for lattice energy, which accounts for the interaction between point charges in an overall lattice?  

text[[115, 657, 431, 675]]
ANSWER: MADELUNG CONSTANT  

sub_title[[462, 691, 533, 708]]
## BONUS  

text[[114, 723, 877, 784]]
6) CHEMISTRY – Short Answer The reduction potential for the \(\mathrm{Cu}^{2 + } / \mathrm{Cu}\) /Cu 2 plus slash Cu/ couple is \(+0.34\) volts, while the reduction potential for the \(\mathrm{Cu}^{+} / \mathrm{Cu}\) couple is \(+0.52\) volts. To two significant figures, what is the reduction potential for the \(\mathrm{Cu}^{2 + } / \mathrm{Cu}^{+}\) couple in volts?  

text[[115, 798, 257, 816]]
ANSWER: \(+0.16\)  

sub_title[[455, 864, 540, 881]]
## TOSS-UPtext[[115, 89, 787, 130]]
7) BIOLOGY – Short Answer What is the term for a simple stimulus that triggers a fixed-action pattern, such as the aggressive behavior in male sticklebacks?  

text[[115, 143, 360, 162]]
ANSWER: SIGN STIMULUS  

sub_title[[462, 177, 533, 195]]
## BONUS  

text[[115, 209, 752, 250]]
7) BIOLOGY – Multiple Choice Which of the following best explains why the Michaelis-Menten equation does not work for allosteric enzymes?  

text[[115, 263, 591, 345]]
W) Cooperativity is not accounted for  
X) Allosteric modulators act as noncompetitive inhibitors  
Y) Multimeric enzymes need separate plots for each subunit  
Z) Allosteric enzymes cannot be saturated  

text[[115, 358, 633, 378]]
ANSWER: W) COOPERATIVITY IS NOT ACCOUNTED FOR  

sub_title[[455, 425, 541, 443]]
## TOSS-UP  

text[[115, 457, 882, 519]]
8) MATH – Multiple Choice In 2020, the AP test scores for all students have a standard deviation of 1. What is the standard deviation of the distribution of sample means for populations containing 625 students from the general population, according to the central limit theorem?  

text[[115, 532, 193, 612]]
W) 1/625  
X) 1/25  
Y) 1/5  
Z) 1  

text[[115, 628, 271, 647]]
ANSWER: X) 1/25  

sub_title[[462, 662, 533, 680]]
## BONUS  

text[[112, 694, 854, 715]]
8) MATH – Short Answer How many of the first 100 triangular numbers are divisible by 6?  

text[[115, 728, 230, 746]]
ANSWER: 33  

sub_title[[455, 794, 541, 812]]
## TOSS-UP  

text[[115, 826, 857, 867]]
9) PHYSICS – Multiple Choice In which direction would the angular velocity vector for the ticking second hand on a clock point?  

text[[115, 881, 231, 899]]
W) Clockwisetext[[113, 90, 285, 150]]
X) CounterclockwiseY) Into the clockZ) Out of the clock  

text[[115, 163, 398, 183]]
ANSWER: Y) INTO THE CLOCK  

sub_title[[462, 198, 533, 216]]
## BONUS  

text[[113, 230, 852, 271]]
9) PHYSICS – Multiple Choice A copper wire is cut in half, keeping its radius constant. By which of the following factors will its conductivity change?  

text[[113, 284, 174, 365]]
W) 1/2X) 1Y) 2Z) 4  

text[[115, 380, 245, 398]]
ANSWER: X) 1  

sub_title[[455, 445, 540, 464]]
## TOSS-UP  

text[[115, 478, 857, 519]]
10) EARTH AND SPACE – Short Answer What front forms when an immobile cold and an immobile warm front meet, creating a stagnant front line?  

text[[115, 532, 336, 551]]
ANSWER: STATIONARY  

sub_title[[462, 567, 533, 585]]
## BONUS  

text[[115, 599, 872, 640]]
10) EARTH AND SPACE – Short Answer By name or number, identify all the following three environments that would create mudcracks: 1) Continental shelves; 2) Tidal flats; 3) Playa lakes  

text[[115, 652, 696, 672]]
ANSWER: 2 AND 3 (ACCEPT: TIDAL FLATS AND PLAYA LAKES)  

sub_title[[455, 708, 540, 726]]
## TOSS-UP  

text[[115, 740, 841, 802]]
11) ENERGY – Short Answer Researchers at Pacific Northwest National Laboratory have developed a faster forensics method for the detection of ricin, a deadly toxin found in castor beans. Ricin stops protein synthesis by inactivating what cellular organelles?  

text[[115, 815, 323, 833]]
ANSWER: RIBOSOMES  

sub_title[[462, 848, 533, 866]]
## BONUStext[[114, 88, 880, 214]]
11) ENERGY – Short Answer Scientists at SLAC National Accelerator Laboratory used powerful laser impulses on an iron sample and discovered that iron can rearrange into different unit cell structures, such as hexagonal close packing at high enough temperatures. Identify all of the following three statements that are true about the hexagonal close packing structure of iron: 1) It contains tetrahedrally coordinated iron atoms; 2) It has a higher packing efficiency than face centered cubic packing; 3) It contains 4 iron atoms per unit cell.  

text[[115, 226, 265, 245]]
ANSWER: NONE  

sub_title[[455, 292, 541, 311]]
## TOSS-UP  

text[[115, 325, 864, 366]]
12) CHEMISTRY – Multiple Choice Which of the following orbitals has the highest energy in the MO diagram of dinitrogen?  

text[[114, 378, 339, 473]]
W) \(\sigma_{2p}\) [sigma-two-\(p\) ] 
X) \(\sigma_{2p}^{*}\) [sigma-two-\(p\) -star] 
Y) \(\pi_{2p}\) [pi-two-\(p\) ] 
Z) \(\pi_{2p}^{*}\) [pi-two-\(p\) -star]  

text[[115, 487, 271, 508]]
ANSWER: X) \(\sigma_{2p}^{*}\)  

sub_title[[462, 525, 533, 544]]
## BONUS  

text[[114, 557, 883, 641]]
12) CHEMISTRY – Multiple Choice For a reaction carried out over a wide range of temperatures, a graph is plotted of the natural log of the rate constant versus one over the temperature. In terms of the activation energy \(\mathbf{E}_{\mathrm{a}} / \mathbf{E}\) -sub-\(a\) , the pre-exponential factor \(\mathbf{A}\) , and the universal gas constant \(\mathbf{R}\) , what are the slope and y intercepts of the line produced, respectively?  

text[[114, 653, 777, 737]]
W) \(\mathrm{E}_{\mathrm{a}} / \mathrm{R}\) and \(1 / \mathrm{A}\) [E SUB A OVER R AND I OVER A] 
X) \(\mathrm{E}_{\mathrm{a}} / \mathrm{R}\) and \(\ln (\mathrm{A})\) [E SUB A OVER R AND NATURAL LOG OF A] 
Y) \(\mathrm{-E}_{\mathrm{a}} / \mathrm{R}\) and \(1 / \mathrm{A}\) [NEGATIVE E SUB A OVER R AND I OVER A] 
Z) \(\mathrm{-E}_{\mathrm{a}} / \mathrm{R}\) and \(\ln (\mathrm{A})\) [NEGATIVE E SUB A OVER R AND NATURAL LOG OF A]  

text[[115, 749, 372, 769]]
ANSWER: Z) \(\mathrm{-E}_{\mathrm{a}} / \mathrm{R}\) AND \(\ln (\mathrm{A})\)  

sub_title[[455, 816, 541, 834]]
## TOSS-UP  

text[[115, 848, 805, 889]]
13) BIOLOGY – Multiple Choice Which of the following is not a part of the phylum Lycophyta?text[[113, 90, 247, 170]]
W) Quillworts 
X) Liverworts 
Y) Club mosses 
Z) Spike mosses  

text[[115, 185, 363, 203]]
ANSWER: X) LIVERWORTS  

sub_title[[463, 218, 533, 236]]
## BONUS  

text[[115, 250, 878, 290]]
13) BIOLOGY – Short Answer What hormone acts antagonistically to juvenile hormone and is responsible for the initiation of metamorphosis within insects?  

text[[115, 304, 555, 323]]
ANSWER: ECDYSTEROID (ACCEPT: ECDYSONE)  

sub_title[[455, 372, 540, 390]]
## TOSS-UP  

text[[115, 404, 841, 444]]
14) MATH – Short Answer How many positive integers between 1 and 160, inclusive, are divisible by 8 or 10 but not both?  

text[[115, 458, 231, 476]]
ANSWER: 32  

sub_title[[463, 492, 533, 510]]
## BONUS  

text[[115, 524, 860, 565]]
14) MATH – Short Answer For two complementary angles \(\alpha\) and \(\beta\) , if \(\sin (\alpha) + \sin (\beta) = 1 / 3\) , what is \(\sin^3 (\alpha) + \sin^3 (\beta)\) ?  

text[[115, 580, 256, 598]]
ANSWER: 13/27  

sub_title[[455, 646, 540, 664]]
## TOSS-UP  

text[[115, 679, 878, 720]]
15) PHYSICS – Multiple Choice By Kepler's first law, the eccentricity of a planet's orbit must be which of the following?  

text[[115, 734, 272, 814]]
W) 0 
X) Between 0 and 1 
Y) 1 
Z) Greater than 1  

text[[115, 829, 406, 847]]
ANSWER: X) BETWEEN 0 AND 1  

sub_title[[463, 863, 533, 880]]
## BONUStext[[115, 88, 876, 172]]
15) PHYSICS – Short Answer Identify all of the following three choices which would increase the volume energy density between the plates of a parallel plate capacitor: 1) Increasing plate separation, holding voltage constant; 2) Increasing plate separation, holding charge constant; 3) Inserting a dielectric between the plates, holding charge constant.  

text[[115, 185, 265, 203]]
ANSWER: NONE  

sub_title[[455, 239, 540, 258]]
## TOSS-UP  

text[[115, 271, 859, 333]]
16) EARTH AND SPACE – Multiple Choice Droplets of lava that erupt from Kilauea [kil-uh-WAY-uh] and cool rapidly form what are colloquially termed Pele's tears. What is the most accurate description of these tears?  

text[[115, 346, 310, 427]]
W) Phaneritic and mafic 
X) Phaneritic and felsic 
Y) Aphanitic and mafic 
Z) Aphanitic and felsic  

text[[115, 442, 457, 461]]
ANSWER: Y) APHANITIC AND MAFIC  

sub_title[[462, 476, 533, 494]]
## BONUS  

text[[115, 508, 866, 570]]
16) EARTH AND SPACE – Multiple Choice You are looking for Permian and Cambrian fossils along a dome that formed 250 million years ago. Where along the dome would you look for each fossil respectively?  

text[[115, 583, 640, 664]]
W) Permian fossils near the center, Cambrian fossils near the edge 
X) Permian fossils near the edge, Cambrian fossils near the center 
Y) Permian fossils near the top, Cambrian fossils near the bottom 
Z) Permian fossils near the bottom, Cambrian fossils near the top  

text[[115, 678, 864, 718]]
ANSWER: X) PERMIAN FOSSILS NEAR THE EDGE, CAMBRIAN FOSSILS NEAR THE CENTER  

sub_title[[455, 766, 540, 784]]
## TOSS-UP  

text[[115, 798, 879, 860]]
17) ENERGY – Short Answer Scientists at the Princeton Plasma Physics Laboratory used advanced algorithms to help confine heat more efficiently in stellarators, a type of fusion reactor. The code was adapted from modelling turbulence in what torus shaped fusion reactor?  

text[[115, 874, 310, 892]]
ANSWER: TOKAMAKsub_title[[462, 90, 533, 108]]
## BONUS  

text[[115, 122, 859, 204]]
17) ENERGY – Short Answer Scientists at Brookhaven National Laboratory are teaching quantum computers to apply statistical mechanics on the complex plane for both fermions and bosons. At high temperatures and low particle density, both Fermi-Dirac statistics and Bose-Einstein statistics converge on what type of particle statistics?  

text[[115, 217, 553, 236]]
ANSWER: MAXWELL BOLTZMANN STATISTICS  

sub_title[[456, 272, 541, 291]]
## TOSS-UP  

text[[115, 304, 879, 365]]
18) CHEMISTRY – Short Answer What is the slope of the line produced by graphing the Gibbs free energy of an isobaric closed system against the change in total entropy in terms of the temperature T?  

text[[115, 379, 245, 398]]
ANSWER: - 1/T  

sub_title[[462, 413, 533, 431]]
## BONUS  

text[[115, 445, 817, 486]]
18) CHEMISTRY – Multiple Choice Which of the following is closest to the hydrogen nitrogen hydrogen bond angle in urea, which has a molecular formula \(\mathrm{CO(NH_2)_2}\) ?  

text[[115, 500, 252, 579]]
W) 90 degrees X) 109.5 degrees Y) 120 degrees Z) 150 degrees  

text[[115, 594, 360, 613]]
ANSWER: Y) 120 DEGREES  

sub_title[[456, 661, 541, 680]]
## TOSS-UP  

text[[115, 694, 877, 735]]
19) BIOLOGY – Multiple Choice An increase in which of the following would NOT boost the rate of glycolysis?  

text[[115, 748, 348, 830]]
W) AMP X) ADP Y) Citrate Z) Fructose 2,6-bisphosphate  

text[[115, 844, 320, 863]]
ANSWER: Y) CITRATEsub_title[[462, 90, 533, 108]]
## BONUS  

text[[112, 121, 830, 143]]
19) BIOLOGY - Multiple Choice Which of the following is NOT a step of SDS-PAGE?  

text[[113, 155, 568, 238]]
W) Adding sodium dodecyl [doe-deck-il] sulfate  X) Adding beta-mercaptoethanol [mer-cap-toe-ethanol]  Y) Loading protein onto the agarose medium  Z) Applying a voltage across the medium  

text[[114, 250, 603, 270]]
ANSWER: Y) LOADING ONTO AN AGAROSE MEDIUM  

sub_title[[454, 317, 541, 336]]
## TOSS-UP  

text[[114, 350, 841, 391]]
20) MATH - Short Answer A 2021 by 2021 matrix is constructed such that each row and column consists of alternating terms of zero and one. What is the determinant of the matrix?  

text[[115, 404, 222, 422]]
ANSWER: 0  

sub_title[[462, 437, 533, 456]]
## BONUS  

text[[114, 470, 861, 511]]
20) MATH - Short Answer How many integers b greater than 1 exist such that 500 in base b has at least three digits?  

text[[115, 524, 229, 543]]
ANSWER: 21  

sub_title[[454, 579, 541, 598]]
## TOSS-UP  

text[[114, 611, 863, 673]]
21) PHYSICS - Short Answer Order the following three uniform objects from first to last to reach the bottom of an incline, if they are all rolled from the top of the incline: 1) Solid sphere; 2) Hollow sphere; 3) Hoop.  

text[[115, 686, 260, 705]]
ANSWER: 1, 2, 3  

sub_title[[462, 719, 533, 737]]
## BONUS  

text[[114, 751, 870, 835]]
21) PHYSICS - Multiple Choice Light with varying wavelengths is shone on a metal with work function \(W\) . When the kinetic energy of the electrons emitted is plotted against the inverse of the wavelength of light, which of the following are the slope and y-intercept of the nonzero portion of the graph, respectively, in terms of planck's constant \(h\) and the speed of light \(c\) ?  

text[[114, 847, 533, 889]]
W) \(hc\) , \(W / (hc)\) [h times \(c\) , \(W\) divided by \(hc\) ]  X) - \(hc\) , \(W / (hc)\) [negative \(h\) times \(c\) , \(W\) divided by \(hc\) ]text[[113, 88, 616, 130]]
Y) \(hc\) , - W/(hc) [h times c, negative W divided by hc]  
Z) - \(hc\) , - W/(hc) [negative h times c, negative W divided by hc]  

text[[114, 143, 625, 163]]
ANSWER: Y) \(hc\) , - W/(hc) [h times c, negative W divided by hc]  

sub_title[[455, 209, 541, 227]]
## TOSS-UP  

text[[114, 242, 876, 283]]
22) EARTH AND SPACE – Multiple Choice What group of clouds composed of thin sheets of ice crystals scatter sunlight around the Sun into a halo?  

text[[114, 297, 242, 377]]
W) Cirrus  
X) Cirrostratus  
Y) Altostratus  
Z) Nimbostratus  

text[[115, 391, 384, 410]]
ANSWER: X) CIRROSTRATUS  

sub_title[[462, 425, 533, 444]]
## BONUS  

text[[114, 458, 850, 520]]
22) EARTH AND SPACE – Short Answer When gneiss experiences high-grade metamorphism, some of the felsic silicates may melt and solidify once more, leaving igneous bands within unmelted, metamorphic mafic silicates. What type of rock has formed?  

text[[115, 533, 323, 552]]
ANSWER: MIGMATITE  

sub_title[[455, 599, 541, 617]]
## TOSS-UP  

text[[114, 632, 848, 693]]
23) ENERGY – Short Answer Scientists at the Large Hadron Collider are discovering new hadrons made out of different numbers of quarks, such as tetraquarks and pentaquarks. What group of hadrons are made up of one quark and an antiquark, and include kaons and pions?  

text[[115, 707, 291, 725]]
ANSWER: MESONS  

sub_title[[462, 740, 533, 759]]
## BONUS  

text[[114, 773, 879, 835]]
23) ENERGY – Short Answer Scientists at the Joint Genome Institute are studying the mechanism by which introns are spliced. What group of RNA-protein complexes are responsible for guiding the spliceosome towards the ends of introns by recognizing their sequences?  

text[[115, 848, 767, 867]]
ANSWER: snRNPs (ACCEPT: SMALL NUCLEAR RIBONUCLEOPROTEINS)sub_title[[455, 122, 541, 140]]
## TOSS-UP  

text[[113, 155, 828, 175]]
24) CHEMISTRY – Multiple Choice What is the molecular geometry of xenon dioxide?  

text[[114, 190, 293, 270]]
W) Linear 
X) Bent 
Y) Trigonal planar 
Z) Trigonal pyramidal  

text[[115, 284, 288, 303]]
ANSWER: X) BENT  

sub_title[[461, 318, 533, 336]]
## BONUS  

text[[114, 350, 866, 432]]
24) CHEMISTRY – Short Answer A chiral catalyst causes a reaction to produce a mixture of enantiomeric products with an observed rotation of -12. However, it is known that an optically pure solution of the product has a specific rotation of -20. What is the enantiomeric excess in percent of the mixture of products?  

text[[115, 446, 247, 464]]
ANSWER: \(60\%\)  

sub_title[[455, 512, 540, 530]]
## TOSS-UP  

text[[114, 544, 877, 585]]
25) BIOLOGY – Multiple Choice A lady beetle begins to lower its metabolic rate and physical activity during the summer. Which of the following is most likely occurring?  

text[[114, 599, 369, 680]]
W) Anhydrobiosis 
X) Hibernation 
Y) Nonshivering thermogenesis 
Z) Estivation  

text[[115, 695, 352, 713]]
ANSWER: Z) ESTIVATION  

sub_title[[461, 728, 533, 746]]
## BONUS  

text[[114, 761, 819, 802]]
25) BIOLOGY – Multiple Choice Which of the following does NOT take advantage of countercurrent exchange?  

text[[114, 816, 539, 855]]
W) Micturition [mick-TER-eh-tion] in avian urethras 
X) Gas diffusion in fish gillstext[[113, 90, 456, 130]]
Y) Temperature regulation in cetacean finsZ) Reabsorption in primate nephrons  

text[[113, 143, 572, 162]]
ANSWER: W) MICTURITION IN AVIAN URETHRAS