sub_title[[455, 89, 541, 107]]
## TOSS-UP  

text[[114, 124, 855, 168]]
1) CHEMISTRY – Multiple Choice What is the pH of a 0.01 molar solution of a weak acid with a \(\mathrm{pK}_{\mathrm{a}}[p - k - a]\) of 4?  

text[[114, 180, 156, 262]]
W) 1 
X) 2 
Y) 3 
Z) 4  

text[[114, 276, 247, 295]]
ANSWER: Y) 3  

sub_title[[461, 309, 533, 327]]
## BONUS  

text[[114, 341, 857, 383]]
1) CHEMISTRY – Multiple Choice Which of the following describes the dependence of the ion-dipole energy potential on the distance of separation r?  

text[[114, 395, 373, 477]]
W) 1/r 
X) \(1 / \mathrm{r}^{2}\) [one over r squared] 
Y) \(1 / \mathrm{r}^{3}\) [one over r cubed] 
Z) \(1 / \mathrm{r}^{4}\) [one over r to the fourth]  

text[[115, 491, 265, 509]]
ANSWER: X) \(1 / \mathrm{r}^{2}\)  

sub_title[[455, 558, 540, 576]]
## TOSS-UP  

text[[114, 590, 872, 653]]
2) ENERGY – Multiple Choice Scientists at Lawrence Livermore National Laboratory discovered that carbonyl sulfide is produced by wildfires and burning biomass, and will use this to better understand photosynthesis. Which of the following is true about photosynthesis?  

text[[114, 666, 812, 747]]
W) Ubiquinone is the mobile electron carrier between photosystem I and photosystem II 
X) Oxygen evolution occurs when \(\mathrm{P700^{+}}\) oxidizes water 
Y) The cytochrome complex pumps protons into the lumen of the thylakoid 
Z) Most photosynthesis occurs within cellenchyma cells  

text[[114, 760, 872, 801]]
ANSWER: Y) THE CYTOCHROME COMPLEX PUMPS PROTONS INTO THE LUMEN OF THE THYLAKOIDsub_title[[462, 90, 533, 108]]
## BONUS  

text[[114, 122, 856, 204]]
2) ENERGY – Short Answer Researchers using the Advanced Photon Source discovered a highly selective catalyst that will activate methane towards the production of liquid fuels. The catalyst belongs to what class of compounds, consisting of 3D metal clusters coordinated by organic ligands?  

text[[115, 217, 670, 236]]
ANSWER: METAL ORGANIC FRAMEWORKS (ACCEPT: MOFs)  

sub_title[[455, 283, 541, 303]]
## TOSS-UP  

text[[114, 316, 856, 356]]
3) PHYSICS – Multiple Choice Which of the following thermodynamic processes is always irreversible?  

text[[114, 371, 312, 451]]
W) Isobaric expansion 
X) Adiabatic expansion 
Y) Free expansion 
Z) Isothermal expansion  

text[[115, 466, 400, 486]]
ANSWER: Y) FREE EXPANSION  

sub_title[[462, 500, 533, 519]]
## BONUS  

text[[114, 532, 879, 594]]
3) PHYSICS – Short Answer The velocity of a particle can be described by the function of displacement as \(\mathrm{v(x) = 2x^{2} + 4}\) . What is the acceleration of the particle when the displacement of the particle is 2 meters, in meters per second squared?  

text[[115, 607, 231, 625]]
ANSWER: 96  

sub_title[[455, 673, 541, 692]]
## TOSS-UP  

text[[114, 706, 826, 747]]
4) MATH – Short Answer For what value of \(x\) are the two vectors \((1, 3, 2)\) and \((-2, x, 7)\) orthogonal?  

text[[115, 761, 231, 779]]
ANSWER: - 4  

sub_title[[462, 794, 533, 812]]
## BONUS  

text[[113, 826, 860, 846]]
4) MATH – Short Answer Determine the rightmost non-zero digit of the expression \(2020^{2020}\) .  

text[[115, 860, 222, 878]]
ANSWER: 6sub_title[[455, 123, 541, 140]]
## TOSS-UP  

text[[113, 155, 864, 196]]
5) BIOLOGY – Short Answer During periods of intense muscular activity, what substance in myocytes rapidly regenerates the amount of ATP by phosphorylating ADP?  

text[[114, 209, 627, 228]]
ANSWER: CREATINE PHOSPHATE (ACCEPT: CREATINE)  

sub_title[[462, 243, 533, 261]]
## BONUS  

text[[113, 275, 754, 296]]
5) BIOLOGY – Multiple Choice Which of the following groups is still extant?  

text[[114, 309, 387, 389]]
W) Eurypterids [yer- RIP- ter- IDs] X) Ratites Y) Ammonites Z) Conodonts  

text[[115, 404, 317, 423]]
ANSWER: X) RATITES  

sub_title[[455, 470, 540, 488]]
## TOSS-UP  

text[[114, 503, 796, 543]]
6) EARTH AND SPACE – Multiple Choice A sample of hornfels would most likely demonstrate a high abundance of what mineral?  

text[[114, 557, 375, 639]]
W) Kyanite [kahy- uhn- nite] X) Andalusite [An- dl- oo- site] Y) Sillimanite [sil- uh- muh- nite] Z) Kaolinite [kay- oo- lun- nite]  

text[[115, 653, 361, 671]]
ANSWER: X) ANDALUSITE  

sub_title[[462, 687, 533, 704]]
## BONUS  

text[[114, 720, 875, 760]]
6) EARTH AND SPACE – Short Answer What is the distance in parsecs of a hypothetical star with an apparent magnitude of 3 and an absolute magnitude of -2?  

text[[115, 774, 241, 792]]
ANSWER: 100  

sub_title[[455, 840, 540, 857]]
## TOSS-UPtext[[115, 89, 879, 150]]
7) CHEMISTRY – Multiple Choice A graph is plotted of the solubility of a hydrated salt at various temperatures. It is observed that at a certain temperature, the solubility of the salt sharply changes. Which of the following best explains why this happens?  

text[[115, 172, 723, 255]]
W) The hydrated salt has more degrees of freedom 
X) Hydration of the salt favors dissolution of the salt to form solvation shells 
Y) Ionic forces between the cation and anion are disrupted in the hydrate 
Z) Hydrogen bonding stabilizes the hydrate in solution  

text[[115, 268, 773, 287]]
ANSWER: W) THE HYDRATED SALT HAS MORE DEGREES OF FREEDOM  

sub_title[[462, 301, 533, 319]]
## BONUS  

text[[115, 333, 882, 435]]
7) CHEMISTRY – Short Answer An alloy containing metals A and B in a 1 to 1 weight ratio is dissolved in strong acid to produce \(\mathrm{A}^{+}\) and \(\mathrm{B}^{2 + }\) cations, and is then exhaustively electrolyzed such that A is deposited first. When a pure sample of A of the same mass as the alloy is electrolyzed with the same current, it takes twice as long. What is the ratio of the molar mass of A to the molar mass of B?  

text[[115, 450, 430, 469]]
ANSWER: 3/2 (ACCEPT: 3 TO 2; 1.5)  

sub_title[[455, 517, 540, 536]]
## TOSS-UP  

text[[115, 550, 877, 610]]
8) ENERGY – Multiple Choice Scientists at Oak Ridge National Laboratory used a mixture of water and tetrahydrofuran to break down biomass into sugars and lignin. Which of the following is correct about tetrahydrofuran?  

text[[115, 625, 371, 705]]
W) It is a homogeneous catalyst 
X) It is a nonpolar solvent 
Y) It is a polar aprotic solvent 
Z) It is a polar protic solvent  

text[[115, 720, 548, 738]]
ANSWER: Y) IT IS A POLAR APROTIC SOLVENT  

sub_title[[462, 753, 533, 771]]
## BONUS  

text[[115, 786, 879, 867]]
8) ENERGY – Short Answer Researchers at Lawrence Livermore National Lab have been studying the genome of many bacteriophages in the hopes of annotating them for their future use in biotech. The CRISPR system that defends bacteria from bacteriophage infection primarily utilizes what enzyme to cleave viral DNA?sub_title[[455, 156, 541, 174]]
## TOSS-UP  

text[[114, 189, 881, 228]]
9) PHYSICS – Short Answer The current in a 6 henry inductor starts at 2 amps and increases to 4 amps across a period of time. How much energy in joules was added during this time?  

text[[115, 243, 231, 260]]
ANSWER: 36  

sub_title[[462, 276, 533, 294]]
## BONUS  

text[[114, 309, 875, 349]]
9) PHYSICS – Multiple Choice Which of the following scenarios would increase the half width of the central line produced by a diffraction grating?  

text[[114, 363, 456, 444]]
W) Increasing wavelength of incident light  
X) Increasing the number of slits  
Y) Increasing the distance between slits  
Z) Decreasing the intensity of light  

text[[115, 466, 691, 485]]
ANSWER: W) INCREASING WAVELENGTH OF INCIDENT LIGHT  

sub_title[[455, 533, 541, 551]]
## TOSS-UP  

text[[115, 566, 872, 626]]
10) MATH – Short Answer From a solid cube with side length 3, a hole in the shape of a right cylinder with radius 1 and height 3 is bored into the cube. What is the surface area of the resulting figure?  

text[[115, 641, 272, 659]]
ANSWER: \(54 + 4\pi\)  

sub_title[[462, 675, 533, 692]]
## BONUS  

text[[115, 707, 821, 747]]
10) MATH – Short Answer Find the sum of all values of \(x\) such that \(|1 - x| = 2 - |x|\) [the absolute value of the quantity 1 minus \(x\) equals two minus the absolute value of \(x\) ].  

text[[115, 761, 220, 779]]
ANSWER: 1  

sub_title[[455, 816, 541, 833]]
## TOSS-UP  

text[[115, 848, 812, 888]]
11) BIOLOGY – Multiple Choice Which of the following mechanisms would increase transcription?text[[113, 90, 584, 170]]
W) An increase in DNA methylationX) A decrease in histone acetylationY) Corepressor binding to repressor in a repressible operonZ) Inducer binding to a repressor in an inducible operon  

text[[112, 183, 860, 203]]
ANSWER: Z) AN INDUCER BINDING TO A REPRESSOR IN AN INDUCIBLE OPERON  

sub_title[[462, 217, 533, 235]]
## BONUS  

text[[113, 250, 857, 290]]
11) BIOLOGY – Short Answer The Vagus nerve releases what neurotransmitter at synapses near the heart to decrease heart rate?  

text[[115, 304, 375, 322]]
ANSWER: ACETYLCHOLINE  

sub_title[[455, 370, 541, 389]]
## TOSS-UP  

text[[115, 403, 870, 463]]
12) EARTH AND SPACE – Multiple Choice If the peak wavelength of light emitted by a star increases by a factor of 2, then the intensity of radiation from the star will change by what factor?  

text[[115, 479, 184, 560]]
W) 1/16X) 1/4Y) 4Z) 16  

text[[115, 575, 277, 594]]
ANSWER: W) 1/16  

sub_title[[467, 641, 526, 658]]
## ONUS  

text[[115, 673, 880, 733]]
12) EARTH AND SPACE – Short Answer Enceladus is under research as a possible habitable zone in part due to what feature on its surface that emits jets of water vapor, molecular hydrogen, other volatiles into the atmosphere?  

text[[115, 748, 384, 766]]
ANSWER: CRYOVOLCANOES  

sub_title[[455, 814, 540, 832]]
## TOSS-UPtext[[115, 88, 838, 150]]
13) CHEMISTRY – Short Answer What type of cleavage in molecules such as AIBN and benzoyl peroxide forms free radicals by giving 1 electron from the cleaved bond to each fragment?  

text[[115, 163, 330, 182]]
ANSWER: HOMOLYTIC  

sub_title[[462, 197, 533, 215]]
## BONUS  

text[[115, 229, 856, 270]]
13) CHEMISTRY – Short Answer How many \(^{13}\mathrm{C}\) NMR [carbon 13 n-m-r] signals does 2,6 diethyl benzoic acid have?  

text[[115, 283, 221, 302]]
ANSWER: 7  

sub_title[[456, 350, 540, 368]]
## TOSS-UP  

text[[115, 382, 874, 464]]
14) ENERGY – Short Answer Scientists at Ames National Laboratory are conducting a 4D analysis of aptamers in soils, which are RNA molecules that are able to bind to ligands. What general group of RNA molecules act like aptamers as well as being able to catalyze biochemical reactions?  

text[[115, 478, 325, 497]]
ANSWER: RIBOZYMES  

sub_title[[462, 512, 533, 530]]
## BONUS  

text[[115, 544, 872, 626]]
14) ENERGY – Multiple Choice Scientists at Brookhaven National Laboratory used the SuperKEKB colliding beam accelerator to achieve the highest luminosity known so far. What is the dependence of the luminosity produced by the colliding beams on the cross sectional area A of the colliding beams?  

text[[115, 640, 178, 722]]
W) \(1 / \mathrm{A}^{2}\) X) \(1 / \mathrm{A}\) Y) A Z) A2  

text[[115, 736, 265, 755]]
ANSWER: X) \(1 / \mathrm{A}\)text[[115, 89, 840, 150]]
15) PHYSICS – Short Answer What is the name for the apparent contradiction between quantum mechanics, which states that information must be conserved, and general relativity which predicts the loss of information from black holes?  

text[[115, 163, 448, 182]]
ANSWER: INFORMATION PARADOX  

sub_title[[462, 197, 533, 215]]
## BONUS  

text[[115, 230, 882, 290]]
15) PHYSICS – Short Answer An RC circuit consists of a 5 ohm resistor and a 10 Farad capacitor initially charged to 4 volts. The capacitor is left to discharge through the resistor until it reaches 1 volt. To the nearest percent, what percent of the total energy was dissipated into heat?  

text[[115, 304, 248, 322]]
ANSWER: \(94\%\)  

sub_title[[455, 360, 541, 377]]
## TOSS-UP  

text[[115, 392, 700, 411]]
16) MATH – Multiple Choice Which of the following series converges?  

text[[113, 425, 844, 625]]
W) \(\sum_{n = 1}^{\infty}\frac{\ln(n)}{n}\) [the summation from \(n = 1\) to infinity of the natural log of \(n\) over \(n\) ] X) \(\sum_{n = 1}^{\infty}\frac{\sin(n)}{n}\) [the summation from \(n = 1\) to infinity of sine \(n\) over \(n\) ] Y) \(\sum_{n = 1}^{\infty}\frac{\sqrt{n}}{n + 1}\) [the summation from \(n = 1\) to infinity of the square root of \(n\) over \(n\) plus 1] Z) \(\sum_{n = 1}^{\infty}n!e^{-n}\) [the summation from \(n = 1\) to infinity of \(n\) factorial times \(e\) to the negative \(n\) ]  

text[[115, 615, 744, 650]]
ANSWER: X) \(\sum_{n = 1}^{\infty}\frac{\sin(n)}{n}\) [the summation from \(n = 1\) to infinity of sine \(n\) over \(n\) ]  

sub_title[[462, 664, 533, 682]]
## BONUS  

text[[115, 696, 872, 736]]
16) MATH – Short Answer A set of six numbers has a median of 8, a unique mode of 3, and a range of 12. What is the greatest possible mean of this set of numbers?  

text[[115, 750, 245, 768]]
ANSWER: 26/3  

sub_title[[455, 817, 541, 834]]
## TOSS-UP  

text[[115, 849, 872, 889]]
17) BIOLOGY – Multiple Choice Which of the following is NOT true about phytochromes in plants?text[[113, 88, 570, 170]]
W) Red light causes the shift from \(\mathrm{P}_{\mathrm{f}}[p - r]\) to \(\mathrm{P}_{\mathrm{fr}}[p - f - r]\) X) Far red light causes the shift from \(\mathrm{P}_{\mathrm{fr}}[p - f - r]\) to \(\mathrm{P}_{\mathrm{t}}[p - r]\) Y) Red light causes germination Z) Far red light causes germination  

text[[115, 184, 604, 203]]
ANSWER: Z) FAR RED LIGHT CAUSES GERMINATION  

sub_title[[462, 217, 533, 235]]
## BONUS  

text[[115, 250, 850, 311]]
17) BIOLOGY – Short Answer The speciation event that gave rise to craniates is due to the duplication of what set of developmental genes that specify regions of the body plan of an embryo along the head-tail axis of animals?  

text[[115, 325, 253, 344]]
ANSWER: HOX  

sub_title[[456, 392, 540, 410]]
## TOSS-UP  

text[[115, 424, 795, 465]]
18) EARTH AND SPACE – Multiple Choice Which of the following is the defining characteristic of greywacke?  

text[[115, 479, 396, 560]]
W) High concentration of feldspars 
X) Low concentration of feldspars 
Y) High concentration of clays 
Z) Low concentration of clays  

text[[115, 574, 557, 593]]
ANSWER: Y) HIGH CONCENTRATION OF CLAYS  

sub_title[[462, 607, 533, 625]]
## BONUS  

text[[115, 640, 783, 680]]
18) EARTH AND SPACE – Short Answer Barchanoid [bar-kahn-oid] dunes are an intermediate between what two types of dunes?  

text[[115, 694, 486, 713]]
ANSWER: TRANSVERSE AND BARCHAN  

sub_title[[456, 760, 540, 779]]
## TOSS-UP  

text[[115, 793, 870, 834]]
19) CHEMISTRY – Short Answer At very high temperatures, what is the heat capacity of one mole of iodine at constant volume in terms of the ideal gas constant R?  

text[[115, 848, 234, 866]]
ANSWER: 3Rsub_title[[462, 90, 533, 108]]
## BONUS  

text[[115, 121, 857, 204]]
19) CHEMISTRY - Short Answer Identify all of the following three statements that are true about Wilkinson's catalyst: 1) It is a heterogeneous catalyst; 2) It possesses chiral triphenylphosphine ligands; 3) When used for catalytic hydrogenation, it yields a high enantiomeric excess.  

text[[115, 217, 265, 236]]
ANSWER: NONE  

sub_title[[455, 283, 541, 303]]
## TOSS-UP  

text[[115, 316, 876, 378]]
20) ENERGY - Short Answer Scientists at Brookhaven National Laboratory are using the Relativistic Heavy Ion Collider to collide gold nuclei. What hot particle soup-like state of matter do these collisions create?  

text[[115, 391, 444, 411]]
ANSWER: QUARK-GLUON PLASMA  

sub_title[[462, 425, 533, 444]]
## BONUS  

text[[115, 457, 870, 562]]
20) ENERGY - Short Answer Researchers at Thomas Jefferson National Accelerator Facility have been calibrating the equipment needed for the MOLLER experiment, which uses the asymmetry of scattered electrons in order to more precisely measure the electroweak parameter. The frequency of scattered electrons is measured by their generation of pale blue light when directed into a silica tube. What type of radiation are they observing?  

text[[115, 574, 648, 594]]
ANSWER: CERENKOV (DO NOT ACCEPT: SYNCHROTRON)  

sub_title[[455, 628, 540, 647]]
## TOSS-UP  

text[[115, 660, 866, 702]]
21) PHYSICS - Short Answer What quark cannot form hadrons, because of its mean lifetime being one twentieth of the timescale for strong interactions?  

text[[115, 715, 323, 734]]
ANSWER: TOP QUARK  

sub_title[[462, 749, 533, 768]]
## BONUS  

text[[115, 781, 850, 823]]
21) PHYSICS - Short Answer Identify all of the following three types of scattering that are elastic: 1) Rayleigh; 2) Raman; 3) Compton.  

text[[115, 836, 280, 855]]
ANSWER: 1 ONLYsub_title[[455, 90, 541, 108]]
## TOSS-UP  

text[[113, 122, 875, 163]]
22) MATH - Short Answer The variance of a set of numbers is 8. If each number is multiplied by 5 and increased by 12, what is the new variance of this set of numbers?  

text[[115, 176, 241, 195]]
ANSWER: 200  

sub_title[[462, 210, 533, 229]]
## BONUS  

text[[115, 242, 750, 262]]
22) MATH - Short Answer Find all solutions to the equation \(4^{x} - 2^{x + 1} - 8 = 0\) .  

text[[115, 276, 221, 294]]
ANSWER: 2  

sub_title[[455, 342, 541, 360]]
## TOSS-UP  

text[[113, 374, 844, 395]]
23) BIOLOGY - Short Answer What is the only proteinogenic amino acid that is bicyclic?  

text[[115, 408, 342, 427]]
ANSWER: TRYPTOPHAN  

sub_title[[462, 442, 533, 460]]
## BONUS  

text[[115, 474, 833, 515]]
23) BIOLOGY - Short Answer During inflammation, what group of paracrine molecules produced from arachidonic acid by the COX pathway leads to localized swelling and pain?  

text[[115, 528, 387, 547]]
ANSWER: PROSTAGLANDINS  

sub_title[[455, 595, 541, 613]]
## TOSS-UP  

text[[112, 627, 860, 648]]
24) EARTH AND SPACE - Multiple Choice The Wilson cycle is a model of which process?  

text[[115, 661, 456, 680]]
W) Increasing and decreasing of sunspots  

text[[115, 684, 432, 702]]
X) Opening and closing of ocean basins  

text[[115, 705, 319, 722]]
Y) Periodicity of eclipses  

text[[115, 725, 456, 743]]
Z) Increasing and decreasing of \(\mathrm{CO}_{2}\) levels  

text[[115, 756, 637, 776]]
ANSWER: X) OPENING AND CLOSING OF OCEAN BASINS  

sub_title[[462, 790, 533, 808]]
## BONUS  

text[[115, 822, 879, 863]]
24) EARTH AND SPACE - Short Answer By name or number, identify all the following three places in a galaxy that Population I stars would be found in: 1) Bulge; 2) Disk; 3) Halo.sub_title[[455, 155, 541, 174]]
## TOSS-UP  

text[[113, 188, 880, 228]]
25) CHEMISTRY - Multiple Choice Which of the following could not be the formal charge of the nitrogen atom in a resonance structure of the isocyanate anion?  

text[[113, 243, 164, 325]]
W)-2 X)-1 Y)0 Z)+1  

text[[114, 340, 253, 358]]
ANSWER: Z) +1  

sub_title[[462, 372, 533, 390]]
## BONUS  

text[[114, 404, 861, 487]]
25) CHEMISTRY - Short Answer Identify all of the following three statements that are true about carbocations in organic chemistry: 1) Tertiary carbocations are more stable than primary carbocations; 2) Carbocations can become more stable by 1,2 methyl or 1,2 hydride shifts; 3) Conjugation with carbon pi systems greatly destabilizes carbocations.  

text[[114, 500, 283, 518]]
ANSWER: 1 AND 2