
## TOSS-UP  


1) BIOLOGY – Short Answer Chondrocytes [kon-dro-sites] secrete collagen and what glycosaminoglycan that contributes to the tensile strength of cartilage?  


ANSWER: CHONDROITIN (ACCEPT: CHONDROITIN SULFATE)  


## BONUS  


1) BIOLOGY – Multiple Choice Alex’s father had Huntington’s disease but his mother does not. His father’s genotype was determined to be heterozygous after his death. His mother’s family has no history of the disease. If the penetrance of Huntington’s is 75%, what is the probability that Alex has the gene for Hungtinton’s though he does not exhibit the phenotype?  


W) 1/2 X) 3/8 Y) 5/9 Z) 2/7  


ANSWER: Z) 2/7  


## TOSS-UP  


2) MATH – Short Answer Alex has 4 different bags of tea he can drink over the course of 5 days, two of which are identical. How many different ways can he select which days he will drink his four bags of tea?  


ANSWER: 375  


## VISUAL BONUS  


2) MATH – Short Answer Shown in the image is a fractal composed of inscribed squares and circles. The shaded region consists of the area inside each square and outside of its inscribed circle. If the largest square has side length 1, determine the total area of the shaded region.  


ANSWER: \(2 - \pi /2\)  


## TOSS-UP  


3) PHYSICS – Multiple Choice In a 2-dimensional universe, which of the following quantities is a vector field?
W) Laplacian of electric potentialX) Gradient of divergence of electrical fieldY) Curl of magnetic fieldZ) Electric potential  


ANSWER: X) GRADIENT OF DIVERGENCE OF ELECTRICAL FIELD  


## VISUAL BONUS  


3) PHYSICS – Short Answer The diagram depicts a certain type of particle accelerator. Answer the following two questions about this machine.  


I. What is the name for this type of particle accelerator?II. Suppose the machine is used to accelerate spherical angry birds with a charge of \(+2\) Coulombs and mass of \(0.5 \mathrm{kg}\) with an applied magnetic field of 6 Tesla. At what angular frequency must the applied electric field oscillate to accelerate these birds?  


ANSWER: 1) CYCLOTRON, 2) 24 RADIANS PER SECOND ( \(\frac{12}{\pi}\) hertz)  


## TOSS-UP  


4) EARTH AND SPACE – Short Answer By name or number, identify all the following three statements that are true about supernovas: 1) The radioactive decay of nickel-56 is the main source of energy that is emitted by the supernova remnant after the initial explosion; 2) Type Ia supernovae may leave behind neutron stars; 3) Type Ic supernovae exhibit characteristic non-ionized helium lines.  


ANSWER: 1 ONLY  


## BONUS  


4. EARTH AND SPACE - Short Answer Identify all of the following three statements that are true concerning subduction zone: 1) Low angle subduction of the Farallon plate created the basin and range territory; 2) High angle subduction zones are associated with increased seismicity; 3) Volcanic gaps are most commonly associated with calc - alkaline magmas.  


ANSWER: 1 AND 3
5) ENERGY – Short Answer Scientists at Argonne National Laboratory are studying the mechanism of diabetes drugs by imaging the 3D shape of human glucagon receptor, a known metabotropic receptor. These receptors initiate signal transduction via a metabolic pathway. By name or number, identify all the following three receptors that are also metabotropic receptors: 1) Nicotinic receptor; 2) Muscarinic receptor; 3) Beta-adrenergic receptors.  


ANSWER: 2 AND 3  


## BONUS  


5) ENERGY – Multiple Choice Scientists at Lawrence Berkeley National Laboratory are researching how non-pathogenic bacteria become pathogenic to prevent the onset of infections like cholera. One facet of their research is the interaction of DNA-binding regulatory proteins that change gene expression. Which of the following DNA-binding motifs is most commonly found within dimerizing bacterial transcription factors?  


W) Helix-loop-helix  
X) Helix-turn-helix  
Y) Zinc finger  
Z) Leucine zipper  


ANSWER: X) HELIX-TURN-HELIX  


## TOSS-UP  


6) CHEMISTRY – Short Answer Order the following three nitrogen heterocycles by increasing pKa of their conjugate acid: 1) Pyrrole; 2) Pyridine; 3) Pyrimidine.  


ANSWER: 3, 2, 1  


## VISUAL BONUS  


6) CHEMISTRY – Short Answer Answer the following three questions about the MO diagram of a metal complex shown in the image:  


I. What is the geometry around the metal center in the complex?  
II. Classify the LUMO as either bonding, nonbonding, or antibonding.  
III. What is the spin multiplicity of the complex?  


ANSWER: 1) OCTAHEDRAL; 2) NONBONDING; 3) 1 (ACCEPT: SINGLET)
## TOSS-UP  


7) BIOLOGY – Multiple Choice Which of the following explains why intrafusal muscles contract after extrafusal muscles have contracted?  


W) To achieve optimal length 
X) To maintain tension on stretch receptors 
Y) To reduce eccentric contraction 
Z) To stabilize connection to tendon  


ANSWER: X) TO MAINTAIN TENSION ON STRETCH RECEPTORS  


## BONUS  


7) BIOLOGY – Short Answer Identify all of the following three compounds that are able to reduce disulfide bonds to two cysteine residues in proteins:1) Sodium dodecyl sulfate; 2) Dithiothreitol; 3) Beta-mercaptoethanol.  


ANSWER: 2 AND 3  


## TOSS-UP  


8) MATH – Short Answer What is the fifth derivative of the function \(f(x) = x^{5}e^{x}\) at \(x = 0\) ?  


ANSWER: 120  


## BONUS  


8) MATH – Short Answer Kira writes the first N positive integers on a chalkboard, then counts the number of digits on the chalkboard. She observes that the total number of digits on the chalkboard is divisible by N. What is the smallest possible three digit value of N?  


ANSWER: 108  


## TOSS-UP  


9) PHYSICS – Short Answer An electron travels with velocity \(3.2 \mathrm{m / s}\) perpendicular to a magnetic field of \(9.1 \mathrm{T}\) . What is the radius of the resulting circular path in meters and in scientific notation with one significant figure?  


ANSWER: \(2 \times 10^{- 12} \mathrm{m}\)
## BONUS  


9) PHYSICS - Short Answer The density of the atmosphere can be modeled as a function of height from the surface, \(\rho (\mathrm{h}) = e^{-h}\) [rho of h equals e to the negative h] What is the force of buoyancy on a 4x4x4m cube sitting on the ground in terms of the gravitational acceleration g?  


ANSWER: \((16 - 16e^{- 4})g\)  


## TOSS-UP  


10) EARTH AND SPACE - Multiple Choice White smokers in Lost City generate heat when peridotite reacts exothermically with water to form what rock?  


W) Serpentinite X) Goethei Y) Geyserite Z) Tachylite  


ANSWER: W) SERPENTINITE  


## VISUAL BONUS  


10) EARTH AND SPACE - Short Answer Shown in the diagram is a cross sectional profile of an ophiolite complex. Answer the following 3 questions concerning the diagram:  


I. Layer 3 is massive gabbro. Give the number for each of the following layers: 1) Peridotite; 2) Sheeted Dikes; 3) Pillow Basalts. II. Order the following three in order from shallowest to deepest: 1) Petrological Moho; 2) Seismic Moho; 3) Sheeted Diabase. III. What is the name of the process of the accretion of oceanic crust on top of continental crust?  


ANSWER: I) \(1 = 4;2 = 2;3 = 1;\) II) 3, 2, 1; 3) OBDUCTION  


## TOSS-UP  


11) ENERGY - Multiple Choice Scientists at the National Renewable Energy Laboratory are using various spectroscopic techniques to analyze organic compounds in batteries, such as \(^{13}\mathrm{C}\) NMR. However unlike proton NMR, peaks in \(^{13}\mathrm{C}\) NMR can not be integrated to yield
meaningful data. Which of the following best explains why \(^{13}\mathrm{C}\) NMR signals can not be integrated?  


W) Slow relaxation time of \(^{13}\mathrm{C}\) nuclei  
X) High nuclear shielding of \(^{13}\mathrm{C}\) nuclei  
Y) Low nuclear spin of \(^{13}\mathrm{C}\) nuclei  
Z) Low coupling constant of \(^{13}\mathrm{C}\) nuclei  


ANSWER: W) SLOW RELAXATION TIME OF \(^{13}\mathrm{C}\) NUCLEI  


## BONUS  


11) ENERGY – Short Answer Scientists at Lawrence Livermore National Laboratory are using seismic data to model the interior of the Earth. Identify all the following three statements that are true regarding the seismic waves: 1) Rayleigh waves roll perpendicular to the ground; 2) Refracted p-waves from the Moho move faster than direct p-waves towards a seismograph station; 3) The Gutenberg discontinuity demarcates the boundary between the mantle and outer core.  


ANSWER: ALL  


## TOSS-UP  


12) CHEMISTRY – Short Answer By name or number, identify all of the following three reducing agents capable of reducing an amide: 1) \(\mathrm{BH}_3\) ; 2) \(\mathrm{NaBH}_4\) ; 3) \(\mathrm{LiAlH}_4\) .  


ANSWER: 1 AND 3  


## BONUS  


12) CHEMISTRY – Short Answer Answer the following two questions about the rigid rotor model for the diatomic molecule dihydrogen:  


I. What is the ratio of the wavelength of the first absorption to the wavelength of the second absorption of dihydrogen?  
II. What is the ratio of the energy of the first absorption of dihydrogen to the energy of the first absorption of dideuterium, consisting of two deuterium atoms?  


ANSWER: 1) 2; 2) 2
## TOSS-UP  


13) BIOLOGY - Multiple Choice To what phylum of bacteria does the causative agent of syphilis, Treponema pallidum, belong to?  


W) Proteobacteria 
X) Spirochetes [Spiro-ketes] 
Y) Actinobacteria 
Z) Chlamydias  


ANSWER: X) SPIROCHETES  


## VISUAL BONUS  


13) BIOLOGY - Short Answer Depicted in the image are three different forms of DNA, the A-form, B-form and Z-form. Answer the following two questions about the depicted images:  


I. Which form of DNA is the most common in biological systems? 
II. Match the three forms of DNA with the numbers in the image.  


ANSWER: 1) B-FORM; 2) 1 IS A-FORM; 2 IS B-FORM; 3 IS Z-FORM  


## TOSS-UP  


14) MATH - Short Answer Let A be a 3 by 4 matrix with a rank of 3, and let T be the linear transformation defined by \(\mathrm{T(v) = Av}\) . By number, identify all of the following three statements that are true about the linear transformation: 1) The codomain of T is \(\mathrm{R^4}\) ; 2) T is bijective; 3) The range of T is the same as its codomain.  


ANSWER: 3 ONLY  


## BONUS  


14) MATH - Short Answer A sequence \(a\) of integers is defined by \(a_{0} = 1\) , \(a_{1} = 0\) , and \(a_{n + 2} = 2 + a_{n + 1} - a_{n}\) . How many of the first 2020 terms in this sequence are one more than a multiple of three?  


ANSWER: 1010  


## TOSS-UP
15) PHYSICS – Short Answer The \(x\) component of a particle’s displacement can be described as a function of time by \(\mathrm{r(t)} = 4\sin (\mathrm{t})\) for \(t\) equals 4 times the sine of \(t\) , where \(t\) is time. Identify all of the following three statements that could be true about the motion of the particle: 1) It is moving in a circle; 2) It is moving between two points; 3) The acceleration is never decreasing.  


ANSWER: ALL  


## VISUAL BONUS  


15) PHYSICS – Short Answer Shown in the image is a device used to measure small oscillations in magnetic fields via the use of a Josephson junction, which can be effectively modeled as a superconducting qubit. Answer the following two questions concerning this device:  


I. What is the common name for this device?  
II. The Josephson junction makes use of the tunneling of which composite bosons?  


ANSWER: 1) SQUID; 2) COOPER PAIR (ACCEPT: BCS PAIR)  


## TOSS-UP  


16) EARTH AND SPACE – Short Answer In contrast to nutation<sup>1</sup> which is caused by small deviations in the axial tilt of the moon, what other phenomena observes the wobbling of the moon due to shifts in the observer’s perspective?  


ANSWER: LIBRATION  


## VISUAL BONUS  


16) EARTH AND SPACE – Short Answer Shown in the picture is the surface of Mercury. Answer the following two questions concerning the image shown:  


I. What is the name for the feature that the picture exhibits?  
II. What relationship does the feature have in relation to the Caloris crater?  


W) Concurrent  
X) Antipodal  
Y) Surrounding  
Z) No relationship  


ANSWER: I) LINEATED TERRAIN; II) X) ANTIPODAL
## TOSS-UP  


17) ENERGY - Short Answer Scientists at Oak Ridge National Laboratory built a novel microscope to view biological systems such as cell membranes. Cell membranes, along with aqueous solutions of detergents and other lipids, belong to what class of liquid crystals which are layered structures that result from the action of a solvent on a liquid?  


ANSWER: LYOTROPIC  


## BONUS  


17) ENERGY - Short Answer Scientists at SLAC National Accelerator Laboratory are using the Fermi Space Telescope to look for the effects of dark matter within the universe. What is the name for the dark matter candidate that exists and strongly interacts with each other via gravity but poorly with normal matter?  


W) Axions 
X) MACHOs 
Y) WIMPs 
Z) SIMPs  


ANSWER: Z) SIMPS  


## TOSS-UP  


18) CHEMISTRY - Multiple Choice Which of the following elements has a greater ionization energy than its respective diatomic compound?  


W) Lithium 
X) Beryllium 
Y) Boron 
Z) Carbon  


ANSWER: X) BERYLLIUM  


## BONUS  


18) CHEMISTRY - Short Answer By name or number, identify all of the following three factors that increase selectivity for elimination over substitution: 1) Using a harder nucleophile; 2) Using a more hindered nucleophile; 3) Using a more basic nucleophile.
## TOSS-UP  


19) BIOLOGY - Short Answer By name or number, identify all the following three groups that utilize protonephridia: 1) Lancelets; 2) Tunicates; 3) Rotifers.  


ANSWER: 1 AND 3  


## VISUAL BONUS  


19) BIOLOGY - Short Answer Many compounds found within animals have similar analogs within plants. Looking at the following picture, give the plant hormone analogs identified by A, B, and C based on the corresponding animal signaling compound on the right.  


ANSWER: A) JASMONATE, B) AUXIN (ACCEPT: IAA) C) BRASSINOSTEROID (ACCEPT: BRASSINOLIDE)  


## TOSS-UP  


20) MATH - Short Answer Let \(f(n) = \frac{n - 1}{3}\) [the fraction with numerator \(n - 1\) and denominator three] What is the smallest integer value of \(n\) for which \(f(f(n))\) is a positive integer?  


ANSWER: 13  


## BONUS  


20) MATH - Short Answer Equiangular hexagon ABCDEF has sides \(\mathrm{AB} = 6\) , \(\mathrm{BC} = 5\) , \(\mathrm{CD} = 4\) , and \(\mathrm{DE} = 3\) . What is the area of this hexagon?  


ANSWER: \(109\sqrt{3} /4\)  


## TOSS-UP  


21) PHYSICS - Short Answer A wave of light originally in a vacuum passes through a medium with a relative permeability of 60 and dielectric constant of 5. To two significant figures and in scientific notation, what is the new speed of light in the medium?  


ANSWER: \(1.7 \times 10^{7}\)
## BONUS  


21) PHYSICS - Short Answer What is the ratio of the final momentum to initial momentum of a \(3\mathrm{kg}\) mass if its velocity increases from \(0.6\mathrm{c}\) to \(0.8\mathrm{c}\) ?  


ANSWER: 16/9  


## TOSS-UP  


22) EARTH AND SPACE - Short Answer What process is responsible for most of the heavy elements past iron within asymptotic giant branch stars?  


ANSWER: S-PROCESS  


## VISUAL BONUS  


22) EARTH AND SPACE - Short Answer Depicted in the image is Sheep Mountain, a prominent plunging anticline. Answer the two questions concerning this mountain.  


I. Using the key to the right, what formation on Sheep Mountain is the oldest?  
II. Using the North signal in the upper right for orientation, what cardinal direction is the Sheep Mountain plunging towards?  


ANSWER: 1) MADISON; 2) NORTH  


## TOSS-UP  


23) ENERGY - Multiple Choice Scientists from Argonne National Laboratory discovered that superfluids can merge via a corkscrew-like mechanism. Examples of superfluids include helium-3 and helium-4, which form superfluids below their lambda points. Which of the following explains the relationship between the lambda point of helium three and the lambda point of helium four?  


W) Helium three has a higher lambda point because it is fermionic  
X) Helium three has a higher lambda point because it is bosonic  
Y) Helium three has a lower lambda point because it is fermionic  
Z) Helium three has a lower lambda point because it is bosonic  


ANSWER: Y) HELIUM THREE HAS A LOWER LAMBDA POINT BECAUSE IT IS FERMIONIC
## BONUS  


23) ENERGY - Short Answer Scientists at Brookhaven National Laboratory are studying the role of the nitrogen cycle within ecosystems. What step within the nitrogen cycle directly converts ammonium back into atmospheric nitrogen?  


ANSWER: ANAMMOX<sup>3</sup> (ACCEPT: ANAEROBIC AMMONIUM OXIDATION)  


## TOSS-UP  


24) CHEMISTRY - Short Answer Order the following three ligands in increasing trans effect: 1) \(\mathrm{NH}_3\) ; 2) \(\mathrm{Cl}^-\) ; 3) \(\mathrm{CN}^-\) .  


ANSWER: 1, 2, 3  


## VISUAL BONUS  


24) CHEMISTRY - Short Answer Shown in the image is a Frost diagram for various oxidation states of chromium, which describes the relative potentials of chromium compounds under different conditions. Answer the following two questions regarding the image:  


I. To the nearest volt, what is the standard reduction potential of \(\mathrm{Cr}^{2 + }\) ? 
II. Which of the 8 species shown in the diagram spontaneously disproportionate?  


ANSWER: 1. - 1V; 2. \(\mathrm{Cr(IV)}\) AND \(\mathrm{Cr(V)}\)  


## TOSS-UP  


25) BIOLOGY - Short Answer Which meninge of the brain is closest to the skull?  


ANSWER: DURA MATER  


## VISUAL BONUS  


25) BIOLOGY - Short Answer Shown in the image is an EEG complex of a sleeping teenager. She is not on any medication and is not intoxicated<sup>4</sup>. Answer the following three questions concerning this teenager:  


I. Is he experiencing REM sleep or NREM sleep?
II. Knowing that apart from the complexes labeled A and B, the rhythm rests around 4 to 8Hz, identify all of the following three rhythms that are occurring: 1) Theta rhythm; 2) Delta rhythm; 3) Alpha rhythm.  


III. What is the term for the high frequency structure that interrupts the rhythm labeled A, and the high amplitude structure labeled B, respectively?  


ANSWER: 1) NREM; 2) 1 ONLY; 3) A) SLEEP SPINDLE; B) K COMPLEX<sup>5</sup>