sub_title[[455, 90, 540, 108]]
## TOSS-UP  

text[[115, 124, 861, 188]]
1) EARTH AND SPACE – Multiple Choice Which of the following types of galaxies were fundamental in helping astronomers determine that the early universe contained more compact and more irregular galaxies?  

text[[114, 202, 399, 283]]
W) Starburst galaxies  X) Ultra luminous infrared galaxies  Y) Blue dwarf galaxies  Z) Seyfert galaxies  

text[[115, 296, 466, 315]]
ANSWER: Y) BLUE DWARF GALAXIES  

sub_title[[424, 330, 573, 349]]
## VISUAL BONUS  

text[[115, 365, 853, 406]]
1) EARTH AND SPACE – Short Answer Answer the following 3 questions concerning the picture shown:  

text[[128, 408, 847, 490]]
I. Give the name for each of the following types of partial melting with their respective number: 1) Decompression Melting; 2) Frictional Melting. 3) Flux Melting.  
II. Name the feature found at the letter 'A'.  
III. Give the letter where one would most likely find MORBs.  

text[[115, 511, 480, 531]]
ANSWER: I. a) 1 b) 3 c) 2; II. DIAPIR; III. B  

sub_title[[454, 567, 541, 585]]
## TOSS-UP  

text[[115, 599, 855, 661]]
2) CHEMISTRY – Short Answer Identify all of the following three rearrangements that proceed through carbene intermediates: 1) Wolff rearrangement; 2) Curtius rearrangement; 3) Hoffman rearrangement.  

text[[115, 675, 280, 693]]
ANSWER: 1 ONLY  

sub_title[[424, 708, 573, 727]]
## VISUAL BONUS  

text[[115, 741, 853, 802]]
2) CHEMISTRY – Short Answer Shown in the image are the mechanisms of three different pericyclic reactions. By number, identify all of the mechanisms shown that are thermally allowed.  

text[[115, 816, 283, 834]]
ANSWER: 2 AND 3sub_title[[455, 90, 540, 108]]
## TOSS-UP  

text[[114, 122, 877, 245]]
3) ENERGY – Short Answer Scientists at Princeton Plasma Physics Laboratory are studying the splitting of Mercury’s spectral lines by the Zeeman effect and the planet’s unique magnetic sphere. While this splitting can easily be seen by most spectrometers, a group of small shifts and splittings caused by nuclear magnetic dipole moments interacting with the magnetic field generated by the electrons can only be seen using interferometry. What is the name of this group of shifts?  

text[[115, 259, 439, 278]]
ANSWER: HYPERFINE STRUCTURE  

sub_title[[424, 292, 572, 311]]
## VISUAL BONUS  

text[[115, 325, 877, 386]]
3) ENERGY – Multiple Choice Shown is the tandem mass spectrum of a polypeptide, with the mass to charge ratio of each peak listed above their respective peaks. Which of the following could be the sequence of the first three amino acid residues in the polypeptide?  

text[[115, 400, 396, 481]]
W) Tryptophan, leucine, isoleucine 
X) Cysteine, valine, proline 
Y) Alanine, methionine, tyrosine 
Z) Lysine, histidine, arginine  

text[[115, 495, 593, 514]]
ANSWER: W) TRYPTOPHAN, LEUCINE, ISOLEUCINE<sup>1</sup>  

sub_title[[455, 562, 540, 580]]
## TOSS-UP  

text[[115, 594, 866, 635]]
4) PHYSICS – Multiple Choice Which of the following statements is false regarding systems at negative temperature?  

text[[115, 650, 555, 731]]
W) They have bounded phase spaces 
X) They are in thermal equilibrium 
Y) As heat is added, entropy decreases 
Z) They are colder than systems at positive temperature  

text[[115, 744, 838, 764]]
ANSWER: Z) THEY ARE COLDER THAN SYSTEMS AT POSITIVE TEMPERATURE  

sub_title[[462, 778, 533, 796]]
## BONUS  

text[[115, 811, 855, 850]]
4) PHYSICS – Short Answer An infinite number of resistors are placed in parallel. The first resistor has a resistance of 1 ohm, the second has a resistance of 3 ohms, the third has atext[[113, 88, 857, 130]]
resistance of 9 ohms, and so on, with each resistor having triple the resistance of the last. If 16 volts are applied across these resistors, how many amperes of current will flow?  

text[[115, 142, 327, 161]]
ANSWER: 24 AMPERES  

sub_title[[454, 209, 541, 227]]
## TOSS-UP  

text[[113, 240, 830, 287]]
5) MATH - Short Answer If \(f(1 + \frac{1}{x}) = x - 1\) , If of the quantity 1 plus 1 over x equals x minus 1J compute \(f^{-1}(2)\) .  

text[[115, 300, 237, 318]]
ANSWER: 4/3  

sub_title[[462, 334, 533, 352]]
## BONUS  

text[[113, 366, 861, 427]]
5) MATH - Short Answer Let D be a point on side AB on equilateral triangle ABC such that \(\mathrm{AD} = 3\) and \(\mathrm{DB} = 9\) . Determine the maximum possible length of segment DE, if E can be any point on the circumcircle of ABC.  

text[[115, 438, 295, 459]]
ANSWER: \(\sqrt{21} +4\sqrt{3}\)  

sub_title[[454, 499, 540, 517]]
## TOSS-UP  

text[[113, 530, 870, 570]]
6) BIOLOGY - Short Answer What group of unmethylated DNA sequences does TLR9 detect that are commonly found within bacteria and viruses, but not animals?  

text[[115, 583, 437, 603]]
ANSWER: CpG SITES (ACCEPT: CG)  

sub_title[[462, 617, 533, 636]]
## BONUS  

text[[113, 650, 860, 691]]
6) BIOLOGY - Short Answer What set of nonlinear differential equations are often used as approximations to model the prey predator relationships in nature?  

text[[115, 703, 507, 722]]
ANSWER: LOTKA-VOLTERRA EQUATIONS  

sub_title[[454, 771, 540, 789]]
## TOSS-UP  

text[[113, 803, 855, 864]]
7) EARTH AND SPACE - Short Answer Rank the following three orbits of a Schwarzschild black hole in increasing distance from the singularity: 1) ISCO; 2) Photon sphere; 3) Event horizon.sub_title[[423, 122, 572, 141]]
## VISUAL BONUS  

text[[115, 155, 882, 216]]
7) EARTH AND SPACE - Short Answer Shown in the image is the black hole in M87 compiled by the Event Horizon Telescope collaboration using radio telescopes via interferometry. Answer the following three questions concerning the black hole in this image:  

text[[123, 229, 860, 374]]
I. The brighter accretion disk on one side of the black hole compared to the other side is due to what phenomenon, occurring when relativistic doppler effects cause matter moving away to appear dimmer than matter moving towards an observer?II. The black hole in the image is mounting evidence for the impossibility of observing a naked singularity, postulated by what hypothesis?III. A: What classic theorem states that this black hole can be completely described by three properties and B: Name these three properties.  

text[[115, 386, 881, 450]]
ANSWER: 1) RELATIVISTIC BEAMING (ACCEPT: DOPPLER BEAMING, DOPPLER BOOSTING, OR THE HEADLIGHT EFFECT); 2) COSMIC CENSORSHIP HYPOTHESIS; 3) A: NO HAIR THEOREM; B) MASS, CHARGE, ANGULAR MOMENTUM  

sub_title[[455, 496, 541, 515]]
## TOSS-UP  

text[[115, 528, 882, 569]]
8) CHEMISTRY - Multiple Choice Which of the following correctly describes the cause of the 21 centimeter line in the hydrogen spectrum?  

text[[115, 582, 549, 664]]
W) An allowed spin flip from a singlet to a triplet stateX) An allowed spin flip from a triplet to a singlet stateY) A forbidden spin flip from a singlet to a triplet stateZ) A forbidden spin flip from a triplet to a singlet state  

text[[115, 678, 825, 699]]
ANSWER: Z) A FORBIDDEN SPIN FLIP FROM A TRIPLET TO A SINGLET STATE  

sub_title[[462, 712, 533, 730]]
## BONUS  

text[[115, 744, 844, 785]]
8) CHEMISTRY - Short Answer A neutral vanadium based complex is created with three methyl ligands and a methylidene ligand. What is the overall electron count of the complex?  

text[[115, 798, 231, 816]]
ANSWER: 10text[[114, 88, 864, 171]]
9) ENERGY – Short Answer Scientists at the Pacific Northwest National Laboratory are studying biochemical metabolites by analyzing their collision cross-section when they are shot into gas. What group of lipid secondary metabolites formed by the condensation of acetyl-CoA are created by plants and fungi for the biosynthesis of compounds such as antimicrobials?  

text[[115, 184, 344, 202]]
ANSWER: POLYKETIDES  

sub_title[[424, 217, 573, 236]]
## VISUAL BONUS  

text[[114, 250, 880, 354]]
9) ENERGY – Short Answer Scientists at the National Renewable Energy Laboratory are researching the use of molybdenum disulfide sheets that are modified with substituted phenyl rings to catalyze hydrogen evolution. The scientists found that the hammett rho values of the phenyl rings influenced the catalyst's functionality. By number, identify all of the three reactions shown that display a negative hammett rho value.  

text[[115, 367, 282, 386]]
ANSWER: 2 AND 3  

sub_title[[455, 434, 541, 453]]
## TOSS-UP  

text[[115, 466, 841, 529]]
10) PHYSICS – Short Answer The measurement of the earth’s magnetic field by birds is a striking example of what effect of quantum mechanical systems in which the eigenstate of a particle may be arrested if measured frequently enough?  

text[[115, 542, 443, 561]]
ANSWER: QUANTUM ZENO EFFECT  

sub_title[[424, 575, 573, 594]]
## VISUAL BONUS  

text[[115, 607, 870, 648]]
10) PHYSICS – Short Answer Shown on the diagram is the Feynman [fine-man] diagram for a specific process. Answer the following two questions about this process.  

text[[129, 661, 802, 702]]
I. Identify both the particle labelled ‘A’ and the particle labelled ‘B’, respectively. 
II. The process shown violates a certain conserved quantity. What is this quantity?  

text[[115, 715, 717, 735]]
ANSWER: 1) A IS W- BOSON, B IS ELECTRON, 2) LEPTON NUMBER  

sub_title[[455, 770, 541, 788]]
## TOSS-UP  

text[[115, 802, 792, 822]]
11) MATH – Short Answer Find the greatest value of \(n\) such that \(5^n\) divides \(11^{25} - 1\) .  

text[[115, 836, 220, 853]]
ANSWER: 3  

sub_title[[462, 869, 533, 887]]
## BONUStext[[114, 88, 875, 131]]
11) MATH – Short Answer Evaluate the double integral of \(xy^2 dA\) over the rectangular region defined by \(0 \leq x \leq 2\) and \(0 \leq y \leq 1\) .  

text[[115, 146, 226, 164]]
ANSWER: \(\frac{2}{3}\)  

sub_title[[455, 212, 541, 231]]
## TOSS-UP  

text[[114, 244, 880, 285]]
12) BIOLOGY – Multiple Choice The Janus kinase or JAK-STAT signaling pathway is mostly responsible for which of the following  

text[[114, 299, 705, 319]]
W) Detection of hypophysiotropic hormones in the anterior pituitary gland  

text[[115, 321, 405, 339]]
X) Activation of the immune system  

text[[115, 342, 358, 360]]
Y) Inhibition of neural growth  

text[[115, 363, 425, 381]]
Z) Monitoring lung interstitial pressure  

text[[115, 394, 600, 414]]
ANSWER: X) ACTIVATION OF THE IMMUNE SYSTEM  

sub_title[[423, 428, 574, 447]]
## VISUAL BONUS  

text[[115, 460, 817, 522]]
12) BIOLOGY – Short Answer Shown in the image is the Wood-Ljungdahl pathway, an anabolic pathway within acetogens and methanogens that reduces carbon dioxide into acetyl-CoA. Answer the following three questions regarding this pathway:  

text[[123, 535, 877, 659]]
I. Based on the image, what is the electron donor in the first reduction of \(\mathrm{CO}_{2}\) to \(\mathrm{CO}_{2}\) II. The acetyl-CoA produced in this pathway can be converted to succinate, and furthermore carbohydrates via what other anabolic pathway that proceeds in specialized peroxisomes not present within animals? III. Unlike the reverse Krebs cycle, instead of requiring \(\mathrm{CO}_{2}\) and water, it requires \(\mathrm{CO}_{2}\) and what reducing agent to initiate the cycle?  

text[[115, 672, 721, 692]]
ANSWER: 1) HYDROGEN; 2) GLYOXYLATE CYCLE; 3) HYDROGEN.  

sub_title[[455, 739, 541, 758]]
## TOSS-UP  

text[[115, 774, 852, 816]]
13) EARTH AND SPACE – Multiple Choice Which of the following resonances causes the largest gap in asteroid concentration around Jupiter known as the Kirkwood gaps?  

text[[115, 830, 284, 870]]
W) 5:2 [five to two] X) 5:3 [five to three]text[[114, 89, 287, 130]]
Y) 3:2 [three to two] Z) 2:1 [two to one]  

text[[115, 143, 258, 162]]
ANSWER: Z) 2:1  

sub_title[[462, 177, 533, 195]]
## BONUS  

text[[115, 209, 877, 250]]
13) EARTH AND SPACE – Multiple Choice Which of the following is NOT correct about the kappa-mechanism in pulsating variable stars?  

text[[114, 263, 861, 365]]
W) The kappa-mechanism primarily occurs in a zone of partially ionized helium  X) In cool stars, the zone of partially ionized helium is too deep in the envelope for rebound to occur  Y) In non-pulsating stars, temperature and opacity typically have a negative relationship  Z) Doubly ionized helium is less opaque than singly ionized helium  

text[[115, 378, 860, 418]]
ANSWER: Z) DOUBLY IONIZED HELIUM IS LESS OPAQUE THAN SINGLY IONIZED HELIUM  

sub_title[[455, 467, 540, 485]]
## TOSS-UP  

text[[115, 499, 857, 583]]
14) CHEMISTRY – Short Answer Identify all of the following three statements that are true about azo coupling: 1) The diazonium salt must be activated for coupling to occur; 2) The HOMO of the reaction is the diazonium pi orbital; 3) The resulting configuration of the azo group is stereospecific.  

text[[115, 596, 265, 614]]
ANSWER: NONE  

sub_title[[462, 629, 533, 647]]
## BONUS  

text[[115, 661, 883, 765]]
14) CHEMISTRY – Short Answer Identify all of the following three statements that are true about the anomeric effect in substituted cyclohexane derivatives: 1) Polar solvents help strengthen the anomeric effect; 2) It is caused by greater stabilization from overlap of the nonbonding heteroatom orbital with the carbon substituent sigma star orbital; 3) Sulfur displays a weaker anomeric effect than oxygen when used as a heteroatom in cyclohexane derivatives.  

text[[115, 778, 279, 796]]
ANSWER: 2 ONLY  

sub_title[[455, 844, 540, 862]]
## TOSS-UPtext[[114, 88, 880, 234]]
15) ENERGY – Short Answer Scientists at Lawrence Berkeley National Lab have been detecting fermionic dark matter on the GeV scale via both the analysis of gravitational footprints and scattering experiments. They previously confirmed detection of certain astronomical bodies found in the spherical component of galaxies, that when passing in front of a star cause gravitational microlensing to occur. These astronomical bodies may explain the apparent detection of dark matter within rotation curves and is a leading dark matter candidate. What is the term for these astronomical objects?  

text[[113, 246, 881, 267]]
ANSWER: MACHOs (ACCEPT: MASSIVE ASTROPHYSICAL COMPACT HALO OBJECT)  

sub_title[[462, 280, 533, 299]]
## BONUS  

text[[114, 313, 880, 394]]
15) ENERGY – Short Answer Scientists at Pacific Northwest National Laboratory are studying the mechanisms of Parkinson’s disease and the resulting depletion of dopamine. One group of drugs used to treat Parkinson’s inhibit what enzyme responsible for the oxidation of dopamine in the brain?  

text[[114, 408, 576, 428]]
ANSWER: MAO (ACCEPT: MONOAMINE OXIDASE)  

sub_title[[455, 463, 541, 481]]
## TOSS-UP  

text[[114, 495, 878, 599]]
16) PHYSICS – Short Answer A stream of photons is directed at a charged particle resulting in the photons undergoing Compton scattering. A detector is placed at a certain angle away from the outgoing stream. Indicate all of the three following choices that would increase the wavelength shift: 1) Increasing detector angle; 2) Using a target with more mass; 3) Increasing the intensity of the photon stream.  

text[[115, 612, 280, 630]]
ANSWER: 1 ONLY  

sub_title[[462, 645, 533, 664]]
## BONUS  

text[[114, 678, 859, 719]]
16) PHYSICS – Multiple Choice Which of the following 2-dimensional electric fields would NOT have a well defined electric potential associated with it?  

text[[114, 732, 395, 816]]
W) \((4x)\mathbf{i} + (\mathbf{y})\mathbf{j}\) X) \(2\mathbf{i} + (9\mathbf{y})\mathbf{j}\) Y) \((\mathbf{y})\mathbf{i} - (\mathbf{x})\mathbf{j}\) Z) \((\sin (\mathbf{y})\cos (\mathbf{x}))\mathbf{i} + (\sin (\mathbf{x})\cos (\mathbf{y}))\mathbf{j}\)  

text[[115, 828, 312, 848]]
ANSWER: Y) \((\mathbf{y})\mathbf{i} - (\mathbf{x})\mathbf{j}\)sub_title[[455, 90, 540, 107]]
## TOSS-UP  

text[[115, 122, 855, 184]]
17) MATH - Short Answer Regular tetrahedron ABCD has side length 1. A plane intersects the tetrahedron at the midpoints of edges AD, AC, BD, and BC. What is the area of the cross section formed by the plane and the tetrahedron?  

text[[115, 198, 226, 215]]
ANSWER: 1/4  

sub_title[[423, 230, 572, 249]]
## VISUAL BONUS  

text[[115, 263, 868, 345]]
17) MATH - Short Answer Show in the image is the graph of a two-valued function along a certain interval of its domain. The point marked in red is a saddle point of the function. Identify whether each of the following two values, when evaluated at the point marked in red, are positive, negative, or zero.  

text[[130, 359, 483, 398]]
I. The magnitude of the gradient. 
II. The determinant of the Hessian matrix.  

text[[115, 412, 418, 431]]
ANSWER: 1) ZERO; 2) NEGATIVE.  

sub_title[[455, 479, 540, 497]]
## TOSS-UP  

text[[115, 511, 879, 594]]
18) BIOLOGY - Short Answer Your friend Daniel walks into the room complaining of a headache. You sit him down and realize that while he does not move, his eyes are uncontrollably darting around as if his vestibular apparatus is being stimulated. What term is given to these uncontrollable movements?  

text[[115, 607, 333, 625]]
ANSWER: NYSTAGMUS  

sub_title[[461, 641, 533, 659]]
## BONUS  

text[[115, 673, 868, 755]]
18) BIOLOGY - Short Answer Some people are born with situs inversus, the inversion of the body positions of the organs. They are often characterized by the lack of primary cilia, which is implicated in the migration of organs. What term is given to the disease characterized by this lack of cilia?  

text[[115, 769, 840, 809]]
ANSWER: KARTAGENER'S DISEASE (ACCEPT: PRIMARY CILIARY DYSKINESIA AND IMMOTILE CILIARY SYNDROME)  

sub_title[[455, 856, 540, 874]]
## TOSS UPtext[[114, 88, 870, 171]]
19) EARTH AND SPACE - Short Answer Give, by name or number, all of the following three statements which are true concerning blazars: 1) They appear brighter due to high relativistic beaming; 2) Superluminal motion can be observed from blazars; 3) They are found at the center of elliptical galaxies.  

text[[115, 185, 249, 202]]
ANSWER: ALL  

sub_title[[462, 217, 533, 236]]
## BONUS  

text[[114, 250, 880, 353]]
19) EARTH AND SPACE – Short Answer By name or number, identify all the following that are true about cratons: 1) Platforms are outcrops of exposed Precambrian igneous and high-grade metamorphic rocks; 2) Shields are platforms that are covered by relatively thin layer of sedimentary strata; 3) When tectonic forces restart in a craton, epiregony [ep-ai-roj-UH-nee] forms new domes and basins.  

text[[115, 367, 265, 385]]
ANSWER: NONE  

sub_title[[455, 433, 541, 451]]
## TOSS-UP  

text[[114, 465, 850, 549]]
20) CHEMISTRY – Multiple Choice Tris(2,2'-bipyridyl) ruthenium (II) is a brightly colored orange compound, which is a versatile photochemical redox reagent. What type of transition metal electronic transition is most likely responsible for its color due to the low reduction potential of the ruthenium metal center?  

text[[114, 563, 393, 643]]
W) \(d\) to \(d\) transition 
X) Ligand-to-metal charge transfer 
Y) Metal-to-ligand charge transfer 
Z) \(\pi\) to \(\pi\) star transition  

text[[114, 657, 609, 676]]
ANSWER: Y) METAL-TO-LIGAND CHARGE TRANSFER  

sub_title[[423, 691, 574, 710]]
## VISUAL BONUS  

text[[114, 724, 861, 765]]
20) CHEMISTRY – Short Answer Shown in the image is a wavefunction of a 2-dimensional square potential well. Answer the following three questions regarding the image:  

text[[123, 778, 881, 858]]
I. How many nodal planes does this wavefunction possess? II. What are the values of the quantum numbers in the \(x\) and \(y\) directions, respectively? III. What is the probability of finding an electron at \(x\) and \(y\) coordinates where \(x < 0.5\) and \(y < 0.5\) ?  

text[[115, 875, 350, 893]]
ANSWER: 1) 6; 2) 4, 4; 3) \(\frac{1}{4}\)sub_title[[455, 110, 540, 128]]
## TOSS-UP  

text[[114, 142, 875, 225]]
21) ENERGY - Short Answer Scientists at Oak Ridge National Laboratory are studying macromolecular nanophase science. Rather than traditional mass spectrometry that allows the molecules themselves to absorb the energy of the laser source, they utilized an energy absorbing matrix to reduce fragmentation of biomolecules. What is this type of mass spectrometry called?  

text[[115, 238, 731, 278]]
ANSWER: MALDI (ACCEPT: MALDI- TOF, MATRIX ASSISTED LASER DESORPTION/IONIZATION)  

sub_title[[462, 280, 533, 298]]
## BONUS  

text[[115, 313, 856, 374]]
21) ENERGY - Short Answer Researchers at Sandia National Laboratory studied various promising methods of hydrogen storage, including nickel metal hydrides. What is the average bond order of each nickel hydrogen bond in the tetrahedral complex \(\mathrm{NiH_4^{4 - }}\) ?  

text[[115, 388, 237, 406]]
ANSWER: 1/4  

sub_title[[455, 455, 540, 473]]
## TOSS-UP  

text[[115, 487, 880, 548]]
22) PHYSICS - Short Answer What interpretation of quantum mechanics results in the same effects as probabilistic interpretations yet suggests that an actual configuration of the particle and its guiding equation exists which evolves deterministically over time?  

text[[115, 561, 787, 581]]
ANSWER: DE BROGLIE- BOHM INTERPRETATION (ACCEPT: PILOT WAVE)  

sub_title[[423, 595, 573, 614]]
## VISUAL BONUS  

text[[115, 628, 875, 668]]
22) PHYSICS - Short Answer The diagram depicts a P-N junction. Answer the following three questions:  

text[[125, 682, 840, 765]]
I. The graphs A-C correspond to voltage, net charge density, electric field. Match each variable to its corresponding graph.  
II. Identify the region D.  
III. What is the term for the quasiparticle consisting of a combined electron and hole?  

text[[115, 778, 841, 818]]
ANSWER: 1) A IS CHARGE, B IS ELECTRIC FIELD, C IS VOLTAGE; 2) DEPLETION REGION (ACCEPT SPACE CHARGE REGION); 3) EXCITON.  

sub_title[[455, 865, 540, 883]]
## TOSS-UPtext[[115, 89, 840, 128]]
23) MATH – Short Answer What is the sum of the magnitudes of the roots to the equation \(x^4 + x^2 + 1 = 0\) .  

text[[115, 145, 222, 163]]
ANSWER: 4  

sub_title[[462, 179, 533, 198]]
## BONUS  

text[[115, 212, 861, 272]]
23) MATH – Short Answer There are six points in a plane, no four of which are collinear. A line is formed between every pair of points. What is the minimum number of distinct lines that can be formed?  

text[[115, 286, 221, 304]]
ANSWER: 7  

sub_title[[455, 352, 540, 370]]
## TOSS-UP  

text[[115, 384, 872, 425]]
24) BIOLOGY – Short Answer Gastric inhibitory peptide belongs to what group of hormones that function to provide a feedforward for insulin secretion?  

text[[115, 439, 314, 457]]
ANSWER: INCRETINS  

sub_title[[423, 473, 573, 491]]
## VISUAL BONUS  

text[[113, 505, 812, 525]]
24) BIOLOGY – Short Answer Answer the following three questions about the image:  

text[[125, 538, 872, 600]]
I. What is the rate-limiting enzyme marked by 1?  
II. What general class of drugs inhibit enzyme 1?  
III. What is the compound marked by 2 from which all steroids and terpenes originate from?  

text[[115, 613, 850, 653]]
ANSWER: 1) HMG-CoA REDUCTASE; 2) STATINS; 3) MEVALONIC ACID (ACCEPT: MEVALONATE)  

sub_title[[455, 699, 540, 718]]
## TOSS-UP  

text[[115, 732, 875, 773]]
25) EARTH AND SPACE – Multiple Choice Which of the following is NOT in the assemblage for greenschist facie rocks with an ultramafic parent?  

text[[115, 787, 228, 867]]
W) Chlorite  
X) Serpentine  
Y) Tremolite  
Z) Albitetext[[115, 90, 303, 108]]
ANSWER: Z) ALBITE  

sub_title[[423, 122, 572, 141]]
## VISUAL BONUS  

text[[115, 155, 880, 237]]
25) EARTH AND SPACE – Short Answer Depicted in the image is a series of spectral lines and their strength against temperature. Using the labeled letters of the curves, match each of the following four spectra with their spectral lines: 1) Titanium oxide; 2) Ionized iron; 3) Helium; 4) Ionized helium.  

text[[115, 250, 446, 270]]
ANSWER: 1 IS F; 2 IS D; 3 IS B; 4 IS A.