sub_title[[115, 90, 201, 108]]
## TOSS-UP  

text[[115, 125, 843, 167]]
1) EARTH AND SPACE – Multiple Choice S0 [S-Zero] designates which of the following types of galaxies?  

text[[115, 181, 225, 260]]
W) Spiral 
X) Lenticular 
Y) Irregular 
Z) Elliptical  

text[[115, 276, 360, 294]]
ANSWER: X) LENTICULAR  

sub_title[[462, 309, 533, 327]]
## BONUS  

text[[115, 342, 881, 382]]
1) EARTH AND SPACE – Short Answer The ancient Farallon plate split into what three plates when it partially subducted under the North American plate?  

text[[115, 396, 550, 415]]
ANSWER: JUAN DE FUCA, COCOS, AND NAZCA  

sub_title[[455, 461, 540, 480]]
## TOSS-UP  

text[[113, 494, 880, 514]]
2) CHEMISTRY – Short Answer What is the angular momentum of an electron in a 4s orbital?  

text[[115, 528, 222, 546]]
ANSWER: 0  

sub_title[[462, 562, 533, 580]]
## BONUS  

text[[115, 594, 881, 635]]
2) CHEMISTRY – Multiple Choice Which of the following is the most stable conformation for trans 1-chloro-3-tert butyl cyclohexane?  

text[[115, 657, 465, 738]]
W) Chlorine equatorial, tert-butyl equatorial 
X) Chlorine equatorial, tert-butyl axial 
Y) Chlorine axial, tert-butyl equatorial 
Z) Chlorine axial, tert-butyl axial  

text[[115, 752, 662, 771]]
ANSWER: Y) CHLORINE AXIAL, TERT-BUTYL EQUATORIALsub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[114, 122, 880, 184]]
3) ENERGY – Short Answer Researchers at Lawrence Berkeley National Laboratory are trying to find new oxide materials to replace silicon in computer chips. The researchers are trying to increase the packing efficiency of what semiconductor based circuit component?  

text[[115, 197, 343, 215]]
ANSWER: TRANSISTORS  

sub_title[[462, 230, 533, 249]]
## BONUS  

text[[114, 263, 878, 325]]
3) ENERGY – Multiple Choice Scientists at the Pacific Northwest National Laboratory are currently studying the effects of ocean currents on nutrient levels along coast lines. Which of the following best explains why downwelling increases along the Oregon coast during the winter?  

text[[114, 338, 755, 420]]
W) Northerly winds strengthen, leading to increased movement of water onshore  X) Southerly winds strengthen, leading to increased movement of water onshore  Y) Northerly winds weaken, leading to increased movement of water offshore  Z) Southerly winds weaken, leading to increased movement of water offshore  

text[[114, 433, 787, 473]]
ANSWER: X) SOUTHERN WINDS STRENGTHEN, LEADING TO INCREASED MOVEMENT OF WATER ONSHORE  

sub_title[[456, 508, 540, 527]]
## TOSS-UP  

text[[114, 541, 881, 581]]
4) PHYSICS – Short Answer What is the ratio of the work done when accelerating a mass from \(1 \mathrm{~m / s}\) to \(3 \mathrm{~m / s}\) to the work done when accelerating it from \(3 \mathrm{~m / s}\) to \(5 \mathrm{~m / s}\) ?  

text[[115, 594, 236, 612]]
ANSWER: 1:2  

sub_title[[462, 628, 533, 647]]
## BONUS  

text[[114, 661, 872, 744]]
4) PHYSICS – Short Answer A pipe filled with water decreases in elevation by 10 meters, but does not change in the velocity of water in the pipe. If the initial pressure inside the pipe is 3 times \(10^{5}\) pascals, what is the pressure of the pipe at the decreased elevation in pascals? The density of water is 1000 kilograms per cubic meter and g equals 10 meters per second squared.  

text[[115, 758, 256, 776]]
ANSWER: \(4*10^{5}\)  

sub_title[[456, 824, 540, 842]]
## TOSS-UPtext[[113, 89, 832, 130]]
5) MATH – Short Answer A rectangle has dimensions of 6 by 12. What is the area of the largest triangle that can be entirely contained within the rectangle?  

text[[115, 143, 231, 161]]
ANSWER: 36  

sub_title[[462, 176, 533, 195]]
## BONUS  

text[[115, 209, 875, 250]]
5) MATH – Short Answer How many real numbers must be selected on the open interval from 0 to 5 to guarantee that a pair of them differ by less than 1?  

text[[115, 263, 221, 281]]
ANSWER: 6  

sub_title[[454, 317, 540, 335]]
## TOSS-UP  

text[[115, 350, 838, 411]]
6) BIOLOGY – Short Answer During neurulation, what group of cells bordering where the neural tube pinches off from the ectoderm migrate off to form teeth, cranial bones, and peripheral nerves?  

text[[115, 424, 355, 443]]
ANSWER: NEURAL CREST  

sub_title[[462, 459, 533, 477]]
## BONUS  

text[[115, 491, 872, 532]]
6) BIOLOGY – Multiple Choice Which of the following groups of animals is not a lepidosaur [lep-E-do-saur]?  

text[[115, 546, 240, 625]]
W) Tuataras 
X) Lizards 
Y) Snakes 
Z) Crocodilians  

text[[115, 640, 380, 658]]
ANSWER: Z) CROCODILIANS  

sub_title[[454, 707, 540, 725]]
## TOSS-UP  

text[[115, 740, 835, 780]]
7) EARTH AND SPACE – Multiple Choice Which of the following types of magma flow would most likely be present at a mid-ocean ridge?  

text[[115, 794, 375, 875]]
W) Aa flow [Ah-Ah] 
X) Pahoehoe flow [Pa-hoy-hoy] 
Y) Block flow 
Z) Pillow flowtext[[115, 90, 347, 108]]
Answer: Z) PILLOW FLOW  

sub_title[[462, 123, 533, 140]]
## BONUS  

text[[115, 155, 861, 196]]
7) EARTH AND SPACE – Short Answer By name or number, identify all the following three geological features that are caused by normal faults: 1) Scarps; 2) Horsts; 3) Hogbacks  

text[[115, 209, 565, 228]]
Answer: 1 AND 2 (ACCEPT: SCARPS AND HORSTS)  

sub_title[[455, 275, 541, 294]]
## TOSS-UP  

text[[115, 308, 861, 349]]
8) CHEMISTRY – Short Answer For a first order reaction, if the half life is 1 second, what is the rate constant of the reaction to 1 significant figure and in inverse seconds?  

text[[115, 362, 235, 380]]
ANSWER: 0.7  

sub_title[[462, 396, 533, 414]]
## BONUS  

text[[115, 428, 863, 491]]
8) CHEMISTRY – Short Answer Identify all of the following three statements that are true about diboron: 1) It is diamagnetic; 2) It has a bond order of 1; 3) The highest filled orbital is a \(\sigma_{2p}\) [sigma 2p] orbital  

text[[115, 506, 280, 525]]
ANSWER: 2 ONLY  

sub_title[[455, 572, 541, 590]]
## TOSS-UP  

text[[115, 604, 876, 688]]
9) ENERGY – Short Answer Scientists at Lawrence Berkeley National Laboratory are using x-ray crystallography to image the molecular structure of Ddn, a tuberculosis bacterium enzyme. One of the reasons why tuberculosis is so deadly is that it blocks the fusion of phagosomes and lysosomes within macrophages from fusing into what structure?  

text[[115, 701, 384, 720]]
ANSWER: PHAGOLYSOSOME  

sub_title[[462, 735, 533, 753]]
## BONUS  

text[[115, 767, 864, 829]]
9) ENERGY – Multiple Choice Scientists at the National Renewable Energy Lab are leading efforts to commercialize perovskite solar cells. Which of the following is NOT one of the most important qualities in commercial solar cells?  

text[[115, 843, 266, 903]]
W) Low toxicity 
X) Low cost 
Y) High efficiencytext[[115, 90, 248, 108]]
Z) High stability  

text[[115, 122, 383, 141]]
ANSWER: W) LOW TOXICITY  

sub_title[[455, 188, 540, 207]]
## TOSS-UP  

text[[115, 221, 861, 281]]
10) PHYSICS – Short Answer A ball is dropped from a tall building and falls d meters in the first 3 seconds of free fall. In terms of d, how many meters will the ball fall in the next 6 seconds?  

text[[115, 295, 232, 314]]
ANSWER: 8d  

sub_title[[462, 330, 533, 349]]
## BONUS  

text[[115, 362, 850, 423]]
10) PHYSICS – Short Answer Identify all of the following three types of magnetism which would display negative magnetic susceptibility: 1) Ferromagnetism; 2) Paramagnetism; 3) Diamagnetism.  

text[[115, 436, 280, 455]]
ANSWER: 3 ONLY  

sub_title[[455, 491, 540, 510]]
## TOSS-UP  

text[[115, 523, 883, 605]]
11) MATH – Multiple Choice A sample of 200 voters are surveyed to estimate the proportion voting for a certain candidate in the upcoming election. If the polling company wishes to cut the margin of error of their estimated proportion in half in a second poll, how many voters should the company aim to sample?  

text[[115, 619, 173, 699]]
W) 50 
X) 100 
Y) 400 
Z) 800  

text[[115, 715, 264, 733]]
ANSWER: Z) 800  

sub_title[[462, 750, 533, 768]]
## BONUS  

text[[115, 781, 835, 822]]
11) MATH – Short Answer For what value of \(k\) is the polynomial \(x^4 - kx^2 - 2x - 1\) evenly divisible by \(x + 1\) ?  

text[[115, 836, 221, 854]]
ANSWER: 2sub_title[[455, 90, 540, 108]]
## TOSS-UP  

text[[115, 122, 800, 163]]
12) BIOLOGY - Multiple Choice Which of the following quantities are the two main determinants of island species diversity according to the island equilibrium model?  

text[[115, 176, 628, 260]]
W) Island succession level and disturbance level  X) Island climate and topography  Y) Island size and distance from the mainland  Z) Island net primary productivity and number of realized niches  

text[[115, 272, 720, 292]]
ANSWER: Y) ISLAND SIZE AND DISTANCE FROM THE MAINLAND  

sub_title[[462, 306, 533, 324]]
## BONUS  

text[[115, 338, 844, 400]]
12) BIOLOGY - Short Answer During protein folding, the hydrophobic core forms to minimize the size of the solvation shell. What thermodynamic quantity is maximized by this process?  

text[[115, 412, 301, 431]]
ANSWER: ENTROPY  

sub_title[[455, 479, 540, 497]]
## TOSS-UP  

text[[115, 511, 870, 552]]
13) EARTH AND SPACE - Multiple Choice Which of the following planets has a retrograde rotation?  

text[[115, 566, 216, 647]]
W) Mercury  X) Mars  Y) Uranus  Z) Neptune  

text[[115, 661, 318, 680]]
ANSWER: Y) URANUS  

sub_title[[462, 695, 533, 713]]
## BONUS  

text[[115, 728, 880, 768]]
13) EARTH AND SPACE - Short Answer What is the zig-zag transport of beach sediment due to angled wave-refracted swash and backwash called?  

text[[115, 781, 702, 801]]
ANSWER: BEACH DRIFT (DO NOT ACCEPT: LONGSHORE DRIFT)  

sub_title[[455, 848, 540, 866]]
## TOSS-UPtext[[112, 88, 879, 110]]
14) CHEMISTRY – Multiple Choice Which of the following acids has the lowest pKa [p-k-a]?  

text[[114, 131, 282, 212]]
W) Acetic acid  
X) Fluoroacetic acid  
Y) Chloroacetic acid  
Z) Bromoacetic acid  

text[[115, 226, 440, 245]]
ANSWER: X) FLUOROACETIC ACID  

sub_title[[462, 259, 533, 278]]
## BONUS  

text[[115, 291, 877, 353]]
14) CHEMISTRY – Short Answer What stabilizing effect explains the increased stability of more substituted alkenes by accounting for the donation of electron density from alkyl groups to the alkene pi star orbital?  

text[[115, 367, 414, 386]]
ANSWER: HYPERCONJUGATION  

sub_title[[456, 433, 541, 451]]
## TOSS-UP  

text[[115, 465, 882, 549]]
15) ENERGY – Short Answer Scientists at Lawrence Berkeley National Laboratory are using computers to model the interactions among river water and groundwater. One part they are trying to model is the vadose [VAY-dose] and phreatic zone. What is the boundary between the vadose and phreatic zone called?  

text[[115, 562, 350, 580]]
ANSWER: WATER TABLE  

sub_title[[462, 595, 533, 614]]
## BONUS  

text[[115, 628, 861, 710]]
15) ENERGY – Short Answer Researchers at Ames National Laboratory have been studying the effects of cholinesterase on histidine negative Salmonella mutants to discover the carcinogenicity of cholinesterase. To perform this, they used which namesake test to detect mutations in the Salmonella mutants?  

text[[115, 723, 316, 742]]
ANSWER: AMES TEST  

sub_title[[456, 778, 540, 796]]
## TOSS-UP  

text[[115, 810, 882, 851]]
16) PHYSICS – Multiple Choice Identify all of the following three dopants that can be used for silicon to create an n type semiconductor: 1) Germanium; 2) Gallium; 3) Arsenic.  

text[[115, 865, 280, 883]]
ANSWER: 3 ONLYsub_title[[462, 90, 533, 108]]
## BONUS  

text[[115, 122, 825, 163]]
16) PHYSICS – Multiple Choice The hydrogen 21 cm line arises from a change in what quantum number of an electron?  

text[[115, 176, 358, 260]]
W) Principal quantum number 
X) Orbital quantum number 
Y) Magnetic quantum number 
Z) Spin quantum number  

text[[115, 272, 470, 291]]
ANSWER: Z) SPIN QUANTUM NUMBER  

sub_title[[455, 338, 541, 356]]
## TOSS-UP  

text[[115, 370, 844, 410]]
17) MATH – Short Answer Determine the number of factors of \(2020^{2}\) that are multiples of 2020.  

text[[115, 424, 231, 443]]
ANSWER: 12  

sub_title[[462, 459, 533, 477]]
## BONUS  

text[[115, 491, 869, 532]]
17) MATH – Short Answer Three sides of a quadrilateral have lengths 1, 5, and 7. How many possible integer lengths are there for the fourth side?  

text[[115, 545, 230, 564]]
ANSWER: 11  

sub_title[[455, 610, 541, 629]]
## TOSS-UP  

text[[115, 643, 875, 664]]
18) BIOLOGY – Multiple Choice Which of the following is a characteristic of deuterostomes?  

text[[115, 678, 335, 760]]
W) Indeterminate cleavage 
X) Blastopore forms mouth 
Y) Spiral cleavage 
Z) Radial symmetry  

text[[115, 773, 512, 792]]
ANSWER: W) INDETERMINATE CLEAVAGE  

sub_title[[462, 807, 533, 825]]
## BONUS  

text[[115, 839, 830, 880]]
18) BIOLOGY – Short Answer Which lobe of the brain is responsible for somatosensory processing?sub_title[[455, 143, 541, 162]]
## TOSS-UP  

text[[115, 175, 861, 216]]
19) EARTH AND SPACE – Short Answer What is the area from 104 to 140 degrees from an earthquake that receives little to no P-waves called?  

text[[115, 229, 682, 249]]
ANSWER: P-WAVE SHADOW ZONE (ACCEPT: SHADOW ZONE)  

sub_title[[462, 263, 533, 281]]
## BONUS  

text[[115, 295, 870, 336]]
19) EARTH AND SPACE – Short Answer During what geologic period did angiosperms first appear and proceed to dominate the floral landscape?  

text[[115, 350, 340, 368]]
ANSWER: CRETACEOUS  

sub_title[[455, 416, 540, 435]]
## TOSS-UP  

text[[115, 448, 879, 490]]
20) CHEMISTRY – Short Answer Identify all of the following three phases of matter that have an activity of 1: 1) Solid; 2) Liquid; 3) Gas.  

text[[115, 503, 283, 521]]
ANSWER: 1 AND 2  

sub_title[[462, 537, 533, 556]]
## BONUS  

text[[115, 569, 863, 652]]
20) CHEMISTRY – Short Answer Identify all of the following three statements that are true about iodometric titrations: 1) They are an example of a redox titration; 2) Thiosulfate can be employed to reduce triiodide to iodide; 3) Silver ions are used to form a yellow precipitate that determines the endpoint.  

text[[115, 666, 283, 684]]
ANSWER: 1 AND 2  

sub_title[[455, 719, 540, 737]]
## TOSS-UP  

text[[115, 751, 863, 813]]
21) ENERGY – Multiple Choice Scientists at Los Alamos National Laboratory are studying the use of aerogels for space missions. Aerogels are gels in which the liquid component for the gel has been replaced with a gas. Which of the following is NOT true about aerogels?  

text[[115, 836, 365, 875]]
W) They are desiccants 
X) They have high surface areatext[[114, 90, 403, 130]]
Y) They are good thermal insulatorsZ) They are hydrophobic  

text[[114, 143, 480, 162]]
ANSWER: Z) THEY ARE HYDROPHOBIC  

sub_title[[462, 177, 533, 195]]
## BONUS  

text[[114, 210, 853, 270]]
21) ENERGY – Short Answer Scientists at Brookhaven National Laboratory are using 2D silicate frameworks to trap noble gases. These porous sheets can assemble to form 3D silicate nanocages, such as what group of microporous aluminosilicate minerals?  

text[[115, 284, 302, 302]]
ANSWER: ZEOLITES  

sub_title[[456, 351, 540, 369]]
## TOSS-UP  

text[[114, 383, 880, 444]]
22) PHYSICS – Short Answer A pipe closed at one end and open at the other end has a fundamental frequency of 50 Hz. Identify all of the following three frequencies at which the pipe resonates: 1) 100 Hz; 2) 150 Hz; 3) 200 Hz  

text[[115, 458, 280, 476]]
ANSWER: 2 ONLY  

sub_title[[462, 492, 533, 510]]
## BONUS  

text[[114, 524, 880, 584]]
22) PHYSICS – Multiple Choice A monatomic ideal gas is expanded adiabatically such that its pressure decreases by a factor of 2. Which of the following describes the change in temperature of the gas?  

text[[114, 599, 470, 675]]
W) Decreases by a factor of between 1 and 2  
X) Decreases by a factor of greater than 2  
Y) Increases by a factor of between 1 and 2  
Z) Increases by a factor of greater than 2  

text[[114, 688, 692, 707]]
ANSWER: W) DECREASES BY A FACTOR OF BETWEEN 1 AND 2  

sub_title[[456, 754, 540, 772]]
## TOSS-UP  

text[[113, 787, 852, 806]]
23) MATH – Short Answer Determine the product of the complex numbers \(1 - i\) and \(2 + 2i\) .  

text[[115, 821, 221, 838]]
ANSWER: 4  

sub_title[[462, 841, 533, 858]]
## BONUStext[[113, 88, 852, 156]]
23) MATH - Short Answer Evaluate \(\int_{-1}^{0} x \sqrt{x + 1} \, dx\) [the integral from -1 to 0 of x times the square root of the quantity x plus 1, dx].  

text[[115, 167, 256, 186]]
ANSWER: - 4/15  

sub_title[[455, 232, 541, 251]]
## TOSS-UP  

text[[113, 264, 880, 327]]
24) BIOLOGY - Multiple Choice Which of the following diseases occurs when antibodies bind to receptors for TSH, perpetually activating them, leading to excessive hunger, heat sensitivity, and tachycardia?  

text[[113, 340, 306, 422]]
W) Graves' disease 
X) Hashimoto's disease 
Y) Addison's disease 
Z) Cushing's disease  

text[[115, 435, 412, 455]]
ANSWER: W) GRAVES' DISEASE  

sub_title[[462, 469, 533, 488]]
## BONUS  

text[[113, 500, 853, 563]]
24) BIOLOGY - Short Answer During DNA replication in E. coli, what group of proteins is responsible for maintaining the separation between the two strands after helicase cleaves the helix?  

text[[113, 576, 700, 597]]
ANSWER: SINGLE STRAND BINDING PROTEINS (ACCEPT: SSBP)  

sub_title[[455, 643, 541, 661]]
## TOSS-UP  

text[[113, 675, 863, 716]]
25) EARTH AND SPACE - Multiple Choice Which of the following ores is correctly paired with its respective metal?  

text[[113, 730, 303, 813]]
W) Galena, germanium 
X) Sphalerite, titanium 
Y) Cinnabar, mercury 
Z) Chalcopyrite, iron  

text[[113, 825, 446, 845]]
ANSWER: Y) CINNABAR, MERCURY  

sub_title[[462, 860, 533, 878]]
## BONUStext[[113, 88, 868, 129]]
25) EARTH AND SPACE – Short Answer What nearly vertical portion of the HR diagram contains different groups of variable stars as they move rightward and leftward on the diagram?  

text[[115, 143, 392, 161]]
ANSWER: INSTABILITY STRIP