sub_title[[455, 90, 541, 108]]
## TOSS-UP  

text[[115, 125, 879, 166]]
1) CHEMISTRY – Short Answer How many electrons are in the 3d subshell for the ground state electron configuration of copper? 1  

text[[115, 180, 231, 198]]
ANSWER: 10  

sub_title[[462, 214, 533, 232]]
## BONUS  

text[[115, 246, 860, 286]]
1) CHEMISTRY – Short Answer What is the ratio of the rate of effusion of sulfur dioxide at 150 kelvin to the rate of effusion of methane at 600 kelvin?  

text[[115, 300, 226, 318]]
ANSWER: ¼  

sub_title[[455, 366, 541, 384]]
## TOSS-UP  

text[[115, 399, 878, 461]]
2) PHYSICS – Short Answer A transformer has a primary winding of 90 turns and a secondary winding of 18 turns. The transformer is then connected to a voltage source of 100 volts. How many volts are passed through the secondary winding?  

text[[115, 475, 231, 492]]
ANSWER: 20  

sub_title[[462, 508, 533, 526]]
## BONUS  

text[[115, 541, 842, 580]]
2) PHYSICS – Short Answer What is the moment of inertia of a solid 5 kilogram disk with radius 2 meters about an axis at the disk edge parallel to its central axis?  

text[[115, 594, 231, 612]]
ANSWER: 30  

sub_title[[455, 660, 541, 678]]
## TOSS-UP  

text[[115, 693, 881, 733]]
3) BIOLOGY – Short Answer Named for its weight in kilodaltons. which tumor suppressor gene often considered the guardian angel of the genome is crucial to the prevention of cancer?  

text[[115, 747, 241, 765]]
ANSWER: P53  

sub_title[[462, 782, 533, 799]]
## BONUS  

text[[115, 814, 864, 875]]
3) BIOLOGY – Short Answer By name or number, give the respective epithelial cell types to the following three organs. Give both the layering and shape: 1) Inner portion of the mouth; 2) Villi of the Small intestine; 3) Kidney tubules.sub_title[[455, 156, 540, 174]]
## TOSS-UP  

text[[114, 189, 874, 270]]
4) ENERGY - Multiple Choice Scientists at Argonne National Laboratory have discovered a technique to significantly improve the accuracy of the measurement of inorganic isotopes. What specific type of spectroscopy did the scientists build upon, which measures the mass to charge ratio of various fragments produced during the experiment?  

text[[114, 285, 512, 366]]
W) Mass spectrometryX) Nuclear magnetic resonance spectroscopyY) Infrared spectroscopyZ) Electron paramagnetic resonance spectroscopy  

text[[115, 379, 451, 398]]
ANSWER: W) MASS SPECTROMETRY  

sub_title[[462, 413, 533, 431]]
## BONUS  

text[[114, 446, 880, 528]]
4) ENERGY - Short Answer Scientists at Brookhaven national laboratory used X-ray diffraction to probe the source of thermodynamic instability in \(\mathrm{CsPbI}_3\) , and discovered that it is due to distortions of cesium within the crystal structure. \(\mathrm{CsPbI}_3\) belongs to what general group of minerals and unit cells with general formula \(\mathrm{ABX}_3\) ?  

text[[115, 542, 343, 560]]
ANSWER: PEROVSKITES  

sub_title[[455, 607, 540, 625]]
## TOSS-UP  

text[[114, 641, 875, 681]]
5) EARTH AND SPACE - Short Answer What is the main nucleosynthesis pathway by which stars greater than 1.3 solar masses fuse hydrogen?  

text[[115, 695, 322, 713]]
ANSWER: CNO CYCLE  

sub_title[[462, 728, 533, 746]]
## BONUS  

text[[114, 761, 850, 801]]
5) EARTH AND SPACE - Multiple Choice Which of the following phenomena is NOT an indicator of star formation?  

text[[114, 816, 313, 854]]
W) Bok globulesX) Star-formation pillarstext[[114, 90, 309, 129]]
Y) Herbig-Haro objectsZ) Apollo-Amor objects  

text[[114, 142, 465, 161]]
ANSWER: Z) APOLLO- AMOR OBJECTS  

sub_title[[455, 197, 541, 215]]
## TOSS-UP  

text[[114, 230, 870, 270]]
6) MATH - Short Answer What is the limit as x approaches 0 of the function f of x equals the fraction with numerator \(2x + 5\) and denominator \(3x^{2}\) ?  

text[[114, 284, 295, 302]]
ANSWER: INFINITY  

sub_title[[461, 318, 533, 336]]
## BONUS  

text[[114, 350, 810, 391]]
6) MATH - Short Answer A circle has equation \(x^{2} + y^{2} - 6x + 4y - 1 = 0\) . What are the coordinates of the center of the circle and the radius of the circle, respectively?  

text[[114, 404, 333, 424]]
ANSWER: (3, - 2); sqrt(14)  

sub_title[[455, 470, 541, 488]]
## TOSS-UP  

text[[114, 503, 836, 544]]
7) CHEMISTRY - Multiple Choice Which of the following elements has the highest first ionization energy?  

text[[114, 558, 245, 639]]
W) Carbon 
X) Silicon 
Y) Nitrogen 
Z) Phosphorous  

text[[114, 653, 337, 671]]
ANSWER: Y) NITROGEN  

sub_title[[461, 687, 533, 705]]
## BONUS  

text[[114, 720, 852, 760]]
7) CHEMISTRY - Short Answer What functional group is produced by the transition metal catalyzed addition of hydrogen to an alkene?  

text[[114, 774, 291, 792]]
ANSWER: ALKANE  

sub_title[[455, 840, 541, 857]]
## TOSS-UPtext[[113, 88, 870, 130]]
8) PHYSICS – Short Answer Identify all of the following three particles that are fermionic: 1) Electron; 2) Photon; 3) Gluon.  

text[[115, 143, 280, 162]]
ANSWER: 1 ONLY  

sub_title[[462, 176, 533, 195]]
## BONUS  

text[[115, 209, 877, 291]]
8) PHYSICS – Short Answer A heat engine operates between a cold reservoir with a temperature of 150 kelvin and a hot reservoir. When the temperature of the hot reservoir is doubled, the efficiency of the engine increases by 50%. What is the initial temperature of the hot reservoir in kelvin?  

text[[115, 305, 241, 323]]
ANSWER: 300  

sub_title[[455, 370, 540, 389]]
## TOSS-UP  

text[[115, 403, 878, 465]]
9) BIOLOGY – Multiple Choice Judson uses restriction fragment length polymorphism analysis to run a paternity test in a court case involving a mother and her two children David and Gideon. RFLP involves which of the following processes?  

text[[115, 479, 312, 560]]
W) Mass spectrometry 
X) Shotgun sequencing 
Y) Reverse transcription 
Z) Gel electrophoresis  

text[[115, 574, 459, 594]]
ANSWER: Z) GEL ELECTROPHORESIS  

sub_title[[462, 608, 533, 626]]
## BONUS  

text[[115, 640, 810, 681]]
9) BIOLOGY – Short Answer What functional group is added to toxins by the smooth endoplasmic reticulum so that they become soluble enough to leave through urine?  

text[[115, 694, 518, 714]]
ANSWER: HYDROXYL (ACCEPT: ALCOHOL)  

sub_title[[455, 761, 540, 780]]
## TOSS-UP  

text[[115, 793, 859, 856]]
10) ENERGY – Short Answer Scientists at Fermi National Laboratory are using the Dark Energy Spectroscopic Instrument, or DESI, to measure the redshift of millions of galaxies and quasars. What constant of proportionality relates the redshift to the distance of a galaxy?  

text[[115, 869, 416, 888]]
ANSWER: HUBBLE'S CONSTANTsub_title[[462, 90, 533, 108]]
## BONUS  

text[[114, 122, 879, 203]]
10) ENERGY - Short Answer Scientists at Lawrence Livermore National Laboratory are studying human genomics. When using DNA fingerprinting to identify people, what genetic sequences are typically studied to differentiate between individuals, owing to their high mutation rate?  

text[[114, 217, 736, 237]]
ANSWER: SHORT TANDEM REPEATS (ACCEPT: MICROSATELLITES)  

sub_title[[455, 272, 540, 291]]
## TOSS-UP  

text[[114, 304, 861, 365]]
11) EARTH AND SPACE - Short Answer When a river's meander grows too large, the river cuts through the land between the necks of the meander, leaving behind a standing body of water. What is this body of water called?  

text[[115, 378, 343, 397]]
ANSWER: OXBOW LAKE  

sub_title[[462, 412, 533, 431]]
## BONUS  

text[[114, 445, 845, 485]]
11) EARTH AND SPACE - Multiple Choice Which of the following is not one of Steno's laws?  

text[[114, 499, 448, 581]]
W) Principle of inclusions 
X) Principle of cross-cutting relationships 
Y) Principle of superposition 
Z) Principle of original horizontality  

text[[114, 594, 492, 614]]
ANSWER: W) PRINCIPLE OF INCLUSIONS  

sub_title[[455, 661, 540, 680]]
## TOSS-UP  

text[[114, 694, 770, 714]]
12) MATH - Short Answer What are the last two digits of 11 to the power of 12?  

text[[115, 728, 230, 746]]
ANSWER: 21  

sub_title[[462, 761, 533, 780]]
## BONUS  

text[[115, 794, 719, 814]]
12) MATH - Short Answer What is the sum of the positive factors of 120?  

text[[115, 828, 241, 846]]
ANSWER: 360sub_title[[455, 90, 540, 107]]
## TOSS-UP  

text[[115, 122, 863, 184]]
13) CHEMISTRY – Short Answer What type of homogeneous mixture consists of one phase dispersed through a continuous phase, causing light to be scattered by the dispersed phase’s particles in the Tyndall effect?  

text[[115, 197, 297, 215]]
ANSWER: COLLOID  

sub_title[[462, 231, 533, 250]]
## BONUS  

text[[115, 263, 875, 305]]
13) CHEMISTRY – Short Answer Order the following three molecules in increasing length of the nitrogen-oxygen bond: 1) Nitrate; 2) Nitric oxide; 3) Nitrogen dioxide.  

text[[115, 317, 785, 337]]
ANSWER: 2, 3, 1 (ACCEPT: NITRIC OXIDE, NITROGEN DIOXIDE, NITRATE)  

sub_title[[455, 383, 540, 401]]
## TOSS-UP  

text[[115, 415, 881, 457]]
14) PHYSICS – Multiple Choice You place an object within the focal length of a single convex lens. Which of the following best describes the object’s image?  

text[[115, 470, 300, 552]]
W) Upright and virtual 
X) Upright and real 
Y) Inverted and virtual 
Z) Inverted and real  

text[[115, 566, 464, 585]]
ANSWER: W) UPRIGHT AND VIRTUAL  

sub_title[[462, 600, 533, 618]]
## BONUS  

text[[115, 632, 777, 673]]
14) PHYSICS – Short Answer Arrange the following three statistical values for a Maxwell-Boltzmann distribution in increasing order: 1) Mean; 2) Mode; 3) Median.  

text[[115, 686, 260, 705]]
ANSWER: 2, 1, 3  

sub_title[[455, 752, 540, 770]]
## TOSS-UP  

text[[115, 784, 797, 826]]
15) BIOLOGY – Multiple Choice Which of the following types of RNA polymerase predominately transcribes mRNA?  

text[[115, 840, 202, 880]]
W) Type I 
X) Type IItext[[114, 90, 209, 130]]
Y) Type IIIZ) Type IV  

text[[115, 143, 304, 162]]
ANSWER: X) TYPE II  

sub_title[[462, 177, 533, 195]]
## BONUS  

text[[115, 209, 790, 250]]
15) BIOLOGY – Multiple Choice Where would one expect to find cells with a high concentration of smooth endoplasmic reticulum?  

text[[115, 264, 275, 344]]
W) Adrenal cortexX) Adrenal medullaY) SkinZ) Pancreas  

text[[115, 359, 418, 377]]
ANSWER: W) ADRENAL CORTEX  

sub_title[[455, 412, 540, 430]]
## TOSS-UP  

text[[115, 444, 833, 527]]
16) ENERGY – Multiple Choice Scientists at Idaho National Laboratory are working with NASA on the Perseverance Rove hn6yr, part of the Mars 2020 mission. One of the rover's functions is to map the topological features of Mars such as outflow channels and valley networks. What process most likely created these features?  

text[[115, 542, 237, 620]]
W) AeolianX) FluvialY) GeothermalZ) Tectonic  

text[[115, 636, 320, 654]]
ANSWER: X) FLUVIAL  

sub_title[[462, 670, 533, 688]]
## BONUS  

text[[115, 703, 860, 765]]
16) ENERGY – Short Answer Scientists at Pacific Northwest National Laboratory have discovered that iron oxide nanoparticles can catalyze the conversion of carbon dioxide to form syngas. What are the two major components of syngas?  

text[[115, 778, 524, 796]]
ANSWER: CARBON MONOXIDE, HYDROGEN  

sub_title[[455, 845, 540, 862]]
## TOSS-UPtext[[113, 88, 833, 129]]
17) EARTH AND SPACE – Multiple Choice What was the main problem with Wegner’s theory of continental drift?  

text[[113, 143, 660, 223]]
W) Fossils were not accepted as evidence by contemporary scientists  
X) There was no mechanism for continental drift  
Y) Catastrophism better explained the position of continents  
Z) Contemporary scientists did not have access to paleomagnetism  

text[[113, 238, 754, 258]]
ANSWER: X) THERE WAS NO MECHANISM FOR CONTINENTAL DRIFT  

sub_title[[462, 272, 533, 291]]
## BONUS  

text[[113, 305, 826, 345]]
17) EARTH AND SPACE – Multiple Choice Which of the following locations is NOT a volcanic arc?  

text[[113, 359, 280, 440]]
W) Aleutian Islands  
X) Ryukyu Islands  
Y) Hawaiian Islands  
Z) Cascade Range  

text[[114, 454, 427, 474]]
ANSWER: Y) HAWAIIAN ISLANDS  

sub_title[[455, 521, 541, 540]]
## TOSS-UP  

text[[114, 553, 880, 635]]
18) MATH – Short Answer Sally and Joe are running on a circular 20 meter track in opposite directions from the same starting point. Joe runs at 2 meters per second, while Sally runs 1 meter per second faster than Joe. How many meters will Joe have run when they first meet again on the track?  

text[[114, 650, 221, 668]]
ANSWER: 8  

sub_title[[462, 683, 533, 701]]
## BONUS  

text[[113, 715, 865, 756]]
18) MATH – Short Answer What is the standard deviation of the following list of 5 numbers: 2, 4, 5, 8, 11.  

text[[114, 769, 246, 788]]
ANSWER: \(\sqrt{10}\)  

sub_title[[455, 838, 541, 856]]
## TOSS-UPtext[[113, 88, 857, 130]]
19) CHEMISTRY – Multiple Choice Which of the following molecular geometries does not have a steric number of 4?  

text[[113, 152, 295, 233]]
W) Square planar 
X) Tetrahedral 
Y) Trigonal pyramidal 
Z) See-saw  

text[[113, 247, 460, 266]]
ANSWER: Y) TRIGONAL PYRAMIDAL  

sub_title[[462, 280, 533, 299]]
## BONUS  

text[[113, 313, 856, 353]]
19) CHEMISTRY – Short Answer What is the oxidation state of the carbonyl carbon atom in acetone?  

text[[114, 367, 232, 385]]
ANSWER: +2  

sub_title[[455, 433, 541, 451]]
## TOSS-UP  

text[[113, 466, 876, 528]]
20) PHYSICS – Short Answer Albert throws a 3 kilogram ball at a 45 degree angle with an initial velocity of 49 meters per second. In meters, what is the horizontal distance the ball travels before hitting the ground?  

text[[114, 542, 241, 560]]
ANSWER: 245  

sub_title[[462, 575, 533, 593]]
## BONUS  

text[[113, 607, 808, 648]]
20) PHYSICS – Short Answer What is the angular resonant frequency of a series circuit containing two 8 farad capacitors and one 9 henry inductor?  

text[[114, 661, 237, 679]]
ANSWER: 1/6  

sub_title[[455, 715, 541, 733]]
## TOSS-UP  

text[[113, 748, 840, 789]]
21) BIOLOGY – Multiple Choice Which of the following structures in seeds represents the terminus of the hypocotyl and is the embryonic root?  

text[[113, 802, 403, 883]]
W) Coleoptile [coal-E-ah-p-tile] 
X) Coleorhiza [coal-E-or-HE-zHA] 
Y) Plumule 
Z) Radiclesub_title[[460, 123, 533, 140]]
## BONUS  

text[[113, 155, 819, 195]]
21) BIOLOGY - Multiple Choice Which of the following statements is NOT true about ecosystems?  

text[[113, 209, 816, 312]]
W) Species diversity is quantified by species richness and relative abundanceX) Moderate levels of disturbance foster the greatest amount of species diversityY) Biomass always decreases as the trophic level increases in biomass pyramidsZ) The amount of energy available always decreases as trophic levels increases in a food pyramid  

text[[113, 324, 870, 365]]
ANSWER: Y) BIOMASS ALWAYS DECREASES AS THE TROPHIC LEVEL INCREASES IN BIOMASS PYRAMIDS  

sub_title[[455, 412, 540, 431]]
## TOSS-UP  

text[[114, 445, 875, 508]]
22) ENERGY - Multiple Choice Scientists at Los Alamos National Laboratory are studying the formation of the early universe. What fundamental force was the first to separate from the other three, prior to the grand unification epoch?  

text[[114, 521, 270, 602]]
W) Weak nuclearX) Strong nuclearY) GravitationalZ) Electromagnetic  

text[[115, 616, 397, 635]]
ANSWER: Y) GRAVITATIONAL  

sub_title[[460, 650, 533, 668]]
## BONUS  

text[[115, 682, 832, 744]]
22) ENERGY - Short Answer Scientists at SLAC National Accelerator Laboratory are studying how to create compact medical imaging machines. What type of medical imaging utilizes radioactive fluorodeoxyglucose to monitor activity in the brain?  

text[[115, 757, 800, 777]]
ANSWER: POSITRON EMISSION TOMOGRAPHY SCAN (ACCEPT: PET SCAN)  

sub_title[[455, 824, 540, 842]]
## TOSS-UPtext[[113, 89, 855, 130]]
23) EARTH AND SPACE – Short Answer According to Bowen’s reaction series, what is the last feldspar group to crystallize?  

text[[113, 142, 771, 162]]
ANSWER: POTASSIUM FELDSPAR (ACCEPT: ORTHOCLASE, ADULARIA)  

sub_title[[462, 176, 533, 195]]
## BONUS  

text[[113, 209, 850, 250]]
23) EARTH AND SPACE – Short Answer The bottom of glaciers slide over the bed due to meltwater under the ice acting as a lubricant. What is the name of this movement?  

text[[115, 263, 320, 281]]
ANSWER: BASAL SLIP  

sub_title[[456, 330, 541, 348]]
## TOSS-UP  

text[[113, 362, 825, 402]]
24) MATH – Short Answer What is the second partial derivative with respect to x of the expression \(4x^2y + 6xy^2\) ?  

text[[115, 416, 231, 435]]
ANSWER: 8y  

sub_title[[462, 450, 533, 468]]
## BONUS  

text[[113, 482, 875, 522]]
24) MATH – Short Answer What is the inradius of a triangle with side lengths of 4, 6, and 8 in simplest radical form?  

text[[115, 535, 270, 555]]
ANSWER: \(\sqrt{15} /3\)  

sub_title[[456, 605, 541, 623]]
## TOSS-UP  

text[[113, 637, 825, 657]]
25) CHEMISTRY – Multiple Choice Which of the following orbitals has 2 radial nodes?  

text[[113, 681, 170, 760]]
W) 3d X) 4p Y) 5f Z) 6s  

text[[115, 776, 256, 795]]
ANSWER: X) 4p  

sub_title[[462, 810, 533, 828]]
## BONUStext[[115, 89, 877, 150]]
25) CHEMISTRY- Short Answer A mixture is prepared between ethanol and methanol in a 2 to 1 molar ratio. The vapor pressures of ethanol and methanol are 45 and 90 torr, respectively. What fraction of the vapor above the mixture is composed of ethanol vapor?  

text[[115, 164, 226, 182]]
ANSWER: \(\frac{1}{2}\)