
## TOSS-UP  


1) PHYSICS – Multiple Choice A T-S diagram can be used to visualize the changes in temperature and specific entropy that take place during a thermodynamic cycle. Which of the following quantities can be calculated as the area enclosed by a clockwise cycle on a T-S diagram?  


W) Entropy change 
X) Heat released 
Y) Heat absorbed 
Z) Thermal efficiency  


ANSWER: Y) HEAT ABSORBED  


## BONUS  


1) PHYSICS – Short Answer By name or number, list all of the following circuit components that have a non-linear relationship between voltage and current: 1) Transistor; 2) Resistor; 3) Diode.  


ANSWER: 1 AND 3  


## TOSS-UP  


2) BIOLOGY – Multiple Choice Anka is suffering from abnormal sleeping patterns where she wakes up during the night multiple times and experiences narcolepsy. Anka most likely has damage to which of the following?  


W) Suprachiasmatic nucleus [sup-rah-qi-az- matic] 
X) Substantia nigra [sub- stan-XIA-ni-gra] 
Y) Amygdala [uh-meh-G-duh-la] 
Z) Basal nuclei  


ANSWER: W) SUPRACHIASMATIC NUCLEUS  


## BONUS  


2) BIOLOGY – Short Answer Allen grows a plant belonging to the Cactaceae [kak-ta-SEE-ey] family. After measuring the pH of the central vacuole, he realizes that the pH decreases during the day and increases during the night. Identify all of the following three statements that are true
of his plant: 1) It lacks photosystem II in its bundle-sheath cells; 2) It likely uses PEP carboxylase to fix \(\mathrm{CO}_{2}\) during the day; 3) It likely possesses a high stomatal density.  


ANSWER: NONE  


## TOSS-UP  


3) CHEMISTRY – Short Answer What type of isomerism is exhibited by S and R BINAP, which arise as different enantiomers due to steric hindrance preventing free rotation around a single bond?  


ANSWER: ATROPISOMERISM  


## BONUS  


3) CHEMISTRY – Short Answer Identify all of the following three statements that are true about the transition state of \(\mathrm{S}_{\mathrm{N}}2\) reactions: 1) It displays 3 center 4 electron bonding; 2) The leaving group and nucleophile display positive partial charges; 3) The nucleophile attacks at a 180 degree angle to the leaving group.  


ANSWER: 1 AND 3  


## TOSS-UP  


4) MATH – Short Answer A particle moving in the \(x - y\) plane has its velocity defined parametrically such that \(v_{x}(t) = 3t\) and \(v_{y}(t) = 4t\) . How far does the particle travel between the times \(t = 0\) and \(t = 4\) ?  


ANSWER: 40  


## BONUS  


4) MATH – Short Answer Two real numbers are chosen independently and uniformly at random between 0 and 1. What is the probability that the two numbers differ by no more than \(\frac{1}{3}\) ?  


ANSWER: 5/9  


## TOSS-UP
5) EARTH AND SPACE – Short Answer By name or number, identify all the following four groups of organisms that would form siliceous ooze: 1) Foraminifera; 2) Diatoms; 3) Radiolarians; 4) Coccolithophores.  


ANSWER: 2 AND 3 (ACCEPT: DIATOMS AND RADIOLARIANS)  


## BONUS  


5) EARTH AND SPACE – Short Answer A binary system is composed of Star A and star B. The binary system has a period of 12 years and an average distance of 12 AU. If the ratio of the distances from the center of mass for stars A and B is 2:1, what are the masses of star A and B respectively in solar masses?  


ANSWER: 4 AND 8  


## TOSS-UP  


6) ENERGY – Multiple Choice Scientists at Los Alamos National Laboratory recently imaged heart RNA—long, non-coding RNA critical to stem cell programming—using small-angle X-ray scattering. What group of small non-coding RNA have a strong function in endogenous gene expression?  


W) miRNA 
X) siRNA 
Y) piRNA 
Z) giRNA  


ANSWER: W) miRNA  


## BONUS  


6) ENERGY – Multiple Choice Scientists at the Joint Genome Institute are attempting to manipulate bacterial colonies to change nitrogen concentrations in ecosystems. Which of the following genera of bacteria do NOT engage in nitrogen fixation?  


W) Anabaena 
X) Nitrosomona 
Y) Rhizobium 
Z) Campylobacter  


ANSWER: Z) CAMPYLOBACTER
## TOSS-UP  


7) PHYSICS – Multiple Choice Which of the following combinations of circuit components will take the longest to lose half of its energy after it is disconnected from a battery?  


W) 2 ohm resistor and 6 microfarad capacitor  X) 3 ohm resistor and 12 microhenry inductor  Y) 4 ohm resistor and 2 microfarad capacitor  Z) 5 ohm resistor and 10 microhenry inductor  


ANSWER: W) 2 OHM RESISTOR AND 6 MICROFARAD CAPACITOR  


## BONUS  


7) PHYSICS – Short Answer Identify all of the following three changes that would increase the physical separation between intensity peaks on the screen in a double-slit diffraction setup: 1) Increasing the distance between the slits; 2) Increasing the distance between the occluding slits and the screen; 3) Decreasing the wavelength of light.  


ANSWER: 2 ONLY  


## TOSS-UP  


8) BIOLOGY – Multiple Choice Which of the following is a proto-oncogene?  


W) HER2  X) BRCA1  Y) APC  Z) p53  


ANSWER: W) HER2  


## BONUS  


8) BIOLOGY – Short Answer What organ do invertebrates such as insects use to detect gravity and maintain equilibrium?  


ANSWER: STATOCYST  


## TOSS-UP
9) CHEMISTRY – Multiple Choice Which of the following alkene addition reactions is NOT a syn addition?  


W) Catalytic hydrogenation  
X) Oxymercuration  
Y) Hydroboration-oxidation  
Z) Osmium tetroxide dihydroxylation  


ANSWER: X) OXYMERCURATION  


## BONUS  


9) CHEMISTRY – Short Answer Identify all of the following three statements that are true about crystal field theory: 1) All d orbitals are lowered in energy upon formation of a metal complex; 2) Octahedral complexes experience larger splitting than tetrahedral complexes; 3) Almost all tetrahedral complexes are low spin.  


ANSWER: 2 ONLY  


## TOSS-UP  


10) MATH – Short Answer By number, identify all of the following three scenarios that are examples of a type II error: 1) A doctor testing the efficacy of a new drug incorrectly concludes that the drug does not improve a patient’s symptoms; 2) A researcher testing a new sports drink incorrectly concludes that the sports drink significantly enhances performance; 3) A car manufacturer evaluating a new engine incorrectly concludes that the engine decreases fuel efficiency.  


ANSWER: I ONLY  


## BONUS  


10) MATH – Short Answer How many two digit positive integers have the property that they are divisible by their units digit?  


ANSWER: 41  


## TOSS-UP  


11) EARTH AND SPACE – Short Answer What term is given to the icy core of the comet that releases dust to form the dust tail?
ANSWER: NUCLEUS  


## BONUS  


11) EARTH AND SPACE – Short Answer The double-exhaust model describes what group of astronomical objects that emit strong radio waves from twin-lobed hotspots?  


ANSWER: DOUBLE-LOBED RADIO GALAXY (ACCEPT: RADIO GALAXIES)  


## TOSS-UP  


12) ENERGY – Short Answer Scientists at Argonne National Laboratory are studying the molecular orbitals of Fe-complexes. In hemoglobin and cytochromes, iron is bound to what heterocyclic macrocycle complexes?  


ANSWER: PORPHYRIN RING  


## BONUS  


12) ENERGY – Multiple Choice Scientists at Brookhaven National Labs have been using Lanthanide Binding Tags to bind proteins and become a fluorescent locator during 3D and 2D X-Ray imaging. What is the likely use of these tags?  


W) To help purify the protein by increasing its affinity for pellets during gel filtration chromatography  


X) To increase the efficiency of protein binding during IC-PMS  


Y) To allow the protein to be localized with electron paramagnetic resonance spectroscopy  


Z) To determine the subcellular localization of the tagged proteins.  


ANSWER: Z) TO DETERMINE THE SUBCELLULAR LOCALIZATION OF THE TAGGED PROTEINS  


## TOSS-UP  


13) PHYSICS – Short Answer A convex lens has a focal length of 40 cm. What distance would an object have to be placed in front of the lens in centimeters such that the image distance is equal to the object distance?  


ANSWER: 80  


## BONUS
13) PHYSICS – Short Answer By name or number, list all the combinations of colors that the two quarks in a pion could have: 1) Red, anti-green; 2) Green, blue; 3) Anti-green, anti-red.  


ANSWER: NONE  


## TOSS-UP  


14) BIOLOGY – Multiple Choice Angiotensin-converting-enzyme inhibitors are used to treat which of the following conditions?  


W) Hypertension 
X) Beriberi 
Y) Diabetes insipidus 
Z) Pernicious anemia  


ANSWER: W) HYPERTENSION  


## BONUS  


14) BIOLOGY – Short Answer By name or number, identify all the following three cellular junctions that are stabilized by cadherins: 1) Desmosome; 2) Adherens junction; 3) Gap junction.  


ANSWER: 1 AND 2 (ACCEPT: DESMOSOME AND ADHERENS JUNCTION)  


## TOSS-UP  


15) CHEMISTRY – Multiple Choice Which of the following describes the spontaneity of the autoionization of water?  


W) Spontaneous at all temperatures 
X) Non-spontaneous at all temperatures 
Y) Spontaneous at low temperatures 
Z) Spontaneous at high temperatures  


ANSWER: X) NON- SPONTANEOUS AT ALL TEMPERATURES  


## BONUS  


15) CHEMISTRY – Short Answer Order the following three elements in increasing third ionization energy: 1) Indium; 2) Calcium; 3) Chlorine.
## TOSS-UP  


16) MATH - Short Answer Express the complex number \((1 + i)^{-6}\) [the quantity 1 plus i to the power of negative 6] in standard form.  


ANSWER: i/8  


## BONUS  


16) MATH - Short Answer Determine the number of ordered triplets \((x, y, z)\) of odd positive integers such that \(x + y + z = 99\) .  


ANSWER: 1225  


## TOSS UP  


17) EARTH AND SPACE - Multiple Choice The drainage of Lake Agassiz led to the widespread deposition of lacustrine clays enriched with vermiculites. The fine grained materials lead to increase in boreal forest development due to the high potassium concentrations and high acidity. What basic soil order resulted from the drainage of Lake Agassiz?  


W) Mollisol 
X) Alfisol 
Y) Spodosol 
Z) Vertisol  


ANSWER: Y) SPODOSOL  


## BONUS  


17) EARTH AND SPACE - Short Answer Identify all of the following three objects that are supported solely by neutron degeneracy pressure: 1) Black hole; 2) O type star; 3) Neutron star.  


ANSWER: 3 ONLY  


## TOSS-UP  


18) ENERGY - Short Answer Scientists at Fermi National Accelerator Laboratory constantly detect muons formed from cosmic rays as they collide with Earth's atmosphere. However, the
half- life calculated in laboratories is too short for these muons to reach Earth's surface. What effect predicted by special relativity must be accounted for to predict these muons that survive longer than they should?  


ANSWER: TIME DILATION (ACCEPT: LENGTH CONTRACTION)  


## BONUS  


18) ENERGY – Short Answer Scientists at Fermilab have been studying the fluctuations of synchrotron photons and found that their oscillations closely model a poisson distribution. They produced these photons via what device, which is composed of alternating dipole magnets that rapidly oscillate electrons?  


ANSWER: UNDULATOR  


## TOSS-UP  


19) PHYSICS – Short Answer Quantum nonlocality is a direct conclusion of which theorem that disproves the existence of local, hidden variable theories if quantum mechanics is to be considered?  


ANSWER: BELL'S THEOREM  


## BONUS  


19) PHYSICS – Short Answer By name or number, identify all of the following three quantities that approach infinity as velocity approaches the speed of light: 1) Momentum; 2) Mass energy; 3) Total energy.  


ANSWER: 1 AND 3  


## TOSS-UP  


20) BIOLOGY – Short Answer What specialized hyphae do arbuscular mycorrhizal fungi use to extract nutrients from, or exchange nutrients with, their plant host?  


ANSWER: HAUSTORIA  


## BONUS
20) BIOLOGY – Short Answer What specific enzyme is responsible for the cleavage of phospholipids into arachidonic acid and lysophosphatidic acid?  


ANSWER: PHOSPHOLIPASE \(\mathbf{A}_2\)  


## TOSS-UP  


21) CHEMISTRY – Multiple Choice Which of the following molecules does NOT display 3 center 4 electron bonding?  


W) Phosphorus pentachloride 
X) Allyl anion 
Y) Tin tetrachloride 
Z) Triiodide  


ANSWER: Y) TIN TETRACHLORIDE  


## BONUS  


21) CHEMISTRY – Short Answer According to the Debye model, the entropy of a solid at very low temperatures is proportional to the temperature raised to what power?  


ANSWER: 3  


## TOSS-UP  


22) MATH – Short Answer 16 teams participate in a double elimination tournament. If the probability of each team winning each individual game is \(\frac{1}{2}\) , what is the probability that the winner of the tournament will be undefeated?  


ANSWER: \(\frac{1}{2}\)  


## BONUS  


22) MATH – Short Answer Isosceles triangle ABC has \(\mathrm{AB} = \mathrm{AC}\) . The angle bisector of angle ABC intersects AC at point D. Given triangle ABD is also isosceles, determine the smallest possible value of angle ABC in degrees.  


ANSWER: 360/7
## TOSS UP  


23) EARTH AND SPACE - Multiple Choice Which of the following best describes how ocean cores can be utilized for proxy climate data?  


W) Inclusions of pollen grains 
X) Variation in settling rates of particulates 
Y) Carbon isotope ratios in fossilized detritus 
Z) Oxygen isotope ratios in carbonate shells  


ANSWER: Z) OXYGEN ISOTOPE RATIOS IN CARBONATE SHELLS  


## BONUS  


23) EARTH AND SPACE - Short Answer What specific ocean zone is characterized by being above the open ocean and having enough light for photosynthesis?  


ANSWER: EPIPELAGIC  


## TOSS-UP  


24) ENERGY - Multiple Choice Researchers at the SLAC National Accelerator Laboratory have been studying stomata mediated bacterial infections of plants. They discovered that some plants can provide immunity for other plants by activating their stomatal regulation pathways that are dependent on which of the following hormones?  


W) Gibberellins 
X) Auxins 
Y) Abscisic acid 
Z) Strigolactones  


ANSWER: Y) ABSCISIC ACID  


## BONUS  


24) ENERGY - Short Answer Researchers at Argonne National Lab have been working with orthorhombic pseudo-perovskite crystals. While cooling, negative magnetization was discovered. They measured the magnetization via the backscattering of what particle, used because it can measure events in the nanosecond time scale?  


ANSWER: NEUTRON
## TOSS-UP  


25) PHYSICS – Multiple Choice Which of the following potential energy functions does not have a stable equilibrium?  


W) \(\cos (\mathbf{x})\) X) \(\mathbf{x}^{2} - 8\mathbf{x} + 3\) Y) \(\mathbf{x}^{3} - \mathbf{x}^{2} + \mathbf{x}\) Z) \(\mathbf{e}^{\mathbf{x}} - \mathbf{x}\)  


ANSWER: \(\mathbf{Y}) \mathbf{x}^{3} - \mathbf{x}^{2} + \mathbf{x}\)  


## BONUS  


25) PHYSICS – Short Answer A tank of water with density \(1000 \mathrm{kg / m}^3\) is filled to a height of 15 meters. A hole is drilled in the side so that a jet of water streams out a horizontal distance \(d\). In meters, what is the maximum possible value of \(d\) ?  


ANSWER: 15