
# NATIONAL DOUBLE ELIMINATION - 7  


## TOSS-UP  


1. ASTR; Multiple Choice: A cloud of gases around the solid portion of a comet is known as the  


(W) coma. 
(X) core. 
(Y) heart. 
(Z) nucleus.  


ANSWER: W- COMA  


## BONUS  


1. ASTR; Multiple Choice: A comet develops a coma because of  


(W) the solar wind. 
(X) Earth's atmosphere. 
(Y) the Oort Cloud. 
(Z) heat from the sun.  


ANSWER: Z- HEAT FROM THE SUN  


## TOSS-UP  


2. BIOL; Multiple Choice: The first vertebrates appeared a little more than  


(W) 50 million years ago. 
(X) 100 million years ago. 
(Y) 500 million years ago. 
(Z) 150 million years ago.  


ANSWER: Y- 500 MILLION YEARS AGO  


## BONUS  


2. BIOL; Multiple Choice: Birds and reptiles excrete nitrogenous wastes in the form of  


(W) uric acid. 
(X) ammonia. 
(Y) free nitrogen. 
(Z) urea.  


ANSWER: W- URIC ACID
## TOSS-UP  


3. PHYS; Multiple Choice: Which of the following is a device that detects charged particles but does NOT show their tracks?  


(W) spark chamber 
(X) photographic plate 
(Y) scintillation counter 
(Z) bubble chamber  


ANSWER: Y- SCINTILLATION COUNTER  


## BONUS  


3. PHYS; Multiple Choice: The photomultiplier tube in the scintillation counter multiplies which of the following?  


(W) scintillations 
(X) electrons 
(Y) ions 
(Z) photons  


ANSWER: X- ELECTRONS  


## TOSS-UP  


4. CHEM; Multiple Choice: A key word in the definition of stoichiometry is  


(W) qualitative. 
(X) subjective. 
(Y) descriptive. 
(Z) quantitative.  


ANSWER: Z- QUANTITATIVE  


## BONUS  


4. CHEM; Multiple Choice: Which concept allows you to relate the coefficients of a balanced chemical equation to actual amounts of reactants or products?  


(W) Equivalence 
(X) Limiting factor 
(Y) The mole 
(Z) Conservation of mass  


ANSWER: Y- THE MOLE
## TOSS-UP  


5. GENR; Multiple Choice: The use of which of the following energy sources does not normally produce nitrogen oxides as a byproduct?  


(W) gasoline (X) coal (Y) nuclear (Z) natural gas  


ANSWER: Y- NUCLEAR  


## BONUS  


5. GENR; Multiple Choice: Which of the following has not been used as a moderator for thermal nuclear reactors?  


(W) beryllium (X) aluminum (Y) graphite (Z) heavy water  


ANSWER: X- ALUMINUM  


## TOSS-UP  


6. COMP; Multiple Choice: High-level languages are converted into machine language and executed immediately, statement by statement, using  


(W) an assembler. (X) a compiler. (Y) an interpreter. (Z) a desk checker.  


ANSWER: Y- AN INTERPRETER  


## BONUS  


6. COMP; Multiple Choice: A new programming language that may transform the Internet into a completely interactive environment is called  


(W) C++. (X) Java. (Y) Logo. (Z) HTML.  


ANSWER: X- JAVA
## TOSS-UP  


7. CHEM; Multiple Choice: What happens to delta H if a chemical equation is reversed?  


(W) It becomes zero. 
(X) It remains the same. 
(Y) It changes in sign. 
(Z) Depends on the reaction.  


ANSWER: Y- IT CHANGES IN SIGN  


## BONUS  


7. CHEM; Multiple Choice: What principle relates the enthalpy change for a net reaction to the enthalpy changes of a series of summed reactions?  


(W) Boyle's law 
(X) Hess's law 
(Y) Avogadro's hypothesis 
(Z) Henry's law  


ANSWER: X- HESS'S LAW  


## TOSS-UP  


8. BIOL; Multiple Choice: In turtles and crocodiles, the lungs are divided into many  


(W) alveoli. 
(X) small chambers. 
(Y) air sacs. 
(Z) bronchi.  


ANSWER: X- SMALL CHAMBERS  


## BONUS  


8. BIOL; Multiple Choice: In the heart of a toad, oxygen-rich and oxygen-poor blood  


(W) mix in the right atrium. 
(X) mix in the left atrium. 
(Y) mix in the ventricle. 
(Z) do not mix.  


ANSWER: Y- MIX IN THE VENTRICLE
## TOS-UP  


9. PHYS; Multiple Choice: Which of the following statements dealing with simple harmonic motion of a mass-spring system is TRUE?  


(W) The acceleration is largest when the oscillating mass is instantaneously at rest. 
(X) The larger the spring force constant the larger the period. 
(Y) The period of the motion depends linearly on the amplitude of the motion. 
(Z) The acceleration is larger when the oscillating mass has its greatest velocity.  


ANSWER: W- THE ACCELERATION IS LARGEST WHEN THE OSCILLATING MASS IS INSTANTANEOUSLY AT REST  


## BONUS  


9. PHYS; Multiple Choice: An ice skater is rotating with her arms extended. When she pulls in her arms her rate of rotation increases. Which of the following statements dealing with the process is TRUE?  


(W) Her moment of inertia is increased. 
(X) Kinetic energy is conserved. 
(Y) The skater does work when pulling in her arms. 
(Z) Angular momentum is increased.  


ANSWER: Y- THE SKATER DOES WORK WHEN PULLING IN HER ARMS  


## TOS-UP  


10. ERSC; Multiple Choice: Which of the following is the thinnest layer of Earth?  


(W) Inner core 
(X) Crust 
(Y) Mantle 
(Z) Outer core  


ANSWER: X- CRUST  


## BONUS  


10. ERSC; Multiple Choice: The crust and upper mantle make up Earth's  


(W) lithosphere. 
(X) asthenosphere. 
(Y) shield. 
(Z) continents.  


ANSWER: W- LITHOSPHERE
## TOSS-UP  


11. BIOL; Multiple Choice: The motion of snakes depends upon the fact that the muscles of their bodies are  


(W) attached by ligaments. 
(X) arranged in circles. 
(Y) arranged in blocks. 
(Z) attached to bones.  


ANSWER: Y- ARRANGED IN BLOCKS  


## BONUS  


11. BIOL; Multiple Choice: In the circulatory system of a bird, blood is moved through the body loop by the  


(W) right and left atria. 
(X) right and left ventricles. 
(Y) right atrium and right ventricle. 
(Z) left atrium and left ventricle.  


ANSWER: Z- LEFT ATRIUM AND LEFT VENTRICLE  


## TOSS-UP  


12. PHYS; Multiple Choice: In simple harmonic motion, the acceleration is  


(W) constant. 
(X) proportional to the distance from the central position. 
(Y) greatest when the velocity is greatest. 
(Z) none of the above  


ANSWER: X- PROPORTIONAL TO THE DISTANCE FROM THE CENTRAL POSITION  


## BONUS  


12. PHYS; Multiple Choice: When a liquid moves through a pipe having a varying diameter, the pressure against the inside walls of the pipe will be  


(W) the same throughout. 
(X) lowest where the diameter is smallest. 
(Y) lowest where the diameter is largest. 
(Z) lowest where the velocity of flow is lowest.  


ANSWER: X- LOWEST WHERE THE DIAMETER IS SMALLEST
## TOSS-UP  


13. CHEM; Multiple Choice: When two reactants are available in the stoichiometric proportions represented by the chemical equation,  


(W) only the most massive reactant will be used up. 
(X) neither of the reactants will be used up. 
(Y) both of the reactants will be used up. 
(Z) only the least massive of the reactants will be used up.  


ANSWER: Y- BOTH OF THE REACTANTS WILL BE USED UP  


## BONUS  


13. CHEM; Multiple Choice: When comparing gaseous reactants and/ or products, the ratio of their coefficients represents  


(W) the molar ratio of the substances. 
(X) the volume ratios of the substances. 
(Y) both the molar and volume ratios. 
(Z) neither the molar nor volume ratios.  


ANSWER: Y- BOTH THE MOLAR AND VOLUME RATIOS  


## TOSS-UP  


14. MATH; Multiple Choice: Mary randomly selects a number from among the integers 1 through 100. What is the probability that the number selected is divisible by both 2 and 3?  


(W) 1/5 
(X) 4/25 
(Y) 3/20 
(Z) 7/50  


ANSWER: X- 4/25  


## BONUS  


14. MATH; Short Answer: How many three-digit area codes are possible if the first digit cannot be 0 or 1 and the second digit must be 0 or 1?  


ANSWER: 160
## TOSS-UP  


15. GENR; Multiple Choice: The fastest-running terrestrial animal is  


(W) a cheetah. 
(X) a lion. 
(Y) man. 
(Z) a jaguar.  


ANSWER: W- ACHEETAH  


## BONUS  


15. GENR; Multiple Choice: Approximately how many meteors enter the Earth's atmosphere each year?  


(W) 1,000 
(X) 10,000 
(Y) 25,000 
(Z) 100,000  


ANSWER: Y- 25,000  


## TOSS-UP  


16. BIOL; Multiple Choice: Male and female gametes are produced in separate flowers in a  


(W) pea plant. 
(X) rose. 
(Y) spruce tree. 
(Z) corn plant.  


ANSWER: Z- CORN PLANT  


## BONUS  


16. BIOL; Multiple Choice: Female pine cones do not produce  


(W) ovules. 
(X) microsporangia. 
(Y) megasporangia. 
(Z) gametophytes.  


ANSWER: X- MICROSPORANGIA
## TOSS-UP  


17. ASTR; Multiple Choice: A comet develops a tail because of  


(W) the solar wind. 
(X) Earth's atmosphere. 
(Y) the Oort Cloud. 
(Z) heat from Mercury.  


ANSWER: W- THE SOLAR WIND  


## BONUS  


17. ASTR; Multiple Choice: The intense magnetic fields of sunspots cause archlike eruptions called  


(W) solar flares. 
(X) corona. 
(Y) photospheres. 
(Z) prominences.  


ANSWER: Z- PROMINENCES  


## TOSS-UP  


18. PHYS; Multiple Choice: If viewed on an oscilloscope, the loudness of a sound wave would be associated with the wave's  


(W) frequency. 
(X) wavelength. 
(Y) velocity. 
(Z) amplitude.  


ANSWER: Z- AMPLITUDE  


## BONUS  


18. PHYS; Multiple Choice: If a sled has a constant acceleration of 2 meters per second squared and starts from rest, the distance in meters that it will have covered after 5 seconds is  


(W) 10 meters. 
(X) 20 meters. 
(Y) 25 meters. 
(Z) 50 meters.  


ANSWER: Y- 25 METERS
## TOSS-UP  


19. CHEM; Multiple Choice: The enthalpy change for melting a solid, such as ice, is called  


(W) heat of fusion. 
(X) heat of vaporization. 
(Y) heat capacity. 
(Z) specific heat.  


ANSWER: W- HEAT OF FUSION  


## BONUS  


19. CHEM; Multiple Choice: The law of partial pressures of gases was formulated by  


(W) Avogadro. 
(X) Boyle. 
(Y) Charles. 
(Z) Dalton.  


ANSWER: Z- DALTON  


## TOSS-UP  


20. ERSC; Multiple Choice: The boundaries between two colliding plates on the Earth- surface are called  


(W) divergent. 
(X) convergent. 
(Y) a transform fault. 
(Z) lithosphere.  


ANSWER: X- CONVERGENT  


## BONUS  


20. ERSC; Multiple Choice: The layer inside Earth that is comprised of material that can flow like a liquid yet also retain solid properties is the  


(W) inner core. 
(X) outer core. 
(Y) mantle. 
(Z) crust.  


ANSWER: Y- MANTLE
## TOSS-UP  


21. COMP; Short Answer: What does the acronym LISP stand for?  


ANSWER: LIST PROCESSING  


## BONUS  


21. COMP; Short Answer: What is the only data structure in the programming language LISP?  


ANSWER: ALIST  


## TOSS-UP  


22. BIOL; Short Answer: The elevations on the surface of the tongue are known as  


ANSWER: PAPILLAE  


## BONUS  


22. BIOL; Multiple Choice: All the petals of a flower form the  


(W) corolla. 
(X) carpel. 
(Y) calyx. 
(Z) stamen.  


ANSWER: W- COROLLA
## TOSS-UP  


23. MATH; Short Answer: In radians, what is the period of the function \(t = \cos (4s)\) ? (read: t equals the cosine of 4 s)  


ANSWER: PI/2 (ACCEPT 1.57)  


## BONUS  


23. MATH; Multiple Choice: USA Deli sells cheese with \(20\%\) water content at \(\) 3.50\(per pound. Removing moisture from the cheese costs\) \ \(1.00\) per pound of water removed. At what rate per pound would cheese with a \(10\%\) water content have to be sold to keep the same profit?  


(W) \(\) 3.60\(\) (X) \(\) 3.80\(\) (Y) \(\) 4.00\(\) (Z) \(\) 4.20\$  


ANSWER: Y- \(\) 4.00\$  


## TOSS-UP  


24. PHYS; Short Answer: The pressure placed on a square with \(1 / 2\) meter sides is 1000 Pascals. How much force, in Newtons, is being applied to the square?  


ANSWER: 250 (NEWTONS)  


## BONUS  


24. PHYS; Multiple Choice: Which of the following is NOT closely associated with a non-magnetic Phase Diagram?  


(W) Eutectic Temperature(pron: you-tek-tik) 
(X) Curie Point 
(Y) Solidus (pron: sahl-ud-us) 
(Z) Liquidus (pron: lick-wid-us) Curves  


ANSWER: X- CURIE POINT
## TOSS-UP  


25. CHEM; Short Answer: The scientist who discovered the law of conservation of matter was  


ANSWER: LAVOISIER (pron: la-voy-zee-eh)  


## BONUS  


25. CHEM; Multiple Choice: The experiment that revealed the charge of the electron involved the use of  


(W) gold foil. 
(X) photographic film. 
(Y) oil droplets. 
(Z) cathode ray tubes.  


ANSWER: Y- OIL DROPLETS