
# NATIONAL DOUBLE ELIMINATION - 8  


## TOSS-UP  


1. MATH; Multiple Choice: What is the minimum number of times a deck of 52 cards must be shuffled to thoroughly mix the cards?  


(W) 2 
(X) 5 
(Y) 7 
(Z) 12  


ANSWER: Y- 7  


## BONUS  


1. MATH; Multiple Choice: Although the chance of YOUR winning a state lottery twice is as low as one chance in 17 trillion, what is the chance that SOMEONE will win twice?  


(W) 1 in 10 
(X) 1 in 30 
(Y) 1 in 3000 
(Z) 1 in 1,000,000  


ANSWER: X- 1 IN 30  


## TOSS-UP  


2. PHYS; Multiple Choice: The Modulus of Elasticity for a material refers to  


(W) the ability of a material to resist corrosion. 
(X) the ratio of stress over strain. 
(Y) the maximum load over the cross sectional area. 
(Z) none of the above  


ANSWER: X- THE RATIO OF STRESS OVER STRAIN  


## BONUS  


2. PHYS; Short Answer: Many common household fluids, such as margarine, undergo a decrease in viscosity when subjected to a shearing force. What is this property called?  


ANSWER: THIXOTROPIC (pron: thik- sa- trop- ick)
## TOSS-UP  


3. BIOL; Multiple Choice: In a seed, the region at the base of the hypocotyl is the  


(W) epicotyl. 
(X) shaft. 
(Y) radicle. 
(Z) silk.  


ANSWER: Y- RADICLE  


## BONUS  


3. BIOL; Multiple Choice: In reproduction in a pine tree,  


(W) two sperm fertilize the egg. 
(X) two sperm disintegrate. 
(Y) the pollen tube contains three sperm. 
(Z) the pollen tube grows into the ovules.  


ANSWER: Z- THE POLLEN TUBE GROWS INTO THE OVULES  


## TOSS-UP  


4. CHEM; Multiple Choice: An atom is defined as the smallest part of an element that  


(W) contains at least one proton, neutron, and electron. 
(X) retains the chemical identity of that element. 
(Y) can carry an electric charge. 
(Z) is affected in a cathode ray tube.  


ANSWER: X- RETAINS THE CHEMICAL IDENTITY OF THAT ELEMENT  


## BONUS  


4. CHEM; Multiple Choice: The fact that carbon dioxide always contains 73 percent oxygen by mass is an illustration of  


(W) the ideas of Democritus. 
(X) the law of conservation of matter. 
(Y) the law of constant composition. 
(Z) Dalton's atomic theory of matter.  


ANSWER: Y- THE LAW OF CONSTANT COMPOSITION
## TOSS-UP  


5. COMP; Multiple Choice: All languages except machine language must be translated into machine language. This is done with  


(W) a syntax translator. 
(X) a language translator. 
(Y) an assembler. 
(Z) a code checker.  


ANSWER: X- ALANGUAGE TRANSLATOR  


## BONUS  


5. COMP; Multiple Choice: An IF-THEN-ELSE structure is also known as  


(W) a test structure. 
(X) an iterative structure. 
(Y) a selection control structure. 
(Z) none of the above  


ANSWER: Y- A SELECTION CONTROL STRUCTURE  


## TOSS-UP  


6. BIOL; Multiple Choice: New African violet plants can grow asexually from fallen  


(W) leaves. 
(X) stems. 
(Y) endosperms. 
(Z) flowers.  


ANSWER: W- LEAVES  


## BONUS  


6. BIOL; Multiple Choice: Grafts are successful only if the two plant parts involved are firmly connected to each other at their  


(W) vascular cambium. 
(X) cork cambium. 
(Y) apical meristem. 
(Z) heartwood.  


ANSWER: W- VASCULAR CAMBIUM
## TOSS-UP  


7. PHYS; Multiple Choice: The temperature of a gas is held constant while its volume is reduced. The pressure the gas exerts on the walls of its container increases because its molecules  


(W) strike the container walls more often. 
(X) strike the container walls with higher speeds. 
(Y) strike the container walls with greater force. 
(Z) all of the above  


ANSWER: W- STRIKE THE CONTAINER WALLS MORE OFTEN  


## BONUS  


7. PHYS; Short Answer: How many joules of energy are consumed if a 100 watt light bulb is operated for 10 MINUTES?  


ANSWER: 60,000 (JOULES)  


## TOSS-UP  


8. CHEM; Multiple Choice: What information about electrons is given by the electron configuration of an atom?  


(W) paths within the principal quantum level 
(X) density of the electron cloud 
(Y) average angular momentum 
(Z) distribution among orbitals  


ANSWER: Z- DISTRIBUTION AMONG ORBITALS  


## BONUS  


8. CHEM; Multiple Choice: Under what conditions can two electrons occupy the same orbital?  


(W) never 
(X) if they have opposite spins 
(Y) if they have parallel spins 
(Z) if they have different principal quantum numbers  


ANSWER: X- IF THEY HAVE OPPOSITE SPINS
## TOSS-UP  


9. ASTR; Multiple Choice: What makes Sirius the brightest star in the night sky?  


(W) apparent magnitude (X) parallax (Y) color (Z) absolute magnitude  


ANSWER: W- APPARENT MAGNITUDE  


## BONUS  


9. ASTR; Multiple Choice: Rigel does not look as bright in the night sky as Sirius although it has greater  


(W) apparent magnitude. (X) parallax. (Y) absolute magnitude. (Z) black hole.  


ANSWER: Y- ABSOLUTE MAGNITUDE  


## TOSS-UP  


10. PHYS; Multiple Choice: When an alpha particle hits an atom of element 13, aluminum, with a mass of 27, an atom of element 15, phosphorus, with a mass of 30 is produced. What atomic particle is also produced in this process?  


(W) proton (X) positron (Y) neutron (Z) deuteron  


ANSWER: Y- NEUTRON  


## BONUS  


10. PHYS; Multiple Choice: Refracting telescopes, if uncorrected, suffer from chromatic aberration. Chromatic aberration occurs because  


(W) red light is focused more strongly than blue light. (X) blue light is focused more strongly than red light. (Y) the outer light rays are focused more strongly than the central rays. (Z) the central light rays are focused more strongly than the outer rays.  


ANSWER: X- BLUE LIGHT IS FOCUSED MORE STRONGLY THAN RED LIGHT
## TOSS-UP  


11. CHEM; Multiple Choice: When a sample of an element is vaporized in a flame, it releases energy in the form of  


(W) a continuous spectrum. 
(X) gamma rays. 
(Y) light of all wavelengths. 
(Z) light of only certain wavelengths.  


ANSWER: Z- LIGHT OF ONLY CERTAIN WAVELENGTHS  


## BONUS  


11. CHEM; Multiple Choice: A systematic variation in the properties of elements going down a group or across a period is called a  


(W) block characteristic. 
(X) periodic law. 
(Y) periodic trend. 
(Z) triad configuration.  


ANSWER: Y- PERIODIC TREND  


## TOSS-UP  


12. BIOL; Multiple Choice: The class Anthozoa contains  


(W) sea anemones and jellyfish. 
(X) jellyfish and hydras. 
(Y) hydras and corals. 
(Z) corals and sea anemones.  


ANSWER: Z- CORALS AND SEA ANEMONES  


## BONUS  


12. BIOL; Multiple Choice: Most sea anemones, unlike corals,  


(W) are colonial polyps. 
(X) are solitary polyps. 
(Y) have skeletons of limestone. 
(Z) have skeletons of calcium carbonate.  


ANSWER: X- ARE SOLITARY POLYPS
## TOSS-UP  


13. ERSC; Multiple Choice: The Great Rift Valley in Africa is a  


(W) mid-ocean ridge. 
(X) convergent plate boundary. 
(Y) divergent plate boundary. 
(Z) transform fault boundary.  


ANSWER: Y- DIVERGENT PLATE BOUNDARY  


## BONUS  


13. ERSC; Multiple Choice: A fossil fern that helps support the theory of continental drift is  


(W) Mesosaurus. 
(X) Glossopteris (pron: gloss-op'-ter-is). 
(Y) Glomar. 
(Z) Pangaea.  


ANSWER: X- GLOSSOPTERIS  


## TOSS-UP  


14. CHEM; Multiple Choice: Mendeleev arranged the elements in his periodic table in order of increasing  


(W) atomic number. 
(X) mass number. 
(Y) ionization energy. 
(Z) atomic mass.  


ANSWER: Z- ATOMIC MASS  


## BONUS  


14. CHEM; Multiple Choice: Electronegativity is the ability of an atom to  


(W) release electrons. 
(X) become an ion. 
(Y) conduct an electric current. 
(Z) attract electrons in a chemical bond.  


ANSWER: Z- ATTRACT ELECTRONS IN A CHEMICAL BOND
## TOSS-UP  


15. PHYS; Multiple Choice: A block of wood initially at rest slides down an inclined plane. Neglecting friction, the kinetic energy of the block at the bottom of the plane is  


(W) all converted into heat. 
(X) equal to its potential energy when it was at the top of the plane. 
(Y) less than its kinetic energy at the top of the plane. 
(Z) dependant on the materials of which the block is made.  


ANSWER: X- EQUAL TO ITS POTENTIAL ENERGY WHEN IT WAS AT THE TOP OF THE PLANE  


## BONUS  


15. PHYS; Short Answer: Name any four of the six quarks.  


ANSWER: UP, DOWN, CHARM, STRANGE, TOP (or truth), BOTTOM (or beauty)  


## TOSS-UP  


16. BIOL; Multiple Choice: Almost every kind of plant and animal is affected by one or more parasitic  


(W) flatworms. 
(X) ascarids. 
(Y) roundworms. 
(Z) cnidarians.  


ANSWER: Y- ROUNDWORMS  


## BONUS  


16. BIOL; Multiple Choice: The nervous system of a roundworm does not include  


(W) ganglia. 
(X) sense organs. 
(Y) nerves. 
(Z) a brain.  


ANSWER: Z- A BRAIN
## TOSS-UP  


17. CHEM; Multiple Choice: An example of an actinide element is  


(W) radium. 
(X) iridium. 
(Y) thorium. 
(Z) cerium.  


ANSWER: Y- THORIUM  


## BONUS  


17. CHEM; Multiple Choice: In the compound ammonia  


(W) each hydrogen has a partial negative charge. 
(X) the nitrogen has a full positive charge. 
(Y) the N-H bond is an ionic bond. 
(Z) the Lewis structure will have one unshared pair of electrons.  


ANSWER: Z- THE LEWIS STRUCTURE WILL HAVE ONE UNSHARED PAIR OF ELECTRONS  


## TOSS-UP  


18. MATH; Multiple Choice: In 1991 two scientists at Columbia University established a new record for the number of digits in the value of pi. Approximately how many digits did they produce?  


(W) 2 thousand 
(X) 2 million 
(Y) 2 billion 
(Z) 2 trillion  


ANSWER: Y- 2 BILLION  


## BONUS  


18. MATH; Short Answer: What is the term for the curve described by a uniform heavy flexible cord hanging freely between two points?  


ANSWER: CATENARY
## TOSS-UP  


19. ASTR; Multiple Choice: Dark, cooler areas on the sun's surface are called  


(W) sunspots. 
(X) solar flares. 
(Y) coronas. 
(Z) prominences.  


ANSWER: W- SUNSPOTS  


## BONUS  


19. ASTR; Multiple Choice: The Clouds of Magellan are two galaxies orbiting the Milky Way. What kind of galaxies are they?  


(W) normal spiral 
(X) barred spiral 
(Y) irregular 
(Z) elliptical  


ANSWER: Y- IRREGULAR  


## TOSS-UP  


20. BIOL; Multiple Choice: Most biologists believe that no other group of multicellular animals evolved from the  


(W) flatworms. 
(X) sponges. 
(Y) cnidarians. 
(Z) roundworms.  


ANSWER: X- SPONGES  


## BONUS  


20. BIOL; Multiple Choice: The gills of a clam are located in the  


(W) foot. 
(X) mantle. 
(Y) visceral mass. 
(Z) shell.  


ANSWER: Y- VISCERAL MASS
## TOSS-UP  


21. GENR; Short Answer: What yellow metal is an alloy of copper and zinc?  


ANSWER: BRASS  


## BONUS  


21. GENR; Short Answer: What is the name of the whale that has a long protruding tusk?  


ANSWER: NARWHAL  


## TOSS-UP  


22. ERSC; Short Answer: Humans first appeared during which Period?  


ANSWER: QUATERNARY  


## BONUS  


22. ERSC; Multiple Choice: A windless zone near the equator is called the  


(W) doldrums. 
(X) westerlies. 
(Y) easterlies. 
(Z) jet streams.  


ANSWER: W- DOLDRUMS
## TOSS-UP  


23. PHYS; Short Answer: What is the name of the Scottish physicist who developed the mathematical description of the theory of light?  


ANSWER: (JAMES CLERK) MAXWELL  


## BONUS  


23. PHYS; Short Answer: A current of 6 amperes flows through a 2 ohm resistor for 30 seconds. How many coulombs of charge have passed through the resistor?  


ANSWER: 180 COULOMBS  


## TOSS-UP  


24. COMP; Short Answer: Give the value of the largest integer that can be written as an 8-bit binary number.  


ANSWER: 255  


## BONUS  


24. COMP; Multiple Choice: Which of the following uses trial and error to learn from experiences, thus constantly improving them?  


(W) fuzzy logic systems 
(X) genetic algorithms 
(Y) expert systems 
(Z) intelligent agents  


ANSWER: X- GENETIC ALGORITHMS
## TOSS-UP  


25. GENR; Short Answer: What is the common name for a mammal that lays eggs?  


ANSWER: PLATYPUS OR ECHIDNA (ALSO CALLED SPINY ANTEATER)  


BONUS  


25. GENR; Multiple Choice: Who is called the Father of the Nuclear Navy?  


(W) Edward Teller  (X) Robert Oppenheimer  (Y) Hyman Rickover  (Z) Chester Nimitz  


ANSWER: Y- HYMAN RICKOVER