
# NATIONAL DOUBLE ELIMINATION - 9  


## TOSS-UP  


1. ERSC; Multiple Choice: The Andes Mountains of South America were formed at what kind of margin?  


(W) convergent plate 
(X) divergent plate 
(Y) hot spot 
(Z) transform fault boundary  


ANSWER: W-- CONVERGENT PLATE  


## BONUS  


1. ERSC; Multiple Choice: Which of the following is an example of a transform fault boundary?  


(W) Appalachian Mountains 
(X) Himalayas 
(Y) Mid-Atlantic Ridge 
(Z) San Andreas Fault  


ANSWER: Z-- SAN ANDREAS FAULT  


## TOSS-UP  


2. CHEM; Multiple Choice: As you move down from left to right across a period of the periodic table, the atomic radii of the elements  


(W) increase. 
(X) decrease. 
(Y) remain constant. 
(Z) show no pattern.  


ANSWER: X-- DECREASE  


## BONUS  


2. CHEM; Multiple Choice: Gases of all types are observed to have similar  


(W) densities, which are less than that of air. 
(X) physical properties and behavior. 
(Y) chemical properties and behavior. 
(Z) chemical composition and characteristics.  


ANSWER: X-- PHYSICAL PROPERTIES AND BEHAVIOR
## TOSS-UP  


3. COMP; Multiple Choice: Which of the following is a field of artificial intelligence that mimics human learning behavior and pattern recognition?  


(W) biometrics 
(X) perception systems 
(Y) natural language 
(Z) neural networks  


ANSWER: Z-- NEURAL NETWORKS  


## BONUS  


3. COMP; Multiple Choice: In what test does a human judge converse by means of a computer terminal with two entities hidden in another location?  


(W) a Turing test 
(X) a genetic algorithm 
(Y) natural language processing 
(Z) a perception test  


ANSWER: W-- A TURING TEST  


## TOSS-UP  


4. BIOL; Multiple Choice: One evolutionary trend is that more complex animals have a concentration of  


(W) blood vessels in the tail. 
(X) nerve cells in the head. 
(Y) muscle cells in the tentacles. 
(Z) bone cells in the body wall.  


ANSWER: X-- NERVE CELLS IN THE HEAD  


## BONUS  


4. BIOL; Multiple Choice: Mollusks that are carnivores drill through the shells of other animals by means of  


(W) radulas. 
(X) gills. 
(Y) shells. 
(Z) mantles.  


ANSWER: W-- RADULAS
## TOSS-UP  


5. PHYS; Multiple Choice: Newton's first law is often referred to as which of the following?  


(W) The law of straight-line motion 
(X) The law of momentum 
(Y) The law of inertia 
(Z) \(\mathrm{F} = \mathrm{ma}\)  


ANSWER: Y- - THE LAW OF INERTIA  


## BONUS  


5. PHYS; Multiple Choice: The statement, "In regions where fluid velocity is smaller, the pressure is higher, and vice versa," is known as the principle of  


(W) Pascal. 
(X) Bernoulli. 
(Y) Torricelli. 
(Z) Archimedes.  


ANSWER: X- - BERNOULLI  


## TOSS-UP  


6. GENR; Multiple Choice: What radioactive element is routinely used in treating hyperthyroidism, and in reducing thyroid activity?  


(W) Iron- 59 
(X) Gold- 198 
(Y) Cobalt- 60 
(Z) Iodine- 131  


ANSWER: Z- - IODINE- 131  


## BONUS  


6. GENR; Multiple Choice: The Statue of Liberty is green because of  


(W) green stone. 
(X) oxidized brass. 
(Y) steel painted green. 
(Z) oxidized copper.  


ANSWER: Z- - OXIDIZED COPPER
## TOSS-UP  


7. CHEM; Multiple Choice: The ideal gas law describes the behavior of real gases under  


(W) all conditions of temperature and pressure. 
(X) most ordinary conditions of temperature and pressure. 
(Y) low temperatures and high-pressure conditions. 
(Z) any specified temperature and pressure conditions.  


ANSWER: X- MOST ORDINARY CONDITIONS OF TEMPERATURE AND PRESSURE  


## BONUS  


7. CHEM; Multiple Choice: Two simplifying, but false, assumptions of the ideal gas law are that gas particles exert no attractive forces upon one another and gas particles  


(W) have elastic collisions. 
(X) are separated by large distances. 
(Y) are in constant random motion. 
(Z) have no volume of their own.  


ANSWER: Z- - HAVE NO VOLUME OF THEIR OWN  


## TOSS-UP  


8. ASTR; Short Answer: The earth's core is predominantly composed of  


ANSWER: IRON  


## BONUS  


8. ASTR; Multiple Choice: Between 1984 and 1991, Pluto and its moon Charon eclipsed each other every three days, as seen from Earth. Since then, the orbit of Pluto and Charon has tipped. How many years will it be before eclipses will again be visible from Earth?  


(W) 15 
(X) 33 
(Y) 97 
(Z) 124  


ANSWER: Z- - 124
## TOSS-UP  


9. BIOL; Multiple Choice: Like many marine annelids, earthworms have  


(W) statocysts. 
(X) two pairs of eyes. 
(Y) sensory tentacles. 
(Z) sensory cells in the skin.  


ANSWER: Z- - SENSORY CELLS IN THE SKIN  


## BONUS  


9. BIOL; Multiple Choice: By grinding and partially digesting incredible amounts of soil, earthworms speed the return to plants of  


(W) nitrogen. 
(X) carbon dioxide. 
(Y) oxygen. 
(Z) hydrogen.  


ANSWER: W- - NITROGEN  


## TOSS-UP  


10. MATH; Multiple Choice: Which of the following functions is NOT a transcendental function?  


(W) trigonometric 
(X) algebraic 
(Y) logarithmic 
Z) exponential  


ANSWER: X- - ALGEBRAIC  


## BONUS  


10. MATH; Short Answer: What is the next term in the following geometric progression 0, 2, 6, 12, 20?  


ANSWER: 30 (the geometric function happens to be x squared - x)
## TOSS-UP  


11. PHYS; Multiple Choice: The electric field pattern for a point charge looks the same as the electric field  


(W) just outside a cube of charge. 
(X) inside a spherical shell of charge. 
(Y) outside a spherical shell of charge. 
(Z) none of the above  


ANSWER: Y- - OUTSIDE A SPHERICAL SHELL OF CHARGE  


## BONUS  


11. PHYS; Multiple Choice: The electric potential of a point charge varies  


(W) linearly with distance and inversely with charge. 
(X) linearly with distance and inversely with charge squared. 
(Y) linearly with charge and inversely with distance squared. 
(Z) linearly with charge and inversely with distance.  


ANSWER: Z- - LINEARLY WITH CHARGE AND INVERSELY WITH DISTANCE  


## TOSS-UP  


12. CHEM; Multiple Choice: Which of the following is a derived unit?  


(W) Ampere 
(X) Newton 
(Y) Mole 
(Z) Kelvin  


ANSWER: X- - NEWTON  


## BONUS  


12. CHEM; Multiple Choice: How should you round off a number that ends with the digit 5?  


(W) Round down. 
(X) Round up. 
(Y) Round off so that the last digit you retain has an even value. 
(Z) Round off so that the last digit you retain has an odd value.  


ANSWER: Y- - ROUND OFF SO THAT THE LAST DIGIT YOU RETAIN HAS AN EVEN VALUE
## TOSS-UP  


13. COMP; Multiple Choice: A narrative that describes the logic and processing flow of a program is called  


(W) a hierarchy chart. 
(X) a flowchart. 
(Y) pseudocode. 
(Z) CASE (spell out).  


ANSWER: Y- - PSEUDOCODE  


## BONUS  


13. COMP; Short Answer: The 1994 Draper Prize for Engineering, worth \(375,000, was given for the development of FORTRAN. Name the recipient.  


ANSWER: (JOHN) BACKUS  


## TOSS-UP  


14. BIOL; Multiple Choice: Ocean plankton consists of many very small  


(W) oligochaetes. 
(X) polychaetes. 
(Y) hirudineans. 
(Z) gastropods.  


ANSWER: X- - POLYCHAETES  


## BONUS  


14. BIOL; Multiple Choice: The cephalopod whose internal shell is either thin and coiled or flat and platelike is the  


(W) octopus. 
(X) cuttlefish. 
(Y) squid. 
(Z) nautilus.  


ANSWER: X- - CUTTLEFISH
## TOSS-UP  


15. ASTR; Short Answer: Halley's comet appears in the sky about every 76 years. Within two years, when is it due again?  


ANSWER: 2061 (ACCEPT 2059- 2063)  


## BONUS  


15. ASTR; Multiple Choice: Because it is tipped on its axis like Earth, Mars has four seasons. Approximately how long is each season on Mars?  


(W) 2 months (X) 4 months (Y) 6 months (Z) 8 months  


ANSWER: Y-- 6 MONTHS  


## TOSS-UP  


16. PHYS; Multiple Choice: A wavelength can be measured by which one of the following units?  


(W) radians (X) angstroms (Y) electron volts (Z) seconds  


ANSWER: X-- ANGSTROMS  


## BONUS  


16. PHYS; Short Answer: What three colors form the picture in a color TV?  


ANSWER: RED GREEN BLUE
## TOSS-UP  


17. CHEM; Multiple Choice: Which of the following techniques cannot be used to separate homogeneous mixtures?  


(W) distillation 
(X) crystallization 
(Y) chromatography 
(Z) filtration  


ANSWER: Z-- FILTRATION  


## BONUS  


17. CHEM; Multiple Choice: Pure substances include  


(W) elements only. 
(X) elements and compounds. 
(Y) compounds and mixtures. 
(Z) elements and mixtures.  


ANSWER: X-- ELEMENTS AND COMPOUNDS  


## TOSS-UP  


18. ERSC; Multiple Choice: The longest division in geologic time is  


(W) an epoch. 
(X) a period. 
(Y) a century. 
(Z) an era.  


ANSWER: Z-- AN ERA  


## BONUS  


18. ERSC; Multiple Choice: Angiosperms are the dominant land plant today because they developed  


(W) deep root systems. 
(X) hard seed coats. 
(Y) large, broad leaves. 
(Z) heavy, thick bark.  


ANSWER: X-- HARD SEED COATS
## TOSS-UP  


19. GENR; Short Answer: What is meant by the statement that an animal is oviparous? (pron: o-vip'-ar-us)  


ANSWER: IT LAYS EGGS  


## BONUS  


19. GENR; Short Answer: Name the satellite that was launched 40 years ago, in March 1958, and is still orbiting the earth.  


ANSWER: VANGUARD I (accept VANGUARD)  


## TOSS-UP  


20. PHYS; Short Answer: What number represents the ratio of the speed of an object to the speed of sound in the surrounding air?  


ANSWER: MACH NUMBER  


## BONUS  


20. PHYS; Multiple Choice: The physicist James Chadwick is known for his association with  


(W) the alpha particle.  


(X) the neutron.  


(Y) the cloud chamber.  


(Z) the electron.  


ANSWER: X-- THE NEUTRON
# TOSS-UP  


21. BIOL; Short Answer: Antidiurtic hormone, which controls water reabsorption in the kidney is produced by the  


ANSWER: PITUITARY GLAND  


BONUS  


21. BIOL; Multiple Choice: Fleas can carry  


(W) yellow fever. 
(X) sleeping sickness. 
(Y) bubonic plague. 
(Z) malaria.  


ANSWER: Y- BUBONIC PLAGUE  


## TOSS-UP  


22. CHEM; Short Answer: What term describes the process when a solid phase changes directly to the gas phase?  


ANSWER: SUBLIMATION  


## BONUS  


22. CHEM; Multiple Choice: "Under the same conditions of temperature and pressure, the volumes of reacting gases and of their gaseous products are expressed in ratios of small whole numbers." This law is attributed to  


(W) Dalton. 
(X) Gay-Lussac. 
(Y) Ramsay. 
(Z) Avogadro.  


ANSWER: X- GAY-LUSSAC
## TOSS-UP  


23. PH YS; Short Answer: Two bodies are moving in circular paths of equal radii. If the speed of the first body is twice that of the second, the centripetal acceleration of the first body is how many times greater than that of the second body?ANSWER: 4 (TIMES)  


ANSWER: 4 (TIMES)  


## BONUS  


23. PH YS; Multiple Choice: At the instant a vibrating mass on a spring passes through its equilibrium position it is acted upon by  


(W) a continuous positive force. 
(X) a continuous negative force. 
(Y) a large force. 
(Z) no net force.  


ANSWER: Z- - NO NET FORCE  


## TOSS-UP  


24. MATH; Short Answer: How many edges does a tetrahedron have?ANSWER: SIX  


ANSWER: SIX  


## BONUS  


24. MATH; Short Answer: Two people are 10 kilometers apart, walking toward each other, each at a rate of 1 kilometer per hour. A bee flies back and forth between their noses at the rate of 10 kilometers per hour until the people meet. How many kilometers will the bee have traveled before the people meet?ANSWER: 50 KILOMETERS  


ANSWER: 50 KILOMETERS
## TOSS-UP  


25. BIOL; Short Answer: How many thoracic vertebrae are there in the human body?  


ANSWER: 12  


## BONUS  


25. BIOL; Multiple Choice: In a grasshopper, the eardrums are located  


(W) behind the legs. 
(X) on the antennae. 
(Y) under the compound eyes. 
(Z) under the simple eye.  


ANSWER: W-- BEHIND THE LEGS