title[[370, 52, 628, 70]]
# NATIONAL ROUND ROBIN - 5  

sub_title[[460, 82, 536, 100]]
## TOSS-UP  

text[[80, 112, 716, 146]]
1. GENR; Multiple Choice: Which of the following units is the one most often used to measure radiation exposure in humans?  

text[[120, 159, 228, 223]]
(W) Rem 
(X) Curie 
(Y) Becquerel 
(Z) Roentgen  

text[[120, 235, 280, 252]]
ANSWER: W- REM  

sub_title[[465, 265, 532, 282]]
## BONUS  

text[[80, 295, 748, 328]]
1. GENR; Multiple Choice: When does equilibrium, such as liquid-solid or liquid-gaseous, exist between two phases?  

text[[120, 340, 645, 433]]
(W) The rate of reaction is not affected by raising or lowering either the temperature or the pressure. 
(X) The rate of reaction between the two phases becomes zero. 
(Y) The individual molecules in each phase remain stationary. 
(Z) An equal number of atoms or molecules is continually interchanged between the phases.  

text[[105, 445, 734, 479]]
ANSWER: Z- AN EQUAL NUMBER OF ATOMS OR MOLECULES IS CONTINUALLY INTERCHANGED BETWEEN THE PHASES  

sub_title[[460, 508, 536, 525]]
## TOSS-UP  

text[[79, 530, 564, 548]]
2. PHYS; Multiple Choice: A computer chip is best described as  

text[[120, 561, 373, 623]]
(W) an integrated circuit. 
(X) a transistor circuit. 
(Y) an etched plate of germanium. 
(Z) a diode.  

text[[105, 636, 419, 653]]
ANSWER: W- INTEGRATED CIRCUIT  

sub_title[[465, 675, 532, 692]]
## BONUS  

text[[79, 696, 592, 714]]
2. PHYS; Multiple Choice: An example of a direct heating system is  

text[[104, 727, 275, 788]]
(W) a hot-water heater. 
(X) a heat pump. 
(Y) steam heating. 
(Z) all of the above  

text[[105, 801, 338, 818]]
ANSWER: X- A HEAT PUMPsub_title[[460, 67, 536, 84]]
## TOSS-UP  

text[[78, 97, 758, 131]]
3. BIOL; Multiple Choice: Although infections occur each day, an infectious disease results only when a pathogen injures a person's  

text[[120, 144, 323, 206]]
(W) blood. 
(X) cells and tissues. 
(Y) temperature regulation. 
(Z) fever mechanism.  

text[[120, 219, 408, 236]]
ANSWER: X- CELLS AND TISSUES  

sub_title[[466, 250, 532, 267]]
## BONUS  

text[[78, 280, 494, 298]]
3. BIOL; Multiple Choice: Athlete's foot is caused by a  

text[[120, 311, 260, 373]]
(W) dermatophyte. 
(X) virus. 
(Y) rickettsia. 
(Z) bacterium.  

text[[120, 386, 388, 404]]
ANSWER: W- DERMATOPHYTE  

sub_title[[460, 448, 536, 465]]
## TOSS-UP  

text[[78, 478, 741, 511]]
4. ASTR; Multiple Choice: As a star like our Sun ages it passes through distinct stages, in this order  

text[[104, 524, 486, 586]]
(W) Planetary Nebula, Main Sequence, White dwarf. 
(X) Planetary Nebula, White Dwarf, Red Giant 
(Y) Main Sequence, Red Giant, White Dwarf 
(Z) Main Sequence, Red Giant, Supernova  

text[[104, 599, 613, 617]]
ANSWER: Y- MAIN SEQUENCE, RED GIANT, WHITE DWARF  

sub_title[[466, 630, 532, 647]]
## BONUS  

text[[78, 660, 470, 678]]
4. ASTR; Multiple Choice: The Saros cycle refers to  

text[[120, 691, 575, 754]]
(W) The 11 year solar sunspot cycle. 
(X) An 18.6 year cycle of eclipses. 
(Y) The 25,800 year cycle of the precession of the Earth's axis. 
(Z) The 29.5 day synodic lunar month.  

text[[120, 766, 522, 784]]
ANSWER: X- AN 18.6 YEAR CYCLE OF ECLIPSESsub_title[[460, 52, 535, 69]]
## TOSS-UP  

text[[78, 82, 766, 102]]
5. CHEM; Multiple Choice: Which of the following is a polysaccharide made only by plants?  

text[[104, 114, 207, 178]]
(W) Ribose (X) Starch (Y) Glycogen (Z) Lactose  

text[[105, 190, 288, 207]]
ANSWER: X- STARCH  

sub_title[[466, 220, 532, 237]]
## BONUS  

text[[78, 250, 710, 270]]
5. CHEM; Multiple Choice: What of the following metals is the best reducing agent?  

text[[120, 281, 230, 344]]
(W) Gold (X) Copper (Y) Potassium (Z) Magnesium  

text[[120, 356, 335, 373]]
ANSWER: Y- POTASSIUM  

sub_title[[460, 417, 535, 435]]
## TOSS-UP  

text[[78, 448, 841, 482]]
6. COMP; Multiple Choice: The adjustment of space between pairs of characters so the overall spacing looks even is called  

text[[120, 495, 280, 556]]
(W) compression. (X) kerning. (Y) winchester. (Z) none of the above  

text[[120, 569, 320, 586]]
ANSWER: X- KERNING  

sub_title[[466, 599, 532, 616]]
## BONUS  

text[[78, 629, 604, 648]]
6. COMP; Multiple Choice: Which of these machines is most general?  

text[[120, 660, 415, 723]]
(W) Deterministic Finite Automaton (X) Nondeterministic Finite Automaton (Y) Turing Machine (Z) Pushdown Automaton  

text[[120, 735, 395, 753]]
ANSWER: Y- TURING MACHINEsub_title[[460, 52, 535, 70]]
## TOSS-UP  

text[[80, 83, 805, 102]]
7. BIOL; Multiple Choice: E. coli prevents the growth of harmful bacteria in the intestinal tract by  

text[[104, 115, 445, 177]]
(W) producing antibiotics that kill them. 
(X) using the nutrients they need to live. 
(Y) producing drugs that prevent their growth. 
(Z) producing carcinogens that destroy them.  

text[[105, 189, 612, 207]]
ANSWER: X- USING THE NUTRIENTSTHEY NEED TO LIVE  

sub_title[[466, 220, 532, 237]]
## BONUS  

text[[78, 250, 636, 269]]
7. BIOL; Multiple Choice: Typhus is transmitted from person to person by  

text[[118, 282, 230, 344]]
(W) viruses. 
(X) rickettsias. 
(Y) ticks. 
(Z) body lice.  

text[[118, 357, 330, 374]]
ANSWER: Z- BODY LICE  

sub_title[[460, 418, 535, 436]]
## TOSS-UP  

text[[78, 449, 785, 482]]
8. PHYS; Multiple Choice: The cathode-ray tube in a color television is different from a simple cathode-ray tube in that  

text[[120, 495, 666, 558]]
(W) in a color television, the screen is coated with many different colors. 
(X) in a color television, the screen is red, blue, and green. 
(Y) only one electron gun is necessary in a color television. 
(Z) there are three electron guns in a cathode-ray tube in a color television.  

text[[118, 570, 738, 602]]
ANSWER: Z- THERE ARE THREE ELECTRON GUNS IN A CATHODE- RAY TUBE IN A COLOR TELEVISION  

sub_title[[466, 615, 532, 632]]
## BONUS  

text[[78, 645, 488, 663]]
8. PHYS; Multiple Choice: Convection is the result of  

text[[120, 677, 529, 739]]
(W) currents caused by the motion of heated molecules. 
(X) increases in the density of solids. 
(Y) colder portions of liquids rising. 
(Z) the lack of heat transfer.  

text[[118, 751, 782, 769]]
ANSWER: W- CURRENTSCAUSED BY THE MOTION OF HEATED MOLECULESsub_title[[460, 52, 535, 69]]
## TOSS-UP  

text[[78, 82, 763, 115]]
9. ERSC; Multiple Choice: Granular, aphanitic and glassy are terms to describe what feature of an igneous rock?  

text[[105, 130, 231, 192]]
(W) Relief 
(X) Composition 
(Y) Texture 
(Z) Schistocity  

text[[106, 205, 303, 221]]
ANSWER: Y- TEXTURE  

sub_title[[465, 234, 532, 251]]
## BONUS  

text[[79, 265, 741, 313]]
9. ERSC; Short Answer: Shales deposited in lakes often exhibit summer and winter layers that differ in color and texture and can be counted much like growth rings in trees. What are these layers called?  

text[[106, 325, 259, 342]]
ANSWER: VARVES  

sub_title[[460, 388, 535, 405]]
## TOSS-UP  

text[[80, 418, 777, 437]]
10. CHEM; Multiple Choice: The metals at the top of the activity series replace hydrogen from  

text[[120, 450, 322, 511]]
(W) water and acids. 
(X) acids but not water. 
(Y) water but not acids. 
(Z) neither water nor acids.  

text[[120, 523, 401, 541]]
ANSWER: W- WATER AND ACIDS  

sub_title[[465, 555, 532, 572]]
## BONUS  

text[[80, 585, 615, 603]]
10. CHEM; Multiple Choice: Photographic film contains an emulsion of  

text[[105, 616, 260, 678]]
(W) silver chloride. 
(X) silver bromide. 
(Y) iron sulfide. 
(Z) sodium perborate.  

text[[106, 691, 370, 708]]
ANSWER: X- SILVER BROMIDEsub_title[[460, 68, 535, 84]]
## TOSS-UP  

text[[80, 91, 451, 108]]
11. BIOL; Multiple Choice: Malaria is caused by a  

text[[120, 122, 228, 184]]
(W) mosquito. 
(X) virus. 
(Y) flea. 
(Z) protozoan.  

text[[120, 197, 346, 213]]
ANSWER: Z- PROTOZOAN  

sub_title[[466, 220, 532, 236]]
## BONUS  

text[[80, 243, 750, 276]]
11. BIOL; Multiple Choice: Unfortunately, antibiotics used to fight off bacterial infection in the throat kill symbiotic  

text[[120, 289, 311, 351]]
(W) Pasteurella pestis. 
(X) Clostridium tetani. 
(Y) E. coli. 
(Z) Neisseria gonorrhea.  

text[[120, 364, 298, 381]]
ANSWER: Y- E. COLI  

sub_title[[460, 410, 535, 426]]
## TOSS-UP  

text[[80, 433, 742, 466]]
12. CHEM; Multiple Choice: In the formula for a polyatomic ion, the algebraic sum of the individual oxidation numbers of all the atoms is equal to  

text[[120, 472, 305, 535]]
(W) 0. 
(X) +1. 
(Y) -1. 
(Z) the charge of the ion.  

text[[120, 547, 462, 564]]
ANSWER: Z- THE CHARGE OF THE ION  

sub_title[[466, 586, 532, 602]]
## BONUS  

text[[80, 608, 760, 640]]
12. CHEM; Multiple Choice: How do oxidation and reduction relate to changes in oxidation number?  

text[[120, 654, 707, 746]]
(W) Oxidation occurs when oxidation number increases, and reduction occurs when oxidation number decreases. 
(X) Oxidation occurs when oxidation number decreases, and reduction occurs when oxidation number increases. 
(Y) Both oxidation and reduction correspond to a decrease in oxidation number. 
(Z) Both oxidation and reduction correspond to an increase in oxidation number.  

text[[106, 763, 760, 796]]
ANSWER: W- OXIDATION OCCURS WHEN OXIDATION NUMBER INCREASES, AND REDUCTION OCCURS WHEN OXIDATION NUMBER DECREASES.sub_title[[460, 52, 536, 69]]
## TOSS-UP  

text[[80, 82, 745, 115]]
13. MATH; Multiple Choice: In the conic section A squared plus B squared - 4A + 2B = 0, which line is an axis of symmetry?  

text[[104, 130, 201, 192]]
W) \(\mathrm{A} = 1\) X) \(\mathrm{B} = - 2\) Y) \(\mathrm{B} = - \mathrm{A} / 2\) Z) \(\mathrm{B} = \mathrm{A} - 1\)  

text[[120, 205, 303, 222]]
ANSWER: \(\mathrm{Y} - \mathrm{B} = - \mathrm{A} / 2\)  

sub_title[[466, 228, 532, 245]]
## BONUS  

text[[80, 250, 755, 283]]
13. MATH; Multiple Choice: Sides of a triangle form three consecutive terms of a geometric sequence with a common ratio R. R is  

text[[104, 296, 250, 358]]
W) less than 2. X) greater than 2. Y) equal to 2. Z) none of the above  

text[[120, 370, 350, 387]]
ANSWER: W- LESS THAN 2  

sub_title[[460, 417, 536, 434]]
## TOSS-UP  

text[[80, 448, 746, 481]]
14. GNNR; Multiple Choice: Which of the following best explains why a car is a safe haven during a lightening storm?  

text[[119, 494, 747, 585]]
(W) A car is relatively closer to the ground than nearby objects, therefore lightening is not attracted to it. 
(X) The car's metal body acts as a Faraday cage, protecting its occupants. 
(Y) The car's rubber tires act as insulators from the car to the ground. 
(Z) The car's movement develops a positive electrical potential on its body, thereby repelling the positive electrical potential of the lightning.  

text[[119, 597, 800, 630]]
ANSWER: X- THE CAR'S METAL BODY ACTS AS A FARADAY CAGE, PROTECTING ITS OCCUPANTS.  

sub_title[[466, 636, 532, 653]]
## BONUS  

text[[80, 667, 545, 685]]
14. GNNR; Multiple Choice: A major function of a refractory is  

text[[104, 699, 468, 761]]
(W) the conduction of heat. 
(X) for heat insulation. 
(Y) as a source of essential reactants for smelting. 
(Z) as a source of flux material for slag formation.  

text[[105, 774, 425, 790]]
ANSWER: X- FOR HEAT INSULATIONsub_title[[460, 68, 535, 84]]
## TOSS-UP  

text[[80, 97, 745, 130]]
15. BIOL; Multiple Choice: Constant sunbathing can result in skin cancer because, in skin cells, ultraviolet light can produce  

text[[104, 144, 280, 207]]
(W) mutations in DNA. 
(X) extra dark pigment. 
(Y) carcinogens. 
(Z) oncogenes.  

text[[105, 220, 400, 237]]
ANSWER: W- MUTATIONS IN DNA  

sub_title[[466, 250, 531, 267]]
## BONUS  

text[[80, 280, 559, 298]]
15. BIOL; Multiple Choice: The final step in Koch's postulates is  

text[[118, 311, 774, 389]]
(W) injecting microorganisms from a pure culture into a host to produce the disease. 
(X) resiotating the microorganism from the infected host and identifying it as the original microorganism. 
(Y) finding the suspected microorganism in an ill organism but not in a healthy organism. 
(Z) isolating the suspected microorganism and growing a pure culture.  

text[[105, 401, 792, 434]]
ANSWER: X- REISOLATING THE MICROORGANISM FROM THE INFECTED HOST AND IDENTIFYING IT AS THE ORIGINAL MICROORGANISM  

sub_title[[460, 463, 535, 480]]
## TOSS-UP  

text[[80, 494, 762, 526]]
16. ASTR; Multiple Choice: Stellar spectroscopy analyzes light emitted by atoms due to what process?  

text[[120, 540, 456, 602]]
(W) Electrons jumping to lower energy levels. 
(X) Vibrations of the electron orbitals. 
(Y) The photoelectric effect. 
(Z) The weak force.  

text[[119, 614, 679, 632]]
ANSWER: W- ELECTRONS JUMPING TO LOWER ENERGY LEVELS  

sub_title[[466, 645, 531, 662]]
## BONUS  

text[[80, 675, 777, 709]]
16. ASTR; Short Answer: Two identical black bodies are heated in outer space so that one is twice as hot as the other. What is the ratio of the total energy radiated by the two objects?  

text[[105, 721, 248, 738]]
ANSWER: 16 TO 1sub_title[[460, 67, 536, 84]]
## TOS-UP  

text[[80, 97, 632, 116]]
17. PHYS; Multiple Choice: The heat of the Earth or outside air is used by  

text[[105, 130, 328, 191]]
(W) warm-air systems. 
(X) heat-pump systems. 
(Y) steam-heating systems. 
(Z) radiant hot-water systems.  

text[[106, 204, 407, 221]]
ANSWER: X- HEAT-PUMP SYSTEMS  

sub_title[[466, 234, 532, 251]]
## BONUS  

text[[80, 265, 613, 283]]
17. PHYS; Multiple Choice: Active and passive heating are two types of  

text[[105, 297, 333, 360]]
(W) radiant heating systems. 
(X) hot-water heating systems. 
(Y) solar-heating systems. 
(Z) warm-air heating systems.  

text[[105, 371, 448, 389]]
ANSWER: Y- SOLAR- HEATING SYSTEMS  

sub_title[[460, 433, 536, 450]]
## TOS-UP  

text[[80, 463, 675, 482]]
18. CHEM; Multiple Choice: Which of the following is a strong oxidizing agent?  

text[[105, 495, 225, 556]]
(W) Sodium 
(X) Fluorine 
(Y) Zinc 
(Z) Magnesium  

text[[105, 569, 312, 586]]
ANSWER: X- FLUORINE  

sub_title[[466, 600, 532, 616]]
## BONUS  

text[[80, 630, 691, 648]]
18. CHEM; Multiple Choice: Which of the following is not an example of a bleach?  

text[[105, 661, 280, 723]]
(W) Chlorine 
(X) Hypochlorite ion 
(Y) Chloride ion 
(Z) Hydrogen peroxide  

text[[105, 735, 357, 753]]
ANSWER: Y- CHLORIDE IONsub_title[[460, 52, 535, 69]]
## TOSS-UP  

text[[81, 82, 723, 131]]
19. ERSC; Multiple Choice: The process of lithification converts unconsolidated earth materials into sedimentary rock. Which one of the following is not associated with this process?  

text[[120, 144, 264, 206]]
(W) Cementation 
(X) Compaction 
(Y) Crystallization 
(Z) Fractionization  

text[[120, 219, 401, 236]]
ANSWER: Z- FRACTIONIZATION  

sub_title[[466, 250, 532, 266]]
## BONUS  

text[[80, 280, 472, 298]]
19. ERSC; Multiple Choice: Darcy's Law pertains to  

text[[105, 311, 380, 374]]
(W) Sea floor spreading. 
(X) Fluid flow through porous media. 
(Y) Karst Geomorphology. 
(Z) Structural Geology.  

text[[105, 386, 567, 404]]
ANSWER: X- FLUID FLOW THROUGH POROUS MEDIA  

sub_title[[460, 433, 535, 450]]
## TOSS-UP  

text[[78, 463, 808, 482]]
20. COMP; Multiple Choice: SQL is a query language for relational databases. It is an acronym for  

text[[105, 495, 336, 558]]
(W) Simple Query Language. 
(X) Sybase Query Language. 
(Y) Standard Query Language. 
(Z) Structured Query language.  

text[[105, 570, 507, 587]]
ANSWER: Z- STRUCTURED QUERY LANGUAGE  

sub_title[[466, 600, 532, 617]]
## BONUS  

text[[78, 630, 774, 664]]
20. COMP; Multiple Choice: In the ASCII character set, what is the order of lower case letters, numbers, and uppercase letters?  

text[[120, 677, 608, 739]]
(W) Numbers precede uppercase letters, which precede lowercase. 
(X) Uppercase letters precede lowercase, which precede numbers. 
(Y) Numbers precede lowercase letters, which precede uppercase. 
(Z) Lowercase letters precede uppercase, which precede numbers.  

text[[105, 751, 749, 784]]
ANSWER: W- NUMBERS PRECEDE UPPERCASE LETTERS, WHICH PRECEDE LOWERCASEsub_title[[460, 51, 536, 69]]
## TOSS-UP  

text[[78, 82, 900, 101]]
21. BIOL; Short Answer: What kind of speciation is the appearance of a new species within a single population?  

text[[105, 113, 293, 130]]
ANSWER: SYMPATRIC  

sub_title[[466, 143, 532, 161]]
## BONUS  

text[[78, 174, 729, 193]]
21. BIOL; Multiple Choice: Any successful invasion of the body by a pathogen results in  

text[[120, 206, 312, 268]]
(W) an infection. 
(X) a disease. 
(Y) a specific defense. 
(Z) a nonspecific defense.  

text[[120, 280, 370, 297]]
ANSWER: W- AN INFECTION  

sub_title[[460, 342, 536, 360]]
## TOSS-UP  

text[[78, 372, 760, 406]]
22. MATH; Short Answer: If two sides of a quadrilateral are parallel and the other two sides are equal but NOT parallel, the quadrilateral is known as a  

text[[120, 417, 310, 435]]
ANSWER: TRAPEZOID  

sub_title[[466, 448, 532, 465]]
## BONUS  

text[[78, 478, 784, 512]]
22. MATH; Multiple Choice: Bill cuts the pie he baked into ten equal pieces. My piece happens to measure about 6 cm at the wide end. Approximately what is the diameter of the pie?  

text[[120, 524, 193, 585]]
W) 10 cm X) 20 cm Y) 6 cm Z) 25 cm  

text[[120, 599, 284, 616]]
ANSWER: X- 20 CMsub_title[[460, 67, 536, 84]]
## TOS-UP  

text[[78, 97, 612, 115]]
23. PHYS; Short Answer: A long coil of wire with many loops is called a  

text[[105, 128, 285, 144]]
ANSWER: SOLENOID  

sub_title[[466, 159, 532, 176]]
## BONUS  

text[[78, 189, 513, 207]]
23. PHYS; Multiple Choice: A heat pump's value is that it  

text[[105, 220, 245, 283]]
(W) converts heat. 
(X) absorbs heat. 
(Y) transfers heat. 
(Z) generates heat.  

text[[105, 295, 374, 312]]
ANSWER: Y- TRANSFERS HEAT  

sub_title[[460, 357, 536, 374]]
## TOS-UP  

text[[78, 387, 825, 405]]
24. CHEM; Short Answer: An invisible, weightless fluid once proposed as the basis of heat was called  

text[[105, 417, 271, 434]]
ANSWER: CALORIC  

sub_title[[466, 448, 532, 465]]
## BONUS  

text[[78, 478, 718, 496]]
24. CHEM; Multiple Choice: An activity series of metals lists metals according to their  

text[[120, 509, 285, 570]]
(W) electronegativity. 
(X) nuclear instability. 
(Y) relative reactivity. 
(Z) electron affinity.  

text[[120, 584, 435, 601]]
ANSWER: Y- RELATIVE REACTIVITYsub_title[[460, 67, 535, 84]]
## TOSS-UP  

text[[79, 97, 567, 115]]
25. PHYS; Short Answer: State the unit of magnetic field strength.  

text[[105, 128, 390, 145]]
ANSWER: TESLA (ACCEPT GAUSS)  

sub_title[[466, 159, 532, 175]]
## BONUS  

text[[79, 188, 618, 207]]
25. PHYS; Multiple Choice: In a typical refrigerator system using Freon,  

text[[120, 220, 631, 281]]
(W) liquid Freon evaporates in the compressor. 
(X) Freon gains heat in the condenser coils. 
(Y) Freon vapor returns to the storage tank. 
(Z) heat from the freezer compartment is absorbed in the freezer unit.  

text[[120, 294, 736, 327]]
ANSWER: Z- HEAT FROM THE FREEZER COMPARTMENT IS ABSORBED IN THE FREEZER UNIT