title[[372, 52, 626, 70]]
# NATIONAL ROUND ROBIN-6  

sub_title[[460, 82, 535, 100]]
## TOSS-UP  

text[[80, 112, 535, 131]]
1. ASTR; Multiple Choice: A total solar eclipse is likely when  

text[[120, 144, 434, 207]]
(W) Full moon occurs at descending node. 
(X) New moon occurs at ascending node. 
(Y) New moon occurs at apogee. 
(Z) New moon occurs at perigee.  

text[[120, 219, 608, 237]]
ANSWER: X- NEW MOON OCCURS AT ASCENDING NODE  

sub_title[[466, 250, 532, 267]]
## BONUS  

text[[80, 280, 499, 298]]
1. ASTR; Multiple Choice: The Zodiacal Light is due to  

text[[120, 311, 562, 375]]
(W) scattering of Sunlight from interplanetary dust particles. 
(X) refraction of Sunlight by the Earth's Atmosphere. 
(Y) scattering of Sunlight by ice crystals in the stratosphere. 
(Z) multiple reflection of Sunlight between the Moon and the Earth.  

text[[120, 386, 704, 419]]
ANSWER: W- SCATTERING OF SUNLIGHT FROM INTERPLANETARY DUST PARTICLES  

sub_title[[460, 463, 535, 481]]
## TOSS-UP  

text[[78, 494, 766, 528]]
2. BIOL; Multiple Choice: The immune system responds to a serious infection by producing white blood cells and  

text[[105, 541, 255, 602]]
(W) mucus. 
(X) marker proteins. 
(Y) pain. 
(Z) fever.  

text[[105, 615, 277, 632]]
ANSWER: Z- FEVER  

sub_title[[466, 636, 532, 653]]
## BONUS  

text[[78, 664, 795, 683]]
2. BIOL; Multiple Choice: One advantage of fever is that a higher-than-normal temperature may  

text[[120, 695, 427, 758]]
(W) cause an increase of lymphocytes. 
(X) increase growth of some viruses. 
(Y) stop growth of some microorganisms. 
(Z) cause an increase in agglutination.  

text[[120, 770, 616, 788]]
ANSWER: Y- STOP GROWTH OF SOME MICROORGANISMSsub_title[[460, 52, 535, 69]]
## TOSS-UP  

text[[79, 83, 395, 101]]
3. PHYS; Multiple Choice: Heat engines  

text[[104, 115, 445, 177]]
(W) produce heat. 
(X) convert mechanical energy to heat energy. 
(Y) convert heat energy to mechanical energy. 
(Z) change steam to water.  

text[[104, 189, 675, 207]]
ANSWER: Y- CONVERT HEAT ENERGY TO MECHANICAL ENERGY  

sub_title[[466, 220, 532, 237]]
## BONUS  

text[[78, 250, 664, 269]]
3. PHYS; Multiple Choice: Heat engines are classified according to where the  

text[[104, 282, 322, 344]]
(W) compression takes place. 
(X) combustion takes place. 
(Y) exhaust takes place. 
(Z) intake takes place.  

text[[104, 356, 460, 373]]
ANSWER: X- COMBUSTION TAKES PLACE  

sub_title[[460, 418, 535, 435]]
## TOSS-UP  

text[[78, 449, 770, 482]]
4. CHEM; Multiple Choice: In a redox reaction, how do the numbers of electrons gained and lost compare?  

text[[104, 495, 562, 558]]
(W) The two numbers are always equal. 
(X) The number lost is greater than the number gained. 
(Y) The number lost is less than the number gained. 
(Z) There is no general relationship between the two numbers.  

text[[104, 570, 577, 587]]
ANSWER: W- THE TWO NUMBERS ARE ALWAYS EQUAL  

sub_title[[466, 600, 532, 617]]
## BONUS  

text[[78, 631, 717, 649]]
4. CHEM; Multiple Choice: In an electroplating process, the object to be plated is the  

text[[104, 662, 235, 723]]
(W) anode. 
(X) cathode. 
(Y) electrolyte. 
(Z) plating metal.  

text[[104, 736, 306, 753]]
ANSWER: X- CATHODEsub_title[[460, 52, 535, 68]]
## TOSS-UP  

text[[78, 82, 675, 101]]
5. GENR; Multiple Choice: What type of projection is used to draw a road map?  

text[[120, 114, 223, 177]]
(W) Mercator 
(X) Robinson 
(Y) Conic 
(Z) Contour  

text[[120, 189, 293, 206]]
ANSWER: Y- CONIC  

sub_title[[466, 220, 532, 237]]
## BONUS  

text[[78, 250, 718, 269]]
5. GENR; Multiple Choice: What is the difference between hard water and soft water?  

text[[120, 281, 692, 342]]
(W) Hard water is denser than soft water 
(X) Hard water contains a greater quantity of minerals than soft water 
(Y) Hard water contains more ions of magnesium and calcium than soft water 
(Z) Hard water is more difficult to freeze than soft water  

text[[120, 355, 743, 388]]
ANSWER: Y- HARD WATER CONTAINS MORE IONS OF MAGNESIUM AND CALCIUM THAN SOFT WATER  

sub_title[[460, 433, 535, 450]]
## TOSS-UP  

text[[78, 463, 460, 481]]
6. COMP; Multiple Choice: A compiler translates  

text[[120, 495, 781, 556]]
(W) from a programming language as a source to a machine-oriented language as a target. 
(X) from a machine language as a source to an assembly language as a target. 
(Y) from a programming language to a high-level plan as a target. 
(Z) from a machine-dependent assembly language to byte code.  

text[[63, 568, 925, 601]]
ANSWER: W- FROM A PROGRAMMING LANGUAGE AS A SOURCE TO A MACHINE- ORIENTED LANGUAGE AS A TARGET  

sub_title[[466, 614, 532, 630]]
## BONUS  

text[[78, 644, 652, 663]]
6. COMP; Multiple Choice: Which of the following is not an SQL command?  

text[[120, 676, 212, 739]]
(W) Update 
(X) Select 
(Y) Remove 
(Z) Insert  

text[[120, 751, 310, 768]]
ANSWER: Y- REMOVEsub_title[[460, 52, 535, 69]]
## TOSS-UP  

text[[79, 82, 780, 101]]
7. CHEM; Multiple Choice: Fuel cells do not run down and do not require recharging because  

text[[120, 114, 533, 178]]
(W) oxidation occurs at both the anode and the cathode. 
(X) reduction occurs at both the anode and the cathode. 
(Y) the fuel is supplied continuously. 
(Z) both half reactions are very energetic.  

text[[120, 189, 583, 207]]
ANSWER: Y- THE FUEL IS SUPPLIED CONTINUOUSLY  

sub_title[[466, 220, 532, 237]]
## BONUS  

text[[78, 250, 615, 269]]
7. CHEM; Multiple Choice: The scientist who built the first battery was  

text[[120, 281, 230, 344]]
(W) Avogadro. 
(X) Ampere. 
(Y) Galvani. 
(Z) Volta.  

text[[120, 356, 295, 373]]
ANSWER: Z- VOLTA  

sub_title[[460, 418, 535, 435]]
## TOSS-UP  

text[[78, 448, 803, 468]]
8. BIOL; Multiple Choice: Any substance that triggers a specific defense of the immune system is  

text[[120, 480, 279, 541]]
(W) an interferon. 
(X) an antigen. 
(Y) a microorganism. 
(Z) a virus.  

text[[120, 554, 347, 572]]
ANSWER: X- AN ANTIGEN  

sub_title[[466, 585, 532, 602]]
## BONUS  

text[[78, 615, 784, 634]]
8. BIOL; Multiple Choice: The process by which antibodies link viruses to form a large mass is  

text[[120, 646, 315, 709]]
(W) inflammation. 
(X) infection. 
(Y) phagocyte production. 
(Z) agglutination.  

text[[120, 721, 384, 739]]
ANSWER: Z- AGGLUTINATIONsub_title[[460, 52, 535, 69]]
## TOSS-UP  

text[[78, 82, 770, 115]]
9. PHYS; Multiple Choice: The heat removed from the freezer compartment of a refrigerator radiates to the outside from the  

text[[120, 130, 271, 192]]
(W) condenser coils. 
(X) storage tank. 
(Y) freezer unit. 
(Z) compressor.  

text[[120, 204, 410, 221]]
ANSWER: W- CONDENSER COILS  

sub_title[[464, 234, 532, 251]]
## BONUS  

text[[78, 264, 439, 283]]
9. PHYS; Multiple Choice: During evaporation  

text[[120, 296, 625, 360]]
(W) both cooling and heating effects result. 
(X) the refrigerant is absorbed. 
(Y) heat absorption leaves an object's temperature lower than before. 
(Z) water molecules change from the gas to the liquid phase.  

text[[120, 370, 800, 404]]
ANSWER: Y- HEAT ABSORPTION LEAVES AN OBJECT'S TEMPERATURE LOWER THAN BEFORE  

sub_title[[460, 448, 535, 465]]
## TOSS-UP  

text[[80, 478, 805, 497]]
10. ERSC; Multiple Choice: A contour map of the hydraulic head in a confined aquifer is called the  

text[[120, 510, 320, 572]]
(W) water table. 
(X) potentiometric surface. 
(Y) terrain. 
(Z) slope.  

text[[120, 585, 485, 603]]
ANSWER: X- POTENTIOMETRIC SURFACE  

sub_title[[464, 615, 532, 632]]
## BONUS  

text[[80, 645, 677, 664]]
10. ERSC; Multiple Choice: Which is not an example of a concordant rock mass?  

text[[104, 677, 206, 739]]
(W) Lopolith 
(X) Sill 
(Y) Laccolith 
(Z) Dike  

text[[120, 752, 278, 768]]
ANSWER: Z- DIKEsub_title[[460, 52, 535, 69]]
## TOSS-UP  

text[[80, 82, 823, 101]]
11. BIOL; Multiple Choice: The production of antibodies following the first injection of a vaccine is a  

text[[120, 114, 364, 177]]
(W) lymph node reaction. 
(X) suppressor T-cell reaction. 
(Y) primary immune response. 
(Z) secondary immune response.  

text[[120, 189, 494, 206]]
ANSWER: Y- PRIMARY IMMUNE RESPONSE  

sub_title[[466, 220, 532, 237]]
## BONUS  

text[[80, 250, 758, 283]]
11. BIOL; Multiple Choice: Pasteur proved that sheep could be protected against anthrax by injecting them with  

text[[120, 296, 350, 358]]
(W) weakened anthrax viruses. 
(X) weakened anthrax bacteria. 
(Y) dead anthrax viruses. 
(Z) dead anthrax bacteria.  

text[[120, 371, 525, 388]]
ANSWER: X- WEAKENED ANTHRAX BACTERIA  

sub_title[[460, 433, 535, 450]]
## TOSS-UP  

text[[80, 463, 410, 481]]
12. PHYS; Multiple Choice: A diesel engine  

text[[120, 495, 401, 558]]
(W) is an external-combustion engine. 
(X) has spark plugs. 
(Y) burns fuel outside the engine. 
(Z) is a compression-ignition engine.  

text[[120, 570, 566, 587]]
ANSWER: Z- IS A COMPRESSION- IGNITION ENGINE  

sub_title[[466, 600, 532, 617]]
## BONUS  

text[[80, 630, 802, 663]]
12. PHYS; Multiple Choice: When the fuel burns in a gasoline engine, the heat added to the gases in the cylinder  

text[[120, 677, 595, 739]]
(W) decreases the energy of the exhaust. 
(X) is converted to work. 
(Y) is unrelated to work. 
(Z) is unrelated to work and decreases the energy of the exhaust.  

text[[120, 751, 456, 768]]
ANSWER: X- IS CONVERTED TO WORKsub_title[[460, 52, 535, 69]]
## TOSS-UP  

text[[80, 82, 789, 101]]
13. CHEM; Multiple Choice: Which of the following is used as the standard reference electrode?  

text[[120, 114, 301, 177]]
(W) Hydrogen electrode 
(X) Zinc electrode 
(Y) Copper electrode 
(Z) Carbon electrode  

text[[120, 189, 456, 206]]
ANSWER: W- HYDROGEN ELECTRODE  

sub_title[[465, 220, 532, 237]]
## BONUS  

text[[80, 250, 872, 269]]
13. CHEM; Multiple Choice: Devices that use redox reactions either to produce or use electricity are called  

text[[120, 281, 310, 343]]
(W) voltaic cells. 
(X) electrolytic cells. 
(Y) batteries. 
(Z) electrochemical cells.  

text[[120, 355, 475, 373]]
ANSWER: Z- ELECTROCHEMICAL CELLS  

sub_title[[460, 417, 535, 435]]
## TOSS-UP  

text[[60, 448, 920, 483]]
14. MATH; Multiple Choice: If the first derivative of a function at a point is zero, and the second derivative is negative, then the point is a  

text[[120, 496, 266, 556]]
(W) local minima. 
(X) inflection point. 
(Y) discontinuity. 
(Z) local maxima.  

text[[120, 570, 370, 587]]
ANSWER: Z- LOCAL MAXIMA  

sub_title[[465, 600, 532, 617]]
## BONUS  

text[[80, 630, 822, 649]]
14. MATH; Multiple Choice: How many distinct arrangements are there for six beads on a necklace?  

text[[120, 661, 183, 722]]
(W) 720 
(X) 120 
(Y) 60 
(Z) 30  

text[[120, 735, 297, 753]]
ANSWER: Y- 60 (5/2)sub_title[[460, 52, 535, 69]]
## TOSS-UP  

text[[80, 82, 702, 101]]
15. GENR; Multiple Choice: The only species of cat that lives and hunts in groups is  

text[[104, 115, 195, 177]]
(W) lion. 
(X) leopard. 
(Y) jaguar. 
(Z) cougar.  

text[[105, 189, 267, 206]]
ANSWER: W- LION  

sub_title[[466, 219, 532, 236]]
## BONUS  

text[[80, 250, 754, 283]]
15. GENR; Short Answer: What is the name of the island in the Caribbean that was recently devastated by the Soufriere Hills volcano?  

text[[120, 295, 330, 312]]
ANSWER: MONTSERRAT  

sub_title[[460, 357, 535, 375]]
## TOSS-UP  

text[[80, 387, 810, 406]]
16. BIOL; Multiple Choice: The Salk vaccine against poliomyelitis contained three slightly different  

text[[120, 419, 350, 481]]
(W) killed polio viruses. 
(X) weakened polio viruses. 
(Y) killed polio antibodies. 
(Z) weakened polio antibodies.  

text[[120, 494, 442, 511]]
ANSWER: W- KILLED POLIO VIRUSES  

sub_title[[466, 524, 532, 541]]
## BONUS  

text[[80, 554, 700, 573]]
16. BIOL; Multiple Choice: Paralysis often results from polio because the polio virus  

text[[120, 586, 360, 647]]
(W) activates suppressor T-cells. 
(X) activates killer T-cells. 
(Y) kills muscle cells. 
(Z) kills nerve cells.  

text[[120, 660, 410, 678]]
ANSWER: Z- KILLSNERVE CELLStitle[[460, 52, 535, 68]]
# TOSS-UP  

text[[60, 82, 920, 116]]
17. ASTR; Multiple Choice: Kepler's discovery that planets move in elliptical orbits was based upon observations of  

text[[120, 130, 288, 192]]
(W) Venus. 
(X) Mars. 
(Y) Jupiter. 
(Z) The Earth's moon.  

text[[120, 205, 285, 221]]
ANSWER: X- MARS  

sub_title[[465, 234, 532, 251]]
## BONUS  

text[[80, 264, 552, 283]]
17. ASTR; Multiple Choice: The planet Venus appears brightest  

text[[120, 296, 520, 358]]
(W) When it is at opposition. 
(X) When its phase is full. 
(Y) About a month before or after inferior conjunction. 
(Z) When it is at superior conjunction.  

text[[119, 370, 784, 389]]
ANSWER: Y- ABOUT A MONTH BEFORE OR AFTER INFERIOR CONJUNCTION  

sub_title[[460, 433, 535, 450]]
## TOSS-UP  

text[[80, 463, 666, 482]]
18. PHYS; Multiple Choice: Insulation materials reduce heat loss because they  

text[[120, 495, 304, 556]]
(W) are poor conductors. 
(X) reduce evaporation. 
(Y) block out the sun. 
(Z) promote convection.  

text[[120, 569, 459, 587]]
ANSWER: W- ARE POOR CONDUCTORS  

sub_title[[465, 600, 532, 617]]
## BONUS  

text[[80, 630, 787, 664]]
18. PHYS; Multiple Choice: The properties of a medium that affect the speed of waves traveling through it are the  

text[[105, 677, 404, 739]]
(W) color and density of the medium. 
(Z) color and elasticity of the medium. 
(Y) density and elasticity of the medium. 
(Z) color and phase of the medium.  

text[[120, 750, 617, 769]]
ANSWER: Y- DENSITY AND ELASTICITY OF THE MEDIUMsub_title[[460, 52, 535, 69]]
## TOSS-UP  

text[[80, 82, 750, 115]]
19. CHEM; Multiple Choice: The ability of a cell reaction to move electrons through a wire between voltaic cells is called the cell  

text[[120, 129, 223, 193]]
(W) potential. 
(X) current. 
(Y) power. 
(Z) energy.  

text[[121, 205, 342, 222]]
ANSWER: W- POTENTIAL  

sub_title[[466, 234, 532, 252]]
## BONUS  

text[[80, 264, 719, 284]]
19. CHEM; Multiple Choice: A voltaic cell in which the electrolyte is a paste is called a  

text[[120, 297, 300, 360]]
(W) fuel cell. 
(X) lead storage battery. 
(Y) wet cell. 
(Z) dry cell.  

text[[120, 371, 320, 389]]
ANSWER: Z- DRY CELL  

sub_title[[460, 432, 535, 450]]
## TOSS-UP  

text[[78, 462, 783, 496]]
20. ERSC; Multiple Choice: Chemical weathering of sodium and plagioclase feldspar result in hydrous aluminous silicates otherwise known as?  

text[[119, 509, 255, 571]]
(W) Evaporites 
(X) Clay minerals 
(Y) Precipitates 
(Z) Sheet silicates  

text[[120, 584, 378, 602]]
ANSWER: X- CLAY MINERALS  

sub_title[[466, 614, 532, 631]]
## BONUS  

text[[78, 644, 780, 678]]
20. ERSC; Multiple Choice: Monocline, syncline and anticline are structural geology terms that are used to describe  

text[[104, 691, 265, 753]]
(W) Folds. 
(X) Plate Boundaries. 
(Y) Faucets. 
(Z) Geosynclines.  

text[[105, 766, 281, 783]]
ANSWER: W- FOLDSsub_title[[460, 52, 536, 69]]
## TOSS-UP  

text[[78, 82, 737, 101]]
21. COMP; Short Answer: What is the programming language used to create Web pages?  

text[[121, 113, 260, 130]]
ANSWER: HTML  

sub_title[[466, 143, 532, 161]]
## BONUS  

text[[78, 174, 797, 209]]
21. COMP; Multiple Choice: Use DeMorgan's Law to restate not(p and q) (read: not parentheses p and q parentheses closed).  

text[[120, 220, 288, 286]]
(W) (not p) or (not q) 
(X) (p) or (q) 
(Y) (p) and (q) 
(Z) (not p) and (not q)  

text[[120, 295, 415, 313]]
ANSWER: W- (NOT P) OR (NOT Q)  

sub_title[[460, 356, 536, 374]]
## TOSS-UP  

text[[78, 386, 650, 405]]
22. BIOL; Short Answer: What is the name of the third bone in the inner ear?  

text[[120, 416, 380, 435]]
ANSWER: STAPES OR STIRRUP  

sub_title[[466, 448, 532, 465]]
## BONUS  

text[[78, 478, 731, 497]]
22. BIOL; Multiple Choice: The most effective attacking cells in the immune system are  

text[[120, 509, 259, 572]]
(W) helper T-cells. 
(X) killer T-cells. 
(Y) plasma cells. 
(Z) mast cells.  

text[[120, 585, 377, 603]]
ANSWER: X- KILLER T-CELLSsub_title[[460, 52, 535, 69]]
## TOSS-UP  

text[[78, 83, 641, 101]]
23. MATH; Short Answer: What is the value of 125 to the two-thirds power?  

text[[120, 113, 225, 131]]
ANSWER: 25  

sub_title[[466, 144, 532, 161]]
## BONUS  

text[[79, 174, 782, 223]]
23. MATH; Short Answer: A teacher is said to have asked Carl Gauss to add up all the numbers from 1 to 100. Gauss was declared a genius when he answered the question immediately at age eight. Since you are older, add up all the whole numbers up to and including 1 million.  

text[[120, 234, 583, 252]]
ANSWER: 500 BILLION, 500 THOUSAND (500,000,500,000)  

sub_title[[460, 297, 535, 314]]
## TOSS-UP  

text[[79, 327, 767, 376]]
24. PHYS; Short Answer: A charged particle is moving in a UNIFORM magnetic field. If the direction of motion of the charged particle is parallel to the magnetic field, describe the shape of the charged particle's path.  

text[[106, 403, 328, 420]]
ANSWER: STRAIGHT LINE  

sub_title[[466, 433, 532, 450]]
## BONUS  

text[[78, 463, 797, 482]]
24. PHYS; Multiple Choice: The speed of sound waves is greater in steel than in air due to steel's  

text[[120, 495, 266, 556]]
(W) greater mass. 
(X) lesser elasticity. 
(Y) greater density. 
(Z) lesser density.  

text[[120, 569, 402, 586]]
ANSWER: Y- GREATER DENSITYsub_title[[460, 51, 535, 68]]
## TOSS-UP  

text[[78, 82, 800, 115]]
25. CHEM; Short Answer: Calculate the maximum number of electrons that can exist in the \(\mathrm{n} = 4\) level.ANSWER: 32  

text[[121, 128, 225, 145]]
ANSWER: 32  

sub_title[[466, 159, 532, 176]]
## BONUS  

text[[78, 188, 713, 207]]
25. CHEM; Multiple Choice: Electrolysis is the process by which electricity is used to  

text[[120, 219, 504, 283]]
(W) divide chemical reactions into half reactions. 
(X) melt sodium chloride. 
(Y) charge the anode and cathode. 
(Z) bring about a nonspontaneous chemical change.  

text[[120, 294, 733, 312]]
ANSWER: Z- BRING ABOUT ANONSPONTANEOUS CHEMICAL CHANGE