
1. GENR; Short Answer: When he was discovered in 1891, he was erroneously considered the "missing link" between man and ape in the popular press. What popular name do modern day anthropologists call him?  


ANSWER: JAVAMAN  


2. CHEM; Short Answer: Only five of the elements on the Periodic Table are liquids at 30 degrees Celsius and standard pressure. Name any four.  


ANSWER: GALLIUM, BROMINE, CESIUM, MERCURY, FRANCIUM  


3. PHYS; Short Answer: What is the ideal efficiency of a reversible heat engine cyclically operating between a source temperature of 600 degrees Kelvin and a sink temperature of 150 degrees Kelvin?  


ANSWER: 75 PERCENT  


4. BIOL; Short Answer: What is the material that is oxidized to produce bioluminescence is some creatures?  


ANSWER: LUCIFERASE  


5. COMP; Short Answer: What 4-letter command is used in BASIC to resume execution of a program at the point it was interrupted by a STOP or END statement?  


ANSWER: CONT
# NATIONAL TIE BREAKER - 2  


1. ERSC; Short Answer: Iceland spar is a pure, transparent form of what mineral?  


ANSWER: CALCITE (ACCEPT CALCIUM CARBONATE)  


2. ASTR; Short Answer: Name the first scientist to apply for a patent on a telescope.  


ANSWER: (HANS) LIPPERSHEY  


3. PHYS; Short Answer: Who developed the wave equation that is used to determine the PROBABILITY of finding the electron in any given place?  


ANSWER: SCHRODINGER (PRON: SHRAD'-IN-ER)  


4. CHEM; Short Answer: Joseph Priestley called it dephlogisticated (pron: de-flow-jis-tee-kated) air. Who named it oxygen?  


ANSWER: LAVOISIER  


5. GENR; Short Answer: Before he became a consulting engineer to General Electric, in 1897 he co-authored "The Theory and Calculation of Alternating Current Phenomena." What was his name?  


ANSWER: (CHARLES) STEINMETZ
# NATIONAL TIE BREAKER - 3  


1. BIOL; Short Answer: Plant movements that are growth responses towards or away from a stimuli are called  


ANSWER: TROPISMS  


2. MATH; Short Answer: In how many ways can 4 different books be given to 2 children so that each child gets exactly 2 books?  


ANSWER: 6 (WAYS)  


3. ERSC; Short Answer: Who was the 16th century cartographer (pron: car- tog'-re-fer) who thought there ought to be a large land mass south of the equator to balance that in the north. He gave his name to one style of map projection.  


ANSWER: MERCATOR (PRON: MER- KAY'-TOR)  


4. CHEM; Short Answer: What is the common name for potassium sodium tartrate?  


ANSWER: ROCHELLE SALT  


5. PHYS; Short Answer: What scientist first successfully explained Brownian motion?  


ANSWER: EINSTEIN
# NATIONAL TIE BREAKER - 4  


1. GENR; Short Answer: What is the name of the calendar introduced in 1582 to make a ten day correction?  


ANSWER: GREGORIAN  


2. ASTR; Short Answer: The Asteroid Belt is between the orbits of which two planets?  


ANSWER: MARS AND JUPITER  


3. BIOL; Short Answer: The Rh (pron: R-h) factor was named after what animal?  


ANSWER: RHESUS MONKEY  


4. MATH; Short Answer: In a triangle, what is the name given to the intersection of the perpendicular bisectors of the sides?  


ANSWER: CIRCUMCENTER  


5. PHYS; Short Answer: Which physicist, after whom a very important physical constant is named, formulated the quantum theory?  


ANSWER: (MAX) PLANCK
# NATIONAL TIE BREAKER - 5  


1. GENR; Short Answer: What is the name of the island between Java and Sumatra that disappeared during a huge volcanic eruption in 1883?  


ANSWER: KRAKATOA (PRON: KRAK-E-TO'-A) OR KRAKATAU OR KRAKATAO  


2. CHEM; Short Answer: What is the maximum number of electrons that a metal usually has in its outer energy level?  


ANSWER: 3  


3. PHYS; Short Answer: According to the quantum theory, the strong nuclear particles. What are these particles called?  


ANSWER: GLUONS  


4. BIOL; Short Answer: What is the name of one of the most primitive land plants, consisting of algae and fungus growing in a mutually helpful association?  


ANSWER: LICHEN  


5. ASTR; Short Answer: Name the two constellations that make up the famous "Great Square of Pegasus."  


ANSWER: PEGASUS, ANDROMEDA
# NATIONAL TIE BREAKER - 6  


1. MATH; Short Answer: What is the name given to the radius of a circle that can be inscribed in any regular polygon?  


ANSWER: APOTHEM (PRON: AP'-O-THEM)  


2. ERSC; Short Answer: Name the dryest continent.  


ANSWER: ANTARCTICA  


3. PHYS; Short Answer: Suppose the power of a prescription lens is 5 diopters. What is the focal length of the lens, in centimeters?  


ANSWER: 20 CENTIMETERS (ACCEPT 0.2 METERS)  


4. CHEM; Short Answer: Name three elements that were named after Greek or Roman gods.  


ANSWER: MERCURY, URANIUM, NEPTUNIUM, PLUTONIUM  


5. GENR; Short Answer: What measure of length, mainly used for sea depths, was originally the breadth of the outstretched arms?  


ANSWER: FATHOM
1. CHEM; Short Answer: Who discovered Nitrogen  


ANSWER: (DANIEL) RUTHERFORD  


2. GENR; Short Answer: The temperature at which water vapor begins to condense in the atmosphere is called the  


ANSWER: DEW POINT  


3. PHYS; Short Answer: Suppose the power of a prescription lens is 5 diopters. What is the focal length of the lens, in centimeters?  


ANSWER: 20 (CENTIMETERS)  


4. ASTR; Short Answer: Whose name is associated with the formula for estimating the probability of extra-terrestrial intelligence?  


ANSWER: DRAKE  


5. BIOL; Short Answer: Retinol is the common name for what vitamin?  


ANSWER: VITAMIN A
# NATIONAL TIE BREAKER - 8  


1. BIOL; Short Answer: What common poisonous gas kills humans by strongly binding to hemoglobin in the bloodstream?  


ANSWER: CARBON MONOXIDE  


2. ERSC; Short Answer: Outside of Alaska, what is the name of North America's longest continuous mountain range?  


ANSWER: SIERRA NEVADA  


3. MATH; Short Answer: The boundary of a Mandelbrot set has a fractal dimension of  


ANSWER: 2  


4. PHYS; Short Answer: In 1932, the first ARTIFICIAL source of radiation was created in France by two famous scientists. Name the TWO scientists.  


ANSWER: IRENE and FREDERIC (JOLIOT-) CURIE  


5. CHEM; Short Answer: What is the name for a material that has the capacity to behave as either an acid or a base?  


ANSWER: AMPHOTERIC (ACCEPT AMPHIPROTIC)
# NATIONAL TIE BREAKER - 9  


1. MATH; Short Answer: What is the area of the square inscribed in a circle of unit radius?  


ANSWER: 2  


2. ASTR; Short Answer: What is the term for the boundary between our solar system and interstellar space?  


ANSWER: HELIOPAUSE  


3. ERSC; Short Answer: What is the last name of the famous husband and wife team who discovered fossils in Africa that were estimated to be over 3.5 million years old?  


ANSWER: LEAKEY  


4. GENR; Short Answer: What is the term for time measured with respect to the stars rather than with respect to the sun?  


ANSWER: SIDEREAL (PRON: SI-DER'-E-AL)  


5. BIOL; Short Answer: What plant nutrient is the most common cause of eutrophication?  


ANSWER: PHOSPHORUS OR PHOSPHATES
# NATIONAL TIE BREAKER - 10  


1. ASTR; Short Answer: Seen from the earth, which two heavenly bodies other than the Moon exhibit phases?  


ANSWER: MERCURY AND VENUS  


2. BIOL; Short Answer: The cells of a root's endodermis are thickened suberin, a waterproofing material. This waterproof band is called the  


ANSWER: CASPARIAN STRIP  


3. GENR; Short Answer: What unit was originally defined as one ten-millionth of the distance from the equator to a pole of the earth?  


ANSWER: A METER  


4. MATH; Short Answer: If it cost \(\) 3\(to paint the plane surface of a hemisphere, what will it cost to paint the hemisphere's curved surface?  


ANSWER: \(\) 6\$  


5. CHEM; Short Answer: What chemical is commonly known as blue vitriol?  


ANSWER: COPPER SULFATE