
## TOSS-UP  


1) Physics – Multiple Choice Which of the following describes a region within a magnetic material that has uniform magnetization?  


W) Magnetic pole 
X) Magnetosphere 
Y) Magnetic domain 
Z) Magnetic line  


ANSWER: Y) MAGNETIC DOMAIN  


## BONUS  


1) Physics – Short Answer An object is launched at 15 degrees from the ground at an initial velocity of \(10\mathrm{m / s}\) . Assuming gravity is \(10\mathrm{m / s^2}\) how far away will it land in meters?  


ANSWER: 5m  


## TOSS-UP  


2) Biology – Short Answer What macromolecule is simultaneously produced with insulin during its post translational modification  


ANSWER: C-PEPTIDE  


## BONUS  


2) Biology – Multiple Choice If Bob were to take a cross section from the stem of a monocot, how are the vascular bundles arranged?  


W) The xylem and phloem form concentric rings 
X) The vascular bundles form concentric rings 
Y) The xylem and phloem are scattered throughout the stem 
Z) The vascular bundles are scattered throughout the stem  


ANSWER: Z) THE VASCULAR BUNDLES ARE SCATTERED THROUGHOUT THE STEM
## TOSS-UP  


3) Chemistry – Short Answer Which covalent compound can be formed from ammonium cyanate through the Wohler synthesis?  


ANSWER: UREA (ACCEPT EQUIVALENTS)  


## BONUS  


3) Chemistry – Short Answer Select all of the following primary alcohols which are not miscible with water. 1) Methanol 2) Ethanol 3) Propanol 4) n-butanol  


ANSWER: 4 ONLY (ACCEPT: BUTANOL)  


## TOSS-UP  


4) Earth and Space – Multiple Choice In the past 800,000 years, Earth’s period of glacial maximums has followed a period of about 100,000 years. Which of the following periodic changes can be attributed as the main forcing factor to cause these glacial maximums?  


W) Axial obliquity  X) Axial precession  Y) Brightness of the sun  Z) Eccentricity  


ANSWER: Z) ECCENTRICITY  


## BONUS  


4) Earth and Space – Multiple Choice In order for a surface low to gain in intensity, which of the following needs to occur at high altitudes?  


W) Convergence  X) Divergence  Y) Absolute geostrophic flow  Z) Conditional geostrophic flow  


ANSWER: X) DIVERGENCE
## TOSS-UP  


5) Math – Short Answer You flip a coin 7 times. What is the probability of flipping more heads than tails?  


ANSWER: \(\frac{1}{2}\)  


## BONUS  


5) Math – Short Answer What is the smallest n such that n! contains at least 6 trailing zeroes?  


ANSWER: 25  


## TOSS-UP  


6) Physics – Short Answer Identify all of the following 3 choices that are considered inertial reference frames where astronomical motions are negligible. 1) In a merry go round 2) An airplane taking off in its runway 3) High Speed train on cruise mode.  


ANSWER: 3 ONLY  


## BONUS  


6) Physics – Short Answer What observatory works with ICECUBE to detect cosmic rays between 100GeV and 100TeV in Puebla Mexico?  


ANSWER: HAWC OBSERVATORY
## TOSS-UP  


7) Biology – Short Answer If two parents of a child are carriers for an autosomal dominant disease, what is the probability that their child is a carrier as well? Express your answer as a reduced fraction.  


ANSWER: 1/2  


## BONUS  


7) Biology – Multiple Choice Geoff is brought to the emergency room after being hit with a baseball bat on the side of his leg immediately below the knee. He is unable to dorsiflex his foot. Which of the following nerves is most likely injured?  


W) Peroneal X) Tibial Y) Femoral Z) Obturator  


ANSWER: W) PERONEAL  


## TOSS-UP  


8) Chemistry – Multiple Choice Which of the following does not represent an increase in entropy?  


W) Condensation of water 
X) Dissolution of NaCl in water 
Y) Sublimation of CO2 
Z) Gas Evolution  


ANSWER: W) CONDENSATION OF WATER  


## BONUS  


8) Chemistry - Multiple Choice Consider the mass spectrometry graphs for n-butanol, sec butanol, and tert butanol. Order the relative areas of the m/z=57 peaks for the three butanol isomers by increasing area. The mass of butanol is 74  


ANSWER: N BUTANOL, SEC BUTANOL, TERT BUTANOL
## TOSS-UP  


9) Earth and Space – Multiple Choice Which ion is the most common ion in seawater?  


W) Sodium  X) Sulfate  Y) Magnesium  Z) Chloride  


ANSWER: Z) CHLORIDE  


## BONUS  


9) Earth and Space – Short Answer The internal structural damage of many zircon crystals is caused by self-irradiation from the radioactive decay of uranium and thorium in the crystal structure. This process of continuous structural disintegration is known as what?  


ANSWER: METAMICTIZATION (ACCEPT: METAMICTION)  


## TOSS-UP  


10) Math – Short Answer If \(2 = \mathrm{x}^{\wedge}\mathrm{x}^{\wedge}\mathrm{x}\) to the infinitely many xs, what is x?  


ANSWER: sqrt(2)  


## BONUS  


10) Math – Short Answer Find the indefinite integral of \(\cos (\mathrm{x})^{*}\cos (\sin (\mathrm{x}))\mathrm{dx}\) ?  


ANSWER: SIN(SIN(X))+C
## TOSS-UP  


11) Physics – Short Answer What is the maximum number of 4W light bulbs that could be connected with a 12V source with the circuit allowing a maximum current of 5A?  


ANSWER: 15  


## BONUS  


11) Physics – Short Answer What is the electric flux through a Gaussian surface of area A enclosing an electric dipole where each charge has an equal magnitude of q?  


ANSWER: 0  


## TOSS-UP  


12) Biology – Short Answer The photoreceptor phytochrome is responsible for what response an organism has to seasonal changes in daylength.  


ANSWER: PHOTOPERIODISM  


## BONUS  


12) Biology – Multiple Choice Which of the following happens to hemoglobin when one of its subunits takes up an oxygen molecule?  


W) The hemoglobin’s affinity for oxygen decreases 
X) The hemoglobin’s affinity for oxygen is unaffected 
Y) The hemoglobin’s affinity for oxygen increases 
Z) The change in the hemoglobin is dependant on which subunit the oxygen molecule bonded with  


ANSWER: Y) The hemoglobin’s affinity for oxygen increases
## TOSS-UP  


13) Chemistry – Multiple Choice What equation is responsible for relating the equilibrium constants for a reaction with varying measurements of temperature?  


W) Van't Hoff Equation 
X) Arrhenius Equation 
Y) Clausius Clapeyron Equation 
Z) Boltzmann Equation  


ANSWER: W) VAN'T HOFF EQUATION  


## BONUS  


13) Chemistry – Multiple Choice Which of the following is not a way to commonly use zeolites?  


W) Zeolites are used as ion exchange beds for commercial water purification 
X) Zeolites assist silver in naturally emitting light 
Y) Zeolites are used to remove nitrogen in compressed air to supply oxygen in flights. 
Z) Zeolites are used in conjunction with beta blockers to reduce blood pressure  


ANSWER: Z) ZEOLITES ARE USED IN CONJUNCTION WITH BETA BLOCKERS TO REDUCE BLOOD PRESSURE  


## TOSS-UP  


14) Earth and Space – Multiple Choice Which of the following best describes the main formation mechanism of tropospheric ozone?  


W) Splitting of H2O into H2 and O by ionosphere-to-ground electrolysis, recombination of O and O2 into ozone 
X) Splitting of NO2 into NO and O by high energy radiation, then recombination of O and O2 into ozone 
Y) Combination of two O2 molecules, releasing O3 and O 
Z) Splitting of O2 into two O radicals, recombination of O radical with O2 into ozone  


ANSWER: X) SPLITTING OF NO2 INTO NO AND O BY HIGH ENERGY RADIATION, THEN RECOMBINATION OF O AND O2 INTO OZONE(Reverse)  


## BONUS  


14) Earth and Space – Multiple Choice Which of the following is indicative of a Type 1a supernova?  


W) Strong silicon line at \(615~\mathrm{nm}\) , no hydrogen lines 
X) Strong helium lines, no hydrogen lines 
Y) Strong iron line at \(810~\mathrm{nm}\) , no hydrogen lines 
Z) Strong helium and hydrogen lines  


ANSWER: W) STRONG SILICON LINE AT 615 NM, NO HYDROGEN LINES (Reverse)
## TOSS-UP  


15) Math – Short Answer Toph flips a quarter four times. Find the probability that the quarter lands heads exactly twice.  


ANSWER: 3/8  


## BONUS  


15) Math – Short Answer Short Answer Find the sum of all positive rational numbers that are less than 1 and that have denominator of 20 when written in lowest terms.  


ANSWER: 4  


## TOSS-UP  


16) Physics – Short Answer What hydrogen series lies in the infrared section of the spectrum and overlaps with the Brackett series?  


ANSWER: PASCHEN SERIES (ACCEPT: BOHR SERIES)  


## BONUS  


16) Physics – Multiple Choice What kind of flow is considered drag-induced flow either between parallel flat plates or between concentric rotating cylinders  


W) Poiseuille flow 
X) Couette flow 
Y) Viscous flow 
Z) Navier flow  


ANSWER: X) COUETTE FLOW
## TOSS-UP  


17) Biology – Short Answer What term describes a plant cell whose membrane has separated from its cell wall due to dehydration?  


ANSWER: PLASMOLYSIS  


## BONUS  


17) Biology – Multiple Choice In prokaryotes, which polymerase is used to carry out most of DNA replication?  


W) DNA Polymerase 1 
X) DNA Polymerase 2 
Y) DNA Polymerase 3 
Z) RNA Polymerase 3  


ANSWER: Y) DNA POLYMERASE 3  


## TOSS-UP  


18) Chemistry – Short Answer Rank the following 3 weak acids in order of increasing pKa values. 1) HClO 2) HBrO 3) HIO  


ANSWER: 1, 2, 3  


## BONUS  


18) Chemistry – Short Answer What isomer differs by the exchange of a ligand with an anion or a neutral molecule that is outside the coordination sphere?  


ANSWER: IONIZATION
## TOSS-UP  


19) Earth Science – Short Answer Which of the following minerals has a sheet-like silicate structure? 1) Biotite 2) Muscovite 3) Microcline 4) Talc  


ANSWER: 1,2,4 (Reverse)  


## BONUS  


19) Earth Science – Multiple Choice Large, euhhedral crystals of muscovite embedded in an igneous rock are indicative of which of the following environments?  


W) Quick cooling time at high temperatures  X) Quick cooling time at low temperatures  Y) Slow cooling time at high temperatures  Z) Slow cooling time at low temperatures  


ANSWER: Z) SLOW COOLING TIME AT LOW TEMPERATURES (Reverse)  


## TOSS-UP  


20) Math – Short Answer
## TOSS-UP  


20) Math - Short Answer Find the volume of the region of points (x,y,z) such that \((x^{\wedge}2 + y^{\wedge}2 + z^{\wedge}2 + 8)^{\wedge}2\) \(\leq 36(\mathrm{x}^{\wedge}2 + \mathrm{y}^{\wedge}2)\) .  


ANSWER: 6pi^2  


## BONUS  


20) Math - Short Answer Evaluate, \(2^{*}(6^{\wedge}2)\)  


ANSWER: 72  


20'B) Math - Short Answer The Trivial Theorem states that the square of any real number is not less than what number?  


ANSWER: 0  


David Jiang, Akkkul,, Dan, Ben, Makorn, Sword of Damocles