
## TOSS-UP  


1) X-Risk - Short Answer In a nuclear winter, aerosols are thrown into the atmosphere that rarely make their way to the surface. Instead, they coagulate to form larger particles via what type of motion, the random motion of particles suspended in the atmosphere?  


ANSWER: Brownian motion  


## BONUS  


1) X-Risk - Multiple Choice Which of the following fossil fuels emits the least amount of carbon dioxide per mass of fuel?  


W) Coal 
X) Oil 
Y) Natural gas 
Z) Gasoline  


ANSWER: Y) Natural gas
## TOSS-UP  


2) Math - Short Answer What is the largest possible three-digit number such that all of its digits are distinct and the sum of the digits is less than 20?  


ANSWER: 982  


## BONUS  


2) Math - Short Answer Find the sum of an infinite geometric series with first term 64 and fourth term 27.  


ANSWER: 256
## TOSS-UP  


3) Chemistry - Short Answer How many angular nodes are in a 3p orbital?  


ANSWER: 1  


## BONUS  


3) Chemistry - Short Answer Order the following three bonds from weakest to strongest: 1) C-H single bond; 2) C-C single bond; 3) C-C double bond  


ANSWER: 2, 1, 3
## TOSS-UP  


4) Earth and Space - Multiple Choice Which of the following soil horizons is the shallowest?  


W) A 
X) B 
Y) C 
Z) E  


ANSWER: W) A  


## BONUS  


4) Earth and Space - Short Answer What is the name for the process which generates precipitation via the growth of ice crystals in supercooled clouds?  


ANSWER: Bergeron process
## TOSS-UP  


5) Biology - Short Answer What enzyme is responsible for cleaving pre-miRNA hairpins into mature pre-miRNAs?  


ANSWER: DICER  


## BONUS  


5) Biology - Multiple Choice Which of the following would NOT occur during photosynthesis?  


W) Increase in pH of the stroma  
X) Increase in ATP production  
Y) Reduction of oxygen into water  
Z) Increase in G3P production  


ANSWER: Y) Reduction of oxygen into water
## TOSS-UP  


6) Physics - Short Answer A circular loop on a roller coaster is built with a radius of 5 meters. To the nearest meter per second, what is the minimum velocity at the top of the loop that would allow the cart to complete the loop?  


ANSWER: 7  


## BONUS  


6) Physics - Multiple Choice Which of the following is an example of a noninertial reference frame?  


W) An object moving at constant velocity through a viscous medium  X) A stationary electric charge  Y) A stationary charged particle in a magnetic field  Z) A particle rotating at a constant speed  


ANSWER: Z) A particle rotating at a constant speed
## TOSS-UP  


7) X-Risk - Multiple Choice Nuclear decay can be modeled as a reaction with which of the following orders?  


W) Zeroth 
X) First 
Y) Second 
Z) Third  


ANSWER: X) First  


## BONUS  


7) X-Risk - Multiple Choice What is the name of the common paradigm in machine learning which describes problems as agents interacting with an environment, trying to maximize their reward?  


W) Supervised learning 
X) Unsupervised learning 
Y) Reinforcement learning 
Z) Inverse reinforcement learning  


ANSWER: Y) Reinforcement learning
## TOSS-UP  


8) Math - Short Answer A right triangle has side lengths of 6, 8, and 10. What is the radius of the triangle's incircle?  


ANSWER: 2  


## BONUS  


8) Math - Short Answer Compute 11 times 12 plus 13 times 14 minus 11 times 14 minus 12 times 13.  


ANSWER: 4
## TOSS-UP  


9) Chemistry - Short Answer The equilibrium constant for the reaction \(\mathrm{A} + \mathrm{B} \longrightarrow \mathrm{C}\) [A plus B yields C] is \(K\) . For the reaction \(3\mathrm{C} \longrightarrow 3\mathrm{A} + 3\mathrm{B}\) [three- C yields three-A plus three-B], what is the equilibrium constant in terms of K?  


ANSWER: \(1 / K^{3}\)  


## BONUS  


9) Chemistry - Short Answer In the \(\mathrm{OF}^{+}\) cation, what is the bond order of the oxygen fluorine bond?  


ANSWER: 2
## TOSS-UP  


10) Earth and Space - Multiple Choice Which of the following statements is not true of chondrites?  


W) They can contain volatiles 
X) They cooled extremely quickly 
Y) They likely condensed at high temperatures near the solar nebula 
Z) They have Widmanstatten [WID-min-stot-in] patterns  


ANSWER: Z) They have Widmanstatten [WID-min-stot-in] patterns  


## BONUS  


10) Earth and Space - Multiple Choice Which of the following best explains why in some binary systems, more massive stars are observed to be in the same stage of life as less massive stars, implying that they have similar life spans to lesser mass stars?  


W) The more massive star formed later than the less massive star 
X) The more massive star's fusion is disrupted through gravitational heating 
Y) The more massive star transfers mass to the younger star while it is evolving 
Z) The less massive star heats up more rapidly due to the Kelvin-Helmholtz mechanism  


ANSWER: Y) The more massive star transfers mass to the younger star while it is evolving
## TOSS-UP  


11) Biology - Short Answer What molecules are used in Sanger sequencing to induce chain termination of DNA strands?  


ANSWER: Dideoxy nucleotide triphosphates (ACCEPT: ddNTPs)  


## BONUS  


11) Biology - Short Answer During the termination of transcription, order the following three steps in the order of which they occur: 1) Reading of the polyadenylation [POL-ee-uh-dee-null-AY-shin] signal; 2) Release of RNA from the transcription complex; 3) Reading of the stop codon.  


ANSWER: 3, 1, 2
## TOSS-UP  


12) Physics - Multiple Choice What is the direction of propagation for an electromagnetic wave where the electric field is moving in the positive \(x\) direction and the magnetic field is moving in the positive \(z\) direction?  


W) Positive y 
X) Negative y 
Y) Positive z 
Z) Negative z  


ANSWER: X) Negative y  


## BONUS  


12) Physics - Short Answer A circuit is created from three resistors in parallel with resistances of 1 ohm, 2 ohms, and 4 ohms, respectively. The circuit is then attached to an 8 volt battery. What is the total power output of the circuit in watts?  


ANSWER: 112
## TOSS-UP  


13) X-Risk - Multiple Choice A researcher finds that CO2 concentrations and light pollution are highly positively correlated. Which of the following is the confounding variable in this situation?  


W) Industrialization 
X) Human health 
Y) World population 
Z) Time  


ANSWER: W) Industrialization  


## BONUS  


13) X-Risk - Multiple Choice In 2021, the Amazon rainforest became a carbon source when it had previously been a carbon sink. What is the main driver for this change?  


W) Deforestation 
X) Forest fires 
Y) Stream migration 
Z) Sedimentation  


ANSWER: W) Deforestation
## TOSS-UP  


14) Math - Short Answer In triangle ABC, D lies on BC such that AD bisects angle BAC. If AB equals 9, AC equals 12, and BD equals 6, what is the length of CD?  


ANSWER: 8  


## BONUS  


14) Math - Short Answer Find the sum of the first 20 positive square numbers.  


ANSWER: 2870
## TOSS-UP  


15) Chemistry - Multiple Choice Which of the following elemental properties monotonically increases down the alkali earth metal group on the periodic table?  


W) Atomic radius 
X) Melting point 
Y) Ionization energy 
Z) Electron affinity  


ANSWER: W) Atomic radius  


## BONUS  


15) Chemistry - Short Answer Order the following three substances by increasing vapor pressure in their solid state: 1) Carbon dioxide; 2) Water; 3) Ammonia.  


ANSWER: 2, 3, 1
## TOSS-UP  


16) Earth and Space - Multiple Choice A large storm blows to the north and encounters a mountain range, where it exhibits orographic lifting. Which of the following locations would receive the most precipitation?  


W) Southern mountainside 
X) Top of the mountain 
Y) Northern mountainside 
Z) Plain north of the mountains  


ANSWER: W) Southern mountainside  


## BONUS  


16) Earth and Space - Multiple Choice The Permian-Triassic extinction was caused by a rapid increase of atmospheric carbon dioxide due to which of the following events?  


W) Volcanic eruptions 
X) Ozone layer destruction 
Y) Ocean anoxia 
Z) Meteor impact  


ANSWER: W) Volcanic eruptions
## TOSS-UP  


17) Biology - Multiple Choice Which of the following best describes the change in mean pressure as blood traverses from the aorta to the veins?  


W) Decreases then increases 
X) Increases then decreases 
Y) Decreases 
Z) Increases  


ANSWER: Y) Decreases  


## BONUS  


17) Biology - Short Answer Identify all of the following three interactions that dominate in secondary structure: 1) Hydrophobic interactions; 2) Disulfide bonds; 3) Hydrogen bonding between R groups.  


ANSWER: None
## TOSS-UP  


18) Physics - Short Answer The law of reflection, stating that the incident angle of a ray of light is equal to the angle at which it is reflected, assumes what type of reflection is occurring?  


ANSWER: Specular  


## BONUS  


18) Physics - Short Answer Calculate the moment of inertia, in kilogram-meters squared, about a central axis of a hollow sphere of radius 5 meters and mass 3 kilograms.  


ANSWER: 50
## TOSS-UP  


19) X-Risk - Short Answer A neural network is often modeled purely in terms of its inputs and outputs, without regard for its internal workings. What is the commonly used term for this model in engineering?  


ANSWER: Black box  


## BONUS  


19) X-Risk - Multiple Choice Which of the following best explains why RNA viruses have a higher mutation rate than DNA viruses?  


W) The RNA polymerase in most RNA viruses lacks proofreading ability  X) Most RNA viruses have a shorter life cycle than DNA viruses  Y) Most RNA viruses have a larger genome than DNA viruses  Z) RNA viruses have a viral envelope that is permeable to mutagens  


ANSWER: W) The RNA polymerase in most RNA viruses lacks proofreading ability
## TOSS-UP  


20) Math - Short Answer Caleb is on a grid at the point \((0,0)\) and wants to reach the point \((2,4)\) . Every second, he can move either one unit right or one unit up. How many distinct paths can Caleb take to reach his destination?  


ANSWER: 15  


## BONUS  


20) Math - Short Answer Mark has an array of integers in the order \([2,3,4,5,6,1]\) . With each move, he can swap any two neighboring elements' positions in the array. How many moves are needed for Mark to make the array sorted in descending order?  


ANSWER: 10
## TOSS-UP  


21) Chemistry - Short Answer In a single-step reaction, what term describes the difference in potential energy between the reactants and the transition state?  


ANSWER: Activation energy  


## BONUS  


21) Chemistry - Short Answer What is the molecular geometry of the central sulfur atom in sulfur tetrafluoride?  


ANSWER: Seesaw
## TOSS-UP  


22) Earth and Space - Short Answer What name is given to the process of mass decay caused by virtual particles slipping beyond an event horizon?  


ANSWER: Hawking radiation  


## BONUS  


22) Earth and Space - Short Answer Identify all of the following three statements that are true of Population II stars: 1) They are common in open clusters; 2) They are metal rich; 3) They have highly eccentric orbits.  


ANSWER: 3 only
## TOSS-UP  


23) Biology - Multiple Choice Which of the following best describes how lipid soluble hormones that are NOT steroids typically elicit a response?  


W) Bind to cell surface receptors 
X) Bind to transcription factors in the cytosol 
Y) Bind to transcription factors in the nucleus 
Z) Bind to nascent mRNA transcripts in the nucleus  


ANSWER: Y) Bind to transcription factors in the nucleus  


## BONUS  


23) Biology - Short Answer Identify all of the following three diseases that are genetically dominant: 1) Albinism; 2) Cystic Fibrosis; 3) Gigantism.  


ANSWER: 3
## TOSS-UP  


24) Physics - Short Answer Nuclear fusion within stars can occur once atoms overcome the intense Coulomb interactions. One way of doing this is through what phenomenon based on the low probability of the atomic wave transmitting through the barrier?  


ANSWER: Quantum tunneling (ACCEPT: Tunneling)  


## BONUS  


24) Physics - Short Answer When a point charge is placed very far away from the surface of a thin spherical conducting shell with uniform volume density, it experiences an electric field E. If the radius of the shell is doubled, what will be the new electric field experienced by the test charge in terms of E?  


ANSWER: E