text[[0, 0, 997, 997]]sub_title[[448, 172, 549, 194]]
## TOSS-UP  

text[[114, 229, 883, 315]]
1) X-Risk - Short Answer In a nuclear winter, aerosols are thrown into the atmosphere that rarely make their way to the surface. Instead, they coagulate to form larger particles via what type of motion, the random motion of particles suspended in the atmosphere?  

text[[115, 330, 394, 352]]
ANSWER: Brownian motion  

sub_title[[456, 373, 540, 394]]
## BONUS  

text[[115, 409, 883, 452]]
1) X-Risk - Multiple Choice Which of the following fossil fuels emits the least amount of carbon dioxide per mass of fuel?  

text[[114, 467, 256, 553]]
W) Coal 
X) Oil 
Y) Natural gas 
Z) Gasoline  

text[[115, 569, 368, 590]]
ANSWER: Y) Natural gassub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 883, 174]]
2) Math - Short Answer What is the largest possible three-digit number such that all of its digits are distinct and the sum of the digits is less than 20?  

text[[115, 189, 264, 210]]
ANSWER: 982  

sub_title[[456, 233, 540, 254]]
## BONUS  

text[[115, 269, 883, 311]]
2) Math - Short Answer Find the sum of an infinite geometric series with first term 64 and fourth term 27.  

text[[115, 327, 264, 348]]
ANSWER: 256sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[112, 131, 833, 155]]
3) Chemistry - Short Answer How many angular nodes are in a 3p orbital?  

text[[115, 168, 240, 189]]
ANSWER: 1  

sub_title[[456, 211, 540, 232]]
## BONUS  

text[[115, 247, 884, 291]]
3) Chemistry - Short Answer Order the following three bonds from weakest to strongest: 1) C-H single bond; 2) C-C single bond; 3) C-C double bond  

text[[115, 305, 288, 326]]
ANSWER: 2, 1, 3sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[113, 131, 883, 175]]
4) Earth and Space - Multiple Choice Which of the following soil horizons is the shallowest?  

text[[113, 190, 171, 275]]
W) A 
X) B 
Y) C 
Z) E  

text[[114, 291, 281, 311]]
ANSWER: W) A  

sub_title[[455, 333, 540, 354]]
## BONUS  

text[[114, 369, 882, 413]]
4) Earth and Space - Short Answer What is the name for the process which generates precipitation via the growth of ice crystals in supercooled clouds?  

text[[114, 427, 393, 448]]
ANSWER: Bergeron processsub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 881, 175]]
5) Biology - Short Answer What enzyme is responsible for cleaving pre-miRNA hairpins into mature pre-miRNAs?  

text[[115, 189, 300, 210]]
ANSWER: DICER  

sub_title[[456, 233, 540, 254]]
## BONUS  

text[[114, 268, 883, 312]]
5) Biology - Multiple Choice Which of the following would NOT occur during photosynthesis?  

text[[114, 327, 445, 412]]
W) Increase in pH of the stroma  
X) Increase in ATP production  
Y) Reduction of oxygen into water  
Z) Increase in G3P production  

text[[114, 427, 557, 448]]
ANSWER: Y) Reduction of oxygen into watersub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 883, 196]]
6) Physics - Short Answer A circular loop on a roller coaster is built with a radius of 5 meters. To the nearest meter per second, what is the minimum velocity at the top of the loop that would allow the cart to complete the loop?  

text[[115, 211, 241, 231]]
ANSWER: 7  

sub_title[[456, 254, 540, 275]]
## BONUS  

text[[114, 290, 882, 333]]
6) Physics - Multiple Choice Which of the following is an example of a noninertial reference frame?  

text[[114, 349, 765, 435]]
W) An object moving at constant velocity through a viscous medium  X) A stationary electric charge  Y) A stationary charged particle in a magnetic field  Z) A particle rotating at a constant speed  

text[[114, 450, 612, 471]]
ANSWER: Z) A particle rotating at a constant speedsub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[113, 131, 883, 175]]
7) X-Risk - Multiple Choice Nuclear decay can be modeled as a reaction with which of the following orders?  

text[[114, 190, 220, 274]]
W) Zeroth 
X) First 
Y) Second 
Z) Third  

text[[115, 290, 303, 311]]
ANSWER: X) First  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[114, 369, 882, 434]]
7) X-Risk - Multiple Choice What is the name of the common paradigm in machine learning which describes problems as agents interacting with an environment, trying to maximize their reward?  

text[[114, 448, 435, 534]]
W) Supervised learning 
X) Unsupervised learning 
Y) Reinforcement learning 
Z) Inverse reinforcement learning  

text[[114, 549, 482, 570]]
ANSWER: Y) Reinforcement learningsub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[113, 131, 883, 174]]
8) Math - Short Answer A right triangle has side lengths of 6, 8, and 10. What is the radius of the triangle's incircle?  

text[[115, 189, 241, 209]]
ANSWER: 2  

sub_title[[456, 233, 540, 254]]
## BONUS  

text[[115, 269, 883, 312]]
8) Math - Short Answer Compute 11 times 12 plus 13 times 14 minus 11 times 14 minus 12 times 13.  

text[[115, 328, 241, 348]]
ANSWER: 4sub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[113, 131, 883, 196]]
9) Chemistry - Short Answer The equilibrium constant for the reaction \(\mathrm{A} + \mathrm{B} \longrightarrow \mathrm{C}\) [A plus B yields C] is \(K\) . For the reaction \(3\mathrm{C} \longrightarrow 3\mathrm{A} + 3\mathrm{B}\) [three- C yields three-A plus three-B], what is the equilibrium constant in terms of K?  

text[[115, 210, 280, 231]]
ANSWER: \(1 / K^{3}\)  

sub_title[[456, 254, 540, 275]]
## BONUS  

text[[113, 290, 883, 333]]
9) Chemistry - Short Answer In the \(\mathrm{OF}^{+}\) cation, what is the bond order of the oxygen fluorine bond?  

text[[115, 348, 241, 368]]
ANSWER: 2sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 884, 175]]
10) Earth and Space - Multiple Choice Which of the following statements is not true of chondrites?  

text[[115, 190, 760, 276]]
W) They can contain volatiles 
X) They cooled extremely quickly 
Y) They likely condensed at high temperatures near the solar nebula 
Z) They have Widmanstatten [WID-min-stot-in] patterns  

text[[115, 290, 760, 312]]
ANSWER: Z) They have Widmanstatten [WID-min-stot-in] patterns  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[115, 369, 884, 454]]
10) Earth and Space - Multiple Choice Which of the following best explains why in some binary systems, more massive stars are observed to be in the same stage of life as less massive stars, implying that they have similar life spans to lesser mass stars?  

text[[115, 470, 881, 576]]
W) The more massive star formed later than the less massive star 
X) The more massive star's fusion is disrupted through gravitational heating 
Y) The more massive star transfers mass to the younger star while it is evolving 
Z) The less massive star heats up more rapidly due to the Kelvin-Helmholtz mechanism  

text[[115, 592, 883, 635]]
ANSWER: Y) The more massive star transfers mass to the younger star while it is evolvingsub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[115, 131, 883, 174]]
11) Biology - Short Answer What molecules are used in Sanger sequencing to induce chain termination of DNA strands?  

text[[115, 189, 742, 211]]
ANSWER: Dideoxy nucleotide triphosphates (ACCEPT: ddNTPs)  

sub_title[[456, 233, 540, 254]]
## BONUS  

text[[115, 269, 888, 355]]
11) Biology - Short Answer During the termination of transcription, order the following three steps in the order of which they occur: 1) Reading of the polyadenylation [POL-ee-uh-dee-null-AY-shin] signal; 2) Release of RNA from the transcription complex; 3) Reading of the stop codon.  

text[[115, 370, 288, 390]]
ANSWER: 3, 1, 2sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 883, 196]]
12) Physics - Multiple Choice What is the direction of propagation for an electromagnetic wave where the electric field is moving in the positive \(x\) direction and the magnetic field is moving in the positive \(z\) direction?  

text[[114, 211, 250, 297]]
W) Positive y 
X) Negative y 
Y) Positive z 
Z) Negative z  

text[[115, 312, 360, 333]]
ANSWER: X) Negative y  

sub_title[[456, 354, 540, 375]]
## BONUS  

text[[115, 390, 883, 455]]
12) Physics - Short Answer A circuit is created from three resistors in parallel with resistances of 1 ohm, 2 ohms, and 4 ohms, respectively. The circuit is then attached to an 8 volt battery. What is the total power output of the circuit in watts?  

text[[115, 470, 264, 490]]
ANSWER: 112sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 883, 196]]
13) X-Risk - Multiple Choice A researcher finds that CO2 concentrations and light pollution are highly positively correlated. Which of the following is the confounding variable in this situation?  

text[[114, 211, 313, 297]]
W) Industrialization 
X) Human health 
Y) World population 
Z) Time  

text[[115, 312, 419, 333]]
ANSWER: W) Industrialization  

sub_title[[455, 354, 540, 375]]
## BONUS  

text[[115, 390, 883, 455]]
13) X-Risk - Multiple Choice In 2021, the Amazon rainforest became a carbon source when it had previously been a carbon sink. What is the main driver for this change?  

text[[114, 469, 312, 556]]
W) Deforestation 
X) Forest fires 
Y) Stream migration 
Z) Sedimentation  

text[[115, 572, 393, 592]]
ANSWER: W) Deforestationsub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[114, 131, 884, 194]]
14) Math - Short Answer In triangle ABC, D lies on BC such that AD bisects angle BAC. If AB equals 9, AC equals 12, and BD equals 6, what is the length of CD?  

text[[115, 211, 241, 231]]
ANSWER: 8  

sub_title[[456, 254, 540, 275]]
## BONUS  

text[[114, 290, 867, 312]]
14) Math - Short Answer Find the sum of the first 20 positive square numbers.  

text[[115, 328, 278, 348]]
ANSWER: 2870sub_title[[448, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 882, 175]]
15) Chemistry - Multiple Choice Which of the following elemental properties monotonically increases down the alkali earth metal group on the periodic table?  

text[[115, 191, 312, 276]]
W) Atomic radius 
X) Melting point 
Y) Ionization energy 
Z) Electron affinity  

text[[115, 291, 399, 312]]
ANSWER: W) Atomic radius  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[115, 369, 882, 413]]
15) Chemistry - Short Answer Order the following three substances by increasing vapor pressure in their solid state: 1) Carbon dioxide; 2) Water; 3) Ammonia.  

text[[115, 427, 286, 448]]
ANSWER: 2, 3, 1sub_title[[448, 90, 549, 111]]
## TOSS-UP  

text[[115, 132, 883, 196]]
16) Earth and Space - Multiple Choice A large storm blows to the north and encounters a mountain range, where it exhibits orographic lifting. Which of the following locations would receive the most precipitation?  

text[[114, 212, 414, 297]]
W) Southern mountainside 
X) Top of the mountain 
Y) Northern mountainside 
Z) Plain north of the mountains  

text[[115, 312, 482, 333]]
ANSWER: W) Southern mountainside  

sub_title[[456, 354, 540, 375]]
## BONUS  

text[[115, 391, 883, 454]]
16) Earth and Space - Multiple Choice The Permian-Triassic extinction was caused by a rapid increase of atmospheric carbon dioxide due to which of the following events?  

text[[114, 470, 373, 556]]
W) Volcanic eruptions 
X) Ozone layer destruction 
Y) Ocean anoxia 
Z) Meteor impact  

text[[115, 572, 440, 592]]
ANSWER: W) Volcanic eruptionssub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 883, 175]]
17) Biology - Multiple Choice Which of the following best describes the change in mean pressure as blood traverses from the aorta to the veins?  

text[[114, 190, 387, 275]]
W) Decreases then increases 
X) Increases then decreases 
Y) Decreases 
Z) Increases  

text[[115, 291, 355, 311]]
ANSWER: Y) Decreases  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[115, 370, 883, 435]]
17) Biology - Short Answer Identify all of the following three interactions that dominate in secondary structure: 1) Hydrophobic interactions; 2) Disulfide bonds; 3) Hydrogen bonding between R groups.  

text[[115, 450, 280, 470]]
ANSWER: Nonesub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[115, 131, 883, 196]]
18) Physics - Short Answer The law of reflection, stating that the incident angle of a ray of light is equal to the angle at which it is reflected, assumes what type of reflection is occurring?  

text[[115, 211, 311, 231]]
ANSWER: Specular  

sub_title[[456, 254, 540, 275]]
## BONUS  

text[[115, 290, 883, 354]]
18) Physics - Short Answer Calculate the moment of inertia, in kilogram-meters squared, about a central axis of a hollow sphere of radius 5 meters and mass 3 kilograms.  

text[[115, 370, 253, 390]]
ANSWER: 50sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 882, 196]]
19) X-Risk - Short Answer A neural network is often modeled purely in terms of its inputs and outputs, without regard for its internal workings. What is the commonly used term for this model in engineering?  

text[[115, 211, 325, 231]]
ANSWER: Black box  

sub_title[[456, 253, 540, 275]]
## BONUS  

text[[115, 290, 882, 333]]
19) X-Risk - Multiple Choice Which of the following best explains why RNA viruses have a higher mutation rate than DNA viruses?  

text[[115, 348, 808, 433]]
W) The RNA polymerase in most RNA viruses lacks proofreading ability  X) Most RNA viruses have a shorter life cycle than DNA viruses  Y) Most RNA viruses have a larger genome than DNA viruses  Z) RNA viruses have a viral envelope that is permeable to mutagens  

text[[115, 448, 883, 491]]
ANSWER: W) The RNA polymerase in most RNA viruses lacks proofreading abilitysub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 882, 196]]
20) Math - Short Answer Caleb is on a grid at the point \((0,0)\) and wants to reach the point \((2,4)\) . Every second, he can move either one unit right or one unit up. How many distinct paths can Caleb take to reach his destination?  

text[[115, 211, 252, 231]]
ANSWER: 15  

sub_title[[456, 254, 540, 275]]
## BONUS  

text[[114, 290, 884, 374]]
20) Math - Short Answer Mark has an array of integers in the order \([2,3,4,5,6,1]\) . With each move, he can swap any two neighboring elements' positions in the array. How many moves are needed for Mark to make the array sorted in descending order?  

text[[115, 391, 253, 411]]
ANSWER: 10sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 883, 175]]
21) Chemistry - Short Answer In a single-step reaction, what term describes the difference in potential energy between the reactants and the transition state?  

text[[115, 190, 395, 210]]
ANSWER: Activation energy  

sub_title[[456, 233, 540, 254]]
## BONUS  

text[[114, 269, 883, 312]]
21) Chemistry - Short Answer What is the molecular geometry of the central sulfur atom in sulfur tetrafluoride?  

text[[115, 328, 300, 348]]
ANSWER: Seesawsub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 883, 175]]
22) Earth and Space - Short Answer What name is given to the process of mass decay caused by virtual particles slipping beyond an event horizon?  

text[[115, 190, 404, 210]]
ANSWER: Hawking radiation  

sub_title[[456, 233, 540, 254]]
## BONUS  

text[[115, 269, 883, 333]]
22) Earth and Space - Short Answer Identify all of the following three statements that are true of Population II stars: 1) They are common in open clusters; 2) They are metal rich; 3) They have highly eccentric orbits.  

text[[115, 348, 288, 369]]
ANSWER: 3 onlysub_title[[448, 90, 549, 110]]
## TOSS-UP  

text[[113, 131, 883, 175]]
23) Biology - Multiple Choice Which of the following best describes how lipid soluble hormones that are NOT steroids typically elicit a response?  

text[[113, 190, 606, 275]]
W) Bind to cell surface receptors 
X) Bind to transcription factors in the cytosol 
Y) Bind to transcription factors in the nucleus 
Z) Bind to nascent mRNA transcripts in the nucleus  

text[[114, 290, 660, 311]]
ANSWER: Y) Bind to transcription factors in the nucleus  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[114, 369, 883, 412]]
23) Biology - Short Answer Identify all of the following three diseases that are genetically dominant: 1) Albinism; 2) Cystic Fibrosis; 3) Gigantism.  

text[[115, 427, 241, 448]]
ANSWER: 3sub_title[[448, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 883, 218]]
24) Physics - Short Answer Nuclear fusion within stars can occur once atoms overcome the intense Coulomb interactions. One way of doing this is through what phenomenon based on the low probability of the atomic wave transmitting through the barrier?  

text[[115, 232, 628, 254]]
ANSWER: Quantum tunneling (ACCEPT: Tunneling)  

sub_title[[456, 275, 540, 297]]
## BONUS  

text[[115, 311, 883, 397]]
24) Physics - Short Answer When a point charge is placed very far away from the surface of a thin spherical conducting shell with uniform volume density, it experiences an electric field E. If the radius of the shell is doubled, what will be the new electric field experienced by the test charge in terms of E?  

text[[115, 412, 244, 432]]
ANSWER: E