text[[0, 0, 997, 997]]
# 1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1sub_title[[445, 171, 549, 193]]
## TOSS-UP  

text[[115, 228, 883, 294]]
1) X-Risk - Short Answer A nuclear winter could be caused by the ejection of light-absorbing particles into what layer of the atmosphere, where they would have a longer lifetime than those near the surface?  

text[[116, 309, 347, 330]]
ANSWER: Stratosphere  

sub_title[[456, 352, 540, 373]]
## BONUS  

text[[115, 388, 882, 451]]
1) X-Risk - Short Answer What term describes the hypothetical point at which technological growth becomes uncontrollable and irreversibly alters human civilization?  

text[[115, 466, 694, 490]]
ANSWER: Technological singularity (ACCEPT: Singularity)sub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[113, 130, 883, 175]]
2) Math - Multiple Choice The graph of the function \(y = 2x^{2} + y^{2} + 4x - 5y - 5\) is an example of what conic section?  

text[[113, 190, 245, 275]]
W) Circle 
X) Ellipse 
Y) Parabola 
Z) Hyperbola  

text[[114, 290, 325, 311]]
ANSWER: X) Ellipse  

sub_title[[455, 333, 540, 354]]
## BONUS  

text[[113, 368, 883, 413]]
2) Math - Short Answer Find all real solutions to the equation: \(2\sqrt{x} + 3\sqrt[4]{x} - 2 = 0\) [2 square root of x plus 3 fourth root of x minus 2 equals 0]  

text[[114, 427, 272, 448]]
ANSWER: 1/16sub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[114, 131, 883, 240]]
3) Chemistry - Short Answer The standard reduction potential of \(\mathrm{Fe}_{3}^{+}\) [iron three plus] to iron metal is -0.04, while the standard reduction potential of \(\mathrm{Ni}_{2}^{+}\) [nickel two plus] to nickel metal is -0.23. For a standard galvanic cell with solutions of \(\mathrm{Fe}_{3}^{+}\) [iron three plus] and \(\mathrm{Ni}_{2}^{+}\) [nickel two plus] in different compartments, what is the cell potential?  

text[[115, 254, 270, 274]]
ANSWER: 0.19  

sub_title[[456, 296, 540, 317]]
## BONUS  

text[[115, 333, 883, 397]]
3) Chemistry - Short Answer Order the following three gases by increasing rate of effusion at 400 kelvin through a pinhole: 1) Oxygen; 2) Hydrogen fluoride; 3) Ammonia.  

text[[115, 411, 288, 432]]
ANSWER: 1, 2, 3sub_title[[448, 90, 549, 111]]
## TOSS-UP  

text[[113, 131, 900, 175]]
4) Earth and Space - Multiple Choice What atmospheric circulation cell is bounded by the equatorial low and subtropical high?  

text[[114, 190, 220, 275]]
W) Hadley 
X) Ferrel 
Y) Walker 
Z) Polar  

text[[115, 291, 332, 312]]
ANSWER: W) Hadley  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[114, 370, 884, 435]]
4) Earth and Space - Short Answer Identify all of the following three unconformities that commonly only involve sedimentary rocks: 1) Angular unconformity; 2) Nonconformity; 3) Disconformity.  

text[[115, 449, 298, 470]]
ANSWER: 1 and 3sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 882, 219]]
5) Biology - Multiple Choice Two species of corn plants can be crossed to produce a hybrid offspring that is infertile. This offspring randomly duplicates its genome, and now can self cross to produce more of itself, creating a new species. This is an example of which of the following?  

text[[114, 233, 352, 319]]
W) Sympatric speciation  X) Allopatric speciation  Y) Founder effect  Z) Bottleneck effect  

text[[114, 334, 463, 355]]
ANSWER: W) Sympatric speciation  

sub_title[[456, 376, 540, 397]]
## BONUS  

text[[114, 411, 882, 455]]
5) Biology - Short Answer What sex determination system is utilized by individuals of hymenoptera [HY-min-OP-tur-uh] and other social insects?  

text[[114, 469, 682, 492]]
ANSWER: Haplodiploid system (ACCPET: Haplodiploidy)sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 883, 239]]
6) Physics - Short Answer A fluid is added to a container where two pistons of non-equal areas are touching the fluid. On a piston with area 20 square centimeters, a force pushes down with a force of 70 newtons. The piston on the other side with area 40 square centimeters experiences an upward force of what magnitude, in newtons?  

text[[115, 254, 265, 275]]
ANSWER: 140  

sub_title[[456, 297, 540, 318]]
## BONUS  

text[[114, 333, 883, 397]]
6) Physics - Multiple Choice Which of the following base and height dimensions for a ramp would ensure the largest magnitude of acceleration of a block placed at the top?  

text[[114, 412, 327, 499]]
W) Base: 5, Height: 3 
X) Base: 4, Height: 3 
Y) Base: 3, Height: 5 
Z) Base: 4, Height: 4  

text[[114, 514, 432, 535]]
ANSWER: Y) Base: 3, Height: 5sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 882, 196]]
7) X-Risk - Short Answer In game theory, what thought experiment involves two completely rational agents either cooperating for a mutual reward or betraying each other for an individual reward?  

text[[115, 210, 411, 231]]
ANSWER: Prisoner's dilemma  

sub_title[[456, 253, 540, 275]]
## BONUS  

text[[115, 290, 882, 375]]
7) X-Risk - Short Answer One early proposal for determining whether a computer program exhibits human-level intelligence was to see if a human judge could discern textual messages sent by a computer from those sent by a human. What is this evaluation known as?  

text[[115, 390, 594, 412]]
ANSWER: Turing test (ACCEPT: Imitation game)sub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[113, 131, 865, 153]]
8) Math - Short Answer If \(45\%\) of a certain number \(x\) is 50, what is \(27\%\) of \(x\) ?  

text[[115, 168, 253, 189]]
ANSWER: 30  

sub_title[[456, 211, 540, 232]]
## BONUS  

text[[115, 247, 883, 312]]
8) Math - Short Answer Tyler draws a number from all integers between 1 and 90, inclusive and at random. What is the probability that Tyler draws a number relatively prime to both 5 and 6?  

text[[115, 327, 271, 348]]
ANSWER: 4/15sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[113, 131, 883, 175]]
9) Chemistry - Short Answer What is the average oxidation state of oxygen in \(\mathrm{O_2F_2?}\)  

text[[115, 190, 258, 210]]
ANSWER: \(+1\)  

sub_title[[456, 233, 540, 254]]
## BONUS  

text[[113, 269, 883, 312]]
9) Chemistry - Multiple Choice Which of the following pairs of elements will have the highest bond dissociation energy?  

text[[113, 327, 337, 413]]
W) Silver and fluorine  X) Carbon and fluorine  Y) Silver and iodine  Z) Carbon and iodine  

text[[114, 428, 448, 449]]
ANSWER: X) Carbon and fluorinesub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 882, 196]]
10) Earth and Space - Short Answer Quintessence and the cosmological constant are two proposed forms of what form of energy which is responsible for the accelerating expansion of the universe?  

text[[115, 210, 345, 231]]
ANSWER: Dark energy  

sub_title[[456, 253, 540, 275]]
## BONUS  

text[[115, 290, 883, 333]]
10) Earth and Space - Multiple Choice Which of the following is closest to the percentage of the total energy in the universe that is made up of dark energy?  

text[[115, 348, 179, 433]]
W) 30 
X) 50 
Y) 70 
Z) 90  

text[[115, 450, 284, 470]]
ANSWER: Y) 70sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 883, 175]]
11) Biology - Multiple Choice The enzyme nitrogenase [ny- TRAW-juh-nase] is most directly involved in which of the following processes?  

text[[114, 190, 310, 275]]
W) Ammonification 
X) Nitrogen fixation 
Y) Denitrification 
Z) Nitrification  

text[[114, 291, 421, 311]]
ANSWER: X) Nitrogen fixation  

sub_title[[455, 333, 540, 354]]
## BONUS  

text[[114, 370, 883, 412]]
11) Biology - Short Answer Identify all of the following three vitamins that are fat soluble: 1) A; 2) B3; 3) E.  

text[[114, 428, 298, 448]]
ANSWER: 1 and 3sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 883, 196]]
12) Physics - Multiple Choice Which of the following changes to the force applied on a spherical surface and the radius of the sphere would result in the smallest change in pressure?  

text[[115, 211, 492, 297]]
W) Force is doubled, radius is tripled  
X) Force is tripled, radius is quadrupled  
Y) Force is tripled, radius is doubled  
Z) Force is quadrupled, radius is tripled  

text[[115, 311, 574, 333]]
ANSWER: Y) Force is tripled, radius is doubled  

sub_title[[455, 354, 540, 375]]
## BONUS  

text[[115, 390, 883, 455]]
12) Physics - Multiple Choice A graduate student calculated the mass of a gold nucleus by summing the masses of the protons and neutrons within it. The mass they calculated is:  

text[[115, 470, 822, 559]]
W) Greater than the actual mass  
X) Less than the actual mass  
Y) Equal to the actual mass  
Z) Mass relative to actual mass is dependent on the specific isotope of gold  

text[[115, 572, 531, 593]]
ANSWER: W) Greater than the actual masssub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 884, 175]]
13) X-Risk - Multiple Choice Which chemical element is used in the core of implosion-type nuclear weapons, such as the one used in the Trinity test?  

text[[114, 190, 255, 275]]
W) Uranium 
X) Neptunium 
Y) Plutonium 
Z) Thorium  

text[[115, 291, 357, 311]]
ANSWER: Y) Plutonium  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[115, 370, 882, 433]]
13) X-Risk - Short Answer As the global effects of climate change continue to develop, the local climate of Western Europe is predicted to cool due to the disruption of what Atlantic ocean current?  

text[[115, 448, 882, 490]]
ANSWER: Gulf stream (ACCEPT: AMOC, Atlantic meridional overturning circulation)sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 883, 197]]
14) Math - Multiple Choice In base 10, the sum of AB and CD is AEF, where each letter represents a unique integer digit. Which of the following integers could C equal?  

text[[114, 211, 166, 295]]
W) 3 
X) 5 
Y) 7 
Z) 9  

text[[115, 312, 270, 333]]
ANSWER: Z) 9  

sub_title[[455, 355, 540, 376]]
## BONUS  

text[[114, 391, 883, 434]]
14) Math - Short Answer How many unique triangles with integer side lengths have a perimeter of 36 and area of 72?  

text[[115, 448, 242, 469]]
ANSWER: 0sub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[113, 131, 883, 174]]
15) Chemistry - Multiple Choice Which of the following reactions is a redox reaction?  

text[[113, 190, 539, 277]]
W) \(2\mathrm{NO}_{2}\longrightarrow [\mathrm{yields}]\mathrm{N}_{2}\mathrm{O}_{4}\) X) \(\mathrm{P_4O_{10} + 6H_2O\longrightarrow 4H_3PO_4}\) Y) HCl + NaHCO3 NaCI + H2O + CO2 Z) \(2\mathrm{H}_{2}\mathrm{O}_{2}\longrightarrow 2\mathrm{H}_{2}\mathrm{O} + \mathrm{O}_{2}\)  

text[[113, 290, 490, 312]]
ANSWER: Z) \(2\mathrm{H}_{2}\mathrm{O}_{2}\longrightarrow 2\mathrm{H}_{2}\mathrm{O} + \mathrm{O}_2\)  

sub_title[[455, 333, 540, 354]]
## BONUS  

text[[113, 368, 883, 432]]
15) Chemistry - Short Answer A basic buffer is prepared using \(10^{-3}\) moles of an acid with a pKa of 3 and \(10^{-3}\) moles of the acid's conjugate acid. What is the pH of the buffer?  

text[[113, 448, 241, 469]]
ANSWER: 3sub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[115, 131, 883, 153]]
16) Earth and Space - Short Answer What is the oxidation state of iron in pyrite?  

text[[115, 168, 388, 189]]
ANSWER: +2 (ACCEPT: 2)  

sub_title[[456, 211, 540, 232]]
## BONUS  

text[[115, 247, 883, 332]]
16) Earth and Space - Multiple Choice Abigail is studying the land formations in Mt. Washington and discovers a dike that cuts through an older body of granite. Which of the following principles allows her to determine the relative age of the two rocks?  

text[[115, 349, 398, 435]]
W) Superposition  X) Original horizontality  Y) Lateral continuity  Z) Cross-cutting relationships  

text[[115, 450, 510, 471]]
ANSWER: Z) Cross-cutting relationshipssub_title[[448, 90, 549, 110]]
## TOSS-UP  

text[[114, 131, 884, 175]]
17) Biology - Multiple Choice Which of the following would occur more often in C3 plants than in C4 plants?  

text[[114, 190, 445, 276]]
W) Thriving in high-intensity light 
X) Photorespiration 
Y) PEP carboxylase fixes CO2 
Z) Open stomata at night  

text[[115, 291, 415, 312]]
ANSWER: X) Photorespiration  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[115, 370, 882, 433]]
17) Biology - Short Answer Identify all of the following three viruses that belong to the family retroviridae [ret-ro-VEER-uh-dee]: 1) HIV; 2) Rhinovirus; 3) Coronavirus.  

text[[115, 449, 288, 470]]
ANSWER: 1 onlysub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[115, 131, 881, 195]]
18) Physics - Short Answer What general technique is used to modulate the properties of electronic materials by introducing impurities to modify their band structure?  

text[[115, 211, 300, 232]]
ANSWER: Doping  

sub_title[[456, 253, 540, 275]]
## BONUS  

text[[115, 290, 883, 333]]
18) Physics - Multiple Choice Which of the following elements, when presented as an impurity in silicon, would result in a p-type semiconductor?  

text[[115, 349, 263, 435]]
W) Phosphorus 
X) Antimony 
Y) Carbon 
Z) Boron  

text[[115, 451, 316, 471]]
ANSWER: Z) Boronsub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 883, 175]]
19) X-Risk - Multiple Choice What is the term to describe hardy organisms that are the first to colonize barren environments or disrupted steady-state ecosystems?  

text[[115, 190, 333, 275]]
W) Foundation species 
X) Climax species 
Y) Keystone species 
Z) Pioneer species  

text[[115, 291, 402, 312]]
ANSWER: Z) Pioneer species  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[115, 369, 883, 412]]
19) X-Risk - Multiple Choice AI boxing refers to a proposal to mitigate the risk of unaligned AI by doing which of the following?  

text[[113, 426, 883, 558]]
W) Isolating it from the world at large except for select communication channels 
X) Placing the AI's communications under the oversight of another AI system 
Y) Separating an AI's capabilities programming from its safety programming, to prevent the two interfering 
Z) Building the AI out of modular systems so that each module can be safety- tested individually  

text[[115, 571, 883, 613]]
ANSWER: W) Isolating it from the world at large except for select communication channelssub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 883, 196]]
20) Math - Short Answer Currently, the time on a digital clock is 12:28. A palindrome time is when the time with colon removed is a palindrome, such as at 2:12 or 10:01. How many minutes are there until the next palindrome time?  

text[[115, 210, 398, 232]]
ANSWER: 33 (ACCEPT: 63)  

sub_title[[456, 254, 540, 275]]
## BONUS  

text[[114, 290, 883, 333]]
20) Math - Short Answer What is the degree measure of the angle formed by the hour and minute hand at 12:28 on an analog clock?  

text[[115, 348, 265, 369]]
ANSWER: 154sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[113, 131, 881, 175]]
21) Chemistry - Multiple Choice Which of the following elements appears closest to red during a flame test?  

text[[114, 190, 260, 275]]
W) Sodium 
X) Magnesium 
Y) Potassium 
Z) Calcium  

text[[115, 290, 336, 311]]
ANSWER: Z) Calcium  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[114, 368, 883, 476]]
21) Chemistry - Multiple Choice Carbon-14, which has a half-life of 6,000 years, is initially present in a geologic deposit and decays without replacement, while all carbon-12 initially present does not decay. When the ratio of carbon-12 to carbon-14 in the geologic deposit triples, which of the following is closest to the number of years that have passed?  

text[[114, 490, 210, 576]]
W) 6000 
X) 12000 
Y) 18000 
Z) 24000  

text[[115, 592, 319, 612]]
ANSWER: X) 12000sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 883, 196]]
22) Earth and Space - Multiple Choice Which of the following types of radiation would best inform a team of scientists about the presence of dust near a galaxy's center?  

text[[114, 211, 255, 297]]
W) Ultraviolet 
X) Infrared 
Y) Radio 
Z) Optical  

text[[115, 312, 336, 333]]
ANSWER: X) Infrared  

sub_title[[456, 355, 540, 376]]
## BONUS  

text[[114, 391, 882, 455]]
22) Earth and Space - Short Answer Saturn's largest known moon, Titan, is notable for having clouds and lakes primarily composed of what chemical compound?  

text[[115, 469, 312, 490]]
ANSWER: Methanesub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 882, 175]]
23) Biology - Short Answer Klinefelter's syndrome is characterized by how many copies of the X chromosome?  

text[[115, 190, 241, 210]]
ANSWER: 2  

sub_title[[456, 232, 540, 254]]
## BONUS  

text[[114, 268, 883, 312]]
23) Biology - Multiple Choice Huntington's disease is characterized by which of the following inheritance patterns?  

text[[114, 327, 352, 412]]
W) Autosomal dominant 
X) Autosomal recessive 
Y) Sex-linked dominant 
Z) Sex-linked recessive  

text[[114, 427, 463, 448]]
ANSWER: W) Autosomal dominantsub_title[[448, 90, 549, 110]]
## TOSS-UP  

text[[114, 131, 883, 218]]
24) Physics - Short Answer A student is observing the properties of electrons ejected from a material when exposed to light. What quantity of the material can the student measure along with the electron kinetic energy to find the energy of the photons?  

text[[115, 233, 365, 253]]
ANSWER: Work function  

sub_title[[456, 275, 540, 296]]
## BONUS  

text[[114, 312, 883, 375]]
24) Physics - Multiple Choice In the Stern-Gerlach [GUR-lock] experiment, the deflection of silver atoms in a magnetic field was due to what quantum property of the atoms?  

text[[114, 391, 410, 476]]
W) Orbital angular momentum  X) Spin  Y) Charge  Z) Mass  

text[[115, 492, 303, 513]]
ANSWER: X) Spin