
# 1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1
## TOSS-UP  


1) X-Risk - Multiple Choice In epistemology [ep-ee-stem-AL-uh-jee], which of the following terms describes a belief held before it is changed by evidence?  


W) Prior 
X) Default 
Y) Base 
Z) Update  


ANSWER: W) Prior  


## BONUS  


1) X-Risk - Short Answer Since the 1960s, a change in the composition of gasoline has decreased the concentration of what toxic element in human blood?  


ANSWER: Lead
## TOSS-UP  


2) Math - Multiple Choice Which of the following quadratics has no real roots?  


W) \(2x^{2} - 6x - 8 = 0\) X) \(- 2x^{2} + 6x + 8 = 0\) Y) \(- 2x^{2} - 6x - 8 = 0\) Z) \(2x^{2} + 6x - 8 = 0\)  


ANSWER: Y) \(- 2x^{2} - 6x - 8 = 0\)  


## BONUS  


2) Math - Short Answer Three fair six-sided dice are rolled simultaneously. What is the probability that the product of the three rolls is greater than 200?  


ANSWER: 1/216
## TOSS-UP  


3) Chemistry - Multiple Choice The rate of the reaction \(\mathrm{A} + \mathrm{B} \longrightarrow \mathrm{C}\) [A plus B yields C] is independent of the concentrations of the reactants. Which of the following describes the graph produced when the concentration of A is plotted against time?  


W) Upwards sloping line 
X) Downwards sloping line 
Y) Logarithmic curve 
Z) Exponential curve  


ANSWER: X) Downwards sloping line  


## BONUS  


3) Chemistry - Short Answer When a reaction is disturbed from equilibrium, it is observed that the reaction shifts in a way to counteract this deviation from equilibrium. This is known as what principle?  


ANSWER: Le Chatelier's principle
## TOSS-UP  


4) Earth and Space - Short Answer Density variations that drive deep-ocean circulation are driven by differences in what two properties of the ocean?  


ANSWER: Temperature and salinity  


## BONUS  


4) Earth and Space - Multiple Choice Which of the following landforms is typically not formed by rivers?  


W) Deltas 
X) Horsts 
Y) Alluvial fans 
Z) Oxbow lakes  


ANSWER: X) Horsts
## TOSS-UP  


5) Biology - Multiple Choice Which of the following phyla contains humans?  


W) Chordata 
X) Platyhelminthes 
Y) Echinodermata 
Z) Cnidaria  


ANSWER: W) Chordata  


## BONUS  


5) Biology - Short Answer Identify all of the following three statements that are differences between plant and animal cells: 1) Plant cells prefer a hypotonic environment; 2) Plant cells lack a cytoskeleton; 3) Plant cells are connected via gap junctions.  


ANSWER: 1 only
## TOSS-UP  


6) Physics - Multiple Choice Which of the following particles has the greatest mass?  


W) Alpha 
X) Beta 
Y) Gamma 
Z) Neutrino  


ANSWER: W) Alpha  


## BONUS  


6) Physics - Short Answer A simple pendulum is placed between two walls separated by the pendulum's amplitude such that each second, the pendulum strikes a wall. To two significant figures and in meters, what is the length of the simple pendulum's string?  


ANSWER: 1.0
## TOSS-UP  


7) X-Risk - Short Answer Melting ice as a result of global warming creates a positive feedback loop via the reduction of what quantity, which describes the amount of light reflected by Earth's surface?  


ANSWER: Albedo [al- BEE- doh]  


## BONUS  


7) X-Risk - Short Answer High levels of iridium at the K-T boundary in strata suggest that the associated mass extinction event was caused by what phenomenon?  


ANSWER: Asteroid impact (ACCEPT: Meteorite impact, DO NOT ACCEPT: Meteor impact)
## TOSS-UP  


8) Math - Short Answer A regular hexagon is constructed such that the distance between opposite points is \(A\) . In terms of \(A\) , what is the perimeter of the hexagon?  


ANSWER: 3A  


## BONUS  


8) Math - Multiple Choice What is the period of the function \(f(x) = \sin (2x) + \cos (3x)\) ?  


W) pi/3 
X) 2pi/3 
Y) pi 
Z) 2pi  


ANSWER: Z) 2pi
## TOSS-UP  


9) Chemistry - Short Answer In the titration of a solution of barium hydroxide with hydrochloric acid, what is the molar ratio of barium hydroxide added to hydrochloric acid added at the equivalence point?  


ANSWER: 1/2 (ACCEPT: 1:2, 1 to 2)  


## BONUS  


9) Chemistry - Multiple Choice Which of the following metals will react with hydrochloric acid?  


W) Copper 
X) Zinc 
Y) Gold 
Z) Platinum  


ANSWER: X) Zinc
## TOSS-UP  


10) Earth and Space - Short Answer Enceladus is the object with the highest albedo in the solar system due to the presence of what substance on its surface?  


ANSWER: Water ice (ACCEPT: Ice)  


## BONUS  


10) Earth and Space - Short Answer A type 1a supernova is differentiated from other type 1 supernovae based on absorption lines of what element?  


ANSWER: Silicon
## TOSS-UP  


11) Biology - Short Answer Red stickleback fish uncontrollably attack any red object they see. This is an example of what kind of behavior?  


ANSWER: Fixed action pattern (ACCEPT: FAP)  


## BONUS  


11) Biology - Short Answer Identify all of the following three diseases that are viral in origin: 1) Ebola; 2) Cholera; 3) Tuberculosis.  


ANSWER: 1 only
## TOSS-UP  


12) Physics - Short Answer A mass of 3 kilograms is spun in a horizontal circle of radius 4 meters at a speed of 6 meters per second. In newtons, what is the centripetal force on the object?  


ANSWER: 27  


## BONUS  


12) Physics - Short Answer A light ray traveling from air to water is positioned at the critical angle. At this angle, instead of partially reflecting and refracting, what phenomenon occurs when the light ray hits the air-water boundary?  


ANSWER: Total internal reflection (DO NOT ACCEPT: Reflection)
## TOSS-UP  


13) X-Risk - Short Answer The bald eagle, peregrine falcon, and osprey's population recovery since being placed on the endangered species list can be attributed to the 1972 ban of what chemical compound by the EPA?  


ANSWER: DDT  


## BONUS  


13) X-Risk - Multiple Choice Which of the following best describes a nuclear fission reaction with a mass equal to its critical mass?  


W) InactiveX) Exponentially decayingY) Self-sustainingZ) Exponentially growing  


ANSWER: Y) Self-sustaining
## TOSS-UP  


14) Math - Multiple Choice Which of the following numbers is not divisible by 9?  


W) 666 
X) 747 
Y) 826 
Z) 972  


ANSWER: Y) 826  


## BONUS  


14) Math - Short Answer A fair coin is flipped five times and comes up heads 4 times. What is the probability that both of the next 2 flips are heads?  


ANSWER: 1/4
## TOSS-UP  


15) Chemistry - Short Answer What is the hybridization of nitrogen in a molecule of ammonia?  


ANSWER: \(sp^3\)  


## BONUS  


15) Chemistry - Multiple Choice Which of the following molecules can exhibit hydrogen bonding?  


W) HF 
X) HCl 
Y) HBr 
Z) HI  


ANSWER: W) HF
## TOSS-UP  


16) Earth and Space - Multiple Choice Which of the following types of sediments is typically found on the continental shelf?  


W) Terrigenous sediments  X) Abyssal clay  Y) Calcareous [kal- KAIR- ee- us] ooze  Z) Siliceous [suh- LISH- is] ooze  


ANSWER: W) Terrigenous sediments  


## BONUS  


16) Earth and Space - Short Answer The jet stream usually reaches the highest wind speeds during which season?  


ANSWER: Winter
## TOSS-UP  


17) Biology - Multiple Choice Which of the following organisms does not possess true tissue?  


W) Sea cucumber 
X) Sand dollar 
Y) Sea urchin 
Z) Sea sponge  


ANSWER: Z) Sea sponge  


## BONUS  


17) Biology - Short Answer Identify all of the following three interactions that benefit at least one of the species involved: 1) Commensalism; 2) Parasitism; 3) Mutualism  


ANSWER: All
## TOSS-UP  


18) Physics - Multiple Choice Which of the following is an example of a nonconservative force?  


W) Spring force 
X) Electrostatic force 
Y) Gravity 
Z) Friction  


ANSWER: Z) Friction  


## BONUS  


18) Physics - Multiple Choice A block begins to slide down a ramp once it reaches an angle of 45 degrees. Which of the following is closest to the coefficient of static friction of this system?  


W) \(\frac{1}{2}\) X) \(\frac{\sqrt{2}}{2}\) Y) 1 Z) \(\sqrt{2}\)  


ANSWER: Y) 1
## TOSS-UP  


19) X-Risk - Short Answer Scientists recently developed a thin metal oxide that produces voltage proportional to the amount of electrons or positrons that hit the surface of the metal. Identify all of the following types of radioactive decay that this material could measure: 1) Alpha; 2) Beta; 3) Gamma.  


ANSWER: 2 only  


## BONUS  


19) X-Risk - Short Answer What is the term for the range of orbits around a star in which a planetary surface can support liquid water and Earth-like life?  


ANSWER: Habitable zone (ACCEPT: Goldilocks zone, Circumstellar habitable zone)
## TOSS-UP  


20) Math - Short Answer The Australian Open men's singles tournament consists of 128 tennis players. Given the tournament uses a single-elimination format, how many rounds must a player win to be crowned the champion?  


ANSWER: 7  


## BONUS  


20) Math - Short Answer What value of k causes the following system of two equations to have no solutions: \(x + ky = 1;kx + y = 1\)  


ANSWER: - 1
## TOSS-UP  


21) Chemistry - Short Answer The anilinuim [an-uh-LIN-ee-um] ion is the protonated form of aniline, an aromatic amine [AM- een]. If the pKa of the anilinuim ion is 4.6, what is the pKb of aniline?  


ANSWER: 9.4  


## BONUS  


21) Chemistry - Short Answer What is the bond order of the nitrogen-nitrogen bond in \(\mathrm{N}_2\mathrm{H}_2\) ?  


ANSWER: 2
## TOSS-UP  


22) Earth and Space - Short Answer What limit is the maximum stable mass for a white dwarf before it collapses in a supernova?  


ANSWER: Chandrasekhar [chun- druh- SHEK- har] limit  


## BONUS  


22) Earth and Space - Short Answer Objects with orbital eccentricities greater than 1 follow what type of orbit?  


ANSWER: Hyperbolic
## TOSS-UP  


23) Biology - Short Answer What is the term describing symbiotic organisms composed of fungi and algae?  


ANSWER: Lichen  


## BONUS  


23) Biology - Multiple Choice Derek is trying to perform in vitro prokaryotic DNA replication and mixes several enzymes with nucleotides and his DNA template. When he is done, he notices that many regions of his DNA still contain RNA in them. Which of the following was likely missing in his experiment?  


W) dNTPs  
X) DNA Polymerase I  
Y) Sliding Clamp  
Z) DNA Ligase  


ANSWER: X) DNA Polymerase I
## TOSS-UP  


24) Physics - Short Answer Identify all of the following three changes to the properties of air that would make sound travel faster: 1) Increasing the percent concentration of oxygen compared to nitrogen; 2) Decreasing the average temperature; 3) Increasing the density of air.  


ANSWER: None  


## BONUS  


24) Physics - Short Answer A cart of mass \(m\) and speed 5 meters per second undergoes an acceleration to end up with a final velocity of speed 7 meters per second. In terms of \(m\) , how much work was done on the cart in joules?  


ANSWER: \(12m\)