
## TOSS-UP  


1) Longtermism - Multiple Choice Which of the following properties does NOT contribute to the global warming potential of carbon dioxide in Earth's atmosphere?  


W) Long atmospheric lifetime 
X) High prevalence 
Y) Absorption of infrared light 
Z) Increased Rayleigh [RAY-lee] scattering  


ANSWER: Z) Increased Rayleigh scattering  


## BONUS  


1) Longtermism - Short Answer To the nearest degree Celsius, how much has the atmosphere warmed on average since the beginning of the twentieth century?  


ANSWER: 1 degree
## TOSS-UP  


2) Math - Short Answer Two irregular quadrilaterals are on a plane. What is the maximum possible number of intersections between these two shapes?  


ANSWER: 16  


## BONUS  


2) Math - Short Answer Identify all of the following three definite integrals from one to infinity that converge: 1) \(\frac{1}{x} dx\) [one over x, d x]; 2) \(\frac{1}{x^2} dx\) [one over x squared, d x]; 3) \(\frac{1}{x^3} dx\) [one over x cubed, d x].  


ANSWER: 2 and 3
## TOSS-UP  


3) Chemistry - Short Answer What is the van't Hoff factor of sodium oxalate [OX-uh-late]?  


ANSWER: 3  


## BONUS  


3) Chemistry - Short Answer Rounded to the nearest integer, what is the pH of the solution created when 1 molar ammonia and 0.5 molar hydrochloric acid are mixed in equivalent amounts?  


ANSWER: 9
## TOSS-UP  


4) Earth and Space - Multiple Choice A tropical rainforest like the Amazon would fall under what Köppen classification?  


W) A 
X) B 
Y) C 
Z) D  


ANSWER: W) A  


## BONUS  


4) Earth and Space - Multiple Choice The descending air in the eye of a hurricane is typically warmer at the surface than at altitude due to which of the following processes?  


W) Hydrostatic equilibrium 
X) Adiabatic [AY-dee-uh-BA-dik] heating 
Y) Dew point reduction 
Z) Rain shadow effect  


ANSWER: X) Adiabatic heating
## TOSS-UP  


5) Biology - Multiple Choice Which of the following terms describe gene homology that is due to a speciation event?  


W) Paralagous [pair-AH-luh-gus] 
X) Orthologous [orth-AH-luh-gus] 
Y) Semilogous [seh-MIH-luh-gus] 
Z) Xenologous [zih-NAW-luh-gus]  


ANSWER: X) Orthologous  


## BONUS  


5) Biology - Short Answer If a trait is controlled by two genes, each with two alleles, how many genotypes and phenotypes are possible for this trait respectively?  


ANSWER: 9; 5
## TOSS-UP  


6) Physics - Multiple Choice What physical quantity is defined as the time integral of the Lagrangian [luh-GRAHNJ-ee-in]?  


W) Action 
X) Impulse 
Y) Force 
Z) Displacement  


ANSWER: W) Action  


## BONUS  


6) Physics - Short Answer A beach is enclosed by a rocky outcropping that causes seawater to only flow in from one point. From the beach, an observer sees that the ocean waves spread radially outwards from that point. This is an example of what idea in physics which states that every point on a wavefront is a source of secondary wavelets?  


ANSWER: Huygens' [HOY-gens] principle
## TOSS-UP  


7) Longtermism - Multiple Choice What term describes a situation where the result of a process accelerates that same process?  


W) Positive feedback loop 
X) Negative feedback loop 
Y) Exponential growth 
Z) Growth-accelerated growth  


ANSWER: W) Positive feedback loop  


## BONUS  


7) Longtermism - Short Answer It is hypothesized that positive feedback loops would dramatically increase the rate of AI improvement once the first superintelligent AI is created. What is this effect called?  


ANSWER: Intelligence explosion (ACCEPT: Singularity, FOOM!)
## TOSS-UP  


8) Math - Short Answer Evaluate \(\frac{\sin(\pi / 6)}{\sin(-\pi / 6)}\) [the fraction with numerator sine of pi over six and denominator sine of negative pi over six].  


ANSWER: - 1  


## BONUS  


8) Math - Short Answer What is the sum of the solutions to the equation \(|x^{2} - 18x + 61| = 20\) [open absolute value; x squared minus 18x plus 61; close absolute value; equals 20]?  


ANSWER: 27
## TOSS-UP  


9) Chemistry - Short Answer Which type of chemical bond has cylindrical symmetry and no nodal planes passing through the internuclear axis?  


ANSWER: Sigma bond  


## BONUS  


9) Chemistry - Short Answer Order the following three salts in order of increasing pH when dissolved in water in equimolar amounts: 1) Ammonium chloride; 2) Sodium acetate; 3) Potassium chlorate.  


ANSWER: 1, 3, 2
## TOSS-UP  


10) Earth and Space - Multiple Choice Which of the following properties of a star does not affect its absolute magnitude?  


W) Age 
X) Surface temperature 
Y) Radial velocity 
Z) Radius  


ANSWER: Y) Radial velocity  


## BONUS  


10) Earth and Space - Short Answer Order the following three planets in order of increasing average density: 1) Mars; 2) Mercury; 3) Earth.  


ANSWER: 1, 2, 3
## TOSS-UP  


11) Biology - Short Answer In plants, metabolites travelling through the sym- . plast [SIM-plast] must pass through what cytoplasmic pores?  


ANSWER: Plasmodesmata [plaz- mo- dez- MAH- ta]  


## BONUS  


11) Biology - Short Answer Identify all of the following three animals in which the blastopore [BLAST-uh-pore] would develop into the mouth: 1) Human; 2) Duck; 3) Turtle.  


ANSWER: None
## TOSS-UP  


12) Physics - Short Answer What is the name of the shape used to visualize the path that a flash of light takes in spacetime?  


ANSWER: Light cone (ACCEPT: Cone)  


## BONUS  


12) Physics - Short Answer A crosswind causes a projectile to miss its target by a distance of 240 meters. If the projectile fell from a height of 8,000 meters above its detonation point, what was the speed of this crosswind to the nearest meter per second?  


ANSWER: 6
## TOSS-UP  


13) Longtermism - Multiple Choice Which type of nuclear reactor avoids the need for uranium enrichment by using a coolant with additional neutrons to reduce neutron absorption?  


W) Fast neutron reactor  
X) Boiling water reactor  
Y) Pressurized heavy water reactor  
Z) Small modular reactor  


ANSWER: Y) Pressurized heavy water reactor  


## BONUS  


13) Longtermism - Multiple Choice Pressurized heavy water reactors are seen as a high nuclear proliferation risk. What is the primary reason for this?  


W) The industrial apparatus used can also produce thermonuclear fusion fuel  
X) They can produce more plutonium than a light water reactor  
Y) They can present a false sense of security  
Z) They are less expensive to construct  


ANSWER: X) They can produce more plutonium than a light water reactor
## TOSS-UP  


14) Math - Multiple Choice Which of the following terms describes a matrix that does not have an inverse and whose determinant is 0?  


W) Invertible 
X) Singular 
Y) Row-echelon 
Z) Null  


ANSWER: X) Singular  


## BONUS  


14) Math - Short Answer While playing Monopoly, a player realizes that they will lose if the sum of the two dice they roll is a 2, 3, or 5. What is the probability that they lose on this turn?  


ANSWER: \(\frac{7}{36}\)
## TOSS-UP  


15) Chemistry - Multiple Choice The process of nuclear fission is caused when the nucleus of an unstable element is struck by what particle?  


W) Neutrino 
X) Proton 
Y) Neutron 
Z) Electron  


ANSWER: Y) Neutron  


## BONUS  


15) Chemistry - Multiple Choice Which of the following best explains why group 16 elements typically have a lower first ionization energy than group 15 elements?  


W) Ionization energy decreases with increasing valence electrons 
X) The -2 oxidation state is easier to attain than -3 
Y) A half-filled subshell experiences less repulsion 
Z) Group 15 elements typically form covalent bonds  


ANSWER: Y) A half-filled subshell experiences less repulsion
## TOSS-UP  


16) Earth and Space - Short Answer As global warming occurs, permafrost melts, causing soil to be saturated with liquid water and flow down a slope in what type of mass wasting?  


ANSWER: Solifluction [SOL- ih- FLUK- shun] (ACCEPT: Creep)  


## BONUS  


16) Earth and Space - Multiple Choice Which of the following processes is not part of thermohaline circulation?  


W) Brine rejection 
X) Upwelling 
Y) Runoff 
Z) Overturning  


ANSWER: Y) Runoff
## TOSS-UP  


17) Biology - Short Answer What structural units of chromatin are formed when DNA wraps around histone octamers?  


ANSWER: Nucleosome  


## BONUS  


17) Biology - Short Answer In a plant's root, apoplastic [A-puh-PLAS-dik] movement is blocked beyond the cortex by what structure with a main composition of lignin?  


ANSWER: Casparian Strip
## TOSS-UP  


18) Physics - Short Answer Within a magnetic field, Particle A moves at a 30 degree angle to the field with a force of 0.5 N acting on it. If Particle B moves at a 60 degree angle relative to the magnetic field at four times the speed of Particle A, what is the magnetic force acting upon Particle B, in Newtons?  


ANSWER: \(2\sqrt{3}\)  


## BONUS  


18) Physics - Short Answer When shining a light on a piece of aluminum, a scientist notices that electrons are ejected with a certain amount of energy less than the photon energy. What physics value quantifies this energy discrepancy?  


ANSWER: Work function
## TOSS-UP  


19) Longtermism - Short Answer In which machine learning paradigm does an artificial intelligence interpret its environment and take action, after which it is rewarded for desired behavior and punished for undesired behavior?  


ANSWER: Reinforcement learning  


## BONUS  


19) Longtermism - Multiple Choice In 2017, an AI trained using reinforcement learning was responsible for the first tournament victory against a human world champion. In which of the following games did this victory occur?  


W) Checkers 
X) Chess 
Y) Go 
Z) Scrabble  


ANSWER: Y) Go
## TOSS-UP  


20) Math - Multiple Choice Given that x and y are positive odd integers, which of the following must also be an odd integer?  


W) \(2x + 2y\) X) \(2x^{2} + 2y^{2}\) Y) \((xy + 1)^{2}\) [open parentheses x y plus one close parentheses squared] Z) \(5xy\)  


ANSWER: Z) \(5xy\)  


## BONUS  


20) Math - Short Answer What famous mathematician first proved that there were infinitely many primes using a proof by cases?  


ANSWER: Euclid [YEW- klid]
## TOSS-UP  


21) Chemistry - Multiple Choice Which of the following atomic orbitals can have a magnetic quantum number of 3?  


W) 2s 
X) 5p 
Y) 3d 
Z) 4f  


ANSWER: Z) 4f  


## BONUS  


21) Chemistry - Multiple Choice Which of the following types of organic reactions would be required to form ethane from ethylene [ETH-ih-leen]?  


W) Metathesis [meh- TA- thih- sis] 
X) Hydrogenation [HYE- droh- juh- NAY- shun] 
Y) Electrophilic substitution 
Z) Nucleophilic substitution  


ANSWER: X) Hydrogenation
## TOSS-UP  


22) Earth and Space - Multiple Choice Which of the following planets has an orbit that does not conform to the Titius [TIE-shus]-Bode law?  


W) Mars  X) Jupiter  Y) Uranus  Z) Neptune  


ANSWER: Z) Neptune  


## BONUS  


22) Earth and Space - Short Answer Identify all of the following three main sequence star masses that typically form a convective core: 1) 0.2 solar masses; 2) 1 solar mass; 3) 5 solar masses.  


ANSWER: 3 only
## TOSS-UP  


23) Biology - Multiple Choice Which of the following types of plant tissue's cells are dead at maturity?  


W) Phloem  X) Xylem [ZYE-lum]  Y) Parenchyma [pair-EN-kih-muh]  Z) Collenchyma [kole-EN-kih-muh]  


ANSWER: X) Xylem  


## BONUS  


23) Biology - Short Answer Identify all of the following three amino acids which can form disulfide bridges: 1) Cysteine [SIS-teen]; 2) Methionine [meth- EYE-uhneen]; 3) Valine [VAY-leen].  


ANSWER: 1 only
## TOSS-UP  


24) Physics - Multiple Choice A resistor is added in parallel to a preexisting RLC circuit. Which of the following is not true about the new circuit compared to the old?  


W) The power dissipated increases 
X) The equivalent resistance decreases 
Y) The capacitance decreases 
Z) The maximum current flowing increases  


ANSWER: Y) The capacitance decreases  


## BONUS  


24) Physics - Multiple Choice Which of the following is not true about the common fictitious forces?  


W) The shape of a rolling ball's path on a rotating disk depends on the reference frame 
X) Regardless of location, the Coriolis [core-ee-OLL-is] force deflects any thrown object to the east 
Y) The Euler [OY-ler] and centrifugal [cen-trih-FEW-gul] forces depend on the radius vector while the Coriolis force does not 
Z) The horizontal deflection due to the Coriolis force is greatest close to the equator  


ANSWER: Z) The horizontal deflection due to the coriolis force is greatest close to the equator