sub_title[[446, 172, 549, 194]]
## TOSS-UP  

text[[115, 228, 881, 293]]
1) Longtermism - Short Answer What proposed type of atmospheric geoengineering mimics natural solar dimming processes such as those from volcanic eruptions, but could also potentially lead to depletion of the ozone layer?  

text[[115, 309, 515, 330]]
ANSWER: Stratospheric aerosol injection  

sub_title[[456, 352, 540, 373]]
## BONUS  

text[[115, 388, 882, 451]]
1) Longtermism - Short Answer It has been suggested that stratospheric aerosol injection be performed near the equator in order to take advantage of what pattern of air circulation that lifts air higher into the stratosphere from the equator?  

text[[115, 467, 484, 488]]
ANSWER: Brewer-Dobson circulationsub_title[[446, 90, 549, 110]]
## TOSS-UP  

text[[113, 131, 883, 196]]
2) Math - Short Answer What is the partial derivative with respect to \(x\) of the polynomial \(5x^{2} + e^{5xy} - 3y^{2}\) [five \(x\) squared plus \(e\) to the five \(x\) y minus three y squared]?  

text[[114, 209, 346, 232]]
ANSWER: \(10x + 5ye^{5xy}\)  

sub_title[[455, 254, 541, 275]]
## BONUS  

text[[113, 290, 883, 333]]
2) Math - Short Answer Find the equation of a hyperbola with vertices (+/-4, 0), and foci (+/-6, 0).  

text[[114, 346, 337, 377]]
ANSWER: \(\frac{x^{2}}{16} - \frac{y^{2}}{20} = 1\)sub_title[[448, 90, 549, 110]]
## TOSS-UP  

text[[114, 131, 883, 195]]
3) Chemistry - Multiple Choice Which of the following terms is defined as a metal electrode that is used to determine the concentration of the cation of that metal in a solution?  

text[[114, 211, 415, 296]]
W) Indicator electrode 
X) Reference electrode 
Y) Electrode of the first kind 
Z) Electrode of the second kind  

text[[114, 312, 500, 333]]
ANSWER: Y) Electrode of the first kind  

sub_title[[456, 354, 540, 375]]
## BONUS  

text[[114, 390, 883, 498]]
3) Chemistry - Short Answer Identify all of the following three statements that are true regarding spectroscopy: 1) Raman active species require a change in dipole moment in their vibration; 2) \(\mathrm{CO_2}\) bending is IR active; 3) Mossbauer [MOSS-bough-er] spectroscopy relies on the recoil-less absorption of gamma radiation.  

text[[115, 513, 297, 534]]
ANSWER: 2 and 3sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 883, 196]]
4) Earth and Space - Short Answer An artesian aquifer is measured to be under exactly one atmosphere of pressure. To the nearest meter, what is the hydraulic head of this aquifer?  

text[[115, 211, 253, 231]]
ANSWER: 10  

sub_title[[456, 254, 540, 275]]
## BONUS  

text[[114, 290, 893, 355]]
4) Earth and Space - Short Answer Order the following three stages of a mesoscale convective system from earliest to latest to develop: 1) Bow echo; 2) Comma echo; 3) Squall line.  

text[[115, 370, 288, 391]]
ANSWER: 3, 1, 2sub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[114, 131, 883, 196]]
5) Biology - Multiple Choice When a reciprocal balanced translocation occurs, a tetravalent synaptic structure forms during meiosis. When this occurs, what is the only segregation pattern that results in viable gametes?  

text[[114, 212, 253, 297]]
W) Alternate 
X) Adjacent-1 
Y) Adjacent-2 
Z) Inverse  

text[[115, 312, 352, 332]]
ANSWER: W) Alternate  

sub_title[[456, 355, 540, 375]]
## BONUS  

text[[114, 390, 883, 454]]
5) Biology - Short Answer The liver produces what protein, which functions to bind free hemoglobin in blood plasma and is often stimulated by inflammatory cytokines [SIGH-duh-kines]?  

text[[115, 469, 347, 490]]
ANSWER: Haptoglobinsub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[114, 131, 883, 196]]
6) Physics - Short Answer What is the product of the number of stable equilibrium positions for a set of 5 charges and the number of Lagrange points for a system of 3 equal charges at the vertices of an equilateral triangle?  

text[[115, 211, 242, 231]]
ANSWER: 0  

sub_title[[456, 253, 540, 274]]
## BONUS  

text[[114, 289, 884, 402]]
6) Physics - Multiple Choice The Lagrangian [luh-GRAWNJ-ee-in] of a one-dimensional system with a single mass \(m\) is given by \(L(x,\dot{x},t) = e^{at}\frac{m(\dot{x}^2 - bx^2)}{2}\) [L of x, x dot, t, equals e to the a t times the fraction with numerator m open parentheses x dot squared minus b x squared, and denominator 2]. Which of the following general examples of physical systems best describes this system?  

text[[114, 416, 416, 504]]
W) Simple harmonic oscillator 
X) Damped harmonic oscillator 
Y) Pendulum 
Z) Damped pendulum  

text[[114, 518, 528, 539]]
ANSWER: X) Damped harmonic oscillatorsub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 883, 196]]
7) Longtermism - Short Answer Russian false advertising campaigns referred to the AstraZeneca vaccine as a monkey vaccine due to its use of what vaccine technology to deliver mRNA to cells?  

text[[115, 211, 520, 232]]
ANSWER: Chimpanzee adenovirus vector  

sub_title[[456, 253, 540, 275]]
## BONUS  

text[[115, 290, 883, 375]]
7) Longtermism - Multiple Choice Adenoviral vectors have been studied as an avenue for rapid vaccine development in the event of a health emergency. Which of the following is NOT a major advantage of adenoviral vector vaccines over subunit vaccines?  

text[[115, 391, 551, 477]]
W) Lower reactivity to pre-existing antibodies  X) Greater scale testing for past pandemics  Y) Can directly elicit T-cell responses  Z) Ability to be genetically modified  

text[[115, 492, 634, 514]]
ANSWER: X) Greater scale testing for past pandemicssub_title[[446, 90, 549, 110]]
## TOSS-UP  

text[[113, 131, 883, 175]]
8) Math - Multiple Choice The Taylor series for \(\ln (e + x)\) [the natural log of the quantity e plus x] converges for which of the following intervals?  

text[[113, 189, 644, 275]]
W) \((- e, \infty)\) [the interval from - e exclusive to infinity] 
X) \((- e, e)\) [the interval from - e exclusive to e exclusive] 
Y) \([- e, e)\) [the interval from - e inclusive to e exclusive] 
Z) \((- e, e]\) [the interval from - e exclusive to e inclusive]  

text[[114, 290, 321, 311]]
ANSWER: Z) \((- e, e]\)  

sub_title[[455, 333, 541, 353]]
## BONUS  

text[[113, 366, 883, 412]]
8) Math - Short Answer Determine \(\frac{dy}{dx}\) when \(F(x, y) = \sin y - xy = 0\). [f x,y equals sin y minus xy equals zero]  

text[[114, 425, 300, 455]]
ANSWER: \(\frac{y}{\cos(y) - x}\)sub_title[[448, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 883, 196]]
9) Chemistry - Multiple Choice Benzaldehyde [ben-ZAL-duh-hide] treated with potassium hydroxide will not stay as benzaldehyde, but will undergo which of the following reactions?  

text[[114, 211, 473, 297]]
W) Aldol [AL-doll] condensation  X) Electrophilic aromatic substitution  Y) Cycloaddition  Z) Disproportionation  

text[[115, 311, 437, 333]]
ANSWER: Z) Disproportionation  

sub_title[[456, 355, 540, 375]]
## BONUS  

text[[114, 390, 883, 433]]
9) Chemistry - Multiple Choice Which of the following reactions generally occurs the fastest?  

text[[114, 448, 577, 534]]
W) Lithium halogen exchange  X) Diels Alder [DEALS ALL-der] cycloaddition  Y) Aldol [AL-doll] condensation  Z) Suzuki coupling  

text[[114, 549, 515, 570]]
ANSWER: W) Lithium halogen exchangesub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[115, 131, 883, 175]]
10) Earth and Space - Short Answer What diagram reveals a bimodal distribution of the color of galaxies, by grouping them into a red sequence and blue cloud?  

text[[115, 189, 480, 210]]
ANSWER: Color-Magnitude Diagram  

sub_title[[460, 232, 540, 253]]
## BONUS  

text[[115, 268, 883, 333]]
10) Earth and Space - Short Answer Identify all of the following three conditions which must be met in order for baryogenesis [BEAR-yuh-JEH-nih-sis] to occur: 1) CP symmetry; 2) Conservation of baryon number; 3) Thermal equilibrium.  

text[[115, 348, 280, 369]]
ANSWER: Nonesub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 882, 217]]
11) Biology - Short Answer When RuBisCO binds oxygen instead of carbon dioxide, the subsequent reaction between RuBP and oxygen results in the production of 3-phosphoglycerate [THREE FOSS-fo-GLIH-suh-rate] and what other molecule?  

text[[115, 232, 820, 254]]
ANSWER: Phosphoglycolate [FOSS-fuh-GLY-kuh-late] (ACCEPT: 2-PG)  

sub_title[[456, 275, 540, 296]]
## BONUS  

text[[115, 312, 882, 375]]
11) Biology - Short Answer What is the name for the network of small blood vessels that supply the walls of larger blood vessels such as the aorta [ay-OR-duh]?  

text[[115, 391, 585, 412]]
ANSWER: Vasa vasorum [VAY-suh VA-sore-um]sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 883, 175]]
12) Physics - Short Answer What is the name given to the quantum mechanical operator defined by [negative i times h bar times the gradient]?  

text[[115, 189, 637, 210]]
ANSWER: Momentum (ACCEPT: Linear Momentum)  

sub_title[[456, 232, 541, 253]]
## BONUS  

text[[115, 269, 883, 332]]
12) Physics - Short Answer A star system moves with an average kinetic energy \(K\) and a total Lagrangian [luh-GRAWNJ-ee-in] of \(nK\) , where \(n\) is what integer value?  

text[[115, 348, 241, 368]]
ANSWER: 3sub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[115, 131, 881, 195]]
13) Longtermism - Short Answer What theoretical model of reinforcement learning involves the use of Bayesian updating of computable environmental models to model actions?  

text[[115, 211, 279, 231]]
ANSWER: AIXI  

sub_title[[456, 254, 540, 275]]
## BONUS  

text[[115, 290, 880, 333]]
13) Longtermism - Short Answer This process of Bayesian [bay-EE-zhin] updating of computable hypotheses is known by what name?  

text[[115, 348, 644, 370]]
ANSWER: Solomonoff [suh- LOW- muh- noff] inductionsub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[115, 131, 884, 174]]
14) Math - Multiple Choice Which of the following is closest to the value of \(100 \times e^{1 / 100}\) ?  

text[[114, 190, 191, 275]]
W) 100 
X) 101 
Y) 102 
Z) 103  

text[[115, 291, 294, 311]]
ANSWER: X) 101  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[115, 369, 884, 413]]
14) Math - Short Answer What theorem states that the product of any collection of compact topological spaces is compact with respect to the product topology?  

text[[115, 426, 590, 448]]
ANSWER: Tychonoff's [TIE-kuh-noffs] Theoremsub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[115, 131, 883, 196]]
15) Chemistry - Short Answer The stereochemistry of a polymer's constituent monomers often affects its material properties. What term describes the relative stereochemistry between monomers within a polymer?  

text[[115, 211, 310, 231]]
ANSWER: Tacticity  

sub_title[[456, 253, 540, 274]]
## BONUS  

text[[115, 290, 883, 333]]
15) Chemistry - Multiple Choice Which of the following best describes the geometry of the borane \(\mathrm{B}_6\mathrm{H}_6^{2 - }\) ?  

text[[114, 349, 230, 435]]
W) Closo 
X) Nido 
Y) Arachno 
Z) Hypho  

text[[115, 450, 320, 470]]
ANSWER: W) Clososub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[115, 131, 882, 197]]
16) Earth and Space - Multiple Choice Which of the following minerals is typically formed from the serpentinization [sir-PEN-tih-nih-ZAY-shun] of peridotites [per-IH-duh-tites]?  

text[[114, 212, 238, 297]]
W) Olivine 
X) Pyroxene 
Y) Biotite 
Z) Talc  

text[[115, 312, 297, 333]]
ANSWER: Z) Talc  

sub_title[[456, 355, 540, 376]]
## BONUS  

text[[115, 391, 883, 456]]
16) Earth and Space - Short Answer Identify all of the following three types of melting that can occur at subduction zones: 1) Flux melting; 2) Decompression melting; 3) Friction melting.  

text[[115, 470, 260, 490]]
ANSWER: Allsub_title[[448, 90, 549, 110]]
## TOSS-UP  

text[[114, 131, 883, 281]]
17) Biology - Short Answer Identify all of the following three statements that are true about human sperm: 1) In the late haploid phase of spermatogenesis, histones are replaced with arginine [AR-jih-neen]-rich protamines [PRO-duh-meens]; 2) Daughter cells descended from one maturing spermatogonium remain connected through differentiation by cytoplasmic bridges, forming a syncytium [sin-SIH-she-um]; 3) The whip-like action of the undulipodium [un-dew-lih-PO-dee-um] allows for the movement of sperm.  

text[[115, 296, 259, 316]]
ANSWER: All  

sub_title[[456, 339, 540, 360]]
## BONUS  

text[[115, 375, 883, 460]]
17) Biology - Short Answer Primordial germ cell differentiation does not depend on the sex chromosomes, instead relying on the environment in the gonad. What vitamin derivative secreted by the mesonephros causes germ cells to enter meiosis I and is degraded by CYP26B1 in males?  

text[[115, 476, 354, 496]]
ANSWER: Retinoic acidsub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[114, 131, 883, 240]]
18) Physics - Short Answer Consider the Schrodinger equation for a particle in the potential \(V(x) = x^{4} - a^{4}\) for a positive constant \(a\) . By name or number, identify all of the following four choices that are accurate about the ground state wavefunction in this potential: 1) It is even; 2) It is a nonzero constant; 3) It goes to zero at \(\pm \infty\) ; 4) It is a delta function.  

text[[115, 254, 298, 274]]
ANSWER: 1 and 3  

sub_title[[456, 296, 540, 317]]
## BONUS  

text[[115, 333, 883, 397]]
18) Physics - Short Answer Identify all of the following three types of radiation that are continuously emitted by black holes with jets: 1) Hawking radiation 2) Brehmsstrahlung [BREM-strah-lung] radiation; 3) Synchrotron radiation.  

text[[115, 412, 260, 432]]
ANSWER: Allsub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 882, 196]]
19) Longtermism - Short Answer The voice synthesis for the Amazon Echo smart speaker is performed by which variant of a recurrent neural network capable of learning long-term dependencies?  

text[[115, 211, 730, 232]]
ANSWER: Long short term memory network (ACCEPT: LSTM)  

sub_title[[456, 253, 540, 275]]
## BONUS  

text[[115, 290, 882, 355]]
19) Longtermism - Short Answer LSTM networks do not suffer from which problem common in gradient descent, in which a gradient becomes so small that neural weights do not change value?  

text[[115, 370, 489, 391]]
ANSWER: Vanishing gradient problemsub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[114, 131, 882, 176]]
20) Math - Short Answer How many integer values of x satisfy \(x^{2} < 200\pi\) [x squared is less than 200 pi]?  

text[[115, 190, 250, 210]]
ANSWER: 51  

sub_title[[456, 232, 540, 253]]
## BONUS  

text[[114, 268, 883, 355]]
20) Math - Multiple Choice Tom would like to estimate the mean height of the population in a certain area. He does this by obtaining one set of sample data from a survey, and repeatedly samples observations from this data set to calculate the mean. What term describes this technique?  

text[[114, 370, 345, 456]]
W) Bagging 
X) Bootstrapping 
Y) Cross-validation 
Z) Jackknife resampling  

text[[115, 471, 393, 492]]
ANSWER: X) Bootstrappingsub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[113, 131, 881, 176]]
21) Chemistry - Multiple Choice Which of the following statements is false regarding carbene [CAR-been] chemistry?  

text[[113, 189, 771, 277]]
W) Triplet carbenes behave as diradicals 
X) Singlet carbenes behave as zwitterions [ZWIH-der- EYE-ons] 
Y) Carbenes are stabilized by a vicinal [VIH-sih-null] lone pair 
Z) Sterically bulky substituents on a carbene promote the singlet state  

text[[113, 290, 881, 312]]
ANSWER: Z) Sterically bulky substituents on a carbene promote the singlet state  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[115, 369, 883, 435]]
21) Chemistry - Short Answer Identify all of the following three molecules that are chiral: 1) Trans-cyclooctene [SIGH-cluh-AWK-teen]; 2) 1,3-dichloroallene [die-KLOR-uh-AL-een]; 3) Syn-1,2-dimethylcyclohexane.  

text[[115, 448, 299, 469]]
ANSWER: 1 and 2sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 882, 218]]
22) Earth and Space - Multiple Choice Which of the following processes is thought to play a role in the supernovae of stars with a mass greater than 250 solar masses, and occurs when an atomic nucleus absorbs a gamma ray, and rapidly emits another subatomic particle?  

text[[114, 233, 489, 319]]
W) Photodisintegration  X) Pair instability  Y) Mossbauer [MOSS-bough-er] decay  Z) Internal conversion  

text[[115, 334, 449, 355]]
ANSWER: W) Photodisintegration  

sub_title[[456, 375, 540, 397]]
## BONUS  

text[[115, 412, 882, 477]]
22) Earth and Space - Short Answer Galaxy A is observed to have a maximum rotation velocity 10 times that of galaxy B. The ratio between the mass of baryonic matter in Galaxy A to Galaxy B is closest to 10 to what integer power?  

text[[115, 491, 241, 512]]
ANSWER: 4sub_title[[448, 90, 549, 111]]
## TOSS-UP  

text[[113, 131, 884, 175]]
23) Biology - Multiple Choice The Leslie matrix is used to model which of the following?  

text[[114, 190, 355, 276]]
W) Neuronal oscillations 
X) Population growth 
Y) Enzyme kinetics 
Z) Phylogenetic trees  

text[[115, 291, 434, 312]]
ANSWER: X) Population growth  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[114, 369, 884, 476]]
23) Biology - Short Answer Identify all of the following three statements that are true of the unfolded protein response: 1) It is triggered by the accumulation of misfolded proteins in the Golgi [GOAL-jee] apparatus; 2) Creutzfeldt-Jacob disease is thought to result in overactivation of the unfolded protein response; 3) It leads to an increase in the production of ribosomes.  

text[[115, 491, 288, 512]]
ANSWER: 2 onlysub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[113, 131, 883, 222]]
24) Physics - Multiple Choice A ball is initially held on an incline at an angle \(\theta\) to the horizontal with \(\mu_{k} = \mu_{s} = \frac{\sqrt{3}}{3}\) . Assuming the ball is dropped from the same height in all scenarios, at which of the following angles \(\theta\) would the ball have the most total energy at the bottom?  

text[[113, 236, 512, 322]]
W) 25 degrees  X) 35 degrees  Y) 45 degrees  Z) All angles would have the same energy  

text[[115, 337, 366, 358]]
ANSWER: W) 25 degrees  

sub_title[[456, 379, 540, 401]]
## BONUS  

text[[114, 415, 883, 502]]
24) Physics - Short Answer An rotating disk of mass \(4\mathrm{kg}\) and radius \(1\mathrm{m}\) rotates at an initial 16 radians per second clockwise. An object of mass \(2\mathrm{kg}\) is dropped vertically onto the edge of the disk and the system continues to rotate. What is the system's final angular velocity?  

text[[115, 515, 517, 538]]
ANSWER: - 9.6 (ACCEPT: 9.6 clockwise)