sub_title[[446, 172, 549, 194]]
## TOSS-UP  

text[[115, 228, 882, 293]]
1) Longtermism - Short Answer Climate scientists use prehistoric atmosphere samples to learn about the history of Earth's climate. What climate proxies are primarily used to collect information about prehistoric atmospheres?  

text[[116, 309, 313, 329]]
ANSWER: Ice cores  

sub_title[[456, 352, 540, 373]]
## BONUS  

text[[115, 388, 882, 452]]
1) Longtermism - Short Answer If large amounts of permafrost were to melt, the greenhouse gases trapped inside could trigger catastrophic runaway climate change. Which is the primary greenhouse gas involved in this effect?  

text[[115, 467, 311, 488]]
ANSWER: Methanesub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[113, 131, 883, 175]]
2) Math - Short Answer What is the smallest three-digit number that has three distinct digits and is also divisible by each of its digits?  

text[[115, 190, 264, 210]]
ANSWER: 124  

sub_title[[456, 233, 540, 254]]
## BONUS  

text[[115, 268, 883, 312]]
2) Math - Short Answer Evaluate the following definite integral: \(\int_{-1}^{1} x^3 \cos x dx\) [the integral from -1 to 1 of x cubed cosine of x dx]  

text[[115, 327, 242, 347]]
ANSWER: 0sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 881, 176]]
3) Chemistry - Short Answer Order the following three liquids in order of increasing vapor pressure at room temperature: 1) Water; 2) Benzene; 3) Ethanol.  

text[[115, 190, 288, 210]]
ANSWER: 1, 3, 2  

sub_title[[456, 232, 540, 254]]
## BONUS  

text[[114, 268, 883, 334]]
3) Chemistry - Multiple Choice In a certain reaction, \(\Delta \mathrm{H}\) is positive and \(\Delta \mathrm{S}\) is negative. Which of the following must be true of the reaction's \(\Delta \mathrm{G}\) value and its spontaneity, respectively?  

text[[114, 348, 400, 435]]
W) Positive, spontaneous 
X) Positive, non-spontaneous 
Y) Negative, spontaneous 
Z) Negative, non-spontaneous  

text[[114, 450, 506, 471]]
ANSWER: X) Positive, non- spontaneoussub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 881, 196]]
4) Earth and Space - Multiple Choice Which of the following climate change-driven processes would create a change in albedo that results in a negative feedback loop?  

text[[114, 211, 377, 296]]
W) Desertification  X) Black carbon deposition  Y) Melting of sea ice  Z) Sea level rise  

text[[115, 312, 404, 332]]
ANSWER: W) Desertification  

sub_title[[456, 355, 540, 375]]
## BONUS  

text[[114, 391, 884, 434]]
4) Earth and Space - Multiple Choice Which of the following terms does not correctly describe a dike?  

text[[114, 449, 424, 536]]
W) Discordant  X) Tabular  Y) Intrusive  Z) Porphyritic [por-fur-RIH-dik]  

text[[115, 550, 363, 571]]
ANSWER: Z) Porphyriticsub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 883, 218]]
5) Biology - Short Answer While the stomach is lined with a layer of mucus to protect against acidity, chyme [KIME] must be neutralized once it enters the small intestine to prevent damage. What ion in pancreatic juice is responsible for this neutralization?  

text[[114, 232, 538, 254]]
ANSWER: Bicarbonate (ACCEPT: \(\mathrm{HCO_3}^-\) )  

sub_title[[456, 275, 540, 296]]
## BONUS  

text[[114, 311, 883, 397]]
5) Biology - Short Answer Identify all of the following three parts of the nephron [NEH-fron] where sodium chloride is actively transported out of the filtrate: 1) Proximal convoluted tubule; 2) Thin segment of the ascending limb of the loop of Henle [HEN-lee]; 3) Distal convoluted tubule.  

text[[115, 412, 298, 432]]
ANSWER: 1 and 3sub_title[[448, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 883, 217]]
6) Physics - Short Answer A 1 kilogram puck on a table is pushed at 2 meters per second and slides for some time before falling off the table just as it reaches a speed of 1 meter per second. In joules, how much energy was released as heat before it fell off the table?  

text[[115, 233, 259, 253]]
ANSWER: 1.5  

sub_title[[456, 275, 540, 296]]
## BONUS  

text[[114, 312, 883, 418]]
6) Physics - Short Answer A massless spring with spring constant 4 newtons per meter is hung from the ceiling. A mass of 2 kilograms is attached and held in place such that the spring not stretched. If the mass is pushed and has an initial downward velocity of 12 meters per second, to the nearest whole number, what is its velocity at the spring's new equilibrium point?  

text[[115, 434, 253, 454]]
ANSWER: 14sub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[114, 131, 882, 196]]
7) Longtermism - Short Answer Which rare astronomical event involves a large outpouring of directed electromagnetic radiation and could lead to a mass extinction if pointed at Earth?  

text[[115, 211, 395, 232]]
ANSWER: Gamma-ray burst  

sub_title[[456, 254, 540, 275]]
## BONUS  

text[[114, 290, 882, 333]]
7) Longtermism - Multiple Choice The first satellites to detect gamma-ray bursts were originally designed to detect which of the following events?  

text[[114, 349, 327, 435]]
W) Solar flares 
X) Lightning strikes 
Y) Meteorite impacts 
Z) Nuclear explosions  

text[[114, 451, 438, 471]]
ANSWER: Z) Nuclear explosionssub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[113, 131, 551, 153]]
8) Math - Short Answer Compute \(9 + 67.73\)  

text[[115, 168, 277, 189]]
ANSWER: 4900  

sub_title[[456, 211, 541, 232]]
## BONUS  

text[[113, 247, 883, 291]]
8) Math - Short Answer What is the total area between the curve and the x-axis for the function \(y = \sin x\) from 0 to \(2\pi\) ?  

text[[115, 305, 241, 325]]
ANSWER: 4sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[113, 131, 883, 175]]
9) Chemistry - Short Answer Identify all of the following three nuclei that are fissile [FISS-eye-ull]: 1) Thorium-232; 2) Uranium-233; 3) Uranium-238.  

text[[115, 190, 288, 210]]
ANSWER: 2 only  

sub_title[[456, 233, 540, 254]]
## BONUS  

text[[115, 269, 888, 333]]
9) Chemistry - Short Answer What is the chemical formula of the nitrogen species formed when hydrazine [HI-druh-zeen] is combusted with 2 equivalents of oxygen gas, assuming only one compound is produced along with water?  

text[[115, 348, 497, 369]]
ANSWER: NO (ACCEPT: Nitric oxide)sub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[115, 131, 882, 196]]
10) Earth and Space - Short Answer Identify all of the following four moons that are satellites of Saturn: 1) Enceladus [en-SELL-ih-dis]; 2) Ganymede [GAN-ih- meed]; 3) Triton; 4) Miranda.  

text[[115, 211, 288, 231]]
ANSWER: 1 only  

sub_title[[456, 254, 540, 275]]
## BONUS  

text[[115, 290, 882, 354]]
10) Earth and Space - Short Answer Lucy is a NASA space probe launched in 2021 that will travel to Jupiter's L4 and L5 Lagrange [luh-GRAWNJ] points to visit what group of asteroids?  

text[[115, 370, 300, 390]]
ANSWER: Trojanssub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[114, 131, 883, 175]]
11) Biology - Multiple Choice Which of the following best explains the function of emulsification [eh-MULL-sih-fih-KAY-shun] during the digestion of fats?  

text[[113, 190, 884, 298]]
W) Increasing the surface area to volume ratio of fat droplets 
X) Breaking down triglycerides [TRY-GLIH-ser-ides] into monoglycerides and fatty acids 
Y) Allowing fats to diffuse into enterocytes [en-TARE-uh-sites] 
Z) Increasing the solubility of fats  

text[[115, 312, 801, 333]]
ANSWER: W) Increasing the surface area to volume ratio of fat droplets  

sub_title[[456, 354, 540, 375]]
## BONUS  

text[[115, 391, 881, 455]]
11) Biology - Multiple Choice Which of the following best explains why saturated fats are typically solid at room temperature, while unsaturated fats are typically liquid?  

text[[113, 470, 883, 596]]
W) Saturated fats have longer tails than unsaturated fatty acids, and therefore experience more hydrogen bonding 
X) The tail ends of two saturated fatty acids can link to form dimers [DIE-murs] 
Y) Saturated fats consist of straight chained fatty acids, which exhibit greater van der Waals [VAN der VALLS] forces than unsaturated fatty acids 
Z) Saturated fats contain aromatic rings, and exhibit pi-pi stacking  

text[[115, 612, 883, 655]]
ANSWER: Y) Saturated fats consist of straight chained fatty acids, which exhibit greater van der Walls forces than unsaturated fatty acidssub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 883, 196]]
12) Physics - Short Answer A resistor, inductor, and capacitor are connected in series across a constant voltage source. What is the phase difference between the current through the capacitor and voltage through the resistor?  

text[[115, 211, 318, 232]]
ANSWER: 0 degrees  

sub_title[[456, 253, 540, 275]]
## BONUS  

text[[115, 290, 883, 355]]
12) Physics - Multiple Choice Using Bohr's model as an approximation, which of the following choices is closest to the lowest amount of energy, in electron volts, required to ionize a electron in the \(n = 1\) state for an atom of Lithium?  

text[[114, 369, 255, 455]]
W) 13  X) 130  Y) 1300  Z) 13000  

text[[115, 470, 296, 491]]
ANSWER: X) 130sub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[115, 131, 883, 175]]
13) Longtermism - Short Answer What phrase is used to describe hypothetical extinction risks due to self-replicating nanomachines?  

text[[115, 190, 317, 211]]
ANSWER: Grey goo  

sub_title[[456, 233, 540, 254]]
## BONUS  

text[[115, 269, 883, 354]]
13) Longtermism - Short Answer The term grey goo was initially coined by K. Eric Drexler, who has arranged to receive an end-of-life procedure involving the vitrification [VIH-trich-fih-KAY-shun] of tissues in super-cold conditions to preserve brain information. What is this procedure called?  

text[[115, 369, 844, 391]]
ANSWER: Cryonics (ACCEPT: Cryostasis; DO NOT ACCEPT: Cryogenics)sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 883, 196]]
14) Math - Short Answer A 10 meter rope is tied 6 meters away from the edge of a vertical cliff. If the rope can only move along a single plane perpendicular to the edge of the cliff, what is the area of the region that the rope can reach?  

text[[115, 211, 267, 231]]
ANSWER: \(54\pi\)  

sub_title[[456, 254, 540, 275]]
## BONUS  

text[[115, 290, 883, 375]]
14) Math - Multiple Choice The weather forecast states that there is a \(50\%\) chance of snow today and a \(60\%\) chance of snow tomorrow. However, there is a \(30\%\) chance that it does not snow at all. Assuming that the forecast is accurate, what is the chance that it snows either today or tomorrow, but not both?  

text[[115, 390, 184, 475]]
W) 0.2 X) 0.3 Y) 0.4 Z) 0.5  

text[[115, 492, 288, 512]]
ANSWER: X) 0.3sub_title[[448, 90, 549, 110]]
## TOSS-UP  

text[[114, 131, 883, 175]]
15) Chemistry - Multiple Choice Which of the following diatomic species has the highest energy HOMO?  

text[[114, 189, 188, 275]]
W) \(\mathrm{F}_{2}^{+}\) X) \(\mathrm{F}_{2}^{-}\) Y) \(\mathrm{N}_{2}^{+}\) Z) \(\mathrm{N}_{2}^{-}\)  

text[[114, 291, 295, 312]]
ANSWER: X) \(\mathrm{F}_{2}^{-}\)  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[114, 370, 883, 435]]
15) Chemistry - Short Answer Identify all of the following three statements about the Downs cell that are true: 1) It is used to produce solid sodium; 2) It uses a carbon anode; 3) The Downs' process produces chlorine as a byproduct.  

text[[114, 448, 260, 469]]
ANSWER: Allsub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[115, 131, 882, 196]]
16) Earth and Space - Short Answer Order the following three minerals from first to last to crystallize from a body of magma: 1) Biotite [BI-uh-tite]; 2) Muscovite [MUS-kuh-vite]; 3) Olivine.  

text[[115, 211, 288, 231]]
ANSWER: 3, 1, 2  

sub_title[[456, 254, 540, 275]]
## BONUS  

text[[115, 290, 882, 355]]
16) Earth and Space - Short Answer Identify all of the following three properties of a stream that typically increase as a stream moves from its headwaters to its mouth: 1) Stream gradient; 2) Discharge; 3) Average flow velocity.  

text[[115, 369, 298, 390]]
ANSWER: 2 and 3sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 882, 197]]
17) Biology - Short Answer Order the following three steps of a polymerase chain reaction by increasing temperature at which they are carried out: 1) Denaturation; 2) Annealing [uh-NEE-ling]; 3) Extension.  

text[[115, 211, 286, 231]]
ANSWER: 2, 3, 1  

sub_title[[456, 254, 540, 275]]
## BONUS  

text[[115, 290, 882, 333]]
17) Biology - Multiple Choice Which of the following clades is most closely related to animals?  

text[[114, 348, 560, 435]]
W) Nucleariids [NEW-klee-AIR-ee-ids] 
X) Choanoflagellates [ko-AN-uh-FLA-juh-lits] 
Y) Apicomplexans [AY-pi-come-PLEX-ins] 
Z) Entamoebas [EN-tuh-MEE-buhs]  

text[[115, 450, 428, 470]]
ANSWER: X) Choanoflagellatessub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 882, 219]]
18) Physics - Short Answer A person spinning on a rotating disk drops an apple from their outstretched hand. Identify all of the following three quantities that are conserved in this situation: 1) Kinetic energy of the system; 2) Angular momentum of the system; 3) Linear momentum of the apple.  

text[[115, 232, 288, 253]]
ANSWER: 2 only  

sub_title[[456, 275, 540, 296]]
## BONUS  

text[[115, 311, 883, 395]]
18) Physics - Multiple Choice Two spacecraft travel away from each other at speeds of 0.6c and 0.7c, respectively. To the nearest tenth, in terms of c, at what speed does the faster craft appear to be moving at to an observer on the slower craft?  

text[[115, 411, 193, 496]]
W) 0.6c 
X) 0.7c 
Y) 0.8c 
Z) 0.9c  

text[[115, 513, 297, 534]]
ANSWER: Z) 0.9csub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 883, 175]]
19) Longtermism - Short Answer What is the current largest non-sparse natural language processing model in existence?  

text[[115, 189, 291, 210]]
ANSWER: GPT- 3  

sub_title[[456, 233, 540, 254]]
## BONUS  

text[[115, 269, 883, 312]]
19) Longtermism - Short Answer What term describes the ability of machines to perform several tasks on different processors at once?  

text[[115, 327, 365, 348]]
ANSWER: Parallelizationsub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[113, 131, 881, 175]]
20) Math - Short Answer Express the following as the log of a single quantity: \(\log 120 - \log 108 + \log 144.\)  

text[[115, 190, 297, 210]]
ANSWER: \(\log 160\)  

sub_title[[456, 233, 540, 254]]
## BONUS  

text[[113, 269, 883, 313]]
20) Math - Multiple Choice Which of the following numbers cannot be the last digit of an integer raised to the 4th power?  

text[[113, 328, 165, 411]]
W) 1  X) 3  Y) 5  Z) 6  

text[[115, 427, 272, 448]]
ANSWER: X) 3sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 883, 218]]
21) Chemistry - Short Answer Given that the enthalpy of combustion of graphite is -393 kJ/mol [kilojoules per mole], and the enthalpy of combustion of diamond is -396 kJ/mol, then in kJ/mol, what is the change in enthalpy for the reaction of graphite yields diamond?  

text[[115, 232, 240, 253]]
ANSWER: 3  

sub_title[[456, 275, 540, 296]]
## BONUS  

text[[115, 312, 882, 375]]
21) Chemistry - Short Answer How many radial and angular nodes respectively does the wavefunction of an electron in a hydrogenic [HI-druh-JEN-ik] 4s orbital have?  

text[[115, 391, 299, 411]]
ANSWER: 3 and 0sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[113, 131, 884, 175]]
22) Earth and Space - Multiple Choice Which of the following observations of a star does not suggest the presence of either exoplanets or another star nearby?  

text[[113, 190, 780, 277]]
W) The parent star wobbles back and forthX) The parent star experiences alternating redshift and blueshiftY) The apparent magnitude of the parent star periodically dips sharplyZ) The apparent magnitude of the parent star varies smoothly  

text[[113, 291, 802, 312]]
ANSWER: Z) The apparent magnitude of the parent star varies smoothly  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[114, 369, 883, 455]]
22) Earth and Space - Multiple Choice A common method for detecting exoplanets is to observe slight Doppler shifts in the star's light due to the gravitational pull of the planet. Which of the following planet types would be easiest to detect using this method?  

text[[114, 470, 283, 556]]
W) Ice giantX) Mini-NeptuneY) Hot JupiterZ) Trojan  

text[[115, 571, 365, 592]]
ANSWER: Y) Hot Jupitersub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[113, 131, 883, 175]]
23) Biology - Multiple Choice Which of the following plant structures is NOT a modified stem?  

text[[113, 190, 485, 274]]
W) Pneumato phore [new-MA-duh-for] 
X) Rhizome [RYE-zone] 
Y) Stolon 
Z) Tuber  

text[[115, 290, 413, 311]]
ANSWER: W) Pneumato phore  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[115, 369, 882, 433]]
23) Biology - Short Answer What is the term given to mychorrizae [MY-kuhRYE-zay] which contain hyphae [HI-fay] that puncture the cell wall of plant roots, and are enclosed by an infolded plasma membrane?  

text[[115, 448, 621, 470]]
ANSWER: Arbuscular [ar-BUS-cue-ler] mychorrizaesub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 883, 196]]
24) Physics - Short Answer In nature, as uranium-235 decays into lead-207, it undergoes both alpha and beta minus decay. How many alpha particles would be released in the complete decay chain of a single atom of uranium-235?  

text[[115, 211, 240, 231]]
ANSWER: 7  

sub_title[[456, 254, 540, 275]]
## BONUS  

text[[115, 290, 883, 375]]
24) Physics - Short Answer Four resistors, made from the same material, have different radii and lengths. Order the following three resistor dimensions in order of increasing resistance: 1) A resistor of length L and radius R; 2) A resistor of length 4L and radius R/3; 3) A resistor of length 2L and radius R/2.  

text[[115, 390, 288, 411]]
ANSWER: 1, 3, 2