title[[168, 113, 818, 178]]
# 2020 MIT Science Bowl High School Invitational Round 6  

sub_title[[448, 210, 546, 228]]
## TOSS UP  

text[[147, 244, 850, 282]]
1) EARTH AND SPACE Short Answer By name or number, identify all of the following three statements that are true of emission nebulae (NEB-yoo-lay):  

text[[168, 295, 609, 350]]
1) They are star formation regions  
2) Their spectra are composed of scattered starlight  
3) They are primarily composed of hydrogen  

text[[147, 368, 311, 386]]
ANSWER: 1 and 3  

sub_title[[457, 421, 538, 440]]
## BONUS  

text[[147, 455, 850, 492]]
1) EARTH AND SPACE Short Answer Rank the following three detrital sedimentary rocks in order of increasing sediment size:  

text[[168, 505, 281, 560]]
1) Mudstone  
2) Arkose  
3) Siltstone  

text[[147, 578, 300, 596]]
ANSWER: 1, 3, 2sub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[145, 153, 850, 191]]
2) MATH Short Answer If the surface area of a cube is 96, what is the length of its longest diagonal?  

text[[147, 196, 285, 215]]
ANSWER: \(4\sqrt{3}\)  

sub_title[[457, 250, 538, 269]]
## BONUS  

text[[146, 284, 850, 376]]
2) MATH Multiple Choice A large conference hall is shaped like a rectangle with a length of 200 feet and a width of 100 feet. Which of the following is closest to the maximum number of people who can stand in the conference hall while abiding by the social distancing guideline that any two people are at least 6 feet apart from each other?  

text[[158, 389, 228, 460]]
W) 100 
X) 300 
Y) 500 
Z) 700  

text[[147, 479, 302, 498]]
ANSWER: Z) 700sub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[146, 153, 851, 227]]
3) PHYSICS Multiple Choice A pendulum is made up of a string of length \(L\) connected to a mass \(m\) . If the mass is released from rest at an angle of 45 degrees from the vertical, which of the following is true concerning the period of the resulting oscillation?  

text[[159, 237, 500, 315]]
W) The period is equal to \(2\pi \sqrt{L / g}\) X) The period is less than \(2\pi \sqrt{L / g}\) Y) The period is greater than \(2\pi \sqrt{L / g}\) Z) The period is infinite  

text[[146, 333, 620, 354]]
ANSWER: Y) The period will be greater than \(2\pi \sqrt{L / g}\)  

sub_title[[457, 387, 538, 406]]
## BONUS  

text[[146, 421, 850, 460]]
3) PHYSICS Short Answer Two events are connected by a spacelike interval. By name or number, identify all of the following three statements that are true:  

text[[168, 470, 850, 562]]
1) It is impossible for any information to be transmitted between the two events 
2) It is always possible to find a reference frame in which the two events are colocated 
3) It is always possible to find a reference frame in which the two events are simultaneous  

text[[146, 580, 311, 599]]
ANSWER: 1 and 3sub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[147, 153, 850, 227]]
4) ENERGY Multiple Choice Researchers in the Regev group at MIT are developing novel computational and experimental approaches for analyzing complex biological networks, including gene expression networks. Which of the following is not a tool used to study the expression of a gene?  

text[[160, 239, 490, 314]]
W) qRT-PCR (read as: Q-R-T-P-C-R) 
X) RNA-seq (read as: R-N-A-seek) 
Y) Luciferase reporters 
Z) Southern blotting  

text[[147, 331, 422, 350]]
ANSWER: Z) Southern blotting  

sub_title[[458, 384, 538, 403]]
## BONUS  

text[[147, 419, 850, 510]]
4) ENERGY Short Answer Researchers in the Langer group at MIT are developing new methods for drug delivery. One particularly desirable type of transport is transport across the blood-brain barrier. Some small molecules are able to enter the endothelial cells that make up the blood-brain barrier from one side and exit through another. What is the name for this type of transport?  

text[[147, 516, 351, 534]]
ANSWER: Transcytosissub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[145, 153, 850, 191]]
5) BIOLOGY Multiple Choice Which of the following amino acids is least likely to be found in an alpha helix?  

text[[157, 203, 382, 278]]
W) Alanine (AL-uh-neen) 
X) Leucine (LOO-seen) 
Y) Lysine 
Z) Glycine  

text[[146, 295, 337, 314]]
ANSWER: Z) Glycine  

sub_title[[457, 348, 538, 366]]
## BONUS  

text[[146, 382, 850, 420]]
5) BIOLOGY Multiple Choice An increase in which of the following parameters will decrease the maximum rate of an enzymatic reaction?  

text[[157, 432, 397, 506]]
W) \(k_{\mathrm{cat}}\) (read: \(k\) cat) 
X) \(K_{M}\) (read: \(K M\) ) 
Y) Substrate concentration 
Z) Enzyme concentration  

text[[146, 523, 306, 542]]
ANSWER: X) \(K_{M}\)sub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[145, 153, 850, 209]]
6) CHEMISTRY Short Answer Which two state variables must be held constant for the change in Gibbs free energy to be proportional to the universal change in entropy?  

text[[146, 215, 466, 233]]
ANSWER: Temperature and pressure  

sub_title[[456, 268, 538, 287]]
## BONUS  

text[[145, 303, 850, 340]]
6) CHEMISTRY Multiple Choice How many unpaired electrons are there in the ground state electron configuration of chromium metal?  

text[[157, 352, 208, 425]]
W) 3 
X) 4 
Y) 5 
Z) 6  

text[[146, 444, 283, 462]]
ANSWER: Z) 6  

sub_title[[448, 515, 546, 534]]
## TOSS UP  

text[[145, 550, 850, 587]]
7) MATH Short Answer In standard form, what the equation of the line tangent to the circle \(x^{2} + y^{2} = 5\) at the point \((1,2)\) ?  

text[[145, 592, 770, 612]]
ANSWER: \(x + 2y = 5\) (accept: \(2y + x = 5\) ; do not accept any other form)  

sub_title[[456, 645, 538, 664]]
## BONUS  

text[[146, 680, 850, 736]]
7) MATH Short Answer Consider the quadrilateral formed by the tangent lines to the circle \(x^{2} + y^{2} = 5\) at the points \((1,2)\) , \((-1,2)\) , \((-1, -2)\) , and \((1, -2)\) . What is the perimeter of this quadrilateral?  

text[[146, 741, 294, 760]]
ANSWER: \(10\sqrt{5}\)sub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[145, 153, 851, 191]]
8) BIOLOGY Multiple Choice Which of the following hormones does NOT play a role in regulation of fluids through the RAA system?  

text[[158, 203, 590, 278]]
W) Renin (REH- nin) 
X) Antidiuretic (AN- tie- die- uh- REH- tik) hormone 
Y) Aldosterone (al- DOSS- ter- own) 
Z) Angiotensin (ANN- jee- oh- TEN- sin)  

text[[146, 295, 456, 313]]
ANSWER: X) Antidiuretic hormone  

sub_title[[457, 348, 538, 366]]
## BONUS  

text[[145, 382, 850, 420]]
8) BIOLOGY Multiple Choice What type of mimicry do moths that can make themselves resemble snakes exhibit?  

text[[159, 432, 491, 505]]
W) Cryptic 
X) Aposematic (APP- oh- sih- MA- tick) 
Y) Batesian (BAYT- see- in) 
Z) Müllerian (moo- LARE- ee- in)  

text[[146, 522, 348, 540]]
ANSWER: Y) Batesiansub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[146, 153, 850, 209]]
9) EARTH AND SPACE Multiple Choice Which of the following terms best describes the telescope focus that uses a concave primary mirror and a convex secondary mirror to focus light through a space in the primary mirror?  

text[[158, 222, 288, 295]]
W) Newtonian 
X) Galilean 
Y) Dobsonian 
Z) Cassegrain  

text[[147, 314, 363, 332]]
ANSWER: Z) Cassegrain  

sub_title[[458, 366, 538, 384]]
## BONUS  

text[[146, 400, 850, 456]]
9) EARTH AND SPACE Multiple Choice A certain exoplanet on an edge-on orbit has high albedo and low temperature. At which of the following positions in its orbit would the star-exoplanet system appear brightest?  

text[[158, 468, 515, 541]]
W) Just before transit in front of the star 
X) During transit in front of the star 
Y) Just before transit behind the star 
Z) During transit behind the star  

text[[146, 560, 564, 578]]
ANSWER: Y) Just before transit behind the starsub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[146, 153, 850, 227]]
10) ENERGY Multiple Choice Researchers in the Griffin group at MIT have developed a way to dramatically enhance the sensitivity of NMR spectroscopy. Which of the following proton environments would produce the most downfield peak on an H-NMR spectrum?  

text[[160, 239, 480, 314]]
W) A carboxylic acid acidic hydrogen 
X) An aldehyde hydrogen 
Y) An ester alpha hydrogen 
Z) A ketone alpha hydrogen  

text[[146, 331, 564, 350]]
ANSWER: W) A carboxylic acid acidic hydrogen  

sub_title[[458, 384, 538, 403]]
## BONUS  

text[[146, 418, 850, 475]]
10) ENERGY Multiple Choice Researchers in the Hong group at MIT are using NMR spectroscopy to study the structure of glucagon fibrils. On an H-NMR spectrum, which of the following compounds would have only one peak?  

text[[159, 487, 473, 560]]
W) Chloroethane 
X) Acetaldehyde (ass- it- AL- di- hide) 
Y) Dimethyl ether 
Z) Acetic acid  

text[[146, 578, 401, 596]]
ANSWER: Y) Dimethyl ethersub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[147, 153, 850, 208]]
11) PHYSICS Multiple Choice An insulating sphere has a uniform charge density \(\rho\) (read: rho). Which of the following best describes the dependence of electric field on distance from the center, within the sphere?  

text[[158, 222, 317, 295]]
W) Linear 
X) Quadratic 
Y) Hyperbolic 
Z) Inverse square  

text[[147, 313, 335, 331]]
ANSWER: W) Linear  

sub_title[[457, 366, 538, 384]]
## BONUS  

text[[147, 400, 850, 456]]
11) PHYSICS Short Answer An AC source is connected to a resistor and a capacitor in series. Indicate, by name or number, all of the following three statements that are true of this system:  

text[[168, 468, 850, 541]]
1) The current through the circuit lags the voltage by 90 degrees 
2) For large frequencies, the impedance is approximately equal to the resistance of the resistor 
3) The net power dissipated in the capacitor is zero  

text[[147, 560, 311, 578]]
ANSWER: 2 and 3sub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[145, 153, 850, 191]]
12) CHEMISTRY Short Answer How many nearest neighbors does an atom in a body centered cubic lattice have?ANSWER: 8  

text[[146, 197, 258, 215]]
ANSWER: 8  

sub_title[[457, 250, 538, 269]]
## BONUS  

text[[145, 284, 835, 305]]
12) CHEMISTRY Multiple Choice Which of the following bonds is not IR-active?  

text[[157, 315, 559, 390]]
W) The carbon-carbon bond in ethene 
X) The carbon-chlorine bond in chloroethane 
Y) The carbon-oxygen bond in formaldehyde 
Z) The carbon-oxygen bond in carbon dioxide  

text[[146, 407, 571, 426]]
ANSWER: W) The carbon-carbon bond in ethene  

sub_title[[449, 478, 546, 497]]
## TOSS UP  

text[[146, 513, 850, 551]]
13) MATH Short Answer How many planes of reflection symmetry does a right regular hexagonal prism have?ANSWER: 7  

text[[146, 556, 258, 574]]
ANSWER: 7  

sub_title[[457, 609, 538, 628]]
## BONUS  

text[[146, 644, 850, 700]]
13) MATH Short Answer An ant is at vertex \(A\) of a regular tetrahedron. During every hour, he randomly jumps to another vertex of the tetrahedron. What is the probability that, after 3 hours, the ant will not be at vertex \(A\) ?ANSWER: 7/9sub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[145, 153, 851, 191]]
14) CHEMISTRY Multiple Choice For an exothermic reaction, which of the following statements is true as temperature increases?  

text[[157, 202, 763, 277]]
W) Both the rate constant and equilibrium constant increase 
X) The rate constant increases, but the equilibrium constant decreases 
Y) The rate constant decreases, but the equilibrium constant increases 
Z) Both the rate constant and the equilibrium constant decrease  

text[[146, 294, 840, 314]]
ANSWER: X) The rate constant increases, but the equilibrium constant decreases  

sub_title[[457, 347, 538, 366]]
## BONUS  

text[[146, 382, 850, 420]]
14) CHEMISTRY Multiple Choice When 1-methylcyclohexene is treated with HCl, the product of this reaction will be which of the following?  

text[[157, 431, 666, 505]]
W) Achiral (ay- KY- ruhl) but not meso (MEE- so) 
X) A mixture of diastereomers (DY- uh- STAY- ree- oh- murs) 
Y) A meso (MEE- so) compound 
Z) A racemic (ruh- SEE- mic) mixture  

text[[146, 522, 459, 541]]
ANSWER: W) Achiral but not mesosub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[147, 153, 851, 228]]
15) PHYSICS Short Answer What is the name of a device that uses a sandwich of two superconductive materials around an insulator, uses quantum tunneling to allow a current through, and can be paired with another of the same device to form a SQUID (read as: squid)?  

text[[147, 233, 408, 252]]
ANSWER: Josephson junction  

sub_title[[457, 286, 538, 305]]
## BONUS  

text[[147, 320, 851, 394]]
15) PHYSICS Multiple Choice Allen is waiting for the bus as he suddenly hears a sonic boom from a plane flying. The sonic boom arrives from an angle of approximately 37 degrees above the ground. Given that the speed of sound is 343 meters per second, what is the approximate speed of the plane, in meters per second?  

text[[157, 406, 228, 480]]
W) 340 
X) 430 
Y) 570 
Z) 660  

text[[147, 498, 304, 517]]
ANSWER: X) 430sub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[147, 153, 850, 227]]
16) ENERGY Multiple Choice Researchers at MIT's Center for Theoretical Physics recently used Lattice Quantum Chromodynamics to make predictions about certain systems that sharpen theory predictions for dark matter direct detection experiments. Which of the following best describes the system that the researchers studied?  

text[[160, 240, 577, 312]]
W) The structure of strange gluons in the proton X) The frequency of neutrino oscillations Y) Rates of CP violation in B meson decays Z) Decay rates of W and Z bosons  

text[[147, 332, 660, 351]]
ANSWER: W) The structure of strange gluons in the proton  

sub_title[[458, 384, 538, 403]]
## BONUS  

text[[147, 418, 850, 511]]
16) ENERGY Short Answer Researchers at MIT's Center for High Energy Physics have recently been involved in the construction of KATRIN (read as: KA-trin), a next-generation experiment geared at directly measuring the neutrino mass down to fractions of an electron volt by measuring the beta decay of tritium. By name or number, identify all of the following three statements that are true of KATRIN:  

text[[168, 522, 850, 633]]
1) The KATRIN experiment is directly measuring the mass of the electron antineutrino 
2) In most beta decay events, the electron and neutrino carry away roughly equal amounts of energy 
3) The researchers have produced an upper bound of 1.1 kiloelectronvolts for the mass of the neutrino  

text[[147, 651, 310, 669]]
ANSWER: 1 and 2sub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[146, 153, 850, 191]]
17) EARTH AND SPACE Multiple Choice Clouds of neutral atomic hydrogen in the interstellar medium are more commonly known as which of the following?  

text[[159, 204, 412, 277]]
W) Bok globule 
X) Molecular cloud 
Y) H I (read: H-one) region 
Z) H II (read: H-two) region  

text[[147, 294, 361, 313]]
ANSWER: Y) H I region  

sub_title[[457, 347, 538, 366]]
## BONUS  

text[[147, 382, 850, 420]]
17) EARTH AND SPACE Short Answer By name or number, indicate all of the following three stars that are in the Winter Triangle:  

text[[168, 432, 250, 488]]
1) Altair 
2) Deneb 
3) Vega  

text[[147, 505, 361, 523]]
ANSWER: None of themsub_title[[450, 118, 547, 137]]
## TOSS UP  

text[[146, 153, 844, 198]]
18) BIOLOGY Short Answer Which male reproductive cells produce testosterone? ANSWER: Leydig cells  

sub_title[[457, 231, 538, 250]]
## BONUS  

text[[146, 266, 850, 303]]
18) BIOLOGY Multiple Choice The protein that blocks myosin binding to actin in relaxed muscle is  

text[[157, 315, 488, 390]]
W) Titin (TIE- tin) 
X) Tropomyosin (troe-poe- MY- oh- sin) 
Y) Troponin (TROW- poe- nin) C 
Z) Calmodulin (cal- MAW- dyu- lin)  

text[[146, 406, 384, 425]]
ANSWER: X) Tropomyosinsub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[146, 152, 850, 191]]
19) CHEMISTRY Multiple Choice Which of the following molecules will have \(\mathrm{sp}^{3}\mathrm{d}\) (read as: S- P- three- D) hybridization?  

text[[157, 203, 253, 278]]
W) \(\mathrm{H}_{2}\mathrm{SO}_{4}\) X) \(\mathrm{BF}_{3}\) Y) \(\mathrm{SF}_{4}\) Z) \(\mathrm{CO}_{2}\)  

text[[146, 295, 306, 314]]
ANSWER: Y) \(\mathrm{SF}_{4}\)  

sub_title[[457, 347, 538, 366]]
## BONUS  

text[[146, 381, 850, 420]]
19) CHEMISTRY Short Answer By name or number, arrange the following 3 measurements of an ideal gas in increasing order:  

text[[168, 431, 421, 448]]
1) Root mean square velocity  

text[[168, 451, 316, 468]]
2) Average speed  

text[[168, 470, 371, 487]]
3) Most probable speed  

text[[146, 504, 299, 522]]
ANSWER: 3, 2, 1sub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[147, 153, 850, 209]]
20) MATH Multiple Choice A commonly cited benefit of the sexual, or base 6, number system is that it provides convenient decimal representations of many simple fractions. Which of the following fractions terminates in sexual but not in decimal?  

text[[157, 222, 235, 295]]
W) 1/4 
X) 1/8 
Y) 1/9 
Z) 1/11  

text[[147, 313, 305, 332]]
ANSWER: Y) 1/9  

sub_title[[457, 366, 538, 384]]
## BONUS  

text[[147, 400, 850, 437]]
20) MATH Short Answer When the sexual number 1344255 is converted to decimal, what is its last digit?  

text[[147, 443, 257, 461]]
ANSWER: 9  

sub_title[[448, 514, 546, 533]]
## TOSS UP  

text[[147, 549, 850, 604]]
21) PHYSICS Short Answer Three resistors, each with resistance 1 ohm, are connected together to form a triangle. What is the equivalent resistance between two vertices of this triangle in ohms?  

text[[147, 610, 277, 628]]
ANSWER: 2/3  

sub_title[[457, 663, 538, 682]]
## BONUS  

text[[147, 698, 850, 735]]
21) PHYSICS Short Answer By name or number, identify all of the following particles which have a nonzero baryon number:  

text[[168, 747, 313, 820]]
1) Pion (PY-on) 
2) Delta particle 
3) Tau quark 
4) Graviton  

text[[147, 840, 310, 858]]
ANSWER: 2 and 3sub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[146, 151, 850, 207]]
22) BIOLOGY Short Answer Although the genetic code is relatively universal, there are some differences between diverse organisms. In prokaryotes, what amino acid does the codon AUG code for?  

text[[146, 213, 850, 250]]
ANSWER: Formylmethionine (Accept: N-formylmethionine) (Do not accept: methionine)  

sub_title[[457, 283, 538, 302]]
## BONUS  

text[[146, 315, 850, 353]]
22) BIOLOGY Multiple Choice Which of the following plant components have even ploidy (PLOY-dee)?  

text[[159, 363, 445, 437]]
W) Synergid (SIH-ner-jid) 
X) Megaspore 
Y) Endosperm 
Z) Integument (in-TE-gyu-mint)  

text[[147, 453, 368, 472]]
ANSWER: Z) Integument  

sub_title[[448, 523, 546, 542]]
## TOSS UP  

text[[146, 556, 850, 611]]
23) EARTH AND SPACE Short Answer By name or number, order the following three metamorphic facies (FAY-sheez) in the order they would appear in a prograde metamorphic series:  

text[[170, 622, 430, 678]]
1) Eclogite (EK-klo-jait) 
2) Zeolite (ZEE-oh-lait) 
3) Greenschist (GREEN-shist)  

text[[147, 694, 299, 712]]
ANSWER: 2, 3, 1  

sub_title[[457, 744, 538, 763]]
## BONUS  

text[[146, 777, 850, 832]]
23) EARTH AND SPACE Short Answer A new Solar System planet is discovered to have a circular orbit and a period of 512 years. In astronomical units, how distant is the planet from the Sun?  

text[[147, 839, 428, 857]]
ANSWER: 64 astronomical units