
# 2020 MIT Science Bowl High School Invitational Round 8  


## TOSS UP  


1) CHEMISTRY Multiple Choice How many normal modes of vibration does the benzene molecule have?  


W) 12 
X) 13 
Y) 30 
Z) 31  


ANSWER: Y) 30  


## BONUS  


1) CHEMISTRY Multiple Choice Assuming that each sodium atom is spherical, which of the following is the closest to the percentage of a body-centered-cubic unit cell occupied by sodium atoms?  


W) 82% 
X) 74% 
Y) 68% 
Z) 52%  


ANSWER: Y) 68%
## TOSS UP  


2) MATH Short Answer In a particular calendar year, the month of December has 5 Mondays. By this information alone, what are all of the days of the week that must occur only 4 times in this month of December?  


ANSWER: Thursday and Friday  


## BONUS  


2) MATH Short Answer Find the roots of the quartic equation (read slowly) \(x^{4} + 2x^{3} + 2x^{2} + 2x + 1 = 0\) .  


ANSWER: \(- 1, i, - i\)  


## TOSS UP  


3) EARTH AND SPACE Short Answer By name or number, arrange the following three layers of the earth in order of increasing density:  


1) Continental lithosphere  
2) Asthenosphere (uhs-THEH-nuh-sfeer)  
3) Oceanic lithosphere  


ANSWER: 1, 3, 2  


## BONUS  


3) EARTH AND SPACE Short Answer Indicate, by name or number, all of the following three statements that are true of T Tauri stars:  


1) They are typically found in star formation regions  
2) T associations are gravitationally bound  
3) They are often found at the center of planetary nebulae  


ANSWER: 1 only
## TOSS UP  


4) BIOLOGY Multiple Choice Antidepressant medications such as fluoxetine (floo- OX-suh-teen) (Prozac) and sertraline (SIR-truh-leen) (Zoloft) work by which of the following mechanisms?  


W) Monoamine oxidase inhibition 
X) N-methyl-D-aspartate receptor antagonism 
Y) Selective serotonin reuptake inhibition 
Z) Serotonin-norepinephrine (nor-e-pi-NE-frin) reuptake inhibition  


ANSWER: Y) Selective serotonin reuptake inhibition  


## BONUS  


4) BIOLOGY Short Answer MAPKKK, also known as mitogen activated protein kinase kinase kinase, is an intracellular kinase important in cell proliferation, cell differentiation, and apoptosis, among other cellular functions. By name or number, identify all of the following four amino acids which are commonly phosphorylated in the cytosol:  


1) Glutamine (GLOO-tuh-meen) 
2) Threonine (THREE-oh-neen) 
3) Phenylalanine (fee-null-A-luh-neen) 
4) Serine (SARE-een)  


ANSWER: 2 and 4
## TOSS UP  


5) PHYSICS Short Answer As a percentage, what is the coefficient of performance of a Carnot (car-KNOW) refrigerator operating to keep its contents at a constant temperature of \(87^{\circ} \mathrm{C}\) while transferring heat to an outside reservoir at \(327^{\circ} \mathrm{C}\) ?  


ANSWER: \(150\%\)  


## BONUS  


5) PHYSICS Short Answer By name or number, identify all of the following three statements that are true of damped harmonic motion:  


1) Energy is conserved  
2) The frequency of underdamped oscillations is greater than the natural oscillation frequency  
3) In overdamped motion, the position goes exponentially to zero  


ANSWER: 3) In overdamped motion, the position goes exponentially to zero
## TOSS UP  


6) ENERGY Multiple Choice Researchers in the Weissman group at MIT are using single-cell CRISPR screens to explore gene function. Which of the following CRISPR-Cas9 system components are needed to bring the Cas9 protein into the nucleus?  


W) sgRNA 
X) PAM 
Y) crRNA 
Z) NLS  


ANSWER: Z) NLS  


## BONUS  


6) ENERGY Short Answer Researchers in the Weissman group at MIT are working on the development of new applications of CRISPR-Cas9 systems. By name or number, identify all of the following four Cas proteins needed for spacer acquisition across all CRISPR-Cas systems.  


1) Cas1 
2) Cas2 
3) Cas5 
4) Cas9  


ANSWER: 1 and 2
## TOSS UP  


7) BIOLOGY Multiple Choice The genome of the novel coronavirus, SARS-CoV-2 (read: SARS Co V 2), can best be described as which of the following?  


W) Double-stranded DNA 
X) Double-stranded RNA 
Y) Single-stranded DNA 
Z) Single-stranded RNA  


ANSWER: Z) Single-stranded RNA  


## BONUS  


7) BIOLOGY Short Answer Which part of the lac operon does the lac repressor bind to?  


ANSWER: Lac operator (accept: operator)  


## TOSS UP  


8) PHYSICS Multiple Choice A spherical conductor carrying net charge Q is placed at the origin. Which of the following statements is NOT true?  


W) The electric field points radially outward 
X) The conductor carries charge only on its surface 
Y) The volume of the conductor is an equipotential 
Z) Outside the sphere, the electric field falls off as \(1 / r^{3}\)  


ANSWER: Z) Outside the sphere, the electric field falls off as \(1 / r^{3}\)  


## BONUS  


8) PHYSICS Short Answer A resistor is constructed using an infinite number of resistors in parallel. The first one has a resistance of 1 ohm, and each successive resistor has a resistance of double the previous one. What is the resistance, in ohms, of this composite?  


ANSWER: 0.5 ohms
## TOSS UP  


9) EARTH AND SPACE Multiple Choice Which of the following silicate minerals does NOT exhibit cleavage?  


W) Muscovite (MUH-schu-vait) 
X) Fluorite (FLOW-rait) 
Y) Orthoclase (OR-thuh-kleis) 
Z) Quartz  


ANSWER: Z) Quartz  


## BONUS  


9) EARTH AND SPACE Multiple Choice Suppose Venus is at its greatest western elongation. Its appearance through a telescope will be most similar to which of the following phases of the Moon?  


W) Waning crescent 
X) Last quarter 
Y) Waning gibbous 
Z) Full moon  


ANSWER: X) Last quarter
## TOSS UP  


10) MATH Short Answer What is the limit, as \(x\) approaches 0, of \(\cos (x) / (x + 1)\) ? ANSWER: 1  


## BONUS  


10) MATH Multiple Choice Which of the following statements about geometry in 4 dimensions is NOT true?  


W) The volume of a hypercube is equal to the fourth power of its side length 
X) The intersection of two non-tangent hyperspheres is a circle 
Y) Two 2-dimensional planes can intersect at a single point 
Z) The maximum number of points which are all at unit distance from each other is 5  


ANSWER: X) The intersection of two non- tangent hyperspheres is a circle
## TOSS UP  


11) ENERGY Multiple Choice Researchers in the Jamison group at MIT are exploring the synthesis of complex natural products through a series of epoxide-opening reactions. Which of the following is NOT true regarding epoxides?  


W) Epoxides contain a three-membered ring 
X) Epoxide stability decreases because of angle strain 
Y) Epoxide stability decreases because of torsional strain 
Z) The full mechanism of ozonolysis proceeds via an epoxide intermediate  


ANSWER: Z) The full mechanism of ozonolysis proceeds via an epoxide intermediate  


## BONUS  


11) ENERGY Short Answer Researchers in the Dinca group at MIT are employing a range of characterization techniques, such as IR spectroscopy, to observe and design new materials. By name or number, rank the following three carbon-oxygen double bonds from least to highest stretching frequency on an IR spectrum:  


1) The carbonyl in an ester 
2) The carbonyl in an amide 
3) The carbonyl in an acid chloride  


ANSWER: 2, 1, 3
## TOSS UP  


12) CHEMISTRY Short Answer Under certain conditions, the average rate of appearance of oxygen gas when ozone is converted to oxygen gas is \(1.2 \times 10^{-3} \mathrm{atm / s}\) . What is the average rate for the disappearance of ozone, expressed in atm/s?  


ANSWER: \(8 \times 10^{- 4}\)  


## BONUS  


12) CHEMISTRY Multiple Choice Which of the following aqueous solutions would have the lowest freezing point?  


W) 0.25 molal (MOW-lul) sodium chloride  X) 0.20 molal sodium sulfate  Y) 0.15 molal magnesium chloride  Z) 0.10 molal aluminum sulfate  


ANSWER: X) 0.20 molal sodium sulfate
## TOSS UP  


13) ENERGY Multiple Choice Researchers in the Surendranath group at MIT are researching how to install modifications at the boundary of graphene surfaces. One technique they discovered was the condensation of a diamine with a 1,3-dicarbonyl at the surface. Which of the following types of ring systems did they form?  


W) Pyridine 
X) Pyrimidine 
Y) Pyrrole 
Z) Pyrazole  


ANSWER: X) Pyrimidine  


## BONUS  


13) ENERGY Short Answer Researchers in the Hong group at MIT are studying the structure of tau fibrils using nuclear magnetic resonance. One technique involved is studying the perturbation between spatially close nuclei, an effect known as what?  


ANSWER: Nuclear Overhauser Effect
## TOSS UP  


14) EARTH AND SPACE Multiple Choice With which of the following river zones is the trunk stream most commonly associated with?  


W) Zone of deposition 
X) Zone of transportation 
Y) Zone of erosion 
Z) Zone of saltation  


ANSWER: X) Zone of transportation  


## BONUS  


14) EARTH AND SPACE Short Answer By name or number, arrange the following three dwarf planets in the solar system from closest to furthest average distance from the Sun:  


1) Eris 
2) Pluto 
3) Ceres  


ANSWER: 3, 2, 1
## TOSS UP  


15) PHYSICS Multiple Choice Which of the following best explains why the speed of sound is higher in water than it is in air?  


W) Water is denser than air 
X) Air is denser than water 
Y) Water is stiffer than air 
Z) Air is stiffer than water  


ANSWER: Y) Water is stiffer than air  


## BONUS  


15) PHYSICS Short Answer Initially unpolarized light passes through three Polaroid filters in the sequence A, B, C. Filter B's polarization axis makes an angle of 60 degrees with respect to filter A, while filter C's polarization axis makes an angle of 90 degrees with respect to filter A. Expressed as a fraction of the initial intensity \(I_0\), find the intensity of the light after passing through filter C. Give your answer in simplest form.  


ANSWER: 3/32
## TOSS UP  


16) CHEMISTRY Multiple Choice The van der Waals equation is a modification of the ideal gas equation, with two constants \(a\) and \(b\) which help characterize the gas. Which of the following molecules has the highest value of \(b\) ?  


W) He 
X) HCl 
Y) \(\mathrm{H}_2\mathrm{O}\) Z) \(\mathrm{C}_6\mathrm{H}_6\)  


ANSWER: Z) \(\mathrm{C}_6\mathrm{H}_6\)  


## BONUS  


16) CHEMISTRY Short Answer By name or number, identify all of the following three statements that true of a weak acid titrated by strong base.  


1) The equivalence point has a pH greater than 7 
2) The pH at the half-equivalence point is equal to the pKa 
3) The slope of the titration curve is smallest at the start of the titration  


ANSWER: 1 and 2
## TOSS UP  


17) BIOLOGY Short Answer What plant hormone causes guard cells to close up in response to water shortage?  


ANSWER: Abscisic acid  


## BONUS  


17) BIOLOGY Multiple Choice Aspirin and Ibuprofen both help to relieve pain by inhibiting cyclooxygenases (cy-clow-OX-i-jin-ay-sis). Cyclooxygenases are responsible for producing what class of molecules?  


W) Prostaglandins  X) Leukotrienes (LOO-koe-treens)  Y) Catecholamines (cat-uh-coal-uh-meens)  Z) PROTACs  


ANSWER: W) Prostaglandins
## TOSS UP  


18) MATH Multiple Choice Which of the following statements about non-degenerate cubic functions with real coefficients is NOT true?  


W) a cubic function can never have a global minimum  
X) a cubic function always has 1 or 3 different real roots  
Y) a cubic function always has an inflection point  
Z) a cubic function must always take on a negative value at some input  


ANSWER: X) A cubic function always has 1 or 3 different real roots  


## BONUS  


18) MATH Multiple Choice Josh is climbing up 10 stairs, taking them either 1 or 2 at a time. How many different ways are there for him to climb up the stairs?  


W) 20  
X) 55  
Y) 89  
Z) 100  


ANSWER: Y) 89
## TOSS UP  


19) EARTH AND SPACE Short Answer By name or by number, identify all of the following four drainage patterns which are not dependent on the composition of the underlying bedrock in their formation:  


1) Dendritic 
2) Rectangular 
3) Radial 
4) Trellis  


ANSWER: 1 and 3  


## BONUS  


19) EARTH AND SPACE Multiple Choice Which of the following forces did Wegner propose as the driving force behind his theory of continental drift?  


W) Repulsive forces from the earth's magnetic field 
X) Convective movement of the earth's mantle 
Y) Tidal forces from the sun and moon 
Z) Buoyancy forces from different crustal densities  


ANSWER: Y) Tidal forces from the sun and moon
## TOSS UP  


20) CHEMISTRY Short Answer What is the term used to describe a covalent bond formed between a Lewis acid and a Lewis base, in which both electrons originate from the base?  


ANSWER: Dative bond (accept: coordinate covalent bond)  


## BONUS  


20) CHEMISTRY Short Answer By name or number, rank the following three isotopes in order of increasing binding energy per nucleon.  


1) H-2 
2) He-4 
3) Li-7  


ANSWER: 1, 3, 2  


## TOSS UP  


21) MATH Short Answer At what real values of x does the following function have a vertical asymptote: \(f(x) = (x^{2} - 3x + 2) / (x^{4} - 16)\) . (read: the quantity \(x^{2} - 3x + 2\) divided by the quantity \(x^{4} - 16\) )?  


ANSWER: \(- 2\)  


## BONUS  


21) MATH Short Answer A square of side length 6 is rotated about one of its diagonals. What is the volume of the solid that it sweeps out?  


ANSWER: \(36\sqrt{2}\pi\)
## TOSS UP  


22) BIOLOGY Multiple Choice Which of the following sugars is NOT an aldose?  


W) Glucose 
X) Ribose 
Y) Galactose 
Z) Fructose  


ANSWER: Z) Fructose  


## BONUS  


22) BIOLOGY Short Answer Name the two fatty acids that are essential for humans.  


ANSWER: Linoleate and linolenate (acceptable: linoleic acid and alpha-linolenic acid; do not accept: omega-3 and omega-6)  


## TOSS UP  


23) PHYSICS Short Answer A ball is moving at a constant velocity of \(\frac{1}{5} c\) in the frame of a space shuttle, which is moving at \(\frac{3}{5} c\) relative to an observer on Earth. If the space shuttle and ball are moving in the same direction to the observer on Earth, what is the speed of the ball for the observer?  


ANSWER: \(\frac{11}{13} c\)  


## BONUS  


23) PHYSICS Multiple Choice Which of the following magnetic fields defined in Cartesian coordinates could theoretically exist in a magnetostatic system?  


W) \(B(x,y,z) = -x\mathbf{i} - y\mathbf{j} - z\mathbf{k}\) X) \(B(x,y,z) = y\mathbf{i} - z\mathbf{j} + x\mathbf{k}\) Y) \(B(x,y,z) = x y\mathbf{i} + y z\mathbf{j} + x z\mathbf{k}\) Z) \(B(x,y,z) = y\mathbf{i} - x\mathbf{j} + z\mathbf{k}\)  


ANSWER: X) \(B(x,y,z) = y\mathbf{i} - z\mathbf{j} + x\mathbf{k}\)