
## TOSS-UP  


1) Physics – Multiple Choice [4] According to Newton's law of universal gravitation, the gravitational potential energy between two objects is proportional to what power of the distance between them?  


W)- 2 X)- 1 Y) 1 Z) 2  


ANSWER: X)- 1 [Mech, GW]  


## BONUS  


1) Physics – Short Answer [4] Water travels through a cylindrical hose at a speed of 1.2 meters per second in a section where the radius of the hose is 4 centimeters. The hose then constricts to a radius of 2 centimeters. What is the speed of the water in this section of the hose?  


ANSWER: 4.8 METERS PER SECOND [Mech, GW]  


## TOSS-UP  


2) Biology – Short Answer [4] What hair-like projections on a paramecium allows it to move through its environment?  


ANSWER: CILIA [Organelle, DJ]  


## BONUS  


2) Biology – Short Answer [4] Order the following three carbohydrates by increasing molar mass: 1) Lactose; 2) Cellulose; 3) Glucose.  


ANSWER: 3, 1, 2 (ACCEPT: GLUCOSE, LACTOSE, CELLULOSE) [Carbohydrates, DJ]
## TOSS-UP  


3) Earth and Space – Short Answer [4] Identify all of the following four layers of the atmosphere in which temperature increases with increasing altitude: 1) Troposphere; 2) Stratosphere; 3) Mesosphere; 4) Thermosphere.  


ANSWER: 2, 4 (ACCEPT: STRATOSPHERE AND THERMOSPHERE) [Meteorology, SS]  


## BONUS  


3) Earth and Space – Multiple Choice [4] Which of the following would result if the density of the universe was greater than the critical density?  


W) Continuous expansion of the universe  
X) Flat universe  
Y) Big crunch  
Z) Big freeze  


ANSWER: Y) BIG CRUNCH [Cosmology, SS]  


## TOSS-UP  


4) Math – Short Answer [4] A coin is flipped 8 times. How many ways are there to get exactly 7 heads?  


ANSWER: 8 [Combo, SS]  


## BONUS  


4) Math – Short Answer [4] Triangle ABC is an obtuse triangle. Identify all of the following three angles, in degrees, that could be the measure of one of the angles in triangle ABC: 1) 20; 2) 90; 3) 110.  


ANSWER: 1 AND 3 (ACCEPT: 20 AND 110) [Geometry, GW]
## TOSS-UP  


5) Chemistry – Multiple Choice [4] Which of the following elements has a yellow flame test?  


W) Lithium  X) Boron  Y) Strontium  Z) Sodium  


ANSWER: Z) SODIUM [Lab, BZ]  


## BONUS  


5) Chemistry – Short Answer [4] The reaction of sodium hydroxide with aluminum foil evolves what flammable gas?  


ANSWER: HYDROGEN GAS (ACCEPT: \(\mathrm{H}_{2}\) ) [Trivia, ND]  


## TOSS-UP  


6) Energy – Short Answer [4] Researchers at UW Madison are studying the release of energy of a chemical reaction by measuring the amount of heat absorbed and released in water. What type of laboratory technique would most likely be used to measure the energy change?  


ANSWER: CALORIMETRY [Chemistry, DJ]  


## BONUS  


6) Energy – Multiple Choice [4] Researchers at the NPRE Lab at UIUC are studying nuclear fusion. Which of the following states of matter are the researchers most likely investigating?  


W) Solid  X) Liquid  Y) Gas  Z) Plasma  


ANSWER: Z) PLASMA [Misc, GW]
## TOSS-UP  


7) Physics - Short Answer [4] A man pulls a sled with a rope at an angle of 60 degrees to the horizontal with a 5-newton force. In joules, what is the work done by the man if he pulls the sled a distance of 4 meters?  


ANSWER: 10 JOULES [Mech, GW]  


## BONUS  


7) Physics - Short Answer [4] What phenomenon occurs when the frequency of an applied force is close to a system's natural frequency, causing the amplitude of oscillations to increase?  


ANSWER: RESONANCE [Mech, GW]  


## TOSS-UP  


8) Biology - Multiple Choice [4] Which of the following best describes the primary structure of a protein?  


W) The interactions between separate polypeptide subunits 
X) The three dimensional shape of the protein 
Y) The amino acid sequence of the protein 
Z) The coiling and folding of a polypeptide due to hydrogen bonds  


ANSWER: Y) THE AMINO ACID SEQUENCE OF THE PROTEIN [Biochemistry, DJ]  


## BONUS  


8) Biology - Short Answer [4] What phylum, whose members often have radial symmetry, do starfish and sea urchins belong to?  


ANSWER: ECHINODERMATA [RSS]
## TOSS-UP  


9) Earth and Space – Short Answer [4] Order the following three mass extinctions in chronological order: 1) Late Devonian; 2) Permian-Triassic; 3) Cretaceous-Paleogene.  


ANSWER: 1, 2, 3 (ACCEPT: LATE DEVONIAN, PERMIAN-TRIASSIC, CRETACEOUS- PALEOGENE) [Geo Time Scale/Misc, JS]  


## BONUS  


9) Earth and Space – Multiple Choice [4] Which of the following planets is NOT correctly matched to the primary component of its atmosphere?  


W) Venus - carbon dioxide  X) Earth - nitrogen  Y) Mars - sulfur dioxide  Z) Jupiter - hydrogen  


ANSWER: Y) MARS - SULFUR DIOXIDE [Solar System, JS]  


## TOSS-UP  


10) Math – Multiple Choice [4] The complex number \(-3 + 2i\) lies in which of the following quadrants in the complex plane?  


W) First  X) Second  Y) Third  Z) Fourth  


ANSWER: X) SECOND [Algebra, GW]  


## BONUS  


10) Math – Short Answer [4] If a sphere has a surface area of \(36\pi\), then in terms of \(\pi\), what is its volume?  


ANSWER: \(36\pi\) [Geometry, GW]
## TOSS-UP  


11) Chemistry – Multiple Choice [4] A one-to-one solution of which of the following would NOT produce an effective buffer?  


W) Ammonia and ammonium chloride  X) Carbonic acid and sodium bicarbonate  Y) Hydrofluoric acid and potassium fluoride  Z) Perchloric acid and silver perchlorate  


ANSWER: Z) PERCHLORIC ACID AND SILVER PERCHLORATE [AB, BZ]  


## BONUS  


11) Chemistry – Short Answer [4] In a 3-liter container of hydrogen gas at 300 kelvin, the pressure is measured to be 1.2 atmospheres. If the volume of the container is expanded to 5 liters while the temperature stays the same, what would be the new pressure, in atmospheres, of the container?  


ANSWER: 0.72 [Thermo, DJ]  


## TOSS-UP  


12) Energy – Short Answer [4] Researchers at UIUC are using acetone to simulate the water-repellent effects of cicada wings. What property describes substances that repel water?  


ANSWER: HYDROPHOBIC [Other, GW]  


## BONUS  


12) Energy – Short Answer [4] Researchers at the University of Chicago have developed "flashlights" to look inside organelles and study how they work. Identify all of the following three organelles that are theorized to have developed from endosymbiosis: 1) Golgi apparatus; 2) Mitochondria; 3) Chloroplast.  


ANSWER: 2 AND 3 (ACCEPT: MITOCHONDRIA AND CHLOROPLAST) [Organelle, DJ]
## TOSS-UP  


13) Physics – Multiple Choice [4] Which of the following is NOT necessarily a part of an RLC circuit?  


W) Inductor 
X) LED 
Y) Capacitor 
Z) Resistor  


ANSWER: X) LED [E&M, GW]  


## BONUS  


13) Physics – Short Answer [4] Identify all of the following three quantities that can NOT be negative: 1) Acceleration; 2) Speed; 3) Distance.  


ANSWER: 2 AND 3 (ACCEPT: SPEED AND DISTANCE) [Mech, GW]  


## TOSS-UP  


14) Biology – Short Answer [4] What enzyme, found in the mesophyll cells of C3 plants, catalyses the carboxylation of RuBP in the Calvin Cycle?  


ANSWER: RUBISCO [Photosynthesis, DJ]  


## BONUS  


14) Biology – Short Answer [4] Identify all of the following three vitamins that are fat soluble: 1) Vitamin A; 2) Vitamin C; 3) Vitamin D.  


ANSWER: 1 AND 3 (ACCEPT: VITAMIN A AND VITAMIN D) [Vitamins, BZ]
## TOSS-UP  


15) Earth and Space - Short Answer [4] What meteorological phenomenon is caused by differential heating of land and ocean and leads to seasonal wind shifts that lead to a wet season with frequent precipitation?  


ANSWER: MONSOON [Meteorology, JS]  


## BONUS  


15) Earth and Space - Short Answer [4] Identify all of the following three minerals that have exactly one plane of cleavage: 1) Biotite; 2) Muscovite; 3) Orthoclase.  


ANSWER: 1 AND 2 (ACCEPT: BIOTITE AND MUSCOVITE) [Mineralogy, BZ]  


## TOSS-UP  


16) Math - Short Answer [4] An arithmetic sequence has a first term of 1 and a fifth term of 13. What is the value of the third term?  


ANSWER: 7 [Algebra, GW]  


## BONUS  


16) Math - Short Answer [4] What is the largest positive integer that divides both 144 and 180?  


ANSWER: 36 [Number Theory, GW]
## TOSS-UP  


17) Chemistry – Short Answer [4] How many different significant resonance structures can be drawn for the carbonate anion, \(\mathrm{CO}_{3}^{2 - }\) ?  


ANSWER: 3 [Counting, BZ]  


## BONUS  


17) Chemistry – Short Answer [4] Manganese reacts with excess sulfate to produce an ionic salt, resulting in an oxidation state of \(+4\) for manganese. What will be the empirical formula for the salt, given that the metal does not form a complex?  


ANSWER: \(\mathrm{Mn(SO_4)_2[OX, DJ]}\)  


## TOSS-UP  


18) Energy – Short Answer [4] Researchers at UW Madison have been studying the effects of enzyme substrate binding affinity with site directed mutagenesis. To what part of an enzyme does a substrate bind to in order to undergo a chemical reaction?  


ANSWER: ACTIVE SITE [Proteins, DJ]  


## BONUS  


18) Energy – Multiple Choice [4] Researchers in the Wei research group at UF are using transition metal nanoparticles to concentrate electromagnetic energy at the nanoscale. Particles of which of the following elements are they most likely using?  


W) Gold X) Magnesium Y) Calcium Z) Zinc  


ANSWER: W) GOLD [BZ]
## TOSS-UP  


19) Physics – Short Answer [4] What elementary particle carries electromagnetic radiation?  


ANSWER: PHOTON [Quantum, GW]  


## BONUS  


19) Physics – Short Answer [4] A piece of aluminum has a density of 2.5 grams per cubic centimeter. If the aluminum thermally expands so that its volume increases by \(25\%\) while its mass remains the same, what is the new density of the metal, in grams per cubic centimeter?  


ANSWER: 2 [Misc, GW]  


## TOSS-UP  


20) Biology – Short Answer [4] Identify all of the following three compounds that are products of glycolysis: 1) Glucose; 2) Pyruvate; 3) ATP.  


ANSWER: 2 AND 3 (ACCEPT: PYRUVATE AND ATP) [Biochem, DJ]  


## BONUS  


20) Biology – Multiple Choice [4] Which of the following statements is true regarding the phospholipids that make up the cell membrane?  


W) The head of the phospholipid is composed of glycerol and phosphate and is hydrophobic X) The head of the phospholipid is composed of hydrocarbons and is hydrophobic Y) The head of the phospholipid is composed of glycerol and phosphate and is hydrophilic Z) The head of the phospholipid is composed of hydrocarbons and is hydrophilic  


ANSWER: Y) THE HEAD OF THE PHOSPHOLIPID IS COMPOSED OF GLYCEROL AND PHOSPHATE AND IS HYDROPHILIC [Lipids, RSS]
## TOSS-UP  


21) Earth and Space – Short Answer [4] What is the only dwarf planet in the solar system not located in the Kuiper belt?  


ANSWER: CERES [Solar System, JS]  


## BONUS  


21) Earth and Space – Short Answer [4] Identify all of the following three techniques or principles that can be used to date a sample of rock WITHOUT using relative dating: 1) Principle of superposition; 2) Principle of fossil succession; 3) Uranium-lead dating.  


ANSWER: 3 ONLY (ACCEPT: URANIUM- LEAD DATING) [Petrology, JS]  


## TOSS-UP  


22) Math – Multiple Choice [4] How many solutions does the system of equations \(5x - 2y = 3\) and \(-10x + 4y = -6\) have?  


W) 0  X) 1  Y) 2  Z) Infinitely many  


ANSWER: Z) INFINITELY MANY [Algebra, GW]  


## BONUS  


22) Math – Short Answer [4] An infinite geometric series has first term 12 and common ratio 1/2. What is the sum of the terms in this infinite series?  


ANSWER: 24 [Algebra, SS]
## TOSS-UP  


23) Chemistry – Multiple Choice [4] What is the expected hybridization of the central carbon atom in methane?  


W) s 
X) sp 
Y) sp2 
Z) sp3  


ANSWER: Z) sp3 [Hybridization, DJ]  


## BONUS  


23) Chemistry – Multiple Choice [4] Which of the following ions is the smallest?  


W) Li+ 
X) Be2+ 
Y) O2- 
Z) F-  


ANSWER: X) Be2+ [Ionic, DJ]