sub_title[[456, 143, 540, 161]]
## TOSS-UP  

text[[115, 178, 874, 215]]
1) Physics – Short Answer [11] In general relativity, what four-dimensional manifold is used to explain relativistic effects and is warped by very massive objects?  

text[[115, 230, 443, 249]]
ANSWER: SPACETIME [Modern, GW]  

sub_title[[463, 266, 533, 284]]
## BONUS  

text[[115, 300, 872, 355]]
1) Physics – Short Answer [11] An infinitely long wire carries a current of 3 amps. Assuming that the permeability of free space is \(4 \mathrm{pi} * 10^{-7}\) Henrys per meter, then to two significant figures, what is the strength of the magnetic field at a distance of 5 meters from the wire?  

text[[115, 370, 466, 389]]
ANSWER: \(1.2 * 10^{- 7}\) TESLAS [E&M, GW]  

sub_title[[456, 440, 540, 459]]
## TOSS-UP  

text[[115, 475, 855, 529]]
2) Biology – Short Answer [11] What is the name of the class of highly specialized small epithelial cells that form outgrowths on plants, which can reduce water loss and reflect excess light in cacti?  

text[[115, 545, 480, 564]]
ANSWER: TRICHOMES [Plant tissues, GW]  

sub_title[[463, 580, 533, 598]]
## BONUS  

text[[115, 615, 865, 651]]
2) Biology – Multiple Choice [11] Which of the following amino acids would you most likely find in the interior of a protein?  

text[[115, 667, 259, 739]]
W) Phenylalanine 
X) Glutamate 
Y) Asparagine 
Z) Lysine  

text[[115, 755, 562, 774]]
ANSWER: W) PHENYLALANINE [Biochemistry, DJ]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[114, 127, 800, 163]]
3) Earth and Space – Multiple Choice [11] Which of the following celestial objects or groupings can NOT be used as a spiral tracer?  

text[[114, 181, 285, 250]]
W) Globular clusters 
X) OB associations 
Y) Cepheid variables 
Z) Emission nebulae  

text[[115, 267, 634, 286]]
ANSWER: W) GLOBULAR CLUSTERS [Other Astronomy, JS]  

sub_title[[463, 303, 533, 320]]
## BONUS  

text[[115, 337, 858, 408]]
3) Earth and Space – Short Answer [11] Identify all of the following three statements that are true regarding subduction zones: 1) Horsts and grabens are common at subduction zones; 2) Most magma produced at subduction zones is a result of flux melting; 3) The deepest earthquakes in the world occur at subduction zones.  

text[[115, 424, 448, 443]]
ANSWER: 2 AND 3 [Other Geology, JS]  

sub_title[[456, 495, 541, 513]]
## TOSS-UP  

text[[114, 529, 832, 565]]
4) Math – Multiple Choice [11] For which of the following values of x will secant of x be undefined?  

text[[115, 583, 177, 652]]
W) 0 
X) \(\pi /4\) Y) \(\pi /2\) Z) \(3\pi /4\)  

text[[115, 669, 386, 688]]
ANSWER: Y) \(\pi /2\) [Algebra, GW]  

sub_title[[463, 705, 533, 722]]
## BONUS  

text[[115, 740, 824, 775]]
4) Math – Short Answer [11] Find the x-coordinate of the point of inflection of the graph \(y = x^3 - 5x^2 + 6x + 2\) .  

text[[115, 792, 365, 811]]
ANSWER: 5/3 [Calculus, GW]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[113, 127, 872, 163]]
5) Chemistry – Short Answer [11] Rank the following three species in order of increasing band gap: 1) Silicon; 2) Diamond; 3) Calcium.  

text[[115, 180, 745, 199]]
ANSWER: 3, 1, 2 (ACCEPT: CALCIUM, SILICON, DIAMOND) [Trivia, BZ]  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 250, 867, 304]]
5) Chemistry – Short Answer [11] Rank the following three processes in terms of increasing work done by the system, assuming that in each case, the system goes from 1 liter to 2 liters: 1) Isothermal expansion; 2) Adiabatic expansion; 3) Isobaric expansion.  

text[[115, 320, 837, 356]]
ANSWER: 2, 1, 3 (ACCEPT: ADIABATIC EXPANSION, ISOTHERMAL EXPANSION, ISOBARIC EXPANSION) [Thermo, BZ]  

sub_title[[456, 408, 540, 425]]
## TOSS-UP  

text[[115, 442, 849, 495]]
6) Energy – Multiple Choice [11] Researchers at the University of Chicago's Gwen Knapp Center for Immunology Research are studying autoimmune diseases. Which of the following diseases is NOT an autoimmune disease?  

text[[115, 513, 305, 583]]
W) Lupus X) Shingles Y) Rheumatoid arthritis Z) Myasthenia gravis  

text[[115, 599, 454, 617]]
ANSWER: X) SHINGLES [Disease, GW]  

sub_title[[463, 634, 533, 652]]
## BONUS  

text[[115, 670, 862, 740]]
6) Energy – Short Answer [11] Researchers in the Weaver lab at the University of Florida are studying the solid surfaces of heterogeneous catalysts on an atomic scale. To study the surface, they are using what form of microscopy, which depends on an electron's ability to penetrate through potential barriers?  

text[[112, 756, 840, 775]]
ANSWER: SCANNING TUNNELING MICROSCOPY (ACCEPT: STM) [Chemistry, BZ]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[113, 127, 872, 163]]
7) Physics – Short Answer [11] When a ferromagnet is heated to a temperature above the Curie point, what type of magnetism does it exhibit?  

text[[115, 180, 482, 199]]
ANSWER: PARAMAGNETISM [Misc, GW]  

sub_title[[462, 215, 533, 234]]
## BONUS  

text[[112, 250, 857, 271]]
7) Physics – Multiple Choice [11] Which of the following types of scattering is NOT elastic?  

text[[115, 286, 220, 355]]
W) Rayleigh X) Raman Y) Mie Z) Thomson  

text[[115, 372, 415, 391]]
ANSWER: X) RAMAN [Mech, GW]  

sub_title[[456, 442, 540, 460]]
## TOSS-UP  

text[[115, 477, 854, 513]]
8) Biology – Multiple Choice [11] Which of the following hormones is NOT secreted by the anterior pituitary gland?  

text[[115, 530, 386, 599]]
W) Thyroid Stimulating Hormone 
X) Follicle Stimulating Hormone 
Y) Growth Hormone 
Z) Calcitonin  

text[[115, 615, 499, 635]]
ANSWER: Z) CALCITONIN [RSS, Endocrine]  

sub_title[[462, 651, 535, 670]]
## BONUS  

text[[115, 687, 867, 723]]
8) Biology – Multiple Choice [11] Which of the following immune cells would be most useful in fighting against multicellular parasites?  

text[[115, 739, 250, 809]]
W) Neutrophil 
X) Eosinophil 
Y) Macrophage 
Z) Dendritic cell  

text[[115, 826, 479, 845]]
ANSWER: X) EOSINOPHIL [Immune, GW]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[114, 127, 861, 163]]
9) Earth and Space – Short Answer [11] Placement of plagioclase feldspars on the continuous series of the Bowen’s reaction series is based on the relative abundance of what two elements?  

text[[114, 180, 780, 216]]
ANSWER: CALCIUM AND SODIUM (ACCEPT: ALUMINUM AND SILICON) [Mineralogy, JS]  

sub_title[[463, 216, 533, 233]]
## BONUS  

text[[114, 250, 822, 287]]
9) Earth and Space – Multiple Choice [11] What two fundamental forces were the last to separate in the moments after the big bang?  

text[[114, 303, 360, 374]]
W) Electromagnetic and weak 
X) Gravity and strong 
Y) Electromagnetic and strong 
Z) Gravity and weak  

text[[114, 390, 680, 409]]
ANSWER: W) ELECTROMAGNETIC AND WEAK [Cosmology, JS]  

sub_title[[456, 460, 541, 478]]
## TOSS-UP  

text[[114, 494, 878, 548]]
10) Math – Multiple Choice [11] \(f(x)\) is a continuous and differentiable function such that \(\mathrm{f}(1) = 4\) and \(\mathrm{f}(6) = 5\) . According to the mean value theorem, which of the following values is guaranteed to be the derivative of \(f(x)\) with respect to \(x\) for some value of \(x\) between 1 and 6?  

text[[114, 565, 180, 633]]
W) -0.2 
X) 0 
Y) 0.2 
Z) 1  

text[[115, 650, 380, 669]]
ANSWER: Y) 0.2 [Calculus, SS]  

sub_title[[463, 686, 533, 704]]
## BONUS  

text[[115, 721, 880, 775]]
10) Math – Short Answer [11] Coby the ant is walking on the surface of a unit cube. He starts at a vertex and wants to go to the vertex across the space diagonal of the cube. What is the shortest length path that he can take?  

text[[115, 790, 409, 809]]
ANSWER: \(\sqrt{5}\) [Geometry, SS]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 866, 163]]
11) Chemistry - Short Answer [11] Rank the following three molecules in terms of increasing carbon-oxygen bond length: 1) Acetate; 2) Tert-butanol; 3) Carbon monoxide.  

text[[115, 180, 869, 216]]
ANSWER: 3, 1, 2 (ACCEPT: CARBON MONOXIDE, ACETATE, TERT- BUTANOL) [Bond Order, BZ]  

sub_title[[461, 233, 533, 251]]
## BONUS  

text[[115, 267, 878, 320]]
11) Chemistry - Short Answer [11] Identify all of the following three species that, when added to a solution of chromic acid, would be oxidized to a carboxylic acid: 1) Ethanol; 2) Isopropanol; 3) Tert-butanol.  

text[[115, 337, 364, 355]]
ANSWER: 1 ONLY [Lab, BZ]  

sub_title[[456, 407, 540, 425]]
## TOSS-UP  

text[[115, 441, 878, 495]]
12) Energy - Short Answer [11] Researchers at the University of Florida are studying the physiology of plants during a drought. What plant hormone do plants secrete during drought-like conditions to minimize water loss through transpiration?  

text[[115, 511, 540, 530]]
ANSWER: ABSCISIC ACID (ACCEPT: ABA) [BZ]  

sub_title[[461, 547, 533, 565]]
## BONUS  

text[[115, 582, 865, 653]]
12) Energy - Multiple Choice [11] Researchers at UW Madison are studying the formation of cosmic rays with the High Altitude Water Cherenkov Gamma-Ray observatory. Which of the following apparatuses would be able to detect cosmic rays based on the condensation of gas in the apparatus?  

text[[115, 670, 293, 740]]
W) Interferometer 
X) Spectrophotometer 
Y) Bubble chamber 
Z) Cloud chamber  

text[[115, 757, 478, 775]]
ANSWER: Z) CLOUD CHAMBER [idk, DJ]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 861, 163]]
13) Physics – Multiple Choice [11] Which of the following objects has the largest moment of inertia about its central axis?  

text[[115, 181, 450, 250]]
W) Hoop of mass m and radius r 
X) Solid cylinder of mass 4m and radius r 
Y) Solid sphere of mass m and radius 2r 
Z) Hollow sphere of mass 2m and radius r  

text[[115, 267, 767, 286]]
ANSWER: X) SOLID CYLINDER OF MASS 4M AND RADIUS R [Mech, GW]  

sub_title[[463, 303, 533, 321]]
## BONUS  

text[[115, 338, 857, 374]]
13) Physics – Short Answer [11] What is the name for the process whereby neutrinos change flavor, confirming that they have a non-zero mass?  

text[[115, 390, 761, 426]]
ANSWER: NEUTRINO OSCILLATION (ACCEPT: OSCILLATION; FLAVOR OSCILLATION) [Modern, SS]  

sub_title[[456, 477, 540, 495]]
## TOSS-UP  

text[[115, 512, 880, 548]]
14) Biology – Short Answer [11] The release of what ion by egg cells during fertilization causes cortical granules to fuse with the cell membrane?  

text[[115, 564, 608, 583]]
ANSWER: \(\mathrm{Ca}^{2 + }\) (ACCEPT: CALCIUM) [Developmental, DJ]  

sub_title[[463, 600, 533, 617]]
## BONUS  

text[[115, 634, 847, 671]]
14) Biology – Multiple Choice [11] Which of the following laboratory techniques would be most useful for counting and sorting individual cells?  

text[[115, 687, 360, 758]]
W) Gel electrophoresis 
X) Flow cytometry 
Y) Thin-layer chromatography 
Z) Polymerase chain reaction  

text[[115, 775, 595, 793]]
ANSWER: X) FLOW CYTOMETRY [Biotechnology, GW]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 860, 164]]
15) Earth and Space - Short Answer [11] At which of the following latitudes is the salinity in oceans generally the highest?  

text[[115, 181, 300, 250]]
W) At the equator  X) \(30^{\circ}\) north and south  Y) \(45^{\circ}\) north and south  Z) \(60^{\circ}\) north and south  

text[[115, 268, 614, 287]]
ANSWER: X) \(30^{\circ}\) NORTH AND SOUTH [Oceanography, JS]  

sub_title[[462, 303, 533, 320]]
## BONUS  

text[[115, 337, 857, 391]]
15) Earth and Space - Short Answer [11] Identify all of the four designations of solar system objects that are associated with close proximity to Earth: 1) Apollo objects; 2) Centaurs; 3) NEOs; 4) Trojans.  

text[[115, 407, 805, 427]]
ANSWER: 1 AND 3 (ACCEPT: APOLLO OBJECTS AND NEOS) [Solar System, JS]  

sub_title[[456, 478, 541, 496]]
## TOSS-UP  

text[[115, 512, 625, 531]]
16) Math - Short Answer [11] In modulo 13, what is 5 times 6?  

text[[115, 547, 396, 566]]
ANSWER: 4 [Number Theory, SS]  

sub_title[[462, 583, 533, 600]]
## BONUS  

text[[115, 617, 883, 653]]
16) Math - Short Answer [11] The circumcircle of an equilateral triangle has a circumference of 20pi. What is its inradius?  

text[[115, 670, 350, 689]]
ANSWER: 5 [Geometry, SS]sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 843, 163]]
17) Chemistry – Multiple Choice [11] Which of the following plots of rate constant against temperature would produce a straight line?  

text[[115, 181, 610, 251]]
W) Rate constant vs temperature  X) Rate constant vs the reciprocal of temperature  Y) Natural log of rate constant vs temperature  Z) Natural log of rate constant vs the reciprocal of temperature  

text[[115, 267, 799, 303]]
ANSWER: Z) NATURAL LOG OF RATE CONSTANT VS THE RECIPROCAL OF TEMPERATURE [Kinetics, BZ]  

sub_title[[462, 320, 533, 338]]
## BONUS  

text[[115, 354, 860, 391]]
17) Chemistry – Short Answer [11] Given that the \(\mathrm{K}_{\mathrm{a}} / \mathrm{k}\) sub a] of HClO is \(3*10^{-8}\) , what is the \(\mathrm{K}_{\mathrm{b}} / \mathrm{k}\) sub b] value for ClO⁻ to two significant figures?  

text[[115, 407, 351, 426]]
ANSWER: \(3.3*10^{- 7}\) [AB, DJ]  

sub_title[[456, 477, 540, 495]]
## TOSS-UP  

text[[115, 512, 847, 582]]
18) Energy – Short Answer [11] Researchers in the Baer lab at the University of Florida are studying the mutational sensitivity in nematode species. What is the name of one of the nematode species they are studying, which was the first multicellular organism to have its genome sequenced?  

text[[115, 598, 736, 617]]
ANSWER: C. ELEGANS (ACCEPT: CAENORHABDITIS ELEGANS) [BZ]  

sub_title[[462, 634, 533, 652]]
## BONUS  

text[[115, 670, 869, 722]]
18) Energy – Short Answer [11] Researchers at UW Madison have been studying the synthetic pathway of a modified type of glucose in bacteria that cause tuberculosis. Tuberculosis comes from what specific genus of bacteria?  

text[[115, 739, 496, 757]]
ANSWER: MYCOBACTERIUM [Disease, DJ]sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 877, 181]]
19) Physics - Short Answer [11] What principle in general relativity states that the gravitational force experienced locally while standing on a massive body is the same as the pseudoforce experienced by an observer in a non-inertial reference frame?  

text[[115, 197, 565, 215]]
ANSWER: EQUIVALENCE PRINCIPLE [Modern, SS]  

sub_title[[462, 233, 533, 251]]
## BONUS  

text[[116, 267, 868, 321]]
19) Physics - Short Answer [11] For a point source emitting a sound wave in 3D equally in all directions, the sound intensity observed at a distance of 1 meter is 80 decibels. What is the observed sound intensity, to the nearest decibel, at a distance of 2 meters?  

text[[116, 338, 333, 356]]
ANSWER: 74 [Mech, ND]  

sub_title[[456, 407, 540, 425]]
## TOSS-UP  

text[[115, 443, 872, 479]]
20) Biology - Short Answer [11] Anthozoa, scyphozoa, and cubozoa are all classes that belong to what animal phylum?  

text[[115, 495, 495, 513]]
ANSWER: CNIDARIA [Animal Diversity, BZ]  

sub_title[[462, 530, 533, 548]]
## BONUS  

text[[115, 565, 879, 653]]
20) Biology - Short Answer [11] After an action potential arrives at a chemical synapse of a neuron, order the following three steps that occur from first to last: 1) The neurotransmitter binds to ligand-gated ion channels in the postsynaptic membrane; 2) Synaptic vesicles fuse to the presynaptic membrane; 3) Depolarization opens voltage-gated channels, triggering an influx of calcium.  

text[[115, 670, 387, 688]]
ANSWER: 3, 2, 1 [Nervous, GW]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 867, 199]]
21) Earth and Space - Short Answer [11] Identify all of the following three statements that are true about the Oort cloud: 1) Most long-period comets originate in the Oort cloud; 2) The Oort Cloud lies as a disk roughly in the plane of the rest of the solar system; 3) The Oort Cloud is easily affected by the gravitational pull of passing stars.  

text[[115, 215, 434, 234]]
ANSWER: 1 AND 3 [Solar System, JS]  

sub_title[[462, 250, 533, 268]]
## BONUS  

text[[115, 285, 833, 321]]
21) Earth and Space - Multiple Choice [11] Which of the following best characterizes the energy transfer in a 6 solar mass star?  

text[[115, 338, 456, 408]]
W) Fully convective  
X) Fully radiative  
Y) Convective core and radiative envelope  
Z) Radiative core and convective envelope  

text[[115, 423, 844, 460]]
ANSWER: Y) CONVECTIVE CORE AND RADIATIVE ENVELOPE [Stellar Astronomy, GW]  

sub_title[[456, 512, 541, 530]]
## TOSS-UP  

text[[115, 546, 827, 584]]
22) Math - Short Answer [11] If \(2^{x} = 5\) , then what is the value of \(2^{3x + 1}\) [2 to the power of quantity \(3x + 1\) ]?  

text[[115, 599, 364, 618]]
ANSWER: 250 [Algebra, GW]  

sub_title[[462, 634, 533, 652]]
## BONUS  

text[[115, 669, 870, 705]]
22) Math - Multiple Choice [11] Let \(\mathrm{f}(x)\) equal the integral from 2 to \(\mathrm{x}^{2}\) of \(\sin (t)\mathrm{dt}\) . What is the derivative of \(\mathrm{f}(x)\) at \(\mathrm{x} = 3\) ?  

text[[115, 722, 200, 792]]
W) \(\sin (3)\) X) \(\sin (9)\) Y) 6sin(3) Z) 6sin(9)  

text[[115, 809, 420, 828]]
ANSWER: Z) 6sin(9) [Calculus, GW]sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[113, 127, 867, 164]]
23) Chemistry – Multiple Choice [11] Which of the following is NOT a product of beta minus decay?  

text[[115, 181, 310, 250]]
W) Proton 
X) Photon 
Y) Electron antineutrino 
Z) Electron  

text[[115, 268, 428, 286]]
ANSWER: X) PHOTON [Nuclear, DJ]  

sub_title[[463, 303, 533, 320]]
## BONUS  

text[[115, 338, 870, 374]]
23) Chemistry – Multiple Choice [11] Which of the following describes the spontaneity of the dissolution of ammonium nitrate?  

text[[115, 391, 449, 460]]
W) Spontaneous at all temperatures 
X) Never spontaneous 
Y) Spontaneous only at high temperatures 
Z) Spontaneous only at low temperatures  

text[[115, 477, 795, 496]]
ANSWER: Y) SPONTANEOUS ONLY AT HIGH TEMPERATURES [Thermo, BZ]