sub_title[[456, 143, 541, 161]]
## TOSS-UP  

text[[115, 178, 845, 214]]
1) Physics – Short Answer [12] If a photon has a high enough energy, it may spontaneously convert to an electron and a positron. What is the name of this process?  

text[[115, 230, 520, 249]]
ANSWER: PAIR PRODUCTION [Quantum, GW]  

sub_title[[463, 265, 534, 284]]
## BONUS  

text[[115, 300, 874, 355]]
1) Physics – Multiple Choice [12] Let c be the speed of light. Particle A, which is traveling at a speed of 0.5c in the +x direction, is moving toward particle B, which is traveling at a speed of 0.5c in the -x direction. In A's reference frame, what is the speed of particle B?  

text[[115, 370, 189, 440]]
W) 0.5c 
X) 0.72c 
Y) 0.8c 
Z) 0.96c  

text[[115, 457, 393, 476]]
ANSWER: Y) 0.8c [Modern, GW]  

sub_title[[456, 528, 540, 546]]
## TOSS-UP  

text[[115, 563, 852, 600]]
2) Biology – Short Answer [12] What phenomenon occurs when excess root pressure causes droplets of xylem sap to accumulate on the edges of plant leaves?  

text[[115, 615, 426, 634]]
ANSWER: GUTTATION [Plants, BZ]  

sub_title[[463, 650, 534, 668]]
## BONUS  

text[[115, 685, 875, 721]]
2) Biology – Short Answer [12] Identify all of the following three eukaryotic cellular structures which have a “9 + 2” arrangement of microtubules: 1) Flagella; 2) Centrioles; 3) Basal body.  

text[[115, 737, 625, 757]]
ANSWER: 1 ONLY (ACCEPT: FLAGELLA) [Organelle, RSS]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 863, 181]]
3) Earth and Space – Short Answer [12] What general term is used to describe any product of condensation or deposition of atmospheric water vapor in the atmosphere or at Earth's surface, such as clouds, fog, rain, snow, or hail?  

text[[115, 197, 510, 215]]
ANSWER: HYDROMETEOR [Meteorology, JS]  

sub_title[[462, 233, 533, 251]]
## BONUS  

text[[115, 268, 870, 304]]
3) Earth and Space – Short Answer [12] What is the ratio of the number of silicon atoms to the number of oxygen atoms in a pyroxene mineral?  

text[[115, 320, 540, 339]]
ANSWER: 1 TO 3 (ACCEPT: 1/3) [Mineralogy, BZ]  

sub_title[[456, 390, 540, 408]]
## TOSS-UP  

text[[115, 424, 870, 461]]
4) Math – Multiple Choice [12] Each interior angle of a regular polygon has a degree measure of 156. How many sides does this regular polygon have?  

text[[115, 477, 168, 547]]
W) 36 X) 30 Y) 24 Z) 15  

text[[115, 564, 382, 583]]
ANSWER: Z) 15 [Geometry, SS]  

sub_title[[462, 599, 533, 617]]
## BONUS  

text[[115, 634, 809, 670]]
4) Math – Short Answer [12] What is the limit as \(x\) approaches \(\mathrm{pi} / 4\) of the fraction with numerator \(\tan (x) - 1\) and denominator \(x - \mathrm{pi} / 4\) ?  

text[[115, 687, 350, 705]]
ANSWER: 2 [Calculus, GW]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 816, 163]]
5) Chemistry – Short Answer [12] What cycle is used to calculate the lattice energy of a crystalline solid using applications of Hess's law?  

text[[115, 180, 576, 199]]
ANSWER: BORN- HABER CYCLE [Lattice Energy, DJ]  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 250, 859, 304]]
5) Chemistry – Short Answer [12] At low temperatures where vibrational degrees of freedom can be ignored, what is the constant pressure molar heat capacity of acetylene in terms of the ideal gas constant R?  

text[[115, 320, 508, 339]]
ANSWER: 7/2 R (ACCEPT: 3.5R) [Thermo, BZ]  

sub_title[[456, 390, 540, 408]]
## TOSS-UP  

text[[115, 425, 857, 479]]
6) Energy – Multiple Choice [12] Researchers at Northwestern University are using atomic force microscopy to measure the Casimir effect. The Casimir effect arises when two plates are separated by which of the following?  

text[[115, 495, 272, 566]]
W) Vacuum X) Superconductor Y) Ferromagnet Z) Strong dielectric  

text[[115, 582, 428, 600]]
ANSWER: W) VACUUM [Misc, GW]  

sub_title[[463, 616, 533, 634]]
## BONUS  

text[[115, 652, 861, 722]]
6) Energy – Short Answer [12] Researchers in the Wagener group at the University of Florida are studying the properties of polymers that contain boronic acids and esters. What is the chemical formula of the acid that boronic acids are derived from, which is the only triprotic boron based oxyacid?  

text[[115, 739, 463, 758]]
ANSWER: \(\mathrm{H_3BO_3}\) (ACCEPT: \(\mathrm{B(OH)_3}\) )[BZ]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 875, 163]]
7) Physics - Short Answer [12] Transformers and motors rely on what effect, where the current from one coil generates a magnetic flux that induces a current in another coil?  

text[[115, 180, 866, 216]]
ANSWER: MUTUAL INDUCTANCE (ACCEPT: MUTUAL INDUCTION; INDUCTANCE; INDUCTION) [E&M, GW]  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 250, 879, 304]]
7) Physics - Short Answer [12] A water tank is 10 meters tall and is completely filled. A hole is drilled 5 meters above the bottom of the tank and water flows out the side. To one significant figure, in meters per second, what is the speed of the water flowing out the side of the tank?  

text[[116, 320, 327, 339]]
ANSWER: 10 [Mech, SS]  

sub_title[[456, 390, 540, 408]]
## TOSS-UP  

text[[115, 424, 874, 460]]
8) Biology - Short Answer [12] Bacteria in the genus Mycoplasma are the only known bacteria to lack what structure?  

text[[115, 476, 825, 496]]
ANSWER: CELL WALL (DO NOT ACCEPT: CELL MEMBRANE) [Systematics, GW]  

sub_title[[463, 512, 533, 530]]
## BONUS  

text[[115, 547, 872, 582]]
8) Biology - Multiple Choice [12] Which of the following statements regarding cytochrome C is NOT true?  

text[[115, 600, 525, 616]]
W) It is found in the inner mitochondrial membrane  

text[[115, 618, 338, 635]]
X) It contains a heme group  

text[[115, 636, 434, 652]]
Y) It is a cofactor in the citric acid cycle  

text[[115, 654, 525, 671]]
Z) It is released into the cytoplasm during apoptosis  

text[[115, 686, 785, 706]]
ANSWER: Y) IT IS A COFACTOR IN THE CITRIC ACID CYCLE [Biochem, DJ]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[113, 127, 872, 163]]
9) Earth and Space – Short Answer [12] What paradox in astronomy states that the darkness of the night sky conflicts with the assumption of an infinite, static universe?  

text[[115, 180, 533, 199]]
ANSWER: OLBERS' PARADOX [Cosmology, SS]  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[113, 250, 802, 270]]
9) Earth and Space – Short Answer [12] What moon of Saturn has the highest albedo?  

text[[115, 285, 475, 304]]
ANSWER: ENCELADUS [Meteorology, JS]  

sub_title[[456, 355, 540, 373]]
## TOSS-UP  

text[[115, 390, 852, 426]]
10) Math – Short Answer [12] Identify all of the following three centers that must always lie inside a triangle: 1) Centroid; 2) Orthocenter; 3) Circumcenter.  

text[[115, 442, 622, 461]]
ANSWER: 1 ONLY (ACCEPT: CENTROID) [Geometry, GW]  

sub_title[[463, 477, 533, 495]]
## BONUS  

text[[115, 512, 879, 548]]
10) Math – Multiple Choice [12] Which of the following chi-squared tests has exactly 6 degrees of freedom?  

text[[115, 565, 312, 635]]
W) 3 rows by 2 columns  X) 8 rows by 1 column  Y) 3 rows by 4 columns  Z) 2 rows by 1 column  

text[[115, 651, 587, 671]]
ANSWER: Y) 3 ROWS BY 4 COLUMNS [Statistics, GW]sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 850, 163]]
11) Chemistry – Short Answer [12] Rank the following three solvents in terms of increasing rate at which an \(\mathrm{S_N2}\) reaction would occur: 1) Diethyl ether; 2) DMSO; 3) Water  

text[[116, 180, 353, 199]]
ANSWER: 3, 1, 2 [Orgo, BZ]  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[116, 250, 832, 321]]
11) Chemistry – Short Answer [12] When redox reactions are carried out, the minimum voltage supplied to make the reaction occur is often greater than the theoretically predicted voltage. What term describes the difference between the practical and theoretical voltage necessary to make a reaction occur?  

text[[115, 337, 528, 356]]
ANSWER: OVERPOTENTIAL [Electrochem, ND]  

sub_title[[456, 408, 540, 426]]
## TOSS-UP  

text[[115, 443, 883, 496]]
12) Energy – Multiple Choice [12] Researchers at UW Madison are studying the Schlosser modification Wittig reaction mechanism, an olefination of a carbonyl functional group. Which of the following statements regarding the carbonyl functional group is NOT true?  

text[[115, 512, 778, 530]]
W) Ketones, aldehydes, and carboxylic acids all have the carbonyl functional group.  

text[[115, 531, 552, 548]]
X) An oxygen atom is double bonded to a carbon atom.  

text[[115, 549, 444, 565]]
Y) The carbonyl carbon is sp2 hybridized  

text[[115, 567, 516, 583]]
Z) There is a partial negative charge on the carbon.  

text[[115, 599, 881, 635]]
ANSWER: Z) THERE IS A PARTIAL NEGATIVE CHARGE ON THE CARBON. [Chemistry, DJ]  

sub_title[[463, 652, 533, 670]]
## BONUS  

text[[115, 687, 879, 740]]
12) Energy – Short Answer [12] Researchers at UW Madison are studying the depolarization of neurons for patients with multiple sclerosis. Multiple sclerosis is a debilitating disease affecting movement. What specific part of the neuron is affected by multiple sclerosis?  

text[[115, 756, 477, 775]]
ANSWER: MYELIN SHEATH [Animal, DJ]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 807, 163]]
13) Physics – Short Answer [12] What principle says that in the limit of large quantum numbers, quantum physics ‘merges smoothly’ with classical physics?  

text[[115, 180, 625, 199]]
ANSWER: CORRESPONDENCE PRINCIPLE [Quantum, ND]  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 250, 877, 304]]
13) Physics – Short Answer [12] Order the following 3 pendulums in order of increasing period of oscillation: 1) Ball on a string of length 5 cm; 2) Uniform rod of length 8 cm; 3) Ball on a string of length 8 cm.  

text[[115, 320, 359, 339]]
ANSWER: 2, 1, 3 [Mech, CT]  

sub_title[[456, 389, 541, 408]]
## TOSS-UP  

text[[115, 424, 866, 460]]
14) Biology – Short Answer [12] What enzyme, found in red blood cells, synthesizes carbonic acid from water and carbon dioxide?  

text[[115, 476, 640, 496]]
ANSWER: CARBONIC ANHYDRASE [RSS, CIRCULATORY]  

sub_title[[463, 512, 533, 530]]
## BONUS  

text[[115, 547, 880, 583]]
14) Biology – Multiple Choice [12] Which of the following genuses of bacteria is most likely to cause inflammation of the tonsils?  

text[[115, 600, 271, 670]]
W) Staphylococcus X) Streptococcus Y) Streptomyces Z) Bacillus  

text[[115, 686, 530, 706]]
ANSWER: X) STREPTOCOCCUS [Diseases, GW]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 861, 182]]
15) Earth and Space - Short Answer [12] Rank the following three forms of stellar nucleosynthesis by increasing temperature dependence: 1) Proton-proton chain; 2) CNO cycle; 3) Triple alpha process.  

text[[115, 197, 856, 234]]
ANSWER: 1, 2, 3 (ACCEPT: PROTON-PROTON CHAIN; CNO CYCLE; TRIPLE ALPHA PROCESS) [Stellar Astronomy, BZ]  

sub_title[[463, 250, 533, 268]]
## BONUS  

text[[115, 285, 848, 321]]
15) Earth and Space - Multiple Choice [12] Which of the following classes of substances is dissolved in water vented from black smokers and forms coatings on nearby rocks?  

text[[115, 338, 253, 408]]
W) Iron oxides 
X) Silicates 
Y) Carbonates 
Z) Metal sulfides  

text[[115, 424, 560, 443]]
ANSWER: Z) METAL SULFIDES [Oceanography, JS]  

sub_title[[456, 495, 540, 512]]
## TOSS-UP  

text[[115, 529, 872, 565]]
16) Math - Short Answer [12] What is the definite integral from 0 to \(2\mathrm{pi}\) of \(\sin (x) - \cos (x)\) with respect to \(x\) ?  

text[[115, 582, 339, 600]]
ANSWER: 0 [Calculus, SS]  

sub_title[[463, 617, 533, 634]]
## BONUS  

text[[115, 652, 870, 688]]
16) Math - Short Answer [12] Given that log base 10 of 2 equals 0.30 and the log base ten of 3 equals 0.48, find the value of log base 10 of 45 to the nearest hundredth.  

text[[115, 705, 368, 723]]
ANSWER: 1.66 [Algebra, GW]sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 805, 163]]
17) Chemistry – Multiple Choice [12] The oxidation of a primary alcohol with sodium dichromate in acidic solution results in which of the following functional groups?  

text[[115, 181, 287, 251]]
W) Ester 
X) Aldehyde 
Y) Carboxylic acid 
Z) Secondary alcohol  

text[[115, 267, 514, 286]]
ANSWER: Y) CARBOXYLIC ACID [Orgo, ND]  

sub_title[[463, 303, 533, 321]]
## BONUS  

text[[115, 338, 850, 373]]
17) Chemistry – Short Answer [12] Considering resonance effects, what is the hybridization about the nitrogen atom in a secondary amide?  

text[[115, 390, 400, 409]]
ANSWER: \(\mathrm{sp}^{2}\) [Hybridization, ND]  

sub_title[[456, 460, 540, 478]]
## TOSS-UP  

text[[115, 494, 859, 547]]
18) Energy – Short Answer [12] Researchers at Iowa State University are studying the Shine- Dalgarno sequence, a binding site in prokaryotic ribosomes. The 70S prokaryotic ribosome is composed of what two other subunits?  

text[[115, 564, 413, 582]]
ANSWER: 30S AND 50S [Cyto, DJ]  

sub_title[[463, 599, 533, 617]]
## BONUS  

text[[115, 634, 879, 722]]
18) Energy – Multiple Choice [12] Scientists at the University of Chicago are using the Advanced Photon Source to generate X-rays, which can be used to study the internal structure of crystals. Suppose that a beam of light with a wavelength of 1 nanometer is shone on a crystal, and the angle at which the maximum constructive interference occurs is 45 degrees with respect to the lattice. Which of the following is closest to the lattice separation of the crystal?  

text[[115, 740, 268, 809]]
W) 0.5 nanometers 
X) 0.7 nanometers 
Y) 1 nanometer 
Z) 1.2 nanometers  

text[[115, 827, 520, 845]]
ANSWER: X) 0.7 NANOMETERS [Physics, GW]sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 870, 163]]
19) Physics – Multiple Choice [12] Which of the following particles does NOT obey the Pauli Exclusion principle?  

text[[115, 181, 210, 250]]
W) Gluon 
X) Electron 
Y) Proton 
Z) Positron  

text[[115, 268, 444, 286]]
ANSWER: W) GLUON [Quantum, GW]  

sub_title[[463, 303, 533, 320]]
## BONUS  

text[[115, 338, 831, 390]]
19) Physics – Short Answer [12] SQUIDs are devices that rely on the Josephson effect to measure extremely sensitive magnetic fields. They typically consist of two of what type of material separated by a weak link?  

text[[115, 407, 483, 425]]
ANSWER: SUPERCONDUCTOR [Misc, SS]  

sub_title[[456, 477, 540, 495]]
## TOSS-UP  

text[[115, 512, 867, 548]]
20) Biology – Multiple Choice [12] Which of the following techniques could be used to detect for the presence of collagen?  

text[[115, 565, 255, 633]]
W) Northern blot 
X) Western blot 
Y) Eastern blot 
Z) Southern blot  

text[[115, 651, 561, 670]]
ANSWER: X) WESTERN BLOT [Biotechnology, GW]  

sub_title[[463, 686, 533, 704]]
## BONUS  

text[[115, 722, 874, 757]]
20) Biology – Short Answer [12] What viscous fluid helps reduce friction between the cartilage of joints during movement?  

text[[115, 774, 525, 792]]
ANSWER: SYNOVIAL FLUID [Connective, GW]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[114, 127, 877, 163]]
21) Earth and Space – Short Answer [12] Pyroxenes are inosilicates that contain chains of silica tetrahedra. Indicating sign, what is the charge of the silicate ion in pyroxenes?  

text[[115, 180, 356, 199]]
ANSWER: 2- [Geochem, YL]  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 250, 872, 286]]
21) Earth and Space – Short Answer [12] What is the name for the region of the Atlantic ocean that has no land boundaries, but is instead bound by four oceanic surface currents?  

text[[115, 303, 523, 321]]
ANSWER: SARGASSO SEA [Oceanography, BZ]  

sub_title[[456, 372, 541, 390]]
## TOSS-UP  

text[[115, 407, 867, 443]]
22) Math – Multiple Choice [12] Suppose the number one-six-nine in base b is equal to 400 in base 10. What is the value of b?  

text[[115, 460, 168, 530]]
W) 15 X) 17 Y) 18 Z) 20  

text[[115, 547, 442, 565]]
ANSWER: X) 17 [Number Theory, GW]  

sub_title[[463, 582, 533, 600]]
## BONUS  

text[[115, 617, 849, 670]]
22) Math – Short Answer [12] Quadrilateral ABCD has side lengths of 3, 9, 7, and x, in that order, and it is known that a circle can be inscribed inside ABCD. What is the value of x, the length of the fourth side?  

text[[115, 687, 360, 706]]
ANSWER: 1 [Geometry, GW]sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[114, 127, 861, 163]]
23) Chemistry – Multiple Choice [12] The change in which of the following quantities equals the heat transferred to a system under constant volume?  

text[[115, 181, 317, 251]]
W) Enthalpy 
X) Internal energy 
Y) Work 
Z) Helmholtz free energy  

text[[115, 268, 534, 286]]
ANSWER: X) INTERNAL ENERGY [Thermo, BZ]  

sub_title[[463, 303, 533, 320]]
## BONUS  

text[[115, 338, 872, 408]]
23) Chemistry – Multiple Choice [12] When a solution of silver diamine nitrate, also known as Tollens' reagent, is added to a solution of an unknown organic compound, a silver mirror appears. Which of the following functional groups is most likely to be part of the unknown organic compound?  

text[[115, 425, 220, 494]]
W) Nitrile 
X) Amide 
Y) Aldehyde 
Z) Ketone  

text[[115, 512, 430, 530]]
ANSWER: Y) ALDEHYDE [Lab, ND]