sub_title[[456, 143, 540, 161]]
## TOSS-UP  

text[[115, 178, 857, 214]]
1) Physics – Short Answer [5] Two sound waves with frequencies of 230 hertz and 240 hertz interfere with each other. What is the beat frequency of the resultant wave?  

text[[115, 230, 400, 249]]
ANSWER: 10 HERTZ [Mech, ND]  

sub_title[[463, 266, 533, 284]]
## BONUS  

text[[115, 301, 839, 336]]
1) Physics – Multiple Choice [5] Which of the following is NOT an example of systematic error?  

text[[115, 354, 790, 424]]
W) A scale randomly differs by a few grams for each measurement  X) The Earth is not a perfect sphere when calculating the local acceleration of gravity  Y) A spring does not precisely follow Hooke's law  Z) The molar mass of an element has a small margin of error  

text[[115, 440, 797, 476]]
ANSWER: W) A SCALE RANDOMLY DIFFERS BY A FEW GRAMS FOR EACH MEASUREMENT [Misc, GW]  

sub_title[[456, 528, 540, 547]]
## TOSS-UP  

text[[115, 564, 878, 600]]
2) Biology – Multiple Choice [5] Lysozymes are responsible for the destruction of bacterial cell walls because they catalyze the hydrolysis of which of the following polymers?  

text[[115, 617, 257, 686]]
W) Cellulose  X) Chitin  Y) Peptidoglycan  Z) Amylose  

text[[115, 703, 523, 722]]
ANSWER: Y) PEPTIDOGLYCAN [Cytology, DJ]  

sub_title[[463, 738, 534, 757]]
## BONUS  

text[[115, 774, 860, 808]]
2) Biology – Short Answer [5] What compound adds two carbons to oxaloacetate in the citric acid cycle to form citrate?  

text[[115, 826, 476, 844]]
ANSWER: ACETYL- COA [Respiration, DJ]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[114, 127, 839, 163]]
3) Earth and Space – Short Answer [5] What term is used to describe the depth zone of the ocean in which photosynthesis can occur?  

text[[114, 179, 880, 216]]
ANSWER: PHOTIC ZONE (ACCEPT: SUNLIT ZONE, EUPHOTIC ZONE, OR EPIPELAGIC ZONE) [Oceanography, JS]  

sub_title[[461, 233, 533, 251]]
## BONUS  

text[[114, 268, 880, 305]]
3) Earth and Space – Short Answer [5] A star with a mass of 4 solar masses fuses hydrogen into helium through what specific six-stage sequence of reactions?  

text[[114, 320, 512, 339]]
ANSWER: CNO CYCLE [Stellar Astronomy, SS]  

sub_title[[456, 390, 540, 408]]
## TOSS-UP  

text[[114, 424, 856, 460]]
4) Math – Short Answer [5] A fair coin is flipped and lands tails. What is the probability that each of the next two coin flips also land tails?  

text[[115, 477, 333, 496]]
ANSWER: \(\frac{1}{4}\) [Combo, SS]  

sub_title[[461, 512, 533, 530]]
## BONUS  

text[[114, 547, 866, 602]]
4) Math – Short Answer [5] A sequence is defined by \(a_{1} = 1\) , \(a_{2} = 3\) (read: a sub 1 = 1, a sub 2 = 3), and for n greater than 0, \(a_{n + 2} = 3a_{n + 1} - 2a_{n}\) (read: a sub quantity \(n + 2\) equals 3 a sub quantity \(n + 1\) minus 2 a sub \(n\) ). What is the value of \(a_{5}\) (read: a sub 5)?  

text[[115, 618, 355, 636]]
ANSWER: 31 [Algebra, GW]sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 840, 163]]
5) Chemistry – Multiple Choice [5] Which of the following elements will have the greatest electronegativity difference when bonded to fluorine?  

text[[115, 181, 213, 252]]
W) Boron 
X) Carbon 
Y) Nitrogen 
Z) Oxygen  

text[[115, 268, 485, 286]]
ANSWER: W) BORON [Periodic Trends, DJ]  

sub_title[[462, 303, 533, 320]]
## BONUS  

text[[115, 338, 872, 390]]
5) Chemistry – Short Answer [5] The reaction A yields B is known to be a third order reaction with respect to A. How many times as fast will the reaction be if the initial concentration of A is tripled?  

text[[115, 407, 346, 425]]
ANSWER: 27 [Kinetics, DJ]  

sub_title[[456, 477, 540, 495]]
## TOSS-UP  

text[[115, 512, 866, 582]]
6) Energy – Short Answer [5] Researchers at UW Madison have been studying the application of metamaterials in our everyday lives. Metamaterials are important because they often have a negative value for what dimensionless number, defined as the speed of light in a vacuum over the phase velocity of the light in the material?  

text[[115, 598, 794, 617]]
ANSWER: INDEX OF REFRACTION (ACCEPT: REFRACTIVE INDEX) [idk, DJ]  

sub_title[[462, 634, 533, 652]]
## BONUS  

text[[115, 670, 877, 722]]
6) Energy – Multiple Choice [5] Researchers at Iowa State University are studying the effects egg consumption has on those with Type 2 diabetes. Which of the following statements correctly describes Type 2 Diabetes?  

text[[115, 740, 797, 810]]
W) The body is unable to produce any insulin 
X) The body is unable to produce any glucagon 
Y) The body is able to produce some insulin, but it isn't enough or cells are resistant 
Z) The body is able to produce some glucagon, but it isn't enough or cells are resistant  

text[[115, 826, 806, 861]]
ANSWER: Y) THE BODY IS ABLE TO PRODUCE SOME INSULIN, BUT IT ISN'T ENOUGH OR CELLS ARE RESISTANTsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[112, 127, 864, 147]]
7) Physics – Short Answer [5] What quantity equals the area under a curve on a P-V diagram?  

text[[115, 162, 390, 181]]
ANSWER: WORK [Thermo, ND]  

sub_title[[462, 198, 533, 216]]
## BONUS  

text[[115, 233, 844, 270]]
7) Physics – Multiple Choice [5] Which of the following substances has the largest average distance between molecules at room temperature?  

text[[115, 286, 233, 355]]
W) Aluminum X) Glass Y) Water Z) Neon  

text[[115, 372, 390, 391]]
ANSWER: Z) NEON [Misc, GW]  

sub_title[[456, 442, 541, 460]]
## TOSS-UP  

text[[115, 477, 872, 514]]
8) Biology – Short Answer [5] What functional unit of the kidney controls the concentration of soluble substrates in urine via absorption and secretion?  

text[[115, 530, 400, 549]]
ANSWER: NEPHRON [Renal, DJ]  

sub_title[[462, 565, 533, 583]]
## BONUS  

text[[112, 600, 867, 620]]
8) Biology – Multiple Choice [5] Blood is classified as which of the following types of tissue?  

text[[115, 636, 238, 706]]
W) Connective X) Epithelial Y) Muscular Z) Nervous  

text[[115, 722, 516, 741]]
ANSWER: W) CONNECTIVE [Connective, GW]sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[113, 127, 833, 147]]
9) Earth and Space – Multiple Choice [5] Which of the following minerals is an iron ore?  

text[[114, 164, 222, 234]]
W) Dolomite 
X) Galena 
Y) Cinnabar 
Z) Hematite  

text[[114, 250, 477, 270]]
ANSWER: Z) HEMATITE [Mineralogy, SS]  

sub_title[[462, 285, 533, 304]]
## BONUS  

text[[114, 320, 848, 356]]
9) Earth and Space – Short Answer [5] A stellar object has a parallax angle measurement of 0.25 arcseconds. To the nearest integer, how far away, in light years, is the object?  

text[[115, 372, 387, 391]]
ANSWER: 13 [Astrophysics, BZ]  

sub_title[[456, 442, 540, 460]]
## TOSS-UP  

text[[115, 477, 771, 496]]
10) Math – Short Answer [5] How many digits does 10 to the 2020th power have?  

text[[115, 512, 427, 531]]
ANSWER: 2021 [Number Theory, SS]  

sub_title[[462, 547, 533, 565]]
## BONUS  

text[[115, 582, 869, 618]]
10) Math – Short Answer [5] If the magnitude of the complex number a + 5i is equal to 6, then what is the absolute value of a?  

text[[115, 634, 413, 653]]
ANSWER: ROOT 11 [Algebra, GW]sub_title[[456, 91, 541, 108]]
## TOSS-UP  

text[[115, 127, 879, 163]]
11) Chemistry – Short Answer [5] According to VSEPR theory, what is the molecular geometry of nitrogen dioxide?  

text[[116, 180, 377, 199]]
ANSWER: BENT [VSEPR, BZ]  

sub_title[[463, 216, 533, 234]]
## BONUS  

text[[115, 250, 820, 286]]
11) Chemistry – Multiple Choice [5] Which of the following statements most accurately describes the Aufbau principle?  

text[[115, 303, 705, 375]]
W) Electrons will occupy previously unoccupied orbitals before pairing up 
X) Electrons can not have the same set of quantum numbers 
Y) Electrons treat degenerate orbitals as the same 
Z) Electrons will occupy the lowest energy orbital as they are filled  

text[[115, 389, 874, 426]]
ANSWER: Z) ELECTRONS WILL OCCUPY THE LOWEST ENERGY ORBITAL AS THEY ARE FILLED [Orbitals, DJ]  

sub_title[[456, 477, 540, 495]]
## TOSS-UP  

text[[115, 511, 866, 565]]
12) Energy – Multiple Choice [5] Researchers at the University of Florida's Department of Astronomy are studying the diversity of planetary systems orbiting red dwarfs. To which of the following spectral classes do red dwarfs belong?  

text[[115, 582, 163, 650]]
W) O 
X) B 
Y) F 
Z) M  

text[[115, 668, 350, 687]]
ANSWER: Z) M [Other, BZ]  

sub_title[[463, 704, 533, 721]]
## BONUS  

text[[115, 739, 864, 792]]
12) Energy – Short Answer [5] Researchers in the Bartlett group at UF have studied the photoelectron spectrum of polyethylene. How many hydrogen atoms does a single molecule of ethylene have?  

text[[115, 809, 263, 827]]
ANSWER: 4 [BZ]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[114, 127, 877, 163]]
13) Physics – Multiple Choice [5] Which of the following pairs of particles will annihilate upon collision?  

text[[115, 181, 316, 250]]
W) Electron and positron 
X) Proton and neutron 
Y) Electron and photon 
Z) Photon and positron  

text[[115, 267, 625, 286]]
ANSWER: W) ELECTRON AND POSITRON [Quantum, GW]  

sub_title[[462, 303, 533, 321]]
## BONUS  

text[[115, 337, 874, 374]]
13) Physics – Short Answer [5] Identify all of the following three quantities that are considered thermodynamic state functions: 1) Work; 2) Heat; 3) Internal energy.  

text[[115, 389, 689, 408]]
ANSWER: 3 ONLY (ACCEPT: INTERNAL ENERGY) [Thermo, GW]  

sub_title[[456, 460, 541, 478]]
## TOSS-UP  

text[[115, 494, 850, 530]]
14) Biology – Short Answer [5] What form of genetic drift occurs when a new population is formed with a different gene pool from the original population?  

text[[115, 546, 510, 565]]
ANSWER: FOUNDER EFFECT [Genetics, GW]  

sub_title[[462, 582, 535, 600]]
## BONUS  

text[[115, 617, 857, 653]]
14) Biology – Multiple Choice [5] Which of the following structures would a photon passing through the eye reach last?  

text[[115, 670, 266, 740]]
W) Retina 
X) Lens 
Y) Cornea 
Z) Vitreous humor  

text[[115, 757, 507, 775]]
ANSWER: W) RETINA [Sense perception, GW]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 875, 164]]
15) Earth and Space - Short Answer [5] What process takes place when soluble particles in soil are washed out and redeposited in a lower layer, often stripping topsoil of nutrients?  

text[[115, 180, 754, 199]]
ANSWER: LEACHING (ALSO ACCEPT: ELUVIATION) [Other Geology, JS]  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 250, 821, 287]]
15) Earth and Space - Short Answer [5] Rank the following three metamorphic rocks by increasing metamorphic grade: 1) Gneiss [nice]; 2) Phyllite; 3) Slate.  

text[[115, 303, 734, 322]]
ANSWER: 3, 2, 1 (ACCEPT: SLATE, PHYLLITE, GNEISS) [Petrology, JS]  

sub_title[[456, 372, 541, 390]]
## TOSS-UP  

text[[115, 408, 816, 443]]
16) Math - Multiple Choice [5] Suppose two planes intersect in 3D space. Which of the following best describes the intersection of the two planes?  

text[[115, 460, 315, 531]]
W) A single point X) A single line Y) Two parallel lines Z) Two intersecting lines  

text[[115, 547, 515, 565]]
ANSWER: X) A SINGLE LINE [Geometry, GW]  

sub_title[[463, 582, 533, 600]]
## BONUS  

text[[115, 617, 844, 653]]
16) Math - Short Answer [5] 9 people go to a party. If each person shakes hands with every other person exactly once, how many handshakes will occur?  

text[[115, 670, 339, 688]]
ANSWER: 36 [Combo, SS]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 864, 181]]
17) Chemistry - Short Answer [5] Identify all of the following three species that appear in the equilibrium constant expression for the reaction of solid carbon and oxygen gas to form carbon dioxide gas: 1) C; 2) \(\mathrm{O}_2\) ; 3) \(\mathrm{CO}_2\) .  

text[[115, 197, 636, 216]]
ANSWER: 2 AND 3 (ACCEPT: \(\mathrm{O}_2\) AND \(\mathrm{CO}_2\) ) [Equilibrium, DJ]  

sub_title[[462, 233, 533, 251]]
## BONUS  

text[[115, 267, 852, 304]]
17) Chemistry - Multiple Choice [5] Which of the following species is NOT colorless when dissolved in water?  

text[[115, 321, 205, 391]]
W) NaCl 
X) KMnO4 
Y) ZnCl2 
Z) KBr  

text[[115, 408, 404, 427]]
ANSWER: X) KMnO4 [Trivia, BZ]  

sub_title[[456, 477, 541, 495]]
## TOSS-UP  

text[[115, 512, 843, 565]]
18) Energy - Multiple Choice [5] Researchers in the Colina research group at UF are using organic microporous materials for use in separating and storing small gases. Which of the following gases are they LEAST likely dealing with?  

text[[115, 582, 183, 652]]
W) \(\mathrm{H}_2\) X) \(\mathrm{N}_2\) Y) \(\mathrm{C}_3\mathrm{H}_8\) Z) \(\mathrm{O}_2\)  

text[[115, 669, 318, 688]]
ANSWER: Y) \(\mathrm{C}_3\mathrm{H}_8\) [BZ]  

sub_title[[462, 704, 533, 722]]
## BONUS  

text[[115, 740, 862, 792]]
18) Energy - Short Answer [5] Researchers at the University of Chicago are studying how complex protein structures with no purpose can accumulate over time in organisms. What term best describes a structure that has no functional purpose in an organism?  

text[[115, 809, 364, 827]]
ANSWER: VESTIGIAL [GW]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[114, 127, 860, 163]]
19) Physics – Multiple Choice [5] According to the second law of thermodynamics, which of the following quantities of the universe cannot decrease?  

text[[114, 181, 245, 252]]
W) Volume 
X) Enthalpy 
Y) Temperature 
Z) Entropy  

text[[114, 268, 447, 287]]
ANSWER: Z) ENTROPY [Thermo, GW]  

sub_title[[462, 303, 533, 320]]
## BONUS  

text[[115, 338, 876, 374]]
19) Physics – Short Answer [5] The position of a particle in terms of time, \(t\) , is described by the equation \(\mathbf{x}(t) = t^2 + 4t + 3\) . What is the change in position of the particle from \(t = 1\) to \(t = 2\) ?  

text[[115, 390, 327, 409]]
ANSWER: 7 [Mech, GW]  

sub_title[[456, 460, 541, 478]]
## TOSS-UP  

text[[113, 494, 855, 530]]
20) Biology – Short Answer [5] What process do neutrophils and macrophages use to engulf and digest large particles such as microbes?  

text[[115, 546, 792, 565]]
ANSWER: PHAGOCYTOSIS (DO NOT ACCEPT: ENDOCYTOSIS) [Immune, DJ]  

sub_title[[462, 582, 533, 600]]
## BONUS  

text[[113, 617, 850, 653]]
20) Biology – Multiple Choice [5] Which of the following is NOT a primary function of the kidneys?  

text[[114, 670, 371, 740]]
W) Production of vitamin D 
X) Filtration of blood 
Y) Regulation of blood pressure 
Z) Storage of glycogen  

text[[114, 756, 563, 775]]
ANSWER: Z) STORAGE OF GLYCOGEN [Renal, DJ]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 126, 853, 164]]
21) Earth and Space – Short Answer [5] What pulsating stars, which can be used as standard candles, have a larger period and luminosity than the related RR Lyrae variables?  

text[[115, 180, 603, 199]]
ANSWER: CEPHEID VARIABLES [Stellar Astronomy, SS]  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 250, 866, 286]]
21) Earth and Space – Short Answer [5] Dolomite's chemical formula is different from calcite because dolomite also contains what element that is not found in calcite?  

text[[115, 303, 476, 321]]
ANSWER: MAGNESIUM [Mineralogy, BZ]  

sub_title[[456, 372, 541, 390]]
## TOSS-UP  

text[[115, 407, 870, 444]]
22) Math – Short Answer [5] A point has the coordinates (5, 3). It is reflected across the y-axis and translated 2 units up. What are the coordinates of the new point?  

text[[115, 460, 377, 479]]
ANSWER: (- 5, 5) [Algebra, SS]  

sub_title[[463, 495, 533, 513]]
## BONUS  

text[[115, 530, 879, 566]]
22) Math – Short Answer [5] A standard die is rolled twice. What is the probability that the sum of the two rolls equals 7?  

text[[115, 583, 344, 601]]
ANSWER: 1/6 [Combo, SS]sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[113, 127, 872, 163]]
23) Chemistry – Multiple Choice [5] Which of the following gas laws is not represented in the combined gas law?  

text[[115, 181, 280, 250]]
W) Boyle's law  X) Gay Lussac's law  Y) Henry's law  Z) Charles's law  

text[[115, 268, 485, 286]]
ANSWER: Y) HENRY'S LAW [Thermo, DJ]  

sub_title[[463, 303, 533, 320]]
## BONUS  

text[[115, 338, 841, 390]]
23) Chemistry – Multiple Choice [5] When carbon tetrachloride and water are mixed together, a layer of water forms over a layer of carbon tetrachloride. Which of the following occurs when iodine crystals are dissolved in this mixture?  

text[[115, 408, 671, 477]]
W) Iodine dissolves in water because iodine is polar  X) Iodine dissolves in water because iodine is non-polar  Y) Iodine dissolves in carbon tetrachloride because iodine is polar  Z) Iodine dissolves in carbon tetrachloride because iodine is non-polar  

text[[115, 494, 880, 529]]
ANSWER: Z) IODINE DISSOLVES IN CARBON TETRACHLORIDE BECAUSE IODINE IS NON- POLAR [IMF, ND]