sub_title[[456, 144, 541, 162]]
## TOSS-UP  

text[[115, 179, 860, 233]]
1) Physics – Short Answer [2] Two charged particles are separated by a distance d and experience an electrostatic force F. If the two particles are moved to a new separation of 3d, in terms of F, what is the new electrostatic force between the two particles?  

text[[116, 249, 343, 268]]
ANSWER: F/9 [E&M, GW]  

sub_title[[464, 285, 533, 303]]
## BONUS  

text[[115, 320, 820, 356]]
1) Physics – Short Answer [2] Order the following three particles by increasing mass: 1) Lithium nucleus; 2) Electron; 3) Proton.  

text[[112, 371, 872, 391]]
ANSWER: 2, 3, 1 (ACCEPT: ELECTRON, PROTON, LITHIUM NUCLEUS) [Quantum, GW]  

sub_title[[456, 443, 541, 461]]
## TOSS-UP  

text[[115, 478, 861, 513]]
2) Biology – Multiple Choice [2] Which of the following is NOT one of the three domains of life?  

text[[115, 531, 214, 600]]
W) Archaea X) Bacteria Y) Eukarya Z) Plantae  

text[[115, 616, 511, 636]]
ANSWER: Z) PLANTAE [Animal Diversity, DJ]  

sub_title[[464, 652, 533, 670]]
## BONUS  

text[[115, 687, 875, 723]]
2) Biology – Short Answer [2] What substance which is stored in the gallbladder, is essential to the digestion of lipids and fats due to its emulsifying properties?  

text[[115, 739, 575, 758]]
ANSWER: BILE (ACCEPT: GALL) [RSS, DIGESTIVE]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[114, 127, 861, 163]]
3) Earth and Space – Short Answer [2] What is the name of the process in which new oceanic crust forms between tectonic plates as a result of upwelling?  

text[[115, 180, 593, 199]]
ANSWER: SEAFLOOR SPREADING [Other Geology, SS]  

sub_title[[464, 215, 533, 233]]
## BONUS  

text[[115, 250, 867, 305]]
3) Earth and Space – Short Answer [2] List all of the following three star types that are correctly matched to their location on the Hertzsprung-Russell diagram: 1) Blue supergiant: top right; 2) Red giant: top left; 3) White dwarf: bottom right.  

text[[115, 320, 456, 339]]
ANSWER: NONE [Stellar Astronomy, JS]  

sub_title[[456, 390, 541, 408]]
## TOSS-UP  

text[[115, 424, 702, 444]]
4) Math – Multiple Choice [2] Which of the following numbers is prime?  

text[[115, 460, 177, 530]]
W) 905 X) 906 Y) 907 Z) 908  

text[[115, 547, 452, 566]]
ANSWER: Y) 907 [Number Theory, GW]  

sub_title[[464, 582, 533, 600]]
## BONUS  

text[[115, 617, 810, 652]]
4) Math – Short Answer [2] A circle has a radius of 6. What is the ratio of its area to its circumference?  

text[[115, 669, 510, 688]]
ANSWER: 3 TO 1 (ACCEPT: 3) [Geometry, SS]sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[113, 127, 794, 147]]
5) Chemistry – Multiple Choice [2] What type of bond is found in diatomic fluorine?  

text[[115, 163, 270, 233]]
W) Single bond  X) Double bond  Y) Triple bond  Z) Quadruple bond  

text[[115, 250, 448, 269]]
ANSWER: W) SINGLE BOND [BO, DJ]  

sub_title[[464, 285, 533, 303]]
## BONUS  

text[[115, 320, 839, 356]]
5) Chemistry – Short Answer [2] Rank the following three elements by increasing metallic character: 1) Oxygen; 2) Potassium; 3) Silicon.  

text[[115, 371, 829, 391]]
ANSWER: 1, 3, 2 (ACCEPT: OXYGEN, SILICON, POTASSIUM) [Periodic Trends, DJ]  

sub_title[[456, 442, 540, 460]]
## TOSS-UP  

text[[115, 477, 875, 530]]
6) Energy – Multiple Choice [2] Researchers at UW Madison are studying metal interactions with amide linkages in enzymes in order to develop new drug delivery methods. Amide linkages are most commonly found in what class of macromolecules?  

text[[115, 547, 258, 616]]
W) Proteins  X) Nucleic acids  Y) Carbohydrates  Z) Lipids  

text[[115, 633, 456, 652]]
ANSWER: W) PROTEINS [Biochem, DJ]  

sub_title[[464, 668, 533, 686]]
## BONUS  

text[[115, 704, 875, 756]]
6) Energy – Short Answer [2] Researchers at Johns Hopkins University are studying the application of certain substances in powering quantum computers in the future. What substances are they studying which are characterized by zero electric resistance?  

text[[115, 773, 510, 792]]
ANSWER: SUPERCONDUCTORS [E&M, GW]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 812, 164]]
7) Physics – Short Answer [2] What circuit element stores energy in an electric field by separating charge?  

text[[115, 180, 428, 199]]
ANSWER: CAPACITOR [E&M, GW]  

sub_title[[464, 215, 533, 233]]
## BONUS  

text[[115, 250, 879, 286]]
7) Physics – Short Answer [2] A particle travels in a circle of radius 5 meters and has a constant angular velocity of 6 radians per second. What is the centripetal acceleration of the particle?  

text[[115, 302, 650, 321]]
ANSWER: 180 METERS PER SECOND SQUARED [Mech, GW]  

sub_title[[456, 372, 541, 390]]
## TOSS-UP  

text[[115, 407, 875, 444]]
8) Biology – Short Answer [2] What protein, which contains a porphyrin ring coordinated to an iron atom, transports oxygen molecules in red blood cells?  

text[[115, 459, 457, 478]]
ANSWER: HEMOGLOBIN [Proteins, DJ]  

sub_title[[464, 494, 533, 512]]
## BONUS  

text[[112, 529, 848, 549]]
8) Biology – Multiple Choice [2] Which of the following processes do NOT occur in fungi?  

text[[115, 565, 275, 635]]
W) Catabolism X) Photosynthesis Y) DNA replication Z) Mitosis  

text[[115, 652, 527, 671]]
ANSWER: X) PHOTOSYNTHESIS [Fungus, GW]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[113, 127, 828, 163]]
9) Earth and Space – Short Answer [2] In what layer of the atmosphere is the ozone layer found?  

text[[115, 180, 510, 200]]
ANSWER: STRATOSPHERE [Meteorology, JS]  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 250, 870, 287]]
9) Earth and Space – Short Answer [2] The collision of black holes releases energy in the form of what type of waves, which travel at the speed of light?  

text[[115, 302, 595, 321]]
ANSWER: GRAVITATIONAL WAVES [Astrophysics, JS]  

sub_title[[456, 372, 541, 390]]
## TOSS-UP  

text[[115, 407, 837, 444]]
10) Math – Multiple Choice [2] The side length of a cube is doubled. By what factor is the volume of the cube multiplied by?  

text[[115, 460, 158, 531]]
W) 2 X) 4 Y) 6 Z) 8  

text[[115, 548, 383, 567]]
ANSWER: Z) 8 [Geometry, GW]  

sub_title[[463, 600, 533, 618]]
## BONUS  

text[[115, 634, 808, 655]]
10) Math – Short Answer [2] If \(\mathrm{f}(x) = 2x^{2}\) and \(\mathrm{g}(x) = x + 3\) , what is \(\mathrm{f}(\mathrm{g}(2))\) If of g of 2?  

text[[115, 670, 344, 689]]
ANSWER: 50 [Algebra, SS]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 805, 164]]
11) Chemistry – Multiple Choice [2] Which of the following elements has the highest electronegativity?  

text[[115, 181, 207, 250]]
W) Carbon 
X) Oxygen 
Y) Silicon 
Z) Sodium  

text[[115, 267, 495, 286]]
ANSWER: X) OXYGEN [Periodic Trends, DJ]  

sub_title[[463, 303, 533, 320]]
## BONUS  

text[[115, 338, 866, 374]]
11) Chemistry – Short Answer [2] How many electrons are in p orbitals for an oxygen atom in its ground state?  

text[[116, 390, 334, 409]]
ANSWER: 4 [Orbitals, DJ]  

sub_title[[456, 460, 540, 478]]
## TOSS-UP  

text[[115, 494, 840, 565]]
12) Energy – Short Answer [2] Researchers at UW Madison are studying the oxidation of organic compounds by inorganic oxidants by adding it dropwise into a solution. What is the laboratory procedure for the slow addition into the analyte to determine an unknown concentration of a solution with the use of a burette?  

text[[115, 581, 447, 600]]
ANSWER: TITRATION [Chemistry, DJ]  

sub_title[[463, 616, 533, 634]]
## BONUS  

text[[115, 652, 863, 722]]
12) Energy – Short Answer [2] Researchers at Iowa State University’s Department of Geological and Atmospheric Sciences are studying the process of exhumation, which allows ancient oceanic rock to reach the surface. The rock they are studying dates back to what period of the Mesozoic Era, which follows the Jurassic?  

text[[115, 738, 447, 757]]
ANSWER: CRETACEOUS [Other, RSS]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 880, 164]]
13) Physics – Short Answer [2] The momentum of a particle is plotted on the y-axis, and time is plotted on the x-axis. What quantity is represented by the slope of this graph?  

text[[115, 180, 589, 199]]
ANSWER: FORCE (ACCEPT: NET FORCE) [Mech, GW]  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 250, 861, 286]]
13) Physics – Short Answer [2] What is the name of a piece of glass that is often triangular in shape and is used to break up light into its different colors?  

text[[115, 302, 620, 321]]
ANSWER: PRISM (ACCEPT: OPTICAL PRISM) [Misc, GW]  

sub_title[[456, 372, 541, 390]]
## TOSS-UP  

text[[115, 407, 864, 444]]
14) Biology – Short Answer [2] In addition to the chloroplast, what organelle's membrane has an electron transport chain containing ubiquinone?  

text[[115, 459, 500, 479]]
ANSWER: MITOCHONDRIA [Organelles, DJ]  

sub_title[[463, 495, 533, 513]]
## BONUS  

text[[115, 530, 875, 567]]
14) Biology – Short Answer [2] After mitosis, order the following three phases of the cell cycle from earliest to latest: 1) S phase; 2) G1 phase; 3) G2 phase.  

text[[115, 583, 775, 602]]
ANSWER: 2, 1, 3 (ACCEPT: G1 PHASE, S PHASE, G2 PHASE) [Cell cycle, DJ]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 872, 164]]
15) Earth and Space – Short Answer [2] The Mid-Atlantic Ridge, the East Pacific Rise, and the East African Rift are all examples of what type of plate boundary?  

text[[115, 180, 485, 199]]
ANSWER: DIVERGENT [Other Geology, JS]  

sub_title[[462, 215, 533, 233]]
## BONUS  

text[[115, 250, 837, 286]]
15) Earth and Space – Multiple Choice [2] Which of the following statements is NOT true about black holes?  

text[[115, 304, 713, 374]]
W) Black holes cannot be binary partners with stars  X) The event horizon marks the boundary of a black hole  Y) Black holes are at the center of most large galaxies  Z) Black holes form from stars with cores of greater than three solar masses  

text[[115, 389, 863, 427]]
ANSWER: W) BLACK HOLES CANNOT BE BINARY PARTNERS WITH STARS [Stellar Astronomy, JS]  

sub_title[[456, 477, 540, 495]]
## TOSS-UP  

text[[115, 512, 870, 548]]
16) Math – Multiple Choice [2] Which of the following points is exactly 5 units away from the line \(x = 3\) ?  

text[[115, 565, 211, 636]]
W) (-2, -8)  X) (1, 8)  Y) (0, 4)  Z) (3, 4)  

text[[115, 651, 428, 670]]
ANSWER: W) (- 2, - 8) [Algebra, GW]  

sub_title[[462, 686, 533, 704]]
## BONUS  

text[[115, 722, 850, 757]]
16) Math – Short Answer [2] Two prime numbers sum to 15. What is the product of the two numbers?  

text[[115, 774, 417, 793]]
ANSWER: 26 [Number Theory, GW]  

text[[115, 898, 870, 933]]
17) Chemistry – Short Answer [2] What acid has formula \(\mathrm{CH}_3\mathrm{COOH}\) and is the conjugate acid of acetate?  

text[[115, 944, 188, 960]]
MOSFETsub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 144, 670, 163]]
ANSWER: ACETIC ACID (ACCEPT: ETHANOIC ACID) [AB, BZ]  

sub_title[[463, 180, 533, 199]]
## BONUS  

text[[115, 215, 837, 252]]
17) Chemistry – Short Answer [2] Rank the following three bonds by increasing length: 1) Carbon-carbon single bond; 2) Carbon-carbon triple bond; 3) Carbon-carbon double bond  

text[[116, 268, 337, 286]]
ANSWER: 2, 3, 1 [BO, DJ]  

sub_title[[456, 337, 540, 355]]
## TOSS-UP  

text[[115, 371, 861, 426]]
18) Energy – Short Answer [2] Researchers at UW Madison are studying how to manufacture better and more efficient photovoltaic cells. Photovoltaic cells are used in what type of renewable energy generation?  

text[[116, 442, 375, 460]]
ANSWER: SOLAR [Misc, GW]  

sub_title[[463, 477, 533, 495]]
## BONUS  

text[[115, 512, 825, 566]]
18) Energy – Multiple Choice [2] Researchers at UW Madison are currently studying the applications of photoredox chemical reactions in order to engage otherwise inert chemical groups. Which of the following statements is TRUE about redox reactions?  

text[[115, 583, 541, 655]]
W) A species that loses electrons undergoes oxidation  X) A species that loses electrons undergoes reduction  Y) A species that loses protons undergoes oxidation  Z) A species that loses protons undergoes reduction  

text[[115, 670, 815, 707]]
ANSWER: W) A SPECIES THAT LOSES ELECTRONS UNDERGOES OXIDATION [Chemistry, DJ]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 856, 163]]
19) Physics – Short Answer [2] What is the name for the type of collision where total kinetic energy is completely conserved?  

text[[115, 180, 867, 216]]
ANSWER: ELASTIC COLLISION (ACCEPT: PERFECTLY ELASTIC COLLISION) [Mech, GW]  

sub_title[[462, 233, 533, 251]]
## BONUS  

text[[115, 267, 878, 338]]
19) Physics – Short Answer [2] A parallel plate capacitor with capacitance C consists of two square plates, each with a surface area of 16 square centimeters, separated by 1 millimeter. If the surface area of each plate is increased to 48 square centimeters, then what is the new capacitance of the capacitor?  

text[[115, 355, 339, 373]]
ANSWER: 3C [E&M, GW]  

sub_title[[456, 425, 540, 443]]
## TOSS-UP  

text[[115, 460, 785, 495]]
20) Biology – Short Answer [2] What cells, which are composed of an axon, are the fundamental units of the brain?  

text[[115, 511, 757, 531]]
ANSWER: NEURONS (ACCEPT: NERVE CELLS; NEURONE) [Nervous, DJ]  

sub_title[[462, 547, 533, 565]]
## BONUS  

text[[115, 582, 697, 601]]
20) Biology – Short Answer [2] ATP is a derivative of what nucleobase?  

text[[115, 618, 744, 636]]
ANSWER: ADENINE (DO NOT ACCEPT: ADENOSINE) [ELEMENTS, DJ]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[113, 127, 875, 163]]
21) Earth and Space – Multiple Choice [2] Which of the following statements regarding stars is true?  

text[[115, 181, 680, 198]]
W) Most of a sun-like star's lifetime is spent fusing hydrogen to helium  

text[[115, 199, 590, 216]]
X) Red stars generally have the hottest surface temperatures  

text[[115, 217, 552, 234]]
Y) Stars of high mass tend to have the longest lifetimes  

text[[115, 234, 621, 251]]
Z) Stars of one solar mass will eventually become a neutron star  

text[[115, 267, 770, 304]]
ANSWER: W) MOST OF A SUN- LIKE STAR'S LIFETIME IS SPENT FUSING HYDROGEN TO HELIUM [Stellar Astronomy, JS]  

sub_title[[463, 320, 533, 338]]
## BONUS  

text[[115, 354, 870, 391]]
21) Earth and Space – Short Answer [2] What term is used to describe large early solar system bodies that collided and combined to create protoplanets?  

text[[115, 407, 525, 426]]
ANSWER: PLANETESIMALS [Solar System, JS]  

sub_title[[456, 477, 540, 495]]
## TOSS-UP  

text[[115, 512, 840, 548]]
22) Math – Short Answer [2] A triangle has a 50 degree and a 60 degree angle. What is the degree measure of the third angle?  

text[[115, 564, 370, 583]]
ANSWER: 70 [Geometry, GW]  

sub_title[[463, 599, 533, 617]]
## BONUS  

text[[115, 634, 850, 671]]
22) Math – Short Answer [2] Solve the following system of equations for \(x\) and \(y\) : \(9x - y = 2\) and \(-2x + y = 5\) .  

text[[115, 687, 643, 707]]
ANSWER: \(x = 1\) AND \(y = 7\) (ACCEPT: 1 AND 7) [Algebra, GW]  

text[[112, 899, 867, 919]]
23) Chemistry – Multiple Choice [2] Which of the following atomic subshells fits 2 electrons?sub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[114, 128, 166, 198]]
W) 4s 
X) 2p 
Y) 3d 
Z) 5f  

text[[115, 215, 371, 233]]
ANSWER: W) 4s [Orbitals, DJ]  

sub_title[[463, 250, 533, 268]]
## BONUS  

text[[114, 284, 871, 339]]
23) Chemistry – Multiple Choice [2] A photon is emitted from an electron falling from one energy level to another. Which of the following pairs of energy levels would emit a photon with the highest frequency?  

text[[114, 355, 255, 425]]
W) \(\mathrm{n} = 5\) to \(\mathrm{n} = 3\) X) \(\mathrm{n} = 5\) to \(\mathrm{n} = 2\) Y) \(\mathrm{n} = 4\) to \(\mathrm{n} = 2\) Z) \(\mathrm{n} = 4\) to \(\mathrm{n} = 1\)  

text[[115, 444, 360, 462]]
ANSWER: Z) \(\mathrm{N} = 4\) TO \(\mathrm{N} = 1\)