
## Things to mention  


Things to mention- Four questions for all categories except for energy- Difficulty is, regs, regs, nats RR, nats DE- There's superpower, which is 4 points, power which is 3 points in all questions. If you get it after power then you get 2 points.- In order to prevent blind guessing for multiple choice, there is a 1 point penalty for incorrect responses for multiple choice.- There is no penalty for incorrect responses on short answers.- You do not have to buzz on a question if you do not want to, particularly you don't need to buzz on multiple choice.- You have 7 seconds to answer.- Buzz in dms
## TOSS-UP  


Biology [3] - Multiple Choice Intermediate filaments are cytoskeletal structural components\*\* composed of which of the following proteins?  


W) Actin\* 
X) Myosin 
Y) Tubulin 
Z) Keratin  


ANSWER: Z) KERATIN [SS]  


## TOSS-UP  


Biology [4] - Short Answer Many hormones directly stimulate target cells to induce effects. However,\*\* some hormones have other endocrine glands as their targets.\* What is the name given to these hormones?  


ANSWER: TROPIC HORMONES [SS]  


## TOSS-UP  


Biology [5] - Multiple Choice Which of the following best describes brassinosteroids' effect on root growth at low and high concentrations respectively?  


W) Low concentrations inhibit root growth, High concentrations\*\* promote root growth 
X) Low concentrations promote root growth, High concentrations inhibit root growth\* 
Y) Both low and high concentrations inhibit root growth 
Z) Both low and high concentrations promote root growth  


ANSWER: X) LOW CONCENTRATIONS PROMOTE ROOT GROWTH, HIGH CONCENTRATIONS INHIBIT ROOT GROWTH [SS]  


## TOSS-UP  


Biology [8] - Short Answer Hemoglobin can transition from its T- state to its R- state by the shifting of the position of what amino acid residue\*\*, to which the F- helix is\* attached?  


ANSWER: HISTIDINE (ACCEPT: HISTIDINE F8) []
## TOSS-UP  


Chemistry [1] - Short Answer Rank the following four hydrohalic acids in increasing acidity\\*\\*: 1) HF\\*; 2) HCl; 3) HBr; 4) HI.  


ANSWER: 1, 2, 3, 4 [SS]  


## TOSS-UP  


Chemistry [3] - Multiple Choice How many sigma and pi bonds, respectively, are found in one molecule of acetone?  


W) 5 sigma, 1 pi\\*\\* 
X) 7 sigma, 2 pi 
Y) 9 sigma, 1 pi\\* 
Z) 10 sigma, 1 pi  


ANSWER: Y) 9 SIGMA, 1 PI [SS]  


## TOSS-UP  


Chemistry [6] - Multiple Choice What is the absolute difference in the number of nodes in the HOMO of 1,3,5- Hexatriene and the number of nodes in the LUMO of 1,3- Butadiene?  


W) 0 \\*\\* 
X) 1 
Y) 2 
Z)\\* 3  


ANSWER: W) 0 [SS]  


## TOSS-UP  


Chemistry [9] - Multiple Choice The reaction of sodium borohydride with an alpha- beta unsaturated ketone, generally reduces both the carbonyl and the carbon- carbon double bond. The addition of which of the following compounds to the reaction vessel would force NaBH4 to attack only the carbonyl group?  


W) KHSO3\\*\\* 
X) CeCl3\\* 
Y) BeCl2 
Z) SnCl2  


ANSWER: X) CeCl3 [SS]
## TOSS-UP  


Earth and Space [1] - Multiple Choice Which of the following jovian planets has a retrograde\*\* rotation?  


W) Jupiter  X) Saturn  Y) Uranus\*  Z) Neptune  


ANSWER: Y) URANUS [SS]  


## TOSS-UP  


Earth and Space [2] - Short Answer Order the following three types of magma in increasing viscosity.\*\* 1) Basaltic; 2) Rhyolitic; \* 3) Andesitic.  


ANSWER: 1, 3, 2 [SS]  


## TOSS-UP  


Earth and Space [6] - Short Answer The removal of the lithospheric mantle from the base of a plate causes the isostatic rebound of the remaining surface\*\* of the plate. What term is given to\* this process by which the upper crust separates from the lower crust and lithospheric mantle?  


ANSWER: DELAMINATION [SS]  


## TOSS-UP  


Earth and Space [8] - Multiple Choice Spectra containing strong titanium oxide absorption bands are most prevalent among which of the following spectral classes?\*\*  


W) A  X) G  Y) M\*  Z) T  


ANSWER: Y) M [SS]
## TOSS-UP  


Math [1] – Short Answer Alice, Bob, Chris, and David are sitting around a circular table. How many\*\* different seating arrangements are possible for the 4 of them\* to sit around the table?  


ANSWER: 6 []  


## TOSS-UP  


Math[3] – Short Answer What is the sum of the roots of the polynomial \(4x^{3} - 6x^{2} + \ast \ast 9x + \ast\) 17?  


ANSWER: 3/2 (ACCEPT: 1.5) []  


## TOSS-UP  


Math [6] – Multiple Choice A circle is inscribed in a regular hexagon, and another circle is circumscribed about the same regular hexagon. What is the ratio of the area of the larger circle to\*\* the smaller circle?  


W) 2/sqrt(3) 
X) 4/3 
Y) 3/2\* 
Z) 2  


ANSWER: X) 4/3 []  


## TOSS-UP  


Math [8] – Multiple Choice Which of the following numbers can NOT be written as the sum of 3 perfect squares?  


W) 2021\*\* 
X) 2022 
Y) 2023\* 
Z) 2024  


ANSWER: Y) 2023 []
## TOSS-UP  


Physics [3] - Multiple Choice Which of the following subatomic particles is the most penetrating?  


W) Neutrino \*\*  
X) Electron  
Y) Proton \*  
Z) Neutron  


ANSWER: W) Neutrino []  


## TOSS-UP  


Physics [2] - Multiple Choice At which of the following launch angles, in degrees, should a projectile be launched from ground level to maximize its \*\* range?  


W) 15  
X) 30 \*  
Y) 45  
Z) 60  


ANSWER: Y) 45 []  


## TOSS-UP  


Physics [6] - Short Answer If the charge of a non- relativistic point charge triples and its acceleration doubles, then\*\* by what factor does its emitted\* power increase?  


ANSWER: 36 []  


## TOSS-UP  


Physics [8] - Multiple Choice In CGS- EMU units, the vacuum permeability is defined to be unitless. In this system, what are the units of inductance? \*\*  


W) unitless  
X) cm  
Y) \(\mathrm{cm}^2\) \*  
Z) \(\mathrm{cm}^3\)  


ANSWER: X) cm []