sub_title[[456, 88, 541, 107]]
## TOSS-UP  

text[[115, 123, 833, 160]]
1) Physics – Short Answer According to the continuity equation, the divergence of what quantity must always equal 0 for an incompressible fluid?  

text[[115, 175, 833, 213]]
ANSWER: VELOCITY (ACCEPT: FLOW VELOCITY; ACCEPT u; DO NOT ACCEPT: SPEED) [GW, Fluids]  

sub_title[[462, 230, 533, 248]]
## BONUS  

text[[115, 264, 860, 318]]
1) Physics – Short Answer A refrigerator operating at theoretical maximum efficiency has a coefficient of performance of 6.5. The temperature outside of the refrigerator is \(27^{\circ}\) celsius. In Celsius, what is the difference between the temperature outside and inside the refrigerator?  

text[[116, 334, 353, 353]]
ANSWER: 40 [GW, Thermo]  

sub_title[[456, 370, 541, 388]]
## TOSS-UP  

text[[115, 404, 875, 441]]
2) Biology [DE] – Short Answer What is the DNA repair mechanism that CRISPR gene editing requires to insert synthetic genes, which is contrasted with non-homologous end joining?  

text[[115, 456, 696, 476]]
ANSWER: HOMOLOGY DIRECTED REPAIR (HDR) [SL, BIOTECH]  

sub_title[[462, 493, 533, 511]]
## BONUS  

text[[112, 527, 866, 547]]
2) Biology – Multiple Choice What organ in spiders functions to remove nitrogenous wastes?  

text[[115, 563, 295, 635]]
W) Protonephridia 
X) Metanephridia 
Y) Malpighian tubules 
Z) Book lungs  

text[[115, 651, 572, 671]]
ANSWER: Y) MALPIGHIAN TUBULES [JH, WASTE]  

sub_title[[456, 687, 541, 706]]
## TOSS-UP  

text[[115, 722, 850, 759]]
3) Math – Short Answer A triangle ABC has side lengths of \(\mathrm{AB} = 6\) , \(\mathrm{BC} = 9\) , and \(\mathrm{CA} = 10\) . The angle bisector of angle ABC intersects side CA at point X. What is the length of AX?  

text[[115, 774, 425, 794]]
ANSWER: 4 [LY, spread those sheets]  

sub_title[[462, 810, 533, 828]]
## BONUS  

text[[112, 844, 824, 864]]
3) Math – Short Answer Given that 2027 is a prime, compute 2023 factorial mod 2027.  

text[[115, 879, 340, 898]]
ANSWER: 338 [LY, MOD]sub_title[[455, 124, 541, 142]]
## TOSS-UP  

text[[113, 159, 877, 196]]
4) Earth and Space – Short Answer What class of binary star systems have an inclination close to 90 degrees and can be detected by a periodic variation in the light curve of the system?  

text[[115, 211, 819, 248]]
ANSWER: PHOTOMETRIC BINARY (ACCEPT: ECLIPSING BINARY; ECLIPSING VARIABLES) [JH, 9]  

sub_title[[462, 265, 533, 283]]
## BONUS  

text[[115, 300, 852, 336]]
4) Earth and Space – Short Answer A cyclostrophic flow is the balance between which two forces?  

text[[115, 352, 725, 371]]
ANSWER: PRESSURE GRADIENT AND CENTRIFUGAL [JY, soft as air]  

sub_title[[455, 388, 541, 406]]
## TOSS-UP  

text[[115, 423, 867, 459]]
5) Chemistry – Short Answer Identify all of the following 3 spectroscopic techniques that are capable of detecting nitric oxide: 1) NMR; 2) EPR; 3) IR.  

text[[116, 476, 336, 494]]
ANSWER: ALL [BZ, spec]  

sub_title[[462, 511, 533, 530]]
## BONUS  

text[[115, 546, 874, 599]]
5) Chemistry – Short Answer Identify all of the following 3 dienes that would prefer the exo product when undergoing a Diels-Alder reaction: 1) 1,3-butadiene; 2) 1-methoxy-1,3-butadiene; 3) Furan.  

text[[116, 616, 368, 635]]
ANSWER: 3 ONLY [BZ, orgo]  

sub_title[[455, 652, 541, 670]]
## TOSS-UP  

text[[115, 686, 857, 757]]
6) Energy – Multiple Choice Researchers at Lawrence Berkeley National Lab are studying various oxidation methods on alcohols for the development of certain drugs. Which of the following alcohol oxidative reagents would you most likely expect to have a signal in EPR spectroscopy?  

text[[115, 774, 208, 844]]
W) TPAP 
X) PCC 
Y) MDSO 
Z) TEMPO  

text[[115, 862, 716, 881]]
ANSWER: Z) TEMPO (ACCEPT: W) [DJ, NOT SUPER CRINGE ORGO]image[[120, 88, 999, 545]]  

text[[113, 546, 864, 584]]
6) Energy – Short Answer Researchers make circuit stuff. Answer the following 2 questions regarding the image shown:  

text[[170, 600, 820, 637]]
I) What logic gate is shown circled and labeled A? II) What binary input for 1 and 2 would result in the output 0 from both Q and Q'.  

text[[115, 652, 704, 672]]
ANSWER: I) NOR GATE; II) 1 AND 1 [DJ, MINECRAFT REDSTONE]  

sub_title[[455, 688, 541, 707]]
## TOSS-UP  

text[[115, 723, 864, 760]]
7) Physics – Multiple Choice A Van De Graaff generator has a very high value for which of the following quantities?  

text[[115, 777, 205, 850]]
W) Charge 
X) Current 
Y) Power 
Z) Voltage  

text[[115, 865, 327, 884]]
ANSWER: Z) VOLTAGEsub_title[[462, 90, 533, 108]]
## BONUS  

text[[115, 123, 825, 179]]
7) Physics – Short Answer Identify all of the following three quantities that are directly proportional to the magnetization of a paramagnetic material: 1) Relative permeability; 2) Magnetic Susceptibility; 3) Applied B field.  

text[[115, 194, 768, 231]]
ANSWER: 2 ONLY (Note: magnetization is proportional to applied H field) [GW, Electromagnetism]  

sub_title[[455, 247, 541, 265]]
## TOSS-UP  

text[[115, 281, 879, 336]]
8) Biology [DE] – Short Answer Rank the following four types of cells by increasing potency: 1) Mouse morula cell; 2) Mouse cheek cell; 3) Mouse cheek cell grown with Yamanaka factors over two months; 4) Mouse hematopoietic stem cell.  

text[[115, 352, 381, 371]]
ANSWER: 2, 4, 3, 1 [JH, STEM]  

sub_title[[413, 387, 583, 406]]
## VISHWAL BONUS  

text[[114, 421, 875, 512]]
8) Biology – Short Answer. Shown is an image of a Vish Fish. Answer the following two questions about the Vish Fish: 1) What is the term for the tissue that covers and protects the gills of the Vish Vish? 2) The lateral line system present on the Vish Fish is known to be either a predecessor or a homolog of what set of electroreceptors found in cartilaginous fish and basal bony fishes?  

image[[145, 536, 850, 800]]  

text[[114, 849, 877, 886]]
ANSWER: 1) OPERCULUM; 2) AMPULLAE OF LORENZINI (ACCEPT: AMPULLAE) [JH, VISH]sub_title[[456, 107, 541, 125]]
## TOSS-UP  

text[[113, 141, 853, 178]]
9) Math – Multiple Choice Which of the following series has a partial sum that is a Cauchy sequence?  

text[[115, 195, 422, 267]]
W) a sub n equals 1 
X) a sub n equals n 
Y) a sub n equals quantity (-1) to the n 
Z) a sub n equals 1 over n squared  

text[[115, 283, 690, 302]]
ANSWER: Z) A SUB N EQUALS 1 OVER N SQUARED [LY, calc bc]  

sub_title[[462, 318, 535, 336]]
## BONUS  

text[[115, 352, 857, 389]]
9) Math – Short Answer Alice rolls 3 dice in succession and notices that each roll is strictly greater than the last. What is the expected value of her first roll?  

text[[115, 404, 480, 423]]
ANSWER: 7/4 (ACCEPT: 1.75) [LY, PROB]  

sub_title[[456, 439, 541, 458]]
## TOSS-UP  

text[[115, 475, 825, 511]]
10) Earth and Space – Multiple Choice Which of the following would have the smallest Rossby number?  

text[[115, 529, 333, 599]]
W) A tornado 
X) North equatorial current 
Y) Tropical easterly jet 
Z) North Atlantic drift  

text[[115, 616, 591, 635]]
ANSWER: Z) NORTH ATLANTIC DRIFT [JY, soft as air]  

sub_title[[462, 651, 535, 670]]
## BONUS  

text[[115, 686, 844, 740]]
10) Earth and Space – Short Answer. The image shows the M-sigma relation, an empirical correlation between the value of sigma for a galactic bulge and the mass of the supermassive black hole at its center. Answer the following two questions about the image:  

text[[172, 756, 842, 828]]
I) What quantity is represented by sigma, which is usually calculated after repeatedly measuring Doppler shifts for different objects in the galactic bulge? II) What similar empirical law exists between the value of sigma and the mass of an elliptical galaxy?image[[163, 118, 838, 625]]  

text[[114, 658, 830, 695]]
ANSWER: 1) VELOCITY DISPERSION (DO NOT ACCEPT: VELOCITY); 2) FABER- JACKSON LAW [JH, 18]  

sub_title[[455, 711, 541, 730]]
## TOSS-UP  

text[[114, 746, 866, 783]]
11) Chemistry – Short Answer What is the primary decay mode undergone by the oxygen-19 nuclide?  

text[[114, 799, 443, 818]]
ANSWER: BETA-MINUS [BZ, nuclear]  

text[[462, 835, 533, 852]]
BONUStext[[115, 89, 844, 141]]
11) Chemistry – Short Answer In the second order reaction E yields F, the initial rate of reaction is 10 molar per second and the initial concentration of E is 2 molar. What is the first half-life of the reaction in seconds?  

text[[115, 159, 348, 177]]
ANSWER: 0.2 [BZ, kinetics]