sub_title[[456, 90, 541, 107]]
## TOSS-UP  

text[[114, 123, 877, 194]]
1) Physics – Multiple Choice Spherical sound waves are emitted uniformly in all directions from a point source, such that the sound level a distance 1 meter away from the source is 100 decibels. In decibels, which of the following is closest to the sound level 2 meters away from the source?  

text[[114, 212, 168, 282]]
W) 90 X) 92 Y) 94 Z) 96  

text[[114, 300, 468, 319]]
ANSWER: Y) 94 [SS, LOG(2) STOCK 1/1]  

sub_title[[463, 336, 533, 354]]
## BONUS  

text[[114, 370, 880, 424]]
1) Physics [] – Short Answer A 12-volt battery with internal resistance of 2 ohms is connected to a variable resistor with resistance \(x\) . For what value of \(x\) will the variable resistor dissipate the maximum amount of power?  

text[[114, 440, 465, 459]]
ANSWER: 2 OHMS [GW, Harder Circuits]  

sub_title[[456, 476, 541, 494]]
## TOSS-UP  

text[[114, 510, 794, 547]]
2) Biology [RR] – Short Answer Identify all of the following 3 molecules that are considered neuropeptides: 1) Norepinephrine; 2) Substance P; 3) GABA.  

text[[115, 563, 379, 581]]
ANSWER: 2 ONLY [DJ, Neuro]  

sub_title[[463, 599, 533, 617]]
## BONUS  

text[[114, 634, 866, 670]]
2) Biology – Short Answer Order the following three layers of a eudicot root from outermost to innermost: 1) Epidermis; 2) Pericycle; 3) Cortex.  

text[[115, 686, 390, 705]]
ANSWER: 1, 3, 2 [SF, STOLEN]  

sub_title[[456, 722, 541, 740]]
## TOSS-UP  

text[[114, 757, 876, 793]]
3) Math – Short Answer What is the average value of the derivative of the function \(f(x) = \text{cube}\) root of \(x\) with respect to \(x\) from \(x = 8\) to \(x = 216\) ?  

text[[114, 810, 500, 829]]
ANSWER: 1/52 [LY, cringe regs stolen content]  

sub_title[[463, 846, 533, 863]]
## BONUStext[[113, 89, 797, 125]]
3) Math – Short Answer What is the area of the region enclosed by the curve \(r = 3 + 2\cos (\text{theta})\) ?  

text[[115, 142, 331, 161]]
ANSWER: 11 PI [LY, ass]  

sub_title[[456, 195, 541, 213]]
## TOSS-UP  

text[[113, 230, 853, 266]]
4) Earth and Space [] – Short Answer Rank the following 4 planets by increasing magnetic field strength: 1) Earth; 2) Mars; 3) Jupiter; 4) Saturn.  

text[[115, 282, 535, 301]]
ANSWER: 2, 1, 4, 3 [GW, Inner Planets/Gas Giants]  

sub_title[[463, 318, 533, 336]]
## BONUS  

text[[113, 352, 879, 388]]
4) Earth and Space – Short Answer What type of fog forms when warm, moist air flows over a cold surface?  

text[[115, 405, 370, 424]]
ANSWER: ADJECTION FOG  

sub_title[[456, 441, 541, 459]]
## TOSS-UP  

text[[113, 475, 844, 512]]
5) Chemistry – Short Answer Rank the following 3 species in order of increasing standard reduction potential: 1) Li⁺; 2) Mg²⁺; 3) Fe²⁺.  

text[[115, 528, 355, 547]]
ANSWER: 1, 2, 3 [BZ, lolrip]  

sub_title[[463, 564, 533, 582]]
## BONUS  

text[[113, 599, 863, 635]]
5) Chemistry – Multiple Choice How many net pi bonds are formed in the electroclyclization of 1, 3, 5 hexatriene?  

text[[113, 652, 163, 722]]
W)- 2 X)- 1 Y) 0 Z) 1  

text[[115, 740, 368, 759]]
ANSWER: X)- 1 [SS/BZ, orgo]  

sub_title[[456, 794, 541, 812]]
## TOSS-UP  

text[[115, 828, 864, 900]]
6) Energy – Multiple Choice Researchers at Pacific Northwest National Lab are interested in increasing the purity of crystalline samples. In particular, they are interested in reducing the likelihood of an atom vacating its place in the lattice in order to occupy a normally empty spot. Which of the following types of defects are they most interested in mitigating?text[[114, 108, 270, 179]]
W) Schottky defect 
X) Frenkel defect 
Y) Disclination 
Z) Stacking fault  

text[[115, 195, 549, 214]]
ANSWER: X) FRENKEL DEFECT [LY, cringe meta]  

sub_title[[463, 230, 533, 249]]
## BONUS  

text[[115, 265, 870, 319]]
6) Energy – ShorT ANSWER Researchers at Oak Ridge National Lab are using spallation to study the scattering of certain types of particles. Identify all of the following 3 particles they are likely studying: 1) photon; 2) neutron; 3) proton.  

text[[115, 336, 279, 354]]
ANSWER: 2 ONLY  

sub_title[[456, 389, 540, 407]]
## TOSS-UP  

text[[115, 423, 832, 460]]
7) Physics [5] – Short Answer What kind of orbital maneuver allows a rocket to move between two circular orbits by placing it in an intermediary elliptical orbit tangent to both?  

text[[115, 476, 790, 513]]
ANSWER: HOHMANN TRANSFER ORBIT (ACCEPT: HOHMANN TRANSFER, HOHMANN) [GW, Stock]  

sub_title[[463, 530, 533, 548]]
## BONUS  

text[[115, 564, 865, 635]]
7) Physics – Short Answer A barbell consists of a massless rod with length 1 meter, and two uniform disks of radii 0.5 meters and masses of 16 kilograms each, attached at either end of the rod. In kilogram meters squared, what is the value of the moment of inertia of the barbell about an axis perpendicular to the rod, passing through the center of the barbell?  

text[[115, 651, 430, 670]]
ANSWER: 10 [PAT DEEZ NUTS, SS]  

sub_title[[456, 705, 540, 723]]
## TOSS-UP  

text[[112, 739, 857, 759]]
8) Biology [] – Multiple Choice Which of the following is NOT true regarding fibronectin?  

text[[115, 776, 634, 848]]
W) Fibronectin is a trimeric protein. 
X) Cells are attached to the extracellular matrix using fibronectin. 
Y) Fibronectin is produced from a single gene. 
Z) Fibronectin is secreted by fibroblasts.  

text[[115, 864, 760, 883]]
ANSWER: W) FIBRONECTIN IS A TRIMERIC PROTEIN [DJ, MEMBRANE]sub_title[[463, 90, 533, 108]]
## BONUS  

text[[113, 123, 877, 161]]
8) Biology [] - Short Answer Identify all of the following 3 antibodies commonly used in the human bodies passive immunity: 1) IgA; 2) IgE; 3) IgG  

text[[115, 177, 392, 196]]
ANSWER: 1, 3 [DJ, IMMUNITY]  

sub_title[[456, 230, 541, 248]]
## TOSS-UP  

text[[115, 264, 856, 318]]
9) Math - Short Answer Identify all of the following 3 statements that are true about cyclic quadrilaterals: 1) They must be convex; 2) They must have two equal internal angles; 3) They must have two equal sides.  

text[[115, 334, 447, 354]]
ANSWER: 1 ONLY [LY, you guys suck]  

sub_title[[463, 370, 533, 388]]
## BONUS  

text[[115, 404, 861, 457]]
9) Math - Short Answer Ken has two yellow nuts and two brown nuts. Every second, he can either eat one yellow nut, one brown nut, or one of each. How many ways can he eat all of his nuts?  

text[[112, 473, 785, 494]]
ANSWER: 13 [LY/SS, KEN YA FIT DEEZ NUTS IN YA MOUTH LMAOOOOO]  

sub_title[[456, 528, 541, 546]]
## TOSS-UP  

text[[115, 562, 853, 599]]
10) Earth and Space - Multiple Choice Which of the following is not a measurement of the moment-magnitude scale?  

text[[115, 616, 368, 688]]
W) S-wave amplitude 
X) Strength of faulted-rock 
Y) Area of slipped fault surface 
Z) Hanging-wall slip  

text[[115, 704, 436, 722]]
ANSWER: W) S-WAVE AMPLITUDE  

sub_title[[463, 740, 533, 757]]
## BONUS  

text[[115, 774, 866, 810]]
10) Earth and Space [] - Short Answer After a low solar mass star leaves the main sequence, it becomes part of what branch on the HR diagram before it undergoes a helium flash?  

text[[115, 826, 707, 845]]
ANSWER: RED GIANT BRANCH [ACCEPT: RGB] [GW, HR Diagram]  

sub_title[[456, 862, 541, 879]]
## TOSS-UPtext[[115, 90, 839, 125]]
11) Chemistry – Multiple Choice Which of the following chemical bonds has the greatest electronegativity difference?  

text[[115, 142, 291, 213]]
W) Carbon - Oxygen 
X) Carbon - Sulfur 
Y) Carbon - Selenium 
Z) Carbon - Tellurium  

text[[115, 230, 522, 249]]
ANSWER: W) CARBON - OXYGEN [BZ, bonds]  

sub_title[[463, 266, 533, 284]]
## BONUS  

text[[115, 301, 830, 337]]
11) Chemistry – Short Answer Rank the following 3 acids in order of increasing pKa: 1) Hydrogen cyanide; 2) Hypochlorous acid; 3) Propanoic acid.  

text[[115, 354, 385, 372]]
ANSWER: 3, 2, 1 [BZ, acid base]  

sub_title[[456, 407, 540, 425]]
## TOSS-UP  

text[[115, 442, 877, 495]]
12) Energy – Short Answer Researchers at Argonne National Lab are studying the properties of unsaturated hydrocarbons. Rank the following 3 hydrocarbons from least to greatest degree of unsaturation: 1) C6H12; 2) C8H18; 3) C16H28.  

text[[115, 512, 260, 529]]
ANSWER: 2, 1, 3  

sub_title[[463, 547, 533, 565]]
## BONUS  

text[[115, 582, 874, 635]]
12) Energy – Short Answer Researchers at Pacific Northwest National Lab are studying the thermal emission of photons from the Earth’s surface. What effect distorts the orbit of planets as a result of the anisotropic distribution of photon emissions from their surfaces?  

text[[115, 652, 410, 670]]
ANSWER: YARKOVSKY EFFECT  

sub_title[[456, 688, 540, 705]]
## TOSS-UP  

text[[115, 722, 879, 810]]
13) Physics [5] – Short Answer Identify all of the following three statements that are true, if air resistance is negligible: 1) An object that launches at the escape velocity from the surface of Earth can only escape if they travel perpendicular to the surface; 2) Projectiles launched from the surface of the Earth at a low speed follow a partial elliptical path; 3) Orbits around the Earth are always centered around the Earth’s core.  

text[[115, 827, 389, 845]]
ANSWER: 2 ONLY [GW, Orbits]  

sub_title[[463, 863, 533, 880]]
## BONUStext[[115, 89, 817, 142]]
13) Physics – Multiple Choice When an external magnetic field is removed from a paramagnetic material, it cools due to thermal motion. Which of the following terms best describes this cooling?  

text[[115, 160, 228, 231]]
W) Isobaric 
X) Isochoric 
Y) Isentropic 
Z) Isenthalpic  

text[[115, 248, 546, 266]]
ANSWER: Y) ISENTROPIC [SS, double penetration]  

sub_title[[456, 301, 540, 320]]
## TOSS-UP  

text[[115, 336, 857, 372]]
14) Biology – Short Answer When parts of a genome are duplicated or moved around, what genetic process allows for the creation of new genes and proteins?  

text[[115, 388, 470, 407]]
ANSWER: EXON SHUFFLING [DJ, DNA]  

sub_title[[462, 424, 533, 442]]
## BONUS  

text[[115, 459, 866, 495]]
14) Biology – Short Answer Identify all of the following 3 diseases that are caused by you: 1) Rheumatoid arthritis; 2) Celiac Disease; 3) Lyme Disease  

text[[115, 511, 555, 530]]
ANSWER: 1 AND 2 [DJ, disease bowl is easy to write]  

sub_title[[456, 565, 540, 583]]
## TOSS-UP  

text[[115, 600, 880, 635]]
15) Math – Short Answer What is the angle in degrees between the minute and hour hands of a clock when it reads 5:30?  

text[[115, 652, 840, 671]]
ANSWER: 15 (i guess 345 is also right but if they say that they're sooo cringe) [LY, hands]  

sub_title[[462, 688, 533, 706]]
## BONUS  

text[[115, 723, 861, 758]]
15) Math – Short Answer \(f(x)\) is a polynomial of degree 2022 such that it only has 2 nonzero coefficients. What is the maximum possible number of real roots that \(f(x)\) can have?  

text[[115, 775, 374, 794]]
ANSWER: 3 [LY, factorization]  

sub_title[[456, 811, 540, 829]]
## TOSS-UP  

text[[115, 846, 835, 899]]
16) Earth and Space [] – Short Answer Identify all of the following 3 properties of the universe that are implied by the cosmological principle: 1) Anisotropy; 2) Homogeneity; 3) Flatness.text[[115, 106, 432, 125]]
ANSWER: 2 ONLY [GW, Cosmology]  

sub_title[[462, 142, 533, 160]]
## BONUS  

text[[115, 177, 847, 213]]
16) Earth and Space [] – Multiple Choice Which of the following is NOT a component of desert varnish?  

text[[115, 230, 287, 301]]
W) Calcrete  X) Iron oxides  Y) Clay minerals  Z) Manganese oxides  

text[[115, 317, 450, 336]]
ANSWER: W) CALCRETE [SS, Deserts]  

sub_title[[456, 353, 540, 371]]
## TOSS-UP  

text[[115, 387, 825, 424]]
17) Chemistry – Short Answer Order the following three isotopes by increasing binding energy per nucleon: 1) Hydrogen-1; 2) Iron-56; 3) Nickel-62.  

text[[115, 440, 368, 459]]
ANSWER: 1, 2, 3 [SS, nuclear]  

sub_title[[462, 476, 533, 494]]
## BONUS  

text[[115, 510, 861, 547]]
17) Chemistry – Multiple Choice Which of the following gases has the greatest compression factor at STP?  

text[[115, 564, 226, 634]]
W) Hydrogen  X) Methane  Y) Ethane  Z) Ammonia  

text[[115, 651, 432, 670]]
ANSWER: W) HYDROGEN [BZ, gas]  

sub_title[[456, 705, 540, 723]]
## TOSS-UP  

text[[115, 739, 860, 793]]
18) Energy – Short Answer Researchers at Lawrence Berkeley National Lab are investigating how predators and prey affect each other. What set of differential equations describes how the two populations fluctuate over time?  

text[[115, 809, 388, 827]]
ANSWER: LOTKA-VOLTERRA  

sub_title[[462, 845, 533, 863]]
## BONUStext[[115, 89, 880, 142]]
18) Energy – Multiple Choice Researchers at Lawrence Berkeley National Lab are studying the optimization of memory usage in computer programs. Which of the following processes would lead to stack overflow?  

text[[115, 160, 300, 230]]
W) Null pointer  X) Index out of bounds  Y) Memory leak  Z) Infinite recursion  

text[[115, 247, 625, 266]]
ANSWER: Z) INFINITE RECURSION [DJ, make people mald]  

sub_title[[456, 301, 540, 319]]
## TOSS-UP  

text[[115, 335, 872, 372]]
19) Physics [] – Multiple Choice The kinetic energy of a particle with constant momentum is proportional to what power of its mass?  

text[[115, 389, 163, 457]]
W)- 1  X) 0  Y) 1  Z) 2  

text[[115, 477, 407, 496]]
ANSWER: W) - 1 [GW, Kinematics]  

sub_title[[462, 513, 533, 531]]
## BONUS  

text[[115, 547, 876, 601]]
19) Physics [] – Short Answer To one significant figure, what is the charge density in coulombs per meter cubed at the point (1,1,1). if the electric field is described by \(\mathrm{E}(\mathrm{x}, \mathrm{y}, \mathrm{z}) = < \mathrm{x}, \mathrm{y}, \mathrm{z}>?\)  

text[[115, 617, 451, 636]]
ANSWER: \(3*10^{- 11}\) [GW, Electrostatics]  

sub_title[[456, 653, 540, 671]]
## TOSS-UP  

text[[115, 687, 830, 724]]
20) Biology – Multiple Choice Which of the following molecules would NOT bind to G protein-coupled receptors  

text[[115, 741, 225, 812]]
W) Morphine  X) Insulin  Y) GABA  Z) Caffeine  

text[[115, 829, 480, 848]]
ANSWER: X) INSULIN [DJ, RECEPTORS]  

sub_title[[462, 865, 533, 882]]
## BONUStext[[113, 89, 848, 127]]
20) Biology – Short Answer Identify all of the following 3 hormones are released from the posterior pituitary gland: 1) ADH; 2) ACTH; 3) LSH  

text[[115, 142, 444, 161]]
ANSWER: 1 ONLY [DJ, HORMONAL]  

sub_title[[456, 195, 541, 212]]
## TOSS-UP  

text[[113, 230, 850, 266]]
21) Math – Short Answer What are the cylindrical coordinates of the point whose spherical coordinates are (1, -1, pi/6)?  

text[[115, 282, 470, 301]]
ANSWER: (½, -1, sqrt3/2) [DJ, coordinates]  

sub_title[[464, 318, 533, 336]]
## BONUS  

text[[115, 353, 863, 390]]
21) Math – Short Answer Congratulations! You successfully dealt with David’s bullshit. For 10 points, what is \(17 + 44\) ?  

text[[115, 406, 357, 425]]
ANSWER: 61 [LY, goddamn]  

sub_title[[456, 460, 541, 477]]
## TOSS-UP  

text[[113, 494, 820, 513]]
22) Earth and Space – Multiple Choice Which of the following is not an ore of copper?  

text[[115, 530, 243, 601]]
W) Bornite 
X) Malachite 
Y) Pyrrolusite 
Z) Chalcopyrite  

text[[115, 617, 368, 635]]
ANSWER: Y) PYRROLUSITE  

sub_title[[464, 636, 533, 653]]
## BONUS  

text[[115, 670, 808, 707]]
22) Earth and Space – Short Answer Identify all of the following three objects that are indicative of star formation. 1) T-associations; 2) Bok globules; 3) OB-associations  

text[[115, 723, 248, 740]]
ANSWER: ALL  

sub_title[[456, 759, 541, 776]]
## TOSS-UP  

text[[115, 794, 875, 829]]
23) Chemistry – Short Answer What is the coordination number of cesium in the standard state form of cesium chloride?  

text[[115, 846, 305, 864]]
ANSWER: 8 [BZ, ions]sub_title[[463, 90, 533, 107]]
## BONUS  

text[[113, 123, 860, 160]]
23) Chemistry – Multiple Choice When cyclohexanone is treated with bromine under acidic conditions, which of the following products is most likely to be formed?  

text[[114, 178, 336, 250]]
W) 2- Bromocyclohexanone  X) 3- Bromocyclohexanone  Y) 4- Bromocyclohexanone  Z) Phenol  

text[[114, 266, 590, 285]]
ANSWER: W) 2- BROMOCYCLOHEXANONE [SS, orgo]