
## TOSS-UP  


1) Physics [3] – Short Answer An object's position as a function of time is described by \(\mathbf{x}(\mathbf{t}) = 4\mathbf{t}^{3} - 5\mathbf{t}\) . What is its velocity at time \(\mathbf{t} = 3\) ?  


ANSWER: 103 [GW, Kinematics]  


## BONUS  


1) Physics [4] – Short Answer What theorem states that the rotation of an object is unstable about its principal axis that has neither the largest nor smallest associated moment of inertia?  


ANSWER: INTERMEDIATE AXIS THEOREM (ACCEPT: TENNIS RACKET THEOREM, DZHANIBEKOV EFFECT) [GW, Stock]  


## TOSS-UP  


2) Biology [] – Short Answer Identify all of the following 3 cells that are glial cells: 1) Ependymal cells; 2) Astrocytes; 3) Chondrocytes.  


ANSWER: 1 AND 2 [DJ, NERVOUS]  


## BONUS  


2) Biology [5] – Short Answer People with PKU are deficient in an enzyme that converts phenylalanine to what other amino acid?  


ANSWER: TYROSINE [GW, Biochem]  


## TOSS-UP  


3) Math [4] – Multiple Choice Which of the following functions is injective over its entire domain?  


W) log X) sin Y) tan Z) absolute value  


ANSWER: W) log [GW, Functions]  


## BONUS  


3) Math [4] – Short Answer Evaluate the cross-product of the two vectors \(3\mathbf{i} + 4\mathbf{j}\) and \(3\mathbf{i} - 5\mathbf{k}\) .  


ANSWER: \(- 20\mathbf{i} + 15\mathbf{j} - 12\mathbf{k}\) [GW, Vectors]
## TOSS-UP  


4) Earth and Space [] – Short Answer  Explosive volcanic eruptions can expel fast-moving currents of gas and tephra. This is known as what type of flow?  


ANSWER: PYROCLASTIC FLOW (ACCEPT: NUEE ARDENTE) [SS, Plate Tectonics]  


## BONUS  


4) Earth and Space [] – Short Answer  What current carries icy water northward from Antarctica and is responsible for the creation of deserts near the coast of Chile?  


ANSWER: HUMBOLDT CURRENT (ACCEPT: PERU CURRENT) [SS, Deserts]  


## TOSS-UP  


5) Chemistry [] – Short Answer  Rank the following 3 molecules in order of increasing bond angle through the central atom: 1) \(\mathrm{H}_2\mathrm{O}\) ; 2) \(\mathrm{NH}_3\) ; 3) \(\mathrm{OF}_2\) .  


ANSWER: 3, 1, 2 [BZ, Bonding]  


## BONUS  


5) Chemistry [] – Short Answer  At a particular temperature, the autoionization constant of water is \(10^{-12}\) . If an acid has a \(\mathrm{K}_{\mathrm{a}}\) of \(10^{-5}\) at that temperature, what is the \(\mathrm{pOH}\) of the solution when 1 mole of the acid is stirred in 100 ml of water?  


ANSWER: 10 [SS, Acid/Base]  


## TOSS-UP  


6) Energy [] – Short Answer  Researchers at Argonne National Lab are using bioactive scaffold injections in paralyzed mice to regenerate axons in damaged spinal cords. Action potentials in axons are initiated in what cone-shaped structure?  


ANSWER: HILLOCK (ACCEPT: AXON HILLOCK) [DJ, BIOLOGY]  


## BONUS  


6) Energy [5] – Multiple Choice  Researchers at Lawrence Livermore National Lab are studying statistical mechanical methods to create a stable cryptocurrency using SHA256. Which of the following is closest to the total number of possible hashes in SHA256?  


W) \(10^{77}\) X) \(10^{78}\)
Y) \(10^{79}\) Z) \(10^{80}\)  


ANSWER: W) \(10^{77}\) [DJ, Computer Science]  


## TOSS-UP  


7) Physics [3] – Multiple Choice In kilopascals, which of the following is closest to the change in pressure of water traveling through a pipe, if its speed doubles from 10 to 20 meters per second and its height remains constant?  


W) 100 X) 150 Y) 300 Z) 400  


ANSWER: X) 150 [GW, Fluids]  


## BONUS  


7) Physics [5] – Multiple Choice Two identical uniform hollow spheres each have a radius of R and are touching each other. The gravitational force of attraction between the spheres is proportional to what power of R?  


W) 0 X) 2 Y) 4 Z) 6  


ANSWER: X) 2 [SS, Forces]  


## TOSS-UP  


8) Biology [4] – Short Answer Identify all of the following 3 features that are characteristic of dicots: 1) Parallel leaf venation; 2) Fibrous root system; 3) Scattered vascular tissue.  


ANSWER: NONE [GW, Plants]  


## BONUS  


8) Biology [] – Short Answer What name is given to the body cavity of most invertebrates that contains its blood or hemolymph?  


ANSWER: HEMOCOEL [GW, Animal Diversity]
## TOSS-UP  


9) Math [] – Short Answer What is the length of a line segment that has an endpoint at (1, 1, 1) and another endpoint at (3, 4, 7)?  


ANSWER: 7 [GW, Coordinates]  


## BONUS  


9) Math [4] – Short Answer In interval notation, what is the range of the rational function \(\mathrm{f(x) = 2x / (x^2 + 1)}\) [read as: \(f\) of \(x\) equals the fraction with numerator \(2x\) and denominator \(x\) squared plus 1]?  


ANSWER: [- 1, 1] [GW, Functions]  


## TOSS-UP  


10) Earth and Space [] – Short Answer Identify all of the following three minerals that can undergo weathering by dissolution: 1) Halite; 2) Dolomite; 3) Quartz.  


ANSWER: 1 AND 2 [BZ, Weathering and Erosion]  


## BONUS  


10) Earth and Space [] – Short Answer What features, known as filaments when viewed against the solar disk, are loops of plasma on the Sun's surface that are anchored to the photosphere?  


ANSWER: PROMINENCES (ACCEPT: SOLAR PROMINENCES) [GW, The Sun]  


## TOSS-UP  


11) Chemistry [] – Short Answer Identify all of the following three types of solid materials whose conductivities increase with increasing temperature: 1) Insulator; 2) Conductor; 3) Semiconductor.  


ANSWER: 1 AND 3 [SS, Matter States]  


## BONUS  


11) Chemistry [] – Multiple Choice Which of the following compounds has the smallest pKa in water?  


W) Acetone X) Propanal
Y) Ethanol Z) Nitromethane  


ANSWER: Z) NITROMETHANE [BZ, Orgo]  


## TOSS-UP  


12) Energy [] – Multiple Choice Researchers at Brookhaven National Lab are studying the acidity of intracellular environments. Which of the following buffer systems would they most likely be studying?  


W) Bicarbonate X) Phosphate Y) Malate Z) Citrate  


ANSWER: X) PHOSPHATE [DJ, Bio]  


## BONUS  


12) Energy [] – Short Answer Researchers at Brookhaven National Lab are using the Relativistic Heavy Ion Collider to track how certain jets of particles lose energy through various mediums. What medium is formed from the removal of strong nuclear attractions between particles, causing the particles to be deconfined?  


ANSWER: QUARK-GLUON PLASMA (ACCEPT: QGP) [DJ, PHYSICS]  


## TOSS-UP  


13) Physics [] – Short Answer What term, which equals epsilon_naught times the time derivative of the electric field in a non-polarizable medium, was added by James Maxwell to Ampere's law?  


ANSWER: DISPLACEMENT CURRENT [GW, Stock]  


## BONUS  


13) Physics [] – Short Answer A 5-kilogram mass is moving at 6 meters per second to the right when it collides perfectly elastically with a stationary 7-kilogram mass. What is the speed of the 7-kilogram mass at the end of the collision?  


ANSWER: 5 METERS PER SECOND [SS]  


## TOSS-UP
14) Biology [] – Short Answer Identify all of the following 3 vitamins, whose deficiency can cause anemia: 1) Folate; 2) Cobalamin; 3) Calciferol.  


ANSWER: ALL [SS, BIOCHEM]  


## BONUS  


14) Biology [] – Short Answer Identify all of the following 3 cells that can express Class II MHCs: 1) Dendritic cells; 2) Cytotoxic T cells; 3) B cells  


ANSWER: 1 AND 3 [RS, Immunology]  


## TOSS-UP  


15) Math [] – Short Answer If x is a real number, then what is the magnitude of the complex number \(\mathrm{e}^{2\mathrm{i}\mathrm{x}}\) ?  


ANSWER: 1 [SS, Complex Numbers]  


## BONUS  


15) Math [] – Short Answer Given 2 red hats, 2 blue hats, and 1 green hat, how many ways are there to arrange the hats in a row such that the red hats are not next to each other and the blue hats are not next to each other?  


ANSWER: 12 [DJ, Discrete]  


## TOSS-UP  


16) Earth and Space [] – Multiple Choice Which of the following drainage patterns would form on ground with numerous vertical joints?  


W) Trellis X) Dendritic Y) Radial Z) Rectangular  


ANSWER: Z) RECTANGULAR [BZ, Rivers and Streams]  


## BONUS  


16) Earth and Space [] – Short Answer To one significant figure, what is the Schwarzschild radius of a ball with a mass of 2 kilograms?  


ANSWER: \(3*10^{- 27}\) METERS [GW, Black Holes]
## TOSS-UP  


17) Chemistry [] – Short Answer Identify all of the following 3 compounds that can act as Lewis acids: 1) ZnCl₂; 2) Xe; 3) BF₃  


ANSWER: 1 AND 3 [BZ, Acid/Base]  


## BONUS  


17) Chemistry [] – Multiple Choice Which of the following species does NOT readily disproportionate in aqueous solution?  


W) Cl₂ X) Cu⁺ Y) Fe²⁺ Z) N₂O  


ANSWER: Y) Fe²⁺ [BZ, Electrochem]  


## TOSS-UP  


18) Energy [5] – Short Answer Researchers at Oak Ridge National Lab are using the supercomputer Summit to train neural networks. When training feedforward neural networks, what step, an application of the chain rule, computes the gradient of the error function with respect to the model's weights?  


ANSWER: BACKPROPAGATION (ACCEPT: BACKPROP) (Note: backpropagation only refers to computing the gradient, not updating the weights) [GW, Computer Science]  


## BONUS  


18) Energy [] – Short Answer Researchers at Brookhaven National Lab are studying microbes in our gut that can decrease the efficacy of the diabetes drug acarbose. What glucose transport are the researchers most likely studying, that is the most heavily involved in diabetes?  


ANSWER: GLUT4 (ACCEPT: GLUCOSE TRANSPORTER TYPE 4; ACCEPT: 4) [DJ, BIO]  


## TOSS-UP  


19) Physics [5] – Multiple Choice How many up and down quarks, respectively, are present in one alpha particle?  


W) 3, 3 X) 4, 2 Y) 5, 5 Z) 6, 6
ANSWER: Z) 6, 6 [GW, Particle]  


## BONUS  


19) Physics [] – Short Answer What is the torque on a square loop with a side length of 5 meters and a current of 2 amperes when an external perpendicular magnetic field of strength 7 teslas is applied to it?  


ANSWER: 0 [GW, Electromagnets]  


## TOSS-UP  


20) Biology [4] – Multiple Choice In the trp operon, which of the following best describes the role of tryptophan?  


W) Operator 
X) Inducer 
Y) Repressor 
Z) Co-repressor  


ANSWER: Z) CO- REPRESSOR [SS, Signaling]  


## BONUS  


20) Biology [] – Short Answer Identify all of the following 3 functions that albumin serves in the human body: 1) Clotting; 2) pH buffering; 3) Osmotic balance.  


ANSWER: 2 AND 3 [DJ, Circulation]  


## TOSS-UP  


21) Math [3] – Short Answer Four fair 6-sided dice are rolled. What is the probability that the sum of the 4 rolls is divisible by 3?  


ANSWER: 1/3 [GW, Coins/Dice]  


## BONUS  


21) Math [] – Short Answer Triangle ABC has side-lengths AB = 13, BC = 14, and AC = 15. The altitude extending from A to BC meets line BC at point H. What is the length of BH?  


ANSWER: 5 [SS, Triangles]  


## TOSS-UP
22) Earth and Space [] – Short Answer According to the Hubble tuning fork, order the following 3 galaxy types from least to most evolved: 1) Sc; 2) S0; 3) E0.  


ANSWER: 3, 2, 1 [GW, Galaxies]  


## BONUS  


22) Earth and Space [5] – Short Answer Unlike the basalt-rich lunar maria, the moon's highlands are primarily composed of what rock?  


ANSWER: ANORTHOSITE (DO NOT ACCEPT: ANORTHITE) [GW, Inner Planets]  


## TOSS-UP  


23) Chemistry [] – Short Answer Identify all of the following 3 species that are paramagnetic. 1) \(\mathrm{O}_{2}^{-}\) , 2) \(\mathrm{O}_{2}\) ; 3) \(\mathrm{O}_{2}^{+}\) .  


ANSWER: ALL [SS, Bonding]  


## BONUS  


23) Chemistry [] – Short Answer How many unpaired electrons does the tetracyanonickelate (II) anion possess?  


ANSWER: 0 [BZ, CFT]