
## TOSS-UP  


1) Physics [5] – Multiple Choice Two points with charges of a and b are located at \(\mathbf{x} = 0\) and \(\mathbf{x} = 5\) . Which of the following values of a and b would NOT result in a point on the \(\mathbf{x}\) -axis with zero electric field?  


\(\mathrm{W}) \mathrm{a} = - 2, \mathrm{b} = - 1\) \(\mathrm{X}) \mathrm{a} = - 2, \mathrm{b} = 2\) \(\mathrm{Y}) \mathrm{a} = 3, \mathrm{b} = - 5\) \(\mathrm{Z}) \mathrm{a} = 4, \mathrm{b} = 4\)  


ANSWER: \(\mathrm{X}) \mathrm{a} = - 2, \mathrm{b} = 2\) [GW, Electrostatics]  


## BONUS  


1) Physics [6] – Short Answer What particle, the most common type of charmonium, consists of a charm quark and a charm antiquark?  


ANSWER: J/PSI MESON (ACCEPT: J/PSI) [GW, Particle]  


## TOSS-UP  


2) Biology [] – Short Answer In the cells of human females, what small densely staining structure is formed as a result of dosage compensation?  


ANSWER: BARR BODY [RS, GENETICS]  


## BONUS  


2) Biology [RR] – Multiple Choice Which of the following cellular events is NOT likely to involve lipid rafts?  


W) Antigen receptor signaling X) Viral entry Y) E.R. vesicle formation Z) Acrosome reaction  


ANSWER: Y) E.R. VESICLE FORMATION [SL, Cyto]  


## TOSS-UP  


3) Math [] – Short Answer a and b are positive integers such that \(\mathrm{a} + \mathrm{b} = 37\) . Identify all of the following 4 options that could be the greatest common divisor of a and b: 1) 1; 2) 2; 3) 3; 4) 5.  


ANSWER: 1 ONLY [SS/GW, Factors]
## BONUS  


3) Math [6] – Short Answer You're playing a coin game where you repeatedly flip a fair coin until you get tails. You win 1 dollar for each time the coin lands on heads. If it is possible to win 0 dollars, then what are your expected earnings?  


ANSWER: 1 [GW, Coins/Dice]  


## TOSSUP  


4) Earth and Space [] – Short Answer Order the following three minerals from first to last to crystallize in magma: 1) Olivine; 2) Amphibole; 3) Muscovite.  


ANSWER: 1, 2, 3 [SS, Mineralogy]  


## BONUS  


4) Earth and Space [] – Multiple Choice Plasma surrounding which of the following types of stellar objects would feel the largest radial force?  


W) Pulsar  X) White Dwarf  Y) Magnetar  Z) Black Dwarf  


ANSWER: Y) MAGNETAR [SS]  


## TOSSUP  


5) Chemistry [] – Short Answer At standard temperature and pressure, identify all of the following three gases in which intermolecular attractions are dominant over repulsions: 1) Sulfur hexafluoride; 2) Ethane; 3) Hydrogen.  


ANSWER: 1 AND 2 [SS, States of Matter]  


## BONUS  


5) Chemistry [] – Short Answer Rank the following 3 elements in order of increasing electron affinity: 1) Argon; 2) Oxygen; 3) Sulfur.  


ANSWER: 1, 2, 3 [BZ, Trends]  


## TOSSUP
6) Energy [RR] – Short Answer Researchers at Los Alamos National Lab are studying biphasic sleep models and the effects on abnormal circadian rhythms. In the hypothalamus, what part of the brain is responsible for the regulation of our circadian rhythms?  


ANSWER: SUPRACHIASMATIC NUCLEUS (ACCEPT: SCN) [DJ, BIO]  


## BONUS  


6) Energy [RR] – Short Answer Researchers at Lawrence Berkeley National Lab are studying distributed adaptive prefix trees, a type of binary search tree, in the use of functional storage in high performance computing. Given a binary search tree with 32 nodes, and assuming that a tree with 1 node has a height of 1, what is the height of a balanced BST and the height of an unbalanced worst case BST?  


ANSWER: 6 AND 32 [DJ, CS]  


## TOSS-UP  


7) Physics [5] – Short Answer In the Bohr model of the atom, the angular momentum of an electron is equal to its principal quantum number times what constant?  


ANSWER: REDUCED PLANCK CONSTANT (ACCEPT: H- BAR; DO NOT ACCEPT: PLANCK'S CONSTANT, h) [GW, Quantum]  


## BONUS  


7) Physics [5] – Multiple Choice Which of the following circuit components, when combined with a resistor, would form the most effective high-pass filter?  


W) Op- amp X) Diode Y) Inductor Z) Capacitor  


ANSWER: Z) CAPACITOR [GW, Circuits]  


## TOSS-UP  


8) Biology [] – Short Answer MRNA transcripts most commonly bind to one ribosome's initiation complex. However, sometimes mRNA transcripts can bind to multiple ribosomes at once. What term is given to this string of ribosomes that actively participates in translation?  


ANSWER: POLYSOME (ACCEPT: POLYRIBOSOME) [SS, RNA]  


## BONUS
8) Biology [RR] – Multiple Choice Which of the following cytoskeletal motors transports cargo inward toward the nucleus?  


W) Dynein 
X) Kinesin 
Y) Myosin 
Z) Prestin  


ANSWER: W) DYNEIN [SL, Cyto]  


## TOSS-UP  


9) Math [] – Short Answer What is the smallest four digit number contained in Pascal's triangle?  


ANSWER: 1000 [LY, DISCRETE]  


## BONUS  


9) Math [] – Short Answer How many integers between 1 and 30 inclusive, are divisible by each of their digits?  


ANSWER: 14 [SS, Digits] (Note: 1- 9, 11, 12, 15, 22, 24)  


## TOSS-UP  


10) Earth and Space [] – Short Answer Identify all of the following 4 elements that are considered metals in astronomy: 1) Hydrogen; 2) Helium; 3) Carbon; 4) Neon.  


ANSWER: 3 AND 4 [GW, Miscellaneous]  


## BONUS  


10) Earth and Space [] – Short Answer Identify all of the following three stars that have convective currents that reach the core: 1) The Sun; 2) Proxima Centauri; 3) Rigel.  


ANSWER: 2, 3 [BZ, Stars]  


## TOSS-UP  


11) Chemistry [] – Short Answer What is the oxidation state of the carbon atom in formic acid?  


ANSWER: +2 (DO NOT ACCEPT: 2) [BZ, Organic]
## BONUS  


11) Chemistry [] – Short Answer Identify all of the following 3 elements that experience sp-mixing in their diatomic form: 1) Lithium; 2) Boron; 3) Carbon.  


ANSWER: ALL [DJ, Bonding]  


## TOSS-UP  


12) Energy [] – Short Answer Researchers at Pacific Northwest National Lab are studying phase changes of Helium-4 to better understand solar conditions. Helium-4 is special because it is missing what point on its phase diagram where the solid/liquid, solid/gas, and liquid/gas equilibrium lines intersect?  


ANSWER: TRIPLE POINT [DJ, CHEM]  


## BONUS  


12) Energy [] – Short Answer Researchers at SLAC are using stimulated emissions in order to create an afterburn-based particle accelerator. They are using what SPECIFIC type of device found in atomic clocks, which was invented by Charles Townes?  


ANSWER: MASER (PROMPT ON: LASER) [DJ, PHYSICS]  


## TOSS-UP  


13) Physics [4] – Short Answer Water is flowing through a cylindrical hose with a radius of 3 centimeters at a speed of 3 meters per second. If the hose then narrows to a radius of 1 centimeter, then at what speed will the water flow?  


ANSWER: 27 METERS PER SECOND [GW, Fluids]  


## BONUS  


13) Physics [5] – Short Answer Alice is traveling at a speed of 0.75c. Alice launches a projectile which moves at a speed of 0.25c relative to Alice. What is the smallest possible relative speed between Alice and the projectile that an outside observer can observe, in terms of c?  


ANSWER: 8c/13 [GW, Relativity]  


## TOSS-UP  


14) Biology [RR] – Short Answer Identify all of the following 3 processes that are associated with senescence: 1) Shrinking of the nucleus; 2) Mitochondrial dysfunction; 3) Increased DNA methylation.
ANSWER: 2 AND 3 [SL, BUTTHOLE]  


## BONUS  


14) Biology [RR] – Short Answer What two protein complexes translocate proteins across the chloroplast membrane?  


ANSWER: TIC/TOC [SL, PLANTS]  


## TOSS-UP  


15) Math [] – Short Answer How many positive 2 digit integers have a smaller ones-digit than tens-digit?  


ANSWER: 45 [SS, Digits]  


## BONUS  


15) Math [] – Short Answer On a \(10 \times 10\) checkerboard, a Knight moves by going 2 units in one direction and then 1 unit perpendicular. What is the maximum number of knights you can place on this board such that no two knight attack each other?  


ANSWER: 50 [DJ, CHESS]  


## TOSS-UP  


16) Earth and Space [] – Short Answer Order the following three steps of sedimentary rock formation chronologically. 1) Compaction; 2) Cementation; 3) Deposition.  


ANSWER: 3, 1, 2 [SS, Rocks]  


## BONUS  


16) Earth and Space [] – Short Answer What is the name given to the groundwater structure formed when groundwater accumulates on an aquitard above the zone of saturation?  


ANSWER: PERCHED WATER TABLE (ACCEPT: PERCHED AQUIFER) [BZ, Rivers and Streams]  


## TOSS-UP  


17) Chemistry [] – Short Answer Given that the half-life of a first order reaction is 21 seconds, then in inverse seconds and to 1 significant figure, what is the rate constant for the reaction?
ANSWER: 0.03 [BZ, Kinetics]  


## BONUS  


17) Chemistry [] – Multiple Choice Which of the following elements has the closest molar mass to that of boron trifluoride?  


W) Calcium X) Manganese Y) Nickel Z) Gallium  


ANSWER: Z) GALLIUM [BZ, Periodic Table]  


## TOSS-UP  


18) Energy [] – Multiple Choice Researchers at Oak Ridge national lab are improving on electrolysis by introducing methods to account for overpotential. Which of the following statements is NOT TRUE regarding electrolytic cells?  


W) The anode is labeled negative and the cathode is labeled positive X) Electrolytic cells have a Gibbs Free Energy greater than zero Y) The down's process is an electrolytic method used to produce sodium and chlorine Z) Faraday's laws can be used to calculate the quantity of products in electrolysis  


ANSWER: W) THE ANODE IS LABELED NEGATIVE AND THE CATHODE IS LABELED POSITIVE [SS]  


## BONUS  


18) Energy [RR/DE] – Short Answer Researchers at Lawrence Berkeley National Lab are using plants in attempts to find a cheaper and environmentally friendly method to produce salicylate. Identify all of the following 3 natural products that salicylate inhibits the production of: 1) Urea; 2) Thromboxane; 3) Prostaglandin.  


ANSWER: 2 AND 3 [DJ, Bio]  


## TOSS-UP  


19) Physics [5] – Multiple Choice A 2-kilogram ball has a kinetic energy of 50 joules and is moving to the right. Later, the ball is moving upward with a kinetic energy of 50 joules. In kilogram-meters per second, what is the change in momentum of the ball?  


W) 5 root 2 X) 10
Y) 10 root 2
Z) 20  


ANSWER: Z) 20 [GW, Forces]  


## BONUS  


19) Physics [] – Short Answer Consider a particle in a box, where the region of 0 potential ranges from \(0 < x < 1\) meter. Identify all of the following 4 values of \(n\) such that the probability density of finding a particle at position \(x = 1/4\) is 0: 1) 1; 2) 2; 3) 3; 4) 4.  


ANSWER: 4 ONLY [GW, Quantum]  


## TOSS-UP  


20) Biology [RR] – Multiple Choice David Jiang went out to play basketball without insurance. While playing he sprained his ankle and is in pain. This would lead to the activation of which of the following types of receptors?  


W) Proprioceptor 
X) Baroreceptor 
Y) Thermocceptor 
Z) Nociceptor  


ANSWER: Z) NOCICEPTOR [DJ/GW, SENSORY]  


## BONUS  


20) Biology [5] – Short Answer Order the following three compounds in order that they are formed in the citric acid cycle starting from citrate: 1) Fumarate; 2) Malate; 3) alpha-Ketoglutarate.  


ANSWER: 3, 1, 2 [GW, Biochem]  


## TOSS-UP  


21) Math [] – Multiple Choice What is the sum of all the positive integer factors of 36?  


W) 96
X) 91
Y) 90
Z) 60  


ANSWER: X) 91 [SS, Factors]
## BONUS  


21) Math [] - Short Answer A regular hexagon has unit side length, and an equilateral triangle is formed by connecting the midpoints of alternating sides of that hexagon. What is the area of that triangle?  


ANSWER: 9 ROOT 3 OVER 16 [LY, POLYGONS]  


## TOSS-UP  


22) Earth and Space [4] - Multiple Choice Which of the following terrestrial planets has the highest density?  


W) Mercury  X) Venus  Y) Earth  Z) Mars  


ANSWER: Y) EARTH [GW, Inner Planets]  


## BONUS  


22) Earth and Space [] - Short Answer What is the term for the collection of rock fragments that accumulate at the base of a cliff due to friction and collisions from rockfall?  


ANSWER: TALUS (ACCEPT: SCREE) [BZ, Mass Wasting]  


## TOSS-UP  


23) Chemistry [4] - Short Answer When phenol is treated with molecular bromine, how many equivalents of bromine react to form the major product?  


ANSWER: 3 [BZ, Organic]  


## BONUS  


23) Chemistry [] - Short Answer Identify all of the following three thermodynamic processes that result in an increase in temperature: 1) Isobaric compression; 2) Isothermal expansion; 3) Reversible adiabatic expansion.  


ANSWER: NONE [SS/BZ/GW/DJ/SL/LY/RS, Thermo]