sub_title[[456, 150, 540, 168]]
## TOSS-UP  

text[[114, 190, 863, 273]]
1) Biology – Short Answer Arin is having trouble breathing at night because Adrian keeps covering his mouth during his REM sleep. However, Adrian is able to do so discreetly, so Arin thinks that there is an issue with his brain. What two structures in the brain control mammalian respiration?  

text[[114, 295, 530, 314]]
ANSWER: MEDULLA OBLONGATA AND PONS  

sub_title[[462, 338, 534, 356]]
## BONUS  

text[[114, 379, 872, 420]]
1) Biology – Short Answer Identify all of the following organs that are correctly matched with the tissue from the embryonic germ layer that they are primarily formed from:  

text[[123, 441, 364, 522]]
I. Spinal Cord: Endoderm II. Heart: Mesoderm III. Thyroid: Endoderm IV. Liver: Ectoderm  

text[[114, 546, 282, 563]]
ANSWER: II and III  

sub_title[[456, 586, 540, 604]]
## TOSS-UP  

text[[114, 626, 859, 666]]
2) Chemistry – Multiple Choice Which of the following best describes the gas-state atoms of ground state zinc?  

text[[114, 689, 285, 770]]
W) Paramagnetic 
X) Diamagnetic 
Y) Ferromagnetic 
Z) Antiferromagnetic  

text[[114, 792, 375, 810]]
ANSWER: X) DIAMAGNETIC  

sub_title[[423, 835, 572, 853]]
## VISUAL BONUSimage[[170, 140, 850, 450]]  

sub_title[[525, 459, 593, 480]]
## Speed  

text[[114, 490, 881, 573]]
2) Chemistry – Short Answer The following three curves represent the curves of Krypton at -50 C, Krypton at 0 C, and Argon at 0 C, though not necessarily in that order. Given that the solid curve is Curve I, the dotted curve is Curve II, and the dashed curve is Curve III, identify what gas and temp pair represents each curve.  

text[[114, 593, 868, 634]]
ANSWER: CURVE I is KRYPTON AT - 50 C, CURVE II IS KRYPTON AT 0 C, CURVE III is ARGON AT 0 C  

sub_title[[457, 655, 538, 673]]
## TOSS-UP  

text[[114, 696, 881, 758]]
3) Physics – Short Answer A 100-kilogram mass is sliding at an initial speed of 7.65 meters per second on ice, coming to rest uniformly in 3 seconds due to friction. In newtons, what is the magnitude of the force of friction on the mass due to the ice?  

text[[115, 780, 240, 798]]
ANSWER: 255  

sub_title[[462, 823, 533, 841]]
## BONUS  

text[[114, 863, 879, 924]]
3) Physics – Short Answer A 7.2-kilogram box is sliding along a frictionless surface at 3 meters per second when it runs into a spring of spring constant 8,000 newtons per meter. In meters, how much will the spring be compressed?text[[115, 145, 245, 163]]
ANSWER: 0.09  

sub_title[[455, 186, 540, 204]]
## TOSS-UP  

text[[115, 227, 844, 289]]
4) Earth and Space – Short Answer Identify all of the following four ores that are correctly matched to the element they are an ore of: 1) Cinnabar, Zinc 2) Bauxite, Aluminum 3) Magnetite, Iron 4) Magnesite, Magnesium  

text[[115, 310, 260, 328]]
ANSWER: 2, 3, 4  

sub_title[[462, 353, 534, 371]]
## BONUS  

text[[115, 393, 870, 433]]
4) Earth and Space – Short Answer Order the following layers of an ophiolite from uppermost to bottomost:  

text[[120, 436, 362, 516]]
I. Pillow lava  
II. Sheeted dike complex  
III. Gabbro layer  
IV. Deep marine sediments  

text[[115, 540, 299, 558]]
ANSWER: IV, I, II, III  

sub_title[[455, 580, 540, 598]]
## TOSS-UP  

text[[115, 620, 867, 681]]
5) Math – Multiple Choice For a twice-differentiable function f(x), f(6) is 26, f prime of 6 is 0 and f double prime of 6 is -2. Which of the following is true of the graph of y = f(x) at the point (6, 26)?  

text[[115, 704, 359, 785]]
W) There is a Local Minimum  
X) There is a Local Maximum  
Y) There is an Inflection Point  
Z) The Graph is Concave Up  

text[[115, 802, 515, 820]]
ANSWER: X) THERE IS A LOCAL MAXIMUM  

sub_title[[462, 880, 535, 897]]
## BONUStext[[114, 124, 866, 185]]
5) Math – Short Answer One dimension of a cube is increased by 3, another is decreased by 3, and the other is left unchanged. If the new solid has a volume 54 less than that of the original cube, what was the volume of the original cube?  

text[[115, 208, 241, 225]]
ANSWER: 216  

sub_title[[455, 247, 541, 266]]
## TOSS-UP  

text[[114, 289, 883, 350]]
6) Energy – Multiple Choice Scientists at Fermilab are using the MINERvA experiment to study interactions of neutrinos through the weak force. Which of the following bosons is a carrier of the weak force?  

text[[114, 372, 247, 454]]
W) Gluon  X) Higgs Boson  Y) Photon  Z) Z Boson  

text[[115, 477, 318, 496]]
ANSWER: Z) Z BOSON  

sub_title[[462, 519, 534, 538]]
## BONUS  

text[[114, 560, 870, 621]]
6) Energy – Short Answer Scientists at the Thomas Jefferson National Accelerator Facility are using supercomputers to model the structure of pions. Pions belong to what class of subatomic particles, which consist of a quark-antiquark pair?  

text[[115, 644, 290, 661]]
ANSWER: MESONS  

sub_title[[455, 683, 541, 702]]
## TOSS-UP  

text[[114, 725, 835, 765]]
7) Biology – Multiple Choice Which of the following divisions of the autonomic nervous system would be most important for prey fleeing their predator?  

text[[114, 787, 279, 868]]
W) Enteric Nervous  X) Somatic Nervous  Y) Parasympathetic  Z) Sympathetic  

text[[115, 891, 368, 909]]
ANSWER: Z) SYMPATHETICsub_title[[463, 125, 533, 144]]
## BONUS  

text[[114, 166, 767, 206]]
7) Biology - Short Answer Order the following elements of a tree trunk from the OUTERMOST region to the INNERMOST:  

text[[123, 230, 327, 311]]
I. Periderm 
II. Heartwood 
III. Sapwood 
IV. Vascular Cambium  

text[[115, 333, 298, 352]]
ANSWER: I, IV, III, II  

sub_title[[456, 372, 541, 391]]
## TOSS-UP  

text[[114, 413, 877, 475]]
8) Chemistry - Short Answer A vessel contains 66 g of Carbon dioxide and 16 g of diatomic oxygen gas. Given that the pressure of the vessel is 10 atm, what is the partial pressure of carbon dioxide in this vessel?  

text[[115, 497, 281, 515]]
ANSWER: 7.5 ATM  

sub_title[[463, 540, 533, 558]]
## BONUS  

text[[114, 580, 872, 621]]
8) Chemistry - Multiple Choice Which of the following solutes, when dissolved in 1 kilogram of water, will give the solution with the highest boiling point?  

text[[114, 642, 456, 745]]
W) 50 g ethylene glycol, \(HOCH_{2}CH_{2}OH\) X) 50 g hydroxyacetic acid, \(HOCH_{2}COOH\) Y) 50 g glycerol, \(HOCH_{2}CHOHCH_{2}OH\) Z) 50 g glyoxal, \(HCOCHO\)  

text[[114, 766, 454, 786]]
ANSWER: Z) 50 g GLYOXAL, \(HCOCHO\)  

sub_title[[456, 807, 541, 825]]
## TOSS-UP  

text[[114, 848, 852, 910]]
9) Physics - Multiple Choice An engineer designs a step-down transformer to convert 800 volts-RMS down to 20 volts-RMS. If the primary winding has 600 turns, how many turns are required on the secondary winding?text[[113, 125, 260, 225]]
W) 15X) 150Y) 600Z) 24000ANSWER: W) 15  

sub_title[[463, 250, 534, 269]]
## BONUS  

text[[112, 291, 825, 311]]
9) Physics – Short Answer In what region of semiconductors does the Fermi Energy lie?  

text[[115, 333, 311, 352]]
ANSWER: BAND GAP  

sub_title[[456, 393, 540, 412]]
## TOSS-UP  

text[[115, 435, 843, 475]]
10) Earth and Space – Short Answer What principle of general relativity states that inertial forces and gravitational forces are similar in nature and are often indistinguishable?  

text[[115, 497, 451, 515]]
ANSWER: EQUIVALENCE PRINCIPLE  

sub_title[[463, 540, 534, 559]]
## BONUS  

text[[115, 581, 847, 621]]
10) Earth and Space – Multiple Choice In what period of Martian history would there most likely be formation of outflow channels?  

text[[115, 643, 232, 725]]
W) NoachianX) AmazonianY) HesperianZ) Cryogenian  

text[[115, 747, 344, 765]]
ANSWER: Y) HESPERIAN  

sub_title[[456, 788, 540, 806]]
## TOSS-UP  

text[[115, 829, 880, 910]]
11) Math – Short Answer Arin has taken his science bowl team to a restaurant, which has 5 members including himself. What is the number of meals that the restaurant must serve so that if a coach came along, the number of combinations of meals that the table could order, with the caveat that each person orders a different meal, would NOT change?text[[115, 145, 228, 163]]
ANSWER: 11  

sub_title[[462, 188, 535, 206]]
## BONUS  

text[[115, 229, 759, 250]]
11) Math – Short Answer What is the cross product of the vectors \(i + j + k\) and \(j\)  

text[[115, 270, 528, 290]]
ANSWER: \(- i + k\) (ACCEPT: \(- Ii + 0j + Ik, - Ii + Ik)\)  

sub_title[[456, 332, 540, 350]]
## TOSS-UP  

text[[115, 371, 840, 435]]
12) Energy – Multiple Choice Scientists at Brookhaven National Lab are using the Rubin Observatory to catalog galaxies in great detail. Which of the following astronomical objects would most likely be formed by one galaxy passing through another one?  

text[[114, 456, 282, 540]]
W) Irregular galaxy  X) Elliptical galaxy  Y) Lenticular galaxy  Z) Ring galaxy  

text[[115, 560, 370, 579]]
ANSWER: Z) RING GALAXY  

sub_title[[462, 602, 535, 620]]
## BONUS  

text[[115, 642, 842, 705]]
12) Energy – Multiple Choice Scientists at Pacific Northwest National Lab are developing improved models for thunderstorms over central North America. Which of the following accessory clouds generally form on the leading edges of thunderstorms?  

text[[114, 726, 256, 808]]
W) Incus clouds  X) Pileus clouds  Y) Arcus clouds  Z) Fractus clouds  

text[[115, 830, 384, 849]]
ANSWER: Y) ARCUS CLOUDS  

sub_title[[456, 871, 540, 889]]
## TOSS-UPtext[[113, 124, 866, 165]]
13) Biology – Multiple Choice Which of the following immunoglobulins is the key source of allergies?  

text[[113, 187, 180, 270]]
W) IgA 
X) IgE 
Y) IgG 
Z) IgM  

text[[114, 292, 253, 310]]
ANSWR: X) IgE  

sub_title[[423, 333, 572, 351]]
## VISUAL BONUS  

text[[115, 354, 348, 373]]
13) Biology – Short Answer  

image[[370, 396, 644, 590]]  

text[[113, 606, 881, 647]]
Consider the following structure of an antibody. What letter represents the site where an antibody bound to a pathogen would be recognized by a macrophage?  

text[[114, 669, 271, 686]]
ANSWER: SITE D  

sub_title[[455, 709, 541, 727]]
## TOSS-UP  

text[[114, 750, 881, 831]]
14) Chemistry – Multiple Choice Arin is messing around with reactions. When he increases the temperature from 50 to 60 degrees Celsius, he found that the rate is 2.3 times faster. By what factor will the rate increase when the temperature is further increased from 60 to 70 degrees Celsius.  

text[[113, 854, 348, 955]]
W) By a Factor Less than 2.3 
X) By a Factor Equal To 2.3 
Y) By a Factor more than 2.3 
Z) The Rate will Decrease  

text[[114, 943, 232, 960]]
CSBL Playoff 3text[[114, 145, 504, 163]]
ANSWER: W) BY A FACTOR LESS THAN 2.3  

sub_title[[463, 189, 534, 207]]
## BONUS  

text[[114, 229, 880, 331]]
14) Chemistry - Short Answer An irreversible reaction, \(\mathrm{A} + \mathrm{B} \rightarrow\) products, is studied under conditions where the concentration of B is much greater than the concentration of A. When [B] = 0.10 M, a plot of \(1 / [\mathrm{A}]\) vs. time is linear. When [B] = 0.30 M, the plot of \(1 / [\mathrm{A}]\) vs. time is indistinguishable from the first plot within experimental error. Given that the rate constant for this reaction is k, what is the rate law for this reaction?  

text[[115, 355, 255, 378]]
ANSWER: \(k[A]^{2}\)  

sub_title[[456, 400, 541, 419]]
## TOSS-UP  

text[[115, 441, 803, 481]]
15) Physics - Multiple Choice Which of the following descriptions is best for an ideal ammeter?  

text[[114, 503, 375, 584]]
W) Zero Resistance in Parallel  
X) Infinite Resistance in Parallel  
Y) Zero Resistance in Series  
Z) Infinite Resistance in Series  

text[[114, 607, 506, 625]]
ANSWER: Y) ZERO RESISTANCE IN SERIES  

sub_title[[463, 650, 535, 668]]
## BONUS  

text[[115, 691, 833, 752]]
15) Physics - Short Answer Arin has just broken physics as we know it! He was able to discover magnetic monopoles. Identify ALL of the following Maxwell's Laws that must be changed to account for this discovery:  

text[[125, 775, 393, 855]]
I. Faraday's Law  
II. Ampere's Law  
III. Gauss's Law of Electricity  
IV. Gauss's Law of Magnetism  

text[[115, 879, 289, 896]]
ANSWER: I AND IVtext[[115, 145, 866, 207]]
16) Earth and Space – Short Answer The flatness and horizon problems both deal with the fundamental structure of the Universe. They are both solved by what theory regarding the early Universe, which states that space rapidly expanded shortly after the Big Bang?  

text[[112, 228, 794, 248]]
ANSWER: COSMIC INFLATION (ACCEPT: INFLATION, INFLATION THEORY)  

sub_title[[463, 292, 534, 310]]
## BONUS  

text[[115, 333, 877, 395]]
16) Earth and Space – Short Answer The triple alpha process for stellar fusion has two primary steps, which each yield an isotope of each element. What are the elements for the isotopes produced in the first and second steps, respectively?  

text[[115, 416, 457, 435]]
ANSWER: BERYLLIUM AND CARBON  

sub_title[[456, 457, 541, 475]]
## TOSS-UP  

text[[115, 498, 839, 542]]
17) Math – Short Answer What is the remainder when \(x^{3} + 2x^{2} + 6x + 1\) is divided by \(x + 2\)  

text[[115, 565, 235, 583]]
ANSWER: - 11  

sub_title[[463, 607, 534, 625]]
## BONUS  

text[[115, 649, 850, 689]]
17) Math – Short Answer What are the mean and median, respectively, of the first 10 prime numbers?  

text[[115, 710, 852, 730]]
ANSWER MEAN = 12.9; MEDIAN = 12 (ACCEPT: 12.9, 12; DO NOT ACCEPT: 12, 12.9)  

sub_title[[456, 750, 540, 769]]
## TOSS-UP  

text[[115, 790, 864, 852]]
18) Energy – Short Answer Scientists at Argonne National Lab are researching systems that can efficiently convert carbon dioxide into ethanol. The reverse combustion of \(3\mathrm{CO}_{2}\) and \(2\mathrm{H}_{2}\mathrm{O}\) yields one molecule of ethanol and how many molecules of \(\mathrm{O}_{2}\) ?  

text[[115, 875, 220, 892]]
ANSWER: 3  

sub_title[[463, 916, 534, 933]]
## BONUStext[[115, 145, 876, 207]]
18) Energy – Multiple Choice Scientists at Lawrence are using ultra-short x-ray bursts to study enzymes involved in photosynthesis. Which of the following light-driven photosynthetic processes involves Photosystem I, but does NOT involve photosystem II?  

text[[114, 229, 309, 310]]
W) Cyclic electron flow  
X) Calvin cycle  
Y) Linear electron flow  
Z) Reverse Krebs cycle  

text[[114, 332, 480, 351]]
ANSWER: W) CYCLIC ELECTRON FLOW  

sub_title[[456, 372, 540, 390]]
## TOSS-UP  

text[[115, 413, 825, 454]]
19) Biology – Short Answer What is the probability of an offspring having the genotype AAbbCCdd from the parents which have genotypes AaBbCcDd and AABbCcDd?  

text[[115, 476, 256, 495]]
ANSWER: 1/128  

sub_title[[462, 519, 534, 538]]
## BONUS  

text[[115, 560, 815, 600]]
19) Biology – Multiple Choice Which of the following amino acid mutations is LEAST LIKELY to be disruptive to protein function?  

text[[114, 622, 332, 705]]
W) Alanine to Valine  
X) Lysine to Glycine  
Y) Cysteine to Leucine  
Z) Aspartate to Tryptophan  

text[[115, 727, 432, 745]]
ANSWER: W) ALANINE TO VALINE  

sub_title[[456, 767, 540, 785]]
## TOSS-UP  

text[[114, 808, 868, 848]]
20) Chemistry – Multiple Choice A solution of which of the following compounds will give a VIOLET flame test?  

text[[114, 870, 285, 930]]
W) Lithium Bromide  
X) Sodium Chloride  
Y) Potassium Nitrate  

text[[114, 943, 232, 960]]
CSBL Playoff 3text[[114, 125, 228, 144]]
Z) Boric Acid  

text[[114, 165, 433, 185]]
ANSWER: Y) POTASSIUM NITRATE  

sub_title[[462, 209, 534, 227]]
## BONUS  

text[[113, 249, 865, 295]]
20) Chemistry - Short Answer How many sigma and pi bonds, respectively are present in the allene \(H_{2}CCCH_{2}\)  

text[[113, 317, 666, 338]]
ANSWER: 6 SIGMA, 2 PI (ACCEPT: 6, 2; DO NOT ACCEPT: 2, 6)  

sub_title[[455, 358, 541, 377]]
## TOSS-UP  

text[[113, 399, 872, 441]]
21) Physics - Short Answer What vector represents the magnitude and direction of the flow of energy in electromagnetic waves?  

text[[114, 461, 395, 481]]
ANSWER: POYNTING VECTOR  

sub_title[[462, 525, 534, 544]]
## BONUS  

text[[114, 565, 872, 628]]
21) Physics - Short Answer Weyl fermions are massless, whereas Dirac fermions do have mass. In addition, there is a third type of fermion, which is its own antiparticle. What is the term for this type of fermion?  

text[[114, 650, 412, 669]]
ANSWER: MAJORANA FERMION  

sub_title[[455, 690, 541, 709]]
## TOSS-UP  

text[[113, 730, 876, 772]]
22) Earth and Space - Multiple Choice Which of the following sedimentary rocks is composed of the finest grained particles?  

text[[114, 793, 260, 874]]
W) Conglomerate 
X) Mudstone 
Y) Sandstone 
Z) Breccia  

text[[114, 898, 346, 916]]
ANSWER: X) MUDSTONEsub_title[[462, 125, 534, 143]]
## BONUS  

text[[114, 165, 870, 249]]
22) Earth and Space – Short Answer Identify all of the following three statements that are true regarding trade winds: 1) They converge at the Intertropical Convergence Zone 2) In the Southern Hemisphere, they generally travel from west to east 3) They are responsible for transporting nutrient-rich sands from North Africa to the Americas  

text[[115, 270, 282, 288]]
ANSWER: 1 AND 3  

sub_title[[455, 311, 540, 329]]
## TOSS-UP  

text[[113, 351, 835, 371]]
23) Math – Short Answer How many types of polyhedra are classified as Platonic Solids?  

text[[115, 393, 220, 411]]
ANSWER: 5  

sub_title[[423, 435, 573, 454]]
## VISUAL BONUS  

text[[113, 476, 871, 516]]
23) Math – Short Answer Your parting gift for your participation in the CSBL is shown below. Answer the following 2 questions about this gift:  

image[[339, 520, 657, 757]]  

text[[127, 766, 840, 825]]
I. What is the name for this Platonic Solid?  
II. Given that this Platonic Solid has 20 faces and 12 vertices, how many edges must it have?  

text[[115, 848, 382, 866]]
ANSWER: ICOSAHEDRON, 30text[[115, 124, 847, 165]]
12) Biology – Multiple Choice MicroRNAs are short noncoding RNAs used to regulate gene expression. What type of gene regulation are microRNAs an example of?  

text[[115, 187, 303, 270]]
W) Pre-Transcriptional 
X) Post-Transcriptional 
Y) Pre-Translational 
Z) Post-Translational  

text[[115, 291, 469, 310]]
ANSWER: X) POST-TRANSCRIPTIONAL  

text[[115, 333, 854, 353]]
13) Earth and Space – Multiple Choice What body in the solar system has the highest albedo?  

text[[115, 355, 225, 435]]
W) Titan 
X) Miranda 
Y) Enceladus 
Z) Triton  

text[[115, 457, 352, 477]]
ANSWER: Y) ENCELADUS  

text[[115, 500, 861, 560]]
8) Math – Short Answer Amy has forgotten her phone password, which consists of four digits, each from 0-9. If she knows that it includes two 1's, one 6, and one other distinct digit, what is the maximum number of passwords she would need to check to unlock her phone?  

text[[115, 583, 230, 600]]
ANSWER: 96  

text[[115, 624, 840, 664]]
1) Chemistry – Short Answer What spectral series for hydrogen contains lines in the visible region of the spectrum?  

text[[115, 686, 363, 705]]
ANSWER: BALMER SERIES  

text[[115, 728, 875, 788]]
1) Physics – Multiple Choice A coin of mass \(m\) is dropped straight down from the top of a tall building. As the coin approaches terminal speed, which of the following statements is true of the net force on the coin  

text[[115, 811, 440, 830]]
W) The Net force on the Coin is Upward  

text[[115, 833, 373, 851]]
X) The net force on the coin is 0  

text[[115, 854, 680, 873]]
Y) The net force on the coin is downward, with a magnitude less than mg  

text[[115, 875, 690, 894]]
Z) The net force on the coin is downward, with a magnitude equal to mg.  

text[[115, 895, 860, 935]]
ANSWER: Y) THE NET FORCE ON THE COIN IS DOWNWARD, WITH A MAGNITUDE LESS THAN MG