sub_title[[455, 150, 540, 169]]
## TOSS-UP  

text[[115, 190, 778, 230]]
1) Biology – Short Answer Identify ALL of the following types of bacteria that are gram-positive:  

text[[121, 233, 357, 315]]
I. Staphylococcus aureus II. Cyanobacteria III. Bacillus Anthracis IV. Streptococcus  

text[[115, 337, 278, 355]]
ANSWER: I, III, IV  

sub_title[[462, 378, 534, 396]]
## BONUS  

text[[115, 419, 861, 481]]
1) Biology – Multiple Choice Joy has just got her hands on a brand new cell! She is studying the attachment of integrins to the extracellular matrix. Which of the following proteins would integrins most likely attach to?  

text[[115, 503, 207, 584]]
W) Dynein X) Actin Y) Myosin Z) Cyclin  

text[[115, 607, 295, 625]]
ANSWER: X) ACTIN  

sub_title[[455, 648, 540, 666]]
## TOSS-UP  

text[[115, 668, 816, 708]]
2) Chemistry – Short Answer Rank the following 3 elements in terms of INCREASING standard reduction potential:  

text[[121, 711, 262, 771]]
I. Chlorine II. Aluminum III. Mercury  

text[[115, 792, 270, 810]]
ANSWER: II, III, I  

sub_title[[462, 835, 534, 852]]
## BONUS  

text[[115, 876, 787, 916]]
2) Chemistry – Short Answer Order the following 4 diatomic molecules in terms of INCREASING order of bond strength.text[[123, 125, 202, 230]]
I. \(F_{2}\) II. \(C l_{2}\) III. \(N_{2}\) IV. \(O_{2}\)  

text[[115, 255, 299, 274]]
ANSWER: I, II, IV, III  

sub_title[[455, 315, 541, 333]]
## TOSS-UP  

text[[114, 356, 877, 438]]
3) Physics – Multiple Choice Two types of equations that are used to model fluid dynamics are Euler Equations and Navier-Stokes Equations. Although these two equations are mostly similar, they differ because Navier-Stokes accounts for what property of fluids that Euler Equations do not?  

text[[114, 461, 262, 543]]
W) Density  X) Specific Heat  Y) Type of Liquid  Z) Viscosity  

text[[115, 565, 337, 584]]
ANSWER: Z) VISCOSITY  

sub_title[[462, 606, 534, 625]]
## BONUS  

text[[114, 648, 850, 689]]
3) Physics – Short Answer Identify ALL of the following 3 conservation laws that would be violated when a neutron decays to a proton and electron:  

text[[120, 691, 432, 770]]
I. Conservation of Charge  
II. Conservation of Lepton Number  
III. Conservation of Spin  ANSWER: II AND III  

sub_title[[455, 813, 541, 831]]
## TOSS-UP  

text[[114, 854, 880, 936]]
4) Earth and Space – Short Answer Identify all of the following three statements that are TRUE regarding the Sun: 1) Gas at the equator orbits faster than at the poles 2) The Maunder Minimum was a period of reduced sunspot activity 3) The convective zone is closer to the core than the radiative zone  

text[[115, 943, 232, 960]]
CSBL Playoff 2text[[115, 146, 241, 163]]
ANSWER: 1, 2  

sub_title[[463, 188, 534, 206]]
## BONUS  

text[[115, 230, 844, 269]]
4) Earth and Space – Multiple Choice If an object has a parallax angle of 2.06 arc seconds, which of the following is closest to its distance in AU?  

text[[114, 291, 216, 372]]
W) \(1\mathrm{x}10^{\wedge}4\) X) \(2\mathrm{x}10^{\wedge}4\) Y) \(1\mathrm{x}10^{\wedge}5\) Z) \(2\mathrm{x}10^{\wedge}5\)  

text[[115, 395, 303, 413]]
ANSWER: Y) \(1\mathrm{x}10^{\wedge}5\)  

sub_title[[456, 436, 541, 454]]
## TOSS-UP  

text[[114, 477, 879, 516]]
5) Math – Multiple Choice An acute triangle ABC is inscribed in a circle with center at point O. If angle ABC is 50 degrees, what is angle AOC?  

text[[114, 539, 266, 639]]
W) 25 X) 50 Y) 100 Z) 130 ANSWER: Y) 100  

sub_title[[463, 683, 534, 701]]
## BONUS  

text[[114, 725, 854, 786]]
5) Math – Short Answer A right trapezoid SCBO has bases SC and BO, and angles SCB and CBO are each 90 degrees. Side CB has length 20, side OS has length 25, and the area of the trapezoid is 550. What is the length of the longer base?  

text[[115, 810, 230, 826]]
ANSWER: 35  

sub_title[[456, 850, 541, 867]]
## TOSS-UPtext[[114, 124, 870, 186]]
6) Energy – Multiple Choice Researchers at Ames Laboratory are studying the applications of high entropy alloys. Which of the following is NOT a property high entropy alloys usually possess that would make them desirable?  

text[[114, 208, 520, 290]]
W) They are usually made up of only two elements  
X) They are usually oxidation resistant  
Y) They are usually highly ductile  
Z) They have high fracture resistance  

text[[114, 311, 763, 330]]
ANSWER: W) THEY ARE USUALLY MADE UP OF ONLY TWO ELEMENTS  

sub_title[[462, 354, 534, 372]]
## BONUS  

text[[114, 395, 847, 477]]
6) Energy – Short Answer Researchers at Fermilab are studying elementary particles. They hypothesize that the gravitational force, like the electromagnetic force, is carried by a boson. Answer the following two questions about this hypothetical particle: 1) What is it called? 2) What would have to be its spin?  

text[[115, 499, 330, 517]]
ANSWER: GRAVITON, 2  

sub_title[[456, 540, 541, 558]]
## TOSS-UP  

text[[114, 580, 852, 641]]
7) Biology – Short Answer Adrian has just finished writing this packet, and he feels hungry. What hormone, released by the walls of the stomach to increase hunger, and is suppressed by PYY, is being released right now?  

text[[115, 664, 297, 682]]
ANSWER: GHRELIN  

sub_title[[462, 706, 534, 724]]
## BONUS  

text[[114, 746, 848, 787]]
7) Biology – Short Answer Identify all of the following three types of plant tissue that have secondary cell walls:  

text[[125, 810, 288, 870]]
I. Sclerenchyma  
II. Collenchyma  
III. Parenchyma  

text[[115, 893, 283, 910]]
ANSWER: I AND IIsub_title[[455, 125, 541, 144]]
## TOSS-UP  

text[[114, 166, 859, 227]]
8) Chemistry – Short Answer For an endothermic reaction to be spontaneous under standard conditions at constant pressure at some pressure T, which of the following statements must be true.  

text[[114, 250, 732, 330]]
W) The entropy change must be NEGATIVE and GREATER than - Delta H/T  
X) The entropy change must be NEGATIVE and LESS than - Delta H/T  
Y) The entropy change must be POSITIVE and GREATER than Delta H/T  
Z) The entropy change must be POSITIVE and LESS than Delta H/T  

text[[114, 373, 835, 412]]
ANSWER: Y) THE ENTROPY CHANGE MUST BE POSITIVE AND GREATER THAN DELTA H/T  

image[[185, 416, 728, 667]]  

text[[114, 679, 844, 760]]
8) Chemistry – Multiple Choice Shown below is a graph of forwards and reverse rates of a reaction as a function of time. At time t, a catalyst is added to the system, and the forward reaction rate proceeds as indicated by the solid curve. Which of the following curves best indicates how the reverse reaction rate changes over time?  

text[[114, 782, 213, 862]]
W) Curve A  
X) Curve B  
Y) Curve C  
Z) Curve D  

text[[115, 886, 323, 903]]
ANSWER: W) CURVE Asub_title[[455, 125, 541, 143]]
## TOSS-UP  

text[[113, 166, 864, 206]]
9) Physics – Multiple Choice Which of the following statements best describes what happens as a traveling wave reflects off a wall that IS NOT fixed?  

text[[114, 230, 533, 311]]
W) It reflects with inversion  X) It reflects without inversion  Y) It interferes with the incident wave constructively  Z) It interferes with the incident wave destructively  

text[[114, 333, 562, 352]]
ANSWER: X) IT REFLECTS WITHOUT INVERSION  

sub_title[[462, 374, 535, 393]]
## BONUS  

text[[114, 415, 849, 456]]
9) Physics – Short Answer What is the rotational inertia of a thin rod about a pivot \(\frac{1}{2}\) of the distance from the end, with uniform mass density?  

text[[114, 479, 266, 505]]
ANSWER: \(\frac{1}{9} ML^2\)  

sub_title[[455, 550, 541, 568]]
## TOSS-UP  

text[[114, 590, 881, 653]]
10) Earth and Space – Multiple Choice Arin observes an earthquake of magnitude 5 on the moment magnitude scale, that releases energy X. If he later observes an earthquake of magnitude 6, in terms of X, approximately how much energy is released by the second earthquake?  

text[[114, 675, 179, 755]]
W) 4X  X) 8X  Y) 16X  Z) 32X  

text[[114, 779, 268, 797]]
ANSWER: Z) 32X  

sub_title[[462, 821, 535, 839]]
## BONUS  

text[[114, 861, 881, 901]]
10) Earth and Space – Short Answer What is the name for patterns found in the cross section of iron meteorites when they are opened up?text[[115, 123, 814, 143]]
ANSWER: WIDMANSTÄTTEN PATTERNS (ACCEPT: THOMSON STRUCTURES)  

sub_title[[455, 165, 541, 184]]
## TOSS-UP  

text[[115, 205, 876, 247]]
11) Math – Multiple Choice Given an inflection point for a certain cubic function, how many more points on the function's graph would you need to know to completely determine the cubic?  

text[[115, 267, 159, 350]]
W) 0 X) 1 Y) 2 Z) 3  

text[[115, 372, 245, 391]]
ANSWER: Y) 2  

sub_title[[462, 415, 533, 433]]
## BONUS  

text[[115, 455, 872, 560]]
11) Math – Short Answer A train carries a certain number of passengers. At its first stop, \(15\%\) of passengers leave the train. At the second stop, 49 passengers get off the train. At the third and final stop, all remaining passengers get off the train. The number of passengers who left at the first stop happened to be the same number of passengers who left at the third stop. How many passengers were originally on the train?  

text[[115, 581, 231, 599]]
ANSWER: 70  

sub_title[[455, 641, 540, 660]]
## TOSS-UP  

text[[115, 682, 861, 765]]
12) Energy – Short Answer Researchers at Los Alamos National Laboratory have been using the Curiosity rover to study the history of water on Mars. When water flowed on Mars, long channels are thought to have been formed by outburst floods. What is the name for these channels?  

text[[115, 787, 416, 806]]
ANSWER: OUTFLOW CHANNELS  

sub_title[[462, 829, 533, 848]]
## BONUS  

text[[115, 870, 847, 911]]
12) Energy – Short Answer Researchers at Lawrence Berkeley National Laboratory are studying the hydrological cycle and its energy applications. A point of study is the differencetext[[113, 124, 860, 163]]
between types of aquifers. What type of aquifer has impermeable layers both above and below it?  

text[[115, 187, 400, 205]]
ANSWER: CONFINED AQUIFER  

sub_title[[455, 228, 540, 246]]
## TOSS-UP  

text[[115, 268, 837, 310]]
13) Biology – Multiple Choice Which of the following plant hormones play a role in fruit ripening?  

text[[114, 331, 275, 412]]
W) Abscisic Acid X) Cytokinins Y) Brassinosteroids Z) Gibberellins  

text[[115, 435, 375, 454]]
ANSWER: Z) GIBBERELLINS  

sub_title[[462, 478, 534, 496]]
## BONUS  

text[[115, 518, 857, 558]]
13) Biology – Short Answer Identify ALL of the following statements that are true about C3 and C4 plants:  

text[[123, 560, 870, 664]]
I. Rubisco performs initial carbon fixation in C3, but PEPase performs initial carbon fixation in C4II. C3 plants lose water and energy through photorespiration, whereas C4 plants have a low photorespiration rateIII. Both plants initially accept carbon dioxide  

text[[115, 686, 247, 704]]
ANSWER: ALL  

sub_title[[455, 725, 540, 744]]
## TOSS-UP  

text[[115, 766, 867, 807]]
14) Chemistry – Multiple Choice Which of the following compounds have the highest normal boiling point?  

text[[114, 829, 311, 910]]
W) 1-Butanol X) 2-Butanol Y) 2- Methyl-1-Propanol Z) 2- Methyl-2-Propanoltext[[115, 125, 349, 143]]
ANSWER: W) 1- BUTANOL  

sub_title[[462, 168, 535, 186]]
## BONUS  

text[[115, 208, 846, 248]]
14) Chemistry – Multiple Choice Which of the following compounds can exhibit geometric isomerism?  

text[[114, 270, 217, 353]]
W) 1-butene  X) 2-butene  Y) 1-butyne  Z) 2-butyne  

text[[115, 375, 330, 394]]
ANSWER: X) 2- BUTENE  

sub_title[[456, 456, 541, 474]]
## TOSS-UP  

text[[115, 497, 792, 537]]
15) Physics – Short Answer A concave mirror has a radius of curvature of 78 cm. In centimeters, what is its focal length?  

text[[115, 560, 266, 578]]
ANSWER: 39 CM  

sub_title[[462, 602, 535, 620]]
## BONUS  

text[[115, 642, 847, 704]]
15) Physics – Short Answer Adrian is playing with his new train set! He wants to make the train go faster and faster, and his dream is to get it near the speed of light. If he can make the train go 50% of the speed of light, by what percent is time slowed down?  

text[[115, 727, 370, 755]]
ANSWER: \(\frac{\sqrt{3}}{2}\) (ACCEPT: 87%)  

sub_title[[456, 799, 541, 817]]
## TOSS-UP  

text[[115, 840, 847, 880]]
16) Earth and Space – Short Answer The rings of Uranus were discovered in 1977, when it passed in front of a distant star. What is the name for this kind of event?  

text[[115, 903, 345, 921]]
ANSWER: OCCULTATION  

text[[115, 943, 232, 960]]
CSBL Playoff 2sub_title[[462, 147, 534, 165]]
## BONUS  

text[[114, 187, 870, 228]]
16) Earth and Space – Short Answer What principle states that on a large enough scale, matter in the Universe is homogeneous and isotropic?  

text[[114, 250, 470, 269]]
ANSWER: COSMOLOGICAL PRINCIPLE  

sub_title[[455, 310, 540, 328]]
## TOSS-UP  

text[[114, 351, 852, 393]]
17) Math – Short Answer If the integral from 1 to 4 of \(f(x) dx = 29\), then what is the definite integral from 1 to 4 of \((f(x) - 5)dx\)  

text[[114, 414, 231, 432]]
ANSWER: 14  

sub_title[[462, 457, 534, 475]]
## BONUS  

text[[114, 497, 864, 537]]
17) Math – Short Answer What is the area of an equilateral triangle whose circumcircle has a radius of 4?  

text[[114, 561, 256, 581]]
ANSWER: \(12\sqrt{3}\)  

sub_title[[455, 603, 540, 621]]
## TOSS-UP  

text[[114, 644, 856, 707]]
18) Energy – Short Answer Researchers at Oak Ridge National Laboratory are studying the potential of quantum computers. Quantum bits, or qubits, cannot be directly observed without using their unique properties. What principle allows for qubits to be observed?  

text[[114, 728, 475, 747]]
ANSWER: QUANTUM ENTANGLEMENT  

sub_title[[462, 770, 534, 788]]
## BONUS  

text[[114, 811, 877, 894]]
18) Energy – Short Answer Researchers at Lawrence Livermore National Lab are studying the formation of the early solar system. The classification of meteorites is a particular point of focus. What type of stony meteorite is characterized by high levels of water content and organic material, as well as large round grains called chondrules?  

text[[114, 915, 500, 934]]
ANSWER: CARBONACEOUS CHONDRITES  

text[[114, 943, 232, 960]]
CSBL Playoff 2sub_title[[455, 144, 541, 162]]
## TOSS-UP  

text[[115, 185, 876, 226]]
19) Biology - Short Answer During translation in prokaryotes, the Shine-Dalgarno sequence is the binding site for what organelle?  

text[[115, 247, 312, 265]]
ANSWER: RIBOSOME  

sub_title[[462, 290, 535, 308]]
## BONUS  

text[[115, 331, 875, 393]]
19) Biology - Short Answer If you're wondering why this packet was written so late, it's because Arin was just recovering from his booster dose. A booster dose of a vaccination helps to increase blood antibody levels by increasing the number of what type of cells?  

text[[115, 414, 375, 432]]
ANSWER: EFFECTOR CELLS  

sub_title[[455, 476, 541, 494]]
## TOSS-UP  

text[[115, 516, 852, 558]]
20) Chemistry - Short Answer Rank the following 4 ionic solids in terms of INCREASING melting point:  

text[[123, 560, 220, 639]]
I. NaF 
II. MgO 
III. KBr 
IV. NaCl  

text[[115, 662, 299, 681]]
ANSWER: III, IV, I, II  

sub_title[[462, 705, 535, 723]]
## BONUS  

text[[115, 745, 830, 787]]
20) Chemistry - Multiple Choice For which of the following reactions would the yield of products at equilibrium NOT increase at higher pressure?  

equation[[115, 807, 544, 914]]
\[\mathrm{W)~}T i(s) + 2C l_{2}(g)\Leftrightarrow T i c l_{4}(g)\] \[\mathrm{X)~}N_{2}(g) + O_{2}(g)\Leftrightarrow 2N O(g)\] \[\mathrm{Y)~}4H C l(g) + O_{2}(g)\Leftrightarrow 2H_{2}O(l) + 2C l_{2}(g)\] \[\mathrm{Z)~}2C_{2}H_{4}(g) + 2H_{2}O(g)\Leftrightarrow 2C_{2}H_{6}(g) + O_{2}(g)\]text[[114, 123, 481, 147]]
ANSWER: X) \(N_{2}(g) + O_{2}(g) \Leftrightarrow 2NO(g)\)  

sub_title[[455, 171, 541, 190]]
## TOSS-UP  

text[[114, 212, 822, 253]]
21) Physics – Short Answer Identify all of the following quantities that Kirchoff’s Laws address:  

text[[125, 255, 264, 336]]
I. Inductance  
II. Resistance  
III. Current  
IV. Voltage  

text[[115, 358, 303, 376]]
ANSWER: III AND IV  

image[[137, 448, 850, 800]]  

text[[114, 812, 882, 875]]
21) Physics – Short Answer Shown below is a new circuit that Kyle formed based on his earlier parts. Given the resistance for each of the resistors shown above, what is the voltage passing through each of the resistors respectively?  

text[[114, 895, 512, 914]]
ANSWER: \(\mathrm{V}1 = 2\mathrm{V}; \mathrm{V}2 = 4\mathrm{V}; \mathrm{V}3 = 8\mathrm{V}; \mathrm{V}4 = 4\mathrm{V}\)sub_title[[455, 125, 541, 143]]
## TOSS-UP  

text[[113, 166, 870, 207]]
22) Earth and Space – Multiple Choice What type of metamorphism would be associated with the collision of two crustal blocks and areas of orogeny?  

text[[113, 230, 215, 310]]
W) Burial  X) Regional  Y) Contact  Z) Impact  

text[[115, 333, 338, 352]]
ANSWER: X) REGIONAL  

sub_title[[462, 374, 534, 393]]
## BONUS  

text[[115, 415, 870, 456]]
22) Earth and Space – Short Answer What type of erosion involves a stream deepening due to material being removed from the streambed?  

text[[115, 479, 358, 497]]
ANSWER: DOWNCUTTING  

sub_title[[455, 540, 541, 558]]
## TOSS-UP  

text[[113, 580, 875, 621]]
23) Math – Short Answer What is the determinant of the 2-by-2 matrix with first row -2, -4 and second row 4, 9  

text[[115, 643, 228, 662]]
ANSWER: - 2  

sub_title[[462, 685, 535, 703]]
## BONUS  

text[[113, 726, 832, 767]]
23) Math – Short Answer What is the sum of the first 5 terms in the increasing geometric sequence with first term 2 and third term 32?  

text[[115, 789, 240, 807]]
ANSWER: 682