sub_title[[456, 145, 540, 162]]
## TOSS-UP  

text[[115, 189, 848, 230]]
1) Biology – Short Answer What cells produce testosterone in response to stimulation from luteinizing hormone?  

text[[115, 253, 350, 272]]
ANSWER: LEYDIG CELLS  

sub_title[[462, 296, 535, 314]]
## BONUS  

text[[115, 338, 847, 358]]
1) Biology – Short Answer Identify ALL of the following that are formed from tryptophan:  

text[[124, 380, 258, 459]]
I. Auxin  
II. Melatonin  
III. Serotonin  
IV. Melanin  

text[[115, 483, 479, 501]]
ANSWER: I, II, III (ACCEPT: ALL BUT IV)  

sub_title[[456, 544, 540, 562]]
## TOSS-UP  

text[[113, 586, 830, 605]]
2) Chemistry – Short Answer Identify ALL of the following that are intensive properties:  

text[[128, 608, 325, 667]]
I. Helmholtz Energy  
II. Gibbs Free Energy  
III. Entropy  

text[[115, 690, 265, 707]]
ANSWER: NONE  

sub_title[[462, 730, 535, 748]]
## BONUS  

text[[115, 772, 848, 812]]
2) Chemistry – Multiple Choice On a phase diagram, if the solid-liquid boundary line has a POSITIVE slope, which of the following statements is TRUE:  

text[[114, 835, 513, 916]]
W) Its Liquid Phase is Denser than its Solid Phase  
X) Its Solid Phase is Denser than its Liquid Phase  
Y) It can never form a supercooled fluid  
Z) It can never form a supercritical fluidtext[[113, 123, 732, 143]]
ANSWER: X) ITS SOLID PHASE IS DENSER THAN ITS LIQUID PHASE  

sub_title[[455, 186, 541, 205]]
## TOSS-UP  

text[[113, 226, 860, 268]]
3) Physics – Multiple Choice Which of the following magnifications CANNOT be produced using a single CONVERGING lens?  

text[[113, 289, 164, 370]]
W) 1/2 X) 2 Y) - 1/2 Z) - 2  

text[[114, 393, 256, 412]]
ANSWER: W) 1/2  

sub_title[[463, 436, 534, 454]]
## BONUS  

text[[113, 477, 879, 539]]
3) Physics – Multiple Choice Arin has just discovered a new mineral! When light travels from air to this mineral, which has an index of refraction of 0.58, at which of the following angles will the reflected ray be maximally polarized?  

text[[113, 560, 233, 641]]
W) 15 degrees X) 30 degrees Y) 45 degrees Z) 60 degrees  

text[[114, 663, 350, 682]]
ANSWER: X) 30 DEGREES  

sub_title[[455, 725, 541, 744]]
## TOSS-UP  

text[[113, 766, 822, 807]]
4) ESS – Short Answer What type of cooling, characterized by the conservation of heat, primarily causes cloud formation?  

text[[114, 829, 315, 848]]
ANSWER: ADIABATIC  

sub_title[[463, 871, 534, 889]]
## BONUStext[[113, 124, 863, 164]]
4) ESS – Short Answer Identify all of the following storm scales that use damage as a way to categorize storms:  

text[[128, 168, 321, 227]]
I. Saffir-Simpson 
II. Enhanced Fujita 
III. Modified Mercalli  

text[[115, 250, 281, 268]]
ANSWER: II ONLY  

sub_title[[456, 290, 541, 308]]
## TOSS-UP  

text[[114, 331, 868, 380]]
5) Math – Short Answer Giving your answer in standard form, what is the equation of the line tangent to \(x^{2} + y^{2} = 169\) at the point (5,12)  

text[[115, 399, 785, 420]]
ANSWER: \(5x + 12y = 169\) (ACCEPT \(12y + 5x = 169\) , do not accept any other form)  

sub_title[[463, 440, 535, 459]]
## BONUS  

text[[114, 482, 760, 529]]
5) Math – Multiple Choice How many points with integer coordinates are in the interior of the circle whose equation is given by \(x^{2} + y^{2} = 13\)  

text[[114, 551, 166, 631]]
W) 31 
X) 37 
Y) 41 
Z) 47  

text[[115, 655, 256, 673]]
ANSWER: X) 37  

sub_title[[456, 736, 541, 754]]
## TOSS-UP  

text[[114, 778, 865, 860]]
6) Energy – Short Answer Scientists at the National Renewable Energy Lab are studying the usage of perovskites in photovoltaic devices. However, the crystal structure of perovskites may trap electrons. What quasiparticles, which are collective excitations within the structure, may explain this?  

text[[115, 883, 303, 900]]
ANSWER: PHONONSsub_title[[463, 125, 534, 144]]
## BONUS  

text[[114, 166, 865, 228]]
6) Energy - Short Answer Scientists at Frederick National Lab are developing ways to slow cancer progression. These techniques often involve targeting of what protein family, known for playing a role in cancer types when mutated or overexpressed?  

text[[115, 250, 295, 268]]
ANSWER: CATENIN  

sub_title[[456, 290, 541, 309]]
## TOSS-UP  

text[[114, 331, 850, 372]]
7) Biology - Short Answer Identify ALL of the following organs that are part of the female reproductive system in a flower:  

text[[124, 374, 250, 453]]
I. Anther 
II. Sepal 
III. Style 
IV. Filament  

text[[115, 476, 288, 495]]
ANSWER: III ONLY  

sub_title[[463, 519, 534, 538]]
## BONUS  

text[[115, 560, 861, 621]]
7) Biology - Short Answer John and Jill are getting married! If they are heterozygous in four genes that all follow a dominant-recessive inheritance pattern, what is the probability that the resulting child will be homozygous dominant for at least one trait?  

text[[115, 643, 276, 661]]
ANSWER: 175/256  

sub_title[[456, 704, 541, 723]]
## TOSS-UP  

text[[115, 745, 861, 786]]
8) Chemistry - Short Answer What is the term for a covalent bond between a Lewis acid and Lewis Base, characterized by both electrons migrating from the base?  

text[[115, 807, 738, 827]]
ANSWER: DATIVE BOND (ACCEPT: COORDINATE COVALENT BOND)  

sub_title[[463, 850, 534, 868]]
## BONUS  

text[[115, 891, 867, 931]]
8) Chemistry - Multiple Choice On a cubic unit cell, there are atoms on ALL of the corners, 4 of the faces, and in the center. How many atoms are contained within this unit cell?text[[113, 125, 168, 205]]
W) 13 
X) 4 
Y) 2 
Z) 1  

text[[114, 230, 247, 247]]
ANSWER: X) 4  

sub_title[[456, 290, 540, 309]]
## TOSS-UP  

text[[113, 331, 850, 372]]
9) Physics – Short Answer In a heat engine, the state of the working substance traces out a closed path on a PV diagram. What quantity is represented by the area enclosed by this path?  

text[[114, 393, 270, 411]]
ANSWER: WORK  

sub_title[[462, 437, 535, 455]]
## BONUS  

text[[113, 477, 870, 538]]
9) Physics – Multiple Choice A parallel plate capacitor with plate area of A and plate separation d has a capacitance of C. If the plate area is doubled to 2A and the plate separation is halved to d/2, what is the new capacitance, in terms of C?  

text[[113, 560, 176, 640]]
W) C 
X) 2C 
Y) 4C 
Z) 16C  

text[[114, 664, 259, 682]]
ANSWER: Y) 4C  

sub_title[[456, 725, 540, 743]]
## TOSS-UP  

text[[113, 766, 880, 806]]
10) ESS – Short Answer Rank the following 3 components of the Sun’s atmosphere in terms of INCREASING temperature:  

text[[127, 809, 293, 868]]
I. Chromosphere 
II. Corona 
III. Photosphere  

text[[114, 891, 270, 909]]
ANSWER: III, I, IIsub_title[[462, 126, 533, 144]]
## BONUS  

text[[114, 166, 855, 249]]
10) ESS - Short Answer Joy has just discovered 2 new planets: Thanksgiving and Christmas. She observes that the period of Thanksgiving is X years and it's semimajor axis is Y AU. She's also determined that the period of Christmas is 8X years, but she's having trouble locating Christmas. Based on this data, in terms of Y, what is the semimajor axis of Christmas?  

text[[115, 270, 234, 288]]
ANSWER: 4Y  

sub_title[[456, 310, 540, 328]]
## TOSS-UP  

text[[114, 351, 867, 392]]
11) Math - Multiple Choice Every angle in a convex polygon is summed EXCEPT for one of them, and the result is 650 degrees. In degrees, what is the last angle?  

text[[114, 414, 262, 515]]
W) 70  X) 90  Y) 110  Z) 130  ANSWER: W) 70  

sub_title[[462, 540, 533, 558]]
## BONUS  

text[[114, 580, 877, 662]]
11) Math - Short Answer Adrian runs at a constant speed of 21 miles per hour. He starts to run for one hour, and after this hour elapses, he turns around and runs for 30 minutes. He repeats this process 2021 times, running for half of the previous time every time. To the nearest integer, how many miles is Adrian from his starting point?  

text[[115, 685, 231, 703]]
ANSWER: 14  

sub_title[[456, 767, 540, 785]]
## TOSS-UP  

text[[114, 807, 877, 890]]
12) Energy - Short Answer Scientists at Argonne National Lab are developing a probe that can sense neurotransmitters in the brain. This will allow for the investigation of neurobiological mechanisms and disease symptoms of various brain disorders. It may also be able to detect hypoxia in the brain, which causes what physiological condition?  

text[[115, 911, 287, 929]]
ANSWER: STROKE  

text[[115, 943, 228, 959]]
CSBL Round 6sub_title[[463, 146, 535, 165]]
## BONUS  

text[[115, 187, 821, 250]]
12) Energy – Short Answer Scientists at SLAC National Lab are studying the electronic structure of a metalloporphyrin ion through L-edge spectroscopy. The metal center in a metalloporphyrin is coordinated to 4 atoms of what element?  

text[[114, 271, 222, 353]]
W) Nitrogen  X) Oxygen  Y) Hydrogen  Z) Iron  

text[[115, 375, 342, 393]]
ANSWER: W) NITROGEN  

sub_title[[456, 414, 541, 432]]
## TOSS-UP  

text[[115, 455, 800, 475]]
13) Biology – Multiple Choice Which of the following diseases is caused by a virus?  

text[[115, 477, 215, 495]]
W) Malaria  

text[[115, 499, 189, 515]]
X) Ebola  

text[[115, 520, 262, 537]]
Y) Toxoplasmosis  

text[[115, 541, 266, 558]]
Z) Bubonic Plague  

text[[115, 581, 301, 599]]
ANSWER: X) EBOLA  

sub_title[[463, 621, 533, 640]]
## BONUS  

text[[115, 663, 833, 683]]
13) Biology – Short Answer Identify ALL of the following 3 diseases that are sex-linked:  

text[[121, 685, 424, 744]]
I. Duchenne Muscular Dystrophy  
II. Hemophilia  
III. Rett Syndrome  

text[[115, 767, 247, 785]]
ANSWER: ALL  

sub_title[[456, 807, 540, 825]]
## TOSS-UP  

text[[115, 848, 866, 887]]
14) Chemistry – Multiple Choice Which of the following conditions will result in the LEAST IDEAL GAS?  

text[[115, 891, 440, 910]]
W) High Pressure and High Temperature  

text[[115, 912, 428, 930]]
X) Low Pressure and Low Temperature  

text[[115, 943, 229, 959]]
CSBL Round 6text[[113, 125, 435, 164]]
Y) Low Pressure and High TemperatureZ) High Pressure and Low Temperature  

text[[115, 187, 626, 206]]
ANSWER: Z) HIGH PRESSURE AND LOW TEMPERATURE  

sub_title[[462, 250, 534, 268]]
## BONUS  

text[[115, 291, 874, 331]]
14) Chemistry - Short Answer The Van der Waals equation has two parameters \(a\) and \(b\) , which are modifications from the Ideal Gas equation. What do these two parameters correct for?  

text[[115, 353, 832, 393]]
ANSWER: IMFS and VOLUME OF GAS (ACCEPT DESCRIPTIONS AND INVERTED ORDER)  

sub_title[[456, 437, 540, 455]]
## TOSS-UP  

text[[115, 477, 854, 516]]
15) Physics - Short Answer Identify ALL of the following three quantities that change for a system in STATIC equilibrium:  

text[[123, 520, 325, 579]]
I. Force 
II. Torque 
III. Linear Momentum  

text[[115, 582, 266, 599]]
ANSWER: NONE  

sub_title[[462, 623, 534, 640]]
## BONUS  

text[[115, 664, 842, 703]]
15) Physics - Short Answer Identify ALL of the following three statements that are TRUE regarding bodies under stress:  

text[[124, 706, 720, 765]]
I. They are permanently deformed past their yield strengthII. They can return to their original form past their compressive strengthIII. In the elastic region, the stress-strain curve is linear  

text[[115, 789, 275, 807]]
ANSWER: I and III  

sub_title[[456, 850, 540, 867]]
## TOSS-UP  

text[[115, 871, 875, 910]]
16) ESS - Short Answer What element is characterized by a doublet in its spectrum at 588 and 589 nanometers?text[[115, 125, 288, 143]]
ANSWER: SODIUM  

sub_title[[462, 168, 534, 186]]
## BONUS  

text[[112, 208, 852, 229]]
16) ESS – Multiple Choice Which of the following is characteristic of a Type Ia supernova?  

text[[113, 250, 670, 343]]
W) Strong silicon line at \(615~\mathrm{nm}\) , no hydrogen lines  X) Strong silicon line at \(615~\mathrm{nm}\) and additional hydrogen lines  Y) Strong iron line at \(810~\mathrm{nm}\) , no hydrogen lines  Z) Strong hydrogen lines  

text[[115, 366, 671, 387]]
ANSWER: W) Strong silicon line at \(615~\mathrm{nm}\) , no hydrogen lines  

sub_title[[456, 406, 541, 425]]
## TOSS-UP  

text[[115, 448, 857, 490]]
17) Math – Multiple Choice In 2021, March 1st fell on a Monday. What is the next year that March 1st will fall on a Monday?  

text[[115, 512, 189, 593]]
W) 2026  X) 2027  Y) 2028  Z) 2029  

text[[115, 615, 276, 635]]
ANSWER: X) 2027  

sub_title[[462, 657, 534, 675]]
## BONUS  

text[[115, 699, 864, 740]]
17) Math – Short Answer What is the distance between the two polar coordinates (8, 120) and (6,0)  

text[[115, 763, 255, 784]]
ANSWER: \(2\sqrt{37}\)  

sub_title[[456, 805, 540, 823]]
## TOSS-UP  

text[[115, 846, 862, 909]]
18) Energy – Multiple Choice Scientists at Berkeley Analytical, a part of Berkeley Lab, have recently begun emission testing for VOCS, or volatile organic compounds. Which of the following compounds is a VOC?text[[113, 145, 325, 247]]
W) Carbon MonoxideX) PolyethyleneY) Carbon DioxideZ) BenzeneANSWER: Z) BENZENE  

sub_title[[463, 270, 535, 289]]
## BONUS  

text[[114, 311, 844, 373]]
18) Energy - Short Answer Scientists at Los Alamos National Lab are researching ways to mitigate wildland fires. Wildfires such as these are seen as a missing source of what carbon-containing compound, and catalyzes the formation of peptides from amino acids?  

text[[114, 394, 545, 413]]
ANSWER: CARBONYL SULFIDE (ACCEPT: OCS)  

sub_title[[456, 456, 540, 474]]
## TOSS-UP  

text[[114, 496, 865, 558]]
19) Biology - Short Answer Help! Arin's grandma has fallen and can't get up! She was taken to the hospital, where she was diagnosed with an injury to the substantia nigra and a lack of dopamine release. What neurologic disease will she likely exhibit symptoms of?  

text[[114, 580, 425, 599]]
ANSWER: PARKINSON'S DISEASE  

sub_title[[463, 621, 533, 640]]
## BONUS  

text[[114, 662, 872, 704]]
19) Biology - Short Answer During apoptosis, the release of what iron-coordinating protein in mitochondria leads to the activation of caspase enzymes?  

text[[114, 725, 365, 744]]
ANSWER: CYTOCHROME C  

sub_title[[456, 787, 540, 805]]
## TOSS-UP  

text[[113, 828, 812, 868]]
20) Chemistry - Multiple Choice Which of the following graphs represent a first-order reaction?  

text[[113, 891, 788, 931]]
W) A graph of concentration vs time, which is linearX) A graph of concentration of products vs concentration of reactants, which is lineartext[[113, 125, 666, 164]]
Y) A graph of the natural log of concentration vs time, which is linearZ) A graph of the reciprocal of concentration vs time, which is linear  

text[[113, 187, 757, 207]]
ANSWER: Y) A graph of the natural log of concentration vs time, which is linear  

sub_title[[463, 250, 534, 268]]
## BONUS  

text[[113, 291, 876, 352]]
20) Chemistry - Short Answer Consider a zeroth-order reaction with a single aqueous reactant, X. If the initial concentration of X is 2 molar, and the half-life at this time is 10 seconds, how many seconds will elapse before the concentration is 0.5 molar.  

text[[114, 375, 230, 392]]
ANSWER: 15  

sub_title[[456, 415, 541, 433]]
## TOSS-UP  

text[[113, 456, 867, 496]]
21) Physics - Short Answer Identify ALL of the following types of materials that have higher resistance at higher temperatures:  

text[[125, 499, 296, 558]]
I. Insulator 
II. Semiconductor 
III. Conductor  

text[[114, 581, 288, 599]]
ANSWER: III ONLY  

sub_title[[463, 622, 534, 640]]
## BONUS  

text[[113, 664, 877, 724]]
21) Physics - Short Answer Two solid spheres of radius r are in contact with each other. Given UNIFORM DENSITY, the gravitational force between the spheres is proportional to what power of r?  

text[[114, 748, 220, 765]]
ANSWER: 4  

sub_title[[456, 807, 540, 825]]
## TOSS-UP  

text[[111, 848, 852, 868]]
22) ESS - Short Answer Identify ALL of the following cycles that are Milankovitch cycles:  

text[[124, 870, 270, 930]]
I. Eccentricity 
II. Obliquity 
III. Precession  

text[[114, 944, 228, 960]]
CSBL Round 6text[[115, 125, 248, 143]]
ANSWER: ALL  

sub_title[[462, 167, 535, 185]]
## BONUS  

text[[112, 208, 795, 228]]
22) ESS – Multiple Choice Which of the following is closest to a lunar synodic day?  

text[[114, 250, 338, 330]]
W) 12 hours  X) 12 hours and 25 minutes  Y) 24 hours  Z) 24 hours and 50 minutes  

text[[114, 353, 489, 373]]
ANSWER: Z) 24 HOURS AND 50 MINUTES  

sub_title[[456, 456, 541, 474]]
## TOSS-UP  

text[[113, 497, 770, 525]]
23) Math – Short Answer What is the derivative with respect to x of \(\mathrm{f(x) = \frac{sin(x)}{tan(x)}}\)  

text[[114, 548, 288, 567]]
ANSWER: - sin(x)  

sub_title[[462, 590, 535, 609]]
## BONUS  

text[[113, 631, 875, 671]]
23) Math – Short Answer What is the radius of a circle inscribed in a triangle with side lengths of 13, 15, and 18  

text[[114, 695, 271, 725]]
ANSWER: \(\frac{20\sqrt{23}}{23}\)