text[[120, 149, 875, 170]]
Icebreaker question: If you could magically become fluent in any language, what would it be?  

sub_title[[455, 185, 541, 204]]
## TOSS-UP  

text[[115, 221, 860, 259]]
1) Physical Science – Short Answer What measurement, with units of kilojoules per mol, is used to indicate the thermodynamic favorability of a reaction?  

text[[115, 275, 637, 295]]
ANSWER: GIBBS (ACCEPT: GIBBS FREE ENERGY, G) [NR]  

sub_title[[462, 312, 533, 331]]
## BONUS  

text[[115, 349, 850, 404]]
1) Physical Science – Short Answer A five-liter gas held at constant pressure has a temperature of 27 celsius. What would the temperature be, in Kelvin, if the gas underwent an expansion to 10 liters?  

text[[115, 421, 286, 441]]
ANSWER: 600 [NR]  

sub_title[[455, 498, 540, 516]]
## TOSS-UP  

text[[114, 533, 794, 571]]
2) Math – Multiple Choice Which of the following numbers is not considered to be triangular?  

text[[114, 588, 166, 660]]
W) 21 
X) 28 
Y) 35 
Z) 45  

text[[115, 678, 301, 697]]
ANSWER: Y) 35 [NR]  

sub_title[[462, 715, 533, 734]]
## BONUS  

text[[115, 751, 875, 789]]
2) Math – Short Answer What is the coefficient of the x squared y cubed term in the binomial expansion of the quantity 2x plus y to the 5th power?  

text[[115, 807, 276, 826]]
ANSWER: 40 [NR]sub_title[[455, 91, 540, 108]]
## TOSS-UP  

text[[114, 130, 836, 185]]
3) Life Science – Multiple Choice The overall protein structure that results from the combination of many polypeptide subunits can be best described by which of the following levels of protein structure?  

text[[114, 204, 230, 280]]
W) Primary  X) Secondary  Y) Tertiary  Z) Quaternary  

text[[115, 298, 415, 317]]
ANSWER: Z) QUATERNARY [DB]  

sub_title[[462, 336, 533, 354]]
## BONUS  

text[[115, 371, 866, 409]]
3) Life Science – Short Answer If a black-furred sheep mates with a white-furred sheep, and produces gray-furred offspring, what type of dominance is exhibited?  

text[[115, 427, 380, 446]]
ANSWER: INCOMPLETE [DB]  

sub_title[[455, 501, 540, 519]]
## TOSS-UP  

text[[115, 536, 821, 573]]
4) Earth and Space – Short Answer Travertine, crystalline limestone, and chalk are all derived from what rock-forming mineral?  

text[[115, 592, 507, 611]]
ANSWER: CALCITE (ACCEPT: CACO3) [DB]  

sub_title[[462, 629, 533, 647]]
## BONUS  

text[[115, 666, 870, 704]]
4) Earth and Space – Multiple Choice Which of the following types of moraines forms along the sides of a valley after a glacier wastes away, leaving behind ridges of materials?  

text[[115, 723, 273, 798]]
W) Lateral moraine  X) Medial moraine  Y) End moraine  Z) Ground moraine  

text[[115, 817, 471, 836]]
ANSWER: W) LATERAL MORAINE [DB]sub_title[[455, 90, 540, 108]]
## TOSS-UP  

text[[113, 130, 835, 166]]
5) Math – Short Answer What type of number is defined as being equal to the sum of its integer divisors excluding itself?  

text[[115, 186, 430, 204]]
ANSWER: PERFECT NUMBER [CD]  

sub_title[[462, 224, 533, 242]]
## BONUS  

text[[115, 262, 686, 281]]
5) Math – Short Answer How many factors does the number 96 have?  

text[[115, 300, 276, 318]]
ANSWER: 12 [CD]  

sub_title[[455, 375, 540, 393]]
## TOSS-UP  

text[[115, 411, 850, 466]]
6) Physical Science – Short Answer Let the centripetal force of a body moving in uniform circular motion be equal to F. If the linear speed of this body is tripled while the radius of its orbit is halved, what will be the new centripetal force of this body, in terms of F?  

text[[115, 486, 287, 504]]
ANSWER: 18F [CD]  

sub_title[[462, 524, 533, 542]]
## BONUS  

text[[115, 561, 879, 615]]
6) Physical Science – Short Answer If an object has an angular speed of 8 radians per second and an angular momentum of 4 kilogram meters squared per second, what is the object's moment of inertia, in kilogram meters squared?  

text[[115, 635, 280, 653]]
ANSWER: 0.5 [CD]sub_title[[455, 90, 540, 108]]
## TOSS-UP  

text[[115, 130, 875, 203]]
7) Energy - Short Answer Scientists at Argonne National Lab are researching the adaptations that plants have made to be able to pollinate new, untouched lands. What type of ecological succession is demonstrated when lichens and mosses colonize land that has been left by a retreating glacier?  

text[[115, 222, 470, 240]]
ANSWER: PRIMARY SUCCESSION [DB]  

sub_title[[462, 259, 533, 277]]
## BONUS  

text[[115, 294, 881, 368]]
7) Energy - Short Answer Scientists at Princeton Plasma Physics Lab are utilizing color confinement to examine the building blocks of protons and neutrons. Identify all of the following 3 subatomic particles that are responsible for making up protons and neutrons: 1) Quarks; 2) Gluons; 3) Leptons.  

text[[115, 385, 328, 404]]
ANSWER: 1 AND 2 [DB]  

sub_title[[455, 457, 540, 475]]
## TOSS-UP  

text[[115, 492, 863, 530]]
8) Life Science - Multiple Choice In the DNA replication of E. coli, which of the following enzymes is responsible for untwisting the double helix at the replication forks?  

text[[115, 547, 264, 619]]
W) Helicase X) Topoisomerase Y) Kinase Z) Primase  

text[[115, 636, 380, 655]]
ANSWER: W) HELICASE [DB]  

sub_title[[462, 672, 533, 690]]
## BONUS  

text[[115, 708, 779, 745]]
8) Life Science - Short Answer What name is given to animals whose embryonic development begins with the anus forming from the first opening?  

text[[115, 762, 425, 781]]
ANSWER: DEUTEROSTOMES [DB]sub_title[[455, 90, 540, 108]]
## TOSS-UP  

text[[113, 129, 880, 167]]
9) Earth and Space – Multiple Choice Neap tides occur during which of the following pairs of moon phases?  

text[[114, 186, 376, 262]]
W) Full moon and new moon  
X) New moon and first quarter  
Y) First quarter and third quarter  
Z) Third quarter and full moon  

text[[114, 280, 643, 300]]
ANSWER: Y) FIRST QUARTER AND THIRD QUARTER [NR]  

sub_title[[462, 319, 533, 337]]
## BONUS  

text[[113, 355, 875, 393]]
9) Earth and Space – Multiple Choice Which of the following types of supernovae has strong helium lines and no hydrogen emission lines?  

text[[114, 411, 212, 488]]
W) Type 1a  
X) Type 1b  
Y) Type 1c  
Z) Type 2  

text[[115, 507, 359, 526]]
ANSWER: X) TYPE 1B [NR]  

sub_title[[455, 583, 540, 600]]
## TOSS-UP  

text[[115, 618, 742, 639]]
10) Math – Multiple Choice How many zeroes are at the end of 23 factorial?  

text[[114, 657, 155, 731]]
W) 1  
X) 2  
Y) 3  
Z) 4  

text[[115, 751, 290, 770]]
ANSWER: Z) 4 [NR]  

sub_title[[462, 789, 533, 807]]
## BONUS  

text[[115, 827, 856, 864]]
10) Math – Short Answer What is the area of a circle which can be modeled by the graph x squared plus y squared + 4x - 8y = 16?  

text[[115, 883, 291, 902]]
ANSWER: 36pi [NR]sub_title[[455, 90, 540, 108]]
## TOSS-UP  

text[[115, 129, 861, 185]]
11) Physical Science – Short Answer A pipe, which is open on both ends, with a length of 5 meters has a fundamental frequency of 45 hertz. What is the frequency, in hertz, of the first overtone of this pipe?  

text[[115, 204, 277, 222]]
ANSWER: 90 [CD]  

sub_title[[462, 242, 533, 260]]
## BONUS  

text[[115, 280, 857, 317]]
11) Physical Science – Short Answer Rank the following four colors in order of increasing frequency:  

text[[115, 336, 193, 410]]
1. Green 
2. Violet 
3. Red 
4. Orange  

text[[115, 430, 328, 449]]
ANSWER: 3; 4; 1; 2 [CD]  

sub_title[[455, 505, 540, 523]]
## TOSS-UP  

text[[115, 543, 863, 598]]
12) Energy – Multiple Choice Scientists at Ames National Lab are studying the heating of substances. They observe that when water is heated, its heating curve has two horizontal lines. Which of the following physical processes is represented by the leftmost horizontal line?  

text[[115, 617, 245, 692]]
W) Sublimation 
X) Melting 
Y) Vaporization 
Z) Deposition  

text[[115, 711, 370, 730]]
ANSWER: X) MELTING [CD]  

sub_title[[462, 750, 533, 767]]
## BONUS  

text[[115, 787, 870, 824]]
12) Energy – Short Answer Scientists at Ames National Lab are studying the mechanisms by which electrons are produced in beta-minus decay. What possible spins can an electron have?  

text[[115, 842, 589, 861]]
ANSWER: - 1/2 AND +1/2 (ACCEPT: - 1/2 AND 1/2) [CD]sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 129, 857, 186]]
13) Life Science – Short Answer What steroid, which is wedged between phospholipid molecules in the plasma membrane, is responsible for reducing permeability of the membrane and controlling membrane fluidity?  

text[[115, 203, 395, 222]]
ANSWER: CHOLESTEROL [DB]  

sub_title[[462, 242, 533, 260]]
## BONUS  

text[[115, 280, 820, 317]]
13) Life Science – Multiple Choice Down syndrome, which is caused by a trisomy of chromosome 21, is an example of which of the following types of ploidy?  

text[[115, 336, 257, 411]]
W) Aneuploidy 
X) Polyploidy 
Y) Dihaploploidy 
Z) Euploidy  

text[[115, 430, 412, 449]]
ANSWER: W) ANEUPLOIDY [DB]  

sub_title[[456, 505, 540, 523]]
## TOSS-UP  

text[[115, 542, 840, 579]]
14) Earth and Space – Multiple Choice During which of the following eras did dinosaurs dominate?  

text[[115, 599, 270, 674]]
W) Early paleozoic 
X) Late paleozoic 
Y) Mesozoic 
Z) Cenozoic  

text[[115, 693, 382, 712]]
ANSWER: Y) MESOZOIC [DB]  

sub_title[[462, 731, 533, 749]]
## BONUS  

text[[115, 769, 848, 824]]
14) Earth and Space – Short Answer Some fungi have special hyphae structures that allow them to mutually exchange nutrients with their plant host. What is the name of this type of relationship between fungi and plant roots?  

text[[115, 842, 400, 861]]
ANSWER: MYCORRHIZAE [DB]sub_title[[455, 91, 540, 108]]
## TOSS-UP  

text[[115, 129, 855, 167]]
15) Math - Short Answer Given that \(\mathrm{f(x)} = 3\mathrm{x} + 5\) and that f and g are inverses, what is the value of \(\mathrm{g}(83)\) ?  

text[[115, 185, 277, 204]]
ANSWER: 26 [CD]  

sub_title[[462, 224, 533, 242]]
## BONUS  

text[[115, 261, 863, 300]]
15) Math - Short Answer The graph of the equation \(\mathrm{y} = \mathrm{x}^{\wedge}2 - 4\mathrm{x} + 3\) is shifted 3 units to the right and 2 units up. What is the vertex of this new graph?  

text[[115, 317, 300, 337]]
ANSWER: (5, 1) [CD]  

sub_title[[455, 392, 540, 410]]
## TOSS-UP  

text[[115, 430, 848, 468]]
16) Physical Science - Multiple Choice Which of the following most accurately describes projectile motion, neglecting air resistance?  

text[[115, 486, 580, 562]]
W) Constant horizontal velocity; constant vertical velocity 
X) Constant horizontal velocity; linear vertical velocity 
Y) Constant horizontal velocity; quadratic vertical velocity 
Z) Linear horizontal velocity; linear vertical velocity  

text[[115, 580, 861, 618]]
ANSWER: X) CONSTANT HORIZONTAL VELOCITY; LINEAR VERTICAL VELOCITY [CD]  

sub_title[[462, 636, 533, 654]]
## BONUS  

text[[115, 673, 872, 747]]
16) Physical Science - Short Answer A ball is thrown off a 50-meter building with an initial vertical velocity of 25 meters per second and an initial horizontal velocity of 45 meters per second. Taking g to be 10 meters per second squared and assuming air resistance to be negligible, what is the vertical velocity, in meters per second, 3 seconds after the ball is thrown?  

text[[115, 765, 273, 784]]
ANSWER: - 5 [CD]sub_title[[455, 90, 540, 108]]
## TOSS-UP  

text[[115, 130, 875, 203]]
17) Energy – Multiple Choice Scientists at Lawrence Berkeley National Lab are studying strigolactones, which are a group of chemicals produced in the roots of plants that serve a numerous number of functions. Strigolactones are highly soluble in polar solvents. What type of vascular tissue would strigolactones most likely be found in?  

text[[115, 220, 209, 291]]
W) Phloem 
X) Xylem 
Y) Cork 
Z) Pith  

text[[115, 310, 351, 328]]
ANSWER: X) XYLEM [DB]  

sub_title[[462, 346, 533, 364]]
## BONUS  

text[[115, 382, 872, 436]]
17) Energy – Short Answer Scientists at Ames National Lab are studying decay modes to improve methods of radiometric dating. Name all of the following 3 particles which are created by beta-minus decay:  

text[[144, 455, 344, 508]]
1. Neutron 
2. Positron 
3. Electron antineutrino  

text[[115, 525, 327, 544]]
ANSWER: 3 ONLY [CD]  

sub_title[[448, 599, 534, 617]]
## TOSS-UP  

text[[115, 636, 813, 674]]
18) Life Science – Short Answer What is the name of the gland that is responsible for producing human tears?  

text[[115, 692, 455, 711]]
ANSWER: LACHRYMAL GLAND [NR]  

sub_title[[455, 731, 525, 749]]
## BONUS  

text[[115, 768, 872, 805]]
18) Life Science – Multiple Choice Which of the following plant hormones is responsible for directing shoot growth toward sunlight?  

text[[115, 824, 237, 899]]
W) Gibberellin 
X) Cytokinin 
Y) Ethylene 
Z) Auxin  

text[[115, 919, 343, 937]]
ANSWER: Z) AUXIN [DB]sub_title[[455, 90, 540, 108]]
## TOSS-UP  

text[[115, 129, 875, 166]]
19) Earth and Space – Short Answer What is the name of the 26,000-year cycle on Earth that refers to a continuous change in the axis of rotation?  

text[[115, 185, 375, 204]]
ANSWER: PRECESSION [NR]  

sub_title[[462, 224, 533, 242]]
## BONUS  

text[[115, 261, 860, 299]]
19) Earth and Space – Multiple Choice Which of the following statements regarding binary star systems is true?  

text[[115, 317, 636, 336]]
W) More than half of all stars are members of binary star systems  

text[[115, 337, 866, 374]]
X) Kepler's third law of orbital motion can be used to determine the mass of extrasolar binaries Y) Binary stars that orbit so close to each other that they are not visible individually are called  

text[[115, 375, 288, 392]]
visual binary systems  

text[[115, 393, 840, 429]]
Z) A light curve graph is often used by astronomers to predict the age of an eclipsing binary system  

text[[115, 447, 861, 484]]
ANSWER: W) MORE THAN HALF OF ALL STARS ARE MEMBERS OF BINARY STAR SYSTEMS [DB]  

sub_title[[455, 542, 540, 560]]
## TOSS-UP  

text[[115, 579, 869, 616]]
20) Math – Multiple Choice How many real roots does the function f of x equals 2 x squared plus 6 x minus 4 have?  

text[[115, 635, 156, 708]]
W) 0 
X) 1 
Y) 2 
Z) 3  

text[[115, 729, 292, 748]]
ANSWER: Y) 2 [NR]  

sub_title[[462, 768, 533, 786]]
## BONUS  

text[[115, 806, 866, 842]]
20) Math – Short Answer What is the term given to the line that extends from the center of a regular polygon to the midpoint of one of its sides?  

text[[115, 860, 351, 879]]
ANSWER: APOTHEM [NR]sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[114, 129, 870, 203]]
21) Physical Science - Short Answer Two planets A and B are orbiting around the same star. When measured about the star, planet A has twice the angular momentum of planet B. If the moment of inertia of planet A is double that of planet B, what is the ratio, omega A over omega B, of their angular speeds?  

text[[115, 222, 266, 240]]
ANSWER: 1 [CD]  

sub_title[[462, 260, 533, 279]]
## BONUS  

text[[115, 297, 877, 352]]
21) Physical Science - Short Answer A student titrates 0.4 molar hydrochloric acid against 25 mL of an unknown concentration of barium hydroxide. What type of reaction is occurring in the flask?  

text[[115, 370, 694, 390]]
ANSWER: NEUTRALIZATION (ACCEPT: ACID-BASE REACTION)  

sub_title[[456, 447, 540, 465]]
## TOSS-UP  

text[[115, 485, 867, 522]]
22) Earth and Space - Multiple Choice What is the name of the galactic cluster that contains the milky way?  

text[[115, 542, 287, 615]]
W) Local group 
X) Andromeda group 
Y) Milky way cluster 
Z) Local cluster  

text[[115, 635, 424, 654]]
ANSWER: W) LOCAL GROUP [NR]  

sub_title[[462, 673, 533, 691]]
## BONUS  

text[[115, 711, 864, 802]]
22) Earth and Space - Short Answer Identify all of the following 3 statements regarding temperature and density variations in the ocean that are true: 1) The thermocline gradually gets stronger near high latitudes; 2) Salinity of ocean water is directly proportional to seawater density; 3) The pycnocline serves as a barrier to the mixing between low and high density seawater.  

text[[115, 821, 328, 840]]
ANSWER: 2 AND 3 [DB]sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[113, 129, 822, 167]]
23) Life Science – Short Answer What is the name for malignant tumors that generally develop on the surface of tissue-lining organs?  

text[[115, 185, 376, 204]]
ANSWER: CARCINOMA [DB]  

sub_title[[462, 224, 533, 242]]
## BONUS  

text[[113, 261, 883, 299]]
23) Life Science – Multiple Choice Which of the following divisions of plants is not classified under the informal group of bryophytes?  

text[[115, 317, 230, 393]]
W) Liverworts 
X) Mosses 
Y) Hornworts 
Z) Ferns  

text[[115, 411, 341, 431]]
ANSWER: Z) FERNS [DB]