sub_title[[455, 162, 541, 180]]
## TOSS-UP  

text[[115, 197, 875, 251]]
1) Physics – Short Answer A 10-kilogram block rests on a rough surface with a coefficient of kinetic and static friction equal to 0.5. If a 25-Newton force is applied to the block parallel to the ground, then what is the acceleration of the block?  

text[[115, 268, 221, 285]]
ANSWER: 0  

sub_title[[462, 303, 533, 320]]
## BONUS  

text[[115, 338, 867, 391]]
1) Physics – Short Answer A 3-kilogram block is traveling on a frictionless surface at 10 meters per second. It collides elastically with a 2-kilogram block traveling at 20 meters per second in the opposite direction. After the collision, what is the total momentum of the system?  

text[[115, 407, 550, 425]]
ANSWER: 10 KILOGRAM-METERS PER SECOND  

sub_title[[455, 478, 541, 496]]
## TOSS-UP  

text[[111, 513, 852, 532]]
2) Biology – Multiple Choice Blood is considered which of the following types of tissues?  

text[[115, 549, 232, 617]]
W) Epithelial X) Connective Y) Muscle Z) Nervous  

text[[115, 635, 362, 653]]
ANSWER: X) CONNECTIVE  

sub_title[[462, 671, 533, 688]]
## BONUS  

text[[115, 706, 848, 741]]
2) Biology – Short Answer Identify all of the following three organisms that have an open circulatory system: 1) Earthworm; 2) Fruit fly; 3) Lobster.  

text[[115, 758, 282, 775]]
ANSWER: 2 AND 3sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[113, 126, 864, 163]]
3) Earth and Space – Short Answer Voyager 1 and 2 both performed what maneuver as they passed by Jupiter and Saturn?  

text[[113, 179, 857, 199]]
ANSWER: GRAVITY ASSIST (ACCEPT: GRAVITATIONAL SLINGSHOT, SWING- BY)  

sub_title[[463, 215, 533, 234]]
## BONUS  

text[[113, 250, 870, 286]]
3) Earth and Space – Short Answer What is the name of the boundary between the outer core and the mantle?  

text[[114, 302, 486, 320]]
ANSWER: GUTENBERG DISCONTINUITY  

sub_title[[456, 372, 541, 390]]
## TOSS-UP  

text[[113, 407, 775, 426]]
4) Math – Multiple Choice Which of the following angles has a negative cosine?  

text[[114, 443, 186, 513]]
W) \(\pi /6\) X) \(\pi /3\) Y) \(2\pi /3\) Z) \(11\pi /6\)  

text[[114, 530, 271, 549]]
ANSWER: Y) \(2\pi /3\)  

sub_title[[463, 566, 533, 584]]
## BONUS  

text[[113, 601, 863, 637]]
4) Math – Short Answer The first two terms of a geometric sequence are 25 and 20. What is the largest term in the sequence that is NOT an integer?  

text[[114, 654, 246, 672]]
ANSWER: 64/5sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[113, 127, 872, 164]]
5) Chemistry – Short Answer Rank the following three gases by increasing dispersion forces: 1) Neon; 2) Argon; 3) Krypton.  

text[[115, 180, 260, 198]]
ANSWER: 1, 2, 3  

sub_title[[462, 215, 533, 233]]
## BONUS  

text[[115, 250, 876, 287]]
5) Chemistry – Multiple Choice The SI definition of Kelvin is defined by setting which of the following properties of water equal to a fixed value?  

text[[115, 303, 259, 375]]
W) Triple point  X) Freezing point  Y) Boiling point  Z) Critical point  

text[[116, 392, 370, 410]]
ANSWER: W) TRIPLE POINT  

sub_title[[456, 461, 541, 480]]
## TOSS-UP  

text[[115, 496, 856, 567]]
6) Energy – Short Answer Researchers at Oak Ridge National Lab are studying the conformational transitions involved in mitochondrial protein complexes. They are studying complex V, which belongs to a class of enzymes known as F-type ATPases. Complex V most likely hydrolyzes what bond in ATP?  

text[[115, 584, 384, 601]]
ANSWER: PHOSPHATE BOND  

sub_title[[462, 619, 533, 637]]
## BONUS  

text[[115, 654, 863, 708]]
6) Energy – Short Answer Researchers at Oak Ridge National Lab are studying membrane-wide energy conversion in purple photosynthetic bacteria. The color of these bacteria is caused by the presence of what type of cells?  

text[[115, 724, 387, 742]]
ANSWER: CHROMATOPHOREsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 850, 181]]
7) Physics – Short Answer Many equations in quantum physics, such as Heisenberg's uncertainty principle, use the reduced Planck constant. Reduced Planck's constant is equal to Planck's constant divided by what number?  

text[[115, 198, 375, 216]]
ANSWER: \(2\pi\) (ACCEPT: TAU)  

sub_title[[462, 233, 533, 252]]
## BONUS  

text[[115, 268, 877, 322]]
7) Physics – Short Answer A proton moves in a 0.01-tesla magnetic field at a speed of \(3 * 10^{7}\) meters per second in a circular path. Assuming that the mass of the proton is \(1.6 * 10^{-27}\) kilograms, then to one significant figure, what is the radius of the proton's path?  

text[[115, 338, 313, 356]]
ANSWER: 30 METERS  

sub_title[[456, 408, 541, 426]]
## TOSS-UP  

text[[115, 443, 820, 479]]
8) Biology – Multiple Choice Which of the following environments has the lowest net primary production?  

text[[173, 496, 353, 567]]
W) Tropical rainforest 
X) Open ocean 
Y) Estuary 
Z) Coral reef  

text[[173, 585, 419, 603]]
ANSWER: X) OPEN OCEAN  

sub_title[[462, 620, 533, 638]]
## BONUS  

text[[115, 655, 870, 709]]
8) Biology – Multiple Choice After creating a small hill in Illinois with his bare hands, Bob has decided to decorate his mountain with plants. On which side of the hill should Bob grow his plants so they get the maximum amount of sunlight annually?  

text[[115, 726, 195, 797]]
W) North 
X) East 
Y) South 
Z) West  

text[[115, 814, 303, 832]]
ANSWER: Y) SOUTHsub_title[[455, 90, 541, 108]]
## TOSS-UP  

text[[113, 126, 805, 163]]
9) Earth and Space – Short Answer What is the second smallest sedimentary particle commonly found in river beds?  

text[[115, 180, 252, 198]]
ANSWER: SILT  

sub_title[[462, 215, 533, 234]]
## BONUS  

text[[113, 250, 864, 288]]
9) Earth and Space – Multiple Choice Red supergiants are located at which of the following locations on a HR diagram?  

text[[115, 304, 238, 373]]
W) Upper right  X) Upper left  Y) Lower right  Z) Lower left  

text[[115, 389, 366, 408]]
ANSWER: W) UPPER RIGHT  

sub_title[[455, 460, 541, 478]]
## TOSS-UP  

text[[115, 491, 831, 514]]
10) Math – Short Answer Let \(\mathrm{f}(x) = 2x^{3} + 3\) . What is the degree of the polynomial \(\mathrm{f}(x)^{3}\) ?  

text[[115, 530, 222, 548]]
ANSWER: 9  

sub_title[[462, 565, 533, 583]]
## BONUS  

text[[115, 600, 863, 636]]
10) Math – Short Answer What theorem states that the sampling distribution approaches the normal distribution as n grows large?  

text[[115, 652, 601, 672]]
ANSWER: CENTRAL LIMIT THEOREM (ACCEPT: CLT)sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 857, 163]]
11) Chemistry – Short Answer Compounds that have L and D isomers exhibit what type of isomerism, characterized by non-superimposable mirror images?  

text[[115, 180, 790, 199]]
ANSWER: ENANTIOMERISM (ACCEPT: OPTICAL ISOMERISM; CHIRALITY)  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 250, 797, 286]]
11) Chemistry – Short Answer What is the most common industrial process used to synthesize ammonia from nitrogen and hydrogen gas?  

text[[115, 303, 702, 321]]
ANSWER: HABER PROCESS (ACCEPT: HABER- BOSCH PROCESS)  

sub_title[[456, 373, 541, 391]]
## TOSS-UP  

text[[115, 408, 876, 478]]
12) Energy – Short Answer Researchers at Ames National Lab are conducting experiments with CaloriSMART, which could improve the energy efficiency of current refrigeration systems. What theoretical heat cycle minimizes heat loss and has the maximum possible theoretical efficiency?  

text[[115, 495, 360, 512]]
ANSWER: CARNOT CYCLE  

sub_title[[463, 530, 533, 548]]
## BONUS  

text[[115, 565, 862, 618]]
12) Energy – Multiple Choice Researchers at Ames National Lab are studying the recycling of rare-earth magnets at the Critical Materials Institute. Which of the following is NOT considered a rare earth metal?  

text[[115, 636, 245, 707]]
W) Neodymium X) Lanthanum Y) Platinum Z) Yttrium  

text[[115, 725, 338, 742]]
ANSWER: Y) PLATINUMsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 852, 163]]
13) Physics – Short Answer When a car drives along a road, the absence of what force can cause slipping on the wheels?  

text[[115, 179, 816, 215]]
ANSWER: FRICTION (ACCEPT: STATIC FRICTION; DO NOT ACCEPT: KINETIC FRICTION)  

sub_title[[462, 232, 533, 251]]
## BONUS  

text[[115, 267, 857, 304]]
13) Physics – Short Answer What is the Lorentz factor of an object moving at 0.6 times the speed of light?  

text[[115, 320, 246, 338]]
ANSWER: 1.25  

sub_title[[456, 390, 541, 408]]
## TOSS-UP  

text[[115, 424, 875, 461]]
14) Biology – Multiple Choice Mycorrhizae are mutualistic relationships between a plant and an organism in which of the following kingdoms?  

text[[115, 478, 216, 550]]
W) Bacteria X) Animalia Y) Protista Z) Fungi  

text[[115, 566, 297, 584]]
ANSWER: X) FUNGI  

sub_title[[462, 601, 533, 620]]
## BONUS  

text[[115, 636, 866, 673]]
14) Biology – Short Answer In the nitrogen cycle, denitrifying bacteria make what nitrogen-containing molecule?  

text[[115, 689, 733, 708]]
ANSWER: \(\mathrm{N}_{2}\) (ACCEPT: ATMOSPHERIC NITROGEN; NITROGEN GAS)sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 126, 844, 163]]
15) Earth and Space – Short Answer What hypothesis states that small changes in Earth’s orbit, precession, and inclination affect its climate and can cause ice ages?  

text[[115, 180, 488, 198]]
ANSWER: MILANKOVITCH HYPOTHESIS  

sub_title[[462, 215, 533, 233]]
## BONUS  

text[[115, 250, 877, 287]]
15) Earth and Space – Multiple Choice Which of the following is the best course of action for a swimmer caught in a rip current?  

text[[114, 304, 499, 374]]
W) Swim parallel to the current towards shore  X) Swim parallel to the current away from shore  Y) Swim parallel to shore in either direction  Z) Float and wait for current to pass.  

text[[115, 390, 705, 408]]
ANSWER: Y) SWIM PARALLEL TO SHORE IN EITHER DIRECTION  

sub_title[[456, 460, 541, 478]]
## TOSS-UP  

text[[115, 494, 870, 531]]
16) Math – Multiple Choice Which of the following functions does NOT have an inverse for all real numbers \(x\) ?  

text[[115, 547, 214, 617]]
W) \(e^{x}\) X) \(\sin (x)\) Y) \(\arctan (x)\) Z) \(x^{3}\)  

text[[115, 635, 281, 653]]
ANSWER: X) \(\sin (x)\)  

sub_title[[462, 670, 533, 689]]
## BONUS  

text[[115, 706, 880, 741]]
16) Math – Short Answer What is the surface area of an regular octahedron with a side length of 9?  

text[[115, 764, 270, 782]]
ANSWER: 162√3sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 852, 162]]
17) Chemistry – Short Answer What quantity characterizes the ability of an atom to attract bonded electrons?  

text[[115, 180, 418, 198]]
ANSWER: ELECTRONEGATIVITY  

sub_title[[463, 216, 533, 234]]
## BONUS  

text[[115, 250, 814, 287]]
17) Chemistry – Multiple Choice Which of the following polymers is formed through addition polymerization and is widely used in plumbing?  

text[[115, 303, 293, 374]]
W) Polyvinyl chloride X) Polycarbonate Y) Polystyrene Z) Polypropylene  

text[[115, 390, 457, 408]]
ANSWER: W) POLYVINYL CHLORIDE  

sub_title[[456, 460, 541, 478]]
## TOSS-UP  

text[[115, 494, 872, 565]]
18) Energy – Short Answer Researchers at Pacific Northwest National Lab have designed a chip-sized sensor to detect toxic polyfluoroalkyl substances, or PFAS, which do not break down naturally and can repel water and oils. Identify all of the following three products that PFAS is commonly used in: 1) Non-stick pans; 2) Food packaging; 3) Silverware.  

text[[115, 581, 283, 599]]
ANSWER: 1 AND 2  

sub_title[[463, 617, 533, 635]]
## BONUS  

text[[115, 652, 857, 704]]
18) Energy – Short Answer Researchers at Pacific Northwest National Lab are studying the quality and quantity of groundwater by examining what part of the Earth that lies between the surface soil and the water table?  

text[[115, 721, 658, 740]]
ANSWER: VADOSE ZONE (ACCEPT: UNSATURATED ZONE)sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[114, 127, 877, 181]]
19) Physics – Multiple Choice A system consists of a ball floating on a cup of water. The ball is then removed from the system. Assuming no water leaves the cup, which of the following will happen to the weight of the system?  

text[[114, 198, 327, 268]]
W) Increase  X) Stay the same  Y) Decrease  Z) Decrease, then increase  

text[[115, 285, 338, 303]]
ANSWER: Y) DECREASE  

sub_title[[462, 321, 533, 339]]
## BONUS  

text[[115, 355, 855, 391]]
19) Physics – Short Answer What set of differential equations, whose exact solution is still unknown, describes the flow of viscous fluids?  

text[[114, 407, 486, 425]]
ANSWER: NAVIER- STOKES EQUATIONS  

sub_title[[456, 477, 541, 495]]
## TOSS-UP  

text[[113, 511, 835, 531]]
20) Biology – Multiple Choice Which of the following is NOT a stage of cell signaling?  

text[[114, 548, 247, 618]]
W) Propagation  X) Reception  Y) Transduction  Z) Response  

text[[115, 636, 379, 653]]
ANSWER: W) PROPAGATION  

sub_title[[462, 672, 533, 689]]
## BONUS  

text[[112, 707, 863, 725]]
20) Biology – Short Answer What enzyme catalyzes the conversion of ATP to cyclic AMP?  

text[[114, 741, 814, 778]]
ANSWER: ADENYLYL CYCLASE (ACCEPT: ADENYL CYCLASE; ADENYLATE CYCLASE; AC)sub_title[[455, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 864, 163]]
21) Earth and Space – Multiple Choice What is the process where the expansion of freezing water mechanically weathers rock?  

text[[115, 181, 300, 251]]
W) Ice breaking 
X) Cold weathering 
Y) Frost wedging 
Z) Destructive freezing  

text[[115, 267, 396, 285]]
ANSWER: Y) FROST WEDGING  

sub_title[[462, 303, 533, 320]]
## BONUS  

text[[115, 337, 872, 390]]
21) Earth and Space – Short Answer Many solar flares are followed by an ejection of plasma, which can have significant effects on our magnetosphere if directed towards Earth. What is the name of these events?  

text[[115, 406, 612, 425]]
ANSWER: CORONAL MASS EJECTION (ACCEPT: CME)  

sub_title[[455, 477, 541, 495]]
## TOSS-UP  

text[[115, 512, 667, 530]]
22) Math – Short Answer What is the fifth smallest prime number?  

text[[115, 547, 229, 564]]
ANSWER: 11  

sub_title[[462, 582, 533, 600]]
## BONUS  

text[[115, 617, 864, 670]]
22) Math – Short Answer Square ABCD has side length 4. The midpoints of the sides of ABCD are connected to form a smaller square. What is the area of the region inside ABCD but outside of the smaller square?  

text[[115, 688, 221, 705]]
ANSWER: 8sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[113, 127, 853, 163]]
23) Chemistry – Multiple Choice An exothermic reaction has a positive change in entropy. Under which of the following conditions will the reaction be spontaneous?  

text[[115, 181, 409, 252]]
W) Only at high temperatures 
X) Only at low temperatures 
Y) At all temperatures 
Z) The reaction is never spontaneous  

text[[115, 269, 470, 288]]
ANSWER: Y) AT ALL TEMPERATURES  

sub_title[[462, 305, 533, 323]]
## BONUS  

text[[113, 339, 845, 359]]
23) Chemistry – Multiple Choice Which of the following is NOT a property of graphene?  

text[[115, 374, 345, 445]]
W) \(\mathrm{sp}^{2}\) hybridization 
X) Two-dimensional lattice 
Y) High tensile strength 
Z) Low thermal conductivity  

text[[115, 462, 530, 480]]
ANSWER: Z) LOW THERMAL CONDUCTIVITY