
## TOSS-UP  


1) BIO- Short Answer Identify all of the following that are antigen presenting cells.  


1- T cell, 2- Dendritic Cell, 3- B cell, 4- Macrophages  


ANSWER: 2 AND 4  


## BONUS  


1) BIO- Short Answer Cytotoxic T cells are activated by binding to what specific molecules on the surface of infected cells?  


ANSWER: CLASS 1 MHC  


## TOSS-UP  


2) CHEM- Short Answer What is the term for disubstituted benzene rings with substituents on the 1 and 3 positions?  


ANSWER: META  


## BONUS  


2) CHEM- Short Answer Answer the following questions about nucleophilic aromatic substitution.  


A) It requires what type of group in the ortho or para position relative to the leaving group? 
B) What is the name for its intermediate resonance-stabilized anionic complex?  


ANSWER: EWG, MEISENHEIMER COMPLEX  


## TOSS-UP  


3) PHYS- Short Answer The quantization of angular momentum in fundamental particles was discovered by what experiment in 1922?  


ANSWER: STERN-GERLACH EXPERIMENT  


## BONUS  


3) PHYS- Short Answer Quantum physicists hypothesize that the exchange of the graviton gives rise to the force of gravity. What is the spin of the hypothetical graviton?  


ANSWER: 2
## TOSS-UP  


4) MATH- Short Answer 15 choose 7 plus 15 choose 8 is equal to n choose k. What is n+k? ANSWER: 24  


## BONUS  


4) MATH- Short Answer How many terms does the trinomial expansion of \((a + b + c)^{\wedge}10\) have?  


ANSWER: 66 (12\*11/2)  


## TOSS-UP  


5) ESS- Short Answer What is the name for the equatorial region where the trade winds meet?  


ANSWER: ITCZ OR INTERTROPICAL CONVERGENCE ZONE (ACCEPT: DOLDRUMS)  


## BONUS  


5) ESS- Short Answer El niño and la niña are different phases of what overall cycle?  


ANSWER: El- niño Southern Oscillation  


## TOSS-UP  


6) ENERGY- Short Answer Scientists at Lawrence Berkeley National Laboratory are developing methods to detect chromosomal defects in sperm cells. In the human male reproductive system, what cells, next to the seminiferous tubules, are activated by LH?  


ANSWER: LEYDIG CELLS  


## BONUS  


6) ENERGY- Short Answer Scientists at Lawrence Berkeley National Laboratory are developing methods to detect chromosomal defects in sperm cells. In the human male reproductive system, what tube connects the vas deferens to the testes?  


ANSWER: EPIDIDYMIS  


## TOSS-UP  


7) BIO- Short Answer Oseltamivir, used to treat influenza, is a powerful antiviral that inhibits what important molecules on viral coatings?  


ANSWER: NEURAMINIDASE  


## BONUS
7) BIO- Short Answer AIP in gram positive bacteria is an autoinducer for a signaling pathway that implicates in what effect observed in groups of bacteria such as Aliivibrio fischeri?  


ANSWER: QUORUM SENSING  


## TOSS-UP  


8) CHEM- Short Answer How many d electrons are in the permanganate anion?  


ANSWER: 0  


## BONUS  


8) CHEM- Short Answer The copper (II) fluoride complex has peaks in its absorbance diagram at two distinct points. This is caused by what molecular effect?  


ANSWER: JAHN-TELLER EFFECT (ACCEPT: JAHN TELLER DISTORTION)  


## TOSS-UP  


9) PHYS- Short Answer Calculate the voltage gap across a capacitor in series with a 9 V battery and 3 Ohm resistor at the moment when the current in the circuit is 2 A.  


ANSWER: 3 VOLTS  


## BONUS  


9) PHYS- Short Answer What is the period of a series LC circuit with a 3 Henry inductor and 12 Farad capacitor. Give your answer as a decimal with three significant figures.  


ANSWER: 37.7  


## TOSS-UP  


10) MATH- Short Answer How many distinct positive factors does 200 have?  


ANSWER: 12  


## BONUS  


10) MATH- Short Answer What is the product of the greatest common divisor and least common multiple of 125 and 30?  


ANSWER: 3750  


## TOSS-UP  


11) ESS- Short Answer What type of neutron star has a magnetic field between \(10^{\wedge}9\) and \(10^{\wedge}11\) Teslas and emits high energy EM radiation?  


ANSWER: MAGNETAR
## BONUS  


11) ESS- Short Answer What is the name for the observation in astronomy of quick lived radio pulses that have been observed from magnetars?  


ANSWER: FAST RADIO BURSTS  


## TOSS-UP  


12) ENERGY- Short Answer Researchers at Oak Ridge National Laboratory are using neutron scattering to study the dynamics of proteins involved in cancer. What is the spin of a neutron?  


ANSWER: 1/2  


## BONUS  


12) ENERGY- Short Answer Researchers at Oak Ridge National Laboratory are using neutron scattering to study the dynamics of proteins involved in cancer. Answer the following questions about scattering.  


A) Electron scattering occurs by the exchange of virtual versions of what particles?  
B) What quantity, used in scattering, is the average distance that a particle travels between two collisions?  


ANSWER: PHOTONS, MEAN FREE PATH  


## TOSS-UP  


13) BIO- Short Answer Generation 1 antipsychotics such as Prochlorperazine are antagonists for the D2 receptors of what neurotransmitter?  


ANSWER: DOPAMINE  


## BONUS  


13) BIO- Short Answer What neurological disorder, believed to be caused by dopamine hyperactivity and glutamate reduction at NMDA receptors, causes hallucinations and delusions?  


ANSWER: SCHIZOPHRENIA  


## TOSS-UP  


14) CHEM- Short Answer Gilman reagents are made with dialkyl types of what transition metal?  


ANSWER: COPPER  


## BONUS
14) CHEM- Short Answer How many equivalents of a Grignard reagent can react with an ester?  


ANSWER: 2  


## TOSS-UP  


15) PHYS- Short Answer The temperature of a gas can be related to its kinetic energy using what fundamental constant?  


ANSWER: BOLTZMANN CONSTANT  


## BONUS  


15) PHYS- Short Answer How many degrees of freedom do monatomic ideal gases possess?  


ANSWER: 3  


## TOSS-UP  


16) MATH- Short Answer How many positive integer triplets (x,y,z) with x y and z less than or equal to 8 and have distinct x,y,z?  


ANSWER: 336  


## BONUS  


16) MATH- Short Answer What is the maximum value of xyz if x+y+z=30 and x,y,z are positive integers?  


ANSWER: 1,000  


## TOSS-UP  


17) ESS- Short Answer What precipitation occurs when supercooled water droplets freeze on the surface of already falling snowflakes outside of a cloud?  


ANSWER: GRAUPEL  


## BONUS  


17) ESS- Short Answer When large scale winds circulate around regions of high atmospheric pressure and rotate clockwise in the Northern hemisphere, what is formed?  


ANSWER: ANTICYCLONE  


## TOSS-UP  


18) ENERGY- Short Answer Researchers at Ames National Laboratory have invented a new algorithm to quickly find high-entropy alloys. What is the entropy of a system with \(e^{10}\) microstates assuming that \(k \cdot b = 1.38\) .  


ANSWER: 13.8
## BONUS  


18) ENERGY- Short Answer Researchers at Ames National Laboratory have invented a new algorithm to quickly find high-entropy alloys. Answer the following two questions about metals.  


A) Superconductivity in metals is hypothesized to be caused by the formation of what low temperature features?  
B) What is the most efficient crystal packing system?  


ANSWER: COOPER PAIRS, FCC(ACCEPT: face-centered cubic or cubic close packed or equivalent)  


## TOSS-UP  


19) BIO- Short Answer Species with extremely high birth rates are said to be selecting for what factor in population dynamics?  


ANSWER: r  


## BONUS  


19) BIO- Short Answer What is the name of the rapid associative learning in which youth learn the characteristics of a stimulus from their parents. This effect is present in nidifugous birds.  


ANSWER: IMPRINTING  


## TOSS-UP  


20) CHEM- Short Answer What is the common name for P(Ph)3O (READ LETTER BY LETTER)  


ANSWER: TRIPHENYLPHOSPHINE OXIDE  


## BONUS  


20) CHEM- Short Answer Copper II iodide is unstable because it disproportionates to what two compounds?  


ANSWER: COPPER (I) IODIDE AND I2  


## TOSS-UP  


21) PHYS- Short Answer What charged fundamental particle is released in beta minus decay?  


ANSWER: ELECTRON  


## BONUS
21) PHYS- Short Answer In beta minus decay, a neutron is converted to a proton by the emission of a boson as a quark changes flavor. Answer the following question.  


A) What is the flavor of the quark before and after the transformation respectively?  
B) What specific fundamental boson is emitted in the quark transformation that quickly decays?  


ANSWER: A) down, up B) W- boson (DO NOT ACCEPT W OR W+)  


## TOSS-UP  


22) MATH- Short Answer What is the magnitude of \(1\mathrm{i} + 2\mathrm{j} + 10\mathrm{k}\) ?  


ANSWER: sqrt(105)  


## BONUS  


22) MATH- Short Answer What is the cross product of 3i with \(\mathrm{i} + \mathrm{j}\) ?  


ANSWER: 3k  


## TOSS-UP  


23) ESS- Short Answer Binary star systems exist because two stars are mutually orbiting around what center, a property of their system?  


ANSWER: BARYCENTER  


## BONUS  


23) ESS- Short Answer The Type 1a "Champagne Supernova" was exceptional because it resulted from a binary system including a massive white dwarf that exceeded what limit?  


ANSWER: CHANDRASEKHAR LIMIT