
## TOSS-UP  


1) BIO- Short Answer Following fertilization in plants, the integument of the ovule develops into what structure of the mature seed?  


ANSWER: Seed Coat  


## BONUS  


1) BIO- Short Answer Identify all of the following structures that are haploid: (1) Integument, (2) Archegonium, (3) Megasporophyll, (4) Microsporangium.  


ANSWER: 2  


## TOSS-UP  


2) CHEM- Short Answer How many hydrogen bonds does each ammonia molecule form?  


ANSWER: 2  


## BONUS  


2) CHEM- Short Answer By what value does the oxidation state of phosphorus change when PCI3 is reacted with water?  


ANSWER: ZERO  


## TOSS-UP  


3) PHYS- Short Answer In 1980, James Cronin and Val Fitch won the Nobel Prize in Physics for their discovery of the violation of what symmetry in kaon decay. This historically violated previously accepted principles of particle mechanics.  


ANSWER: CP (ACCEPT EQUIVALENTS)  


## BONUS  


3) PHYS- Short Answer What dimensionless constant is used as a measure of the strength of the electromagnetic force between elementary charged particles? It is represented by the Greek letter alpha.  


ANSWER: FINE STRUCTURE CONSTANT  


## TOSS-UP  


4) MATH- Short Answer If the chance of landing heads on an unfair coin is 0.8, what is the most likely number of tosses that will be necessary in order to land the first tail?
ANSWER: 5  


## BONUS  


4) MATH- Short Answer A gambler wins a bet if a 6 - sided dice rolls on a prime number or 1. What is the probability that the gambler wins at least 2 out of 10 bets.  


ANSWER: 1013/1024  


## TOSS-UP  


5) ESS- Short Answer In astronomy, what phenomenon occurs when a planet appears to be moving backwards in its orbit, often compared to when "one car overtakes another on a highway"?  


ANSWER: Retrograde Motion  


## BONUS  


5) ESS- Short Answer Order the following spectral classes from the one with the least temperature to the one with the most temperature: 1) M, (2) B, (3) F, (4) G.  


ANSWER: 1, 4, 3, 2  


## TOSS-UP  


6) ENERGY- Short Answer Researchers at Brookhaven National Laboratory are exploring DNA self - assembly and replication in an attempt to create smaller electronic components. What famous experiment in 1958 demonstrated that DNA replication is semi - conservative?  


ANSWER: Meselson - Stahl Experiment  


## BONUS  


6) ENERGY- Short Answer Researchers at Brookhaven National Laboratory are trying to copy the geometry of mammal bones using batteries. Mammal bones have a function in storing red and yellow bone marrow. What is the name for the space within the bone that performs this function?  


ANSWER: Medullary Cavity  


## TOSS-UP
7) BIO- Short Answer In the digestive system, G cells are responsible for secreting what hormone in response to the presence of food?  


ANSWER: Gastrin  


## BONUS  


7) BIO- Multiple Choice Inhibin is responsible for inhibiting the secretion of which of the following reproductive hormones?  


W) Follicle - Stimulating Hormone 
X) Luteinizing Hormone 
Y) Human Chorionic Gonadotropin 
Z) Testosterone  


ANSWER: W) Follicle - Stimulating Hormone  


## TOSS-UP  


8) CHEM- Short Answer What are the values of n and l respectively for a 4f orbital?  


ANSWER: 4 and 3  


## BONUS  


8) CHEM- Short Answer Oxygen is paramagnetic because it can be described what adjective, meaning it has two unpaired electrons?  


ANSWER: DIRADICAL (ACCEPT: TRIPLET)  


## TOSS-UP  


9) PHYS- Multiple Choice To the nearest integer, what is the drag coefficient of an aerofoil?  


W) 0 
X) 1 
Y) 4 
Z) 15  


ANSWER: W) 0  


## BONUS  


9) PHYS- Short Answer For a fluid with drag coefficient 1, calculate the drag force for an object around which fluid flows at 3 m/s, has a circular cross section of radius 5, and is in a fluid of density 6. Give your answer in terms of pi.  


ANSWER: 675π  


TOSS- UP
10) MATH- Short Answer What is the area bounded by the polar curve \(\mathrm{r} = 4\) ?  


ANSWER: 16 pi  


## BONUS  


10) MATH- Short Answer What is the name for polar curves produced by the general equations of \(\mathrm{r} = \mathrm{a} + \mathrm{b}\) sin (theta) or \(\mathrm{r} = \mathrm{a} + \mathrm{b}\) cos (theta)?  


ANSWER: Limacons  


## TOSS-UP  


11) ESS- Short Answer What mineral corresponds to an 8 on the Mohs hardness scale?  


ANSWER: Topaz  


## BONUS  


11) ESS- Short Answer Provide the name for the major zinc ore, which contains zinc, sulfur, and iron, and is sometimes referred to as marmatite when there is high iron composition.  


ANSWER: Sphalerite  


## TOSS-UP  


12) ENERGY- Short Answer Researchers at Fermi National Accelerator Laboratory are using elementary particles to discover rare and hidden phenomena in the universe. What second- generation particles are they using, which have similar properties to electrons and a spin of \(\frac{1}{2}\) that are found in cosmic rays?  


ANSWER: Muons  


## BONUS  


12) ENERGY- Short Answer Researchers at Fermi National Accelerator Laboratory are operating large clusters of computers to study lattice quantum chromodynamics. Lattice quantum chromodynamics primarily involves the interactions between what 2 elementary particles within the standard model?  


ANSWER: Quarks and Gluons  


## TOSS-UP  


13) BIO- Short Answer The node of ranvier is associated with which of the following types of cells?  


W) Hepatocytes X) Neurons Y) T cells
Z) Osteocytes  


ANSWER: X) Neurons  


## BONUS  


13) BIO- Short Answer After cell division in plants, the cell plate develops into what pectin - rich layer, which cements the primary cell walls of adjacent cells?  


ANSWER: Middle Lamella  


## TOSS-UP  


14) CHEM- Short Answer The standard calomel electrode is a reference electrode based on the reactions of what unusual transition metal?  


ANSWER: MERCURY  


## BONUS  


14) CHEM- Short Answer The contraction of d and f block elements can be explained by the probability distribution of the d and f orbitals leading to weaker shielding. In comparisons, d and f orbitals are said to be less what than s and p orbital? This term describes the orbital's proximity to the nucleus.  


ANSWER: PENETRATING  


## TOSS-UP  


15) PHYS- Short Answer The power output of a blackbody is proportional to what power of its temperature?  


ANSWER: FOURTH  


## BONUS  


15) PHYS- Short Answer The number density of photons emitted from a blackbody is proportional to what power of its temperature?  


ANSWER: THIRD  


## TOSS-UP  


16) MATH- Short Answer Which of the following is not a pythagorean triplet?  


W) 18, 24, 30  X) 105, 252, 273  Y) 7, 40, 41  Z) 40, 42, 58  


ANSWER: Y) 7, 40, 41
## BONUS  


16) MATH- Short Answer An arithmetic sequence has third term 7 and 51st term 79. What is the sum of the first 10 terms in this sequence?  


ANSWER: 215/2  


## TOSS-UP  


17) ESS- Multiple Choice Which of the following ages was part of the pleistocene epoch?  


W) Northgrippian 
X) Galesian 
Y) Greenlandian 
Z) Ordovician  


ANSWER: X) Galesian  


## BONUS  


17) ESS- Short Answer This group of naturally occurring silicate minerals are composed of long, thin microfibrils that can be released into the air with abrasion. What is the name for this group, which has become infamous for its negative health impacts, such as mesothelioma?  


ANSWER: Asbestos  


## TOSS-UP  


18) ENERGY- Short Answer Researchers at Argonne National Laboratory are studying tarantula myosin in order to better understand human muscle function. The sarcomere, which is the basic unit of muscle, is responsible for contraction through interactions between myosin heads and actin. What coiled protein in the sarcomere blocks myosin binding to actin until a signal transduction pathway from the brain is initiated?  


ANSWER: Tropomyosin  


## BONUS  


18) ENERGY- Short Answer Researchers at Argonne National Laboratory are taking X - rays of the human skull in order to improve military helmets. One of the intricacies of studying the structure of the skull is that it exhibits different mechanical properties depending upon its angle in relation to ballistics. What is the broader name for this property, which describes variations in the properties of an object based on different orientations and axes?  


ANSWER: Anisotropy  


## TOSS-UP
19) BIO- Short Answer The indirect pathway, which passes through the basal nuclei of the brain, involves the release of what neurotransmitter by the substantia nigra, which inhibits the thalamus?  


ANSWER: GABA or Gamma Aminobutyric Acid (DO NOT ACCEPT: Glycine)  


## BONUS  


19) BIO- Short Answer In the human body, what large muscle is responsible for the adduction of the arm at the shoulder joint and acts as an antagonist to the middle deltoid?  


ANSWER: Pectoralis Major (DO NOT ACCEPT: Pectoralis Minor)  


## TOSS-UP  


20) CHEM- Short Answer What ionic compound, whose molten form is used to dissolve silica and other metals, is a medium for glass making and consists of a group 1 metal with a polyatomic ion?  


ANSWER: SODIUM CARBONATE  


## BONUS  


20) CHEM- Short Answer Polyesters are formed by what type of polymerization that produces water?  


ANSWER: CONDENSATION POLYMERIZATION  


## TOSS-UP  


21) PHYS- Short Answer Damping in an RLC circuit is achieved by which component?  


ANSWER: RESISTOR  


## BONUS  


21) PHYS- Short Answer What is the Lorentz factor of a particle moving at 0.8c. Give your answer as a fraction in lowest terms.  


ANSWER: 5/3  


## TOSS-UP  


22) MATH- Short Answer Calculate the derivative of \(x^{5} + 6x\) at \(x = 2\)  


ANSWER: 86  


## BONUS
22) MATH- Short Answer How many petals does a rose curve with the formula of \(\mathrm{r} = 3 \cos (4\) times theta) have?  


ANSWER: 8  


## TOSS-UP  


23) ESS- Short Answer The coma and nucleus are terms associated with what type of near- Earth astronomical objects?  


ANSWER: Comets  


## BONUS  


23) ESS- Short Answer Order the following 3 asteroids in order of increasing size: (1) Ceres, (2) Eros, (3) Vesta.  


ANSWER: 2, 3, 1