sub_title[[456, 106, 540, 125]]
## TOSS-UP  

text[[115, 143, 867, 179]]
1) BIO- Short Answer C4 plants perform the Calvin cycle in what specialized cells, which are far from stomata?  

text[[115, 195, 361, 212]]
ANSWER: Bundle Sheath Cells  

sub_title[[462, 230, 533, 248]]
## BONUS  

text[[115, 265, 870, 319]]
1) BIO- Short Answer In a hypothetical environment, the trait for yellow stems is recessive, and the trait for green stems is dominant. If 81 percent of the population has yellow stems, what percentage of the population is heterozygous?  

text[[115, 333, 242, 351]]
ANSWER: \(18\%\)  

sub_title[[456, 351, 540, 369]]
## TOSS-UP  

text[[115, 386, 870, 422]]
2) CHEM- Short Answer An atom of an unknown element undergoes alpha decay to become a mercury atom. What element was the original atom?  

text[[115, 437, 257, 455]]
ANSWER: LEAD  

sub_title[[462, 472, 533, 490]]
## BONUS  

text[[115, 506, 773, 525]]
2) CHEM- Short Answer What is the bond order of the N-O bond in nitric oxide?  

text[[115, 544, 235, 562]]
ANSWER: 2.5  

sub_title[[456, 562, 540, 579]]
## TOSS-UP  

text[[115, 597, 852, 651]]
3) PHYS- Short Answer When traveling at relativistic speed, your clock may not agree with someone's clock in a reference frame at rest, what effect in special relativity causes this discrepancy?  

text[[115, 666, 348, 684]]
ANSWER: TIME DILATION  

sub_title[[462, 684, 533, 701]]
## BONUS  

text[[115, 719, 870, 754]]
3) PHYS- Short Answer How many numbers completely describe the spacetime position of an event in our universe?  

text[[115, 772, 221, 790]]
ANSWER: 4  

sub_title[[456, 791, 540, 809]]
## TOSS-UP  

text[[115, 826, 850, 862]]
4) MATH- Short Answer How many distinct sets of 3 vertices can be chosen from a regular hexagon  

text[[115, 877, 323, 895]]
ANSWER: 20 (6 choose 3)sub_title[[462, 108, 533, 125]]
## BONUS  

text[[115, 142, 696, 161]]
4) MATH- Short Answer How many prime numbers are less than 100?  

text[[115, 177, 230, 194]]
ANSWER: 25  

sub_title[[455, 195, 540, 212]]
## TOSS-UP  

text[[115, 230, 839, 266]]
5) ESS- Short Answer Order the following three seismic waves by the order in which they arrive at a seismograph: 1) P waves 2) S waves 3) Surface waves  

text[[115, 281, 245, 299]]
ANSWER: 1 2 3  

sub_title[[462, 316, 533, 333]]
## BONUS  

text[[115, 350, 729, 369]]
5) ESS- Short Answer What rock comprises the majority of Earth's mantle?  

text[[115, 387, 324, 405]]
ANSWER: PERIDOTITE  

sub_title[[455, 405, 540, 422]]
## TOSS-UP  

text[[115, 440, 870, 494]]
6) ENERGY- Short Answer Researches at Brookhaven National Lab are studying how gold nuclei collide at low energies in a particle accelerator. During the collision, what form of matter can momentarily be created, in which the nucleus falls apart into quarks and gluons?  

text[[115, 510, 427, 528]]
ANSWER: QUARK-GLUON PLASMA  

sub_title[[462, 528, 533, 545]]
## BONUS  

text[[115, 562, 881, 615]]
6) ENERGY- Short Answer Researches at Brookhaven National Lab are studying how gold nuclei collide at low energies in a particle accelerator. What is the most common type of quark in these nuclei?  

text[[115, 634, 346, 652]]
ANSWER: DOWN QUARK  

sub_title[[455, 670, 540, 687]]
## TOSS-UP  

text[[112, 705, 850, 724]]
7) BIO- Short Answer What plant hormone is responsible for mediating the triple response?  

text[[115, 740, 277, 758]]
ANSWER: Ethylene  

sub_title[[462, 758, 533, 775]]
## BONUS  

text[[112, 793, 802, 812]]
7) BIO- Multiple Choice Which of the following plant groups are not gymnosperms?  

text[[115, 829, 258, 899]]
W) Cycadophytes 
X) Ginkgophytes 
Y) Anthophytes 
Z) Gnetophytestext[[115, 105, 333, 123]]
ANSWER: Y) Anthophytes  

sub_title[[455, 123, 540, 141]]
## TOSS-UP  

text[[113, 159, 768, 178]]
8) CHEM- Short Answer What is the molecular geometry of sulfur hexafluoride?  

text[[115, 193, 334, 210]]
ANSWER: OCTAHEDRAL  

sub_title[[462, 211, 533, 229]]
## BONUS  

text[[115, 245, 883, 299]]
8) CHEM- Short Answer An ideal gas expands isothermally from an initial volume of 5 liters to a final volume of 15 liters. What is the final pressure of the gas if the initial pressure is 30 atmospheres?  

text[[115, 317, 231, 335]]
ANSWER: 10  

sub_title[[455, 336, 540, 354]]
## TOSS-UP  

text[[115, 370, 857, 407]]
9) PHYS- Short Answer What law relates the angle of refraction for light in a medium to the medium's index of refraction?  

text[[115, 421, 330, 439]]
ANSWER: SNELL'S LAW  

sub_title[[462, 440, 533, 458]]
## BONUS  

text[[115, 475, 876, 510]]
9) PHYS- Short Answer What general type of fluid flow occurs when the Reynold's number of the fluid is relatively low?  

text[[115, 529, 362, 547]]
ANSWER: LAMINAR FLOW  

sub_title[[455, 547, 540, 565]]
## TOSS-UP  

text[[115, 584, 866, 638]]
10) MATH- Short Answer A parabola is given by the equation \(y = (x + 1)^2 - 5\) . The parabola is then moved 2 units right and 3 units up. It is then reflected across the x-axis. What are the coordinates of its new vertex?  

text[[115, 653, 255, 671]]
ANSWER: (1, - 2)  

sub_title[[462, 671, 533, 689]]
## BONUS  

text[[115, 706, 880, 742]]
10) MATH- Short Answer What is the volume of a frustum with circular bases of radius 6 and 3 and a height of 4?  

text[[115, 761, 244, 779]]
ANSWER: 84π  

sub_title[[455, 780, 540, 798]]
## TOSS-UP  

text[[115, 815, 870, 868]]
11) ESS- Short Answer An area of land is lifted by tectonic forces into a mountain. Over time, this mountain erodes and becomes flat again. Then sediments are deposited onto the land and lithified. What type of unconformity does this process produce in this area?  

text[[115, 884, 454, 902]]
ANSWER: ANGULAR UNCONFORMITYsub_title[[462, 89, 533, 107]]
## BONUS  

text[[115, 123, 848, 160]]
11) ESS- Short Answer What rare type of stars display strong stellar winds that have blown away most or all of their hydrogen envelopes?  

text[[115, 178, 404, 196]]
ANSWER: WOLF- RAYET STARS  

sub_title[[455, 196, 540, 214]]
## TOSS-UP  

text[[115, 231, 868, 285]]
12) ENERGY- Short Answer Researchers at Ames National Lab have found a way to convert lignin into nylon polymers. What type of polymers, which includes nylon, are made of different monomers combined into one polymer?  

text[[115, 300, 333, 317]]
ANSWER: COPOLYMERS  

sub_title[[461, 319, 533, 337]]
## BONUS  

text[[115, 353, 868, 406]]
12) ENERGY- Short Answer Researchers at Ames National Lab have found a way to convert lignin into nylon polymers. This process involves converting cyclohexanol into cyclohexanone. What gas is released during this reaction?  

text[[115, 423, 321, 441]]
ANSWER: HYDROGEN  

sub_title[[455, 460, 540, 478]]
## TOSS-UP  

text[[115, 495, 877, 514]]
13) BIO- Short Answer Zygapophysial joints are plane joints located in what skeletal structure?  

text[[115, 529, 443, 547]]
ANSWER: Vertebral Column or Vertebrae  

sub_title[[461, 564, 533, 582]]
## BONUS  

text[[115, 598, 877, 635]]
13) BIO- Short Answer Identify all of the following proteins that are located within the I band of a sarcomere: (1) Myosin, (2) Actin, (3) Nebulin, (4) Titin.  

text[[115, 653, 260, 671]]
ANSWER: 2, 3, 4  

sub_title[[455, 671, 540, 689]]
## TOSS-UP  

text[[115, 706, 875, 742]]
14) CHEM- Short Answer What is the name for the effect in which the ionization of an atom is immediately followed by the absorption of a free electron into the atom?  

text[[115, 758, 344, 776]]
ANSWER: AUGER EFFECT  

sub_title[[461, 775, 533, 793]]
## BONUS  

text[[115, 810, 812, 846]]
14) CHEM- Short Answer What is the limit of the derivative of entropy with respect to temperature as temperature approaches zero kelvins?  

text[[115, 864, 221, 882]]
ANSWER: 0sub_title[[455, 88, 540, 106]]
## TOSS-UP  

text[[114, 124, 872, 160]]
15) PHYS- Short Answer What process can be considered as an inverse of beta positive decay, in which an electron is absorbed by a nucleus?  

text[[115, 175, 395, 193]]
ANSWER: ELECTRON CAPTURE  

sub_title[[461, 195, 533, 212]]
## BONUS  

text[[115, 228, 867, 264]]
15) PHYS- Short Answer What phase of matter is created by supercooling gases and has been suggested as an explanation for the superfluidity of Helium-4?  

text[[115, 283, 490, 300]]
ANSWER: BOSE-EINSTEIN CONDENSATE  

sub_title[[455, 301, 540, 319]]
## TOSS-UP  

text[[115, 336, 860, 356]]
16) MATH- Short Answer What is the distance between the point (5,6) and the point (-3,-9)?  

text[[115, 371, 225, 388]]
ANSWER: 17  

sub_title[[461, 387, 533, 405]]
## BONUS  

text[[115, 422, 880, 459]]
16) MATH- Multiple Choice A quadrilateral is created by choosing 4 random points on a circle and connecting them. What is the probability that this quadrilateral tessellates the plane?  

text[[115, 457, 186, 528]]
W) \(25\%\) X) \(50\%\) Y) \(75\%\) Z) \(100\%\)  

text[[115, 548, 280, 566]]
ANSWER: Z) \(100\%\)  

sub_title[[455, 566, 540, 584]]
## TOSS-UP  

text[[115, 601, 835, 638]]
17) ESS- Short Answer Identify all of the following three solar system objects that have a substantial atmosphere: 1) Titan 2) Miranda 3) Callisto  

text[[115, 652, 272, 670]]
ANSWER: 1 ONLY  

sub_title[[461, 670, 533, 688]]
## BONUS  

text[[115, 704, 857, 741]]
17) ESS- Short Answer What is the term for a glacier that forms in an alpine region and then flows onto a plain, where it quickly spreads out?  

text[[115, 759, 402, 777]]
ANSWER: PIEDMONT GLACIER  

sub_title[[455, 777, 540, 794]]
## TOSS-UP  

text[[115, 812, 835, 865]]
18) ENERGY- Short Answer Researchers at Oak Ridge National Lab have been studying interactions between neutrinos and baryonic matter. Neutrinos are produced by interactions caused by which fundamental force?  

text[[115, 881, 328, 899]]
ANSWER: WEAK FORCEsub_title[[462, 90, 533, 107]]
## BONUS  

text[[115, 123, 853, 177]]
18) ENERGY- Short Answer Researchers at Oak Ridge National Lab have been studying interactions between neutrinos and baryonic matter. What hypothetical type of neutrino could explain the dark matter in our universe?  

text[[115, 196, 395, 214]]
ANSWER: STERILE NEUTRINO  

sub_title[[455, 250, 540, 268]]
## TOSS-UP  

text[[115, 286, 866, 322]]
19) BIO- Short Answer In the human body, what is the only bone that does not articulate with any other bones?  

text[[115, 338, 295, 356]]
ANSWER: Hyoid bone  

sub_title[[462, 355, 533, 372]]
## BONUS  

text[[115, 389, 859, 443]]
19) BIO- Short Answer The kinetoplastid Trypanosoma Brucei is famously known to cause what disease, which is characterized by severe headaches and fatigue? This disease is spread through fly bites.  

text[[115, 462, 825, 482]]
ANSWER: African Sleeping Sickness (ACCEPT: Sleeping Sickness or Trypanosomiasis)  

sub_title[[455, 498, 540, 515]]
## TOSS-UP  

text[[115, 532, 668, 551]]
20) CHEM- Short Answer What is the chemical formula for phenol?  

text[[115, 567, 266, 585]]
ANSWER: C6H6O  

sub_title[[462, 584, 533, 601]]
## BONUS  

text[[112, 618, 812, 638]]
20) CHEM- Multiple Choice Which of the following molecules contains a triple bond?  

text[[115, 655, 226, 726]]
W) Acetylene X) Ethylene Y) Ethane Z) Propane  

text[[115, 745, 355, 763]]
ANSWER: W) ACETYLENE  

sub_title[[455, 762, 540, 780]]
## TOSS-UP  

text[[115, 797, 816, 833]]
21) PHYS- Short Answer What theorem in fluid mechanics, derivable from Bernouill's principle, gives the velocity of a stream of laminar fluid exiting a container?  

text[[115, 849, 520, 884]]
ANSWER: TORRICELLI'S THEOREM (OR LAW) BONUStext[[114, 88, 830, 125]]
21) PHYS- Short Answer Fluids often form stable structures such as smoke rings that are examples of what 3 dimensional shape that is a closed loop?  

text[[115, 144, 275, 162]]
ANSWER: TORUS  

sub_title[[455, 161, 540, 180]]
## TOSS-UP  

text[[115, 197, 844, 251]]
22) MATH- Short Answer What 3d analog of polar coordinates is defined by a series of xy planes each defined by an r and theta for the function in that plane and a z value for the z coordinate of the function in each plane?  

text[[115, 265, 470, 283]]
ANSWER: CYLINDRICAL COORDINATES  

sub_title[[462, 300, 533, 319]]
## BONUS  

text[[115, 335, 852, 373]]
22) MATH- Short Answer What is the name of the spiral formed when the function \(r = \theta\) is plotted in polar coordinates?  

text[[115, 390, 419, 409]]
ANSWER: ARCHIMEDEAN SPIRAL  

sub_title[[455, 409, 540, 427]]
## TOSS-UP  

text[[115, 444, 875, 480]]
23) ESS- Short Answer What is the name of the boundary that separates the Earth's mantle and its crust?  

text[[115, 496, 490, 514]]
ANSWER: MOHOROVICIC DISCONTINUITY  

sub_title[[462, 514, 533, 531]]
## BONUS  

text[[115, 548, 875, 584]]
23) ESS- Short Answer What is the name of a binary system in which both stars are larger than their Roche lobes?  

text[[115, 602, 382, 620]]
ANSWER: CONTACT BINARY