sub_title[[456, 106, 541, 125]]
## TOSS-UP  

text[[115, 142, 783, 163]]
1) BIO- Short Answer Identify all of the following that are antigen presenting cells.  

text[[115, 177, 527, 197]]
1- T cell, 2- Dendritic Cell, 3- B cell, 4- Macrophages  

text[[115, 212, 277, 230]]
ANSWER: 2 AND 4  

sub_title[[462, 246, 533, 264]]
## BONUS  

text[[115, 280, 870, 317]]
1) BIO- Short Answer Cytotoxic T cells are activated by binding to what specific molecules on the surface of infected cells?  

text[[115, 335, 336, 353]]
ANSWER: CLASS 1 MHC  

sub_title[[456, 353, 540, 371]]
## TOSS-UP  

text[[115, 388, 870, 425]]
2) CHEM- Short Answer What is the term for disubstituted benzene rings with substituents on the 1 and 3 positions?  

text[[115, 441, 260, 459]]
ANSWER: META  

sub_title[[462, 476, 533, 494]]
## BONUS  

text[[115, 510, 800, 546]]
2) CHEM- Short Answer Answer the following questions about nucleophilic aromatic substitution.  

text[[141, 562, 867, 600]]
A) It requires what type of group in the ortho or para position relative to the leaving group? 
B) What is the name for its intermediate resonance-stabilized anionic complex?  

text[[115, 615, 513, 634]]
ANSWER: EWG, MEISENHEIMER COMPLEX  

sub_title[[456, 650, 540, 669]]
## TOSS-UP  

text[[115, 686, 867, 722]]
3) PHYS- Short Answer The quantization of angular momentum in fundamental particles was discovered by what experiment in 1922?  

text[[115, 737, 485, 755]]
ANSWER: STERN-GERLACH EXPERIMENT  

sub_title[[462, 772, 533, 790]]
## BONUS  

text[[115, 807, 847, 844]]
3) PHYS- Short Answer Quantum physicists hypothesize that the exchange of the graviton gives rise to the force of gravity. What is the spin of the hypothetical graviton?  

text[[115, 861, 221, 879]]
ANSWER: 2sub_title[[455, 88, 540, 106]]
## TOSS-UP  

text[[113, 123, 852, 176]]
4) MATH- Short Answer 15 choose 7 plus 15 choose 8 is equal to n choose k. What is n+k? ANSWER: 24  

sub_title[[461, 194, 533, 212]]
## BONUS  

text[[113, 229, 870, 248]]
4) MATH- Short Answer How many terms does the trinomial expansion of \((a + b + c)^{\wedge}10\) have?  

text[[115, 265, 314, 284]]
ANSWER: 66 (12\*11/2)  

sub_title[[455, 283, 540, 302]]
## TOSS-UP  

text[[113, 319, 870, 339]]
5) ESS- Short Answer What is the name for the equatorial region where the trade winds meet?  

text[[113, 352, 835, 371]]
ANSWER: ITCZ OR INTERTROPICAL CONVERGENCE ZONE (ACCEPT: DOLDRUMS)  

sub_title[[461, 387, 533, 405]]
## BONUS  

text[[113, 421, 793, 441]]
5) ESS- Short Answer El niño and la niña are different phases of what overall cycle?  

text[[115, 459, 437, 477]]
ANSWER: El- niño Southern Oscillation  

sub_title[[455, 477, 540, 495]]
## TOSS-UP  

text[[115, 512, 800, 566]]
6) ENERGY- Short Answer Scientists at Lawrence Berkeley National Laboratory are developing methods to detect chromosomal defects in sperm cells. In the human male reproductive system, what cells, next to the seminiferous tubules, are activated by LH?  

text[[115, 582, 339, 600]]
ANSWER: LEYDIG CELLS  

sub_title[[461, 599, 533, 617]]
## BONUS  

text[[115, 634, 794, 688]]
6) ENERGY- Short Answer Scientists at Lawrence Berkeley National Laboratory are developing methods to detect chromosomal defects in sperm cells. In the human male reproductive system, what tube connects the vas deferens to the testes?  

text[[115, 705, 325, 723]]
ANSWER: EPIDIDYMIS  

sub_title[[455, 761, 540, 779]]
## TOSS-UP  

text[[115, 796, 865, 832]]
7) BIO- Short Answer Oseltamivir, used to treat influenza, is a powerful antiviral that inhibits what important molecules on viral coatings?  

text[[115, 848, 363, 866]]
ANSWER: NEURAMINIDASE  

sub_title[[461, 866, 533, 884]]
## BONUStext[[115, 89, 867, 125]]
7) BIO- Short Answer AIP in gram positive bacteria is an autoinducer for a signaling pathway that implicates in what effect observed in groups of bacteria such as Aliivibrio fischeri?  

text[[115, 144, 386, 162]]
ANSWER: QUORUM SENSING  

sub_title[[456, 162, 540, 180]]
## TOSS-UP  

text[[115, 198, 757, 216]]
8) CHEM- Short Answer How many d electrons are in the permanganate anion?  

text[[115, 232, 216, 249]]
ANSWER: 0  

sub_title[[463, 249, 533, 266]]
## BONUS  

text[[115, 284, 875, 319]]
8) CHEM- Short Answer The copper (II) fluoride complex has peaks in its absorbance diagram at two distinct points. This is caused by what molecular effect?  

text[[115, 336, 770, 354]]
ANSWER: JAHN-TELLER EFFECT (ACCEPT: JAHN TELLER DISTORTION)  

sub_title[[456, 371, 540, 389]]
## TOSS-UP  

text[[115, 406, 825, 442]]
9) PHYS- Short Answer Calculate the voltage gap across a capacitor in series with a 9 V battery and 3 Ohm resistor at the moment when the current in the circuit is 2 A.  

text[[115, 458, 282, 475]]
ANSWER: 3 VOLTS  

sub_title[[463, 476, 533, 493]]
## BONUS  

text[[115, 510, 865, 546]]
9) PHYS- Short Answer What is the period of a series LC circuit with a 3 Henry inductor and 12 Farad capacitor. Give your answer as a decimal with three significant figures.  

text[[115, 564, 245, 581]]
ANSWER: 37.7  

sub_title[[456, 582, 540, 599]]
## TOSS-UP  

text[[115, 617, 737, 636]]
10) MATH- Short Answer How many distinct positive factors does 200 have?  

text[[115, 652, 225, 669]]
ANSWER: 12  

sub_title[[463, 670, 533, 687]]
## BONUS  

text[[115, 705, 825, 740]]
10) MATH- Short Answer What is the product of the greatest common divisor and least common multiple of 125 and 30?  

text[[115, 758, 250, 776]]
ANSWER: 3750  

sub_title[[456, 776, 540, 794]]
## TOSS-UP  

text[[115, 812, 878, 848]]
11) ESS- Short Answer What type of neutron star has a magnetic field between \(10^{\wedge}9\) and \(10^{\wedge}11\) Teslas and emits high energy EM radiation?  

text[[115, 863, 313, 880]]
ANSWER: MAGNETARsub_title[[462, 90, 533, 107]]
## BONUS  

text[[115, 123, 875, 160]]
11) ESS- Short Answer What is the name for the observation in astronomy of quick lived radio pulses that have been observed from magnetars?  

text[[115, 178, 405, 196]]
ANSWER: FAST RADIO BURSTS  

sub_title[[456, 197, 540, 214]]
## TOSS-UP  

text[[115, 231, 872, 268]]
12) ENERGY- Short Answer Researchers at Oak Ridge National Laboratory are using neutron scattering to study the dynamics of proteins involved in cancer. What is the spin of a neutron?  

text[[115, 284, 231, 301]]
ANSWER: 1/2  

sub_title[[462, 301, 533, 319]]
## BONUS  

text[[115, 335, 870, 390]]
12) ENERGY- Short Answer Researchers at Oak Ridge National Laboratory are using neutron scattering to study the dynamics of proteins involved in cancer. Answer the following questions about scattering.  

text[[143, 407, 861, 465]]
A) Electron scattering occurs by the exchange of virtual versions of what particles?  
B) What quantity, used in scattering, is the average distance that a particle travels between two collisions?  

text[[115, 487, 478, 505]]
ANSWER: PHOTONS, MEAN FREE PATH  

sub_title[[456, 542, 540, 560]]
## TOSS-UP  

text[[115, 577, 861, 614]]
13) BIO- Short Answer Generation 1 antipsychotics such as Prochlorperazine are antagonists for the D2 receptors of what neurotransmitter?  

text[[115, 629, 306, 646]]
ANSWER: DOPAMINE  

sub_title[[462, 647, 533, 665]]
## BONUS  

text[[115, 681, 872, 718]]
13) BIO- Short Answer What neurological disorder, believed to be caused by dopamine hyperactivity and glutamate reduction at NMDA receptors, causes hallucinations and delusions?  

text[[115, 736, 365, 754]]
ANSWER: SCHIZOPHRENIA  

sub_title[[456, 754, 540, 772]]
## TOSS-UP  

text[[115, 789, 835, 825]]
14) CHEM- Short Answer Gilman reagents are made with dialkyl types of what transition metal?  

text[[115, 842, 278, 859]]
ANSWER: COPPER  

sub_title[[462, 859, 533, 876]]
## BONUStext[[115, 88, 835, 125]]
14) CHEM- Short Answer How many equivalents of a Grignard reagent can react with an ester?  

text[[115, 144, 220, 162]]
ANSWER: 2  

sub_title[[455, 161, 540, 180]]
## TOSS-UP  

text[[115, 197, 852, 233]]
15) PHYS- Short Answer The temperature of a gas can be related to its kinetic energy using what fundamental constant?  

text[[115, 249, 430, 267]]
ANSWER: BOLTZMANN CONSTANT  

sub_title[[462, 266, 533, 284]]
## BONUS  

text[[115, 300, 861, 320]]
15) PHYS- Short Answer How many degrees of freedom do monatomic ideal gases possess?  

text[[115, 339, 220, 356]]
ANSWER: 3  

sub_title[[455, 355, 540, 373]]
## TOSS-UP  

text[[115, 390, 881, 428]]
16) MATH- Short Answer How many positive integer triplets (x,y,z) with x y and z less than or equal to 8 and have distinct x,y,z?  

text[[115, 443, 236, 460]]
ANSWER: 336  

sub_title[[462, 460, 533, 478]]
## BONUS  

text[[115, 494, 832, 531]]
16) MATH- Short Answer What is the maximum value of xyz if x+y+z=30 and x,y,z are positive integers?  

text[[115, 549, 255, 567]]
ANSWER: 1,000  

sub_title[[455, 567, 540, 585]]
## TOSS-UP  

text[[115, 602, 861, 639]]
17) ESS- Short Answer What precipitation occurs when supercooled water droplets freeze on the surface of already falling snowflakes outside of a cloud?  

text[[115, 654, 292, 672]]
ANSWER: GRAUPEL  

sub_title[[462, 671, 533, 689]]
## BONUS  

text[[115, 706, 857, 743]]
17) ESS- Short Answer When large scale winds circulate around regions of high atmospheric pressure and rotate clockwise in the Northern hemisphere, what is formed?  

text[[115, 761, 351, 779]]
ANSWER: ANTICYCLONE  

sub_title[[455, 778, 540, 796]]
## TOSS-UP  

text[[115, 814, 857, 869]]
18) ENERGY- Short Answer Researchers at Ames National Laboratory have invented a new algorithm to quickly find high-entropy alloys. What is the entropy of a system with \(e^{10}\) microstates assuming that \(k \cdot b = 1.38\) .  

text[[115, 886, 240, 902]]
ANSWER: 13.8sub_title[[462, 89, 533, 107]]
## BONUS  

text[[115, 123, 875, 160]]
18) ENERGY- Short Answer Researchers at Ames National Laboratory have invented a new algorithm to quickly find high-entropy alloys. Answer the following two questions about metals.  

text[[143, 176, 861, 232]]
A) Superconductivity in metals is hypothesized to be caused by the formation of what low temperature features?  
B) What is the most efficient crystal packing system?  

text[[115, 248, 839, 285]]
ANSWER: COOPER PAIRS, FCC(ACCEPT: face-centered cubic or cubic close packed or equivalent)  

sub_title[[456, 320, 538, 338]]
## TOSS-UP  

text[[115, 355, 879, 393]]
19) BIO- Short Answer Species with extremely high birth rates are said to be selecting for what factor in population dynamics?  

text[[115, 408, 214, 425]]
ANSWER: r  

sub_title[[462, 425, 533, 443]]
## BONUS  

text[[115, 459, 872, 496]]
19) BIO- Short Answer What is the name of the rapid associative learning in which youth learn the characteristics of a stimulus from their parents. This effect is present in nidifugous birds.  

text[[115, 514, 327, 532]]
ANSWER: IMPRINTING  

sub_title[[456, 532, 540, 550]]
## TOSS-UP  

text[[115, 567, 827, 603]]
20) CHEM- Short Answer What is the common name for P(Ph)3O (READ LETTER BY LETTER)  

text[[115, 618, 479, 637]]
ANSWER: TRIPHENYLPHOSPHINE OXIDE  

sub_title[[462, 653, 533, 671]]
## BONUS  

text[[115, 688, 880, 724]]
20) CHEM- Short Answer Copper II iodide is unstable because it disproportionates to what two compounds?  

text[[115, 741, 451, 760]]
ANSWER: COPPER (I) IODIDE AND I2  

sub_title[[456, 778, 540, 796]]
## TOSS-UP  

text[[112, 813, 867, 832]]
21) PHYS- Short Answer What charged fundamental particle is released in beta minus decay?  

text[[115, 848, 305, 865]]
ANSWER: ELECTRON  

sub_title[[462, 866, 533, 883]]
## BONUStext[[115, 88, 820, 125]]
21) PHYS- Short Answer In beta minus decay, a neutron is converted to a proton by the emission of a boson as a quark changes flavor. Answer the following question.  

text[[143, 141, 839, 195]]
A) What is the flavor of the quark before and after the transformation respectively?  
B) What specific fundamental boson is emitted in the quark transformation that quickly decays?  

text[[115, 213, 678, 232]]
ANSWER: A) down, up B) W- boson (DO NOT ACCEPT W OR W+)  

sub_title[[455, 249, 541, 267]]
## TOSS-UP  

text[[115, 285, 636, 304]]
22) MATH- Short Answer What is the magnitude of \(1\mathrm{i} + 2\mathrm{j} + 10\mathrm{k}\) ?  

text[[115, 320, 277, 337]]
ANSWER: sqrt(105)  

sub_title[[463, 337, 533, 355]]
## BONUS  

text[[115, 371, 658, 390]]
22) MATH- Short Answer What is the cross product of 3i with \(\mathrm{i} + \mathrm{j}\) ?  

text[[115, 408, 230, 425]]
ANSWER: 3k  

sub_title[[455, 425, 541, 443]]
## TOSS-UP  

text[[115, 461, 828, 497]]
23) ESS- Short Answer Binary star systems exist because two stars are mutually orbiting around what center, a property of their system?  

text[[115, 513, 333, 531]]
ANSWER: BARYCENTER  

sub_title[[463, 531, 533, 549]]
## BONUS  

text[[115, 565, 836, 601]]
23) ESS- Short Answer The Type 1a "Champagne Supernova" was exceptional because it resulted from a binary system including a massive white dwarf that exceeded what limit?  

text[[115, 619, 445, 638]]
ANSWER: CHANDRASEKHAR LIMIT