
# Winter Science Bowl Tournament 2022-2023 Playoff Round 2  


a5a7#2184, APLegends1#3363, cymbidium#2318<sup>‡</sup>, dan.k.memes#5912<sup>‡</sup>, dannyridel#2256, effervescence#3904, EVTrainer#5388, juneboon#0962, Rara#3565, P2ep0#1900, spencerd#4926, ThisIsDenry#0446, Vc05#6115, Vish#8148  


# Past and Present Sponsors  

image[[175, 240, 828, 526]]
## TOSS-UP  


1) Biology - Short Answer The enzyme pyruvate carboxylase requires what vitamin as its prosthetic group, which is considered to be a specialized carrier of carbon dioxide?  


ANSWER: Biotin (ACCEPT: Vitamin B7)  


## BONUS  


1) Biology - Short Answer What collection of cells in embryos of vertebrates, found at the edges of the closing neural tubes of the embryo, are known to give rise to teeth, bones, and cartilage?  


ANSWER: Neural Crest Written by: APLegends1#3363  


## TOSS-UP  


2) Earth and Space - Short Answer What type of thunderstorm contains a rotating updraft called a mesocyclone, which can spawn tornadoes?  


ANSWER: SUPERCELL [2, METEO] Eric  


## BONUS  


2) Earth and Space - Multiple Choice During Ekman transport in the northern hemisphere, the net movement of ocean water relative to the direction of surface wind is:  


W) 90 degrees to the right X) 90 degrees to the left Y) 45 degrees to the right Z) 45 degrees to the left  


ANSWER: W) 90 DEGREES TO THE RIGHT [2, OCE] Eric
## TOSS-UP  


3) Math - Short Answer A figure has a base bounded by the x-axis, the curve \(y = \sqrt{x}\) , and the line \(x = 3\) . The cross sections of the figure are perpendicular to the x-axis and are in the shape of squares. What is the volume of the figure?  


ANSWER: 9/2 [1, Calc I] <Rak>  


## BONUS  


3) Math - Short Answer Identify all of the following 3 differential equations that have a linear solution with a slope of \(\frac{1}{2}\) : 1) \(\mathrm{dy / dx} = -2x + 4y - 5\) ; 2) \(\mathrm{dy / dx} = 4x - 8y + 2\) ; 3) \(\mathrm{dy / dx} = -3x + 4y - 7\)  


ANSWER: 1 AND 2 [4, Diff eq] <Rak>  


## TOSS-UP  


4) Physics - Short Answer Three objects are released at the same height from a ramp and roll to the bottom. Rank the following objects by greatest to least in terms of the time it takes to reach the bottom: 1) spherical shell; 2) solid disc; 3) hoop.  


ANSWER: 3 1 2  


## BONUS  


4) Physics - Short Answer Assuming all incident light rays are parallel, what is the focal length of a glass hemisphere with a radius of 5 centimeters and index of refraction of 1.2 if incoming light is incident on the round side?  


ANSWER: 25 [Geometric Optics, 4] ThisIsDenry#0446  


## TOSS-UP  


5) Chemistry - Short Answer Identify all of the following 3 choices which are correct regarding gas liquid chromatography.  


1) Hydrogen can be used as the mobile phase  
2) Soluble compounds will have a shorter retention time  
3) Reducing temperature decreases separation in the column  


ANSWER: 1 ONLY  


## BONUS  


5) Chemistry - Short Answer Identify the following 3 choices that are TRUE regarding the Hofmann Elimination, which prepares alkenes from amines.  


1) It can be enhanced by the use of methyl iodide on the amine  
2) It follows an E1 mechanism  
3) Its major product is the less substituted alkene  


ANSWER: 1 AND 3 Written by APLegends1#336/Org (Kleins)
## TOSS-UP  


6) Energy – Short Answer For many decades, NASA has observed Jupiter's magnetosphere to be by far the strongest among the Solar System planets. The circulation of what liquid element, found in Jupiter's outer core, causes the planet's magnetic field?  


ANSWER: Hydrogen  


## BONUS  


6) Energy – Short Answer Oak Ridge National Lab researchers observe a blue glow emitted from an underwater nuclear reactor. They determine that these emissions are caused by the passing of charged particles generated by the reactor through water faster than light travels in water. What is the name of this type of radiation?  


ANSWER: Cherenkov Radiation  


## TOSS-UP  


7) Biology - Short Answer What protein, found in smooth muscle cells and structurally-related to troponin, is known to activate the myosin light-chain kinase?  


ANSWER: Calmodulin Written by: APLegends1#3363  


## BONUS  


7) Biology - Multiple Choice Which of the following is NOT true regarding boron's role on plant growth?  


W) Boron regulates calcium ion utilization in plants 
X) Boron regulates nucleic acid synthesis and cell wall stability 
Y) Boron regulates the active sites of enzymes in nitrogen metabolism 
Z) Eudicots generally require more boron than monocots  


ANSWER: Y) Boron regulates the active sites of enzymes in nitrogen metabolism
## TOSS-UP  


8) Earth and Space – Multiple Choice Which term refers to the global system of deep-water currents driven by variations in density?  


W) Langmuir circulation  X) thermohaline circulation  Y) Ekman transport  Z) equatorial counter current  


ANSWER: X) THERMOHALINE CIRCULATION [2, OCE] Eric  


## BONUS  


8) Earth and Space – Short Answer What structures form when a meander in an ocean current pinches off and spins around either a warm core or a cold core?  


ANSWER: EDDIES (ACCEPT: EDDY)
## TOSS-UP  


9) Math – Multiple Choice Which of the following values does the integral from 0 to infinity of \(1 / (1 + x^{\wedge}2)\) [one divided by the quantity one plus x squared] converge to?  


W) \(\pi\) X) \(\pi /2\) Y) 2 Z) 1  


ANSWER: X) \(\pi /2\) [5, Calc I] <Rak>  


## BONUS  


9) Math – Multiple Choice Which of the following correctly represents the integrand of the Laplace Transform of \(\sin (\mathrm{at})\) [sine of the quantity a t]?  


W) X) Y) Z) ANSWER: Y) [4, diff eq] <Rak>  


## TOSS-UP  


10) Physics – Short Answer Tony is carrying a tank full of water when it gets punctured by a wild dart. If the water level is 20 cm above the hole, to the nearest whole number, how fast is the water flowing when it leaves the tank?  


ANSWER: 2m/s  


## BONUS  


10) Physics – Short Answer To one significant figure and using the ideal gas approximation, what is the root-mean-square speed of a Helium molecule in Helium gas at 1000 kelvin?  


ANSWER: 2000 [Kinetic Theory, 4] ThisIsDenry#0446
## TOSS-UP  


11) Chemistry - Short Answer In the presence of an acid or a base, a ketone containing an alpha proton will exist in equilibrium with what type of compound, also its tautomer?  


ANSWER: Enol  


## BONUS  


11) Chemistry - Short Answer Identify the following 4 choices which are true of lithium and of its properties. 1) It is high in ionic character and low in covalent character compared to alkali metals 2) It is the only alkali metal to form nitrides 3) It is inefficient for hydrogen storage 4) It tends to form a superoxide when heated with excess oxygen  


ANSWER: 2 ONLY  


## TOSS-UP  


12) Energy - Short Answer Brookhaven National Lab estimates the national prevalence of various genetic disorders through testing a sample of neonates. What human autosomal recessive disease, tested by measuring sweat chlorine levels, causes frequent lung infections due to mutations to chromosome 7?  


ANSWER: Cystic fibrosis  


## BONUS  


12) Energy - Short Answer Acromegaly, a disorder which results in enlarged hands, feet, and skeletal muscle, is often caused by the growth of a benign tumor in the brain which results in the excessive release of somatotropin. What part of the brain do these tumors disrupt?  


ANSWER: Pituitary gland (ACCEPT: Anterior Pituitary)  


## TOSS-UP  


13) Biology - Short Answer The presence of what aminopolysaccharide polymer allows for the exoskeleton of arthropods to remain extremely durable?  


ANSWER: Chitin Written by: APLegends1#3363  


## BONUS  


13) Biology - Short Answer Order the following 4 regions of the adrenal gland from most inner to most outer.  


1) Zona fasciculata 
2) Zona glomerulosa 
3) Zona reticularis 
4) Medulla  


ANSWER: 4, 3, 1, 2 Written by: APLegends1#3363.
## TOSS-UP  


14) Earth and Space – Short Answer What phenomenon is responsible for melting the interior of the moon Io and driving its volcanism?  


ANSWER: TIDAL HEATING (ACCEPT: TIDES) [2, SPACE] Tony  


## BONUS  


14) Earth and Space – Multiple Choice Which of the following statements best explains why basaltic lava forms very little pyroclastic material?  


W) Its silica content is high  X) Its temperature is low  Y) Its gas content is high  Z) Its viscosity is low  


ANSWER: Z) ITS VISCOSITY IS LOW [2, GEO] Tony
## TOSS-UP  


15) Math - Short Answer What is the volume of the object formed by rotating the equation \(y = \operatorname {sqrt}(x)\) [y equals the square root of x] about the x axis on the closed interval from 0 to 3?  


ANSWER: \(9\pi /2\) [4, Calc I] <Rak>  


## BONUS  


15) Math - Short Answer If \(\sin (x) - \cos (x) = \frac{1}{2}\) , what is the value of \(\sin (x) + \cos (x)\) in simplest radical form if x is between 0 and \(2\pi\) ?  


ANSWER: sqrt(17)/3 [3, ALG] Tony  


## TOSS-UP  


16) Physics - Short Answer A light golf ball is placed on a heavy basketball. Assuming the sizes of the balls are negligible, if the two balls are dropped through a height of 2 meters, how high does the golf ball rise from the ground?  


ANSWER: 8 [Momentum, 4] ThisIsDenry#0446  


## BONUS  


16) Physics - Short Answer What is the minimum coefficient of static friction required for a uniform hoop to roll without slipping down an inclined plane at an angle 30 degrees above the horizontal?  


ANSWER: \(\sqrt{3} /6\) [Rotat. Dynamics, 5] ThisIsDenry#0446  


## TOSS-UP  


17) Chemistry - Short Answer Identify all the following 3 choices that are generally true of blue metal-ammonia solutions. 1) They are relatively concentrated 2) They have electrical conductance similar to a metal 3) They are excellent reducing agents.  


ANSWER: 3 ONLY  


## BONUS  


17) Chemistry - Multiple Choice Alice finds that her solid state NMR spectra has low resolution, which she hypothesizes is due to dipolar magnetic coupling. Her direct investigator suggests spinning her sample at high speeds relative to the field axis. At which of the following angles should Alice spin her samples?  


W) 32 degrees X) 44 degrees Y) 55 degrees Z) 67 degrees  


ANSWER: Y) 55 degrees
## TOSS-UP  


18) Energy – Short Answer Lawrence Livermore National Lab investigates a rare set of stars to determine the origin of their surrounding nebulae. These stars exhibit broad emission lines of ionized helium, nitrogen, and carbon. What term refers to these massive stars, which are known for their strong stellar winds?  


ANSWER: Wolf-Rayet stars (ACCEPT: WR stars)  


## BONUS  


18) Energy – Short Answer When Princeton Plasma Physics Laboratory researchers run spectroscopic procedures, they find that spectral lines split into several components when in the presence of a static magnetic field. What is the name of this effect, which can be used to determine the magnetic field strength of stars?  


ANSWER: Zeeman effect  


## TOSS-UP  


19) Biology - Short Answer Identify all of the following 3 disorders that are known to be caused by simple sequence repeats.  


1) Fragile X Syndrome 
2) Huntington's Disease 
3) Edward's Syndrome  


ANSWER: 1 AND 2 ONLY  


## BONUS  


19) Biology - Multiple Choice Which of the following is TRUE regarding echinoderms?  


W) Echinoderms are acoelomates 
X) Echinoderms contain a water vascular system 
Y) Echinoderms contain cephalization 
Z) Echinoderms descended from radially symmetrical ancestors  


ANSWER: X) Echinoderms contain a water vascular system
## TOSS-UP  


20) Earth and Space – Short Answer Carbon deflagration is a series of violent nuclear reactions that precedes a type Ia supernova in which type of star?  


ANSWER: WHITE DWARF [2, SPACE] Tony  


## BONUS  


20) Earth and Space – Multiple Choice Wien’s law states that the temperature of a black body and its wavelength of maximum intensity emitted follows which of the following relationships?  


W) Inverse  X) Direct  Y) Quadratic  Z) Inverse Square  


ANSWER: W) INVERSE [2, SPACE] Tony
## TOSS UP  


21) Math - Multiple Choice What value of k makes the piecewise function \(3x^{2} + 2\) for \(x > 2\) and \(2x + k\) for \(x \leq 2\) continuous?  


W) 1  X) 10  Y) - 10  Z) 5  


ANSWER: X) 10 [2, Calc I] <Rak>  


## BONUS  


21) Math - Short Answer What is the slope of the line perpendicular to the tangent line of the graph \(2xy + x^2 = y^2 + 100\) at the point (10, 0)?  


ANSWER: 1 [3, Calc I] <Rak>  


## TOSS UP  


22) Physics - Short Answer In scientific notation and in units of \(\mathrm{N} / \mathrm{m}^2\) (read: newtons per meter squared), what is the Young's Modulus of a linear material of cross-sectional area \(10 \mathrm{cm}^2\) that sustains a tension of \(300 \mathrm{N}\) when stretched so that its length increases by \(0.1\%\) ?  


ANSWER: \(3 \times 10^8\) [Stress and Strain, 3]  ThisIsDenry#0446  


## BONUS  


22) Physics - Short Answer 1 mol solid at high temperature contains 6 degrees of freedom. To two significant figures and in scientific notation, what is the internal energy of the solid in joules at 1000 K?  


Answer: \(5.0 \times 10^4\) [Kinetic Theory, 4]  ThisIsDenry#0446  


## TOSS-UP  


23) Chemistry - Short Answer The preparation of 1-bromobutane from 1-bromocyclopentene can be catalyzed by what reagent, containing both copper and lithium?  


ANSWER: Gilman's Reagent  


## BONUS  


23) Chemistry - Multiple Choice Which of the following types of carbon atoms will generally produce the lowest chemical shift downwards in parts per million on a Carbon-13 NMR spectrum?  


W) Carbon of Carbonyl  X) Carbon of Ethene  Y) Carbon of Methine  Z) Carbon of Organic Acid  


ANSWER: Y) Carbon of Methine