
# Winter Science Bowl Tournament 2022-2023 Playoff Round 5  


a5a7#2184, APLegends1#3363, cymbidium#2318<sup>‡</sup>, dan.k.memes#5912<sup>‡</sup>, dannyridel#2256, effervescence#3904, EVTrainer#5388, juneboon#0962, Rara#3565, P2ep0#1900, spencerd#4926, ThisIsDenry#0446, Vc05#6115, Vish#8148  


# Past and Present Sponsors  

image[[175, 240, 828, 526]]
## TOSS-UP  


1) Biology – Short Answer What group of cells, known to differentiate in the presence of insulin-like growth factors, carries out the production of new cartilage at the epiphyseal plate? ANSWER: Chondrocytes  


Written by: APLegends1#3363  


## BONUS  


1) Biology – Short Answer Identify the following is TRUE regarding the Excavata clade 1) Parabasalids contain hydrogen-releasing mitochondria known as hydrogenosomes 2) Euglenozoans are anaerobic organisms containing reduced mitochondria with no electron transport chain 3) Diplomonads are known to contain a spiral or crystalline rod within their flagella  


ANSWER: 1 ONLY  


## TOSS-UP  


2) Earth and Space – Multiple Choice Which of the following is NOT produced by an earthquake?  


W) S-wave  X) Love wave  Y) Rayleigh wave  Z) Rossby wave  ANSWER: Z) ROSSBY WAVE [3, GEO] Eric  


## BONUS  


2) Earth and Space – Short Answer Identify all of the following three fossils that are considered trace fossils:  


1) coprolite; 2) tracks; 3) amber fossils  


ANSWER: 1 AND 2 [3, GEO] Tony  


## TOSS-UP  


3) Math – Short Answer If find when  


ANSWER: <spencerd>  


## BONUS  


3) Math – Short Answer Find if: and  


ANSWER: <spencerd>
## TOSS-UP  


4) Physics - Multiple Choice Indium Tin Oxide (ITO) typically has a band gap of 3.5 eV. Which of the following types of materials could it belong to?  


W) Conductor 
X) p-type Semiconductor 
Y) n-type Semiconductor 
Z) Insulator  


ANSWER: Y) n-type Semiconductor dannyridel#2256  


## BONUS  


4) Physics - Short Answer The ideal band gap for a basic solar cell is slightly more than 1 eV. On what part of the electromagnetic spectrum does the light corresponding to this ideal band gap fall?  


ANSWER: Infrared (\~1000nm) dannyridel#2256
## TOSS-UP  


5) Chemistry - Multiple Choice Which of the following is incorrect regarding iodine pentoxide?  


W) It is used to oxidize carbon monoxide  
X) It is a hygroscopic white solid  
Y) It is commercially produced via photolysis  
Z) It is thermally stable above -40 C  


ANSWER: Y) It is commercially produced via photolysis  


# VISUAL BONUS  

image[[301, 227, 695, 336]]  


5) Chemistry - Short Answer What is the expected lambda max of the molecule above assuming its base value is 217 nm?  


ANSWER: 390nm  Written by APLegends1#3363/Org (Klein)  


## TOSS-UP  


6) Energy - Short Answer Pacific Northwest Lab scientists observe a human patient's death. After infection, the patient exhibits behavioral changes and memory problems, which develop into blindness and dementia within a year. What disease, which has a 100% fatality rate, do the researchers most likely observe?  


ANSWER: Creutzfeldt-Jakob disease; subacute spongiform encephalopathy; transmissible spongiform encephalopathy  


## BONUS  


6) Energy - Short Answer The researchers observe another patient, a retired boxer, who exhibits similar symptoms of coordination loss and dementia, as well as aggression and amnesia, as a result of repeated brain trauma. What disease do they exhibit?  


ANSWER: Chronic traumatic encephalopathy
## TOSS-UP  


7) Biology - Multiple Choice Which of the following is NOT true regarding gluconeogenesis?  


W) Gluconeogenesis takes place within the cytoplasm 
X) Gluconeogenesis begins with the transportation of malate across the mitochondrial membrane 
Y) Gluconeogenesis is considered to be a reversible process in cells 
Z) The rate of gluconeogenesis increases in the presence of fatty acids ANSWER: Y) Gluconeogenesis is considered to be a reversible process in cells Written by: APLegends1#3363  


## BONUS  


7) Biology - Short Answer Identify the following 4 choices which originate from the Wolffian Duct in the embryos of human females.  


1) Hymen 
2) Fallopian Tubes 
3) Uterus 
4) Vestibule  


ANSWER: 2 AND 3  


## TOSS-UP  


8) Earth and Space - Multiple Choice Which of the following statements most accurately describes a relationship between metamorphic grade and the resulting metamorphic rock's properties?  


W) Higher grade decreases the degree of foliation 
X) Lower grade produces smaller grains 
Y) Lower grade decreases the abundance of hydrous minerals 
Z) Higher grade commonly produces slaty rocks ANSWER: X) LOWER GRADE PRODUCES SMALLER GRAINS [3, GEO] Tony  


## VISUAL BONUS  


8) Earth and Space - Short Answer Label the environmental conditions represented by the colored sections in the order that is numbered:  

image[[58, 653, 465, 895]]  


ANSWER: Absolute Instability, Conditional Instability, Absolute Stability [3, METEO] Tony
## TOSS-UP  


9) Math - Short Answer If is a positive integer less than 53, and is congruent to 15 modulo 53, what is the sum of the 2 possible values of x  


ANSWER: 53 [Number Theory] <spencerd>  


## BONUS  


9) Math - Short Answer Order the following 4 terms from largest to smallest:  


1)  


2)  


3)  


4)  


ANSWER: 1,2,3,4 [Calc I] <spencerd>  


## TOSS-UP  


10) Physics - Short Answer The Davisson-Germer experiment confirmed de Broglie's matter wave hypothesis by observing the diffraction pattern of what particle, which was scattered from a nickel crystal?  


ANSWER: ELECTRON [Wave/Part. Dual., 2] ThisIsDenry#0446  


## BONUS  


10) Physics - Short Answer What is the work done by a constant force vector \(2i - 1j\) Newtons through a straight line connecting the points (3 meters, 4 meters) and (7 meters, 5 meters)  


ANSWER: 7 [Math, 2]  


ThisIsDenry#0446
## TOSS-UP  


11) Chemistry - Short Answer Identify the following which are true regarding a reaction between an aliphatic carbon and oxidizing metal fluoride. 1) HF is always the byproduct 2) Cobalt (II) Fluoride is 3) Cyclic saturated fluoride can be produced from this reaction  


ANSWER: ALL  


## VISUAL BONUS  


11) Chemistry - Short Answer What process is shown below, which results in the formation of carboxylic acid derivatives?  

image[[130, 267, 860, 480]]  


ACCEPT: Favorskii Rearrangement (DO NOT ACCEPT: Favorskii Reaction)  Written by APLegends1#3363/Org  


## TOSS-UP  


12) Energy - Short Answer Ames Lab pharmacologists observe that the Wolff-Chaikoff effect leads to a reduction of thyroid hormone synthesis within follicular cells. What ion, when ingested, leads to this effect?  


ANSWER: Iodide  


## BONUS  


12) Energy - Short Answer Which of the following silicon types are used in modern solar cells?  


1) Monocrystalline 
2) Polycrystalline 
3) Thin Film Amorphous  


ANSWER: ALL  dannyridel#2256
## TOSS-UP  


13) Biology- Multiple Choice Which of the following structures of the nephron is primarily affected by increased expression of vasopressin?  


W) Loop of Henle  X) Bowman's Capsule  Y) Proximal Convoluted Tube  Z) Collecting Duct  


ANSWER: Z) COLLECTING DUCT  


Written by: APLegends1#3363  


## VISUAL BONUS  

image[[191, 303, 806, 553]]  


13) Biology - Short Answer Alice studies the plant above, which she finds contains yellow leaves and is unusually purple. After using liquid chromatography-mass spectrometry, she finds a high concentration of anthocyanins present within its cells. This is most likely due to the deficiency of what essential element?  


ANSWER: Phosphorous  


## TOSS-UP  


14) Earth and Space - Short Answer In 2010 a set of "bubbles" lying above and below the Milky Way were discovered by NASA's premier Fermi Telescope, which primarily observes what type of electromagnetic radiation?  


ANSWER: GAMMA RAY [3, SPACE] Eric  


## BONUS  


14) Earth and Space - Short Answer: Armaan splits open an iron meteorite and finds that its interior is marked by interweaving bands of kamacite and taenite. What is the name of these structures?  


ANSWER: WIDMANSTÄTTEN PATTERN [3, SPACE] Tony
## TOSS-UP  


15) Math – Short Answer Two numbers x and y are randomly and independently chosen from the range [0,1] [from 0 to 1, inclusive]. What is the expected value of the smaller of the two elements?  


ANSWER: [Statistics] <spencerd>  


## BONUS  


15) Math – Short Answer What is the slope of the line tangent to the curve  


at the point (1,1)?  


ANSWER:  


## TOSS-UP  


16) Physics – Short Answer What is the name of the numerical constant that describes the elastic properties of a solid or fluid when it is under pressure on all surfaces?  


ANSWER: Bulk Modulus [Stress and Strain, 2]  Vc05#6115  


## BONUS  


16) Physics – Multiple Choice How much does work is done by the force \(3\mathrm{i} + 4\mathrm{j} - 2\mathrm{k}\) newtons through a displacement of \(-1\mathrm{i} + 2\mathrm{j} + 5\mathrm{k}\) meters?  


ANSWER: - 5 [Energy, 4]  ThisIsDenry#0446
## TOSS-UP  


17) Chemistry- Multiple Choice Which of the following uses should Helium be used instead of Argon?  


W) Atmosphere to suppress oxidation of metals  
X) Cooling for superconducting magnets  
Y) Medical Imaging  
Z) Anesthetic products  


ANSWER: X) Cooling for superconducting magnets  


## BONUS  


17) Chemistry – Short Answer Identify the following 4 choices which can be used for the conversion of nitrobenzene to aniline by reduction in the presence of an aqueous acid. 1) Iron 2) Lithium Aluminum Hydride 3) Tin 4) Tin (II) Chloride  


ANSWER: 1,3, AND 4  


## TOSS-UP  


18) Energy – Short Answer Lawrence Berkeley Lab researchers couple plasmons with photons to create another quasiparticle. What particle, which can also be formed using other types of polar excitations, do they produce?  


ANSWER: Polariton  


## BONUS  


18) Energy – Short Answer Oak Ridge Lab astronomers observe that radiation pressure tangential to dust particles orbiting a star cause the particles to lose angular momentum, thereby spiraling them into the star. What term refers to this effect?  


ANSWER: Poynting-Robertson effect
## TOSS-UP  


19) Biology - Short Answer Identify all of the following that are carried out by thyroid hormones. 1) Reducing expression of glycosaminoglycans 2) Inhibiting Sodium-Potassium ATPases 3) Carbohydrate absorption from small intestine  


ANSWER: 1 and 3  Written by: APLegends1#3363  

image[[135, 192, 844, 508]]  


19) Biology - Short Answer Identify all of the following 3 choices that can be elucidated from the hydropathy index above.  


1) It exhibits a Beta-Adrenergic Receptor  
2) It exhibits a singular beta barrel from position 80-100  
3) It exhibits a cluster of charged hydrophilic residues from positions 100 to 108  


ANSWER: 3 ONLY  Written by: APLegends1#3363  


## TOSS-UP  


20) Earth and Space - Short Answer The Tharsis Rise and Elysium Region are geologic features of what planet in our Solar System?  


ANSWER: MARS  


## BONUS  


20) Earth and Space - Short Answer What theory proposed by Mordecai Milgram explains the observed rotation disks of galaxies without requiring the existence of dark matter.  


ANSWER: MODIFIED NEWTONIAN DYNAMICS (ACCEPT: MOND) [3, THRY] Eric
21) Math – Multiple Choice Which of the following is an example of a linear, 2nd order differential equation?  


W)  


X)  


Y)  


Z)  


ANSWER: Z  


## BONUS  


21) Math – Short Answer If and, find the value of  


ANSWER: 850 [Algebra] <spencerd>  


## TOSS-UP  


22) Physics – Short Answer Select all of the following processes that conserve momentum for the specified system: 1) a system of two balls undergoing a collision in which the two balls stick together 2) a system consisting of a satellite as it orbits the Sun 3) a system consisting of a photon and subsequently produced matter and antimatter as the photon undergoes pair production  


ANSWER: 1, 2 [Particle Physics, 4] ThisIsDenry#0446  


## BONUS  


22) Physics - Short Answer What approximation for the Fermi function at high energy levels simplifies it to decreasing exponentially with increasing energy?  


ANSWER: Boltzmann approximation dannyridel#2256
## TOSS-UP  


23) Chemistry - Short Answer Identify the following metals that are substitution-inert. 1) Chromium \(3+\) 2) Vanadium \(2+\) 3) Mercury \(2+\)  


ANSWER: 1 AND 2  


## BONUS  


23) Chemistry – Multiple Choice Which of the following is CORRECT about DABCO, a highly nucleophilic reagent?  


W) It is a secondary amine  
X) It is the primary reagent in the Baylis-Hillman Reaction  
Y) It is unreactive in the presence of methyl iodide  
Z) It is characterized as a flexible bicyclic reagent  


ANSWER: X) It is the primary reagent in the Baylis-Hillman Reaction