text[[123, 150, 872, 168]]
Buzzer test + Ice breaker question: Who’s birthdate, other than yours, do you have memorized the best?  

sub_title[[458, 186, 536, 203]]
## TOSS-UP  

text[[115, 220, 869, 272]]
1) Physics – Short Answer The emf of a battery is 12 volts. When the battery delivers a current of 0.5 amperes to a load, the potential difference between the terminals of the battery is 10 volts. What is the internal resistance in ohms of the battery?  

text[[115, 289, 221, 305]]
ANSWER: 24  

sub_title[[463, 323, 530, 340]]
## BONUS  

text[[115, 356, 876, 408]]
1) Physics – Short Answer Order the following 3 objects, by name or number, by increasing moment of inertia, given that the mass and radius are all the same: 1) Sphere; 2) Hoop about cylinder axis; 3) Spherical shell.  

text[[115, 424, 248, 441]]
ANSWER: 1, 3, 2  

sub_title[[458, 460, 536, 476]]
## TOSS-UP  

text[[115, 494, 882, 562]]
2) Earth and Space – Short Answer Identify, by name or number, all of the following 3 theories that are proposed about the formation of Maxwell Montes: 1) It formed over a hot plume of material rising from the interior of the planet; 2) Surrounding active volcanoes created the bedrock for it; 3) The region surrounding it is being compressed from all sides  

text[[115, 579, 225, 595]]
ANSWER: 1, 3  

sub_title[[463, 596, 530, 612]]
## BONUS  

text[[115, 629, 830, 664]]
2) Earth and Space – Multiple Choice Which of the following accurately describes the difference between uplift and subsidence?  

text[[115, 681, 870, 715]]
W) Subsidence is the motion of a surface as it moves downward relative to a datum, while an uplift is an increase in elevation.  

text[[115, 715, 857, 749]]
X) Subsidence is the downflow motion of water molecules as the water cycle occurs, while an uplift is when the water is evaporated.  

text[[115, 750, 848, 784]]
Y) Subsidence is the downflow of magmatic rocks into the earth's outer core, while an uplift is when magma flows out of the earth's crust.  

text[[115, 784, 855, 818]]
Z) Subsidence is the pumping in certain areas due to the convergence of water, while an uplift is when water is sucked due to the divergence of water.  

text[[115, 834, 835, 869]]
ANSWER: W)SUBSIDENCE IS THE MOTION OF A SURFACE AS IT MOVES DOWNWARD RELATIVE TO A DATUM, WHILE AN UPLIFT IS AN INCREASE IN ELEVATIONsub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[113, 125, 879, 160]]
3) Chemistry – Short Answer Identify, by name or number, all of the following 3 bases that would favor the Hoffman product in an E2 reaction: 1) Hydroxide ion; 2) Tert-Butoxide ion; 3) Ethylene Oxide Ion.  

text[[115, 177, 270, 193]]
ANSWER: 2 ONLY  

sub_title[[465, 211, 530, 228]]
## BONUS  

text[[113, 245, 876, 280]]
3) Chemistry – Short Answer Order the following 3 molecules, by name or number, by increasing pKa: 1) Phenol; 2) Acetylene; 3) Ethene.  

text[[115, 296, 248, 313]]
ANSWER: 1, 2, 3  

sub_title[[459, 364, 536, 381]]
## TOSS-UP  

text[[113, 398, 850, 433]]
4) Biology – Multiple Choice Which of the following is a mechanism that a neuron uses to prepare secretory vesicles near the axon terminal.  

text[[113, 449, 850, 570]]
W) The neuron uses flagella to move the secretory vesicles to the axon terminal  X) Vesicles with a high concentration of neurotransmitter ride along kinesin motors towards the axon terminal  Y) The neuron performs transcription and translation near the axon terminal to reduce the distance of diffusion of the secretory products  Z) Vesicles with a high concentration of neurotransmitter ride along actin motors towards the axon terminal  

text[[115, 586, 850, 620]]
ANSWER: X) VESICLES WITH A HIGH CONCENTRATION OF NEUROTRANSMITTER RIDE ALONG KINESIN MOTORS TOWARDS THE AXON TERMINAL  

sub_title[[465, 638, 530, 655]]
## BONUS  

text[[115, 672, 868, 724]]
4) Biology – Short Answer Identify all of the following 3 statements that are true of the yeast, Saccharomyces cerevisiae: 1) The two known mating factors for them are alpha and beta; 2) They can stably exist as either a diploid or a haploid; 3) They can undergo meiosis to produce four haploid spores.  

text[[115, 740, 230, 756]]
ANSWER: 2, 3sub_title[[455, 91, 540, 108]]
## TOSS-UP  

text[[115, 125, 651, 143]]
5) Math - Short Answer How many four digit perfect squares are there?  

text[[115, 159, 222, 176]]
ANSWER: 68  

sub_title[[465, 194, 530, 211]]
## BONUS  

text[[115, 228, 847, 262]]
5) Math - Short Answer Using Newton's Method, approximate to the nearest tenth, x sub 2 for the given function when x sub 0 is 5: f(x)=3x^2-14x+8  

text[[115, 279, 225, 295]]
ANSWER: 5.7  

sub_title[[460, 347, 536, 364]]
## TOSS-UP  

text[[115, 381, 866, 416]]
6) Physics - Short Answer A spring with a spring constant of 200Nm is compressed 0.5m. What is the potential energy in joules stored in the spring?  

text[[115, 432, 223, 448]]
ANSWER 25J  

sub_title[[465, 466, 530, 483]]
## BONUS  

text[[115, 500, 863, 552]]
6) Physics - Short Answer A block attached to a spring is moving along the x-axis on a frictionless horizontal surface. What is the hamiltonian for the block? In terms of p, the momentum, m, the mass, k, the spring constant, and x, the distance on the x-axis.  

text[[115, 568, 362, 586]]
ANSWER: \((\mathrm{p}^{\wedge}2) / (2\mathrm{m}) + (\mathrm{kx}^{\wedge}2) / 2\)sub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[115, 125, 822, 160]]
7) Earth and Space – Short Answer What aluminum rich silicate mineral, which forms at low to medium temperature and pressures, is trimorphus with sillimanite and kyanite.  

text[[115, 177, 316, 193]]
ANSWER: ANDALUSITE  

sub_title[[465, 211, 530, 228]]
## BONUS  

text[[115, 245, 870, 296]]
7) Earth and Space – Short Answer Identify, by name or number, all of the following 3 choices that would trigger stream rejuvenation: 1) Stream’s base level falls; 2) Acidic buildup passes the set point; 3) When land rises beneath a stream.  

text[[115, 313, 230, 329]]
ANSWER: 1, 3  

sub_title[[460, 380, 536, 397]]
## TOSS-UP  

text[[115, 414, 790, 449]]
8) Chemistry – Multiple Choice Which of the following describes a reaction that is NEVER endergonic?  

text[[115, 466, 583, 533]]
W) Negative enthalpy and negative entropy at high temperatures  X) Positive enthalpy and positive entropy at low temperatures  Y) Negative enthalpy and positive entropy at high temperatures  Z) Positive enthalpy and negative entropy at low temperatures  

text[[115, 550, 855, 567]]
ANSWER: Y) NEGATIVE ENTHALPY AND POSITIVE ENTROPY AT HIGH TEMPERATURES  

sub_title[[465, 602, 530, 619]]
## BONUS  

text[[115, 636, 880, 670]]
8) Chemistry – Short Answer What is the minimum amount of carbons in a ring required to have both E and Z isomers of a cycloalkene?  

text[[115, 688, 212, 704]]
ANSWER: 8sub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[113, 141, 881, 178]]
9) Biology - Short Answer Identify, by name or number, all of the following 4 cellular components that are present in eukaryotic cells: 1) Flagella; 2) 30s ribosomes; 3) 50s ribosomes; 4) Peptidoglycan.  

text[[115, 193, 266, 210]]
ANSWER: 1 ONLY  

sub_title[[464, 228, 530, 245]]
## BONUS  

text[[113, 262, 840, 297]]
9) Biology - Multiple Choice Which of the following mechanisms does not allow viruses to have compact genomes?  

text[[113, 312, 870, 347]]
W) Viruses can use the host's translational machinery, which means viruses do not have to store genetic material for translational machinery.  

text[[113, 347, 872, 381]]
X) Viruses can use the host's transcriptional machinery, which means viruses do not have to store genetic material for transcription.  

text[[115, 381, 570, 398]]
Y) Virus capsids can contain protein rather than DNA or RNA.  

text[[113, 399, 856, 432]]
Z) Viruses can use the host's alternative splicing mechanisms to create different polypeptides from the same transcript.  

text[[113, 447, 812, 466]]
ANSWER: Y) VIRUS CAPSIDS CAN CONTAIN PROTEIN RATHER THAN DNA OR RNA  

sub_title[[459, 517, 536, 535]]
## TOSS-UP  

text[[115, 551, 768, 587]]
10) Math - Short Answer What is the greatest prime factor for the following expression: (21!)*(20!)*(19!)/(20!)*(19!)*(18!)  

text[[115, 602, 221, 618]]
ANSWER: 19  

sub_title[[464, 637, 530, 654]]
## BONUS  

text[[115, 670, 872, 722]]
10) Math - Short Answer Find the smallest 3 digit number such that, when divided by 6 it gives you a remainder of 3, and when divided by 9 gives you a remainder of 6, and when divided by 11, gives you a remainder of 8.  

text[[115, 738, 230, 755]]
ANSWER: 195sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 124, 870, 159]]
11) Physics – Short Answer The sign of a charge carried in a doped semiconductor can be deduced by measuring what effect?  

text[[115, 175, 582, 194]]
ANSWER: HALL EFFECT (ACCEPT: HALL COEFFICIENT)  

sub_title[[465, 210, 530, 227]]
## BONUS  

text[[115, 243, 870, 280]]
11) Physics – Short Answer Two blocks with masses \(2\mathrm{kg}\) and \(1\mathrm{kg}\) lie horizontally together on a frictionless table. A force of \(3\mathrm{N}\) is applied, what is the normal force in newtons between the two blocks?  

text[[115, 295, 210, 312]]
ANSWER: 1  

sub_title[[460, 346, 537, 364]]
## TOSS-UP  

text[[115, 380, 857, 415]]
12) Chemistry – Short Answer How many electrons are in the antibonding orbitals for the molecule He2.  

text[[115, 431, 212, 448]]
ANSWER: 2  

sub_title[[465, 465, 530, 483]]
## BONUS  

text[[115, 499, 870, 534]]
12) Chemistry – Short Answer What class of compounds are characterized as cyclic with a pi electron system that has delocalized electrons equally the expression 4n.  

text[[115, 550, 342, 567]]
ANSWER: ANTIAROMATICsub_title[[455, 91, 540, 108]]
## TOSS-UP  

text[[115, 125, 870, 160]]
13) Biology – Multiple Choice When prions cause the misfolding of other proteins by changing alpha helices to beta pleated sheets, what molecular property is most drastically changed during this?  

text[[115, 177, 258, 245]]
W) Solubility 
X) pH 
Y) Annealing point 
Z) Conductivity  

text[[115, 262, 336, 279]]
ANSWER: W) SOLUBILITY  

sub_title[[465, 296, 530, 313]]
## BONUS  

text[[115, 330, 822, 364]]
13) Biology – Short Answer What ribosomal binding site in bacterial mRNA is located 8 bases upstream from the start codon and has the 6 base sequence AGGAGG.  

text[[115, 380, 461, 397]]
ANSWER: SHINE-DALGARNO SEQUENCE  

sub_title[[460, 432, 536, 449]]
## TOSS-UP  

text[[115, 466, 875, 501]]
14) Chemistry – Multiple Choice Boron trichloride is a useful reactant for forming adducts with amines in some organic syntheses. In these reactions, boron trichloride most likely acts as a:  

text[[115, 518, 252, 586]]
W) Nucleophile 
X) Neutron source 
Y) Proton source 
Z) Electrophile  

text[[115, 602, 335, 618]]
ANSWER: ELECTROPHILE  

sub_title[[465, 636, 530, 653]]
## BONUS  

text[[115, 670, 820, 705]]
14) Chemistry – Short Answer What quantity is plotted against time in a reaction with rate law \(-d[A] / dt = k[A]^4\) in order to have a linear relationship?  

text[[115, 721, 263, 738]]
ANSWER: \(1 / [A]^3\)sub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[115, 125, 864, 177]]
15) Math – Short Answer In a ranch with 56 people that are either cowboys or US Marines, find how many US Marines there would be, if the odds of randomly selecting 2 US Marines with replacement is 1/4th.  

text[[115, 194, 221, 210]]
ANSWER: 28  

sub_title[[465, 228, 530, 245]]
## BONUS  

text[[115, 262, 821, 297]]
15) Math – Short Answer How many total rectangles are made from a larger rectangle having 4 horizontal lines, and 3 vertical lines evenly spaced through it?  

text[[115, 313, 231, 329]]
ANSWER: 150  

sub_title[[459, 380, 536, 397]]
## TOSS-UP  

text[[115, 414, 870, 450]]
16) Physics – Multiple Choice Which of the following is the best type of laser to do spectroscopy over the range of visible wavelengths?  

text[[115, 467, 312, 533]]
W) Dye laser 
X) Hene laser 
Y) Excimer laser 
Z) Neodymium-YAG laser  

text[[115, 550, 300, 567]]
ANSWER: W) Dye laser  

sub_title[[465, 586, 530, 602]]
## BONUS  

text[[115, 619, 870, 671]]
16) Physics – Multiple Choice In the hydrogen spectrum, what is the ratio of the wavelengths for Lyman- a radiation, to Balmer- a radiation, where the respective jumps for each radiation are \(n = 2\) to \(n = 1\) , and \(n = 3\) to \(n = 2\) ?  

text[[115, 688, 183, 755]]
W) 5/48 
X) 5/27 
Y) 1/3 
Z) 27/5  

text[[115, 772, 258, 789]]
ANSWER: X) 5/27sub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[115, 125, 860, 159]]
17) Chemistry – Short Answer What approximation in chemical kinetics states that the intermediates and reactants in a multi-step reaction exist in a dynamic namesake state?  

text[[115, 176, 515, 194]]
ANSWER: PRE-EQUILIBRIUM APPROXIMATION  

sub_title[[458, 211, 523, 227]]
## BONUS  

text[[115, 244, 866, 280]]
17) Chemistry – Multiple Choice Which of the following reagents would be most appropriate in the formation of alkyl bromides from secondary alcohols through an Sn2 mechanism?  

text[[115, 296, 194, 364]]
W) LiBr 
X) MgBr2 
Y) Br2 
Z) PBr3  

text[[115, 380, 261, 398]]
ANSWER: Z) PBr3  

sub_title[[451, 449, 530, 465]]
## TOSS-UP  

text[[115, 482, 856, 517]]
18) Biology – Short Answer What cellular organelle is primarily responsible for the formation of the hormone: progesterone?  

text[[115, 533, 520, 551]]
ANSWER: SMOOTH ENDOPLASMIC RETICULUM  

sub_title[[458, 568, 523, 585]]
## BONUS  

text[[115, 602, 875, 654]]
18) Biology – Short Answer ACGH was performed on the genome of a young child with unusual phenotypic features. Which of the following findings would be most consistent with a translocation event in one of the parental gametes during development?  

text[[115, 670, 473, 739]]
W) Partial trisomy of chromosome 18 
X) A point mutation of chromosome 21 
Y) Inversion on the small arm of chromosome 13 
Z) Inversion on the long arm of chromosome 13  

text[[115, 755, 575, 773]]
ANSWER: W) PARTIAL TRISOMY OF CHROMOSOME 18sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 124, 870, 194]]
19) Earth and Space - Short Answer Identify, by name or number, all of the following 3 statements that are true regarding aquifer flow: 1) If there is no pressure gradient over a distance, no flow occurs; 2) The greater the pressure gradient, the greater the discharge rate; 3) If there is a pressure gradient, flow will occur from high pressure towards low pressure  

text[[115, 210, 370, 227]]
ANSWER: 1,2,3 (ACCEPT: ALL)  

sub_title[[465, 244, 530, 261]]
## BONUS  

text[[115, 278, 832, 314]]
19) Earth and Space - Short Answer What empirical relationship is described between the stellar velocity dispersion of a galaxy bulge, and the mass of a superblack hole in the center of the galaxy.  

text[[115, 329, 378, 347]]
ANSWER: M- SIGMA RELATION  

sub_title[[459, 397, 537, 414]]
## TOSS-UP  

text[[113, 431, 881, 468]]
20) Math - Short Answer Order the following 3 numbers in order from least to greatest: 1) e^pi; 2) sqrt(2)^sqrt(2); 3) pi^sqrt(3).  

text[[115, 483, 238, 500]]
ANSWER: 2,3,1  

sub_title[[465, 517, 530, 534]]
## BONUS  

text[[113, 550, 708, 568]]
20) Math - Short Answer Find the indefinite integral of the function: \(\ln (x^2) dx\)  

text[[115, 585, 283, 602]]
ANSWER: \(2x(\ln (x) - 1)\)sub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[113, 125, 883, 160]]
21) Biology - Short Answer Determine, by name or number, the ploidy for all of the following 3 plant structures: 1) Tube Cell; 2) Endosperm nucleus; 3) Meristematic cell.  

text[[115, 177, 512, 195]]
ANSWER: 1) HAPLOID, 2) TRIPLOID, 3) DIPLOID  

sub_title[[465, 211, 530, 228]]
## BONUS  

text[[115, 245, 866, 297]]
21) Biology - Short Answer Identify, by name or number, all of the following 3 choices where an average human adult would have cartilage: 1) Sutures in the skull; 2) Walls of the Trachea; 3) Walls of the larynx.  

text[[115, 313, 230, 330]]
ANSWER: 2, 3  

sub_title[[459, 380, 536, 397]]
## TOSS-UP  

text[[115, 414, 883, 450]]
22) Chemistry - Short Answer Identify, by name or number, all of the following 3 solvents that are both polar and protic: 1) H2O; 2) Et2O; 3) EtSH.  

text[[115, 466, 230, 483]]
ANSWER: 1, 3  

sub_title[[465, 500, 530, 517]]
## BONUS  

text[[115, 534, 850, 569]]
22) Chemistry - Short Answer Identify, by name or number, all of the following 3 compounds that could be cleaved by ozone in an ozonolysis reaction: 1) Alkene; 3) Alkene; 3) Azo.  

text[[115, 585, 374, 602]]
ANSWER: 1,2,3 (ACCEPT: ALL)sub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[113, 125, 881, 160]]
23) Math – Short Answer What is the radius of a circle inscribed in an isosceles triangle that has an area of 60 and legs of length 13 and 10.  

text[[115, 177, 235, 193]]
ANSWER: 10/3  

sub_title[[465, 212, 530, 229]]
## BONUS  

text[[113, 245, 872, 280]]
23) Math – Short Answer How many integer solutions are there for the equation: abc-2=a+b+c, where a,b, and c are all positive integers.  

text[[115, 297, 211, 313]]
ANSWER: 3