text[[222, 149, 772, 168]]
Buzzer test + Ice breaker question: What is your favorite amino acid?  

sub_title[[455, 189, 540, 207]]
## TOSS-UP  

text[[115, 225, 875, 262]]
1) Physics – Short Answer By name or number, identify all of the following 4 choices that are considered quasiparticles: 1) Phonon; 2) Selectron; 3) Exciton 4) Dilaton.  

text[[115, 280, 269, 298]]
ANSWER: 1 and 3  

sub_title[[462, 317, 533, 335]]
## BONUS  

text[[115, 352, 881, 406]]
1) Physics – Short Answer How large of a torque to the nearest tenth in newton-meters is needed to stop a hoop with a radius of 30 centimeters and a mass of 8kg with an initial speed of 8 rad/s in 5 seconds.  

text[[115, 425, 270, 443]]
ANSWER: 1.2 Nm  

sub_title[[455, 500, 540, 518]]
## TOSS-UP  

text[[115, 536, 858, 590]]
2) Earth and Space – Multiple Choice Which of the following rocks is a grey-black extrusive igneous rock that is extremely prevalent in Iceland and Hawaii and forms when magma or lava rapidly cools?  

text[[115, 608, 210, 676]]
W) Gabbro 
X) Andesite 
Y) Pumice 
Z) Basalt  

text[[115, 693, 302, 711]]
ANSWER: Z) BASALT  

sub_title[[462, 711, 533, 728]]
## BONUS  

text[[115, 746, 868, 782]]
2) Earth and Space – Short Answer What list of 110 astronomical objects, including nebulae, star clusters, and galaxies, were compiled into a list by its namesake French astronomer.  

text[[115, 800, 381, 817]]
ANSWER: MESSIER OBJECTSsub_title[[455, 90, 540, 108]]
## TOSS-UP  

text[[115, 125, 844, 162]]
3) Chemistry – Short Answer Rank the following three acids in order of increasing pKa: 1) Butanoic Acid 2) Chloroacetic acid 3) Iodoacetic acid  

text[[115, 181, 258, 199]]
ANSWER: 2,3,1  

sub_title[[462, 201, 533, 219]]
## BONUS  

text[[115, 235, 875, 309]]
3) Chemistry – Short Answer The reaction \(\mathrm{Zn_{(s)} + Cu^{2 + }_{(aq)}\rightarrow Zn^{2 + }_{(aq)} + Cu_{(s)}}\) has a standard cell potential of 1.1 V. Identify all of the following 3 changes that would increase the cell potential: 1) Increasing the concentration of \(\mathrm{Zn2 + }\) ; 2) Increasing the mass of the solid zinc electrode; 3) Increasing the mass of the solid copper electrode.  

text[[115, 327, 265, 345]]
ANSWER: NONE  

sub_title[[455, 400, 540, 418]]
## TOSS-UP  

text[[115, 435, 860, 473]]
4) Biology – Short Answer What two granulocytes produce histamine in response to foreign pathogens as an inflammatory response?  

text[[115, 491, 489, 510]]
ANSWER: MAST CELLS AND BASOPHILS  

sub_title[[462, 528, 533, 546]]
## BONUS  

text[[115, 565, 872, 603]]
4) Biology – Short Answer What group of enzymes is responsible for phosphorylating glucose to form glucose 6-phosphate during the investment stage of glycolysis?  

text[[115, 621, 348, 640]]
ANSWER: HEXOKINASESsub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[113, 125, 880, 161]]
5) Math – Short Answer A fair six-sided die is rolled six times. What is the probability that the product of the six rolls is odd?  

text[[115, 181, 423, 199]]
ANSWER: 1/64 (ACCEPT: 0.015625)  

sub_title[[463, 219, 533, 237]]
## BONUS  

text[[115, 257, 864, 330]]
5) Math – Short Answer Identify all of the following three series that converge: 1) The sum from n=1 to infinity of the fraction with numerator 1 and denominator n 2) The sum from n = 1 to infinity of the fraction with numerator 1 and denominator n + 3n 3) The sum of n = 1 to infinity of the fraction with numerator 1 and denominator n! (factorial)  

text[[115, 349, 266, 367]]
ANSWER: 2 and 3  

sub_title[[456, 422, 540, 440]]
## TOSS-UP  

text[[115, 459, 875, 496]]
6) Physics – Short Answer The potential energy of a ball varies according to the equation: \(5t^2\) + 3t. In Newtons, what is the force of the ball at \(t = 5\) ?  

text[[115, 515, 256, 533]]
ANSWER: - 53 N  

sub_title[[463, 554, 533, 572]]
## BONUS  

text[[115, 591, 882, 664]]
6) Physics – Short Answer A particle with mass 10 micrograms and charge of 10 micro coulombs is accelerated to a velocity of \(3*10^6\) m/s. It then enters into a uniform magnetic field of 600 microteslas at an angle of 90 degrees to the field. Expressing your answer in meters and in scientific notation, what is the radius of the path the electron follows?  

text[[115, 684, 285, 701]]
ANSWER: \(5*10^6\) 9msub_title[[455, 90, 540, 108]]
## TOSS-UP  

text[[115, 125, 872, 162]]
7) Earth and Space – Short Answer What is the name for the periodic climate event in which the eastern pacific ocean is warmed, typically occurring in late December?  

text[[115, 179, 289, 197]]
ANSWER: EL NINO  

sub_title[[462, 215, 533, 233]]
## BONUS  

text[[115, 251, 882, 288]]
7) Earth and Space – Short Answer What scientist names the cycles of the variations in earth's climate?  

text[[115, 305, 333, 323]]
ANSWER: MILANKOVIC  

sub_title[[455, 377, 540, 395]]
## TOSS-UP  

text[[115, 412, 880, 450]]
8) Chemistry – Multiple Choice In the creation of an addition polymer, what is the middle step in which no new free radicals are being produced?  

text[[115, 467, 258, 540]]
W) Propagation 
X) Determination 
Y) Perpetuation 
Z) Declination  

text[[115, 558, 355, 576]]
ANSWER: PROPAGATION  

sub_title[[462, 607, 533, 625]]
## BONUS  

text[[115, 643, 872, 680]]
8) Chemistry – Multiple Choice Which of the following molecules would be expected to have a proton NMR peak furthest downfield?  

text[[115, 697, 198, 770]]
W) \(\mathrm{CH}_3\mathrm{F}\) X) \(\mathrm{CH}_3\mathrm{Br}\) Y) \(\mathrm{CHF}_3\) Z) \(\mathrm{CHBr}_3\)  

text[[115, 787, 280, 805]]
ANSWER: Y) \(\mathrm{CHF}_3\)sub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[113, 125, 872, 163]]
9) Biology – Short Answer Identify by name or number all of the following 4 choices that are stages in a fungi sexual reproduction: 1) Plasmagamy; 2) Karyogamy; 3) Apomixis; 4) Meiosis.  

text[[115, 182, 260, 200]]
ANSWER: 1, 2, 4  

sub_title[[462, 219, 533, 237]]
## BONUS  

text[[113, 257, 848, 294]]
9) Biology – Multiple Choice Which of the following reasons is the best explanation as to why the Murchison Meteorite's nucleobases did not come from the earth.  

text[[113, 312, 861, 388]]
W) Uracil had an abnormally high percentage of Carbon-13 in the meteorite 
X) Hypoxanthine samples present in the meteorite were unable to effectively wobble base pair 
Y) The nucleobase sample in the meteorite was found to be racemic 
Z) There was an abundance of pyrimidines compared to terrestrial samples  

text[[113, 406, 864, 443]]
ANSWER: W) URACIL HAD AN ABNORMALLY HIGH PERCENTAGE OF CARBON 13 IN THE METEORITE.  

sub_title[[456, 500, 540, 519]]
## TOSS-UP  

text[[115, 537, 812, 557]]
10) Math – Short Answer What is the sum of the first 7 perfect squares greater than 0?  

text[[115, 576, 241, 594]]
ANSWER: 140  

sub_title[[462, 614, 533, 632]]
## BONUS  

text[[115, 651, 864, 689]]
10) Math – Short Answer Giving your answer as a common fraction, what is the largest real value of x such that the floor of x divided by x = 9/10?  

text[[115, 707, 246, 725]]
ANSWER: 80/9sub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[115, 125, 877, 216]]
11) Physics – Short Answer Identify by name or number all of the following three statements that are NOT true regarding the movement of sound waves: 1) Sound waves move more quickly through solids than through gases; 2) Sound waves move more slowly through a material with a high bulk modulus than one with a low bulk modulus; 3) Sound waves cannot propagate through a vacuum.  

text[[116, 235, 279, 252]]
ANSWER: 2 ONLY  

sub_title[[462, 274, 533, 292]]
## BONUS  

text[[115, 310, 878, 383]]
11) Physics – Short Answer Assume you have 2 identical spheres with a charge of q at a distance d away from each other. If you then take a neutral sphere and touch it with the first sphere, and then touch the 2nd sphere right after. What will the final charge on the 2nd sphere be in terms of q?  

text[[115, 402, 250, 420]]
ANSWER: 3/4Q  

sub_title[[456, 477, 540, 494]]
## TOSS-UP  

text[[115, 496, 847, 532]]
12) Earth and Space – Short Answer What element’s oxide is produced through the Bayer Process?  

text[[115, 552, 321, 570]]
ANSWER: ALUMINUM  

sub_title[[462, 590, 533, 608]]
## BONUS  

text[[115, 626, 864, 664]]
12) Earth and Space – Short Answer Charon was first discovered by New Horizons in 2015, what celestial object is Charon the moon for?  

text[[115, 683, 275, 701]]
ANSWER: PLUTOsub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 125, 870, 162]]
13) Biology – Short Answer  Tetracycline and erythromycin bind to what cellular structure to block protein synthesis in prokaryotes?  

text[[115, 181, 323, 199]]
ANSWER: RIBOSOMES  

sub_title[[462, 220, 533, 238]]
## BONUS  

text[[115, 257, 867, 312]]
13) Biology – Short Answer  Identify all of the following 3 statements that are true regarding neurulation: 1) The neural tube differentiates from endoderm; 2) The neural tube becomes the peripheral nervous system; 3) Neural crest cells migrate from their original site.  

text[[115, 330, 260, 349]]
ANSWER: 3 only  

sub_title[[456, 406, 540, 424]]
## TOSS-UP  

text[[115, 443, 864, 481]]
14) Chemistry – Multiple Choice  In a hydroboration-oxidation reaction, what two functional groups are always present in the reactant and product, respectively?  

text[[114, 499, 364, 575]]
W) Alkene and Alcohol 
X) Aldehyde and Borane 
Y) Borane and Carboxylic acid 
Z) Alkyne and Ester  

text[[114, 593, 464, 611]]
ANSWER: W) ALKENE AND ALCOHOL  

sub_title[[462, 632, 533, 650]]
## BONUS  

text[[115, 669, 870, 760]]
14) Chemistry – Multiple Choice  Identify by name or number all of the following 3 choices regarding x-ray crystallography that are true. 1) More electron dense atoms are easier to observe through x-ray crystallography; 2) X-ray crystallography measures the angles and intensities of the diffracted beams; 3) Absolute stereochemical species can be identified using x-ray crystallography  

text[[115, 779, 260, 797]]
ANSWER: 1, 2, 3sub_title[[455, 90, 541, 108]]
## TOSS-UP  

text[[115, 142, 858, 180]]
15) Math - Short Answer The function \(\mathrm{f(x) = sqrt(2x + 1)}\) is continuous and differentiable in the interval (4, 12). What real number within this interval satisfies the mean value theorem?  

text[[115, 199, 308, 217]]
ANSWER: 7.5 OR 15/2  

sub_title[[462, 238, 533, 256]]
## BONUS  

text[[115, 275, 870, 312]]
15) Math - Short Answer The equation \(\mathrm{y = sqrt(3x - 2)}\) is parametrized by \((\mathrm{x},\mathrm{y}) = (\mathrm{f(t)},3\mathrm{t - 8})\) Find the function \(\mathrm{f(t)}\)  

text[[115, 331, 295, 350]]
ANSWER: \(3\mathrm{t}^{2} - 16\mathrm{t} + 22\)  

sub_title[[455, 387, 541, 405]]
## TOSS-UP  

text[[115, 424, 879, 480]]
16) Physics - Multiple Choice Assume you have a cube with side lengths of \(\mathrm{x}\) with an electric field that is entering the bottom of the cube and exits the top of the cube at a normal angle. What is the net electric flux of the cube in VM?  

text[[115, 499, 258, 517]]
ANSWER: 0 VM  

sub_title[[462, 537, 533, 555]]
## BONUS  

text[[115, 574, 844, 611]]
16) Physics - Short Answer Which of the following is true regarding a lens in which both surfaces are concave?  

text[[115, 630, 373, 705]]
W) Its focal length is positive 
X) It cannot form real images 
Y) It cannot form virtual images 
Z) It can magnify objects  

text[[115, 725, 538, 744]]
ANSWER: X) IT CANNOT FORM REAL IMAGESsub_title[[455, 91, 540, 108]]
## TOSS-UP  

text[[115, 125, 870, 163]]
17) Chemistry – Multiple Choice What kind of organic projection is used when representing the tacticity of a polymer with characteristic zigzag bonds representing sp3 hybridized carbons?  

text[[115, 182, 215, 256]]
W) Fischer  X) Newman  Y) Haworth  Z) Natta  

text[[115, 276, 300, 295]]
ANSWER: Z) NATTA  

sub_title[[455, 314, 525, 332]]
## BONUS  

text[[115, 351, 865, 388]]
17) Chemistry – Multiple Choice Which of the following molecules would form the most reactive enolate intermediate?  

text[[115, 407, 325, 481]]
W) 4-Methyl-2-pentanone  X) 4-Amino-2-pentanone  Y) 2-Pentanone  Z) 3-Oxopentalan  

text[[115, 499, 396, 517]]
ANSWER: Z) 3-OXOPENTANAL  

sub_title[[448, 556, 533, 574]]
## TOSS-UP  

text[[115, 592, 835, 629]]
18) Biology – Multiple Choice What complex forms between homologous chromosomes during meiosis?  

text[[115, 649, 255, 724]]
W) Proteasome  X) Connexons  Y) Pyrrolysine  Z) Synaptonemal  

text[[115, 742, 393, 760]]
ANSWER: Z) SYNAPTONEMAL  

sub_title[[455, 781, 525, 799]]
## BONUS  

text[[115, 818, 866, 874]]
18) Biology – Short Answer Polydactyly is an autosomal dominant trait. In a population at Hardy-Weinberg equilibrium, the gene for polydactyly makes up \(20\%\) of the gene pool. What percentage of the population is heterozygous for the polydactyl gene?  

text[[115, 892, 247, 910]]
ANSWER: \(32\%\)sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 125, 880, 163]]
19) Earth and Space – Short Answer A Hertzsprung Russel (HR) diagram plots what quantity on the x and y axis respectively?  

text[[115, 181, 528, 200]]
ANSWER: TEMPERATURE AND LUMINOSITY  

sub_title[[462, 219, 533, 237]]
## BONUS  

text[[115, 257, 868, 312]]
19) Earth and Space – Short Answer What quantity is shown on the vertical axis of Bowen's Reaction Series, where objects towards the top of Bowen's Reaction Series has a high value for this, and those at the bottom have a low value for this?  

text[[115, 330, 540, 349]]
ANSWER: CRYSTALLIZATION TEMPERATURE  

sub_title[[456, 388, 540, 406]]
## TOSS-UP  

text[[112, 424, 835, 444]]
20) Math – Short Answer How many more edges does an icosahedron have than a cube?  

text[[115, 463, 231, 481]]
ANSWER: 18  

sub_title[[462, 500, 533, 519]]
## BONUS  

text[[115, 538, 880, 592]]
20) Math – Short Answer A right circular cone has base of radius 1 and height 3. A cube is inscribed in the cone so that one face of the cube is contained in the base of the cone. What is the side-length of the cube?  

text[[115, 610, 287, 652]]
\(\frac{9\sqrt{2} - 6}{7}\) ANSWER: 7