text[[197, 149, 799, 167]]
Buzzer test + Ice breaker question: Who's your least favorite person on your team?  

sub_title[[459, 185, 536, 203]]
## TOSS-UP  

text[[115, 220, 839, 257]]
1) Physics – Short Answer What type of scattering is characterized by particles similar to or larger than the wavelength of the incident light?  

text[[115, 275, 375, 294]]
ANSWER: MIE SCATTERING  

sub_title[[464, 311, 530, 329]]
## BONUS  

text[[115, 345, 875, 383]]
1) Physics – Short Answer By what factor does the volume flow-rate of a cylindrical pipe change by, if the radius of the pipe is multiplied by 2, given that no other factors change?  

text[[115, 401, 231, 419]]
ANSWER: 16  

sub_title[[459, 471, 536, 489]]
## TOSS-UP  

text[[115, 506, 865, 544]]
2) Earth and Space – Multiple Choice There is an unusually high concentration of which of the following elements in the KT Boundary.  

text[[115, 560, 240, 637]]
W) Rhenium 
X) Iridium 
Y) Strontium 
Z) Germanium  

text[[115, 660, 315, 679]]
ANSWER: X) IRIDIUM  

sub_title[[464, 699, 530, 716]]
## BONUS  

text[[115, 733, 880, 787]]
2) Earth and Space – Short Answer Scientists have discovered microscopic fissures in ancient crystals. These fissures, caused by decaying atoms, can be used to date the crystal and are known as what?  

text[[115, 806, 367, 825]]
ANSWER: FISSION TRACKSsub_title[[455, 91, 540, 108]]
## TOSS-UP  

text[[113, 125, 867, 160]]
3) Chemistry – Multiple Choice What term describes an alkyl halide that has 2 halogens bonded to the same carbon atom?  

text[[114, 177, 208, 245]]
W) Ortho 
X) Terminal 
Y) Vicinal 
Z) Geminal  

text[[115, 262, 306, 279]]
ANSWER: Z) GEMINAL  

sub_title[[465, 279, 530, 296]]
## BONUS  

text[[115, 312, 835, 348]]
3) Chemistry – Short Answer Rank the following 4 orbitals from least to greatest in terms of total nodes: 1) 5f; 2) 4f; 3) 7p; 4) 6d.  

text[[115, 363, 266, 381]]
ANSWER: 2, 1, 4, 3  

sub_title[[459, 414, 537, 431]]
## TOSS-UP  

text[[115, 448, 833, 484]]
4) Biology – Short Answer Identify all of the following 4 mechanisms that humans go through in response to low body temperature: 1) Vasodilation; 2) Vasoconstriction; 3) Shivering; 4) Sweating  

text[[115, 499, 230, 516]]
ANSWER: 2, 3  

sub_title[[465, 534, 530, 551]]
## BONUS  

text[[115, 568, 836, 603]]
4) Biology – Short Answer Rank the following 3 optical structures in order of increasing cone cell density: 1) Fovea; 2) Peripheral Retina; 3) Optic Disk.  

text[[115, 619, 246, 636]]
ANSWER: 3, 2, 1sub_title[[455, 91, 540, 108]]
## TOSS-UP  

text[[113, 125, 842, 161]]
5) Math – Multiple Choice The radical axis of two circles is the locus of points that have the same:  

text[[115, 183, 290, 257]]
W) Length  X) Power  Y) Geometric Inverse  Z) Length squared  

text[[115, 274, 290, 291]]
ANSWER: X) POWER  

sub_title[[465, 308, 530, 325]]
## BONUS  

text[[115, 342, 811, 379]]
5) Math – Short Answer What is the sum of values n, such that n is between 0 and 2020 inclusive and n over 2020 simplifies to 1/m for some positive integer m?  

text[[115, 396, 240, 413]]
ANSWER: 4284  

sub_title[[460, 465, 537, 482]]
## TOSS-UP  

text[[115, 499, 864, 535]]
6) Physics – Short Answer Assuming g to be ten meters per second squared, what is the angular frequency in radians per second of a pendulum with a length of ten meters?  

text[[115, 554, 251, 571]]
ANSWER: ONE  

sub_title[[465, 590, 530, 607]]
## BONUS  

text[[115, 624, 877, 678]]
6) Physics – Short Answer A cyclotron has a radius of 5 meters, and is made for an electron. If a new cyclotron is made for an electron moving with twice the speed, what must be the radius in meters of this cyclotron, if the magnetic field is kept constant?  

text[[115, 696, 235, 712]]
ANSWER: 10msub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[113, 125, 875, 163]]
7) Earth and Space – Short Answer The Van Allen Radiation Belts are created by the interaction of solar wind and which of the following:  

text[[115, 180, 365, 258]]
W) Magnetic Solar Phenomena 
X) Chromosphere 
Y) Aurorae 
Z) Magnetosphere  

text[[115, 280, 356, 300]]
ANSWER: Z) Magnetosphere  

sub_title[[465, 317, 530, 335]]
## BONUS  

text[[115, 351, 850, 389]]
7) Earth and Space – Short Answer Gas Hydrates are an unconventional form of hydrocarbon deposits. They are made up of water ice enclosing molecules of what hydrocarbon?  

text[[115, 403, 416, 422]]
ANSWER: METHANE (ACCEPT: \(\mathrm{CH_4}\)  

sub_title[[459, 473, 536, 490]]
## TOSS-UP  

text[[115, 506, 861, 543]]
8) Chemistry – Short Answer Identify all of the following 3 catalysts that would result in a cis alkene after the hydrogenation of an alkyne: 1) Lindlar’s Catalyst; 2) P-2 Catalyst; 3) Platinum Catalyst.  

text[[115, 558, 274, 575]]
ANSWER: 1 AND 2  

sub_title[[465, 609, 530, 626]]
## BONUS  

text[[115, 643, 850, 678]]
8) Chemistry – Multiple Choice Which of the following statements regarding argentometry is NOT true:  

text[[115, 695, 675, 761]]
W) It is a titration involving the nitrate ion. 
X) It is used to calculate the standard reduction potential of a silver electrode. 
Y) The Mohr method uses potassium chromate as an indicator. 
Z) Volhard’s method uses back titration to titrate.  

text[[115, 778, 852, 813]]
ANSWER: X) IT IS USED TO CALCULATE THE STANDARD REDUCTION POTENTIAL OF A SILVER ELECTRODE.sub_title[[455, 91, 540, 108]]
## TOSS-UP  

text[[113, 125, 844, 160]]
9) Biology – Short Answer In the development of a protostome, what opening becomes the mouth, while in the development of a deuterostome, the same opening becomes the anus.  

text[[115, 176, 319, 193]]
ANSWER: BLASTOPORE  

sub_title[[465, 211, 530, 228]]
## BONUS  

text[[115, 244, 856, 280]]
9) Biology – Short Answer Identify all of the following 4 plant divisions in which the sporophyte is less well developed than the gametophyte: 1) Mosses 2) Ferns 3) Liverworts 4) Hornworts  

text[[115, 295, 248, 313]]
ANSWER: 1, 3, 4  

sub_title[[459, 364, 536, 381]]
## TOSS-UP  

text[[115, 397, 872, 434]]
10) Math – Short Answer How many non-empty subsets are there for the set of positive integers less than 10?  

text[[115, 451, 229, 468]]
ANSWER: 511  

sub_title[[465, 486, 530, 503]]
## BONUS  

text[[115, 520, 833, 556]]
10) Math – Multiple Choice How many ways are there to triangulate a convex seven-sided polygon?  

text[[115, 574, 166, 648]]
W) 14 X) 28 Y) 42 Z) 56  

text[[115, 667, 245, 684]]
ANSWER: Y) 42sub_title[[455, 91, 540, 108]]
## TOSS-UP  

text[[115, 125, 848, 180]]
11) Physics – Short Answer What is the magnetic flux in webers emanating from a circular surface with radius one meter, and magnetic field of one tesla, if the magnetic field makes an angle of 60 degrees with the normal?  

text[[115, 198, 231, 214]]
ANSWER: pi/2  

sub_title[[465, 231, 530, 248]]
## BONUS  

text[[115, 265, 858, 320]]
11) Physics – Short Answer A beam of light enters a series of 4 polarizers, each rotated 45 degrees from the previous polarizer. What fraction of the initial intensity of light remains after leaving the 4th polarizer?  

text[[115, 355, 235, 371]]
ANSWER: 1/16  

sub_title[[459, 406, 536, 423]]
## TOSS-UP  

text[[115, 440, 865, 494]]
12) Earth and Space – Multiple Choice Conventional hydrocarbon reserves have been mined for oil, gas, etc since the 1800s. As those dry up, companies turn to unconventional hydrocarbons such as which of the following:  

text[[115, 512, 270, 589]]
W) Oil Trap 
X) Oil Seep 
Y) Oil Sands 
Z) Hydrofracturing  

text[[115, 612, 318, 630]]
ANSWER: Y) Oil Sands  

sub_title[[465, 650, 530, 667]]
## BONUS  

text[[115, 685, 879, 720]]
12) Earth and Space – Multiple Choice Which of the following is NOT a form of submarine mass movement:  

text[[115, 741, 330, 815]]
W) Turbidity Current 
X) Submarine Slump 
Y) Submarine Debris Flow 
Z) Submarine Groin  

text[[115, 833, 392, 850]]
ANSWER: Z) SUBMARINE GROINsub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[115, 125, 866, 143]]
13) Biology - Short Answer What prokaryotic factor is responsible for the initiation of transcription?  

text[[115, 159, 463, 177]]
ANSWER: SIGMA (ACCEPT: SPECIFICITY)  

sub_title[[468, 194, 530, 211]]
## BONUS  

text[[115, 228, 848, 280]]
13) Biology - Short Answer In a differential centrifugation experiment, multiple speeds are used to separate out cellular components. Order the following 3 cellular components in order of lowest to the highest speed required to separate it out: 1) Nuclei; 2) Ribosomes; 3) Lysosomes.  

text[[115, 296, 248, 312]]
ANSWER: 1, 3, 2  

sub_title[[459, 347, 536, 364]]
## TOSS-UP  

text[[115, 380, 839, 399]]
14) Chemistry - Short Answer How many electrons are in the pi system for a molecule of Ozone?  

text[[115, 415, 212, 430]]
ANSWER: 4  

sub_title[[465, 449, 530, 465]]
## BONUS  

text[[115, 483, 822, 517]]
14) Chemistry - Multiple Choice Which of the following statements is NOT true regarding the epoxidation of alkenes:  

text[[115, 535, 360, 551]]
W) The reaction can use a peroxy acid.  

text[[115, 552, 566, 568]]
X) It is an electrophilic addition of oxygen to the double bond.  

text[[115, 570, 488, 585]]
Y) A product can only be formed from a cis alkene.  

text[[115, 587, 421, 602]]
Z) The addition can happen on either face.  

text[[115, 619, 715, 636]]
ANSWER: Y) A PRODUCT CAN ONLY BE FORMED FROM A CIS ALKENE.sub_title[[455, 91, 540, 108]]
## TOSS-UP  

text[[115, 124, 866, 162]]
15) Math - Short Answer Find the determinant of a matrix with first row 1, 2, and second row, 3, 4.  

text[[115, 180, 218, 197]]
ANSWER: - 2  

sub_title[[465, 214, 530, 231]]
## BONUS  

text[[115, 247, 819, 267]]
15) Math - Short Answer Solve the following system of equations for A, B, C, D, and E.  

equation[[115, 266, 319, 360]]
\[2\mathrm{A} + \mathrm{B} + \mathrm{C} + \mathrm{D} + \mathrm{E} = 10\] \[\mathrm{A} + 2\mathrm{B} + \mathrm{C} + \mathrm{D} + \mathrm{E} = 11\] \[\mathrm{A} + \mathrm{B} + 2\mathrm{C} + \mathrm{D} + \mathrm{E} = 12\] \[\mathrm{A} + \mathrm{B} + \mathrm{C} + 2\mathrm{D} + \mathrm{E} = 13\] \[\mathrm{A} + \mathrm{B} + \mathrm{C} + \mathrm{D} + 2\mathrm{E} = 14\]  

text[[115, 379, 433, 398]]
ANSWER) \(\mathrm{A} = 0, \mathrm{B} = 1, \mathrm{C} = 2, \mathrm{D} = 3, \mathrm{E} = 4\)  

sub_title[[459, 450, 536, 467]]
## TOSS-UP  

text[[115, 484, 867, 539]]
16) Physics - Multiple Choice A cylindrical resistor has a resistance of 5 Ohms. A new resistor is made such that its length is double the original resistor, and its diameter is twice that of the original resistor. What is the resistance of the new resistor in ohms?  

text[[115, 558, 172, 633]]
W) 2.5 X) 5 Y) 10 Z) 20  

text[[115, 650, 253, 668]]
ANSWER: W) 2.5  

sub_title[[465, 685, 530, 701]]
## BONUS  

text[[115, 718, 872, 773]]
16) Physics - Short Answer A rocket moves at a speed 0.8c to the right and fires a bullet at 0.6c to the left. In terms of c, to the nearest tenth, what speed does an observer on earth measure the bullet to be traveling at in terms of c?  

text[[115, 793, 244, 810]]
ANSWER: 0.4csub_title[[455, 91, 540, 108]]
## TOSS-UP  

text[[115, 125, 866, 160]]
17) Chemistry – Short Answer In the crown ether 18-crown-6, how many carbon and hydrogen atoms are there respectively?  

text[[115, 176, 248, 193]]
ANSWER: 12, 24  

sub_title[[458, 211, 523, 228]]
## BONUS  

text[[115, 245, 796, 280]]
17) Chemistry – Multiple Choice Which of the following compounds is considered a meso compound?  

text[[115, 296, 377, 365]]
W) (2R,2S)-2,3- dibromobutane  X) (1R, 4R)-1,4- dinitrocyclohexane  Y) 2,4,6- trinitrotoluene  Z) (1R, 2S, 3S)-1,2,3- triethylheptane  

text[[115, 380, 479, 398]]
ANSWER: W) (2R,2S)-2,3- DIBROMOBUTANE  

sub_title[[451, 432, 530, 449]]
## TOSS-UP  

text[[115, 465, 799, 500]]
18) Biology – Multiple Choice What organic product is given after the nucleotide, adenine is deaminated?  

text[[115, 517, 255, 585]]
W) Inosine  X) Hypoxanthine  Y) Uracil  Z) Guanine  

text[[115, 601, 368, 619]]
ANSWER: X) HYPOXANTHINE  

sub_title[[458, 636, 523, 653]]
## BONUS  

text[[115, 670, 878, 722]]
18) Biology – Multiple Choice Dan was found after wandering a hot desert for several hours with no water. Which of the following solutions given intravenously would best return Dan’s intracellular volume toward normal?  

text[[115, 739, 277, 764]]
W) Hypertonic Saline  

text[[115, 765, 328, 810]]
X) Plasma  Y) Isotonic Saline  Z) Dextran in isotonic saline.  

text[[115, 825, 379, 842]]
ANSWER: Y) ISOTONIC SALINEsub_title[[455, 90, 540, 108]]
## TOSS-UP  

text[[115, 125, 852, 160]]
19) Earth and Space – Short Answer Metamorphic Rocks that appear banded are classified as what?  

text[[115, 179, 291, 196]]
ANSWER: FOLIATED  

sub_title[[465, 214, 530, 231]]
## BONUS  

text[[115, 248, 870, 284]]
19) Earth and Space – Multiple Choice Of the following, which technique uses stellar parallax as its primary measurement:  

text[[115, 304, 346, 378]]
W) Occultation X) Triangulation Y) Aperture synthesis Z) Entanglement Distillation  

text[[115, 396, 375, 413]]
ANSWER: X) TRIANGULATION  

sub_title[[460, 464, 536, 481]]
## TOSS-UP  

text[[113, 498, 881, 534]]
20) Math – Short Answer What is the definite integral from 0 to pi of the expression 1 plus cosine of x dx?  

text[[115, 553, 217, 570]]
ANSWER: pi  

sub_title[[465, 587, 530, 603]]
## BONUS  

text[[115, 620, 860, 656]]
20) Math – Short Answer A triangle has three altitudes of 5, 6 and 7. What is the radius of the circle inscribed in this triangle?  

text[[115, 676, 275, 694]]
ANSWER: 210/107sub_title[[455, 91, 540, 108]]
## TOSS-UP  

text[[113, 125, 852, 159]]
21) Biology – Multiple Choice Which of the following plant tissues is present in eudicots but not in monocots?  

text[[115, 177, 230, 250]]
W) Pith  X) Endodermis  Y) Cortex  Z) Epidermis  

text[[115, 272, 270, 288]]
ANSWER: W) PITH  

sub_title[[459, 308, 524, 324]]
## BONUS  

text[[115, 341, 830, 375]]
21) Biology – Short Answer What genetic disease is characterized by excess copper buildup in several essential organs, which causes jaundice in certain cases.  

text[[115, 392, 329, 409]]
ANSWER: Wilson's Disease  

sub_title[[459, 460, 537, 477]]
## TOSS-UP  

text[[115, 494, 812, 529]]
22) Chemistry – Short Answer Identify all of the following 3 materials that can be considered metastable: 1) Graphene; 2) Graphene oxide; 3) Diamond  

text[[115, 545, 268, 561]]
ANSWER: 2 AND 3  

sub_title[[465, 580, 530, 596]]
## BONUS  

text[[115, 613, 880, 648]]
22) Chemistry – Short Answer Order the following 3 molecules based on melting points: 1) S8; 2) C60; 3) C6H6.  

text[[115, 665, 248, 682]]
ANSWER: 3, 1, 2sub_title[[455, 90, 540, 108]]
## TOSS-UP  

text[[113, 125, 883, 162]]
23) Math – Multiple Choice For a continuous and differentiable function f of x, if f of 1 equals 10 and f of 9 equals 10, which of the following must exist on the open interval from 1 to 9?  

text[[114, 182, 393, 257]]
W) A local minimum or maximum  X) A point of inflection  Y) A vertical asymptote  Z) A horizontal asymptote  

text[[114, 276, 562, 294]]
ANSWER: W) A LOCAL MINIMUM OR MAXIMUM  

sub_title[[465, 311, 530, 328]]
## BONUS  

text[[113, 345, 828, 382]]
23) Math – Short Answer When the five-digit number AB0AB is divided by the two-digit number AB the result is A00B. What is the value of A+B?  

text[[115, 401, 220, 419]]
ANSWER: 2