sub_title[[455, 150, 540, 168]]
## TOSS-UP  

text[[114, 185, 866, 223]]
1) Physics – Multiple Choice What equation in physics is used to describe the magnetic field produced by a given current?  

text[[114, 242, 297, 316]]
W) Biot-Savart 
X) Ampere 
Y) Maxwell 
Z) Clausius-Clapeyron  

text[[115, 335, 371, 353]]
ANSWER: W) BIOT-SAVART  

sub_title[[462, 373, 533, 391]]
## BONUS  

text[[115, 408, 880, 462]]
1) Physics – Short Answer When a ball is thrown straight up at a speed v the maximum height the ball reaches is h1. When the ball is instead thrown straight upward at 4v the maximum height is h2. What is h2/h1?  

text[[115, 482, 230, 499]]
ANSWER: 16  

sub_title[[455, 556, 540, 574]]
## TOSS-UP  

text[[114, 592, 830, 629]]
2) Chemistry – Multiple Choice Which of the following statements regarding an atomic orbital is false?  

text[[115, 647, 517, 665]]
W) An atomic orbital is a three dimensional shape.  

text[[115, 666, 866, 720]]
X) The principal quantum number is the quantum number with the largest effect on orbital size. 
Y) A subshell consists of a collection of orbitals that have the same first two quantum numbers 
Z) The equation for total nodes of an atomic orbital is (n -L-1)  

text[[115, 736, 803, 755]]
ANSWER: Z) THE EQUATION FOR TOTAL NODES OF AN ORBITAL IS (N- L-1)  

sub_title[[462, 775, 533, 792]]
## BONUS  

text[[115, 810, 825, 847]]
2) Chemistry – Short Answer How many distinct forms of \(\mathrm{C}_3\mathrm{HCl}_5\) would not be able to display addition reactions?  

text[[115, 867, 220, 884]]
ANSWER: 1sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[113, 130, 877, 166]]
3) Biology – Short Answer What is the name given to the fluid inside of a plant cell's vacuole that primarily consists of water, amino acids, glucose, and more?  

text[[115, 185, 300, 203]]
ANSWER: CELL SAP  

sub_title[[462, 224, 533, 242]]
## BONUS  

text[[115, 260, 883, 296]]
3) Biology – Short Answer What illness caused by nondisjunction during meiosis causes some females to be born with only one X chromosome and loss of ovarian function?  

text[[115, 315, 730, 334]]
ANSWER: TURNER SYNDROME (ACCEPT: GONADAL DYSGENESIS)  

sub_title[[456, 387, 540, 405]]
## TOSS-UP  

text[[115, 423, 877, 478]]
4) Earth and Space – Short Answer Identify all of the following 3 statements that are true of S waves 1) S waves travel through either liquid or solids. 2) P waves travel 60% faster than S waves on average. 3) S waves are energetically favorable moving on the surface of the earth.  

text[[115, 497, 279, 515]]
ANSWER: 2 ONLY  

sub_title[[462, 535, 533, 553]]
## BONUS  

text[[115, 572, 863, 608]]
4) Earth and Space – Multiple Choice Which of the following distances is closest to that of the radius of the galaxy Andromeda?  

text[[115, 628, 300, 702]]
W) 100 Light years  X) 1,000 Light years  Y) 10,000 Light years  Z) 100,000 Light years  

text[[115, 722, 420, 740]]
ANSWER: Z) 100,000 LIGHT YEARSsub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[114, 130, 872, 166]]
5) Math – Short Answer In a world where pennies do not exist, how many unique cent values under a dollar can be made by nickels, dimes, and quarters?  

text[[115, 186, 231, 203]]
ANSWER: 20  

sub_title[[462, 224, 533, 242]]
## BONUS  

text[[115, 262, 865, 316]]
5) Math – Short Answer In a game of 2 truths and 1 lie the following statements were given, identify which one of these statements is the lie: 1)Statement 2 is true 2) Statement 3 is false 3) Statement 1 is false.  

text[[115, 335, 451, 353]]
ANSWER: 3) STATEMENT 1 IS FALSE  

sub_title[[456, 410, 540, 428]]
## TOSS-UP  

text[[115, 448, 872, 485]]
6) Physics – Multiple Choice Identify all of the following three forces that will never do work on a system? 1) Kinetic Friction 2) Static Friction 3) Normal Force  

text[[115, 504, 356, 521]]
ANSWER: NONE OF THEM  

sub_title[[462, 523, 533, 541]]
## BONUS  

text[[115, 560, 832, 597]]
6) Physics – Short Answer Cooper pairs in superconductors are what class of composite particles due to their spin?  

text[[115, 616, 288, 634]]
ANSWER: BOSONSsub_title[[455, 91, 540, 108]]
## TOSS-UP  

text[[114, 130, 870, 166]]
7) Chemistry – Multiple Choice What scientist is credited with the discovery of the 2 resonant structures of benzene in 1865 that contribute the majority to its overall structure?  

text[[114, 185, 210, 256]]
W) Dewar 
X) Kekule 
Y) Claus 
Z) Lavosier  

text[[115, 275, 315, 293]]
ANSWER: X) KEKULE  

sub_title[[462, 310, 533, 328]]
## BONUS  

text[[115, 345, 848, 400]]
7) Chemistry – Multiple Choice In lab, you use a \(5.00 \mathrm{mL}\) volumetric pipet, a \(25.00 \mathrm{mL}\) volumetric flask, and a \(250 \mathrm{mL}\) beaker to measure out solutions to make a series of dilutions. The number of significant figures you need in the concentration of the final solution is:  

text[[115, 418, 155, 486]]
W) 1 
X) 2 
Y) 3 
Z) 4  

text[[115, 508, 246, 525]]
ANSWER: X) 2  

sub_title[[455, 580, 540, 598]]
## TOSS-UP  

text[[115, 615, 854, 652]]
8) Biology – Multiple Choice What effect causes reduced genetic variation of a population that split off from a larger original population?  

text[[115, 668, 379, 687]]
ANSWER: FOUNDER EFFECT  

sub_title[[462, 705, 533, 723]]
## BONUS  

text[[115, 741, 875, 778]]
8) Biology – Multiple Choice In a cross section of a stem of a monocot, how are the vascular bundles arranged?  

text[[115, 798, 590, 877]]
W) The xylem and phloem form concentric rings 
X) The vascular bundles form concentric rings 
Y) The xylem and phloem are scattered throughout the stem 
Z) The vascular bundles are scattered throughout the stem  

text[[115, 898, 880, 917]]
ANSWER: Z) THE VASCULAR BUNDLES ARE SCATTERED THROUGHOUT THE STEMsub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[113, 130, 855, 166]]
9) Earth and Space – Multiple Choice What is the most prominent last stage of an average star's life before it turns into a black dwarf?  

text[[115, 186, 337, 203]]
ANSWER: WHITE DWARF  

sub_title[[462, 224, 533, 242]]
## BONUS  

text[[115, 262, 860, 299]]
9) Earth and Space – Multiple Choice What is the name for a small hill that is steep on one end and tapered on the other end, where it points towards the direction of ice movement?  

text[[115, 318, 303, 336]]
ANSWER: DRUMLIN  

sub_title[[456, 392, 540, 410]]
## TOSS-UP  

text[[115, 430, 866, 467]]
10) Math – Short Answer A right triangle has sides of length \(x + 3\) , \(x + 10\) , and \(x + 11\) . What is the smallest positive value of \(x\) possible?  

text[[115, 486, 220, 503]]
ANSWER: 2  

sub_title[[462, 525, 533, 543]]
## BONUS  

text[[115, 562, 871, 634]]
10) Math – Short Answer An ant is on a vertex of an equilateral triangle with length 5 inches. If the ant wants to get to the middle of the side directly opposite of it, how much of a difference to the nearest inch is it if the ant goes straight across the triangle rather than following the edge of the triangle?  

text[[115, 654, 220, 671]]
ANSWER: 3sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 130, 872, 166]]
11) Physics – Short Answer On square ABCD, each point A, B, C, D has a charge of q. What is the net electric force in Newtons on a test charge in the center of the square?  

text[[115, 184, 221, 201]]
ANSWER: 0  

sub_title[[462, 222, 533, 240]]
## BONUS  

text[[115, 260, 861, 296]]
11) Physics – Multiple Choice Two charges, +q & -q, are placed a distance away from each other. Which of the following is NOT true regarding the electric field lines?  

text[[115, 313, 695, 386]]
W) Where there are less lines the electric field will be weaker. 
X) The electric field vectors can be added to find the total electric field strength. 
Y) +q and -q form an electric dipole 
Z) Electric field lines will cross at a maximum field potential.  

text[[115, 407, 787, 443]]
ANSWER: Z) ELECTRIC FIELD LINES WILL CROSS AT A MAXIMUM FIELD POTENTIAL.  

sub_title[[456, 501, 540, 519]]
## TOSS-UP  

text[[115, 539, 850, 575]]
12) Chemistry – Short Answer What principle arises from the addition of F block electrons that deviates from expected atomic radii for the predicted atoms?  

text[[115, 594, 483, 611]]
ANSWER: LANTHANIDE CONTRACTION  

sub_title[[462, 633, 533, 651]]
## BONUS  

text[[115, 670, 847, 707]]
12) Chemistry – Short Answer Which of the following statements is not correct regarding Rydberg’s Formula?  

text[[115, 726, 879, 818]]
W) Rydberg’s formula can be expanded to calculate the energy for multi electron systems. 
X) If you assume the final energy state for an electron is infinity you will calculate the ionization energy of the atom. 
Y) Rydberg’s formula only works for single electron systems 
Z) Rydberg’s formula works towards helping our understanding of emission spectrum.  

text[[115, 839, 835, 874]]
ANSWER: W) RYDBERG’S FORMULA CAN BE EXPANDED TO CALCULATE THE ENERGY FOR MULTI ELECTRON SYSTEMSsub_title[[455, 91, 540, 108]]
## TOSS-UP  

text[[115, 129, 847, 166]]
13) Biology – Short Answer What pair of almond sized part of the brain is responsible for processing memory and other functions?  

text[[115, 185, 325, 203]]
ANSWER: AMYGDALA  

sub_title[[462, 205, 533, 223]]
## BONUS  

text[[115, 243, 850, 279]]
13) Biology – Short Answer Silica is a substance that composes what name for an external layer of a diatom?  

text[[115, 298, 310, 316]]
ANSWER: FRUSTULE  

sub_title[[455, 373, 540, 391]]
## TOSS-UP  

text[[115, 411, 869, 448]]
14) Earth and Space – Multiple Choice What amorphous sedimentary rock is primarily used for the production of aluminum through the Bayer process?  

text[[115, 467, 297, 485]]
ANSWER: BAUXITE  

sub_title[[462, 505, 533, 523]]
## BONUS  

text[[115, 543, 841, 579]]
14) Earth and Space – Short Answer How far in meters from the east coast of the United States in the Atlantic Ocean do Nor'easter storms usually form?  

text[[115, 599, 262, 674]]
W) 6,000 Meters  X) 24,000 Meters  Y) 72,000 Meters  Z) 160,000 Meters  

text[[115, 694, 358, 712]]
ANSWER: Z) 160,000 Meterssub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 129, 867, 166]]
15) Math – Short Answer What is the inverse of a 3x3 matrix with first row 1,0,0 second row 0,1,0 and third row 0,0,1.  

text[[115, 185, 839, 222]]
ANSWER: FIRST ROW 1,0,0 SECOND ROW 0,1,0 AND THIRD ROW 0,0,1 (ACCEPT: IDENTITY MATRIX)  

sub_title[[462, 242, 533, 260]]
## BONUS  

text[[115, 280, 863, 316]]
15) Math – Short Answer How many integer values of n between 1 and 1,000 inclusive does the decimal representation of n/1,400 terminate?  

text[[115, 336, 240, 353]]
ANSWER: 142  

sub_title[[456, 409, 540, 428]]
## TOSS-UP  

text[[115, 448, 881, 485]]
16) Physics – Short Answer A charge of 3 microcoulombs is placed in an electric field with an electric field vector of 30000 N/C. Find the force in Newtons felt by the charge q.  

text[[115, 505, 264, 523]]
ANSWER: 0.09 N  

sub_title[[462, 545, 533, 563]]
## BONUS  

text[[115, 583, 880, 637]]
16) Physics – Multiple Choice If you apply a force to the pedals of your bike and accelerate, the wheels have an angular acceleration. Consider the rim of the back wheel, the things that apply a torque to this rim are  

text[[115, 657, 391, 732]]
W) The ground 
X) The spokes 
Y) Both the ground and spokes 
Z) Neither the ground or the spoke  

text[[115, 752, 558, 770]]
ANSWER: Y) BOTH THE GROUNDS AND SPOKESsub_title[[455, 91, 540, 108]]
## TOSS-UP  

text[[115, 130, 881, 166]]
17) Chemistry – Multiple Choice When the molecule Calcium Carbide melts, what bond stays together?  

text[[115, 186, 400, 261]]
W) Calcium Carbon Bond  X) Carbon Carbon Bond  Y) Calcium Carbide Bond  Z) None of the bonds stays together  

text[[115, 281, 470, 299]]
ANSWER: X) CARBON CARBON BOND  

sub_title[[455, 300, 525, 317]]
## BONUS  

text[[115, 338, 876, 392]]
17) Chemistry – Short Answer What phenomenon occurs when molecular orbitals of the same symmetry form from the combination of 2s and 2p orbitals that are close enough in energy to further interact, exemplified by C2  

text[[115, 411, 310, 428]]
ANSWER: SP MIXING  

sub_title[[448, 486, 533, 504]]
## TOSS-UP  

text[[115, 523, 783, 560]]
18) Biology – Multiple Choice Which of the following is NOT a feature of human embryonic development?  

text[[115, 580, 388, 654]]
W) Presence of an inner cell mass  X) Formation of a primitive streak  Y) Meroblastic cleavage  Z) Holoblastic cleavage  

text[[115, 674, 485, 692]]
ANSWER: Y) MEROBLASTIC CLEAVAGE  

sub_title[[455, 712, 525, 730]]
## BONUS  

text[[115, 750, 764, 768]]
18) Biology – Multiple Choice A carotene differs from that of a xanthophyll by:  

text[[115, 788, 866, 862]]
W) Xanthophyll are oxygen containing carotenoids, while carotene contain aromatic rings.  X) Xanthophyll have 13 degrees of unsaturation while Carotene are straight chain alkanes  Y) Xanthophyll have a more characteristic yellow hue while carotene is more of an orange hue.  Z) Xanthophyll is a derivative of chlorophyll, while carotene is a derivative of carotenoids.  

text[[115, 882, 829, 917]]
ANSWER: Y) XANTHOPHYLL HAVE A MORE CHARACTERISTIC YELLOW HUE WHILE CAROTENE IS MORE OF AN ORANGE HUE.sub_title[[455, 90, 540, 108]]
## TOSS-UP  

text[[115, 148, 877, 186]]
19) Earth and Space – Short Answer What effect arises from the apparent change of position of something based on a different line of sight?  

text[[115, 205, 315, 222]]
ANSWER: PARALLAX  

sub_title[[462, 243, 533, 261]]
## BONUS  

text[[115, 280, 820, 318]]
19) Earth and Space – Multiple Choice Which of the following is the name for glacial outburst flood triggered by geothermal heating and volcanism?  

text[[115, 336, 262, 411]]
W) Plinian 
X) Oranunai 
Y) Jokulhlaup 
Z) Cryovolcanism  

text[[115, 430, 364, 448]]
ANSWER: Y) JOKULHLAUP  

sub_title[[455, 505, 540, 523]]
## TOSS-UP  

text[[115, 543, 548, 562]]
20) Math – Short Answer Simplify: \(\sin (x) + \sin (pi - x)\)  

text[[115, 580, 280, 599]]
ANSWER: 2SIN(X)  

sub_title[[462, 619, 533, 637]]
## BONUS  

text[[115, 656, 870, 694]]
20) Math – Short Answer What is the definite integral from 0 to 2 of \(\ln (x)/x\) dx and indefinite integral of \(\ln (x)/x\) dx?  

text[[115, 712, 374, 732]]
ANSWER: - infinity, \(\ln (x)^2 /2 + C\)sub_title[[455, 90, 540, 108]]
## TOSS-UP  

text[[114, 129, 874, 185]]
21) Physics – Short Answer Identify all of the following statements that are true for an object in static equilibrium 1) All forces acting on the object are equal 2) The net force of the system is 0 3) The static friction force is equivalent to the normal force.  

text[[115, 204, 280, 221]]
ANSWER: 2 ONLY  

sub_title[[462, 242, 533, 260]]
## BONUS  

text[[112, 280, 839, 300]]
21) Physics – Multiple Choice What is the spatial dimension for the Dirac Spin matrices?  

text[[114, 319, 175, 393]]
W) 2x3 
X) 3x2 
Y) 4x4 
Z) 5x5  

text[[115, 411, 270, 430]]
ANSWER: Y) 4X4  

sub_title[[455, 488, 540, 505]]
## TOSS-UP  

text[[114, 525, 841, 581]]
22) Biology – Short Answer What type of speciation arises from the evolution of a new species from a surviving ancestral species while both of the species continue to reside in the same region?  

text[[115, 599, 443, 618]]
ANSWER: SYMPATRIC SPECIATION  

sub_title[[462, 638, 533, 656]]
## BONUS  

text[[114, 675, 826, 712]]
22) Biology – Multiple Choice What type of glial cell is responsible for creating myelin sheaths in the central nervous system?  

text[[114, 731, 288, 806]]
W) Oligodendrocytes 
X) Schwann cells 
Y) Astrocytes 
Z) Microglia  

text[[115, 825, 445, 844]]
ANSWER: W) OLIGODENDROCYTESsub_title[[455, 91, 540, 108]]
## TOSS-UP  

text[[114, 129, 848, 185]]
23) Chemistry – Short Answer In lab, you use a \(5.00 \mathrm{mL}\) volumetric pipet, a \(25.00 \mathrm{mL}\) volumetric flask, and a \(250 \mathrm{mL}\) beaker to measure out solutions to make a series of dilutions. The number of significant figures you need in the concentration of the final solution is:  

text[[114, 204, 155, 275]]
W) 1  X) 2  Y) 3  Z) 4  

text[[115, 293, 247, 311]]
ANSWER: X) 2  

sub_title[[462, 330, 533, 348]]
## BONUS  

text[[113, 367, 875, 404]]
23) Chemistry – Short Answer What is the coordination number and number of atoms per unit cell for a hexagonal closest packed?  

text[[115, 423, 250, 440]]
ANSWER: 12, 6