sub_title[[464, 92, 533, 110]]
## Tossup  

text[[115, 111, 876, 181]]
1) Physics - Short Answer: A 5 kg mass is hanging from two springs connected in parallel. The first spring has a spring constant of 20 Newtons per meter and a mass of 6 kilograms, while the second spring has a spring constant of 60 Newtons per meter and a mass of 3 kilograms. To the nearest tenth, what is the angular frequency of the mass's oscillations?  

text[[115, 198, 240, 215]]
ANSWER: 3.2  

sub_title[[466, 238, 530, 256]]
## Bonus  

text[[115, 258, 861, 327]]
1) Physics - Short Answer: An ideal gas begins at a pressure of 20 Pascals and a volume of 4 \(\mathrm{m}^3\) . If the gas undergoes isothermal expansion to a volume of \(11 \mathrm{m}^3\) , then to one significant figure, what is the change in entropy in Joules per Kelvin during expansion if the gas ends at a temperature of 300 Kelvin?  

text[[115, 344, 240, 362]]
ANSWER: 0.3  

sub_title[[464, 453, 533, 471]]
## Tossup  

text[[115, 472, 880, 525]]
2) Chemistry - Multiple Choice: Solvents that limit the maximum acid strength of a certain acid are called leveling solvents. Conversely, what is the term given to solvents that do not limit a certain acid's acidity?  

text[[115, 542, 401, 559]]
ANSWER: Differentiating solvents  

sub_title[[466, 580, 530, 597]]
## Bonus  

text[[115, 599, 880, 633]]
2) Chemistry - Multiple Choice: Order the following 4 solvents in order of increasing acidity of \(\mathrm{HNO}_2\) in them:  

text[[173, 652, 266, 720]]
1) Water 
2) HCl 
3) Benzene 
4) NaOH  

text[[115, 739, 285, 757]]
ANSWER: 2, 3, 1, 4sub_title[[463, 92, 533, 110]]
## Tossup  

text[[113, 111, 880, 145]]
3) Math - Short Answer: Let x be a real number such that 5x plus the floor of x equals 14. What is x?  

text[[115, 163, 241, 180]]
ANSWER: 2.4  

sub_title[[465, 201, 530, 218]]
## Bonus  

text[[113, 220, 860, 238]]
3) Math - Short Answer: What is the sum from k=1 to 99 of the floor of the square root of k?  

text[[115, 255, 245, 272]]
ANSWER: 615  

sub_title[[465, 328, 533, 345]]
## Tossup  

text[[115, 346, 825, 381]]
4) Biology - Short Answer: What cell type makes up the inner layer of the glomerulus in kidneys?  

text[[115, 399, 297, 417]]
ANSWER: Podocytes  

sub_title[[465, 437, 530, 454]]
## Bonus  

text[[112, 455, 784, 473]]
4) Biology - Short Answer: Identify all of the following 3 structures that are diploid:  

text[[172, 491, 338, 560]]
I) Microspores  II) Megasporangium  III) Zygote  IV) Endosperm  

text[[115, 578, 258, 595]]
ANSWER: II, IIIsub_title[[463, 92, 533, 110]]
## Tossup  

text[[114, 111, 875, 180]]
5) Energy – Short Answer: Researchers at Sandia National Labs are studying ways that the human immune system fights off microbial infections. One of these ways involves the production of a powerful oxidant from water and singlet oxygen molecules. What is the name of this compound?  

text[[115, 198, 301, 215]]
ANSWER: Trioxidane  

sub_title[[466, 252, 530, 270]]
## Bonus  

text[[115, 272, 852, 342]]
5) Energy – Multiple Choice: Scientists in Fauci's attic, funded by the DOE, have made anthrax that is resistant to penicillin. They figure out that the anthrax is breaking down the penicillin, and have isolated the enzyme doing so. Which of the following enzymes have they most likely identified?  

text[[172, 360, 424, 430]]
W) Beta Lactamase 
X) Delta Trilactone 
Y) Penicillin Breaking Proteins 
Z) Alpha Galactase  

text[[115, 448, 365, 465]]
ANSWER: W) Beta Lactamase  

sub_title[[463, 520, 533, 539]]
## Tossup  

text[[112, 540, 797, 558]]
6) Math – Short Answer: What is the area of the lemniscate with equation \(\mathrm{r}^2 = \sin (20)\) ?  

text[[115, 575, 223, 592]]
ANSWER: 1  

sub_title[[466, 615, 530, 633]]
## Bonus  

text[[115, 634, 880, 670]]
6) Math – Short Answer: Evaluate the limit as x approaches 0 of \(\csc (x) - 1 / x\) [READ: cosecant of open parenthesis x close parenthesis minus 1 over open parenthesis x close parenthesis].  

text[[115, 687, 225, 704]]
ANSWER: 0sub_title[[463, 127, 533, 145]]
## Tossup  

text[[115, 146, 808, 165]]
7) Chemistry - Short Answer: How many geometric isomers does [FeCl<sub>2</sub>(NH<sub>3</sub>)<sub>4</sub>] have?  

text[[115, 181, 220, 198]]
ANSWER: 2  

sub_title[[466, 201, 530, 219]]
## Bonus  

text[[115, 221, 854, 256]]
7) Chemistry - Short Answer: Electron transitions between which two molecular orbitals are responsible for octachlorodirhenate's distinctive color?  

text[[115, 273, 355, 290]]
ANSWER: Delta to delta star  

sub_title[[463, 345, 533, 363]]
## Tossup  

text[[115, 364, 872, 400]]
8) Earth and Space - Multiple Choice: Which of the following phases of corundum would you be most likely to find in the D" [D prime prime] layer of the mantle?  

text[[172, 416, 290, 490]]
W) Alpha-Cor 
X) \(\mathrm{Rh}_2\mathrm{O}_3\) Y) Perovskite 
Z) Post-Perovskite  

text[[115, 506, 358, 523]]
ANSWER: Z) Post-Perovskite  

sub_title[[466, 543, 530, 560]]
## Bonus  

text[[115, 561, 882, 596]]
8) Earth and Space - Short Answer: Identify all of the following 3 quantities that could increase with increasing vertical wind shear:  

text[[172, 614, 483, 668]]
I) Hurricane longevity 
II) Friction with the ground 
III) Height of planetary boundary layer  

text[[115, 685, 282, 702]]
ANSWER: II and IIIsub_title[[463, 92, 533, 110]]
## Tossup  

text[[114, 111, 881, 163]]
9) Physics - Short Answer: A spherical bubble is made of soapy water with a surface tension of 0.5 Newtons per meter. The radius of the bubble is \(5 \mathrm{cm}\) . What is the pressure difference between the inside and outside of the bubble, in Pascals?  

text[[115, 181, 297, 199]]
ANSWER: 20 pascals  

sub_title[[466, 218, 530, 235]]
## Bonus  

text[[115, 237, 883, 289]]
9) Physics - Multiple Choice: Consider an infinite square potential well with a width W. Considering the left edge of the well to be \(\mathbf{x} = 0\) , where are the most likely locations for a particle at the \(\mathrm{n} = 2\) energy level to be found?  

equation[[172, 306, 390, 380]]
\[\mathrm{W)~x = 0~and~x = W}\] \[\mathrm{X)~x = W / 2~and~x = W\sqrt{2} /2}\] \[\mathrm{Y)~x = W / 4~and~x = 3W / 4}\] \[\mathrm{Z)~x = W / 3~and~x = 2W / 3}\]  

text[[115, 396, 418, 414]]
ANSWER: \(\mathrm{Y)~x = W / 4}\) and \(\mathrm{x} = 3\mathrm{W / 4}\)  

sub_title[[463, 469, 533, 487]]
## Tossup  

text[[115, 488, 806, 522]]
10) Math - Short Answer: Let ABC be a triangle with D on AC and E on BC such that AD/DC=5/3 and BE/EC=5/2. Let BD and AE meet at F. What is BF/FD?  

text[[115, 540, 226, 557]]
ANSWER: 4  

sub_title[[466, 577, 530, 595]]
## Bonus  

text[[115, 596, 874, 666]]
10) Math - Short Answer: An inversion is defined as a geometric map about a center of inversion O and with radius R such that the image P\* lying on the ray OP of the point P satisfies OP x OP\* = R². The center of inversion will map to a point at infinity. Identify all of the following 3 properties of an inversion with center O and radius R that are true:  

text[[172, 684, 881, 753]]
I) An inversion about a point twice is equivalent to a rotation of 180 degrees about O 
II) Any line passing through O is mapped to itself. 
III) Any circle o [omega] passing through O is mapped to the line that passes through the two intersections of the circle with radius R and center O with o  

text[[115, 771, 287, 789]]
ANSWER: II and IIIsub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 808, 146]]
11) Earth and Space – Short Answer: Identify all of the following 3 rock types that are commonly used to make paleoclimate observations:  

text[[172, 163, 314, 216]]
I) Petrified Wood  II) Ice  III) Travertine  

text[[115, 234, 247, 252]]
ANSWER: ALL  

sub_title[[466, 272, 530, 290]]
## Bonus  

text[[115, 291, 868, 326]]
11) Earth and Space – Short Answer: Identify all of the following 3 statements that are true of the East Pacific rise:  

text[[115, 343, 857, 432]]
I) It rifts faster on its Eastern side  II) It rifts faster than subduction occurs at the boundaries of the ring of fire, expanding the Pacific ocean basin  III) Rifting of the pacific plate can entirely account for the positions of the Hawaii-emperor seamount chain  

text[[115, 448, 257, 466]]
ANSWER: I only  

sub_title[[463, 521, 533, 540]]
## Tossup  

text[[115, 540, 849, 592]]
12) Physics – Short Answer: Andrew is riding in a bullet train with velocity 0.5c. If Andrew throws a ball towards the back of the train at a speed of 0.25c, what speed would the ball be traveling at with respect to a ground observer?  

text[[115, 609, 250, 626]]
ANSWER: 2c/7  

sub_title[[466, 629, 530, 647]]
## Bonus  

text[[115, 648, 875, 753]]
12) Physics – Short Answer: Consider a capacitor with a capacitance of 4 Farads. The capacitor is charged by a 9 Volt voltage source and then disconnected. Another capacitor with a capacitance of 2 Farads is connected in parallel with the 4 Farad capacitor, allowed to charge, and removed. A 1 Farad capacitor is then connected and disconnected from the 4 Farad capacitor, and the process continues. In Coulombs, what is the charge remaining on the 4 Farad capacitor after the 0.5 Farad capacitor has been disconnected?  

text[[115, 771, 270, 788]]
ANSWER: 256/15sub_title[[464, 92, 533, 110]]
## Tossup  

text[[115, 111, 847, 180]]
13) Energy – Short Answer: Researchers at Fermilab are studying high energy collisions between subatomic particles. What mathematical function, which is the derivative of the Heaviside Step Function, can be used to model the force on a subatomic particle in an elastic collision as a function of time?  

text[[115, 198, 381, 215]]
ANSWER: Dirac Delta Function  

sub_title[[466, 238, 530, 256]]
## Bonus  

text[[115, 257, 875, 327]]
13) Energy – Multiple Choice: Researchers at NASA are using reflecting telescopes to study the formation of stars in the Orion Nebula. Both Gregorian and Cassegrain telescope designs are used to focus incoming radio waves. Which of the following best describes the difference between Gregorian and Cassegrain telescopes?  

text[[172, 344, 866, 451]]
W) Gregorian telescopes are reflecting and Cassegrain are not 
X) Gregorian telescopes use two lenses while Cassegrain use three 
Y) Gregorian telescopes use a concave secondary mirror while Cassegrain use a convex secondary mirror 
Z) Gregorian telescopes reflect incoming light at a high angle of incidence while Cassegrain reflect at a low angle of incidence  

text[[115, 468, 844, 503]]
ANSWER: Y) Gregorian telescopes use a concave secondary mirror while Cassegrain use a convex secondary mirror  

sub_title[[464, 526, 533, 544]]
## Tossup  

text[[115, 545, 839, 580]]
14) Earth and Space – Multiple Choice: Which of the following is closest to the age of the surface of Venus?  

text[[172, 581, 340, 650]]
W) 4.5 million years 
X) 45 million years 
Y) 450 million years 
Z) 4.5 billion years  

text[[115, 652, 228, 668]]
ANSWER: Y  

sub_title[[466, 670, 530, 688]]
## Bonus  

text[[115, 689, 870, 724]]
14) Earth and Space – Multiple Choice: Which of the following satellites of Saturn is believed to be a captured Kuiper Belt Object?  

text[[115, 741, 275, 828]]
W) Phoebe 
X) Titan 
Y) Mimas 
Z) Hyperion  

text[[115, 812, 233, 828]]
ANSWER: Wsub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 879, 198]]
15) Biology - Multiple Choice: Thanush, a person who is usually healthy, starts to complain of indigestion. He goes to the doctor who checks his stool for digestive enzymes. The doctor detected lower amounts of elastase and chymotrypsin but normal levels of pepsinogen. Which of the following anatomical structures, when not working properly, would cause the symptoms listed above?  

text[[173, 215, 345, 288]]
W) Pyloric Sphincter 
X) Sphincter of Oddi 
Y) Bile Duct 
Z) Rugal Folds  

text[[115, 304, 356, 322]]
Answer: X) Sphincter of Oddi  

sub_title[[466, 323, 530, 340]]
## Bonus  

text[[115, 342, 844, 378]]
15) Biology - Short Answer: Identify all of the following 4 vesicle pathways that do not use COPI [C O P one]  

text[[172, 395, 608, 465]]
I) Going from one golgi cisterna to another. II) Going from the plasma membrane to the Golgi III) Going from the ER to the Golgi IV) Going from the plasma membrane to an endosome  

text[[115, 482, 283, 500]]
ANSWER: II, III, IV  

sub_title[[463, 520, 533, 539]]
## Tossup  

text[[115, 539, 852, 574]]
16) Chemistry - Multiple Choice: 6 pi electroclyclic thermal ring closing is best described as which of the following?  

text[[172, 592, 294, 664]]
W) Conrotary 
X) Destructive 
Y) Disrotary 
Z) Inverting  

text[[115, 680, 315, 699]]
ANSWER: Y) Disrotary  

sub_title[[466, 718, 530, 735]]
## Bonus  

text[[115, 736, 875, 755]]
16) Chemistry - Multiple Choice: Which of the following statements about point groups is false?  

text[[172, 771, 697, 844]]
W) Compounds in the \(\mathrm{C}_{\mathrm{s}}\) point group have no planes of symmetry. 
X) Compounds in the \(\mathrm{C}_{\mathrm{i}}\) point group have a center of inversion. 
Y) Compounds in the \(\mathrm{C}_{1}\) point group only have an identity axis. 
Z) Compounds in the \(\mathrm{D}_{\mathrm{N}}\) point group are always chiral.  

text[[115, 861, 710, 880]]
Answer: W) Compounds in the \(\mathrm{C}_{\mathrm{s}}\) point group have no planes of symmetry.sub_title[[464, 92, 533, 110]]
## Tossup  

text[[115, 111, 857, 145]]
17) Earth and Space –Multiple Choice: Which of the following moon-planet systems are not tidally locked?  

text[[173, 163, 404, 234]]
W) Phobos and Mars  
X) Hippocamp and Neptune  
Y) Io and Jupiter  
Z) Titan and Saturn  

text[[115, 253, 230, 270]]
ANSWER: X  

sub_title[[465, 272, 530, 290]]
## Bonus  

text[[115, 291, 840, 361]]
17) Earth and Space – Short Answer: Carbon Rich Mira Variable stars tend to have larger amounts of carbon at their surfaces than is expected for similar stars in the asymptotic giant branch. What is the name for the process that allows them to maintain a high surface carbon content?  

text[[115, 378, 293, 396]]
ANSWER: Dredge up  

sub_title[[464, 450, 533, 469]]
## Tossup  

text[[115, 470, 835, 540]]
18) Physics – Short Answer: The Legendre [READ: le-zhan-der (zh like S in meaSure)] transform is used to transform Lagrangian systems into Hamiltonian ones. The Legendre transform turns equations of any quantity \(q\) and \(q\) dot into equations of \(q\) and \(X\) , with \(X\) representing what quantity?  

text[[115, 556, 810, 576]]
ANSWER: Conjugate quantity of \(q\) (ACCEPT: conjugate of \(q\) , generalized momentum)  

sub_title[[465, 614, 530, 632]]
## Bonus  

text[[115, 633, 859, 686]]
18) Physics – Short Answer: Consider a system of 3 einstein solids each in turn containing 3 oscillators, sharing a total of 3 units of energy. Assuming the solids are in thermal contact, and the total energy is fixed to 3 units, how many possible macrostates are available to the system?  

text[[115, 704, 230, 721]]
ANSWER: 10sub_title[[463, 92, 533, 110]]
## Tossup  

text[[114, 111, 860, 146]]
19) Chemistry - Short Answer: What reagent can be used to convert a carboxylic acid into an acid chloride, resulting in a triprotic acid as a byproduct?  

text[[115, 162, 250, 181]]
ANSWER: \(\mathrm{PCl}_3\)  

sub_title[[463, 201, 533, 219]]
## Tossup  

text[[115, 220, 844, 257]]
19) Chemistry - Short Answer: Identify all of the following 4 molecules have a measurable dipole moment in their lowest energy states:  

text[[172, 259, 453, 337]]
I) 1,2-Dichloroethane  II) trans-1,3-Dichlorocyclobutane  III) trans-1,4-Dichlorocyclohexane  IV) 1,3-Dichlorocyclopentane  

text[[115, 358, 269, 376]]
ANSWER: 2 and 4  

sub_title[[463, 431, 533, 450]]
## Tossup  

text[[115, 451, 855, 487]]
20) Biology - Short Answer: What is the name of the structure in the lateral line organ of fish that detects vibration and changes in pressure?  

text[[115, 503, 469, 522]]
ANSWER: Neuromasts (ACCEPT: Cupula)  

sub_title[[465, 541, 530, 559]]
## Bonus  

text[[115, 560, 816, 595]]
20) Biology - Short Answer: Identify all of the following 4 enzymes that are incorrectly matched with their substrate  

text[[172, 613, 510, 683]]
I) Aromatase - testosterone  II) Phospholipase C - phosphatidylinositol  III) Separase - cohesin  IV) Catalase - hydrogen peroxide  

text[[115, 700, 258, 717]]
ANSWER: Nonesub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 875, 181]]
21) Energy - Short Answer: Researchers at Princeton Plasma Physics Lab are studying the behavior of materials at very low temperatures. Which physical law, which does not hold at very low temperatures, relates the predicted molar heat capacity of elements in their standard state with the ideal gas constant?  

text[[115, 198, 549, 216]]
ANSWER: Dulong-Petit Law (ACCEPT: Kopp's Law)  

sub_title[[465, 235, 530, 253]]
## Bonus  

text[[115, 255, 872, 325]]
21) Energy - Short Answer: Scientists at Johns Hopkins University have measured the vacuum energy of free space to be on the order of \(10^{-9}\) joules per cubic meter. Approximately how many orders of magnitude smaller is this finding compared to the theoretical result derived from quantum electrodynamics?  

text[[172, 343, 230, 414]]
W) 10 
X) 30 
Y) 80 
Z) 120  

text[[115, 431, 264, 449]]
ANSWER: Z) 120  

sub_title[[463, 506, 533, 524]]
## Tossup  

text[[115, 525, 875, 560]]
22) Biology - Multiple Choice: Which of the following plant nutrient deficiencies is incorrectly matched with its symptoms?  

text[[172, 577, 875, 650]]
W) Iron - Interveinal chlorosis of young leaves along with shorter stems. 
X) Boron - Failure of root tips to elongate, young leaves become light green at the base. 
Y) Copper - Young leaves are light green and twisted, with many necrotic spots. 
Z) Potassium - Mottled or chlorotic leaves with necrotic spots, more older leaves affected  

text[[115, 667, 223, 684]]
ANSWER: Y  

sub_title[[465, 704, 530, 721]]
## Bonus  

text[[115, 722, 864, 758]]
22) Biology - Multiple Choice: Order the following 4 sections of the adult spine in increasing order of how many vertebrae they contain:  

text[[173, 775, 316, 847]]
1) Sacrum 
2) Cervical Spine 
3) Thoracic Spine 
4) Lumbar Spine  

text[[115, 864, 264, 881]]
ANSWER: 1,4,2,3sub_title[[463, 108, 533, 127]]
## Tossup  

text[[114, 128, 884, 181]]
23) Math - Short Answer: Define the function f:Z+->Z [READ: f from Z positive to Z] as tau(n) mod 2, where tau(n) denotes the number of factors of n. What is the sum from 1 to 1000 of f(n)  

text[[115, 199, 234, 216]]
ANSWER: 31  

sub_title[[466, 235, 530, 253]]
## Bonus  

text[[115, 254, 880, 308]]
23) Math - Short Answer: Bela and Jenn are playing Scibowl against each other, until one of them wins two games in a row. The result of each game is independent from each other, and each player has a \(\frac{1}{2}\) chance of winning. What is the expected number of games that they will play?  

text[[115, 325, 225, 342]]
ANSWER: 5