sub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 841, 146]]
1) Chemistry – Short Answer: Identify all of the following 4 coordinate geometries that are correctly paired with their coordination numbers:  

text[[172, 163, 422, 234]]
I) Octahedral and 8 
II) Tetrahedral and 3 
III) Trigonal bipyramidal and 3 
IV) Square pyramidal and 4  

text[[115, 251, 258, 268]]
ANSWER: None  

sub_title[[465, 291, 530, 309]]
## Bonus  

text[[115, 310, 864, 346]]
1) Chemistry – Short Answer: Identify all of the following four coordinate geometries that are correctly paired with the type of hybridization around the central ion:  

text[[172, 362, 388, 433]]
I) Tetrahedral and \(\mathrm{sp}^{3}\) II) Octahedral and \(\mathrm{d}^{3}\mathrm{s}^{3}\) III) Square planar and \(\mathrm{dsp}^{2}\) IV) Linear and \(\mathrm{sp}^{2}\)  

text[[115, 450, 280, 467]]
ANSWER: I and III  

sub_title[[463, 505, 533, 523]]
## Tossup  

text[[115, 524, 848, 560]]
2) Math – Short Answer: What is the area of the region in the xy plane corresponding to the domain of the function \(\mathrm{f(x, y) = sqrt(1 - x^{2} - y^{2})}\) ?  

text[[115, 576, 231, 594]]
ANSWER: pi  

sub_title[[465, 631, 530, 649]]
## Bonus  

text[[115, 650, 877, 686]]
2) Math – Short Answer: Regular hexagon ABCDEF has a side length of 6. What is the ratio of the length of AC to the length of AD?  

text[[115, 702, 284, 721]]
ANSWER: sqrt(3)/2sub_title[[463, 128, 533, 146]]
## Tossup  

text[[113, 146, 870, 183]]
3) Biology – Short Answer: Identify all of the following 4 polysaccharides that are incorrectly matched with their type of glycosidic (gly-ko-si-dic) linkage  

text[[172, 199, 697, 270]]
I) Sucrose: 1,2 glycosidic linkage  
II) Lactose: Beta 1,4 glycosidic linkage  
III) Amylopectin: 1,4 glycosidic linkage with 1,2 branching points  
IV) Glycogen: 1,4 glycosidic linkage with 1,6 branching points  

text[[115, 286, 275, 304]]
ANSWER: III only  

sub_title[[465, 324, 530, 341]]
## Bonus  

text[[115, 343, 832, 379]]
3) Biology – Multiple Choice: A competitive inhibitor does NOT change what aspect of a reaction’s progress, described by Michaelis-Menten kinetics?  

text[[172, 395, 242, 466]]
W) Vmax X) Km Y) Vo Z) Ea  

text[[115, 483, 280, 502]]
ANSWER: W) Vmax  

sub_title[[463, 540, 533, 558]]
## Tossup  

text[[112, 558, 875, 576]]
4) Physics – Short Answer: In Lagrangian mechanics, what principle replaces Newton’s F=ma?  

text[[115, 592, 750, 611]]
ANSWER: Principle of Stationary Action (ACCEPT: Principle of Least Action)  

sub_title[[465, 648, 530, 666]]
## Bonus  

text[[115, 667, 880, 702]]
#) Physics – Short Answer: A charged particle is placed in a constant electric field and moved in a figure 8 pattern. Identify all of the following 3 statements that are true of this process:  

text[[172, 719, 655, 774]]
I) The total work done is zero  
II) The total distance moved is zero  
III) The integral of the electric force over the path is nonzero  

text[[115, 791, 257, 808]]
ANSWER: I onlysub_title[[463, 92, 533, 110]]
## Tossup  

text[[113, 111, 880, 147]]
5) Math - Short Answer: The two legs of a right triangle are equal to the roots of the polynomial \(\mathrm{x}^2 - 15\mathrm{x} + 48\) [READ: x squared minus 15 x plus 48]. What is the area of the triangle?  

text[[115, 163, 230, 180]]
ANSWER: 24  

sub_title[[466, 201, 530, 218]]
## Bonus  

text[[115, 220, 857, 255]]
5) Math - Short Answer: What is the average of all the possible areas of a triangle ABC with angle \(\mathrm{A} = 60\) degrees, side \(\mathrm{b} = 9\) , and side \(\mathrm{a} = 8.6\) ?  

text[[115, 271, 281, 289]]
ANSWER: \(81\sqrt{3} /8\)  

sub_title[[463, 363, 533, 381]]
## Tossup  

text[[115, 382, 864, 434]]
6) Energy - Multiple Choice: Researchers at the University of Oxford are studying the effects of Solar winds on the isotopic composition of asteroids. Which of the following types of asteroids are considered to be the oldest in the solar system?  

text[[173, 451, 300, 524]]
W) Chondrite 
X) Stony 
Y) Metallic 
Z) Carbonaceous  

text[[115, 541, 323, 559]]
ANSWER: W) Chondrite  

sub_title[[466, 579, 530, 596]]
## Bonus  

text[[115, 597, 878, 666]]
6) Energy - Short Answer: Researchers at the National Ignition Facility at Lawrence Livermore National Lab are studying a proposed high pressure phase transformation in diamond under laser shock. Order the following allotropes of carbon from least to greatest stability at ambient conditions.  

text[[173, 684, 368, 752]]
1) Graphite 
2) Buckminsterfullerene 
3) Diamond 
4) Bc8  

text[[115, 770, 264, 787]]
ANSWER: 4,2,3,1sub_title[[464, 92, 533, 110]]
## Tossup  

text[[115, 111, 872, 145]]
7) Biology – Short Answer: Recognition of sound at different parts inside the cochlea allows us to distinguish what characteristic of sound waves?  

text[[115, 162, 654, 181]]
ANSWER: Pitch (ACCEPT: frequency or other equivalent answers)  

sub_title[[465, 204, 530, 221]]
## Bonus  

text[[115, 222, 833, 258]]
7) Biology – Short Answer: Identify all of the following 4 genetic disorders that follow an X-linked recessive inheritance pattern:  

text[[172, 276, 528, 346]]
I) Marfan syndrome  II) Red green color blindness  III) Phenylketonuria [feen-il-kee-to-nur-i-a]  IV) Tay Sachs disease  

text[[115, 362, 268, 380]]
ANSWER: II only  

sub_title[[464, 438, 533, 456]]
## Tossup  

text[[115, 457, 836, 491]]
8) Earth and Space – Short Answer: Which of the following statements is NOT true about Pluto?  

text[[172, 509, 631, 581]]
W) It is in a 3 to 2 orbital resonance with Neptune  X) It undergoes prograde rotation  Y) Its ice is made up of primarily methane  Z) It rotates over 10,000 times in one orbit around the sun  

text[[115, 615, 479, 633]]
ANSWER: X) It undergoes prograde rotation  

sub_title[[465, 652, 530, 670]]
## Bonus  

text[[115, 671, 875, 706]]
8) Earth and Space – Short Answer: Order the following three satellites of Jupiter in increasing albedo.  

text[[172, 724, 283, 777]]
1) Ganymede  
2) Europa  
3) Callisto  

text[[115, 795, 260, 813]]
ANSWER: 3, 1, 2sub_title[[463, 130, 533, 149]]
## Tossup  

text[[115, 149, 859, 202]]
9) Math - Short Answer: Your school has between 40 and 80 students. If classes are formed with size 7, there are 6 students left over. If classes are formed with size 9, there are 8 students left over. How many people are in the school?  

text[[115, 219, 235, 236]]
ANSWER: 62  

sub_title[[466, 259, 530, 277]]
## Bonus  

text[[115, 279, 870, 349]]
9) Math - Short Answer: Pranav buys an old collection of manga, hoping that some of them will turn out to be valuable. If a manga is valuable, its value doubles every 5 years, and if it is not, its value halves every 5 years. If he buys a collection of 300 manga for \(5 each and 20\%\) of them are valuable, what is the expected value of the collection after 15 years?  

text[[115, 365, 265, 383]]
ANSWER: \(\) 2550\$  

sub_title[[466, 420, 530, 438]]
## Bonus  

text[[115, 440, 810, 492]]
10) Energy - Short Answer: Scientists at Fermilab National Accelerator Laboratory are studying the decay of subatomic particles, such as muons. Identify all of the following 3 statements that are true about theories that predict proton decay:  

text[[171, 509, 800, 563]]
I) SU(5) Grand Unified Theory is one such theory. II) These theories predict a proton decaying into a positron and an antineutrino. III) The simplest of these theories have been experimentally disproven.  

text[[115, 579, 280, 596]]
ANSWER: I and III  

sub_title[[463, 598, 533, 617]]
## Tossup  

text[[115, 618, 870, 671]]
10) Energy - Short Answer: Scientists at Lawrence Berkeley National Laboratory are studying atomic nuclei and nuclear decay. What term describes the radiation emitted by an electron emitted from a nuclear reactor as it moves faster than the speed of light in the medium?  

text[[115, 687, 372, 705]]
ANSWER: Cherenkov radiationsub_title[[463, 111, 533, 130]]
## Tossup  

text[[115, 131, 868, 183]]
11) Physics – Short Answer: A soap bubble is created in a \(3 \mathrm{m}\) by \(5 \mathrm{m}\) rectangular wire frame. If the force from the liquid on one of the longer sides is \(15 \mathrm{N}\) , what is the force on one of the shorter sides?  

text[[115, 201, 245, 218]]
ANSWER: 9 N  

sub_title[[466, 238, 530, 256]]
## Bonus  

text[[115, 257, 874, 346]]
11) Physics – Multiple Choice: Consider a mass M moving at velocity u inside reference frame S. Reference frame S is moving at velocity v with respect to the observer. If \(\mathrm{K}_{\mathrm{u}}\) [READ: K sub u] is equal to \(\frac{1}{2} \mathrm{Mu}^2\) [READ: one half M u squared] and \(\mathrm{K}_{\mathrm{v}}\) [READ: K sub v] is equal to \(\frac{1}{2} \mathrm{Mv}^2\) [READ: one half M v squared], which of the following conditions must be true if the kinetic energy of mass M with respect to the observer is equal to \(\mathrm{K}_{\mathrm{u}} + \mathrm{K}_{\mathrm{v}}\) ?  

text[[172, 362, 731, 433]]
W) Velocity u is perpendicular to velocity v 
X) Velocity u is parallel to velocity v 
Y) The magnitude of velocity u is equal to the magnitude of velocity v 
Z) Velocity u and velocity v point in opposite directions  

text[[115, 450, 558, 469]]
ANSWER: W) Velocity u is perpendicular to velocity v  

sub_title[[463, 530, 533, 549]]
## Tossup  

text[[115, 549, 860, 601]]
12) Chemistry – Short Answer: Seth Landesman is developing new beard care products, specifically with beard gels. What intermolecular force is most important to the gel's ability to keep long strands of hair stuck together?  

text[[115, 618, 550, 636]]
ANSWER: Dispersion (ACCEPT: London dispersion)  

sub_title[[466, 673, 530, 691]]
## Bonus  

text[[115, 692, 810, 727]]
12) Chemistry – Short Answer: Identify all of the following four compounds that act as electrophiles:  

text[[172, 745, 278, 797]]
I) BH3 
II) NaOH 
III) HCOOH  

text[[115, 817, 252, 835]]
ANSWER: I, IIIsub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 110, 857, 145]]
13) Biology - Short Answer: Identify all of the following 4 statements that correctly describe characteristics of bacteria and archaea  

text[[171, 162, 865, 250]]
I) Bacterial flagella and archaean flagella are homologous  II) Archaean [arc-ay-an] cell walls lack peptidoglycan [pep-tid-o-gly-can]  III) Archaea use methionine [meth-i-o-neen] as their starting amino acid while bacteria use formyl-methionine  IV) Archaea have linear chromosomes while bacteria have circular chromosomes  

text[[115, 267, 259, 285]]
ANSWER: II, III  

sub_title[[466, 286, 530, 304]]
## Bonus  

text[[115, 306, 881, 341]]
13) Biology - Short Answer: Identify all of the following bacteria that you would expect to stain red in a traditional Gram test:  

text[[172, 359, 380, 428]]
I) Vibrio cholerae  II) Staphylococcus aureus  III) Bacillus anthracis  IV) Helicobacter pylori  

text[[115, 446, 253, 464]]
ANSWER: I, IV  

sub_title[[463, 483, 533, 501]]
## Tossup  

text[[115, 502, 881, 537]]
14) Physics - Short Answer: If a refrigerator has a thermodynamic efficiency of \(88\%\) , then what is its coefficient of performance to the nearest whole number?  

text[[115, 554, 225, 572]]
ANSWER: 8  

sub_title[[466, 594, 530, 612]]
## Bonus  

text[[115, 614, 792, 649]]
14) Physics - Short Answer: Identify all of the following 4 real processes that can be approximated as isobaric:  

text[[172, 667, 656, 737]]
I) Combustion in an open container  II) Slow heating of a gas-filled balloon  III) Combustion in a closed container  IV) Evaporation of water vapor in a vacuum sealed container  

text[[115, 755, 274, 772]]
ANSWER: I and IIsub_title[[464, 92, 533, 110]]
## Tossup  

text[[115, 111, 864, 181]]
15) Energy - Short Answer: The Department of Energy is working with researchers at the Desert Research Institute to study the effects of erosion and deposition on the landscape. In the context of deposition, what term describes the maximum angle that sediment can be piled at relative to the horizontal before it begins to slip?  

text[[115, 198, 347, 216]]
ANSWER: Angle of Repose  

sub_title[[466, 238, 530, 256]]
## Bonus  

text[[115, 257, 871, 327]]
15) Energy - Short Answer: Researchers at Pacific Northwest National lab are studying cell signaling pathways in yeast cells. Yeast are known to produce two distinct types of gametes that secrete distinct mating signals. What are the two kinds of yeast gametes that merge to form a new yeast organism?  

text[[115, 344, 428, 363]]
ANSWER: a, \(\alpha\) (READ: a, alpha) cells  

sub_title[[464, 420, 533, 439]]
## Tossup  

text[[115, 439, 861, 509]]
16) Chemistry - Short Answer: Nikhil is investigating the bonding inside a metal-containing salt he has produced. He determines that the type of bonding he is observing mostly appears in quadruple bonds between metals with low metallic character and contains two nodal planes. What type of bonding is he observing?  

text[[115, 526, 328, 544]]
ANSWER: Delta bonding  

sub_title[[466, 564, 530, 582]]
## Bonus  

text[[115, 583, 842, 636]]
16) Chemistry - Multiple Choice: Mr. Condit forgot what sodium salt he dissolved in a solution! In order to figure out what anion is present, he first adds a little acid, causing the solution to bubble, producing a colorless, pungent gas. What sodium salt is this likely to be?  

text[[172, 652, 277, 724]]
W) \(\mathrm{NaHCO_3}\) X) \(\mathrm{Na_2CO_3}\) Y) \(\mathrm{Na_2SO_3}\) Z) \(\mathrm{NaNO_3}\)  

text[[115, 741, 301, 759]]
ANSWER: Y) \(\mathrm{Na_2SO_3}\)sub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 857, 145]]
17) Physics - Multiple Choice: Which of the following statements is not true of electric field lines?  

text[[172, 164, 827, 235]]
W) They cannot cross 
X) They are parallel to equipotential lines 
Y) They point away from positive charges and towards negative charges 
Z) They show the path a positively charged particle would follow through the field  

text[[115, 252, 544, 270]]
ANSWER: X) They are parallel to equipotential lines  

sub_title[[466, 291, 530, 309]]
## Bonus  

text[[115, 311, 877, 363]]
17) Physics - Short Answer: Consider a setup of point charges on the X axis, with a 2 Coulomb charge at \(\mathbf{x} = 0\) , a -1 Coulomb charge at \(\mathbf{x} = -2\) , and a 1 Coulomb charge at \(\mathbf{x} = 1\) . How many points are there on the X axis where the electric field is 0?  

text[[115, 380, 225, 398]]
ANSWER: 2  

sub_title[[463, 435, 533, 454]]
## Tossup  

text[[115, 455, 879, 525]]
18) Biology - Multiple Choice: A certain locus has 3 alleles controlling it, p, q, and r, and the gene is in Hardy-Weinberg equilibrium. If the allele frequency of p is 0.2, the allele frequency of q is 0.3, and the allele frequency of r is 0.5, what is the frequency of heterozygotes in the population?  

text[[172, 543, 250, 612]]
W) 0.015 
X) 0.03 
Y) 0.31 
Z) 0.62  

text[[115, 630, 273, 648]]
ANSWER: Z) 0.62  

sub_title[[466, 668, 530, 686]]
## Bonus  

text[[115, 688, 881, 757]]
18) Biology - Multiple Choice: You are an aspiring botanist studying an unknown plant's cell samples in the lab. You observe a cross sectional tissue sample that has a central star of vascular tissue surrounded by circles of ground tissue. Which of the following best describes the plant and tissue sample, respectively?  

text[[172, 775, 380, 845]]
W) Monocot root sample 
X) Eudicot root sample 
Y) Monocot shoot sample 
Z) Eudicot shoot sample  

text[[115, 863, 399, 880]]
ANSWER: X) Eudicot root samplesub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 866, 146]]
19) Math - Short Answer: How many times between x equals 0 and x equals 6pi do the graphs \(\sin (x)\) and \(\sec (x)\) intersect?  

text[[115, 181, 222, 199]]
ANSWER: 0  

sub_title[[466, 219, 530, 237]]
## Bonus  

text[[115, 238, 883, 273]]
19) Math - Short Answer: What is the value of the summation from n equals 0 to infinity of 2 to the power of n divided by n factorial? Express your answer to the nearest whole number.  

text[[115, 290, 225, 308]]
ANSWER: 7  

sub_title[[463, 348, 533, 366]]
## Tossup  

text[[115, 367, 860, 401]]
20) Earth and Space - Multiple Choice: Which of the following will not radiate gravitational waves?  

text[[172, 419, 576, 492]]
W) A perfectly symmetrical planet orbiting the sun 
X) An asymmetrical planet orbiting the sun 
Y) A perfectly symmetrical supernova explosion 
Z) An asymmetrical supernova explosion  

text[[115, 508, 590, 527]]
ANSWER: Y) A perfectly symmetrical supernova explosion  

sub_title[[466, 546, 530, 563]]
## Bonus  

text[[115, 565, 860, 600]]
20) Earth and Space - Short Answer: In the first step of the proton-proton chain, two protons combine to form deuterium and release what two leptons?  

text[[115, 635, 455, 653]]
ANSWER: Positron and Electron Neutrinosub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 872, 145]]
21) Earth and Space – Multiple Choice: Which of the following best describes the direction of foliation in mylonites at a strike slip fault?  

text[[172, 163, 559, 180]]
W) Foliation occurs normal to the primary stress  

text[[172, 181, 560, 198]]
X) Foliation occurs normal to the strike direction  

text[[172, 199, 545, 215]]
Y) Foliation occurs normal to the dip direction  

text[[115, 216, 808, 250]]
Z) Foliation is observed normal to a vector between the primary stress and strike direction  

text[[129, 268, 238, 285]]
ANSWER: Z  

sub_title[[466, 286, 530, 303]]
## Bonus  

text[[115, 306, 880, 340]]
21) Earth and Space – Multiple Choice: Which of the following rocks is incorrectly paired with its texture and maficity?  

text[[172, 358, 512, 430]]
W) Dacite: glassy and felsic  
X) Tachylite [tacky-lite]: glassy and mafic  
Y) Pumice: glassy and felsic  
Z) Scoria: glassy and mafic  

text[[115, 445, 432, 463]]
ANSWER: W) Dacite: glassy and felsic  

sub_title[[463, 482, 533, 500]]
## Tossup  

text[[115, 501, 844, 535]]
22) Chemistry – Short Answer: Nitrogen dioxide reacts with water to undergo what type of reaction, involving the transfer of electrons from one nitrogen dioxide unit to another?  

text[[115, 553, 564, 571]]
ANSWER: Disproportionation (ACCEPT: Dismutation)  

sub_title[[466, 590, 530, 608]]
## Bonus  

text[[115, 609, 881, 662]]
22) Chemistry – Multiple Choice: Colin decides to create a 1 Molar solution of sulfuric acid. He finds a 12 Molar stock solution in his chemical cabinet and pours distilled water into it to form a 1 Molar solution. Which of the following best explains why this is incredibly unsafe?  

text[[172, 680, 881, 786]]
W) Concentrated sulfuric acid produces toxic sulfur dioxide when diluted  
X) Sulfuric acid's pH becomes lower the more you dilute it, forming a solution with an extremely acidic pH  
Y) Sulfuric acid's dilution is exothermic, and directly adding water can cause it to splatter  
Z) Sulfuric acid's dilution is endothermic, and directly diluting it can cause serious frostbite to fingers touching the container  

text[[115, 804, 228, 820]]
ANSWER: Ysub_title[[463, 92, 533, 110]]
## Tossup  

text[[113, 111, 870, 147]]
23) Earth and Space – Multiple Choice: Which of the following is closest to the average angle of repose for the volcanic tephra?  

text[[172, 164, 288, 235]]
W) 5 degrees  X) 15 degrees  Y) 30 degrees  Z) 45 degrees  

text[[115, 253, 315, 271]]
ANSWER Y) 30 degrees  

sub_title[[466, 290, 530, 307]]
## Bonus  

text[[115, 308, 795, 344]]
23) Earth and Space - Multiple Choice: Which of the following forms of sulfur is not commonly found in naturally occurring mineral assemblages  

text[[172, 360, 340, 432]]
W) Elemental Sulfur  X) Sulfide  Y) Sulfite  Z) Sulfate  

text[[115, 450, 288, 468]]
ANSWER: Y) Sulfite