
## Tossup  


1) Chemistry – Short Answer: Identify all of the following 4 coordinate geometries that are correctly paired with their coordination numbers:  


I) Octahedral and 8 
II) Tetrahedral and 3 
III) Trigonal bipyramidal and 3 
IV) Square pyramidal and 4  


ANSWER: None  


## Bonus  


1) Chemistry – Short Answer: Identify all of the following four coordinate geometries that are correctly paired with the type of hybridization around the central ion:  


I) Tetrahedral and \(\mathrm{sp}^{3}\) II) Octahedral and \(\mathrm{d}^{3}\mathrm{s}^{3}\) III) Square planar and \(\mathrm{dsp}^{2}\) IV) Linear and \(\mathrm{sp}^{2}\)  


ANSWER: I and III  


## Tossup  


2) Math – Short Answer: What is the area of the region in the xy plane corresponding to the domain of the function \(\mathrm{f(x, y) = sqrt(1 - x^{2} - y^{2})}\) ?  


ANSWER: pi  


## Bonus  


2) Math – Short Answer: Regular hexagon ABCDEF has a side length of 6. What is the ratio of the length of AC to the length of AD?  


ANSWER: sqrt(3)/2
## Tossup  


3) Biology – Short Answer: Identify all of the following 4 polysaccharides that are incorrectly matched with their type of glycosidic (gly-ko-si-dic) linkage  


I) Sucrose: 1,2 glycosidic linkage  
II) Lactose: Beta 1,4 glycosidic linkage  
III) Amylopectin: 1,4 glycosidic linkage with 1,2 branching points  
IV) Glycogen: 1,4 glycosidic linkage with 1,6 branching points  


ANSWER: III only  


## Bonus  


3) Biology – Multiple Choice: A competitive inhibitor does NOT change what aspect of a reaction’s progress, described by Michaelis-Menten kinetics?  


W) Vmax X) Km Y) Vo Z) Ea  


ANSWER: W) Vmax  


## Tossup  


4) Physics – Short Answer: In Lagrangian mechanics, what principle replaces Newton’s F=ma?  


ANSWER: Principle of Stationary Action (ACCEPT: Principle of Least Action)  


## Bonus  


#) Physics – Short Answer: A charged particle is placed in a constant electric field and moved in a figure 8 pattern. Identify all of the following 3 statements that are true of this process:  


I) The total work done is zero  
II) The total distance moved is zero  
III) The integral of the electric force over the path is nonzero  


ANSWER: I only
## Tossup  


5) Math - Short Answer: The two legs of a right triangle are equal to the roots of the polynomial \(\mathrm{x}^2 - 15\mathrm{x} + 48\) [READ: x squared minus 15 x plus 48]. What is the area of the triangle?  


ANSWER: 24  


## Bonus  


5) Math - Short Answer: What is the average of all the possible areas of a triangle ABC with angle \(\mathrm{A} = 60\) degrees, side \(\mathrm{b} = 9\) , and side \(\mathrm{a} = 8.6\) ?  


ANSWER: \(81\sqrt{3} /8\)  


## Tossup  


6) Energy - Multiple Choice: Researchers at the University of Oxford are studying the effects of Solar winds on the isotopic composition of asteroids. Which of the following types of asteroids are considered to be the oldest in the solar system?  


W) Chondrite 
X) Stony 
Y) Metallic 
Z) Carbonaceous  


ANSWER: W) Chondrite  


## Bonus  


6) Energy - Short Answer: Researchers at the National Ignition Facility at Lawrence Livermore National Lab are studying a proposed high pressure phase transformation in diamond under laser shock. Order the following allotropes of carbon from least to greatest stability at ambient conditions.  


1) Graphite 
2) Buckminsterfullerene 
3) Diamond 
4) Bc8  


ANSWER: 4,2,3,1
## Tossup  


7) Biology – Short Answer: Recognition of sound at different parts inside the cochlea allows us to distinguish what characteristic of sound waves?  


ANSWER: Pitch (ACCEPT: frequency or other equivalent answers)  


## Bonus  


7) Biology – Short Answer: Identify all of the following 4 genetic disorders that follow an X-linked recessive inheritance pattern:  


I) Marfan syndrome  II) Red green color blindness  III) Phenylketonuria [feen-il-kee-to-nur-i-a]  IV) Tay Sachs disease  


ANSWER: II only  


## Tossup  


8) Earth and Space – Short Answer: Which of the following statements is NOT true about Pluto?  


W) It is in a 3 to 2 orbital resonance with Neptune  X) It undergoes prograde rotation  Y) Its ice is made up of primarily methane  Z) It rotates over 10,000 times in one orbit around the sun  


ANSWER: X) It undergoes prograde rotation  


## Bonus  


8) Earth and Space – Short Answer: Order the following three satellites of Jupiter in increasing albedo.  


1) Ganymede  
2) Europa  
3) Callisto  


ANSWER: 3, 1, 2
## Tossup  


9) Math - Short Answer: Your school has between 40 and 80 students. If classes are formed with size 7, there are 6 students left over. If classes are formed with size 9, there are 8 students left over. How many people are in the school?  


ANSWER: 62  


## Bonus  


9) Math - Short Answer: Pranav buys an old collection of manga, hoping that some of them will turn out to be valuable. If a manga is valuable, its value doubles every 5 years, and if it is not, its value halves every 5 years. If he buys a collection of 300 manga for \(5 each and 20\%\) of them are valuable, what is the expected value of the collection after 15 years?  


ANSWER: \(\) 2550\$  


## Bonus  


10) Energy - Short Answer: Scientists at Fermilab National Accelerator Laboratory are studying the decay of subatomic particles, such as muons. Identify all of the following 3 statements that are true about theories that predict proton decay:  


I) SU(5) Grand Unified Theory is one such theory. II) These theories predict a proton decaying into a positron and an antineutrino. III) The simplest of these theories have been experimentally disproven.  


ANSWER: I and III  


## Tossup  


10) Energy - Short Answer: Scientists at Lawrence Berkeley National Laboratory are studying atomic nuclei and nuclear decay. What term describes the radiation emitted by an electron emitted from a nuclear reactor as it moves faster than the speed of light in the medium?  


ANSWER: Cherenkov radiation
## Tossup  


11) Physics – Short Answer: A soap bubble is created in a \(3 \mathrm{m}\) by \(5 \mathrm{m}\) rectangular wire frame. If the force from the liquid on one of the longer sides is \(15 \mathrm{N}\) , what is the force on one of the shorter sides?  


ANSWER: 9 N  


## Bonus  


11) Physics – Multiple Choice: Consider a mass M moving at velocity u inside reference frame S. Reference frame S is moving at velocity v with respect to the observer. If \(\mathrm{K}_{\mathrm{u}}\) [READ: K sub u] is equal to \(\frac{1}{2} \mathrm{Mu}^2\) [READ: one half M u squared] and \(\mathrm{K}_{\mathrm{v}}\) [READ: K sub v] is equal to \(\frac{1}{2} \mathrm{Mv}^2\) [READ: one half M v squared], which of the following conditions must be true if the kinetic energy of mass M with respect to the observer is equal to \(\mathrm{K}_{\mathrm{u}} + \mathrm{K}_{\mathrm{v}}\) ?  


W) Velocity u is perpendicular to velocity v 
X) Velocity u is parallel to velocity v 
Y) The magnitude of velocity u is equal to the magnitude of velocity v 
Z) Velocity u and velocity v point in opposite directions  


ANSWER: W) Velocity u is perpendicular to velocity v  


## Tossup  


12) Chemistry – Short Answer: Seth Landesman is developing new beard care products, specifically with beard gels. What intermolecular force is most important to the gel's ability to keep long strands of hair stuck together?  


ANSWER: Dispersion (ACCEPT: London dispersion)  


## Bonus  


12) Chemistry – Short Answer: Identify all of the following four compounds that act as electrophiles:  


I) BH3 
II) NaOH 
III) HCOOH  


ANSWER: I, III
## Tossup  


13) Biology - Short Answer: Identify all of the following 4 statements that correctly describe characteristics of bacteria and archaea  


I) Bacterial flagella and archaean flagella are homologous  II) Archaean [arc-ay-an] cell walls lack peptidoglycan [pep-tid-o-gly-can]  III) Archaea use methionine [meth-i-o-neen] as their starting amino acid while bacteria use formyl-methionine  IV) Archaea have linear chromosomes while bacteria have circular chromosomes  


ANSWER: II, III  


## Bonus  


13) Biology - Short Answer: Identify all of the following bacteria that you would expect to stain red in a traditional Gram test:  


I) Vibrio cholerae  II) Staphylococcus aureus  III) Bacillus anthracis  IV) Helicobacter pylori  


ANSWER: I, IV  


## Tossup  


14) Physics - Short Answer: If a refrigerator has a thermodynamic efficiency of \(88\%\) , then what is its coefficient of performance to the nearest whole number?  


ANSWER: 8  


## Bonus  


14) Physics - Short Answer: Identify all of the following 4 real processes that can be approximated as isobaric:  


I) Combustion in an open container  II) Slow heating of a gas-filled balloon  III) Combustion in a closed container  IV) Evaporation of water vapor in a vacuum sealed container  


ANSWER: I and II
## Tossup  


15) Energy - Short Answer: The Department of Energy is working with researchers at the Desert Research Institute to study the effects of erosion and deposition on the landscape. In the context of deposition, what term describes the maximum angle that sediment can be piled at relative to the horizontal before it begins to slip?  


ANSWER: Angle of Repose  


## Bonus  


15) Energy - Short Answer: Researchers at Pacific Northwest National lab are studying cell signaling pathways in yeast cells. Yeast are known to produce two distinct types of gametes that secrete distinct mating signals. What are the two kinds of yeast gametes that merge to form a new yeast organism?  


ANSWER: a, \(\alpha\) (READ: a, alpha) cells  


## Tossup  


16) Chemistry - Short Answer: Nikhil is investigating the bonding inside a metal-containing salt he has produced. He determines that the type of bonding he is observing mostly appears in quadruple bonds between metals with low metallic character and contains two nodal planes. What type of bonding is he observing?  


ANSWER: Delta bonding  


## Bonus  


16) Chemistry - Multiple Choice: Mr. Condit forgot what sodium salt he dissolved in a solution! In order to figure out what anion is present, he first adds a little acid, causing the solution to bubble, producing a colorless, pungent gas. What sodium salt is this likely to be?  


W) \(\mathrm{NaHCO_3}\) X) \(\mathrm{Na_2CO_3}\) Y) \(\mathrm{Na_2SO_3}\) Z) \(\mathrm{NaNO_3}\)  


ANSWER: Y) \(\mathrm{Na_2SO_3}\)
## Tossup  


17) Physics - Multiple Choice: Which of the following statements is not true of electric field lines?  


W) They cannot cross 
X) They are parallel to equipotential lines 
Y) They point away from positive charges and towards negative charges 
Z) They show the path a positively charged particle would follow through the field  


ANSWER: X) They are parallel to equipotential lines  


## Bonus  


17) Physics - Short Answer: Consider a setup of point charges on the X axis, with a 2 Coulomb charge at \(\mathbf{x} = 0\) , a -1 Coulomb charge at \(\mathbf{x} = -2\) , and a 1 Coulomb charge at \(\mathbf{x} = 1\) . How many points are there on the X axis where the electric field is 0?  


ANSWER: 2  


## Tossup  


18) Biology - Multiple Choice: A certain locus has 3 alleles controlling it, p, q, and r, and the gene is in Hardy-Weinberg equilibrium. If the allele frequency of p is 0.2, the allele frequency of q is 0.3, and the allele frequency of r is 0.5, what is the frequency of heterozygotes in the population?  


W) 0.015 
X) 0.03 
Y) 0.31 
Z) 0.62  


ANSWER: Z) 0.62  


## Bonus  


18) Biology - Multiple Choice: You are an aspiring botanist studying an unknown plant's cell samples in the lab. You observe a cross sectional tissue sample that has a central star of vascular tissue surrounded by circles of ground tissue. Which of the following best describes the plant and tissue sample, respectively?  


W) Monocot root sample 
X) Eudicot root sample 
Y) Monocot shoot sample 
Z) Eudicot shoot sample  


ANSWER: X) Eudicot root sample
## Tossup  


19) Math - Short Answer: How many times between x equals 0 and x equals 6pi do the graphs \(\sin (x)\) and \(\sec (x)\) intersect?  


ANSWER: 0  


## Bonus  


19) Math - Short Answer: What is the value of the summation from n equals 0 to infinity of 2 to the power of n divided by n factorial? Express your answer to the nearest whole number.  


ANSWER: 7  


## Tossup  


20) Earth and Space - Multiple Choice: Which of the following will not radiate gravitational waves?  


W) A perfectly symmetrical planet orbiting the sun 
X) An asymmetrical planet orbiting the sun 
Y) A perfectly symmetrical supernova explosion 
Z) An asymmetrical supernova explosion  


ANSWER: Y) A perfectly symmetrical supernova explosion  


## Bonus  


20) Earth and Space - Short Answer: In the first step of the proton-proton chain, two protons combine to form deuterium and release what two leptons?  


ANSWER: Positron and Electron Neutrino
## Tossup  


21) Earth and Space – Multiple Choice: Which of the following best describes the direction of foliation in mylonites at a strike slip fault?  


W) Foliation occurs normal to the primary stress  


X) Foliation occurs normal to the strike direction  


Y) Foliation occurs normal to the dip direction  


Z) Foliation is observed normal to a vector between the primary stress and strike direction  


ANSWER: Z  


## Bonus  


21) Earth and Space – Multiple Choice: Which of the following rocks is incorrectly paired with its texture and maficity?  


W) Dacite: glassy and felsic  
X) Tachylite [tacky-lite]: glassy and mafic  
Y) Pumice: glassy and felsic  
Z) Scoria: glassy and mafic  


ANSWER: W) Dacite: glassy and felsic  


## Tossup  


22) Chemistry – Short Answer: Nitrogen dioxide reacts with water to undergo what type of reaction, involving the transfer of electrons from one nitrogen dioxide unit to another?  


ANSWER: Disproportionation (ACCEPT: Dismutation)  


## Bonus  


22) Chemistry – Multiple Choice: Colin decides to create a 1 Molar solution of sulfuric acid. He finds a 12 Molar stock solution in his chemical cabinet and pours distilled water into it to form a 1 Molar solution. Which of the following best explains why this is incredibly unsafe?  


W) Concentrated sulfuric acid produces toxic sulfur dioxide when diluted  
X) Sulfuric acid's pH becomes lower the more you dilute it, forming a solution with an extremely acidic pH  
Y) Sulfuric acid's dilution is exothermic, and directly adding water can cause it to splatter  
Z) Sulfuric acid's dilution is endothermic, and directly diluting it can cause serious frostbite to fingers touching the container  


ANSWER: Y
## Tossup  


23) Earth and Space – Multiple Choice: Which of the following is closest to the average angle of repose for the volcanic tephra?  


W) 5 degrees  X) 15 degrees  Y) 30 degrees  Z) 45 degrees  


ANSWER Y) 30 degrees  


## Bonus  


23) Earth and Space - Multiple Choice: Which of the following forms of sulfur is not commonly found in naturally occurring mineral assemblages  


W) Elemental Sulfur  X) Sulfide  Y) Sulfite  Z) Sulfate  


ANSWER: Y) Sulfite