
## Tossup  


1) Chemistry – Multiple Choice: Which of the following ions is not in a stable oxidation state?  


W) Sc4+ 
X) Ti3+ 
Y) V5+ 
Z) Cr6+  


ANSWER: W) Sc4+  


## Bonus  


1) Chemistry – Short Answer: Identify all of the following 3 properties that are generally higher in hard acids or bases than soft ones:  


I) Ionic radius II) Polarizability III) Ionic character  


ANSWER: III  


## Tossup  


2) Physics – Multiple Choice: Nikhil is riding on a carousel when he suddenly spots an organic reaction taking place with 73% yield. He jumps inwards in shock, moving directly towards the center of the carousel (but not reaching it). When he lands on the ground, where is he on the carousel relative to the horse he was riding?  


W) He is besides and ahead of the horse. 
X) He is directly besides the horse but not ahead of or behind it. 
Y) He is besides and behind the horse. 
Z) The answer depends on the hemisphere he is in.  


ANSWER: W  


## Bonus  


2) Physics – Short Answer: Order the following four subatomic particles from least to greatest charge:  


1) Tau lepton 
2) Charm quark 
3) Down quark 
4) \(\mathrm{Pi}^{0}\) [READ: Pi 0] meson  


ANSWER: 1, 3, 4, 2
## Tossup  


3) Energy – Short Answer: Researchers at Pacific Northwest National Laboratory are studying the transport of information in quantum computers at ultra-low temperatures. What quasiparticle, which represents the vibration of a lattice of atoms or molecules, transports information in these quantum computers?  


ANSWER: Phonon  


## Bonus  


3) Energy – Multiple Choice: Researchers at Lawrence Berkeley National Lab are studying methods to increase the efficiency of cracking, or refining crude oil to specific petroleum products. Which of the following processes does cracking use the most?  


W) Simple distillation 
X) Destructive distillation 
Y) Osmotic distillation 
Z) Azeotropic distillation  


ANSWER: X) Destructive distillation  


## Tossup  


4) Math – Short Answer: Let a, b, and c be real numbers such that a+b+c=11. What is the minimum value of a²+b²+c²?  


ANSWER: 121/3  


## Bonus  


4) Math – Short Answer: Nikhil is playing Genshin Impact. He is trying to get the 5 star character Ayaka. Every time Nikhil gets a five star, there is a 50% chance that it will be Ayaka. However, if he loses this 50% chance, then his next five star is guaranteed to be Ayaka. Given that he is expected to pull a five star approximately every 67 pulls, then to the nearest integer, what is the expected number of pulls he must do to get Ayaka?  


ANSWER: 101
## Tossup  


5) Physics – Multiple Choice: Which of the following thermodynamic processes does the most work for a given increase in volume?  


W) Adiabatic 
X) Isentropic 
Y) Isobaric 
Z) Isothermal  


ANSWER: Y  


## Bonus  


5) Physics – Short Answer: An ideal gas starts out at a volume of \(12 \mathrm{~m}^3\) and a pressure of 7 Pascals. The gas is kept at a constant temperature, and its volume changes to \(24 \mathrm{~m}^3\) . What is the work done by the gas on its environment?  


ANSWER: 84 ln(2)  


## Tossup  


6) Biology – Short Answer: Rishabh is conducting an experiment involving the plasma membrane of normal and apoptotic human skin cells. He fluorescently labels an unknown part of the membrane, molecule X, and finds it primarily located on the inner leaflet of the normal cells and outer leaflet of apoptotic cells. What is the most likely identity of molecule X?  


ANSWER: Phosphatidylserine [foss- fa- tee- dil- say- reene]  


## Bonus  


6) Biology – Short Answer: Order the following \(4 5^{\circ} - 3^{\circ}\) (READ: 5 prime to 3 prime) sequences of 10 base pairs in increasing likelihood of their usage as a primer in PCR:  


1) AATGGCAA TA 
2) GCATAGG TTA 
3) AATATATTAA 
4) TAGGCAGGAT  


ANSWER: 3, 1, 2, 4
## Tossup  


7) Chemistry - Short Answer: What is the name of the base induced reaction in which an aldehyde undergoes a disproportionation which results in a carboxylic acid and a primary alcohol?  


ANSWER: Cannizaro reaction  


## Bonus  


7) Chemistry - Short Answer: A solution contains 0.2 Molar malic acid and 0.4 Molar malate. If the \(\mathrm{pK_b}\) of malate is 10.6, what is the pH of the solution to the nearest tenth?  


ANSWER: 3.7  


## Tossup  


8) Energy - Short Answer: Scientists at Princeton Plasma Physics Laboratory are studying transport processes of plasma in fusion devices. One type of transport process they are studying is turbulent transport. What number associated with a fluid predicts whether the fluid will undergo laminar or turbulent flow?  


ANSWER: Reynold's number  


## Bonus  


8) Energy - Short Answer: Researchers at Sandia National Laboratories are studying ways to make electrical circuits more efficient. One way to simulate circuits is with their Thevenin equivalent circuits, which are composed of an ideal voltage source and a resistor in series. If a circuit's V-I graph has the equation \(\mathrm{V} = 3\mathrm{I} + 4\) , what is the Thevenin voltage and Thevenin resistance of this circuit, respectively?  


ANSWER: Voltage is 4, resistance is 3
## Tossup  


9) Earth and Space – Multiple Choice: Which of the following, in degrees Celsius, is closest to the coldest temperature in which a liquid water droplet can remain metastable given the timescales of precipitation?  


W) 4 
X) 0 
Y) -10 
Z) -40  


ANSWER: Z) - 40  


## Bonus  


9) Earth and Space – Short Answer: Identify all of the following types of precipitation which could form from the Bergeron process.  


I) Rime 
II) Rain 
III) Sleet 
IV) Snow  


ANSWER: II, III, and IV  


## Tossup  


10) Chemistry – Short Answer: What term, often used to describe metal alloys, refers to a solution where the melting point of the solution is less than any of its components?  


ANSWER: Eutectic  


## Bonus  


10) Chemistry – Multiple Choice: In the electrophilic aromatic substitution of benzene, which of the following species acts as the electrophile?  


W) Delocalized pi electrons on the ring 
X) A Carbon-Hydrogen sigma bond 
Y) The species substituted onto the ring 
Z) The hydrogen removed from the ring  


ANSWER: Y) The species substituted onto the ring
## Tossup  


11) Math - Multiple Choice: What is the integral from -3 to 6 of \(-1 / x^{2} \mathrm{~d} \mathrm{x}?\)  


W) - 1/6  
X) 1/6  
Y) 1/2  
Z) The integral is divergent  


ANSWER: Z  


## Bonus  


11) Math - Short Answer: What is the sum of the coefficients of the result when dividing \(x^{3} - 4x^{2} - 11x + 30\) by \((x - 2)\) ?  


ANSWER: - 16  


## Tossup  


12) Biology - Short Answer: In what part of a bone are osteoblasts most active?  


ANSWER: Periosteum  


## Bonus  


12) Bonus - Short Answer: Which of the following 3 plant embryonic tissues is correctly matched to the mature structures it forms:  


I) Procambium - sieve tube elements  
II) Protoderm - cortex  
III) Ground meristem - parenchyma [pair-in-kim-uh]  


ANSWER: I, III
## Tossup  


13) Physics - Short Answer: Identify all of the following 4 particles that follow the Pauli Exclusion Principle  


I) Gluon II) Tau Neutrino III) Up quark IV) Graviton  


ANSWER: II and III  


## Bonus  


13) Physics - Short Answer: To the nearest second, how long will it take a non-uniform 8 kilogram cylinder with moment of inertia \(\frac{1}{3} \mathrm{MR}^2\) [READ: one third M R squared] to roll down a 75 meter long plane inclined at 29 degrees to the horizontal?  


ANSWER: 6  


## Tossup  


14) Math - Short Answer: Colin, being excited for ESBOT, decides to dress to represent Enloe Science Bowl every day until the competition by wearing at least one piece of Science Bowl clothing each day. If Colin has two Science Bowl shirts and three other shirts, one pair of Science Bowl pants and four other pairs of pants, and three pairs of Science Bowl socks and five other pairs of socks, how many possible outfits can Colin choose from?  


ANSWER: 140  


## Bonus  


14) Math - Short Answer: Rishabh has an infinitely long barn, and he wants to fence off an a unit by b unit enclosure on the side, where the sides with length b are perpendicular to the side of the barn. He has 36 units of fencing, and he wants the area of his enclosure to be 144 square units. What are all the possible values of (a, b) that satisfy this condition?  


ANSWER: (24, 6) and (12, 12)
## Tossup  


15) Chemistry – Short Answer: What interaction explains why proton NMR shift of alcohol hydrogens is easily affected by factors like acidity, temperature, and solvation?  


ANSWER: Hydrogen bonding  


## Bonus  


15) Chemistry – Short Answer: Abhinav is performing a calorimetry experiment to determine the amount of heat released in the combustion of pentanol. Identify all of the following 3 errors that would lead to a calculated value that is lower than the actual value:  


I) The alcohol was not dry  
II) Some heat was lost to the surroundings through the container  
III) The thermometer used to measure the start and end temperatures was incorrectly calibrated  


ANSWER: I and II  


## Tossup  


16) Earth and Space – Multiple Choice: Approximately what percentage of the total mass of the asteroid belt is accounted for by Ceres?  


W) \(2\%\) X) \(4\%\) Y) \(20\%\) Z) \(40\%\)  


ANSWER: Z  


## Tossup  


16) Earth and Space – Multiple Choice: Order the following four bodies in order of increasing volume.  


1) Mercury  
2) Ceres  
3) Ganymede  
4) Vesta  


ANSWER: 4,2,1,3
## Tossup  


17) Biology - Multiple Choice: In a western blot, what is the purpose of the secondary antibody?  


W) To bind to the N terminus  X) To bind to the C terminus  Y) To bind to hydrophobic pockets  Z) To bind to the primary antibody  


ANSWER: Z) To bind to the primary antibody  


## Bonus  


17) Biology - Short Answer: Which of the following 4 experiments is correctly matched to the breakthrough it produced?  


1) Hershey-Chase - DNA is the hereditary material  
2) Griffith - molecular origins of life on earth  
3) Miller-Urey - horizontal gene transfer in bacteria  
4) Meselson-Stahl - discovery of transcription  


ANSWER: 1 only  


## Tossup  


18) Energy - Short Answer: Scientists at Lawrence Berkeley National Laboratory are studying C4 plant photosynthesis. What organic molecule is used in C4 photosynthesis to carry fixed carbons from bundle sheath cells to mesophyll cells  


ANSWER: malate (ACCEPT: malic acid)  


## Bonus  


18) Energy - Short Answer: Oak Ridge National Lab is investigating the origins of life on Earth, specifically the racemic imbalance of amino acids and sugars. Notably, only L-amino acids are encoded in proteins, and only D-sugars are used as backbones in nucleic acids. What is this uniformity of chirality called?  


ANSWER: Homochirality
## Tossup  


19) Math - Short Answer: Compute the largest integer N less than or equal to 2022 with 4 distinct digits and divisible by 11.  


ANSWER: 2013  


## Bonus  


19) Math - Short Answer: Thanush has a rectangle whose sides are positive integers. When he increases the length by 1 unit and decreases the width by 1 unit, the area increases by x units. Find the minimum possible value of x.  


ANSWER: 1 (length = 1, width = 3)  


## Tossup  


20) Earth and Space - Multiple Choice: Order the following 4 layers of the mantle by increasing P-Wave velocity:  


1) Low Velocity Zone 
2) D" [D prime prime] layer 
3) Lithospheric Mantle  


ANSWER: 1, 3, 2  


## Bonus  


20) Earth and Space - Multiple Choice: Which of the following types of stress is the primary contributor to the formation of basin and range provinces?  


W) Tension 
X) Compression 
Y) Shear 
Z) Transverse  


ANSWER: W) Tension
## Tossup  


21) Physics - Multiple Choice: Consider two permanent magnets dropped from a height h. The one on the left is dropped normally and travels through the air, while the one on the right is dropped through the middle of a nonmagnetic conducting metal tube. Which of the following choices best describes the motion of the two magnets?  


W) The magnet on the left will hit the ground after the magnet on the right 
X) The magnet on the left will hit the ground before the magnet on the right 
Y) The two magnets will hit the ground at the same time 
Z) The behavior depends on the exact properties of the tube  


ANSWER: X) The magnet on the left will hit the ground before the magnet on the right  


## Bonus  


21) Physics - Multiple Choice: A circuit is constructed out of an ideal voltage source and two resistors, A and B. Which of the following conditions would maximize the power dissipated through resistor B?  


W) Resistance B is less than Resistance A 
X) Resistance B is equal to Resistance A 
Y) Resistance B is greater than Resistance A 
Z) Resistance B is equal to 0  


ANSWER: X) Resistance B is equal to Resistance A  


## Tossup  


22) Biology - Short Answer: In protostomes, what structure develops into the mouth?  


ANSWER: Archertoner (ACCEPT: blastopore)  


## Bonus  


22) Biology - Multiple Choice: In the kingdom of the Lion King, Scar's tribe of lions are pushed towards the edge of the biome while still staying within it. Over time, Scar's tribe evolves longer manes and more slender body frames. This is best described by what type of speciation  


W) Allopatric 
X) Peripatric 
Y) Parapatric 
Z) Sympatric  


ANSWER: Y) Parapatric
## Tossup  


23) Earth and Space – Multiple Choice: Which of the following best describes why larger stars don’t undergo a helium flash?  


W) They have a convective core  
X) They have a radiative core  
Y) They lack a tachocline [tack- o- cline]  
Z) Their core never becomes degenerate.  


ANSWER: Z) Their core never becomes degenerate.  


## Bonus  


23) Earth and Space – Short Answer: Identify all of the following properties of stars that increase with scale height in the Milky Way galaxy:  


I) Metalicity  
II) Luminosity  
III) Age  


ANSWER: III only