sub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 861, 146]]
1) Physics – Short Answer: One quark in a meson has a color charge of red. Identity all of the following 3 options are possible color charges for the other quark:  

text[[172, 164, 257, 216]]
I) Red II) Blue III) Green  

text[[115, 234, 258, 252]]
ANSWER: None  

sub_title[[465, 274, 530, 292]]
## Bonus  

text[[115, 294, 867, 364]]
1) Physics – Short Answer: Consider a person standing at the outer edge of a 5 meter diameter disk rotating at 2 radians per second. If the person throws a 50 gram ball towards the center of the disk at 4 meters per second, what is the magnitude of the Coriolis force acting on the ball in the disk's reference frame?  

text[[115, 380, 315, 398]]
ANSWER: 0.4 Newtons  

sub_title[[463, 453, 533, 472]]
## Tossup  

text[[115, 472, 808, 491]]
2) Math – Short Answer: What is the sum of squares of the roots of \(x^{4} - 8x^{3} + 13x^{2} - 5\) ?  

text[[115, 508, 236, 526]]
ANSWER: 38  

sub_title[[465, 544, 530, 562]]
## Bonus  

text[[115, 563, 880, 600]]
2) Math – Short Answer: What is the sum from \(k = 1\) to \(k = 6560\) of \(\log_{3}(1 + 1 / k)\) [READ: log base 3 of open parenthesis one plus one over k close parenthesis].  

text[[115, 616, 226, 634]]
ANSWER: 8sub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 832, 145]]
3) Earth and Space – Short Answer: Identify all of the following 4 factors which promote thunderstorm formation.  

text[[172, 163, 373, 234]]
I) High Turbulence  
II) Atmospheric Stability  
III) Orographic uplift  
IV) Frontal Wedging  

text[[115, 251, 288, 269]]
ANSWER: 1, 3 and 4  

sub_title[[465, 287, 530, 305]]
## Bonus  

text[[115, 306, 879, 341]]
3) Earth and Space – Multiple Choice: Which of the following best describes the calculation of the Southern Oscillation Index?  

text[[172, 358, 810, 431]]
W) The anomaly in average pressure between Tahiti and Australia  
X) The anomaly in average sea surface temperature between Tahiti and Australia  
Y) The anomaly in average pressure between Tahiti and Peru  
Z) The anomaly in average sea surface temperature between Tahiti and Peru  

text[[115, 448, 728, 466]]
ANSWER: W) The anomaly in average pressure between Tahiti and Australia  

sub_title[[463, 523, 533, 541]]
## Tossup  

text[[115, 543, 867, 594]]
4) Energy – Short Answer: Scientists at Fermilab are studying neutrinos. While neutrinos usually interact with both gravity and the weak nuclear force, a proposed type of neutrinos only interacts with gravity. What is the name for these neutrinos, which do not undergo oscillation?  

text[[115, 611, 342, 628]]
ANSWER: Sterile Neutrino  

sub_title[[465, 652, 530, 670]]
## Bonus  

text[[115, 672, 863, 758]]
4) Energy – Short Answer: Scientists at Lawrence Berkeley National Laboratory are studying new models of physics, such as weak scale supersymmetry. They are looking to explain certain properties of the electroweak theory. What property of the electroweak theory states that as energy levels are lowered, the electromagnetic and weak nuclear forces diverge, unlike at high energies where they can be unified into one force?  

text[[115, 776, 727, 794]]
ANSWER: Spontaneous symmetry breaking [ACCEPT: symmetry breaking]sub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 860, 146]]
5) Biology – Multiple Choice: Which of the following best explains the mechanism by which renin directly influences osmoregulation:  

text[[172, 163, 603, 234]]
W) Renin decreases stroke volume and blood pressure  
X) Renin increases stroke volume and blood pressure  
Y) Renin activates angiotensin  
Z) Renin activates aldosterone  

text[[115, 252, 451, 270]]
ANSWER: Y) Renin activates angiotensin  

sub_title[[465, 289, 530, 307]]
## Bonus  

text[[115, 308, 877, 343]]
5) Biology – Short Answer: The mean arterial pressure of a person is 90 mmHg. If their systolic pressure is 100, what is their diastolic pressure?  

text[[115, 360, 235, 377]]
ANSWER: 85  

sub_title[[463, 416, 533, 434]]
## Tossup  

text[[115, 435, 879, 504]]
6) Chemistry – Short Answer: While out camping, Colin is out camping, he finds that he left his favorite bottle of urea open and all the water has evaporated off! He tries to dissolve the solid urea evaporite by adding distilled water but the urea refuses to dissolve. Identify all of the following 3 things that Colin's brother could do to improve the solubility of the urea:  

text[[172, 521, 452, 576]]
I) Add \(\mathrm{Fe}^{3 + }\) ions to form a complex  
II) Add uric acid  
III) Heat the water solvent  

text[[115, 592, 252, 609]]
ANSWER: I, III  

sub_title[[465, 629, 530, 647]]
## Bonus  

text[[115, 648, 879, 736]]
6) Chemistry – Short Answer: After failing to retrieve the urea, Colin looks for and finds a bottle of urea solution of unknown concentration with molar absorptivity of \(4*10^{3}\) Liters per mol centimeter. He brings it back to the lab to measure its absorbance and measures an absorbance of 20 in a 2 centimeter thick sample. In moles per liter, what is the molar concentration of the urea sample?  

text[[115, 753, 292, 771]]
ANSWER: 0.0025 Msub_title[[463, 92, 533, 110]]
## Tossup  

text[[114, 111, 868, 146]]
7) Math - Short Answer: It takes 5 Enloe Science Bowl members 5 days to write 30 questions. How many days will it take for 107 Enloe Science Bowl members to write 642 questions?  

text[[115, 163, 225, 180]]
ANSWER: 5  

sub_title[[466, 203, 530, 221]]
## Bonus  

text[[115, 222, 850, 258]]
7) Math - Short Answer: If E, S, B, O, T are positive integers such that \(\mathrm{E}*\mathrm{S}*\mathrm{B}*\mathrm{O}*\mathrm{T}\) is equal to 2022, then what is the minimum possible value of \(\mathrm{E} + \mathrm{S} + \mathrm{B} + \mathrm{O} + \mathrm{T}\) ?  

text[[115, 275, 245, 293]]
ANSWER: 344  

sub_title[[463, 368, 533, 386]]
## Tossup  

text[[113, 387, 844, 423]]
8) Biology - Short Answer: White muscle derives its energy primarily from what metabolic pathway?  

text[[115, 439, 597, 458]]
ANSWER: Glycolysis (DO NOT ACCEPT: cell respiration)  

sub_title[[466, 477, 530, 495]]
## Bonus  

text[[115, 496, 877, 532]]
8) Biology - Short Answer: Identify all of the following structures in the brain that are correctly matched to the embryonic tissue they are derived from:  

text[[172, 549, 661, 619]]
I) Telencephalon [te-len-sef-alon] - Thalamus  II) Metencephalon [met-en-sef-alon] - Cerebellum  III) Diencephalon [di-en-sef-alon] - Hypothalamus  IV) Myelencephalon [mi-el-en-sef-alon] - Medulla oblongata  

text[[115, 635, 288, 653]]
ANSWER: II, III, IVsub_title[[463, 92, 533, 110]]
## Tossup  

text[[113, 111, 881, 145]]
9) Chemistry – Multiple Choice: Which of the following best describes the purpose of including the prefactor inside the Arrhenius equation?  

text[[172, 163, 714, 234]]
W) To account for changes in temperature  
X) To account for the activation energy of the reaction  
Y) To account for the probability of a successfully oriented collision  
Z) To account for the change in enthalpy of a reaction  

text[[115, 252, 751, 270]]
ANSWER: Y) To account for the probability of a successfully oriented collision  

sub_title[[466, 309, 530, 326]]
## Bonus  

text[[115, 328, 848, 380]]
9) Chemistry – Short Answer: Consider the reaction mechanism \(\mathrm{A} + \mathrm{B}\) goes to \(\mathrm{C} + \mathrm{D}\) in a reversible mechanism, and then \(\mathrm{D} + \mathrm{A}\) forms \(\mathrm{E}\) , the final product. What is the rate law of this reaction, assuming the intermediate \(\mathrm{D}\) is immediately used after production?  

text[[115, 397, 384, 417]]
ANSWER: \(\mathrm{Rate} = \mathrm{k}[\mathrm{A}]^2 [\mathrm{B}] / [\mathrm{C}]\)  

sub_title[[463, 471, 533, 489]]
## Tossup  

text[[115, 490, 877, 525]]
10) Math – Short Answer: It takes 5 Enloe Science Bowl members 5 days to write 30 questions. How many days will it take for 107 Enloe Science Bowl members to write 642 questions?  

text[[115, 542, 225, 559]]
ANSWER: 5  

sub_title[[466, 584, 530, 601]]
## Bonus  

text[[115, 602, 880, 637]]
10) Math – Short Answer: A circle O circumscribes a quadrilateral ABCD. If AB is 9, CD is 21, and BC equals DA equals 10, what is the length of diagonal AC?  

text[[115, 656, 234, 674]]
ANSWER: 17sub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 110, 878, 180]]
11) Physics – Multiple Choice: Thanush and Colin believe that they have discovered a new element named Esbotium. Their measurements indicate that Esbotium has a mass of 332 amu and an atomic number of 140. Which of the following choices best describes why this is possible or not?  

text[[172, 197, 840, 304]]
W) It is possible because there are infinitely many electron energy levels and all 140 electrons can fit within these levels  
X) It is possible because elements with very large nuclei are stable  
Y) It is not possible because the nuclear charge is too great and the electromagnetic repulsion will overcome the strong nuclear force  
Z) It is not possible because the \(n = 1\) electrons will have to exceed the speed of light  

text[[115, 321, 872, 340]]
ANSWER: Z) It is not possible because the \(n = 1\) electrons will have to exceed the speed of light  

sub_title[[466, 360, 530, 378]]
## Bonus  

text[[115, 380, 875, 449]]
11) Physics – Short Answer: Consider a person standing at the outer edge of a 5 meter diameter disk rotating at 2 radians per second. If the person throws a 50 gram ball towards the center of the disk at 4 meters per second, what is the magnitude of the Coriolis force acting on the ball in the disk’s reference frame?  

text[[115, 468, 315, 485]]
ANSWER: 0.4 Newtonssub_title[[464, 92, 533, 110]]
## Tossup  

text[[115, 111, 847, 146]]
12) Chemistry - Multiple Choice: The "ring current effect" dramatically affects the results of which of the following types of spectroscopy?  

text[[172, 163, 362, 234]]
W) NMR Spectroscopy 
X) ESR Spectroscopy 
Y) IR Spectroscopy 
Z) MS Spectroscopy  

text[[115, 252, 375, 270]]
Answer: W) NMR Spectroscopy  

sub_title[[466, 271, 530, 289]]
## Bonus  

text[[115, 290, 843, 343]]
12) Chemistry - Multiple Choice: Mercury has a very low melting point compared to other metals, which can be explained using band theory. Which of the following best explains Mercury's low melting point?  

text[[171, 360, 870, 485]]
W) It's valence and conduction bands are very close in energy, but not overlapping 
X) It has too few valence electrons, and cannot fully fill up the composite s-d composite band 
Y) It has too many valence electrons, and fills up the antibonding locations of the s-d composite band 
Z) Mercury's valence and conduction bands overlap too much, and the resulting band does not have a high enough bonding strength  

text[[115, 501, 228, 519]]
ANSWER: Y  

sub_title[[464, 538, 533, 556]]
## Tossup  

text[[115, 557, 875, 626]]
13) Energy - Multiple Choice: Oak ridge national lab is looking into the application of berms on the many streams in the tennessee valley to control flooding. If a berm is placed along the Tennessee River, which of the following would happen to the velocity of the stream downstream of the berm.  

text[[172, 645, 525, 715]]
W) Increase 
X) Decrease 
Y) Remain unchanged 
Z) Increases in summer, Decreases in winter  

text[[115, 732, 306, 750]]
ANSWER: W) Increase  

sub_title[[466, 772, 530, 789]]
## Bonus  

text[[115, 790, 880, 875]]
13) Energy - Short Answer: Scientists at ASAN have discovered a new star named Enolios in a far, far away galaxy. Using fancy equipment in their lab, they have determined the wavelength of an H-alpha particle as it reaches the lab from the star to be 2600 nm. If the initial wavelength of the H-alpha particle from the star is 650 nm, calculate the redshift of light between the star and the lab.text[[115, 91, 225, 107]]
ANSWER: 3  

sub_title[[463, 110, 533, 128]]
## Tossup  

text[[115, 128, 836, 164]]
14) Earth and Space – Short Answer: Order the following 4 rocks in order from highest to lowest elevation along a stream profile:  

text[[173, 182, 337, 252]]
1) Breccia 
2) Quartz Sandstone 
3) Conglomerate 
4) Arkose  

text[[115, 270, 280, 288]]
ANSWER: 1, 3, 4, 2  

sub_title[[465, 309, 530, 327]]
## Bonus  

text[[115, 329, 869, 364]]
14) Earth and Space – Short Answer: What is the name for alternating dark and light bands of ice on glaciers?  

text[[115, 381, 271, 400]]
ANSWER: Ogives  

sub_title[[463, 437, 533, 455]]
## Tossup  

text[[115, 456, 870, 491]]
15) Biology – Multiple Choice: A macrophage has just endocytosed a bacteria, but is unable to digest and kill it. What 2 organelles did not merge together?  

text[[172, 508, 403, 580]]
W) Lysosome and Golgi 
X) Endosome and Lysosome 
Y) Endosome and Golgi 
Z) Lysosome and ER  

text[[115, 596, 437, 614]]
ANSWER: X) Endosome and Lysosome  

sub_title[[465, 634, 530, 652]]
## Bonus  

text[[115, 653, 871, 705]]
15) Biology – Multiple Choice: The local population of birds at Enloe were recently decimated by an avian flu, resulting in a much smaller population size. Which of the following is NOT a possible effect on the population of birds?  

text[[172, 723, 495, 794]]
W) Increased average beak size 
X) Average mating song becomes longer 
Y) Overall reduction in competition 
Z) Increased adaptability to change  

text[[115, 812, 487, 830]]
ANSWER: Z) Increased adaptability to changesub_title[[463, 92, 533, 110]]
## Tossup  

text[[114, 111, 860, 181]]
Tossup#) Energy - Multiple Choice: Enloe Science Bowl decides to explore the pool located on the roof of Enloe's East building. After swimming for some time, they become suspicious that the pool has an extremely high chloride concentration. Which technique can they use to determine chloride concentration, a common argentometric titration using silver nitrate?  

text[[115, 198, 325, 215]]
ANSWER: Mohr Method  

sub_title[[465, 238, 530, 255]]
## Bonus  

text[[115, 257, 870, 310]]
Bonus#) Energy - Short Answer: Researchers at Oak Ridge National Laboratory are studying the renin-angiotensin- aldosterone system. What enzyme converts Angiotensin II to Angiotensin I- 7, also commonly found as a spike protein for the SARS CoV- 2 virus?  

text[[115, 327, 555, 346]]
ANSWER: ACE2 (Angiotensin Converting Enzyme 2)  

sub_title[[463, 402, 533, 420]]
## Tossup  

text[[115, 421, 881, 474]]
Tossup17) Physics - Multiple Choice: Consider a spherical region of uniform charge density with radius R. Which of the following options best describes the electric field as a function of distance from the center of the sphere?  

text[[173, 492, 733, 563]]
W) Increasing linearlyX) Decreasing proportional to \(1 / \mathrm{x}\) Y) Decreasing proportional to \(1 / \mathrm{x}\) , then decreasing proportional to \(1 / \mathrm{x}^2\) Z) Increasing linearly, then decreasing proportional to \(1 / \mathrm{x}^2\)  

text[[115, 580, 228, 598]]
ANSWER: Z  

sub_title[[465, 621, 530, 638]]
## Bonus  

text[[115, 640, 875, 675]]
Bonus17) Physics - Multiple Choice: Which of the following statements best describes the difference between Young's modulus [mod- yoo- lus] and bulk modulus?  

text[[172, 692, 872, 780]]
W) Young's modulus has units of pressure while bulk modulus has units of forceX) Young's modulus is accurate in high- stress situations and bulk modulus is accurate in low- stress situationsY) Young's modulus relates to length while bulk modulus relates to volumeZ) Young's modulus is for gases while bulk modulus is for liquids  

text[[115, 797, 808, 816]]
ANSWER: Y) Young's modulus relates to length while bulk modulus relates to volumesub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 841, 146]]
18) Biology - Multiple Choice: What are the two end products of the oxidative stage of the pentose phosphate pathway?  

text[[172, 163, 522, 234]]
W) NADPH and Ribulose 1,5 Bisphosphate  X) ATP and Ribulose 1,5 Bisphosphate  Y) ATP and Ribose 5 Phosphate  Z) Ribose 5 Phosphate and NADPH  

text[[115, 252, 500, 270]]
ANSWER: Z) Ribose 5 Phosphate and NADPH  

sub_title[[466, 289, 530, 307]]
## Bonus  

text[[115, 309, 842, 343]]
18) Biology - Multiple Choice: Which of the following proteins is correctly matched to the membrane that it is found in?  

text[[172, 361, 707, 432]]
W) Tom - Inner mitochondrial membrane  X) Tim - Outer mitochondrial membrane  Y) Glycophorin - Plasma Membrane  Z) Plastoquinone [plast- o-kwi-none] - Inner chloroplast membrane  

text[[115, 449, 340, 467]]
ANSWER: Y) Glycophorin  

sub_title[[463, 504, 533, 522]]
## Tossup  

text[[115, 523, 820, 575]]
19) Earth and Space - Short Answer: A star is measured to have a luminosity of 8 solar luminosities. If the radius of this star was halved and the temperature was tripled, in solar luminosities, what would the new luminosity of the star be?  

text[[115, 593, 245, 610]]
ANSWER: 162  

sub_title[[466, 612, 530, 630]]
## Bonus  

text[[115, 632, 840, 667]]
19) Earth and Space - Short Answer: Identify all of the following 3 properties of stars that increase with scale height in the Milky Way galaxy:  

text[[172, 685, 291, 738]]
I) Metalicity  II) Luminosity  III) Age  

text[[115, 756, 270, 774]]
ANSWER: III onlysub_title[[463, 92, 533, 110]]
## Tossup  

text[[113, 111, 850, 146]]
#) Math - Short Answer: To the nearest integer, what is the average value of the first 10,000 positive integers?  

text[[115, 162, 253, 180]]
ANSWER: 5001  

sub_title[[465, 201, 530, 218]]
## Bonus  

text[[115, 220, 872, 255]]
#) Math - Short Answer: Assuming that \(\log (2) = 0.3\) , \(\log (3) = 0.5\) , and \(\log (5) = 0.7\) , then to the nearest tenth, what is the value of \(\log_{125}(450)\) [READ: log base 125 of 450]?.  

text[[115, 272, 240, 289]]
ANSWER: 1.3  

sub_title[[465, 328, 533, 345]]
## Tossup  

text[[115, 346, 880, 381]]
21) Chemistry - Short Answer: What is the name and hapticity respectively of the ligands in the simplest ferrocene complex?  

text[[115, 398, 373, 416]]
ANSWER: Cyclopentadienyl, 5  

sub_title[[465, 453, 530, 470]]
## Bonus  

text[[115, 472, 880, 560]]
21) Chemistry - Short Answer: Assume that at 1000 Kelvin, and with all aqueous species at 1 molar, the reaction of Cu \(2+\) with Zinc to form Zn \(2+\) and Copper has a potential of 0 V. What, to 2 significant figures, is the natural log of the concentration of zinc ion required to raise the potential of the reaction to 1 V? Assume the universal gas constant has a value of 8, and Faraday's constant has a value of 96500.  

text[[115, 577, 242, 594]]
ANSWER: - 24sub_title[[463, 126, 533, 145]]
## Tossup  

text[[115, 145, 828, 181]]
22) Earth and Space – Multiple Choice: Order the following 4 locations on the terrestrial planets in order of increasing strength of the Coriolis effect:  

text[[173, 198, 377, 270]]
1) North Pole of Mercury 
2) North Pole of Venus 
3) North Pole of Earth 
4) North Pole of Mars  

text[[115, 288, 264, 306]]
ANSWER: 2,1,4,3  

sub_title[[466, 325, 530, 342]]
## Bonus  

text[[115, 344, 852, 380]]
22) Earth and Space – Multiple Choice: Which of the following best describes the magnetic anomaly of impact craters on mars?  

text[[115, 396, 866, 433]]
W) They have high magnetic anomaly because impact cratering heats craters up beyond their curie point  

text[[115, 432, 860, 468]]
X) They have low magnetic anomaly because impact cratering heats craters up beyond their curie point  

text[[115, 467, 844, 503]]
Y) They have a high magnetic anomaly because of the high magnetic anomaly in the meteorite  

text[[115, 502, 830, 538]]
Z) They have a low magnetic anomaly because of the low magnetic anomaly in the meteorite  

text[[115, 555, 830, 592]]
ANSWER: X) They have low magnetic anomaly because impact cratering heats craters up beyond their curie point.sub_title[[463, 92, 533, 110]]
## Tossup  

text[[113, 111, 872, 146]]
23) Physics – Short Answer: Identify all of the following 4 statements that are true of the fields in an AC circuit with a purely resistive load:  

text[[172, 163, 781, 233]]
I) The electric field is constant in magnitude  II) The electric field oscillates with the same frequency as the source voltage  III) The magnetic field oscillates at twice the frequency of the source voltage  IV) The direction of the Poynting vector is constant over time.  

text[[115, 250, 287, 268]]
ANSWER: II and IV  

sub_title[[466, 290, 530, 308]]
## Bonus  

text[[115, 310, 882, 379]]
23) Physics – Multiple Choice: A 10 kilogram machine gun begins with 40 kg of ammo on a flat frictionless surface. It shoots out ammo at a rate of 5 kilograms per second. The ammo leaves the machine gun at a constant velocity of 120 meters per second (relative to the machine gun). What is the acceleration of the machine gun after 4 seconds?  

text[[172, 397, 227, 466]]
W) 12  X) 15  Y) 20  Z) 25  

text[[115, 485, 229, 503]]
ANSWER: Y