
## Tossup  


1) Chemistry – Short Answer: What metal is deposited when Tollens’ reagent reacts with an aldehyde?  


ANSWER: Silver  


## Bonus  


1) Chemistry – Short Answer: Identify all of the following 3 atoms that have more neutrons than electrons:  


I) \(\mathrm{O}_{17}{}^{2 - }\) [READ: O 17 two minus] II) \(\mathrm{Cr}_{53}{}^{7 + }\) III) \(\mathrm{Si}_{29}{}^{4 - }\)  


ANSWER: II only  


## Tossup  


2) Biology – Short Answer: If the pKa of the carboxylic acid in an amino acid is 2, the pKa of the amino group is 10, and the pKa of the R group is 4, what is the isoelectric point of the amino acid?  


ANSWER: 3  


## Bonus  


2) Biology – Short Answer: Identify all of the following 3 statements that are true of capillaries in the cardiovascular system:  


I) The smaller radius of capillaries results in a higher blood pressure than arteries II) Oxygen from the blood passively diffuses into the alveolar capillaries III) New capillaries can be formed from angiogenesis  


ANSWER: II, III
## Tossup  


3) Earth and Space – Short Answer: Identify all of the following 3 tectonic features that do NOT correctly match with the corresponding stage of the Wilson Cycle?  


1) East African Rift, Embryonic 
2) Red Sea, Declining 
3) Pacific Ocean, Terminal  


ANSWER: 2 and 3  


## Bonus  


3) Earth and Space – Multiple Choice: At which of the following areas in the earth's mantle do the deepest earthquakes occur?  


W) Moho Discontinuity 
X) Gutenberg Discontinuity 
Y) Wadati Benioff Zone 
Z) Low Velocity Zone  


ANSWER: Y) Wadati Benioff Zone  


## Tossup  


4) Physics – Short Answer: A thermocouple measures the voltage difference created between two different metals when heated in order to find their temperature. What effect, which creates this voltage difference upon heating, do thermocouples take advantage of?  


ANSWER: Seebeck effect  


## Bonus  


4) Physics – Short Answer: Consider a reference frame containing a mass m rotating at angular frequency \(\omega\) [omega]. If the point at the center of rotation has a potential energy of 0, what is the magnitude of the potential energy associated with the centrifugal force at a distance r from the rotation axis in terms of all relevant variables?  


ANSWER: \(\frac{1}{2} m\omega^2 r^2\)
## Tossup  


5) Energy – Multiple Choice: Researchers at Pacific Northwest National Lab are researching the chloroform attenuation parameter and its effect on the dissolution of carbon tetrachloride. CCl<sub>4</sub> has an unusually high boiling point, which can be best attributed to which of the following factors?  


W) Strong London dispersion forces due to high polarizability  X) Strong dipole-dipole forces due to high dipole moment  Y) Hydrogen bonding between the carbon and chlorine atoms on different molecules  Z) Formation of a dimer from separate molecules  


ANSWER: W) Strong London dispersion forces due to high polarizability  


## Bonus  


5) Energy – Multiple Choice: Researchers at Sandia National Laboratory are studying ways that LEDs can be made more efficient, including the differences between direct and indirect semiconductors. Which of the following choices best describes the difference between direct and indirect band gap semiconductors?  


W) Direct band gap materials have a positive energy band gap while indirect do not  X) Direct band gap materials exist at lower temperatures while indirect band gap materials exist at higher temperatures  Y) Direct band gaps do not require phonon absorption or emission during band transition while indirect band gaps do  Z) Direct band gaps exist in intrinsic semiconductors while indirect band gaps exist in III-V [READ: three five] semiconductors  


ANSWER: Y) Direct band gaps do not require phonon absorption or emission during band transition while indirect band gaps do
## Tossup  


6) Earth and Space – Short Answer: What is the name for the locations around the world in which the tidal amplitude is very close to 0?  


ANSWER: Amphidromic Points  


## Bonus  


6) Earth and Space – Short Answer: Identify all of the following 3 statements that are true of internal waves:  


I) Internal waves have higher amplitude than surface waves with the same energy  II) Internal waves have lower frequency than surface waves with the same energy  III) Internal waves tend to be most pronounced at \(30^{\circ}\) north.  


ANSWER: I, and II  


## Tossup  


7) Chemistry – Short Answer: The ions \(\mathrm{Fe}^{2 + }\) , \(\mathrm{Cr}^{3 + }\) and \(\mathrm{Ni}^{2 + }\) all precipitate a green solid when reacting with what anion?  


ANSWER: OH- (Accept: Hydroxide, deprotonated hydroxide acid)  


## Bonus  


7) Chemistry – Short Answer: Identify all of the following 4 reagent-catalyst pairs that react with benzene to form an acidic compound:  


I) Chlorine gas 
- Iron Chloride  II) Methyl Chloride 
- Aluminum Chloride  III) Nitric Acid 
- Sulfuric Acid  IV) Sulfur Trioxide 
- Sulfuric Acid  


ANSWER: IV Only
## Tossup  


8) Math - Multiple Choice: Which of the following functions is differentiable at \(\mathbf{x} = 0\) ?  

equation[[171, 145, 280, 234]]
\[\mathrm{W)~}s e c^{-1}(x)\] \[\mathrm{X)~}c s c^{-1}(x)\] \[\mathrm{Y)~}s e c(x)\] \[\mathrm{Z)~}c s c(x)\]  


ANSWER: Y) sec(x)  


## Bonus  


8) Math - Short Answer: What is the limit as h approaches 0 of [read slowly] 1 over h times the integral from 0 to h of \(\sin^{2}(x)\) [READ: sine squared of x (?)] divided by \(\mathbf{x}^{2}\) dx?  


ANSWER: 1  


## Tossup  


9) Physics - Multiple Choice: Two particles at a distance of 2 meters from each other have an electromagnetic force of 4 Newtons between them, what is the minimum sum of charges on the two particles?  


ANSWER: 0  


## Bonus  


9) Physics - Short Answer: Identify all of the following 3 points that would be in stable equilibrium under the influence of the potential function \(\mathrm{U}(\mathbf{x}) = 4\mathbf{x}^{3} - 3\mathbf{x}^{2} + 1\) :  


I) \(\mathbf{x} = -0.5\) II) \(\mathbf{x} = 0\) III) \(\mathbf{x} = 0.5\)  


ANSWER: III only
## Tossup  


10) Earth and Space – Multiple Choice: An asteroid is orbiting at Jupiter's L4 lagrange point. Which of the following is closest to its average distance in Astronomical Units from Jupiter?  


W) 3 
X) 4 
Y) 5 
Z) 6  


ANSWER: Y) 5  


## Bonus  


10) Earth and Space – Short Answer: A star's emission spectrum is characterized by strong Balmer lines and Calcium 2 lines. If the star has an effective temperature of around 8,000 Kelvin, what is the spectral class of this star?  


ANSWER: A (ACCEPT: A5, A6 or A7)  


## Tossup  


11) Math – Short Answer: An upward opening parabola has a vertex at (0, 2) with the x-axis as its directrix. The point A, with an x-value of 8, lies on the parabola. What is the distance between A and the point (0, 4)?  


ANSWER: 10  


## Bonus  


11) Math – Short Answer: What is the limit as h approaches 0 of [read slowly] 1 over h times the integral from 0 to h of \(\sin^2 (x)\) [READ: sine squared of x (?)] divided by \(x^2 dx\) ?  


ANSWER: 1
## Tossup  


#) Energy - Short Answer: Scientists at Lawrence Berkeley National Laboratory are studying extensions of the Standard Model that solve the discrepancy between the gravitational and weak nuclear forces. What extension of the Standard Model introduces a new boson associated with every fermion and vice versa?  


ANSWER: Supersymmetry  


## Bonus  


12) Energy - Short Answer: Researchers at SLAC National Accelerator Facility are studying quantum physics using the SSRL. What type of radiation is emitted by subatomic particles that are accelerating due to a centripetal force?  


ANSWER: Synchrotron radiation [ACCEPT: cyclotron radiation]  


## Tossup  


13) Physics - Short Answer: What quantity is defined as the inverse hyperbolic tangent of the ratio of an object's velocity to the speed of light?  


ANSWER: Rapidity  


## Bonus  


13) Physics - Multiple Choice: Which of the following options is true of Gauss's Law?  


W) Gauss's Law can be applied to any type of two dimensional surface 
X) The principle behind Gauss's Law applies to any field proportional to \(1 / \mathrm{r}^2\) Y) Gauss's Law relates the electric flux through a closed surface to the current through it 
Z) Gauss's Law is analogous to Hooke's Law  


ANSWER: X) The principle behind Gauss's Law applies to any field proportional to \(1 / \mathrm{r}^2\)
## Tossup  


14) Biology - Short Answer: What method of prokaryotic transcription termination involves the formation of protein complexes that bind to the growing RNA transcript and separates it from the template?  


ANSWER: Rho-dependent termination  


## Bonus  


14) Biology - Short Answer: What is the name for the ubiquitin [yoo-bi-quit-in] ligase that marks cyclin B for degradation by proteasomes?  


ANSWER: Anaphase- promoting complex  


## Tossup  


15) Earth and Space - Short Answer: The mass fractions of hydrogen and helium for a star are 0.68 and 0.22 respectively. What is the metallicity of this star?  


ANSWER: 0.1 (ACCEPT: \(10\%\) , \(1 / 10 < -\) only psychopaths will give this answer)  


## Bonus  


15) Earth and Space - Short Answer: Order the following 3 satellites of Saturn from least to greatest mass:  


1) Mimas 
2) Titan 
3) Iapetus  


ANSWER: 1, 3, 2
## Tossup  


16) Chemistry- Multiple Choice: Which of the following best describes a racemic [race-ee-mic] mixture:  


W) Equimolar mixture of enantiomers [READ: in-an-tee-o-mers] 
X) 1:1 mixture of diastereomers [READ: di-ast-ree-o-mers] 
Y) 2:1 mixture of of enantiomers and diastereomers 
Z) 1:2 mixture of enantiomers and diastereomers  


ANSWER: W) Equimolar mixture of enantiomers  


## Bonus  


16) Chemistry - Multiple Choice: Which of the following solvents is most ideal for Sn2 reactions to take place in?  


W) Dimethyl Sulfoxide 
X) Water 
Y) Ammonia 
Z) Dioxane  


ANSWER: W) Dimethyl Sulfoxide  


## Tossup  


17) Biology - Short Answer: Cardiac muscle is able to communicate and propagate electric signals extremely quickly due to the presence of what distinctive connecting structures?  


ANSWER: Intercalated discs  


## Bonus  


17) Biology - Short Answer: In the Bundren family, the mother Addie Bundren has a daughter with Anse named Dewey Dell. She also has a child with another man named Whitfield, and has a son named Jewel. If Jewel and Dewey Dell have a child, what is the coefficient of relatedness between the child and Addie.  


ANSWER: 0.5
## Tossup  


18) Math - Short Answer: What is the integral from \(\pi /2\) to \(15\pi /2\) of \(\sin (x / 2)\) [READ: sin of open parenthesis x over 2 close parenthesis]?  


ANSWER: 0  


## Bonus  


18) Math - Short Answer: Colin is creating a list of the positive integers using the following rule: he lists all numbers in numerical order but skips multiples of 3 and skips multiples of 5. In this list, at what position will the number 101 be?  


ANSWER: 54  


## Tossup  


19) Physics - Short Answer: Consider a planet orbiting around a star. If the angular momentum vector of this planet is pointing in the positive Z direction, in what direction would the angular momentum vector be pointing if the system was mirrored along the XY plane?  


ANSWER: Positive Z  


## Bonus  


19) Physics - Multiple Choice: When considering cycles like the Otto and Brayton cycle, the assumption is made that the exhausted air is automatically returned to its initial state and fed back into the intake. This assumption is made to satisfy what requirement of thermodynamic cycles?  


W) No net change in entropy 
X) Ideal gas working fluid 
Y) Closed system 
Z) Uniform working fluid  


ANSWER: Y) Closed system
## Bonus  


Bonus#) Energy - Short Answer: Researchers at Pacific Northwest National Lab are simulating ways to use stronger building materials to increase the efficiency of truss structures. Consider a beam in a truss that can pivot at one end. If the linear density of the beam as a function of the distance from the pivot is equal to \(4 / \mathrm{d}\) kilograms per meter, what is the moment of inertia of the beam around the pivot as a function of its total length L?  


ANSWER: \(2\mathrm{L}^2\)  


## Tossup  


Tossup#) Energy- Short Answer: Researchers at the Idaho lab are studying muscle fibers. After studying Lebron's body, they observe that Lebron trains these kinds of muscle fibers everyday with resistance bands and by sprinting. These muscle fibers produce powerful quick actions. But the downside is it fatigues and cramps easily. What are these muscle fibers called?  


Researchers at Idaho National Lab are studying Lebron's muscles, in particular a certain kind of muscle fiber. If the fibers they are studying produce quick actions, but fatigue and cramp easily, what type of muscle fibers are being studied?  


ANSWER: Glycolytic fibers  


## Tossup  


Tossup21) Math - Short Answer: Identify all of the following 3 numbers that are not prime.  


I) 7,749 II) 33,549 III) 13,625  


ANSWER: All  


## Bonus  


Bonus21) Math - Short Answer: Rishil and Nikhil want to choose 3 more people to make up their 5-person ESBOT team; however, 40 people, including Colin, have requested to be on the team. With Nikhil reluctantly agreeing, Rishil decides to choose the other 3 people randomly. What is the probability that Colin is chosen to be on the team?  


ANSWER: 3/40
## Tossup  


22) Chemistry - Short Answer: What species is formed by the dissolution of gold in Aqua Regia?  


ANSWER: \(\mathrm{AuCl_4^- }\) (ACCEPT: tetrachloroaurate)  


## Bonus  


22) Chemistry - Multiple Choice: According to Markovnikov's rule, which of the following locations in a compound would be most favorable for addition reactions to add onto?  


W) The least substituted carbon 
X) The most substituted carbon 
Y) The carbon with the highest formal charge 
Z) The carbon with the lowest formal charge  


ANSWER: X) The most substituted carbon  


## Tossup  


23) Biology - Short Answer: What organelle do the proteins Bak and Bax bind onto?  


ANSWER: Mitochondria  


## Bonus  


23) Biology - Short Answer: The way that cone cells detect light can vary greatly between species. Identify all of the following 3 statements that are true about the ways that animals detect colors:  


I) L, M, and S human cone cells are most active in the yellow, green, and violet ranges of the spectrum respectively II) Canines only have two types of cone cells III) Cone cells are most sensitive in low-light conditions  


ANSWER: I and II