sub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 704, 130]]
1) Biology - Short Answer: Deficiency in what vitamin leads to pellagra?  

text[[115, 145, 390, 164]]
ANSWER: Niacin (ACCEPT: B3)  

sub_title[[465, 183, 530, 201]]
## Bonus  

text[[115, 202, 880, 238]]
1) Biology - Short Answer: Identify all of the following 4 conditions that would result in a Bohr shift of the hemoglobin-oxygen dissociation curve:  

text[[172, 254, 600, 326]]
I) Increased partial pressure of \(\mathrm{CO}_{2}\) II) Increased partial pressure of \(\mathrm{O}_{2}\) III) Increased concentration of 2,3 BPG in the blood IV) Increased concentration of lactic acid in the blood  

text[[115, 342, 282, 360]]
ANSWER: I, III, IV  

sub_title[[463, 422, 533, 441]]
## Tossup  

text[[115, 442, 864, 478]]
2) Chemistry - Multiple Choice: Which of the following compounds would cause the greatest boiling point elevation when added to water?  

text[[172, 494, 286, 566]]
W) \(\mathrm{Rh}_{2}\mathrm{O}_{3}\) X) \(\mathrm{Mg}_{3}(\mathrm{PO}_{4})_{2}\) Y) \(\mathrm{CH}_{2}\mathrm{O}\) Z) CsCl  

text[[115, 583, 325, 602]]
ANSWER: X) \(\mathrm{Mg}_{3}(\mathrm{PO}_{4})_{2}\)  

sub_title[[465, 624, 530, 641]]
## Bonus  

text[[115, 642, 825, 678]]
2) Chemistry - Short Answer: Order the following 4 elements in terms of increasing first electron affinity:  

text[[172, 696, 260, 765]]
1) Oxygen 
2) Lithium 
3) Boron 
4) Sodium  

text[[115, 782, 283, 800]]
ANSWER: 4, 2, 3, 1sub_title[[463, 92, 533, 110]]
## Tossup  

text[[114, 111, 872, 163]]
3) Earth and Space – Short Answer: Occasionally, two separate crystals in a mineral can grow in such a way that they intersect each other and share a crystallographic plane. What is the name of this phenomenon?  

text[[115, 181, 290, 199]]
ANSWER: Twinning  

sub_title[[465, 201, 530, 218]]
## Bonus  

text[[115, 220, 860, 255]]
3) Earth and Space – Multiple Choice: Which of the following radioactive isotopes would be most appropriate for dating a sample of age 140 million years?  

text[[173, 272, 317, 341]]
W) Uranium-235 
X) Samarium-147 
Y) Rubidium-87 
Z) Uranium-238  

text[[115, 358, 346, 376]]
ANSWER: W) Uranium-235  

sub_title[[463, 439, 533, 457]]
## Tossup  

text[[115, 458, 877, 511]]
4) Physics – Multiple Choice: Which of the following reasons best describes why birds are able to sit on a power line without being electrocuted, while humans can die from standing on the ground near a lightning strike?  

text[[172, 528, 879, 652]]
W) The outer coating of power lines protects the birds' feet, but there is no protective coating on the ground 
X) Humans are much less resistive than birds, causing more current to flow through them 
Y) The ground has a much higher resistance than a power line, causing a greater voltage difference per unit distance 
Z) The ground the human is standing on is grounded, leading to a greater voltage difference between the human and the ground  

text[[115, 670, 228, 687]]
ANSWER: Y  

sub_title[[465, 707, 530, 724]]
## Bonus  

text[[115, 725, 876, 795]]
4) Physics – Short Answer: Consider a system of levers where a lever of length 4 meters is connected to the left side of a lever of length 7 meters. If the system has an efficiency of 80%, what is the output torque measured at the far right side if an input torque of 40 Newton-meters is applied?  

text[[115, 813, 270, 830]]
ANSWER: 32 Nmsub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 110, 857, 163]]
5) Chemistry - Multiple Choice: Identical volumes of two solutions, A and B, are prepared. Solution A is made of pure water and Solution B is made of 0.5 Molar \(\mathrm{NaHCO_3}\) . Which of the following statements about the solutions is true?  

text[[172, 181, 696, 252]]
W) A has a higher vapor pressure and B has a higher boiling point  X) B has a higher vapor pressure and A has a higher boiling point  Y) A has a higher vapor pressure and boiling point  Z) B has a higher vapor pressure and boiling point  

text[[115, 270, 734, 288]]
ANSWER: W) A has a higher vapor pressure and B has a higher boiling point  

sub_title[[466, 306, 530, 323]]
## Bonus  

text[[112, 325, 861, 344]]
5) Chemistry - Short Answer: Order the following 4 atoms by increasing number of neutrons:  

text[[172, 361, 290, 430]]
1) Technetium  
2) Platinum  
3) Tungsten  
4) Silver  

text[[115, 448, 285, 465]]
ANSWER: 1, 4, 3, 2  

sub_title[[463, 527, 533, 545]]
## Tossup  

text[[115, 546, 857, 599]]
6) Math - Short Answer: Enloe Science Bowl needs to select new board members for their 2022-2023 season. If there are 15 ways they can choose a 2 person board, how many different ways can they select a 3 person board?  

text[[115, 616, 230, 633]]
ANSWER: 20  

sub_title[[466, 655, 530, 672]]
## Bonus  

text[[115, 674, 854, 726]]
6) Math - Short Answer: Providing your answer in base 8, add the following numbers in different bases [READ AS DIGITS]: 101011 in base 2, 221 in base 4, 14 in base 8, A in base 16?  

text[[115, 744, 246, 762]]
ANSWER: 150sub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 857, 145]]
7) Physics – Multiple Choice: Which of the following changes would increase the number of electrons being emitted from a metal due to an incident light source?  

text[[173, 163, 633, 234]]
W) Increasing the frequency of the light source  
X) Decreasing the frequency of the light source  
Y) Making the light waves travel in phase with each other  
Z) Increasing the intensity of the light  

text[[115, 252, 514, 270]]
ANSWER: Z) Increasing the intensity of the light  

sub_title[[466, 291, 530, 309]]
## Bonus  

text[[115, 311, 871, 380]]
7) Physics – Short Answer: Vedang is riding a bike at a constant speed of 7.4 m/s while he pedals with a power of 200 Watts. If the wheels of the bike are changed to be 1.5 times larger in diameter while Vedang pedals with the same power, what is the new speed of the bike in meters per second?  

text[[115, 398, 240, 415]]
ANSWER: 7.4  

sub_title[[463, 476, 533, 495]]
## Tossup  

text[[115, 496, 879, 548]]
8) Energy – Short Answer: Researchers at the Office of Fossil Energy are studying ways to improve the transportation of liquified natural gas. What is the term for the process of converting liquified natural gas back to its gaseous state?  

text[[115, 565, 329, 583]]
ANSWER: Regasification  

sub_title[[466, 603, 530, 620]]
## Bonus  

text[[115, 622, 868, 691]]
8) Energy – Short Answer: Researchers at the Office of Fossil Energy are studying ways to improve the processing of natural gas. If the first step in a purification process has an activation energy of 830 kJ, what is the natural log of the ratio between the reaction rate constants at 800 Kelvin and 400 Kelvin?  

text[[115, 709, 245, 726]]
ANSWER: 125sub_title[[463, 92, 533, 110]]
## Tossup  

text[[113, 111, 835, 146]]
9) Chemistry – Multiple Choice: Emission and absorption spectra provide evidence for all except which of the following?  

text[[172, 163, 488, 234]]
W) Lepton-boson interactions  
X) The Bohr model of the atom  
Y) A universally constant speed of light  
Z) Quantization of electron energy  

text[[113, 252, 528, 270]]
ANSWER: Y) A universally constant speed of light  

sub_title[[465, 291, 530, 309]]
## Bonus  

text[[113, 311, 870, 346]]
9) Chemistry – Short Answer: Order the following 4 gaseous molecules from highest to lowest velocity at 273 Kelvin:  

text[[172, 364, 339, 435]]
1) Ammonia  
2) Nitrogen  
3) Oxygen  
4) Carbon monoxide  

text[[115, 453, 264, 470]]
ANSWER: 1,4,2,3  

sub_title[[463, 513, 533, 531]]
## Tossup  

text[[113, 532, 872, 567]]
10) Earth and Space – Multiple Choice: Which of the following minerals has the fewest planes of cleavage?  

text[[172, 585, 397, 654]]
W) Biotite  
X) Calcite  
Y) Lepidolite [lep-i-dol-ite]  
Z) Quartz  

text[[115, 672, 265, 689]]
ANSWER: Quartz  

sub_title[[465, 690, 530, 708]]
## Bonus  

text[[113, 710, 864, 744]]
10) Earth and Space – Multiple Choice: Which of the following rocks displays compositional layering?  

text[[172, 762, 320, 832]]
W) Andesite  
X) Shale  
Y) Quartzite  
Z) Gneiss [nie-ce]  

text[[115, 849, 288, 867]]
ANSWER: Z) Gneisssub_title[[463, 108, 533, 127]]
## Tossup  

text[[115, 127, 879, 163]]
11) Biology – Short Answer: The contraction of muscles in the human body is stimulated by the release of what ion?  

text[[115, 180, 518, 199]]
ANSWER: \(\mathrm{Ca}^{2 + }\) (ACCEPT: calcium, calcium ion)  

sub_title[[466, 218, 530, 235]]
## Bonus  

text[[115, 236, 796, 273]]
11) Biology – Multiple Choice: Cyclic electron flow in photosynthesis excludes what photosystem and serves to primarily produce what substance, respectively?  

text[[172, 289, 397, 362]]
W) Photosystem I, NADPH 
X) Photosystem I, ATP 
Y) Photosystem II, NADPH 
Z) Photosystem II, ATP  

text[[115, 378, 401, 397]]
ANSWER: Z) Photosystem II, ATP  

sub_title[[463, 435, 533, 454]]
## Tossup  

text[[115, 455, 810, 490]]
12) Math – Short Answer: A tetrahedron of volume 1 is removed from each vertex of a tetrahedron of volume 17. How many edges does the new solid have?  

text[[115, 507, 231, 525]]
ANSWER: 18  

sub_title[[466, 544, 530, 562]]
## Bonus  

text[[115, 563, 879, 617]]
12) Math – Short Answer: A Pythagorean Quadruple is a set of 4 numbers a, b, c, d, such that \(a^2 + b^2 + c^2 = d^2\) [READ: a squared plus b squared plus c squared equals d squared]. Identify all of the following 3 sets of numbers that will form a Pythagorean Quadruple.  

text[[172, 633, 312, 687]]
I) (3, 4, 12, 13) II) (6, 10, 15, 17) III) (8, 9, 12, 17)  

text[[115, 703, 281, 721]]
ANSWER: I and IIIsub_title[[465, 92, 533, 110]]
## Tossup  

text[[115, 111, 850, 146]]
13) Physics – Multiple Choice: Which of the following is true of the frequency of a damped spring system compared to an undamped one with the same spring constant and mass?  

text[[172, 163, 556, 234]]
W) It is larger 
X) It is smaller 
Y) It is the same 
Z) It depends on the value of the spring constant  

text[[115, 252, 335, 270]]
ANSWER: X) It is smaller  

sub_title[[466, 271, 530, 289]]
## Bonus  

text[[115, 290, 860, 343]]
13) Physics – Multiple Choice: A regular hexagonal prism is laying on its side on an inclined plane with a very high coefficient of friction. Which of the following is closest to the incline angle needed for the heptagonal prism to begin to roll?  

text[[172, 360, 228, 429]]
W) 10 
X) 20 
Y) 30 
Z) 40  

text[[115, 448, 261, 466]]
ANSWER: Y) 30  

sub_title[[465, 506, 533, 524]]
## Tossup  

text[[115, 525, 872, 560]]
14) Earth and Space–Multiple Choice: Which of the following best explains why the Moon is red on a lunar eclipse?  

text[[115, 576, 881, 682]]
W) Neutrinos traveling through the Earth illuminate the moon at low frequencies 
X) Red light gets refracted at the largest angle by the Earth's atmosphere to illuminate the moon. 
Y) Blue light gets absorbed by the Earth's oceans preventing it from reaching the moon 
Z) Blue light gets scattered by the Earth's atmosphere to the greatest degree, preventing it from reaching the moon.  

text[[115, 700, 222, 717]]
ANSWER: Z  

sub_title[[466, 719, 530, 736]]
## Bonus  

text[[115, 738, 761, 774]]
14) Earth and Space – Multiple Choice: In which of the following regions of the electromagnetic spectrum does the sun emit the largest amount of energy?  

text[[172, 790, 390, 860]]
W) 200-380 nanometers 
X) 380-780 nanometers 
Y)780 - 2500 nanometers 
Z) 2500-30000 nanometers  

text[[115, 878, 333, 896]]
ANSWER: X) 380-780 nmsub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 844, 146]]
15) Math - Multiple Choice: The circumcenter of an equilateral triangle is 3 units above its bases. Which of the following is the area of the equilateral triangle?  

text[[172, 162, 243, 234]]
W) \(9\sqrt{3}\) X) \(12\sqrt{3}\) Y) \(18\sqrt{3}\) Z) \(27\sqrt{3}\)  

text[[115, 251, 280, 270]]
ANSWER: Z) \(27\sqrt{3}\)  

sub_title[[465, 289, 530, 307]]
## Bonus  

text[[115, 308, 812, 343]]
15) Math - Short Answer: Identify all of the following four numbers in base 13 that are divisible by 4 [READ DIGITS INDIVIDUALLY]:  

text[[172, 360, 237, 413]]
I) B36 II) 259 III) 435  

text[[115, 430, 252, 448]]
ANSWER: ALL  

sub_title[[463, 488, 533, 506]]
## Tossup  

text[[115, 507, 879, 542]]
16) Biology - Multiple Choice: Which of the following is not a requirement of Hardy-Weinberg equilibrium?  

text[[172, 560, 375, 630]]
W) Random mating 
X) No Gene Flow 
Y) No Selection 
Z) Small Population Size  

text[[115, 647, 415, 665]]
ANSWER: Z) Small Population Size  

sub_title[[465, 705, 530, 723]]
## Bonus  

text[[115, 724, 875, 760]]
16) Biology - Multiple Choice: Which of the following DNA repair pathways would be used to repair pyrimidine [pi-ri-mid-ee] dimers?  

text[[172, 777, 420, 848]]
W) Mismatch Repair 
X) Base Excision Repair 
Y) Nucleotide Excision Repair 
Z) Homology Directed Repair  

text[[115, 865, 457, 883]]
ANSWER: Y) Nucleotide Excision Repairsub_title[[463, 109, 533, 128]]
## Tossup  

text[[115, 128, 875, 199]]
17) Energy - Short Answer: Researchers at the Brookhaven National Laboratory are studying the ways that plant seeds get energy from the endosperm. One of these ways includes synthesizing sugars from lipids, and occurs in a specialized version of a peroxisome. What is the name of this anabolic pathway?  

text[[116, 216, 345, 234]]
ANSWER: glyoxylate cycle  

sub_title[[463, 257, 530, 275]]
## Bonus  

text[[115, 275, 866, 363]]
17) Energy - Short Answer: Scientists at SLAC National Accelerator Facility are leading the creation of new laser technologies. So far, they have succeeded in producing lasers that emit highly cohesive radiation as well as lasers that emit very short pulses of strong radiation, but have not been able to create a laser that accomplishes both of these. What scientific principle is preventing them from making advancements towards this?  

text[[115, 379, 473, 397]]
ANSWER: Heisenberg uncertainty principle  

sub_title[[463, 459, 533, 478]]
## Tossup  

text[[115, 478, 840, 496]]
18) Physics - Short Answer: Impedance is a combination of what two electrical quantities?  

text[[115, 513, 419, 530]]
ANSWER: Resistance and Reactance  

sub_title[[463, 550, 530, 568]]
## Bonus  

text[[115, 569, 840, 604]]
18) Physics - Short Answer: What is the magnitude of the impedance of a circuit with resistance of 7 ohms, capacitance reactance of 30 ohms, and inductive reactance of 6 ohms?  

text[[115, 621, 235, 638]]
ANSWER: 25sub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 110, 882, 163]]
19) Math - Multiple Choice: Thanush has a list of eight integers. He calculates the average of the numbers, and rounds his answer to the nearest tenth. Which one of the following values could not possibly be his result?  

text[[172, 181, 231, 252]]
W) 2.5 
X) 2.6 
Y) 2.7 
Z) 2.8  

text[[115, 270, 240, 287]]
ANSWER: 2.7  

sub_title[[466, 288, 530, 306]]
## Bonus  

text[[115, 308, 866, 342]]
19) Math - Multiple Choice: Which of the following operations between two numbers a and b is commutative?  

text[[172, 360, 865, 450]]
W) a / (b + a) [READ: a divided by the quantity of b plus a] 
X) 3a + 4b 
Y) (a + b)² + (a - b)² [READ: open parenthesis a plus b close parentheses squared plus open parentheses a minus b close parentheses squared] 
Z) ln(a/b) [READ: natural log of open parenthesis a divided by b close parenthesis]  

text[[115, 466, 229, 483]]
ANSWER: Y  

sub_title[[463, 507, 533, 525]]
## Tossup  

text[[115, 526, 866, 561]]
20) Biology - Short Answer: Identify all of the following 3 hormones that are produced by the anterior pituitary [pit-oo-i-tar-ee] gland:  

text[[172, 579, 532, 632]]
I) Oxytocin 
II) Luteinizing [loo-tee-in-izing] Hormone 
III) Antidiuretic [anti-di-yur-etic] Hormone  

text[[115, 649, 268, 666]]
ANSWER: II only  

sub_title[[466, 686, 530, 704]]
## Bonus  

text[[115, 705, 870, 740]]
20) Biology - Multiple Choice: Which of the following incorrectly matches a glial cell with its function?  

text[[172, 758, 618, 829]]
W) Microglia - immune cell 
X) Ependymal cells - circulate cerebrospinal fluid 
Y) Astrocytes - myelinate central nervous system 
Z) Schwann cells - myelinate peripheral nervous system  

text[[115, 849, 602, 867]]
ANSWER: Y) Astrocytes - myelinate central nervous systemsub_title[[463, 92, 533, 110]]
## Tossup  

text[[114, 111, 874, 163]]
21) Energy - Multiple Choice: Researchers in Anirudh's basement are studying the digestive tracts of various mammals. Which of the following statements is not true of digestive systems in relation to dietary preference?  

text[[172, 181, 666, 252]]
W) Frugivores tend to have larger intestinal surface areas 
X) Carnivores tend to have shorter intestines 
Y) Herbivores tend to have multiple stomachs to process fiber 
Z) Omnivores tend to eat more animal than plant matter.  

text[[115, 270, 657, 288]]
ANSWER: Z) Omnivores tend to eat more animal than plant matter.  

sub_title[[466, 306, 530, 324]]
## Bonus  

text[[115, 326, 865, 378]]
21) Energy - Short Answer: Researchers at Sandia National Labs are studying the ways that semiconducting materials can be improved. What is the name of the positive charge carrier in a doped semiconductor which represents the absence of an electron?  

text[[115, 395, 254, 412]]
ANSWER: Hole  

sub_title[[463, 474, 533, 492]]
## Tossup  

text[[115, 494, 839, 528]]
22) Chemistry - Short Answer: What term describes a solution that rotates the polarization angle of light that travels through it?  

text[[115, 545, 341, 563]]
ANSWER: Optically active  

sub_title[[466, 582, 530, 600]]
## Bonus  

text[[115, 601, 852, 636]]
22) Chemistry - Short Answer: Identify all of the following 3 terms that are used to describe types of metal alloys:  

text[[172, 654, 317, 707]]
I) Smectic 
II) Interstitial 
III) Substitutional  

text[[115, 725, 287, 742]]
ANSWER: II and IIIsub_title[[460, 92, 533, 110]]
## Tossup  

text[[446, 111, 550, 127]]
Stars/Cosmo  

text[[113, 128, 855, 164]]
23) Earth and Space – Multiple Choice: In which of the following areas on the H-R diagram would you find Delta Cephei?  

text[[172, 181, 348, 252]]
W) Main Sequence  
X) Horizontal Branch  
Y) Turnoff Point  
Z) Instability Strip  

text[[115, 268, 362, 286]]
ANSWER: Z) Instability Strip  

sub_title[[468, 287, 530, 304]]
## Bonus  

text[[115, 306, 810, 342]]
23) Earth and Space – Multiple Choice: Which of the following best describes a single degenerate progenitor [pro-jen-i-tor] supernova?  

text[[172, 358, 682, 431]]
W) Type 1A supernova involving a white dwarf and a larger star  
X) Type 1B supernova involving a single massive star  
Y) Type 1A supernova involving two white dwarfs  
Z) Type 1B supernova involving a single white dwarf  

text[[115, 448, 228, 465]]
ANSWER: W