sub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 802, 146]]
1) Biology – Short Answer: Huntington's disease is characterized by repeats of what 3 nucleotide sequence?  

text[[115, 163, 258, 181]]
ANSWER: CAG  

sub_title[[463, 225, 533, 243]]
## Tossup  

text[[115, 243, 881, 279]]
2) Earth and Space – Multiple Choice: Which of the following iron minerals is most resistant to chemical weathering?  

text[[173, 296, 287, 366]]
W) Magnetite 
X) Hematite 
Y) Goethite 
Z) Limonite  

text[[115, 382, 308, 401]]
ANSWER: X) Hematite  

sub_title[[463, 419, 533, 437]]
## Tossup  

text[[115, 438, 857, 473]]
3) Math – Short Answer: An ellipse has 2 foci at (-3,0) and (3,0) and includes the point (0,4). What is the area of this ellipse?  

text[[115, 490, 246, 508]]
ANSWER: 20π  

sub_title[[463, 528, 533, 546]]
## Tossup  

text[[115, 547, 878, 600]]
4) Physics – Multiple Choice: A metal plate has a coefficient of linear expansion of 0.006 inverse Kelvins and an original area of 100 square meters. The temperature of the plate increases by 5 Kelvins. What is the new area of the plate to the nearest square meter?  

text[[173, 618, 234, 688]]
W) 101 
X) 103 
Y) 104 
Z) 106  

text[[115, 706, 228, 723]]
ANSWER: Z  

sub_title[[463, 761, 533, 780]]
## Tossup  

text[[115, 781, 771, 816]]
5) Chemistry – Short Answer: Iodometry is most commonly used to determine the concentration of what types of compounds?  

text[[115, 833, 558, 852]]
ANSWER: Oxidizing agents (Accept equivalent terms)sub_title[[463, 92, 533, 111]]
## Tossup  

text[[113, 111, 870, 146]]
6) Biology - Short Answer: What region of the inner ear is responsible for detecting horizontal acceleration?  

text[[115, 163, 270, 181]]
ANSWER: Utricle  

sub_title[[463, 202, 533, 220]]
## Tossup  

text[[115, 220, 877, 256]]
7) Earth and Space - Short Answer: Tatooine orbits 3 AU away from a binary star system with masses of 1 solar mass and 3 solar masses. What is its orbital period to the nearest year?  

text[[115, 273, 221, 291]]
ANSWER: 6  

sub_title[[463, 292, 533, 310]]
## Tossup  

text[[113, 311, 880, 346]]
8) Chemistry - Short Answer: How many radial and angular nodes respectively are contained in a 3d orbital?  

text[[115, 363, 273, 381]]
ANSWER: 0 and 2  

sub_title[[463, 383, 533, 402]]
## Tossup  

text[[115, 404, 852, 461]]
9) Physics - Short Answer: A spaceship is in orbit with average mechanical energy of -78J. It fires its rockets and increases its average kinetic energy by 34 J. What is the average total mechanical energy in the orbit now?  

text[[115, 484, 258, 502]]
ANSWER: - 112 J  

sub_title[[463, 528, 533, 546]]
## Tossup  

text[[115, 547, 870, 600]]
10) Math - Short Answer: If \(\mathrm{a}^{2} + \mathrm{b} = 6\) [a squared plus b equals 6] and \(\mathrm{a} + \mathrm{b}^{2} = 7\) [a plus b squared equals 7], then what is the value of \(\mathrm{a}^{2}\mathrm{b}^{2} + \mathrm{a}^{3} + \mathrm{b}^{3} + \mathrm{ab}\) [a squared times b squared plus a cubed plus b cubed plus a time b]?  

text[[115, 616, 235, 634]]
ANSWER: 42