
## Tossup  


1) Biology – Short Answer: Huntington's disease is characterized by repeats of what 3 nucleotide sequence?  


ANSWER: CAG  


## Tossup  


2) Earth and Space – Multiple Choice: Which of the following iron minerals is most resistant to chemical weathering?  


W) Magnetite 
X) Hematite 
Y) Goethite 
Z) Limonite  


ANSWER: X) Hematite  


## Tossup  


3) Math – Short Answer: An ellipse has 2 foci at (-3,0) and (3,0) and includes the point (0,4). What is the area of this ellipse?  


ANSWER: 20π  


## Tossup  


4) Physics – Multiple Choice: A metal plate has a coefficient of linear expansion of 0.006 inverse Kelvins and an original area of 100 square meters. The temperature of the plate increases by 5 Kelvins. What is the new area of the plate to the nearest square meter?  


W) 101 
X) 103 
Y) 104 
Z) 106  


ANSWER: Z  


## Tossup  


5) Chemistry – Short Answer: Iodometry is most commonly used to determine the concentration of what types of compounds?  


ANSWER: Oxidizing agents (Accept equivalent terms)
## Tossup  


6) Biology - Short Answer: What region of the inner ear is responsible for detecting horizontal acceleration?  


ANSWER: Utricle  


## Tossup  


7) Earth and Space - Short Answer: Tatooine orbits 3 AU away from a binary star system with masses of 1 solar mass and 3 solar masses. What is its orbital period to the nearest year?  


ANSWER: 6  


## Tossup  


8) Chemistry - Short Answer: How many radial and angular nodes respectively are contained in a 3d orbital?  


ANSWER: 0 and 2  


## Tossup  


9) Physics - Short Answer: A spaceship is in orbit with average mechanical energy of -78J. It fires its rockets and increases its average kinetic energy by 34 J. What is the average total mechanical energy in the orbit now?  


ANSWER: - 112 J  


## Tossup  


10) Math - Short Answer: If \(\mathrm{a}^{2} + \mathrm{b} = 6\) [a squared plus b equals 6] and \(\mathrm{a} + \mathrm{b}^{2} = 7\) [a plus b squared equals 7], then what is the value of \(\mathrm{a}^{2}\mathrm{b}^{2} + \mathrm{a}^{3} + \mathrm{b}^{3} + \mathrm{ab}\) [a squared times b squared plus a cubed plus b cubed plus a time b]?  


ANSWER: 42