title[[310, 212, 685, 367]]
ESBOT
2023 

text[[422, 450, 571, 500]]
DE8sub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 110, 872, 146]]
1) Chemistry – Short Answer: Identify all of the following three molecules which are predicted to be paramagnetic by molecular orbital theory.  

text[[171, 163, 264, 216]]
I) \(\mathrm{N}_{2}^{2 + }\) ion II) \(\mathrm{O}_{2}^{4 + }\) ion III) \(\mathrm{O}_{2}\)  

text[[115, 234, 282, 252]]
ANSWER: II and III  

sub_title[[466, 289, 530, 307]]
## Bonus  

text[[115, 308, 875, 396]]
1) Chemistry – Short Answer: Colin is conducting a titration of formic acid using NaOH titrant, but he is all out of indicator solution. He decides to run a conductometric titration to determine the concentration of formic acid. He creates a graph of his data with volume of NaOH added on the horizontal axis and conductivity on the vertical axis. What quantity is represented by the slope of the lines on the graph?  

text[[115, 412, 567, 431]]
ANSWER: Molar conductivity (ACCEPT: conductivity)  

sub_title[[463, 504, 533, 522]]
## Tossup  

text[[115, 522, 866, 558]]
2) Biology – Multiple Choice: If a cell lacks vitamin B5, which of the following is most likely to occur?  

text[[172, 575, 481, 647]]
W) Increase in lactic acid fermentation 
X) Increase in fatty acid synthesis 
Y) Increase in fatty acid catabolism 
Z) Increase in citrate synthase activity  

text[[115, 663, 523, 682]]
ANSWER: W) Increase in lactic acid fermentation  

sub_title[[466, 719, 530, 736]]
## Bonus  

text[[115, 737, 881, 843]]
2) Biology – Short Answer: Feather color in eagles is regulated by two genes, A and B. The A gene follows an autosomal dominant inheritance pattern, where the dominant phenotype denotes a green coloration and the recessive phenotype denotes a gold coloration. Furthermore, the B gene epistatically regulates the A gene where the presence of the dominant B allele is required to express feather coloration, otherwise the eagle will be albino. If two eagles heterozygous for both genes are crossed, what is the probability the offspring will have gold feathers?  

text[[115, 860, 250, 877]]
ANSWER: 3/16sub_title[[463, 92, 533, 110]]
## Tossup  

text[[114, 111, 790, 145]]
3) Earth and Space – Multiple Choice: At which of the following times of day is the atmosphere most stable?  

text[[173, 163, 323, 234]]
W) Early Morning 
X) Noon 
Y) Evening 
Z) Midnight  

text[[115, 252, 362, 270]]
ANSWER: W) Early Morning  

sub_title[[464, 289, 530, 307]]
## Bonus  

text[[115, 308, 821, 343]]
3) Earth and Space – Short Answer: The abundance of life in the geologic record can be determined by the decreased relative abundance of what isotope of carbon?  

text[[116, 360, 300, 378]]
ANSWER: Carbon- 13  

sub_title[[463, 452, 533, 470]]
## Tossup  

text[[115, 470, 870, 524]]
4) Energy – Short Answer: Researchers at Savannah River National Lab are studying batteries. Lead-acid batteries, commonly used in cars, can generate flammable gasses when overcharged. These gasses are most likely generated through the electrolysis of what compound?  

text[[115, 541, 262, 558]]
ANSWER: Water  

sub_title[[464, 594, 530, 612]]
## Bonus  

text[[115, 614, 867, 701]]
4) Energy – Short Answer: Scientists at Lawrence Berkeley National Labs are studying quantum computing and how it can be used to speed up computations using number base systems other than binary. Radix economy is a measure used to compare the efficiency of different number bases, and is defined as the base times the number of digits used to express some number in that base. What base has the lowest radix economy for the base 10 number 70?  

text[[115, 718, 225, 735]]
ANSWER: 3sub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 800, 146]]
5) Math – Short Answer: How many consecutive zeros appear at the end of 600! [600 factorial]?  

text[[115, 163, 240, 180]]
ANSWER: 148  

sub_title[[466, 219, 530, 236]]
## Bonus  

text[[115, 237, 879, 308]]
5) Math – Short Answer: Thanush is back at the gym to work on his bench press. He has an unlimited supply of 8 pound weights, 9 pound weights, and 17 pound weights. If the bar weighs 45 pounds and balancing the bar does not matter, identify all of the following 3 total weights that Thanush can bench using the weights he has:  

text[[172, 325, 300, 378]]
I) 60 pounds  II) 75 pounds  III) 100 pounds  

text[[115, 395, 259, 413]]
ANSWER: None  

sub_title[[463, 486, 533, 504]]
## Tossup  

text[[115, 505, 825, 539]]
6) Biology – Short Answer: Identify all of the following 3 characteristics which correctly describe siRNA:  

text[[172, 558, 408, 611]]
I) Endogenous  II) Single stranded  III) Forms the RISC complex  

text[[115, 628, 275, 646]]
ANSWER: III only  

sub_title[[466, 684, 530, 701]]
## Bonus  

text[[115, 703, 879, 737]]
6) Biology – Short Answer: Identify all of the following 3 statements that are true about the role of hormones in the male reproductive cycle:  

text[[172, 755, 857, 809]]
I) Follicle-stimulating hormone is released by the hypothalamus  II) Follicle-stimulating hormone stimulates Sertoli cells to secrete luteinizing hormone  III) Luteinizing hormone stimulates Leydig cells to secrete testosterone  

text[[115, 825, 275, 843]]
ANSWER: III onlysub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 110, 848, 146]]
7) Physics – Multiple Choice: Which of the following best describes the magnitude of work done by friction on a rolling object?  

text[[172, 163, 758, 237]]
W) Nonzero for rolling with slipping, nonzero for rolling without slipping  X) Nonzero for rolling with slipping, zero for rolling without slipping  Y) Zero for rolling with slipping, nonzero for rolling without slipping  Z) Zero for rolling with slipping, zero for rolling without slipping  

text[[115, 252, 763, 272]]
ANSWER: X) Nonzero for rolling with slipping, zero for rolling without slipping  

sub_title[[466, 307, 530, 325]]
## Bonus  

text[[115, 326, 866, 379]]
7) Physics – Short Answer: For a NPN BJT transistor where positive current flows in and negative current flows out, order the following 3 terminals from most positive to most negative current:  

text[[173, 397, 272, 450]]
1) Base  
2) Collector  
3) Emitter  

text[[115, 467, 264, 485]]
ANSWER: 2, 1, 3  

sub_title[[463, 557, 533, 576]]
## Tossup  

text[[115, 577, 812, 612]]
8) Chemistry – Short Answer: When conducting IR spectroscopy, order the following 3 resonance modes from lowest to highest wavenumber:  

text[[173, 630, 301, 683]]
1) Vibrational  
2) Translational  
3) Rotational  

text[[115, 700, 264, 718]]
ANSWER: 2, 3, 1  

sub_title[[466, 755, 530, 772]]
## Bonus  

text[[115, 774, 875, 809]]
8) Chemistry – Short Answer: How many unpaired electrons are in a neutral, ground-state atom of molybdenum?  

text[[115, 827, 226, 844]]
ANSWER: 6sub_title[[463, 92, 533, 110]]
## Tossup  

text[[114, 111, 881, 181]]
9) Math - Multiple Choice: Sukrith is recording the Enloe football team's pass completion rate. He records the pass completion rate by taking samples of 10 consecutive passes and writing down the completion rate of that sample. After he has recorded a large number of samples, which of the following best describes the shape of the distribution of his data?  

text[[172, 198, 321, 270]]
W) Binomial 
X) Geometric 
Y) Hyperbinomial 
Z) Normal  

text[[115, 287, 300, 305]]
ANSWER: Z) Normal  

sub_title[[466, 342, 530, 360]]
## Bonus  

text[[114, 361, 850, 396]]
9) Math - Short Answer: What are the eigenvalues [eye-gen-values] for the 2 by 2 matrix A with top row 2, -3 and bottom row 1, -2?  

text[[115, 413, 402, 431]]
ANSWER: 1 and - 1 (ACCEPT: ±1)  

sub_title[[463, 504, 533, 522]]
## Tossup  

text[[115, 523, 881, 575]]
10) Physics - Multiple Choice: When calculating the speed of sound in a solid, the Young's modulus of the solid is used, but when calculating speed of sound in a liquid, the bulk modulus is used instead. Which of the following best explains why this is the case?  

text[[172, 592, 725, 664]]
W) Liquids are much less dense than solids 
X) Liquids flow laterally under stress while solids do not 
Y) Liquids have nonlinear stress-strain curves while solids do not 
Z) Liquids compress adiabatically while solids compress isothermally  

text[[115, 681, 663, 700]]
ANSWER: X) Liquids flow laterally under stress while solids do not  

sub_title[[466, 736, 530, 754]]
## Bonus  

text[[115, 755, 856, 808]]
10) Physics - Short Answer: In a diode, what form of breakdown occurs near a highly doped PN junction with a thin depletion zone that allows a reverse current to pass through the diode without destroying the junction?  

text[[115, 825, 353, 843]]
ANSWER: Zener breakdownsub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 110, 826, 130]]
11) Earth and Space – Short Answer: Order the following 3 events from earliest to latest:  

text[[173, 145, 460, 200]]
1) Electroweak Symmetry Breaking 
2) Recombination 
3) Inflation  

text[[115, 216, 265, 234]]
ANSWER: 3, 1, 2  

sub_title[[466, 277, 530, 295]]
## Bonus  

text[[115, 296, 882, 350]]
11) Earth and Space – Multiple Choice: Most larger asteroids have very high rotation rates such that the inertial force is higher than their gravitational acceleration. This suggests which of the following formation origins?  

text[[172, 366, 666, 438]]
W) They are ejecta from planets 
X) They form from the collisions of multiple smaller asteroids 
Y) They formed outside the asteroid belt 
Z) They formed from dust accretion  

text[[115, 454, 663, 474]]
ANSWER: X) They from the collisions of multiple smaller asteroids  

sub_title[[463, 546, 533, 565]]
## Tossup  

text[[115, 565, 866, 610]]
12) Math – Short Answer: If \(\frac{1}{\log(a)} + \frac{1}{\log(b)} = 2\) [1 over log of a plus 1 over log of b equals 2] and \(\log(a) \cdot \log(b) = 2\) [log of a times log of b equals 2], then what is the value of \(ab\) ?  

text[[115, 625, 266, 644]]
ANSWER: 10000  

sub_title[[466, 682, 530, 700]]
## Bonus  

text[[115, 704, 875, 750]]
12) Math – Short Answer: Let a, b, and c be the roots of the polynomial \(x^3 - 7x^2 + 12x + 5\). What is \(1/a^2 + 1/b^2 + 1/c^2\)?  

text[[115, 766, 229, 784]]
ANSWER: - 1sub_title[[464, 92, 533, 110]]
## Tossup  

text[[115, 111, 846, 181]]
13) Energy - Short Answer: Brian is using machine learning to analyze the effectiveness of different Genshin builds. When building his model, he uses tensors in order to organize and manipulate his data. Covariant and contravariant are terms used to describe the behavior of a tensor under what operation?  

text[[115, 198, 608, 216]]
ANSWER: Change of basis (ACCEPT: linear transformation)  

sub_title[[466, 253, 530, 271]]
## Bonus  

text[[115, 272, 878, 342]]
13) Energy - Short Answer: Researchers at Fermilab are studying the production of radioisotopes for medical imaging. Technetium-99m was the first artificial radioisotope, and unlike its counterpart Technetium-99, has a shorter half life of roughly a day. What does the m in Technetium-99m stand for?  

text[[115, 359, 301, 377]]
ANSWER: Metastable  

sub_title[[464, 450, 533, 468]]
## Tossup  

text[[115, 469, 847, 539]]
14) Physics - Short Answer: Despite carrying power, lasers can be used to cool individual atoms or molecules. What is the name for the laser cooling process where laser light slightly below an electron transition frequency is used to induce an electron transition in fast-moving atoms, but not slow ones?  

text[[115, 556, 344, 574]]
ANSWER: Doppler cooling  

sub_title[[466, 610, 530, 628]]
## Bonus  

text[[115, 630, 869, 682]]
14) Physics - Short Answer: Kaiwen has built a computer simulator for quantum interactions that relies on Feynman diagrams. If the probability of the simplest electrodynamic interaction is \(\alpha\) [alpha], what is the probability for the simplest 2 particle interaction to occur?  

text[[115, 699, 232, 716]]
ANSWER: \(\alpha^2\)sub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 835, 146]]
15) Biology - Multiple Choice: Which of the following symptoms is not associated with a potassium deficiency in plants?  

text[[172, 163, 387, 234]]
W) Death of terminal buds 
X) Weak stems 
Y) Molting of older leaves 
Z) Drying of leaf edges  

text[[115, 252, 426, 270]]
ANSWER: W) Death of terminal buds  

sub_title[[466, 306, 530, 323]]
## Bonus  

text[[115, 325, 854, 360]]
15) Biology - Short Answer: Identify all of the following 3 statements that are true about the role of hormones in the male reproductive cycle:  

text[[172, 378, 857, 432]]
I) Follicle-stimulating hormone is released by the hypothalamus 
II) Follicle-stimulating hormone stimulates Sertoli cells to secrete luteinizing hormone 
III) Luteinizing hormone stimulates Leydig cells to secrete testosterone  

text[[115, 448, 275, 466]]
ANSWER: III only  

sub_title[[463, 531, 533, 549]]
## Tossup  

text[[115, 550, 808, 584]]
16) Chemistry - Multiple Choice: An \(\mathrm{S_N1}\) reaction is carried out on a chiral center of a substrate. Which of the following best describes the stereochemical outcome?  

text[[172, 602, 710, 673]]
W) Complete inversion of the stereocenter 
X) Partial inversion with a preference for inversion of configuration 
Y) Partial inversion with a preference for retention of configuration 
Z) Nearly perfectly racemic  

text[[115, 690, 744, 709]]
ANSWER: X) Partial inversion with a preference for inversion of configuration  

sub_title[[466, 745, 530, 762]]
## Bonus  

text[[115, 764, 848, 799]]
16) Chemistry - Short Answer: Identify all of the following 3 types of electrophilic addition reactions that follow the Markovnikov rule:  

text[[172, 817, 455, 870]]
I) Hydroboration-oxidation 
II) Hydrohalogenation 
III) Oxymercuration demercuration  

text[[115, 888, 287, 905]]
ANSWER: II and IIIsub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 877, 146]]
17) Earth and Space – Short Answer: Antarctic Bottom Water is formed through brine rejection at what areas of ice free ocean surrounded on all sides by contiguous sea ice?  

text[[115, 163, 275, 181]]
ANSWER: Polynya  

sub_title[[466, 201, 530, 218]]
## Bonus  

text[[115, 220, 812, 255]]
17) Earth and Space – Short Answer: Order the following 3 ocean waves by increasing amplitude:  

text[[173, 273, 328, 288]]
1) Capillary Waves  

text[[173, 291, 303, 307]]
2) Rogue Waves  

text[[173, 309, 313, 325]]
3) Gravity Waves  

text[[115, 343, 260, 360]]
ANSWER: 1, 3, 2  

sub_title[[463, 433, 533, 451]]
## Tossup  

text[[115, 452, 880, 487]]
18) Physics – Short Answer: Identify all of the following quantities that would increase the drift velocity of a charged quasiparticle in a metal when increased:  

text[[173, 505, 310, 558]]
I) Effective mass  
II) Charge  
III) Electric field  

text[[115, 576, 286, 593]]
ANSWER: II and III  

sub_title[[466, 630, 530, 648]]
## Bonus  

text[[115, 650, 841, 720]]
18) Physics – Multiple Choice: Colin is investigating the motion of electrons in condensed matter. He finds that the potential of an electron as a function of position is given by [U of x equals x times sine of the quantity x squared]. How many stable and unstable equilibrium points exist between \(x = 0\) and \(x = 3\) ?  

text[[173, 738, 357, 810]]
W) 1 stable, 1 unstable  
X) 2 stable, 1 unstable  
Y) 1 stable, 2 unstable  
Z) 2 stable, 2 unstable  

text[[115, 828, 392, 846]]
ANSWER: Y) 1 stable, 2 unstablesub_title[[463, 92, 533, 110]]
## Tossup  

text[[114, 111, 877, 148]]
19) Math - Short Answer: Points \(A, B, C,\) and \(D\) lie on a circle in that order such that \(AB = 10,\) \(BC = 5, CD = 3\) and \(DA = 9\) . What is the value of \(AC * BD\) ?  

text[[115, 165, 235, 183]]
ANSWER: 75  

sub_title[[466, 220, 530, 238]]
## Bonus  

text[[115, 239, 870, 292]]
19) Math - Short Answer: Emma, Siddharth, Brian, Mr. Oliphant, and Thanush want to sit in a row of 5 chairs. Thanush wants to sit next to Brian, and Emma refuses to sit next to Brian. How many ways are there for the five people to sit such that the conditions are satisfied?  

text[[115, 308, 235, 326]]
ANSWER: 36  

sub_title[[463, 410, 533, 428]]
## Tossup  

text[[113, 429, 872, 465]]
20) Earth and Space - Short Answer: Order the following three planets in increasing similarity of bulk composition to the sun:  

text[[173, 483, 255, 536]]
1) Jupiter 
2) Saturn 
3) Uranus  

text[[115, 553, 260, 571]]
ANSWER: 3, 1, 2  

sub_title[[466, 613, 530, 630]]
## Bonus  

text[[115, 632, 880, 702]]
20) Earth and Space - Short Answer: Alderaan is orbiting its star with an orbital period of 33 weeks. If the star was replaced with the Death Star, which has 1/4 of the mass of the original star, and the orbital radius remained constant, then to the nearest day, what would the new orbital period be?  

text[[115, 720, 282, 738]]
ANSWER: 462 dayssub_title[[423, 108, 574, 127]]
## Tossup - Serena  

text[[115, 128, 800, 163]]
21) Biology - Short Answer: O-linked glycosylation is an important post translational modification. In what cellular organelle does O-linked glycosylation occur?  

text[[115, 180, 608, 199]]
ANSWER: Golgi (ACCEPT: Golgi Apparatus, Golgi Bodies)  

sub_title[[466, 235, 530, 253]]
## Bonus  

text[[115, 255, 850, 290]]
21) Biology - Short Answer: Identify all of the following 3 structures that are formed by the metencephalon:  

text[[172, 308, 347, 361]]
I) Medulla Oblongata II) Pons III) Cerebellum  

text[[115, 378, 258, 396]]
ANSWER: II, III  

sub_title[[463, 468, 533, 488]]
## Tossup  

text[[115, 491, 880, 531]]
22) Chemistry - Short Answer: How many nodes are present in the HOMO of the conjugated pi system of 1,3,5,7,octa-tetraene [1 3 5 7 octa-tetra-een]?  

text[[115, 550, 226, 568]]
ANSWER: 4  

sub_title[[466, 616, 530, 634]]
## Bonus  

text[[115, 636, 870, 671]]
22) Chemistry - Short Answer: Order the following 3 thermodynamic potentials from smallest to largest for an arbitrary system:  

text[[172, 689, 375, 742]]
1) Internal energy 
2) Enthalpy 
3) Helmholtz free energy  

text[[115, 760, 265, 777]]
ANSWER: 3, 1, 2sub_title[[463, 91, 533, 110]]
## Tossup  

text[[115, 111, 861, 181]]
23) Energy – Multiple Choice: Researchers at Argonne National Lab are studying superconductivity in low-temperature materials. Cooper pairs, which are the cause of superconductivity, can form in either singlet or triplet states. Which of the following quantities differ between singlet and triplet Cooper pairs?  

text[[172, 199, 336, 270]]
W) Charge 
X) Spin 
Y) Electric potential 
Z) Mean free path  

text[[115, 287, 278, 305]]
ANSWER: X) Spin  

sub_title[[466, 341, 530, 359]]
## Bonus  

text[[115, 360, 856, 430]]
23) Energy – Short Answer: Researchers at Sandia National Laboratory are studying the formation and ripening of fruit in an attempt to improve yields. They are interested in the way that ethylene controls fruit development at the cellular level. What amino acid is ethylene derived from?  

text[[115, 448, 306, 466]]
ANSWER: Methionine