
ESBOT 


2023 


RR1
## Tossup  


1) Physics - Short Answer: A lightbulb glows brightly when it is connected across a certain ideal battery. Two more identical bulbs are then connected across the same battery, so that all three bulbs are in parallel. By what factor will the brightness of each of the three bulbs increase compared to the original bulb?  


ANSWER: 1  


## Bonus  


1) Physics - Short Answer: Kaiwen is repairing a brake system on a car. To prevent overheating of the brake pads, he attaches a heat sink to them with a contact area of 0.05 square meters. If the wheel of the car is spinning at 60 radians per second and the brakes apply a torque of 150 Newton-meters, how much power in Watts must the heat sink absorb to avoid overheating?  


ANSWER: 9000  


## Tossup  


2) Energy - Multiple Choice: Researchers at Sandia National Laboratory are finding ways to combat the cellular processes involved in the destruction of the substantia nigra. What disease are they aiming to find a solution for?  


W) Hypothyroidism 
X) Parkinson's 
Y) Huntington's 
Z) Lou Gherig's [Loo-Geh-Rigs]  


ANSWER: X) Parkinsons  


## Bonus  


2) Energy - Multiple Choice: Researchers at North Carolina State University are studying ways to improve the efficiency of combustion engines. Which of the following thermodynamic cycles are used inside airbreathing jet engines?  


W) Otto 
X) Stirling 
Y) Brayton 
Z) Rankine  


ANSWER: Y) Brayton
## Tossup  


3) Math – Multiple Choice: Brian writes all of the integers from 1 to 100 inclusive on a whiteboard. How many times does he write the number 1?  


W) 18 
X) 19 
Y) 20 
Z) 21  


ANSWER: Z) 21  


## Bonus  


3) Math – Multiple Choice: Which of the following is logically equivalent to the saying, “If a student attends Enloe High School, then they are a nerd”?  


W) If a student does not attend Enloe High School, then they are not a nerd 
X) If a student is not a nerd, then they attend Enloe High School 
Y) If a student is a nerd, then they attend Enloe High School 
Z) If a student is not a nerd, then they do not attend Enloe High School  


ANSWER: Z
## Tossup  


4) Earth and Space – Multiple Choice: Which of the following minerals displays the highest hardness?  


W) Beryl [Beh-Ril] 
X) Hematite 
Y) Fluorite 
Z) Plagioclase [Play-jee-oh-claise]  


ANSWER: W) Beryl  


## Bonus  


4) Earth and Space – Multiple Choice: What is the name of the structure that is formed from sediments accreted onto the non-subducting tectonic plate at a convergent plate boundary?  


W) Shock diamond 
X) Accretionary wedge 
Y) Triple junction 
Z) Subduction triangle  


ANSWER: X) Accretionary wedge  


## Tossup  


5) Chemistry – Short Answer: Order the following 3 compounds in order of increasing boiling point:  


1) HF 
2) \(\mathrm{H}_2\mathrm{O}\) 3) \(\mathrm{NH}_3\)  


ANSWER: 3, 1, 2  


## Bonus  


5) Chemistry – Short Answer: What term describes the tendency of a reaction to favor one constitutional isomer over others?  


ANSWER: Regioselectivity
## Tossup  


6) Energy – Multiple Choice: Kaiwen is investigating the use of ionic substances as insulators for his high-voltage electronics. The breakdown voltage of ionic solids is roughly proportional to the lattice energy of that compound. Which of the following compounds would be best for him to use as an insulator?  


W) \(\mathrm{CaCl}_2\) X) \(\mathrm{AlCl}_3\) Y) \(\mathrm{MgO}\) Z) \(\mathrm{RbCl}\)  


ANSWER: Y) \(\mathrm{MgO}\)  


## Bonus  


6) Energy – Short Answer: Kaiwen is studying the effectiveness of different radioactive isotopes in nuclear bombs. He acquires a sample of Uranium-238 and begins to examine one atom of the sample. The atom undergoes alpha decay 3 times, beta minus decay 2 times, and gamma decay once. What is the atomic number and atomic mass, respectively, of the resulting atom?  


ANSWER: 88, 226 (ACCEPT: Atomic number 88 and Atomic mass 226)
## Tossup  


7) Biology – Multiple Choice: Which of the following groups of protists are multicellular?  


W) Parabasalids [pair-a-bay-suh-lids] 
X) Euglenids [you-glee-nids] 
Y) Diatoms 
Z) Brown Algae  


ANSWER: Z) Brown Algae  


## Bonus  


7) Biology – Short Answer: Identify all of the following 4 types of RNA that are involved in post-transcriptional RNA interference:  


I) tRNA 
II) miRNA 
III) siRNA 
IV) snRNA  


ANSWER: II, III  


## Tossup  


8) Chemistry – Short Answer: Colin, after driving to school on a cold day, gets out of his warm car and turns it off. The air inside the car begins to cool from being in contact with the cold outside air. Identify all of the following 3 statements that are true about the process:  


I) The entropy of the car's air increases 
II) The entropy of the outside air increases 
III) The entropy of the universe increases  


ANSWER: II and III  


## Bonus  


8) Chemistry – Short Answer: What is the formal charge on the nitrogen atom in nitrile oxide, which has a structural formula CNO?  


ANSWER: +1
## Tossup  


9) Earth and Space – Short Answer: Order the following 4 planets in order of increasing density:  


1) Mercury 
2) Earth 
3) Saturn 
4) Neptune  


ANSWER: 3, 4, 1, 2  


## Bonus  


9) Earth and Space – Short Answer: What is the term that refers to the rotating circumstellar disk of dense gas surrounding a young newly formed star?  


ANSWER: Protoplanetary Disk
## Tossup  


10) Physics – Short Answer: Identify all of the following 3 forces that are conservative:  


I) Gravitational force  
II) Electrostatic force  
III) Tension  


ANSWER: I and II  


## Bonus  


10) Physics – Short Answer: Brian places a 8 centimeter tall Genshin Impact figurine 20 centimeters from a lens with a focal length of 5 centimeters. How tall will the image of the figurine appear in centimeters?  


ANSWER: 8/3  


## Tossup  


11) Biology – Multiple Choice: Which of the following enzymes is the “rate limiter” of glycolysis?  


W) Hexokinase  
X) Aldolase  
Y) Phosphofructokinase  
Z) Phosphoglycerokinase [phospho-glycero-kinase]  


ANSWER: Y) Phosphofructokinase  


## Bonus  


11) Biology – Short Answer: Select all of the following three amino acids that have aromatic side chains:  


I) Tyrosine  
II) Proline  
III) Phenylalanine [feen-ill-al-an-een]  


ANSWER: I and III
## Tossup  


12) Math - Short Answer: There are two faucets in the bathroom. One drips every 6 seconds, and the other drips every 13 seconds. If the two faucets just dripped at the same time, how many seconds will pass before they both drip at the same time again?  


ANSWER: 78  


## Bonus  


12) Math - Short Answer: Kaiwen has 10 nuclear warheads labeled from 1 to 10. How many ways can Kaiwen choose 3 warheads to put on a MIRV such that no two labels of two chosen warheads are consecutive numbers?  


ANSWER: 56  


## Tossup  


13) Physics - Short Answer: The fine structure constant is the coupling constant for what fundamental force?  


ANSWER: Electromagnetic Force (ACCEPT: Electromagnetic Interaction)  


## Bonus  


13) Physics - Short Answer: Order the following 3 objects from smallest to largest moment of inertia about their perpendicular central axis:  


1) 1 kilogram hoop with radius 2 meters 
2) 4 kilogram disk with radius 1 meter 
3) 2 kilogram rod with length 3 meters  


ANSWER: 3, 2, 1
## Tossup  


14) Chemistry - Short Answer: What is the name of a common reagent used to distinguish between aldehydes and ketones, also used for silver mirroring?  


ANSWER: Tollens reagent  


## Bonus  


14) Chemistry - Short Answer: Which two decay mechanisms are most likely to occur in nuclei that are neutron deficient?  


ANSWER: Beta plus and electron capture  


## Tossup  


15) Math - Short Answer: What is the sum of the coefficients of the expanded form of \((x + y)^{10}\) [the quantity x plus y to the tenth power]?  


ANSWER: 1024  


## Bonus  


15) Math - Short Answer: Siddharth leaves home to go to school, driving at a constant speed of 60 miles per hour. When he is halfway there, he realizes that he is going to be late and drives the second half at a constant speed of 90 miles per hour. What was his average speed for the entire trip, in miles per hour?  


ANSWER: 72
## Tossup  


16) Energy - Short Answer: Scientists at Sandia National Lab are studying electron transitions in molecules. What process occurs when electrons are energized by incoming light and slowly transition back to the ground state through forbidden transitions?  


ANSWER: Phosphorescence  


## Bonus  


16) Energy - Short Answer: Scientists at NASA are using the James Webb Space telescope to create more detailed maps of the universe. Identify all of the following 3 methods which can be used to map spiral arms in galaxies:  


I) O and B associations  II) Carbon monoxide absorption lines  III) Emission nebulae  


ANSWER: All  


## Tossup  


17) Biology - Short Answer: List the following 3 parts of the heart electric system in order of activation during a regular heartbeat:  


1) AV Node  
2) Bundle of His  
3) SA Node  


ANSWER: 3, 1, 2  


## Bonus  


17) Biology - Short Answer: Identify all of the following 3 organisms that are triploblastic [trip-lo-blast-ic]:  


I) Frogs  II) Jellyfish  III) Sponges  


ANSWER: I only
## Tossup  


18) Physics - Short Answer: Identify all of the following 3 scenarios that would produce an electric field with a nonzero curl:  


I) A stationary point charge  II) A wire with a constant current flowing through it  III) A point charge moving with a constant nonzero acceleration  


ANSWER: III only  


## Bonus  


18) Physics - Short Answer: Two common units for size measurements are pounds and kilograms, which are related by a numeric factor of approximately 2.2 pounds per kilogram. In SI base units, what must be the units of this numeric factor?  


ANSWER: \(\mathrm{m / s^2}\) (meter per second squared)  


## Tossup  


19) Earth and Space - Short Answer: What is the name for the valley formed between two horses?  


ANSWER: Graben  


## Bonus  


19) Earth and Space - Short Answer: Order the following 3 noble gases in order of increasing abundance in the Earth's atmosphere:  


1) Neon 
2) Argon 
3) Xenon  


ANSWER: 3, 1, 2
## Tossup  


20) Math - Multiple Choice: Serena is making a poster in the shape of a rhombus. What is the area of her poster in square inches if the side length of it is 5 inches and shorter diagonal length is 6 inches?  


W) 15 
X) 24 
Y) 30 
Z) 48  


ANSWER: X) 24  


## Bonus  


20) Math - Multiple Choice: Andy is broke and decides to start saving money in his empty piggy bank. He inserts one dollar on Mondays, two dollars on Tuesdays, three dollars on Wednesdays, four dollars on Thursdays, five dollars on Fridays, six dollars on Saturdays, and seven dollars on Sundays. After 17 days of saving, he counts 71 dollars in his piggy bank. On what day of the week did he start saving money?  


W) Thursday 
X) Friday 
Y) Saturday 
Z) Sunday  


ANSWER: W) Thursday
## Tossup  


21) Biology – Short Answer: According to the ABC hypothesis, identify all of the following 3 genes that are expressed during the development of stamens:  


I) A II) B III) C  


ANSWER: II and III  


## Bonus  


21) Biology – Short Answer: Sieve tube elements are known to not have nuclei or any functioning organelles as their primary function is to transport sugars. Sieve tube elements receive resources from what other cells as a result  


ANSWER: Companion cells  


## Tossup  


22) Chemistry – Short Answer: How many radial and angular nodes, respectively, are in a 4p orbital?  


ANSWER: 2, 1  


## Bonus  


22) Chemistry – Multiple Choice: Serena is trying to make a buffer solution at pH 5.2 using her stock solutions of various bases and their conjugate acids. Which of the following \(\mathrm{K}_{\mathrm{b}}\) values should she use for her base to make the best buffer solution?  


W) \(3\mathrm{x}10^{-12}\) X) \(2\mathrm{x}10^{-9}\) Y) \(8\mathrm{x}10^{-6}\) Z) \(4\mathrm{x}10^{-3}\)  


ANSWER: X) \(2\mathrm{x}10^{-9}\)
## Tossup  


23) Earth and Space – Short Answer: Astronomers have discovered an alien civilization in the Trisolaris system, which has a parallax of 750 milliarcseconds. How many parsecs away is Trisolaris, to three significant figures?  


ANSWER: 1.33 parsecs  


## Bonus  


23) Earth and Space – Multiple Choice: The two moons of Kerbin, Mun and Minmus, have an apparent magnitude of \(-20.0\) and \(-12.0\), respectively. Which of the following is closest to the ratio of the brightness of Mun to the brightness of Minmus?  


W) 50 
X) 100 
Y) 500 
Z) 1000  


ANSWER: Z) 1000