title[[310, 230, 683, 300]]
ESBOT 

text[[416, 343, 576, 391]]
2023 

text[[420, 502, 570, 550]]
RR2sub_title[[464, 92, 533, 110]]
## Tossup  

text[[115, 110, 818, 146]]
1) Earth and Space – Short Answer: Identify all of the following 3 minerals which form primarily by precipitation from a solvent:  

text[[172, 161, 294, 214]]
I) Sulfur  II) Gypsum  III) Orthoclase  

text[[115, 229, 275, 246]]
ANSWER: I and II  

sub_title[[465, 247, 530, 265]]
## Bonus  

text[[115, 266, 804, 303]]
1) Earth and Space – Multiple Choice: The late heavy bombardment had which of the following effects on the geologic record from 4 to 3.8 billion years ago?  

text[[172, 317, 642, 389]]
W) It erased the geologic record  X) It added increased amounts of carbon to rocks produced  Y) It added large amounts of iron to the rocks produced  Z) It brought evidence of large scale shock metamorphism  

text[[115, 403, 470, 421]]
ANSWER: W) It erased the geologic record  

sub_title[[464, 491, 533, 509]]
## Tossup  

text[[115, 510, 820, 546]]
2) Chemistry – Short Answer: Order the following 3 types of intermolecular forces from weakest to strongest:  

text[[172, 562, 384, 616]]
1) Ion - induced dipole  
2) Dipole - induced dipole  
3) Dipole - dipole  

text[[115, 632, 265, 650]]
ANSWER: 2, 1, 3  

sub_title[[465, 688, 530, 706]]
## Bonus  

text[[115, 707, 868, 743]]
2) Chemistry – Short Answer: The standard reduction potentials of \(\mathrm{Cr}^{3 + }\) and \(\mathrm{Cr}^{2 + }\) are \(-0.74\) and \(-0.9\) , respectively. What is the standard reduction potential of the reaction \(\mathrm{Cr}^{2 + }\) yields \(\mathrm{Cr}^{3 + } + \mathrm{e}^{-}\) ?  

text[[115, 760, 257, 777]]
ANSWER: - 0.42sub_title[[463, 92, 533, 110]]
## Tossup  

text[[113, 111, 832, 146]]
3) Biology – Multiple Choice: Wobble base pairing is most likely to occur in which of the following cellular processes:  

text[[172, 163, 420, 234]]
W) DNA replication 
X) Transcription 
Y) Translation 
Z) Homologous recombination  

text[[115, 251, 330, 270]]
ANSWER: Y) Translation  

sub_title[[465, 312, 530, 330]]
## Bonus  

text[[115, 331, 875, 367]]
3) Biology – Short Answer: Identify all of the following 3 stages of cellular respiration that use substrate level phosphorylation:  

text[[172, 384, 407, 437]]
I) Glycolysis 
II) Krebs Cycle 
III) Electron Transport Chain  

text[[115, 453, 275, 471]]
ANSWER: I and II  

sub_title[[463, 526, 533, 545]]
## Tossup  

text[[115, 548, 831, 586]]
4) Math – Short Answer: How many lattice points does the equation \(x^{2} + y^{2} = 169\) pass through?  

text[[115, 603, 235, 621]]
ANSWER: 12  

sub_title[[465, 659, 530, 677]]
## Bonus  

text[[115, 679, 877, 715]]
4) Math – Short Answer: A triangle is formed by connecting the points (0, 0), (3, 4), and (2, -1). Rounded to the nearest tenth, what is the area of this triangle?  

text[[115, 731, 240, 749]]
ANSWER: 5.5sub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 844, 163]]
5) Energy – Multiple Choice: Scientists at the Joint Genomics Institute are studying the phylogeny of life. Which of the following life forms is not correctly paired with the period it formed in?  

text[[172, 180, 395, 250]]
W) Eukaryotes; Cambrian 
X) Land Plants; Ordovician 
Y) Vascular Plants; Silurian 
Z) Amphibians; Devonian  

text[[115, 267, 422, 285]]
ANSWER: W) Eukaryotes; Cambrian  

sub_title[[466, 320, 530, 338]]
## Bonus  

text[[115, 340, 844, 392]]
5) Energy – Multiple Choice: Researchers at Savannah River National Lab are studying the various different types of crustaceans that are found in the Savannah River. Which of the following statements about crustaceans is correct?  

text[[172, 409, 680, 480]]
W) Large crustaceans are called copepods 
X) Many small crustaceans are classified as decapods 
Y) The cuticles of decapods are hardened by calcium carbonate 
Z) Barnacles have a cuticle which is hardened by silica  

text[[115, 500, 708, 519]]
ANSWER: Y) The cuticles of decapods are hardened by calcium carbonatesub_title[[463, 92, 533, 110]]
## Tossup  

text[[113, 111, 855, 146]]
6) Physics - Multiple Choice: Which of the following thermodynamic cycles has the highest possible efficiency for a given temperature difference?  

text[[172, 163, 321, 235]]
W) Brayton Cycle 
X) Otto Cycle 
Y) Diesel Cycle 
Z) Carnot Cycle  

text[[115, 252, 344, 270]]
ANSWER: Z) Carnot Cycle  

sub_title[[466, 306, 530, 323]]
## Bonus  

text[[115, 326, 879, 378]]
6) Physics - Multiple Choice: A positively charged particle is slowly lowered into a neutral conducting soda can until it touches the bottom of the can. Which of the following best describes the charge on the outer surface of the can before and after the particle touches it?  

text[[172, 396, 385, 466]]
W) Positive, then negative 
X) Negative, then positive 
Y) Always positive 
Z) Always negative  

text[[115, 484, 369, 502]]
ANSWER: Y) Always positive  

sub_title[[463, 576, 533, 593]]
## Tossup  

text[[115, 595, 850, 629]]
7) Earth and Space - Short Answer: Along what track would a star of 2 solar masses evolve towards the main sequence?  

text[[115, 644, 528, 662]]
ANSWER: Hayashi track (ACCEPT: Henyey track)  

sub_title[[466, 680, 530, 697]]
## Bonus  

text[[115, 699, 848, 732]]
7) Earth and Space - Short Answer: Order the following three objects from least to greatest abundance in the universe:  

text[[173, 749, 378, 802]]
1) Active Galactic Nuclei 
2) Blazar 
3) Quasar  

text[[115, 818, 263, 835]]
ANSWER: 2, 3, 1sub_title[[463, 91, 534, 110]]
## Tossup  

text[[113, 112, 874, 152]]
8) Math - Short Answer: The function \(f(x) = ax^{2} + bx + c\) with \(b \neq 0\) has at least one real root for all values of \(c\). What is the value of \(a\) ?  

text[[115, 170, 226, 187]]
ANSWER: 0  

sub_title[[466, 225, 530, 243]]
## Bonus  

text[[113, 245, 840, 264]]
8) Math - Short Answer: What is the integral from 0 to \(16 / 3\) of \(x\) minus the floor of \(x\) dx?  

text[[115, 280, 251, 298]]
ANSWER: 23/9  

sub_title[[463, 370, 533, 389]]
## Tossup  

text[[115, 390, 852, 443]]
9) Energy - Multiple Choice: Researchers at Fermilab National Accelerator Facility are studying neutrinos. If A, B, and C are the mass states of the electron neutrino, muon neutrino, and tau neutrino respectively, which of the following statements is true?  

text[[172, 460, 648, 532]]
W) A less than B approximately equal to C  
X) A approximately equal to B less than C  
Y) A less than B less than C  
Z) Each neutrino flavor does not have a single defined mass  

text[[115, 548, 686, 567]]
ANSWER: Z) Each neutrino flavor does not have a single defined mass  

sub_title[[466, 603, 530, 621]]
## Bonus  

text[[115, 622, 877, 711]]
9) Energy - Multiple Choice: Researchers at Lawrence Berkeley National Lab are studying advanced computing methods and how they can solve real world problems. In the system of formal mathematics and logic commonly used today, there does not always exist an algorithm that can analyze another algorithm and correctly answer any yes-or-no question about it. What is the term for this property of a mathematical system?  

text[[172, 728, 330, 800]]
W) Incompleteness  
X) Inconsistency  
Y) Incomputability  
Z) Undecidability  

text[[115, 816, 355, 835]]
ANSWER: Z) Undecidabilitysub_title[[463, 92, 533, 110]]
## Tossup  

text[[112, 111, 844, 130]]
10) Chemistry – Short Answer: How many sigma and pi bonds exist in one molecule of \(\mathrm{S}_8\) ?  

text[[115, 146, 246, 164]]
ANSWER: 8, 0  

sub_title[[466, 201, 530, 218]]
## Bonus  

text[[115, 220, 842, 255]]
10) Chemistry – Short Answer: Identify all of the following crystal structures which have a coordination number of 12:  

text[[172, 273, 312, 343]]
I) HCP  II) FCC  III) BCC  IV) Simple cubic  

text[[115, 360, 275, 378]]
ANSWER: I, II, III  

sub_title[[463, 468, 533, 486]]
## Tossup  

text[[115, 486, 881, 521]]
11) Biology – Multiple Choice: Which of the following locations relative to a gene would be the most likely location of an enhancer?  

text[[172, 540, 521, 611]]
W) 10,000 base pairs downstream of a gene  X) 100 base pairs downstream of a gene  Y) 10 base pairs downstream of a gene  Z) 10 base pairs upstream of a gene  

text[[115, 628, 560, 646]]
ANSWER: W) 10,000 base pairs downstream of a gene  

sub_title[[466, 686, 530, 704]]
## Bonus  

text[[115, 705, 784, 740]]
11) Biology – Short Answer: Select all of the following 3 statements that are true of osmoregulation in fish:  

text[[172, 758, 876, 829]]
I) Sharks consume large amounts of seawater to offset osmotic water loss  II) Freshwater fish produce large quantities of dilute urine to remove excess water  III) When salmon move from freshwater to marine environments, a physiological change is induced where they produce more cells specialized to excrete salts  

text[[115, 848, 258, 865]]
ANSWER: II, IIIsub_title[[463, 92, 533, 110]]
## Tossup  

text[[114, 110, 861, 152]]
12) Math - Multiple Choice: Which of the following is not a possible value for the remainder when \(n^2\) is divided by 6 for an integer \(n\) ?  

text[[172, 170, 217, 241]]
W) 0 
X) 1 
Y) 2 
Z) 4  

text[[114, 258, 252, 276]]
ANSWER: Y) 2  

sub_title[[466, 312, 530, 330]]
## Bonus  

text[[114, 331, 881, 386]]
12) Math - Multiple Choice: The acceleration of a particle traveling along the x-axis is modeled by the equation \(a(t) = 6t + 4\) . If the initial velocity of the particle is 3 and the initial position is 4, which equation could model the position \(x(t)\) of the particle?  

equation[[171, 403, 377, 500]]
\[\mathrm{W)~}2t^{3} + 4t^{2} + 3t + 4\] \[\mathrm{X)~}2t^{3} + 4t^{2} + 4t + 3\] \[\mathrm{Y)~}t^{3} + 2t^{2} + 3t + 4\] \[\mathrm{Z)~}t^{3} + 2t^{2} + 4t + 3\]  

text[[114, 518, 400, 541]]
ANSWER: Y) \(t^{3} + 2t^{2} + 3t + 4\)sub_title[[463, 92, 533, 110]]
## Tossup  

text[[113, 111, 836, 145]]
13) Physics – Multiple Choice: A galvanometer is used to measure which of the following quantities?  

text[[172, 163, 315, 234]]
W) Voltage 
X) Current 
Y) Electric field 
Z) Magnetic field  

text[[115, 252, 302, 270]]
ANSWER: X) Current  

sub_title[[465, 307, 530, 324]]
## Bonus  

text[[115, 326, 839, 361]]
13) Physics – Short Answer: In the collision and annihilation of an electron and a positron, identify all of the following 3 quantities that are conserved:  

text[[172, 379, 330, 432]]
I) Momentum 
II) Energy 
III) Lepton number  

text[[115, 448, 241, 466]]
ANSWER: All  

sub_title[[463, 540, 533, 558]]
## Tossup  

text[[115, 559, 840, 593]]
14) Chemistry – Short Answer: Identify all of the following 3 traits that would increase the acidity of an organic hydrogen atom:  

text[[172, 610, 488, 664]]
I) C-H bond with high S character 
II) Resonance in the acid molecule 
III) Halogenation of the primary carbon  

text[[115, 681, 280, 699]]
ANSWER: I, II, III  

sub_title[[465, 735, 530, 753]]
## Bonus  

text[[115, 755, 800, 773]]
14) Chemistry – Short Answer: Order the following 3 ions in terms of increasing size:  

text[[172, 790, 222, 842]]
1) H 
2) F 
3) CI  

text[[115, 860, 264, 878]]
ANSWER: 2, 1, 3sub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 110, 832, 146]]
15) Earth and Space – Short Answer: Order the following 3 earthquake waves in order of increasing amplitude:  

text[[173, 161, 293, 214]]
1) Love waves 
2) P waves 
3) S waves  

text[[115, 229, 264, 247]]
ANSWER: 2, 3, 1  

sub_title[[466, 264, 530, 281]]
## Bonus  

text[[115, 282, 812, 319]]
15) Earth and Space – Short Answer: Order the following 4 extrusive igneous rocks by increasing density:  

text[[173, 333, 270, 403]]
1) Pumice 
2) Obsidian 
3) Scoria 
4) Tachylite  

text[[115, 418, 285, 437]]
ANSWER: 1, 3, 2, 4  

sub_title[[463, 490, 533, 509]]
## Tossup  

text[[115, 510, 875, 580]]
16) Energy – Short Answer: Researchers at Argonne National Lab are researching ways to make paper recycling more energy efficient. One of the first steps of paper recycling is chemical pulping, where basic solvents are used to cleave the bonds between what two carbohydrate polymers?  

text[[115, 597, 377, 615]]
ANSWER: Lignin and cellulose  

sub_title[[466, 652, 530, 670]]
## Bonus  

text[[115, 671, 857, 742]]
16) Energy – Multiple Choice: Researchers at Pacific Northwest National Lab are studying ways to improve the efficiency of electroplating processes. After electroplating, extra metal in solution is often precipitated out to be reused in later batches. Which of the following solutes would be best to precipitate silver ions out of solution?  

text[[173, 758, 282, 830]]
W) \(\mathrm{Ba(NO_3)_2}\) X) \(\mathrm{Al_2(SO_4)_3}\) Y) \(\mathrm{NH_4F}\) Z) \(\mathrm{CrBr_2}\)  

text[[115, 847, 285, 865]]
ANSWER: Z) \(\mathrm{CrBr_2}\)sub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 110, 877, 170]]
17) Physics - Multiple Choice: The force exerted by a spring on some block as a function of displacement follows the relation \(F = 5x^{2}\) . If a block is attached to the end of the spring and the spring is compressed 1 meter, how much work is done by the spring on the block?  

text[[172, 186, 297, 260]]
W) - 4/3 Joules 
X) - 5/3 Joules 
Y) - 2 Joules 
Z) - 7/3 Joules  

text[[115, 276, 327, 294]]
ANSWER: X) - 5/3 Joules  

sub_title[[465, 330, 530, 348]]
## Bonus  

text[[115, 350, 859, 402]]
17) Physics - Short Answer: Rohit connects two balls with mass 4 kilograms and 1 kilogram with a string and hangs them over a pulley. When he releases the balls and lets the pulley spin, what is the acceleration of the balls to the nearest meter per second squared?  

text[[115, 418, 226, 436]]
ANSWER: 6  

sub_title[[463, 510, 533, 528]]
## Tossup  

text[[115, 529, 863, 564]]
18) Earth and Space - Short Answer: Radio emission from active galactic nuclei results from what parts of the celestial object?  

text[[115, 579, 245, 597]]
ANSWER: Jets  

sub_title[[465, 614, 530, 631]]
## Bonus  

text[[115, 633, 868, 667]]
18) Earth and Space - Short Answer: Identify all of the following 3 statements that are true of quasars:  

text[[172, 684, 549, 737]]
I) They only formed in the early universe 
II) Quasars are a type of Seyfert galaxy 
III) Quasars contain a Black hole at their center  

text[[115, 752, 275, 770]]
ANSWER: III onlysub_title[[463, 92, 533, 110]]
## Tossup  

text[[113, 111, 880, 146]]
19) Biology - Multiple Choice: Parenchyma tissue provides which of the following functions in a plant?  

text[[172, 163, 434, 234]]
W) Provides mechanical support 
X) Conducts photosynthesis 
Y) Forms bark 
Z) Forms xylem  

text[[115, 252, 438, 270]]
ANSWER: X) Conducts photosynthesis  

sub_title[[466, 306, 530, 324]]
## Bonus  

text[[115, 326, 880, 378]]
19) Biology - Multiple Choice: Which of the following sequences correctly describes the changes in osmolarity of filtrate as it passes through the nephron from the descending limb of the loop of Henle to the ascending limb of the loop of Henle?  

text[[172, 396, 401, 466]]
W) Decreases then increases 
X) Increases then decreases 
Y) Decreases 
Z) Increases  

text[[115, 485, 433, 502]]
ANSWER: X) Increases then decreases  

sub_title[[463, 558, 533, 576]]
## Tossup  

text[[115, 577, 878, 629]]
20) Math - Short Answer: Point C is chosen at random on a square table with side length 8 feet. Point C will then become the center of a circle with radius 1.5 feet. What is the probability that the circle is entirely on the table and no part of the circle is hanging over any edge?  

text[[115, 646, 260, 664]]
ANSWER: 25/64  

sub_title[[466, 701, 530, 718]]
## Bonus  

text[[115, 720, 841, 755]]
20) Math - Multiple Choice: Given that March 26, 2023 falls on a Sunday, what day of the week does March 26, 2050 fall on?  

text[[172, 773, 291, 844]]
W) Monday 
X) Wednesday 
Y) Friday 
Z) Saturday  

text[[115, 862, 309, 880]]
ANSWER: Z) Saturdaysub_title[[463, 92, 533, 110]]
## Tossup  

text[[113, 111, 848, 146]]
21) Chemistry – Multiple Choice: Which of the following best describes how the density of metals changes moving left to right across a period?  

text[[172, 163, 400, 234]]
W) Increases 
X) Decreases 
Y) Increases, then decreases 
Z) Decreases, then increases  

text[[115, 252, 439, 270]]
ANSWER: Y) Increases, then decreases  

sub_title[[466, 307, 530, 324]]
## Bonus  

text[[115, 326, 872, 361]]
21) Chemistry – Multiple Choice: Which of the following analysis techniques is most useful to determine the concentration of a compound with a wide endpoint range?  

text[[172, 379, 396, 450]]
W) Back titration 
X) Iodometry 
Y) Conductometric titration 
Z) Liquid chromatography  

text[[115, 467, 354, 485]]
ANSWER: W) Back titrationsub_title[[463, 92, 533, 110]]
## Tossup  

text[[113, 110, 843, 147]]
22) Physics - Short Answer: Identify all of the following 3 changes that would increase the spacing between fringes projected on a wall by passing light through a double slit:  

text[[172, 163, 425, 216]]
I) Increase slit spacing  II) Increase wavelength of light  III) Increase distance to wall  

text[[115, 232, 287, 250]]
ANSWER: II and III  

sub_title[[466, 289, 530, 306]]
## Bonus  

text[[115, 307, 870, 360]]
22) Physics - Multiple Choice: A newly discovered planet is found in the solar system. If the orbital period of the planet is 10 Earth years, then in astronomical units, what is the length of its major axis?  

text[[172, 377, 236, 448]]
W) 2.4  X) 9.3  Y) 20.0  Z) 31.6  

text[[115, 465, 265, 484]]
ANSWER: X) 9.3  

sub_title[[463, 540, 533, 558]]
## Tossup  

text[[113, 558, 877, 592]]
23) Biology - Short Answer: Identify all of the following 3 characteristics that are derived traits of plants:  

text[[172, 610, 414, 663]]
I) Apical meristems  II) Walled spores  III) Alternation of generations  

text[[115, 680, 241, 697]]
ANSWER: All  

sub_title[[466, 735, 530, 753]]
## Bonus  

text[[113, 754, 847, 789]]
23) Biology - Short Answer: Identify all of the following 3 organisms that follow a Type III survivorship curve  

text[[172, 807, 266, 859]]
I) Humans  II) Birds  III) Lizards  

text[[115, 877, 258, 894]]
ANSWER: None