title[[310, 229, 685, 300]]
ESBOT 

text[[416, 343, 576, 391]]
2023 

text[[420, 501, 570, 550]]
RR3sub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 850, 163]]
1) Biology - Short Answer: A man with red-green colorblindness marries a woman who is a carrier for red-green colorblindness. If they have a son and a daughter, what is the probability that the son has red-green colorblindness but the daughter does not?  

text[[115, 180, 379, 199]]
ANSWER: 0.25 (ACCEPT: 1/4)  

sub_title[[465, 236, 530, 254]]
## Bonus  

text[[115, 255, 866, 291]]
1) Biology - Short Answer: Identify all of the following 3 immune cells which can function as antigen-presenting cells to activate Helper T cells:  

text[[173, 308, 323, 361]]
I) Neutrophils II) Mast cells III) Dendritic cells  

text[[115, 377, 275, 396]]
ANSWER: III only  

sub_title[[463, 451, 533, 469]]
## Tossup  

text[[115, 470, 810, 505]]
2) Math - Multiple Choice: What is the 2023rd digit following the decimal point in the expansion of \(3 / 7\) ?  

text[[173, 523, 215, 594]]
W) 1 X) 2 Y) 4 Z) 8  

text[[115, 611, 247, 629]]
ANSWER: Y) 4  

sub_title[[465, 666, 530, 684]]
## Bonus  

text[[115, 685, 841, 721]]
2) Math - Multiple Choice: What is the radius of convergence for the series [fraction with numerator x to the power of n and denominator n factorial]?  

text[[173, 738, 215, 811]]
W) 0 X) 1 Y) e Z) Infinity  

text[[115, 827, 293, 845]]
ANSWER: Z) Infinitysub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 857, 163]]
3) Energy – Short Answer: Scientists at the Center for Applied Geosciences are studying the role of bacteria in the formation of paleoclimate records. What patterns in marine sedimentary rock, indicative of oxygenation, have alternating layers of iron oxide and chert?  

text[[115, 181, 402, 198]]
ANSWER: Banded iron formations  

sub_title[[466, 236, 530, 253]]
## Bonus  

text[[115, 255, 872, 308]]
3) Energy – Short Answer: Scientists at Fermilab are working on the development of particle detectors. What type of particle detector, which was used in the discovery of the positron, uses a supersaturated vapor to create a track around the path of a particle moving through it?  

text[[115, 324, 333, 342]]
ANSWER: Cloud chamber  

sub_title[[463, 415, 533, 433]]
## Tossup  

text[[115, 434, 839, 469]]
4) Earth and Space – Multiple Choice: At which of the following plate boundaries could a fold-thrust belt form?  

text[[173, 485, 444, 556]]
W) Continental Rift  
X) Ocean-Continent Convergence  
Y) Mid-Ocean Ridge  
Z) Transform Boundary  

text[[115, 570, 484, 588]]
ANSWER: X) Ocean-Continent Convergence  

sub_title[[466, 605, 530, 622]]
## Bonus  

text[[115, 623, 848, 659]]
4) Earth and Space – Short Answer: Identify all of the following 3 rocks that can be formed through contact metamorphism:  

text[[173, 685, 281, 737]]
I) Marble  
II) Phyllite  
III) Quartzite  

text[[115, 763, 280, 781]]
ANSWER: I and IIIsub_title[[463, 92, 533, 110]]
## Tossup  

text[[114, 111, 879, 180]]
5) Physics - Short Answer: A wire with a 2 centimeter radius has some uniform current density J. The magnetic field at a distance of 1 centimeter from the center of the wire has a magnitude of 2 milliteslas. What is the magnetic field in milliteslas at a distance of 3 centimeters from the center of the wire?  

text[[115, 198, 235, 215]]
ANSWER: 8/3  

sub_title[[466, 252, 530, 271]]
## Bonus  

text[[114, 273, 876, 331]]
5) Physics - Short Answer: Stefan-Boltzmann's Law states that \(L = A\sigma T^{4}\) [L equals A times sigma times T to the fourth], where \(\sigma\) is the Stefan-Boltzmann constant and \(A\) is an area. If \(L\) is a value in watts, then what are the base SI units for \(\sigma\) ?  

text[[115, 350, 870, 373]]
ANSWER: \(kg \cdot s^{-3} \cdot K^{-4}\) (ACCEPT: kilograms per seconds cubed times Kelvin to the fourth)  

sub_title[[463, 445, 533, 464]]
## Tossup  

text[[114, 465, 875, 501]]
6) Chemistry - Short Answer: A certain diatomic compound has 5 electrons in bonding orbitals and 2 electrons in antibonding orbitals. What is the bond order of this compound?  

text[[115, 517, 240, 535]]
ANSWER: 1.5  

sub_title[[466, 572, 530, 590]]
## Bonus  

text[[114, 591, 872, 679]]
6) Chemistry - Short Answer: Cisplatin is a common cancer treatment compound that must be activated by reacting with water molecules before it can act on DNA. The reaction between cisplatin and water is first-order in cisplatin concentration. If 0.2 Molar cisplatin begins reacting at a rate of 0.14 Molar per second, what is the half-life of this reaction in seconds to one significant figure?  

text[[115, 697, 224, 714]]
ANSWER: 1sub_title[[463, 92, 533, 110]]
## Tossup  

text[[114, 110, 838, 163]]
7) Math - Multiple Choice: Andy deposits 100 dollars in his empty savings account. If the yearly interest rate is \(2\%\) and his money is compounded annually, which of the following is closest to the number of years it will take for his money to become 400 dollars?  

text[[172, 181, 230, 252]]
W) 35 
X) 50 
Y) 70 
Z) 100  

text[[114, 270, 262, 288]]
ANSWER: Y) 70  

sub_title[[466, 325, 530, 342]]
## Bonus  

text[[114, 343, 870, 380]]
7) Math - Multiple Choice: Consider a rectangle ABCD with \(\mathrm{AB} = 10\) and \(\mathrm{BC} = 5\) . If line X is drawn from C to the midpoint of AB, what is the shortest distance from B to line X?  

text[[172, 397, 264, 488]]
W) \(5\sqrt{2}\) X) \(5\sqrt{2} /2\) Y) \(10\sqrt{2}\) Z) \(10\sqrt{2} /3\)  

text[[114, 506, 295, 526]]
ANSWER: X) \(5\sqrt{2} /2\)sub_title[[463, 108, 533, 127]]
## Tossup  

text[[113, 127, 845, 163]]
8) Biology – Multiple Choice: Which of the following kinds of defensive adaptation is used when a snake deters potential predators using bright coloration?  

text[[172, 181, 383, 253]]
W) Cryptic Coloration 
X) Mullerian Coloration 
Y) Sematic Coloration 
Z) Aposematic Coloration  

text[[115, 270, 422, 288]]
ANSWER: Z) Aposematic Coloration  

sub_title[[466, 325, 530, 342]]
## Bonus  

text[[113, 344, 863, 378]]
8) Biology – Short Answer: Identify all of the following 3 organelles that are types of reduced mitochondria:  

text[[172, 397, 330, 450]]
I) Glyoxysome 
II) Hydrogenosome 
III) Mitosome  

text[[115, 467, 258, 484]]
ANSWER: II, IIIsub_title[[463, 92, 533, 110]]
## Tossup  

text[[114, 111, 860, 198]]
9) Energy - Multiple Choice: Researchers at Enloe High School are collecting data to determine whether or not squirrels have a preference for the color of acorns that they eat. Data was collected by placing a white acorn and a black acorn next to each other for a day. Which statistical analysis method should be used to determine the likelihood of random variation causing the results in the data?  

text[[172, 216, 394, 286]]
W) Correlation  X) Chi-square [kai-square]  Y) Interquartile range  Z) Percent change  

text[[115, 304, 328, 322]]
ANSWER: X) Chi-square  

sub_title[[466, 360, 530, 377]]
## Bonus  

text[[115, 378, 875, 431]]
9) Energy - Short Answer: Researchers at Oak Ridge National Lab are studying the formation of cleavage furrows in dividing cells in order to develop drugs to fight cancer. What cytoskeletal element are they most likely targeting?  

text[[115, 448, 480, 466]]
ANSWER: Actin (ACCEPT: microfilaments)  

sub_title[[463, 522, 533, 540]]
## Tossup  

text[[115, 541, 865, 576]]
10) Chemistry - Short Answer: What is the general term for intermolecular forces which have potentials that vary with intermolecular distance to the negative sixth power?  

text[[115, 593, 696, 611]]
ANSWER: Van Der Waals forces (ACCEPT: London Dispersion Forces)  

sub_title[[466, 648, 530, 665]]
## Bonus  

text[[115, 667, 870, 701]]
10) Chemistry - Multiple Choice: Which of the following types of groups does not exist for an electrophilic aromatic substitution?  

text[[172, 720, 455, 790]]
W) Activating ortho-para director  X) Deactivating ortho-para director  Y) Activating meta director  Z) Deactivating meta director  

text[[115, 809, 433, 826]]
ANSWER: Y) Activating meta directorsub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 110, 875, 146]]
11) Earth and Space – Short Answer: Order the following 3 fundamental forces from earliest to latest occurrence in the universe:  

text[[173, 161, 258, 215]]
1) Weak 
2) Strong 
3) Gravity  

text[[115, 229, 263, 247]]
ANSWER: 3, 2, 1  

sub_title[[465, 264, 530, 282]]
## Bonus  

text[[115, 283, 850, 319]]
11) Earth and Space – Short Answer: Rishabh looks at the sky in the morning 1 hour before sunrise, and he sees the moon rising in the east. What is the phase of the moon?  

text[[115, 333, 346, 352]]
ANSWER: Waning crescent  

sub_title[[463, 405, 533, 423]]
## Tossup  

text[[115, 423, 877, 442]]
12) Biology – Short Answer: The glyoxylate cycle is a variation of what other metabolic cycle?  

text[[115, 458, 830, 495]]
ANSWER: Krebs Cycle (ACCEPT: Citric Acid Cycle, Tricarboxylic Acid Cycle, or TCA Cycle)  

sub_title[[465, 530, 530, 548]]
## Bonus  

text[[115, 549, 778, 567]]
12) Biology – Short Answer: Order the following 3 hormones in order of secretion:  

text[[173, 584, 237, 636]]
1) T3 
2) TSH 
3) TRH  

text[[115, 654, 263, 672]]
ANSWER: 3, 2, 1sub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 839, 163]]
13) Physics – Short Answer: In superconductors, Cooper pairs are pairs of electrons bound together at low temperatures. Cooper pairs arise from the interaction of electrons with what quasiparticle, which represents the collective movement of the metal ion lattice?  

text[[115, 181, 270, 198]]
ANSWER: Phonon  

sub_title[[466, 235, 530, 253]]
## Bonus  

text[[115, 254, 877, 307]]
13) Physics – Short Answer: How many nodes and antinodes, respectively, are on the pressure wave produced by a 2 meter tube with one end closed that is resonating with a wavelength of 1.6 meters?  

text[[115, 324, 377, 342]]
ANSWER: 3 nodes, 3 antinodes  

sub_title[[463, 415, 533, 433]]
## Tossup  

text[[115, 434, 833, 470]]
14) Chemistry – Short Answer: Order the following 4 elements in order of increasing first ionization energy:  

text[[173, 487, 264, 556]]
1) Oxygen 
2) Fluorine 
3) Neon 
4) Sodium  

text[[115, 574, 284, 591]]
ANSWER: 4, 1, 2, 3  

sub_title[[466, 610, 530, 628]]
## Bonus  

text[[115, 630, 879, 666]]
14) Chemistry – Multiple Choice: Assuming that the ligands of a square planar compound lie in the xy plane, which of the following d orbitals would have the highest energy?  

text[[172, 683, 499, 755]]
W) \(\mathrm{d_{xy}}\) [d x y] 
X) \(\mathrm{d_{xz}}\) [d x z] 
Y) \(\mathrm{d_{z}^{2}}\) [d z squared] 
Z) \(\mathrm{d_{x^{-}y}^{2}}\) [d x squared minus y squared]  

text[[115, 771, 277, 790]]
ANSWER: Z) \(\mathrm{d_{x^{-}y}^{2}}\)sub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 872, 146]]
15) Math - Multiple Choice: Which of the following most accurately defines the coefficient of determination?  

text[[172, 162, 875, 288]]
W) It describes how correlated the dependent variable is to the independent variable 
X) It describes how much of the variance in the independent variable can be attributed to the dependent variable 
Y) It describes how much of the variance in the dependent variable can be attributed to the independent variable 
Z) It describes how much of the variance in both the independent and dependent variable can be attributed to an external factor  

text[[115, 305, 224, 322]]
ANSWER: Y  

sub_title[[466, 360, 530, 377]]
## Bonus  

text[[115, 378, 844, 415]]
15) Math - Short Answer: Sphere A has a volume of \(36\pi\) cubic meters. If the radius of A is increased by 2 meters, by how many square meters does the surface area of A increase by?  

text[[115, 431, 247, 449]]
ANSWER: \(64\pi\)  

sub_title[[463, 504, 533, 523]]
## Tossup  

text[[115, 523, 863, 576]]
16) Physics - Short Answer: If the electric field at a distance of 1 meter from an infinite charged sheet is 3 Volts per meter, by what factor will the electric field change if measured at a distance of 3 meters?  

text[[115, 593, 224, 610]]
ANSWER: 1  

sub_title[[466, 649, 530, 667]]
## Bonus  

text[[115, 668, 866, 738]]
16) Physics - Multiple Choice: Andy completely submerges a block of ice in a glass of water. He observes the height of the water in the glass. Then, he microwaves the glass, causing the ice to melt into water. Assuming evaporation is negligible, which of the following statements is accurate afterwards?  

text[[172, 755, 803, 828]]
W) The height of the water increases and the temperature of the water increases 
X) The height of the water increases and the temperature of the water decreases 
Y) The height of the water decreases and the temperature of the water increases 
Z) The height of the water decreases and the temperature of the water decreases  

text[[115, 844, 840, 863]]
ANSWER: Y) The height of the water decreases and the temperature of the water increasessub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 111, 840, 163]]
17) Energy – Short Answer: Researchers at Savannah River National Lab are studying the effects that excess chlorine can have on water health. Order the following 3 chlorine species from least acidic to most acidic:  

text[[173, 181, 251, 234]]
1) \(\mathrm{HClO_3}\) 2) HCl 3) \(\mathrm{ClO_4^-}\)  

text[[115, 250, 265, 268]]
ANSWER: 3, 1, 2  

sub_title[[465, 304, 530, 322]]
## Bonus  

text[[115, 325, 863, 394]]
17) Energy – Short Answer: PCR is a very widely-used laboratory technique that uses the mechanisms of DNA transcription to amplify and clone selected DNA segments. However, human DNA polymerase cannot be used in this process due to its lack of heat-resistance. What DNA polymerase is used instead?  

text[[115, 411, 560, 430]]
ANSWER: Taq polymerase (ACCEPT: Pfu polymerase)  

sub_title[[463, 483, 533, 501]]
## Tossup  

text[[115, 503, 877, 555]]
18) Chemistry – Short Answer: If the ionization energy of \(\mathrm{H}^-\) is 74 kilojoules per mol and the electron affinity of \(\mathrm{H}^+\) is 1310 kilojoules per mol, what is the enthalpy change in kilojoules when one mole of \(\mathrm{H}^+\) is turned into \(\mathrm{H}^-\) ?  

text[[115, 573, 261, 590]]
ANSWER: - 1384  

sub_title[[465, 628, 530, 645]]
## Bonus  

text[[115, 647, 877, 682]]
18) Chemistry – Short Answer: What period 4 element would have the highest ratio between its second ionization energy and its first ionization energy?  

text[[115, 699, 296, 716]]
ANSWER: Potassiumsub_title[[463, 92, 533, 110]]
## Tossup  

text[[115, 110, 864, 146]]
19) Earth and Space – Short Answer: What is the name for the phenomenon that occurs when precipitation evaporates before hitting the ground?  

text[[115, 160, 420, 179]]
ANSWER: Virga (Accept: dry storm)  

sub_title[[465, 196, 530, 213]]
## Bonus  

text[[115, 214, 848, 250]]
19) Earth and Space – Short Answer: Identify all of the following 3 conditions which result from the El Niño:  

text[[172, 265, 472, 319]]
I) Drought in western Australia  II) Downwelling off the coast of Peru  III) Cyclogenesis near Brazil  

text[[115, 333, 274, 351]]
ANSWER: I and II  

sub_title[[463, 405, 533, 423]]
## Tossup  

text[[115, 424, 878, 478]]
20) Physics – Short Answer: Two objects with equal mass \(M\) experience a gravitational force of \(G\) . If the mass of each of the two objects is doubled and the distance between them is tripled, what is the new gravitational force in terms of \(G\) ?  

text[[115, 495, 260, 513]]
ANSWER: 4/9 G  

sub_title[[465, 551, 530, 568]]
## Bonus  

text[[115, 569, 877, 657]]
20) Physics – Short Answer: Rohit has just bought a brand new sledgehammer with a 4 kg head on the end of a uniform handle. He wants to calculate the mass of the entire sledgehammer, but he does not know the mass of the handle. By balancing the sledgehammer and using a meter stick, he is able to find that the entire handle has a length of 1 meter and the center of mass lies 0.1 meters from the head. What is the mass of the entire sledgehammer?  

text[[115, 675, 251, 693]]
ANSWER: 5 kgsub_title[[463, 92, 533, 110]]
## Tossup  

text[[113, 111, 760, 131]]
21) Math - Short Answer: What is the value of \(\log (24) + \log (250) - \log (6)\) ?  

text[[115, 147, 225, 165]]
ANSWER: 3  

sub_title[[466, 202, 530, 220]]
## Bonus  

text[[115, 221, 865, 258]]
21) Math - Short Answer: What is the inverse of the 2 by 2 matrix [with top row three seven and bottom row two five]?  

text[[115, 273, 754, 293]]
ANSWER: Top row 5, - 7 and bottom row - 2, 3 (ACCEPT: equivalent matrices)  

sub_title[[463, 346, 533, 365]]
## Tossup  

text[[115, 365, 876, 401]]
22) Biology - Multiple Choice: VDJ Recombination primarily occurs in which of the following types of cells?  

text[[173, 418, 308, 490]]
W) Erythrocytes 
X) Fibroblasts 
Y) Lymphocytes 
Z) Osteoblasts  

text[[115, 507, 348, 525]]
ANSWER: Y) Lymphocytes  

sub_title[[466, 561, 530, 579]]
## Bonus  

text[[115, 580, 875, 616]]
22) Biology - Multiple Choice: If a low concentration solution of auxin was sprayed on the left side of a growing plant stem, how will the growth of the stem change?  

text[[173, 633, 460, 650]]
W) The stem will bend to the left.  

text[[173, 652, 444, 669]]
X) The stem will bend to the right.  

text[[173, 670, 465, 687]]
Y) Vertical growth rate will increase.  

text[[173, 688, 399, 705]]
Z) Vertical growth will stop.  

text[[115, 722, 486, 740]]
ANSWER: X) The stem will bend to the right.sub_title[[463, 92, 533, 110]]
## Tossup  

text[[113, 110, 865, 146]]
23) Earth and Space – Multiple Choice: At which of the following times of day would you be most likely to see Mercury in the sky?  

text[[173, 161, 323, 231]]
W) Dawn  X) Noon  Y) Late Afternoon  Z) Midnight  

text[[115, 246, 293, 264]]
ANSWER: W) Dawn  

sub_title[[465, 281, 530, 299]]
## Bonus  

text[[115, 300, 828, 335]]
23) Earth and Space – Short Answer: Which of the following occurs as the sunspot cycle progresses?  

text[[173, 351, 544, 420]]
W) The Sun's magnetic field strength reduces  X) The Sun's magnetic field strength increases  Y) New sunspots form at lower latitudes  Z) New sunspots form at higher latitudes  

text[[115, 435, 535, 454]]
ANSWER: Y) New sunspots form at lower latitudes