
ESBOT 


2023 


RR4
## Tossup  


1) Physics – Short Answer: Muons are unstable and have a rest lifetime of about 2.2 microseconds. In the most common form of muon decay, the products are an electron and what two specific other particles?  


ANSWER: Muon neutrino and electron antineutrino (DO NOT ACCEPT: only neutrino/antineutrino)  


## Bonus  


1) Physics – Short Answer: Two sinusoidal voltage signals with RMS voltage of 120 Volts are added together 90 degrees out of phase. What is the peak voltage of the resulting signal?  


ANSWER: 240  


## Tossup  


2) Earth and Space – Short Answer: Which of the following sedimentary rocks displays the poorest sorting?  


W) Diamictite 
X) Arkose 
Y) Coquina 
Z) Shale  


ANSWER: W) Diamictite  


## Bonus  


2) Earth and Space – Multiple Choice: In which of the following conditions would an observer in Australia experience the highest tidal range?  


W) Lunar periapsis [pair-ee-ap-sis] but not syzygy [siz-i-jee] in January 
X) Lunar syzygy but not periapsis in January 
Y) Lunar periapsis but not syzygy in June 
Z) Lunar syzygy but not periapsis in June  


ANSWER: X) Lunar syzygy but not periapsis in January
## Tossup  


3) Chemistry - Multiple Choice: Trouton's rule states that all liquids have approximately the same entropy of vaporization. Which of the following phenomena would lead to a negative deviation from the expected entropy of vaporization?  


W) Association of molecules in the liquid phase 
X) Association of molecules in the gas phase 
Y) Dissociation of molecules in the liquid phase 
Z) Dissociation of molecules in the gas phase  


ANSWER: X) Association of molecules in the gas phase  


## Bonus  


3) Chemistry - Short Answer: For an endothermic reaction in equilibrium, how do the rates of the forward and reverse reaction change, respectively, when temperature is increased?  


ANSWER: Increase, increase (ACCEPT: Both increase)  


## Tossup  


4) Physics - Multiple Choice: Which of the following quantities cannot be expressed as a cross product of two other quantities?  


W) Torque 
X) Angular momentum 
Y) Power 
Z) Magnetic force  


ANSWER: Y) Power  


## Bonus  


4) Physics - Multiple Choice: Kaiwen is making measurements on a quantum system. He repeatedly makes measurements on the system, causing it to essentially be frozen in the same quantum state. Which of the following is the best name for this effect?  


W) Quantum Decoherence 
X) Schrodinger effect 
Y) Quantum Zeno Effect 
Z) Wave Function collapse  


ANSWER: Y) Quantum Zeno Effect
## Tossup  


5) Biology - Short Answer: Order the following 3 parts of the cardiac cycle from earliest to latest:  


1) Q 
2) T 
3) S  


ANSWER: 1, 3, 2  


## Bonus  


5) Biology - Multiple Choice: Which of the following statements about protein secondary structures is not true?  


W) Antiparallel beta pleated sheets tend to be stronger than parallel beta pleated sheets 
X) Alpha helices form hydrogen bonds every 4th residue 
Y) The cores of many globular proteins are composed of beta pleated sheets 
Z) Salt bridges commonly stabilize secondary structures of proteins  


ANSWER: Z) Salt bridges commonly stabilize secondary structures of proteins  


## Tossup  


6) Chemistry - Short Answer: What is the molecular geometry around the Aluminum atoms in \(\mathrm{Al}_{2} \mathrm{Cl}_{6}\) ?  


ANSWER: Tetrahedral  


## Bonus  


6) Chemistry - Multiple Choice: Rohit would like to conduct a redox titration using \(\mathrm{H}_{2} \mathrm{O}_{2}\) as the titrant and an unknown solution of \(\mathrm{KMnO}_{4}\) and \(\mathrm{H}_{2} \mathrm{SO}_{4}\) as the analyte. He uses ACS grade \(\mathrm{H}_{2} \mathrm{O}_{2}\) labeled with a concentration of \(35\%\) that has been sitting on his shelf for the past year and calculates the \(\mathrm{KMnO}_{4}\) concentration using this \(35\%\) figure. Which of the following statements about Rohit's experimental process is true?  


W) His process has no errors 
X) His error would decrease his predicted \(\mathrm{KMnO}_{4}\) concentration 
Y) His error would increase his predicted \(\mathrm{KMnO}_{4}\) concentration 
Z) His error would not affect his predicted \(\mathrm{KMnO}_{4}\) concentration  


ANSWER: Y) His error would increase his predicted \(\mathrm{KMnO}_{4}\) concentration
## Tossup  


7) Math – Short Answer: If an equilateral triangle has the same area as a regular hexagon, then what is the square of the ratio of the side length of the equilateral triangle to the side length of the regular hexagon?  


ANSWER: 6  


## Bonus  


7) Math – Short Answer: Andy, Brandon, Colin, Derek, and Emily go to the movies to watch Avatar 2 together. They are given five seats in one row, and can choose where they sit. However, Andy and Brandon are best friends and want to sit next to each other. How many ways can they sit in the five seats?  


ANSWER: 48  


## Tossup  


8) Earth and Space – Multiple Choice: Which of the following is closest to the surface pressure on Mercury in Pascals?  


W) 0 X) 1 Y) 100 Z) 10,000  


ANSWER: W) 0  


## Bonus  


8) Earth and Space – Multiple Choice: Which of the following is closest to the moon’s albedo?  


W) 0.1 X) 0.3 Y) 0.5 Z) 0.7  


ANSWER: W) 0.1
## Tossup  


9) Energy – Short Answer: Recently, controversy surrounding fraudulent images and data in an incredibly influential 2006 publication on the cause of dementia in Alzheimer's has raised concerns about scientific integrity. The new revelations revealing the fraud in the data threaten the leading theory that Alzheimer's disease is caused by accumulation of what protein?  


ANSWER: amyloid (ACCEPT: amyloid proteins, amyloid plaques, beta amyloid proteins, \(\mathrm{A}\beta^{*}56\) , and any variation)  


## Bonus  


9) Energy – Short Answer: Researchers at Savannah River National Lab are studying regenerative braking systems in electric vehicles. Standard regenerative braking technologies are 60% efficient. If a 3000 kg car is traveling at a constant speed of 10 meters per second down a 30 degree incline, what is the power transferred to the battery to the nearest ten kilowatts?  


ANSWER: 90  


## Tossup  


10) Physics – Multiple Choice: Processes that occur very quickly are generally classified as which of the following?  


W) Isobaric 
X) Isochoric 
Y) Adiabatic 
Z) Isothermal  


ANSWER: Y) Adiabatic  


## Bonus  


10) Physics – Multiple Choice: A hemispherical mirror with a radius of 5 meters is set up and an object is placed inside the hemisphere 2 meters from its vertex along its central axis. Which of the following best describes the image produced by the object and the mirror?  


W) Real and upright 
X) Real and inverted 
Y) Virtual and upright 
Z) Virtual and inverted  


ANSWER: Y) Virtual and upright
## Tossup  


11) Chemistry – Short Answer: Order the following 3 elements in order of increasing electron affinity:  


1) Argon 
2) Manganese 
3) Zinc  


ANSWER: 1, 3, 2  


## Bonus  


11) Chemistry – Short Answer: What are the oxidation states of oxygen and fluorine, respectively, in hypoflurous acid?  


ANSWER: 0 and - 1  


## Tossup  


12) Earth and Space – Short Answer: The earliest dated minerals come from which geologic eon?  


ANSWER: Hadean  


## Bonus  


12) Earth and Space – Multiple Choice: Which of the following is closest to the percentage of the Earth’s atmosphere by mass that lies at an elevation of less than 50 kilometers?  


W) \(50\%\) X) \(75\%\) Y) \(90\%\) Z) \(99\%\)  


ANSWER: Z) \(99\%\)
## Tossup  


13) Energy – Multiple Choice: Researchers at Princeton Plasma Physics Lab are studying the propagation of waves. When a traveling wave meets a fixed boundary point, which of the following will occur?  


W) An identical wave will be reflected 
X) An inverted wave will be reflected 
Y) The wave will dissipate its energy 
Z) The wave will double its frequency  


ANSWER: X) An inverted wave will be reflected  


## Bonus  


13) Energy – Multiple Choice: Researchers at Pacific Northwest National Lab are studying ways to improve industrial chemical production. When producing large quantities of chemicals, it is important for conditions to remain fixed throughout the reaction process, often accomplished through a buffer solution. Which of the following pairs of compounds would make the best buffer?  


W) \(\mathrm{Na}_{2}\mathrm{C}_{2}\mathrm{O}_{4}\) and \(\mathrm{NaHC}_{2}\mathrm{O}_{4}\) X) \(\mathrm{H}_{2}\mathrm{SO}_{4}\) and \(\mathrm{KHSO}_{4}\) Y) \(\mathrm{Mg(CN)}_{2}\) and HCN Z) \(\mathrm{NaCl}\) and \(\mathrm{HClO}_{4}\)  


ANSWER: Y) \(\mathrm{Mg(CN)}_{2}\) and HCN  


## Tossup  


14) Biology – Short Answer: A new highway is built through a forest, causing the forest adjacent to the new highway to change in flora and fauna. What is the term for this effect?  


ANSWER: Edge Effect  


## Bonus  


14) Biology – Short Answer: What is the name of arteries that provide oxygen-rich blood to the heart?  


ANSWER: Coronary arteries
## Tossup  


15) Math - Multiple Choice: When the expression \(81^{2} + 81^{2} + 81^{2}\) is written in the form [open parentheses square root of 3 close parentheses to the power of n], what is n?  


W) 9 
X) 10 
Y) 14 
Z) 18  


ANSWER: Z) 18  


## Bonus  


15) Math - Short Answer: Consider the number \(F\) , which is equal to [2 0 2 3 base 4]. How many base 2 numbers \(T\) end with the digit 0 and satisfy the inequality \(0 < T < F\) ?  


ANSWER: 69  


## Tossup  


16) Earth and Space - Short Answer: During a star's transformation to a neutron star, extremely large amounts of what particles are released, expelling up to 98% of the star's energy?  


ANSWER: Neutrino  


## Bonus  


16) Earth and Space - Short Answer: Identify all of the following 4 types of galaxies that can contain an Active Galactic Nucleus:  


I) Spiral II) Lenticular III) Elliptical IV) Irregular  


ANSWER: All
## Tossup  


17) Biology - Short Answer: Select all of the following three parts of a gene that are part of the open reading frame:  


I) Promotor  II) 5' [5 prime] Untranslated Region  III) Stop codon  


ANSWER: None  


## Bonus  


17) Biology - Multiple Choice: Pineapples are an example of what kind of fruit, which is formed from many carpels from several flowers in an inflorescence?  


W) Simple  X) Aggregate  Y) Multiple  Z) Accessory  


ANSWER: Y) Multiple  


## Tossup  


18) Math - Short Answer: An ant is standing at the origin of the Cartesian plane. Every second, it crawls left, right, up, or down one unit by choosing a direction at random. After 5 seconds, what is the probability that the ant is back at the origin?  


ANSWER: 0  


## Bonus  


18) Math - Short Answer: Order the integral from 1 to \(e\) of the following 3 functions from smallest to largest value:  


1) \(x^{x}\) 2) \(x^{e}\) 3) \(e^{x}\)  


ANSWER: 1, 2, 3
## Tossup  


19) Physics – Short Answer: Identify all of the following 3 changes that would change the magnetic field strength inside an ideal solenoid:  


I) Increasing the current  II) Increasing the number of turns per unit length  III) Decreasing the radius  


ANSWER: I and II  


## Bonus  


19) Physics – Short Answer: A thin spherical shell can withstand 150 kilopascals of pressure difference before it bursts. If a vacuum is pulled inside of the shell and the shell is immersed in water, how many meters can it travel below the surface before it bursts to one significant figure?  


ANSWER: 5  


## Tossup  


20) Chemistry – Multiple Choice: Which of the following moieties [moy-et-ees] is most unstable?  


W) Geminal Diol  X) Acid chloride  Y) Imine [eye-mean]  Z) Allene  


ANSWER: W) Geminal Diol  


## Bonus  


20) Chemistry – Short Answer: Serena is studying an element that has a very low electron affinity and a very high effective nuclear charge. What period 3 element best fits these characteristics?  


ANSWER: Argon
## Tossup  


21) Energy - Short Answer: Scientists at Lawrence Berkeley National Labs are studying quantum computing and how it can be used to speed up computations using number base systems other than binary. Identify all of the following numbers in base 12 that are divisible by 3:  


I) [one two five] II) [three seven nine] III) [seven six two]  


ANSWER: II only  


## Bonus  


21) Energy - Short Answer: Scientists at LIGO are studying the propagation of gravitational waves through spacetime. Identify all of the following bodies which produce measurable gravitational waves.  


I) Rapidly rotating black hole II) Neutron Star Binary III) Magnetar  


ANSWER: All  


## Tossup  


22) Biology - Short Answer: What supergroup of eukaryotes contains red algae, green algae, and plants.  


ANSWER: Archaeplastida  


## Bonus  


22) Biology - Short Answer: Order the following 4 events in chronological order of a fungus life cycle:  


1) Karyogamy 
2) Heterokaryotic stage 
3) Spore germination 
4) Plasmagamy  


ANSWER: 4, 2, 1, 3
## Tossup  


23) Math - Short Answer: If the greatest common denominator of two positive numbers \(a\) and \(b\) is 5 and the least common multiple of \(a\) and \(b\) is 20, what is the least possible sum of \(a\) and \(b\) ?  


ANSWER: 25  


## Bonus  


23) Math - Short Answer: Skyler is given four cards, labeled with the numbers 5, 6, 7, and 8. He arranges the four cards so that he creates two two-digit numbers. The set \(S\) contains all possible sums of the two numbers he can create. What is the difference between the largest and smallest elements in \(S\) ?  


ANSWER: 36