sub_title[[455, 144, 541, 162]]
## TOSS-UP  

text[[115, 178, 841, 215]]
1) Biology – Short Answer What hormone, secreted by the adrenal glands, plays a role in regulating salt and water levels in the kidney?  

text[[115, 230, 354, 248]]
ANSWER: ALDOSTERONE  

sub_title[[462, 266, 533, 285]]
## BONUS  

text[[115, 300, 875, 336]]
1) Biology – Multiple Choice Which of the following is most accurate regarding the transport of proteins across the nuclear membrane?  

text[[115, 352, 745, 424]]
W) Most proteins are small enough to pass through the pores without regulation 
X) Proteins are tagged with a detectable amino acid sequence 
Y) Proteins do not pass through nuclear pores 
Z) Proteins are tagged with a carbohydrate chain  

text[[115, 438, 790, 475]]
ANSWER: X) PROTEINS ARE TAGGED WITH A DETECTABLE AMINO ACID SEQUENCE  

sub_title[[455, 526, 541, 545]]
## TOSS-UP  

text[[115, 560, 874, 614]]
2) Earth and Space – Short Answer Identify all of the following four changes to seawater that would increase salinity: 1) Higher evaporation; 2) Increased formation of sea ice; 3) Increased number of icebergs; 4) Increased stream runoff into the ocean.  

text[[115, 630, 283, 648]]
ANSWER: 1 AND 2  

sub_title[[462, 666, 533, 684]]
## BONUS  

text[[115, 700, 832, 736]]
2) Earth and Space – Short Answer What is the name of the upper mass limit of neutron stars?  

text[[112, 751, 798, 771]]
ANSWER: TOV LIMIT (ACCEPT: TOLMAN- OPPENHEIMER- VOLKOFF LIMIT)sub_title[[455, 90, 540, 108]]
## TOSS-UP  

text[[112, 126, 852, 164]]
3) Math - Multiple Choice Which of the following statements is true regarding the function \(f(x) = x^{2} + x + 1?\)  

text[[114, 180, 598, 250]]
W) It is always concave up 
X) Its discriminant is positive 
Y) It has two real roots 
Z) As \(x\) approaches infinity, \(f(x)\) approaches negative infinity  

text[[114, 266, 500, 285]]
ANSWER: W) IT IS ALWAYS CONCAVE UP  

sub_title[[462, 301, 533, 320]]
## BONUS  

text[[113, 336, 868, 373]]
3) Math - Short Answer Five people are sitting in a row of five chairs. How many orders are possible if Anna can't sit next to Brian and Catherine can't sit next to Edward?  

text[[115, 388, 230, 406]]
ANSWER: 48  

sub_title[[455, 459, 540, 477]]
## TOSS-UP  

text[[113, 493, 863, 529]]
4) Physics - Multiple Choice The electric field in a region is conservative only under which of the following conditions?  

text[[114, 545, 432, 615]]
W) No charges are present 
X) All charges are stationary 
Y) All currents are steady 
Z) No displacement currents are present  

text[[114, 631, 508, 650]]
ANSWER: Y) ALL CURRENTS ARE STEADY  

sub_title[[462, 666, 533, 684]]
## BONUS  

text[[114, 701, 870, 771]]
4) Physics - Short Answer Daniel stands on a scale in an elevator, which is initially at rest. It first undergoes a constant acceleration upwards for 3 seconds, during which the scale reads 80 kilograms. Then, it decelerates to a stop over 2 seconds, during which the scale reads 60 kilograms. In kilograms, what is Daniel's mass?  

text[[115, 788, 230, 806]]
ANSWER: 72sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[114, 126, 860, 163]]
5) Chemistry – Short Answer Identify all of the following three compounds that are salts of strong acids: 1) Sodium chloride; 2) Potassium fluoride; 3) Ammonium perchlorate.  

text[[115, 180, 282, 197]]
ANSWER: 1 AND 3  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 250, 835, 303]]
5) Chemistry – Short Answer Identify all of the following three options that are likely to increase the rate of a chemical reaction: 1) Increasing temperature; 2) Decreasing reactant concentrations; 3) Decreasing product concentrations.  

text[[115, 319, 279, 337]]
ANSWER: 1 ONLY  

sub_title[[456, 389, 540, 407]]
## TOSS-UP  

text[[115, 423, 877, 476]]
6) Energy – Multiple Choice Scientists at Pacific Northwest National Lab are creating protein lattices on the surfaces of mica crystals. Which of the following statements regarding mica is false?  

text[[115, 493, 432, 565]]
W) Mica exhibits perfect basal cleavage 
X) Mica is a phyllosilicate 
Y) Most micas are harder than quartz 
Z) Most micas are insulators  

text[[115, 580, 631, 599]]
ANSWER: Y) MOST MICAS ARE HARDER THAN QUARTZ  

sub_title[[463, 615, 533, 633]]
## BONUS  

text[[115, 650, 845, 720]]
6) Energy – Short Answer Scientists at Pacific Northwest National Lab have identified the structure of the Janus intermediate, which is an intermediate in the biological conversion of atmospheric nitrogen to ammonia. This step of nitrogen fixation is accomplished via what important group of enzymes?  

text[[115, 736, 359, 754]]
ANSWER: NITROGENASESsub_title[[455, 90, 540, 108]]
## TOSS-UP  

text[[113, 126, 870, 163]]
7) Chemistry – Multiple Choice Which of the following properties tends to decrease across a period on the periodic table?  

text[[115, 180, 333, 250]]
W) Ionization energy 
X) Electronegativity 
Y) Atomic radius 
Z) Effective nuclear charge  

text[[115, 267, 392, 285]]
ANSWER: Y) ATOMIC RADIUS  

sub_title[[463, 302, 533, 320]]
## BONUS  

text[[115, 336, 836, 372]]
7) Chemistry – Short Answer What is the term for materials that can become electrically polarized under mechanical stress?  

text[[115, 388, 360, 406]]
ANSWER: PIEZOELECTRIC  

sub_title[[455, 459, 540, 477]]
## TOSS-UP  

text[[115, 493, 836, 529]]
8) Math – Short Answer An equilateral triangle has an area of 49 square root of 3 square centimeters. In centimeters, how long is each side?  

text[[115, 545, 231, 562]]
ANSWER: 14  

sub_title[[463, 580, 533, 598]]
## BONUS  

text[[115, 615, 864, 667]]
8) Math – Short Answer Evelyn has a strange plant. At first, it is 1 inch tall. At the end of every day, it has a 50% chance of tripling its height. In inches, what is the expected value of its height after 3 days?  

text[[115, 684, 221, 702]]
ANSWER: 8sub_title[[456, 91, 541, 108]]
## TOSS-UP  

text[[113, 127, 860, 163]]
9) Biology – Multiple Choice What is the term for flowers that lack one or more of the four basic plant organs?  

text[[115, 181, 295, 250]]
W) Partial flowers 
X) Deficient flowers 
Y) Incomplete flowers 
Z) Sufficient flowers  

text[[115, 267, 457, 285]]
ANSWER: Y) INCOMPLETE FLOWERS  

sub_title[[456, 303, 526, 320]]
## BONUS  

text[[112, 339, 870, 358]]
9) Biology – Short Answer How many primers are needed to perform a single PCR reaction?  

text[[115, 374, 220, 391]]
ANSWER: 2  

sub_title[[448, 444, 533, 461]]
## TOSS-UP  

text[[115, 481, 874, 551]]
10) Physics – Multiple Choice A red marble traveling to the right at 3 meters per second collides head-on with a blue marble of identical mass traveling to the left at 5 meters per second. In meters per second, what are the minimum and maximum speeds, respectively, of the red marble after the collision?  

text[[115, 569, 283, 586]]
ANSWER: 1 AND 5  

sub_title[[463, 604, 533, 621]]
## BONUS  

text[[115, 639, 874, 692]]
10) Physics – Short Answer A 6-kilogram car is driving into a vertical, circular loop of radius 10 meters. What is the minimum kinetic energy in joules that the car needs at the bottom of the loop in order to be able to complete the loop without leaving the loop’s surface?  

text[[115, 709, 250, 725]]
ANSWER: 1470sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 126, 848, 163]]
11) Earth and Space – Multiple Choice Which of the following plate boundaries is NOT a convergent boundary?  

text[[115, 182, 576, 252]]
W) Nazca plate and South American plate boundary  X) Juan de Fuca plate and North American plate boundary  Y) Pacific plate and Phillipine plate boundary  Z) North American plate and African plate boundary  

text[[115, 268, 796, 287]]
ANSWER: Z) NORTH AMERICAN PLATE AND AFRICAN PLATE BOUNDARY  

sub_title[[463, 304, 533, 322]]
## BONUS  

text[[115, 339, 874, 392]]
11) Earth and Space – Multiple Choice The moon is seen in the Northern hemisphere with its right side illuminated with a sliver of light on April 2nd. What phase will the moon be on April 13th?  

text[[115, 408, 272, 478]]
W) First quarter  X) Full moon  Y) Waning gibbous  Z) Third quarter  

text[[115, 495, 350, 513]]
ANSWER: X) FULL MOON  

sub_title[[456, 565, 540, 583]]
## TOSS-UP  

text[[115, 600, 859, 653]]
12) Energy – Multiple Choice Researchers at Argonne National Lab operate the Advanced Electron Paramagnetic Resonance facility, or AEPR, in order to analyze transition metal complexes. Which of the following types of molecules would this facility most likely analyze?  

text[[115, 669, 448, 739]]
W) A molecule with unpaired electrons  X) A molecule with unpaired protons  Y) A molecule with no unpaired electrons  Z) A molecule with no unpaired protons  

text[[115, 755, 644, 774]]
ANSWER: W) A MOLECULE WITH UNPAIRED ELECTRONS  

sub_title[[456, 791, 527, 809]]
## BONUS  

text[[115, 827, 879, 880]]
12) Energy – Short Answer Scientists at Pacific Northwest National Lab are developing better models to predict subsurface water flow. Which fundamental law of hydrogeology describes the flow velocity of a fluid through a porous medium?  

text[[116, 897, 346, 914]]
ANSWER: DARCY'S LAWsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 126, 800, 163]]
13) Biology – Short Answer What sequencing technique is most often used in DNA fingerprinting to detect polymorphisms?  

text[[115, 178, 844, 198]]
ANSWER: RESTRICTION FRAGMENT LENGTH POLYMORPHISM (ACCEPT: RFLP)  

sub_title[[463, 214, 533, 232]]
## BONUS  

text[[115, 249, 843, 286]]
13) Biology – Multiple Choice Cri du chat [kree-doo-SHAH] syndrome is an example of which of the following errors during DNA replication?  

text[[115, 302, 252, 372]]
W) Duplication 
X) Deletion 
Y) Translocation 
Z) Transversion  

text[[115, 389, 333, 407]]
ANSWER: X) DELETION  

sub_title[[456, 459, 541, 477]]
## TOSS-UP  

text[[115, 493, 833, 530]]
14) Chemistry – Short Answer When carbon dioxide is be added to lime water, a cloudy precipitate is formed. What is the identity of this precipitate?  

text[[115, 545, 591, 564]]
ANSWER: CALCIUM CARBONATE (ACCEPT: CaCO3)  

sub_title[[463, 580, 533, 599]]
## BONUS  

text[[115, 615, 879, 652]]
14) Chemistry – Multiple Choice When the solid-liquid boundary line on a phase diagram has a negative slope, which of the following must be true of the substance being studied?  

text[[115, 667, 495, 739]]
W) Its liquid phase is denser than its solid phase 
X) Its solid phase is denser than its liquid phase 
Y) It can never form a supercritical fluid 
Z) It can never form a supercooled fluid  

text[[115, 753, 736, 773]]
ANSWER: W) ITS LIQUID PHASE IS DENSER THAN ITS SOLID PHASEsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 880, 163]]
15) Math – Short Answer Every angle in a convex polygon is summed except for one of them, and the result is 400 degrees. In degrees, what is the last angle?  

text[[115, 180, 241, 197]]
ANSWER: 140  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 250, 880, 320]]
15) Math – Short Answer Michael starts running at a constant speed of 9 miles per hour. After an hour, he turns around and runs for 30 minutes, then repeats this process 2020 times, running for half of the previous time every time. To the nearest integer, how many miles is Michael from his starting point?  

text[[115, 337, 221, 354]]
ANSWER: 6  

sub_title[[456, 407, 540, 425]]
## TOSS-UP  

text[[115, 441, 853, 478]]
16) Earth and Space – Short Answer Rank the following three stages of reef evolution from first to last: 1) Fringing reef; 2) Barrier reef; 3) Atoll.  

text[[115, 494, 260, 511]]
ANSWER: 1, 2, 3  

sub_title[[463, 529, 533, 547]]
## BONUS  

text[[115, 563, 839, 599]]
16) Earth and Space – Short Answer What phenomenon occurs when saturated soil loses stiffness in the presence of an earthquake?  

text[[115, 615, 403, 633]]
ANSWER: SOIL LIQUEFACTIONsub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[115, 127, 871, 181]]
17) Physics – Multiple Choice A massive rope is attached to the ceiling and kept taut by a weight at the bottom. If the weight is given a small wiggle, which of the following describes the speed of the resulting wave as it travels up the string?  

text[[115, 198, 355, 268]]
W) It increases 
X) It decreases 
Y) It increases, then decreases 
Z) It remains constant  

text[[115, 284, 370, 302]]
ANSWER: W) IT INCREASES  

sub_title[[462, 320, 533, 337]]
## BONUS  

text[[115, 354, 857, 407]]
17) Physics – Short Answer A charge moves in an electric field with potential described by the function \(\mathrm{V}(x) = 3x^{2} - 6x + 8\) . If the charge experiences a force of 18 newtons at \(x = 2\) , then what is its potential energy in joules at \(x = 1\) ?  

text[[115, 422, 305, 440]]
ANSWER: 15 JOULES  

sub_title[[456, 495, 540, 512]]
## TOSS-UP  

text[[115, 530, 877, 566]]
18) Energy – Multiple Choice Researchers at Princeton Plasma Physics Lab have developed a new design for the internal combustion engine that reduces the emission of what toxic gas?  

text[[115, 584, 305, 653]]
W) Methane 
X) Nitric oxide 
Y) Carbon monoxide 
Z) Chlorofluorocarbons  

text[[115, 670, 367, 688]]
ANSWER: X) NITRIC OXIDE  

sub_title[[462, 707, 533, 724]]
## BONUS  

text[[115, 741, 844, 793]]
18) Energy – Multiple Choice A family in Cape Town, South Africa, would like to install solar panels on their house. How should they orient their solar panels to maximize energy output?  

text[[115, 810, 635, 880]]
W) South-facing and at an angle of 30 degrees with the horizontal 
X) North-facing and at angle of 30 degrees with the horizontal 
Y) South-facing and at an angle of 60 degrees with the horizontal 
Z) North-facing and at angle of 60 degrees with the horizontal  

text[[115, 897, 810, 931]]
ANSWER: Z) NORTH-FACING AND AT AN ANGLE OF 30 DEGREES WITH THE HORIZONTAL  

text[[115, 942, 383, 959]]
Discord Spring Tournament—RRsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 126, 836, 163]]
19) Biology - Short Answer Several types of non-Watson-Crick base pairing may occur during translation due to what phenomenon involving genetic code redundancy?  

text[[115, 179, 293, 197]]
ANSWER: WOBBLE  

sub_title[[463, 214, 533, 232]]
## BONUS  

text[[115, 249, 870, 285]]
19) Biology - Short Answer Tracheids and vessel elements are components of what vascular tissue in plants?  

text[[115, 303, 280, 321]]
ANSWER: XYLEM  

sub_title[[456, 374, 541, 393]]
## TOSS-UP  

text[[115, 411, 849, 465]]
20) Energy - Short Answer Scientists at Pacific Northwest National Lab are working on improving the stability of qubits in quantum computers. Qubits can be represented as a linear combination of two states that are joined by what quantum mechanical principle?  

text[[115, 481, 360, 499]]
ANSWER: SUPERPOSITION  

sub_title[[463, 517, 533, 535]]
## BONUS  

text[[115, 552, 878, 605]]
20) Energy - Multiple Choice Scientists at Sandia National Lab have developed a prototype for a cheaper device to perform magnetoencephalography. Which of the following best describes the function of magnetoencephalography?  

text[[115, 621, 670, 692]]
W) It probes the brain with a magnetic field and measures the rebound 
X) It probes the heart with a magnetic field and measures the rebound 
Y) It detects magnetic fields from the electrical signals in the brain 
Z) It detects magnetic fields from the electrical signals in the heart  

text[[115, 708, 866, 744]]
ANSWER: Y) IT DETECTS MAGNETIC FIELDS FROM THE ELECTRICAL SIGNALS IN THE BRAINsub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 126, 872, 163]]
21) Chemistry - Short Answer What term is given to liquids such as helium-II that exhibit an ability to flow without viscosity?  

text[[115, 180, 341, 198]]
ANSWER: SUPERFLUIDS  

sub_title[[463, 215, 533, 234]]
## BONUS  

text[[115, 249, 879, 320]]
21) Chemistry - Short Answer Given that the standard reduction potential of chlorine is \(+1.36\) volts, and that the standard reduction potential of aluminum is \(-1.66\) volts, then, to two decimal places and in volts, what is the standard cell potential for the electrolysis of an aluminum chloride solution?  

text[[115, 337, 255, 355]]
ANSWER: - 3.02  

sub_title[[456, 408, 540, 426]]
## TOSS-UP  

text[[115, 443, 870, 498]]
22) Earth and Space - Short Answer Identify all of the following four atmospheric gases that directly contribute to the formation of tropospheric ozone: 1) Nitrogen dioxide; 2) Carbon dioxide; 3) Sulfur dioxide; 4) Carbon monoxide  

text[[115, 513, 279, 531]]
ANSWER: 1 ONLY  

sub_title[[463, 548, 533, 566]]
## BONUS  

text[[115, 583, 852, 619]]
22) Earth and Space - Multiple Choice Which of the following metamorphic facies is most likely associated with subduction zones?  

text[[115, 636, 330, 707]]
W) Blueschist 
X) Greenschist 
Y) Granulite 
Z) Eclogite [ECK-loh-jite]  

text[[115, 723, 359, 741]]
ANSWER: W) BLUESCHISTsub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 126, 850, 181]]
23) Physics – Short Answer A tank is completely filled with oil with a density of 500 kilograms per cubic meter. If the height of the tank is 3 meters, what is the gauge pressure, in pascals, at the bottom of the tank?  

text[[115, 197, 260, 214]]
ANSWER: 14700  

sub_title[[463, 232, 533, 250]]
## BONUS  

text[[115, 267, 879, 321]]
23) Physics – Short Answer A particle of mass 3 kilograms is moving at 15 meters per second east. Starting at \(t = 0\) seconds, a constant northward force of 12 newtons is applied to the particle. What is the work done in joules by the force between \(t = 0\) and \(t = 5\) ?  

text[[115, 337, 241, 354]]
ANSWER: 600