
## TOSS-UP  


1) Earth and Space – Short Answer What type of supernova occurs when there is runaway fusion in a secondary white dwarf after enough mass transfer from a giant star?  


ANSWER: TYPE IA SUPERNOVA  


## BONUS  


1) Earth and Space – Multiple Choice Which of the following air masses is most likely to be present above western Washington in February?  


W) Maritime tropical  X) Maritime polar  Y) Continental tropical  Z) Continental polar  


ANSWER: X) MARITIME POLAR  


## TOSS-UP  


2) Math – Short Answer How many games need to be played in a single-elimination tournament to declare a winner from 16 teams?  


ANSWER: 15  


## BONUS  


2) Math – Short Answer Two concentric circles have radii of 5 and 12. What is the area of the region in between the circles?  


ANSWER: 119π
## TOSS-UP  


3) Physics – Short Answer A car starts accelerating from the top of a 9-meter tall ramp from rest. The ramp makes an angle of 30 degrees with the horizontal. Given that the car accelerates at 1 meter per second squared, how long does it take, in seconds, for the ball to go down the ramp?  


ANSWER: 6  


## BONUS  


3) Physics – Short Answer A 40-kilogram box is sitting at rest on a 30 degree incline. In newtons, what is the magnitude of the frictional force acting on the block?  


ANSWER: 196  


## TOSS-UP  


4) Chemistry – Multiple Choice Which of the following is the electron configuration of the \(\mathrm{Mg}^{2 + }\) ion?  


W) \(1\mathrm{s}^{2}2\mathrm{s}^{2}2\mathrm{p}^{6}\) X) \(1\mathrm{s}^{2}2\mathrm{s}^{2}2\mathrm{p}^{6}3\mathrm{s}^{1}\) Y) \(1\mathrm{s}^{2}2\mathrm{s}^{2}2\mathrm{p}^{6}3\mathrm{s}^{2}\) Z) \(1\mathrm{s}^{2}2\mathrm{s}^{2}2\mathrm{p}^{6}3\mathrm{s}^{2}3\mathrm{p}^{6}\)  


ANSWER: W) \(1\mathrm{s}^{2}2\mathrm{s}^{2}2\mathrm{p}^{6}\)  


## BONUS  


4) Chemistry – Short Answer Identify all of the following three quantities that are state functions: 1) Volume; 2) Heat; 3) Work.  


ANSWER: 1 ONLY
## TOSS-UP  


5) Biology - Short Answer Identify all of the following four cell junctions that can be found between animal cells: 1) Tight junctions; 2) Desmosomes; 3) Gap junctions; 4) Plasmodesmata.  


ANSWER: 1, 2 AND 3  


## BONUS  


5) Biology - Multiple Choice Which of the following is NOT an organ that may be used by an amphibian to perform gas exchange?  


W) Skin 
X) Lungs 
Y) Gills 
Z) Cloaca  


ANSWER: Z) CLOACA  


## TOSS-UP  


6) Energy - Short Answer Scientists at SLAC National Accelerator Lab are researching efficient methods for synthesizing diamonds via the compression of diamondoids, a class of materials extracted from crude oil. Under high pressure, what element is released from diamondoids, leaving the residual carbon?  


ANSWER: HYDROGEN  


## BONUS  


6) Energy - Short Answer Scientists at Fermilab, Brookhaven National Lab, and Lawrence Berkeley National Lab have designed a niobium-tin quadrupole magnet that sets the record for the highest field strength ever recorded for an accelerator focusing magnet. The niobium-tin alloy is a superconductor that expels magnetic fields via what effect?  


ANSWER: MEISSNER EFFECT (ACCEPT: MEISSNER- OCHSENFELD EFFECT)
## TOSS-UP  


7) Chemistry – Short Answer What law of thermodynamics states that the internal energy change of an isolated system is zero?  


ANSWER: FIRST LAW OF THERMODYNAMICS  


## BONUS  


7) Chemistry – Short Answer A vessel containing 3 moles of \(\mathrm{H}_{2}\) gas is held at pressure of 2 atmospheres and a volume of 9 liters. If another 3 moles of gas are added, and the container is expanded to a volume of 12 liters, what is the final pressure of the vessel, in atmospheres, assuming constant temperature?  


ANSWER: 3  


## TOSS-UP  


8) Biology – Multiple Choice Which of the following is NOT characteristic of eudicots?  


W) Vascular bundles arranged in a circle 
X) Taproots 
Y) Reticular leaf venation 
Z) Two cotyledons [koh-tuh-LEE-duns]  


ANSWER: Y) RETICULAR LEAF VENATION  


## BONUS  


8) Biology – Short Answer The nuclear lamina is a dense network important for maintaining the structural integrity of the nucleus. What type of cytoskeletal element composes the majority of the nuclear lamina?  


ANSWER: INTERMEDIATE FILAMENT
## TOSS-UP  


9) Earth and Space – Short Answer What is the name of the primary mechanism of helium-4 fusion in medium-mass stars?  


ANSWER: TRIPLE- ALPHA PROCESS  


## BONUS  


9) Earth and Space – Multiple Choice An air parcel in the Northern Hemisphere subsides and creates a high pressure system at the surface. Which of the following best describes airflow in the system?  


W) Cyclonic, clockwise  X) Cyclonic counterclockwise  Y) Anticyclonic, clockwise  Z) Anticyclonic, counterclockwise  


ANSWER: Y) ANTICYCLONIC, CLOCKWISE  


## TOSS-UP  


10) Math – Short Answer The point (4, 2) is reflected across the \(y\) -axis and then translated 8 units up. What are the final coordinates of the point?  


ANSWER: (- 4, 10)  


## BONUS  


10) Math – Short Answer Connor’s drawer contains 3 green socks, 6 red socks, 9 blue socks, and 2 yellow socks. What is the minimum number of socks Connor needs to pull from his drawer to guarantee that he has at least 1 pair of each color?  


ANSWER: 20
## TOSS-UP  


11) Physics – Short Answer A circuit contains a 12-volt battery connected in series with a 3-ohm resistor. What is the power dissipated by the resistor in watts?  


ANSWER: 48  


## BONUS  


11) Physics – Multiple Choice A 50-kilogram sphere collides head-on in a perfectly elastic collision with a metal plate of mass \(m\) . As the value of \(m\) approaches infinity, which of the following best describes the behavior of the system after the collision?  


W) The sphere will stick to the plate and both objects will move at the sphere's original velocity X) The sphere will stop moving and the plate will move at the sphere's original velocity Y) The sphere will stick to the plate and stop moving Z) The sphere begin traveling in the opposite direction with the same speed  


ANSWER: Z) THE SPHERE WILL BEGIN TRAVELING IN THE OPPOSITE DIRECTION WITH THE SAME SPEED  


## TOSS-UP  


12) Energy – Multiple Choice DOE Researchers at Ames Lab have discovered that periodic vibrational motion may stabilize some currently unstable electron states, which can make advanced quantum computing possible. On a macroscopic level, what is the name for this periodic vibrational motion?  


W) Resonance 
X) Damping 
Y) Harmonic oscillation 
Z) Laminar flow  


ANSWER: Y) HARMONIC OSCILLATION  


## BONUS  


12) Energy – Multiple Choice Researchers at CERN are running the Baryon Antibaryon Symmetry Experiment, or BASE, to look for differences between matter and antimatter. Which of the following particles is a baryon?  


W) Neutrino 
X) Positron 
Y) Electron 
Z) Proton  


ANSWER: Z) PROTON
## TOSS-UP  


13) Physics – Short Answer A Carnot engine has a hot reservoir of 102 degrees Celsius and an efficiency of \(40\%\) . In degrees Celsius, what is the temperature of the cold reservoir?  


ANSWER: - 48  


## BONUS  


13) Physics – Short Answer A projectile is launched from the ground at a 45 degree angle. If it reaches a maximum height of 23 meters, what is its horizontal range in meters?  


ANSWER: 92  


## TOSS-UP  


14) Biology – Short Answer What is the largest structure in the nucleus of eukaryotic cells?  


ANSWER: NUCLEOLUS  


## BONUS  


14) Biology – Short Answer What enzyme participates in both the citric acid cycle and the electron transport chain?  


ANSWER: COMPLEX 2 (ACCEPT: SUCCINATE DEHYDROGENASE; SUCCINATE COENZYME-Q)
## TOSS-UP  


15) Math - Short Answer What is the area of an isosceles right triangle with a hypotenuse of 6 times the square root of 2?  


ANSWER: 18  


## BONUS  


15) Math - Short Answer What is the greatest common factor of 350 and 518?  


ANSWER: 14  


## TOSS-UP  


16) Chemistry - Short Answer What is the general term for a substance that accelerates a chemical reaction by providing an alternate pathway for the reaction to occur?  


ANSWER: CATALYST (DO NOT ACCEPT: ENZYME)  


## BONUS  


16) Chemistry - Short Answer Rank the following three ions in terms of increasing ionic radius: 1) \(\mathrm{Na}^{+}\) ; 2) \(\mathrm{Al}^{3+}\) ; 3) \(\mathrm{F}^{-}\) .  


ANSWER: 2, 1, 3
## TOSS-UP  


17) Earth and Space – Multiple Choice Which of the following statements concerning plate tectonics is NOT true?  


W) Slab pull contributes much more driving force than ridge push 
X) In a collision between two oceanic plates, the older one sinks 
Y) Mid-ocean ridges are associated with asthenosphere upwelling 
Z) Continental plates are generally denser than oceanic plates  


ANSWER: Z) CONTINENTAL PLATES ARE GENERALLY DENSER THAN OCEANIC PLATES  


## BONUS  


17) Earth and Space – Short Answer What oceanic layer is characterized by a rapid vertical change in density?  


ANSWER: PYCNOCLINE  


## TOSS-UP  


18) Physics – Short Answer The frequency of a photon is directly related to its energy by what physical constant?  


ANSWER: PLANCK'S CONSTANT  


## BONUS  


18) Physics – Short Answer An ideal Atwood machine has two blocks of masses 3 and 4 kilograms connected by a string on either side of a pulley. In meters per second squared, which of the following is the acceleration of the system?  


W) 0.7 
X) 1.4 
Y) 2.1 
Z) 2.8  


ANSWER: X) 1.4
## TOSS-UP  


19) Biology - Short Answer Several types of non-Watson-Crick base pairing may occur during translation due to what phenomenon involving genetic code redundancy?  


ANSWER: WOBBLE  


## BONUS  


19) Biology - Short Answer Tracheids and vessel elements are components of what vascular tissue in plants?  


ANSWER: XYLEM  


## TOSS-UP  


20) Energy - Short Answer Scientists at Pacific Northwest National Lab are working on improving the stability of qubits in quantum computers. Qubits can be represented as a linear combination of two states that are joined by what quantum mechanical principle?  


ANSWER: SUPERPOSITION  


## BONUS  


20) Energy - Multiple Choice Scientists at Sandia National Lab have developed a prototype for a cheaper device to perform magnetoencephalography. Which of the following best describes the function of magnetoencephalography?  


W) It probes the brain with a magnetic field and measures the rebound 
X) It probes the heart with a magnetic field and measures the rebound 
Y) It detects magnetic fields from the electrical signals in the brain 
Z) It detects magnetic fields from the electrical signals in the heart  


ANSWER: Y) IT DETECTS MAGNETIC FIELDS FROM THE ELECTRICAL SIGNALS IN THE BRAIN
## TOSS-UP  


21) Math - Multiple Choice Which of the following polynomials has more than 4 roots?  


W) \(6x^{2} + 11x - 17\) X) \(x^{3} - 3x^{2} + 1\) Y) \(4x^{4} - 17x + 34\) Z) \(x^{6} - 3\)  


ANSWER: Z) \(x^{6} - 3\)  


## BONUS  


21) Math - Short Answer A sequence has \(a\) sub \(1 = 2\) , \(a\) sub \(2 = 4\) , and \(a\) sub quantity \(n + 2\) equals 3 times a sub quantity \(n + 1\) minus a sub \(n\) for all positive integers \(n\) . What is \(a\) sub 5?  


ANSWER: 68  


## TOSS-UP  


22) Chemistry - Multiple Choice Which of the following unit cells has the lowest coordination number?  


W) Simple cubic 
X) Body-centered cubic 
Y) Face-centered cubic 
Z) Base-centered cubic  


ANSWER: W) SIMPLE CUBIC  


## BONUS  


22) Chemistry - Short Answer The variation of vapor pressure with temperature can be calculated using what equation?  


ANSWER: CLAUSIUS-CLAPEYRON EQUATION
## TOSS-UP  


23) Earth and Space – Multiple Choice Which of the following fluvial environments would most likely involve braided stream morphology?  


W) Outwash plain of an alpine glacier  X) Mid-continent hot desert  Y) Coastal floodplain  Z) Uneroded bedrock  


ANSWER: W) OUTWASH PLAIN OF AN ALPINE GLACIER  


## BONUS  


23) Earth and Space – Multiple Choice Which of the following rocks would most likely function as an aquitard?  


W) Shale  X) Sandstone  Y) Arkose  Z) Limestone  


ANSWER: W) SHALE