sub_title[[455, 140, 540, 157]]
## TOSS-UP  

text[[115, 179, 876, 252]]
1) Chemistry – Multiple Choice In the Baeyer-Villiger oxidation, ketones or aldehydes are converted to esters by the addition of a peroxyacid. The oxygen atom can be added to either side of the carbonyl group, depending on the migratory aptitudes of the substituents. Which of the following groups has the greatest migratory aptitude?  

text[[115, 268, 226, 339]]
W) Hydrogen  X) Tert-butyl  Y) Isopropyl  Z) Methyl  

text[[116, 355, 350, 373]]
ANSWER: W) HYDROGEN  

sub_title[[421, 391, 570, 409]]
## VISUAL BONUS  

text[[115, 429, 843, 465]]
1) Chemistry – Short Answer Shown in the image is the reaction of an aldehyde with two alcohol equivalents. Answer the following three questions regarding the image:  

text[[115, 481, 856, 534]]
1. What is the name for the unstable intermediate labeled A?  
2. Is a pH of 2 or 12 more appropriate for the conditions in the reaction labeled B?  
3. Is the oxygen atom in the water molecule labeled C derived from the ketone or the alcohol?  

text[[115, 550, 536, 568]]
ANSWER: 1 – HEMIACETAL; 2 – 2; 3 – KETONE  

sub_title[[455, 625, 540, 643]]
## TOSS-UP  

text[[115, 661, 877, 697]]
2) Math – Short Answer A square ABCD has a side length of 6, and M is the midpoint of side AB. What is the volume of the figure made by rotating AMCD about CD?  

text[[115, 714, 251, 731]]
ANSWER: 144π  

sub_title[[463, 750, 533, 767]]
## BONUS  

text[[115, 784, 879, 854]]
2) Math – Short Answer A modified game of Nim starts with \(k\) stones, where \(k\) is greater than 0. Each turn, one of two players can either take 3, 5, or 6 stones. The first player to not be able to move loses. Assuming optimal play, what is the 2020th smallest value for \(k\) such that the first player wins?  

text[[115, 872, 250, 889]]
ANSWER: 3030sub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[113, 127, 857, 163]]
3) Biology – Multiple Choice Which of the following is NOT physiologically promoted by hyperthyroidism?  

text[[114, 180, 281, 250]]
W) Gluconeogenesis 
X) Glycogenolysis 
Y) Proteolysis 
Z) Myogenesis  

text[[115, 268, 360, 286]]
ANSWER: Z) MYOGENESIS  

sub_title[[424, 306, 572, 324]]
## VISUAL BONUS  

text[[115, 343, 876, 398]]
3) Biology – Short Answer Shown in the image are two plants of the same species. The plant to the left is wild type and the plant to the right has a loss-of-function mutation in the PIN1 gene. What plant hormone is PIN1 most likely involved with?  

text[[115, 417, 273, 435]]
ANSWER: AUXIN  

sub_title[[456, 494, 540, 511]]
## TOSS-UP  

text[[115, 530, 877, 565]]
4) Earth and Space – Multiple Choice In oceanography, which of the following dimensionless numbers is most useful for quantifying water stratification?  

text[[115, 583, 295, 652]]
W) Reynolds number 
X) Darcy number 
Y) Prandtl number 
Z) Richardson number  

text[[115, 670, 449, 688]]
ANSWER: Z) RICHARDSON NUMBER  

sub_title[[462, 708, 533, 726]]
## BONUS  

text[[115, 745, 865, 816]]
4) Earth and Space – Short Answer Identify all of the following three statements about extraterrestrial polyaromatic hydrocarbons, or PAH [P-A-H] that are true: 1) PAH can undergo hydrogenation in the interstellar medium; 2) PAH can be identified via their UV absorption spectra; 3) PAH are rarely found on the surface of interstellar ice grains.  

text[[115, 834, 248, 851]]
ANSWER: ALLsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 126, 827, 163]]
5) Physics – Multiple Choice Which of the following statements is NOT true regarding antiferromagnetism?  

text[[115, 180, 860, 270]]
W) Magnetic susceptibility for antiferromagnets always decreases as a function of temperature 
X) Without an applied magnetic field, every orbiting electron in an antiferromagnet has a magnetic moment in a random direction 
Y) In higher-dimension models, antiferromagnets have multiple ground states 
Z) At very low temperatures, neighboring magnetic moments can become skew to each other  

text[[115, 283, 845, 320]]
ANSWER: W) MAGNETIC SUSCEPTIBILITY FOR ANTIFERROMAGNETS ALWAYS DECREASES AS A FUNCTION OF TEMPERATURE  

sub_title[[463, 338, 533, 356]]
## BONUS  

text[[115, 374, 814, 394]]
5) Physics – Multiple Choice Which of the following particles is an eigenstate of CP?  

text[[115, 410, 291, 480]]
W) Omega baryon 
X) Pi zero meson 
Y) Sigma zero baryon 
Z) Neutral kaon  

text[[115, 497, 384, 515]]
ANSWER: X) PI ZERO MESON  

sub_title[[456, 572, 541, 590]]
## TOSS-UP  

text[[115, 608, 879, 699]]
6) Energy – Short Answer Scientists at Argonne National Lab are studying the effects of iron on oceanic productivity. Identify all of the following three statements about iron fertilization that are true: 1) Most natural iron fertilization in the North Atlantic occurs from wind-deposited dust; 2) Iron is a limiting nutrient for photosynthesis; 3) Almost all of the bioavailable iron is chelated by organic ligands.  

text[[115, 715, 248, 732]]
ANSWER: ALL  

sub_title[[424, 752, 572, 771]]
## VISUAL BONUS  

text[[115, 789, 863, 860]]
6) Energy – Multiple Choice Scientists at Pacific Northwest National Lab are investigating the rapid oxidation of uranium via laser-induced breakdown spectroscopy. Shown in the image are two elementary reactions for the formation of uranium dioxide at high temperatures. Assuming steady-state, what is the overall rate law of the reaction?  

text[[115, 878, 228, 895]]
ANSWER: Wsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 799, 163]]
7) Chemistry – Short Answer The Zimmerman–Traxler model is used to predict the stereochemistry of what organic reaction?  

text[[115, 180, 382, 198]]
ANSWER: ALDOL REACTION  

sub_title[[463, 217, 533, 235]]
## BONUS  

text[[115, 253, 879, 307]]
7) Chemistry – Short Answer Identify all of the following three statements that are true regarding the Suzuki coupling mechanism: 1) It employs organoboron compounds; 2) It involves a transmetallation step; 3) It requires basic conditions.  

text[[115, 323, 248, 341]]
ANSWER: ALL  

sub_title[[456, 397, 540, 415]]
## TOSS-UP  

text[[115, 434, 844, 471]]
8) Math – Short Answer Find the quadratic with integer coefficients and smallest positive leading coefficient that has the same sum and product of the roots as \(9x^{9} + 3x^{7} - 5x^{2} + 1\).  

text[[115, 487, 264, 506]]
ANSWER: \(9x^{2} - 1\)  

sub_title[[423, 526, 573, 545]]
## VISUAL BONUS  

text[[115, 563, 883, 599]]
8) Math – Short Answer Shown in the image is triangle ABC, with \(\mathrm{AB} = 10\) and \(\mathrm{BC} = 17\) . The length of the altitude from B to AC is 8. Answer the following two questions about ABC:  

text[[115, 616, 812, 669]]
1. What is the sum of all possible lengths of AC? 
2. Assume that angle BAC is obtuse. A point P is in the same plane as ABC. What is the minimum sum of the lengths of the altitudes from P to AB, AC, and BC?  

text[[115, 685, 344, 703]]
ANSWER: \(1 - 30, 2 - 72 / 17\)sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[113, 127, 880, 164]]
9) Biology – Multiple Choice Which of the following is NOT a human physiological response to pregnancy?  

text[[115, 180, 740, 250]]
W) Retention of salt and water in the kidneys  
X) Breast enlargement and development of a mature glandular structure  
Y) Hyperventilation  
Z) Increased secretion of luteinizing hormone and follicle-stimulating hormone  

text[[115, 266, 876, 303]]
ANSWER: Z) INCREASED SECRETION OF LUTEINIZING HORMONE AND FOLLICLE- STIMULATING HORMONE  

sub_title[[463, 323, 533, 341]]
## BONUS  

text[[115, 360, 852, 396]]
9) Biology – Short Answer What animal hormone is characterized by its minute-to-minute pulses of secretion, paradoxical to the standard model of hormonal regulation?  

text[[115, 411, 828, 448]]
ANSWER: SOMATOTROPIN (ACCEPT: GROWTH HORMONE, HUMAN GROWTH HORMONE, HGH)  

sub_title[[456, 504, 540, 521]]
## TOSS-UP  

text[[115, 540, 877, 629]]
10) Earth and Space – Short Answer Identify all of the following three statements regarding the lunar KREEP [creep] that are true: 1) The distribution of KREEP is uniform throughout a layer beneath the lunar crust; 2) The deposition of KREEP is attributed to the presence of a lunar magma ocean shortly after the moon’s formation; 3) KREEP is heat-generating due to the presence of radioactive isotopes.  

text[[115, 647, 282, 665]]
ANSWER: 2 AND 3  

sub_title[[463, 685, 533, 702]]
## BONUS  

text[[115, 721, 872, 775]]
10) Earth and Space – Short Answer Order the following four layers of an idealized ophiolite sequence from topmost to bottommost: 1) Sheet dike complex; 2) Pillow basalts; 3) Depleted harzburgite; 4) Layered gabbro.  

text[[115, 792, 280, 809]]
ANSWER: 2, 1, 4, 3sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 126, 856, 163]]
11) Physics – Multiple Choice Which of the following pairs of thermodynamic variables is NOT a conjugate variable pair?  

text[[115, 180, 452, 250]]
W) Temperature and entropy 
X) Volume and pressure 
Y) Helmholtz free energy and enthalpy 
Z) Chemical potential and particle number  

text[[115, 266, 648, 285]]
ANSWER: Y) HELMHOLTZ FREE ENERGY AND ENTHALPY  

sub_title[[462, 304, 533, 322]]
## BONUS  

text[[115, 340, 879, 394]]
11) Physics – Short Answer A particle moving in two dimensions has a potential energy equal to the expression \(x^2 t + y^2 t\). Identify all of the following three quantities that will be conserved in this system: 1) Linear momentum; 2) Angular momentum; 3) Energy.  

text[[115, 409, 279, 427]]
ANSWER: 2 ONLY  

sub_title[[456, 484, 541, 502]]
## TOSS-UP  

text[[115, 520, 806, 574]]
12) Energy – Short Answer Contemporary research on the common theme of protein aggregate spread during neurodegenerative disease progression is centered around what microtubule-associated protein?  

text[[115, 590, 339, 608]]
ANSWER: TAU PROTEIN  

sub_title[[424, 629, 572, 647]]
## VISUAL BONUS  

text[[115, 665, 864, 719]]
12) Energy – Multiple Choice Researchers at the Lawrence Livermore National Lab have developed novel methods of antibody design to target SARS-CoV-2. Which of the following is most likely representative of the blue region of the pictured biological model?  

text[[115, 735, 329, 805]]
W) Spike glycoprotein 
X) Hemagglutinin esterase 
Y) Nucleocapsid protein 
Z) Class 1 Fusion Protein  

text[[115, 822, 450, 840]]
ANSWER: W) SPIKE GLYCOPROTEINsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 126, 844, 163]]
13) Chemistry – Multiple Choice Which of the following statements regarding carboxylic acid derivatives is NOT true?  

text[[114, 179, 712, 251]]
W) They are more electrophilic in acidic conditions than basic conditions 
X) Nitriles are carboxylic acid derivatives 
Y) Amides can by hydrolyzed to amines in both acidic and basic conditions 
Z) C-O carbonyl bonds are stronger in amides than acid chlorides  

text[[115, 266, 828, 302]]
ANSWER: Z) C-O CARBONYL BONDS ARE STRONGER IN AMIDES THAN ACID CHLORIDES  

sub_title[[424, 321, 573, 339]]
## VISUAL BONUS  

text[[115, 357, 840, 411]]
13) Chemistry – Short Answer Shown in the image is an NMR spectrum of an unknown organic compound with formula \(\mathrm{C_9H_{10}O}\) . Answer the following two questions regarding the image:  

text[[115, 426, 682, 463]]
1. What functional group is responsible for the multiplet above 7 ppm? 
2. What oxygen-containing functional group is present in the molecule?  

text[[115, 479, 794, 498]]
ANSWER: 1 – PHENYL (ACCEPT: ARYL; AROMATIC RING); 2 – ALDEHYDE  

sub_title[[455, 553, 541, 572]]
## TOSS-UP  

text[[115, 590, 652, 610]]
14) Math – Multiple Choice What is the 2-adic valuation of 768?  

text[[115, 627, 156, 694]]
W) 6 
X) 7 
Y) 8 
Z) 9  

text[[115, 712, 247, 731]]
ANSWER: Y) 8  

sub_title[[424, 749, 573, 768]]
## VISUAL BONUS  

text[[115, 786, 854, 840]]
14) Math – Short Answer Shown in the image is a regular octagon is inscribed in a triangle such that three of its sides lie on the sides of the triangle, as shown in the diagram. If the side length of the octagon is 2, what is the area of the black region?  

text[[115, 857, 445, 875]]
ANSWER: 4 PLUS 2 SQUARE ROOT 2sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 126, 844, 163]]
15) Biology - Short Answer What nucleobase is most common in primers used by reverse transcriptase to make cDNA from mRNA?  

text[[115, 180, 301, 198]]
ANSWER: THYMINE  

sub_title[[463, 218, 533, 236]]
## BONUS  

text[[115, 254, 869, 310]]
15) Biology - Short Answer Rank the following four molecules in chronological order in the catecholamine biosynthetic pathway: 1) Dopamine; 2) L-Dopa; 3) Epinephrine; 4) Norepinephrine.  

text[[115, 325, 280, 343]]
ANSWER: 2, 1, 4, 3  

sub_title[[456, 397, 540, 416]]
## TOSS-UP  

text[[115, 433, 835, 471]]
16) Earth and Space - Multiple Choice Which of the following statements regarding the solubility of water in magma is false?  

text[[115, 487, 870, 576]]
W) The solubility of water in magma increases with increased pressure 
X) The addition of CO2 increases the activity of water in magma 
Y) At low pressures, water hydrolyses the magma by breaking up silica polymers 
Z) At pressures greater than 0.1 gigapascals, the solubility of water in magma increases linearly as a function of pressure  

text[[115, 593, 830, 630]]
ANSWER: X) THE ADDITION OF CO2 INCREASES THE ACTIVITY OF WATER IN MAGMA  

sub_title[[424, 650, 573, 669]]
## VISUAL BONUS  

text[[115, 687, 879, 759]]
16) Earth and Space - Short Answer Shown is a block of sandstone representative of a small section of porous strata. In meters per second and in scientific notation to two significant figures, calculate the flow rate of water through the block from point A to point B with the parameters given.  

text[[115, 776, 288, 794]]
ANSWER: \(5.0 \times 10^{- 3}\)sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 126, 853, 181]]
17) Physics – Short Answer A star emits the most blackbody radiation at 500 nanometers. How many times as much power does another star of the same surface area emit if the second star emits the most blackbody radiation at 250 nanometers?  

text[[115, 198, 231, 215]]
ANSWER: 16  

sub_title[[421, 233, 570, 252]]
## VISUAL BONUS  

text[[115, 270, 872, 307]]
17) Physics – Short Answer Shown in the image is a table of the nuclides arranged by atomic number and neutron number. Answer the following three questions regarding this image:  

text[[115, 323, 875, 377]]
1. What decay modes do the nuclides colored orange, blue, and yellow undergo, respectively? 
2. What doubly magic nucleus is the heaviest stable isotope? 
3. Into what lettered stable isotope will the isotope of tantalum outlined in blue eventually decay?  

text[[115, 392, 730, 411]]
ANSWER: 1 – BETA PLUS, BETA MINUS, ALPHA; 2 – LEAD- 208; 3 – B  

sub_title[[456, 468, 540, 486]]
## TOSS-UP  

text[[115, 504, 844, 540]]
18) Chemistry – Multiple Choice What functional group is formed by the reaction of acid anhydrides with excess methylamine?  

text[[115, 557, 280, 627]]
W) Primary amide X) Secondary amide Y) Enamine Z) Imine  

text[[115, 644, 426, 662]]
ANSWER: X) SECONDARY AMIDE  

sub_title[[463, 680, 533, 698]]
## BONUS  

text[[115, 716, 880, 787]]
18) Chemistry – Short Answer Cyclobutadiene is a molecule of great interest to scientists. Once isolated, scientists discovered that the structure of cyclobutadiene was not perfectly square-like, but rather a rapidly-interconverting equilibrium between two rectangular forms. What effect likely causes this phenomenon?  

text[[115, 803, 503, 821]]
ANSWER: PSEUDO-JAHN-TELLER EFFECTsub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 126, 865, 198]]
19) Energy - Multiple Choice Researchers at SLAC National Accelerator Lab are analyzing the effects of dark matter haloes on galaxy formation and evolution. Galaxy mergers are also thought to drive galactic evolution. Which of the following statements regarding the role of galaxy mergers in galactic evolution is least accurate?  

text[[115, 215, 868, 285]]
W) Smaller spiral galaxies merge to form large elliptical galaxies  X) Star formation rate may rapidly increase as a result of galaxy mergers  Y) Quasar activity may be triggered as a result of galaxy mergers  Z) Galaxy mergers are significantly more common in the present epoch than 9 billion years ago  

text[[115, 302, 840, 339]]
ANSWER: Z) GALAXY MERGERS ARE SIGNIFICANTLY MORE COMMON IN THE PRESENT EPOCH THAN 9 BILLION YEARS AGO  

sub_title[[424, 360, 573, 378]]
## VISUAL BONUS  

text[[115, 396, 882, 433]]
19) Energy - Short Answer Shown in the image is an anion being studied at Pacific Northwest National Lab. Answer the following two questions about the image:  

text[[115, 449, 456, 485]]
1) What element is indicated by the arrow?  
2) What is the charge of this anion?  

text[[115, 501, 695, 520]]
ANSWER: 1 - BORON (ACCEPT: B); 2 - (- 2) (DO NOT ACCEPT: 2)  

sub_title[[456, 577, 540, 595]]
## TOSS-UP  

text[[115, 614, 861, 650]]
20) Math - Short Answer Let \(f\) be a permutation of the first 15 positive integers. How many different values are possible for the sum of the first 11 elements of \(f\) ?  

text[[115, 667, 231, 684]]
ANSWER: 45  

sub_title[[463, 702, 534, 720]]
## BONUS  

text[[115, 739, 860, 792]]
20) Math - Short Answer A monic cubic \(P(x)\) has roots of 1, \(r\) , and \(r\) squared, where \(r\) is a positive integer greater than 1. Given that \(P(3) = -2\) , at what \(x\) value between 1 and \(r\) is there a local maximum?  

text[[115, 809, 560, 826]]
ANSWER: 7 MINUS SQUARE ROOT 7 ALL OVER 3sub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[113, 127, 875, 163]]
21) Biology – Multiple Choice What post-translational histone modification demarcates large chromatin domains around sites of DNA breakage?  

text[[114, 180, 420, 250]]
W) Methylation 
X) Acetylation 
Y) Phosphorylation 
Z) Sumoylation [soo-moy-LAY-shun]  

text[[114, 266, 515, 285]]
ANSWER: Y) HISTONE PHOSPHORYLATION  

sub_title[[462, 305, 533, 322]]
## BONUS  

text[[114, 341, 881, 412]]
21) Biology – Short Answer Rank the following four steps of X-chromosome inactivation in chronological order: 1) Pluripotency factors bind to the X-inactivation centers, 2) CTCF joins the two X chromosomes, 3) CTCF and the pluripotency factors move to one of the two X chromosomes, 4) mRNA recruits compaction proteins to form a Barr body.  

text[[115, 428, 280, 446]]
ANSWER: 1, 2, 3, 4  

sub_title[[456, 504, 540, 521]]
## TOSS-UP  

text[[114, 540, 872, 593]]
22) Earth and Space – Short Answer Neutron star glitches, characterized by a slight, but sudden, increase in rotational speed, are thought to be caused by what phenomenon occurring in the solid crust of the neutron star?  

text[[115, 611, 330, 628]]
ANSWER: STARQUAKE  

sub_title[[462, 648, 533, 666]]
## BONUS  

text[[113, 686, 875, 722]]
22) Earth and Space – Short Answer Shown in the image is an aerial photograph of a polynya [poh-LIH-nia] off the coast of Antarctica. Answer the following two questions about the image:  

text[[114, 739, 866, 810]]
1) The formation of coastal polynyas is primarily driven by what winds that flow out from the Antarctic interior? 
2) Polynyas are thought to drive the formation of what dense water mass via brine rejection and surface cooling?  

text[[113, 826, 830, 862]]
ANSWER: 1 – KATABATIC WINDS; 2 – ANTARCTIC BOTTOM WATER (ACCEPT: AABW)sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[114, 127, 852, 216]]
23) Physics - Short Answer In some grand unified theories, protons are predicted to be unstable. With a half-life of around \(10^{31}\) years, they would decay into a positron and a neutral pion. Which of the following three conservation laws would this decay process violate? 1) Conservation of charge; 2) Conservation of lepton number; 3) Conservation of baryon number.  

text[[115, 232, 283, 250]]
ANSWER: 2 AND 3  

sub_title[[424, 269, 572, 287]]
## VISUAL BONUS  

text[[115, 306, 839, 359]]
23) Physics - Short Answer This Feynman diagram depicts a hypothetical decay process currently under investigation by scientists around the world. Answer the following three questions:  

text[[115, 375, 850, 445]]
1. What is the name of this decay process?  
2. What particles are represented by the blue squiggles?  
3. If observed, this decay would imply that neutrinos belong to what currently empty class of particles?  

text[[115, 462, 814, 498]]
ANSWER: 1 - NEUTRINOLESS DOUBLE BETA DECAY; 2 - W MINUS BOSONS; 3 - MAJORANA FERMIONS (ACCEPT: MAJORANA PARTICLES)