sub_title[[455, 140, 540, 157]]
## TOSS-UP  

text[[115, 178, 880, 215]]
1) Chemistry – Short Answer Phosphoryl chloride can be used to synthesize alkyl halides from what class of organic molecules?  

text[[115, 231, 315, 249]]
ANSWER: ALCOHOLS  

sub_title[[460, 267, 531, 286]]
## BONUS  

text[[115, 304, 866, 357]]
1) Chemistry – Short Answer When the molecule bilirubin is exposed to blue light, one of its carbon-carbon double bonds changes configuration from Z to E. What is the specific term for this type of reaction?  

text[[115, 372, 430, 390]]
ANSWER: PHOTOISOMERIZATION  

sub_title[[455, 443, 540, 460]]
## TOSS-UP  

text[[115, 477, 880, 513]]
2) Physics – Short Answer A 9 volt battery is connected to a nichrome wire, through which 4 amperes flow. What will the wire’s resistance be if it is squished down to half its original length?  

text[[115, 524, 306, 542]]
ANSWER: 9/16 OHMS  

sub_title[[460, 555, 533, 572]]
## BONUS  

text[[115, 591, 833, 644]]
2) Physics – Short Answer A block starts sliding down a frictionless 80 centimeter ramp inclined at a \(30^{\circ}\) angle downwards to the right. As a vector, what is its velocity right before reaching the floor?  

text[[115, 655, 321, 674]]
ANSWER: \(1.4\sqrt{3}\mathrm{i} - 1.4\mathrm{j}\)sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[114, 127, 875, 165]]
3) Biology – Short Answer Identify all of the following three groups of bacteria that are gram-positive: 1) Chlamydias; 2) Spirochetes [SPY-ruh-keets]; 3) Cyanobacteria.  

text[[116, 180, 356, 198]]
ANSWER: NONE OF THEM  

sub_title[[463, 211, 533, 228]]
## BONUS  

text[[113, 242, 853, 279]]
3) Biology – Multiple Choice Given a sponge sample, which of the following would be the most informative in determining the number of different kinds of prokaryotic contaminants?  

text[[113, 294, 710, 331]]
W) Compare the sequences of the genes that encode ribosomal RNA for all the cells that are part of the sponge sample.  

text[[114, 331, 700, 348]]
X) Culture each of the microorganisms and then test their susceptibility to  

text[[114, 349, 422, 364]]
antibiotics that kill bacteria or archaea.  

text[[114, 365, 875, 400]]
Y) Culture the microorganisms and classify them according to their nutritional requirements and biochemical pathways.  

text[[114, 400, 686, 435]]
Z) Examine the microorganisms under a microscope to see whether they look like bacteria or like archaea.  

text[[113, 450, 866, 486]]
ANSWER: W) COMPARE THE SEQUENCES OF THE GENES THAT ENCODE RIBOSOMAL RNA FOR ALL THE CELLS THAT ARE PART OF THE SPONGE SAMPLE  

sub_title[[456, 550, 541, 568]]
## TOSS-UP  

text[[114, 585, 871, 638]]
4) Earth and Space – Short Answer Identify all of the following three statements that are true about circulation in a mature hurricane: 1) Air sinks in the eye; 2) Air rises in the eyewall; 3) At the top of the hurricane, most air travels towards the eye.  

text[[115, 654, 240, 672]]
ANSWER: 1, 2  

sub_title[[463, 685, 533, 703]]
## BONUS  

text[[113, 720, 875, 756]]
4) Earth and Space – Short Answer A binary system has a total mass of 27 solar masses. If the period of rotation is 8 years, find the semimajor axis of the system, in AU.  

text[[115, 772, 264, 789]]
ANSWER: 12 AUsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[113, 127, 879, 163]]
5) Math - Multiple Choice The complex number \(3 + 4\mathrm{i}\) is multiplied by the complex number \(-8 + 8\mathrm{i}\) . By how many degrees does its argument increase?  

text[[114, 180, 252, 250]]
W) \(- 135\) degrees 
X) \(- 45\) degrees 
Y) 45 degrees 
Z) 135 degrees  

text[[115, 267, 357, 285]]
ANSWER: Z) 135 DEGREES  

sub_title[[462, 302, 533, 320]]
## BONUS  

text[[113, 337, 875, 373]]
5) Math - Short Answer For the curve given parametrically by \(x = \ln t\) and \(y = t \ln t\) , what is the derivative of \(y\) with respect to \(x\) when \(t = e^{2}\) ?  

text[[115, 388, 236, 406]]
ANSWER: \(3e^{2}\)  

sub_title[[456, 440, 541, 459]]
## TOSS-UP  

text[[114, 488, 864, 559]]
6) Energy - Multiple Choice Scientists at Oak Ridge National Lab are working to refine a sorbent that can effectively recover lithium salts from concentrated brines at geothermal plants. This is motivated by the lack of significant deposits of conventional lithium ores in the United States. Which of the following is a conventional ore of lithium?  

text[[114, 576, 378, 647]]
W) Spodumene 
X) Pentlandite 
Y) Chalcopyrite [KAL-co-pyrite] 
Z) Sylvite  

text[[115, 662, 361, 680]]
ANSWER: W) SPODUMENE  

sub_title[[462, 710, 533, 728]]
## BONUS  

text[[115, 745, 875, 799]]
6) Energy - Short Answer Scientists at Argonne National Lab are investigating the pressure-induced solid phase transition in cadmium sulfide nanocrystals from the wurtzite structure to the rocksalt structure. What are the coordination numbers of wurtzite and rocksalt, respectively?  

text[[115, 810, 312, 828]]
ANSWER: 4,4 AND 6,6sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 880, 199]]
7) Chemistry – Short Answer An alkene is placed in a reaction vessel with water. Identify all of the following three changes to the reaction vessel that would favor acid-catalyzed hydration to an alcohol: 1) Decreasing temperature; 2) Adding dilute sulfuric acid; 3) Increasing alkene concentration.  

text[[115, 215, 248, 233]]
ANSWER: ALL  

sub_title[[463, 250, 533, 268]]
## BONUS  

text[[115, 284, 863, 321]]
7) Chemistry – Short Answer Identify all of the following three reagents that can function as nucleophiles but not bases: 1) Sodium hydride; 2) Methanol; 3) Hydroxide.  

text[[115, 336, 355, 354]]
ANSWER: NONE OF THEM  

sub_title[[456, 406, 541, 424]]
## TOSS-UP  

text[[115, 441, 842, 478]]
8) Physics – Short Answer What variational principle explains reflection and refraction as consequences of light rays taking the quickest path between two given points?  

text[[115, 488, 763, 507]]
ANSWER: FERMAT'S PRINCIPLE (ACCEPT: PRINCIPLE OF LEAST TIME)  

sub_title[[463, 549, 533, 567]]
## BONUS  

text[[115, 584, 857, 637]]
8) Physics – Short Answer When heated from \(29^{\circ}\mathrm{C}\) to \(54^{\circ}\mathrm{C}\) , a 2 meter long metal rod expands by 250 micrometers. Calculate the coefficient of volume expansion of the rod, giving your answer in scientific notation.  

text[[115, 647, 513, 667]]
ANSWER: \(1.5 \times 10^{- 5} / \mathrm{K}\) (ACCEPT: \(1.5 \times 10^{- 5} / ^{\circ}\mathrm{C}\) )sub_title[[456, 91, 541, 108]]
## TOSS-UP  

text[[113, 127, 865, 163]]
9) Biology - Short Answer What is the name for the instrument that determines diastolic and systolic pressures using an inflatable cuff?  

text[[115, 180, 433, 198]]
ANSWER: SPHYGMOMANOMETER  

sub_title[[460, 210, 530, 228]]
## BONUS  

text[[113, 246, 860, 283]]
9) Biology - Short Answer What major plant hormone is synthesized in plastids through the terpenoid pathway?  

text[[115, 294, 352, 312]]
ANSWER: ABSCISIC ACID  

sub_title[[456, 359, 540, 377]]
## TOSS-UP  

text[[113, 397, 843, 416]]
10) Earth and Space - Short Answer What is the second most common anion in seawater?  

text[[115, 432, 444, 451]]
ANSWER: SULFATE (ACCEPT: \(\mathrm{SO}_4^{2 - }\)  

sub_title[[462, 451, 533, 468]]
## BONUS  

text[[115, 485, 863, 522]]
10) Earth and Space - Short Answer Identify all of the following four particles that are a significant constituent of primary cosmic rays: 1) Photon; 2) Proton; 3) Alpha particle; 4) Pion.  

text[[115, 538, 240, 555]]
ANSWER: 2, 3sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 869, 163]]
11) Math - Short Answer A diagonal of a regular hexagon measures 6 cm. What is the ratio of the largest possible area of the hexagon to the smallest possible area of the hexagon?  

text[[115, 180, 235, 197]]
ANSWER: 4/3  

sub_title[[462, 198, 533, 216]]
## BONUS  

text[[115, 232, 872, 268]]
11) Math - Short Answer Compute the double integral of \(xy\) dx dy on the square domain with \(x = 0\) to \(x = 8\) and \(y = 0\) to \(y = 8\) .  

text[[115, 284, 250, 302]]
ANSWER: 1024  

sub_title[[456, 337, 540, 355]]
## TOSS-UP  

text[[115, 371, 877, 460]]
12) Energy - Short Answer Scientists at Pacific Northwest National Lab have developed a model for the multistep dissolution of gibbsite, one of the polymorphs of aluminum hydroxide. Identify all of the following three statements about aluminum hydroxide that are true: 1) Its solid form is held together by hydrogen bonds; 2) When aluminum hydroxide is reacted with acid, the aluminate ion is formed; 3) Aluminum hydroxide is amphoteric.  

text[[115, 471, 240, 488]]
ANSWER: 1, 3  

sub_title[[462, 501, 533, 519]]
## BONUS  

text[[115, 537, 868, 609]]
12) Energy - Short Answer Scientists at Lawrence Berkeley National Lab have disproved the validity of the 3.5 kiloelectron-volt line as evidence for a form of dark matter. The 3.5 keV line was previously thought to be emitted from the decay of what hypothetical, low mass particles that only interact through gravity?  

text[[115, 620, 682, 639]]
ANSWER: STERILE NEUTRINOS (ACCEPT: INERT NEUTRINOS)sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 870, 163]]
13) Chemistry – Multiple Choice An alkene is treated with cold potassium permanganate and sodium hydroxide. What will be the major product of this reaction?  

text[[115, 180, 247, 250]]
W) Syn-1,2- diol 
X) Anti-1,2- diol 
Y) Syn-1,3- diol 
Z) Anti-1,3- diol  

text[[116, 267, 364, 285]]
ANSWER: W) SYN-1,2- DIOL  

sub_title[[463, 302, 533, 320]]
## BONUS  

text[[115, 336, 822, 389]]
13) Chemistry – Multiple Choice Hydrogenation of alkenes can be achieved using both homogeneous and heterogeneous catalysts. Which of the following is an example of a homogeneous catalyst used in hydrogenation?  

text[[115, 406, 319, 476]]
W) Ziegler-Natta catalyst 
X) Lindlar's catalyst 
Y) Wilkinson's catalyst 
Z) Grubbs catalyst  

text[[115, 493, 472, 510]]
ANSWER: Y) WILKINSON'S CATALYST  

sub_title[[456, 563, 540, 581]]
## TOSS-UP  

text[[115, 597, 867, 650]]
14) Physics – Short Answer What is the name of the effect responsible for an increase in the effective resistance of wires at high frequencies as current density is concentrated at the surface of the conductor?  

text[[115, 662, 333, 680]]
ANSWER: SKIN EFFECT  

sub_title[[463, 698, 533, 716]]
## BONUS  

text[[115, 733, 880, 786]]
14) Physics – Short Answer When a block is attached to a massless spring, the spring extends 10 centimeters under the weight of the block. To the nearest tenth of a second, what would be the period of oscillations of the spring-block system?  

text[[115, 797, 330, 815]]
ANSWER: 0.6 SECONDSsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 853, 163]]
15) Biology - Multiple Choice Which of the following is not a way by which muscle fibers can increase their ATP concentration?  

text[[115, 180, 745, 250]]
W) Dehydrating phosphoric acid to add to ADP 
X) Phosphorylation of ADP by creatine phosphate 
Y) Oxidative phosphorylation of ADP in mitochondria 
Z) Substrate-level phosphorylation of ADP by glycolysis or the citric acid cycle  

text[[115, 262, 716, 280]]
ANSWER: W) DEHYDRATING PHOSPHORIC ACID TO ADD TO ADP  

sub_title[[462, 310, 533, 328]]
## BONUS  

text[[115, 345, 859, 381]]
15) Biology - Short Answer The glyoxylate cycle is an anabolic pathway in plants, bacteria, protists, and fungi that takes place in a specialized type of what more common organelle?  

text[[115, 391, 656, 410]]
ANSWER: PEROXISOME (DO NOT ACCEPT: GLYOXYSOME)  

sub_title[[456, 470, 541, 488]]
## TOSS-UP  

text[[115, 504, 849, 558]]
16) Earth and Space - Multiple Choice Minerals like zircon and xenotime [ZEE-no-time] precipitate from highly evolved magmas that are rich in incompatible elements. Which of the following is an example of an incompatible element?  

text[[115, 576, 325, 647]]
W) Magnesium 
X) Aluminum 
Y) Fluorine 
Z) Yttrium [YIH-tree-um]  

text[[115, 662, 325, 681]]
ANSWER: Z) YTTRIUM  

sub_title[[462, 693, 533, 711]]
## BONUS  

text[[115, 728, 835, 747]]
16) Earth and Space - Short Answer Spicules are jets of plasma in what layer of the sun?  

text[[115, 764, 370, 781]]
ANSWER: CHROMOSPHEREsub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[114, 126, 872, 164]]
17) Math – Short Answer In how many ways can 21 identical marbles be distributed amongst 7 people such that no two people have the same number of marbles?  

text[[115, 179, 251, 198]]
ANSWER: 5040  

sub_title[[460, 215, 531, 233]]
## BONUS  

text[[115, 250, 875, 288]]
17) Math – Short Answer What is the length of the path traced by the function \(f(t) = (t, 3\) cosine \(t, 3\) sine \(t\) ) from \(t = 0\) to \(t = 3\) ?  

text[[115, 303, 418, 322]]
ANSWER: 3 SQUARE ROOT OF 10  

sub_title[[456, 374, 540, 393]]
## TOSS-UP  

text[[115, 411, 880, 449]]
18) Energy – Multiple Choice Scientists at Thomas Jefferson National Accelerator are studying the structure of the pion. The pion, along with other mesons, mediates what interaction?  

text[[115, 460, 312, 531]]
W) Beta minus decay 
X) Beta plus decay 
Y) Residual strong force 
Z) Color force  

text[[115, 546, 484, 565]]
ANSWER: Y) RESIDUAL STRONG FORCE  

sub_title[[462, 577, 533, 595]]
## BONUS  

text[[115, 622, 866, 678]]
18) Energy – Short Answer Scientists at Argonne National Lab are studying the NatA/Naa50 enzyme complex, which co-translationally acetylates the N-termini of over 40% of eukaryotic proteins. From which molecule is the acetyl group derived during N-terminus acetylation?  

text[[115, 688, 737, 708]]
ANSWER: ACETYL- COA (ACCEPT: AC- COA, ACETYL- COENZYME A)sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 861, 181]]
19) Chemistry - Multiple Choice The hydrohalogenation of alkynes proceeds via a disputed reaction mechanism. One of the proposed mechanisms is termolecular. Which of the following may be a reason scientists were hesitant to accept this mechanism as valid?  

text[[115, 198, 644, 269]]
W) Termolecular reactions are statistically unlikely to occur 
X) Termolecular reactions have unusually high activation energies 
Y) Termolecular reactions are entropically disfavored 
Z) Termolecular reactions produce various unwanted side products  

text[[115, 284, 850, 320]]
ANSWER: W) TERMOLECULAR REACTIONS ARE STATISTICALLY UNLIKELY TO OCCUR  

sub_title[[463, 336, 533, 355]]
## BONUS  

text[[115, 371, 872, 408]]
19) Chemistry - Short Answer Identify all of the following three polymers that can be formed via radical polymerization: 1) Polyethylene; 2) Polyvinylchloride; 3) Polyurethane.  

text[[116, 423, 283, 441]]
ANSWER: 1 AND 2  

sub_title[[456, 507, 540, 525]]
## TOSS-UP  

text[[115, 544, 861, 597]]
20) Physics - Short Answer The Lennard-Jones potential contains terms of \(r\) , the distance between particles, to the negative 6th and 12th powers. Which of the following forces explains the \(\mathrm{r}^{-12}\) term?  

text[[115, 611, 343, 681]]
W) Pauli repulsion 
X) Coulomb forces 
Y) London dispersion forces 
Z) Dipole-dipole forces  

text[[115, 692, 411, 710]]
ANSWER: W) PAULI REPULSION  

sub_title[[463, 740, 533, 758]]
## BONUS  

text[[115, 775, 880, 845]]
20) Physics - Short Answer A uniform, spherical planet has a local acceleration due to gravity of \(7 \mathrm{m / s^2}\) at the surface. If the radius of the planet is 2450 kilometers, compute, to two significant digits and in scientific notation, the mass of the planet in kilograms. Assume that the universal gravitational constant is \(6.67 * 10^{-11}\) meters cubed per kilogram second squared.  

text[[116, 857, 410, 875]]
ANSWER: \(6.3 * 10^{23}\) KILOGRAMSsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[113, 127, 864, 147]]
21) Biology - Short Answer Roots may release phytosiderophores to absorb what metal ion?  

text[[115, 157, 397, 176]]
ANSWER: IRON (ACCEPT: \(\mathrm{Fe}^{3 + }\) )  

sub_title[[463, 189, 533, 207]]
## BONUS  

text[[115, 223, 867, 260]]
21) Biology - Short Answer Bees, yellow jackets, and wasps all share similar coloring due to what form of mimicry?  

text[[115, 270, 419, 289]]
ANSWER: MÜLLERIAN MIMICRY  

sub_title[[456, 336, 541, 354]]
## TOSS-UP  

text[[115, 370, 790, 407]]
22) Earth and Space - Multiple Choice Which of the following minerals is NOT an inosilicate?  

text[[115, 424, 237, 494]]
W) Augite 
X) Hornblende 
Y) Enstatite 
Z) Epidote  

text[[115, 511, 316, 529]]
ANSWER: Z) EPIDOTE  

sub_title[[463, 546, 533, 564]]
## BONUS  

text[[115, 581, 872, 652]]
22) Earth and Space - Short Answer An unsaturated air parcel with a temperature of \(20^{\circ}\mathrm{C}\) rises from the surface with a dry adiabatic lapse rate of \(7^{\circ}\mathrm{C / km}\) and a wet adiabatic lapse rate of \(5^{\circ}\mathrm{C / km}\) . Assuming the dew point at the surface is \(14^{\circ}\mathrm{C}\) and the dew point lapse rate is \(2^{\circ}\mathrm{C / km}\) , at what altitude, in meters, will clouds start forming?  

text[[115, 668, 333, 686]]
ANSWER: 1200 METERSsub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[113, 127, 874, 163]]
23) Math – Multiple Choice Jack rolls some 8-sided dice and sums the result of each die. There are exactly 2003 possible values for that sum. How many dice does Jack have?  

text[[115, 180, 178, 251]]
W) 284 
X) 285 
Y) 286 
Z) 287  

text[[115, 268, 266, 286]]
ANSWER: Y) 286  

sub_title[[463, 303, 533, 320]]
## BONUS  

text[[115, 337, 872, 389]]
23) Math – Short Answer Let A and B be nodes on a complete 12-graph. How many paths start at A, end at B, visit at most 5 distinct nodes including A and B, and never go to the same node twice?  

text[[115, 407, 238, 424]]
ANSWER: 821