sub_title[[455, 144, 541, 162]]
## TOSS-UP  

text[[114, 178, 877, 231]]
1) Chemistry – Multiple Choice According to the particle-in-a-box model, when the length of the box is increased by a factor of 2, by what factor will the energy of each allowed energy level change?  

text[[114, 247, 175, 316]]
W) 1/4 
X) 1/2 
Y) 2 
Z) 4  

text[[115, 334, 266, 352]]
ANSWER: W) 1/4  

sub_title[[462, 370, 533, 388]]
## BONUS  

text[[114, 404, 850, 440]]
1) Chemistry – Short Answer Order the following three compounds from most covalent to least covalent: 1) KCl; 2) BeCl₂; 3) LiBr.  

text[[115, 456, 259, 474]]
ANSWER: 2, 3, 1  

sub_title[[455, 526, 541, 545]]
## TOSS-UP  

text[[114, 560, 875, 596]]
2) Math – Multiple Choice Given that the natural log of 2 is roughly equal to 0.693, which of the following values is closest to the natural log of 8?  

text[[114, 612, 192, 682]]
W) 0.173 
X) 0.231 
Y) 2.079 
Z) 2.772  

text[[115, 700, 281, 718]]
ANSWER: Y) 2.079  

sub_title[[462, 735, 533, 753]]
## BONUS  

text[[114, 770, 874, 822]]
2) Math – Short Answer A concert sold 13 tickets, each to either an adult or a child. The cost of an adult ticket is \(2.70 and the cost of a child ticket is\) 2.10. If the total value of the tickets is \(31.50, how many adult tickets were sold?  

text[[115, 839, 220, 856]]
ANSWER: 7sub_title[[455, 91, 540, 108]]
## TOSS-UP  

text[[113, 127, 842, 163]]
3) Earth and Space – Multiple Choice When viewed from Jupiter, which of the following planets has the greatest maximum elongation?  

text[[114, 180, 216, 250]]
W) Mercury 
X) Venus 
Y) Earth 
Z) Mars  

text[[115, 267, 290, 285]]
ANSWER: Z) MARS  

sub_title[[463, 302, 533, 320]]
## BONUS  

text[[114, 336, 848, 372]]
3) Earth and Space – Multiple Choice In the Northern Hemisphere, at approximately what latitude does air in Ferrel cells rise?  

text[[114, 389, 275, 458]]
W) 0 degrees north 
X) 15 degrees north 
Y) 30 degrees north 
Z) 60 degrees north  

text[[115, 475, 422, 493]]
ANSWER: Y) 30 DEGREES NORTH  

sub_title[[455, 546, 540, 564]]
## TOSS-UP  

text[[113, 580, 843, 616]]
4) Biology – Multiple Choice Which of the following correctly identifies end products of glycolysis?  

text[[114, 633, 501, 702]]
W) 1 pyruvate molecule and 1 NADH molecule 
X) 2 pyruvate molecules and 1 NADH molecule 
Y) 1 pyruvate molecule and 2 NADH molecules 
Z) 2 pyruvate molecules and 2 NADH molecules  

text[[115, 719, 722, 737]]
ANSWER: Z) 2 PYRUVATE MOLECULES AND 2 NADH MOLECULES  

sub_title[[463, 754, 533, 772]]
## BONUS  

text[[113, 789, 814, 808]]
4) Biology – Multiple Choice Which of the following is least accurate about miRNA?  

text[[114, 824, 620, 893]]
W) miRNAs form from hairpins in RNA transcripts 
X) The length of most miRNAs is between 10 and 50 base pairs 
Y) miRNAs are exogenous 
Z) miRNAs are single stranded  

text[[115, 910, 475, 928]]
ANSWER: Y) miRNAs ARE EXOGENOUS  

text[[115, 943, 384, 960]]
Discord Spring Tournament—RRsub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 126, 830, 163]]
5) Physics – Short Answer By what factor is the equivalent capacitance of two identical capacitors multiplied if they are connected in parallel as opposed to in series?  

text[[115, 180, 221, 197]]
ANSWER: 4  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 249, 882, 320]]
5) Physics – Short Answer Identify all of the following three statements that are true regarding entropy: 1) The entropy of a system can never decrease; 2) The entropy of the universe can never decrease; 3) The entropy of a combination of two systems is the product of their individual entropies.  

text[[115, 336, 280, 354]]
ANSWER: 2 ONLY  

sub_title[[456, 406, 540, 424]]
## TOSS-UP  

text[[115, 441, 879, 495]]
6) Energy – Short Answer Scientists at Lawrence Berkeley National Lab are developing fiber optic cables for the detection of earthquakes. Fiber optic cables rely on what phenomenon, which occurs when the angle of incidence exceeds the critical angle?  

text[[115, 510, 502, 529]]
ANSWER: TOTAL INTERNAL REFLECTION  

sub_title[[463, 546, 533, 564]]
## BONUS  

text[[115, 581, 876, 634]]
6) Energy – Short Answer Scientists at Argonne National Lab are studying oxidation-induced strain in magnetite crystals. What is the major product from the complete oxidation of magnetite?  

text[[115, 650, 639, 669]]
ANSWER: HEMATITE (ACCEPT: \(\mathrm{Fe_2O_3}\) or IRON (III) OXIDE)sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[113, 126, 796, 146]]
7) Math – Multiple Choice Which of the following numbers is NOT divisible by 4?  

text[[114, 162, 228, 233]]
W) 5,313,172  X) 5,322,864  Y) 7,524,828  Z) 9,845,542  

text[[115, 250, 313, 268]]
ANSWER: Z) 9,845,542  

sub_title[[463, 285, 533, 303]]
## BONUS  

text[[115, 320, 857, 355]]
7) Math – Short Answer In a non-leap year, January 1st will be a Monday. What day of the week will December 25th of the same year be?  

text[[115, 371, 301, 389]]
ANSWER: TUESDAY  

sub_title[[456, 440, 541, 459]]
## TOSS-UP  

text[[115, 475, 858, 529]]
8) Physics – Short Answer A car with an initial velocity of 30 meters per second undergoes constant acceleration. If the car then travels 90 meters in the next 2 seconds, what is the magnitude of the car's acceleration in meters per second?  

text[[115, 545, 230, 563]]
ANSWER: 15  

sub_title[[463, 580, 533, 598]]
## BONUS  

text[[115, 615, 880, 669]]
8) Physics – Short Answer A 400-gram tennis ball hits a concrete wall head-on at 15 meters per second. 100 milliseconds later, it leaves the wall traveling at 15 meters per second in the opposite direction. In newtons, what was the average force exerted by the wall on the tennis ball?  

text[[115, 685, 241, 702]]
ANSWER: 120sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[114, 126, 880, 181]]
9) Earth and Space – Multiple Choice When observing a sample of schist, you notice dodecahedral grains of a mysterious red mineral. Which of the following minerals have you most likely observed?  

text[[114, 198, 232, 270]]
W) Corundum  X) Almandine  Y) Cinnabar  Z) Vanadinite  

text[[116, 286, 355, 305]]
ANSWER: X) ALMANDINE  

sub_title[[456, 321, 526, 339]]
## BONUS  

text[[114, 357, 872, 411]]
9) Earth and Space – Multiple Choice You are on a beach in the afternoon and notice there is a rather strong breeze coming from the sea. Which of the following options BEST describes the mechanism behind this phenomenon?  

text[[114, 427, 783, 500]]
W) The land heats up faster than the sea, leading to low-level convergence over land  X) The land heats up faster than the sea, leading to low-level divergence over land  Y) The sea heats up faster than the land, leading to low-level convergence over land  Z) Air is pushed by the waves towards land  

text[[114, 515, 843, 551]]
ANSWER: W) THE LAND HEATS UP FASTER THAN THE SEA, LEADING TO LOW- LEVEL CONVERGENCE OVER LAND  

sub_title[[448, 604, 533, 621]]
## TOSS-UP  

text[[114, 641, 822, 678]]
10) Chemistry – Short Answer What law states that the solubility of a gas in a liquid is directly proportional to its partial pressure directly above the liquid?  

text[[116, 694, 345, 712]]
ANSWER: HENRY'S LAW  

sub_title[[462, 730, 533, 748]]
## BONUS  

text[[115, 764, 868, 836]]
10) Chemistry – Short Answer \(\mathrm{NO}_2\) is in a gas-phase equilibrium with \(\mathrm{N}_2\mathrm{O}_4\) . Given that the forward reaction is exothermic, identify all of the following three changes to the system that would shift the reaction to the left: 1) Increasing temperature; 2) Decreasing volume of reaction vessel; 3) Increasing partial pressure of \(\mathrm{NO}_2\) .  

text[[116, 852, 283, 869]]
ANSWER: 1 AND 2sub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[115, 127, 825, 163]]
11) Biology – Short Answer What enzyme is responsible for producing the majority of glucose-6-phosphate in a respiring cell?  

text[[116, 180, 337, 197]]
ANSWER: HEXOKINASE  

sub_title[[463, 216, 533, 233]]
## BONUS  

text[[115, 250, 866, 303]]
11) Biology – Short Answer The cholera bacteria infects intestinal cells by secreting a toxin that keeps G-protein coupled receptors continually in the active state. What compound does the toxin enzymatically add to a G protein to keep it activated?  

text[[116, 319, 327, 337]]
ANSWER: ADP-RIBOSE  

sub_title[[456, 389, 540, 406]]
## TOSS-UP  

text[[115, 423, 840, 494]]
12) Energy – Short Answer Scientists at Pacific Northwest National Lab are detecting concentrations of the pertechnetate ion in groundwater to assess water safety near nuclear facilities. Given that the chemical formula of pertechnetate is \(\mathrm{TcO_4^- }\) , then, indicating proper charge, what is the oxidation state of the central technetium atom?  

text[[115, 510, 430, 528]]
ANSWER: \(7+\) (DO NOT ACCEPT: 7)  

sub_title[[456, 546, 526, 563]]
## BONUS  

text[[115, 582, 877, 635]]
12) Energy – Short Answer Scientists at SLAC National Accelerator Lab are studying how proteins crystallize to form microbial shells. They observe that crystallization ends with the crystallization of the n-terminus. What functional group is present at the n-terminus of a protein?  

text[[115, 651, 445, 670]]
ANSWER: AMINE (ACCEPT: AMINO)sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 126, 881, 181]]
13) Physics – Short Answer A ball is launched off a cliff horizontally. Three seconds later, it is traveling at a 45 degree angle to the horizontal. At that moment, what is its speed to the nearest meter per second?  

text[[115, 197, 230, 214]]
ANSWER: 42  

sub_title[[462, 232, 533, 250]]
## BONUS  

text[[115, 266, 866, 337]]
13) Physics – Short Answer A satellite is circling a planet 50 kilometers above the surface with constant velocity. Given that the planet's diameter is 300 kilometers, if the satellite moves to a circular orbit 300 km above the surface, what is the ratio of its initial velocity to its final velocity?  

text[[115, 354, 400, 372]]
ANSWER: 1.5 (ACCEPT: 3 TO 2)  

sub_title[[456, 424, 540, 442]]
## TOSS-UP  

text[[115, 459, 836, 495]]
14) Earth and Space – Short Answer What was the minor supercontinent that formed the northern part of Pangaea [pan-JEE-uh]?  

text[[115, 511, 310, 528]]
ANSWER: LAURASIA  

sub_title[[456, 546, 527, 564]]
## BONUS  

text[[115, 582, 863, 618]]
14) Earth and Space – Short Answer The yellow color of Io’s surface is primarily caused by compounds of what element?  

text[[115, 635, 285, 652]]
ANSWER: SULFURsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 126, 830, 146]]
15) Math – Short Answer What is the sum of the squares of the first 5 positive integers?  

text[[115, 162, 230, 180]]
ANSWER: 55  

sub_title[[462, 198, 533, 216]]
## BONUS  

text[[115, 232, 880, 286]]
15) Math – Short Answer Three metal plates with radii of 11 centimeters, 12 centimeters, and 24 centimeters are melted down and recast into a new plate of the same thickness. In centimeters, what will be the radius of the new plate?  

text[[115, 302, 230, 320]]
ANSWER: 29  

sub_title[[456, 372, 540, 390]]
## TOSS-UP  

text[[115, 406, 857, 444]]
16) Biology – Short Answer What basophilic cell type in the gastric fundus secretes gastric lipase and pepsinogen?  

text[[115, 459, 320, 477]]
ANSWER: CHIEF CELL  

sub_title[[462, 495, 533, 512]]
## BONUS  

text[[115, 528, 877, 565]]
16) Biology – Short Answer What enzyme directly allows for the conversion of RNA to DNA in retroviruses?  

text[[115, 580, 460, 599]]
ANSWER: REVERSE TRANSCRIPTASEsub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 126, 847, 163]]
17) Chemistry – Multiple Choice Which of the following molecules has the highest vapor pressure at room temperature?  

text[[115, 180, 245, 250]]
W) Methanol 
X) Water 
Y) Acetic acid 
Z) Diethyl ether  

text[[115, 267, 388, 285]]
ANSWER: Z) DIETHYL ETHER  

sub_title[[463, 302, 533, 320]]
## BONUS  

text[[115, 336, 835, 373]]
17) Chemistry – Multiple Choice Which of the following materials is NOT considered a crystalline solid?  

text[[115, 390, 220, 460]]
W) Rubber 
X) Ceramic 
Y) Water ice 
Z) Graphite  

text[[115, 477, 319, 495]]
ANSWER: W) RUBBER  

sub_title[[456, 550, 540, 567]]
## TOSS-UP  

text[[115, 585, 850, 623]]
18) Earth and Space – Short Answer Order the following four stages of the Big Bang from first to last: 1) Nucleosynthesis; 2) Inflation; 3) Recombination; 4) Grand unification epoch.  

text[[115, 639, 280, 657]]
ANSWER: 4, 2, 1, 3  

sub_title[[463, 674, 533, 692]]
## BONUS  

text[[115, 708, 830, 745]]
18) Earth and Space – Multiple Choice Which of the following is not a form of primary porosity?  

text[[115, 762, 432, 834]]
W) Vesicles 
X) Miarolitic cavities 
Y) Fault breccia cavities 
Z) Pore space between sandstone grains  

text[[115, 850, 483, 868]]
ANSWER: Y) FAULT BRECCIA CAVITIESsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 126, 872, 180]]
19) Physics – Short Answer Which of the following is closest to the electric potential in volts at the center of a loop with radius 28 centimeters and linear charge density 4 coulombs per meter?  

text[[115, 196, 226, 270]]
W) \(2.3\mathrm{x}10^{10}\) X) \(2.3\mathrm{x}10^{11}\) Y) \(2.3\mathrm{x}10^{12}\) Z) \(2.3\mathrm{x}10^{13}\)  

text[[115, 284, 313, 303]]
ANSWER: X) \(2.3\mathrm{x}10^{11}\)  

sub_title[[463, 320, 533, 338]]
## BONUS  

text[[115, 354, 872, 390]]
19) Physics – Short Answer What is the horizontal range of a projectile fired from the ground at 14 meters per second at a 15 degree angle to the horizontal?  

text[[115, 406, 313, 423]]
ANSWER: 10 METERS  

sub_title[[456, 477, 541, 495]]
## TOSS-UP  

text[[115, 514, 868, 567]]
20) Energy – Short Answer Scientists at SLAC National Accelerator Lab are using the Linac Coherent Light Source to study buckminsterfullerenes. Buckminsterfullerenes are made of carbon rings of what two sizes?  

text[[115, 584, 283, 601]]
ANSWER: 5 AND 6  

sub_title[[463, 619, 533, 637]]
## BONUS  

text[[115, 654, 857, 725]]
20) Energy – Short Answer Scientists at Lawrence Berkeley National Lab are investigating ferromagnetism in graphene. Identify all of the following three other properties exhibited by graphene: 1) Excellent electrical conductivity; 2) Excellent thermal conductivity; 3) \(\mathrm{sp}^2\) hybridized carbon atoms.  

text[[115, 741, 248, 758]]
ANSWER: ALLsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[113, 125, 866, 163]]
21) Biology – Short Answer How many Barr bodies will form in a cell of an individual with Klinefelter syndrome?  

text[[115, 180, 220, 198]]
ANSWER: 1  

sub_title[[463, 214, 534, 233]]
## BONUS  

text[[113, 249, 881, 286]]
21) Biology – Multiple Choice At which of the following environmental pH levels will pepsin exhibit maximum activity?  

text[[115, 302, 173, 372]]
W) 1.0 
X) 2.0 
Y) 3.0 
Z) 4.0  

text[[115, 389, 261, 407]]
ANSWER: X) 2.0  

sub_title[[456, 460, 541, 479]]
## TOSS-UP  

text[[115, 494, 840, 532]]
22) Math – Short Answer Identify all of the following three quadrilaterals that must have perpendicular diagonals: 1) Rhombus, 2) Rectangle, 3) Kite.  

text[[115, 547, 283, 565]]
ANSWER: 1 AND 3  

sub_title[[463, 583, 534, 601]]
## BONUS  

text[[115, 617, 857, 654]]
22) Math – Short Answer What is the \(y\) - intercept of the line that is perpendicular to the line \(-6x + 3y = 18\) and passes through the point (4, 9)?  

text[[115, 669, 393, 688]]
ANSWER: (0, 11) (ACCEPT: 11)sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[113, 125, 836, 163]]
23) Chemistry – Multiple Choice Van der Waals forces include all intermolecular forces whose energy is proportional to distance between molecules to what power?  

text[[114, 180, 166, 250]]
W)- 1 X)- 2 Y)- 3 Z)- 6  

text[[115, 268, 255, 285]]
ANSWER: Z)- 6  

sub_title[[463, 303, 533, 320]]
## BONUS  

text[[113, 337, 752, 356]]
23) Chemistry – Short Answer How many radial nodes are in the 4d subshell?  

text[[115, 373, 220, 390]]
ANSWER: 1