
## TOSS-UP  


1) Biology – Short Answer Identify all of the following three characteristics that are found in both charophytes and land plants: 1) Formation of phragmoplast [frag-MOE-plast]; 2) Rosette-shaped cellulose synthesizing enzymes; 3) Flagellated sperm.  


ANSWER: ALL  


## BONUS  


1) Biology – Short Answer Identify all of the following three diseases that are sex linked: 1) Cystic fibrosis; 2) Mononucleosis; 3) AIDS.  


ANSWER: NONE  


## TOSS-UP  


2) Energy – Multiple Choice Researchers at Brookhaven National Lab are studying iron-nickel meteorites and their role in solar system formation. Which of the following statements regarding the origin of iron-nickel meteorites is true?  


W) They are usually formed from surficial impacts on large planetesimals 
X) They originate from ejected material in young protostars 
Y) They originate from the cores of differentiated planetesimals 
Z) They originate from the differentiation of chondrites  


ANSWER: Y) THEY ORIGINATE FROM THE CORES OF DIFFERENTIATED PLANETESIMALS  


## BONUS  


2) Energy – Short Answer Scientists at Lawrence Berkeley National Lab have been studying predisposition to cancer. They found that the largest genetic contributor was the inheritance of one malfunctioning tumor suppressor allele. Identify all of the following three genes that are tumor suppressor genes: 1) p53; 2) Ras; 3) BRCA1.  


ANSWER: 1 AND 3
## TOSS-UP  


3) Math - Short Answer What is the limit as \(x\) approaches infinity of the fraction with numerator \(7x^{2} + 4x\) and denominator \(4x^{2} + 10x + 11\) ?  


ANSWER: 7/4  


## BONUS  


3) Math - Short Answer Albert pays Bill 10 dollars, and each of them guesses an integer between 1 and 100, inclusive. If the units digits of Albert's and Bill's numbers match, then Bill returns 5 dollars to Albert; if Albert's and Bill's numbers are identical, Bill pays Albert \(x\) more dollars. Given that the expected value of playing this game is 0, what is \(x\) ?  


ANSWER: 950  


## TOSS-UP  


4) Physics - Multiple Choice What instrument did Michelson and Morley use to disprove the existence of the luminiferous ether?  


W) Laser  X) Torsion balance  Y) Interferometer  Z) Cyclotron  


ANSWER: Y) INTERFEROMETER  


## BONUS  


4) Physics - Short Answer Identify all of the following three statements that are true regarding bodies under stress: 1) They become permanently deformed past their yield strength; 2) They can return to their original form past their ultimate strength; 3) The stress-strain curve is quadratic in the elastic range.  


ANSWER: 1 ONLY
## TOSS-UP  


5) Earth and Space – Multiple Choice Which of the following spectral classes of stars experiences the strongest ionized calcium lines?  


W) O 
X) A 
Y) G 
Z) M  


ANSWER: Y) G  


## BONUS  


5) Earth and Space – Multiple Choice In which of the following petrogenic environments would hornfels-facies [FAE-ships] metamorphism most likely be expected?  


W) Subduction zone 
X) Continent-continent convergence 
Y) Mid-ocean ridge 
Z) Pluton aureole [OH-ree-ole]  


ANSWER: Z) PLUTON AUREOLE  


## TOSS-UP  


6) Chemistry – Multiple Choice Which of the following gases has a compression factor greater than 1 for all pressures at 300 kelvins?  


W) Methane 
X) Ammonia 
Y) Dimethyl ether 
Z) Hydrogen  


ANSWER: Z) HYDROGEN  


## BONUS  


6) Chemistry – Short Answer In the Lennard-Jones potential, the \(r^6\) term is used to approximate the potential energy of what specific class of intermolecular interactions?  


ANSWER: VAN DER WAALS FORCES (ACCEPT: DISPERSION FORCES)
## TOSS-UP  


7) Physics - Short Answer A passenger is standing on a scale in an elevator. As the elevator accelerates upwards, the scale reads 830 newtons. The elevator then begins to accelerate downwards at the same magnitude, with the scale now reading 650 newtons. In newtons, what is the weight of the passenger?  


ANSWER: 740  


## BONUS  


7) Physics - Short Answer A 12-volt battery has a 3-ohm internal resistance. What is the maximum power, in watts, that it can deliver to a light bulb connected in series?  


ANSWER: 12  


## TOSS-UP  


8) Biology - Short Answer Vernalization is a treatment to many plants used to promote which response?  


ANSWER: FLOWERING  


## BONUS  


8) Biology - Short Answer During apoptosis, the release of which iron coordinating protein in the mitochondria is responsible for the activation of caspase enzymes?  


ANSWER: CYTOCHROME C
## TOSS-UP  


9) Earth and Space – Short Answer Sulfuric acid in the Earth's atmosphere is formed from the hydration of what specific secondary air pollutant?  


ANSWER: SULFUR TRIOXIDE (ACCEPT: \(\mathrm{SO}_3\) )  


## BONUS  


9) Earth and Space – Short Answer The innermost stable circular orbit, or ISCO, is often applied to black holes and as a test of general relativity. The ISCO is equal to what multiple of the Schwarzschild radius?  


ANSWER: 3  


## TOSS-UP  


10) Chemistry – Short Answer The partial combustion of methane produces carbon monoxide, which then reacts with diatomic oxygen to form carbon dioxide. If the enthalpy change of each of these reactions is known, what law can be used to calculate the enthalpy of complete combustion for methane?  


ANSWER: HESS'S LAW  


## BONUS  


10) Chemistry – Multiple Choice Two rigid containers are filled at room temperature, one with 1 mole of monatomic ideal gas, and another with 1 mole of diatomic ideal gas. When 100 kilojoules of heat are supplied to each container, the final temperature is higher in one of the containers. Which of the following is a reason for this effect?  


W) The monatomic gas has more vibrational modes 
X) The diatomic gas has more vibrational modes 
Y) The monatomic gas has more rotational modes 
Z) The diatomic gas has more rotational modes  


ANSWER: Z) THE DIATOMIC GAS HAS MORE ROTATIONAL MODES
## TOSS-UP  


11) Math - Short Answer Points A and B lie on a circle centered at O, and the tangents to the circle at A and B intersect at C. If \(\mathrm{OA} = \mathrm{AC}\) , what is angle AOB in degrees?  


ANSWER: 90  


## BONUS  


11) Math - Short Answer If \(f(x) = x^{3} - 3x^{2} + 3x - 9\) , what is the derivative of the inverse of \(f\) at \(x = 0\) ?  


ANSWER: 1/12  


## TOSS-UP  


12) Energy - Short Answer Scientists at Ames Lab have been studying the novel properties of high-temperature superconductors. In low-temperature superconductors, what process is responsible for the expulsion of a magnetic field as a material transitions into a superconducting state?  


ANSWER: MEISSNER EFFECT  


## BONUS  


12) Energy - Short Answer Scientists at Pacific Northwest National Lab have been studying the gradients of different greenhouse gases in tree stems of the Pacific Northwest. They found that the different gradients mostly depended on the tree physiology and its bark structure. In trees, lenticels are analogous to what oxygen exchanging structure in herbaceous plants?  


ANSWER: STOMATA (ACCEPT: STOMA)
## TOSS-UP  


13) Math - Short Answer If \(f(x) = 1\) over the quantity \(1 - x\) , what is \(f\) of \(f\) of \(f\) of 2020?  


ANSWER: 2020  


## BONUS  


13) Math - Short Answer There are five distinct marbles in a bag. Every second, Alice draws a random marble and puts it back, stopping when she has drawn all five marbles at least once. What is the probability that she stops after exactly 5 seconds?  


ANSWER: 24/625  


## TOSS-UP  


14) Biology - Short Answer What neuropeptide functions as a neurotransmitter and neuromodulator by being implicated in the transmission of pain and inflammation?  


ANSWER: SUBSTANCE P  


## BONUS  


14) Biology - Short Answer Rank the following three amino acids in terms of increasing migration speed in SDS-PAGE; 1) Alanine; 2) Glycine; 3) Tryptophan.  


ANSWER: 3, 1, 2
## TOSS-UP  


15) Earth and Space – Multiple Choice Lithium fusion is often useful for identifying which of the following substellar structures?  


W) Black dwarf 
X) White dwarf 
Y) Brown dwarf 
Z) Exoplanet  


ANSWER: Y) BROWN DWARF  


## BONUS  


15) Earth and Space – Multiple Choice Internal waves in the ocean propagate along a distinct density boundary that separates two layers. Most internal waves are observed in what marine environment?  


W) Near the bottom of the seafloor in abyssal regions 
X) Near river mouths on the continental shelf 
Y) On the continental slope 
Z) Within polar pycnoclines  


ANSWER: X) NEAR RIVER MOUTHS ON THE CONTINENTAL SHELF  


## TOSS-UP  


16) Physics – Multiple Choice The position of a particle along the \(x\) -axis is described by the function \(x(t) = 3t^3 - 6t^2 + 18t + 14\). Which of the following accurately describes the particle's motion at time \(t = 2\) ?  


W) Moving to the left and speeding up 
X) Moving to the right and speeding up 
Y) Moving to the left and slowing down 
Z) Moving to the right and slowing down  


ANSWER: X) MOVING TO THE RIGHT AND SPEEDING UP  


## BONUS  


16) Physics – Short Answer In the rocket equation, the fuel consumption rate multiplied by the fuel exhaust speed represents what quantity?  


ANSWER: THRUST
## TOSS-UP  


17) Chemistry – Short Answer Identify all of the following three particles that can be used to conduct diffraction studies on chemical samples: 1) Photons; 2) Electrons; 3) Neutrons.  


ANSWER: ALL  


## BONUS  


17) Chemistry – Multiple Choice Which of the following is closest to the bond angle in degrees found in hydrogen sulfide?  


W) 90 X) 107 Y) 120 Z) 180  


ANSWER: W) 90  


## TOSS-UP  


18) Earth and Space – Short Answer How many Lagrange points are there within a standard two-body system?  


ANSWER: 5  


## BONUS  


18) Earth and Space – Multiple Choice Cross-bedded sandstones with individual beds several meters in height are best indicative of which of the following depositional environments?  


W) Desert dunes 
X) Deep sea basin 
Y) Tidal flat 
Z) Alpine glacier  


ANSWER: W) DESERT DUNES
## TOSS-UP  


19) Energy - Short Answer Scientists at Lawrence Berkeley National Lab are using ferroelectric ceramic materials with engineered crystal defects to create a "super" version of what energy-storing circuit component?  


ANSWER: CAPACITOR  


## BONUS  


19) Energy - Short Answer In order to determine the grain structure of ceramic microcrystals, scientists at Idaho National Lab are generating internal sound waves and using laser pulses to measure the frequencies of the acoustic phonons that result. How many distinct phonon frequencies must they measure in order to ascertain the general grain structure?  


ANSWER: THREE  


## TOSS-UP  


20) Physics - Short Answer Identify all of the following three quantities that remain constant for a system in static equilibrium: 1) Force; 2) Torque; 3) Linear momentum.  


ANSWER: ALL  


## BONUS  


20) Physics - Short Answer What technique can be used to slow and trap atoms at low temperatures by using a light source tuned to a frequency just below an electronic transition to selectively target atoms moving toward the light beam?  


ANSWER: DOPPLER COOLING (ACCEPT: LASER COOLING)
## TOSS-UP  


21) Math - Multiple Choice What is the domain of the function \(y =\) the square root of the quantity \(4 - x\) times the square root of the quantity \(4 + x\) ?  


W) \(x\) is greater than \(-4\) and less than 4 
X) \(x\) is greater than \(-4\) and less than or equal to 4 
Y) \(x\) is greater than or equal to \(-4\) and less than 4 
Z) \(x\) is greater than or equal to \(-4\) and less than or equal to 4  


ANSWER: Z) \(x\) IS GREATER THAN OR EQUAL TO \(-4\) AND LESS THAN OR EQUAL TO 4  


## BONUS  


21) Math - Short Answer The Spiral of Theodorus is a spiral of right triangles made by starting with a right triangle with both legs equal to 1, and making each successive triangle have one leg equal to 1 and the previous triangle's hypotenuse as the other leg. What is the ratio of the areas of the tenth triangle and the first triangle?  


ANSWER: ROOT 10  


## TOSSUP  


22) Chemistry - Short Answer Photoelectron spectroscopy is a laboratory method used to determine orbital energies. In this technique, high-energy light is directed towards samples, causing electrons to be ejected. Identify all of the following quantities that must be known to calculate the orbital energies: 1) Kinetic energy of ejected electrons; 2) Frequency of light; 3) Intensity of light.  


ANSWER: 1 AND 2  


## BONUS  


22) Chemistry - Short Answer Rank the following three compounds in terms of increasing boiling point; 1) Benzene; 2) 1,4- dibromobenzene; 3) 1,2- dibromobenzene.  


ANSWER: 1, 2, 3
## TOSS-UP  


23) Biology - Short Answer Alex receives a critical injury to his substantia nigra and thus experiences a lack of dopamine release to the basal nuclei. He will likely exhibit symptoms of what neurologic disease?  


ANSWER: PARKINSON'S DISEASE  


## BONUS  


23) Biology - Short Answer In the Heuring-Bruer [her-ing-BREW-er] reflex, pulmonary stretch receptors within the bronchioles send inputs inhibiting the apneustic [ap-NEW-stick] center, which is present in which portion of the brainstem?  


ANSWER: PONS