sub_title[[456, 143, 541, 161]]
## TOSS-UP  

text[[115, 178, 872, 214]]
1) Math – Short Answer An acute triangle ABC is inscribed in a circle with center at point O. If angle ABC is 40 degrees, what is angle AOC?  

text[[115, 230, 231, 248]]
ANSWER: 80  

sub_title[[462, 265, 533, 283]]
## BONUS  

text[[115, 300, 868, 336]]
1) Math – Short Answer What is the minimum value of \(2^{n}\) mod 2020 for any positive integer \(n\) ?  

text[[115, 353, 220, 370]]
ANSWER: 2  

sub_title[[456, 421, 541, 440]]
## TOSS-UP  

text[[115, 456, 850, 492]]
2) Earth and Space – Short Answer In a mid-latitude cyclone, what type of front is formed when the cold front overtakes a warm front?  

text[[115, 508, 387, 527]]
ANSWER: OCCLUDED FRONT  

sub_title[[462, 544, 533, 562]]
## BONUS  

text[[115, 579, 881, 615]]
2) Earth and Space – Multiple Choice Which of the following compounds likely composes the upper atmospheric clouds on Jupiter?  

text[[115, 632, 281, 701]]
W) Methane X) Dimethyl sulfide Y) Hydrogen sulfide Z) Ammonia  

text[[115, 718, 332, 736]]
ANSWER: Z) AMMONIAsub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 879, 181]]
3) Physics – Short Answer Real objects do not radiate as much thermal energy as predicted by the Stefan–Boltzmann law. What quantity is equal to the ratio of an object’s measured thermal radiation to its ideal thermal radiation?  

text[[116, 198, 321, 215]]
ANSWER: EMISSIVITY  

sub_title[[462, 232, 533, 250]]
## BONUS  

text[[115, 267, 864, 320]]
3) Physics – Short Answer Electrons can possess magnetic moments due to their spin and orbital angular momentum. What relativistic phenomenon is a result of the interaction between these two?  

text[[115, 336, 783, 355]]
ANSWER: SPIN- ORBIT COUPLING (ACCEPT: SPIN- ORBIT INTERACTION)  

sub_title[[456, 407, 540, 425]]
## TOSS-UP  

text[[115, 442, 880, 478]]
4) Biology – Short Answer Rank the following three ions in terms of decreasing concentration in the intracellular fluid of a resting neuron: 1) \(\mathrm{Na^{+}}\) ; 2) \(\mathrm{Cl^{-}}\) ; 3) \(\mathrm{K^{+}}\) .  

text[[115, 494, 260, 511]]
ANSWER: 3, 1, 2  

sub_title[[462, 528, 533, 546]]
## BONUS  

text[[115, 563, 875, 599]]
4) Biology – Short Answer Identify all of the following three types of plant ground tissue that possess secondary cell walls: 1) Parenchyma; 2) Collenchyma; 3) Sclerenchyma.  

text[[115, 615, 282, 633]]
ANSWER: 2 AND 3sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[114, 127, 844, 163]]
5) Chemistry – Short Answer How many normal vibrational modes does one molecule of acetylene have?  

text[[115, 180, 220, 198]]
ANSWER: 7  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 250, 865, 304]]
5) Chemistry – Short Answer Identify all of the following three carbon dioxide vibrational modes that are considered to be Raman active: 1) Asymmetric C–O stretch; 2) Symmetric C–O stretch; 3) Symmetrical bend in plane.  

text[[115, 320, 279, 338]]
ANSWER: 2 ONLY  

sub_title[[456, 389, 541, 407]]
## TOSS-UP  

text[[115, 424, 879, 478]]
6) Energy – Short Answer Scientists at Argonne National Lab are working on new solvent extraction methods that employ magnetic fields to act on paramagnetic metal ions. Identify all of the following three metal ions that are paramagnetic: 1) Na<sup>+</sup>; 2) Cr<sup>3+</sup>; 3) Zn<sup>2+</sup>.  

text[[115, 493, 279, 511]]
ANSWER: 2 ONLY  

sub_title[[463, 528, 533, 546]]
## BONUS  

text[[115, 563, 870, 616]]
6) Energy – Short Answer Researchers at Fermilab are conducting particle physics experiments in order to ascertain information about the early universe. One of their experiments focuses on the conversion of what particles to electrons without the emission of neutrinos?  

text[[115, 633, 281, 650]]
ANSWER: MUONSsub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 734, 146]]
7) Biology - Short Answer Insects secrete what form of nitrogenous waste?  

text[[115, 162, 310, 180]]
ANSWER: URIC ACID  

sub_title[[463, 200, 533, 218]]
## BONUS  

text[[115, 236, 872, 273]]
7) Biology - Short Answer During inflammation, which class of leukocytes may migrate into the blood to become mast cells and release histamine?  

text[[115, 289, 317, 307]]
ANSWER: BASOPHILS  

sub_title[[456, 361, 540, 379]]
## TOSS-UP  

text[[115, 398, 846, 435]]
8) Earth and Space - Short Answer Solid contours on a high level isobaric chart represent what quantity?  

text[[115, 450, 611, 469]]
ANSWER: ELEVATION (ACCEPT: HEIGHT; ALTITUDE)  

sub_title[[463, 485, 533, 503]]
## BONUS  

text[[115, 521, 870, 558]]
8) Earth and Space - Multiple Choice Which of the following most closely approximates the time of the last geomagnetic reversal, in years?  

text[[115, 574, 220, 644]]
W) 1,000  X) 10,000  Y) 100,000  Z) 1,000,000  

text[[115, 660, 313, 678]]
ANSWER: Z) 1,000,000sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[113, 127, 830, 165]]
9) Chemistry – Multiple Choice Which of the following compounds is the least suitable nucleophile for an SN2 reaction?  

text[[114, 184, 291, 260]]
W) Ethanol  X) Methylamine  Y) Sodium iodide  Z) Sodium methoxide  

text[[115, 279, 333, 297]]
ANSWER: W) ETHANOL  

sub_title[[462, 316, 533, 334]]
## BONUS  

text[[113, 353, 805, 391]]
9) Chemistry – Short Answer Rank the following three liquids in terms of increasing viscosity: 1) Mercury; 2) Water; 3) Diethyl ether.  

text[[115, 406, 258, 424]]
ANSWER: 3, 2, 1  

sub_title[[456, 480, 540, 497]]
## TOSS-UP  

text[[115, 516, 857, 570]]
10) Math – Short Answer Identify all of the following three classes of functions that have a finite Taylor series expansion: 1) Polynomials, 2) Rational functions, 3) Hyperbolic trig functions.  

text[[115, 586, 279, 604]]
ANSWER: 1 ONLY  

sub_title[[462, 622, 533, 640]]
## BONUS  

text[[115, 660, 848, 697]]
10) Math – Short Answer How many positive three-digit integers have a bigger units digit than tens digit?  

text[[115, 716, 240, 734]]
ANSWER: 405sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 875, 184]]
11) Energy – Short Answer Scientists at Lawrence Berkeley National Lab have been developing methods for performing artificial photosynthesis. In these methods, titanium dioxide is used for the water-splitting reaction that is traditionally catalyzed by what enzyme in plants?  

text[[115, 201, 881, 225]]
ANSWER: OXYGEN- EVOLVING (ACCEPT: WATER- SPLITTING COMPLEX)  

sub_title[[463, 241, 533, 259]]
## BONUS  

text[[115, 277, 877, 353]]
11) Energy – Short Answer Researchers at Lawrence Livermore National Lab are using short laser pulses to remove atoms from the surface of metals. Lasers are generated by shooting photons at excited electrons, causing them to relax to their ground state. What is the term for this process?  

text[[115, 371, 434, 390]]
ANSWER: STIMULATED EMISSION  

sub_title[[456, 446, 541, 464]]
## TOSS-UP  

text[[115, 483, 763, 520]]
12) Physics – Multiple Choice Most jet engines employ which of the following thermodynamic cycles?  

text[[115, 536, 250, 606]]
W) Carnot cycle 
X) Stirling cycle 
Y) Otto cycle 
Z) Brayton cycle  

text[[115, 622, 399, 640]]
ANSWER: Z) BRAYTON CYCLE  

sub_title[[463, 658, 533, 677]]
## BONUS  

text[[115, 695, 863, 771]]
12) Physics – Short Answer Identify all of the following three statements that are true regarding electric field lines: 1) Induced electric field lines form closed loops; 2) Equipotential lines are always parallel to electric field lines; 3) More closely-spaced electric field lines correspond to stronger electric fields.  

text[[115, 790, 283, 808]]
ANSWER: 1 AND 3sub_title[[455, 91, 540, 108]]
## TOSS-UP  

text[[113, 127, 852, 165]]
13) Chemistry – Multiple Choice How many net pi bonds are formed during a sigmatropic rearrangement?  

text[[113, 184, 166, 260]]
W)- 1 X) 0 Y) 1 Z) 2  

text[[115, 279, 247, 297]]
ANSWER: X) 0  

sub_title[[462, 316, 533, 334]]
## BONUS  

text[[113, 353, 860, 391]]
13) Chemistry – Multiple Choice When \(\mathrm{H}_{2}\) forms a side-on complex with a tungsten center, which of the following is most likely to occur?  

text[[113, 409, 856, 445]]
W) The H-H bond strength decreases because tungsten donates electrons into the H-H sigma star orbital  

text[[113, 447, 850, 483]]
X) The H-H bond strength increases because tungsten donates electrons into the H-H sigma orbital  

text[[113, 484, 852, 520]]
Y) The H-H bond strength decreases because tungsten donates electrons into the H-H pi star orbital  

text[[113, 522, 866, 541]]
Z) The H-H bond strength increases because tungsten donates electrons into the H-H pi orbital  

text[[113, 559, 810, 596]]
ANSWER: W) THE H-H BOND STRENGTH DECREASES BECAUSE TUNGSTEN DONATES ELECTRONS INTO THE H-H SIGMA STAR ORBITAL  

sub_title[[455, 653, 540, 671]]
## TOSS-UP  

text[[113, 690, 875, 727]]
14) Biology – Short Answer Identify all of the following three organelles that are enclosed by a double membrane: 1) Nucleus; 2) Glyoxysome; 3) Chloroplast.  

text[[115, 743, 282, 760]]
ANSWER: 1 AND 3  

sub_title[[462, 780, 533, 797]]
## BONUS  

text[[115, 817, 825, 852]]
14) Biology – Short Answer What enzyme in red blood cells is responsible for the rapid conversion of water and carbon dioxide into carbonic acid?  

text[[115, 870, 438, 887]]
ANSWER: CARBONIC ANHYDRASEsub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[115, 127, 818, 164]]
15) Math – Multiple Choice A group on the integers mod 256 is abelian. Which of the following operations could NOT be the operation associated with this group?  

text[[115, 180, 300, 251]]
W) Addition 
X) Subtraction 
Y) Multiplication 
Z) Binary XOR [ex or]  

text[[115, 268, 373, 285]]
ANSWER: X) SUBTRACTION  

sub_title[[462, 303, 533, 320]]
## BONUS  

text[[115, 339, 874, 392]]
15) Math – Short Answer A right trapezoid ABCD has bases AB and CD, and angles ABC and BCD are each 90 degrees. Side BC has length 16, side DA has length 20, and the area of the trapezoid is 400. What is the length of the longer base?  

text[[115, 409, 228, 426]]
ANSWER: 31  

sub_title[[456, 480, 540, 497]]
## TOSS-UP  

text[[115, 514, 789, 533]]
16) Earth and Space – Multiple Choice What is the largest tectonic plate on Earth?  

text[[115, 550, 315, 618]]
W) Eurasian plate 
X) North American plate 
Y) Pacific plate 
Z) Indo-Australian plate  

text[[115, 635, 377, 653]]
ANSWER: Y) PACIFIC PLATE  

sub_title[[462, 670, 533, 688]]
## BONUS  

text[[115, 705, 874, 741]]
16) Earth and Space – Multiple Choice Which of the following stellar spectral classes is most likely associated with an emission nebula?  

text[[115, 758, 163, 826]]
W) K 
X) M 
Y) G 
Z) O  

text[[115, 844, 248, 862]]
ANSWER: Z) Osub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 864, 199]]
17) Energy – Multiple Choice Scientists at Brookhaven National Lab are using cryoelectron microscopy to characterize the activated CAS9 guide RNA complex in E. coli. E. coli guide RNA is likely to exhibit sequence specificity for nucleic acids in which of the following organisms?  

text[[115, 216, 330, 286]]
W) Treponema pallidum  X) T4  Y) Plasmodium falciparum  Z) HIV  

text[[115, 302, 259, 320]]
ANSWER: X) T4  

sub_title[[463, 337, 533, 355]]
## BONUS  

text[[115, 374, 875, 428]]
17) Energy – Short Answer Researchers at Argonne National Lab have been looking for cost-effective ways to enrich molybdenum isotopes. They have developed a method that used parts such as acrylic contractors, which were produced by what technique?  

text[[115, 444, 331, 461]]
ANSWER: 3D PRINTING  

sub_title[[456, 514, 540, 532]]
## TOSS-UP  

text[[115, 548, 830, 585]]
18) Physics – Short Answer Curie’s law states that the magnetization of a paramagnetic sample is directly proportional to what quantity?  

text[[115, 600, 840, 636]]
ANSWER: EXTERNAL MAGNETIC FIELD (ACCEPT: APPLIED MAGNETIC FIELD; MAGNETIC FIELD)  

sub_title[[463, 653, 533, 670]]
## BONUS  

text[[115, 688, 852, 723]]
18) Physics – Short Answer What is the name for devices containing one p–n junction that convert light into electrical current?  

text[[115, 740, 337, 757]]
ANSWER: PHOTODIODEsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[114, 127, 861, 163]]
19) Math - Multiple Choice Which of the following functions best approximates the prime-counting function of \(x\) ?  

text[[114, 180, 592, 251]]
W) \(x\) over the natural log of \(x\) X) \(x\) over the natural log of the quantity \(x^{2}\) Y) \(x\) over the square root the natural log of \(x\) Z) \(x\) over the square root of the natural log of the quantity \(x^{2}\)  

text[[114, 267, 538, 286]]
ANSWER: W) \(x\) OVER THE NATURAL LOG OF \(x\)  

sub_title[[462, 302, 535, 320]]
## BONUS  

text[[114, 339, 835, 375]]
19) Math - Short Answer What is the indefinite integral of the tangent squared of \(x\) with respect to \(x\) ?  

text[[115, 392, 320, 410]]
ANSWER: \(\tan (x) - x + C\)  

sub_title[[456, 461, 541, 480]]
## TOSS-UP  

text[[114, 496, 852, 533]]
20) Earth and Space - Short Answer Identify all of the following three solar system bodies that are known to have permanent polar ice caps: 1) Mars; 2) The Earth's moon; 3) Venus.  

text[[115, 549, 280, 567]]
ANSWER: 1 ONLY  

sub_title[[462, 584, 535, 602]]
## BONUS  

text[[114, 618, 853, 673]]
20) Earth and Space - Short Answer Identify all of the following three features that would usually be associated with an extensional tectonic regime: 1) Graben and horst topography; 2) Normal faulting; 3) Low angle thrust faulting.  

text[[115, 689, 283, 707]]
ANSWER: 1 AND 2sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[114, 127, 835, 163]]
21) Chemistry – Short Answer Esters can be hydrolyzed under acidic conditions to form carboxylic acids and what other functional group?  

text[[115, 180, 304, 198]]
ANSWER: ALCOHOL  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 252, 825, 289]]
21) Chemistry – Multiple Choice For which of the following gas-phase reactions is the change in enthalpy the same as the change in internal energy?  

text[[115, 305, 576, 323]]
W) Dissociation of water vapor to form hydrogen and oxygen gas  

text[[115, 323, 580, 340]]
X) Formation of ammonia from hydrogen and nitrogen gas  

text[[115, 341, 460, 357]]
Y) Hydrogenation of ethene to form ethane  

text[[115, 358, 825, 376]]
Z) Formation of carbon dioxide and hydrogen gas from water vapor and carbon monoxide  

text[[115, 391, 822, 427]]
ANSWER: Z) FORMATION OF CARBON DIOXIDE AND HYDROGEN GAS FROM WATER VAPOR AND CARBON MONOXIDE  

sub_title[[456, 496, 540, 514]]
## TOSS-UP  

text[[115, 531, 857, 567]]
22) Biology – Short Answer PYY is a hormone that suppresses the action of what hormone released by the walls of the stomach to increase hunger?  

text[[115, 584, 297, 601]]
ANSWER: GHRELIN  

sub_title[[463, 619, 533, 637]]
## BONUS  

text[[115, 654, 855, 691]]
22) Biology – Short Answer What two monomers collectively compose the polysaccharide peptidoglycan?  

text[[115, 707, 750, 743]]
ANSWER: N- ACETYLMUAMIC ACID AND N- ACETYLGLUCOSAMINE (ACCEPT: NAM AND NAG)sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[114, 127, 872, 181]]
23) Physics – Short Answer Suppose a charged particle moves with an initial velocity neither parallel nor perpendicular to a uniform magnetic field. What type of curve will be traced out by its resultant motion?  

text[[115, 198, 293, 215]]
ANSWER: HELICAL  

sub_title[[462, 233, 533, 251]]
## BONUS  

text[[115, 268, 841, 339]]
23) Physics – Short Answer Identify all of the following three statements that are true regarding statistical mechanics: 1) All microstates have equal probability of being occupied: 2) Entropy is proportional to the natural log of the number of microstates; 3) Canonical ensembles have a fixed number of particles.  

text[[115, 356, 248, 373]]
ANSWER: ALL