
# Competitive Division Double Elimination 2  


## TOSS-UP  


1) BIOLOGY Short Answer What enzyme generates the hydrogen ions secreted by parietal cells in gastric pits, producing bicarbonate as a waste product?  


ANSWER: CARBONIC ANHYDRASE  


## BONUS  


1) BIOLOGY Multiple Choice In which of the following locations would you find the cell bodies of lower motor neurons?  


W) Dorsal root ganglia 
X) Ventral root ganglia 
Y) Dorsal horn 
Z) Ventral horn  


ANSWER: Z) VENTRAL HORN  


## TOSS-UP  


2) CHEMISTRY Multiple Choice How many unpaired electrons would be found in the high-spin and low-spin complexes of an octahedral \(\mathrm{Co}^{2 + }\) ion, respectively?  


W) 2, 0 
X) 2, 1 
Y) 3, 0 
Z) 3, 1  


ANSWER: Z) 3, 1  


DASONI 2022
## BONUS  


2) CHEMISTRY Multiple Choice Which of the following describes positive hyperconjugation?  


W) Sigma orbital donates into pi star orbital  


X) Sigma star orbital donates into pi orbital  


Y) Pi star orbital donates into sigma orbital  


Z) Pi orbital donates into sigma star orbital  


ANSWER: W) SIGMA ORBITAL DONATES INTO PI STAR ORBITAL  


## TOSS-UP  


3) EARTH AND SPACE Multiple Choice Which of the following would indicate the presence of a  


P Cygni profile?  


W) Broad forbidden lines  


X) Both broad and narrow allowed lines  


Y) A highly blueshifted spectrum  


Z) Absorption and emission of the same spectral line  


ANSWER: Z) ABSORPTION AND EMISSION OF THE SAME SPECTRAL LINE  


## BONUS  


3) EARTH AND SPACE Short Answer By name or number, identify all of the following four values that increase as a wave approaches the shore:  


1) Height  


2) Speed  


3) Wavelength  


4) Wave Steepness  


ANSWER: 1 AND 4 (ACCEPT: HEIGHT AND WAVE STEEPNESS)  


## TOSS-UP
4) MATH Multiple Choice Which of the following numbers of distinct real roots can a cubic equation not have?  


W) 0 
X) 1 
Y) 2 
Z) 3  


ANSWER: W) 0  


## BONUS  


4) MATH Short Answer What is the slope of \(y^{2} + 2y + x = 4\) at the point \((1,1)\) ?  


Answer: - 1/5  


## TOSS-UP  


5) PHYSICS Short Answer Rotational and spatial translational invariance is related by Noether's theorem to what type of physical quantity?  


ANSWER: MOMENTUM  


## BONUS  


5) PHYSICS Short Answer A mass is attached to a S spring and oscillates with a period T. 4 S springs are assembled into a complex spring. Three springs are glued parallel to each other and then the third spring is glued in series to this group. If the same mass is attached to this spring and allowed to oscillate, what is the period of this oscillator in terms of T?  


ANSWER: sqrt(3)/2 T  


## TOSS-UP  


6) ENERGY Short Answer Davidson HS A team members are studying actually useful methods of synthetic organic chemistry. One such method involves the late-stage modification of alkyl chains in natural product or drug-like molecules after, and not before, construction of the carbon
backbone, greatly simplifying total or semi synthesis. This modification is often carried out through stereoselective organometallic or bio- catalysts. What is this strategy called?  


ANSWER: C- H FUNCTIONALIZATION  


## BONUS  


6) ENERGY Short Answer Davidson MS B team members are studying abnormal magnetic moments in particles like the muon. What constant is a sort of "proportionality constant" for the magnetic moment and has a namesake experiment at Fermilab?  


ANSWER: g- factor  


## TOSS-UP  


7) BIOLOGY Short Answer There is an energy barrier limiting exocytosis of neurotransmitters filled vesicles in neurons due to electrostatic repulsion of charged phospholipid head groups. To overcome this energy barrier, what group of proteins assembles into a complex, functioning as a tether to pull the vesicle and plasma membranes together?  


ANSWER: SNARE PROTEINS  


## BONUS  


7) BIOLOGY Short Answer Yajur is a lab researcher studying endocytosis. He puts cells in a medium containing fluorescently labeled proteins and then examines the cells using fluorescence microscopy. After being endocytosed, what is the first organelle Yajur would see the fluorescent proteins in?  


ANSWER: ENDOSOME (ACCEPT: EARLY ENDOSOME; DO NOT ACCEPT: LYSOSOME)  


## TOSS-UP  


8) CHEMISTRY Short Answer Identify all of the following four molecules that are infrared active:  


1) Carbon dioxide  
2) Diatomic nitrogen  
3) Nitric oxide
4) Ethene  


ANSWER: 1, 3, AND 4 (ACCEPT: CARBON DIOXIDE, NITRIC OXIDE, ETHENE)  


## BONUS  


8) CHEMISTRY Multiple Choice While London dispersion forces arise due to fleeting dipole moments, what intermolecular force arises due to permanent dipoles inducing a dipole on a neighboring molecule?  


W) Debye 
X) Keesom 
Y) Leitner 
Z) Bauer  


ANSWER: W) DEBYE  


## TOSS-UP  


9) EARTH AND SPACE Multiple Choice Which of the following soil types is characterized by mixing due to the expansion and contraction of clay minerals?  


W) Alfisols 
X) Gelisols [geh-lih-zols, hard g] 
Y) Inceptisols 
Z) Vertisols  


ANSWER: Z) VERTISOLS  


## BONUS  


9) EARTH AND SPACE Short Answer The Northern Atlantic Oscillation, abbreviated as the NAO, is an oscillation of Atlantic sea-surface temperatures due to changes in strength of what low and high pressure systems, respectively?  


ANSWER: ICELANDIC LOW, AZORES HIGH (ACCEPT: BERMUDA-AZORES HIGH, BERMUDA HIGH)  


DASONI 2022
## TOSS-UP  


10) MATH Short Answer Lucas is getting dressed, but doesn't want to turn on the lights and wake his brother. He will reach into each drawer and grab the minimum number of things from each to be guaranteed to get what he needs, since everything is thrown in unpaired and unsorted to the drawers. He needs 1 pair out of 40 socks that make 20 pairs, 1 shirt out of 10 and 1 pants out of 8. How many total things must he grab?  


Answer: 23  


## BONUS  


10) MATH Short Answer What is the area of the region between the curves y equals x squared and y equals four minus three x squared?  


ANSWER: 16/3  


## TOSS-UP  


11) PHYSICS Short Answer The electric field due to a dipole is proportional to what power of the distance to the dipole?  


ANSWER: - 3  


## BONUS  


11) PHYSICS Short Answer The electric potential inside of Akshansh's torso is given by \(z'2^{2}x'2 + y\) volts. In unit vector notation and in volts per meter, what is the electric field inside Akshansh's torso at the point (3, 1, -2)?  


ANSWER: - 24i - 1j + 36k (ACCEPT: ANY ORDERING OF THE THREE TERMS)  


## TOSS-UP
12) ENERGY Short Answer Davidson HS A Team members are studying types of graphs. They learn about null graphs - graphs with no edges - and complete graphs - graphs where every pair of vertices are connected by 1 edge. How many edges are in a complete - 9 graph?  


Answer: 36  


## BONUS  


12) ENERGY Multiple Choice Davidson HS B Team members are studying the color index of stars. Order the following three stars in terms of increasing B-V color index:  


1) Our Sun 
2) Aldebaran 
3) Vega  


ANSWER: 3, 1, 2 (ACCEPT: VEGA, OUR SUN, ALDEBARAN)  


## TOSS-UP  


13) BIOLOGY Multiple Choice In Drosophila [druh-SAW-fil-uh], which of the following genotypes would be male?  


W) X0 [X-zero] 
X) XX 
Y) XXX 
Z) XXY  


ANSWER: W) X0  


## BONUS  


13) BIOLOGY Short Answer Hymenoptera [high-men-OP-ter-uh] display a haplodiploidy [hap-low-DIH-ploy-dee] sex determination system. Arrange the following three relationships in order of increasing coefficient of relatedness in Hymenoptera:  


1) Males and the queen 
2) Sister workers 
3) Queen and her sons
## TOSS-UP  


14) CHEMISTRY Short Answer Identify all of the following three reactions that would be anti-Markovnikov:  


1) Reaction of an alkene with hydrogen bromide in the presence of a peroxide  
2) Acid-catalyzed hydration  
3) Hydroboration-oxidation  


ANSWER: 1 AND 3  


## BONUS  


14) CHEMISTRY Short Answer Identify all of the following three conditions that would hydrolyze an acetal:  


1) 3% HCl, \(\mathrm{H}_2\mathrm{O}\) , 30 minutes  
2) 3% NaOH, \(\mathrm{H}_2\mathrm{O}\) , 2 hours  
3) 3% acetone, \(\mathrm{CHCl}_3\) , 1 hour  


ANSWER: 1 ONLY  


## TOSS-UP  


15) EARTH AND SPACE Short Answer Winston is a geologist in the field trying to ID porphyroblasts [pour-FEER-o-blasts] in metamorphic rocks. He examines a pelitic [peh-LIH-tick] amphibolite [am-FIH-bo-lite] and notices a reddish brown crystal that shows cruciform twinning. What mineral has he found?  


ANSWER: STAUROLITE [STAR-uh-lite]  


## BONUS  


15) EARTH AND SPACE Multiple Choice A few days before the DASONI tournament, Emmy got a notification from QuakeFeed that there had been a magnitude 6.6 earthquake about 50
kilometers off the west coast of Cyprus. Which of the following best describes the likely origin of this earthquake?  


W) Renewed activity along a failed rift zone  
X) Slippage along the East Anatolian transform fault  
Y) Faulting at the Eurasian-Anatolian rift zone  
Z) Buildup of stress along the Anatolian-African convergent boundary  


ANSWER: Z) BUILDUP OF STRESS ALONG THE ANATOLIAN-AFRICAN CONVERGENT BOUNDARY  


## TOSS-UP  


16) MATH Short Answer What is 14 mod \(7 + 44 \mathrm{mod} 7 + (49 \mathrm{mod} 5 + 177 \mathrm{mod} 11) \mathrm{mod} 7?\)  


Answer: 7  


## BONUS  


16) MATH Short Answer What is the limit as x approaches 0 of open parenthesis cosine of quantity 2x end quantity minus one close parenthesis divided by x squared?  


ANSWER: - 2  


## TOSS-UP  


17) PHYSICS Short Answer Because the Sun is made of an electrically conducting plasma, it is an example of what type of system that involves a fluid affected by magnetic fields?  


ANSWER: MAGNETOHYDRODYNAMIC (ACCEPT HYDRO- Magnetic)  


## BONUS  


17) PHYSICS Short Answer Whispering gallery waves can follow concave surfaces using resonance. The sound intensity of whispering gallery waves is proportional to what power of distance?
## TOSS-UP  


18) ENERGY Multiple Choice Davidson HS A Team members are studying the high concentrations of Europium in some igneous rocks. Which of the following best describes why this anomaly exists?W) Europium has a relatively stable \(+2\) oxidation state and can replace elements like Calcium in common igneous mineralsX) Europium is most stable in its \(+3\) oxidation state and can replace ions like \(\mathrm{Fe}^{3 + }\) in common igneous mineralsY) Europium is stable in a \(+4\) oxidation state and can replace elements like Silicon in common igneous mineralsZ) Europium is produced from the decay of heavier nuclides that are found in trace amounts in common igneous minerals  


ANSWER: W) EUROPIUM HAS A RELATIVELY STABLE \(+2\) OXIDATION STATE AND CAN REPLACE ELEMENTS LIKE CALCIUM IN COMMON IGNEOUS MINERAL  


## BONUS  


18) ENERGY Short Answer Davidson HS A Team members are studying parthenogenesis, the development of unfertilized eggs. While sexual reproduction has the advantage of introducing genetic diversity into a population, the limited amount of parthenogenesis that has been observed is puzzling because the number of offspring being equal, the growth rate of an all-female population is expected to be how many times greater than the growth rate of a population consisting of half males and half females?  


ANSWER: 2
19) BIOLOGY Short Answer Identify all of the following three statements that are true about operant conditioning:  


1) The learner is passive  
2) The stimulus occurs after the response  
3) The response is voluntary  


ANSWER: 2 AND 3  


## BONUS  


19) BIOLOGY Short Answer What anatomical term is given to the part of a flower consisting of the calyx and corolla?  


ANSWER: PERIANTH [PAIR- ee- anth]  


## TOSS-UP  


20) CHEMISTRY Short Answer Magnetite is a common iron oxide that is the most magnetic naturally occurring mineral on earth. Give its formula and the average charge of the iron cation.  


ANSWER: \(\mathrm{Fe}_{3}\mathrm{O}_{4}\) +2.67 (ACCEPT: \(+8 / 3\)  


## BONUS  


20) CHEMISTRY Short Answer Magnetite is an example of a class of minerals with formula \(\mathrm{AB}_{2}\mathrm{X}_{4}\) in which the \(\mathrm{A}^{2 + }\) cation is found in a tetrahedral hole and the \(\mathrm{B}^{3 + }\) cation is found in an octahedral hole. Name this class of minerals.  


ANSWER: SPINEL  


## TOSS-UP  


21) EARTH AND SPACE Short Answer By name or number, order the following three sedimentary rocks in order of decreasing energy of depositional environment?  


1) Conglomerate  
2) Breccia
3) Sandstone  


ANSWER: 1, 2, 3 (ACCEPT: CONGLOMERATE, BRECCIA, SANDSTONE)  


## BONUS  


21) EARTH AND SPACE Short Answer Identify all of the following three statements that are not true about gamma ray bursts:  


1) Long gamma ray bursts are thought to have formed via stars larger than 30 solar masses going supernova and becoming a black hole2) Gamma ray bursts are most common in mature galaxies3) The shortest long gamma ray bursts are generally around half a second in duration  


ANSWER: 2 AND 3  


## TOSS-UP  


22) MATH Short Answer How many rectangles can be found within a grid of unit squares 6 units long and 3 units wide?  


Answer: 126  


## BONUS  


22) MATH Short Answer What is the area under the curve \(y = \ln x\) from \(x\) equals \(e\) to \(x\) equals \(3e\) ?  


ANSWER: 6e  


## TOSS-UP  


23) PHYSICS Multiple Choice Which of the following is most directly linked to why the Bohr model was inadequate for explaining the atom?  


W) Larmor formula  


X) Schrodinger Equation  


Y) Rydberg formula  


Z) Coulomb's Law
ANSWER: W) LARMOR FORMULA (SOLUTION: LARMOR DESCRIBES ENERGY LOSS OF AN ACCELERATING CHARGE, SO ELECTRONS SHOULD SPIRAL INTO THE NUCLEUS)  


## BONUS  


23) PHYSICS Short Answer Name all of the following three isotopes that could form a Bose-Einstein condensate.  


1) Rubidium-87  


2) Helium-3  


3) Sodium-23  


ANSWER: ALL