title[[137, 180, 844, 214]]
# Competitive Division Double Elimination 4  

sub_title[[457, 254, 539, 272]]
## TOSS-UP  

text[[116, 284, 875, 304]]
1) BIOLOGY Short Answer What is the first class of antibody secreted after activation of a B cell?  

text[[115, 338, 238, 356]]
ANSWER: IgM  

sub_title[[465, 365, 533, 383]]
## BONUS  

text[[115, 394, 833, 441]]
1) BIOLOGY Short Answer Identify all of the following three statements that are true about action potentials in the heart:  

text[[144, 448, 861, 602]]
1) After HCN channels brings autorhythmic cells to threshold, voltage-gated calcium channels hyperpolarize the cell  
2) In contractile cells, voltage-gated sodium channels stay open for much longer than in neurons, producing a prolonged depolarization  
3) In renal failure, high extracellular potassium concentration produces depolarization that prevents HCN channels from opening  

text[[115, 634, 272, 652]]
ANSWER: 3 ONLYsub_title[[457, 92, 540, 110]]
## TOSS-UP  

text[[113, 122, 856, 170]]
2) CHEMISTRY Multiple Choice Which of the following is true regarding base-catalyzed aldol condensations?  

text[[113, 176, 740, 197]]
W) They begin with deprotonation of the hydrogen adjacent to the beta carbon  

text[[113, 202, 864, 250]]
X) If two different carbonyls are initially in one pot upon catalysis, four different products may be obtained  

text[[113, 256, 522, 276]]
Y) They involve a tertiary carbocation intermediate  

text[[113, 282, 602, 302]]
Z) Aldol reactions must be carried out in chlorinated solvents  

text[[113, 334, 833, 382]]
ANSWER: X) IF TWO DIFFERENT CARBONYLS ARE INITIALLY IN ONE POT UPON CATALYSIS, FOUR DIFFERENT PRODUCTS MAY BE OBTAINED  

sub_title[[464, 389, 533, 407]]
## BONUS  

text[[113, 418, 872, 493]]
2) CHEMISTRY Short Answer A specialized aldol condensation followed by Michael addition involves the reaction between methyl vinyl ketone and any other ketone to form an enone and a six-membered ring. What is this reaction called?  

text[[114, 525, 433, 545]]
ANSWER: ROBINSON ANNULATIONsub_title[[457, 92, 540, 110]]
## TOSS-UP  

text[[113, 122, 830, 169]]
3) EARTH AND SPACE Multiple Choice Which of the following metamorphic facies would mostly likely contain high concentrations of andalusite?  

text[[113, 177, 240, 275]]
W) Blueschist 
X) Hornfels 
Y) Greenschist 
Z) Amphibolite  

text[[114, 309, 330, 328]]
ANSWER: X) HORNFELS  

sub_title[[464, 336, 533, 354]]
## BONUS  

text[[114, 366, 875, 438]]
3) EARTH AND SPACE Short Answer Also known as DA variables, what class of pulsating white dwarf stars has prototype Ross 548, a period between 30 seconds and 25 minutes, and a hydrogen-rich atmosphere?  

text[[113, 471, 552, 491]]
ANSWER: ZZ CETI VARIABLES (ACCEPT ZZ CETI)sub_title[[456, 92, 540, 110]]
## TOSS-UP  

text[[113, 121, 875, 170]]
4) MATH Multiple Choice Which of the following pairs of terms correctly classifies the following differential equation: y double prime plus 2 y prime equals sin of 5x:  

text[[113, 177, 345, 275]]
W) non-linear, separable 
X) non-linear, non-separable 
Y) linear, separable 
Z) linear, non-separable  

text[[113, 308, 460, 328]]
ANSWER: Z) LINEAR, NON-SEPARABLE  

sub_title[[464, 362, 533, 380]]
## BONUS  

text[[115, 392, 604, 412]]
4) MATH Short Answer What is the last non-zero digit of 20!sub_title[[457, 92, 540, 110]]
## TOSS-UP  

text[[115, 122, 860, 195]]
5) PHYSICS Short Answer A centipede is learning classical mechanics and is analyzing a system using the Lagrangian formulation. If her teacher tells her that she must use the Hamiltonian formulation, what transformation can she use to convert between the two?  

text[[115, 228, 481, 247]]
ANSWER: LEGENDRE TRANSFORMATION  

sub_title[[464, 255, 533, 273]]
## BONUS  

text[[115, 285, 875, 384]]
5) PHYSICS Multiple Choice Objects such as stars can be approximated to be blackbodies. By Wien's law, there should be stars whose emissions peak in all areas of the visible spectrum. Stars never appear green or purple, even though some stars undoubtedly peak in those sections. Which of they following best explains this discrepancy?  

text[[115, 392, 816, 440]]
W) Stars emit so much light in other wavelengths that our eyes do not perceive the peak wavelength strongly enough  

text[[115, 446, 870, 492]]
X) Stars are not perfect blackbodies, as emission lines in hotter stars correspond with the colors we see  

text[[115, 499, 857, 547]]
Y) Stars are not perfect blackbodies, as absorption lines in colder stars cause the colors we see Z) Dust and gas in between us and the star filters those wavelengths out most  

text[[115, 579, 859, 626]]
ANSWER: W) Stars emit so much light in other wavelengths that our eyes do not perceive the peak wavelength strongly enoughsub_title[[457, 92, 540, 110]]
## TOSS-UP  

text[[114, 122, 872, 195]]
6) ENERGY Short Answer Davidson HS A team members are studying the enteric nervous system. What cells in gastric pits release histamine, which upregulates \(\mathrm{H}^{+} / \mathrm{K}^{+}\) ATPases on parietal cells?  

text[[114, 228, 712, 249]]
ANSWER: ENTEROCHROMAFFIN-LIKE CELLS (ACCEPT: ECL CELLS)  

sub_title[[464, 256, 533, 273]]
## BONUS  

text[[114, 285, 880, 412]]
6) CHEMISTRY Short Answer Davidson HS A team members are studying biophysical research methods. Recent advances have allowed researchers to forego the tedious collection of crystal data for biomolecules via X-ray diffraction via an alternative technique that determines structures via the computational combination of molecular "snapshots" taken from cooled aqueous samples. What is this technique called?  

text[[114, 444, 736, 465]]
ANSWER: CRYOGENIC ELECTRON MICROSCOPY (ACCEPT: CRYO- EM)  

sub_title[[457, 490, 540, 508]]
## TOSS-UP  

text[[114, 520, 850, 566]]
7) BIOLOGY Short Answer What amino acid has the most allowed values on a Ramachandran plot?  

text[[114, 601, 286, 620]]
ANSWER: GLYCINE  

sub_title[[464, 628, 533, 645]]
## BONUS  

text[[114, 658, 864, 758]]
7) BIOLOGY Short Answer Assuming that during the electron transport chain, each molecule of NADH produces 2.5 ATP and each molecule of FADH₂ produces 1.5 ATP, what is the net ATP yield from the aerobic respiration of 2 molecules of maltose, excluding the ATP produced from substrate-level phosphorylation [foss-for-uh-LAY-shun]?  

text[[114, 789, 236, 806]]
ANSWER: 112sub_title[[457, 93, 539, 110]]
## TOSS-UP  

text[[115, 122, 878, 169]]
8) CHEMISTRY Short Answer Phosphorus pentachloride exists as an ionic compound in the solid state. Give the molecular geometries for the cation and anion, respectively.  

text[[115, 202, 471, 220]]
ANSWER: TETRAHEDRAL, OCTAHEDRAL  

sub_title[[465, 230, 533, 248]]
## BONUS  

text[[114, 259, 879, 387]]
8) CHEMISTRY Short Answer Consider the gas phase decomposition of phosphorus pentachloride into phosphorus trichloride and chlorine gas. 1 mole of \(\mathrm{PCl}_5\) is placed into a sealed container, and at equilibrium, the total pressure in the container is 0.2 bar. Given that the \(\mathrm{K}_{\mathrm{p}}\) for this reaction is 1.4, to one significant figure, how many moles of \(\mathrm{Cl}_2\) will be present at equilibrium?  

text[[115, 419, 230, 437]]
ANSWER: 0.9  

sub_title[[457, 464, 540, 482]]
## TOSS-UP  

text[[114, 494, 872, 568]]
9) EARTH AND SPACE Short Answer Due to stability, triple junctions often consist of three rift arms. However, there is generally only rifting along two of those arms. What is the name for the third, inactive rift arm?  

text[[114, 600, 475, 621]]
ANSWER: AULACOGEN [aw- LACK- oh- jen]  

sub_title[[465, 628, 533, 645]]
## BONUS  

text[[114, 658, 848, 758]]
9) EARTH AND SPACE Short Answer What oscillation trend, characterized by changes in the Aleutian Low, leads to cooler northwest Pacific seas surface temperatures, warmer northeast Pacific sea surface temperatures, and is thought to lead to more or less pronounced ENSO extremes, depending on phase?  

text[[114, 791, 639, 811]]
ANSWER: PACIFIC DECADAL OSCILLATION (ACCEPT: PDO)sub_title[[456, 92, 540, 110]]
## TOSS-UP  

text[[113, 123, 872, 220]]
10) MATH Short Answer Evan is drawing a rough approximation of a target. He draws two concentric circles of radius 5 and radius 1, and one other circle with radius 3 and a center somewhere within the radius 5 circle. What is the probability this circle is completely within the larger circle?  

text[[115, 230, 224, 247]]
Answer: 4/25  

sub_title[[464, 282, 533, 300]]
## BONUS  

text[[113, 313, 879, 411]]
10) MATH Short Answer Annabelle writes down every even number from 1 to 900 on a sheet of paper. On the same sheet of paper, Boya writes down every number from 1 to 900 that is 1 mod 3. CJ writes down on the same paper every number from 1 to 900 that is 2 mod 5. How many numbers appear exactly twice on the paper?  

text[[115, 420, 237, 437]]
ANSWER: 210sub_title[[456, 92, 540, 110]]
## TOSS-UP  

text[[115, 123, 812, 168]]
11) PHYSICS Short Answer In a Josephson junction, what particles tunnel across the thin insulating layer?  

text[[115, 201, 629, 220]]
ANSWER: COOPER PAIRS (DO NOT ACCEPT: ELECTRONS)  

sub_title[[464, 229, 533, 247]]
## BONUS  

text[[115, 259, 850, 280]]
11) PHYSICS Short Answer Which of the following best explains how Cooper pairs can form?  

text[[115, 287, 694, 307]]
W) Electrons interact quantum mechanically with plasmons to form pairs  

text[[115, 314, 625, 333]]
X) Electrons attract other electrons by exchanging virtual gluons  

text[[115, 340, 872, 385]]
Y) Electron movement induce magnetic fields that induce positive electric fields, attracting other electrons  

text[[115, 393, 839, 439]]
Z) Electrons cause a region of slightly higher positive charge in the ion lattice around them, attracting other electrons  

text[[115, 471, 875, 518]]
ANSWER: Z) Electrons cause a region of slightly higher positive charge in the ion lattice around them, attracting other electronssub_title[[456, 92, 540, 110]]
## TOSS-UP  

text[[113, 121, 874, 198]]
12) ENERGY Multiple Choice Davidson HS A team members are studying the Seebeck effect. A hot-point probe that utilizes the Seebeck effect would be most useful for measuring which of the following?  

text[[113, 202, 603, 303]]
W) Thermal expansion coefficient relative to a standard metal 
X) Dielectric breakdown voltage 
Y) Resistance of a surface layer 
Z) Whether a semiconductor is n or p type  

text[[113, 336, 544, 355]]
ANSWER: Z) Whether a semiconductor is n or p type  

sub_title[[464, 363, 533, 381]]
## BONUS  

text[[113, 392, 879, 494]]
ENERGY Multiple Choice Davidson HS B Team members are studying the works of mathematicians who bear an uncanny resemblance to Vladimir Putin. According to the Cauchy [KOH- shee]- Schwarz inequality, the absolute value of the dot product of the vector 4i - 3j and 5i + 12j theoretically cannot exceed what value?  

text[[113, 500, 173, 600]]
W) 10 
X) 16 
Y) 48 
Z) 65  

text[[113, 632, 252, 651]]
ANSWER: Z) 65sub_title[[456, 92, 539, 110]]
## TOSS-UP  

text[[115, 122, 875, 169]]
13) BIOLOGY Short Answer Identify all of the following four plant hormones that undergo polar transport by PIN proteins:  

text[[144, 176, 470, 277]]
1) Abscisic [ab-SIH-sick] acid  
2) Cytokinin [sigh-toe-KIH-nin]  
3) Auxin [OX-en]  
4) Strigolactone [STRIH-go-LACK-tone]  

text[[115, 309, 273, 327]]
ANSWER: 3 ONLY  

sub_title[[464, 336, 533, 354]]
## BONUS  

text[[113, 365, 875, 572]]
13) BIOLOGY Short Answer A population of 1000 phoenixes has two alleles for feather color, red and blue. The two alleles are codominant, and phoenixes with one of each allele are purple. The phoenixes are being hunted by dragons and need to hide in fire, giving red phoenixes an advantage. If red phoenixes have a relative fitness of 1, purple phoenixes 0.6, and blue phoenixes 0.25, and if there are originally 300 red phoenixes, 500 purple phoenixes, and 200 blue phoenixes in the population, then as a fraction in simplest terms, what will the frequency of blue phoenixes be in the next generation if we assume that the population follows the Hardy- Weinberg model?  

text[[115, 606, 263, 623]]
ANSWER: 16/169sub_title[[457, 92, 539, 109]]
## TOSS-UP  

text[[115, 122, 875, 168]]
14) CHEMISTRY Short Answer What diagram depicts the electronic states and spin multiplicities of a molecule and its transitions?  

text[[115, 202, 395, 220]]
ANSWER: JABLONSKI DIAGRAM  

sub_title[[464, 230, 533, 247]]
## BONUS  

text[[115, 260, 880, 306]]
14) CHEMISTRY Short Answer Carbenes can exist in either the singlet or triplet state. For simple carbenes, the triplet state is more stable. What rule explains why this is so?  

text[[115, 339, 880, 359]]
ANSWER: HUND'S FIRST RULE (ACCEPT: HUND'S RULE OF MAXIMUM MULTIPLICITY)sub_title[[456, 92, 540, 110]]
## TOSS-UP  

text[[113, 121, 881, 222]]
15) EARTH AND SPACE Multiple Choice Although epicycles are best-known for their appearance in Claudius Ptolemy's geocentric model of the universe, they were first proposed over two hundred years previous by what Ancient Greek astronomer who also discovered the precession of the equinoxes?  

text[[113, 230, 532, 330]]
W) HipparchusX) Eudoxus [you-DOCKS-us] of Cnidus [NYE-duss]Y) AristarchusZ) Eratosthenes [air-uh-TOSS-theh-nees]  

text[[114, 362, 352, 381]]
ANSWER: W) HIPPARCHUS  

sub_title[[464, 389, 533, 407]]
## BONUS  

text[[114, 418, 870, 465]]
15) EARTH AND SPACE Short Answer Order the following three soil orders from least to most defined soil horizons:  

text[[145, 473, 260, 492]]
1) Alfisols  

text[[145, 501, 238, 519]]
2) Entisols  

text[[145, 528, 260, 546]]
3) Inceptisols  

text[[113, 579, 668, 599]]
ANSWER: 2, 3, 1 (ACCEPT: ENTISOLS, INCEPTISOLS, ALFISOLS)sub_title[[457, 92, 540, 110]]
## TOSS-UP  

text[[115, 122, 765, 168]]
16) MATH Short Answer What is log base 9 of 240, rounded to one decimal place? Answer: 2.5  

sub_title[[464, 203, 533, 220]]
## BONUS  

text[[114, 233, 866, 359]]
16) MATH Short Answer Akshansh needs to submit his photo to receive credit for his contributions to DASONI. Every day, he is hounded by another writer to send his picture to Dallin by 7:30 am. He has a 50% chance to do as he is told, which he will do immediately. This starts on January 1st. What is the probability he has submitted his image before the tournament actually begins at 8am on January 15th?  

text[[115, 394, 315, 411]]
ANSWER: 32767/32768sub_title[[456, 92, 540, 110]]
## TOSS-UP  

text[[114, 122, 861, 196]]
17) PHYSICS Short Answer A ray hits an ideal diffusing surface at 30 degrees to the horizontal. By what factor will the intensity of the reflected light be multiplied by if the ray instead hits at 60 degrees to the horizontal?  

text[[114, 230, 262, 249]]
ANSWER: sqrt(3)  

sub_title[[464, 256, 533, 275]]
## BONUS  

text[[113, 286, 866, 308]]
17) PHYSICS Multiple Choice Which of the following best explains a Debye sheath in a plasma?  

text[[113, 312, 781, 333]]
W) A positively charged layer caused by low-energy heavy ions attracting each other  

text[[113, 339, 803, 384]]
X) A positively charged layer caused by high energy electrons leaving the plasma near a transition  

text[[113, 392, 870, 439]]
Y) A negatively charged layer caused by the unequal presence of charges in a plasma made from ionic materials  

text[[113, 445, 718, 467]]
Z) A negatively charged layer induced in a plasma by nearby electric charges  

text[[113, 499, 876, 546]]
ANSWER: X) A positively charged layer caused by high energy electrons leaving the plasma near a transitionsub_title[[457, 92, 540, 110]]
## TOSS-UP  

text[[113, 121, 881, 222]]
18) ENERGY Short Answer Davidson HS A Team members are studying structural geology and how to interpret geologic cross sections. What is the dip direction and angle of a thrust fault with largest possible dip angle that slopes downward to the right with respect to its strike of Northeast?  

text[[114, 255, 428, 274]]
ANSWER: 45 DEGREES SOUTHEAST  

sub_title[[464, 309, 533, 327]]
## BONUS  

text[[114, 339, 879, 388]]
18) ENERGY Short Answer Davidson HS A Team members are studying active galaxies. By name or number, identify all of the three properties that BL Lac objects and OVV quasars do not share:  

text[[144, 393, 520, 466]]
1) Orientation relative to an observer on earth  
2) Strength of emission lines  
3) Luminosity  

text[[113, 498, 784, 519]]
ANSWER: 2 AND 3 (ACCEPT: STRENGTH OF EMISSION LINES, LUMINOSITY)sub_title[[456, 92, 540, 110]]
## TOSS-UP  

text[[113, 121, 882, 223]]
19) BIOLOGY Multiple Choice Many natives of the Tibetan Plateau carry the gene EPAS1 that allows them to live at high altitudes without increased hemoglobin levels. Researchers believe that EPAS1 came from the interbreeding of early Homo sapiens with another hominid species. Which of the following species likely donated the EPAS1 gene?  

text[[113, 230, 441, 330]]
W) Denisovans X) Neanderthals Y) Homo rudolfensis [roo-doll-FEN-sis] Z) Homo floresiensis [floor-ih-zee-EN-sis]  

text[[114, 362, 355, 381]]
ANSWER: W) DENISOVANS  

sub_title[[464, 415, 533, 433]]
## BONUS  

text[[113, 444, 880, 572]]
19) BIOLOGY Short Answer When potassium hydroxide is added to bacteria, if it causes them to lyse, the released DNA makes a viscous and stringy solution. Given that potassium hydroxide will dissolve the cell walls of bacteria that only have a thin layer of peptidoglycan [pep-TIH-do-GLY-can], identify all of the following three genera of bacteria that will produce a stringy solution when subjected to the test:  

text[[144, 579, 491, 653]]
1) Staphylococcus [STAFF-ih-luh-COCK-us] 
2) Clostridium [claw-STRIH-dee-um] 
3) Bacillus  

text[[114, 686, 260, 704]]
ANSWER: NONEsub_title[[457, 92, 540, 110]]
## TOSS-UP  

text[[115, 123, 874, 169]]
20) CHEMISTRY Short Answer According to frontier molecular orbital theory, at which position does electrophilic aromatic substitution occur in pyrrole?  

text[[115, 202, 453, 221]]
ANSWER: 2 (DO NOT ACCEPT: META)  

sub_title[[465, 230, 533, 247]]
## BONUS  

text[[114, 260, 879, 386]]
20) CHEMISTRY Short Answer The Upjohn dihydroxylation involves the reaction between an olefin and osmium tetroxide to yield a vicinal syn-diol. Normally, osmium(VI) is reduced to osmium(IV) per equivalent of olefin. However, because osmium tetroxide is nasty and expensive, it is often used in a catalytic amount along with a sacrificial catalyst. What is this sacrificial catalyst?  

text[[115, 418, 662, 438]]
ANSWER: N- METHYLMORPHOLINE N- OXIDE (ACCEPT: NMO)sub_title[[456, 92, 540, 110]]
## TOSS-UP  

text[[113, 122, 882, 170]]
21) EARTH AND SPACE Short Answer By name or number, identify all of the following drainage patterns that are considered subsequent:  

text[[144, 177, 240, 250]]
1) Trellis 
2) Annular 
3) Parallel  

text[[113, 281, 553, 302]]
ANSWER: 1 AND 2 (ACCEPT: TRELLIS, ANNULAR)  

sub_title[[464, 336, 532, 354]]
## BONUS  

text[[113, 365, 883, 492]]
21) EARTH AND SPACE Short Answer A recent study by the University of Glasgow suggests that some Earth's water might have formed as a result of solar wind carrying water-rich dust particles from the near-earth asteroid Itokawa. However, previously, one of the major hypotheses was that Earth's water came from asteroid impacts. What common class of volatile-rich asteroids were the source of these impacts?  

text[[113, 524, 525, 545]]
ANSWER: C- TYPE (ACCEPT: CARBONACEOUS)sub_title[[456, 92, 540, 110]]
## TOSS-UP  

text[[113, 122, 880, 197]]
22) MATH Short Answer Sam is putting rubber bands around circumferences of a sphere. If he puts on 4 rubber bands, what is the maximum number of regions he can divide the surface of the sphere into?Answer: 14  

text[[115, 205, 208, 221]]
Answer: 14  

sub_title[[464, 256, 533, 274]]
## BONUS  

text[[113, 286, 866, 386]]
22) MATH Multiple Choice When practicing for DASONI, Akshansh will buzz in with a normal "buzz" or his choice of copy-paste poem. Akshansh has a \(10\%\) chance to, at any point, use his poem. Once he uses this, this is all he will use for the rest of the 10 questions. What is the expected number of times Akshansh will use his poem, to the nearest question?  

text[[113, 393, 171, 512]]
W) 1 X) 2 Y) 4 Z) 6 Answer: Y) 4sub_title[[458, 92, 540, 110]]
## TOSS-UP  

text[[113, 122, 839, 170]]
23) PHYSICS Multiple Choice Which of the following operations on the wave function psi is directly proportional to the probability density?  

text[[115, 177, 241, 196]]
W) norm of psi  

text[[115, 204, 233, 222]]
X) psi squared  

text[[115, 230, 474, 250]]
Y) quantity norm of psi end quantity squared  

text[[115, 257, 260, 275]]
Z) real part of psi  

text[[114, 309, 561, 329]]
ANSWER: Y) quantity norm of psi end quantity squared  

sub_title[[463, 336, 533, 354]]
## BONUS  

text[[113, 366, 791, 387]]
23) PHYSICS Multiple Choice Which of the following is false about the Eightfold way?  

text[[115, 393, 550, 412]]
W) Baryons and mesons are both organized into octets  

text[[115, 420, 576, 439]]
X) Particles are organized by strangeness and color charge  

text[[115, 446, 568, 465]]
Y) Particles on opposite sides of an octet are antiparticles  

text[[115, 472, 716, 492]]
Z) Some particles share the same position on a diagram of the eightfold way  

text[[115, 525, 663, 546]]
ANSWER: X) Particles are organized by strangeness and color charge