
# Competitive Division Finals 1  


## TOSS-UP  


1) BIOLOGY Short Answer Van Valen's law states that the probability of extinction for a species is constant over time. Because this appears to contradict the idea that species will continually become better adapted to their environment and thus have a lower probability of extinction, it is explained by what hypothesis that states that species are in constant competition, which has the net effect of preventing a long-term gain in fitness?  


ANSWER: RED QUEEN HYPOTHESIS  


## BONUS  


1) BIOLOGY Short Answer Grime's CSR triangle classifies plant species based on their adaptations to stress, which encompasses resource availability, and disturbance, which encompasses natural disasters, disease, and interspecific interactions. C species function best in low stress and low disturbance, S species in high stress and low disturbance, and R species in high disturbance and low stress. Order the three types of species in order of first to last to colonize after a secondary succession event:  


1) C 
2) S 
3) R  


ANSWER: 3, 1, 2 (ACCEPT: R, C, S)
## TOSS-UP  


2) CHEMISTRY Short Answer A diazoketone, under thermal or photochemical conditions, can, with loss of nitrogen, form an organic compound in which the carbonyl is directly attached to an olefin. What is this functional group called?  


ANSWER: KETENE  


## BONUS  


2) CHEMISTRY Short Answer A round bottom flask initially contains diazoacetone dissolved in chloroform and is covered by aluminium foil. The foil is then taken off, the flask is irradiated with ultraviolet light, and ethylene is added to the reaction mixture. After off-gassing, what is the major product formed?  


ANSWER: CYCLOBUTANONE
## TOSS-UP  


3) EARTH AND SPACE Multiple Choice Which of the following is not a type of galactic filament?  


W) Wall  


X) Superstructure complex  


Y) Helicoid  


Z) Large quasar groups  


ANSWER: Y) HELICOLD  


## BONUS  


3) EARTH AND SPACE Short Answer Pyramid Lake is an endorheic lake located east of Reno, Nevada. Near the lake, there are many calcium carbonate deposits near areas that would have been underwater thousands of years ago during the existence of the larger Lake Lahontan. Knowing that there is no geothermal heating in the Pyramid Lake area, what is the identity of those calcium carbonate deposits?  


W) Travertine  


X) Oolite  


Y) Chalk  


Z) Tufa  


ANSWER: Z) TUFA
## TOSS-UP  


4) MATH Short Answer [read slowly] The point (5,-3) is rotated 90 degrees clockwise around the origin, then translated 7 units to the right and 1 unit up, then reflected across the x-axis. What is the distance between the resulting point and the original one?  


ANSWER: 5sqrt(2)  


## BONUS  


4) MATH Short Answer How many integers n from 3 to 1000 inclusive are there such that the number of diagonals in an n-gon is a multiple of 10?  


ANSWER: 200
## TOSS-UP  


5) PHYSICS Multiple Choice Milgrom's original hypothesis modified Newtonian gravity attempted to explain the rotation curves of galaxies by changing how gravity behaves at low accelerations. One way of doing this is by setting gravitational force proportional to the centripetal acceleration to what power?  


W) 1/2 X) 1 Y) 2 Z) 4  


ANSWER: Y) 2  


## BONUS  


5) PHYSICS Short Answer Griffin has stayed up all night and is now imagining things that break the laws of physics. He sees a slightly lubricated cantaloupe flying past him faster than the speed of light and draws its world line on a spacetime diagram from his own reference frame. If the angle between the world line and the x-axis is 60 degrees, how fast was the cantaloupe going, in meters per second and to two sig figs?  


ANSWER: 5.2 \* 10\*8
## TOSS-UP  


6) ENERGY Short Answer Davidson HS A team members are studying Green's theorem. What is the line integral of the vector field \(\mathbf{x}^{4}\mathbf{i} + \mathbf{y}^{3}\mathbf{j}\) over the curve C, where C is defined as the triangle in the xy-plane with vertices (0, 0), (0, 1), and (1, 0)?  


ANSWER: 0  


## BONUS  


6) ENERGY Short Answer Davidson HS A team members are studying weird hydrocarbons, one of which is cubane. As its name suggests, cubane is a molecule in which each vertex of a cube is represented by a CH group. If one hydrogen in cubane is replaced with a methyl group, how many stereocenters are added to the molecule?  


ANSWER: 6
## TOSS-UP  


7) BIOLOGY Short Answer Metformin [met-FOR-min], a type 2 diabetes drug, can cause lactic acidosis because it interferes with what metabolic pathway in which lactate generated during anaerobic respiration in skeletal muscle is converted into glucose in the liver?  


ANSWER: CORI CYCLE  


## BONUS  


7) BIOLOGY Short Answer Thioglycollate [thigh-oh-GLY-ko-late] broth is used in microbiology labs to test the oxygen consumption requirements of bacteria. The broth contains oxidizing agents that reduce oxygen to water. When thioglycollate broth is placed in a test tube that isn't fully sealed, order the following three types of bacteria in order of where they would be found in the tube, from top to bottom:  


1) Microaerophile  


2) Obligate aerobe  


3) Obligate anaerobe  


ANSWER: 2, 1, 3 (ACCEPT: OBLIGATE AEROBE, MICROAEROPHILE, OBLIGATE ANAEROBE)
## TOSS-UP  


8) CHEMISTRY Short Answer What phenomenon, which can be observed in the simple molecule propanediol, involves the instantaneous disappearance and reappearance of a proton at two different locations?  


ANSWER: PROTON TUNNELING  


## BONUS  


8) CHEMISTRY Short Answer The Schrodinger equation for many-electron atoms cannot be solved due to electron correlation. It can, however, be approximated, via the Hartree-Fock method, which approximates the antisymmetric wave function with a single function. What is this function called?  


ANSWER: SLATER DETERMINANT
## TOSS-UP  


9) EARTH AND SPACE Multiple Choice Which of the following statements is false about microplastics in the atmosphere?  


W) The bulk of airborne microplastics are fibers or secondary microplastics  


X) Microplastics are hydrophilic and can serve as condensation nuclei  


Y) Microplastic cycle through the earth's systems in a so-called "plastic cycle"  


Z) Microplastics are found in remote, mountaintop areas that are generally considered clean due to not usually being affected by the local climate  


ANSWER: X) MICROPLASTICS ARE HYDROPHILIC AND CAN SERVE AS CONDENSATION NUCLEI  


## BONUS  


9) EARTH AND SPACE Multiple Choice Due to freshwater influx from melting ice, the Atlantic Meridional Overturning Circulation, abbreviated as AMOC, is weakening and may eventually collapse altogether, possibly creating conditions similar to the Younger Dryas 15,000 years ago. Which of the following would not be an effect of AMOC collapse?  


X) Colder temperatures in western Europe  


Y) Warmer temperatures in the southern hemisphere  


Z) Strengthening of south asian monsoons  


ANSWER: Z) STRENGTHENING OF SOUTH ASIAN MONSOONS
## TOSS-UP  


10) MATH Short Answer Audrey flips 100 fair coins. What is the standard deviation in the expected number of heads she sees?  


ANSWER: 5  


## BONUS  


10) MATH Short Answer What is the area of the parallelogram bounded by the vectors \(< 4, 3, 5>\) and \(< 6, 7, 8>\)  


ANSWER: 15  


## TOSS-UP  


11) PHYSICS Short Answer In non-viscous fluids, the pressure times the change in volume gives mechanical work done by the system. If we want to calculate mechanical work for a viscous fluid, pressure and volume are replaced by what two tensors, respectively?  


ANSWER: STRESS, STRAIN  


## BONUS  


11) PHYSICS Short Answer Name all of the following that are equivalent to saying a system has ergodicity.  


1) The system can be replicated without some particles in the system  
2) A particle will eventually visit all points in a system  
3) A random collection of particles in a system is representative of the entire system  


ANSWER: 2 and 3]
## TOSS-UP  


12) ENERGY Multiple Choice Davidson HS A team members are studying molecular biology laboratory techniques. If you wanted to visualize protein bands on a western blot, which of the following reagents would be most appropriate?  


W) SYBR green 
X) Coomassie blue 
Y) Trypan blue 
Z) Ethidium bromide  


ANSWER: X) COOMASSIE BLUE  


## BONUS  


12) ENERGY Short Answer Davidson HS A team members are out doing fieldwork and come across a cliff face where they see two distinct layers. The top layer contains ichthyosaur fossils, and the bottom layer is cut through by a sill dated to be 300 million years old. The bottom layer also contains fossils of multiple orders of trilobite. By number, identify all of the following four geologic periods during which the bottom layer could have been deposited:  


1) Carboniferous 
2) Ordovician 
3) Permian 
4) Triassic  


ANSWER: 2 ONLY (ACCEPT: ORDOVICIAN)
## TOSS-UP  


13) BIOLOGY Short Answer Identify all of the following three statements that are true about histones:  


1) Histone H4 is not part of the nucleosomal core particle  
2) Histones are highly basic  
3) Bacteria do not have histones  


ANSWER: 2 AND 3  


## BONUS  


13) BIOLOGY Multiple Choice A 46,XY individual is diagnosed with complete androgen insensitivity syndrome. Which of the following best describes the duct system they have after development?  


W) Wolffian duct and no Müllerian [mew- LER- ee- en] duct  


X) Müllerian duct and no Wolffian duct  


Y) Both Wolffian and Müllerian ducts  


Z) Neither Wolffian nor Müllerian ducts  


ANSWER: Z) NEITHER WOLFFIAN NOR MÜLLERIAN DUCTS  


(SOLUTION: because the individual is XY, they develop testes that secrete anti- Müllerian hormone, degrading the Müllerian duct, but because their androgen receptors are nonfunctional, the Wolffian duct can't bind testosterone and degrades)
## TOSS-UP  


14) CHEMISTRY Short Answer A sample of fine iron powder is treated with a flow of carbon monoxide gas at room temperature. The resultant compound is a yellow viscous liquid. What is the identity of this compound?  


ANSWER: IRON PENTACARBONYL  


## BONUS  


14) CHEMISTRY Short Answer Dimanganese decacarbonyl is an important organometallic reagent. Give the coordination number and valence electron count, respectively, for each manganese atom.  


ANSWER: 6, 18
## TOSS-UP  


15) EARTH AND SPACE Short Answer As a star decreases in temperature, the strength of the titanium oxide spectral types increases until it peaks in M-type stars and begins to decrease. This is due to the titanium oxide combining with other materials to form what titanite mineral being used in solar cells?  


## ANSWER: PEROVSKITE  


## BONUS  


15) EARTH AND SPACE Short Answer Name all of the following three statements that are true about the Penrose process.  


1) Some mass is always lost to the black hole  
2) A Kerr black hole is, in general, more efficient than a Kerr-Newman one  
3) The ergosurface must be separate from the event horizon for the penrose process to function properly  


ANSWER: 1 and 3  


## TOSS-UP  


16) MATH Short Answer Alan chooses a random five-digit palindrome. What is the expected value of Alan's number?  


ANSWER: 55000  


## BONUS  


16) MATH Short Answer A tetrahedron and an octahedron have the same volume. What is the ratio of the surface area of the octahedron to the surface area of the tetrahedron?  


ANSWER: Cube root of 2 (ACCEPT: \(2^{\wedge}(\frac{1}{3})\)
## TOSS-UP  


17) PHYSICS Multiple Choice Where does the ergosurface of a rotating black hole intersect the event horizon?  


W) At the poles  


X) At the equator  


Y) At circles parallel to the equator around each pole  


Z) It depends on how fast the black hole is rotating  


ANSWER: W) AT THE POLES  


## BONUS  


17) PHYSICS Short Answer The path integral formulation is analogous to what principle in classical mechanics?  


ANSWER: ACTION PRINCIPLE (ACCEPT: PRINCIPLE OF LEAST ACTION)
## TOSS-UP  


18) ENERGY Short Answer Davidson HS A Team members are studying neutrino astronomy. Most neutrino detectors like Super-kamiokande do not detect the direct results of neutrino interactions but rather what type of emission?  


ANSWER: CHERENKOV RADIATION  


## BONUS  


18) ENERGY Multiple Choice Davidson MS B team members are studying the conduction of heat. Which of the following is not true of Fourier's law of heat conduction?  W) The temperature gradient points opposite to the direction of heat flow  X) A cube made out of an anisotropic material can have different heat flows even when the gradient is held constant  Y) The heat kernel is a solution to Fourier's law  Z) Resistance adds in reciprocal  


ANSWER: Z) RESISTANCE ADDS IN RECIPROCAL
## TOSS-UP  


19) BIOLOGY Short Answer In in vitro fertilization, FSH is used to stimulate excess follicle production, which are then grown in a dish. When fertilized eggs are reintroduced into the uterus, they are immediately able to implant into the endometrium, indicating the embryo is in what stage of development?  


ANSWER: BLASTOCYST  


## BONUS  


19) BIOLOGY Multiple Choice While doing fieldwork, Audrey stumbles across a plant she doesn't recognize. She notes that it has vascular tissue, its leaves are microphylls, and it has strobili [stro- BIH-lie]. Based on these observations, what phylum does this plant most likely belong to?  


W) Lycophyta  


X) Psilotophyta [sigh-LOW-duh-fie-duh]  


Y) Pterophyta [TARE-uh-fie-duh]  


Z) Gnetophyta [NEE-duh-fie-duh]  


ANSWER: W) LYCOPHYTA
## TOSS-UP  


20) CHEMISTRY Multiple Choice The Diels-Alder reaction is the most famous type of pericyclic reaction. Which of the following pairs of dienes and dienophiles will NOT undergo a Diels-Alder reaction?  


W) Danishefsky's diene and vinyl alcohol 
X) Danishefsky's diene and maleic anhydride 
Y) acrolein and vinyl alcohol 
Z) acrolein and maleic anhydride  


ANSWER: Z) ACROLEIN AND MALEIC ANHYDRIDE  


## BONUS  


20) CHEMISTRY Short Answer Another type of pericyclic reaction reminiscent of the Diels-Alder reaction, albeit less well known, involves a \([4 + 1]\) cycloaddition between a diene and sulfur dioxide. What is this subclass of cycloadditions called?  


ANSWER: CHELOTROPIC REACTION
## TOSS-UP  


21) EARTH AND SPACE Short Answer Jonathan is observing a star and determines this star has an apparent magnitude of \(+7.8\) . If this star is a standard candle known to have an absolute magnitude of \(+2.8\) , how far, in parsecs, is this star from earth?  


ANSWER: 100  


## BONUS  


21) EARTH AND SPACE Multiple Choice Currently, the majority of lithium is mined from brines, but hard-rock mining is becoming increasingly popular, due to demand for longer-lasting batteries. Which of the following is not a reason why up until recently, brine mining was the favored method?  


W) Hard-rock mining is more resource-intensive than brine mining  


X) Brine mining does not use toxic chemicals in the mining process  


Z) Brine mining is cheaper than hard-rock mining  


ANSWER: X) BRINE MINING DOES NOT USE TOXIC CHEMICALS IN THE MINING PROCESS
## TOSS-UP  


22) MATH Short Answer Arnesh is asked to find the remainder when \(\mathrm{x}^{\wedge}3 - 3\mathrm{x}^{\wedge}2 - 5\mathrm{x} + 3\) is divided by \(\mathrm{x} + 2\) . However, he messes up and divides by \(\mathrm{x} - 2\) instead. By how much is Arnesh's answer off? ANSWER: 4  


## BONUS  


22) MATH Short Answer Michelle is talking to her pet parrot. It starts with the probability of calling her Michelle at \(2 / 5\) and Jessica at \(3 / 5\) . These probabilities get \(50\%\) closer to \(1 / 2\) each time he says a name. What is the probability, as a fraction in simplest terms, that, when the parrot says the names 3 times, he says them all incorrectly and Michelle storms off?  


Answer: 693/4000  


## TOSS-UP  


23) PHYSICS Short Answer What disordered magnetic state is made up of particles frozen in a random configuration of spin?  


ANSWER: Spin glass  


## BONUS  


23) PHYSICS Short Answer Because it has zero spin, the Higgs Boson was the first elementary particle to be described by what equation?  


ANSWER: KLEIN- GORDON