
# Competitive Division Round Robin 3 TOSS-UP  


1) BIOLOGY Short Answer What is the fundamental structural unit of compact bone?  


ANSWER: OSTEON (ACCEPT: HAVERSIAN SYSTEM)  


## BONUS  


1) BIOLOGY Multiple Choice Sarcomas are a class of tumors that originate from cells of mesenchymal [mes-zen-KYE-mull] origin. Which of the following cell types could NOT generate a sarcoma?  


W) Osteocyte  X) Fibrocyte  Y) Keratinocyte [care-uh-TIN-o-site]  Z) Chondrocyte  


ANSWER: Y) KERATINOCYTE
## TOSS-UP  


2) CHEMISTRY Multiple Choice Which of the following reactions results in an Hofmann product if a bulky base is used?  


W) \(\mathrm{S}_{\mathrm{N}}2\) X) E2 Y) \(\mathrm{S}_{\mathrm{N}}1\) Z) E1  


ANSWER: X) E2  


## BONUS  


2) CHEMISTRY Multiple Choice Which of the following statements is false about \(\mathrm{S}_{\mathrm{N}}2\) reactions?  


W) They occur with inversion of stereochemistry  


X) They occur faster in polar aprotic solvents than in protic solvents  


Y) They commonly involve carbocation rearrangements  


Z) Tertiary substrates do not undergo \(\mathrm{S}_{\mathrm{N}}2\) reactions  


ANSWER: Y) THEY COMMONLY INVOLVE CARBOCATION REARRANGEMENTS
## TOSS-UP  


3) EARTH AND SPACE Short Answer Which Lagrange point is located behind the earth with respect to the sun?  


ANSWER: L2 (DO NOT ACCEPT: L5)  


(SOLUTION: L5 in the orbit and not behind)  


## BONUS  


3) EARTH AND SPACE Short Answer By name or number, identify all of the following three environmental lapse rates that could create an absolutely unstable atmosphere:  


1) 7 degrees Centigrade per kilometer  
2) 9 degrees Centigrade per kilometer  
3) 11 degrees Centigrade per kilometer  


ANSWER: 3 ONLY (ACCEPT: 11 DEGREES CENTIGRADE PER KILOMETER  


## TOSS-UP  


4) MATH Short Answer Akshansh is walking down a hotel hall, with doors numbered 1 to 500. He opens every door that is a multiple of 1, then closes every door that is a multiple of 2, then opens closed doors or closes open doors for every door that is a multiple of 3, then does the same for every number that is a multiple of 4, and so on through 500. How many doors are left open when he's done?  


Answer: 22  


## BONUS  


4) MATH Short Answer How many ways are there to choose positive integers a and b such that \(a + b = 20\) and \(a\) 'b has a units digit of 6?  


Answer: 6
## TOSS-UP  


5) PHYSICS Short Answer Since capacitors and inductors can resist current but do not dissipate it as heat, they have a nonzero value for what quantity?  


ANSWER: REACTANCE  


## BONUS  


5) PHYSICS Short Answer A telescope with an aperture of radius 1.5 meters is observing a teapot near Mars at a wavelength of 600 nanometers. Using the small angle approximation, what is the angular resolution of this telescope, in radians and to 2 sig figs?  


ANSWER: 2.4 \* 10\*- 7  


## TOSS-UP  


6) ENERGY Short Answer Davidson MS B team members are studying neuroglia. What ciliated cells line the ventricles and are responsible for producing and circulating cerebrospinal fluid?  


ANSWER: EPENDYMAL CELLS  


## BONUS  


6) ENERGY Short Answer Davidson HS A team members are studying Britney Spears' guide to semiconductor physics. One exciting prospect in semiconductor physics is a class of compounds that involve the coordination of metal ions or clusters to organic ligands. These compounds can have one, two, or three-dimensional structures as a result. What is this class of compounds called?  


ANSWER: METAL- ORGANIC FRAMEWORKS
## TOSS-UP  


7) BIOLOGY Multiple Choice Signal peptides are short sequences of amino acids that are found in proteins destined to be secreted. Amino acids in signal peptides tend to be hydrophobic, and the first few amino acids are often positively charged. Which of the following amino acids would you least expect to be found in a signal peptide?  


W) Leucine X) Lysine Y) Methionine Z) Serine  


ANSWER: Z) SERINE  


## BONUS  


7) BIOLOGY Multiple Choice G-protein coupled receptors are transmembrane proteins that span the plasma membrane 7 times. Given this information, which of the following would you expect to be the most prevalent secondary structure in G-protein coupled receptors?  


W) Alpha helix X) Parallel beta sheet Y) Antiparallel beta sheet Z) Pi helix  


ANSWER: W) ALPHA HELIX
## TOSS-UP  


8) CHEMISTRY Short Answer Tertiary aliphatic carbocations are more stable than primary aliphatic (aa-lih-FAT-ic) carbocations. What phenomenon explains why this is so?  


ANSWER: HYPERCONJUGATION (ACCEPT: POSITIVE HYPERCONJUGATION)  


## BONUS  


8) CHEMISTRY Short Answer Davidson HS A team members are studying quantum chemistry. Consider a particle in a one-dimensional box with length L. When \(n = 3\) , in terms of L, at what positions in the box would the nodes be?  


ANSWER: 0, L/3, 2L/3, AND L (MUST SAY ALL OF THEM)  


## TOSS-UP  


9) EARTH AND SPACE Multiple Choice Which of the following drainage patterns is often formed in areas where water drains from all directions into a central basin?  


W) Radial  


X) Trellis  


Y) Centripetal  


Z) Rectangular  


ANSWER: Y) CENTRIPETAL  


## BONUS  


9) EARTH AND SPACE Short Answer Often exhibited by varieties of corundum, what is the name for the optical phenomenon that occurs when light is reflected by small inclusions or impurities arranged in a six-ravaged pattern?  


ANSWER: ASTERISM
## TOSS-UP  


10) MATH Short Answer A number of animals are in a zoo. Monkeys are the most common animal in the zoo, with 10 of them. This is double the second most common animal, and together the two make up 1/5 of the total animals. How many animals are there in the zoo?  


Answer: 75  


## BONUS  


10) MATH Short Answer In the language of Logjam, a word is an arrangement of letters that has no two vowels adjacent to one another. How many arrangements of the word "animal" are words in Logjam?  


ANSWER: 72  


## TOSS-UP  


11) PHYSICS Short Answer A elastic rubber band obeys Hooke's law and has a spring constant of 250 Newtons per meter. Arvind yanks on one end of the band with 200 newtons of force. Dallin pulls on the other end with 200 Newtons of force. In meters, how much does the spring extend from its equilibrium position?  


ANSWER: 4/5 (ACCEPT: 0.8)  


## BONUS  


11) PHYSICS Multiple Choice Which of the following is false about a quantum harmonic oscillator?  


W) Energy levels are evenly spaced  


X) Energy is proportional to the inverse square of the characteristic quantum number  


Y) There is a minimum energy level for the oscillator  


Z) The angular frequency of the oscillator determines the spacing between energy levels  


ANSWER: X) Energy is proportional to the inverse square of the characteristic quantum number
## TOSS-UP  


12) ENERGY Multiple Choice Davidson HS A Team members are studying metamorphic rocks and their environments of formation. Which of the following conditions is not correctly matched with the type of metamorphic rock formed?W) Intermediate temperature, low pressure and hornfels [HORN-felz]X) Intermediate temperature, intermediate pressure and mica schistY) High temperature, high pressure and glaucophane [GLAW-kuh-fane] schistZ) Low temperature, low pressure and slate  


ANSWER: Y) HIGH TEMPERATURE, HIGH PRESSURE AND GLAUCOPHANE SCHISTBONUS  


12) ENERGY Short Answer Davidson HS B Team members are still studying hadrons. There is another hadron that, while technically unstable, has a relatively long free half-life of 10 minutes or so. Name the types of quark found in this hadron.ANSWER: UP AND DOWN  


ANSWER: UP AND DOWN  


## TOSS-UP  


13) BIOLOGY Short Answer Identify all of the following three tissues that are part of the periderm:  


1) Phelloderm [FELL-uh-derm] 
2) Secondary xylem 
3) Cork cambium  


ANSWER: 1 AND 3  


## BONUS  


13) BIOLOGY Short Answer What group of enzymes are responsible for charging transfer RNAs?  


ANSWER: AMINOACYL- tRNA SYNTHETASES (ACCEPT: ANYTHING THAT SOUNDS VAGUELY SIMILAR - ASK GRIFFIN IF NEEDED)
14) CHEMISTRY Short Answer Which allotrope of phosphorus is associated with a graphene-like structure where phosphorus atoms are linked to each other in a repeated hexagonal pattern?  


ANSWER: BLACK  


## BONUS  


14) CHEMISTRY Short Answer Identify all of the following three solutions that you would expect to display a negative deviation from Raoult's (ra-OOLTS) law:  


1) Chloroform and benzene  
2) Ethanol and methylcyclohexane (methyl-cyclo-HeX-ain)  
3) Hydrochloric acid and water  


ANSWER: 1 AND 3  


## TOSS-UP  


15) EARTH AND SPACE Short Answer Order the following three volcanic eruption types from most to least explosive:  


1) Plinian [PLIH-nee-in]  
2) Hawaiian  
3) Strombolian  


ANSWER: 1, 3, 2 (PLINIAN, STROMBOLIAN, HAWAIIAN)  


## BONUS  


15) EARTH AND SPACE Short Answer What is the name for the location in the ocean where the speed of sound is at a minimum?  


ANSWER: SOFAR CHANNEL
## TOSS-UP  


16) MATH Short Answer A planning meeting is scheduled to be 10 minutes long. Each member over the third will add ten minutes to the runtime and, if Akshansh is there, the time it would otherwise be is tripled. 5 people, including Akshansh, show up. How many minutes over the expected time is the meeting?  


Answer: 50  


## BONUS  


16) MATH Short Answer In base 16, how many single digit numbers have divisibility rules similar to that of 3 and 9 in base 10 (ie, the number is divisible by that factor if and only if the digit sum of the number is divisible by the factor)?  


Answer: 3  


## TOSS-UP  


17) PHYSICS Short Answer Exchange of a Z boson between particles cannot change many key properties such as electric charge and strangeness, which is why it is referred to as what type of interaction?  


ANSWER: NEUTRAL CURRENT (DO NOT ACCEPT: WEAK FORCE)  


## BONUS  


17) PHYSICS Short Answer A block of mass m slides down a frictionless ramp of height h. It then slides around a loop of radius r. If the gravitational acceleration is g, express the minimum height needed for the block to clear the loop without losing contact in terms of r, m and g.  


ANSWER: rg/2
## TOSS-UP  


18) ENERGY Short Answer Davidson MS A Team members are studying things they really shouldn't be and are now running from the cops in a pair of elevators, going down a 19 story building. The elevators are wired by an eccentric Davidson alum, and each elevator has a -1, a -2, and -3 button. The two elevators can take turns pressing a button, and both elevators will move down by that many floors. The elevator that pushes the button to land at the ground gets to go free, while the other drops to the center of the earth. What should Davidson students push first to get to escape?  


Answer: 3  


## BONUS  


18) ENERGY Short Answer Davidson HS B Team members are studying orbital mechanics. If a planet with orbital radius of r completes one quarter of its orbit in time t, what fraction of its orbit would a planet with orbital radius of 3r complete in the same amount of time?  


ANSWER: 1/36
## TOSS-UP  


19) BIOLOGY Multiple Choice During the nitrogen cycle, ammonia is converted to ammonium. However, the reverse process, referred to as volatilization, can occur under which of the following soil conditions?  


W) Low bacterial species diversity 
X) High pH 
Y) High moisture content 
Z) Low carbon to nitrogen ratio  


ANSWER: X) HIGH PH  


## BONUS  


19) BIOLOGY Multiple Choice Which of the following families of viruses would have a genome that obeys Chargaff's [SHAR-goff's] rules?  


W) Flavivirus [FLA-vih-virus] 
X) Coronavirus 
Y) Adenovirus 
Z) Filovirus [FIE-low-virus]  


ANSWER: Y) ADENOVIRUS
## TOSS-UP  


20) CHEMISTRY Short Answer Tetraxenonogold (II) (tetra-ZENON-oh-gold two) is a cation with the formula \(\mathrm{AuXe}_{4}^{2 + }\) . What is its molecular geometry?  


ANSWER: SQUARE PLANAR  


## BONUS  


20) CHEMISTRY Short Answer How many stereoisomers does the following compound have (read slowly!): 3,3-dimethyl-1,2-cyclopropanediol (cyclo-pro-pain-dye-all).  


ANSWER: THREE  


## TOSS-UP  


21) EARTH AND SPACE Short Answer Giving your answer with proper significant figures and in arcseconds, what is the parallax angle of an object measured to be 16 parsecs from the earth?  


ANSWER: 0.063 ARCSECONDS  


## BONUS  


21) EARTH AND SPACE Short Answer The Arches cluster is the densest known star cluster in the Milky Way. None of the main sequence stars have mass greater than a class O5 star, so scientists estimate the cluster's age at 2.5 million years. This was done by calculating what property of those type O5 stars?  


ANSWER: MAIN SEQUENCE TURNOFF POINT (ACCEPT: TURNOFF POINT)
## TOSS-UP  


22) MATH Short Answer Yajur claims to have flipped a coin 6 times in a row, and gotten 6 heads. Identify, by name or number, all alpha values for which we reject his claim:  


1) 0.10 
2) 0.05 
3) 0.01  


Answer: 1 AND 2 (ACCEPT: 0.10, 0.05)  


## BONUS  


22) MATH Short Answer A cup is a frustum with height 10 inches, top diameter of 4 inches and bottom diameter of 3 inches. If it were extended through the bottom to be a whole cone, how many times as large would the volume be?  


Answer: 64/37  


## TOSS-UP  


23) PHYSICS Short Answer A perfect lens will still be unable to focus light perfectly due to diffraction. The best-focused spot possible takes what shape?  


ANSWER: AIRY DISK  


## BONUS  


23) PHYSICS Short Answer Current passes through a 250 millihinery inductor at a rate given by two t cubed minus one half t squared plus four t minus seventeen amperes. What is the magnitude of the voltage drop across this inductor, at time t = 5 in volts and to the nearest decimal place?  


ANSWER: 29.8