
# 2021 MIT Science Bowl High School Invitational Round 6  


## TOSS UP  


1) BIOLOGY Short Answer In the most common form of glycolysis, the final step involves the synthesis of pyruvate from the dephosphorylation of what compound, which is also involved in carbon fixation of C4 plants?  


ANSWER: PEP (accept: Phosphoenolpyruvate)  


## BONUS  


1) BIOLOGY Short Answer By name or number, identify all of the following four compounds that would result in increased rates of glycolysis at concentrations higher than normal:  


1) AMP (A.M.P)  
2) Fructose-2,6-bisphosphate  
3) Glucagon  
4) Glucose-6-phosphate  


ANSWER: 1 and 2
## TOSS UP  


2) ENERGY Short Answer The Bartel group studies microRNAs which contribute to gene silencing by base-pairing to mRNA. What is the analogous RNA component involved in RNA interference?  


ANSWER: siRNAs (accept: small interfering RNAs)  


## BONUS  


2) ENERGY Multiple Choice The Bartel group produced a model for how microRNAs can act cooperatively to enhance gene silencing. Cooperative binding between proteins is often quantified using a Hill Coefficient. What values for a Hill coefficient indicate cooperative binding?  


W) Less than 0 
X) Between 0 and 0.5 
Y) Between 0.5 and 1 
Z) Greater than 1  


ANSWER: Z) Greater than 1
## TOSS UP  


3) CHEMISTRY Multiple Choice When you add zinc to concentrated sulfuric acid, you notice the evolution of a pungent gas from the solution. Which of the following is the most likely identity of the pungent gas?  


W) \(\mathrm{H}_{2}\mathrm{S}\) X) \(\mathrm{H}_{2}\) Y) \(\mathrm{SO}_{2}\) Z) \(\mathrm{SO}_{3}\)  


ANSWER: Y) \(\mathrm{SO}_{2}\)  


## BONUS  


3) CHEMISTRY Short Answer Fuming sulfuric acid consists of a concentrated solution of sulfur trioxide gas in sulfuric acid. What is the chemical formula of the predominant sulfur containing species in fuming sulfuric acid?  


ANSWER: \(\mathrm{H}_{2}\mathrm{S}_{2}\mathrm{O}_{7}\)  


## TOSS UP  


4) MATH Multiple Choice How many real roots does the polynomial \(x^{3} + 7x + 2\) have?  


W) 0 X) 1 Y) 2 Z) 3  


ANSWER: X) 1  


## BONUS  


4) MATH Short Answer What is the average value of the function \(f(x) = \sin^{2}(x)\cos^{2}(x)\) on the interval between \(x = 0\) and \(x = \pi\) ?  


ANSWER: 1/8
## TOSS UP  


5) EARTH AND SPACE Multiple Choice Which of the following is not an ore of copper?  


W) Bornite 
X) Chalcopyrite 
Y) Chalcocite 
Z) Bauxite  


ANSWER: Z) Bauxite  


## BONUS  


5) EARTH AND SPACE Short Answer What term describes the degree of flattening of celestial objects, generally due to rotation?  


ANSWER: Oblateness
## TOSS UP  


6) PHYSICS Short Answer To one significant figure, in meters, what is the maximum height attained by a ball thrown directly upward from the ground at 14 meters per second?  


ANSWER: 10 meters  


## BONUS  


6) PHYSICS Multiple Choice When the cosmic microwave background, or CMB, is measured, one finds a relative difference on the order of \(0.01\%\) between the frequency of the radiation in one direction and the frequency of the radiation in the opposite direction. This difference can be explained by which of the following?  


W) Small fluctuations in energy density in the early universe  


X) Emissions from a distant quasar  


X) Emissions from a distant quasar  


Y) The Local Group having nonzero velocity relative to the CMB  


Z) Interference from interstellar gas and dust  


ANSWER: Y) The Local Group having nonzero velocity relative to the CMB
## TOSS UP  


7) CHEMISTRY Multiple Choice A nickel-63 nucleus would most likely undergo which of the following decay modes?  


W) Alpha decay 
X) Electron capture 
Y) Beta-plus decay 
Z) Beta-minus decay  


ANSWER: Z) Beta-minus decay  


## BONUS  


7) CHEMISTRY Short Answer By name or number, rank the following 3 ligands in order of increasing denticity:  


1) EDTA 
2) Porphine 
3) Oxalate  


ANSWER: 3, 2, 1
## TOSS UP  


8) BIOLOGY Short Answer What term describes the majority of animals that are not able to tolerate changes in surrounding osmolarity?  


ANSWER: Stenohaline  


## BONUS  


8) BIOLOGY Short Answer By name or number, identify all of the following three statements that are true regarding human sensory mechanisms:  


1) Hearing is perceived via the bending of the cupula, leading to the hyperpolarization of mechanoreceptors  
2) The semicircular canals are partially responsible for balance  
3) Humans are well known for the use of a lateral line system  


ANSWER: 2 only
## TOSS UP  


9) MATH Multiple Choice A strange calculator has two buttons which either allow you to double the current number or add 1 to the current number. Starting from an input of 1, what is the minimum number of button presses required to arrive at a value of 20?  


W) 5 X) 6 Y) 7 Z) 8  


ANSWER: W) 5  


## BONUS  


9) MATH Short Answer On another strange calculator, there are two buttons which either allow you to multiply the current input by \(-2\) or subtract 1 from the current input. From a starting input of 1, what is the largest possible number that you can generate in at most 7 button presses?  


ANSWER: 96
## TOSS UP  


10) PHYSICS Multiple Choice Which of the following is NOT a condition of mechanical equilibrium?  


W) Acceleration is 0 
X) Net force is 0 
Y) Angular momentum is 0 
Z) Net torque is 0  


ANSWER: Y) Angular momentum is 0  


## BONUS  


10) PHYSICS Short Answer Consider a tube closed at one end and open at the other. A standing pressure wave is set up inside of that tube. By name or number, identify all of the four boundary conditions which must be satisfied to create this situation:  


1) The absolute pressure at the open end of the pipe is zero 
2) The gauge pressure at the open end of the pipe is zero 
3) The gauge pressure at the closed end of the pipe is zero 
4) The pressure at the closed end must equal the pressure at the open end  


ANSWER: 2 only
## TOSS UP  


11) EARTH AND SPACE Multiple Choice A decrease of 1 in a star's absolute magnitude corresponds to an increase in flux by approximately what factor?  


W) 1.5 
X) 2 
Y) 2.5 
Z) 5  


ANSWER: Y) 2.5  


## BONUS  


11) EARTH AND SPACE Short Answer The Barbados Ridge has resulted from South American Plate is subducting beneath Caribbean Plate and sediments accumulating in the space between them. What is the name of this type of structure?  


ANSWER: Accretionary wedge (accept: accretionary prism)  


## TOSS UP  


12) ENERGY Short Answer The Swager group at MIT has developed a device to detect peroxides in materials. Hydrogen peroxide decomposes in air to release what two molecules?  


ANSWER: Water and oxygen gas  


## BONUS  


12) ENERGY Short Answer The Swager group at MIT has recently published research on a chemiresistive methane sensor based on the formation of high-valent platinum. In the sensor, methane undergoes a two electron oxidation. What is the product of methane oxidation in this reaction?  


ANSWER: \(\mathrm{CH}_3\mathrm{OH}\) or methanol
## TOSS UP  


13) MATH Short Answer What mathematician developed a notation of calculus that uses \(dy\) and \(dx\) independently of the work of Isaac Newton?  


ANSWER: Gottfried Wilhelm Leibniz (accept: Leibniz)  


## BONUS  


13) MATH Multiple Choice What is the maximum \(r\) such that nine spheres of radius \(r\) can be packed inside a cube of side length 4?  


W) \(3\sqrt{3} - 5\) X) \(4\sqrt{3} - 6\) Y) \(2\sqrt{3} - \sqrt{6}\) Z) \(2\sqrt{3} - 1\)  


ANSWER: X) \(4\sqrt{3} - 6\)
## TOSS UP  


14) ENERGY Short Answer Researchers in the Fault Mechanics group at MIT are studying how magmatic intrusions can cause extensional strain in the Earth's crust. They are specifically studying the affects of intrusions that vertically cut through many layers of rock. What are the names of these intrusions?ANSWER: Dikes  


ANSWER: Dikes  


## BONUS  


14) ENERGY Short Answer Researchers in the Fault Mechanics group at MIT the moment magnitude scale to measure the intensity of foreshocks and aftershocks of earthquakes. Which of the following statements best describes the difference between the Richter scale and the moment magnitude scale?  


W) The Richter scale is based on energy released whereas the moment magnitude scale is based on damage done X) The moment magnitude scale considers factors such as fault displacement whereas the Richter scale does not Y) The Richter scale is a quadratic scale whereas the moment magnitude scale is a logarithmic scale Z) A high scoring earthquake on the Richter scale will have a low score on the moment magnitude scale  


ANSWER: X) The moment magnitude scale considers factors such as fault displacement whereas the Richter Scale does not
## TOSS UP  


15) BIOLOGY Multiple Choice Which of the following statements is true regarding plant transport?  


W) Sucrose is typically transported through sieve-tubes  
X) Bulk flow in plants functions through negative pressure  
Y) Under normal conditions, proteins may pass through plant plasmodesmata  
Z) The Casparian strip is only permeable to water  


ANSWER: W) Sucrose is typically transported through sieve-tubes  


## BONUS  


15) BIOLOGY Multiple Choice Suppose there are three groups with 100 organisms each with 3 different species W, X, and Y: Group 1 contains 25 W, 50 X and 25 Y, Group 2 contains 50 W and 50 X while Group 3 contains 33 W, 34 X, and 33 Y, which of the three groups has the highest diversity, according to the Shannon Diversity Index?  


W) Group 1  
X) Group 2  
Y) Group 3  
Z) Two groups have equal diversity  


ANSWER: Y) Group 3
## TOSS UP  


16) EARTH AND SPACE Short Answer What term describes streamlined asymmetrical hills formed by retreating glaciers that point in the opposite direction of a glacier's retreat?ANSWER: Drumlin  


ANSWER: Drumlin  


## BONUS  


16) EARTH AND SPACE Short Answer By name or number, identify all of the following three elements that are present in the Fraunhofer spectral line series:  


1) Hydrogen 
2) Calcium 
3) Iron  


ANSWER: 1, 2, and 3 (accept: all)  


## TOSS UP  


17) PHYSICS Short Answer In kilogram meters squared, what is the moment of inertia about the central axis perpendicular to the plane of a square with sides of length 3 meters and a mass of 10 kilograms?ANSWER: 15 kilogram meters squared  


ANSWER: 15 kilogram meters squared  


## BONUS  


17) PHYSICS Short Answer A 1-centimeter long projectile is shot through a wheel at 100 meters per second. There are 8 evenly spaced spokes on the wheel. What is the minimum angular velocity, in revolutions per second, that is needed to ensure the projectile hits a spoke?ANSWER: 1250 revolutions per second  


ANSWER: 1250 revolutions per second
## TOSS UP  


18) CHEMISTRY Multiple Choice In electroplating, the pure metal deposits on which electrode?  


W) Positive cathode 
X) Positive anode 
Y) Negative cathode 
Z) Negative anode  


ANSWER: Y) Negative cathode  


## BONUS  


18) CHEMISTRY Short Answer By name or number, identify all of the following three pairs of compounds which have the same molecular geometry:  


1) \(\mathrm{ICl}_3\) and \(\mathrm{NH}_3\) 2) \(\mathrm{SF}_4\) and \(\mathrm{XeF}_4\) 3) \(\mathrm{SO}_3\) and \(\mathrm{BF}_3\)  


ANSWER: 3 only
## TOSS UP  


19) CHEMISTRY Multiple Choice Jessica is performing colorimetry on a compound, so she plots the transmittance versus the concentration of the compound. Which of the following best describes the graph that results?  


W) Linear 
X) Quadratic 
Y) Exponential 
Z) Logarithmic  


ANSWER: Y) Exponential  


## BONUS  


19) CHEMISTRY Multiple Choice Which of the following numbers is closest to the maximal molar extinction coefficient in the visible light range of the permanganate anion?  


W) \(10^{2}\) liters per mole per centimeter 
X) \(10^{4}\) liters per mole per centimeter 
Y) \(10^{6}\) liters per mole per centimeter 
Z) \(10^{8}\) liters per mole per centimeter  


ANSWER: X) \(10^{4}\) liters per mole per centimeter
## TOSS UP  


20) PHYSICS Short Answer In relativity, the combination of space and time allows the construction of what vectors with timelike and spacelike components?  


ANSWER: Four- vectors  


## BONUS  


20) PHYSICS Short Answer By name or number, arrange the following three materials in order of increasing thermal conductivity:  


1) Diamond 
2) Brass 
3) Fiberglass  


ANSWER: 3, 2, 1  


## TOSS UP  


21) BIOLOGY Multiple Choice Which of the following mutagens is the most common cause of a thymine dimer?  


W) Benzo[a]pyrene (BEN-zoh A py-reen) 
X) Radium 
Y) UV light 
Z) Mustard gas  


ANSWER: Y) UV light  


## BONUS  


21) BIOLOGY Short Answer Quantum tunneling is thought to be a possible source of some mutations in DNA. Ions of what element in DNA are susceptible to moving via quantum tunneling?  


ANSWER: Hydrogen
## TOSS UP  


22) MATH Multiple Choice How many 100-digit positive integers have digit sum 898?  


W) 4950 
X) 5050 
Y) 5150 
Z) 5250  


ANSWER: X) 5050  


## BONUS  


22) MATH Short Answer For real values of \(x\) , what is the maximum possible value of \(\sin x + 2 \cos x\) ?  


ANSWER: \(\sqrt{5}\)  


## TOSS UP  


23) EARTH AND SPACE Short Answer What is the name given to the stage of our universe during which protons captured free electrons to form neutral hydrogen, resulting in the universe becoming transparent?  


ANSWER: Recombination  


## BONUS  


23) EARTH AND SPACE Multiple Choice Which of the following minerals is the principle ore for lead?  


W) Sphaelerite 
X) Galena 
Y) Cinnabar 
Z) Chalcopyrite  


ANSWER: X) Galena