title[[168, 113, 818, 179]]
# 2021 MIT Science Bowl High School Invitational Round 10  

sub_title[[450, 210, 546, 228]]
## TOSS-UP  

text[[145, 244, 850, 281]]
1) PHYSICS Short Answer Excluding gravity, strangeness is NOT conserved under which fundamental force?  

text[[147, 288, 407, 306]]
ANSWER: Weak nuclear force  

sub_title[[457, 341, 538, 360]]
## BONUS  

text[[146, 375, 850, 413]]
1) PHYSICS Multiple Choice When an undamped oscillator is driven at its resonant frequency, what happens to the amplitude of the resulting oscillation?  

text[[156, 424, 742, 443]]
W) It assumes a maximum possible value but stays constant in time.  

text[[164, 444, 518, 460]]
X) It grows linearly as a function of time.  

text[[164, 462, 567, 479]]
Y) It grows exponentially as a function of time.  

text[[164, 480, 465, 497]]
Z) It immediately becomes infinite.  

text[[147, 515, 596, 535]]
ANSWER: X) It grows linearly as a function of time.sub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[145, 153, 851, 190]]
2) CHEMISTRY Multiple Choice Which of the following compounds is ionic in the solid state?  

text[[157, 202, 380, 278]]
W) \(\mathrm{PCl}_{3}\) (read: \(P - C - L - 3\) X) \(\mathrm{PCl}_{5}\) (read: \(P - C - L - 5\) Y) \(\mathrm{SF}_{4}\) (read: \(S - F - 4\) Z) \(\mathrm{SF}_{6}\) (read: \(S - F - 6\)  

text[[146, 295, 316, 314]]
ANSWER: X) \(\mathrm{PCl}_{5}\)  

sub_title[[458, 348, 538, 366]]
## BONUS  

text[[146, 382, 851, 420]]
2) CHEMISTRY Short Answer By name or number, identify all of the following three statements that are true regarding reaction kinetics:  

text[[168, 431, 850, 542]]
1) A reaction with a more negative entropy of activation will have a smaller Arrhenius pre-exponential factor  
2) A reactions entropy of activation is strongly correlated to its Arrhenius activation energy  
3) A reaction's entropy of activation is strongly correlated with the temperature dependence of the rate  

text[[146, 560, 299, 578]]
ANSWER: 1 onlysub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[145, 153, 850, 191]]
3) MATH Short Answer By name or number, identify all of the following three shapes that can always be inscribed in a circle:  

text[[168, 204, 352, 259]]
1) Isosceles trapezoid 
2) Kite 
3) Rectangle  

text[[147, 277, 311, 296]]
ANSWER: 1 and 3  

sub_title[[458, 330, 538, 349]]
## BONUS  

text[[146, 364, 850, 402]]
3) MATH Short Answer What is the sum of the three smallest positive numbers \(x\) such that the floor of \(x\) is equal to \(14x / 15\) ?  

text[[147, 406, 286, 425]]
ANSWER: 45/7  

sub_title[[449, 479, 546, 497]]
## TOSS-UP  

text[[147, 512, 850, 569]]
4) ENERGY Short Answer Former MIT professor Jeremy England posited the hypothesis known as "dissipation-driven adaptation", which asserts that the emergence of life can be explained as a natural consequence of what physical law?  

text[[147, 574, 508, 593]]
ANSWER: Second law of thermodynamics  

sub_title[[458, 627, 538, 646]]
## BONUS  

text[[147, 661, 850, 754]]
4) ENERGY Short Answer Researchers in the MIT Department of Mathematics are investigating hydrodynamic quantum analogs, which feature droplets of water walking on a vibrating fluid bath. Which interpretation of quantum mechanics, which is inherently nonlocal but preserves determinism, does this behavior most resemble?  

text[[147, 760, 850, 797]]
ANSWER: Pilot wave theory (accept: pilot wave, pilot wave interpretation, Bohmian mechanics, de Broglie- Bohm theory)sub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[146, 153, 850, 191]]
5) EARTH AND SPACE Short Answer By name or number, identify all of the following three planets which generate internal heat from the Kelvin-Helmholtz mechanism:  

text[[168, 204, 259, 259]]
1) Uranus 
2) Saturn 
3) Jupiter  

text[[147, 277, 311, 295]]
ANSWER: 2 and 3  

sub_title[[457, 329, 539, 348]]
## BONUS  

text[[146, 363, 852, 401]]
5) EARTH AND SPACE Multiple Choice Which of the following is closest to the critical density of the universe in kilograms per meter cubed?  

text[[156, 411, 277, 488]]
W) \(1\times 10^{-15}\) X) \(1\times 10^{-25}\) Y) \(1\times 10^{-35}\) Z) \(1\times 10^{-45}\)  

text[[147, 504, 354, 523]]
ANSWER: X) \(1\times 10^{-25}\)sub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[145, 153, 850, 191]]
6) BIOLOGY Multiple Choice On which nitrogenous base does DNA methylation usually occur?  

text[[157, 204, 272, 277]]
W) Adenine 
X) Thymine 
Y) Guanine 
Z) Cytosine  

text[[146, 295, 346, 314]]
ANSWER: Z) Cytosine  

sub_title[[458, 348, 538, 366]]
## BONUS  

text[[146, 382, 850, 437]]
6) BIOLOGY Short Answer The process in which methylation patterns determine the activity of a maternal or paternal allele of a particular gene in early development is called what?ANSWER: Genomic imprinting (accept: imprinting)  

text[[146, 443, 590, 462]]
ANSWER: Genomic imprinting (accept: imprinting)  

sub_title[[448, 514, 546, 533]]
## TOSS UP  

text[[146, 549, 850, 586]]
7) EARTH AND SPACE Short Answer What term describes the thin strands of glass that form from the solidification of thin strands of lava after a basaltic eruption?ANSWER: Pele's Hair  

text[[147, 592, 338, 610]]
ANSWER: Pele's Hair  

sub_title[[458, 645, 538, 663]]
## BONUS  

text[[146, 680, 850, 753]]
7) EARTH AND SPACE Short Answer The Blandford-Znajcek (BLAN-ford-ZNAH- jeck) process is a proposed mechanism for the extraction of energy from a rotating black hole with a strong magnetic field. By name or number, identify all of the follwing three phenomena which could be explained by this mechanism?  

text[[168, 767, 386, 821]]
1) Astrophysical Jets 
2) Type II Supernovae 
3) Active Galactic Nuclei  

text[[147, 840, 311, 857]]
ANSWER: 1 and 3sub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[146, 153, 850, 227]]
8) PHYSICS Short Answer When curved pieces of glass are placed on each other, interference of light generates a pattern of concentric circles which is often used by lensmakers to verify their lens has the proper curvature. What is the name of this pattern?ANSWER: Newton rings  

text[[147, 233, 359, 251]]
ANSWER: Newton rings  

sub_title[[457, 286, 538, 305]]
## BONUS  

text[[146, 321, 850, 358]]
8) PHYSICS Short Answer By name or number, identify all of the following three statements which are true regarding wavefunctions:  

text[[168, 370, 850, 443]]
1) Wavefunctions must be continuous everywhere 
2) The derivatives of wavefunctions must be continuous everywhere 
3) The derivatives of wavefunctions must be continuous at all points where the potential is discontinuous  

text[[147, 461, 299, 480]]
ANSWER: 1 only  

sub_title[[448, 532, 546, 551]]
## TOSS UP  

text[[146, 567, 850, 604]]
9) CHEMISTRY Multiple Choice Which of the following species is least susceptible to lithium halogen exchange with an alkyl halide?  

text[[159, 617, 320, 632]]
W) phenylthium  

text[[160, 636, 303, 652]]
X) butyllithium  

text[[160, 655, 303, 671]]
Y) vinylthium  

text[[160, 673, 338, 690]]
Z) lithium acetylide  

text[[147, 708, 414, 727]]
ANSWER: Z) lithium acetylide  

sub_title[[457, 762, 538, 780]]
## BONUS  

text[[146, 796, 850, 833]]
9) CHEMISTRY Short Answer To the nearest whole number, how many grams of lithium are required to form one mole of butyllithium from 1-chlorobutane?  

text[[147, 840, 267, 857]]
ANSWER: 14sub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[146, 153, 850, 207]]
10) BIOLOGY Multiple Choice Which of the following cranial nerves controls the lateral rectus muscle, which is involved in moving the eye outwards to look to the side?  

text[[157, 221, 457, 295]]
W) Abducens (AB-duh-sins) nerve 
X) Facial nerve 
Y) Oculomotor nerve 
Z) Trigeminal nerve  

text[[146, 313, 540, 332]]
ANSWER: W) Abducens (AB-duh-sins) nerve  

sub_title[[457, 366, 538, 384]]
## BONUS  

text[[146, 400, 850, 438]]
10) BIOLOGY Short Answer By name or number, identify all of the following three statements that are true of muscarinic receptors:  

text[[168, 450, 765, 506]]
1) They are classified as ionotropic receptors 
2) They are primarily involved in the parasympathetic nervous system 
3) Atropine is a well-known muscarinic agonist  

text[[146, 523, 298, 541]]
ANSWER: 2 onlysub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[147, 153, 850, 246]]
11) ENERGY Short Answer The Langer group at MIT is currently researching drug delivery in various parts of the body, such as at the blood brain barrier. Although most drugs cannot cross the blood-brain barrier, there are a select few that can. What drug often used to treat Parkinson's disease is able to cross the blood brain barrier and is related to dopamine?ANSWER: L-dopa (accept: levodopa)  

text[[147, 251, 467, 270]]
ANSWER: L- dopa (accept: levodopa)  

sub_title[[457, 304, 538, 323]]
## BONUS  

text[[147, 339, 850, 412]]
11) ENERGY Short Answer The Langer group is also studying angiogenesis inhibition. One pathway that activates angiogenesis is through hypoxia, which upregulates what transcription factor that further activates the important angiogenesis inducer VEGF (V.E.G.F)?ANSWER: HIF-1a (accept: HIF-1, HIF, hypoxia-inducible factor)  

text[[147, 417, 704, 437]]
ANSWER: HIF- 1a (accept: HIF- 1, HIF, hypoxia- inducible factor)  

sub_title[[449, 489, 546, 508]]
## TOSS UP  

text[[147, 523, 850, 560]]
12) MATH Multiple Choice Which of the following functions of \(x\) is continuous on all real numbers?  

text[[157, 570, 260, 648]]
W) \(x^{2 / 3}\) X) \(\sqrt{x + 1}\) Y) \(7 / x\) Z) \(\tan x^{2}\)  

text[[147, 664, 313, 684]]
ANSWER: W) \(x^{2 / 3}\)  

sub_title[[457, 718, 538, 737]]
## BONUS  

text[[147, 753, 850, 790]]
12) MATH Short Answer Find the largest possible value of \(n\) divided by the totient of \(n\) , where \(n\) is a positive integer less than 1000.  

text[[147, 796, 286, 814]]
ANSWER: 35/8sub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[147, 153, 852, 228]]
13) BIOLOGY Short Answer Calcitonin secretion is known to be regulated by the release of a certain stomach hormone which is secreted from the G cells. What is the name of this stomach hormone, whose primary role is to stimulate the secretion of hydrochloric acid from the parietal cells of the stomach?ANSWER: Gastrin  

text[[147, 233, 311, 251]]
ANSWER: Gastrin  

sub_title[[457, 287, 538, 306]]
## BONUS  

text[[147, 321, 850, 360]]
13) BIOLOGY Short Answer Mammary glands and ceruminous (sehr-OO-min-uhs) glands are an example of what kind of glandular secretion?ANSWER: Apocrine  

text[[147, 364, 324, 383]]
ANSWER: Apocrine  

sub_title[[448, 434, 546, 454]]
## TOSS UP  

text[[146, 469, 850, 508]]
14) MATH Short Answer By name or number, identify all of the following three polynomials that are a factor of \(x^{99} - 1\) :  

text[[168, 518, 250, 575]]
1) \(x^{2} - 1\) 2) \(x^{3} - 1\) 3) \(x^{4} - 1\)  

text[[147, 592, 299, 611]]
ANSWER: 2 only  

sub_title[[457, 645, 538, 664]]
## BONUS  

text[[146, 680, 850, 718]]
14) MATH Short Answer How many nondecreasing sequences of 5 positive integers have first term 1 and last term 5?ANSWER: 35sub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[147, 153, 850, 264]]
15) ENERGY Short Answer Researchers in the Johnson group at MIT are exploring ways to safely deliver drugs into the human body. One method they developed involves attaching the drug onto a polymer framework to make a macromolecular prodrug. One step in the synthesis involves forming an ester from a carboxylic acid and a phenol. By name or number, identify all of the following three reagents that could accomplish this transformation:  

text[[168, 276, 420, 332]]
1) aqueous hydrogen chloride 
2) dicyclohexylcarbodiimide 
3) sodium hydroxide solution  

text[[148, 350, 310, 367]]
ANSWER: 1 and 2  

sub_title[[458, 403, 537, 420]]
## BONUS  

text[[147, 437, 850, 547]]
15) ENERGY Short Answer Researchers in the Johnson group at MIT are study methods of synthesizing macromolecular prodrugs. To synthesize the polymer framework, the researchers employ a ring-opening metathesis polymerization with a Grubbs third generation catalyst. The mechanism is analagous to a standard olefin metathesis reaction, but the monomers are cyclic olefins rather than linear olefins. Answer the following two questions about ring-opening metathesis polymerization.  

text[[168, 559, 850, 632]]
1) If you add 5 mole percent of Grubbs catalyst, what is the expected degree of polymerization? 
2) Is ring-opening metathesis polymerization step-growth or chain-growth polymerization?  

text[[147, 650, 240, 668]]
ANSWER:  

text[[168, 683, 437, 719]]
1) 20; 
2) chain-growth polymerizationsub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[146, 153, 850, 191]]
16) PHYSICS Short Answer With what power of distance does the potential energy between two molecules experiencing London Dispersion Forces scale as?ANSWER: \(-6\)  

text[[147, 197, 272, 215]]
ANSWER: \(- 6\)  

sub_title[[457, 249, 538, 268]]
## BONUS  

text[[147, 283, 850, 376]]
16) PHYSICS Short Answer A solid uniform disk has mass \(M\) , radius \(R\) , and moment of inertia \(I\) . A circle of radius \(R / 2\) is drawn on the disk such that the circle passes through the center of the disk and is tangent to the edge of the disk. This circle is then cut out of the disk. In terms of \(I\) , what is the moment of inertia of the remainder of the disk?ANSWER: \(13I / 16\)  

text[[147, 382, 305, 400]]
ANSWER: \(13I / 16\)  

sub_title[[449, 453, 546, 472]]
## TOSS UP  

text[[147, 488, 850, 543]]
17) EARTH AND SPACE Short Answer By name or number, identify all of the following three locations in a galaxy that one would predominately expect to find Population 1 stars:  

text[[168, 556, 308, 610]]
1) Halo 
2) Spiral arms 
3) Galactic disk  

text[[147, 628, 310, 646]]
ANSWER: 2 and 3  

sub_title[[457, 681, 538, 700]]
## BONUS  

text[[147, 716, 850, 753]]
17) EARTH AND SPACE Short Answer By name or number, identify all of the following three statements that are true about the Bergeron process:  

text[[168, 766, 792, 821]]
1) It involves supercooled water freezing upon impact with a solid surface 
2) Forming ice crystals absorb water vapor as they grow 
3) Only snow and not rain can be caused by the Bergeron Process  

text[[147, 840, 310, 857]]
ANSWER: 1 and 2sub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[147, 153, 851, 227]]
18) CHEMISTRY Short Answer A container contains an ideal gas at a pressure of 1.5 atmospheres. An isothermal compression process compresses the gas to a quarter of its original volume. By name or number, identify all of the following three variables which increased due to the compression:  

text[[168, 241, 408, 295]]
1) pressure 
2) work done by the system 
3) internal energy  

text[[147, 313, 299, 330]]
ANSWER: 1 only  

sub_title[[457, 366, 538, 384]]
## BONUS  

text[[147, 400, 850, 438]]
18) CHEMISTRY Short Answer By name or number, order the following three compounds in increasing order of their highest energy absorption in infrared spectroscopy:  

text[[168, 451, 312, 504]]
1) acetone 
2) chloroform 
3) methyl amine  

text[[147, 523, 300, 540]]
ANSWER: 2, 1, 3sub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[147, 153, 850, 209]]
19) BIOLOGY Multiple Choice Because the blood brain barrier limits the transport of most antibodies into the CNS, which of the following cells play a major role in the immune defense of the brain?  

text[[158, 221, 336, 295]]
W) Astrocytes 
X) Ependymal cells 
Y) Horizontal cells 
Z) Microglia  

text[[147, 313, 352, 332]]
ANSWER: Z) Microglia  

sub_title[[457, 366, 538, 384]]
## BONUS  

text[[147, 400, 850, 438]]
19) BIOLOGY Short Answer By name or number, identify all of the following four organisms that possess a nerve net:  

text[[168, 450, 390, 524]]
1) Portuguese man o' war 
2) King sea cucumber 
3) Brown recluse spider 
4) Pacific hagfish  

text[[147, 542, 311, 560]]
ANSWER: 1 and 2sub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[145, 153, 850, 191]]
20) PHYSICS Short Answer Suppose a certain ideal gas is observed to have an adiabatic index of 10/9. How many degrees of freedom does this imply?ANSWER: 18  

text[[147, 197, 267, 214]]
ANSWER: 18  

sub_title[[457, 249, 538, 268]]
## BONUS  

text[[146, 284, 850, 376]]
20) PHYSICS Short Answer Consider a monatomic ideal gas in the extreme relativistic limit, at which its energy is linearly proportional to momentum, unlike the classical limit in which energy is quadratically proportional to momentum. According to the equipartition theorem, what is the average energy per particle, in terms of Boltzmann's constant \(k\) and the temperature \(T\) ?ANSWER: \(3kT\)  

text[[147, 381, 281, 400]]
ANSWER: \(3kT\)  

sub_title[[449, 453, 546, 472]]
## TOSS UP  

text[[146, 488, 850, 543]]
21) EARTH AND SPACE Short Answer When the swash of a wave approaches the shoreline in an oblique fashion and the backwash is then parallel to the shore what phenomenon occurs?ANSWER: Longshore transport  

text[[147, 549, 417, 567]]
ANSWER: Longshore transport  

sub_title[[457, 602, 538, 621]]
## BONUS  

text[[146, 637, 850, 674]]
21) EARTH AND SPACE Short Answer By name or number, identify all of the following three currents that are cold water currents:  

text[[169, 686, 352, 741]]
1) California Current 
2) Labrador Current 
3) Gulf Stream  

text[[147, 760, 311, 778]]
ANSWER: 1 and 2sub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[145, 153, 850, 191]]
22) CHEMISTRY Short Answer By name or number, rank the following three substances by increasing nucleophilicity:  

text[[168, 203, 325, 258]]
1) Hydroxylamine 
2) Ammonia 
3) Water  

text[[146, 277, 299, 295]]
ANSWER: 3, 2, 1  

sub_title[[458, 329, 538, 348]]
## BONUS  

text[[145, 363, 850, 401]]
22) CHEMISTRY Short Answer How many nodal planes exist in the lowest unoccupied molecular orbital of 1,3,5-hexatriene?  

text[[146, 406, 258, 424]]
ANSWER: 4  

sub_title[[448, 477, 546, 496]]
## TOSS UP  

text[[145, 512, 850, 550]]
23) MATH Multiple Choice What mathematician discovered the first aperiodic tiling of a plane?  

text[[158, 562, 295, 636]]
W) Archimedes 
X) Euler 
Y) Laplace 
Z) Penrose  

text[[146, 653, 339, 672]]
ANSWER: Z) Penrose  

sub_title[[458, 707, 538, 726]]
## BONUS  

text[[146, 742, 850, 797]]
23) MATH Short Answer On a circle with radius 12, minor arc \(AB\) has measure 75 degrees. What is the area of the smaller section enclosed by the circle and line segment \(AB\) ?  

text[[146, 802, 418, 822]]
ANSWER: \(30\pi - 18\sqrt{2} - 18\sqrt{6}\)