title[[168, 113, 819, 179]]
# 2021 MIT Science Bowl High School Invitational Round 1  

sub_title[[448, 210, 546, 228]]
## TOSS UP  

text[[146, 245, 850, 283]]
1) EARTH AND SPACE Short Answer What is the distance, to the nearest megaparsec, of a galaxy moving at a recessional velocity of 120 kilometers per second?  

text[[147, 289, 258, 306]]
ANSWER: 2  

sub_title[[457, 341, 539, 360]]
## BONUS  

text[[147, 376, 852, 413]]
1) EARTH AND SPACE Short Answer By name or number, identify all of the following three statements that are true of the cosmic microwave background:  

text[[168, 425, 590, 480]]
1) Its temperature is around 30 kelvin 
2) It was formed at an early stage of the universe 
3) It serves as evidence for the Big Bang  

text[[147, 499, 311, 516]]
ANSWER: 2 and 3sub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[145, 153, 850, 191]]
2) MATH Multiple Choice The square of which of the following numbers has the same first and last digit?  

text[[157, 204, 218, 277]]
W) 26 
X) 23 
Y) 17 
Z) 14  

text[[146, 295, 300, 314]]
ANSWER: W) 26  

sub_title[[457, 348, 538, 366]]
## BONUS  

text[[145, 382, 850, 420]]
2) MATH Short Answer By name or number, identify all of the following four shapes which can be the intersection of a plane and a cube:  

text[[168, 432, 360, 505]]
1) Equilateral triangle 
2) Square 
3) Regular pentagon 
4) Regular hexagon  

text[[146, 523, 300, 541]]
ANSWER: 1, 2, 4sub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[145, 153, 850, 191]]
3) CHEMISTRY Multiple Choice Which of the following gases is the densest at room temperature?  

text[[158, 204, 327, 277]]
W) Helium 
X) Oxygen 
Y) Argon 
Z) Carbon dioxide  

text[[147, 295, 402, 314]]
ANSWER: Z) Carbon dioxide  

sub_title[[458, 348, 538, 366]]
## BONUS  

text[[145, 382, 850, 421]]
3) CHEMISTRY Short Answer If Anton combusts 11 grams of propane in air, to the nearest gram, how many grams of water vapor should he expect to get?  

text[[147, 425, 324, 444]]
ANSWER: 18 grams  

sub_title[[448, 495, 546, 514]]
## TOSS UP  

text[[145, 530, 850, 571]]
4) BIOLOGY Short Answer Lactase breaks down lactose into which two molecules? ANSWER: Glucose and galactose  

sub_title[[458, 608, 538, 626]]
## BONUS  

text[[145, 643, 850, 682]]
4) BIOLOGY Short Answer Which molecule is responsible for alcohol intolerance, produced by the metabolism of alcohol by alcohol dehydrogenases? ANSWER: Acetaldehydesub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[147, 153, 850, 208]]
5) PHYSICS Short Answer If 24 coulombs of charge flow through a resistor over two seconds with a potential difference of 4 volts, what is the resistance of the resistor in ohms?  

text[[147, 215, 327, 233]]
ANSWER: 1/3 ohms  

sub_title[[457, 268, 538, 287]]
## BONUS  

text[[147, 302, 850, 376]]
5) PHYSICS Short Answer In 2019, the SI base units were redefined to decrease the dependence of the base units on arbitrary physical artifacts and increase their dependence on fundamental constants. Which SI base unit was redefined so that Planck's constant would have an exact value?  

text[[147, 381, 325, 400]]
ANSWER: Kilogram  

sub_title[[449, 454, 546, 472]]
## TOSS UP  

text[[147, 488, 850, 543]]
6) ENERGY Multiple Choice The Tannenbaum group at MIT studies nitrogen-containing small molecules such as nitric oxide and their effects on biological systems. Which of the following effects can be caused by nitric oxide?  

text[[157, 555, 472, 628]]
W) Vasodilation of blood vessels 
X) Vasoconstriction of blood vessels 
Y) Extension of blood vessels 
Z) Migration of blood vessels  

text[[147, 647, 520, 666]]
ANSWER: W) Vasodilation of blood vessels  

sub_title[[457, 701, 538, 719]]
## BONUS  

text[[147, 735, 850, 790]]
6) ENERGY Short Answer The Voigt group studies genetic circuits in \(E\) . coli, which may use clusters of related genes under the control of a single promoter. What are these clusters called?  

text[[147, 797, 317, 815]]
ANSWER: Operonssub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[146, 153, 850, 191]]
7) CHEMISTRY Short Answer By name or number, identify all of the following three processes that are endothermic:  

text[[168, 203, 543, 258]]
1) Melting of ice 
2) Dissolution of sodium chloride in water 
3) Dissolution of sodium hydroxide in water  

text[[147, 276, 311, 294]]
ANSWER: 1 and 2  

sub_title[[458, 329, 538, 348]]
## BONUS  

text[[146, 363, 850, 401]]
7) CHEMISTRY Multiple Choice Which of the following is the VSEPR molecular geometry of sulfur trioxide?  

text[[160, 413, 358, 487]]
W) Bent 
X) Trigonal planar 
Y) Trigonal pyramidal 
Z) T-shaped  

text[[147, 504, 407, 523]]
ANSWER: X) Trigonal Planar  

sub_title[[449, 575, 546, 594]]
## TOSS UP  

text[[146, 610, 850, 666]]
8) ENERGY Short Answer The Cummins group at MIT is studying how to reduce phosphate directly to phosphines without having white phosphorus as an intermediate. What is the oxidation state of phosphorus in phosphate?  

text[[147, 671, 369, 690]]
ANSWER: \(+5\) (accept: 5)  

sub_title[[458, 725, 538, 743]]
## BONUS  

text[[146, 759, 850, 833]]
8) ENERGY Short Answer The Cummins group at MIT is studying the synthesis of oligophosphates such as adenosine triphosphate. The synthesis of adenosine triphosphate from adenosine diphosphate and the phosphate anion is accompanied by the elimination of what molecule?  

text[[147, 840, 298, 857]]
ANSWER: Watersub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[145, 153, 850, 192]]
9) PHYSICS Short Answer What is the name of the law that relates the hydrodynamical pressure, velocity, and gravitational potential?  

text[[147, 197, 325, 215]]
ANSWER: Bernoulli  

sub_title[[457, 249, 538, 268]]
## BONUS  

text[[145, 284, 850, 322]]
9) PHYSICS Multiple Choice When a spinning ice skater moves their hands inwards, what happens to the angular momentum and angular velocity, respectively?  

text[[157, 333, 723, 409]]
W) Angular momentum decreases, angular velocity increases  
X) Angular momentum increases, angular velocity increases  
Y) Angular momentum stays the same, angular velocity increases  
Z) Angular momentum stays the same, angular velocity decreases  

text[[146, 425, 797, 445]]
ANSWER: Y) Angular momentum stays the same, angular velocity increases  

sub_title[[449, 495, 546, 515]]
## TOSS UP  

text[[146, 530, 850, 569]]
10) MATH Short Answer What is the equation in standard form for the circle with a diameter whose endpoints are \((2,0)\) and \((6,6)\) ?  

text[[147, 573, 450, 594]]
ANSWER: \((x - 4)^{2} + (y - 3)^{2} = 13\)  

sub_title[[457, 627, 538, 646]]
## BONUS  

text[[146, 662, 850, 700]]
10) MATH Short Answer How many squares can be formed from the edges of a 6 by 6 square grid?  

text[[147, 704, 265, 723]]
ANSWER: 91sub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[146, 153, 850, 191]]
11) BIOLOGY Multiple Choice Which of the following anatomical features of finches led Charles Darwin to formulate his theory of evolution?  

text[[159, 204, 308, 278]]
W) Beak size 
X) Leg length 
Y) Tail plumage 
Z) Wingspan  

text[[146, 295, 360, 314]]
ANSWER: W) Beak size  

sub_title[[457, 348, 538, 366]]
## BONUS  

text[[146, 382, 850, 419]]
11) BIOLOGY Multiple Choice Which of the following animals is most closely related to a whale?  

text[[158, 432, 247, 504]]
W) Cat 
X) Frog 
Y) Snake 
Z) Sheep  

text[[146, 522, 322, 541]]
ANSWER: Z) Sheepsub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[146, 153, 850, 191]]
12) EARTH AND SPACE Multiple Choice Which of the following statements describes the conditions under which absolute instability would occur?  

text[[157, 202, 728, 277]]
W) Environmental lapse rate is less than the wet adiabatic rate  
X) Environmental lapse rate is less than the dry adiabatic rate  
Y) Environmental lapse rate is greater than the wet adiabatic rate  
Z) Environmental lapse rate is greater than the dry adiabatic rate  

text[[146, 294, 802, 314]]
ANSWER: Z) Environmental lapse rate is greater than the dry adiabatic rate  

sub_title[[457, 348, 538, 366]]
## BONUS  

text[[146, 382, 850, 420]]
12) EARTH AND SPACE Short Answer By name or number, order the following four ions in increasing concentration in seawater:  

text[[168, 432, 293, 505]]
1) Sodium  
2) Chloride  
3) Calcium  
4) Magnesium  

text[[146, 523, 321, 541]]
ANSWER: 3, 4, 1, 2sub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[147, 153, 850, 209]]
13) ENERGY Short Answer In 2001, MIT professor Wolfgang Ketterle won the Nobel Prize in Physics for being one of the first people to create what state of matter using an ultracold gas of sodium atoms?  

text[[147, 215, 460, 233]]
ANSWER: Bose-Einstein condensate  

sub_title[[457, 268, 538, 287]]
## BONUS  

text[[147, 302, 850, 395]]
13) ENERGY Short Answer Researchers in the MIT Center for Theoretical Physics are investigating the black hole information problem, which asks what happens to the information carried by an object when it falls into a black hole. This scenario is of particular interest because it appears to bring the conservation of quantum information into conflict with what theorem about black holes?  

text[[147, 400, 625, 420]]
ANSWER: No-hair theorem (accept: no-hair conjecture)  

sub_title[[448, 471, 546, 490]]
## TOSS UP  

text[[147, 506, 850, 544]]
14) EARTH AND SPACE Short Answer By name or number, order the following three cloud types by increasing altitude of where they are usually found:  

text[[168, 555, 272, 610]]
1) Cirrus 
2) Cumulus 
3) Stratus  

text[[147, 628, 299, 647]]
ANSWER: 3, 2, 1  

sub_title[[457, 682, 538, 701]]
## BONUS  

text[[147, 717, 850, 755]]
14) EARTH AND SPACE Short Answer What term refers to the periods when glaciers advance extremely quickly, at rates of up to 100 times their normal speed?  

text[[147, 760, 295, 779]]
ANSWER: Surgesub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[144, 153, 850, 173]]
15) CHEMISTRY Multiple Choice Which of the following acids is NOT polyprotic?  

text[[158, 185, 345, 259]]
W) Phosphorous acid 
X) Sulfurous acid 
Y) Carbonic acid 
Z) Palmitic acid  

text[[146, 277, 384, 295]]
ANSWER: Z) Palmitic acid  

sub_title[[458, 330, 538, 349]]
## BONUS  

text[[146, 364, 851, 402]]
15) CHEMISTRY Short Answer By name or number, identify all of the following three metals that would reduce aqueous \(\mathrm{Cu}^{2 + }\) :  

text[[168, 414, 245, 470]]
1) Iron 
2) Silver 
3) Zinc  

text[[146, 487, 311, 505]]
ANSWER: 1 and 3  

sub_title[[448, 558, 546, 577]]
## TOSS UP  

text[[146, 592, 810, 612]]
16) PHYSICS Short Answer An alpha particle is the nucleus of what element?  

text[[146, 618, 308, 636]]
ANSWER: Helium  

sub_title[[458, 671, 538, 690]]
## BONUS  

text[[146, 705, 850, 761]]
16) PHYSICS Short Answer Three identical resistors in parallel are connected in series to a fourth identical resistor. If the resistance of each resistor is 15 ohms, in ohms, what is the equivalent resistance of this entire arrangement?  

text[[146, 767, 317, 785]]
ANSWER: 20 ohmssub_title[[450, 118, 547, 137]]
## TOSS UP  

text[[146, 153, 692, 174]]
17) MATH Short Answer What is the sine of the arccosine of \(\frac{1}{5}\) ?  

text[[147, 180, 277, 204]]
ANSWER: \(\frac{2\sqrt{6}}{5}\)  

sub_title[[457, 235, 538, 254]]
## BONUS  

text[[147, 270, 850, 325]]
17) MATH Short Answer Suppose that events A, B, and C all have probability 0.3. If events B and C are disjoint and event A is independent from both the other events, then what is the probability that exactly one of the events occurs?  

text[[147, 330, 417, 349]]
ANSWER: 0.54 (accept: 27/50)  

sub_title[[450, 401, 547, 420]]
## TOSS UP  

text[[147, 436, 850, 492]]
18) BIOLOGY Short Answer In sea urchins, depolarization caused by the fusion of a sperm nucleus with an egg cytoplasm acts as a fast block to what condition in which multiple sperm fuse with a single egg?  

text[[147, 497, 345, 515]]
ANSWER: Polyspermy  

sub_title[[457, 550, 538, 569]]
## BONUS  

text[[147, 585, 850, 622]]
18) BIOLOGY Short Answer By name or number, identify all of the following three terms that accurately describe humans:  

text[[168, 635, 321, 690]]
1) Deuterostomes 
2) Diploblasts 
3) Holoblasts  

text[[147, 708, 310, 726]]
ANSWER: 1 and 3sub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[146, 153, 850, 191]]
19) PHYSICS Short Answer By name or number, identify all of the following three quantities which are vectors:  

text[[168, 204, 320, 259]]
1) Velocity 
2) Momentum 
3) Kinetic energy  

text[[147, 277, 311, 295]]
ANSWER: 1 and 2  

sub_title[[457, 330, 538, 349]]
## BONUS  

text[[147, 364, 850, 402]]
19) PHYSICS Multiple Choice At room temperature and pressure, iron displays what type of magnetism?  

text[[159, 414, 364, 488]]
W) Diamagnetism 
X) Paramagnetism 
Y) Ferromagnetism 
Z) Antiferromagnetism  

text[[147, 505, 410, 524]]
ANSWER: Y) Ferromagnetismsub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[147, 153, 850, 208]]
20) BIOLOGY Multiple Choice A plant with red flowers and a plant with white flowers are crossed to produce a plant with pink flowers. Which of the following best describes this type of inheritance?  

text[[159, 221, 386, 294]]
W) Mendelian 
X) Codominance 
Y) Incomplete dominance 
Z) Mitochondrial  

text[[147, 313, 463, 331]]
ANSWER: Y) Incomplete dominance  

sub_title[[457, 366, 538, 384]]
## BONUS  

text[[147, 400, 850, 455]]
20) BIOLOGY Multiple Choice A certain genetic disease in humans can only be inherited from the mother. Which of the following inheritance patterns could explain this effect?  

text[[159, 468, 354, 541]]
W) X-linked dominant 
X) X-linked recessive 
Y) Y-linked dominant 
Z) Mitochondrial  

text[[147, 560, 390, 578]]
ANSWER: Z) Mitochondrialsub_title[[448, 118, 547, 137]]
## TOSS UP  

text[[145, 153, 850, 190]]
21) CHEMISTRY Multiple Choice What is the formal charge of the carbon atom in methanol?  

text[[156, 203, 225, 277]]
W) \(- 2\) X) \(- 1\) Y) 0 Z) \(+1\)  

text[[146, 295, 285, 314]]
ANSWER: Y) 0  

sub_title[[457, 348, 539, 366]]
## BONUS  

text[[145, 382, 850, 420]]
21) CHEMISTRY Multiple Choice Which of the following ions does NOT have the same electron configuration as argon?  

text[[156, 430, 240, 504]]
W) \(\mathrm{Ca}^{2 + }\) X) \(\mathrm{Na}^{+}\) Y) \(\mathrm{Sc}^{3 + }\) Z) \(\mathrm{Cl}^{-}\)  

text[[146, 522, 310, 541]]
ANSWER: X) \(\mathrm{Na}^{+}\)sub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[145, 153, 850, 191]]
22) EARTH AND SPACE Multiple Choice In which of the following layers of the atmosphere does the ozone layer primarily reside in?  

text[[158, 204, 317, 277]]
W) Troposphere 
X) Stratosphere 
Y) Mesosphere 
Z) Thermosphere  

text[[147, 295, 382, 314]]
ANSWER: X) Stratosphere  

sub_title[[458, 348, 538, 366]]
## BONUS  

text[[145, 382, 850, 421]]
22) EARTH AND SPACE Short Answer What is the name of the angle which is the steepest angle where unconsolidated granulated material remains stable at a slope?  

text[[147, 425, 377, 444]]
ANSWER: Angle of repose  

sub_title[[448, 496, 546, 515]]
## TOSS UP  

text[[145, 531, 850, 570]]
23) MATH Short Answer Two concentric circles have radii 3 and 6. What is the area of an ellipse which shares its center with these circles and is tangent to both circles?  

text[[147, 575, 278, 592]]
ANSWER: \(18\pi\)  

sub_title[[458, 628, 538, 646]]
## BONUS  

text[[145, 662, 850, 700]]
23) MATH Short Answer What is the value of the expression \((1 + 3i)(3 + i)(1 + 5i)(5 + i)\) ?  

text[[147, 705, 292, 723]]
ANSWER: \(- 260\)