title[[168, 113, 819, 179]]
# 2021 MIT Science Bowl High School Invitational Round 3  

sub_title[[450, 210, 546, 228]]
## TOSS UP  

text[[146, 244, 850, 283]]
1) BIOLOGY Short Answer Which reproductive plant organ contains the stigma, style, and ovary?  

text[[147, 288, 433, 307]]
ANSWER: Carpel (accept: pistil)  

sub_title[[457, 341, 539, 360]]
## BONUS  

text[[146, 376, 850, 414]]
1) BIOLOGY Multiple Choice In plants, which ion is released in the cytoplasm immediately after gamete fusion?  

text[[157, 425, 293, 500]]
W) Potassium 
X) Calcium 
Y) Magnesium 
Z) Sodium  

text[[147, 517, 345, 536]]
ANSWER: X) Calciumsub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[146, 153, 850, 209]]
2) EARTH AND SPACE Short Answer A star has a temperature 5 times that of the sun and a radius 2 times that of the sun. The luminosity of this star is how many times greater than the solar luminosity?  

text[[147, 214, 287, 232]]
ANSWER: 2500  

sub_title[[457, 268, 538, 287]]
## BONUS  

text[[146, 303, 850, 340]]
2) EARTH AND SPACE Multiple Choice Approximately how thin is the earth's oceanic crust?  

text[[159, 353, 330, 425]]
W) 1 kilometer  X) 10 kilometers  Y) 100 kilometers  Z) 1000 kilometers  

text[[147, 444, 388, 462]]
ANSWER: X) 10 kilometerssub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[147, 153, 851, 245]]
3) ENERGY Short Answer The Lamason group at MIT studies the life cycle of Listeria monocytogenes (lis-TEER-ee-uh MON-oh-SAI-toh-jeenz), which causes listeriosis after consumption of contaminated foods. This bacterium, though capable of surviving in the absence or presence of oxygen, prefers aerobic respiration, and is termed what kind of anaerobe?  

text[[148, 251, 341, 269]]
ANSWER: Facultative  

sub_title[[457, 304, 538, 322]]
## BONUS  

text[[147, 339, 850, 411]]
3) ENERGY Multiple Choice The Lamason group at MIT studies the intracellular life cycle of Rickettsia parkeri (rick-KETT-see-uh par-KEHR-ee), a small bacterium whose genus causes many human diseases. Which of the following diseases is NOT caused by rickettsias?  

text[[158, 425, 310, 500]]
W) Lyme disease 
X) Spotted fever 
Y) Typhus fever 
Z) Scrub typhus  

text[[147, 517, 392, 535]]
ANSWER: W) Lyme diseasesub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[145, 153, 850, 191]]
4) PHYSICS Short Answer By name or number, identify all the following four units that are base SI units:  

text[[168, 204, 273, 277]]
1) Meter 
2) Gram 
3) Coulomb 
4) Second  

text[[147, 295, 311, 313]]
ANSWER: 1 and 4  

sub_title[[458, 348, 538, 366]]
## BONUS  

text[[145, 382, 850, 420]]
4) PHYSICS Short Answer What is the shape of an object's orbit if it is moving at above escape velocity?  

text[[147, 425, 336, 444]]
ANSWER: Hyperbola  

sub_title[[448, 495, 546, 514]]
## TOSS UP  

text[[145, 530, 850, 568]]
5) CHEMISTRY Short Answer Magnetite has chemical formula \(\mathrm{Fe}_{3}\mathrm{O}_{4}\) . In one formula unit of magnetite, how many iron II ions are there?  

text[[147, 574, 256, 592]]
ANSWER: 1  

sub_title[[458, 627, 538, 646]]
## BONUS  

text[[145, 662, 850, 700]]
5) CHEMISTRY Short Answer By name or number, identify all of the following statements which are true of the anion \(\mathrm{[FeO_4]^{2 - }}\) :  

text[[168, 712, 630, 767]]
1) It is a strong oxidizing agent. 
2) It is only stable in acidic conditions 
3) The oxidation state of iron in this compound is \(+6\)  

text[[147, 784, 311, 802]]
ANSWER: 1 and 3sub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[145, 153, 850, 192]]
6) MATH Short Answer What is the taxicab distance (also known as the Manhattan distance) between the points (3, 4) and (6, 2)?  

text[[147, 197, 258, 215]]
ANSWER: 5  

sub_title[[457, 250, 538, 269]]
## BONUS  

text[[147, 285, 850, 340]]
6) MATH Short Answer If two points in the Cartesian plane are at a Euclidean distance of 6, then what are the minimum and maximum possible taxicab distance between them?  

text[[147, 345, 338, 364]]
ANSWER: 6 and \(6\sqrt{2}\)  

sub_title[[448, 416, 546, 435]]
## TOSS UP  

text[[146, 451, 850, 489]]
7) CHEMISTRY Short Answer By name or number, rank the following three neutral atoms in order of increasing electron affinity:  

text[[168, 502, 270, 556]]
1) Chlorine 
2) Gold 
3) Oxygen  

text[[147, 574, 300, 592]]
ANSWER: 3, 2, 1  

sub_title[[457, 627, 538, 646]]
## BONUS  

text[[146, 662, 850, 700]]
7) CHEMISTRY Short Answer In the most stable resonance structure of the cyanate anion, what is the formal charge on the oxygen atom?  

text[[147, 704, 272, 722]]
ANSWER: - 1sub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[145, 153, 850, 191]]
8) BIOLOGY Multiple Choice Which of the following terms best characterizes the movement of a fly moving towards a sample of strongly-scented food?  

text[[158, 204, 370, 277]]
W) Positive chemotaxis 
X) Negative chemotaxis 
Y) Positive phototaxis 
Z) Negative phototaxis  

text[[146, 295, 446, 313]]
ANSWER: W) Positive chemotaxis  

sub_title[[458, 348, 538, 366]]
## BONUS  

text[[145, 382, 850, 420]]
8) BIOLOGY Short Answer What type of distribution best characterizes populations in environments in which resources are scarce?  

text[[147, 425, 324, 444]]
ANSWER: Clumped  

sub_title[[448, 496, 546, 515]]
## TOSS UP  

text[[146, 531, 850, 586]]
9) PHYSICS Short Answer Two springs with spring constants 4 newtons per meter and 2 newtons per meter are attached in series to a box weighing 10 kilograms. What is the effective spring constant of the system, in newtons per meter?  

text[[147, 592, 438, 610]]
ANSWER: 4/3 newtons per meter  

sub_title[[458, 645, 538, 664]]
## BONUS  

text[[146, 680, 850, 718]]
9) PHYSICS Short Answer By name or number, rank the following three types of radiation in terms of increasing ability to penetrate through barriers:  

text[[168, 731, 263, 786]]
1) Alpha 
2) Beta 
3) Gamma  

text[[147, 804, 300, 822]]
ANSWER: 1, 2, 3sub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[147, 153, 850, 227]]
10) ENERGY Short Answer Researchers in the Center for Theoretical Physics at MIT are working on designing quantum computers to tackle large datasets which are challenging to analyze by classical means. What basic unit of information is used to build quantum computers?  

text[[147, 233, 304, 251]]
ANSWER: Qubits  

sub_title[[457, 286, 538, 305]]
## BONUS  

text[[147, 321, 850, 394]]
10) ENERGY Short Answer Scientists in the Guth group at MIT have been studying the physics of the early universe. To do so, they have been analyzing data from WMAP, a probe which measures temperature differences in what energy remnant from the Big Bang?  

text[[147, 400, 732, 419]]
ANSWER: Cosmic microwave background radiation (accept: CMBR)  

sub_title[[448, 471, 546, 490]]
## TOSS UP  

text[[147, 506, 850, 543]]
11) EARTH AND SPACE Short Answer By name or number, arrange the following four minerals in order of increasing melting point:  

text[[168, 556, 289, 630]]
1) Amphibole 
2) Biotite 
3) Olivine 
4) Quartz  

text[[147, 648, 321, 666]]
ANSWER: 4, 2, 1, 3  

sub_title[[457, 701, 538, 719]]
## BONUS  

text[[147, 735, 850, 772]]
11) EARTH AND SPACE Short Answer On a psychrometer, if the dry bulb and the wet bulb temperatures are the same, what is the relative humidity?  

text[[147, 778, 293, 796]]
ANSWER: \(100\%\)sub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[147, 153, 852, 191]]
12) MATH Multiple Choice Which mathematician is credited with the first proof that there are infinitely many prime numbers?  

text[[159, 204, 372, 277]]
W) Euclid 
X) Leonhard Euler 
Y) Carl Friedrich Gauss 
Z) Bernhard Riemann  

text[[147, 295, 335, 313]]
ANSWER: W) Euclid  

sub_title[[457, 348, 538, 366]]
## BONUS  

text[[147, 382, 852, 420]]
12) MATH Short Answer What is the smallest possible surface area of a solid which has a volume of 12?  

text[[147, 423, 470, 444]]
ANSWER: \(12\sqrt[3]{3\pi}\) (accept: \(12(3\pi)^{1 / 3}\) )sub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[146, 153, 850, 191]]
13) CHEMISTRY Multiple Choice Which of the following gas molecules will have the largest constant volume molar heat capacity at standard conditions?  

text[[158, 203, 357, 277]]
W) Diatomic hydrogen 
X) Hydrogen chloride 
Y) Sulfur dioxide 
Z) Diatomic nitrogen  

text[[146, 295, 393, 313]]
ANSWER: Y) Sulfur dioxide  

sub_title[[458, 348, 538, 366]]
## BONUS  

text[[146, 382, 850, 438]]
13) CHEMISTRY Short Answer By name or number, identify all of the following three statements that would be true of the boiling of water at a temperature \(T\) above its normal boiling point of 373 kelvin.  

text[[168, 450, 850, 485]]
1) The enthalpy of vaporization for water at \(T\) is more positive than the enthalpy of vaporization at 373 kelvin.  

text[[168, 486, 850, 522]]
2) The Gibbs free energy of vaporization for water at \(T\) is more positive than the Gibbs free energy of vaporization at 373 kelvin.  

text[[168, 523, 850, 559]]
3) The change in internal energy for the boiling of water at \(T\) is more positive than the change in internal energy at 373 kelvin.  

text[[146, 577, 361, 595]]
ANSWER: None of themsub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[145, 153, 850, 191]]
14) MATH Short Answer How many zeroes does the number 33! (read: 33 factorial) end in?  

text[[146, 196, 258, 215]]
ANSWER: 7  

sub_title[[456, 250, 538, 269]]
## BONUS  

text[[146, 284, 850, 340]]
14) MATH Short Answer How many ways can a 2-by-2 grid of squares be painted such that each square is either red, green, or blue, and no two squares that share a side have the same color?  

text[[146, 345, 267, 364]]
ANSWER: 18  

sub_title[[448, 416, 546, 435]]
## TOSS UP  

text[[146, 451, 850, 507]]
15) PHYSICS Short Answer A simple pendulum with length \(L\) is released 50 degrees from the vertical. Which of the following describes the period of the resulting oscillations?  

text[[159, 519, 464, 596]]
W) The pendulum will not oscillate X) Less than \(2\pi \sqrt{L / g}\) Y) \(2\pi \sqrt{L / g}\) Z) More than \(2\pi \sqrt{L / g}\)  

text[[146, 613, 443, 635]]
ANSWER: Z) More than \(2\pi \sqrt{L / g}\)  

sub_title[[456, 668, 538, 687]]
## BONUS  

text[[146, 703, 850, 759]]
15) PHYSICS Short Answer A mass is placed on an inclined plane, which is angled 45 degrees from horizontal and has a coefficient of friction of 0.14. To the nearest meter per second squared, what is the acceleration of the mass?  

text[[146, 764, 485, 784]]
ANSWER: 6 meters per second squaredsub_title[[448, 118, 547, 137]]
## TOSS UP  

text[[146, 153, 850, 191]]
16) BIOLOGY Multiple Choice How many cotyledons (CAW-tuhl-LEE-duhns) does the seed of a tulip exhibit?  

text[[157, 204, 210, 277]]
W) 1 
X) 2 
Y) 3 
Z) 4  

text[[146, 295, 290, 314]]
ANSWER: W) 1  

sub_title[[457, 348, 539, 367]]
## BONUS  

text[[146, 382, 850, 420]]
16) BIOLOGY Multiple Choice Which of the following is NOT a trait of a dicot plant?  

text[[158, 432, 358, 505]]
W) Taproots 
X) Net-like veins 
Y) 4 to 5 petals 
Z) Two pollen furrows  

text[[146, 523, 434, 542]]
ANSWER: Z) Two pollen furrowssub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[147, 153, 850, 191]]
17) EARTH AND SPACE Short Answer By name or number, order the following three layers of the sun from outermost to innermost:  

text[[168, 204, 318, 258]]
1) Chromosphere 
2) Photosphere 
3) Corona  

text[[147, 277, 300, 295]]
ANSWER: 3, 1, 2  

sub_title[[457, 329, 538, 348]]
## BONUS  

text[[147, 363, 850, 418]]
17) EARTH AND SPACE Multiple Choice What is the name of the semiarid climate region characterized by grassland plains without trees occuring in temperate climates?  

text[[157, 432, 282, 506]]
W) Desert 
X) Steppe 
Y) Chaparral 
Z) Taiga  

text[[147, 523, 333, 542]]
ANSWER: X) Steppesub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[147, 153, 851, 227]]
18) ENERGY Short Answer Researchers in the Ceyer group at MIT are studying the reaction of xenon difluoride with a silicon surface, in which the silicon abstracts a fluorine atom from the compound. What is the electron pair geometry of xenon difluoride?ANSWER: Trigonal bipyramidal  

text[[147, 233, 424, 252]]
ANSWER: Trigonal bipyramidal  

sub_title[[457, 286, 538, 305]]
## BONUS  

text[[147, 321, 851, 394]]
18) ENERGY Short Answer The Danheiser group at MIT is working on annulation strategies to form rings of various sizes in organic synthesis. One of the strategies is to use allenes and tosyl cyanide. In an allene structure, what is the hybridization of the middle carbon?ANSWER: sp  

text[[147, 401, 266, 419]]
ANSWER: sp  

sub_title[[449, 472, 546, 490]]
## TOSS UP  

text[[147, 506, 850, 544]]
19) BIOLOGY Short Answer Proteolipid protein accounts for a majority of what general substance that is absent from the nodes of Ranvier?ANSWER: Myelin  

text[[147, 549, 304, 567]]
ANSWER: Myelin  

sub_title[[457, 602, 538, 621]]
## BONUS  

text[[147, 637, 850, 675]]
19) BIOLOGY Multiple Choice Which of the following best explains the reason why action potentials only proceed in one direction?  

text[[159, 686, 808, 760]]
W) The region behind the action potential has its sodium channels closed 
X) The region behind the action potential has its sodium channels open 
Y) The region behind the action potential has its potassium channels closed 
Z) The region behind the action potential has its potassium channels open  

text[[145, 778, 850, 797]]
ANSWER: W) The region behind the action potential has its sodium channels closedsub_title[[449, 118, 546, 137]]
## TOSS UP  

text[[145, 153, 850, 191]]
20) PHYSICS Short Answer By name or number, identify all of the following three colors of light which have wavelengths greater than green light:  

text[[168, 204, 259, 258]]
1) Red 
2) Violet 
3) Orange  

text[[147, 276, 311, 295]]
ANSWER: 1 and 3  

sub_title[[457, 329, 538, 348]]
## BONUS  

text[[146, 363, 850, 401]]
20) PHYSICS Multiple Choice Which of the following fundamental forces are sterile neutrinos thought to be able to interact with?  

text[[156, 414, 333, 488]]
W) Strong nuclear 
X) Weak nuclear 
Y) Electromagnetic 
Z) Gravitational  

text[[147, 505, 385, 524]]
ANSWER: Z) Gravitationalsub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[145, 153, 850, 191]]
21) CHEMISTRY Short Answer By name or number, identify all of the following three diatomic molecules which have a bond order of 3:  

text[[168, 204, 234, 259]]
1) \(O_{2}^{-}\) 2) CN- 3) CO  

text[[146, 277, 311, 295]]
ANSWER: 2 and 3  

sub_title[[457, 329, 538, 348]]
## BONUS  

text[[146, 363, 850, 401]]
21) CHEMISTRY Multiple Choice In which of the following compounds is the N-O (read: \(N O\) ) bond order the least?  

text[[156, 413, 240, 488]]
W) \(N_{2}O\) X) NO Y) \(N O_{2}\) Z) \(N O_{2}^{-}\)  

text[[146, 504, 318, 523]]
ANSWER: W) \(N_{2}O\)sub_title[[448, 118, 546, 137]]
## TOSS UP  

text[[145, 146, 850, 184]]
22) MATH Multiple Choice Which of the following statements follows from the statement "If A, then B?"  

text[[158, 191, 368, 265]]
W) If B, then A 
X) If not A, then not B 
Y) If not B, then not A 
Z) If not A, then B  

text[[146, 278, 446, 297]]
ANSWER: Y) If not B, then not A  

sub_title[[456, 324, 539, 342]]
## BONUS  

text[[146, 351, 851, 390]]
22) MATH Short Answer Three ordinary six-sided dice are rolled. What is the probability that the product of the numbers shown is composite?  

text[[147, 393, 315, 412]]
ANSWER: 103/108  

sub_title[[448, 458, 546, 476]]
## TOSS UP  

text[[146, 485, 850, 523]]
23) EARTH AND SPACE Multiple Choice The last ice age occurred during which of the following epochs?  

text[[158, 530, 293, 603]]
W) Eocene 
X) Miocene 
Y) Pleistocene 
Z) Holocene  

text[[147, 616, 370, 635]]
ANSWER: Y) Pleistocene  

sub_title[[456, 662, 539, 681]]
## BONUS  

text[[146, 690, 851, 745]]
23) EARTH AND SPACE Multiple Choice Which of the following is closest to the ratio of the luminosity of a main sequence star to another main sequence star with half the mass?  

text[[158, 753, 222, 825]]
W) 1.6 
X) 3 
Y) 8 
Z) 11  

text[[147, 840, 291, 858]]
ANSWER: Z) 11