
## TOSS-UP  


1) Chemistry – Short Answer The Daniell cell uses two electrodes, one made of copper and another made of what element?  


ANSWER: ZINC (ACCEPT: Zn)  


## BONUS  


1) Chemistry – Short Answer Given that a first-order reaction has a half-life of 12 seconds, how many seconds does it take for the reactants to reach one sixteenth of their initial concentration?  


ANSWER: 48  


## TOSS-UP  


2) Earth and Space – Short Answer Which moon of Saturn has the highest albedo in the Solar System?  


ANSWER: ENCELADUS  


## BONUS  


2) Earth and Space – Short Answer Asteroids are distributed unevenly in the asteroid belt. What regions of the asteroid belt contain very few asteroids due to orbital resonances with Jupiter?  


ANSWER: KIRKWOOD GAPS
## TOSS-UP  


3) Math - Short Answer What is the partial derivative with respect to \(y\) of \(7x^{3}y^{6}\) ?  


ANSWER: \(42x^{3}y^{5}\)  


## BONUS  


3) Math - Short Answer What is the population standard deviation of the set of the following 4 numbers: {6, 7, 9, 14}?  


ANSWER: SQUARE ROOT OF 38 DIVIDED BY 2  


## TOSS-UP  


4) Physics - Multiple Choice Which of the following laws was modified by Maxwell to include a term for the displacement current?  


W) Gauss' law of electricity 
X) Gauss' law of magnetism 
Y) Ampere's law 
Z) Faraday's law  


ANSWER:Y) AMPERE'S LAW  


## BONUS  


4) Physics - Short Answer Coulomb's constant can be written in the form one over the quantity four pi times what fundamental constant?  


ANSWER: PERMITTIVITY OF FREE SPACE (ACCEPT: EPSILON NAUGHT)
## TOSS-UP  


5) Energy - Short Answer Scientists at SLAC national laboratory are studying a metalloenzyme used to convert methane to methanol. What is the change in carbon's oxidation state in this reaction?  


ANSWER: \(+2\) (ACCEPT: 2)  


## BONUS  


5) Energy - Short Answer Scientists at Argonne National Lab have recently formed a 2-dimensional diamond-like structure via compression of few-layer graphene samples. Identify all of the following three statements that are true about this diamond structure: 1) It was formed via compression under 4 to 6 megapascals; 2) The material conducts electricity well; 3) The material formed has a greater hardness than the graphene substrate.  


ANSWER: 3 ONLY  


## TOSS-UP  


6) Biology - Short Answer During photosynthesis, P680 is continuously reduced and oxidized. What molecule is the source of electrons for the reduction of P680?  


ANSWER: WATER  


## BONUS  


6) Biology - Short Answer tRNAs possess an anticodon to each codon found in an mRNA molecule. Identify all of the following three statements that are true of tRNA: 1) There are more types of tRNA than codons; 2) There are more types of aminoacyl tRNA synthetases than tRNAs; 3) There are more types of anticodons than types of amino acids.  


ANSWER: 3 ONLY
## TOSS-UP  


7) Math - Short Answer What is log base 9 of the quantity 27 cubed?  


ANSWER: 4.5 (ACCEPT: 9/2)  


## BONUS  


7) Math - Short Answer Moonjay has a pile of ovals that when divided into groups of 4, there is one opal left over; when divided into groups of 5, there are 3 opals left over, and when divided into groups of 7 there are 4 left over. What is the least number of opals Moonjay could have?  


ANSWER: 53  


## TOSS-UP  


8) Physics - Short Answer Two charged particles are separated by a distance of one meter, and feel a force of attraction of F. If the distance between the particles is doubled, in terms of F, what is the new force of attraction between the particles?  


ANSWER: F/4  


## BONUS  


8) Physics - Multiple Choice Which of the following thermodynamic quantities is a path function?  


W) Internal energy 
X) Work 
Y) Entropy 
Z) Helmholtz free energy  


ANSWER: X) WORK
## TOSS-UP  


9) Biology – Short Answer Many biological molecules possess metal cofactors in order to function. While hemoglobin contains iron, chlorophyll contains a porphyrin ring that coordinates what metal?  


ANSWER: MAGNESIUM  


## BONUS  


9) Biology – Short Answer What type of survivorship curve are humans most commonly associated with?  


ANSWER: TYPE 1  


## TOSS-UP  


10) Earth and Space – Multiple Choice Which type of front is indicated on weather maps by alternating blue triangles and red semicircles pointing in opposite directions?  


W) Cold front 
X) Warm front 
Y) Stationary front 
Z) Occluded front  


ANSWER: Y) STATIONARY FRONT  


## BONUS  


10) Earth and Space – Multiple Choice Which of the following objects would have the greatest composition of iron?  


W) Comets 
X) C-Type Asteroids 
Y) S-Type Asteroids 
Z) M-Type Asteroids  


ANSWER: Z) M- TYPE ASTEROIDS
## TOSS-UP  


11) Chemistry – Short Answer What overall kinetic reaction order results in a rate constant with units equal to inverse seconds?  


ANSWER: FIRST (ACCEPT: 1)  


## BONUS  


11) Chemistry – Multiple Choice Which of the following pairs of compounds could never be mixed to create a buffer solution?  


W) Citric acid and lithium hydroxide  X) Hydrofluoric acid and potassium fluoride  Y) Carbonic acid and potassium hydroxide  Z) Hydrochloric acid and sodium hydroxide  


ANSWER: Z) HYDROCHLORIC ACID AND SODIUM HYDROXIDE  


## TOSS-UP  


12) Energy – Short Answer Researchers at Lawrence Berkeley National Lab have helped create a gamma ray detector in order to investigate nuclear fusion in stars. Gamma rays are difficult to detect because they easily pass through matter, a property called penetrating power. Identify all of the following three particles that have greater penetrating power than gamma rays: 1) Alpha particles; 2) Beta particles; 3) Neutrons.  


ANSWER: 3 ONLY  


## BONUS  


12) Energy – Short Answer Scientists at Fermilab are involved with research at the Large Hadron Collider, particularly with CMS, which is one of the two main detectors at the LHC. What is the name of the other major particle detector?  


ANSWER: ATLAS
## TOSS-UP  


13) Biology – Short Answer What type of bacteriophages can only replicate through the lytic cycle?  


ANSWER: VIRULENT  


## BONUS  


13) Biology – Short Answer Identify all of the following three animal phyla that possess a true coelom [SEE-lum]: 1) Echinoderms; 2) Rotifera; 3) Arthropoda.  


ANSWER: 1 AND 3  


## TOSS-UP  


14) Earth and Space – Short Answer Identify all of the following three quantities that are greater for population-1 stars than population-2 stars in the Milky Way: 1) Distance from the center of the galaxy; 2) Metallicity; 3) Age.  


ANSWER: 1 AND 2  


## BONUS  


14) Earth and Space – Multiple Choice Which of the following statements regarding spicules is correct?  


W) They are composed of hotter gas from the lower chromosphere  X) They are composed of hotter gas from the lower photosphere  Y) They are composed of cooler gas from the lower chromosphere  Z) They are composed of cooler gas from the lower photosphere  


ANSWER: Y) THEY ARE COMPOSED OF COOLER GAS FROM THE LOWER CHROMOSPHERE
## TOSS-UP  


15) Chemistry – Short Answer Identify all of the following three solvents that may be used to accelerate a bimolecular nucleophilic substitution reaction: 1) DMSO; 2) Water; 3) Acetone.  


ANSWER: 1 AND 3  


## BONUS  


15) Chemistry – Multiple Choice Which of the following pairs of species produces the shallowest potential well when total potential energy is plotted against their distance?  


W) Sodium ion and chloride ion  X) Hydrogen atom and hydrogen atom  Y) Water molecule and water molecule  Z) Chlorine atom and chlorine atom  


ANSWER: Y) WATER MOLECULE AND WATER MOLECULE  


## TOSS-UP  


16) Math – Short Answer A rectangular prism has a length of 4, a width of 7, and a height with value \(x\). For what value of \(x\) are the numerical values of surface area and volume equivalent?  


ANSWER: 28/3  


## BONUS  


16) Math – Short Answer What is the maximum value of \(n\) such that 200 factorial is divisible by 35 to the power of \(n\) ?  


ANSWER: 32
## TOSS-UP  


17) Energy – Short Answer Researchers at Argonne national lab are studying the optical transmittance of fluorozirconate glass films. What is the molecular geometry of the fluorozirconate anion?  


ANSWER: OCTAHEDRAL  


## BONUS  


17) Energy – Short Answer Scientists at SLAC National Accelerator Lab have been using the Linac Coherent Light Source to develop polymyxin antibiotics to target the Lipid A core of what molecules which are found in the outer membrane of bacteria?  


ANSWER: LIPOPOLYSACCHARIDES  


## TOSS-UP  


18) Physics – Short Answer Identify all of the following three statements that are true regarding momentum: 1) It is a vector; 2) It has the same units as power; 3) It is conserved for elastic collisions.  


ANSWER: 1 AND 3  


## BONUS  


18) Physics – Short Answer An block of mass 10 kilograms on a surface is being acted on by a force of 50 newtons to the right. Taking the acceleration due to gravity to be 10 meters per second squared, what is the minimum coefficient of static friction between the block and the surface for the block to remain at rest?  


ANSWER: 0.5
## TOSS-UP  


19) Biology - Short Answer Identify all of the following three tissues in a eudicot that are dead when mature: 1) Primary xylem; 2) Primary phloem; 3) Sclerenchyma.  


ANSWER: 1 AND 3  


## BONUS  


19) Biology - Short Answer Spemann's organizer is known to be a group of cells that induce the formation of neural structures in amphibians via the secretion of a mesoderm forming factor. It is an example of a group of cells influencing the development of another via proximal interactions. What general name is given to this process?  


ANSWER: INDUCTION  


## TOSS-UP  


20) Chemistry - Short Answer What is the chemical formula for the acid anhydride of nitric acid?  


ANSWER: \(\mathrm{N}_2\mathrm{O}_5\)  


## BONUS  


20) Chemistry - Short Answer While the ideal gas constant is used to calculate the entropy of macro-scale quantities of compounds, what related constant is used for micro-scale quantities?  


ANSWER: BOLTZMANN CONSTANT
## TOSS-UP  


21) Physics – Short Answer An object of mass 15 kilograms is accelerating at 2 meters per second squared. If it starts from rest, how far does it travel in 10 seconds?  


ANSWER: 100  


## BONUS  


21) Physics – Multiple Choice Which of the following quantities does not have the same units as energy?  


W) Torque  X) Work  Y) Poynting vector  Z) Lagrangian  


ANSWER: Y) POYNTING VECTOR  


## TOSS-UP  


22) Earth and Space – Multiple Choice Which of the following best describes the strength of the ionized calcium spectral line as one gets hotter?  


W) Increases in strength from class M to class A, then decreases in strength from class A to class O  


X) Increases in strength from class M to class K, then decreases in strength from class K to class A  


Y) Decreases in strength from class M to class A, then increases in strength from class A to class O  


Z) Decreases in strength from class M to class K, then increases in strength from class K to class A  


ANSWER: X) INCREASES IN STRENGTH FROM CLASS M TO CLASS K, THEN DECREASES IN STRENGTH FROM CLASS K TO CLASS A  


## BONUS  


22) Earth and Space – Short Answer Identify all of the following three statements that are true regarding oceanic crust; 1) It is more felsic than continental crust; 2) It is thinner than continental crust; 3) It is more dense than continental crust.  


ANSWER: 2 AND 3
## TOSS-UP  


23) Math - Short Answer Circle O contains points A, B, and C. Given that angle ABC measures 48 degrees, and angle BAC measures 72 degrees, what is the angle measure, in degrees, of arc AB?  


ANSWER: 120  


## BONUS  


23) Math - Short Answer In 3012, January 1st will fall on a Tuesday. On what day of the week will January 1st fall in 3024?  


ANSWER: WEDNESDAY