sub_title[[455, 143, 541, 162]]
## TOSS-UP  

text[[115, 178, 874, 250]]
1) Physics – Short Answer A car is traveling at 10 meters per second to the right and another car is traveling at 20 meters per second to the left. If both cars decelerate at a constant rate of \(-5\) meters per second squared, then what is the minimum initial distance in meters between the cars such that they do not collide?  

text[[115, 266, 226, 283]]
ANSWER: 50  

sub_title[[462, 300, 533, 319]]
## BONUS  

text[[115, 335, 882, 405]]
1) Physics – Short Answer Identify all of the following three statements that are true regarding motion in polar coordinates but NOT in Cartesian coordinates: 1) Unit vectors vary with position; 2) Unit vectors have nonzero time derivatives; 3) Unit vectors are not always orthogonal to each other.  

text[[115, 421, 282, 440]]
ANSWER: 1 AND 2  

sub_title[[455, 492, 541, 510]]
## TOSS-UP  

text[[115, 526, 864, 564]]
2) Earth and Space – Short Answer Rank the following three features of Saturn’s rings from outermost to innermost: 1) Cassini division; 2) Encke gap; 3) C ring.  

text[[115, 580, 260, 598]]
ANSWER: 2, 1, 3  

sub_title[[462, 615, 533, 633]]
## BONUS  

text[[115, 650, 848, 686]]
2) Earth and Space – Multiple Choice Which of the following ocean currents is an eastern boundary current?  

text[[115, 703, 281, 772]]
W) Kuroshio current 
X) The Gulf stream 
Y) Brazil current 
Z) Benguela current  

text[[115, 790, 436, 808]]
ANSWER: Z) BENGUELA CURRENTsub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[114, 127, 877, 181]]
3) Chemistry – Short Answer A photoelectron spectrum of an unknown element displays only three peaks, all of which have the same amplitude. What element is most likely being investigated?  

text[[115, 198, 291, 215]]
ANSWER: CARBON  

sub_title[[462, 233, 533, 251]]
## BONUS  

text[[114, 268, 812, 321]]
3) Chemistry – Multiple Choice Treating a primary alcohol with two equivalents of pyridinium chlorochromate yields which of the following functional groups as the major product?  

text[[114, 339, 268, 409]]
W) Ester  X) Carboxylic acid  Y) Aldehyde  Z) Ketone  

text[[115, 426, 343, 445]]
ANSWER: Y) ALDEHYDE  

sub_title[[456, 497, 540, 515]]
## TOSS-UP  

text[[115, 532, 797, 568]]
4) Biology – Short Answer Identify all of the following three diseases that exhibit a heterozygote advantage: 1) Malaria; 2) Cystic fibrosis; 3) Tay-Sachs.  

text[[115, 584, 283, 601]]
ANSWER: 1 AND 2  

sub_title[[462, 620, 533, 637]]
## BONUS  

text[[115, 654, 866, 708]]
4) Biology – Short Answer John observes anheridia and archegonia in a certain plant he found outside his house. Identify all of the following three statements that are likely true of this plant: 1) Most of its cells are diploid; 2) It is a gymnosperm; 3) It possesses sporangia.  

text[[115, 724, 265, 741]]
ANSWER: NONEsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[114, 127, 879, 182]]
5) Energy - Short Answer Scientists at SLAC national laboratory are studying synchrotron radiation produced in insertion devices containing repeating arrays of magnets. What is the name given to these arrays of magnets?  

text[[115, 198, 331, 215]]
ANSWER: UNDULATOR  

sub_title[[462, 233, 533, 251]]
## BONUS  

text[[115, 267, 864, 322]]
5) Energy - Short Answer Researchers at Lawrence Livermore National Lab are developing electrochemical reactors using 3D printing to convert carbon dioxide into useful fuels such as ethene. In this reaction, how many moles of electrons are transferred per mole of ethene?  

text[[115, 338, 230, 356]]
ANSWER: 12  

sub_title[[456, 408, 541, 426]]
## TOSS-UP  

text[[115, 443, 857, 496]]
6) Math - Short Answer The point with coordinates \((7, -2)\) is reflected across the \(y\) -axis, translated 3 units upward, and then reflected across the line \(y = x\) . What are the coordinates of the new point?  

text[[115, 513, 263, 532]]
ANSWER: (1, - 7)  

sub_title[[462, 548, 533, 566]]
## BONUS  

text[[115, 583, 881, 619]]
6) Math - Short Answer How many pythagorean triples, with numbers all less than or equal to 30, contain at least 1 prime number?  

text[[115, 635, 220, 653]]
ANSWER: 5sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[114, 127, 880, 199]]
7) Energy – Multiple Choice Scientists at Argonne National Lab are developing new thin-film technologies for applications in photovoltaic cells. They are attempting to surpass the maximum efficiency for a single p-n junction, which is known as the Shockley-Queisser limit. Which of the following values is closest to this limit?  

text[[114, 216, 183, 286]]
W) \(15\%\) X) \(30\%\) Y) \(45\%\) Z) \(60\%\)  

text[[115, 305, 271, 322]]
ANSWER: X) \(30\%\)  

sub_title[[463, 340, 533, 358]]
## BONUS  

text[[115, 374, 868, 427]]
7) Energy – Short Answer Scientists at the Linac Coherent Light Source are observing X-ray scattering by compressing what group 8 metal with laser-driven shocks to earth-core-like pressures?  

text[[115, 444, 258, 461]]
ANSWER: IRON  

sub_title[[456, 515, 540, 533]]
## TOSS-UP  

text[[115, 549, 863, 602]]
8) Biology – Short Answer Identify all of the following three observations that would be indicative of a K-selected species: 1) Densely populated environment; 2) Type III survivorship curve; 3) Iteroparous.  

text[[115, 619, 248, 636]]
ANSWER: ALL  

sub_title[[463, 654, 533, 672]]
## BONUS  

text[[115, 689, 875, 724]]
8) Biology – Short Answer Identify all of the following three cells that express MHC Class I: 1) Erythrocyte; 2) Dendritic cell; 3) B cell.  

text[[115, 741, 282, 758]]
ANSWER: 2 AND 3sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[113, 127, 870, 164]]
9) Chemistry – Short Answer Identify all of the following three alkene reactions that proceed via an anti addition: 1) Hydrogenation; 2) Hydroboration-oxidation; 3) Bromination.  

text[[115, 181, 279, 199]]
ANSWER: 3 ONLY  

sub_title[[463, 215, 533, 234]]
## BONUS  

text[[115, 250, 879, 304]]
9) Chemistry – Short Answer Rank the following three solutions in terms of increasing percentage deprotonation: 1) 1-molar hydrofluoric acid; 2) 2-molar hydrofluoric acid; 3) 1-molar hydrocyanic acid.  

text[[115, 321, 258, 339]]
ANSWER: 3, 2, 1  

sub_title[[456, 390, 540, 408]]
## TOSS-UP  

text[[115, 425, 882, 479]]
10) Physics – Short Answer A particle's position can be described by the parametric equations \(x(t) = 4\cos (3t)\) and \(y(t) = 4\sin (3t)\) . What is the magnitude of the particle's centripetal acceleration?  

text[[115, 495, 226, 512]]
ANSWER: 36  

sub_title[[463, 530, 533, 548]]
## BONUS  

text[[115, 565, 879, 618]]
10) Physics – Short Answer A battery with an emf of 6 volts is connected to a lightbulb of variable resistance and a resistor of 3 ohms in parallel. In watts, what is the maximum power that can be dissipated across the circuit?  

text[[115, 635, 225, 652]]
ANSWER: 24sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 850, 164]]
11) Earth and Space – Short Answer Identify all of the following three features that can be found in reverse faults: 1) Fault block mountains; 2) Horsts; 3) Joints.  

text[[115, 180, 265, 198]]
ANSWER: NONE  

sub_title[[462, 215, 533, 233]]
## BONUS  

text[[115, 250, 839, 287]]
11) Earth and Space – Multiple Choice At which of the following latitudes is the oceanic pycnocline the least well developed?  

text[[115, 304, 275, 374]]
W) 0 degrees north  X) 30 degrees north  Y) 60 degrees north  Z) 90 degrees north  

text[[115, 390, 420, 409]]
ANSWER: Z) 90 DEGREES NORTH  

sub_title[[456, 460, 541, 479]]
## TOSS-UP  

text[[115, 495, 864, 532]]
12) Math – Short Answer Identify all of the following three points that would lie outside the sphere with equation \(x^{2} + y^{2} + z^{2} = 202: 1) (1, 10, 10); 2) (13, 9, 4); 3) (5, 11, 8).\)  

text[[115, 548, 282, 565]]
ANSWER: 2 AND 3  

sub_title[[462, 583, 533, 601]]
## BONUS  

text[[115, 617, 872, 672]]
12) Math – Multiple Choice Which of the following best describes the polar graph with equation \(r\) squared equals the fraction with numerator 2 and denominator 9 sine squared of theta plus 4 cosine squared of theta?  

text[[115, 688, 303, 758]]
W) A line  X) An ellipse  Y) A parabola  Z) A vertical hyperbola  

text[[115, 775, 346, 793]]
ANSWER: X) AN ELLIPSEsub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 813, 181]]
13) Energy – Multiple Choice Scientists at SLAC National Accelerator Lab are using resonance inelastic X-ray scattering, or RIXS, in pump-probe experiments. Which of the following cannot be observed using RIXS?  

text[[114, 198, 371, 270]]
W) Thomson scattering 
X) Electron-phonon interactions 
Y) Charge excitations 
Z) Compton scattering  

text[[114, 286, 464, 304]]
ANSWER: W) THOMSON SCATTERING  

sub_title[[460, 322, 533, 340]]
## BONUS  

text[[115, 356, 881, 428]]
13) Energy – Short Answer Scientists at Argonne National Lab are searching for new materials to serve as catalysts for bulky organic molecules. One example of such materials are zeolites. Identify all of the following three statements that are true regarding zeolites: 1) They are a type of ceramic; 2) They are acidic; 3) They exhibit hexagonal geometry.  

text[[115, 444, 279, 462]]
ANSWER: 2 ONLY  

sub_title[[456, 514, 540, 532]]
## TOSS-UP  

text[[115, 548, 881, 585]]
14) Earth and Space – Short Answer Identify all of the following three rocks and minerals that are likely to form karst topography: 1) Dolostone; 2) Gypsum; 3) Hornblende.  

text[[115, 601, 283, 619]]
ANSWER: 1 AND 2  

sub_title[[460, 637, 533, 655]]
## BONUS  

text[[115, 671, 870, 708]]
14) Earth and Space – Short Answer Rank the following three regions of the solar system in terms of increasing distance from the sun: 1) Termination shock; 2) Heliosheath; 3) Heliopause.  

text[[115, 724, 260, 742]]
ANSWER: 1, 2, 3sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 881, 181]]
15) Chemistry - Short Answer Identify all of the following three changes that would increase the solubility of calcium fluoride in water: 1) Increasing temperature; 2) Adding sodium fluoride; 3) Adding hydrochloric acid.  

text[[115, 198, 282, 215]]
ANSWER: 1 AND 3  

sub_title[[462, 233, 533, 251]]
## BONUS  

text[[115, 268, 874, 321]]
15) Chemistry - Short Answer A given reaction has a standard Gibbs free energy change of \(-8.3\) kilojoules per mole at 1000 kelvins. To one decimal place, what is the equilibrium constant for this reaction?  

text[[115, 338, 234, 356]]
ANSWER: 2.7  

sub_title[[456, 408, 540, 426]]
## TOSS-UP  

text[[115, 443, 850, 479]]
16) Biology - Short Answer Order the following three phyla of animals from most to least basal: 1) Porifera; 2) Nematoda; 3) Platyhelminthes.  

text[[115, 496, 260, 513]]
ANSWER: 1, 3, 2  

sub_title[[462, 531, 533, 549]]
## BONUS  

text[[115, 565, 879, 637]]
16) Biology - Short Answer A population is initially in Hardy-Weinberg equilibrium with 1000 individuals possessing allele frequencies of \(\mathrm{q} = 0.6\) and \(\mathrm{p} = 0.4\) . A freak accident kills \(50\%\) of the individuals possessing both \(\mathrm{q}\) alleles. If the next generation regains Hardy-Weinberg frequencies, what proportion of them will be heterozygous?  

text[[115, 654, 255, 671]]
ANSWER: 24/49sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 849, 181]]
17) Math - Short Answer A sequence is given by having first term 3, and each subsequent term is equivalent to 4 times the previous term plus 14. How many of the first 20 terms are divisible by 7?  

text[[115, 198, 220, 215]]
ANSWER: 0  

sub_title[[462, 233, 533, 252]]
## BONUS  

text[[115, 268, 852, 305]]
17) Math - Short Answer A dodecahedron is randomly painted red on two of its faces, and green on every other face. What is the probability that the two red faces are adjacent?  

text[[115, 321, 245, 339]]
ANSWER: 5/11  

sub_title[[456, 391, 541, 409]]
## TOSS-UP  

text[[115, 425, 867, 462]]
18) Physics - Short Answer A refrigerator has a coefficient of performance of 2. What is the efficiency of its corresponding heat engine?  

text[[115, 478, 370, 496]]
ANSWER: 1/3 (ACCEPT: \(33\%\) )  

sub_title[[462, 513, 533, 531]]
## BONUS  

text[[115, 548, 874, 602]]
18) Physics - Short Answer Five objects of masses 1, 2, 3, 4, and 5 kilograms are placed 1, 2, 3, 4, and 5 meters from the origin, respectively, in the positive \(x\) direction. How far away from the origin is the center of mass of the system?  

text[[115, 618, 245, 636]]
ANSWER: 11/3sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 881, 181]]
19) Biology - Short Answer Identify all of the following three groups of cytoskeletal elements that are mainly responsible for bearing tension: 1) Microfilaments; 2) Microtubules; 3) Intermediate filaments.  

text[[115, 198, 282, 215]]
ANSWER: 1 AND 3  

sub_title[[462, 233, 533, 251]]
## BONUS  

text[[115, 268, 857, 321]]
19) Biology - Short Answer A tree that is experiencing extensive secondary growth cannot exchange gases through stomata. Instead, it exchanges air through which raised areas of the periderm?  

text[[115, 338, 315, 355]]
ANSWER: LENTICELS  

sub_title[[456, 408, 540, 426]]
## TOSS-UP  

text[[115, 443, 881, 479]]
20) Chemistry - Short Answer Rank the following three dilute solutions in terms of increasing van't Hoff factor: 1) Sodium chloride; 2) Calcium chloride; 3) Calcium fluoride.  

text[[115, 496, 259, 513]]
ANSWER: 3, 1, 2  

sub_title[[462, 531, 533, 549]]
## BONUS  

text[[115, 565, 872, 618]]
20) Chemistry - Short Answer It is observed that more substituted alkenes are more stable. A common explanation for this is that the empty pi star orbital on the alkene interacts with neighboring filled C—H sigma bonds. What is the term for this phenomenon?  

text[[115, 635, 728, 654]]
ANSWER: HYPERCONJUGATION (ACCEPT: SIGMA CONJUGATION)sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[114, 127, 872, 181]]
21) Math - Multiple Choice Which of the following best describes the graph of the complex equation: the absolute value of the quantity \(z - 2i\) equals the absolute value of the quantity \(z + 4\), when plotted in the complex plane?  

text[[114, 198, 225, 270]]
W) A circle 
X) An ellipse 
Y) A line 
Z) A point  

text[[115, 286, 300, 304]]
ANSWER: Y) A LINE  

sub_title[[462, 321, 533, 339]]
## BONUS  

text[[114, 355, 864, 391]]
21) Math - Short Answer An equiangular hexagon has sides of lengths 2, 6, 2, 6, 2 and 6, in that order. What is the area of the hexagon?  

text[[114, 407, 524, 425]]
ANSWER: 22 TIMES THE SQUARE ROOT OF 3  

sub_title[[456, 479, 541, 496]]
## TOSS-UP  

text[[114, 512, 879, 566]]
22) Earth and Space - Short Answer Identify all of the following three statements regarding the Maunder Minimum that are correct: 1) During solar eclipses, the corona was not visible; 2) It correlated with the Little Ice Age; 3) It resulted in a decrease in the solar constant.  

text[[115, 583, 248, 600]]
ANSWER: ALL  

sub_title[[462, 618, 533, 636]]
## BONUS  

text[[115, 653, 870, 707]]
22) Earth and Space - Short Answer For most stars, the mass luminosity relationship states that luminosity is proportional to mass to the 3.5th power. However, as the mass approaches the Eddington limit, which value does the exponential factor approach?  

text[[115, 723, 219, 740]]
ANSWER: 1sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[114, 127, 875, 181]]
23) Physics – Multiple Choice A series RLC circuit has a resistance of 3 ohms, a capacitor of capacitance 10 farads and an inductor of inductance 10 henrys. In hertz, which of the following is the frequency of oscillation of the circuit at resonance?  

text[[114, 198, 170, 268]]
W) 1  X) 0.5  Y) 0.3  Z) 0.1  

text[[115, 285, 251, 302]]
ANSWER: Z) 0.1  

sub_title[[463, 319, 533, 337]]
## BONUS  

text[[114, 354, 880, 424]]
23) Physics – Multiple Choice A block has a mass of 5 kilograms and an initial momentum of 20 kilogram meters per second, sliding on a surface with friction. Assuming the acceleration due to gravity is 10 meters per second and if the block slows to a stop over 10 meters, what is the coefficient of kinetic friction?  

text[[114, 441, 182, 510]]
W) 0.04  X) 0.08  Y) 0.16  Z) 0.2  

text[[115, 528, 264, 545]]
ANSWER: X) 0.08