sub_title[[456, 142, 541, 161]]
## TOSS-UP  

text[[115, 177, 826, 216]]
1) Physics – Short Answer Identify all of the following three quantities that are vectors: 
1) Speed; 
2) Displacement; 
3) Work.  

text[[115, 229, 280, 248]]
ANSWER: 2 ONLY  

sub_title[[462, 265, 533, 284]]
## BONUS  

text[[115, 300, 872, 338]]
1) Physics – Multiple Choice Which of the following principles in fluid mechanics is a direct consequence of the conservation of energy?  

text[[114, 352, 312, 424]]
W) Pascal's principle 
X) Archimedes principle 
Y) Bernoulli's principle 
Z) Amonton's principle  

text[[115, 439, 468, 459]]
ANSWER: Y) BERNOULLI'S PRINCIPLE  

sub_title[[456, 509, 541, 528]]
## TOSS-UP  

text[[114, 543, 880, 581]]
2) Biology – Short Answer In the alternation of generations model of plants, which generation possesses gametangia?  

text[[115, 595, 358, 614]]
ANSWER: GAMETOPHYTE  

sub_title[[462, 631, 533, 650]]
## BONUS  

text[[115, 666, 876, 720]]
2) Biology – Short Answer Identify all of the following three events that occur in prophase of a human cell: 1) The nuclear membrane dissolves; 2) The chromosomes condense; 3) The chromatids separate.  

text[[115, 735, 280, 753]]
ANSWER: 2 ONLYsub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[114, 127, 840, 164]]
3) Earth and Space – Short Answer Rank the following three types of magma in terms of increasing volatility: 1) Andesitic; 2) Rhyolitic; 3) Basaltic.  

text[[115, 180, 260, 198]]
ANSWER: 3, 1, 2  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 250, 825, 286]]
3) Earth and Space – Short Answer Tornadoes often tend to develop from what class of thunderstorms, which contain a region of rotation called a mesocyclone?  

text[[115, 302, 332, 320]]
ANSWER: SUPERCELS  

sub_title[[456, 372, 540, 390]]
## TOSS-UP  

text[[115, 407, 828, 443]]
4) Chemistry – Short Answer Identify all of the following three quantities which can be measured in units of joules: 1) Electron affinity; 2) Ionization energy; 3) Work function.  

text[[115, 459, 247, 477]]
ANSWER: ALL  

sub_title[[463, 494, 533, 512]]
## BONUS  

text[[115, 529, 866, 583]]
4) Chemistry – Short Answer A reversible isothermal expansion is performed with one mole of an ideal gas at a temperature of 300 kelvins. If the container expands from 1 liter to 3 liters during the process, how much work, to one significant figure and in joules, is done by the gas?  

text[[115, 598, 250, 616]]
ANSWER: 3000sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[114, 127, 881, 181]]
5) Energy – Short Answer Scientists at SLAC national laboratory are using energetic beams in high-intensity short-pulse lasers. These beams typically consist of what positively charged particle found in the nucleus?  

text[[115, 198, 288, 215]]
ANSWER: PROTON  

sub_title[[462, 232, 533, 250]]
## BONUS  

text[[114, 267, 881, 321]]
5) Energy – Short Answer Researchers at Los Alamos National Lab have created arrays of nanomagnets to observe mobile quasiparticles that act like magnetic monopoles. Actual magnetic monopoles are famously forbidden by what law?  

text[[112, 336, 827, 356]]
ANSWER: GAUSS'S LAW FOR MAGNETISM (DO NOT ACCEPT: GAUSS'S LAW)  

sub_title[[456, 407, 540, 425]]
## TOSS-UP  

text[[113, 441, 690, 461]]
6) Math – Multiple Choice Which of the following numbers is prime?  

text[[114, 477, 176, 546]]
W) 251 X) 253 Y) 255 Z) 261  

text[[115, 563, 268, 581]]
ANSWER: W) 251  

sub_title[[462, 598, 533, 616]]
## BONUS  

text[[113, 632, 875, 668]]
6) Math – Short Answer What is the integral from negative 30 to 30 of the absolute value of \(x\) \(dx\) ?  

text[[115, 685, 241, 703]]
ANSWER: 900sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 832, 163]]
7) Earth and Space – Multiple Choice Which of the following seismic waves travels the fastest through Earth?  

text[[115, 181, 272, 250]]
W) Rayleigh waves 
X) Love waves 
Y) P waves 
Z) S waves  

text[[115, 268, 322, 286]]
ANSWER: Y) P WAVES  

sub_title[[462, 303, 533, 320]]
## BONUS  

text[[115, 337, 847, 373]]
7) Earth and Space – Short Answer In our Sun, the photons produced in the proton-proton chain all belong to what portion of the electromagnetic spectrum?  

text[[115, 389, 335, 406]]
ANSWER: GAMMA RAY  

sub_title[[456, 460, 541, 477]]
## TOSS-UP  

text[[115, 494, 746, 512]]
8) Math – Short Answer What is the decimal number 52 expressed in base 7?  

text[[115, 529, 240, 546]]
ANSWER: 103  

sub_title[[462, 564, 533, 581]]
## BONUS  

text[[115, 598, 878, 634]]
8) Math – Short Answer What is the distance between two parallel lines with slope 1 and with \(y\) -intercepts of 11 and 19?  

text[[115, 650, 514, 668]]
ANSWER: 4 TIMES THE SQUARE ROOT OF 2sub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[113, 127, 857, 163]]
9) Biology – Short Answer Glycogen is predominantly stored in which organ of the human body?  

text[[115, 180, 268, 198]]
ANSWER: LIVER  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 250, 872, 303]]
9) Biology – Short Answer The mitochondrial membrane possesses specialized proteins bearing iron containing heme groups involved in electron transport. What general name is given to these proteins?  

text[[115, 319, 360, 337]]
ANSWER: CYTOCHROMES  

sub_title[[456, 389, 540, 407]]
## TOSS-UP  

text[[115, 423, 833, 460]]
10) Physics – Short Answer Identify all of the following three particles that are charged: 1) Neutrino; 2) Positron; 3) Electron.  

text[[115, 476, 275, 494]]
ANSWER: 2 AND 3  

sub_title[[463, 511, 533, 529]]
## BONUS  

text[[115, 545, 879, 599]]
10) Physics – Short Answer A ball is thrown upwards at a speed of 10 meters per second. Assuming the acceleration due to gravity equals 10 meters per second squared, in meters, what is the height of the ball at its highest point?  

text[[115, 614, 220, 632]]
ANSWER: 5sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 802, 163]]
11) Chemistry – Short Answer Rank the following three gaseous species in terms of increasing rate of effusion: 1) Neon; 2) Fluorine; 3) Chlorine.  

text[[115, 180, 258, 198]]
ANSWER: 3, 2, 1  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 250, 857, 286]]
11) Chemistry – Multiple Choice Which of the following is the highest occupied molecular orbital of the homonuclear diatomic \(\mathrm{N}_{2}^{-}\) ion?  

text[[115, 303, 252, 374]]
W) Sigma 2p 
X) Pi 2p 
Y) Sigma star 2p 
Z) Pi star 2p  

text[[115, 390, 333, 408]]
ANSWER: Z) PI STAR 2P  

sub_title[[456, 460, 541, 478]]
## TOSS-UP  

text[[115, 494, 860, 530]]
12) Math – Short Answer Two fair six-sided dice are rolled. What is the probability that the product of the rolls is less than 3?  

text[[115, 546, 246, 564]]
ANSWER: 1/12  

sub_title[[463, 581, 533, 599]]
## BONUS  

text[[115, 615, 837, 635]]
12) Math – Short Answer What is the area of a triangle with sides of length 7, 8, and 11?  

text[[115, 650, 535, 669]]
ANSWER: 2 TIMES THE SQUARE ROOT OF 195sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 842, 164]]
13) Earth and Space – Short Answer The path of an object that is traveling faster than the escape velocity of a planet will form what conic section while escaping its gravity?  

text[[115, 180, 328, 198]]
ANSWER: HYPERBOLA  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 250, 866, 287]]
13) Earth and Space – Short Answer Rank the following 3 rocks in order of increasing silica content: 1) Rhyolite; 2) Gabbro; 3) Peridotite.  

text[[115, 303, 258, 320]]
ANSWER: 3, 2, 1  

sub_title[[456, 372, 541, 390]]
## TOSS-UP  

text[[115, 407, 872, 461]]
14) Energy – Short Answer Argonne National Lab scientists are studying the potential benefits of alcohols as blendstocks for internal combustion engines. Identify all of the following three molecules that are secondary alcohols: 1) Isobutanol; 2) Isopropanol; 3) 2-butanol.  

text[[115, 477, 281, 495]]
ANSWER: 2 AND 3  

sub_title[[463, 512, 533, 530]]
## BONUS  

text[[115, 547, 866, 583]]
14) Energy – Short Answer Scientists at Fermilab have been studying the 21 centimeter line, an emission line produced by the neutral form of what element?  

text[[115, 599, 320, 617]]
ANSWER: HYDROGENsub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[114, 127, 820, 163]]
15) Physics – Multiple Choice The equilibrium of a system of free charges can be best described as which of the following?  

text[[114, 181, 222, 250]]
W) Stable 
X) Unstable 
Y) Static 
Z) Rotational  

text[[115, 268, 339, 286]]
ANSWER: X) UNSTABLE  

sub_title[[462, 303, 533, 321]]
## BONUS  

text[[115, 338, 806, 392]]
15) Physics – Short Answer Rank the following three particles in terms of increasing DeBroglie [de-BROY] wavelength, assuming they are all traveling at the same speed: 1) Alpha particle; 2) Beta particle; 3) Neutrino.  

text[[115, 408, 260, 425]]
ANSWER: 1, 2, 3  

sub_title[[456, 478, 540, 495]]
## TOSS-UP  

text[[115, 512, 815, 548]]
16) Biology – Short Answer The suprachiasmatic nucleus is a group of neurons in the hypothalamus that is responsible for the regulation of what 24-hour-long cycles?  

text[[115, 564, 421, 582]]
ANSWER: CIRCADIAN RHYTHMS  

sub_title[[462, 600, 533, 618]]
## BONUS  

text[[115, 635, 824, 671]]
16) Biology – Multiple Choice The Meselson-Stahl experiment supported which of the following models of DNA replication?  

text[[115, 688, 283, 758]]
W) Conservative 
X) Integrative 
Y) Semiconservative 
Z) Dispersive  

text[[115, 775, 434, 793]]
ANSWER: Y) SEMICONSERVATIVEsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 126, 727, 146]]
17) Chemistry - Short Answer What is the molecular geometry of XeOF \(_2\) ?  

text[[115, 162, 305, 181]]
ANSWER: T-SHAPED  

sub_title[[462, 199, 533, 217]]
## BONUS  

text[[115, 233, 872, 270]]
17) Chemistry - Multiple Choice How many chiral centers can be found in the product of the reaction of 2-methylpropene with bromine?  

text[[115, 286, 158, 357]]
W) 0 X) 1 Y) 2 Z) 3  

text[[115, 375, 251, 393]]
ANSWER: W) 0  

sub_title[[456, 445, 541, 463]]
## TOSS-UP  

text[[115, 479, 872, 534]]
18) Math - Short Answer Identify all of the following three functions that are invertible over the real numbers: 1) The quantity \(x\) minus 4 to the sixth power; 2) Secant of \(x\); 3) The cube root of the quantity \(x + 1\).  

text[[115, 549, 280, 567]]
ANSWER: 3 ONLY  

sub_title[[462, 586, 533, 603]]
## BONUS  

text[[115, 619, 739, 639]]
18) Math - Short Answer How many digits does 2 to the 120th power have?  

text[[115, 655, 230, 673]]
ANSWER: 37sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 871, 181]]
19) Energy - Short Answer Scientists at SLAC National Accelerator Lab have been studying a new way to oxidize methane into methanol in an attempt to reduce methane emissions. They used crystals of what microporous aluminosilicates as a catalyst?  

text[[115, 198, 301, 215]]
ANSWER: ZEOLITES  

sub_title[[462, 233, 533, 251]]
## BONUS  

text[[115, 268, 880, 338]]
19) Energy - Short Answer Scientists at Lawrence Livermore National Lab have been using machine learning models to simulate climate change in the next hundred years. Identify all of the following three gases that are considered greenhouse gases: 1) Water; 2) Nitrous oxide; 3) Ozone.  

text[[115, 355, 247, 372]]
ANSWER: ALL  

sub_title[[456, 425, 540, 443]]
## TOSS-UP  

text[[115, 460, 855, 496]]
20) Chemistry - Short Answer Rank the following three 1-molar acid solutions in terms of increasing pH: 1) Sulfuric; 2) Hydrofluoric; 3) Hydrocyanic.  

text[[115, 513, 259, 530]]
ANSWER: 1, 2, 3  

sub_title[[462, 549, 533, 567]]
## BONUS  

text[[115, 584, 866, 620]]
20) Chemistry - Short Answer Identify all of the following three elements that can be added to silicon to create an n-type semiconductor: 1) Boron; 2) Germanium; 3) Arsenic.  

text[[115, 637, 280, 654]]
ANSWER: 3 ONLYsub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[115, 127, 833, 164]]
21) Biology – Short Answer C4 and CAM plants contain adaptations that allow for improved carbon fixation in arid environments by limiting the occurrence of what process?  

text[[115, 180, 404, 199]]
ANSWER: PHOTORESPIRATION  

sub_title[[463, 216, 533, 234]]
## BONUS  

text[[115, 250, 843, 321]]
21) Biology – Multiple Choice In a certain ecosystem, the buzzlao, a certain type of bee, makes up a small part of the population. However, when the buzzlao is removed from the population, the biodiversity of the population greatly decreases. Which of the following best describes the species buzzlao?  

text[[115, 338, 285, 410]]
W) Founding species 
X) Ring species 
Y) Apex predator 
Z) Keystone species  

text[[115, 425, 419, 444]]
ANSWER: Z) KEYSTONE SPECIES  

sub_title[[456, 497, 540, 515]]
## TOSS-UP  

text[[115, 531, 870, 585]]
22) Physics – Short Answer An infinite conducting sheet has a uniform charge density. If a particle is moved from a distance 1 meter to a distance 2 meters from the sheet, what is the ratio of the initial force experienced by the particle to the final force?  

text[[115, 600, 215, 617]]
ANSWER: 1  

sub_title[[463, 635, 533, 653]]
## BONUS  

text[[115, 670, 822, 706]]
22) Physics – Multiple Choice A proton can decay into a neutral pion and which of the following particles?  

text[[115, 723, 243, 794]]
W) Positron 
X) Electron 
Y) Antineutrino 
Z) Top Quark  

text[[115, 811, 336, 829]]
ANSWER: W) POSITRONsub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[114, 127, 850, 164]]
23) Earth and Space – Short Answer Kowalski's and Halley's comets are both objects that originate from what region of the solar system?  

text[[116, 180, 335, 199]]
ANSWER: KUIPER BELT  

sub_title[[463, 216, 533, 234]]
## BONUS  

text[[114, 250, 844, 287]]
23) Earth and Space – Short Answer Identify all of the following three types of faults that form from compressional forces: 1) Normal; 2) Thrust; 3) Strike-slip.  

text[[116, 303, 279, 321]]
ANSWER: 2 ONLY