sub_title[[456, 143, 541, 162]]
## TOSS-UP  

text[[115, 178, 870, 232]]
1) Energy – Short Answer Argonne national lab scientists have used computational methods to discover the material with chemical formula \(\mathrm{MoBi_2}\) . Normally, when bismuth is incorporated into compounds, it is in what oxidation state?  

text[[115, 248, 429, 267]]
ANSWER: \(+3\) (DO NOT ACCEPT: 3)  

sub_title[[462, 283, 533, 302]]
## BONUS  

text[[115, 318, 866, 372]]
1) Energy – Short Answer Researchers at Argonne national lab are looking into methods of making sodium-ion batteries more cost-efficient by finding low-cost anode materials. One such anode they are looking at is one made of what kinetically favored isotope of phosphorus?  

text[[115, 387, 382, 405]]
ANSWER: RED PHOSPHORUS  

sub_title[[456, 459, 541, 477]]
## TOSS-UP  

text[[115, 494, 880, 529]]
2) Math – Short Answer An equilateral triangle is inscribed inside a circle of radius 2. What is the area of the triangle?  

text[[115, 545, 514, 564]]
ANSWER: 3 TIMES THE SQUARE ROOT OF 3  

sub_title[[462, 581, 533, 599]]
## BONUS  

text[[115, 615, 857, 652]]
2) Math – Short Answer What is the smallest positive integer that is evenly divisible by the first 6 perfect squares?  

text[[115, 668, 251, 686]]
ANSWER: 3600sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[113, 127, 857, 163]]
3) Earth and Space – Short Answer How many planes of cleavage does the mineral fluorite have?  

text[[115, 181, 221, 198]]
ANSWER: 4  

sub_title[[463, 216, 534, 234]]
## BONUS  

text[[113, 250, 879, 287]]
3) Earth and Space – Multiple Choice Which of the following best describes the path taken by a star on the HR diagram after entering the zero-age main sequence?  

text[[115, 303, 315, 375]]
W) Up and to the right  X) Up and to the left  Y) Down and to the right  Z) Down and to the left  

text[[115, 391, 451, 409]]
ANSWER: W) UP AND TO THE RIGHT  

sub_title[[456, 460, 541, 479]]
## TOSS-UP  

text[[115, 495, 866, 549]]
4) Physics – Short Answer A 10-kilogram block is resting on an inclined plane which makes an angle of 45 degrees with respect to the horizontal. In newtons, what is the maximum static friction force that the plane exerts on the block.  

text[[115, 564, 525, 583]]
ANSWER: 49 TIMES THE SQUARE ROOT OF 2  

sub_title[[463, 600, 533, 618]]
## BONUS  

text[[115, 634, 861, 671]]
4) Physics – Multiple Choice A ball is dropped from a plane and slowly reaches its terminal velocity. Which of the following best describes the total power delivered to the ball as it falls?  

text[[115, 688, 336, 758]]
W) Increases  X) Decreases  Y) Increases then decreases  Z) Decreases then increases  

text[[115, 776, 517, 794]]
ANSWER: Y) INCREASES THEN DECREASESsub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[114, 127, 864, 181]]
5) Energy – Short Answer Researchers at Argonne National Lab are studying the kinetics of hydride transfer to carbon dioxide molecules. When one hydride ion is transferred to a carbon dioxide molecule, what anion is formed?  

text[[115, 198, 303, 214]]
ANSWER: FORMATE  

sub_title[[462, 233, 533, 251]]
## BONUS  

text[[115, 268, 850, 321]]
5) Energy – Short Answer Researchers at Argonne National Lab are studying the rock-salt type of a lithium-ion cathode that improves performance and energy density through the maximization of what state function?  

text[[115, 338, 300, 355]]
ANSWER: ENTROPY  

sub_title[[456, 407, 540, 425]]
## TOSS-UP  

text[[115, 443, 864, 496]]
6) Chemistry – Multiple Choice A small sample of phenol is dissolved in a 1-molar solution of sodium hydroxide. Which of the following is closest to the percent of phenol molecules that are deprotonated after the reaction is allowed to reach equilibrium?  

text[[115, 513, 171, 584]]
W) 0 X) 25 Y) 75 Z) 100  

text[[115, 601, 264, 618]]
ANSWER: Z) 100  

sub_title[[462, 636, 533, 654]]
## BONUS  

text[[115, 671, 872, 707]]
6) Chemistry – Multiple Choice The energy levels in the boron \(4+\) ion differ from differ from those of hydrogen by what factor?  

text[[115, 725, 163, 794]]
W) 4 X) 5 Y) 16 Z) 25  

text[[115, 812, 253, 829]]
ANSWER: Z) 25sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[113, 127, 836, 164]]
7) Math - Short Answer What is the centroid of a triangle with vertices in the coordinate plane of (0, 2), (3, 4), and (3, 6)?  

text[[115, 180, 254, 199]]
ANSWER: (2, 4)  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 250, 825, 287]]
7) Math - Short Answer What is the shortest distance between the circle defined by the equation \(x^{2} + 8x + y^{2} - 2y = 32\) and the line \(3x - 4y = 69\) ?  

text[[115, 303, 231, 321]]
ANSWER: 10  

sub_title[[456, 372, 541, 390]]
## TOSS-UP  

text[[115, 407, 858, 444]]
8) Earth and Space - Short Answer The helium flash occurs due to the instability generated from the degeneracy of what particles?  

text[[115, 459, 325, 478]]
ANSWER: ELECTRONS  

sub_title[[463, 495, 533, 513]]
## BONUS  

text[[115, 530, 825, 566]]
8) Earth and Space - Short Answer Along with the Bergeron process, what other major process is responsible for precipitation?  

text[[115, 582, 461, 600]]
ANSWER: COLLISION- COALESCENCEsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[113, 127, 872, 164]]
9) Chemistry – Multiple Choice A scientist seeks to compare the bond strengths of carbon with various hydrogen isotopes. Which of the following lab methods is best for this application?  

text[[114, 181, 337, 252]]
W) NMR spectroscopy 
X) IR spectroscopy 
Y) UV-Vis spectroscopy 
Z) Microwave spectroscopy  

text[[114, 269, 410, 287]]
ANSWER: X) IR SPECTROSCOPY  

sub_title[[462, 304, 533, 322]]
## BONUS  

text[[114, 339, 852, 392]]
9) Chemistry – Short Answer One of the main forms of industrial production for isopropyl alcohol is the reaction of 2-propene with dilute sulfuric acid in water. What role does the acid play in this reaction?  

text[[114, 408, 706, 428]]
ANSWER: CATALYST (DO NOT ACCEPT: REACTANT; REAGENT)  

sub_title[[456, 480, 541, 498]]
## TOSS-UP  

text[[115, 514, 857, 567]]
10) Physics – Short Answer A 5-kilogram block is moving with a velocity of 20 meters per second to the right when it hits a wall and bounces off with a final velocity of 10 meters per second to the left. In joules, how much net work is done on the block during this collision?  

text[[115, 584, 250, 601]]
ANSWER: - 750  

sub_title[[462, 619, 533, 637]]
## BONUS  

text[[115, 654, 864, 690]]
10) Physics – Short Answer Identify all of the following factors that affect the linear motion of a rocket in free space: 1) Exhaust velocity; 2) Mass; 3) Rate of mass ejection.  

text[[115, 706, 283, 724]]
ANSWER: 1 AND 2sub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[115, 127, 864, 164]]
11) Earth and Space – Short Answer The blue color of reflection nebulae is primarily due to what type of light scattering?  

text[[115, 180, 438, 198]]
ANSWER: RAYLEIGH SCATTERING  

sub_title[[464, 216, 533, 234]]
## BONUS  

text[[115, 250, 803, 287]]
11) Earth and Space – Short Answer Rank the following Galilean moons in terms of increasing size: 1) Callisto; 2) Ganymede; 3) Io; 4) Europa.  

text[[115, 303, 280, 321]]
ANSWER: 4, 3, 1, 2  

sub_title[[456, 373, 540, 391]]
## TOSS-UP  

text[[115, 407, 875, 461]]
12) Energy – Multiple Choice Researchers at Argonne National Lab are studying the stability of various minerals under conditions mimicking Earth’s tectonic activity. What particular mineral are they studying, which can be found in metamorphic rocks at subduction zones?  

text[[115, 478, 247, 549]]
W) Chlorite X) Glaurophane Y) Vaterite Z) Olivine  

text[[115, 565, 383, 583]]
ANSWER: X) GLAUCOPHANE  

sub_title[[464, 600, 533, 618]]
## BONUS  

text[[115, 634, 857, 740]]
12) Energy – Short Answer Scientists at Pacific Northwest National Lab have been using machine learning models to automate the operation of electron microscopes. Identify all of the following three statements that are true of electron microscopy: 1) Transmission electron microscopy cannot operate on live samples; 2) Scanning electron microscopy requires metal coating of the sample; 3) Electron microscopes have a smaller diffraction limit than light microscopes.  

text[[115, 757, 247, 774]]
ANSWER: ALLsub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 756, 146]]
13) Physics – Multiple Choice Which of the following forces cannot do work?  

text[[115, 163, 270, 233]]
W) Surface tension 
X) Gravity 
Y) Magnetic force 
Z) Kinetic friction  

text[[115, 250, 408, 268]]
ANSWER: Y) MAGNETIC FORCE  

sub_title[[463, 285, 533, 303]]
## BONUS  

text[[115, 320, 875, 373]]
13) Physics – Short Answer A concave mirror has a focal length of 8 centimeters. If an object of height 5 meters is placed 10 centimeters from the mirror, what is the magnitude of the height of the image, in meters?  

text[[115, 390, 230, 408]]
ANSWER: 20  

sub_title[[456, 460, 540, 478]]
## TOSS-UP  

text[[115, 494, 859, 530]]
14) Earth and Space – Multiple Choice Which of the following best describes the period of recombination in the universe?  

text[[115, 547, 629, 619]]
W) Quarks and Antiquarks are glued together by the strong force 
X) Protons and Neutrons combine to form heavier nuclei 
Y) Neutral hydrogen atoms are formed 
Z) Protons are replaced by other baryons in nuclei  

text[[115, 634, 647, 653]]
ANSWER: Y) NEUTRAL HYDROGEN ATOMS ARE FORMED  

sub_title[[463, 670, 533, 688]]
## BONUS  

text[[115, 704, 875, 740]]
14) Earth and Space – Short Answer Identify all of the following three bodies that are located on Mars: 1) Lakshmi Planum; 2) Maxwell Montes; 3) Olympus Mons.  

text[[115, 756, 279, 774]]
ANSWER: 3 ONLYsub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 875, 164]]
15) Chemistry – Multiple Choice Which of the following pairs of quantities is included in the most rigorous statement of Heisenberg's uncertainty principle?  

text[[115, 181, 480, 252]]
W) Force and velocity  X) Momentum and position  Y) Entropy and temperature  Z) Angular momentum and angular frequency  

text[[115, 269, 497, 288]]
ANSWER: X) MOMENTUM AND POSITION  

sub_title[[462, 305, 533, 323]]
## BONUS  

text[[115, 340, 850, 376]]
15) Chemistry – Multiple Choice YBCO is a high-temperature superconductor that can be classified as which of the following materials?  

text[[115, 393, 226, 462]]
W) Glass  X) Ceramic  Y) Alloy  Z) Composite  

text[[115, 480, 325, 498]]
ANSWER: X) CERAMIC  

sub_title[[456, 550, 540, 568]]
## TOSS-UP  

text[[115, 585, 863, 621]]
16) Biology – Short Answer Alpha-melanocyte stimulating hormone is released from which endocrine gland of the human body?  

text[[115, 637, 625, 656]]
ANSWER: ANTERIOR PITUITARY (ACCEPT: PITUITARY)  

sub_title[[462, 673, 533, 691]]
## BONUS  

text[[115, 708, 844, 743]]
16) Biology – Short Answer Tetrodotoxin is responsible for the blocking of voltage gated channels for what ion?  

text[[115, 760, 288, 778]]
ANSWER: SODIUMsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 852, 164]]
17) Math - Multiple Choice Which of the following functions does NOT contain the point (2, 12)?  

text[[115, 181, 525, 250]]
W) \(y = x\) cubed plus \(x\) squared 
X) \(y =\) the ceiling of the quantity \(x\) plus 29 thirds 
Y) \(y = 11\) plus cosine of pi \(x\) Z) \(y =\) the absolute value of the quantity \(x\) minus 10  

text[[115, 267, 737, 286]]
ANSWER: Z) THE ABSOLUTE VALUE OF THE QUANTITY \(x\) MINUS 10  

sub_title[[462, 303, 533, 321]]
## BONUS  

text[[115, 338, 800, 374]]
17) Math - Short Answer What is the cross product of the two vectors \(3i + j - k\) and \(-4i + 7j + 3k\) ?  

text[[115, 391, 321, 410]]
ANSWER: \(10i - 5j + 25k\)  

sub_title[[456, 443, 541, 461]]
## TOSS-UP  

text[[115, 478, 832, 548]]
18) Energy - Multiple Choice Scientists at SLAC National Accelerator Lab have been analyzing results of the Dark Energy Survey to predict the evolution of the galaxy via dark matter and large scale distributions of matter. Via which of the following methods was this accomplished?  

text[[115, 565, 625, 636]]
W) Measuring redshifts of far away type-I supernovae 
X) Measuring gravitational lensing from far away galaxies 
Y) Measuring cosmic microwave background radiation redshifts 
Z) Measuring galactic spiral arm waves  

text[[115, 652, 880, 671]]
ANSWER: X) MEASURING GRAVITATIONAL LENSING FROM FAR AWAY GALAXIES  

sub_title[[462, 688, 533, 705]]
## BONUS  

text[[115, 723, 848, 776]]
18) Energy - Short Answer Scientists at Argonne National Lab have been studying the integration of motor information in neurons synapsing with a major relay station of the brain. Which region of the brain were they likely studying?  

text[[115, 792, 319, 810]]
ANSWER: THALAMUSsub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[115, 127, 840, 164]]
19) Biology - Short Answer A molecule of nascent mRNA has five possible exons and 4 possible introns. How many possible mature mRNA transcripts are possible?  

text[[115, 180, 229, 198]]
ANSWER: 31  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 250, 860, 303]]
19) Biology - Short Answer An inhibitor of the enzyme pyruvate decarboxylase is added to an animal cell. Identify all of the following three processes that would still occur under these circumstances: 1) Production of NADH; 2) Production of ATP; 3) Production of oxygen.  

text[[115, 319, 282, 337]]
ANSWER: 1 AND 2  

sub_title[[456, 390, 540, 408]]
## TOSS-UP  

text[[115, 424, 839, 460]]
20) Chemistry - Multiple Choice Which of the following elements is most likely to form diatomic molecules in its elemental state?  

text[[115, 477, 206, 549]]
W) Carbon 
X) Sulfur 
Y) Silicon 
Z) Oxygen  

text[[115, 565, 316, 583]]
ANSWER: Z) OXYGEN  

sub_title[[463, 601, 533, 619]]
## BONUS  

text[[115, 635, 872, 707]]
20) Chemistry - Short Answer In spherical coordinates, the hydrogen atom wavefunction can be separated into an angular component and a radial component. Identify all of the following three statements that are true regarding the angular wavefunction: 1) It is independent of radius; 2) It determines the shapes of the orbitals; 3) It is zero for the ground-state hydrogen atom.  

text[[115, 723, 282, 741]]
ANSWER: 1 AND 2sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[113, 127, 878, 163]]
21) Earth and Space – Short Answer The reciprocal of the age of the universe is equal to what fundamental constant?  

text[[115, 180, 399, 198]]
ANSWER: HUBBLE CONSTANT  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 250, 854, 286]]
21) Earth and Space – Short Answer Identify all of the following three organisms that can lead to the formation of siliceous ooze: 1) Radiolarians; 2) Coccolithophores; 3) Foraminifera  

text[[115, 303, 279, 320]]
ANSWER: 1 ONLY  

sub_title[[456, 372, 541, 390]]
## TOSS-UP  

text[[115, 407, 880, 443]]
22) Math – Short Answer To one significant figure and in scientific notation, how many edges are there in a complete graph with 2021 vertices?  

text[[115, 459, 268, 477]]
ANSWER: \(2 \times 10^{6}\)  

sub_title[[463, 477, 533, 495]]
## BONUS  

text[[115, 512, 875, 548]]
22) Math – Short Answer A geometric series has first term 4 and a common ratio of –3. What is the minimum number of terms required for the sum of the series to exceed 2021?  

text[[115, 564, 221, 581]]
ANSWER: 9sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 865, 181]]
23) Physics - Short Answer A sphere of radius 1 meter is placed in a container filled with water. If the sphere has a density half that of water, in meters squared, what is the exposed area of the sphere?  

text[[115, 198, 231, 215]]
ANSWER: \(2\pi\)  

sub_title[[462, 233, 533, 251]]
## BONUS  

text[[115, 267, 881, 339]]
23) Physics - Short Answer Light is illuminated through a slit and forms an interference pattern on a cardboard box behind the slit. Identify all of the following three choices that are true about the interference pattern. 1) The intensity is monotonically decreasing from the center of the box; 2) The intensity is greatest at the center of the box; 3) There are a finite number of fringes.  

text[[115, 355, 279, 372]]
ANSWER: 2 ONLY