title[[175, 180, 820, 213]]
# Standard Division Double Elimination 4  

sub_title[[457, 243, 540, 261]]
## TOSS-UP  

text[[115, 269, 825, 316]]
1) BIOLOGY Short Answer The idea that only species that are sufficiently different in their resource usage can stably coexist is known as what principle?  

text[[115, 349, 727, 370]]
ANSWER: COMPETITIVE EXCLUSION (ACCEPT: GAUSE'S LAW) [GKD]  

sub_title[[464, 377, 533, 395]]
## BONUS  

text[[115, 402, 880, 476]]
1) BIOLOGY Short Answer Modern phoenixes evolved from an ancient bird called a roc. Harpies and griffins also evolved from rocs. In cladistics, what term would be given to a group containing rocs, phoenixes, and griffins?  

text[[115, 509, 581, 531]]
ANSWER: PARAPHYLETIC [pair- uh- fie- LEH- tick] [GKD]sub_title[[456, 92, 540, 109]]
## TOSS-UP  

text[[113, 118, 823, 163]]
2) CHEMISTRY Multiple Choice Which of the following unit cells would have the greatest coordination number?  

text[[113, 172, 309, 272]]
W) Simple cubic 
X) Cubic closest packed 
Y) Body-centered cubic 
Z) Primitive cubic  

text[[113, 304, 514, 325]]
ANSWER: X) CUBIC CLOSEST PACKED [GKD]  

sub_title[[463, 332, 533, 350]]
## BONUS  

text[[113, 358, 844, 404]]
2) CHEMISTRY Multiple Choice When an electron is removed from nitric oxide, from which molecular orbital is it removed?  

text[[113, 410, 311, 512]]
W) \(2\sigma\) [two sigma] 
X) \(2\sigma^{*}\) [two sigma star] 
Y) \(2\pi\) [two pi] 
Z) \(2\pi^{*}\) [two pi star]  

text[[113, 543, 425, 565]]
ANSWER: Z) \(2\pi^{*}\) [two pi star] [GKD]sub_title[[456, 92, 540, 110]]
## TOSS-UP  

text[[115, 118, 876, 164]]
3) EARTH AND SPACE Short Answer By name or number, order the following three minerals in order of increased rate of weathering at the Earth's surface:  

text[[144, 173, 392, 247]]
1) Muscovite 
2) Quartz 
3) Pyroxene [pie-ROCKS-ee]  

text[[115, 277, 705, 299]]
ANSWER: 2, 1, 3 (ACCEPT: QUARTZ, MUSCOVITE, PYROXENE) [EB]  

sub_title[[464, 305, 533, 322]]
## BONUS  

text[[115, 331, 822, 404]]
3) EARTH AND SPACE Multiple Choice What is the name of the igneous intrusion that is vaguely saucer-like in shape with a sunken center, forms parallel to existing strata, and is generally fed by a dike?  

text[[115, 410, 335, 432]]
W) Lopolith [LAW-po-lith]  

text[[115, 438, 334, 459]]
X) Laccolith [LACK-o-lith]  

text[[115, 466, 169, 484]]
Y) Sill  

text[[115, 492, 216, 510]]
Z) Batholith  

text[[115, 543, 370, 563]]
ANSWER: W) LOPOLITH [EB]sub_title[[457, 92, 540, 110]]
## TOSS-UP  

text[[114, 118, 870, 191]]
4) MATH Short Answer Six knights seat themselves at a round table with six seats. How many ways are there to arrange the knights at the table, given that Sir Lancelot and Sir Galahad refuse to sit next to one another?  

text[[115, 225, 277, 244]]
ANSWER: 72 [AKa]  

sub_title[[465, 252, 533, 270]]
## BONUS  

text[[114, 279, 855, 351]]
4) MATH Short Answer Emmy writes down all of the abundant numbers - numbers where the sum of their proper factors is greater than itself - less than 25. What is the sum of these numbers?  

text[[115, 385, 275, 405]]
ANSWER: 74 [MD]sub_title[[456, 92, 540, 110]]
## TOSS-UP  

text[[113, 118, 857, 191]]
5) PHYSICS Multiple Choice A rigid object is dropped from a height h above the ground in the presence of air resistance. Which of the following best describes how the average speed of the object over the time period that it is falling changes as h increases?  

text[[113, 199, 625, 299]]
W) It increases proportional to the square root of h  
X) It initially increases but then starts to decrease  
Y) It increases at a decreasing rate, approaching a nonzero value  
Z) It depends on the shape of the object  

text[[113, 330, 839, 380]]
ANSWER: Y) IT INCREASES AT A DECREASING RATE, APPROACHING A NONZERO VALUE [AC]  

sub_title[[464, 385, 533, 403]]
## BONUS  

text[[113, 410, 880, 511]]
5) PHYSICS Short Answer A rectangular loop of wire with dimensions 2 cm by 9 cm is placed in a magnetic field such that its normal vector makes a 90 degree angle with a 5 millitesla magnetic field. What is the torque on the loop about its center, in Newton meters and in scientific notation to 2 sig figs if a 7 ampere current is passed through the wire?  

text[[115, 544, 339, 564]]
ANSWER: 6.4 \* 10\*- 5 [AC]sub_title[[456, 92, 539, 110]]
## TOSS-UP  

text[[113, 118, 830, 192]]
6) ENERGY Multiple Choice Davidson HS B Team members are studying Alfred Wegener's [VEHG-eh-ner] theory of plate tectonics. Which of the following mechanisms did Wegener propose led to continental drift?  

text[[113, 199, 450, 299]]
W) Mantle convectionX) The centrifugal forceY) Ocean currentsZ) Wegener did not propose a mechanism  

text[[113, 331, 515, 352]]
ANSWER: X) THE CENTRIFUGAL FORCE [EB]  

sub_title[[464, 358, 533, 376]]
## BONUS  

text[[113, 384, 877, 485]]
6) ENERGY Short Answer Davidson HS B Team members are studying the principle of inclusion and exclusion. They survey the school and see that there are 28 students who have dogs, 58 with cats, and 74 with fish. 17 have dogs and cats, 39 have cats and fish, 21 have dogs and fish, and 12 have all 3. How many students have pets?  

text[[114, 517, 275, 537]]
ANSWER: 95 [MD]sub_title[[456, 92, 540, 110]]
## TOSS-UP  

text[[113, 118, 857, 165]]
7) BIOLOGY Short Answer Identify all of the following four hormones that are released by the anterior pituitary:  

text[[144, 173, 426, 273]]
1) Oxytocin 
2) Prolactin 
3) Vasopressin [VAY-zo-press-in] 
4) Aldosterone [al-DAH-stir-own]  

text[[113, 304, 542, 325]]
ANSWER: 2 ONLY (ACCEPT: PROLACTIN) [GKD]  

sub_title[[464, 332, 533, 350]]
## BONUS  

text[[113, 357, 861, 405]]
7) BIOLOGY Short Answer Vasopressin [VAY-zo-press-in] is a peptide hormone. Identify all of the following three statements that are true concerning its mechanism of action:  

text[[144, 411, 850, 512]]
1) It binds to a receptor in the cytoplasm or nucleus 
2) The vasopressin receptor acts as a transcription factor 
3) Vasopressin binding to its receptor causes increased production of second messengers inside the target cell  

text[[113, 543, 330, 563]]
ANSWER: 3 ONLY [GKD]sub_title[[456, 92, 540, 110]]
## TOSS-UP  

text[[112, 118, 857, 139]]
8) CHEMISTRY Multiple Choice Which of the following oxides would you expect to be acidic?  

text[[114, 145, 285, 245]]
W) Sodium oxide 
X) Carbon monoxide 
Y) Sulfur dioxide 
Z) Magnesium oxide  

text[[114, 277, 443, 298]]
ANSWER: Y) SULFUR DIOXIDE [GKD]  

sub_title[[464, 305, 533, 323]]
## BONUS  

text[[114, 330, 868, 404]]
8) CHEMISTRY Short Answer The solubility of silver chloride in pure water is \(1.3 \mathrm{x} 10^{-5}\) molar. To two significant figures and in scientific notation, what is the solubility of silver chloride in a 0.02 molar solution of sodium chloride, in moles per liter?  

text[[114, 436, 340, 457]]
ANSWER: \(8.5 \mathrm{x} 10^{- 9}\) [GKD]sub_title[[457, 92, 540, 110]]
## TOSS-UP  

text[[114, 118, 826, 192]]
9) EARTH AND SPACE Short Answer What famous paradox disproved the idea of a static, infinite universe by suggesting that in such a universe, there must be a star in every single possible direction, leading to night skies just as bright as daytime?  

text[[114, 224, 413, 244]]
ANSWER: OLBER'S PARADOX [EB]  

sub_title[[464, 252, 533, 270]]
## BONUS  

text[[113, 279, 850, 325]]
9) EARTH AND SPACE Multiple Choice Which of the following tidal patterns consists of two high tides and two low tides with differing tide heights?  

text[[113, 332, 293, 431]]
W) Diurnal 
X) Semidiurnal 
Y) Mixed diurnal 
Z) Mixed semidiurnal  

text[[113, 465, 466, 485]]
ANSWER: Z) MIXED SEMIDIURNAL [EB]  

sub_title[[457, 507, 540, 525]]
## TOSS-UP  

text[[114, 533, 857, 580]]
10) MATH Short Answer What is the probability, if Alan flips 2 nickels and 2 dimes, he gets at least 1 head for each coin type?  

text[[114, 612, 293, 633]]
ANSWER: 9/16 [MD]  

sub_title[[464, 640, 533, 658]]
## BONUS  

text[[113, 666, 875, 767]]
10) MATH Short Answer Paolo has 143 loaves of bread. He gives away half of his remaining loaves, rounding down to each person he encounters, until he can no longer give away loaves. Griffin has 195 fishes. He gives one third, rounding down, to each person, until he can no longer give them away. When they are done, how many total loaves and fishes do they have left?  

text[[114, 799, 264, 819]]
ANSWER: 3 [MD]sub_title[[457, 92, 540, 110]]
## TOSS-UP  

text[[114, 118, 880, 218]]
11) PHYSICS Short Answer Jason pushes his time machine with a force of \(58 \pm 0.5\) Newtons. His friend Paolo opposes the push with a force of \(23 \pm 1.2\) Newtons. Assuming Gaussian distribution and in Newtons, what is the calculated force exerted on the time machine, with proper uncertainty?  

text[[114, 250, 318, 270]]
ANSWER: \(35 \pm 1.3\) [AC]  

sub_title[[464, 278, 533, 296]]
## BONUS  

text[[114, 305, 872, 404]]
11) PHYSICS Short Answer Arvind launches a giant spider out of a cannon. Nikesh measures the mass of the spider to be \(2 \pm 0.09 \mathrm{kg}\) , and the acceleration of the spider to be \(200 \pm 9 \mathrm{m / s}^2\) . Assuming Gaussian distribution and in Newtons, what is the uncertainty in the calculated force exerted on the spider?  

text[[114, 437, 259, 457]]
ANSWER: 6 [AC]sub_title[[457, 92, 540, 109]]
## TOSS-UP  

text[[115, 118, 864, 165]]
12) ENERGY Short Answer During RNA interference, what type of double stranded RNA binds to mRNAs with near perfect homology, causing their degradation?  

text[[115, 197, 827, 245]]
ANSWER: siRNA (ACCEPT: SMALL INTERFERING RNA; DO NOT ACCEPT: miRNA) [GKD]  

sub_title[[465, 252, 533, 270]]
## BONUS  

text[[115, 279, 858, 352]]
12) ENERGY Multiple Choice Davidson MS A team members are studying the various types of galaxies. Which of the following types of galaxies, the most abundant in the universe, contain mostly older stars and rarely have any sites of new star formation?  

text[[115, 359, 247, 457]]
W) Spiral 
X) Irregular 
Y) Elliptical 
Z) Barred spiral  

text[[115, 491, 375, 511]]
ANSWER: Y) ELLIPTICAL [EB]sub_title[[457, 92, 540, 110]]
## TOSS-UP  

text[[114, 118, 847, 192]]
13) BIOLOGY Short Answer In his quest to destroy all the plants on Earth, Griffin develops a small peptide that binds to and inhibits proton pumps. What plant hormone is most directly affected by this peptide?  

text[[114, 224, 395, 245]]
ANSWER: AUXIN [OX-en] [GKD]  

sub_title[[464, 252, 533, 270]]
## BONUS  

text[[114, 278, 879, 378]]
13) BIOLOGY Short Answer In phoenixes, feather color is determined by several different genes with additive effects, and each gene has two possible alleles, making feathers range from white to red. If a cross between two phoenixes heterozygous for each gene produces white phoenixes with a frequency of \(1 / 4096\) , how many genes control feather color?  

text[[114, 410, 292, 430]]
ANSWER: SIX [GKD]  

sub_title[[457, 454, 540, 472]]
## TOSS-UP  

text[[115, 480, 808, 501]]
14) CHEMISTRY Short Answer What is the molecular geometry of iodine heptafluoride?  

text[[113, 532, 519, 554]]
ANSWER: PENTAGONAL BIPYRAMIDAL [GKD]  

sub_title[[464, 588, 533, 606]]
## BONUS  

text[[114, 614, 881, 660]]
14) CHEMISTRY Short Answer Identify all of the following three solutions that you would expect to deviate significantly from Raoult's law:  

text[[144, 667, 345, 739]]
1) Nitric acid and water 
2) Hexane and heptane 
3) Water and ethanol  

text[[113, 772, 828, 820]]
ANSWER: 1 AND 3 (ACCEPT: NITRIC ACID AND WATER, WATER AND ETHANOL) [GKD]sub_title[[456, 92, 540, 110]]
## TOSS-UP  

text[[115, 118, 859, 163]]
15) EARTH AND SPACE Short Answer Put the following three layers of the sun in order from outermost to innermost:  

text[[144, 171, 388, 192]]
1) Tachocline [TACK-o-cline]  

text[[144, 200, 216, 216]]
2) Core  

text[[144, 227, 291, 244]]
3) Radiative zone  

text[[113, 277, 666, 299]]
ANSWER: 1, 3, 2 (TACHOCLINE, RADIATIVE ZONE, CORE) [EB]  

sub_title[[464, 306, 533, 323]]
## BONUS  

text[[115, 332, 836, 378]]
15) EARTH AND SPACE Short Answer Identify all of the following three situations that are examples of anticyclonic flow:  

text[[144, 385, 576, 406]]
1) Counterclockwise flow in the northern hemisphere  

text[[144, 412, 575, 431]]
2) Counterclockwise flow in the southern hemisphere  

text[[144, 440, 358, 458]]
3) A high pressure system  

text[[113, 490, 808, 509]]
ANSWER: 2 AND 3 (ACCEPT: COUNTERCLOCKWISE FLOW IN THE SOUTHERN  

text[[113, 517, 533, 537]]
HEMISPHERE, A HIGH PRESSURE SYSTEM) [EB]  

sub_title[[456, 560, 540, 579]]
## TOSS-UP  

text[[115, 587, 807, 607]]
16) MATH Short Answer How many factors of 2 are there in the number 20 choose 10?  

text[[113, 640, 267, 660]]
ANSWER: 2 [AKa]  

sub_title[[464, 667, 533, 685]]
## BONUS  

text[[115, 694, 826, 739]]
16) MATH Short Answer What is the sum of the inverses of all numbers whose only prime factors are 2 and 3?  

text[[113, 772, 264, 792]]
ANSWER: 3 [MD]sub_title[[457, 92, 540, 110]]
## TOSS-UP  

text[[115, 118, 875, 165]]
17) PHYSICS Short Answer What is the electric flux through an ellipsoid that contains an electric dipole of charge 9.81 Coulombs?  

text[[115, 198, 260, 217]]
ANSWER: 0 [AC]  

sub_title[[464, 225, 533, 243]]
## BONUS  

text[[113, 251, 850, 400]]
17) PHYSICS Multiple Choice Which of the following best explains why quarks rarely exist in isolation?  
W) Quarks decay via the weak force as soon as they are isolated  
X) The strong force that binds quarks together is extremely hard to overcome  
Y) Particles must be net color neutral, and all quarks have color charge  
Z) Vacuum energy spontaneously produces new quarks to bind with a lone quark  

text[[113, 437, 846, 485]]
ANSWER: Y) PARTICLES MUST BE NET COLOR NEUTRAL, AND ALL QUARKS HAVE COLOR CHARGE [AC]sub_title[[456, 92, 540, 110]]
## TOSS-UP  

text[[113, 118, 863, 192]]
18) ENERGY Multiple Choice Davidson MS C Team members are studying electromagnetism. Lenz's law gives a qualitative description of induction. What equation gives a more quantitative description of induction?  

text[[113, 199, 419, 300]]
W) Ampere's law 
X) Faraday's law 
Y) Biot-Savart [BEE-oh suv-ART] law 
Z) Gauss's law  

text[[113, 330, 420, 352]]
ANSWER: X) FARADAY'S LAW [AC]  

sub_title[[464, 359, 533, 376]]
## BONUS  

text[[113, 384, 844, 560]]
18) ENERGY Short Answer Davidson HS B team members are studying equations derived by scientists whose last names start with C. When the natural log of vapor pressure is graphed against the inverse of temperature, a straight line is produced. What is the slope of that line? 
W) Enthalpy of vaporization divided by the gas constant 
X) Negative enthalpy of vaporization divided by the gas constant 
Y) Gas constant divided by enthalpy of vaporization 
Z) Negative gas constant divided by enthalpy of vaporization  

text[[113, 595, 799, 644]]
ANSWER: X) NEGATIVE ENTHALPY OF VAPORIZATION DIVIDED BY THE GAS CONSTANT [GKD]sub_title[[457, 92, 540, 110]]
## TOSS-UP  

text[[114, 118, 883, 219]]
19) BIOLOGY Short Answer Ashley orders a fluorescently labeled antibody that binds to a cytoskeletal protein, but upon receiving the antibody, she realizes she forgot what protein it binds to. When she adds the antibody to a cell culture, she finds that it causes a netlike mesh in the nucleus to glow. What structure is the antibody allowing her to see?  

text[[114, 250, 430, 270]]
ANSWER: NUCLEAR LAMINA [GKD]  

sub_title[[464, 279, 533, 297]]
## BONUS  

text[[114, 305, 797, 352]]
19) BIOLOGY Multiple Choice Which of the following best describes the change in left ventricular pressure during systolic ejection?  

text[[114, 359, 342, 459]]
W) Increases 
X) Decreases 
Y) Increases, then decreases 
Z) Decreases, then increases  

text[[114, 491, 559, 511]]
ANSWER: Y) INCREASES, THEN DECREASES [GKD]sub_title[[457, 92, 540, 110]]
## TOSS-UP  

text[[113, 118, 808, 165]]
20) CHEMISTRY Multiple Choice Infrared spectroscopy is used to measure which of the following types of molecular energy?  

text[[113, 172, 252, 270]]
W) Translational 
X) Rotational 
Y) Vibrational 
Z) Electronic  

text[[114, 304, 413, 324]]
ANSWER: Y) VIBRATIONAL [GKD]  

sub_title[[464, 332, 533, 350]]
## BONUS  

text[[114, 358, 870, 457]]
20) CHEMISTRY Short Answer Consider a simple elementary reaction \(\mathrm{A} + \mathrm{B}\) react to yield C. If this reaction is performed with excess A, it can be treated as a pseudo-first order reaction. If the concentration of A is 0.55 molar, the pseudo-first order rate constant is 1375. What is the rate constant for the reaction?  

text[[114, 490, 304, 510]]
ANSWER: 2500 [GKD]sub_title[[456, 92, 540, 110]]
## TOSS-UP  

text[[113, 118, 830, 165]]
21) EARTH AND SPACE Multiple Choice Which of the following soil horizons is generally lighter in color than surrounding horizons and has been leached of clays and oxides?  

text[[113, 172, 163, 272]]
W) A 
X) B 
Y) E 
Z) O  

text[[114, 304, 280, 325]]
ANSWER Y) E [EB]  

sub_title[[464, 332, 533, 350]]
## BONUS  

text[[114, 358, 866, 405]]
21) EARTH AND SPACE Short Answer What class of variable star, named after its prototype, is composed of young stars evolving towards the main sequence?  

text[[114, 436, 320, 457]]
ANSWER: T TAURI [EB]  

sub_title[[456, 481, 540, 499]]
## TOSS-UP  

text[[114, 506, 852, 607]]
22) MATH Short Answer Water drains out of a bathtub at 1.5 gallon/minute. The showerhead fills the bathtub at 1 gallon/minute, and the faucet fills it at 2 gallon/minute. Sam, Evan, and Ethan simultaneously turn on both the showerhead and faucet, and open the drain. How long does it take for their 42 gallon bathtub to fill up?  

text[[114, 639, 366, 660]]
ANSWER: 28 MINUTES [MD]  

sub_title[[464, 667, 533, 685]]
## BONUS  

text[[114, 693, 866, 766]]
22) MATH Short Answer Boya the Bug is traveling across the coordinate plane at x equals 42t plus 8 and y equals negative 56t minus 12, where t is in seconds. What is his speed in units per second?  

text[[114, 799, 275, 819]]
ANSWER: 70 [MD]sub_title[[457, 92, 540, 110]]
## TOSS-UP  

text[[113, 118, 830, 165]]
23) PHYSICS Multiple Choice Which of the following best explains how the water exiting a hydraulic ram pump compares to the water entering it?  

text[[113, 172, 378, 273]]
W) Lower pressure, lower speed 
X) Lower pressure, higher speed 
Y) Higher pressure, lower speed 
Z) Higher pressure, higher speed  

text[[113, 304, 579, 325]]
ANSWER: Y) HIGHER PRESSURE, LOWER SPEED [AC]  

sub_title[[464, 333, 533, 350]]
## BONUS  

text[[113, 358, 872, 430]]
23) PHYSICS Short Answer Some amorphous objects do not approach 0 entropy as their temperature goes to absolute zero. What is the name for the entropy these objects would have at absolute zero?  

text[[113, 464, 430, 484]]
ANSWER: RESIDUAL ENTROPY [AC]