
# Standard Division Round Robin 1  


## TOSS-UP  


1) BIOLOGY Multiple Choice Which type of ground tissue has a primary cell wall that is unevenly thickened and provides flexible mechanical support?  


W) Parenchyma [pair-EN-kih-ma] 
X) Collenchyma [cole-EN-kih-ma] 
Y) Sclerenchyma [scler-EN-kih-ma] 
Z) Procambium  


ANSWER: X) COLLENCHYMA [GKD]  


## BONUS  


1) BIOLOGY Multiple Choice What type of cell junction functions as a rivet, linking epithelial cells into sheets?  


W) Gap junction 
X) Tight junction 
Y) Desmosome 
Z) Adherens [add-HERE-ins] junction  


ANSWER: Y) DESMOSOME [GKD]  


## TOSS-UP  


2) CHEMISTRY Short Answer How many sigma bonds are contained in the nitrate ion?  


ANSWER: 3 [GKD]  


BONUS
2) CHEMISTRY Short Answer What intermolecular force explains why octane has a much higher boiling point than methane?  


ANSWER: LONDON DISPERSION (ACCEPT: VAN DER WAALS) [GKD]  


## TOSS-UP  


3) EARTH AND SPACE Short Answer What is the name of the large depression formed by a volcano's magma chamber collapsing post-eruption?  


ANSWER: CALDERA [EB]  


## BONUS  


3) EARTH AND SPACE Short Answer How many atmospheric cells are located in each hemisphere?  


ANSWER: 3 [EB]
## TOSS-UP  


4) MATH Short Answer What is the area of the region bounded by the lines y equals 0, x equals 0, x equals 4, and y equals x plus 2?  


ANSWER: 16 [SG]  


## BONUS  


4) MATH Multiple Choice What is the sum of the distinct prime factors of 2022?  


W) 1013 
X) 4056 
Y) 3036 
Z) 342  


ANSWER: Z) 342 [AKa]  


## TOSS-UP  


5) PHYSICS Multiple Choice Which of the following is closest to the temperature of the cosmic microwave background, in Kelvin?  


W) 0.03 
X) 3 
Y) 300 
Z) 3,000,000  


ANSWER: X) 3 [AC]  


## BONUS  


5) PHYSICS Short Answer The period of a perfect pendulum is 2 seconds. If the mass of the pendulum is doubled, its length halved, and it is moved to a planet with gravitational acceleration twice that of Earth, what is the new period, in seconds?  


ANSWER: 1 [AC]
## TOSS-UP  


6) ENERGY Short Answer Davidson HS B Team members are studying the forces acting on moving and static objects. A box is sliding down a ramp at an increasing speed. By name or number, order the following three forces on the box by increasing magnitude:  


1) Gravity 
2) Friction 
3) Normal force  


ANSWER: 2, 3, 1 (ACCEPT: FRICTION, NORMAL FORCE, GRAVITY) [AC]  


## BONUS  


6) ENERGY Short Answer Davidson MS B Team members are studying non-Newtonian fluids like silly putty and flubber. A mysterious bouncy ball has the strange property of bouncing \(50\%\) higher on each successive bounce. If the ball is dropped from a height of 10 meters, how much total distance, in meters, will it have covered just before its 4th bounce?  


ANSWER: 152.5 [AC]  


## TOSS-UP  


7) BIOLOGY Short Answer In what type of mimicry do two unpalatable species resemble each other?  


ANSWER: MULLERIAN [mew-LER-ee-in] [GKD]  


## BONUS  


7) BIOLOGY Short Answer In a population of twenty-five phoenixes, one individual is blue. Assuming that the population is in Hardy-Weinberg equilibrium and that the allele for red feather color is dominant over the allele for blue feather color, how many individuals are heterozygous?  


ANSWER: 8 [EB]
## TOSS-UP  


8) CHEMISTRY Multiple Choice A neutron-rich isotope such as tritium would most likely decay by which of the following mechanisms?  


W) Beta minus decay 
X) Beta plus decay 
Y) Alpha decay 
Z) Electron capture  


ANSWER: W) BETA MINUS DECAY [EB]  


## BONUS  


8) CHEMISTRY Short Answer What law states that the net enthalpy change of a reaction is independent of the number of steps the reaction occurs in?  


ANSWER: HESS'S LAW [GKD]
## TOSS-UP  


9) EARTH AND SPACE Short Answer Order the following three minerals from hardest to softest on the Mohs scale:  


1) Apatite 
2) Gypsum 
3) Orthoclase  


ANSWER: 3, 1, 2 (ACCEPT: ORTHOCLASE, APATITE, GYPSUM) [EB]  


## BONUS  


9) EARTH AND SPACE Multiple Choice Which of the following space telescopes observes in the visible part of the electromagnetic spectrum and was launched to help discover earth-sized exoplanets?  


W) Spitzer  


X) COBE [Coby]  


Y) Compton  


Z) Kepler  


ANSWER: Z) KEPLER [EB]
## TOSS-UP  


10) MATH Short Answer Sam has 3 red balls and 5 green balls. If he chooses two balls at random without replacement, what is the probability they are the same color?  


ANSWER: 13/28 [SG]  


## BONUS  


10) MATH Multiple Choice Given that a perfect number is any number n whose factors sum to 2 times n, which of the following numbers is perfect?  


W) 18 X) 24 Y) 28 Z) 36  


ANSWER: Y) 28 [AKa]  


## TOSS-UP  


11) PHYSICS Short Answer What is the probability that a particle in an infinite square well will be found outside of the well?  


ANSWER: 0 [AC]  


## BONUS  


11) PHYSICS Multiple Choice How will the temperature of the cosmic microwave background radiation change in the future?  


W) It will be hotter 
X) It will be colder 
Y) It will stay constant 
Z) Some parts will get hotter while others will get colder  


ANSWER: X) IT WILL BE COLDER [AC]
## TOSS-UP  


12) ENERGY Short Answer Davidson HS B Team members are studying the Harvard Spectral Classification. Order the following four spectral classes from coldest to hottest:  


1) A 
2) K 
3) B 
4) F  


ANSWER: 2, 4, 1, 3 (ACCEPT: K, F, A, B) [EB]  


## BONUS  


12) ENERGY Short Answer Davidson MS A team members are studying weak acids. If the \(\mathrm{K}_{\mathrm{a}}[\mathrm{k}^{-}\) a] of acetic acid is \(2 \mathrm{x} 10^{-5}\) , what is its \(\mathrm{K}_{\mathrm{b}}[\mathrm{k}^{-}\mathrm{b}]\) in scientific notation?  


ANSWER: \(5 \mathrm{x} 10^{- 10}[\mathrm{GKD}]\)  


## TOSS-UP  


13) BIOLOGY Short Answer Which chamber of the heart is the pulmonary vein connected to?  


ANSWER: LEFT ATRIUM [GKD]  


## BONUS  


13) BIOLOGY Multiple Choice Which protein blocks the myosin binding sites on actin?  


W) Troponin [tro- PAW- nin]  


X) Alpha-actinin  


Y) Tropomyosin [tro- poe- MY- oh- sin]  


Z) Desmin  


ANSWER: Y) TROPOMYOSIN [GKD]
## TOSS-UP  


14) CHEMISTRY Short Answer What reaction order has a half-life independent of concentration?  


ANSWER: FIRST (ACCEPT: ONE) [GKD]  


## BONUS  


14) CHEMISTRY Short Answer Consider the decomposition of ozone into oxygen gas. If oxygen gas is evolved at a rate of \(6.0 \mathrm{x} 10^{-5}\) molar per second, to two significant figures and in molar per second, at what rate does ozone disappear?  


ANSWER: \(4.0 \mathrm{x} 10^{- 5}\) (ACCEPT: \(- 4.0 \mathrm{x} 10^{- 5}\) ) [GKD]  


## TOSS-UP  


15) EARTH AND SPACE Short Answer In stars, what is the last element produced before nuclear fusion requires more energy than it produces?  


ANSWER: IRON [EB]  


## BONUS  


15) EARTH AND SPACE Short Answer Order the following three layers of the sun from innermost to outermost:  


1) Convective zone 
2) Photosphere 
3) Radiative zone  


ANSWER: 3, 1, 2 (ACCEPT: RADIATIVE ZONE, CONVECTIVE ZONE, PHOTOSPHERE) [EB]
## TOSS-UP  


16) MATH Short Answer On each of the three days from Monday to Wednesday, the probability of rain is \(40\%\) . Given that the occurrence of rain on any two days is independent, what is the probability that there is no rain on any of the days? Express your answer as a fraction.  


ANSWER: 27/125 [AKa]  


## BONUS  


16) MATH Short Answer Two circles of radius 3 are externally tangent to one another and internally tangent to another, larger, circle. Giving your answer in terms of pi, find the smallest possible area of the region inside the larger circle and outside the two smaller circles.  


ANSWER: 18 PI [AKa]  


## TOSS-UP  


17) PHYSICS Multiple Choice Which of the following necessarily implies that angular momentum is conserved?  


W) There is no angular momentum in the system 
X) Linear momentum is conserved 
Y) The net torque is zero 
Z) All forces acting on the system are conservative  


ANSWER: Y) THE NET TORQUE IS ZERO [AC]  


## BONUS  


17) PHYSICS Short Answer Schrodinger's equation describes the evolution over time of what mathematical description of a quantum state?  


ANSWER: WAVEFUNCTION [AC]
## TOSS-UP  


18) ENERGY Short Answer Davidson HS A Team members are currently studying freezing fog. Freezing fog is fog formed at temperatures below freezing and can lead to icy roads as the supercooled droplets in the fog freeze on the road surface. What type of precipitation behaves most similarly to freezing fog?  


ANSWER: FREEZING RAIN [EB]  


## BONUS  


18) ENERGY Multiple Choice Davidson MS A team members are studying the immune system. Which of the following best describes humoral immunity? W) Cytokines recruiting neutrophils to the site of infection X) Antibody release by plasma cells Y) Killing of infected cells by cytotoxic T cells Z) Release of interferon by virus-infected cells  


ANSWER: X) ANTIBODY RELEASE BY PLASMA CELLS [GKD]  


## TOSS-UP  


19) BIOLOGY Short Answer What is the net \(\mathrm{FADH}_2\) yield per molecule of glucose in the Krebs cycle?  


ANSWER: 2 [GKD]  


## BONUS  


19) BIOLOGY Short Answer One method of karyotyping [CARE-yo-typing] involves adding colchicine [CULL-chih-seen] to cells, a drug that causes microtubules to dissociate into individual tubulin units. What phase of mitosis would this arrest cells in?  


ANSWER: METAPHASE [GKD]
## TOSS-UP  


20) CHEMISTRY Multiple Choice Which of the following best describes the titration between. chloric acid and ammonia?  


W) The equivalence point is at a pH less than 7  


X) The equivalence point is at pH 7  


Y) The equivalence point is at a pH greater than 7  


Z) The equivalence point depends on the indicator used  


ANSWER: W) THE EQUIVALENCE POINT IS AT A PH LESS THAN 7 [GKD]  


## BONUS  


20) CHEMISTRY Short Answer Identify all of the following three sets of compounds that, if mixed together in the appropriate ratios, would act as buffers:  


1) Sodium acetate and acetic acid  
2) Dihydrogen phosphate and hydrogen phosphate  
3) Carbonate and bicarbonate  


ANSWER: ALL [GKD]
## TOSS-UP  


21) EARTH AND SPACE Multiple Choice In the sea/land breeze convective cell, which of the following options best describes surface wind direction at midday and during the night?  


W) To sea, to sea 
X) To sea, to land 
Y) To land, to land 
Z) To land, to sea  


ANSWER: Z) TO LAND, TO SEA [EB]  


## BONUS  


21) EARTH AND SPACE Multiple Choice What is the name of the type of fan fold where the youngest layers are located inside the fold, assuming no layers are overturned?  


W) Anticline 
X) Syncline 
Y) Monocline 
Z) Pycnocline [PICK-nuh-cline]  


ANSWER: X) SYNCLINE [EB]
## TOSS-UP  


22) MATH Short Answer What is sixty four raised to the power of quantity log base twenty seven of nine end quantity?  


ANSWER: 16 [MD]  


## BONUS  


22) MATH Short Answer Yajur is on a farm. He has horses, chickens, and cows. He sees that the number of feet on his horses and cows combined is 32, on his cows and chickens is 42, and his horses and chickens is 26. How many cows does he have?  


ANSWER: 6 [MD]  


## TOSS-UP  


23) PHYSICS Multiple Choice A 10 kilogram block is released from rest on a frictionless \(30^{\circ}\) slope. If the acceleration due to gravity is \(10 \mathrm{m / s}^2\) , what is the acceleration of the block?  


W) \(0 \mathrm{m / s}^2\)  


X) \(5 \mathrm{m / s}^2\)  


Y) \(5 \square \mathrm{m / s}^2\)  


Z) \(10 \mathrm{m / s}^2\)  


ANSWER: X) \(5 \mathrm{M / S}^2\) [AC]  


## BONUS  


23) PHYSICS Short Answer If the voltage across a circuit is tripled and the resistance is halved, what is the ratio of the power of the new circuit to the original?  


ANSWER: 18 (ACCEPT: 18 TO 1) [AC]