title[[228, 180, 767, 212]]
# Standard Division Round Robin 2  

sub_title[[457, 243, 539, 261]]
## TOSS-UP  

text[[115, 270, 878, 316]]
1) BIOLOGY Short Answer Identify all of the following three enzymes that are used in both DNA replication and transcription:  

text[[144, 325, 295, 396]]
1) Helicase 
2) Ligase 
3) Topoisomerase  

text[[115, 428, 736, 450]]
ANSWER: 1 AND 3 (ACCEPT: HELICASE AND TOPOISOMERASE) [GKD]  

sub_title[[463, 457, 533, 475]]
## BONUS  

text[[115, 483, 860, 531]]
1) BIOLOGY Short Answer Which component of the eukaryotic cytoskeleton is associated with the motor protein dynein [DIE-nee-in]?  

text[[115, 562, 408, 582]]
ANSWER: MICROTUBULES [GKD]sub_title[[457, 92, 540, 110]]
## TOSS-UP  

text[[114, 118, 855, 165]]
2) CHEMISTRY Short Answer A solution at \(25^{\circ}\mathrm{C}\) has a hydrogen ion concentration 100 times greater than its hydroxide ion concentration. What is the pH of this solution?  

text[[114, 198, 274, 217]]
ANSWER: 6 [GKD]  

sub_title[[464, 225, 533, 243]]
## BONUS  

text[[113, 251, 874, 299]]
2) CHEMISTRY Multiple Choice Which of the following sets of quantum numbers is not allowed in the ground state of antimony, located in period five of the periodic table?  

text[[113, 305, 472, 406]]
W) N equals 4, L equals 2, M sub L equals 1 
X) N equals 5, L equals 1, M sub L equals -1 
Y) N equals 2, L equals 0, M sub L equals 0 
Z) N equals 3, L equals 3, M sub L equals -2  

text[[113, 437, 680, 458]]
ANSWER: Z) N EQUALS 3, L EQUALS 3, M SUB L EQUALS -2 [EB]  

sub_title[[457, 480, 540, 498]]
## TOSS-UP  

text[[113, 506, 866, 581]]
3) EARTH AND SPACE Short Answer What is the name for the fusion cycle common in stars greater than 1.3 solar masses where protons fuse with isotopes of three heavier elements before the production of helium and regeneration of the first intermediate?  

text[[113, 612, 707, 633]]
ANSWER: CNO CYCLE (ACCEPT: BETHE-WEIZSACKER CYCLE) [EB]  

sub_title[[464, 640, 533, 658]]
## BONUS  

text[[113, 666, 870, 714]]
3) EARTH AND SPACE Short Answer What is the name of the point where the solar wind is no longer strong enough to travel through the interstellar medium?  

text[[113, 745, 360, 765]]
ANSWER: HELIOPAUSE [EB]sub_title[[457, 92, 540, 109]]
## TOSS-UP  

text[[114, 118, 880, 191]]
4) MATH Short Answer For a "research project", Sophie goes to 500 different ice cream shops. At each one, she orders vanilla ice cream, and then rolls a die for each of the 20 toppings, getting it if she rolls a 6. What is the expected mode number of toppings?  

text[[114, 225, 265, 244]]
ANSWER: 3 [MD]  

sub_title[[464, 253, 533, 270]]
## BONUS  

text[[114, 279, 857, 325]]
4) MATH Short Answer Julian and Melody, along with 8 other of their classmates, get in a line randomly. What is the probability the two are next to each other?  

text[[114, 358, 282, 378]]
ANSWER: 1/5 [MD]sub_title[[457, 92, 540, 110]]
## TOSS-UP  

text[[112, 118, 864, 264]]
5) PHYSICS Multiple Choice Which of the following best describes the electric field distribution in a charged conductor?W) Decreases linearly from centerX) Decreases quadratically from centerY) Stays zero throughout the interiorZ) Stays a constant, nonzero value throughout the interior  

text[[113, 303, 661, 325]]
ANSWER: Y) STAYS ZERO THROUGHOUT THE INTERIOR [AC]  

sub_title[[464, 332, 533, 350]]
## BONUS  

text[[113, 358, 872, 430]]
5) PHYSICS Short Answer A satellite orbiting a planet in a circular orbit constantly undergoes gravitation acceleration. Identify all of the following four factors that affect the magnitude of the acceleration:  

text[[144, 438, 327, 537]]
1) Velocity of satellite 
2) Mass of planet 
3) Radius of orbit 
4) Mass of satellite  

text[[113, 570, 750, 591]]
ANSWER: 2 AND 3 (ACCEPT: MASS OF PLANET, RADIUS OF ORBIT) [AC]sub_title[[457, 92, 540, 110]]
## TOSS-UP  

text[[113, 118, 870, 219]]
6) ENERGY Short Answer Davidson MS B Team members are studying solar system objects and their histories. As the planet Mercury formed, it underwent one, possibly two, periods of heavy bombardment by comets and asteroids, leading to the presence of multiple large impact basins. What is the name of the largest of Mercury's impact basins?  

text[[114, 252, 384, 272]]
ANSWER: CALORIS BASIN [EB]  

sub_title[[464, 279, 533, 297]]
## BONUS  

text[[113, 305, 882, 431]]
6) ENERGY Short Answer Davidson HS A Team members are studying languages that don't have a base 10 number system. In ancient Mesoamerica, the Mayans used a base 20 system with a combination of three kinds of symbols to represent each digit. A dot meant one, a line meant five, and a shell served as zero. How many shells, dots, and lines, respectively, are contained in the Mayan representation of the base ten number 378?  

text[[114, 465, 372, 484]]
ANSWER: ZERO, SIX, SIX [EB]  

sub_title[[457, 507, 540, 525]]
## TOSS-UP  

text[[113, 533, 882, 553]]
7) BIOLOGY Short Answer What is the fundamental structural and functional unit of the kidneys?  

text[[114, 587, 355, 606]]
ANSWER: NEPHRON [GKD]  

sub_title[[464, 614, 533, 631]]
## BONUS  

text[[114, 640, 828, 686]]
7) BIOLOGY Short Answer Identify all of the following three digestive enzymes that would produce glucose as a product:  

text[[144, 694, 443, 767]]
1) Chymotrypsin [kve-mo-TRIP-sin] 
2) Lactase 
3) Lipase  

text[[114, 799, 516, 820]]
ANSWER: 2 ONLY (ACCEPT: LACTASE) [GKD]sub_title[[457, 92, 540, 109]]
## TOSS-UP  

text[[113, 118, 748, 138]]
8) CHEMISTRY Multiple Choice Which of the following graphs would be linear?  

text[[113, 145, 615, 164]]
W) Plotting concentration versus time for a first order reaction  

text[[113, 172, 750, 192]]
X) Plotting the natural log of concentration versus time for a first order reaction  

text[[113, 199, 631, 218]]
Y) Plotting concentration versus time for a second order reaction  

text[[113, 225, 772, 245]]
Z) Plotting the natural log of concentration versus time for a second order reaction  

text[[113, 277, 876, 325]]
ANSWER: X) PLOTTING THE NATURAL LOG OF CONCENTRATION VERSUS TIME FOR A FIRST ORDER REACTION [GKD]  

sub_title[[463, 332, 533, 350]]
## BONUS  

text[[113, 358, 872, 405]]
8) CHEMISTRY Short Answer By name or number, order the following three ionic salts in order of decreasing lattice energy:  

text[[144, 411, 325, 485]]
1) Sodium chloride 
2) Potassium chloride 
3) Magnesium oxide  

text[[113, 516, 833, 566]]
ANSWER: 3, 1, 2 (ACCEPT: MAGNESIUM OXIDE, SODIUM CHLORIDE, POTASSIUM CHLORIDE) [EB]sub_title[[457, 92, 540, 110]]
## TOSS-UP  

text[[114, 118, 878, 192]]
9) EARTH AND SPACE Short Answer Given a wind coming from the northeast, 45 degrees from true north, what will be the direction of the resulting Ekman transport, with respect to true north, in the Northern hemisphere?  

text[[114, 223, 864, 273]]
ANSWER: 45 DEGREES WEST OF TRUE NORTH (ACCEPT: 45 DEGREES NORTHWEST) [EB]  

sub_title[[464, 278, 533, 297]]
## BONUS  

text[[114, 305, 806, 352]]
9) EARTH AND SPACE Short Answer What is the name of the deposits of unsorted and unlayered till found specifically at the sides of a glacier?  

text[[114, 384, 692, 406]]
ANSWER: LATERAL MORAINE (DO NOT ACCEPT: MORAINE) [EB]  

sub_title[[457, 427, 540, 445]]
## TOSS-UP  

text[[115, 454, 865, 501]]
10) MATH Short Answer What is the length of the short base of a trapezoid with a long base of 13, a side length of 13, and a height of 12.  

text[[114, 532, 265, 553]]
ANSWER: 3 [MD]  

sub_title[[464, 560, 533, 579]]
## BONUS  

text[[115, 587, 867, 608]]
10) MATH Short Answer What is the quantity one plus i end quantity raised to the sixth power?  

text[[114, 640, 277, 660]]
ANSWER: - 8i [MD]sub_title[[457, 92, 539, 110]]
## TOSS-UP  

text[[115, 118, 767, 139]]
11) PHYSICS Short Answer What is the SI unit for the strength of a magnetic field?  

text[[115, 172, 304, 192]]
ANSWER: TESLA [AC]  

sub_title[[464, 200, 533, 217]]
## BONUS  

text[[114, 225, 875, 325]]
11) PHYSICS Short Answer A 4 kilogram block is placed at the top of a 40 meter long ramp that is inclined 30 degrees from the horizontal. Treating the acceleration due to gravity as ten meters per second squared, how long, in seconds, does it take for the block to slide to the bottom of the ramp?  

text[[115, 357, 258, 378]]
ANSWER: 4 [AC]  

sub_title[[457, 401, 539, 419]]
## TOSS-UP  

text[[114, 426, 857, 527]]
12) ENERGY Short Answer Davidson HS B team members are studying evolution and natural selection. What type of selection is exhibited by the black-bellied seedcracker, a species of bird where individuals with small beaks or large beaks are evolutionarily favored, while individuals with medium beaks are not?  

text[[114, 560, 586, 581]]
ANSWER: DISRUPTIVE (ACCEPT: DIVERSIFYING) [EB]  

sub_title[[464, 614, 533, 631]]
## BONUS  

text[[115, 639, 863, 714]]
12) ENERGY Short Answer Davidson HS A team members are studying the properties of transition metals. Identify all of the following three transition metals you would expect to form ions in the \(+3\) oxidation state:  

text[[144, 722, 230, 792]]
1) Iron 
2) Zinc 
3) Cobalt  

text[[114, 825, 614, 847]]
ANSWER: 1 AND 3 (ACCEPT: IRON AND COBALT) [GKD]sub_title[[456, 92, 539, 110]]
## TOSS-UP  

text[[113, 118, 870, 163]]
13) BIOLOGY Multiple Choice Which of the following interspecific interactions does not benefit either species?  

text[[113, 172, 234, 191]]
W) Mutualism  

text[[113, 199, 459, 219]]
X) Commensalism [kuh-MEN-suh-lih-zim]  

text[[113, 225, 437, 246]]
Y) Ammensalism [uh-MEN-suh-lih-zim]  

text[[113, 253, 221, 271]]
Z) Predation  

text[[113, 304, 428, 325]]
ANSWER: Y) AMMENSALISM [GKD]  

sub_title[[464, 333, 533, 351]]
## BONUS  

text[[113, 359, 828, 379]]
13) BIOLOGY Short Answer In what type of survivorship is death rate independent of age?  

text[[113, 410, 327, 430]]
ANSWER: TYPE II [GKD]  

sub_title[[456, 454, 540, 472]]
## TOSS-UP  

text[[113, 480, 794, 526]]
14) CHEMISTRY Short Answer By name or number, identify all of the following three compounds that are polar:  

text[[144, 534, 327, 553]]
1) Sulfur tetrafluoride  

text[[144, 562, 327, 580]]
2) Sulfur hexafluoride  

text[[144, 589, 288, 606]]
3) Sulfur dioxide  

text[[113, 639, 857, 660]]
ANSWER: 1 AND 3 (ACCEPT: SULFUR TETRAFLUORIDE AND SULFUR DIOXIDE) [EB]  

sub_title[[464, 667, 533, 685]]
## BONUS  

text[[113, 693, 857, 767]]
14) CHEMISTRY Short Answer If half a liter of 0.5 molar phosphoric acid is titrated with one liter of a sodium hydroxide solution, what is the molarity of the sodium hydroxide solution, to two significant figures?  

text[[113, 799, 281, 819]]
ANSWER: 0.75 [EB]sub_title[[456, 92, 540, 110]]
## TOSS-UP  

text[[115, 119, 832, 165]]
15) EARTH AND SPACE Short Answer What are the names for the pointer stars in the Big Dipper that are often used to locate Polaris?  

text[[113, 197, 536, 246]]
ANSWER: MERAK AND DUBHE [DOOB-huh] [EB] BONUS  

text[[115, 252, 836, 297]]
15) EARTH AND SPACE Short Answer Order the following three eons from most recent to oldest:  

text[[144, 306, 440, 380]]
1) Hadean 
2) Archean [are-KEY-in] 
3) Phanerozoic [fan-er-oh-ZO-ic]  

text[[113, 410, 720, 431]]
ANSWER: 3, 2, 1 (ACCEPT: PHANEROZOIC, ARCHEAN, HADEAN) [EB]  

sub_title[[456, 454, 540, 472]]
## TOSS-UP  

text[[115, 480, 779, 500]]
16) MATH Short Answer Determine the sum of the integers from 10 to 40 inclusive.  

text[[115, 533, 279, 553]]
ANSWER: 775 [SG]  

sub_title[[464, 561, 533, 579]]
## BONUS  

text[[115, 587, 872, 633]]
16) MATH Multiple Choice Alan has a list of every integer power of 4. He adds the reciprocal of each number on his list. What sum does he get?  

text[[115, 640, 195, 740]]
W) 1/3 
X) 4/3 
Y) 2 
Z) Infinity  

text[[115, 772, 309, 792]]
ANSWER: X) 4/3 [MD]sub_title[[456, 92, 540, 110]]
## TOSS-UP  

text[[112, 118, 872, 354]]
17) PHYSICS Multiple Choice A ball is attached to the edge of an initially rotating disk. The disk undergoes a constant, nonzero angular acceleration. Which of the following directions cannot describe the ball's acceleration vector?  
W) With a component in the direction of tangential velocity and a component pointing towards the center  
X) With a component opposite the direction of tangential velocity and a component pointing towards the center  
Y) Having a magnitude greater than the magnitude of its tangential acceleration  
Z) Pointing directly towards the center of the disk  

text[[113, 384, 802, 405]]
ANSWER: Z) POINTING DIRECTLY TOWARDS THE CENTER OF THE DISK [AC]  

sub_title[[464, 412, 533, 430]]
## BONUS  

text[[113, 438, 780, 562]]
17) PHYSICS Multiple Choice Which of the following is true about magnetic fields?  
W) Unlike electric fields, magnetic fields only attract other magnetic fields, not repel  
X) Changing magnetic fields can change the current through a wire  
Y) Magnetic field line always point away from magnets  
Z) Magnetic fields drop with the cube of distance  

text[[113, 595, 875, 644]]
ANSWER: X) CHANGING MAGNETIC FIELDS CAN CHANGE THE CURRENT THROUGH A WIRE [AC]sub_title[[456, 92, 539, 110]]
## TOSS-UP  

text[[113, 118, 832, 166]]
18) ENERGY Multiple Choice Davidson HS A Team Members are studying particle physics. Which of the following particles is a fermion?  

text[[113, 174, 235, 273]]
W) Photon 
X) Muon [MEW-on] 
Y) Gluon 
Z) Higgs  

text[[114, 304, 352, 325]]
ANSWER: X) MUON [GKD]  

sub_title[[464, 333, 533, 350]]
## BONUS  

text[[113, 358, 877, 457]]
18) ENERGY Short Answer Davidson MS C Team members are currently studying atmospheric convective cells. At the intersection of the Hadley and the Ferrel cells, the sinking of warming air leads to increased evaporation and the formation of deserts. At what degree of latitude does this take place?  

text[[113, 490, 757, 510]]
ANSWER: 30 DEGREES (ACCEPT: 30 DEGREES NORTH AND SOUTH) [EB]sub_title[[456, 92, 539, 110]]
## TOSS-UP  

text[[113, 118, 861, 164]]
19) BIOLOGY Multiple Choice What layer of cells is found just inside of the endodermis and is the formation site of lateral roots?  

text[[113, 172, 283, 273]]
W) Pericycle 
X) Procambium 
Y) Ground meristem 
Z) Pith  

text[[114, 305, 395, 325]]
ANSWER: W) PERICYCLEC [GKD]  

sub_title[[464, 332, 533, 350]]
## BONUS  

text[[114, 358, 876, 405]]
19) BIOLOGY Short Answer What enzyme, used in \(C_4\) and CAM plants to limit photorespiration, has a much higher affinity for \(CO_2\) than RuBisCO?  

text[[114, 436, 432, 457]]
ANSWER: PEP CARBOXYLASE [GKD]  

sub_title[[456, 480, 540, 498]]
## TOSS-UP  

text[[114, 506, 839, 553]]
20) CHEMISTRY Short Answer Which law of thermodynamics states that the entropy of the universe will always increase?  

text[[114, 586, 386, 606]]
ANSWER: SECOND LAW [GKD]  

sub_title[[464, 614, 533, 631]]
## BONUS  

text[[113, 640, 830, 686]]
20) CHEMISTRY Multiple Choice What are the molecular and electron domain geometries, respectively, of ammonia?  

text[[114, 694, 408, 713]]
W) Tetrahedral, trigonal bipyramidal  

text[[114, 721, 390, 740]]
X) Tetrahedral, trigonal pyramidal  

text[[114, 748, 402, 767]]
Y) Trigonal bipyramidal, tetrahedral  

text[[114, 775, 389, 794]]
Z) Trigonal pyramidal, tetrahedral  

text[[113, 826, 621, 847]]
ANSWER: Z) TRIGONAL PYRAMIDAL, TETRAHEDRAL [EB]sub_title[[457, 92, 539, 110]]
## TOSS-UP  

text[[113, 118, 815, 165]]
21) EARTH AND SPACE Multiple Choice Which of the following mineral groups is most common in the Earth's crust?  

text[[113, 172, 228, 273]]
W) Sulfate 
X) Silicate 
Y) Oxide 
Z) Carbonate  

text[[114, 304, 355, 325]]
ANSWER: X) SILICATE [EB]  

sub_title[[464, 332, 533, 350]]
## BONUS  

text[[113, 358, 880, 404]]
21) EARTH AND SPACE Multiple Choice In which of the following ocean zones would you most likely find infauna?  

text[[113, 410, 241, 511]]
W) Epipelagic 
X) Mesopelagic 
Y) Benthic 
Z) Photic  

text[[114, 543, 355, 563]]
ANSWER: Y) BENTHIC [EB]sub_title[[456, 92, 540, 110]]
## TOSS-UP  

text[[112, 118, 850, 140]]
22) MATH Multiple Choice Determine the number of zeros after the last nonzero digit of 30!.  

text[[113, 145, 160, 245]]
W) 4 
X) 5 
Y) 6 
Z) 7  

text[[113, 277, 285, 298]]
ANSWER: Z) 7 [SG]  

sub_title[[464, 305, 533, 323]]
## BONUS  

text[[113, 331, 848, 404]]
22) MATH Multiple Choice 5% of the population is positive for COVID-19, and COVID tests have a 1% false positive rate. If a person tests positive for COVID, which of the following is closest to the probability that they actually contracted the virus?  

text[[113, 410, 185, 510]]
W) 65% 
X) 75% 
Y) 85% 
Z) 95%  

text[[113, 543, 323, 563]]
ANSWER: Y) 85% [GKD]sub_title[[457, 92, 540, 110]]
## TOSS-UP  

text[[115, 118, 880, 164]]
23) PHYSICS Short Answer Which famous physicist predicted the existence of antimatter with his namesake equation?  

text[[115, 197, 520, 217]]
ANSWER: DIRAC (ACCEPT: PAUL DIRAC) [AC]  

sub_title[[465, 225, 533, 243]]
## BONUS  

text[[115, 251, 872, 325]]
23) PHYSICS Short Answer Given the speed of light as three times ten to the eighth meters per second, what is the frequency in Hertz, to two significant figures and in scientific notation, of an orange photon with a wavelength of 6.0 times ten to the second power nanometers?  

text[[115, 357, 390, 378]]
ANSWER: \(5.0 * 10^{14}\) HERTZ [EB]