
## ROUND 1  


## TOSS-UP  


1) BIOLOGY Multiple Choice What proteins have a cysteine residue at their active site and are responsible for apoptosis in animal cells?  


W) Kinesins 
X) Proteases 
Y) Caspases 
Z) Kinases ANSWER: Y) CASPASES  


## BONUS  


1) BIOLOGY Short Answer IAP is a family of proteins thought to inhibit apoptosis. What does the acronym IAP stand for?  


ANSWER: INHIBITOR OF APOPTOSIS  


## TOSS-UP  


2) CHEMISTRY Multiple Choice What type of intermolecular interactions exists between noble gas solids?  


W) Delocalized covalent bonds  


X) London dispersion forces  


Y) Directional covalent bonds  


Z) Ionic bonds  


ANSWER: X) LONDON DISPERSION FORCES  


## BONUS  


2) CHEMISTRY Short Answer What is the only element in the periodic table that does NOT freeze at 1 atm? ANSWER: HELIUM  


## TOSS-UP  


3) PHYSICS Short Answer What type of friction results from the deformation of an object moving across a line?  


ANSWER: ROLLING FRICTION  


## BONUS  


3) PHYSICS Multiple Choice Assuming gravity is \(10 \text{m} /\text{s}^2\), what is the minimum coefficient of friction necessary between an object and a surface if the object is traveling at \(5 \text{m} /\text{s}\) in a uniform circular path with a radius of \(5 \text{meters}\)?  


W) 0.25
X) 0.5Y) 0.6Z) 0.75ANSWER: X) 0.5  


## TOSS-UP  


4) EARTH AND SPACE Multiple Choice Which of the following Galilean moons is the only one known to have its own magnetic field?  


W) CallistoX) IoY) GanymedeZ) EuropaANSWER: Y) GANYMEDE  


## BONUS  


4) EARTH AND SPACE Multiple Choice What is the largest of Jupiter's inner satellites?  


W) AmaltheaX) ThebeY) AdrasteaZ) MetisANSWER: W) AMALTHEA  


## TOSS-UP  


5) MATHEMATICS Multiple Choice What type of prime number is formed when one takes a power of 2 and subtracts 1?  


W) Goldbach primeX) Euclidean primeY) Mersenne primeZ) Euler's primeANSWER: Y) MERSENNE PRIME  


## BONUS  


5) MATHEMATICS Short Answer What is the sum of the first five prime numbers?ANSWER: 28  


## TOSS-UP  


6) ENERGY Multiple Choice What is the world's largest tidal power station as of January 2014?W) Rance Tidal Power StationX) Sihwa Tidal Power Station
Y) Race Rocks Tidal Power Station  
Z) Annapolis Royal Generating Station  
ANSWER: X) SIHWA TIDAL POWER STATION  


## BONUS  


6) ENERGY Short Answer In ebb generation, what structure fills a basin at high tide and releases seawater to generate energy?  ANSWER: SLUICE GATE  


## TOSS-UP  


7) BIOLOGY Multiple Choice Which of the following hormones is produced and released by the posterior pituitary gland?  


W) Oxytocin  
X) Prolactin  
Y) Growth hormone  
Z) Luteinizing hormone  
ANSWER: W) OXYTOCIN  


## BONUS  


7) BIOLOGY Short Answer What structure of the brain is responsible for regulating hormone secretion by the anterior pituitary gland?  ANSWER: HYPOTHALAMUS  


ANSWER: HYPOTHALAMUS  


## TOSS-UP  


8) CHEMISTRY Multiple Choice What scientist devised an electronegativity scale and won Nobel Prizes in both chemistry and peace?  


W) Amedeo Avogadro  
X) Archibald Scott Couper  
Y) John Dalton  
Z) Linus Pauling  
ANSWER: Z) LINUS PAULING  


## BONUS  


8) CHEMISTRY Short Answer Ions that contain the same number of electrons are referred to by what term?  ANSWER: ISOELECTRONIC IONS  


ANSWER: ISOELECTRONIC IONS  


## TOSS-UP  


9) PHYSICS Multiple Choice In special relativity, the lowercase gamma is used to symbolize what quantity?
W) Speed of lightX) Inertial reference frameY) Lorentz factorZ) Euclidean factorANSWER: Y) LORENTZ FACTOR  


## BONUS  


9) PHYSICS Short Answer What happens to an individual's apparent weight, when viewed by an outside observer, as the individual travels near the speed of light?ANSWER: INCREASES  


## TOSS-UP  


10) EARTH AND SPACE Multiple Choice The Matterhorn exemplifies what type of glacial formation that results in an angular mountaintop?  


W) Glacial striationsX) AreteY) Glacial hornZ) CirqueANSWER: Y) GLACIAL HORN  


## BONUS  


10) EARTH AND SPACE Short Answer What type of landform results from the glacial deposition of unstratified and unsorted material?ANSWER: MORAINES  


## TOSS-UP  


11) MATHEMATICS Multiple Choice What is the coefficient of the 4th term in the following expression: \((3x + 2y)^5\) ?  


W) 320X) 720Y) 1440Z) 1680ANSWER: X) 720  


## BONUS  


11) MATHEMATICS Short Answer List the terms that exist in the 5th row of Pascal's Triangle.ANSWER: 1, 5, 10, 10, 5, 1  


## TOSS-UP
12) ENERGY Multiple Choice Humphry Davy created the first incandescent light bulb using what metal?  


W) Tungsten 
X) Iridium 
Y) Platinum 
Z) Molybdenum ANSWER: Y) PLATINUM  


## BONUS  


12) ENERGY Short Answer What does the acronym ITER, a nuclear fusion research facility, stand for? ANSWER: INTERNATIONAL THERMONUCLEAR EXPERIMENTAL REACTOR  


## TOSS-UP  


13) BIOLOGY Multiple Choice What enzyme is responsible for splicing out errors in DNA replication?  


W) Ligase 
X) Primase 
Y) Helicase 
Z) Nuclease ANSWER: Z) NUCLEASE  


## BONUS  


13) BIOLOGY Short Answer What enzyme compensates for the shortening of chromosomal endings during eukaryotic cell replication and plays an important role in aging and cancer? ANSWER: TELOMERASE  


## TOSS-UP  


14) CHEMISTRY Multiple Choice According to Le Chatelier's principle, what effect would a catalyst have on the rate of a chemical reaction? W) Increase forward reaction X) Increase backward reaction Y) Increase forward and backward reactions equally Z) Have no influence on reaction rates ANSWER: Y) INCREASE FORWARD AND BACKWARD REACTIONS EQUALLY  


## BONUS  


14) CHEMISTRY Short Answer If heat is added to an endothermic reaction, in which direction does the equilibrium shift? ANSWER: RIGHT OR TOWARD THE PRODUCTS
## TOSS-UP  


15) PHYSICS Multiple Choice If the charge on one plate of a capacitor is \(+15\) Coulombs and the capacitance is 25000 microfarads, what is the potential energy stored in the capacitor?  


W) 9000 Joules  X) 8000 Joules  Y) 4500 Joules  Z) 18000 Joules  ANSWER: Y) 4500 JOULES  


## BONUS  


15) PHYSICS Short Answer What is the potential energy stored in a spring that is compressed 4 meters from its rest position given that \(k = 50 \text{N / m}\) ?  ANSWER: 400 JOULES  


## TOSS-UP  


16) EARTH AND SPACE Multiple Choice A massive star fuses with which element before undergoing core collapse and becoming a supernova?  


W) Silicon  X) Oxygen  Y) Platinum  Z) Iron  ANSWER: Z) IRON  


## BONUS  


16) EARTH AND SPACE Short Answer White dwarfs typically transform into what type of supernova because they lack hydrogen?  ANSWER: TYPE I  


## TOSS-UP  


17) MATHEMATICS Multiple Choice What is the fourth prime term in the Fibonacci sequence?  


W) 3  X) 7  Y) 13  Z) 89  ANSWER: Y) 13  


## BONUS  


17) MATHEMATICS Short Answer Leonardo Fibonacci considered the idealized population of what animal as a model for his sequence?
## TOSS-UP  


18) ENERGY Multiple Choice As of January 2014, what is the largest capacity that a hydroelectric power station can generate in megawatts?  


W) 2,000 
X) 4,000 
Y) 10,000 
Z) 20,000 ANSWER: Z) 20,000  


## BONUS  


18) ENERGY Short Answer What is the name of the facility in Livermore, California, that uses laser based inertial confinement to attempt nuclear fusion? ANSWER: NATIONAL IGNITION FACILITY (ACCEPT NIF)  


## TOSS-UP  


19) BIOLOGY Multiple Choice What gaseous hormone promotes fruit ripening and flowering in pineapples?  


W) Ethylene 
X) Methylene 
Y) Cytokinins 
Z) Abscisic acid ANSWER: W) ETHYLENE  


## BONUS  


19) BIOLOGY Short Answer What is the predominant natural auxin in plants called? ANSWER: INDOLEACETIC ACID OR IAA  


## TOSS-UP  


20) CHEMISTRY Multiple Choice What indicator is blue above a pH of 7.6, and yellow below a pH of 6.0?  


W) Bromophenol Blue 
X) Litmus  


Y) Bromothymol Blue  


Z) Phenolphthalein  


ANSWER: BROMOTHYMOL BLUE  


## BONUS
20) CHEMISTRY Short Answer What type of titration is used when the endpoint of a normal titration is difficult to identify?  


ANSWER: BACK/REVERSE TITRATION  


## TOSS-UP  


21) PHYSICS Multiple Choice A single fission reaction with uranium-235 produces approximately how much energy?  


W) 100 MeV 
X) 200 MeV 
Y) 300 MeV 
Z) 400 MeV ANSWER: X) 200 MeV  


## BONUS  


21) PHYSICS Short Answer What chemical element has an atomic number 90, is named after a Norse god, and is used as a substitute nuclear fuel? ANSWER: THORIUM  


## TOSS-UP  


22) EARTH AND SPACE Multiple Choice What planet has the highest albedo in the solar system?  


W) Earth 
X) Mars 
Y) Mercury 
Z) Venus ANSWER: Z) VENUS  


## BONUS  


22) EARTH AND SPACE Short Answer An albedo value of 0 indicates that a surface has what property? ANSWER: PERFECT/IDEAL ABSORPTION  


## TOSS-UP  


23) MATHEMATICS Multiple Choice If set A contains all factors of 12 and set B contains all prime numbers, what numbers are in the intersection of set A and set B?  


W) 1,2,4 
X) 2,3,6 
Y) 2,3 
Z) 2,3,6,7 ANSWER: Y) 2,3
## BONUS  


23) MATHEMATICS Short Answer What principle states that a proper subset of S is any subset of S other than S itself? ANSWER: PRINCIPLE OF EXTENSIONALITY  


## TOSS-UP  


24) ENERGY Multiple Choice What type of batteries depend on the reaction between zinc and manganese dioxide?  W) Lithium-ion batteries  X) Daniell batteries  Y) Alkaline batteries  Z) Bunsen batteries  ANSWER: Y) ALKALINE BATTERIES  


## BONUS  


24) ENERGY Short Answer What is the atomic mass of the plutonium isotope most commonly used in nuclear fission? ANSWER: 239  


## TOSS-UP  


25) BIOLOGY Multiple Choice What hormone stimulates the release of digestive enzymes from the pancreas?  W) Secretin  X) Cholecystokinin  Y) Cytokinins  Z) Gastrin  ANSWER: X) CHOLECYSTOKININ  


## BONUS  


25) BIOLOGY Short Answer What hormone promotes the breakdown of glycogen in the liver and the release of glucose into the blood?  ANSWER: GLUCAGON