sub_title[[452, 68, 544, 87]]
## ROUND 1  

sub_title[[452, 108, 544, 126]]
## TOSS-UP  

text[[90, 128, 880, 167]]
1) BIOLOGY Multiple Choice What proteins have a cysteine residue at their active site and are responsible for apoptosis in animal cells?  

text[[92, 169, 320, 270]]
W) Kinesins 
X) Proteases 
Y) Caspases 
Z) Kinases ANSWER: Y) CASPASES  

sub_title[[461, 299, 535, 317]]
## BONUS  

text[[90, 319, 897, 358]]
1) BIOLOGY Short Answer IAP is a family of proteins thought to inhibit apoptosis. What does the acronym IAP stand for?  

text[[90, 358, 439, 377]]
ANSWER: INHIBITOR OF APOPTOSIS  

sub_title[[452, 405, 544, 423]]
## TOSS-UP  

text[[90, 425, 857, 464]]
2) CHEMISTRY Multiple Choice What type of intermolecular interactions exists between noble gas solids?  

text[[92, 465, 368, 483]]
W) Delocalized covalent bonds  

text[[93, 486, 346, 503]]
X) London dispersion forces  

text[[93, 506, 352, 524]]
Y) Directional covalent bonds  

text[[93, 527, 222, 544]]
Z) Ionic bonds  

text[[90, 546, 512, 565]]
ANSWER: X) LONDON DISPERSION FORCES  

sub_title[[461, 594, 536, 612]]
## BONUS  

text[[90, 614, 881, 673]]
2) CHEMISTRY Short Answer What is the only element in the periodic table that does NOT freeze at 1 atm? ANSWER: HELIUM  

sub_title[[452, 701, 544, 719]]
## TOSS-UP  

text[[90, 721, 861, 760]]
3) PHYSICS Short Answer What type of friction results from the deformation of an object moving across a line?  

text[[90, 760, 374, 779]]
ANSWER: ROLLING FRICTION  

sub_title[[461, 809, 536, 827]]
## BONUS  

text[[90, 829, 892, 888]]
3) PHYSICS Multiple Choice Assuming gravity is \(10 \text{m} /\text{s}^2\), what is the minimum coefficient of friction necessary between an object and a surface if the object is traveling at \(5 \text{m} /\text{s}\) in a uniform circular path with a radius of \(5 \text{meters}\)?  

text[[94, 890, 167, 907]]
W) 0.25text[[90, 68, 244, 147]]
X) 0.5Y) 0.6Z) 0.75ANSWER: X) 0.5  

sub_title[[453, 175, 543, 193]]
## TOSS-UP  

text[[90, 196, 909, 234]]
4) EARTH AND SPACE Multiple Choice Which of the following Galilean moons is the only one known to have its own magnetic field?  

text[[92, 236, 328, 336]]
W) CallistoX) IoY) GanymedeZ) EuropaANSWER: Y) GANYMEDE  

sub_title[[461, 366, 535, 384]]
## BONUS  

text[[90, 386, 850, 405]]
4) EARTH AND SPACE Multiple Choice What is the largest of Jupiter's inner satellites?  

text[[92, 406, 323, 504]]
W) AmaltheaX) ThebeY) AdrasteaZ) MetisANSWER: W) AMALTHEA  

sub_title[[453, 533, 543, 551]]
## TOSS-UP  

text[[90, 553, 884, 592]]
5) MATHEMATICS Multiple Choice What type of prime number is formed when one takes a power of 2 and subtracts 1?  

text[[92, 593, 395, 690]]
W) Goldbach primeX) Euclidean primeY) Mersenne primeZ) Euler's primeANSWER: Y) MERSENNE PRIME  

sub_title[[461, 722, 535, 740]]
## BONUS  

text[[90, 742, 799, 781]]
5) MATHEMATICS Short Answer What is the sum of the first five prime numbers?ANSWER: 28  

sub_title[[453, 810, 543, 828]]
## TOSS-UP  

text[[90, 830, 860, 909]]
6) ENERGY Multiple Choice What is the world's largest tidal power station as of January 2014?W) Rance Tidal Power StationX) Sihwa Tidal Power Stationtext[[91, 68, 504, 128]]
Y) Race Rocks Tidal Power Station  
Z) Annapolis Royal Generating Station  
ANSWER: X) SIHWA TIDAL POWER STATION  

sub_title[[461, 158, 535, 176]]
## BONUS  

text[[90, 179, 857, 238]]
6) ENERGY Short Answer In ebb generation, what structure fills a basin at high tide and releases seawater to generate energy?  ANSWER: SLUICE GATE  

sub_title[[453, 265, 543, 283]]
## TOSS-UP  

text[[90, 285, 888, 324]]
7) BIOLOGY Multiple Choice Which of the following hormones is produced and released by the posterior pituitary gland?  

text[[92, 325, 323, 421]]
W) Oxytocin  
X) Prolactin  
Y) Growth hormone  
Z) Luteinizing hormone  
ANSWER: W) OXYTOCIN  

sub_title[[461, 454, 535, 472]]
## BONUS  

text[[90, 474, 890, 513]]
7) BIOLOGY Short Answer What structure of the brain is responsible for regulating hormone secretion by the anterior pituitary gland?  ANSWER: HYPOTHALAMUS  

text[[91, 513, 352, 531]]
ANSWER: HYPOTHALAMUS  

sub_title[[453, 560, 543, 578]]
## TOSS-UP  

text[[90, 581, 878, 620]]
8) CHEMISTRY Multiple Choice What scientist devised an electronegativity scale and won Nobel Prizes in both chemistry and peace?  

text[[92, 621, 364, 717]]
W) Amedeo Avogadro  
X) Archibald Scott Couper  
Y) John Dalton  
Z) Linus Pauling  
ANSWER: Z) LINUS PAULING  

sub_title[[461, 750, 535, 768]]
## BONUS  

text[[90, 770, 899, 809]]
8) CHEMISTRY Short Answer Ions that contain the same number of electrons are referred to by what term?  ANSWER: ISOELECTRONIC IONS  

text[[91, 809, 403, 828]]
ANSWER: ISOELECTRONIC IONS  

sub_title[[453, 857, 543, 875]]
## TOSS-UP  

text[[90, 877, 890, 916]]
9) PHYSICS Multiple Choice In special relativity, the lowercase gamma is used to symbolize what quantity?text[[91, 68, 392, 168]]
W) Speed of lightX) Inertial reference frameY) Lorentz factorZ) Euclidean factorANSWER: Y) LORENTZ FACTOR  

sub_title[[461, 199, 535, 217]]
## BONUS  

text[[90, 218, 904, 278]]
9) PHYSICS Short Answer What happens to an individual's apparent weight, when viewed by an outside observer, as the individual travels near the speed of light?ANSWER: INCREASES  

sub_title[[454, 305, 543, 323]]
## TOSS-UP  

text[[90, 324, 866, 364]]
10) EARTH AND SPACE Multiple Choice The Matterhorn exemplifies what type of glacial formation that results in an angular mountaintop?  

text[[92, 365, 360, 462]]
W) Glacial striationsX) AreteY) Glacial hornZ) CirqueANSWER: Y) GLACIAL HORN  

sub_title[[461, 494, 535, 512]]
## BONUS  

text[[90, 514, 832, 572]]
10) EARTH AND SPACE Short Answer What type of landform results from the glacial deposition of unstratified and unsorted material?ANSWER: MORAINES  

sub_title[[454, 601, 543, 619]]
## TOSS-UP  

text[[90, 620, 870, 660]]
11) MATHEMATICS Multiple Choice What is the coefficient of the 4th term in the following expression: \((3x + 2y)^5\) ?  

text[[92, 661, 250, 760]]
W) 320X) 720Y) 1440Z) 1680ANSWER: X) 720  

sub_title[[461, 791, 535, 808]]
## BONUS  

text[[90, 811, 897, 850]]
11) MATHEMATICS Short Answer List the terms that exist in the 5th row of Pascal's Triangle.ANSWER: 1, 5, 10, 10, 5, 1  

sub_title[[454, 877, 543, 895]]
## TOSS-UPtext[[90, 68, 884, 110]]
12) ENERGY Multiple Choice Humphry Davy created the first incandescent light bulb using what metal?  

text[[92, 110, 312, 210]]
W) Tungsten 
X) Iridium 
Y) Platinum 
Z) Molybdenum ANSWER: Y) PLATINUM  

sub_title[[461, 239, 535, 257]]
## BONUS  

text[[90, 259, 890, 319]]
12) ENERGY Short Answer What does the acronym ITER, a nuclear fusion research facility, stand for? ANSWER: INTERNATIONAL THERMONUCLEAR EXPERIMENTAL REACTOR  

sub_title[[454, 345, 543, 364]]
## TOSS-UP  

text[[90, 365, 864, 404]]
13) BIOLOGY Multiple Choice What enzyme is responsible for splicing out errors in DNA replication?  

text[[92, 405, 320, 504]]
W) Ligase 
X) Primase 
Y) Helicase 
Z) Nuclease ANSWER: Z) NUCLEASE  

sub_title[[461, 535, 535, 553]]
## BONUS  

text[[90, 555, 888, 614]]
13) BIOLOGY Short Answer What enzyme compensates for the shortening of chromosomal endings during eukaryotic cell replication and plays an important role in aging and cancer? ANSWER: TELOMERASE  

sub_title[[454, 640, 543, 659]]
## TOSS-UP  

text[[90, 660, 880, 800]]
14) CHEMISTRY Multiple Choice According to Le Chatelier's principle, what effect would a catalyst have on the rate of a chemical reaction? W) Increase forward reaction X) Increase backward reaction Y) Increase forward and backward reactions equally Z) Have no influence on reaction rates ANSWER: Y) INCREASE FORWARD AND BACKWARD REACTIONS EQUALLY  

sub_title[[461, 830, 535, 848]]
## BONUS  

text[[90, 850, 903, 910]]
14) CHEMISTRY Short Answer If heat is added to an endothermic reaction, in which direction does the equilibrium shift? ANSWER: RIGHT OR TOWARD THE PRODUCTSsub_title[[453, 68, 544, 86]]
## TOSS-UP  

text[[90, 88, 896, 127]]
15) PHYSICS Multiple Choice If the charge on one plate of a capacitor is \(+15\) Coulombs and the capacitance is 25000 microfarads, what is the potential energy stored in the capacitor?  

text[[92, 128, 340, 230]]
W) 9000 Joules  X) 8000 Joules  Y) 4500 Joules  Z) 18000 Joules  ANSWER: Y) 4500 JOULES  

sub_title[[461, 259, 536, 277]]
## BONUS  

text[[90, 279, 800, 339]]
15) PHYSICS Short Answer What is the potential energy stored in a spring that is compressed 4 meters from its rest position given that \(k = 50 \text{N / m}\) ?  ANSWER: 400 JOULES  

sub_title[[453, 365, 544, 383]]
## TOSS-UP  

text[[90, 384, 867, 424]]
16) EARTH AND SPACE Multiple Choice A massive star fuses with which element before undergoing core collapse and becoming a supernova?  

text[[92, 424, 263, 524]]
W) Silicon  X) Oxygen  Y) Platinum  Z) Iron  ANSWER: Z) IRON  

sub_title[[461, 555, 536, 573]]
## BONUS  

text[[90, 575, 866, 635]]
16) EARTH AND SPACE Short Answer White dwarfs typically transform into what type of supernova because they lack hydrogen?  ANSWER: TYPE I  

sub_title[[453, 661, 544, 679]]
## TOSS-UP  

text[[90, 681, 808, 720]]
17) MATHEMATICS Multiple Choice What is the fourth prime term in the Fibonacci sequence?  

text[[92, 722, 238, 820]]
W) 3  X) 7  Y) 13  Z) 89  ANSWER: Y) 13  

sub_title[[461, 850, 536, 868]]
## BONUS  

text[[90, 870, 904, 910]]
17) MATHEMATICS Short Answer Leonardo Fibonacci considered the idealized population of what animal as a model for his sequence?sub_title[[453, 115, 543, 133]]
## TOSS-UP  

text[[90, 135, 825, 175]]
18) ENERGY Multiple Choice As of January 2014, what is the largest capacity that a hydroelectric power station can generate in megawatts?  

text[[92, 175, 275, 275]]
W) 2,000 
X) 4,000 
Y) 10,000 
Z) 20,000 ANSWER: Z) 20,000  

sub_title[[461, 305, 535, 323]]
## BONUS  

text[[90, 325, 902, 384]]
18) ENERGY Short Answer What is the name of the facility in Livermore, California, that uses laser based inertial confinement to attempt nuclear fusion? ANSWER: NATIONAL IGNITION FACILITY (ACCEPT NIF)  

sub_title[[453, 411, 543, 429]]
## TOSS-UP  

text[[90, 431, 893, 470]]
19) BIOLOGY Multiple Choice What gaseous hormone promotes fruit ripening and flowering in pineapples?  

text[[92, 471, 325, 568]]
W) Ethylene 
X) Methylene 
Y) Cytokinins 
Z) Abscisic acid ANSWER: W) ETHYLENE  

sub_title[[461, 602, 535, 619]]
## BONUS  

text[[90, 621, 820, 660]]
19) BIOLOGY Short Answer What is the predominant natural auxin in plants called? ANSWER: INDOLEACETIC ACID OR IAA  

sub_title[[453, 688, 543, 705]]
## TOSS-UP  

text[[90, 708, 896, 747]]
20) CHEMISTRY Multiple Choice What indicator is blue above a pH of 7.6, and yellow below a pH of 6.0?  

text[[92, 748, 293, 787]]
W) Bromophenol Blue 
X) Litmus  

text[[92, 789, 285, 807]]
Y) Bromothymol Blue  

text[[92, 809, 262, 826]]
Z) Phenolphthalein  

text[[90, 829, 401, 847]]
ANSWER: BROMOTHYMOL BLUE  

sub_title[[461, 877, 535, 895]]
## BONUStext[[88, 68, 888, 108]]
20) CHEMISTRY Short Answer What type of titration is used when the endpoint of a normal titration is difficult to identify?  

text[[90, 108, 456, 127]]
ANSWER: BACK/REVERSE TITRATION  

sub_title[[454, 155, 543, 173]]
## TOSS-UP  

text[[90, 175, 805, 215]]
21) PHYSICS Multiple Choice A single fission reaction with uranium-235 produces approximately how much energy?  

text[[92, 216, 295, 315]]
W) 100 MeV 
X) 200 MeV 
Y) 300 MeV 
Z) 400 MeV ANSWER: X) 200 MeV  

sub_title[[464, 346, 535, 364]]
## BONUS  

text[[88, 366, 908, 425]]
21) PHYSICS Short Answer What chemical element has an atomic number 90, is named after a Norse god, and is used as a substitute nuclear fuel? ANSWER: THORIUM  

sub_title[[454, 452, 543, 470]]
## TOSS-UP  

text[[88, 472, 866, 512]]
22) EARTH AND SPACE Multiple Choice What planet has the highest albedo in the solar system?  

text[[92, 512, 280, 610]]
W) Earth 
X) Mars 
Y) Mercury 
Z) Venus ANSWER: Z) VENUS  

sub_title[[464, 641, 535, 659]]
## BONUS  

text[[88, 661, 908, 720]]
22) EARTH AND SPACE Short Answer An albedo value of 0 indicates that a surface has what property? ANSWER: PERFECT/IDEAL ABSORPTION  

sub_title[[454, 747, 543, 765]]
## TOSS-UP  

text[[88, 767, 880, 806]]
23) MATHEMATICS Multiple Choice If set A contains all factors of 12 and set B contains all prime numbers, what numbers are in the intersection of set A and set B?  

text[[92, 807, 243, 905]]
W) 1,2,4 
X) 2,3,6 
Y) 2,3 
Z) 2,3,6,7 ANSWER: Y) 2,3sub_title[[460, 98, 535, 115]]
## BONUS  

text[[90, 118, 856, 178]]
23) MATHEMATICS Short Answer What principle states that a proper subset of S is any subset of S other than S itself? ANSWER: PRINCIPLE OF EXTENSIONALITY  

sub_title[[452, 205, 543, 223]]
## TOSS-UP  

text[[90, 225, 872, 365]]
24) ENERGY Multiple Choice What type of batteries depend on the reaction between zinc and manganese dioxide?  W) Lithium-ion batteries  X) Daniell batteries  Y) Alkaline batteries  Z) Bunsen batteries  ANSWER: Y) ALKALINE BATTERIES  

sub_title[[460, 394, 535, 411]]
## BONUS  

text[[90, 414, 907, 473]]
24) ENERGY Short Answer What is the atomic mass of the plutonium isotope most commonly used in nuclear fission? ANSWER: 239  

sub_title[[452, 500, 543, 518]]
## TOSS-UP  

text[[90, 520, 875, 660]]
25) BIOLOGY Multiple Choice What hormone stimulates the release of digestive enzymes from the pancreas?  W) Secretin  X) Cholecystokinin  Y) Cytokinins  Z) Gastrin  ANSWER: X) CHOLECYSTOKININ  

sub_title[[460, 690, 535, 707]]
## BONUS  

text[[90, 710, 895, 770]]
25) BIOLOGY Short Answer What hormone promotes the breakdown of glycogen in the liver and the release of glucose into the blood?  ANSWER: GLUCAGON