
## TOSS-UP  


1) Math – Short Answer Short Answer What is the remainder when \(25^{3}\) is divided by 7?  


ANSWER: 1  


## BONUS  


1) Math – Short Answer What are the solutions for z given the equation \(z^2 - 8i = 0\), answer expressed in polar form?  


ANSWER: \(\sqrt{2} + i\sqrt{2}\) and \(-\sqrt{2} - i\sqrt{2}\)  


## TOSS-UP  


2) Biology – Multiple Choice Which of the following fixing agents is used to fix lipid membranes and their associated proteins?  


W) Glutaraldehyde 
X) Acrolein 
Y) Osmium Tetroxide 
Z) Formaldehyde  


ANSWER: Y) Osmium Tetroxide  


## BONUS  


2) Biology Multiple Choice Which of the following is most likely to occur if additional Bcd protein is introduced into a D. melanogaster embryo?  


W) The cephalic furrow forms posterior to where it would normally form 
X) The cephalic furrow forms anterior to where it would normally form 
Y) The cephalic furrow forms dorsal to where it would normally form 
Z) The cephalic furrow forms ventral to where it would normally form  


ANSWER: W) The cephalic furrow forms posterior to where it would normally form
## TOSS-UP  


hemistry – Multiple Choice When phenyl trimethyl silane is treated with AlCl3 and Cl2, in h of the following positions does substitution occur on?  


W) Ipso X) Ortho Y) Meta Z) Para  


ANSWER: W) Ipso  


## BONUS  


3) Chemistry – Multiple Choice Leaving groups such as Cl attached to a beta carbon of an alkyl silane are more prone to leaving when compared to plain alkanes. Which of the following interactions best explains why?  


W) Si-C sigma to Cl-C sigma\* X) Si-C sigma to Cl-C sigma Y) Si nonbonding to Cl-C sigma\* Z) Si nonbonding to Cl-C sigma  


ANSWER: W) Si-C sigma to Cl-C sigma\*  


## TOSS-UP  


4) Earth and Space – Short Answer Identify all of the following three choices which would be much more common in a starburst galaxy than the milky way.  


1) supernovae 
2) x-rays from galactic nuclei 
3) stellar winds  


ANSWER: 1 and 3  


## BONUS
4) Earth and Space - Short Answer In simplest radical form, what is the redshift of a star that is moving away from the viewer at a speed of \(0.5c\) ?  


ANSWER: \(\sqrt{3} - 1\)  


## TOSS-UP  


5) Physics – Multiple Choice A sphere of radius R is rolling without spinning, and its center of mass is moving to the right at speed v. What is the relative speed between the ground and the very top of the sphere?  


W) 0 X) v/2 Y) v Z) 2v  


ANSWER: Z) 2v  


## BONUS  


5) Physics – Multiple Choice The speed of the center of mass of an object rolling without slipping is v. Given that it rolls up a hill to a maximum height of \(3v^2 /4g\) , which of the following could be the identity of the object?  


W) a solid sphere 
X) a hollow sphere 
Y) a solid cylinder 
Z) a solid hoop  


ANSWER: Y) A SOLID CYLINDER  


## TOSS-UP  


6) Energy – Short Answer Scientists at CERN are using fermi dirac statistics to study the trajectory of particles after a collision. Identify all of the following three particles which they could have been studying:
1) J/psi Pentaquark 
2) K+ 
3) Omega - 


ANSWER: 1 and 3 


## BONUS 


6) Energy – Short Answer Scientists at CERN are researching the decay of the proton, which seems to violate the conservation of baryon number. Identify all of the following reactions which conserve baryon number (* = antiparticle); 


1) K+ → e+ + v_e* [Read as: Positive Kaon yields positron + electron antineutrino]
2) pi+ + e- → p+ + K- + v_e [Read as: Positive pion plus electron yields proton plus kaon + electron neutrino]
3) lambda 0 → pi0 + v_tau [Read as: neutral Lambda yields neutral pion and tau neutrino] 


ANSWER: 2 and 3 


## TOSS-UP 


7) Math - Multiple Choice Which of the following is equal to the limit \((1+4/n)^{n/2}\) as n approaches infinity? 


W) e<sup>1/2</sup>
X) e
Y) e<sup>2</sup>
Z) e<sup>4</sup> 


ANSWER: Y) e<sup>2</sup> 


## BONUS 


7) Math - Short Answer Rohan needs to design a closed cylindrical can that holds 475 cubic centimeters of fluid to store his viagra pills. What is the smallest radius possible that would require the least amount of material? 


ANSWER: sqrt(475/2pi)
## TOSS-UP  


8) Biology – Short Answer Identify all of the following three statements about snoRNAs which are true:  


1) They direct cleavage of pre-rRNA  
2) They Guide \(2'\) -O-methylation  
3) They are known to form pseudo knots with the target RNA  


ANSWER: All  


## BONUS  


8) Biology – Multiple Choice Nipun goes to a doctor’s office with extremely low hematocrit, proteinuria, and a low blood pressure. Which of the following is the most likely explanation of this man’s conditions?  


W) Failing kidneys leading to a lack of EPO  
X) Chronic lymphocytic leukemia in red bone marrow  
Y) Megaloblastic anemia caused by lack of folate  
Z) Polycythemia vera in red bone marrow  


ANSWER: W) Failing kidneys leading to a lack of EPO  


## TOSS-UP  


9) Chemistry – Multiple Choice For the photoelectric effect, if the frequency of the incident light is doubled, which one of the following could be the ratio of the final Kinetic Energy to the original Kinetic Energy of the ejected electrons?  


W) 1/2  
X) 1  
Y) 1.4  
Z) 2.7
ANSWER: Z) 2.7  


## BONUS  


9) Chemistry – Short Answer A hole in a certain lattice can be modeled as a flat square, with an anion on each corner with radius r. Given that the side length of each square is \(2r\), and a cation can occupy the center of the hole, what is the radius ratio of the cation to the anion  


ANSWER: \(\sqrt{2} - 1\)  


## TOSS-UP  


10) Earth and Space – Short Answer Order the following three rocks from increasing grain size.  


1) migmatite 
2) slate 
3) phyllite  


ANSWER: 2 3 1  


## BONUS  


10) Earth and Space – Short Answer A planet is circularly orbiting a star at radius r. The planet very slowly loses mass to \(50\%\) of its original mass. If the orbit stays circular, what will be the new orbital radius \(r_2\) in terms of r.  


ANSWER: 4r  


## TOSS-UP  


11) Physics – Multiple Choice In a Clash Royale match, a hidden Tesla is triggered by an incoming minion. The tesla contains a massive negative point charge, and when it is triggered, moves up with constant velocity. Which of the following statements is true about this scenario.  


W) If the minion is directly above the Tesla, it feels an electric field but not a magnetic field X) If the minion is directly above the Tesla, it feels a magnetic field but not an electric field Y) If the minion is directly above the Tesla, it feels both an electric field and a magnetic field
Z) If the minion is directly above the Tesla, it feels neither an electric field or a magnetic field  


ANSWER: W) If the minion is directly above the Tesla, it feels an electric field but not a magnetic field  


## BONUS  


11) Physics – Short Answer Four identical positive charges are placed and held in place at the vertices of a square. One of the charges is released and travels away from the arrangement while the other charges are kept stationary. Given that the energy of the original four-charge arrangement was E, what is the kinetic energy of the released charge at a very large distance away from the other charges in terms of E?  


ANSWER: - E/2  


## TOSS-UP  


12) Energy – Short Answer Scientists are studying the effect of heating and cooling graphene to extremes. Similar to Helium, it is found that when heated, graphene also freezes its electrons at place. For this to be most observable, scientists had to turn each parallel graphene sheet by 5 degrees and the sheets out of plane, to create what pattern?  


ANSWER: Moire Pattern  


## BONUS  


12) Energy - Short Answer Scientists are studying the effects of heating and cooling graphene to the extremes. In their research they also studied the effects of heating and cooling on He-3, to compare and contrast both materials. They encountered that upon heating, liquid Helium solidified, as the entropy of solid helium is greater than that of liquid helium. What effect best describes this phenomenon?  


ANSWER: Pomeranchuk Effect  


## TOSS-UP  


13) Math – Short Answer Which of the following shapes would the equation \(r = a\theta\) in the polar plane be of?
W) Rose  X) Cardioid  Y) Limacon  Z) Spiral  


ANSWER: Z) Spiral  


## BONUS  


13) Math – Short Answer If x=1+2^p and y=1+2^(-p), what is y in terms of x as a fraction?  


ANSWER: x/(x- 1)  


## TOSS-UP  


14) Biology – Short Answer What specific motor cells in grass leaves control the rolling and unrolling of the blade in response to changes in water potential?  


ANSWER: Bulliform cells  


## BONUS  


14) Biology – Short Answer An unusual substance, called Vishwalium, acts as a reversible inhibitor of carbonic anhydrase. Vishwalium, interestingly, increases the rate \(k_{\text{cat}}\) of the enzyme, but significantly reduces the affinity of carbonic anhydrase to its substrate. Name all of the following changes that would be seen on a double-reciprocal plot as a result  


1) The x-intercept would shift to the left  
2) The slope of the line would increase  
3) The y-intercept of the plot would decrease  


ANSWER: 2 and 3  


## TOSS-UP  


15) Chemistry – Multiple Choice Which of the following reagents, when used on an alpha beta unsaturated carbonyl produces an intermediate that will undergo the mannich reaction with dimethyl amine and formaldehyde?
W) Trifluoroacetic acidX) Dimethyl formamideY) 2,3-Dichloro-5,6-dicyano-1,4-benzoquinoneZ) DABCO  


ANSWER: Z) DABCO  


## BONUS  


15) Chemistry – Short Answer Shohom is trying to make dopamine. In his synthesis, he is required to form 5 amino 4 hydroxy 2 methoxy phenol from para hydroxy phenol. Order all of the following three reagents in order at which they should be used starting on phenol;  


1) FeBr3, Br2  
2) Amalgamated Zinc, H3O+  
3) MeO-  
4) HNO3, H2SO4  


ANSWER: 1 4 3 2  


## TOSS-UP  


16) Earth and Space – Short Answer Identify all of the following three quantities, when varied, would change the transit depth of an exoplanet-star system?  


1) diameter of the planet  
2) mass of the planet  
3) orbital radius of the planet  


ANSWER: 1  


## BONUS  


16) Earth and Space - Short Answer Identify all of the following three statements which are true of the hill sphere:  


1) The outer shell of the hill sphere constitutes a zero-velocity surface
2) It lies between the 2 and 3 lagrange points  
3) Beyond the sphere the object deforms due to tidal forces  


ANSWER: 1 only  


## TOSS-UP  


17) Physics – Short Answer Consider a hollow cylindrical shell of length L and uniform surface charge density sigma, rotating at angular velocity omega. Assuming L is much larger than the radius of the shell, then by name or number, indicate all of the following three changes to the shell that would increase the magnitude of the magnetic field at the center of the shell:  


1) increasing sigma  
2) increasing omega  
3) increasing L  


ANSWER: 1 AND 2  


## BONUS  


"physics – Short Answer Consider a diatomic molecule with moment of inertia \(2.6 \times 10^{- 36}\) \(n^2\) . What is the energy difference between the third and fourth excited rotational states, in terms of the reduced planck's constant  


ANSWER: \(3.1 \times 10^{- 36} \text{h}^2\)  


## TOSS-UP  


18) Energy – Short Answer Researchers at the University of Michigan Rogel Cancer Center have taken a promising new approach to targeting STAT3 – developing a small-molecule compound that harnesses the power of a natural cellular "cleanup" system to get rid of what type of cancer, which has Burkitt and Hodgkins forms.  


ANSWER: Lymphoma  


## BONUS
18) Energy – Multiple Choice Physicists at Princeton Plasma Physics Lab have discovered a new way to measure high energy density plasmas. Which of the following statements is not true about plasmas in general.  


W) The higher the density of a plasma, the less energy required for a fusion reaction to proceed X) The debye length characterizes the influence of a charge in a plasma Y) Particles in a plasma approximately follow the Fermi - Dirac distribution Z) Maxwell's laws can be treated as being governed by Maxwell's laws and the Navier Stokes equation  


ANSWER: Y) Particles in a plasma approximately follow the Fermi - Dirac distribution  


## TOSS-UP  


19) Math - Short Answer What is the shortest altitude in the triangle with side lengths 15 20 25?  


ANSWER: 12  


## BONUS  


19) Math - Short Answer What is the simplest value of the expression sqrt(8+sqrt(28)) - sqrt(8-sqrt(28))?  


ANSWER: 2  


## TOSS-UP  


20) Biology – Short Answer What type of synapse is characterized by being located on the axon terminal of another synapse?  


ANSWER: Axo- axonic synapse  


## BONUS  


20) Biology – Short Answer Name each of the following enzymes based on their function in genomic regulation
1) Catalyzes strand separation of dsRNA into single strands that it uses to target certain mRNAs and prevent their expression  
2) Cuts dsRNA from genes like lin-4 into short strands that are used in gene regulation  
3) Channel protein that allows dsRNA to leave the nucleus and enter the cytoplasm  


ANSWER: 1) RISC 2) DICER 3) Exportin-5  


## TOSS-UP  


21) Chemistry – Multiple Choice Compound Z decays into compound Y with a rate constant of \(12L \wedge 2 / \mathrm{mol} \wedge 2 \mathrm{s}\) . If it takes 10M D 50 seconds for half of Z to decay into Y, then how much time would it take 10 M Z to decay to \(1.25 \mathrm{M} \mathrm{Z}\)  


W) 88.5 seconds  
X) 150 seconds  
Y) 350 seconds  
Z) 1050 seconds  


ANSWER: Z) 1050 seconds  


## BONUS  


21) Chemistry – Short Answer Metal Clathrates can be modeled as coordination complexes with two sets of ligands. The metal clathrate of AuI4- has the Iodide in a square planar geometry, and is not directly bonded to, but rather neighbored by 6 H2O in an octahedral geometry, where the iodine and water are offset by 45 degrees. Given that H2O is a stronger ligand than I-, rank all of the following three orbitals by increasing energy; 1) \(\mathrm{dz} \wedge 2 2) \mathrm{dx} \wedge 2 - \mathrm{y} \wedge 2 3) \mathrm{dy}\)  


ANSWER: 2 3 1  


## TOSS-UP  


22) Earth and Space – Multiple Choice Which of the following is true regarding magma and lava.  


W) Most intraplate volcanism occurs due to divergent plates spreading and letting out magma
X) Increased water vapor content tends to make eruptions less explosiveY) A sudden decrease in pressure can cause rock to melt and form magmaZ) The tendency to form pyroclasts in magma is inversely related to its silica content  


ANSWER: Y) A sudden decrease in pressure can cause rock to melt and form magma  


## BONUS  


22) Earth and Space – Short Answer Determine whether each of the following three choices is characteristic of El Nino or La Nina.  


1 Formation of tropical cyclones on the equator  


2 Droughts in South America  


3 Increased rainfall in Australia  


ANSWER: 1) El Niño 2) La Niña 3) La Niña  


## TOSS-UP  


23) Physics – Multiple Choice A particle of mass m is traveling at 60% of the speed of light. What percent of its total energy is composed of its rest energy?  


W) 20 X) 40 Y) 60 Z) 80  


ANSWER: Z) 80  


## BONUS  


23) Physics – Short Answer Consider two satellites A and B of the same mass that travel in circular orbits around a massive planet. Given that the orbit radius of satellite A is greater than that of satellite B, indicate all of the following three statements that are true, ignoring the gravitational attraction between the two satellites:  


1) the magnitude of the angular momentum of satellite A about the planet is greater than that of satellite B 
2) the magnitude of the linear momentum of satellite A is greater than that of satellite B 
3) the kinetic energy of satellite A is greater than that of satellite B
ANSWER: 1 ONLY  


## TOSS-UP  


24) Energy – Short Answer Researchers at Idaho National lab are developing a fission surface power system for lunar power applications. What is the power of this system if the rover starts with \(5 \times 10^{2} \mathrm{~kg}\) of plutonium which is linearly depleted until there is none left after \(5 \times 10^{10}\) seconds.  


ANSWER: \(9 \times 10^{8}\) (watts)  


## BONUS  


24) Energy – Short Answer Scientists at ARC are studying the nuclear Overhauser Effect in hopes of furthering the applications of NMR to biological fields. To what power of r does the Nuclear Overhauser drop off at?  


ANSWER: - 6