
# Iolani Science Bowl Invitational Round Robin 2  


## Tossup  


Earth and Space - Multiple Choice What crystal habit, often displayed by tremolite and actinolite, is known to cause lung cancer due to the extremely small needles created?  


W) Hopper 
X) Bladed 
Y) Tabular 
Z) Asbestiform  


Answer: Z) ASBESTIFORM [RE]  


## Bonus  


Earth and Space - Multiple Choice Brennan the geologist is studying Earth's interior using seismic waves. Which of the following of Earth's layers can S waves NOT travel through?  


W) Crust 
X) Mantle 
Y) Outer Core 
Z) Inner Core  


Answer: Y) OUTER CORE [RE]  


## Tossup  


Biology - Short Answer Brennan is breeding Puffles where color is controlled by a single allele. He notices when he crosses a true- breeding strain of blue Puffles with a true- breeding strain of red Puffles, some of the progeny are purple. What term describes the relationship between the blue and red alleles?  


Answer: INCOMPLETELY DOMINANT (ACCEPT: INCOMPLETE DOMINANCE)  


## Bonus  


Biology - Short Answer What is the maximum number of molecules of \(\mathrm{O}_2\) that hemoglobin can bind to?  


Answer: 4  


Tossup
Chemistry - Short Answer How many moles of water would you expect to form from reacting one mole of glucose in excess oxygen to produce water and carbon dioxide?  


Answer: 6 [JK]  


## Bonus  


Chemistry - Short Answer A sample of \(\mathrm{SO}_2\) gas takes 20 seconds to effuse through a porous plug. If the molar mass of \(\mathrm{SO}_2\) is 64 grams per mole, and the molar mass of helium gas is 4 grams per mole, how long, in seconds, would it take the same amount of helium to effuse through the plug?  


Answer: 5 (seconds) [AI]  


## Tossup  


Math - Short Answer Brennan the coordinate mathematician is studying how to strictly define geometric elements off a certain set of points. How many points must he use to strictly define a plane?  


Answer: 3 [RE]  


## Bonus  


Math - Short Answer Michael, Ryan, Samuel, Alan, and Gina are seated around a table. How many ways are there to arrange them if Gina and Alan must sit next to each other?  


Answer: 12 [RE]  


## Tossup  


Physics - Short Answer What phenomenon occurs when a photon incident on a material ejects an electron?  


Answer: PHOTOELECTRIC EFFECT [RE]  


## Bonus  


Physics - Short Answer What term denotes the minimum energy required to release an electron in the photoelectric effect?  


Answer: WORK FUNCTION [RE]  


## Tossup  


Earth and Space - Multiple Choice Which of the following stars is not on the Main Sequence?
W) SiriusX) Betelgeuse [beetle- juice]Y) The SunZ) Vega  


Answer: X) BETELGEUSE [AE]  


## Bonus  


Earth and Space - Multiple Choice Which of the following is not a dwarf planet?  


W) Chariklo (char- ee- klo)X) PlutoY) Haumea (how- may- ah) (it's Hawaiian!)Z) Ceres (seer- ees)  


Answer: W) CHARIKLO [AE]  


## Tossup  


Biology - Short Answer Identify all of the following four organelles which have a double- membrane:  


I - NucleusII - Golgi ApparatusIII - MitochondriaIV - Chloroplast  


Answer: I, III, IV  


## Bonus  


Biology - Short Answer Identify all of the following four characteristics that all members of Chordata possess.  


I - NotochordII - BackboneIII - Pharyngeal SlitsIV - Post- Anal Tail  


Answer: I, III, IV  


## Tossup  


Chemistry - Multiple Choice A molecule with many unpaired electrons can be described as which of the following?
W) Paramagnetic 
X) Diamagnetic 
Y) Supermagnetic 
Z) Undermagnetic  


Answer: W) PARAMAGNETIC [JK]  


## Bonus  


Chemistry - Short Answer Identify all of the following three types of intermolecular forces that are present between hydrogen sulfide molecules.  


I. London dispersion forces 
II. Dipole-dipole forces 
III. Hydrogen bonding  


Answer: I and II  


## Tossup  


Math - Short Answer What is the value of \(\mathrm{arcsin}(0.5)\) in radians?  


Answer: PI/6 [RE]  


## Bonus  


Math - Multiple Choice Which of the following is the correct decimal expansion of \(2 / 7\) ?  


W) 0.142857 repeating 
X) 0.275481 repeating 
Y) 0.285714 repeating 
Z) 0.314832 repeating  


Answer: Y) 0.285714 REPEATING [RE]  


## Tossup  


Physics - Short Answer Brennan stands 6 meters away from a plane mirror. If he then proceeds to run away from his image at a blazing \(10\mathrm{m / s}\) , at what speed does Brennan perceive his image as moving away from him?
Answer: 20 m/s [RE]  


## Bonus  


BonusPhysics - Short Answer A ball is launched with velocity 10 m/s at an angle of 45 degrees. Neglecting air resistance and taking gravity as 10 m/s^2, how far does the ball travel before hitting the ground again?  


Answer: 10 METERS [RE]  


## Tossup  


TossupEarth and Space - Multiple Choice Brennan the meteorologist is responsible for telling locals what the weather will be. Sensors picked up that air temperature suddenly dropped and clouds with significant vertical development began forming. What type of weather can he expect?  


W) Light RainX) Warm breezesY) Radiation fogZ) Thunderstorms  


Answer: Z) THUNDERSTORMS [RE]  


## Bonus  


BonusEarth and Space - Multiple Choice Which of the following oceans does the Nazca Plate primarily underlie?  


W) The AtlanticX) The PacificY) The IndianZ) The Arctic  


Answer: X) THE PACIFIC [RE]  


## Tossup  


TossupBiology - Short Answer What term describes the interaction between a clownfish and an anemone, where both parties benefit?  


Answer: MUTUALISM
## Bonus  


Biology - Short Answer Brennan is studying a particular strain of yeast where color is controlled by a single gene. Brennan induces a substitution of a nucleotide in this gene but notices the yeast stay the same color. What term best describes the mutation Brennan caused in the yeast?  


Answer: SILENT MUTATION (Accept: Synonymous)  


## Tossup  


Chemistry - Short Answer In the Lewis structure for hydrogen sulfide, how many lone pairs are present?  


Answer: 2 (pairs) [AI]  


## Bonus  


Chemistry - Short Answer 84 g of a pure sample of a hydrocarbon contains 72 g of carbon. What is the empirical formula of this molecule?  


Answer: CH2 [JK]  


## Tossup  


Math - Short Answer What is the exterior angle of a regular 6- sided polygon?  


Answer: 60 degrees [RE]  


## Bonus  


Math - Multiple Choice What is the limit of the function with numerator \(\mathrm{x}^{\wedge}2 + 5\mathrm{x} + 4\) and denominator \(\mathrm{x}^{\wedge}2 + 9\mathrm{x} + 20\) as \(\mathrm{x}\) approaches - 4?  


W)- 1 X)- 2 Y)- 3 Z)- 4  


Answer: Y)- 3 [RE]  


## Tossup  


Physics - Short Answer A block of mass \(5\mathrm{kg}\) is attached via a string to a \(15\mathrm{kg}\) mass. Taking gravitational acceleration to be \(10\mathrm{m / s}^{\wedge}2\) , if the string is then placed over a massless pulley, forming a simple Atwood machine, what is the acceleration of the two blocks?
Answer: 5 m/s^2 [RE]  


## Bonus  


Physics - Multiple Choice A thermodynamic process is graphed as a curve on a P- V diagram. Which of the following quantities is given by the area under the curve?  


W) Heat 
X) Internal Energy 
Y) Temperature 
Z) Work  


Answer: Z) WORK [RE]  


## Tossup  


Earth and Space - Short Answer What is the name for large regions of ionized hydrogen, in which star formation has often recently taken place?  


Answer: H- II REGION [AE]  


## Bonus  


Earth and Space - Multiple Choice If the universe's density were greater than the critical density of the universe, what shape would the universe have?  


W) Open 
X) Closed 
Y) Ajar 
Z) Flat  


Answer: X) CLOSED [AE]  


## Tossup  


Biology - Short Answer What term describes gaps in the myelin sheath of a neuron?  


Answer: NODES OF RANVIER  


## Bonus  


Biology - Multiple Choice Which of the following traits would you NOT expect to observe in a monocot?
W) Parallel venation in leaves  
X) Flowers with six petals  
Y) Vascular bundles arranged in a ring  
Z) Fibrous root system  


Answer: Y) VASCULAR BUNDLES ARRANGED IN A RING  


## Tossup  


Chemistry - Short Answer Identify all of the following liquids, which, when used as the mobile phase in thin layer chromatography on cellulose paper, would travel further than ethanol.  


I. Hexanes;  
II. Ammonia;  
III. Water  


Answer: I only [RE]  


## Bonus  


Chemistry - Short Answer What name is given to the famous mixture of nitric acid and sulfuric acid, capable of dissolving gold?  


Answer: AQUA REGIA [RE]  


## Tossup  


Math - Short Answer Identify all of the following 4 shapes that must have perpendicular diagonals.  


I. Square;  
II. Parallelogram;  
III. Kite;  
IV. Rhombus
Answer: I, III, IV [RE]  


## Bonus  


Math - Short Answer A 6 sided dice is rolled twice. What is the probability that the sum of the two numbers is a perfect square?  


Answer: 7/36 [RE]  


## Tossup  


Physics - Short Answer Brennan exerts a 20 newton force on a \(2\mathrm{kg}\) block initially at rest over a distance of 5 meters. What is the final velocity of the block in \(\mathrm{m / s}\) ?  


Answer: \(10\mathrm{m / s}\) [RE]  


## Bonus  


Physics - Multiple Choice Scientists building extremely powerful microscopes have been limited by the wavelength of light. Instead they've turned to using what subatomic particle instead of photons?  


W) Electrons X) Gluons Y) Neutrinos Z) Neutrons  


Answer: W) ELECTRONS [RE]