
# Iolani Science Bowl Invitational Round Robin 3  


## Tossup  


Earth and Space - Short Answer Identify all of the following types of fronts that require at least 2 cold air masses to be present? I. Cold; II. Warm; III. Occluded  


Answer: III only [RE]  


## Bonus  


Earth and Space - Short Answer What name is given to the steeply sloping section of a subducting plate where a large number of earthquakes originate from?  


Answer: WADATI- BENIOFF ZONE [RE]  


## Tossup  


Biology - Multiple Choice Brennan is tracking the fate of the carbons in a glucose molecule in both eukaryotes and prokaryotes. To distinguish these carbons, he adds radioactive Carbon- 13 glucose to cultures of the cells of interest. Which of the following molecules would Brennan NOT expect to be radioactive?  


W) Pyruvate X) Acetyl CoA Y) Ethanol Z) NADH  


Answer: Z) NADH  


## Bonus  


Biology - Short Answer If the embryo of an angiosperm has 32 chromosomes, how many chromosomes does the endosperm have?  


Answer: 48
Chemistry - Short Answer What is the oxidation number of the chlorine atom in a perchlorate ion?  


Answer: \(+7\) (Accept: 7) [AI]  


## Bonus  


BonusChemistry - Short Answer According to Molecular Orbital Theory, oxygen gas has how many anti- bonding electrons?  


Answer: 6 [JK]  


## Tossup  


TossupMath - Short Answer What is the value of \(\sin (30^{\circ})^{\wedge}2 + \cos (30^{\circ})^{\wedge}2\) [sin squared 30 degrees plus cosin squared 30 degrees] in simplest radical form?  


Answer: 1 [RE]  


## Bonus  


BonusMath - Multiple Choice Brennan the metal worker creates an aluminum sphere of radius 5 meters. If he then proceeds to melt the sphere and cast it into cubes of side length 5 meter, how many cubes can he make?  


W) 1 X) 2 Y) 3 Z) 4  


Answer: Z) 4 [RE]  


## Tossup  


TossupPhysics - Short Answer What name is given to the phase transition between solid and gas?  


Answer: SUBLIMATION [RE]  


## Bonus  


BonusPhysics - Short Answer What principle states that a change in pressure is transmitted to the rest of the fluid undiminished?  


Answer: PASCAL'S PRINCIPLE [RE]  


Tossup
Earth and Space - Short Answer What is the name for the region on the HR diagram where Cepheid (se- fee- id) and RR Lyrae (lee- ray) variable stars lie?  


Answer: INSTABILITY STRIP [AE]  


## Bonus  


Earth and Space - Short Answer What is the name for the radius of a black hole's event horizon?  


Answer: SCHWARZSCHILD RADIUS [AE]  


## Tossup  


Biology - Multiple Choice Which of the following macromolecule groups contains both nitrogen and phosphorus?  


W) Carbohydrates X) Proteins Y) Lipids Z) Nucleic Acids  


Answer: Z) NUCLEIC ACIDS  


## Bonus  


Biology - Multiple Choice As a competitor listens to a science bowl question, their sympathetic nervous system activates. Which of the following is not a result of sympathetic nervous system activation?  


W) Increased Heart Rate 
X) Widened Bronchial Passages 
Y) Pupil Constriction 
Z) Blood Vessel Constriction  


Answer: Y) PUPIL CONSTRICTION
Chemistry - Multiple Choice Which of the following atoms would require the most energy to remove an electron from?  


W) N 
X) \(\mathrm{N}^{+}\) Y) F 
Z) \(\mathrm{F}^{+}\)  


Answer: Z) \(\mathrm{F}^{+}\) [AI]  


## Bonus  


Chemistry - Multiple Choice Which of the following acids is not polyprotic?  


W) Carbonic Acid  


X) Oxalic Acid  


Y) Phosphoric Acid  


Z) Nitric Acid  


Answer: Z) NITRIC ACID [AE]  


## Tossup  


Math - Multiple Choice The magnitude of the cross product between two vectors is maximized when the angle between the two vectors is what?  


W) 0 degrees  


X) 45 degrees  


Y) 90 degrees  


Z) 180 degrees  


Answer: Y) 90 DEGREES [RE]  


## Bonus  


Math - Multiple Choice The sum of an infinitely decreasing geometric series is 1. If its first term is x, what is the common ratio in terms of x?  


W) x + 1  


X) x  


Y) 1 - x  


Z) x^2  


Answer: Y) 1 - x [RE]  


## Tossup
Physics - Short Answer The Stefan- Boltzmann law states that the radiative intensity of a blackbody is proportional to the temperature raised to what power?  


Answer: 4 [RE]  


## Bonus  


Physics - Short Answer Brennan's car is moving at \(25~\mathrm{m / s}\) and suddenly stops over a distance of 1 meter. How many g's does Brennan experience rounded to the nearest g?  


Answer: 32 [RE]  


## Tossup  


Earth and Space - Multiple Choice The Enhanced Fujita Scale was developed to describe the intensity of which of the following phenomena?  


W) Tornadoes  X) Earthquakes  Y) Volcanic Eruptions  Z) Hurricanes  


Answer: W) TORNADOES [RE]  


## Bonus  


Earth and Space - Multiple Choice Which of the following best explains why building a well on a confined aquifer is advantageous to building onto an unconfined aquifer?  


W) Confined aquifers are more protected from polluted rainwater  X) The recharge time of confined aquifers is much quicker  Y) Confined aquifers are pressurized so water doesn't need to be pumped to the surface  Z) Confined aquifers are typically much larger  


Answer: Y) CONFINED AQUIFERS ARE PRESSURIZED SO WATER DOESN'T NEED TO BE PUMPED TO THE SURFACE [RE]
Biology - Short Answer What is the maximum observable recombination frequency between two genes on the same chromosome?  


Answer: \(50\%\) (Accept: 0.5)  


## Bonus  


Biology - Short Answer Order the following three chambers of the heart based on the order blood will flow through them after it has exited the left atrium: I - Left Ventricle, II - Right Atrium, III - Right Ventricle  


Answer: I, II, III  


## Tossup  


Chemistry - Short Answer Given a reaction with constant concentrations of the reactants, the reaction rate of aqueous barium chloride with silver nitrate to form barium nitrate and silver chloride is proportional to the concentration of silver chloride raised to what power?  


Answer: 0 [RE]  


## Bonus  


Chemistry - Multiple Choice Which of the following best describes the trend in melting point as you move across the group on the periodic table?  


W) Always increases 
X) Always decreases 
Y) Increases towards the middle 
Z) Decreases towards the middle  


Answer: Y) INCREASES TOWARDS THE MIDDLE [RE]
Math - Short Answer The ratio of consecutive terms in the Fibonacci sequence approaches which of the following mathematical constants?  


W) e 
X) Pi 
Y) i 
Z) The Golden Ratio  


Answer: Z) THE GOLDEN RATIO [RE]  


## Bonus  


Math - Short Answer Suppose that an equilateral triangle simultaneously has a circle inscribed and circumscribed about it. What is the ratio of the area of the circumscribed circle to that of the inscribed circle?  


Answer: 4 (Accept: 4 to 1) [RE]  


## Tossup  


Physics - Short Answer What color does a red shirt primarily reflect?  


Answer: RED [RE]  


## Bonus  


Physics - Short Answer 5, 1 farad capacitors are wired in series. How much charge, in coulombs, is stored across all the capacitors if they are then connected to a 10V battery?  


Answer: 50 COULOMBS [RE]
Earth and Space - Multiple Choice Which of the following is not a requirement for a celestial body to be classified as a planet?  


W) It's in hydrostatic equilibrium  
X) It has cleared its orbit of debris  
Y) Its mass is at least \(10\%\) of Earth's  
Z) It directly orbits its central star  


Answer: Y) ITS MASS IS AT LEAST \(10\%\) OF EARTH'S [AE]  


## Bonus  


Earth and Space - Short Answer Order the following four planets by mass in increasing order. I. Earth; II. Mars; III. Jupiter; IV. Saturn  


Answer: II, I, IV, III [AE]  


## Tossup  


Biology - Short Answer Brennan wants to track the growth of a tree. He sticks a pole in the trunk of the tree 5 feet above the ground. If the tree grows at a rate of 1 foot/2 years, how far above the ground will Brennan's pole be in 10 years?  


Answer: 5 FEET  


## Bonus  


Biology - Multiple Choice Steroid hormones such as testosterone and estrogen are hydrophobic. Which of the following would be the least likely place for a steroid hormone receptor to be found?  


W) Cell Membrane  
X) Nucleus  
Y) Cytoplasm  
Z) Mitochondria  


Answer: W) CELL MEMBRANE  


## Tossup  


Chemistry - Multiple Choice Which of the following elements react most violently in water?
W) Sodium 
X) Aluminum 
Y) Zinc 
Z) Silver  


Answer: W) SODIUM [AE]  


## Bonus  


Chemistry - Multiple Choice Which of the following techniques can be used to separate two liquids of different densities?  


W) Chromatography 
X) Distillation 
Y) Decanting 
Z) Filtration  


Answer: Y) DECANTING [AI]  


## Tossup  


Math - Short Answer Brennan notices that on his 30 minute drive into work everyday, the traffic is 30 minutes worse on days when it rains. If there is a 1/3rd chance of rain on a given day, what is the expected time it takes for Brennan to get to work?  


Answer: 40 minutes [RE]  


## Bonus  


Math - Short Answer A circle is tangent to the lines \(\mathrm{y} = 7\) and \(\mathrm{y} = - 9\) . If its center lies on the line \(\mathrm{y} = 3\mathrm{x} + 4\) , what is the equation of the circle in standard \((\mathrm{x - a})^{\wedge}2 + (\mathrm{y - b})^{\wedge}2 = \mathrm{c}\) form [x minus a squared plus y minus b squared equals c]?  


Answer: \((\mathrm{x} + 5 / 3)^{\wedge}2 + (\mathrm{y} + 1)^{\wedge}2 = 64\) [RE]  


## Tossup  


Physics - Multiple Choice Brennan drops a book out of his airplane. Which of the following properties of the book will approach zero as it travels towards the ground?
W) MassX) VelocityY) AccelerationZ) Momentum  


Answer: Y) ACCELERATION [RE]  


## Bonus  


Physics - Short Answer Identify all of the following 3 forces which are not considered pseudo forces? I. Gravity; II. Coriolis Force; III. Centrifugal Force  


Answer: I [RE]