
# Iolani Science Bowl Invitational Single Elimination 1  


## Tossup  


Earth and Space - Multiple Choice Which of the following correctly describes a yazoo [yah- zoo] stream?  


W) A stream that lies on the floodplain of another river, running parallel to said river X) A stream created by the confluence of two other streams Y) A stream originating from the ocean Z) A stream that drains into a basin with no outlet  


Answer: W) A STREAM THAT LIES ON THE FLOODPLAIN OF ANOTHER RIVER RUNNING PARALLEL TO SAID RIVER [RE]  


## Bonus  


Earth and Space - Multiple Choice What name is given to the curved glacial valleys created by the erosion of mountains?  


W) Horns X) Cirques Y) Aretes Z) Eskers  


Answer: X) CIRQUES [RE]  


## Tossup  


Biology - Short Answer What term describes the inactivated X chromosome in female mammals?  


Answer: BARR BODY  


## Bonus  


Biology - Short Answer Order the following three blood vessels in terms of INCREASING blood flow velocity: I - Arteries, II - Capillaries, III - Veins  


Answer: II, III, I  


## Tossup  


Chemistry - Multiple Choice Which of the following atoms has the largest atomic radius?  


W) Carbon
X) CesiumY) CalciumZ) Chlorine  


Answer: X) CESIUM [AI]  


## Bonus  


BonusChemistry - Short Answer Which of the following three ions have the same electron configuration as argon? I. Cl- ; II. Li+ ; III. K+  


Answer: I, III. Cl- , K+ [AI]  


## Tossup  


TossupMath - Short Answer What is the determinant of a matrix with top row 5, 7 and bottom row 3, 8?  


Answer: 19 [RE]  


## Bonus  


BonusMath - Short Answer What is the area between the curves \(y = x^{\wedge}2\) and \(y = \mathrm{sqrt}(x)\) ?  


Answer: 1/3 [RE]  


## Tossup  


TossupPhysics - Short Answer An adiabatic process involves no net exchange of what quantity between thermodynamic systems?  


Answer: HEAT [RE]  


## Bonus  


BonusPhysics - Multiple Choice Which of the following effects explains the oddly long life of a water droplet over an extremely hot surface due to the formation of an insulating layer of vapor?  


W) Leidenfrost EffectX) Hydrothermal SuspensionY) Joule-Thomson EffectZ) Paschen-Back Effect  


Answer: W) LEIDENFROST EFFECT [RE]  


## Tossup  


TossupEarth and Space - Multiple Choice Which of the following is not an asteroid type?  


W) C- Type
X) S-TypeY) T-TypeZ) M-Type  


Answer: Y) T-TYPE [AE]  


## Bonus  


Earth and Space - Short Answer Identify all of the following three statements that are true about comets. I. Long period comets likely originate from the Asteroid Belt; II. Comets have two distinct tails; III. Naked eye comets usually have low eccentricities.  


Answer: II [AE]  


## Tossup  


Biology - Multiple Choice Brennan wants to compare the organelles within his liver cells and the cells of his green onion plant. Which organelle would you NOT expect to see in both cells?  


W) MitochondriaX) CentrosomeY) PeroxisomeZ) Rough ER  


Answer: X) CENTROSOME  


## Bonus  


Biology - Short Answer Order the following three steps of muscle contraction in order following the binding of ATP to myosin: I - Myosin binds to actin, II - Thin filament moves towards the center of the sarcomere, III - ATP Hydrolysis  


Answer: III, I, II  


## Tossup  


Chemistry - Short Answer A sample of gas is held above a beaker of water. If the concentration of carbon dioxide in the water is tripled, by what factor does the partial pressure of carbon dioxide in the gas sample increase?  


Answer: 3 [AE]  


## Bonus  


Chemistry - Multiple Choice Brennan dissolves a solute B into a solvent water, and uses Raoult's Law to predict the vapor pressure. If water's interactions with itself and B's interactions with itself are both weaker than water's interactions with B, the actual vapor pressure:
W) Is lower than Brennan's prediction  
X) Is the same as Brennan's prediction  
Y) Is higher than Brennan's prediction  
Z) Cannot be predicted from this information  


Answer: W) IS LOWER THAN BRENNAN'S PREDICTION [AE]  


## Tossup  


Math - Short Answer What is the value of the integral of \(\mathrm{f(x) = x^{\wedge}3}\) from 0 to 1?  


Answer: 1/4 [RE]  


## Bonus  


Math - Short Answer - In Game Theory, a zero sum game is a game where one player's loss equals another player's gain. Name all of the following 3 games that are zero sum games.  


1) Chess  
2) Poker  
3) Prisoner's Dilemma  


Answer: 1 and 2 ONLY [EC]  


## Tossup  


Physics - Short Answer A Gaussian sphere surrounds a particle of charge \(+2\) coulombs. If the charge doubles and the sphere is changed into a Gaussian cube with the same center, by what factor is the original flux multiplied?  


Answer: 2 [RE]  


## Bonus  


Physics - Multiple Choice Which of the following is not a type of damping for a simple harmonic oscillator?  


W) Ultradamped  
X) Overdamped  
Y) Critically Damped  
Z) Underdamped  


Answer: W) ULTRADAMPED [RE]  


## Tossup  


Earth and Space - Short Answer Order the following 3 types of silicates in increasing number of bridging, or shared oxygens. I. Phyllosilicates; II. Nesosilicates; III. Inosilicates
Answer: II, III, I [RE]  


## Bonus  


Earth and Space - Multiple Choice A northwesterly moving, ideal current, in the southern hemisphere, would cause the net movement of water in which of the following directions?  


W) Northwest  X) Northeast  Y) Southwest  Z) Southeast  


Answer: Y) SOUTHWEST [RE]  


## Tossup  


Biology - Multiple Choice A flower that lacks a fragrance and is not colorful is most likely pollinated by which of the following?  


W) Bee  X) Bird  Y) Wind  Z) Bat  


Answer: Y) WIND  


## Bonus  


Biology - Short Answer Identify all of the following three statements which are functions of RNA within a human cell: I - Serves as hereditary material, II - Catalyzing chemical reactions, III - Silencing gene expression  


Answer: II, III  


## Tossup  


Chemistry - Short Answer Which of the following three scenarios will cause the solubility of CO2 in water to increase?  


I. The temperature of the system is increased. 
II. More CO2 is added to the system. 
III The partial pressure of CO2 is increased.  


Answer: II, III. [AI]  


## Bonus
Chemistry - Multiple Choice Which of the following oxyacids would you expect to be the strongest?  


W) HNO 
X) HNO2 
Y) HNO3 
Z) HNO4  


Answer: W) HNO4 [RE]  


## Tossup  


Math - Short Answer What is the derivative of the function \(\mathrm{f(x) = x^{\wedge}15 - x^{\wedge}2}\) at \(\mathrm{x} = 1\) ?  


Answer: 13 [RE]  


## Bonus  


Math - Multiple Choice How many non- negative integers satisfy the inequality \(\mathrm{x}^{\wedge}3 + 5\mathrm{x}^{\wedge}2 - \mathrm{x} - 5\) \(< 0?\)  


W) 0  


X) 1  


Y) 2  


Z) Infinitely many  


Answer: X) 1 [RE]  


## Tossup  


Physics - Short Answer Identify all of the following 3 things that are quantized. I. Charge; II. Light; III. Spin  


Answer: ALL [RE]  


## Bonus  


Physics - Multiple Choice In what type of thermodynamic process is no work done?  


W) Adiabatic 
X) Isobaric 
Y) Isochoric 
Z) Isothermal  


Answer: Y) ISOCHORIC [RE]  


## Tossup
Earth and Space - Multiple Choice Which of the following is least likely to have emission lines?  


W) Globular Cluster 
X) Wolf-Rayet Star 
Y) Planetary Nebula 
Z) Active Galaxy  


Answer: W) GLOBULAR CLUSTER [AE]  


## Bonus  


Earth and Space - Short Answer In kilometers per second, what is the recessional velocity of a galaxy 20 megaparsecs away?  


Answer: 1400 [AE]  


## Tossup  


Biology - Multiple Choice Which of the following organisms most likely follows a Type III survivorship curve?  


W) Oyster 
X) Human 
Y) Bird 
Z) Elephant  


Answer: W) OYSTER  


## Bonus  


Biology - Multiple Choice Which of the following would you expect to increase the activity of phosphofructokinase?  


W) High AMP concentration 
X) High Citrate concentration 
Y) High ATP concentration 
Z) High Pyruvate concentration  


Answer: W) HIGH AMP CONCENTRATION  


## Tossup  


Chemistry - Short Answer Identify all of the following three properties that generally increase as you move left to right on the periodic table. I. Ionization Energy; II. Electron Affinity; III. Atomic Radius
Answer: I, II [AE]  


## Bonus  


BonusChemistry - Short Answer Order the following three elements in terms of increasing electronegativity. I. Potassium; II. Chlorine; III. Silicon  


Answer: I, III, II [AE]  


## Tossup  


TossupMath - Multiple Choice Which of the following polynomials is divisible by \(\mathrm{x} + 2\) ?  


\(\mathrm{W})\mathrm{x}^{\wedge}2 + 4\) \(\mathrm{X})\mathrm{x}^{\wedge}3 + 8\) \(\mathrm{Y})\mathrm{x}^{\wedge}4 + 16\) \(\mathrm{Z})\mathrm{x}^{\wedge}5 + 32\)  


Answer: \(\mathrm{X})\mathrm{x}^{\wedge}3 + 8\) [RE]  


## Bonus  


BonusMath - Short Answer What is A6B base 12 in base 10?  


Answer: 1523 [RE]  


## Tossup  


TossupPhysics - Short Answer What effect occurs when a particle moves faster than the phase velocity of light in a dielectric medium?  


Answer: CHERENKOV RADIATION [RE]  


## Bonus  


BonusPhysics - Multiple Choice A particle of charge - 2 coulombs travels at \(100\mathrm{m / s}\) in the positive x- direction. If a 5 Tesla magnetic field is set up in the positive y direction, what is the magnitude and direction of the resulting magnetic force is newtons?  


W) Positive z, 1000 X) Positive z, 500 Y) Negative z, 1000 Z) Negative z, 500  


Answer: Y) NEGATIVE Z, 1000 [RE]