sub_title[[456, 123, 541, 140]]
## TOSS-UP  

text[[115, 153, 881, 207]]
1) PHYSICS Short Answer A 36 V battery is connected in an R-L circuit to 1.5 ohm resistor and a solenoid with an inductance of \(12\mathrm{H}\) . After the switch has been in the "on" position for a very long time, what is the total current running through the circuit?  

text[[115, 220, 250, 236]]
ANSWER: 24 A  

sub_title[[463, 250, 534, 267]]
## BONUS  

text[[115, 280, 881, 334]]
1) PHYSICS Short Answer Winnie is gazing out his window when he suddenly sees a \(5\mathrm{kg}\) jar of honey fly up and then fall back down the \(3\mathrm{m}\) length in a total of 2 seconds. Assuming no air resistance, what is the maximum height the jar will go above the window?  

text[[115, 347, 256, 363]]
ANSWER: 0.2 m  

sub_title[[456, 436, 541, 453]]
## TOSS-UP  

text[[115, 466, 852, 501]]
2) BIOLOGY Short Answer Genes that code for human MHC complexes are found on which chromosome?  

text[[115, 514, 332, 530]]
ANSWER: Chromosome 6  

sub_title[[463, 544, 534, 561]]
## BONUS  

text[[115, 574, 861, 609]]
2) BIOLOGY Multiple Choice Which of the following organelles is located next to the neurite that will differentiate into an axon during neuron development?  

text[[115, 622, 255, 694]]
W) Mitochondria 
X) Nucleus 
Y) Golgi Body 
Z) ER  

text[[115, 707, 329, 724]]
ANSWER: Y) Golgi Body  

sub_title[[456, 768, 541, 784]]
## TOSS-UP  

text[[115, 797, 830, 832]]
3) EARTH AND SPACE Multiple Choice Which of the following rocks takes up the most volume of Earth's Crust?text[[114, 124, 225, 197]]
W) DioriteX) SandstoneY) GraniteZ) Basalt  

text[[115, 210, 284, 226]]
ANSWER: Z) Basalt  

sub_title[[462, 239, 534, 255]]
## BONUS  

text[[113, 268, 864, 304]]
3) EARTH AND SPACE Multiple Choice Which of the following phyllosilicates is commonly known as magnesium mica?  

text[[114, 317, 492, 389]]
W) AnniteX) Phlogopite (FLO-GO-PITE?)Y) Siderophyllite (SID-UR-OH-FIE-LIGHT)?Z) Muscovite  

text[[115, 403, 322, 420]]
ANSWER: X) Phlogopite  

sub_title[[456, 522, 541, 539]]
## TOSS-UP  

text[[113, 551, 866, 587]]
4) CHEMISTRY Multiple Choice Which of the following can make up the mobile phase in gas chromatography?  

text[[114, 599, 219, 715]]
W) ChlorineX) NitrogenY) HydrogenZ) Oxygen  

text[[115, 719, 306, 736]]
ANSWER: X) Nitrogen  

sub_title[[462, 749, 534, 765]]
## BONUS  

text[[113, 778, 778, 795]]
4) CHEMISTRY Short Answer Lugol's solution is a mixture of what two elements?  

text[[115, 808, 380, 824]]
ANSWER: Potassium and Iodinesub_title[[455, 154, 541, 170]]
## TOSS-UP  

text[[113, 183, 814, 201]]
5) ENERGY Short Answer What is the term for the energy required to melt a substance?  

text[[115, 214, 320, 230]]
ANSWER: heat of fusion  

sub_title[[462, 244, 534, 261]]
## BONUS  

text[[114, 273, 880, 327]]
5) ENERGY Short Answer How much energy, in kJ to two significant figures, is required to turn 50 grams of water at \(0^{\circ}\) C into steam at \(100^{\circ}\) C? The heat of vaporization for water is 40.65 kJ/mol.  

text[[115, 340, 262, 357]]
ANSWER: 130 kJ  

sub_title[[455, 429, 541, 446]]
## TOSS-UP  

text[[113, 459, 872, 494]]
6) MATH Short Answer What is the shortest distance between the point (4, 6) and the line \(15y = 8x\) ?  

text[[115, 507, 256, 524]]
ANSWER: 58/17  

sub_title[[462, 538, 534, 555]]
## BONUS  

text[[113, 568, 844, 604]]
6) MATH Short Answer Find the slope of the line tangent to the graph with equation \(\square \square^{2} + 6\square^{2} = 21\) at the point (1,3).  

text[[115, 617, 453, 635]]
ANSWER: - 6/37 (dy/dx = - 2xy/(x²+12y))  

sub_title[[455, 737, 541, 755]]
## TOSS-UP  

text[[111, 767, 875, 785]]
7) BIOLOGY Multiple Choice Which of the following chordates display chevron segmentation?  

text[[114, 798, 216, 870]]
W) Tunicate  
X) Lancelet  
Y) Myxini  
Z) Lampreytext[[115, 124, 304, 140]]
ANSWER: X) Lancelet  

sub_title[[462, 154, 534, 170]]
## BONUS  

text[[115, 183, 660, 201]]
7) BIOLOGY Short Answer Name three bacteria-associated PAMPs:  

text[[113, 214, 874, 248]]
ANSWER: N-formylmethionine, peptidoglycan, lipopolysaccharide, uncapped RNA, no poly- A tail  

sub_title[[456, 352, 541, 368]]
## TOSS-UP  

text[[113, 380, 863, 418]]
8) EARTH AND SPACE Multiple Choice Which of the following ocean currents brings warm water down through the Mozambique Channel near Madagascar?  

text[[113, 430, 248, 501]]
W) Benguela 
X) Agulhas 
Y) Mozambique 
Z) South Indian  

text[[115, 515, 302, 532]]
ANSWER: X) Agulhas  

sub_title[[462, 545, 534, 561]]
## BONUS  

text[[113, 574, 855, 610]]
8) EARTH AND SPACE Short Answer List the following galaxies in order of increasing size within the Local Group:  

text[[113, 622, 343, 696]]
I) Milky Way 
II) Andromeda 
III) Triangulum 
IV) Large Magellanic Cloud  

text[[115, 708, 301, 724]]
ANSWER: IV, III, I, II  

sub_title[[456, 797, 541, 813]]
## TOSS-UP  

text[[113, 826, 868, 862]]
9) CHEMISTRY Short Answer What is the oldest documented form of resistance heating alloy, consisting of \(80\%\) nickel and \(20\%\) chromium by mass?text[[115, 123, 426, 140]]
ANSWER: Nichrome (Nickel-chrome)  

sub_title[[462, 153, 535, 170]]
## BONUS  

text[[113, 183, 875, 220]]
9) CHEMISTRY Multiple Choice In fractional distillation, what kind of gas condenser is known as the bulb condenser, consisting of a long glass tube marked by a series of bulbs on said tube?  

text[[115, 232, 283, 249]]
W) Allihn condenser  

text[[115, 262, 283, 279]]
X) Davies condenser  

text[[115, 292, 280, 309]]
Y) Liegib condenser  

text[[115, 322, 271, 339]]
Z) West Condenser  

text[[115, 352, 377, 369]]
ANSWER: W) Allihn condenser  

sub_title[[456, 471, 541, 488]]
## TOSS-UP  

text[[115, 500, 860, 537]]
10) MATH Multiple Choice Which of the following conditions would best describe a possible graph of \(\mathrm{f(x)}\) in [a,b] (the open interval from a to b) if it is concave down in that range?  

text[[114, 548, 372, 622]]
W) \(\mathrm{f}^{\prime \prime}(\mathrm{x}) > 0\) \(\mathrm{f}^{\prime}(\mathrm{x})\) is increasing X) \(\mathrm{f}^{\prime \prime}(\mathrm{x})< 0\) \(\mathrm{f}^{\prime}(\mathrm{x})\) is increasing Y) \(\mathrm{f}^{\prime \prime}(\mathrm{x}) > 0\) \(\mathrm{f}^{\prime}(\mathrm{x})\) is decreasing Z) \(\mathrm{f}^{\prime \prime}(\mathrm{x})< 0\) \(\mathrm{f}^{\prime}(\mathrm{x})\) is decreasing  

text[[115, 634, 461, 652]]
ANSWER: Z) \(\mathrm{f}^{\prime \prime}(\mathrm{x})< 0\) \(\mathrm{f}^{\prime}(\mathrm{x})\) is decreasing  

# BONUS  

text[[115, 694, 842, 749]]
10) MATH Short Answer 5 points are positioned on a circle. Find the number of regions the circle is cut into if lines are drawn connecting every distinct pair of points and no three lines intersect at the same point.  

text[[115, 761, 231, 777]]
ANSWER: 16text[[113, 123, 880, 159]]
11) ENERGY Short Answer A system does 54 J of work on its surroundings and then absorbs 17 J as heat. What is its change in internal energy?  

text[[115, 172, 250, 189]]
ANSWER: - 37 J  

sub_title[[463, 203, 534, 220]]
## BONUS  

text[[115, 232, 876, 268]]
11) ENERGY Short Answer What is the internal energy of two moles of an ideal gas at 200 K at constant pressure?  

text[[115, 281, 262, 298]]
ANSWER: 8314 J  

sub_title[[456, 370, 541, 387]]
## TOSS-UP  

text[[115, 400, 874, 454]]
12) PHYSICS Short Answer If an electric current flows through a conductor in a magnetic field, what phenomenon is responsible for the creation of a potential difference perpendicular to both the current and magnetic field?  

text[[115, 466, 298, 483]]
ANSWER: Hall Effect  

sub_title[[463, 497, 534, 514]]
## BONUS  

text[[115, 526, 874, 562]]
12) PHYSICS Short Answer If an object is in freefall and its area is doubled, by how much does the drag force on the object increase by?  

text[[115, 575, 221, 591]]
ANSWER: 2  

sub_title[[456, 695, 541, 711]]
## TOSS-UP  

text[[115, 724, 799, 760]]
13) BIOLOGY Short Answer Which two organs in the human body contain glucose-6-phosphatase?  

text[[115, 772, 345, 789]]
ANSWER: Liver and kidney  

sub_title[[463, 832, 534, 848]]
## BONUStext[[113, 123, 866, 159]]
13) BIOLOGY Multiple Choice Which of the following does not occur in humans with Type II diabetes:  

text[[114, 171, 425, 245]]
W) Amylin induced beta cell apoptosis 
X) Postprandial hyperglycemia 
Y) Overactivation of GLUT 4 
Z) Impaired insulin secretion  

text[[115, 257, 447, 274]]
ANSWER: Y) Overactivation of GLUT 4  

sub_title[[456, 346, 541, 363]]
## TOSS-UP  

text[[114, 375, 880, 429]]
14) PHYSICS Short Answer In terms of any electromagnetic constants, what is the energy stored in the magnetic field of a solenoid with an average 5 turns per unit length, carrying a current of 4 A?  

text[[115, 442, 266, 460]]
ANSWER: \(200\mu_{0}\mathrm{J}\)  

sub_title[[462, 475, 534, 492]]
## BONUS  

text[[114, 503, 877, 558]]
14) PHYSICS Short Answer What law states that the intensity of a beam of plane polarized light is directly proportional to the square of the cosine of the angle through which the polarizer is rotated?  

text[[114, 571, 528, 588]]
ANSWER: Law of Malus (ACCEPT: Malus's Law)  

sub_title[[456, 660, 541, 677]]
## TOSS-UP  

text[[114, 690, 682, 708]]
15) EARTH AND SPACE Multiple Choice What is the anion in pyrite?  

text[[114, 720, 175, 793]]
W) \(\mathrm{S}^{2 - }\) X) S- Y) \(\mathrm{S}_{2}^{2 - }\) Z) \(\mathrm{S}_{2}^{3 - }\)  

text[[114, 807, 224, 822]]
ANSWER: Y  

sub_title[[462, 835, 534, 851]]
## BONUStext[[113, 123, 813, 159]]
15) EARTH AND SPACE Short Answer Which of the following elements are present in feldspar?  

text[[118, 173, 258, 246]]
I. Al 
II. C 
III. Fe ANSWER: I only  

sub_title[[456, 346, 541, 363]]
## TOSS-UP  

text[[113, 375, 872, 411]]
16) CHEMISTRY Multiple Choice Which of the following are in the anode compartment under standard conditions?  

text[[114, 424, 409, 498]]
W) oxidizing agent, oxidized species 
X) oxidizing agent, reduced species 
Y) reducing agent, oxidized species 
Z) reducing agent, reduced species  

text[[115, 510, 224, 526]]
ANSWER: Y  

sub_title[[463, 540, 533, 557]]
## BONUS  

text[[115, 569, 877, 624]]
16) CHEMISTRY Short Answer A redox reaction can be separated into the sum of three different reactions: two oxidations and a reduction. If the standard reduction potentials are \(+0.50\) V and \(-0.30\) V and \(+0.90\) V, what is the \(\mathrm{e}^{\mathrm{o}}\) for the entire reaction?  

text[[115, 636, 275, 653]]
ANSWER: \(+1.60\) V  

sub_title[[456, 725, 541, 742]]
## TOSS-UP  

text[[115, 754, 844, 790]]
17) ENERGY Short Answer What is the change in Gibbs free energy for the vaporization of water at \(100^{\circ}\mathrm{C}\) ?  

text[[115, 803, 222, 819]]
ANSWER: 0  

sub_title[[463, 833, 533, 849]]
## BONUStext[[113, 123, 850, 159]]
17) ENERGY Short Answer State whether the following processes increases or decreases the free energy of the system  

text[[120, 172, 590, 264]]
I. hydrogen reacting with oxygen  
II. battery charging  
III. burning natural gas  
IV. boiling water at room temperature  ANSWER: I. decrease II. increase III. decrease IV. increase  

sub_title[[456, 336, 541, 352]]
## TOSS-UP  

text[[115, 365, 608, 382]]
18) MATH Short Answer What is the 63rd triangular number?  

text[[115, 395, 256, 411]]
ANSWER: 2016  

sub_title[[462, 425, 535, 441]]
## BONUS  

text[[115, 454, 866, 472]]
18) MATH Short Answer Find the remainder when \(\mathrm{P(x) = x^4 + 3x^2 - 17x + 23}\) is divided by \(\mathrm{x + 2}\) .  

text[[115, 485, 230, 500]]
ANSWER: 85  

sub_title[[456, 604, 541, 620]]
## TOSS-UP  

text[[115, 633, 872, 669]]
19) BIOLOGY Short Answer Classify each of the following chordates as oviparous, viviparous, or ovoviviparous:  

text[[114, 682, 243, 754]]
I) Ratites  
II) Monotremes  
III) Marsupials  
IV) Eutherians  

text[[114, 767, 674, 784]]
ANSWER: I) Oviparous II) Oviparous, III) Viviparous IV) Viviparous  

sub_title[[462, 797, 535, 813]]
## BONUS  

text[[115, 826, 855, 862]]
19) BIOLOGY Multiple Choice At which section of the axon terminal do potassium channels aggregate in order to ensure that only the strongest waves of depolarization are passed on?text[[114, 124, 262, 197]]
W) Juxtaparanode  
X) Paranode  
Y) Heminode  
Z) Nodes of Ranvier  

text[[115, 210, 318, 226]]
ANSWER: Y) Heminode  

sub_title[[456, 298, 541, 315]]
## TOSS-UP  

text[[114, 328, 870, 400]]
20) PHYSICS Multiple Choice A \(10\mathrm{kg}\) ball is loosely attached to a massless spring on a table with a spring constant of \(6\mathrm{N / m}\) which is currently compressed a distance of \(4\mathrm{m}\) from equilibrium and then released. If the coefficient of kinetic friction of the table is 0.5, what is the resulting acceleration of the mass?  

text[[114, 412, 222, 429]]
W) \(0.8\mathrm{m / s^2}\)  

text[[114, 443, 220, 459]]
X) \(1.2\mathrm{m / s^2}\)  

text[[114, 473, 220, 489]]
Y) \(1.6\mathrm{m / s^2}\)  

text[[114, 504, 220, 519]]
Z) \(2.4\mathrm{m / s^2}\)  

text[[114, 533, 313, 549]]
ANSWER: X) \(1.2\mathrm{m / s^2}\)  

sub_title[[462, 563, 534, 579]]
## BONUS  

text[[113, 592, 866, 628]]
20) PHYSICS Short Answer If Xavier is \(30\mathrm{kg}\) and Yavier is \(60\mathrm{kg}\) and are standing together in an inertial frame, what is the reduced mass of the system?  

text[[114, 640, 394, 657]]
ANSWER: \(20\mathrm{kg}(1 / (1 / \mathrm{m}1 + 1 / \mathrm{m}2))\)  

sub_title[[456, 730, 541, 747]]
## TOSS-UP  

text[[113, 760, 768, 778]]
21) CHEMISTRY Multiple Choice Tm is the chemical symbol for which element?  

text[[113, 791, 225, 862]]
W) Thorium  
X) Thulium  
Y) Thallium  
Z) Telluriumtext[[115, 124, 226, 140]]
ANSWER: X  

sub_title[[462, 154, 534, 170]]
## BONUS  

text[[113, 183, 710, 200]]
21) CHEMISTRY Short Answer What is the electron configuration of \(\mathrm{Au}^{3 + }\)  

text[[115, 214, 313, 230]]
ANSWER: [Xe] 4f14 5d8  

sub_title[[456, 333, 541, 350]]
## TOSS-UP  

text[[113, 362, 785, 380]]
22) EARTH AND SPACE Short Answer What type of air mass is abbreviated as cP?  

text[[115, 393, 344, 409]]
ANSWER: continental polar  

sub_title[[462, 423, 534, 440]]
## BONUS  

text[[113, 452, 875, 488]]
22) EARTH AND SPACE Short Answer The dew point of an air mass at sea level is \(6^{\circ}\mathrm{C}\) . Given that the temperature is \(25^{\circ}\mathrm{C}\) , at what elevation will the water begin to condense?  

text[[115, 500, 266, 517]]
ANSWER: 2.5 km  

sub_title[[456, 590, 541, 607]]
## TOSS-UP  

text[[113, 620, 844, 656]]
23) ENERGY Multiple Choice Which of the following is not a method for the production of syngas?  

text[[113, 669, 279, 740]]
W) water-gas shift 
X) steam reforming 
Y) dry reforming 
Z) partial oxidation  

text[[115, 753, 230, 769]]
ANSWER: W  

sub_title[[462, 783, 534, 800]]
## BONUS  

text[[113, 813, 857, 849]]
23) ENERGY Multiple Choice Production of aluminum by recycling requires what percent of the energy required to produce the same amount from bauxite?text[[113, 123, 185, 197]]
W) 1% 
X) 5% 
Y) 50% 
Z) 90%  

text[[115, 211, 225, 226]]
ANSWER: X  

sub_title[[456, 298, 541, 315]]
## TOSS-UP  

text[[114, 327, 875, 419]]
24) MATH Short Answer Zarr needs to file 12 sheets of paper. First, he separates them into two piles, one containing the first 6 papers counting from the top and another containing the last 6. Then, he draws one sheet from the first pile into another pile and puts a sheet from the second pile on top of the third pile and continues this process until all of the paper is in the third pile. How many pieces of paper are below the paper that was the 9th from the top in the original pile?  

text[[115, 431, 221, 447]]
ANSWER: 4  

sub_title[[462, 491, 534, 508]]
## BONUS  

text[[115, 520, 858, 575]]
24) MATH Short Answer How many ways are there to color a circular spinner with five equal sections with the colors red, blue, and purple, assuming reflections are distinct and only one color may occupy a single sector at a time?  

text[[115, 587, 228, 604]]
ANSWER: 51  

sub_title[[456, 677, 541, 694]]
## TOSS-UP  

text[[113, 706, 868, 742]]
25) CHEMISTRY Short Answer What is the formal charge of Cl in \(\mathrm{ClO_4^-}\) if there are no double bonds?  

text[[115, 755, 231, 772]]
ANSWER: +3  

sub_title[[462, 786, 534, 802]]
## BONUS  

text[[113, 814, 794, 832]]
25) CHEMISTRY Short Answer Rank the following in order of increasing bond order  

text[[131, 845, 205, 861]]
I. \(\mathrm{O_2}^+\)text[[115, 123, 270, 179]]
II. CO²-
III. N₂
ANSWER: II, I, III