sub_title[[455, 143, 541, 162]]
## TOSS-UP  

text[[114, 178, 864, 232]]
1) Physics – Multiple Choice When travelling at or near terminal velocity, the magnitude of the force of air resistance upon an object is proportional to the velocity of the object to what power?  

text[[114, 248, 170, 320]]
W) 1  X) 3/2  Y) 2  Z) 5/2  

text[[115, 338, 246, 356]]
ANSWER: Y) 2  

sub_title[[463, 355, 533, 373]]
## BONUS  

text[[115, 390, 872, 427]]
1) Physics – Short Answer Identify all of the following types of scattering that are considered to be inelastic: 1) Raman; 2) Compton; 3) Thomson; 4) Rayleigh.  

text[[115, 444, 283, 461]]
ANSWER: 1 AND 2  

sub_title[[456, 514, 540, 532]]
## TOSS UP  

text[[115, 548, 872, 585]]
2) Biology – Short Answer What is the term for the central body cavity of most invertebrates, which contains the circulatory fluid?  

text[[115, 600, 319, 618]]
ANSWER: HEMOCOEL  

sub_title[[463, 636, 533, 654]]
## BONUS  

text[[115, 670, 854, 723]]
2) Biology – Short Answer A plant is said to have chlorosis, a condition where insufficient chlorophyll is produced due to a mineral deficiency, when its leaves turn what characteristic color?  

text[[115, 740, 293, 757]]
ANSWER: YELLOWsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[113, 127, 872, 163]]
3) Chemistry – Short Answer Identify all of the following three species in which carbon does NOT form four bonds: 1) Carbon monoxide: 2) Methyl carbocation; 3) Ethanol.  

text[[115, 181, 283, 199]]
ANSWER: 1 AND 2  

sub_title[[463, 216, 533, 234]]
## BONUS  

text[[113, 251, 802, 288]]
3) Chemistry – Multiple Choice Which of the following diatomic molecules is NOT diamagnetic?  

text[[115, 305, 170, 377]]
W) C2 
X) N2 
Y) O2 
Z) F2  

text[[115, 393, 258, 412]]
ANSWER: Y) O2  

sub_title[[456, 464, 541, 482]]
## TOSS-UP  

text[[115, 499, 874, 553]]
4) Math – Short Answer Identify all of the following three statements that are TRUE concerning dot products: 1) They produce vectors; 2) The dot product of parallel vectors is zero; 3) They are commutative.  

text[[115, 570, 280, 587]]
ANSWER: 3 ONLY  

sub_title[[463, 604, 533, 622]]
## BONUS  

text[[112, 639, 866, 658]]
4) Math – Short Answer Find the derivative of \(x\) to the \(x\) power with respect to \(x\) when \(x = e\) .  

text[[115, 674, 235, 692]]
ANSWER: \(2e^e\)sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[113, 127, 883, 163]]
5) Earth and Space – Short Answer What element is present in the mineral dolomite that is not present in calcite?  

text[[115, 180, 333, 198]]
ANSWER: MAGNESIUM  

sub_title[[463, 215, 533, 234]]
## BONUS  

text[[115, 250, 788, 287]]
5) Earth and Space – Short Answer Name all of the following four plutons that are concordant: 1) Laccolith; 2) Batholith; 3) Sill; 4) Dike.  

text[[115, 316, 283, 335]]
ANSWER: 1 AND 3  

sub_title[[456, 386, 540, 404]]
## TOSS-UP  

text[[115, 421, 867, 476]]
6) Energy – Multiple Choice Researchers at Lawrence Livermore National Lab have been studying carbon nanotubes for their potential applications as channels in biological membranes. Which of the following is true regarding carbon nanotubes?  

text[[115, 492, 545, 563]]
W) They are electrically insulating 
X) They are composed of \(\mathrm{sp}^3\) hybridized carbon atoms 
Y) They contain a delocalized system of pi electrons 
Z) They exhibit low tensile strength  

text[[115, 578, 794, 597]]
ANSWER: Y) THEY CONTAIN A DELOCALIZED SYSTEM OF PI ELECTRONS  

sub_title[[463, 613, 533, 631]]
## BONUS  

text[[115, 648, 875, 719]]
6) Energy – Short Answer Scientists at Oak Ridge National Lab have been developing new methods to produce radiochemical products for a variety of applications. What general type of nuclear reaction, characterized by the conversion of one nuclide to another, could be used in this process?  

text[[115, 735, 380, 753]]
ANSWER: TRANSMUTATIONsub_title[[456, 91, 541, 108]]
## TOSS-UP  

text[[114, 128, 850, 163]]
7) Math – Short Answer What is the signed area between the \(x\) -axis and the curve \(y\) equals sine \(x\) minus tangent \(x\) on the interval \(-1\) to 1?  

text[[115, 180, 221, 197]]
ANSWER: 0  

sub_title[[464, 215, 533, 233]]
## BONUS  

text[[115, 250, 870, 303]]
7) Math – Short Answer It takes Sharon 1.5 hours to sort 60 books, and it takes Evan 4 hours to sort 80 books. How long will it take Sharon and Evan to sort 300 books if they work together?  

text[[115, 319, 293, 337]]
ANSWER: 5 HOURS  

sub_title[[456, 389, 540, 407]]
## TOSS UP  

text[[115, 423, 875, 460]]
8) Biology – Multiple Choice What glial cells in the central nervous system perform the same role as Schwann cells in the peripheral nervous system?  

text[[115, 477, 285, 547]]
W) Astrocytes X) Oligodendrocytes Y) Microglia Z) Ependymal cells  

text[[115, 563, 442, 581]]
ANSWER: X) OLIGODENDROCYTES  

sub_title[[464, 598, 533, 616]]
## BONUS  

text[[115, 633, 875, 686]]
8) Biology – Short Answer In response to mechanical stress, some plants slow stem elongation, thicken the stem, and curve it away from the source of stress. What is the term given for this type of response?  

text[[115, 702, 380, 720]]
ANSWER: TRIPLE RESPONSEsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[114, 127, 870, 181]]
9) Chemistry – Short Answer Identify all of the following three statements that are NOT true regarding the bromination of alkenes: 1) The reaction proceeds via a syn-addition; 2) The reaction follows Markovnikov's rule; 3) The reaction produces a carbocation intermediate.  

text[[115, 198, 282, 215]]
ANSWER: 1 AND 3  

sub_title[[462, 233, 533, 250]]
## BONUS  

text[[114, 268, 861, 304]]
9) Chemistry – Multiple Choice If the temperature of a black body is doubled, then by what factor is the wavelength of its emitted radiation multiplied?  

text[[114, 321, 175, 392]]
W) 1/4 X) 1/2 Y) 2 Z) 4  

text[[115, 409, 261, 427]]
ANSWER: X) 1/2  

sub_title[[456, 480, 541, 497]]
## TOSS-UP  

text[[115, 515, 872, 586]]
10) Energy – Short Answer Scientists at SLAC National Accelerator Laboratory have been using X-rays to study the chemical composition of materials. What type of radiation, emitted when charged particles are accelerated radially through a magnetic field, can be used to produce these X-rays?  

text[[115, 602, 839, 638]]
ANSWER: SYNCHROTRON RADIATION (DO NOT ACCEPT: BREMSSTRAHLUNG RADIATION OR CYCLOTRON RADIATION)  

sub_title[[462, 655, 533, 673]]
## BONUS  

text[[115, 691, 857, 744]]
10) Energy – Multiple Choice Researchers at Argonne National Lab have been looking for ways to maximize the efficiency of solar cells. One of the most promising designs uses the structure of calcium titanate, which is the chemical name for which of the following minerals?  

text[[115, 761, 242, 832]]
W) Vermiculite X) Perovskite Y) Dolomite Z) Rutile  

text[[115, 849, 355, 867]]
ANSWER: X) PEROVSKITEsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 872, 181]]
11) Earth and Space – Multiple Choice Which of the following most accurately describes the matter distribution of the universe from the standpoint of an observer on Earth and on the gigaparsec scale?  

text[[115, 199, 355, 270]]
W) Isotropic, heterogeneous  
X) Isotropic, homogenous  
Y) Anisotropic, homogeneous  
Z) Anisotropic, heterogenous  

text[[115, 286, 499, 305]]
ANSWER: X) ISOTROPIC, HOMOGENEOUS  

sub_title[[462, 322, 533, 340]]
## BONUS  

text[[115, 357, 861, 393]]
11) Earth and Space – Short Answer What hypothesized region of the solar system contains trillions of icy bodies that are thought to be the source of long-period comets?  

text[[115, 410, 336, 428]]
ANSWER: OORT CLOUD  

sub_title[[456, 481, 541, 499]]
## TOSS-UP  

text[[115, 516, 828, 552]]
12) Physics – Short Answer What is the amount of energy, in joules, stored in a 4-farad capacitor with a potential difference of 23 volts?  

text[[115, 569, 255, 586]]
ANSWER: 1,058  

sub_title[[462, 603, 533, 621]]
## BONUS  

text[[115, 638, 877, 691]]
12) Physics – Short Answer The integral form of Gauss’ law for magnetism states that a closed surface integral across a magnetic vector field for any region of space equals which of the following?  

text[[115, 708, 744, 777]]
W) The enclosed volume integral of magnetic flux  
X) The enclosed volume integral of the bound electric field  
Y) The permeability of the enclosed region divided by the volume of the region  
Z) Zero  

text[[115, 794, 285, 812]]
ANSWER: Z) ZEROsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 799, 164]]
13) Biology - Short Answer On which face of the Golgi apparatus are vesicles with unpackaged proteins received?  

text[[115, 180, 295, 198]]
ANSWER: CIS FACE  

sub_title[[463, 215, 534, 234]]
## BONUS  

text[[115, 250, 808, 287]]
13) Biology - Short Answer Identify all the following that are examples of torpor: 1) Brumation; 2) Estivation; 3) Hibernation.  

text[[115, 303, 249, 320]]
ANSWER: ALL  

sub_title[[456, 372, 541, 390]]
## TOSS-UP  

text[[115, 406, 879, 443]]
14) Math - Short Answer Mike picks three letters randomly from the list of letters A, B, C, D, and E. What is the chance that Mike picks the letters B, D, and E in any order?  

text[[115, 458, 392, 477]]
ANSWER: \(10\%\) (ACCEPT: 1/10)  

sub_title[[463, 494, 534, 512]]
## BONUS  

text[[113, 528, 860, 565]]
14) Mathematics - Short Answer What is the volume of the solid generated when the curve \(f(x) = x^{2} + 1\) is rotated about the \(x\) -axis from \(x = 0\) to \(x = 1\) ?  

text[[115, 581, 266, 599]]
ANSWER: \(28\pi /15\)sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 881, 163]]
15) Physics – Short Answer Order the following substances from lowest to highest in terms of their dielectric constants at 300K: 1) Polyethylene; 2) Air; 3) Water; 4) Titanium dioxide.  

text[[115, 180, 280, 198]]
ANSWER: 2, 1, 3, 4  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 250, 850, 285]]
15) Physics – Multiple Choice Which of the following statements regarding momentum is true?  

text[[115, 303, 664, 373]]
W) Angular and linear momentum share the same units  
X) Linear momentum is a vector while angular momentum is a scalar  
Y) All collisions preserve linear momentum  
Z) Some collisions do not preserve angular momentum  

text[[115, 388, 696, 407]]
ANSWER: Y) ALL COLLISIONS PRESERVE LINEAR MOMENTUM  

sub_title[[456, 460, 540, 478]]
## TOSS-UP  

text[[115, 494, 870, 530]]
16) Earth and Space – Multiple Choice Which of the following responses correctly describes the relationship between Cepheid variable and RR Lyrae variable stars?  

text[[115, 546, 805, 617]]
W) Cepheid variables are brighter and pulsate more frequently than RR Lyrae variables  
X) Cepheid variables are brighter and pulsate less frequently than RR Lyrae variables  
Y) Cepheid variables are fainter and pulsate more frequently than RR Lyrae variables  
Z) Cepheid variables are fainter and pulsate less frequently than RR Lyrae variables  

text[[115, 633, 770, 668]]
ANSWER: X) CEPHEID VARIABLES ARE BRIGHTER AND PULSATE LESS FREQUENTLY THAN RR LYRAE VARIABLES  

sub_title[[463, 685, 533, 703]]
## BONUS  

text[[115, 720, 844, 756]]
16) Earth and Space – Multiple Choice What process occurs when glaciers cause rocks to become dislodged and join the glacier's load?  

text[[115, 773, 220, 843]]
W) Abrasion  
X) Striation  
Y) Plucking  
Z) Attrition  

text[[115, 860, 336, 878]]
ANSWER: Y) PLUCKINGsub_title[[456, 91, 541, 108]]
## TOSS-UP  

text[[115, 127, 880, 163]]
17) Chemistry – Short Answer What term describes a flash of light produced by a high-energy particle striking a fluorescent material?  

text[[115, 181, 358, 199]]
ANSWER:SCINTILLATION  

sub_title[[462, 217, 533, 235]]
## BONUS  

text[[115, 253, 857, 289]]
17) Chemistry – Multiple Choice 1-chlorobutane is reacted with potassium tert-butoxide in acetone. What functional group is predominantly formed by this reaction?  

text[[114, 306, 266, 377]]
W) Alcohol  X) Alkene  Y) Aldehyde  Z) Carboxylic acid  

text[[115, 394, 314, 412]]
ANSWER: X) ALKENE  

sub_title[[456, 465, 541, 483]]
## TOSS-UP  

text[[115, 499, 881, 552]]
18) Math – Short Answer Jimmy has a bag containing 3 red, 4 blue, and 5 green marbles. If he removes marbles from the bag randomly, how many must he remove in order to ensure he takes out at least 1 of each color?  

text[[115, 569, 231, 586]]
ANSWER: 10  

sub_title[[462, 604, 533, 622]]
## BONUS  

text[[115, 639, 707, 657]]
18) Math – Short Answer What is the unit digit of 4 to the 358th power?  

text[[115, 674, 221, 691]]
ANSWER: 6sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 876, 163]]
19) Biology - Short Answer What plant hormone is responsible for promoting seed dormancy and drought tolerance?  

text[[116, 180, 352, 198]]
ANSWER: ABSCISIC ACID  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 250, 758, 269]]
19) Biology - Multiple Choice Which of the following is true about glucagon?  

text[[115, 284, 844, 356]]
W) Glucagon is produced by the alpha cells of the pancreas and decreases blood sugar levels X) Glucagon is produced by the alpha cells of the pancreas and increases blood sugar levels Y) Glucagon is produced by the beta cells of the pancreas and decreases blood sugar levels Z) Glucagon is produced by the beta cells of the pancreas and increases blood sugar levels  

text[[115, 371, 870, 407]]
ANSWER: X) GLUCAGON IS PRODUCED BY THE ALPHA CELLS OF THE PANCREAS AND INCREASES BLOOD SUGAR LEVELS  

sub_title[[456, 460, 541, 478]]
## TOSS-UP  

text[[115, 495, 867, 548]]
20) Chemistry - Multiple Choice When tin is heated in air, it forms tin (IV) oxide [tin four oxide]. However, when lead is heated in air, it forms lead (II) oxide [lead two oxide]. Which of the following best explains this phenomenon?  

text[[115, 565, 525, 635]]
W) Lead has a lower ionization energy than tin 
X) Lead exhibits a stronger inert-pair effect than tin 
Y) Tin exhibits a diagonal relationship with lead 
Z) Tin has fewer shielding electrons than lead  

text[[115, 652, 797, 671]]
ANSWER: X) LEAD EXHIBITS A STRONGER INERT-PAIR EFFECT THAN TIN  

sub_title[[463, 688, 533, 706]]
## BONUS  

text[[115, 724, 880, 776]]
20) Chemistry - Short Answer What spectroscopic technique, analogous to NMR, utilizes the spins of unpaired electrons to study compounds such as coordination complexes and organic radicals?  

text[[115, 794, 847, 829]]
ANSWER: ELECTRON PARAMAGNETIC RESONANCE (ACCEPT: EPR; ELECTRON SPIN RESONANCE; ESR)sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 872, 199]]
21) Energy - Multiple Choice Researchers at Lawrence Berkeley National Lab have been developing new technologies that will allow them to increase the flight time of unmanned aerial devices such as drones using thermophotovoltaic generators, which convert which of the following types of electromagnetic radiation into electrical energy?  

text[[115, 215, 207, 286]]
W) UV 
X) Infrared 
Y) Visible 
Z) X-ray  

text[[116, 303, 335, 321]]
ANSWER: X) INFRARED  

sub_title[[462, 339, 533, 357]]
## BONUS  

text[[115, 373, 866, 427]]
21) Energy - Short Answer Scientists at Ames Laboratory have been using porous inorganic substances that allow for small molecules to pass through for catalytic purposes. What is the name for this type of material?  

text[[115, 442, 861, 461]]
ANSWER: MOLECULAR SIEVE (DO NOT ACCEPT: SEMIPERMEABLE MEMBRANE)  

sub_title[[456, 513, 541, 531]]
## TOSS-UP  

text[[115, 547, 848, 584]]
22) Earth and Space - Multiple Choice Which of the following responses most accurately explains why oceanic ridges are elevated compared to the surrounding seafloor?  

text[[115, 600, 845, 635]]
W) Convection currents in the mantle push the oceanic crust near divergent plate boundaries upwards  

text[[115, 636, 866, 689]]
X) Magma rising from the mantle naturally forms a dome like shape is it cools underwater 
Y) Freshly formed oceanic crust is less dense than older oceanic crust, and thus is raised higher 
Z) Lithosphere proximate to plate boundaries is naturally thicker and appears taller.  

text[[115, 704, 842, 740]]
ANSWER: Y) FRESHLY FORMED OCEANIC CRUST IS LESS DENSE THAN OLDER OCEANIC CRUST, AND THUS IS RAISED HIGHER  

sub_title[[462, 757, 533, 775]]
## BONUS  

text[[115, 791, 857, 826]]
22) Earth and Space - Short Answer What is the name of the region of the H-R diagram on which variable stars lie?  

text[[115, 843, 391, 861]]
ANSWER: INSTABILITY STRIPsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[113, 127, 863, 163]]
23) Math – Short Answer If sine theta equals the square root of 2 over 2 and cotangent theta equals the negative square root of 3, then in what quadrant does theta lie?  

text[[115, 180, 408, 198]]
ANSWER: SECOND (ACCEPT: 2)  

sub_title[[463, 215, 533, 233]]
## BONUS  

text[[115, 250, 830, 286]]
23) Math – Short Answer A right triangle has side lengths of 5, 12, and 13. Giving your answer as a fraction, what is the length of the altitude to the hypotenuse?  

text[[115, 303, 255, 320]]
ANSWER: 60/13