
## TOSS-UP  


1) Chemistry – Multiple Choice  Acetic acid is treated with excess lithium aluminum hydride, followed by the addition of water to the reaction vessel. The final product is observed to be a primary alcohol. Which of the following roles does water play in this reaction?  


W) Protecting group 
X) Proton source 
Y) Electrophile 
Z) Nucleophile  


ANSWER: X) PROTON SOURCE  


## BONUS  


1) Chemistry – Short Answer  In the equation for calculating lattice energy, what material-specific constant accounts for the arrangement of ions in the lattice?  


ANSWER: MADELUNG CONSTANT  


## TOSS-UP  


2) Math – Short Answer  What are the \(xy\) coordinates of the centroid of the triangle with vertices at the points (0, 4), (0, 0), and (1, 2)?  


ANSWER: (1/3, 2)  


## BONUS  


2) Math – Short Answer  Given that \(y =\) the natural log of \(y + x\) , then, in terms of \(y\) , what is the derivative of \(y\) with respect to \(x\) ?  


ANSWER: \(y / (y - 1)\)
## TOSS-UP  


3) Earth and Space – Multiple Choice How many distinct ice sheets exist on Earth?  


W) 1 
X) 2 
Y) 6 
Z) 8  


ANSWER: X) 2  


## BONUS  


3) Earth and Space – Short Answer When a groundwater well is pumped excessively, the level of the aquifer surrounding the well may fall, resulting in what phenomenon?  


ANSWER: DRAWDOWN (ACCEPT: CONE OF DEPRESSION)  


## TOSS-UP  


4) Biology – Short Answer Identify all of the following three organisms that are coleomates [SEE-luh-mates]: 1) Sea urchin; 2) Earthworm; 3) Planarian.  


ANSWER: 1 AND 2  


## BONUS  


4) Biology – Short Answer The “beta” form of what specific protein is associated with many neurodegenerative diseases such as Alzheimer’s disease due to its aggregation into damaging plaques?  


ANSWER: AMYLOID
## TOSS-UP  


5) Physics - Short Answer A step-down transformer has a primary winding of 180 coils and is supplied an emf [e-m-f] of 100 volts. If the secondary winding consists of 36 coils, then what is the secondary voltage of the transformer?  


ANSWER: 20  


## BONUS  


5) Physics - Short Answer The position of a particle is given by the function \(x(t) = 2t^3 - 8t^2 + 8t + 20\) . At what times \(t\) is the particle not moving?  


ANSWER: \(t = 2\) AND \(t = 3 / 2\)  


## TOSS-UP  


6) Energy - Short Answer DOE researchers at the Joint Genome Institute have been studying microbial cell walls in order to develop new methods for differentiating organisms. What polysaccharide is responsible for the rigidity of fungal cell walls?  


ANSWER: CHITIN  


## BONUS  


6) Energy - Short Answer Scientists at Argonne National Lab have been investigating network solids due to their potential applications in solid-state quantum technologies. Identify all of the following three compounds that are network solids: 1) Silicon carbide; 2) Silicon dioxide; 3) Boron nitride.  


ANSWER: ALL
## TOSS-UP  


7) Chemistry – Multiple Choice Which of the following is NOT true regarding substitution reactions?  


W) Rearrangements occur with SN1 but not SN2 reactions  
X) Polar aprotic solvents speed up SN1 reactions  
Y) Excellent leaving groups are required for SN1 reactions  
Z) SN2 reactions often occur with inversion of configuration  


ANSWER: X) POLAR APROTIC SOLVENTS SPEED UP SN1 REACTIONS  


## BONUS  


7) Chemistry – Short Answer In some octahedral metal complexes, orbital degeneracy is lost and the resulting complex exhibits an altered geometry. What effect is responsible for this?  


ANSWER: JAHN-TELLER EFFECT (ACCEPT: JAHN-TELLER DISTORTION)  


## TOSS-UP  


8) Biology – Multiple Choice Which of the following plants does NOT use the C4 pathway during photosynthesis?  


W) Maize  
X) Orchid  
Y) Sugarcane  
Z) Switchgrass  


ANSWER: X) ORCHID  


## BONUS  


8) Biology – Multiple Choice What term describes the continuum of cytoplasm connected by plasmodesmata between plant cells?  


W) Apoplast  
X) Symplast  
Y) Protoplast  
Z) Amyloplast  


ANSWER: X) SYMPLAST
## TOSS-UP  


9) Physics – Multiple Choice Which of the following is NOT a major reason that the measured weight of an object differs from the predicted force exerted on it by gravity?  


W) The Earth is rotatingX) The Earth is not a perfect sphereY) The Earth's mass is not uniformly distributedZ) The Earth's distance from the Sun varies  


ANSWER: Z) THE EARTH'S DISTANCE FROM THE SUN VARIES  


## BONUS  


9) Physics – Short Answer What principle states that, at high quantum numbers, quantum mechanical systems must resemble classical behavior?  


ANSWER: CORRESPONDENCE PRINCIPLE  


## TOSS-UP  


10) Math – Multiple Choice If \(y = \sin x + \cos \sin x\) , which of the following expressions is equal to \(y^2\) ?  


W) 1X) \(1 + \sin 2x\) Y) Cosine \(2x\) Z) \(1 - \cos \sin 2x\)  


ANSWER: X) \(1 + \sin 2x\)  


## BONUS  


10) Math – Short Answer In radians, what is the angle measure of each acute angle in a regular 100-pointed star?  


ANSWER: \(\pi /100\)
## TOSS-UP  


11) Earth and Space – Multiple Choice At what area or areas of the Earth do the most partial solar eclipses occur?  


W) At the equator  X) At horse latitudes  Y) At approximately 45 degrees north and south of the equator  Z) At the poles  


ANSWER: Z) AT THE POLES  


## BONUS  


11) Earth and Space – Short Answer Identify all of the following three formations that are depositional shoreline features: 1) Spits; 2) Baymouth bars; 3) Sea stacks.  


ANSWER: 1 AND 2  


## TOSS-UP  


12) Chemistry – Short Answer In order for elimination to occur on a substituted cyclohexane ring by a concerted mechanism, the leaving group must exhibit what relative configuration to the abstracted proton?  


ANSWER: ANTI- COPLANAR (ACCEPT: ANTI- PERIPLANAR)  


## BONUS  


12) Chemistry – Short Answer Consider a beaker containing a saturated solution of silver sulfide, with some solid remaining at the bottom. Identify all of the following three changes to the system that would allow more silver sulfide to be dissolved: 1) Addition of ammonia; 2) Addition of sodium hydroxide; 3) Addition of more solid silver sulfide.  


ANSWER: 1 ONLY
## TOSS-UP  


13) Math - Short Answer In integers mod 6, what is 11 times 3?  


ANSWER: 3  


## BONUS  


13) Math - Short Answer A population of frogs in a local lake triples once every 16 days. If there are 10 frogs initially, how many will there be after 80 days?  


ANSWER: 2430  


## TOSS-UP  


14) Physics - Multiple Choice A 0.6-meter long string is fixed at both ends and allowed to vibrate as a standing wave. At its third harmonic, how many nodes can be found in the standing wave pattern?  


W) 2 X) 3 Y) 4 Z) 5  


ANSWER: Y) 4  


## BONUS  


14) Physics - Short Answer What is the time constant of an RC circuit, in seconds, consisting of two 5-ohm resistors in parallel connected to a battery in series with a 6-millifarad capacitor?  


ANSWER: 0.015
## TOSS-UP  


15) Biology - Multiple Choice Which of the following is false regarding protostomes?  


W) Cleavage is radial  X) Cleavage is determinate  Y) Solid masses of mesoderm form the coelom [SEE-luhm]  Z) The mouth develops from the blastopore  


ANSWER: W) CLEAVAGE IS RADIAL  


## BONUS  


15) Biology - Short Answer Identify all the following three locations where one could find simple squamous epithelium: 1) Lungs; 2) Esophagus; 3) Kidney tubules.  


ANSWER: 1 ONLY  


## TOSS-UP  


16) Energy - Short Answer Scientists at the Thomas Jefferson National Accelerator Facility have been studying mesons in order to ascertain information about the strong nuclear force. What meson are they studying, due to the fact that it is the lightest and simplest particle to experience the strong nuclear force?  


ANSWER: PION  


## BONUS  


16) Energy - Short Answer Researchers at Lawrence Berkeley National Lab have been using 3D printers to print magnetic liquid droplets for their potential applications in fields such as cancer research and artificial intelligence. Most magnetic liquids, or ferrofluids, are composed of the mineral magnetite. What is the chemical formula of this mineral?  


ANSWER: Fe3O4
## TOSS-UP  


17) Earth and Space – Multiple Choice Which of the following statements is NOT true regarding light and dark silicates?  


W) Dark silicates have higher iron and magnesium content  
X) Light silicates have higher silica content  
Y) Olivine and pyroxene are dark silicates  
Z) Biotite mica and amphibole are light silicates  


ANSWER: Z) BIOTITE MICA AND AMPHIBOLE ARE LIGHT SILICATES  


## BONUS  


17) Earth and Space – Multiple Choice What type of fracture does quartz exhibit?  


W) Irregular fracture  
X) Conchoidal fracture  
Y) Splintery fracture  
Z) Fibrous fracture  


ANSWER: X) CONCHOIDAL FRACTURE  


## TOSS-UP  


18) Math – Short Answer What is the 11th triangular number?  


ANSWER: 66  


## BONUS  


18) Math – Short Answer What is the area of an equilateral triangle that is circumscribed around a circle with a diameter of 12?  


ANSWER: 432
## TOSS-UP  


19) Chemistry - Short Answer According to hard-soft acid base theory, identify all of the following combinations of ions that, as ionic solids, are likely to be soluble in water: 1) Soft acid and hard base; 2) Hard acid and soft base; 3) Hard acid and hard base.  


ANSWER: 1 AND 2  


## BONUS  


19) Chemistry - Short Answer How many unpaired electrons are there in the compound nickel tetracarbonyl?  


ANSWER: 0  


## TOSS-UP  


20) Physics - Short Answer In beta plus decay, a proton is converted into a neutron, releasing a positron and electron neutrino. This process is mediated by the emission of what specific virtual particle?  


ANSWER: W+ BOSON (DO NOT ACCEPT: W BOSON; W- BOSON)  


## BONUS  


20) Physics - Short Answer What is the average power, in watts, of an AC circuit with a root-mean-square current of 3 amps and a resistance of 12 ohms?  


ANSWER: 54
## TOSS-UP  


21) Biology - Short Answer Order the following three flower organs from the most lateral to most medial: 1) Sepals; 2) Petals; 3) Carpels.  


ANSWER: 1, 2, 3  


## BONUS  


21) Biology - Short Answer What genus of bacteria is defined by their lack of cell wall?  


ANSWER: MYCOPLASMA  


## TOSS-UP  


22) Energy - Short Answer DOE researchers at Argonne National Lab have been using the Advanced Photon Source to examine crystal defects. They do this by firing photons at samples and observing the resulting patterns for anomalies. Photons in what range of the electromagnetic spectrum are most likely used for these purposes?  


ANSWER: X- RAY  


## BONUS  


22) Energy - Short Answer Scientists at Ames Lab have been using mass spectrometry in order to identify specific compounds. When ketone functional groups are present in these compounds, they often produce fragments that differ from their predicted structure. This is a result of what phenomenon?  


ANSWER: MCLAFFERTY REARRANGEMENT
## TOSS-UP  


23) Earth and Space – Multiple Choice Which of the following types of silicate do micas belong to?  


W) Single tetrahedral silicates  
X) Single chain silicates  
Y) Double chain silicates  
Z) Sheet silicates  


ANSWER: Z) SHEET SILICATES  


## BONUS  


23) Earth and Space – Short Answer What is the term for the process in which a variety of igneous rocks are produced by a single parent magma?  


ANSWER: MAGMATIC DIFFERENTIATION