
## ROUND 3  


## TOSS-UP  


1) Chemistry Multiple Choice Which of the following functional groups has the carbon atom in an \(sp^3\) hybridized state?  


W) Alcohol 
X) Ketone 
Y) Aldehyde 
Z) Amide  


ANSWER: W) Alcohol  


## BONUS  


1) Chemistry Short Answer Cracking of hydrocarbons results in the formation of what functional group?  


ANSWER: Alkene  


## TOSS-UP  


2) Math Short Answer What is the second derivative of \(5x^2\) at \(x = 5\) ?  


ANSWER: 10  


## BONUS  


2) Math Short Answer Find the sum of the arithmetic series with first term 5, last term 37, and common difference 4.  


ANSWER: 189
## TOSS-UP  


3) Physics Short Answer A 1 kilogram block slides frictionlessly down a hill with height 5 meters, what is its final velocity in meters per second, rounded to the nearest integer, when it reaches the bottom?  


ANSWER: 10  


## BONUS  


3) Physics Short Answer Name all of the following that are true of the torque vector. 1) It is equivalent to the cross product of force and radius 2) It points in the same direction as angular acceleration 3) It is the dot product of moment of inertia and angular acceleration  


ANSWER: 1 and 2  


## TOSS-UP  


4) Biology Short Answer What secondary messenger has an inverse relation to the concentration of glucose within a cell?  


ANSWER: cyclic AMP or cyclic Adenosine monophosphate  


## BONUS  


4) Biology Short Answer What water-soluble vitamin helps in the process of collagen synthesis?  


ANSWER: Vitamin C (Accept: Ascorbic Acid)  


## TOSS-UP  


5) Earth and Space Short Answer What type of front occurs when a cold front overtakes a warm front?  


ANSWER: Occluded Front  


## BONUS  


5) Earth and Space Short Answer What is the name for the depth within an ocean in which the temperature begins to change greatly?  


ANSWER: Thermocline
## TOSS-UP  


6) Math Short Answer How many edges are there on a hexagonal prism?  


ANSWER: 18  


## BONUS  


6) Math Short Answer What is the volume of a cone with a slant height of 13, and a diameter of 10?  


ANSWER: \(100\pi\)  


## TOSS-UP  


7) Chemistry Short Answer What is the bond order of the diatomic ion \(N_{2}^{2 + }\)  


ANSWER: 2  


## BONUS  


7) Chemistry Multiple Choice Which of the following solvents would be most effective in dissolving benzene?  


W) Water 
X) Propanoic Acid 
Y) Cyclohexane 
Z) Ethanol  


ANSWER: Y) Cyclohexane
## TOSS-UP  


8) Earth and Space Multiple Choice Decreasing a star's magnitude by 1 would be closest to multiplying its brightness by which of the following numbers?  


W) 2.5 
X) 10 
Y) 25 
Z) 100  


ANSWER: W) 2.5  


## BONUS  


8) Earth and Space Multiple Choice Which of the following star colors has the shortest lifetime?  


W) White 
X) Blue 
Y) Red 
Z) Yellow  


ANSWER: X) Blue  


## TOSS-UP  


9) Biology Multiple Choice Which of the following nucleotide base pairs is a purine?  


W) Cytosine 
X) Adenine 
Y) Uracil 
Z) Thymine  


ANSWER: X) Adenine  


## BONUS  


9) Biology Short Answer The presence of what two base pairs of DNA provides the most stability within DNA's structure?  


ANSWER: Cytosine and Guanine (in any order)
## TOSS-UP  


10) Physics Short Answer What is the impulse required to change a 7 kilogram object's velocity from 4 meters per second to 10 meters per second?  


ANSWER: 42  


## BONUS  


10) Physics Short Answer What is the constant pressure heat capacity of a monatomic ideal gas, in terms of the ideal gas constant?  


ANSWER: 5/2 R  


## TOSS-UP  


11) Earth and Space Multiple Choice Which of the following periods of geological time is the oldest?  


W) Ordivician  


X) Permian  


Y) Jurassic  


Z) Devonian  


ANSWER: W) Ordivician  


## BONUS  


11) Earth and Space Multiple Choice Which of the following rocks is not coarse-grained?  


W) Granite  


X) Diorite  


Y) Dacite  


Z) Basalt  


ANSWER: Z) Basalt
## TOSS-UP  


12) Chemistry Multiple Choice Which of the following gases has the greatest root mean square speed at 200 Kelvin?  


W) Oxygen  X) Helium  Y) Neon  Z) Fluorine  


ANSWER: X) Helium  


## BONUS  


12) Chemistry Short Answer How many hydrogens are there in 4-ethyl octane?  


ANSWER: 22  


## TOSS-UP  


13) Biology Short Answer What is the name for the channel protein that primarily facilitates the diffusion of water?  


ANSWER: Aquaporin  


## BONUS  


13) Biology Short Answer What is the term for the type of speciation that occurs when two species become geographically isolated from one another?  


ANSWER: Allopatric Speciation
## TOSS-UP  


14) Physics Multiple Choice The muon and 3 neutrinos are part of the 6 leptons in the standard model. What are the other two?  


W) Electron and Proton 
X) Neutron and Proton 
Y) Electron and Tauon 
Z) Electron and Photon  


ANSWER: Y) Electron and Tauon  


## BONUS  


14) Physics Short Answer What is the normal force exerted on a block with a mass of 6 kilograms on a slope with an angle of 60 degrees to the horizontal?  


ANSWER: 30  


## TOSS-UP  


15) Math Short Answer What is the base 10 numeral 54 in base 7?  


ANSWER: 105  


## BONUS  


15) Math Short Answer What is the unit vector that points in the same direction as the vector \(< 2\) , 7, -9>?  


ANSWER: \(< \frac{\sqrt{134}}{67}, \frac{7\sqrt{134}}{134}, -\frac{9\sqrt{134}}{134} >\)
16) Biology Short Answer In which organelle does oxidative phosphorylation occur?  


ANSWER: Mitochondrion  


## BONUS  


16) Biology Multiple Choice What contribution do two cysteine amino acids provide in the tertiary structure of a protein?  


W) Disulfide bridges  
X) Ionic Bonding  
Y) Hydrophobic interactions  
Z) Hydrophilic interactions  


ANSWER: W) Disulfide bridges  


## TOSS-UP  


17) Math Short Answer What is the expected value of the sum of two dice that are rolled?  


ANSWER: 7  


## BONUS  


17) Math Short Answer How many edges exist on a dodecahedron?  


ANSWER: 30  


TOSS- UP
18) Physics Short Answer Rounded to the nearest tenth, what is the maximum height of a ball that is thrown upwards at 9.8 meters per second?  


ANSWER: 4.9 meters  


## BONUS  


18) Physics Multiple Choice Which of the following factors does not play a role in the period of a physical pendulum?  


W) Moment of Inertia 
X) Length 
Y) Rigidity 
Z) Mass  


ANSWER: Y) Rigidity  


## TOSS-UP  


19) Chemistry Short Answer Rank the following 3 ions in terms of increasing atomic radius. 1) Sodium cation 2) Magnesium cation 3) Fluorine Anion  


ANSWER: 2, 1, 3  


## BONUS  


19) Chemistry Multiple Choice Which of the following carboxylic acid derivatives is the most stable?  


W) Acid anhydride 
X) Acid Chloride 
Y) Ester 
Z) Amide  


ANSWER: Z) Amide  


TOSS- UP
20) Earth and Space Short Answer What planet has the highest eccentricity?  


ANSWER: Mercury  


## BONUS  


20) Earth and Space Multiple Choice In a telescope, you see what appears to be a cloud of gas that is illuminated blue. What type of nebula are you most likely seeing?  


W) Emission nebula 
X) Reflection nebula 
Y) Dark nebula 
Z) Balmer Nebula  


ANSWER: X) Reflection Nebula  


## TOSS-UP  


21) Math Multiple Choice Which of the following types of matrices cannot be multiplied together?  


W) A 2 by 3 and a 3 by 4 
X) A 6 by 4 and a 6 by 4 
Y) A 4 by 2 and a 2 by 4 
Z) A 3 by 3 and a 3 by 3  


ANSWER: X) A 6 by 4 and a 6 by 4  


## BONUS  


21) MATH Short Answer What is the product of the two complex numbers \(3 + 4i\) and \(6 + 7i\) ?  


ANSWER: \(- 10 + 45i\)  


TOSS- UP
22) Chemistry Short Answer What is the oxidation state of the oxygen atom in methanol?  


ANSWER: - 2  


## BONUS  


22) Chemistry Short Answer Name all of the following types of reactions that would obey Zaitsev's rule. 1) SN1 2) SN2 3) E1 4) E2  


ANSWER: 3 and 4  


## TOSS-UP  


23) Earth and Space Short Answer What is the name for the dark, vesicular rock that commonly makes up cinder cones?  


ANSWER: Scoria  


## BONUS  


23) Earth and Space Short Answer What is the name for the process in which the ground begins to behave in a fluid like manner, often as a result of earthquakes?  


ANSWER: Liquefaction