title[[345, 66, 650, 106]]
# Virtual Science Bowl High School - Regional Round  

sub_title[[448, 145, 548, 166]]
## TOSS-UP  

text[[56, 186, 896, 228]]
1) Physics – Short Answer The dot product between the force acting on an object and its displacement will result in what physical quantity?  

text[[56, 247, 237, 267]]
ANSWER: WORK  

sub_title[[457, 308, 539, 328]]
## BONUS  

text[[55, 349, 928, 431]]
1) Physics – Short Answer Water is moving through a pipe of radius 10 centimeters at 0.4 meters per second. The pipe’s radius narrows until it assumes a new radius of 5 centimeters. In pascals, to two significant figures, what is the hydrostatic pressure in the wider section of the pipe minus the hydrostatic pressure in the narrower section?  

text[[56, 450, 214, 470]]
ANSWER: 1200  

sub_title[[448, 551, 548, 571]]
## TOSS-UP  

text[[55, 592, 940, 634]]
2) Biology – Short Answer Catherine stains a sample of plant cells with a dye that selectively binds to lignin. What plant ground tissue will be MOST strongly stained by this dye?  

text[[56, 652, 354, 673]]
ANSWER: SCLERENCHYMA  

sub_title[[457, 674, 539, 694]]
## BONUS  

text[[55, 714, 919, 755]]
2) Biology – Multiple Choice Which of the following pairs of organisms shares the MOST recent common ancestor?  

text[[55, 776, 328, 857]]
W) Snail and oyster  X) Octopus and tapeworm  Y) Sea cucumber and sponge  Z) Earthworm and scallop  

text[[56, 877, 420, 897]]
ANSWER: W) SNAIL AND OYSTERsub_title[[448, 64, 548, 84]]
## TOSS-UP  

text[[55, 103, 912, 146]]
3) Earth and Space – Short Answer What mechanism of energy transport dominates in the core of a 3.5-solar-mass star?  

text[[56, 165, 316, 186]]
ANSWER: CONVECTION  

sub_title[[456, 227, 539, 248]]
## BONUS  

text[[55, 267, 936, 331]]
3) Earth and Space – Short Answer Identify all of the following three planets that, when they approach opposition, slow to a halt and trace a retrograde loop to the west before traveling eastward again: 1) Venus; 2) Jupiter; 3) Mars.  

text[[56, 350, 201, 370]]
ANSWER: 2, 3  

sub_title[[448, 409, 548, 430]]
## TOSS-UP  

text[[55, 449, 928, 515]]
4) Math – Short Answer Identify all of the following 4 rays that are intersected by the graph of \(y = 3x - 7: 1\) Positive \(x\) -axis; 2) Positive \(y\) -axis; 3) Negative \(x\) -axis; 4) Negative \(y\) -axis.  

text[[56, 532, 202, 552]]
ANSWER: 1, 4  

sub_title[[456, 593, 539, 614]]
## BONUS  

text[[55, 632, 923, 696]]
4) Math – Short Answer What is the slope of the tangent line to the curve \(x^{2}y - y^{2} = 3\) at the point (2, 3)?  

text[[56, 715, 179, 736]]
ANSWER: 6  

sub_title[[448, 795, 548, 816]]
## TOSS-UP  

text[[55, 835, 919, 879]]
5) Chemistry – Short Answer Rank the following three species by increasing boiling point: 1) Methane; 2) Hydrogen fluoride; 3) Water.  

text[[56, 897, 225, 918]]
ANSWER: 1, 2, 3sub_title[[456, 64, 539, 84]]
## BONUS  

text[[55, 104, 921, 147]]
5) Chemistry - Short Answer Rank the following three electrophiles in terms of increasing rate at which they can be alkylated: 1) Primary halide; 2) Secondary halide; 3) Tertiary halide.  

text[[57, 166, 223, 187]]
ANSWER: 3, 2, 1  

sub_title[[448, 227, 548, 247]]
## TOSS-UP  

text[[55, 267, 930, 330]]
6) Energy - Short Answer Researchers at Princeton Plasma Physics Laboratory are studying the process of accretion. This process is responsible for the activity of quasars, in which matter accretes onto what type of object?  

text[[55, 348, 755, 371]]
ANSWER: BLACK HOLE (ACCEPT: SUPERMASSIVE BLACK HOLE)  

sub_title[[456, 409, 539, 430]]
## BONUS  

text[[55, 450, 925, 513]]
6) Energy - Short Answer Scientists sponsored by the Department of Energy are studying a special excited state of carbon whose existence is necessary for the triple-alpha process to produce universally-observed amounts of carbon. What is the name of this state?  

text[[57, 531, 322, 552]]
ANSWER: HOYLE STATE  

sub_title[[448, 611, 548, 632]]
## TOSS-UP  

text[[55, 652, 928, 715]]
7) Physics - Short Answer If you graph the De Broglie [da-BROY] wavelength of a particle on the \(y\) -axis and one over the particle's momentum on the \(x\) -axis, what is the name of the constant that will equal the slope of the graph?  

text[[57, 733, 748, 756]]
ANSWER: PLANCK'S CONSTANT (ACCEPT: \(h\) ) [do not accept: \(h\) bar]  

sub_title[[456, 795, 539, 816]]
## BONUS  

text[[55, 836, 936, 919]]
7) Physics - Short Answer A bird is standing at the vertex of a cube with side length 1 meter. Every second, it randomly chooses another vertex and travels there in a straight line. In meters per second with two significant figures, what is its average speed over the course of this process?text[[56, 66, 196, 85]]
ANSWER: 1.3  

sub_title[[448, 147, 548, 167]]
## TOSS-UP  

text[[56, 186, 890, 230]]
8) Biology – Short Answer During linear electron flow, what pigment is responsible for oxidizing water?  

text[[56, 247, 396, 269]]
ANSWER: P680+ (ACCEPT: P680)  

sub_title[[456, 308, 539, 329]]
## BONUS  

text[[55, 349, 937, 412]]
8) Biology – Short Answer Identify all of the following three features that are present in both phospholipids and triglycerides: 1) Glycerol backbone; 2) Ester linkages; 3) Hydrophobic region.  

text[[56, 430, 211, 450]]
ANSWER: ALL  

sub_title[[448, 491, 548, 512]]
## TOSS-UP  

text[[55, 530, 930, 574]]
9) Earth and Space – Multiple Choice Which of the following processes produces rock melt at mid-ocean ridges?  

text[[56, 592, 312, 675]]
W) Increase in temperature 
X) Decrease in temperature 
Y) Increase in pressure 
Z) Decrease in pressure  

text[[56, 694, 462, 716]]
ANSWER: Z) DECREASE IN PRESSURE  

sub_title[[456, 755, 539, 776]]
## BONUS  

text[[55, 795, 894, 839]]
9) Earth and Space – Short Answer The Southern Oscillation Index is a measurement of geographic differences in what meteorological quantity?  

text[[55, 856, 844, 920]]
ANSWER: AIR PRESSURE (ACCEPT: SEA- LEVEL PRESSURE, BAROMETRIC PRESSURE) [do not accept: pressure]sub_title[[447, 85, 548, 105]]
## TOSS-UP  

text[[56, 125, 830, 148]]
10) Math – Multiple Choice Which of the following angles has a rational cosine?  

text[[55, 167, 152, 250]]
W) 10pi/3 
X) 11pi/4 
Y) 12pi/5 
Z) 13pi/6  

text[[56, 269, 264, 290]]
ANSWER: W) 10PI/3  

sub_title[[457, 329, 539, 350]]
## BONUS  

text[[55, 369, 932, 411]]
10) Math – Short Answer Given the segment with endpoints at (3, 4) and (7, -5), what is the \(y\) - intercept of the line that is perpendicular to this segment and intersects it at (7, -5)?  

text[[56, 429, 400, 450]]
ANSWER: - 73/9 (ACCEPT: - 8 1/9)  

sub_title[[447, 510, 548, 531]]
## TOSS-UP  

text[[56, 551, 867, 594]]
11) Chemistry – Multiple Choice Which of the following bonds has the closest bond-dissociation energy to a hydrogen-hydrogen single bond?  

text[[56, 613, 307, 696]]
W) sp carbon to hydrogen 
X) sp2 carbon to hydrogen 
Y) sp3 carbon to hydrogen 
Z) sp3 oxygen to hydrogen  

text[[56, 715, 500, 736]]
ANSWER: Y) sp3 CARBON TO HYDROGEN  

sub_title[[457, 776, 539, 797]]
## BONUS  

text[[56, 816, 935, 879]]
11) Chemistry – Short Answer Identify all of the following three amino acids whose titration curve has two equivalence points: 1) Lysine [LYE-seen]; 2) Arginine [AR-jih-neen]; 3) Valine [VAIL-een].  

text[[56, 898, 178, 918]]
ANSWER: 3sub_title[[447, 84, 548, 105]]
## TOSS-UP  

text[[55, 125, 937, 250]]
12) Energy - Short Answer Scientists at Los Alamos National Laboratory have implemented software that models how a natural disaster will impact a power network. A power network over a large region could be modeled by a graph where each vertex represents a component like a generator or transformer and edges represent power traveling from one component to another. For an undirected graph with 10 vertices and no self-connections, what is the maximum number of edges?  

text[[57, 269, 191, 288]]
ANSWER: 45  

sub_title[[457, 329, 538, 350]]
## BONUS  

text[[56, 369, 911, 411]]
12) Energy - Multiple Choice Scientists at Lawrence Berkeley National Laboratory are studying materials that do not obey Planck's law. Which of the following best explains why?  

text[[56, 430, 580, 450]]
W) The materials are composed of non-quantized matter  

text[[57, 452, 456, 471]]
X) The materials are a quark-gluon plasma  

text[[57, 472, 848, 492]]
Y) The materials contain charged particles that can absorb fractional quantum packets  

text[[57, 493, 780, 512]]
Z) The dimensions of the materials are small relative to the radiation they emit  

text[[56, 531, 899, 573]]
ANSWER: Z) THE DIMENSIONS OF THE MATERIALS ARE SMALL RELATIVE TO THE RADIATION THEY EMIT  

sub_title[[447, 633, 548, 653]]
## TOSS-UP  

text[[56, 674, 925, 715]]
13) Physics - Short Answer Contact forces, such as tension and friction, primarily originate as effects of which one of the four fundamental forces?  

text[[56, 734, 754, 755]]
ANSWER: ELECTROMAGNETISM (ACCEPT: ELECTROMAGNETIC)  

sub_title[[457, 796, 538, 816]]
## BONUS  

text[[56, 837, 936, 897]]
13) Physics - Multiple Choice A 0.2-meter cubed block with specific gravity 1.4 is initially resting on a boat. After it is dropped into the water, by how many cubic meters does the volume of displaced water decrease?  

text[[57, 919, 106, 937]]
W) 0text[[55, 45, 130, 105]]
X) 0.08Y) 0.28Z) 2.8  

text[[56, 125, 238, 146]]
ANSWER: X) 0.08  

sub_title[[448, 207, 548, 227]]
## TOSS-UP  

text[[56, 246, 915, 290]]
14) Biology - Multiple Choice Which of the following is most likely to be observed in the "transcription bubble" during transcriptional elongation?  

text[[55, 309, 283, 390]]
W) Hairpin loopsX) DNA-RNA hybridsY) IRES [EYE-ris] sitesZ) Inversions  

text[[56, 410, 410, 431]]
ANSWER: X) DNA-RNA HYBRIDS  

sub_title[[457, 451, 538, 472]]
## BONUS  

text[[55, 491, 935, 594]]
14) Biology - Short Answer If the critical dark period of a long-day plant is 13 hours, then identify all of the following three conditions that would cause this plant to flower: 1) Keeping the plant in the dark while flashing a bright red light every 12 hours; 2) Keeping the plant in 12 hours of light then 12 hours of darkness; 3) Keeping the plant in 10 hours of light then 14 hours of darkness.  

text[[56, 613, 202, 633]]
ANSWER: 1, 2  

sub_title[[448, 694, 548, 714]]
## TOSS-UP  

text[[56, 734, 941, 797]]
15) Earth and Space - Short Answer What solar-system object has a radius about \(75\%\) that of Mars, has no atmosphere, and is thought to have a liquid ocean with more water than Earth's global ocean?  

text[[56, 816, 299, 836]]
ANSWER: GANYMEDE  

sub_title[[457, 877, 538, 897]]
## BONUStext[[55, 44, 910, 106]]
15) Earth and Space – Short Answer Identify all of the following three improvements that would increase the magnification of an optical telescope: 1) Increasing the diameter; 2) Increasing the focal length of the objective; 3) Increasing the focal length of the eyepiece.  

text[[56, 125, 180, 145]]
ANSWER: 2  

sub_title[[447, 207, 549, 227]]
## TOSS-UP  

text[[55, 247, 924, 290]]
16) Math – Short Answer How many sides does a regular polygon have if its smallest angle of turn symmetry is 1.5 degrees?  

text[[56, 308, 203, 328]]
ANSWER: 240  

sub_title[[457, 370, 539, 390]]
## BONUS  

text[[55, 410, 870, 452]]
16) Math – Short Answer When applying the Euclidean algorithm to find the greatest common divisor of 274 and 936, what is the remainder after the third step?  

text[[56, 471, 191, 491]]
ANSWER: 22  

sub_title[[447, 552, 549, 572]]
## TOSS-UP  

text[[55, 592, 857, 635]]
17) Chemistry – Multiple Choice Which of the following pH values is closest to the equivalence point when titrating acetic acid with sodium hydroxide?  

text[[55, 654, 104, 737]]
W) 3 X) 5 Y) 7 Z) 9  

text[[56, 756, 207, 777]]
ANSWER: Z) 9  

sub_title[[457, 817, 539, 837]]
## BONUS  

text[[55, 857, 870, 900]]
17) Chemistry – Short Answer Rank the following three molecules by increasing pKa [p.k.a.]:  

text[[56, 899, 518, 920]]
1) Methane; 2) Ethyne [eh-THIGH-n]; 3) Ethene.sub_title[[448, 125, 549, 146]]
## TOSS-UP  

text[[56, 165, 900, 228]]
18) Energy - Short Answer Scientists at the Joint Genome Institute are studying the photosynthesis pathway in Kalanchoe, a succulent. What is the name for the photosynthesis variant it performs?  

text[[56, 246, 758, 268]]
ANSWER: CAM (ACCEPT: CRASSULACAEAN ACID METABOLISM)  

sub_title[[456, 308, 539, 329]]
## BONUS  

text[[56, 348, 902, 411]]
18) Energy - Short Answer Oak Ridge National Laboratory researchers are studying theobromine, which is a methylated form of caffeine. What specific element in theobromine bears this extra methyl group?  

text[[57, 429, 285, 450]]
ANSWER: NITROGEN  

title[[395, 492, 603, 553]]
# Virtual Science Bowl Middle School Preliminary Round  

sub_title[[448, 592, 548, 612]]
## TOSS-UP  

text[[56, 632, 884, 675]]
1) Physical Science - Short Answer What is the name of the gas law that states that the volume of a given gas is proportional to its temperature and to no other quantity?  

text[[57, 694, 337, 714]]
ANSWER: CHARLES' LAW  

sub_title[[456, 755, 539, 775]]
## BONUS  

text[[56, 795, 932, 858]]
1) Physical Science - Short Answer Light within a material with an index of refraction of 2, hits the boundary between the material and the outside air at an incident angle of 45 degrees. In degrees, what is the smallest angle between the incident ray and the resulting ray?  

text[[57, 877, 191, 896]]
ANSWER: 90sub_title[[448, 44, 548, 64]]
## TOSS-UP  

text[[55, 84, 931, 128]]
2) Earth and Space – Multiple Choice Which of the following is indicated by closely spaced contours on a map?  

text[[55, 147, 199, 229]]
W) Steep slope 
X) Basin 
Y) Valley 
Z) Plane  

text[[56, 247, 346, 268]]
ANSWER: W) STEEP SLOPE  

sub_title[[457, 308, 539, 329]]
## BONUS  

text[[55, 349, 915, 412]]
2) Earth and Space – Short Answer Identify all of the following three rock properties that differ between granite and rhyolite: 1) Chemical composition; 2) Bulk mineralogy; 3) Crystal size.  

text[[56, 430, 178, 450]]
ANSWER: 3sub_title[[448, 44, 547, 64]]
## TOSS-UP  

text[[55, 84, 937, 149]]
3) Math – Short Answer Identify all of the following four types of quadrilaterals that must be parallelograms: 1) Kites; 
2) Rectangles; 3) Rhombuses; 4) Trapezoids.  

text[[56, 167, 202, 187]]
ANSWER: 2, 3  

sub_title[[457, 227, 539, 248]]
## BONUS  

text[[55, 268, 936, 310]]
3) Math – Short Answer If it takes three-quarters of an hour to paint one-fifth of a wall, what fraction of the wall will be painted in two hours?  

text[[56, 329, 209, 350]]
ANSWER: 8/15  

sub_title[[448, 389, 548, 410]]
## TOSS-UP  

text[[55, 429, 925, 472]]
4) Life Science – Short Answer In mitochondria, ATP synthase is powered by a gradient of what ion?  

text[[55, 490, 448, 512]]
ANSWER: HYDROGEN (ACCEPT: H+)  

sub_title[[457, 552, 539, 573]]
## BONUS  

text[[55, 592, 928, 636]]
4) Life Science – Short Answer Lucy, of fossil fame, is an example of an early hominid that walked upright. To what genus did Lucy belong?  

text[[55, 653, 876, 696]]
ANSWER: AUSTRALOPITHECUS (ACCEPT: AUSTRALOPITHECINES, AUSTRALOPITH)sub_title[[448, 44, 548, 64]]
## TOSS-UP  

text[[55, 84, 884, 127]]
5) Energy – Short Answer Scientists at Ames Laboratory are studying the properties of twisted bi-layer graphene. This is a material composed entirely of what element?  

text[[56, 145, 400, 167]]
ANSWER: CARBON (ACCEPT: C)  

sub_title[[457, 227, 539, 248]]
## BONUS  

text[[55, 267, 920, 330]]
5) Energy – Short Answer Scientists at SLAC National Accelerator Laboratory are using x-ray fluorescence to image metals in fossils. What metal, found in malachite, did they recently use to determine the likely coat color of a mouse fossil?  

text[[56, 348, 402, 370]]
ANSWER: COPPER (ACCEPT: Cu)  

sub_title[[448, 428, 548, 449]]
## TOSS-UP  

text[[55, 469, 812, 492]]
6) Physical Science – Short Answer What is the chemical formula of table salt?  

text[[56, 510, 216, 531]]
ANSWER: NaCl  

sub_title[[457, 574, 539, 594]]
## BONUS  

text[[55, 613, 930, 676]]
6) Physical Science – Short Answer Consider a dipole that causes an electric potential in the space around it. Far from the dipole, the potential is directly proportional to what power of the distance from the dipole?  

text[[56, 694, 342, 715]]
ANSWER: NEGATIVE TWOsub_title[[448, 44, 548, 64]]
## TOSS-UP  

text[[55, 84, 936, 127]]
7) Earth and Space – Short Answer What is the name for the 18-year cycle that describes the interval of time between eclipses?  

text[[56, 145, 241, 166]]
ANSWER: SAROS  

sub_title[[457, 207, 539, 228]]
## BONUS  

text[[55, 246, 940, 330]]
7) Earth and Space – Short Answer Identify all of the following three statements about multi-star systems that are TRUE: 1) Evidence suggests that the Sun once belonged to a binary star system; 2) White dwarf stars are rarely found in binary systems; 3) A majority of stars are found in binary systems.  

text[[56, 349, 178, 369]]
ANSWER: 3  

sub_title[[448, 410, 548, 430]]
## TOSS-UP  

text[[55, 449, 928, 514]]
8) Math – Short Answer An item that originally sold for 64 dollars was discounted 40%. After a few days, it was discounted another 30% from the discounted price. What was the final percentage of discount from the original price?  

text[[56, 531, 191, 551]]
ANSWER: 58  

sub_title[[457, 592, 539, 613]]
## BONUS  

text[[55, 632, 930, 676]]
8) Math – Short Answer What is the diameter of the circle with center at (9, -3) and passing through the point (-4, 8)?  

text[[56, 694, 227, 716]]
ANSWER: \(2\sqrt{290}\)sub_title[[448, 45, 547, 65]]
## TOSS-UP  

text[[55, 84, 935, 127]]
9) Life Science – Short Answer What is the general term for metabolic reactions that harvest energy by breaking high-energy chemical bonds to form low-energy ones?  

text[[55, 145, 568, 167]]
ANSWER: CATABOLIC (ACCEPT: CATABOLISM)  

sub_title[[457, 207, 539, 227]]
## BONUS  

text[[55, 247, 924, 310]]
9) Life Science – Short Answer A person hears a sound. Place the following three locations through which the sound will pass in chronological order: 1) Tympanic membrane; 2) Oval window; 3) Cochlea.  

text[[56, 329, 225, 350]]
ANSWER: 1, 2, 3  

sub_title[[448, 390, 548, 410]]
## TOSS-UP  

text[[56, 430, 933, 512]]
10) Energy – Short Answer Lawrence Berkeley National Lab scientists are neutralizing coronavirus proteins using Fabs, which are synthetic small proteins specific to the active site of the coronavirus proteins. Fabs are derived from what protein component of the human immune system?  

text[[56, 530, 654, 553]]
ANSWER: ANTIBODIES (ACCEPT: IMMUNOGLOBULINS)  

sub_title[[457, 592, 539, 612]]
## BONUS  

text[[56, 632, 937, 715]]
10) Energy – Short Answer Scientists supported by the Department of Energy are determining the wavefunction of various molecular systems. The wavefunction is a concept that arose from what relation that states that all matter has a wavelength inversely proportional to its momentum?  

text[[56, 733, 803, 756]]
ANSWER: DE BROGLIE RELATION (ACCEPT: DE BROGLIE EQUATION)sub_title[[448, 44, 548, 64]]
## TOSS-UP  

text[[55, 84, 907, 146]]
11) Physical Science – Short Answer What is the term given to the phenomenon in which multiple Lewis structures average together to describe the total electronic configuration of a molecule?  

text[[56, 166, 305, 187]]
ANSWER: RESONANCE  

sub_title[[457, 227, 539, 248]]
## BONUS  

text[[55, 267, 923, 310]]
11) Physical Science – Short Answer Rank the following three diatomic molecules in terms of increasing bond length: 1) Oxygen; 2) Fluorine; 3) Nitrogen.  

text[[56, 329, 226, 350]]
ANSWER: 3, 1, 2  

sub_title[[448, 409, 548, 430]]
## TOSS-UP  

text[[56, 449, 875, 472]]
12) Earth and Space – Short Answer Emerald is the gemstone name for what mineral?  

text[[56, 491, 243, 512]]
ANSWER: BERYL  

sub_title[[457, 552, 539, 573]]
## BONUS  

text[[56, 592, 902, 655]]
12) Earth and Space – Short Answer Place the following three features of a passive continental margin in order of increasing distance from the shoreline: 1) Continental rise; 2) Continental shelf; 3) Abyssal plain.  

text[[56, 674, 226, 694]]
ANSWER: 2, 1, 3sub_title[[448, 44, 548, 64]]
## TOSS-UP  

text[[55, 84, 880, 127]]
13) Math – Short Answer A circle is centered at the point (3, 4) and passes through the point (8, 1). What is the area of the circle?  

text[[56, 146, 203, 166]]
ANSWER: 34π  

sub_title[[457, 207, 539, 227]]
## BONUS  

text[[55, 246, 927, 290]]
13) Math – Short Answer What is the sum of the infinite geometric sequence with first term 8 and second term 5?  

text[[55, 308, 388, 329]]
ANSWER: 64/3 (ACCEPT: 21 1/3)  

sub_title[[448, 369, 548, 389]]
## TOSS-UP  

text[[55, 408, 933, 452]]
14) Life Science – Short Answer What is the term, for the part of a gene that is kept after the splicing process, and is ultimately encoded in functional protein?  

text[[56, 470, 231, 490]]
ANSWER: EXON  

sub_title[[457, 531, 539, 551]]
## BONUS  

text[[55, 571, 915, 615]]
14) Life Science – Multiple Choice Which of the following structures is of the appropriate size scale to be a target of the antigen-binding site of an antibody?  

text[[55, 634, 326, 715]]
W) Protruding oxygen atoms X) A group of amino acids Y) A whole protein Z) A cell  

text[[55, 734, 490, 756]]
ANSWER: X) A GROUP OF AMINO ACIDSsub_title[[448, 44, 547, 64]]
## TOSS-UP  

text[[55, 84, 914, 146]]
15) Energy - Short Answer Researchers at Sandia National Laboratory are investigating algal biofuels. With the exception of blue-green algae, most algae belong to what kingdom in the 5-kingdom classification scheme?  

text[[55, 166, 504, 187]]
ANSWER: PROTISTA (ACCEPT: PROTISTS)  

sub_title[[457, 226, 538, 247]]
## BONUS  

text[[55, 267, 914, 329]]
15) Energy - Short Answer Researchers at Savannah River National Lab are analyzing the process of absorption onto solid catalysts for natural gas purification. When saturated, this reaction will proceed with a reaction order of what?  

text[[55, 349, 228, 369]]
ANSWER: ZERO  

image[[55, 495, 943, 595]]  

title[[346, 598, 650, 639]]
# Virtual Science Bowl High School - Regional Round  

sub_title[[448, 677, 547, 697]]
## TOSS-UP  

text[[55, 717, 865, 760]]
1) Physics - Short Answer The momentum of a particle is plotted against time. What physical quantity corresponds to the slope of this plot?  

text[[56, 779, 241, 799]]
ANSWER: FORCE  

sub_title[[457, 860, 538, 880]]
## BONUS  

text[[55, 901, 916, 942]]
1) Physics - Multiple Choice In meters per second, which of the following is closest to the speed of sound in air at 320 degrees Celsius?text[[55, 65, 130, 145]]
W) 430 
X) 480 
Y) 530 
Z) 580  

text[[56, 166, 232, 187]]
ANSWER: X) 480  

sub_title[[448, 287, 548, 308]]
## TOSS-UP  

text[[55, 327, 937, 371]]
2) Biology - Short Answer Identify all of the following three NTPs that DNA polymerase III can add to a growing strand of DNA under normal conditions: 1) ATP; 2) UTP; 3) CTP.  

text[[56, 389, 231, 410]]
ANSWER: NONE  

sub_title[[457, 410, 539, 430]]
## BONUS  

text[[55, 450, 940, 533]]
2) Biology - Short Answer Identify all of the following three statements that are TRUE of both meiosis and mitosis: 1) The daughter cells are genetically identical to one another; 2) DNA replication occurs prior to division; 3) They introduce genetic variability in the form of recombination.  

text[[56, 553, 179, 572]]
ANSWER: 2  

sub_title[[448, 652, 546, 673]]
## TOSS-UP  

text[[55, 694, 936, 736]]
3) Earth and Space - Multiple Choice Helium rain on Saturn could best explain which of the following observations?  

text[[55, 755, 744, 839]]
W) The white spot that appears every 30 Earth-years near Saturn's equator 
X) The composition of Saturn's inner core 
Y) Saturn's higher-than-expected blackbody temperature 
Z) Saturn's variable magnetic field strength  

text[[55, 856, 919, 878]]
ANSWER: Y) SATURN'S HIGHER-THAN-EXPECTED BLACKBODY TEMPERATURE  

sub_title[[457, 919, 539, 939]]
## BONUStext[[55, 64, 888, 107]]
3) Earth and Space – Rank the following three celestial bodies in order of increasing core volume relative to total volume: 1) The Moon; 2) Mercury; 3) Earth.  

text[[56, 125, 225, 146]]
ANSWER: 1, 3, 2  

sub_title[[448, 208, 549, 228]]
## TOSS-UP  

text[[55, 247, 900, 290]]
4) Math – Short Answer In an isosceles triangle, the measure of the vertex angle is seven times the measure of a base angle. What is the degree measure of the vertex angle?  

text[[56, 308, 203, 328]]
ANSWER: 140  

sub_title[[457, 370, 539, 390]]
## BONUS  

text[[55, 409, 930, 452]]
4) Math – Short Answer Two dice are rolled. What is the probability that the sum of the two numbers rolled is prime?  

text[[56, 470, 208, 491]]
ANSWER: 5/12  

sub_title[[448, 572, 549, 592]]
## TOSS-UP  

text[[55, 612, 896, 655]]
5) Chemistry – Short Answer The vapor pressure of a liquid is defined as the pressure at which the rate of condensation is equal to the rate of what process for that liquid?  

text[[56, 672, 622, 695]]
ANSWER: EVAPORATION (ACCEPT: VAPORIZATION)  

sub_title[[457, 755, 539, 775]]
## BONUS  

text[[55, 795, 850, 838]]
5) Chemistry – Multiple Choice Which of the following atoms has the greatest first ionization energy?  

text[[55, 857, 191, 939]]
W) Titanium  
X) Iron  
Y) Zinc  
Z) Manganesetext[[56, 65, 250, 85]]
ANSWER: Y) ZINC  

sub_title[[448, 187, 548, 207]]
## TOSS-UP  

text[[55, 227, 939, 290]]
6) Energy - Short Answer Scientists at Brookhaven National Lab are developing instruments for electron diffraction imaging. What is the name of the law that predicts the angles that an electron will diffract through a crystalline lattice?  

text[[56, 308, 325, 329]]
ANSWER: BRAGG'S LAW  

sub_title[[457, 389, 539, 410]]
## BONUS  

text[[55, 430, 933, 472]]
6) Energy - Short Answer Scientists at Fermilab are developing computational methods to model the interactions between phonons and what fermions that are found commonly in solids?  

text[[56, 491, 300, 512]]
ANSWER: ELECTRONS  

sub_title[[448, 611, 548, 632]]
## TOSS-UP  

text[[55, 652, 939, 695]]
7) Physics - Short Answer Giving your answer in terms of the electric field strength, \(\mathbf{E}\) , what is the electric potential for a closed path that has a radius of 3 meters in a uniform electric field?  

text[[56, 714, 180, 734]]
ANSWER: 0  

sub_title[[457, 776, 539, 797]]
## BONUS  

text[[55, 817, 936, 879]]
7) Physics - Short Answer A student pushes a cart with a nonconstant force equal to \(1 + 4\mathrm{t} + \mathrm{t}^{2}\) , where t represents time. If the student pushes the cart for 3 seconds starting from \(\mathrm{t} = 0\) , then in SI base units, what is the impulse corresponding to the student's force?  

text[[55, 897, 707, 919]]
ANSWER: 30 (ACCEPT: 30 KILOGRAM- METERS PER SECOND)sub_title[[447, 105, 549, 125]]
## TOSS-UP  

text[[55, 145, 927, 188]]
8) Biology – Multiple Choice Valves can be found in which of the following types of blood vessels in order to prevent backflow?  

text[[55, 208, 185, 290]]
W) Veins 
X) Arteries 
Y) Arterioles 
Z) Capillaries  

text[[56, 308, 270, 329]]
ANSWER: W) VEINS  

sub_title[[457, 409, 539, 430]]
## BONUS  

text[[55, 450, 888, 493]]
8) Biology – Short Answer Identify all of the following three nutrients that, if deficient, could cause chlorosis in plants: 1) Magnesium; 2) Manganese; 3) Iron.  

text[[56, 512, 211, 533]]
ANSWER: ALL  

sub_title[[448, 633, 549, 653]]
## TOSS-UP  

text[[55, 673, 876, 716]]
9) Earth and Space – Short Answer During El Niño years, what large-scale circulation system in the eastern Pacific is weakened or stops completely?  

text[[55, 734, 708, 755]]
ANSWER: WALKER CELL (ACCEPT: WALKER CIRCULATION)  

sub_title[[457, 837, 539, 857]]
## BONUS  

text[[55, 877, 928, 940]]
9) Earth and Space – Short Answer Identify all of the following three tectonic environments that typically exhibit partial melting and volcanic eruptions: 1) Ocean-ocean convergent; 2) Continent-continent convergent; 3) Ocean-continent convergent.text[[55, 66, 201, 85]]
ANSWER: 1, 3  

sub_title[[446, 187, 548, 208]]
## TOSS-UP  

text[[55, 227, 916, 270]]
10) Math – Short Answer What is the limit as \(x\) goes to zero of the fraction with numerator \(3x^2 - 28\) and denominator \(2x^2 + 7\) ?  

text[[55, 289, 191, 309]]
ANSWER: - 4  

sub_title[[456, 350, 540, 371]]
## BONUS  

text[[55, 390, 921, 432]]
10) Math – Short Answer A concert hall has 25 seats in the first row, and each row has two more seats than the row in front of it. How many seats are there in the first 22 rows?  

text[[55, 451, 214, 471]]
ANSWER: 1012  

sub_title[[446, 572, 549, 593]]
## TOSS-UP  

text[[55, 612, 940, 655]]
11) Chemistry – Short Answer Sodium has a tendency to crystallize as a body-centered-cubic unit cell. How many total sodium atoms are in one of these unit cells?  

text[[55, 674, 180, 695]]
ANSWER: 2  

sub_title[[456, 755, 540, 776]]
## BONUS  

text[[55, 795, 920, 838]]
11) Chemistry – Short Answer What is the ratio of the shortest wavelength in the hydrogen Balmer series to the shortest wavelength in the hydrogen Paschen [PASS-ken] series?  

text[[55, 856, 384, 878]]
ANSWER: 4/9 (ACCEPT: 4 TO 9)sub_title[[448, 64, 548, 84]]
## TOSS-UP  

text[[56, 104, 919, 147]]
12) Energy – Short Answer Idaho National Laboratory researchers are studying blue-green algal blooms. These blooms are caused by organisms in what phylum?  

text[[57, 166, 363, 187]]
ANSWER: CYANOBACTERIA  

sub_title[[457, 248, 539, 268]]
## BONUS  

text[[56, 288, 936, 350]]
12) Energy – Multiple Choice Scientists at Idaho National Laboratory are developing molten salt reactors. Which of the following describes one of the advantages of using molten salt in a nuclear reactor?  

text[[56, 369, 668, 451]]
W) Critical mass is easier to achieve when the fuel is a molten salt X) Molten salt can act as a high-temperature liquid coolant Y) Molten salt is effective at propagating neutron chain reactions Z) Molten salt typically acts as a good neutron absorber  

text[[56, 470, 841, 512]]
ANSWER: X) MOLTEN SALT CAN ACT AS A HIGH-TEMPERATURE LIQUID COOLANT  

sub_title[[448, 612, 548, 633]]
## TOSS-UP  

text[[56, 653, 927, 696]]
13) Physics – Short Answer What is the term for a material that can be inserted between the slabs of a parallel-plate capacitor to increase its capacitance?  

text[[57, 715, 301, 735]]
ANSWER: DIELECTRIC  

sub_title[[457, 796, 539, 816]]
## BONUS  

text[[56, 836, 936, 898]]
13) Physics – Short Answer Identify all of the following three statements that must be TRUE for a fluid undergoing laminar flow: 1) It evolves continuously with time; 2) There is no internal friction;text[[56, 45, 416, 65]]
3) Fluid elements follow smooth paths.  

text[[56, 85, 179, 105]]
ANSWER: 3  

sub_title[[447, 187, 548, 208]]
## TOSS-UP  

text[[56, 227, 904, 270]]
14) Biology – Short Answer What compound present in the bacterial cell walls facilitates trapping of crystal violet during Gram staining?  

text[[56, 287, 357, 308]]
ANSWER: PEPTIDOGLYCAN  

sub_title[[457, 329, 539, 350]]
## BONUS  

text[[55, 369, 919, 432]]
14) Biology – Short Answer A restriction enzyme has a recognition sequence that is 6 base pairs in length. If this enzyme is applied to a randomly-constructed genome of length 2 mega-base pairs, then, to one significant figure, what is the expected number of fragments?  

text[[56, 450, 202, 470]]
ANSWER: 500  

sub_title[[447, 551, 548, 572]]
## TOSS-UP  

text[[55, 592, 893, 614]]
15) Earth and Space – Short Answer What ion is the primary weak base in ocean water?  

text[[55, 632, 802, 655]]
ANSWER: BICARBONATE (ACCEPT: HYDROGEN CARBONATE, \(\mathrm{HCO_3}^-\) )  

sub_title[[457, 715, 539, 736]]
## BONUS  

text[[55, 755, 911, 818]]
15) Earth and Space – Short Answer Identify all of the following three statements that are TRUE of faults: 1) Fault scarps are created by dip-slip faults; 2) Normal faults are associated with compressional stresses; 3) A thrust fault is a type of reverse fault with a large dip angle.  

text[[56, 837, 177, 857]]
ANSWER: 1sub_title[[447, 44, 548, 65]]
## TOSS-UP  

text[[55, 84, 937, 127]]
16) Math - Short Answer With respect to the axis of symmetry of the graph of \(y = x^{2} + 12x + 25\) , what are the coordinates of the point that is symmetric to the point \((-10, 5)\) ?  

text[[56, 145, 230, 167]]
ANSWER: (- 2, 5)  

sub_title[[456, 207, 539, 228]]
## BONUS  

text[[55, 247, 940, 291]]
16) Math - Short Answer What is the sum of all of the positive integers less than 220 that are divisible by 6?  

text[[56, 309, 214, 330]]
ANSWER: 3996  

sub_title[[447, 410, 548, 431]]
## TOSS-UP  

text[[55, 451, 920, 494]]
17) Chemistry - Short Answer The strongest hydrogen bonds are typically thought to form only when hydrogen is bonded to one of what three atoms?  

text[[55, 511, 818, 535]]
ANSWER: NITROGEN, OXYGEN, AND FLUORINE (ACCEPT: N, O, AND F)  

sub_title[[456, 574, 539, 595]]
## BONUS  

text[[55, 614, 933, 657]]
17) Chemistry - Short Answer Rank the following three atoms in terms of increasing atomic radius:  

text[[56, 657, 438, 678]]
1) Chromium; 2) Scandium; 3) Titanium.  

text[[56, 697, 225, 718]]
ANSWER: 1, 3, 2  

sub_title[[447, 797, 548, 818]]
## TOSS-UP  

text[[55, 837, 937, 920]]
18) Energy - Short Answer Pacific Northwest National Laboratory scientists are studying secondary organic aerosols, which are distinguished from primary organic aerosols in that they only enter the solid phase once they undergo chemical reactions in the atmosphere. Prior to this, in what phase are those molecules?sub_title[[456, 145, 538, 166]]
## BONUS  

text[[57, 185, 916, 248]]
18) Energy – Short Answer Scientists at Oak Ridge National Laboratory are using neutron scattering to study the structures of fungi. What polymer is the major structural component of the fungal cell wall?  

text[[57, 268, 245, 288]]
ANSWER: CHITIN