
# 1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1
## TOSS-UP  


1) X-Risk - Multiple Choice Among the first proposed "doomsday devices" was a powerful thermonuclear bomb jacketed with which metal to increase its fallout?  


W) Cesium 
X) Cobalt 
Y) Thorium 
Z) Strontium  


ANSWER: X) Cobalt  


## BONUS  


1) X-Risk - Multiple Choice Peter gets infected with a reovirus, and needs to have the genome immediately sequenced in order to create an antidote for the disease. In addition, he wants to be able to see if the genome is double-stranded, so he comes up with an assay to detect whether the DNA is double-stranded by raising the temperature and assessing its UV absorbance. Which of the following techniques would he use, and what would he notice about the UV absorbance after the temperature increase?  


W) Northern blotting; increase in UV absorbance 
X) Northern blotting; no change in absorbance 
Y) Southern blotting; increase in UV absorbance 
Z) Southern blotting; no chance in UV absorbance  


ANSWER: Y) Southern blotting; increase in UV absorbance
## TOSS-UP  


2) Math - Short Answer Let \(Z\) be a standard normal variable, and let \(\mu\) [mu] and \(\sigma\) [sigma] be two real numbers greater than zero. If the random variable \(X = e^{\mu + Z\sigma}\) [x equals e to the power of the quantity mu plus z times sigma], then \(X\) is what type of distribution?  


ANSWER: Log- normal  


## BONUS  


2) Math - Multiple Choice Suppose a journal article is randomly selected from a source with an average of 1000 words per article, with a standard deviation of 200 words. Chebyshev's inequality states that the probability that the chosen article has between 600 and 1400 words can be inferred to be at least which of the following?  


W) \(50\%\) X) \(75\%\) Y) \(90\%\) Z) \(95\%\)  


ANSWER: X) \(75\%\)
## TOSS-UP  


3) Chemistry - Short Answer In contrast to amines, chiral phosphines are observed in solutions because chiral inversion occurs much more slowly. What physical effect accelerates chiral inversion in amines compared to other pyramidal molecules?  


ANSWER: Quantum tunneling  


## BONUS  


3) Chemistry - Short Answer Identify all of the following three syntheses that will form a carbon-carbon bond: 1) An alcohol is treated with triphenylphosphine in carbon tetrachloride; 2) An aldehyde is treated with an alkyl halide and lithium metal; 3) A ketone is treated with meta-chloro peroxy benzoic acid.  


ANSWER: 2 only
## TOSS-UP  


4) Earth and Space - Short Answer Order the following three geologic periods by increasing average levels of \(\mathrm{CO_2}\) : 1) Cambrian; 2) Permian; 3) Jurassic.  


ANSWER: 2, 3, 1  


## BONUS  


4) Earth and Space - Multiple Choice Which of the following processes contributes most directly to the increased albedo of sea ice compared to lake ice?  


W) Brine inclusions  
X) Brine rejection  
Y) Liquid-liquid transition  
Z) Vitrification leading to amorphous ice  


ANSWER: W) Brine inclusions
## TOSS-UP  


5) Biology - Multiple Choice The hormones beta-lipotropin and beta-endorphin are both derived from the same prohormone as what other anterior pituitary gland hormone?  


W) LH 
X) GH 
Y) TSH 
Z) ACTH  


ANSWER: Z) ACTH  


## BONUS  


5) Biology - Short Answer [Read slowly] A restriction enzyme has recognition sequence 5'GTTCA3' [5 prime GTTCA 3 prime]. If you treat a 4096 base pair long length of DNA with this restriction enzyme, what is the expected number of fragments you will have?  


ANSWER: 5
## TOSS-UP  


6) Physics - Multiple Choice Which of the following best explains the effects of rotational frame dragging from a black hole rotating counterclockwise on a planet that is orbiting counterclockwise at the black hole's equator?  


W) The planet would accelerate in its orbit. 
X) The planet would decelerate in its orbit. 
Y) The planet would become heavier. 
Z) The planet would become lighter.  


ANSWER: Z) The planet would become lighter.  


## BONUS  


6) Physics - Multiple Choice Which of the following statements is false regarding the relative permittivity of a material?  


W) It is dimensionless 
X) It is complex-valued 
Y) In anisotropic media, it can be modeled as a first-rank tensor 
Z) It is dependent on frequency  


ANSWER: Y) In anisotropic media, it can be modeled as a first-rank tensor
## TOSS-UP  


7) X-Risk - Multiple Choice The Andromeda paradox considers what would happen from the perspective of Earth if an observer traveled to Andromeda near the speed of light while an alien invasion approached Earth. If an observer leaves for Andromeda before observing the aliens' decision to invade, which of the following is true?  


W) The invasion is unknown to the observer due to spacelike light cone intervals and no warning is sent to EarthX) The invasion is known to the observer due to timelike light cone intervals but the warning sent to Earth arrives after the invasionY) The information of the invasion is blueshifted and the observer is informed before the alien arrivalZ) The information of the invasion is redshifted and the observer is informed after the alien arrival  


ANSWER: W) The invasion is unknown to the observer due to spacelike light cone intervals and no warning is sent to Earth  


## BONUS  


7) X-Risk - Short Answer Hafnium 178m2 is a candidate for experiments studying induced gamma emission, a controversial process which has the potential for use in nuclear weaponry. This process involves the fluorescent emission of gamma rays from a metastable atomic nucleus. What is the term given to these high-energy metastable states of atomic nuclei?  


ANSWER: Nuclear isomers
## TOSS-UP  


8) Math - Multiple Choice Which of the following numbers divides the sum from \(n = 1\) to 7 of \(n^7\) ?  


W) 13 
X) 35 
Y) 42 
Z) 49  


ANSWER: Z) 49  


## BONUS  


8) Math - Short Answer The point \((x,y)\) [x comma y] lies on or above the two lines with equations \(5x + 7y = 35\) and \(6x + 3y = 24\) . What is the smallest possible value of \(5x + 4y\) ?  


ANSWER: 25
## TOSS-UP  


9) Chemistry - Multiple Choice An IR spectrum contains two sharp peaks between 1200 and 1600 inverse centimeters. Which of the following functional groups is most likely responsible for both of these peaks?  


W) Enone 
X) Nitro 
Y) Enamine 
Z) Amide  


ANSWER: X) Nitro  


## BONUS  


9) Chemistry - Multiple Choice A solution of a vanadium salt is observed to have a green color, but Mossbauer spectroscopy reveals that vanadium is not in a \(+3\) oxidation state. Which of the following best explains what is happening?  


W) It is the pure hydrate of the vanadium \(2+\) ion 
X) It is a dilute solution of vanadium in the \(+4\) oxidation state 
Y) It is a mix of vanadium ions in the \(+4\) and \(+5\) oxidation states 
Z) It is an exotic vanadium species in the \(+1\) oxidation state  


ANSWER: Y) It is a mix of vanadium ions in the \(+4\) and \(+5\) oxidation states
## TOSS-UP  


10) Earth and Space - Short Answer Satellites at Lagrange points do not tend to orbit the Lagrange point in circular orbits, but rather trace paths following what family of curves?  


ANSWER: Lissajous [LEES- uh- joo]  


## BONUS  


10) Earth and Space - Multiple Choice Class S stars are characterized by which of the following compounds present in their absorption spectra?  


W) Ammonia  X) Magnesium oxide  Y) Methane  Z) Zirconium oxide  


ANSWER: Z) Zirconium oxide
## TOSS-UP  


11) Biology - Short Answer [Read slowly] A peptide is composed of the sequence, from N to C terminus, Alanine-Valine-Lysine-Asparagine-Histidine-Serine-Lysine-Glutamine. How many acetylation sites are present on this peptide?  


ANSWER: 3  


## BONUS  


11) Biology - Short Answer In plants, medium to low concentrations of indoleacetic [in-dole-uh-SEE-tic] acid is known to cause cell elongation and growth. However, it is observed that high concentrations of IAA actually inhibit cell elongation and growth. This is because high concentrations of indoleacetic acid promote the production of what other plant hormone?  


ANSWER: Ethylene
## TOSS-UP  


12) Physics - Multiple Choice A large spherical gas cloud is accreting onto a central core. Assuming material at the outer edge of the cloud is at rest, which of the following velocity profiles correctly describes the evolution of the accreted matter?  


W) Subsonic 
X) Trans-sonic 
Y) Sonic 
Z) Supersonic  


ANSWER: X) Trans- sonic  


## BONUS  


12) Physics - Short Answer To explain the low masses of neutrinos, what mechanism proposes a mass matrix where one eigenvalue is large, corresponding to the Majorana [my-ur-ON-uh] mass and the other eigenvalue is small, corresponding to the observed mass value?  


ANSWER: Seesaw mechanism
## TOSS-UP  


13) X-Risk - Multiple Choice  Updatedess decision theory allows for two agents to each predict what the other wants and do it, even if they have no way of communicating with each other. What is this behavior called?  


W) Counterfactual mugging 
X) Values handshake 
Y) Acausal trade 
Z) Simulation capture  


ANSWER: Y) Acausal trade  


## BONUS  


13) X-Risk - Multiple Choice  Despite its presence throughout nearly all of human history, vaccines for the prevention of malaria have only recently been developed, and only one is currently in use. The Mosquirix vaccine developed targets Circumsporozoite protein due to it possessing highly conserved regions among many different strains of the malaria sporozoite. Targeting this protein will cause disruption of which of the following parts of the malarial life cycle?  


W) Invasion of red blood cells through apical complex 
X) Invasion of hepatocytes in the liver 
Y) Division of merozoites inside red blood cells 
Z) Formation of gametocytes  


ANSWER: X) Invasion of hepatocytes in the liver
## TOSS-UP  


14) Math - Short Answer Identity all of the following three statements that are true regarding cyclic groups: 1) They have finite order; 2) They are Abelian; 3) They are generated by a single element.  


ANSWER: 2 and 3  


## BONUS  


14) Math - Multiple Choice Which of the following matrices \(M\) will be a solution to the polynomial \(M^2 + M - 6I = 0\) ?  


W) First row 2, 0, second row 1, -3 
X) First row 3, 0 second row -1, -2 
Y) First row 4, 1 second row 1, -5 
Z) First row 5, 0 second row 4, -4  


ANSWER: W) First row 2 0, second row 1 -3
## TOSS-UP  


15) Chemistry - Short Answer Ryan heats acetylene with hydrogen cyanide in a 2:1 ratio at 800 K. What is the major aromatic heterocycle produced by this reaction?  


ANSWER: Pyridine  


## BONUS  


15) Chemistry - Multiple Choice An organic compound is analyzed using quadrapole mass spectrometry. The relative intensities of the \(\mathbf{M}+\) , \(\mathbf{M}+1\) , and \(\mathbf{M}+2\) peaks are found to be 75, 10, and 100, respectively. Which of the following could be the identity of the compound?  


W) \(\mathrm{C_{10}H_{20}Cl_{2}}\) X) \(\mathrm{C_{12}H_{24}Cl_{2}}\) Y) \(\mathrm{C_{10}H_{20}ClBr}\) Z) \(\mathrm{C_{12}H_{24}ClBr}\)  


ANSWER: Z) \(\mathrm{C_{12}H_{24}ClBr}\)
## TOSS-UP  


16) Earth and Space - Multiple Choice What type of deep ocean sediment would be expected to dominate the Pacific along the equator where strong upwelling is present in deep waters?  


W) Siliceous [suh-LISH-is] ooze  X) Calcareous [cal- KAIR-ee-is] ooze  Y) Terrigenous sediment  Z) Cosmogenous sediment  


ANSWER: W) Siliceous ooze  


## BONUS  


16) Earth and Space - Multiple Choice How does the presence of a ridge off the US east coast during the negative mode of the North Atlantic Oscillation affect regional weather?  


W) Colder and more precipitation  X) Warmer and more precipitation  Y) Colder and less precipitation  Z) Warmer and less precipitation  


ANSWER: W) Colder and more precipitation
## TOSS-UP  


17) Biology - Short Answer In many insects, their hemolymph contains a high concentration of a certain carbohydrate that is used for both flight and antifreeze purposes. What is the identity of this carbohydrate?  


ANSWER: Trehalose  


## BONUS  


17) Biology - Multiple Choice Which of the following best describes the function of Raphide crystals in the vacuole of plants?  


W) Defense against herbivory  X) Structural support  Y) Protection against high salt concentrations  Z) Protection against freezing  


ANSWER: W) Defense against herbivory
## TOSS-UP  


18) Physics - Multiple Choice Which of the following four-vector products involving the momentum, position, wavenumber, and frequency for a particle will isolate the mass of a particle in SI base units?  


W) \(k^{\mu}k_{\mu}\) [k- mu k- mu] 
X) \(p^{\mu}p_{\mu}\) Y) \(x^{\mu}x_{\mu}\) Z) \(f^{\mu}f_{\mu}\)  


ANSWER: X) \(p^{\mu}p_{\mu}\)  


## BONUS  


18) Physics - Multiple Choice What is the momentum, in kilogram meters per second, of a visible photon that has a wavelength of 500 nanometers?  


W) \(1.33\times 10^{-24}\) X) \(1.33\times 10^{-27}\) Y) \(1.33\times 10^{-30}\) Z) \(1.33\times 10^{-33}\)  


ANSWER: X) \(1.33\times 10^{-27}\)
## TOSS-UP  


19) X-Risk - Multiple Choice Which hypothetical AI design selects its actions only from a distribution of human-like actions, rather than over all actions?  


W) Quantilizer  X) Satisficer  Y) Mild optimizer  Z) Meliorizer [MEEL-ee-ur-eye-zur]  


ANSWER: W) Quantilizer  


## BONUS  


19) X-Risk - Short Answer When using expected utility maximization, an agent may focus on very impactful outcomes with very low probabilities, even when this defies common sense. What is this problem called?  


ANSWER: Pascal's mugging
## TOSS-UP  


20) Math - Short Answer Kaylee has a collection of sticks with lengths of 3 meters, 5 meters, or 7 meters. Assuming she has a large amount of each stick length, how many triangles can Kaylee make if each side is made of one stick?  


ANSWER: 9  


## BONUS  


20) Math - Short Answer Let \(A\) , \(B\) , and \(C\) be points in the plane such that the tangents from \(A\) , \(B\) , and \(C\) to triangle \(ABC\) 's incircle have lengths 1, 2, and 3, respectively. Find the radius of triangle \(ABC\) 's incircle.  


ANSWER: 1
## TOSS-UP  


21) Chemistry - Multiple Choice Which of the following electronic transitions is responsible for the vibrant color of the titanium (IV) hexachloride complex?  


W) 3d to 3d 
X) 3d to 3p 
Y) 3p to 3d 
Z) 4s to 3d  


ANSWER: Y) 3p to 3d  


## BONUS  


21) Chemistry - Short Answer The free rotation of peptide bonds would require an electronic excitation between what two types of molecular orbitals?  


ANSWER: Nonbonding and pi antibonding
## TOSS-UP  


22) Earth and Space - Short Answer What law describes how the surface brightness of an elliptical galaxy varies with the apparent distance from the galaxy center?  


ANSWER: De Vaucouleur's law  


## BONUS  


22) Earth and Space - Short Answer The Primakoff effect, which occurs in the interior of stars, is thought to be capable of producing what hypothetical dark matter candidate?  


ANSWER: Axion
## TOSS-UP  


23) Biology - Short Answer Carbamoyl phosphate synthetase is the rate-limiting enzyme of what biochemical cycle?  


ANSWER: Urea cycle  


## BONUS  


23) Biology - Multiple Choice Which of the following features of an apoptotic cell does the TUNEL [TUN-ul] assay directly detect?  


W) Double-stranded DNA breaks 
X) Cytochrome C 
Y) Fas ligand 
Z) Heterochromatin  


ANSWER: W) Double-stranded DNA breaks
## TOSS-UP  


24) Physics - Multiple Choice Which of the following is NOT true regarding the TEM mode for an electromagnetic wave in a waveguide set up along the z-axis?  


W) The z-component of the electric field is zero 
X) The z-component of the magnetic field is zero 
Y) The wave can travel through vacuum occupied wave guides 
Z) The wave can travel through non-vacuum occupied wave guides  


ANSWER: Y) The wave can travel through vacuum occupied wave guides  


## BONUS  


24) Physics - Short Answer Consider a discrete thermodynamic system that has three states with distinct energies. Identify all of the following three statements that are true of this system: 1) As temperature goes to infinity, the probability of being in the highest-energy state approaches 1; 2) As temperature goes to zero, the probability of being in the lowest-energy state approaches 1; 3) At some temperature, the most probable state is the medium-energy state.  


ANSWER: 2 only