text[[0, 0, 997, 997]]
# 1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1sub_title[[444, 171, 549, 193]]
## TOSS-UP  

text[[115, 228, 883, 293]]
1) X-Risk - Short Answer What is the term that describes the fast-moving current of hot gas and volcanic matter that is produced as a result of certain explosive eruptions?  

text[[116, 309, 380, 330]]
ANSWER: Pyroclastic flow  

sub_title[[456, 352, 540, 373]]
## BONUS  

text[[115, 388, 883, 452]]
1) X-Risk - Short Answer The End-Permian extinction was particularly deadly to marine organisms because rising temperatures led to what oceanic condition, in which water has little to no oxygen for fish to breathe?  

text[[115, 467, 500, 489]]
ANSWER: Hypoxia (ACCEPT: Anoxia)sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[112, 131, 835, 155]]
2) Math - Short Answer How many edges does a decagonal pyramid have?  

text[[115, 168, 254, 189]]
ANSWER: 20  

sub_title[[456, 211, 540, 232]]
## BONUS  

text[[115, 247, 883, 291]]
2) Math - Short Answer How many two digit values of \(n\) exist such that the 5 numbers \(n / 2\) , \(n / 3\) , \(n / 4\) , \(n / 5\) , and \(n / 6\) are all positive integer values?  

text[[115, 305, 239, 325]]
ANSWER: 1sub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[114, 131, 883, 195]]
3) Chemistry - Short Answer The energy required to eject an electron from a neon atom is E. In terms of E, how much energy is released when an electron is added to neon's monovalent cation?  

text[[115, 211, 244, 231]]
ANSWER: E  

sub_title[[456, 254, 540, 275]]
## BONUS  

text[[114, 290, 883, 375]]
3) Chemistry - Short Answer An aqueous [AY-kwee-is] solution is prepared containing silver (I) [one] and barium (II) [two] cations, as well as fluoride, chloride, iodide, and sulfate anions. A yellow precipitate forms from the solution. What is the chemical identity of the precipitate?  

text[[115, 390, 620, 412]]
ANSWER: Silver iodide (ACCEPT: Silver (I) iodide)sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[113, 131, 881, 174]]
4) Earth and Space - Short Answer During which season is the Intertropical Convergence Zone deflected furthest north?  

text[[113, 189, 754, 210]]
ANSWER: Summer (ACCEPT: Northern summer, southern winter)  

sub_title[[456, 233, 540, 254]]
## BONUS  

text[[113, 269, 883, 312]]
4) Earth and Space - Short Answer What type of wasting occurs in periglacial areas where freeze-thaw cycles cause expansion in the regolith?  

text[[113, 327, 517, 349]]
ANSWER: Solifluction (ACCEPT: Creep)sub_title[[448, 90, 549, 111]]
## TOSS-UP  

text[[113, 131, 882, 175]]
5) Biology - Multiple Choice What angiosperm [AN-jee-oh-sperm] seed structure is analogous to the egg yolk in animals?  

text[[113, 189, 451, 277]]
W) Hypocotyl [hai-puh-KOW-tuhl] 
X) Endosperm 
Y) Cotyledon [caw-tuh-LEE-dun] 
Z) Micropyle [MAI-krow-pile]  

text[[115, 291, 367, 311]]
ANSWER: X) Endosperm  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[115, 369, 884, 412]]
5) Biology - Short Answer The distribution of what class of hormones plays a major role in the response of plants to gravity?  

text[[115, 427, 288, 447]]
ANSWER: Auxinsub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[114, 131, 881, 174]]
6) Physics - Short Answer The impossibility of reducing the temperature of any closed system to absolute zero is a consequence of what law?  

text[[114, 189, 509, 210]]
ANSWER: Third law of thermodynamics  

sub_title[[459, 232, 540, 253]]
## BONUS  

text[[114, 268, 883, 354]]
6) Physics - Short Answer A cord pulls a box of mass 5 kilograms up a frictionless plane inclined at 30 degrees. If the force from the cord has a magnitude of 25 newtons, what is the magnitude of the box's acceleration, in meters per second squared, parallel to the inclined plane?  

text[[115, 370, 257, 390]]
ANSWER: 0.1sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 882, 196]]
7) X-Risk - Short Answer What is the term for the minimum amount of fissile material required to sustain a nuclear chain reaction, such that neutrons produced by the reaction will go on to cause further fission events?  

text[[115, 210, 352, 231]]
ANSWER: Critical mass  

sub_title[[456, 253, 540, 275]]
## BONUS  

text[[115, 290, 882, 354]]
7) X-Risk - Short Answer What is the term that describes the situation where a model may contain more parameters than can be justified by the data, which can then cause it to fail to reliably predict future observations?  

text[[115, 369, 333, 390]]
ANSWER: Overfittingsub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[113, 131, 883, 175]]
8) Math - Short Answer [read carefully] What is the value of \(y\) if \(x\) percent of \(y\) is 6 and \(x\) percent of \(x\) percent of \(y\) is 4?  

text[[115, 189, 241, 209]]
ANSWER: 9  

sub_title[[456, 232, 540, 253]]
## BONUS  

text[[114, 269, 883, 353]]
8) Math - Short Answer An isosceles triangle in the plane has an area of 2, and has one vertex at the point \((1,2)\) [one comma two] and one vertex at the point \((-1,2)\) [negative one comma two]. How many potential points can be the third vertex?  

text[[115, 370, 241, 390]]
ANSWER: 6sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[113, 131, 884, 175]]
9) Chemistry - Multiple Choice Which of the following statements is true about paramagnetism?  

text[[113, 189, 808, 277]]
W) Paramagnetic substances must have an odd number of electrons 
X) Paramagnetic substances are weakly repelled by a magnetic field 
Y) Paramagnetic substances have at least one unpaired electron 
Z) Paramagnetism transitions to ferromagnetism as temperature increases  

text[[113, 290, 823, 312]]
ANSWER: Y) Paramagnetic substances have at least one unpaired electron  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[113, 369, 884, 413]]
9) Chemistry - Short Answer Order the following three compounds by increasing dipole moment: 1) Ammonia; 2) Methanol; 3) Hydrogen bromide.  

text[[115, 427, 288, 448]]
ANSWER: 3, 1, 2sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 883, 175]]
10) Earth and Space - Multiple Choice S-process nuclides are generally formed by the addition of what subatomic particle to smaller nuclides?  

text[[114, 190, 280, 275]]
W) Neutron 
X) Proton 
Y) Electron 
Z) Alpha particle  

text[[115, 290, 343, 311]]
ANSWER: W) Neutron  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[115, 369, 883, 435]]
10) Earth and Space - Short Answer Order the following three gases by increasing abundance in the Martian atmosphere: 1) Nitrogen gas; 2) Carbon dioxide; 3) Argon.  

text[[115, 450, 288, 470]]
ANSWER: 3, 1, 2sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 881, 175]]
11) Biology - Short Answer What tissue type is characterized by a lack of striation, involuntary contraction, and a presence within the digestive system?  

text[[115, 190, 375, 210]]
ANSWER: Smooth muscle  

sub_title[[456, 233, 540, 254]]
## BONUS  

text[[115, 269, 882, 312]]
11) Biology - Short Answer What cellular organelle gives brown fat, a tissue involved in thermogenesis, its distinctive color?  

text[[115, 327, 357, 348]]
ANSWER: Mitochondriasub_title[[448, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 883, 175]]
12) Physics - Multiple Choice A marble balanced on top of a bowling ball is said to be in which of the following states?  

text[[114, 189, 348, 277]]
W) Neutral equilibrium 
X) Stable equilibrium 
Y) Unstable equilibrium 
Z) Turning point  

text[[115, 291, 459, 312]]
ANSWER: Y) Unstable equilibrium  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[115, 369, 883, 435]]
12) Physics - Multiple Choice Allison places a conducting wire loop inside a flat uniform magnetic field. Which of the following changes will not cause the flux through the loop to change?  

text[[114, 449, 756, 536]]
W) Vary the strength of the magnetic field 
X) Translate the loop along the direction of the magnetic field 
Y) Rotate the loop about an axis perpendicular to the magnetic field 
Z) Expand the loop radially  

text[[115, 549, 809, 571]]
ANSWER: X) Translate the loop along the direction of the magnetic fieldsub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 882, 175]]
13) X-Risk - Short Answer Carbon dioxide in seawater contributes to ocean acidification because it reacts with water to form what compound?  

text[[115, 189, 361, 210]]
ANSWER: Carbonic acid  

sub_title[[456, 233, 540, 254]]
## BONUS  

text[[115, 268, 883, 312]]
13) X-Risk - Multiple Choice The weights in each layer of a neural network are most commonly programmed as which mathematical object?  

text[[115, 327, 217, 414]]
W) Matrix X) Set Y) Tree Z) Ring  

text[[115, 428, 329, 449]]
ANSWER: W) Matrixsub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 881, 175]]
14) Math - Short Answer How many ways are there to assign non-negative integers to the values of \(a, b,\) and \(c\) , such that \(a + b + c = 5\) ?  

text[[114, 189, 251, 210]]
ANSWER: 21  

sub_title[[455, 232, 541, 254]]
## BONUS  

text[[114, 268, 881, 312]]
14) Math - Short Answer Identify all of the following three trigonometric functions that cannot have a value of 0: 1) Sine; 2) Tangent; 3) Cosecant.  

text[[114, 327, 288, 348]]
ANSWER: 3 onlysub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 883, 175]]
15) Chemistry - Short Answer In liquid chromatography, what property of the mobile and stationary phases is controlled to separate the solvent components?  

text[[115, 190, 303, 210]]
ANSWER: Polarity  

sub_title[[456, 233, 540, 254]]
## BONUS  

text[[115, 269, 883, 312]]
15) Chemistry - Multiple Choice As the external pressure on a liquid decreases, which of the following changes must occur?  

text[[114, 327, 538, 413]]
W) The liquid's freezing point must increase 
X) The liquid's freezing point must decrease 
Y) The liquid's boiling point must increase 
Z) The liquid's boiling point must decrease  

text[[114, 428, 634, 449]]
ANSWER: Z) The liquid's boiling point must decreasesub_title[[448, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 881, 175]]
16) Earth and Space - Multiple Choice Tropospheric ozone is produced naturally by what phenomenon?  

text[[114, 190, 382, 275]]
W) Decomposition by fungi 
X) Emission via fumaroles 
Y) Lightning 
Z) Auroras  

text[[115, 291, 353, 312]]
ANSWER: Y) Lightning  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[115, 370, 882, 434]]
16) Earth and Space - Multiple Choice The energy released by a magnitude 7 earthquake on the moment magnitude scale is roughly how many times larger than that of a magnitude 3 earthquake?  

text[[114, 448, 296, 533]]
W) 1,000 
X) 10,000 
Y) 100,000 
Z) 1,000,000  

text[[115, 549, 352, 569]]
ANSWER: Z) 1,000,000sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 883, 175]]
17) Biology - Multiple Choice Which of the following families of viruses is responsible for respiratory infections in vertebrates?  

text[[115, 189, 567, 276]]
W) Retroviridae [retro- VIR- ih- dee] 
X) Adenoviridae [ad- en- oh- VIR- ih- dee] 
Y) Herpesviridae [herpes- VIR- ih- dee] 
Z) Polyomaviridae [pah- lee- oh- ma- VIR- ih- dee]  

text[[115, 290, 387, 311]]
ANSWER: X) Adenoviridae  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[115, 369, 883, 434]]
17) Biology - Multiple Choice Sean performs gel electrophoresis on two sequences of DNA: one that is 20 base pairs long and another that is 80 base pairs long. Which of the following most accurately summarizes his results?  

text[[115, 448, 883, 555]]
W) The 80 base-pair sequence is downstream of the 20 base-pair sequence 
X) The 20 base-pair sequence is downstream of the 80 base-pair sequence 
Y) The 20 base-pair sequence is located at the same distance as the 80-base pair sequence 
Z) It depends on the concentration of agarose  

text[[115, 570, 882, 612]]
ANSWER: X) The 20 base-pair sequence is downstream of the 80 base-pair sequencesub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 883, 196]]
18) Physics - Multiple Choice Sean jumps off of a very tall building. Which of the following best describes the graph of his position versus time if there is air resistance directly proportional to his velocity?  

text[[114, 211, 264, 297]]
W) Quadratic 
X) Logarithmic 
Y) Sinusoidal 
Z) Exponential  

text[[115, 312, 370, 333]]
ANSWER: Z) Exponential  

sub_title[[456, 354, 540, 375]]
## BONUS  

text[[114, 390, 883, 455]]
18) Physics - Multiple Choice A block is pulled over a horizontal plane with a force \(F\) that makes an angle of 15 degrees with the horizontal. Which of the following statements is NOT true?  

text[[112, 468, 884, 641]]
W) The direction of the force pulling the block is opposite to the direction of the force of friction 
X) The direction of the force of friction is perpendicular to the direction of the normal force 
Y) The direction of the force of friction is perpendicular to the direction of the gravitational force 
Z) The direction of the normal force is opposite to the direction of the gravitational force  

text[[114, 656, 882, 700]]
ANSWER: W) The direction of the force pulling the block is opposite to the direction of the force of frictionsub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[115, 131, 883, 196]]
19) X-Risk - Short Answer The Carrington event, which caused auroras as far south as the Caribbean, was caused by what type of astronomical phenomenon occurring on the Sun?  

text[[115, 210, 772, 232]]
ANSWER: Coronal mass ejection (ACCEPT: Solar flare, solar storm)  

sub_title[[456, 253, 540, 275]]
## BONUS  

text[[115, 290, 883, 376]]
19) X-Risk - Short Answer Space debris orbits Earth at about 7 kilometers per second, while a bullet from a handgun travels at around 350 meters per second. If a bullet has a mass of 8 grams, what would be the mass in grams of a piece of space debris with the same kinetic energy as the bullet?  

text[[115, 390, 434, 411]]
ANSWER: 0.02 (ACCEPT: 1/50)sub_title[[447, 90, 549, 110]]
## TOSS-UP  

text[[114, 131, 882, 194]]
20) Math - Short Answer [read carefully] What is the sum of the digits of \(N\) , given that \(N\) is the sum of the 6 numbers \(111, 111 + 11, 111 + 1, 111 + 111 + 11 + 1\) ?  

text[[115, 211, 251, 231]]
ANSWER: 21  

sub_title[[456, 253, 540, 275]]
## BONUS  

text[[115, 290, 882, 334]]
20) Math - Multiple Choice Which of the following describes the point \((-2, 8)\) [negative two comma eight] in the function \(y = x^{3} + 6x^{2} - 2x - 12\) ?  

text[[114, 350, 308, 435]]
W) Local maximum 
X) Local minimum 
Y) Inflection point 
Z) Saddle point  

text[[115, 450, 404, 471]]
ANSWER: Y) Inflection pointsub_title[[448, 90, 549, 111]]
## TOSS-UP  

text[[113, 131, 884, 176]]
21) Chemistry - Multiple Choice Which of the following chemical species has the greatest electronegativity?  

text[[113, 191, 420, 276]]
W) Vanadium atomX) Vanadium (III) [three] cationY) Vanadium (IV) [four] cationZ) Vanadium (V) [five] cation  

text[[114, 291, 454, 312]]
ANSWER: Z) Vanadium (V) cation  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[113, 369, 884, 413]]
21) Chemistry - Multiple Choice Which of the following isotopes contains a doubly-magic nucleus?  

text[[113, 428, 297, 513]]
W) Magnesium-26X) Argon-40Y) Calcium-42Z) Nickel-48  

text[[114, 528, 351, 549]]
ANSWER: Z) Nickel-48sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 881, 175]]
22) Earth and Space - Multiple Choice Which of the following would conclusively identify an iron meteorite?  

text[[114, 190, 377, 275]]
W) Evidence of weathering 
X) Magnetism 
Y) A fusion crust 
Z) Heft  

text[[115, 291, 393, 311]]
ANSWER: Y) A fusion crust  

sub_title[[456, 333, 540, 354]]
## BONUS  

text[[114, 370, 882, 435]]
22) Earth and Space - Short Answer Identify all of the following three phenomena that are associated with an increase in rotational speed of a pulsar: 1) Glitch; 2) Accretion; 3) Emission of pulsar wind.  

text[[115, 450, 299, 470]]
ANSWER: 1 and 2sub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 883, 175]]
23) Biology - Short Answer What is the term for a species interaction where one species benefits and the other is neither harmed nor benefitted?  

text[[115, 189, 376, 210]]
ANSWER: Commensalism  

sub_title[[456, 232, 540, 253]]
## BONUS  

text[[114, 268, 884, 312]]
23) Biology - Multiple Choice Which of the following conditions would lead to resource partitioning between species?  

text[[114, 327, 590, 415]]
W) Allopatric populations with different niches  X) Allopatric populations with overlapping niches  Y) Sympatric populations with different niches  Z) Sympatric populations with overlapping niches  

text[[114, 428, 700, 450]]
ANSWER: Z) Sympatric populations with overlapping nichessub_title[[447, 90, 549, 111]]
## TOSS-UP  

text[[114, 131, 883, 175]]
24) Physics - Short Answer What type of damped harmonic oscillator returns to equilibrium in the shortest amount of time?  

text[[115, 189, 399, 210]]
ANSWER: Critically damped  

sub_title[[456, 232, 540, 253]]
## BONUS  

text[[114, 268, 883, 331]]
24) Physics - Short Answer In terms of \(M\) and \(L\) , what is the moment of inertia of a rod with mass \(M\) and length \(L\) rotating about an axis that is a distance \(L / 4\) from its center?  

text[[115, 344, 275, 371]]
ANSWER: \(\frac{7ML^2}{48}\)