
## TOSS-UP  


1) Biology – Multiple Choice Which of the following is not a part of the endomembrane system?  


W) Vacuole  X) Lysosome  Y) Rough endoplasmic reticulum  Z) Peroxisome  


ANSWER: Z) PEROXISOME  


## BONUS  


1) Biology – Short Answer What kind of microtubule arrangement characterizes mature basal bodies?  


ANSWER: 9 PLUS 0  


## TOSS-UP  


2) Physics – Multiple Choice A car has velocity 5 m/s. A truck is driving in the same direction as the car at 10 m/s. To the car driver, who perceives herself as stationary, how fast, in meters per second is the truck moving?  


W) 5  X) 10  Y) 15  Z) Cannot be determined  


ANSWER: W) 5  


## BONUS  


2) Physics – Short Answer A car drives north at 6 m/s, and a truck drives west at 8 m/s. After how many seconds will they be 50 meters apart?  


ANSWER: 5