sub_title[[455, 140, 541, 159]]
## TOSS-UP  

text[[115, 174, 864, 228]]
1) Chemistry – Multiple Choice Brandon is performing an iodometric (read: eye-oh-doh-metric) titration. Unfortunately, he has no clue what he is doing. Which of the following would be the first step Brandon needs to take?  

text[[115, 244, 426, 315]]
W) Standardization of iodine  X) Standardization of iodide  Y) Addition of analyte to excess iodine  Z) Addition of analyte to excess iodide  

text[[115, 330, 639, 350]]
ANSWER: Z) ADDITION OF ANALYTE TO EXCESS IODIDE  

sub_title[[463, 366, 534, 384]]
## BONUS  

text[[115, 400, 874, 454]]
1) Chemistry – Multiple Choice Excited by his new found iodometry skills, Brandon seeks to titrate every compound he can find. Which of the following could Brandon not titrate with iodometric titration?  

text[[115, 470, 256, 541]]
W) Manganese II  X) Lead II  Y) Copper III  Z) Iron III  

text[[115, 558, 308, 576]]
ANSWER: X) LEAD II  

sub_title[[455, 627, 541, 645]]
## TOSS-UP  

text[[115, 662, 870, 715]]
2) Physics – Short Answer A sphere of mass 1 kg and radius 2 meters has a torque applied to it such that it rotates around a line tangent to the sphere. If the angular acceleration produced by this torque is 5 radians/s, what was the magnitude of the torque applied, in Newton-meters?  

text[[115, 731, 230, 749]]
ANSWER: 28  

sub_title[[463, 767, 534, 785]]
## BONUS  

text[[115, 802, 875, 855]]
2) Physics – Short Answer How far, in centimeters, must an object be placed away from a concave lens with focal length 33 cm in order to form a virtual image 30 cm from the lens on the same side as the object?  

text[[115, 871, 240, 889]]
ANSWER: 330sub_title[[455, 88, 541, 107]]
## TOSS-UP  

text[[113, 123, 852, 160]]
3) Math – Multiple Choice If G is a finite group with order 210, which of these numbers is NOT a possible order of a subgroup of G?  

text[[114, 176, 157, 247]]
W) 4 
X) 5 
Y) 6 
Z) 7  

text[[115, 264, 251, 282]]
ANSWER: W) 4  

sub_title[[462, 298, 534, 317]]
## BONUS  

text[[114, 334, 879, 392]]
3) Math – Short Answer Given \(a_0 = 69\) and \(a_n\) satisfies the recurrence \(a_{n+1} = \sqrt{-9 + 6}\) (READ: a sub n plus 1 equals the square root of open parentheses negative 9 plus 6 times a sub n close parentheses), what is the limit as n approaches infinity of \(a_n\) ?  

text[[115, 407, 220, 425]]
ANSWER: 3  

sub_title[[455, 477, 541, 496]]
## TOSS-UP  

text[[114, 511, 859, 548]]
4) Earth and Space – Multiple Choice Which of the following terms best describes La Brea Tar Pits as a lagerstate?  

text[[114, 564, 271, 633]]
W) Concentration 
X) Preservation 
Y) Conglomeration 
Z) Conservation  

text[[115, 650, 387, 669]]
ANSWER: Z) CONSERVATION  

sub_title[[462, 686, 534, 704]]
## BONUS  

text[[114, 720, 861, 757]]
4) Earth and Space – Multiple Choice Which of the following dates best describes when the Burgess Shale formed?  

text[[114, 773, 318, 844]]
W) 500 million years ago 
X) 150 million years ago 
Y) 2 million years ago 
Z) 40,000 years ago  

text[[115, 860, 474, 878]]
ANSWER: W) 500 MILLION YEARS AGOsub_title[[456, 89, 541, 107]]
## TOSS-UP  

text[[115, 123, 880, 178]]
5) Energy – Multiple Choice Researchers at Lawrence Berkeley National Lab are studying the use of metals in catalyzing chemical reactions. What product is formed when reducing nitrobenzene with a platinum catalyst in the presence of one equivalent of hydrogen gas?  

text[[115, 194, 287, 264]]
W) Nitrocyclohexane 
X) Aniline 
Y) Nitrosobenzene 
Z) 1-nitrohexane  

text[[115, 281, 411, 299]]
ANSWER: Y) NITROSOBENZENE  

sub_title[[462, 315, 534, 333]]
## BONUS  

text[[115, 350, 880, 421]]
5) Energy – Short Answer Researchers at Oak Ridge National Lab are studying the effectiveness of catalytic converters. By name or number, identify all of the following 3 actions that a catalytic converter would perform: 1) Oxidizes ethylene; 2) Oxidizes Carbon Monoxide; 3) Reduces nitrogen dioxide.  

text[[115, 437, 248, 455]]
ANSWER: ALL  

sub_title[[456, 505, 540, 523]]
## TOSS-UP  

text[[115, 540, 872, 594]]
6) Biology – Multiple Choice Humans exhibit many morphological differences based on sex, but these differences are not as pronounced in the skeleton. However, some do exist; which of the following features of the human skeleton do NOT highlight sexual dimorphism?  

text[[115, 610, 191, 680]]
W) Skull 
X) Pelvis 
Y) Teeth 
Z) Wrists  

text[[115, 697, 305, 715]]
ANSWER: Z) WRISTS  

sub_title[[462, 732, 534, 750]]
## BONUS  

text[[115, 767, 839, 820]]
6) Biology – Short Answer By name or number, order the following 3 organs in terms of increasing speeds at which Interstitial cells of Cajal act in them: 1) Colon; 2) Ileum; 3) Duodenum.  

text[[115, 837, 260, 854]]
ANSWER: 1, 2, 3sub_title[[455, 89, 541, 107]]
## TOSS-UP  

text[[114, 123, 845, 159]]
7) Chemistry – Short Answer Zinc metal is added to a concentrated solution of nitric acid. What gas is evolved?  

text[[115, 175, 539, 194]]
ANSWER: NO2 (ACCEPT: NITROGEN DIOXIDE)  

sub_title[[463, 210, 533, 228]]
## BONUS  

text[[115, 245, 869, 299]]
7) Chemistry – Multiple Choice The Ostwald process, used to produce nitric acid, involves a series of steps to gradually oxidize ammonia through many intermediates. Which of the following is not one of these intermediates?  

text[[115, 315, 285, 385]]
W) N2 
X) NO 
Y) NO2 
Z) None of the above  

text[[115, 402, 265, 420]]
ANSWER: W) N2  

sub_title[[455, 473, 541, 490]]
## TOSS-UP  

text[[115, 507, 874, 543]]
8) Physics – Multiple Choice Which of these patterns regarding the color of light did Thomas Young observe when shining white light through a double slit?  

text[[115, 559, 875, 594]]
W) The central fringe is white, while the outer fringes contain a spectrum of colors, increasing in wavelength while getting farther away  

text[[115, 594, 564, 611]]
X) Both the central fringe and the outer fringes are white  

text[[115, 612, 864, 647]]
Y) The central fringe is white, while the outer fringes contain a spectrum of colors, decreasing in wavelength while getting farther away  

text[[115, 647, 789, 665]]
Z) The nature of the color of the fringes depended on the distance in between the slits  

text[[115, 681, 812, 733]]
ANSWER: W) THE CENTRAL FRINGE IS WHITE, WHILE THE OUTER FRINGES CONTAIN A SPECTRUM OF COLORS, INCREASING IN WAVELENGTH WHILE GETTING FARTHER AWAY  

sub_title[[463, 750, 533, 768]]
## BONUS  

text[[115, 785, 872, 839]]
8) Physics – Short Answer Roger Penrose created the Andromeda paradox as a thought experiment illustrating the problems with defining what concept, referring to whether or not two spatially separated events occur at the same time?  

text[[115, 855, 355, 873]]
ANSWER: SIMULTANETTYsub_title[[455, 89, 541, 107]]
## TOSS-UP  

text[[113, 123, 860, 159]]
9) Math – Multiple Choice If two equilateral triangles, both with area 1, are inscribed in the same circle, what is the minimum area of their intersection?  

text[[114, 177, 175, 247]]
W) 1/4 
X) 1/3 
Y) 1/2 
Z) 2/3  

text[[115, 264, 260, 282]]
ANSWER: Z) 2/3  

sub_title[[462, 298, 534, 316]]
## BONUS  

text[[114, 332, 857, 385]]
9) Math – Short Answer If Brandon wants to choose a real number between 0 and 1, with a probability density of \(2 + \ln (x)\) of choosing \(x\) , what is the probability that he chooses a number less than \(\frac{1}{2}\) ?  

text[[115, 400, 829, 437]]
ANSWER: \(\frac{1}{2} +\ln (\frac{1}{2}) / 2\) (ACCEPT EQUIVALENTS, SUCH AS \(\frac{1}{2} -\ln (2) / 2\) ; CHECK WITH CALCULATOR IF NECESSARY BUT ALL ANSWERS MUST BE SIMPLIFIED)  

sub_title[[455, 490, 541, 508]]
## TOSS-UP  

text[[115, 523, 855, 560]]
10) Earth and Space – Short Answer Hubble’s law predicts the proportionality of what two quantities?  

text[[115, 576, 595, 595]]
ANSWER: DISTANCE AND RECESSIONAL VELOCITY  

sub_title[[462, 611, 534, 630]]
## BONUS  

text[[115, 646, 874, 700]]
10) Earth and Space – Short Answer A gas cloud emits light at a frequency of \(1.07 \times 10^{10} \text{Hz}\) . If the light is observed to have a frequency of \(1.00 \times 10^{10} \text{Hz}\) from earth, how far away is the gas cloud, in megaparsecs to 1 significant figure?  

text[[115, 716, 241, 733]]
ANSWER: 300sub_title[[456, 88, 541, 107]]
## TOSS-UP  

text[[115, 123, 837, 178]]
11) Energy – Short Answer Researchers at Argonne National Laboratory are researching continental drift and plate tectonics. What hypothesis was the first key scientific test of the seafloor spreading theory?  

text[[115, 193, 836, 229]]
ANSWER: VINE- MATTHEWS- MORLEY HYPOTHESIS (ACCEPT: MORLEY- VINE- MATTHEWS HYPOTHESIS)  

sub_title[[463, 245, 533, 264]]
## BONUS  

text[[115, 280, 864, 334]]
11) Energy – Multiple Choice Researchers at Lawrence Livermore National Laboratory are studying the composition of pegmatite. Which of the following minerals cannot be found in the dark portions of pegmatite?  

text[[115, 350, 235, 420]]
W) Biotite 
X) Tourmaline 
Y) Pyroxene 
Z) Orthoclase  

text[[115, 436, 364, 455]]
ANSWER: Z) ORTHOCLASE  

sub_title[[456, 507, 541, 525]]
## TOSS-UP  

text[[115, 541, 881, 595]]
12) Biology – Short Answer Members of what phylum of protozoans are known for their tests and pseudopodia that appear granular under microscopes and are most critical in searching for oil deposits?  

text[[115, 610, 357, 628]]
ANSWER: FORAMINIFERA  

sub_title[[463, 645, 533, 664]]
## BONUS  

text[[115, 680, 870, 716]]
12) Biology – Multiple Choice Which of the following is typically not expected of a member of class articulata of phylum brachiopoda?  

text[[115, 732, 390, 803]]
W) Contains a lophophore 
X) Leads an epifaunal mode of life 
Y) Is hermaphroditic 
Z) Has tooth-and-groove hinges  

text[[115, 820, 434, 838]]
ANSWER: Y) IS HERMAPHRODITICsub_title[[456, 89, 541, 107]]
## TOSS-UP  

text[[115, 123, 875, 177]]
13) Chemistry - Short Answer A chemical compound A, with chemical formula C10H12, absorbs 3 equivalents of H2 upon catalytic hydrogenation over palladium. How many rings does A have?  

text[[115, 194, 220, 211]]
ANSWER: 2  

sub_title[[462, 228, 534, 247]]
## BONUS  

text[[115, 263, 883, 300]]
13) Chemistry - Short Answer Compound A from the previous question reacts with potassium permanganate to form a single organic product. What is the chemical formula of this product?  

text[[115, 315, 281, 333]]
ANSWER: C5H4O5  

sub_title[[456, 384, 541, 403]]
## TOSS-UP  

text[[115, 418, 880, 525]]
14) Physics - Short Answer By name or number, identify all of the following 4 quantities can an ammeter and a voltmeter connected in series correctly measure: 1) Current through a circuit element inserted in series with the ammeter and voltmeter; 2) Current through a circuit element inserted in parallel with the ammeter and voltmeter; 3) Voltage through a circuit element inserted in series with the ammeter and voltmeter; 4) Voltage through a circuit element inserted in parallel with the ammeter and voltmeter.  

text[[115, 541, 279, 559]]
ANSWER: 4 ONLY  

sub_title[[462, 560, 534, 577]]
## BONUS  

text[[115, 593, 877, 648]]
14) Physics - Short Answer The current moving through a wire is given by the equation \(\mathrm{I(t) =}\) \(4\mathrm{e}^{-2\mathrm{t}}\) . How much charge, in Coulombs, passes through a cross section of the wire between time t \(= 0\) and \(\mathrm{t} =\) infinity?  

text[[115, 664, 220, 681]]
ANSWER: 2sub_title[[455, 89, 541, 107]]
## TOSS-UP  

text[[115, 123, 840, 159]]
15) Math - Short Answer What is the derivative with respect to x of the integral from the square root of x to \(x^{\wedge}2\) of t dt?  

text[[115, 175, 280, 194]]
ANSWER: \(2x^{3} - 1 / 2\)  

sub_title[[463, 211, 534, 229]]
## BONUS  

text[[115, 245, 868, 281]]
15) Math - Short Answer How many ordered tuples of positive integers are there that sum to 10?  

text[[115, 298, 240, 316]]
ANSWER: 512  

sub_title[[455, 368, 541, 386]]
## TOSS-UP  

text[[115, 402, 868, 455]]
16) Earth and Space - Short Answer As air in the Hadley Cells moves poleward, it cools and gains a strong eastward proponent. This can be attributed to the Coriolis effect and the conservation of what?  

text[[115, 471, 431, 490]]
ANSWER: ANGULAR MOMENTUM  

sub_title[[463, 507, 534, 525]]
## BONUS  

text[[115, 542, 853, 578]]
16) Earth and Space - Multiple Choice Which of the following is not one of the five major gyres?  

text[[115, 594, 268, 664]]
W) Majid Gyre 
X) Columbus Gyre 
Y) Heyerdahl Gyre 
Z) Kuroshio Gyre  

text[[115, 681, 394, 699]]
ANSWER: Z) KUROSHIO GYREsub_title[[456, 88, 541, 107]]
## TOSS-UP  

text[[115, 123, 864, 178]]
17) Energy - Short Answer Researchers at Oak Ridge National Lab are studying regression-based machine learning. What phenomenon describes machine learning models that see a significant drop in performance from training data to test data?  

text[[115, 194, 341, 211]]
ANSWER: OVERFITTING  

sub_title[[462, 228, 534, 247]]
## BONUS  

text[[115, 263, 877, 317]]
17) Energy - Short Answer Researchers at Oak Ridge National Lab are studying ways to increase the efficiency of training neural networks. Gradient descent and the lowering of the cost function are used in what process used in training neural networks?  

text[[115, 333, 404, 351]]
ANSWER: BACKPROPAGATION  

sub_title[[456, 402, 541, 420]]
## TOSS-UP  

text[[115, 437, 820, 473]]
18) Biology - Short Answer What chromosome can the mutation causing Prader-Willi Syndrome be located on?  

text[[115, 489, 230, 507]]
ANSWER: 15  

sub_title[[462, 525, 534, 543]]
## BONUS  

text[[115, 560, 874, 596]]
18) Biology - Short Answer By name or number, order the following five phases of Prophase I from first to last: 1) Diplotene; 2) Leptotene; 3) Zygotene; 4) Diakinesis; 5) Pachytene.  

text[[115, 612, 300, 630]]
ANSWER: 2, 3, 5, 1, 4sub_title[[456, 88, 541, 107]]
## TOSS-UP  

text[[115, 123, 866, 179]]
19) Chemistry – Multiple Choice A 1 kilogram particle is constrained in a 1D box of length 10 meters. Which of the following is closest, logarithmically speaking, to the zero-point energy of this system, in Joules?  

text[[115, 193, 186, 264]]
W) \(10^{-60}\) X) \(10^{-65}\) Y) \(10^{-70}\) Z) \(10^{-75}\)  

text[[115, 281, 293, 299]]
ANSWER: Y) \(10^{\wedge} - 70\)  

sub_title[[462, 315, 534, 333]]
## BONUS  

text[[115, 350, 864, 404]]
19) Chemistry – Short Answer A 1 kilogram particle is constrained in a 1D box of length 10 meters. What is the probability density of the lowest energy wavefunction at the center of this system?  

text[[115, 420, 235, 437]]
ANSWER: 0.2  

sub_title[[456, 490, 541, 508]]
## TOSS-UP  

text[[115, 524, 878, 578]]
20) Physics – Short Answer Water passing through a pipe is going at \(10 \mathrm{m / s}\) when the pipe has diameter \(2 \mathrm{cm}\) . If the pipe expands to a diameter of \(5 \mathrm{cm}\) , what is the velocity of the water, in meters/second, in that part of the pipe?  

text[[115, 594, 235, 611]]
ANSWER: 1.6  

sub_title[[462, 611, 534, 630]]
## BONUS  

text[[115, 647, 872, 700]]
20) Physics – Short Answer Randy the Rapid Runner runs past a log. When Randy is not moving, he sees the log as being 2.5 meters long. When Randy runs past the log at four-fifths of the speed of light, how long, in meters, does he observe the log to be?  

text[[115, 716, 235, 733]]
ANSWER: 1.5sub_title[[455, 88, 541, 107]]
## TOSS-UP  

text[[113, 123, 777, 142]]
21) Math - Short Answer What is the sum from \(\mathrm{i} = 0\) to 11 of \((-1)^{i*}\) (11 choose i)  

text[[115, 158, 221, 175]]
ANSWER: 0  

sub_title[[462, 176, 534, 195]]
## BONUS  

text[[115, 211, 809, 247]]
21) Math - Short Answer What is the largest finite number of intersection points of 2 quadrilaterals?  

text[[115, 263, 231, 281]]
ANSWER: 16  

sub_title[[455, 333, 541, 351]]
## TOSS-UP  

text[[115, 367, 868, 404]]
22) Earth and Space - Short Answer A main-sequence star with mass M has luminosity L. If M is quadrupled, what is the new luminosity in terms of L?  

text[[115, 419, 252, 437]]
ANSWER: 128L  

sub_title[[462, 455, 534, 473]]
## BONUS  

text[[115, 489, 867, 526]]
22) Earth and Space - Short Answer A main-sequence star with mass M has lifespan T. If M is quadrupled, what is the new lifespan in terms of T to one significant figure?  

text[[115, 542, 257, 560]]
ANSWER: 0.03Tsub_title[[456, 88, 541, 106]]
## TOSS-UP  

text[[114, 123, 832, 160]]
23) Biology – Short Answer What enzyme catalyses the 9th step of glycolysis, where 2- phosphoglycerate is dehydrated to form phosphoenolpyruvate?  

text[[115, 176, 300, 194]]
ANSWER: ENOLASE  

sub_title[[463, 211, 534, 230]]
## BONUS  

text[[115, 246, 862, 300]]
23) Biology – Short Answer By name or number, identify all of the following 3 substances that are found in the inner mitochondrial membrane: 1) Cardiolipin; 2) Monoamine oxidase; 3) Oxysomes.  

text[[115, 315, 282, 333]]
ANSWER: 1 AND 3