sub_title[[456, 139, 541, 158]]
## TOSS-UP  

text[[115, 174, 866, 211]]
1) Biology – Short Answer What phylum of deuterostomes is generally considered the sister phylum of echinoderms and contains acorn worms?  

text[[116, 226, 370, 245]]
ANSWER: HEMICHORDATA  

sub_title[[463, 262, 533, 280]]
## BONUS  

text[[115, 296, 867, 333]]
1) Biology – Multiple Choice A sea cucumber can most commonly be classified as which of the following kinds of hermaphrodites?  

text[[115, 349, 507, 420]]
W) Sequential hermaphrodites  
X) Simultaneous hermaphrodites  
Y) Bidirectional sex changers  
Z) Sea cucumbers are not usually hermaphrodites  

text[[115, 434, 766, 454]]
ANSWER: Z) SEA CUCUMBERS ARE NOT USUALLY HERMAPHRODITES  

sub_title[[456, 505, 540, 524]]
## TOSS-UP  

text[[115, 540, 870, 576]]
2) Chemistry – Multiple Choice Which of the following solvents would be the best for use in thin-layer chromatography of benzoic acid?  

text[[115, 593, 295, 664]]
W) Acetone  
X) Ethanol  
Y) Hexane  
Z) Methylene chloride  

text[[115, 680, 328, 699]]
ANSWER: X) ETHANOL  

sub_title[[463, 698, 533, 715]]
## BONUS  

text[[115, 732, 870, 769]]
2) Chemistry – Short Answer By name or number, order the following four stationary phases in increasing order of adsorbance in thin-layer chromatography:  

text[[115, 784, 206, 854]]
1) alumina  
2) charcoal  
3) florisil  
4) silica  

text[[115, 870, 762, 907]]
ANSWER: SILICA, FLORISIL, CHARCOAL, ALUMINA (ACCEPT: 4, 3, 2, 1) TOSS-UPtext[[115, 106, 872, 161]]
3) Physics – Short Answer A circuit has an infinite number of capacitors in series. If the capacitance of each capacitor is twice the capacitance of the previous, and the first capacitor has capacitance C, what is the equivalent capacitance in the circuit in terms of C?  

text[[115, 177, 240, 195]]
ANSWER: C/2  

sub_title[[463, 211, 533, 230]]
## BONUS  

text[[115, 246, 866, 300]]
3) Physics – Short Answer A series RLC circuit has a Q-factor of 5. Using the same resistor, inductor, and capacitor, what would the Q-factor be of a parallel RLC circuit if the resistor has resistance 5 ohms?  

text[[115, 316, 219, 334]]
ANSWER: 1  

sub_title[[456, 385, 540, 403]]
## TOSS-UP  

text[[113, 420, 848, 440]]
4) Math – Multiple Choice Which of the following statements is true about infinite series?  

text[[115, 456, 863, 527]]
W) Infinite series must converge if the limit of the sequence approaches zero at infinity 
X) If the ratio of consecutive terms approaches 1 at infinity, the sequence diverges 
Y) If the difference between consecutive terms does not approach zero, the series must diverge 
Z) If a series is divergent, there exists an infinite subsequence that is convergent  

text[[115, 542, 833, 577]]
ANSWER: Y) IF THE DIFFERENCE BETWEEN CONSECUTIVE TERMS DOES NOT APPROACH ZERO, THE SERIES MUST DIVERGE  

sub_title[[463, 594, 533, 612]]
## BONUS  

text[[115, 629, 728, 648]]
4) Math – Short Answer Evaluate the sum from \(\mathrm{i} = 1\) to 35 of \(1 / (\square + \square)\)  

text[[115, 664, 220, 682]]
ANSWER: 5sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[112, 124, 814, 143]]
5) Earth and Space – Multiple Choice How would lava with \(65\%\) silica be classified?  

text[[114, 159, 223, 230]]
W) Andesitic 
X) Felsic 
Y) Mafic 
Z) Ultrafelsic  

text[[115, 246, 301, 264]]
ANSWER: X) FELSIC  

sub_title[[463, 280, 533, 299]]
## BONUS  

text[[115, 315, 876, 369]]
5) Earth and Space – Multiple Choice In a volcanic eruption, there was one big explosion and then pyroclastic flows down the side of the volcano. Which of the following most accurately classifies the eruption?  

text[[115, 385, 223, 455]]
W) Hawaiian 
X) Peléan 
Y) Plinian 
Z) Vulcanian  

text[[115, 471, 311, 490]]
ANSWER: X) PELÉAN  

sub_title[[456, 542, 540, 560]]
## TOSS-UP  

text[[115, 577, 803, 613]]
6) Energy – Short Answer Researchers at the University of Chicago are studying the evolutionary biology of plants. During which period did angiosperms evolve?  

text[[115, 629, 339, 647]]
ANSWER: CRETACEOUS  

sub_title[[463, 664, 533, 682]]
## BONUS  

text[[115, 698, 880, 735]]
6) Energy – Multiple Choice Researchers at Argonne National Lab are studying fossilized plants and plant resins. Which of the following comparisons between copal and amber is correct?  

text[[115, 750, 880, 786]]
W) Amber has a hardness of around 2.5 on the Mohs scale while copal only has a hardness of 1.5 X) Copal formed early in geologic time than amber  

text[[115, 786, 863, 838]]
Y) Amber melts faster than copal and gives off a pine-like scent when doing so 
Z) Copal floats in saltwater unlike Amber, which sinks, especially if the solution is mixed with some plastic  

text[[115, 854, 835, 890]]
ANSWER: W) AMBER HAS A HARDNESS OF AROUND 2.5 ON THE MOHS SCALE WHILE COPAL ONLY HAS A HARDNESS OF 1.5sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 124, 800, 160]]
7) Biology – Multiple Choice Which of the following does adenine most commonly deaminate into?  

text[[115, 177, 255, 247]]
W) Uracil 
X) Xanthine 
Y) Hypoxanthine 
Z) Nothing  

text[[116, 263, 392, 281]]
ANSWER: Y) HYPOXANTHINE  

sub_title[[463, 299, 533, 316]]
## BONUS  

text[[115, 333, 835, 369]]
7) Biology – Short Answer What term describes the structural motif that arises from two strands of DNA being held apart by a strand of RNA?  

text[[116, 385, 281, 403]]
ANSWER: R-LOOP  

sub_title[[456, 456, 540, 473]]
## TOSS-UP  

text[[115, 490, 870, 560]]
8) Chemistry – Multiple Choice In IR spectroscopy, free carboxylic acids should hypothetically absorb at around 1760 inverse centimeters. However, most commonly encountered samples of carboxylic acid absorb closer to 1710 inverse centimeters. Which of the following best explains this phenomenon?  

text[[115, 577, 738, 648]]
W) Most carboxylic acids are part of conjugated pi systems 
X) Most carboxylic acids are part of aromatic pi systems 
Y) Most carboxylic acids experience significant hydrogen bonding 
Z) Most carboxylic acids experience significant interactions with their solvents  

text[[115, 664, 856, 699]]
ANSWER: Y) MOST CARBOXYLIC ACIDS EXPERIENCE SIGNIFICANT HYDROGEN BONDING  

sub_title[[463, 717, 533, 734]]
## BONUS  

text[[115, 751, 870, 804]]
8) Chemistry – Short Answer One common method of creating proteins from amino acids in the lab is through treatment with dicyclohexylcarbodiimide, or DCC. Along with peptide chains and water, what product is formed when glycine is reacted with DCC?  

text[[116, 821, 417, 839]]
ANSWER: DICYCLOHEXYLUREAsub_title[[456, 90, 540, 107]]
## TOSS-UP  

text[[113, 124, 830, 160]]
9) Physics – Multiple Choice A pendulum undergoes overdamped harmonic oscillation. Which of the following could describe the displacement graph with respect to time?  

text[[115, 177, 243, 247]]
W) Exponential 
X) Cycloid 
Y) Hyperbolic 
Z) Sinusoidal  

text[[116, 264, 377, 282]]
ANSWER: W) EXPONENTIAL  

sub_title[[463, 299, 533, 317]]
## BONUS  

text[[115, 333, 865, 370]]
9) Physics – Multiple Choice Brandon wants to move a heavy mass. Which of the following would decrease the amount of force he needs to exert the most?  

text[[115, 385, 463, 456]]
W) A fixed pulley pulling with 2 ropes 
X) A fixed pulley pulling with 4 ropes 
Y) A compound pulley pulling with 2 ropes 
Z) A third class lever  

text[[115, 472, 673, 491]]
ANSWER: Y) A COMPOUND PULLEY PULLING WITH 2 ROPES  

sub_title[[456, 543, 540, 560]]
## TOSS-UP  

text[[115, 577, 875, 631]]
10) Math – Short Answer By name or number, identify all of the following 3 statements that are true about the taxicab distance: 1) The taxicab distance is always greater than the Euclidean distance; 2) The taxicab distance is always an integer; 3) The taxicab distance is always positive.  

text[[115, 647, 265, 665]]
ANSWER: NONE  

sub_title[[463, 682, 533, 700]]
## BONUS  

text[[115, 716, 867, 769]]
10) Math – Short Answer A taxicab starts at the origin and moves with equal probability one unit to the left, right, up, or down. What is its expected taxicab distance from the origin after 2 moves?  

text[[115, 787, 236, 804]]
ANSWER: 3/2sub_title[[456, 90, 540, 107]]
## TOSS-UP  

text[[115, 123, 842, 161]]
11) Earth and Space – Multiple Choice Which of the following is closest to the minimum mass required to undergo a Type II supernova?  

text[[115, 177, 262, 247]]
W) 2 solar masses  X) 4 solar masses  Y) 6 solar masses  Z) 8 solar masses  

text[[115, 263, 395, 282]]
ANSWER: Z) 8 SOLAR MASSES  

sub_title[[463, 299, 533, 317]]
## BONUS  

text[[115, 333, 805, 370]]
11) Earth and Space – Multiple Choice The Cygnus Loop is what type of supernova remnant?  

text[[115, 386, 295, 456]]
W) Shell-like  X) Composite  Y) Mixed morphology  Z) Thermal composite  

text[[115, 473, 353, 491]]
ANSWER: W) SHELL-LIKE  

sub_title[[456, 542, 540, 560]]
## TOSS-UP  

text[[115, 576, 822, 613]]
12) Biology – Multiple Choice Which of the following terms best describes strawberry runners?  

text[[115, 614, 220, 682]]
W) Stolons  X) Corms  Y) Rhizomes  Z) Tubers  

text[[115, 700, 229, 717]]
ANSWER: W  

sub_title[[463, 734, 533, 752]]
## BONUS  

text[[115, 768, 859, 822]]
12) Biology – Short Answer By name or number, order the following 3 stele types found in vascular plants based on increasing leaf gap abundance: 1) Protostele; 2) Eustele; 3) Siphonostele.  

text[[115, 839, 259, 856]]
ANSWER: 1, 2, 3sub_title[[456, 90, 540, 107]]
## TOSS-UP  

text[[115, 124, 878, 160]]
13) Energy – Short Answer Researchers at Brookhaven National Lab are studying Lagrangian mechanics. Lagrangian mechanics are fundamentally based on what principle?  

text[[115, 176, 485, 195]]
ANSWER: PRINCIPLE OF LEAST ACTION  

sub_title[[463, 211, 533, 229]]
## BONUS  

text[[115, 246, 825, 299]]
13) Energy – Short Answer Researchers at Brookhaven National Lab are studying computationally efficient ways to solve the Euler-Lagrange equation. The Euler-Lagrange equation is central to what field of mathematical analysis?  

text[[115, 315, 469, 333]]
ANSWER: CALCULUS OF VARIATIONS  

sub_title[[456, 384, 540, 402]]
## TOSS-UP  

text[[115, 419, 863, 492]]
14) Chemistry – Short Answer By name or number, identify all of the following 4 types of bonds which are found in boranes, a general class of compounds with chemical formula BxHy: 1) 2-center 2-electrons; 2) 3-center-2-electrons; 3) Sigma 3-center-4-electrons; 4) Pi 3-center-4-electrons.  

text[[115, 508, 283, 525]]
ANSWER: 1 AND 2  

sub_title[[463, 543, 533, 560]]
## BONUS  

text[[115, 577, 878, 612]]
14) Chemistry – Multiple Choice Pentaborane 11, with chemical formula B5H11, is classified as which of the following types of borane clusters?  

text[[115, 629, 215, 699]]
W) Arachno X) Closo Y) Hypho Z) Nido  

text[[115, 716, 338, 733]]
ANSWER: W) ARACHNOsub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 124, 864, 179]]
15) Physics - Short Answer By name or number, order the following 3 objects in increasing order by the time it takes to roll down a ramp without slipping if they have the same mass: 1) Disk with radius 2; 2) Sphere with radius 1; 3) Rod with length 4.  

text[[115, 195, 258, 212]]
ANSWER: 3, 2, 1  

sub_title[[463, 229, 533, 247]]
## BONUS  

text[[115, 263, 880, 335]]
15) Physics - Short Answer The rotational inertia about the z-axis of a uniform rod of mass M and length L set along the x-axis, with one end on the origin, is \(\frac{1}{3} *\mathrm{ML}^2\) . What is the moment of inertia of a rod of mass \(3\mathrm{kg}\) and length 4 meters about an axis parallel to the z-axis passing through the middle of the rod?  

text[[115, 351, 221, 369]]
ANSWER: 4  

sub_title[[456, 420, 540, 438]]
## TOSS-UP  

text[[115, 454, 850, 491]]
16) Math - Multiple Choice Which of these statements is FALSE about simple, connected planar graphs?  

text[[115, 507, 730, 578]]
W) They can be vertex-colored using 5 colors 
X) They must not contain the complete graph \(\mathbf{K}_5\) Y) The amount of edges is less than or equal to 3 times the amount of vertices 
Z) All vertices must have degree less than 6  

text[[115, 594, 697, 612]]
ANSWER: Z) ALL VERTICES MUST HAVE DEGREE LESS THAN 6  

sub_title[[463, 629, 533, 647]]
## BONUS  

text[[115, 664, 875, 700]]
16) Math - Short Answer How many edges must be removed from \(\mathbf{K}_6\) , the complete graph on six vertices to leave a graph without any copies of \(\mathbf{K}_4\) , the complete graph on four vertices?  

text[[115, 716, 220, 733]]
ANSWER: 3sub_title[[455, 90, 540, 108]]
## TOSS-UP  

text[[115, 123, 876, 160]]
17) Earth and Space – Multiple Choice Which of the following kinds of moraines is the most common?  

text[[115, 177, 285, 247]]
W) Ground Moraine 
X) Lateral Moraine 
Y) Medial Moraine 
Z) Terminal Moraine  

text[[115, 263, 421, 282]]
ANSWER: W) GROUND MORAINE  

sub_title[[463, 298, 533, 316]]
## BONUS  

text[[115, 333, 840, 352]]
17) Earth and Space – Multiple Choice Which of the following minerals lacks cleavage?  

text[[115, 368, 220, 438]]
W) Olivine 
X) Epidote 
Y) Staurolite 
Z) Sodalite  

text[[115, 455, 320, 474]]
ANSWER: W) OLIVINE  

sub_title[[455, 525, 540, 543]]
## TOSS-UP  

text[[115, 559, 872, 631]]
18) Energy – Short Answer Researchers at Idaho National Labs are studying how to implement solar energy in the US. By name or number, order the following 4 layers from furthest to exposed sunlight to closest to exposed sunlight in a solar panel: 1) Silicon layer; 2) N type semiconductor; 3) P type semiconductor.  

text[[115, 647, 260, 665]]
ANSWER: 3, 1, 2  

sub_title[[463, 682, 533, 700]]
## BONUS  

text[[115, 716, 879, 787]]
18) Energy – Short Answer Researchers at Lawrence Berkeley National Lab are studying how to shorten methane’s lifespan in the atmosphere. By name or number, identify all of the following 3 greenhouse gases that have a Global Warming Potential less than that of methane: 1) Water; 2) Carbon Dioxide; 3) Nitrous Oxide.  

text[[115, 803, 283, 821]]
ANSWER: 1 AND 2sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 123, 850, 160]]
19) Biology – Multiple Choice Which of the following animals would produce the highest urine/plasma ratio?  

text[[115, 177, 248, 247]]
W) Salmon  X) Salamander  Y) Kangaroo rat  Z) Ostrich  

text[[115, 263, 392, 282]]
ANSWER: Y) KANGAROO RAT  

sub_title[[463, 298, 533, 316]]
## BONUS  

text[[115, 332, 861, 370]]
19) Biology – Multiple Choice Which of the following neurotransmitters mimics the effects of the neurotransmitter glutamate in regards to synaptic plasticity?  

text[[115, 385, 207, 456]]
W) TRPV1  X) NMDA  Y) P2X  Z) GABA  

text[[115, 473, 296, 491]]
ANSWER: X) NMDA  

sub_title[[456, 542, 540, 560]]
## TOSS-UP  

text[[115, 576, 857, 630]]
20) Chemistry – Short Answer By name or number, order the following three measures of speed for a sample of gas particles from least to greatest: 1) Average; 2) Root mean square; 3) Most common.  

text[[115, 646, 260, 664]]
ANSWER: 3, 1, 2  

sub_title[[463, 681, 533, 699]]
## BONUS  

text[[115, 715, 852, 769]]
20) Chemistry – Multiple Choice Which of the following is closest to the value of X given that half of the particles in a sample of gas are moving at a speed between 0 and X times the square root of the quantity RT over M?  

text[[115, 785, 173, 855]]
W) 1.4  X) 1.5  Y) 1.6  Z) 1.7  

text[[115, 873, 261, 891]]
ANSWER: Y) 1.6sub_title[[456, 90, 540, 107]]
## TOSS-UP  

text[[115, 123, 874, 195]]
21) Physics – Multiple Choice Two initially uncharged conductors are mounted on insulating stands. A negatively charged rod is brought near the conductors but does not touch them. With the rod held in place, conductor 2 is moved to the right so that the conductors are separated. What is the charge on conductor 2?  

text[[115, 211, 250, 281]]
W) Positive X) Negative Y) Zero Z) Indeterminate  

text[[116, 298, 336, 316]]
ANSWER: X) NEGATIVE  

sub_title[[464, 333, 533, 351]]
## BONUS  

text[[115, 368, 864, 422]]
21) Physics – Multiple Choice A negatively charged rod is brought near, but does not touch, an initially uncharged electroscope. With the rod in place, a finger touches the electroscope. When the finger and the rod are removed, what is the charge on the leaves of the electroscope?  

text[[115, 438, 250, 507]]
W) Positive X) Negative Y) Zero Z) Indeterminate  

text[[116, 524, 328, 542]]
ANSWER: W) POSITIVE  

sub_title[[456, 594, 540, 612]]
## TOSS-UP  

text[[115, 629, 875, 665]]
22) Math – Short Answer Given that the areas of the faces of a rectangular prism are 6, 8, and 12, what is the volume of the rectangular prism?  

text[[116, 681, 230, 699]]
ANSWER: 24  

sub_title[[464, 716, 533, 734]]
## BONUS  

text[[115, 750, 856, 804]]
22) Math – Short Answer A plane cuts a cube with side length 6 and splits it into two parts. Given that one of the parts is a triangular pyramid, find the maximum possible value of the volume of the triangular pyramid.  

text[[116, 821, 230, 838]]
ANSWER: 36sub_title[[456, 90, 540, 107]]
## TOSS-UP  

text[[115, 123, 861, 179]]
23) Earth and Space – Short Answer By name or number, order the following four astronomical bodies in increasing order of energy per photon emitted: 1) crab pulsar, 2) quasar 3C 273, 3) Betelgeuse, 4) Rigel.  

text[[116, 195, 279, 212]]
ANSWER: 2, 3, 4, 1  

sub_title[[463, 229, 533, 247]]
## BONUS  

text[[115, 263, 871, 300]]
23) Earth and Space – Multiple Choice Due to the high penetration of x-rays, the Chandra X-Ray Observatory makes use of which of the following types of mirrors?  

text[[115, 316, 232, 386]]
W) Spherical 
X) Parabolic 
Y) Hyperbolic 
Z) Planar  

text[[115, 403, 348, 421]]
ANSWER: X) PARABOLIC