sub_title[[456, 140, 540, 158]]
## TOSS-UP  

text[[115, 174, 874, 228]]
1) Energy – Short Answer Researchers at the University of Southampton are studying chaotic physical phenomena, including turbulence. What dimensionless quantity quantifies the turbulence of a fluid?  

text[[115, 244, 404, 262]]
ANSWER: REYNOLDS NUMBER  

sub_title[[463, 279, 533, 297]]
## BONUS  

text[[115, 314, 867, 367]]
1) Energy – Short Answer Researchers at Los Alamos National Laboratory are studying the Quantum Butterfly effect. The butterfly effect is named after what quintessential demonstration of chaos theory?  

text[[115, 382, 674, 402]]
ANSWER: LORENZ ATTRACTOR (ACCEPT: LORENZ SYSTEM)  

sub_title[[456, 454, 540, 472]]
## TOSS-UP  

text[[115, 488, 867, 524]]
2) Biology – Multiple Choice An orchid mantis that disguises itself as a bright flower to lure prey exhibits what kind of mimicry?  

text[[115, 541, 240, 610]]
W) Batesian X) Mullerian Y) Peckhamian Z) Self  

text[[115, 627, 367, 645]]
ANSWER: Y) PECKHAMIAN  

sub_title[[463, 662, 533, 680]]
## BONUS  

text[[115, 697, 836, 732]]
2) Biology – Short Answer What kind of symbiotic relationship is exhibited between the bread mold Penicillium and certain bacteria?  

text[[115, 748, 694, 767]]
ANSWER: ANTIBIOSIS (ACCEPT: ANTAGONISM, AMENSALISM)sub_title[[456, 90, 540, 107]]
## TOSS-UP  

text[[115, 123, 876, 195]]
3) Chemistry - Short Answer By name or number, identify all of the following 4 changes to a standard copper-zinc galvanic cell that would increase the measured cell potential: 1) Increasing the concentration of copper (II); 2) Decreasing the concentration of copper (II); 3) Increasing the concentration of zinc (II); 4) Decreasing the concentration of zinc (II).  

text[[116, 211, 283, 229]]
ANSWER: 1 AND 4  

sub_title[[463, 247, 533, 265]]
## BONUS  

text[[115, 281, 874, 352]]
3) Chemistry - Short Answer At 298 K, a concentration cell with two solutions of \(\mathrm{Ag^{+}}\) has a measured cell potential of 0.075 V. To one significant figure, by what factor must the concentration of the more concentrated cell be multiplied by to double the measured cell potential?  

text[[115, 368, 230, 386]]
ANSWER: 20  

sub_title[[456, 438, 540, 456]]
## TOSS-UP  

text[[115, 472, 872, 577]]
4) Physics - Short Answer Two particles have both charge and mass, and feel an attractive force of F to each other, which is a combination of the electrostatic force and the gravitational force. When the charge of one particle is doubled, the two particles feel an attractive force of 4F/3 towards each other. If the charges of the particles had remained at their original values, but the mass of one particle was doubled instead, then what would be the force the particles felt towards each other?  

text[[115, 594, 246, 611]]
ANSWER: 5F/3  

sub_title[[463, 630, 533, 647]]
## BONUS  

text[[115, 664, 881, 716]]
4) Physics - Short Answer A car with mass 2,000 kg is driving up a ramp with a 30 incline. If the car exerts a force of 10,000 N, and it moves a vertical distance of 10 meters high in 2 seconds, what is the power exerted over those 2 seconds, in Watts?  

text[[115, 733, 275, 750]]
ANSWER: 100,000sub_title[[456, 90, 540, 107]]
## TOSS-UP  

text[[115, 123, 875, 160]]
5) Math - Short Answer On Anurag's farm, there are chickens and cows. If there are 72 heads and 150 feet not including Anurag, how many chickens are there on Anurag's farm?  

text[[115, 176, 230, 194]]
ANSWER: 69  

sub_title[[464, 211, 533, 229]]
## BONUS  

text[[115, 245, 864, 282]]
5) Math - Short Answer The product of the factors of \(12^{4}\) can be written as \(12^{n}\) , where n is a positive integer. What is the value of n?  

text[[115, 298, 230, 316]]
ANSWER: 90  

sub_title[[456, 368, 540, 386]]
## TOSS-UP  

text[[115, 402, 861, 456]]
6) Physics - Short Answer Billie the Blithe Blower blows into a closed pipe that is 2 meters long. Being blithe, Billie wants to know the wavelength of the second lowest note she could blow, in meters. What is it?  

text[[115, 472, 235, 490]]
ANSWER: 8/3  

sub_title[[464, 508, 533, 526]]
## BONUS  

text[[115, 542, 872, 613]]
6) Physics - Short Answer Barry the Big Bellower bellows a note at 100 decibels. His friend, Wally the Wimpy Whisperer, who is standing a negligible distance away, wants to join in, so he tries his best and yells a note at 80 decibels. To the nearest integer, what is the intensity, in decibels, of the sound the two produce in combination?  

text[[115, 629, 240, 647]]
ANSWER: 100sub_title[[456, 90, 540, 107]]
## TOSS-UP  

text[[115, 124, 863, 178]]
7) Energy – Multiple Choice Researchers at the US Department of Energy have been engineering systems of RNA with CAD to study genetic expression in microorganisms. Which of the following is found in prokaryotes?  

text[[115, 195, 212, 264]]
W) snRNA  X) miRNA  Y) RNase P  Z) snoRNA  

text[[116, 281, 316, 299]]
ANSWER: Y) RNASE P  

sub_title[[463, 316, 533, 333]]
## BONUS  

text[[115, 351, 872, 404]]
7) Energy – Short Answer Researchers at the US Department of Energy have also been studying TATA box equivalents in prokaryotes. Disregarding 5 prime and 3 prime ends, what is the DNA sequence of that equivalent?  

text[[116, 420, 288, 437]]
ANSWER: TATAAT  

sub_title[[456, 490, 540, 507]]
## TOSS-UP  

text[[112, 524, 822, 544]]
8) Biology – Short Answer What phylum of fungi do ectomycorrhizal fungi belong to?  

text[[115, 560, 393, 577]]
ANSWER: GLOMEROMYCOTA  

sub_title[[463, 594, 533, 612]]
## BONUS  

text[[115, 629, 880, 664]]
8) Biology – Multiple Choice Which of the following statements describing imperfect fungi is FALSE?  

text[[115, 682, 645, 698]]
W) They are classified based on the morphological species concept  

text[[115, 700, 380, 716]]
X) They are a polyphyletic group  

text[[115, 717, 485, 733]]
Y) They include fungi that cause athlete's foot  

text[[115, 735, 485, 751]]
Z) They utilize budding processes to reproduce  

text[[115, 768, 727, 786]]
ANSWER: Z) THEY UTILIZE BUDDING PROCESSES TO REPRODUCEsub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[113, 123, 880, 161]]
9) Chemistry – Multiple Choice Which of the following elements shows two near-equal peaks in mass spectrometry?  

text[[115, 177, 214, 247]]
W) Fluorine 
X) Chlorine 
Y) Bromine 
Z) Iodine  

text[[116, 264, 327, 282]]
ANSWER: Y) BROMINE  

sub_title[[463, 299, 533, 317]]
## BONUS  

text[[115, 333, 875, 370]]
9) Chemistry – Multiple Choice The base peak in a mass spectrum of 3-pentanone has a mass to charge ratio closest to which of the following?  

text[[115, 386, 168, 455]]
W) 43 
X) 57 
Y) 71 
Z) 86  

text[[116, 473, 256, 491]]
ANSWER: X) 57  

sub_title[[456, 542, 540, 560]]
## TOSS-UP  

text[[115, 576, 875, 631]]
10) Physics – Short Answer If an object of mass m falling through the air with a velocity v experiences a drag force of magnitude F, what is the magnitude of the drag force experienced by an object falling with mass 3m and velocity 4v?  

text[[116, 647, 241, 664]]
ANSWER: 16F  

sub_title[[463, 682, 533, 700]]
## BONUS  

text[[116, 716, 872, 770]]
10) Physics – Short Answer If the air temperature is 70 degrees Fahrenheit, and water takes 5 minutes to cool from 170 degrees Fahrenheit to 120 degrees Fahrenheit, what will its temperature be in 5 more minutes, in degrees Fahrenheit?  

text[[116, 786, 230, 803]]
ANSWER: 95sub_title[[455, 90, 540, 108]]
## TOSS-UP  

text[[115, 123, 879, 160]]
11) Math – Multiple Choice A brandohedron is a convex polyhedron with 100 vertices and 69 faces. How many edges does a brandohedron have?  

text[[115, 177, 585, 247]]
W) 167  X) 168  Y) 169  Z. There is not enough information to determine the answer  

text[[115, 263, 270, 281]]
ANSWER: W) 167  

sub_title[[463, 298, 533, 316]]
## BONUS  

text[[115, 332, 881, 369]]
11) Math – Short Answer There are 30 different complex numbers z such that \(z^{30} = 1\) . For how many of these is \(z^5\) a real number?  

text[[115, 385, 231, 403]]
ANSWER: 10  

sub_title[[455, 456, 540, 474]]
## TOSS-UP  

text[[115, 490, 875, 527]]
12) Earth and Space – Short Answer What period of rapid expansion immediately follows the Big Bang?  

text[[115, 542, 604, 561]]
ANSWER: COSMIC INFLATION (ACCEPT: INFLATION)  

sub_title[[463, 578, 533, 595]]
## BONUS  

text[[115, 612, 866, 666]]
12) Earth and Space – Short Answer By name or number, order the following four epochs in the history of the universe in chronological order: 1) Grand unification; 2) Planck; 3) Quark; 4) Inflationary.  

text[[115, 682, 280, 700]]
ANSWER: 2, 1, 4, 3sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 124, 878, 177]]
13) Energy - Multiple Choice Researchers at Lawrence Livermore National Laboratory are studying the properties of chemical warfare agents in the gas phase. In the virial expansion, what does the second virial coefficient account for?  

text[[115, 195, 422, 265]]
W) Size of the gas particles 
X) dimerization of gaseous species 
Y) Bimolecular attraction of particles 
Z) Trimolecular repulsions of particles  

text[[115, 281, 605, 299]]
Answer: Y) MOLECULAR ATTRACTION OF PARTICLES  

sub_title[[463, 316, 533, 333]]
## BONUS  

text[[115, 350, 858, 421]]
13) Energy - Short Answer Researchers at Idaho National Laboratory are studying vapor enriching methods to separate radioactive gases. When separating a 1:1 mixture of Bromine vapor (molar mass 160) and Argon (molar mass 40) via effusion, how many effusion steps are needed to obtain a 16:1 ratio of Argon to Bromine Vapor?  

text[[115, 437, 221, 455]]
ANSWER: 4  

sub_title[[456, 507, 540, 525]]
## TOSS-UP  

text[[115, 542, 783, 560]]
14) Biology - Short Answer What kind of survivorship curve do squirrels follow?  

text[[115, 576, 279, 594]]
ANSWER: TYPE II  

sub_title[[463, 612, 533, 630]]
## BONUS  

text[[115, 647, 875, 666]]
14) Biology - Multiple Choice What kind of evolution is illustrated by Red Queen dynamics?  

text[[115, 682, 308, 751]]
W) Disruptive selection 
X) Fluctuating selection 
Y) Kin selection 
Z) Sexual dimorphism  

text[[115, 769, 485, 786]]
ANSWER: X) FLUCTUATING SELECTIONsub_title[[456, 90, 540, 107]]
## TOSS-UP  

text[[115, 123, 825, 143]]
15) Chemistry - Multiple Choice Which of the following has the highest boiling point?  

text[[115, 159, 303, 229]]
W) Chloromethane 
X) Dichloromethane 
Y) Trichloromethane 
Z) Carbon tetrachloride  

text[[115, 246, 484, 264]]
ANSWER: Z) CARBON TETRACHLORIDE  

sub_title[[463, 280, 533, 298]]
## BONUS  

text[[115, 315, 866, 385]]
15) Chemistry - Short Answer Two molecules experience London dispersion forces of magnitude F when at a distance D from each other. In terms of F to one significant figure, what will the magnitude of the London dispersion forces between the two molecules be at a distance 1.5D?  

text[[115, 402, 255, 420]]
ANSWER: 0.06F  

sub_title[[456, 473, 540, 490]]
## TOSS-UP  

text[[115, 507, 812, 543]]
16) Physics - Short Answer If a material has an index of refraction of 10 million, to 2 significant figures, how many meters does light travel in the material in 1 minute?  

text[[115, 559, 251, 576]]
ANSWER: 1800  

sub_title[[463, 594, 533, 612]]
## BONUS  

text[[115, 629, 872, 682]]
16) Physics - Short Answer A bar of metal with mass M lies on the x axis between \(x = 0\) and \(x = 1\) , with the density at a point \(x\) being 6 \(\square\) . What is the \(x\) -coordinate of the center of mass of the bar, in terms of M?  

text[[115, 699, 244, 716]]
ANSWER: 7/Msub_title[[456, 89, 541, 107]]
## TOSS-UP  

text[[115, 123, 847, 144]]
17) Math - Short Answer What is the geometric mean of the roots of \(\mathrm{x}^{3} - 11\mathrm{x}^{2} + 34\mathrm{x} - 27?\)  

text[[115, 159, 221, 176]]
ANSWER: 3  

sub_title[[463, 177, 534, 195]]
## BONUS  

text[[115, 211, 877, 247]]
17) Math - Short Answer Let \(\mathrm{r}_{1}, \mathrm{r}_{2}, \mathrm{r}_{3}\) be roots of the polynomial \(\mathrm{x}^{3} + 5\mathrm{x}^{2} - 4\mathrm{x} + 9\) . What is the value of \(1 / \mathrm{r}_{1} + 1 / \mathrm{r}_{2} + 1 / \mathrm{r}_{3}?\)  

text[[115, 263, 237, 281]]
ANSWER: 4/9  

sub_title[[456, 316, 541, 333]]
## TOSS-UP  

text[[115, 350, 802, 387]]
18) Earth and Space - Short Answer What region around a rotating black hole drags spacetime and is a means of theoretically extracting energy from black holes?  

text[[115, 402, 337, 420]]
ANSWER: ERGOSPHERE  

sub_title[[463, 437, 534, 455]]
## BONUS  

text[[115, 472, 854, 526]]
18) Earth and Space - Short Answer By name or number, identify all of the following four spacetime metrics which predict the existence of an ergosphere: 1) Schwarzschild; 2) Kerr; 3) Reissner-Nordstrom; 4) Kerr-Newman.  

text[[115, 542, 240, 560]]
ANSWER: 2, 4sub_title[[456, 90, 540, 107]]
## TOSS-UP  

text[[115, 124, 840, 160]]
19) Chemistry - Short Answer Ignoring spin-spin coupling, how many peaks would a H1 NMR spectrum of 2-butanol have?  

text[[115, 177, 221, 194]]
ANSWER: 6  

sub_title[[463, 211, 533, 229]]
## BONUS  

text[[115, 245, 864, 281]]
19) Chemistry - Short Answer An organic compound with formula C4H8O2 shows a single peak in H1 NMR. What is this compound's IUPAC name?  

text[[115, 297, 675, 316]]
ANSWER: 1,4- DIOXANE (ACCEPT: 1,4- DIOXACYCLOHEXANE)  

sub_title[[456, 368, 540, 386]]
## TOSS-UP  

text[[115, 402, 879, 439]]
20) Biology - Multiple Choice Which of the following techniques was used extensively in the Human Genome Project?  

text[[115, 456, 359, 526]]
W) Next-gen sequencing 
X) Southern blotting 
Y) Phage Induction 
Z) Polymerase Chain Reaction  

text[[115, 542, 535, 560]]
ANSWER: Z) POLYMERASE CHAIN REACTION  

sub_title[[463, 577, 533, 595]]
## BONUS  

text[[115, 611, 875, 648]]
20) Biology - Short Answer By name or number, identify all of the following four things that are used in Sanger Sequencing: 1) DNA Primer; 2) Deoxynucleotides; 3) Buffer; 4) Cations.  

text[[115, 664, 248, 682]]
ANSWER: ALLsub_title[[456, 89, 540, 107]]
## TOSS-UP  

text[[115, 123, 712, 142]]
21) Earth and Space - Short Answer During what era did Laurasia form?  

text[[115, 158, 312, 176]]
ANSWER: MESOZOIC  

sub_title[[463, 194, 533, 212]]
## BONUS  

text[[115, 228, 835, 265]]
21) Earth and Space - Short Answer What is the new geologic period currently being proposed to describe the period of which humans have had significant impact on the Earth?  

text[[115, 280, 368, 299]]
ANSWER: ANTHROPOCENE  

sub_title[[456, 350, 540, 368]]
## TOSS-UP  

text[[115, 384, 881, 421]]
22) Earth and Space - Short Answer If the horizontal and the vertical component of the earth's magnetic field are equal, what is the resulting angle of dip?  

text[[115, 436, 323, 455]]
ANSWER: 45 DEGREES  

sub_title[[463, 473, 533, 490]]
## BONUS  

text[[115, 507, 864, 560]]
22) Earth and Space - Short Answer What is the name of the theory that explains how Earth gets its magnetic field from convection currents of the molten outer core and the solid inner core?  

text[[115, 576, 374, 594]]
ANSWER: DYNAMO EFFECTsub_title[[456, 90, 540, 107]]
## TOSS-UP  

text[[114, 123, 866, 161]]
23) Math – Short Answer By name or number, identify all of the following three shapes that can tessellate the plane: 1) Scalene triangle; 2) Kite; 3) Regular octagon.  

text[[115, 177, 283, 194]]
ANSWER: 1 AND 2  

sub_title[[463, 196, 533, 213]]
## BONUS  

text[[115, 230, 870, 265]]
23) Math – Short Answer What is the term for the set of numbers in between 0 and 1 with no 1s in their ternary representation?  

text[[115, 281, 331, 299]]
ANSWER: CANTOR SET