sub_title[[494, 89, 595, 107]]
## ROUND 17  

sub_title[[500, 140, 585, 159]]
## TOSS-UP  

text[[144, 175, 725, 195]]
1) BIOLOGY Short Answer Riboflavin is to FAD as Pantothenate is to:  

text[[144, 210, 710, 229]]
ANSWER: CoA (pronounced: Kho-A) (ACCEPT: COENZYME A)  

sub_title[[506, 245, 577, 264]]
## BONUS  

text[[144, 280, 871, 317]]
1) BIOLOGY Short Answer Order the following 4 objects from the smallest to the largest: the diameter of a DNA molecule, a Rickettsia, a ribosome, a methionine molecule  

text[[144, 332, 875, 370]]
ANSWER: A METHIONINE MOLECULE, THE DIAMETER OF A DNA MOLECULE, A RIBOSOME, A RICKETTSIA  

sub_title[[500, 418, 585, 437]]
## TOSS-UP  

text[[144, 453, 902, 491]]
2) PHYSICS Short Answer In 1851, Thomson independently rediscovered the idea of absolute zero by extrapolating from the law most commonly known as?  

text[[145, 507, 384, 525]]
ANSWER: CHARLES LAW  

sub_title[[506, 542, 577, 561]]
## BONUS  

text[[144, 577, 904, 614]]
2) PHYSICS Multiple Choice If an astronaut traveling at \(25\%\) of the speed of light passes a 10 meter long satellite, what length will the astronaut get for a measure of the satellite:  

text[[144, 629, 275, 648]]
W) 1.75 meters  

text[[144, 664, 270, 717]]
X) 0.87 meters Y) 8.66 meters Z) 9.68 meters  

text[[144, 733, 386, 751]]
ANSWER: Z) 9.68 METERS  

text[[144, 766, 634, 787]]
(Solution: \(\mathrm{L}^{1} = \mathrm{L}\sqrt{1 - \mathrm{V}^{2}} = 10\) meters \(\times \sqrt{1 - .25} = 9.68\) meters)sub_title[[500, 89, 584, 107]]
## TOSS-UP  

text[[144, 124, 933, 179]]
3) CHEMISTRY Short Answer What is the name for one of the most central concepts of chemical equilibria, which states that a change in one of the variables that describes a system at equilibrium produces a shift in the position of the equilibrium that counteracts the effect of the change:  

text[[144, 194, 500, 212]]
ANSWER: LECHATELIER'S PRINCIPLE  

sub_title[[508, 230, 577, 248]]
## BONUS  

text[[144, 264, 933, 301]]
3) CHEMISTRY Short Answer Using electrophoresis at a pH of 6.0, which two of the following 5 amino acids would move fastest to the cathode: arginine, glutamic acid, glycine, alanine, lysine  

text[[144, 315, 425, 334]]
ANSWER: LYSINE, ARGININE  

sub_title[[500, 385, 584, 404]]
## TOSS-UP  

text[[144, 420, 940, 474]]
4) ASTRONOMY Multiple Choice What form of diffraction grating has very fine lines ruled much farther apart than other gratings, giving it a much higher resolution, but over a narrow wavelength band:  

text[[144, 491, 310, 563]]
W) airy disc grating 
X) campo grating 
Y) Doppler grating 
Z) eschelle grating  

text[[144, 578, 465, 596]]
ANSWER: Z) ESCHELLE GRATING  

sub_title[[508, 613, 577, 630]]
## BONUS  

text[[144, 647, 937, 684]]
4) ASTRONOMY Short Answer The solar neutrino detector in Lead, South Dakota, was originally constructed to contain about 100,000 gallons of what chemical?  

text[[144, 699, 656, 718]]
ANSWER: \(\mathrm{C_2CL_4}\) (ACCEPT: TETRACHLOROETHYLENE)sub_title[[500, 90, 584, 107]]
## TOSS-UP  

text[[144, 124, 766, 143]]
5) MATH Multiple Choice The total distance traveled, given by the equation  

text[[144, 143, 931, 195]]
\(\mathrm{f(t_{1})\Delta t + f(t_{2})\Delta t + \ldots f(t_{n})\Delta t}\) , (read as: f of t sub 1, delta t, + f of t sub 2, delta t, + all values up to f of t sub n, delta t, ), for which f is an increasing function, can be used to find which of the following between the values \(\mathrm{t} = \mathrm{a}\) and \(\mathrm{t} = \mathrm{b}\) :  

text[[144, 212, 301, 283]]
W) right-hand sum 
X) left-hand sum 
Y) upper bound 
Z) endless bound  

text[[144, 298, 451, 317]]
ANSWER: W) RIGHT-HAND SUM  

sub_title[[507, 334, 577, 352]]
## BONUS  

text[[144, 368, 841, 389]]
5) MATH Short Answer Find the derivative of the following equation: \(y = 2^{x} + 2 \times 3^{x}\)  

text[[144, 403, 399, 422]]
ANSWER: \(\ln 2(2^{x}) + 2 \ln 3(3^{x})\)  

sub_title[[500, 470, 584, 488]]
## TOSS-UP  

text[[144, 504, 936, 541]]
6) EARTH SCIENCE Multiple Choice A major break through in the development of plate tectonic theory occurred in the late 1960s with sea floor mapping by:  

text[[144, 558, 377, 628]]
W) satellite imagery 
X) magnetic characteristics 
Y) aerial photography 
Z) water depth by soundings  

text[[144, 644, 562, 662]]
ANSWER: X) MAGNETIC CHARACTERISTICS  

sub_title[[507, 679, 578, 697]]
## BONUS  

text[[144, 714, 896, 750]]
6) EARTH SCIENCE Short Answer Order the following three types of magma based on their viscosity, starting with the least viscous: rhyolitic, basaltic, andesitic  

text[[144, 766, 570, 784]]
ANSWER: BASALTIC, ANDESITIC, RHYOLITICsub_title[[500, 90, 584, 107]]
## TOSS-UP  

text[[144, 124, 925, 160]]
7) GENERAL SCIENCE Multiple Choice Which of the following is TRUE for the f-number in a typical camera lens:  

text[[144, 177, 655, 247]]
W) the larger the f-number, the more light reaches the film 
X) the larger the f-number, the greater the depth of field 
Y) the smaller the f-number, the lesser the light reaches the film 
Z) the smaller the f-number, the greater the depth of field  

text[[144, 263, 891, 282]]
ANSWER: X) THE LARGER THE F- NUMBER, THE GREATER THE DEPTH OF FIELD  

sub_title[[507, 299, 577, 316]]
## BONUS  

text[[144, 333, 888, 369]]
7) GENERAL SCIENCE Multiple Choice Which of the following has been most effectively implicated in Alzheimer's disease:  

text[[144, 386, 421, 456]]
W) glutanic oxygenase 
X) aluminum toxicosis 
Y) amyloid-beta precursor protein 
Z) poor diet  

text[[144, 473, 628, 491]]
ANSWER: Y) AMYLOID-BETA PRECURSOR PROTEIN  

sub_title[[500, 542, 584, 560]]
## TOSS-UP  

text[[144, 577, 876, 612]]
8) COMPUTER SCIENCE Multiple Choice Which of the following algorithms is the most efficient:  

text[[144, 630, 290, 700]]
W) Insertion Sort 
X) Selection Sort 
Y) Quick Sort 
Z) Merge Sort  

text[[144, 716, 396, 734]]
ANSWER: Z) MERGE SORT  

sub_title[[507, 752, 577, 769]]
## BONUS  

text[[144, 786, 903, 839]]
8) COMPUTER SCIENCE Short Answer C programs typically go through 6 phases to be executed. Order the following 6 phases from initial to final development: preprocess; compile; load; link; edit; execute  

text[[144, 855, 768, 874]]
ANSWER: EDIT; PREPROCESS; COMPILE; LINK; LOAD; EXECUTEsub_title[[499, 89, 584, 107]]
## TOSS-UP  

text[[140, 123, 900, 144]]
9) BIOLOGY Multiple Choice Select the hormone NOT CORRECTLY paired with its target:  

text[[143, 159, 480, 231]]
W) MSH and epidermal melanocytes  
X) ACTH and adrenal gland  
Y) TSH and thyroid parafollicular C cells  
Z) LH and maturing follicles  

text[[143, 245, 716, 265]]
ANSWER: Y) TSH AND THYROID PARAFOLICULAR C CELLS  

sub_title[[507, 281, 577, 299]]
## BONUS  

text[[142, 315, 911, 352]]
9) BIOLOGY Short Answer Using the following single stranded DNA, give the corresponding messenger RNA sequence:  

text[[143, 352, 922, 389]]
(Pronunciation: please give a brief pause at each hyphen between the reading of each three letters) TAC - GGA - GGG - GCA - CCC - TAT - TTA  

text[[143, 402, 770, 423]]
ANSWER: AUG - CCU - CCC - CGU - GGG - AUA - AAU (must be exact)  

sub_title[[500, 472, 584, 490]]
## TOSS-UP  

text[[143, 506, 861, 544]]
10) PHYSICS Short Answer What did Roentgen accidentally discover when he noticed a platinocyanide coated paper began to glow?  

text[[143, 558, 323, 577]]
ANSWER: X- RAYS  

sub_title[[507, 594, 577, 612]]
## BONUS  

text[[143, 628, 916, 667]]
10) PHYSICS Multiple Choice Given Planck's constant is \(6.6 \times 10^{-34}\) Joule-seconds, what is the de Broglie wavelength of a of a 0.15 kilogram onion traveling at 20 meters per second:  

text[[143, 681, 323, 757]]
W) \(3.3 \times 10^{-35}\) meters  
X) \(3.3 \times 10^{-34}\) meters  
Y) \(2.2 \times 10^{-34}\) meters  
Z) \(2.2 \times 10^{-35}\) meters  

text[[143, 773, 441, 794]]
ANSWER: Y) \(2.2 \times 10^{-34}\) METERS  

text[[143, 809, 623, 830]]
(Solution: \(6.6 \times 10^{-34} \div 0.15 \mathrm{~Kg} \times 20 \mathrm{~m} / \mathrm{sec} = 2.2 \times 10^{-34} \mathrm{~m}\) )sub_title[[500, 89, 585, 107]]
## TOSS-UP  

text[[144, 124, 890, 161]]
11) CHEMISTRY Short Answer What is the molecular formula for the conjugate base of the following Brønsted-Lowry acid: \(\mathrm{HPO_4^{2 - }}\)  

text[[144, 176, 288, 196]]
ANSWER: \(\mathrm{PO_4^{3 - }}\)  

sub_title[[507, 212, 577, 230]]
## BONUS  

text[[144, 247, 936, 283]]
11) CHEMISTRY Short Answer To 2 decimal places, calculate how many moles of air are in a 4.0 liter tank at 1 atmosphere of pressure and at a temperature of 300K:  

text[[144, 299, 500, 318]]
ANSWER: 0.17 (ACCEPT: 0.16 MOLES)  

text[[144, 334, 773, 353]]
(Solution: \(\mathrm{n = PV / RT; = (1atm)(4L) / 0.08L. atm / K.mol)(300K); = 0.166moles)}\)  

sub_title[[500, 403, 585, 421]]
## TOSS-UP  

text[[144, 438, 897, 474]]
12) ASTRONOMY Multiple Choice Which of the following eyepieces consists of two planoconvex lenses with their flat sides towards the eye and a field stop between them:  

text[[144, 491, 272, 560]]
W) Huygens 
X) Ramsden 
Y) Kellner 
Z) Orthoscopic  

text[[144, 577, 375, 595]]
ANSWER: W) HUYGENS  

sub_title[[507, 612, 577, 630]]
## BONUS  

text[[144, 647, 916, 700]]
12) ASTRONOMY Short Answer Ancient Greek estimates of the sizes of the sun and moon and their relative distances from Earth were based on geometrical relationships in what two celestial events?  

text[[144, 716, 528, 735]]
ANSWER: SOLAR AND LUNAR ECLIPSESsub_title[[500, 89, 585, 107]]
## TOSS-UP  

text[[144, 124, 919, 160]]
13) MATH Short Answer In the graph of a curve such as the cosecant curve, the straight vertical line to which the curve moves closer and closer is called what:  

text[[144, 176, 364, 195]]
ANSWER: ASYMPTOTE  

sub_title[[507, 211, 578, 229]]
## BONUS  

text[[144, 248, 863, 270]]
13) MATH Short Answer Calculate the following indefinite integral: \(\mathrm{I} = x(2x^{2} + 3)^{3}dx\)  

text[[144, 293, 385, 330]]
ANSWER: \(\frac{1}{16} (2x^{2} + 3)^{4} + C\)  

sub_title[[500, 382, 585, 401]]
## TOSS-UP  

text[[144, 416, 923, 454]]
14) EARTH SCIENCE Short Answer If all seismic waves leave the earthquake focus at the same instant, which seismic wave will typically be recorded by as seismograph second?  

text[[144, 469, 736, 489]]
ANSWER: S- WAVE (ACCEPT: SECONDARY OR SHEAR WAVES)  

sub_title[[507, 504, 578, 522]]
## BONUS  

text[[144, 539, 904, 575]]
14) EARTH SCIENCE Multiple Choice In miles per second, the typical velocity of an S-wave near the Earth's surface is which of the following:  

text[[144, 592, 208, 662]]
W) 3.7 
X) 2.2 
Y) 9.7 
Z) 0.6  

text[[144, 679, 301, 697]]
ANSWER: X) 2.2sub_title[[500, 90, 584, 107]]
## TOSS-UP  

text[[144, 124, 897, 144]]
15) GENERAL SCIENCE Multiple Choice A vulture is best classified in which trophic level:  

text[[144, 160, 337, 230]]
W) primary carnivore 
X) secondary carnivore 
Y) omnivore 
Z) detritivore  

text[[144, 246, 403, 264]]
ANSWER: Z) DETRITIVORE  

sub_title[[507, 281, 577, 299]]
## BONUS  

text[[144, 315, 897, 352]]
15) GENERAL SCIENCE Multiple Choice Which of the following best describes why Citrus Canker is such a large threat to Florida's citrus industry:  

text[[144, 369, 520, 438]]
W) canker scales blemish the fruit 
X) it causes early fruit drop 
Y) it rapidly kills the trees 
Z) the fruit rot before they are ready to harvest  

text[[144, 455, 563, 473]]
ANSWER: X) IT CAUSES EARLY FRUIT DROP  

sub_title[[500, 507, 584, 525]]
## TOSS-UP  

text[[144, 542, 933, 595]]
16) COMPUTER SCIENCE Multiple Choice In C programming, what enables programs to simulate call by reference, and to create and manipulate dynamic data structures, such as linked lists and queues:  

text[[144, 612, 262, 682]]
W) pointers 
X) controllers 
Y) processors 
Z) streams  

text[[144, 699, 375, 717]]
ANSWER: W) POINTERS  

sub_title[[507, 734, 577, 752]]
## BONUS  

text[[144, 769, 936, 788]]
16) COMPUTER SCIENCE Multiple Choice Which of the following is NOT a legal tag in HTML:  

text[[144, 805, 218, 873]]
W) span 
X) code 
Y) pic 
Z) linktext[[144, 90, 306, 107]]
ANSWER: Y) PIC  

sub_title[[500, 124, 583, 141]]
## TOSS-UP  

text[[144, 159, 937, 195]]
17) BIOLOGY Multiple Choice Which of the following is well-suited for staining nuclear material and most bacterial outer surfaces:  

text[[144, 212, 303, 282]]
W) methylene blue 
X) crystal violet 
Y) eosin 
Z) safranin  

text[[144, 299, 333, 317]]
ANSWER: Y) EOSIN  

text[[144, 334, 852, 352]]
(Solution: methylene blue, crystal violet and safranin are cationic while eosin is anionic)  

sub_title[[507, 369, 577, 386]]
## BONUS  

text[[144, 403, 916, 439]]
17) BIOLOGY Short Answer Order the following intermediates as they would progress through the citric acid cycle: citrate, oxaloacetate, succinyl CoA, alpha ketogluterate  

text[[144, 455, 916, 473]]
ANSWER: OXALOACETATE, CITRATE, ALPHA KETOGLUTERATE, SUCCINYL COA  

sub_title[[500, 525, 584, 543]]
## TOSS-UP  

text[[144, 560, 919, 595]]
18) PHYSICS Short Answer What principal, enunciated in 1927, was to that date the most direct challenge to the deterministic nature of the universe?  

text[[144, 611, 917, 647]]
ANSWER: HEISENBERG'S UNCERTAINTY PRINCIPAL (ACCEPT: INDETERMINANCY PRINCIPAL)  

sub_title[[507, 664, 577, 681]]
## BONUS  

text[[144, 699, 912, 734]]
18) PHYSICS Short Answer What three elemental isotopes are typically considered the starting points of the three, main, naturally-occurring radioactive decay series?  

text[[144, 750, 828, 786]]
ANSWER: U- 238, U- 235, TH- 232 (ACCEPT: URANIUM- 238, URANIUM- 235, THORIUM- 232)sub_title[[500, 90, 585, 107]]
## TOSS-UP  

text[[144, 124, 883, 160]]
19) CHEMISTRY Short Answer The aldeoxes have 4 asymmetric carbon atoms and can therefore exist as how many stereoisomers?  

text[[144, 177, 266, 195]]
ANSWER: 16  

text[[144, 210, 290, 230]]
(Solution: \(2^{4} = 16\) )  

sub_title[[507, 246, 577, 264]]
## BONUS  

text[[144, 280, 937, 317]]
19) CHEMISTRY Short Answer Calculate the molecular weight of an ether if a 500 milliliter flask is filled with 0.6 grams of the gas at 300K and at a pressure of 380 mmHg:  

text[[144, 333, 461, 352]]
ANSWER: 60G/MOL (ACCEPT: 60)  

text[[144, 369, 667, 404]]
(Solution: \(\mathrm{n} = \frac{\mathrm{PV}}{\mathrm{RT}}; = 0; = 0.0104\mathrm{mol}; 0.6\mathrm{g} / 0.01\mathrm{mol} = 60\mathrm{g} / \mathrm{mol})\)  

sub_title[[500, 456, 585, 474]]
## TOSS-UP  

text[[141, 490, 907, 510]]
20) ASTRONOMY Short Answer In degrees, what is the declination of the sun at the equinox?  

text[[144, 526, 261, 544]]
ANSWER: 0  

sub_title[[507, 561, 577, 579]]
## BONUS  

text[[144, 595, 910, 632]]
20) ASTRONOMY Multiple Choice To a stargazer living in Northern Michigan, a star that lies almost exactly on the celestial equator, such as sigma Orionis, will do which of the following:  

text[[144, 648, 604, 665]]
W) spend 12 hours above the horizon and 12 hours below  

text[[144, 666, 459, 683]]
X) rise in the north and set in the south  

text[[144, 684, 293, 700]]
Y) cannot be seen  

text[[144, 701, 604, 718]]
Z) its diurnal path is cut by the horizon into unequal parts  

text[[144, 733, 864, 753]]
ANSWER: W) SPEND 12 HOURS ABOVE THE HORIZON AND 12 HOURS BELOWsub_title[[499, 88, 585, 107]]
## TOSS-UP  

text[[143, 123, 888, 160]]
21) MATH Short Answer Named after a German mathematician, what type of bottle has one surface with no edges and thus neither an outside nor an inside?  

text[[144, 175, 557, 195]]
ANSWER: KLEIN BOTTLE (ACCEPT: KLEIN)  

sub_title[[507, 210, 577, 228]]
## BONUS  

text[[144, 245, 861, 309]]
21) MATH Short Answer If \(\sin \theta = \frac{\sqrt{3}}{2}\) and \(\theta\) terminates in Quadrant II of the Cartesian coordinate system, in a unit circle find \(\cos \theta\) :  

text[[144, 324, 639, 345]]
ANSWER: - 1/2 (ACCEPT: - 0.5) (answer must be negative)  

text[[144, 359, 802, 383]]
(Solution: \(\mathrm{r}^{2} = \mathrm{x}^{2} + \mathrm{y}^{2}; 1^{2} = \mathrm{x}^{2} + (\sqrt{3} /2)^{2}; \mathrm{x}^{2} = 1 / 4; \mathrm{x} = 1 / 2;\) negative for Quad II)  

sub_title[[499, 435, 585, 454]]
## TOSS-UP  

text[[144, 469, 932, 523]]
22) EARTH SCIENCE Multiple Choice Oxygen and nitrogen molecules in the atmosphere preferentially scatter light of shorter wavelengths causing the sky to appear blue owing to what type of scattering:  

text[[144, 540, 270, 610]]
W) Rayleigh 
X) Mie 
Y) Crepuscular 
Z) parallel  

text[[144, 625, 381, 644]]
ANSWER: W) RAYLEIGH  

sub_title[[507, 660, 577, 679]]
## BONUS  

text[[144, 695, 937, 750]]
22) EARTH SCIENCE Short Answer Calculate the percent relative humidity of air at \(20^{\circ}\mathrm{C}\) with a partial pressure of water of 0.50 kilo-Pascals if liquid water has a vapor pressure of 2.00 kilo-Pascals at that temperature:  

text[[144, 766, 287, 785]]
ANSWER: \(25\%\)  

text[[144, 801, 550, 820]]
(Solution: actual VP/saturation \(\mathrm{VP} = 0.5 / 2 = 25\%\) )sub_title[[500, 89, 584, 107]]
## TOSS-UP  

text[[142, 124, 901, 160]]
23) BIOLOGY Short Answer Which germ layer in mammals is predominantly responsible for forming the skeletal system?  

text[[144, 177, 357, 195]]
ANSWER: MESODERM  

sub_title[[507, 211, 577, 229]]
## BONUS  

text[[144, 245, 940, 282]]
23) BIOLOGY Short Answer If 1n is haploid, 2n is diploid, and 1s is the DNA content in a haploid genome, then what is the n and s value of a somatic human cell in metaphase of mitosis?  

text[[144, 298, 528, 316]]
ANSWER: 4N AND 4S (ACCEPT: 4 AND 4)  

sub_title[[500, 368, 584, 386]]
## TOSS-UP  

text[[144, 402, 866, 438]]
24) CHEMISTRY Short Answer What common disaccharide is composed of two glucose residues?  

text[[144, 455, 338, 473]]
ANSWER: MALTOSE  

sub_title[[507, 490, 577, 508]]
## BONUS  

text[[144, 524, 910, 561]]
24) CHEMISTRY Short Answer Which two of the following 5 amino acids contain nonpolar R groups? serine, glutamine, leucine, tyrosine, phenylalanine  

text[[144, 576, 509, 595]]
ANSWER: LEUCINE, PHENYLALANINEsub_title[[500, 90, 584, 107]]
## TOSS-UP  

text[[144, 124, 916, 178]]
25) PHYSICS Short Answer What is the most common scientific name for the form of radiation that is emitted when relativistic electrons are forced to travel through a curved trajectory in a magnetic field?  

text[[144, 194, 507, 212]]
ANSWER: SYNCHROTRON RADIATION  

sub_title[[508, 229, 577, 247]]
## BONUS  

text[[144, 263, 940, 317]]
25) PHYSICS Short Answer The Department of Energy's Brookhaven National Lab is the home of the RHIC, which is world's highest energy particle collider. What do the letters R, H, I, and C each respectively stand for?  

text[[144, 333, 592, 352]]
ANSWER: RELATIVISTIC HEAVY ION COLLIDER