
## ROUND 14  


## TOSS-UP  


1) CHEMISTRY Multiple Choice The amount of heat required for melting a substance is called its:  


W) heat of liquidation 
X) enthalpy of evaporation 
Y) enthalpy of vaporization 
Z) heat of fusion  


ANSWER: Z) HEAT OF FUSION  


## BONUS  


1) CHEMISTRY Short Answer A Beer's law standard straight-line curve is a plot of what value on the ordinate and what value on the abscissa?  


ANSWER: ORDINATE = ABSORBANCE; ABSCISSA = CONCENTRATION (or molarity)  


## TOSS-UP  


2) PHYSICS Short Answer According to the standard model of particle physics, how many leptons are there, including both matter and antimatter?  


ANSWER: 12  


## BONUS  


2) PHYSICS Short Answer Order the following three substances from the one that will show the largest increase in temperature for each single calorie added to one gram of that substance, to the one that will show the least: lead, water, aluminum  


ANSWER: LEAD, ALUMINUM, WATER  


(Solution: specific heat of water is 1.0, aluminum is 0.21, and lead is 0.03)
## TOSS-UP  


3) BIOLOGY Multiple Choice Which of the following most closely represents the resting membrane potential in a typical human neuron:  


W) -70 millivolts 
X) -60 millivolts 
Y) -45 millivolts 
Z) 0 millivolts  


ANSWER: W) -70 MILLIVOLTS  


## BONUS  


3) BIOLOGY Short Answer According to recent research, especially by Japanese scientists, there are 5 basic tastes. What are they?  


ANSWER: UMAMI, SOUR, BITTER, SALTY, SWEET (accept in any order)  


## TOSS-UP  


4) ASTRONOMY Multiple Choice Which of the following do many astronomers consider as the best candidates for dark matter:  


W) intergalactic quasars 
X) dwarf stars and baryons 
Y) undetected galaxies 
Z) cosmic background radiation  


ANSWER: X) DWARF STARS AND BARYONS  


## BONUS  


4) ASTRONOMY Short Answer Which 2 of the following 5 stars are binary stars: Sirius, Arcturus, Vega, Rigel, Betelgeuse  


ANSWER: SIRIUS; RIGEL
## TOSS-UP  


5) MATH Multiple Choice In trigonometry, the ratio of \(\frac{\text{hypotenuse}}{\text{adjacent}}\) is denoted by:  


W) sec \(\theta\) (read as: the secant of theta)  


X) cot \(\theta\) (read as: the cotangent of theta)  


Y) csc \(\theta\) (read as: the cosecant of theta)  


Z) tan \(\theta\) (read as: the tangent of theta)  


ANSWER: W) SEC \(\theta\)  


## BONUS  


5) MATH Short Answer Use the Binomial Theorem to expand and simplify the following equation: \((x - 2)^{3}\)  


ANSWER: \(x^{3} - 6x^{2} + 12x - 8\)  


## TOSS-UP  


6) EARTH SCIENCE Short Answer From the oldest to the youngest, the Mesozoic Era is subdivided into what 3 periods of the Geological Time Scale:  


ANSWER: TRIASSIC, JURASSIC, CRETACEOUS  


## BONUS  


6) EARTH SCIENCE Short Answer On open seacoasts, what man-made structures are often constructed in pairs at the mouth of a inlet, estuary, or bay, and are intended to stabilize the channel, prevent shoaling, and are used as general protection from larger waves?  


ANSWER: JETTIES (DO NOT ACCEPT: GROINS, BREAKWATERS, OR SEA WALLS)
## TOSS-UP  


7) GENERAL SCIENCE Multiple Choice During the summer, a person swimming on the surface of a lake is swimming in which layer:  


W) thermocline 
X) thermolimnion 
Y) epilimnion 
Z) hypolimnion  


ANSWER: Y) EPILIMNION  


## BONUS  


7) GENERAL SCIENCE Multiple Choice Cellophane is which of the following polymers:  


W) cellulose arylate 
X) nitrocellulose 
Y) colloidon cellulose 
Z) cellulose acetate  


ANSWER: Z) CELLULOSE ACETATE  


## TOSS-UP  


8) COMPUTER SCIENCE Multiple Choice What type of data structure consists of a set of keys and corresponding values:  


W) vector 
X) array 
Y) hashtable 
Z) list  


ANSWER: Y) HASHTABLE  


## BONUS  


8) COMPUTER SCIENCE Short Answer What does the acronym NIC stand for?  


ANSWER: NETWORK INTERFACE CARD
## TOSS-UP  


9) CHEMISTRY Multiple Choice What law states that the vapor pressure of a solution containing a nonvolatile solute is equal to the vapor pressure of pure solvent times the mole fraction of the solvent?  


W) Gay-Lussac's Law  


X) Raoult's Law  


Y) Henry's Law  


Z) Dalton's Law  


ANSWER: X) RAOULT'S LAW  


## BONUS  


9) CHEMISTRY Short Answer After one hour, a radioactive substance decays to \(25\%\) of its original radioactivity. What is the half-life of the sample in minutes?  


ANSWER: 30 MINUTES  


## TOSS-UP  


10) PHYSICS Multiple Choice Which of the following colors of light has the greatest angle of refraction in normal glass:  


W) yellow 
X) green 
Y) orange 
Z) red  


ANSWER: X) GREEN  


## BONUS  


10) PHYSICS Short Answer Ignoring friction and assuming \(\mathrm{g} = 9.8 \mathrm{m / sec}^2\) , how high will a stone reach, in meters rounded to the nearest whole number, if launched vertically at \(25 \mathrm{m / sec}\) :  


ANSWER: 32
## TOSS-UP  


11) BIOLOGY Short Answer What gland is located in the mediastinum (Pron: meed-i-ast-in-um) and after puberty continues to diminish in size and function until it is mostly fatty connective tissue at age 50 in humans?  


ANSWER: THYMUS  


## BONUS  


11) BIOLOGY Multiple Choice Which of the following is NOT true of the Calvin-Benson Cycle:  


W) it was partially deciphered by using two-dimensional paper chromatography 
X) it is also sometimes called the light-independent reaction of photosynthesis 
Y) it converts energy trapped in the light reactions into sugar 
Z) for each \(12\mathrm{CO}_2\) fixed, 6 PGAL are formed  


ANSWER: Z) FOR EACH 12 CO2 FIXED, 6 PGAL ARE FORMED  


## TOSS-UP  


12) ASTRONOMY Multiple Choice Which of the following is another name for the Pleiades (Pron: plea-ah-dees):  


W) M25 
X) the seven sisters 
Y) the little dipper 
Z) the crescent  


ANSWER: X) THE SEVEN SISTERS  


## BONUS  


12) ASTRONOMY Short Answer For a telescope with a focal length of 440 centimeters and an eyepiece of 20 millimeters, what is the magnifying power of the telescope?  


ANSWER: 220 TIMES (ACCEPT: 220X OR 220)  


(Solution: Since 440 centimeters \(= 4,400 \mathrm{mm} \rightarrow 4,400 / 20 = 220\) )
## TOSS-UP  


13) MATH Multiple Choice If f" (read as: f double prime) is greater than zero, the function f is:  


W) concave up 
X) concave down 
Y) the point of inflection 
Z) the point of local maximum  


ANSWER: W) CONCAVE UP  


## BONUS  


13) MATH Short Answer A circle has a diameter of 120 and a minor arc L whose interior angle is \(120^{\circ}\) . In terms of \(\pi\) , what is the arc length?  


ANSWER: \(40\pi\)  


(Solution: arc length \(= (120^{\circ} / 360^{\circ})(2\pi \mathrm{r}); = 1 / 3 (2)(60)\pi ; = 40\pi)\)  


## TOSS-UP  


14) EARTH SCIENCE Multiple Choice The depth at which an ocean wave is disturbed is a function of which of the following:  


W) wavelength 
X) wave energy 
Y) wave period 
Z) wave frequency  


ANSWER: W) WAVELENGTH  


## BONUS  


14) EARTH SCIENCE Multiple Choice An ocean wave begins to change in appearance and behavior when it reaches water depth that is approximately:  


W) 1/8 of its wavelength 
X) 1/4 of its wavelength 
Y) 1/2 of its wavelength 
Z) 3/4 of its wavelength  


ANSWER: Y) 1/2 OF ITS WAVELENGTH
## TOSS-UP  


15) GENERAL SCIENCE Multiple Choice Which of the following is the term for the process whereby steel is softened through slow cooling after enough heat has been added to make the steel lose its brittleness:  


W) drawing 
X) quenching 
Y) tempering 
Z) annealing  


ANSWER: Z) ANNEALING  


## BONUS  


15) GENERAL SCIENCE Multiple Choice A new 2002 USA penny weighs about how many grams:  


W) 0.5 
X) 1.0 
Y) 1.5 
Z) 2.5  


ANSWER: Z) 2.5  


## TOSS-UP  


16) COMPUTER SCIENCE Multiple Choice With ray tracing, the appearance of an object is governed by how the object surface reflects light. Which of the following is best used to give an object an inhomogeneous appearance:  


W) texture 
X) pixelation 
Y) specularity 
Z) amorphous shape  


ANSWER: W) TEXTURE  


## BONUS  


16) COMPUTER SCIENCE Short Answer What does the acronym FORTRAN stand for?  


ANSWER: FORMULA TRANSLATOR
## TOSS-UP  


17) CHEMISTRY Multiple Choice Which of the following is an aromatic hydrocarbon?  


W) benzene 
X) dimethyl ketone 
Y) ethyl methyl ether 
Z) formamide  


ANSWER: W) BENZENE  


## BONUS  


17) CHEMISTRY Multiple Choice \(\mathrm{C}_2\mathrm{H}_4\mathrm{Br}_2\) is the only product of a reaction between ethane and bromine. The reaction is:  


W) an addition reaction 
X) a substitution reaction 
Y) an esterification reaction 
Z) a hydrogenation reaction  


ANSWER: W) AN ADDITION REACTION  


## TOSS-UP  


18) PHYSICS Multiple Choice Light that is a green color is composed of which of the following wavelengths:  


W) 300-400 nanometers 
X) 400-500 nanometers 
Y) 500-600 nanometers 
Z) 600-700 nanometers  


ANSWER: Y) 500-600 NANOMETERS  


## BONUS  


18) PHYSICS Short Answer What is the energy used, in joules, if a current of 2 amps flows though a 10 ohm resistance circuit for 1 minute?  


ANSWER: 2,400  


(Solution: \(\mathrm{W} = \mathrm{I}^2\mathrm{R}\times \mathrm{T} = (2\mathrm{A})^2\times 10\) ohms \(\times 60\mathrm{s} = 2400\) joules)
## TOSS-UP  


19) BIOLOGY Short Answer The absence of what accessory organ demands that Elasmobranchs constantly swim or else they will sink?  


ANSWER: SWIMBLADDER  


## BONUS  


19) BIOLOGY Short Answer Which 2 of the following 5 organisms are NOT nematodes? Nectarocmarcantes (Pron: nee-kate-or mer-kant-ees), Ancylostoma duodenale (Pron: ank-ee-low-stow-mah dew-odd-en-ale-ee), Ascaris lumbricoides (Pron: as-kar-iss lumbri-koid-ees), Taenia saginata (Pron: teen-i-ah saj-inn-a-tah), Fasciola hepatica (Pron: fas-i-oh-lah hep-at-i-ka)  


ANSWER: TAENIA SAGINATA, FASCILIA HEPATICA  


## TOSS-UP  


20) ASTRONOMY Multiple Choice Considering that the Sun is expected to live for a total of ten billion years, how long would a star of ten times the mass of the sun live:  


W) 100 billion years 
X) 100 million years 
Y) 10 million years 
Z) 1 million years  


ANSWER: Y) 10 MILLION YEARS  


## BONUS  


20) ASTRONOMY Multiple Choice Because of recent magnetometer analysis of Europa, it is believed that this moon has:  


W) a subsurface salty ocean 
X) a molten iron core 
Y) polar caps of solid hydrogen 
Z) an atmosphere of methane and ice crystals  


ANSWER: W) A SUBSURFACE SALTY OCEAN
## TOSS-UP  


21) MATH Short Answer What is the general term for a polyhedron with 2 congruent and parallel faces called bases, and whose remaining faces are called parallelograms?  


ANSWER: PRISM  


## BONUS  


21) MATH Multiple Choice If the circumference of a cylindrical tube is 6 and its height is 12, what is the area in terms of \(\pi\) of the base of the cylindrical tube?  


W) \(9\pi\) X) \(3\pi\) Y) \(9 / \pi\) Z) \(3 / \pi\)  


ANSWER: Y) \(9 / \pi\)  


(Solution: \(C = 2\pi r; 6 = 2\pi r; r = 3 / \pi ; \text{Area} = \pi r^2; = \pi (3 / \pi)^2; = 9 / \pi)\)  


## TOSS-UP  


22) GENERAL SCIENCE Multiple Choice Another name for vitamin \(\mathbf{B}_{3}\) is:  


W) thiamin 
X) riboflavin 
Y) niacin 
Z) folic acid  


ANSWER: Y) NIACIN  


## BONUS  


22) GENERAL SCIENCE Multiple Choice Which of the following best describes an interaction between two organisms when one participant is harmed but the other is unaffected:  


W) competition 
X) commensalism (Pron: ko-mens-a-lis-um) 
Y) mutualism 
Z) amensalism (ay-mens-a-lis-um)  


ANSWER: Z) AMENSALISM
## TOSS-UP  


23) CHEMISTRY Multiple Choice Monounsaturated fatty acids contain:  


W) single bonds only 
X) one single bond 
Y) one double bond 
Z) two double bonds  


ANSWER: Y) ONE DOUBLE BOND  


## BONUS  


23) CHEMISTRY Short Answer What two monosaccharides make up the disaccharide lactose?  


ANSWER: GALACTOSE AND GLUCOSE (accept in any order)  


## TOSS-UP  


24) PHYSICS Multiple Choice Which of the following cases would be most directly solved by applying Wien's law:  


W) half-life of an isotope given its nucleon make up  


X) angle of refraction  


Y) charge of an electron  


Z) color of a star given its temperature  


ANSWER: Z) COLOR OF A STAR GIVEN ITS TEMPERATURE  


## BONUS  


24) PHYSICS Multiple Choice In one second, how many electrons will move past a point in a wire carrying a direct current of two amps?  


W) \(2.5\times 10^{18}\) X) \(1.25\times 10^{16}\) Y) \(1.25\times 10^{19}\) Z) \(2.5\times 10^{19}\)  


ANSWER: Y) \(1.25\times 10^{19}\)
## TOSS-UP  


25) BIOLOGY Short Answer What organ of the human body is primarily responsible for culling abnormal erythrocytes?  


ANSWER: SPLEEN  


## BONUS  


25) BIOLOGY Short Answer Order the following 3 monosaccharides from the smallest to the largest: erythrose, mannose, ribose  


ANSWER: ERYTHROSE, RIBOSE, MANNOSE