
## ROUND 1 A  


## TOSS-UP  


1. CHEMISTRY Multiple Choice The best name for the compound made by combining magnesium and chlorine is  


W) magnesium dichloride 
X) dimagnesium monochloride 
Y) magnesium chloride 
Z) chlorine magnusate  


ANSWER: Y) MAGNESIUM CHLORIDE  


## BONUS  


1. CHEMISTRY Short Answer A substance that can react as an acid or a base is called  


ANSWER: AMPHOTERIC (OR AMPHIPROTIC)  


## TOSS-UP  


2. COMPUTER SCIENCE Short Answer On a network, the copying of files or software from a remote server to a local computer system is called what?  


ANSWER: DOWNLOADING  


## BONUS  


2. COMPUTER SCIENCE Short Answer What is the term used for data associated with web page content and design but which doesn't show up visibly?  


ANSWER: METADATA
## TOSS-UP  


3. EARTH SCIENCE Multiple Choice A stream that is supplied with excessive amounts of sediment is  


W) meandering 
X) braided 
Y) broad and swiftly flowing 
Z) none of the above  


ANSWER: X) BRAIDED  


## BONUS  


3. EARTH SCIENCE Short Answer What is the term for a mineral that contains enough of an element to make mining and separation profitable?  


ANSWER: ORE  


## TOSS-UP  


4. MATH Multiple Choice To estimate a value of a function beyond the values already known, especially by the extension of a curve, is called  


W) extrapolation 
X) interpolation 
Y) extermination 
Z) internation  


ANSWER: W) EXTRAPOLATION  


## BONUS  


4. MATH Short Answer Applying Descartes' rule of signs to the polynomial \(x^{3} + x^{2} - x - 1\) , indicates that there are how many positive roots?  


ANSWER: ONE
## TOSS-UP  


5. PHYSICS Multiple Choice If a net torque is applied to an object, that object will experience:  


W) a constant angular velocity X) an angular acceleration Y) a constant moment of inertia Z) an increasing moment of inertia  


ANSWER: X) AN ANGULAR ACCELERATION  


## BONUS  


5. PHYSICS Multiple Choice A dipole placed in a uniform electric field can experience  


W) an acceleration X) a net flux Y) a net force Z) a torque  


ANSWER: Z) A TORQUE  


## TOSS-UP  


6. CHEMISTRY Short Answer The scientific term for disorder is  


ANSWER: ENTROPY  


## BONUS  


6. CHEMISTRY Multiple Choice The atomic orbital that approaches closest to the nucleus is  


W) 5s X) 5p Y) 5d Z) 4d  


ANSWER: W) 5S
## TOSS-UP  


7. MATH Short Answer Find the inverse function for f of \(\mathrm{x} = 2\mathrm{x} + 5\) . ANSWER: (X-5)/2 (read as: QUANTITY X - 5 DIVIDED BY 2)  


## BONUS  


7. MATH Short Answer The 3rd century B. C. Greek Mathematician credited with the first axiomatic treatment of geometry was  


ANSWER: EUCLID (PRONOUNCED: YOU' - CLID)  


## TOSS-UP  


8. COMPUTER SCIENCE Multiple Choice A group of professional software developers who are responsible for testing and validating programs is  


W) programmers X) system analysts Y) software quality assurance team Z) development team  


ANSWER: Y) SOFTWARE QUALITY ASSURANCE TEAM  


## BONUS  


8. COMPUTER SCIENCE Short Answer What country is referred to by the domain name extension of .za (read as: dot z a)?  


ANSWER: SOUTH AFRICA  


## TOSS-UP  


9. GENERAL SCIENCE Short Answer What is the term for the scientific study of poisons?  


ANSWER: TOXICOLOGY  


## BONUS  


9. GENERAL SCIENCE Short Answer What is the name for the study of friction, lubrication, and lubricants?  


ANSWER: TRIBOLOGY
## TOSS-UP  


10. EARTH SCIENCE Multiple Choice In a river, the finer sediments make up the  


W) suspended load 
X) discharge load 
Y) bed load 
Z) meander load  


ANSWER: W) SUSPENDED LOAD  


## BONUS  


10. EARTH SCIENCE Multiple Choice The half-life of carbon 14 is  


W) less than 6,000 years 
X) about 1 million years 
Y) 704 million years 
Z) more than 4.5 billion years  


ANSWER: W) LESS THAN 6,000 YEARS  


## TOSS-UP  


11. CHEMISTRY Short Answer The energy required to melt a solid at its melting point is called  


ANSWER: (LATENT) HEAT OF FUSION  


## BONUS  


11. CHEMISTRY Multiple Choice Which of the following is an exothermic process?  


W) Ice melts 
X) A kettle full of water boils 
Y) Water decomposes into \(\mathrm{H}_2\) and \(\mathrm{O}_2\) Z) "Dew" condenses on the grass  


ANSWER: Z) "DEW" CONDENSES ON THE GRASS
## TOSS-UP  


12. PHYSICS Multiple Choice Of the nine known planets in our solar system, the innermost is Mercury. When compared to the other planets in the system, Mercury has the:  


W) greatest centripetal acceleration X) greatest period of revolution Y) smallest angular velocity Z) smallest tangential velocity  


ANSWER: W) GREATEST CENTRIPETAL ACCELERATION  


## BONUS  


12. PHYSICS Multiple Choice The maximum value for the displacement of a harmonic oscillator is called the  


W) frequency 
X) period 
Y) wavelength 
Z) amplitude  


ANSWER: Z) AMPLITUDE  


## TOSS-UP  


13. GENERAL SCIENCE Short Answer What type of high cloud is composed entirely of ice crystals and is typically thin and wispy in appearance?  


ANSWER: CIRRUS  


## BONUS  


13. GENERAL SCIENCE Short Answer To obtain fathoms, one would divide feet by what number?  


ANSWER: 6
## TOSS-UP  


14. MATH Short Answer The axiom or theorem of a particular formal system that establishes a hierarchical order of a given pair of operators such as a x (b + c) = (a x b) + (a x c) is called  


ANSWER: DISTRIBUTIVE LAW  


## BONUS  


14. MATH Short Answer If the odds of an event occurring are 5 to 2, what is the probability of the event occurring?  


ANSWER: 5/7 (or 71.4%)  


## TOSS-UP  


15. CHEMISTRY Short Answer A solid which separates from a solution is called  


ANSWER: PRECIPITATE  


## BONUS  


15. CHEMISTRY Multiple Choice When a homogeneous mixture is formed from gaseous \(\mathrm{CO_2}\) and water, the resulting liquid is called a  


W) melt X) solvent Y) solute Z) solution  


ANSWER: Z) SOLUTION  


## TOSS-UP  


16. BIOLOGY Short Answer The period during which both the atria and the ventricles are relaxed is called  


ANSWER: DIASTOLE (DI- YAH'- STOW- LE)  


## BONUS  


16. BIOLOGY Short Answer The enzyme secreted by the kidney that causes an increase in blood pressure is called  


ANSWER: RENIN
## TOSS-UP  


17. PHYSICS Multiple Choice Heat is  


W) measured in degrees 
X) a form of energy 
Y) temperature 
Z) equivalent to force  


ANSWER: X) A FORM OF ENERGY  


## BONUS  


17. PHYSICS Multiple Choice The path of a charged particle moving parallel to a uniform magnetic field will be  


W) straight line 
X) circle 
Y) ellipse 
Z) parabola  


ANSWER: W) STRAIGHT LINE  


## TOSS-UP  


18. CHEMISTRY Multiple Choice The effective nuclear charge for an atom is less than the actual nuclear charge due to  


W) shielding 
X) penetration 
Y) paramagnetism 
Z) electron-pair repulsion  


ANSWER: W) SHIELDING  


## BONUS  


18. CHEMISTRY Multiple Choice Upon intense heating, a thermoset polymer is likely to  


W) deform 
X) melt 
Y) burn 
Z) fracture  


ANSWER: Y) BURN
## TOSS-UP  


19. GENERAL SCIENCE Short Answer What is the name for the process of separating metal from its ore by heating the ore to a high temperature in the presence of a reducing agent and a fluxing agent?  


ANSWER: SMELTING  


## BONUS  


19. GENERAL SCIENCE Multiple Choice Absolute zero is equivalent to:  


W) 0 degrees Kelvin  X) -400 degrees Fahrenheit  Y) -100 degrees Celsius  Z) all of the above  


ANSWER: W) 0 DEGREES KELVIN  


## TOSS-UP  


20. MATH Multiple Choice Given that numbers \(p\) and \(q\) are both irrational, what can be said about the sum of the two?  


W) Always rational  X) Always irrational  Y) Could be either rational or irrational  Z) Part rational and part irrational  


ANSWER: Y) COULD BE EITHER RATIONAL OR IRRATIONAL  


## BONUS  


20. MATH Short Answer An elevator can hold the weight of 8 adults or 12 children. How many children can ride on the elevator with 6 adults?  


ANSWER: 3
## TOSS-UP  


21. CHEMISTRY Multiple Choice The following substance with a Lewis structure that does not obey the octet rule is  


W) BCl3 
X) PH3 
Y) SO3 
Z) ClO3-  


ANSWER: W) BCl3  


## BONUS  


21. CHEMISTRY Short Answer What subatomic particle has the greatest charge to mass ratio?  


ANSWER: ELECTRON  


## TOSS-UP  


22. ASTRONOMY Short Answer The tilt of the Earth's axis leads to what effect on the Earth?  


ANSWER: SEASONS (ALSO ACCEPT: PRECESSION)  


## BONUS  


22. ASTRONOMY Short Answer Which two planets have no natural satellites?  


ANSWER: MERCURY AND VENUS  


## TOSS-UP  


23. BIOLOGY Short Answer What do we call substances that endocrine glands produce?  


ANSWER: HORMONES  


## BONUS  


23. BIOLOGY Multiple Choice The function of the alveoli is  


W) air storage 
X) blood production 
Y) gas exchange 
Z) oxygen production  


ANSWER: Y) GAS EXCHANGE
## TOSS-UP  


24. EARTH SCIENCE Short Answer What scale is a rating system used to describe the concentration of hydrogen ions in a solution?  


ANSWER: PH SCALE  


## BONUS  


24. EARTH SCIENCE Multiple Choice All of the following are formed by deposition EXCEPT:  


W) sea stack 
X) beach 
Y) sandbar 
Z) spit  


ANSWER: W) SEA STACK  


## TOSS-UP  


25. PHYSICS Short Answer Three 4.0 Ohm resistors are connected in parallel to a 12.0 volt battery. What is the current in any one of the resistors?  


ANSWER: 3.0 AMPS  


## BONUS  


25. PHYSICS Multiple Choice A man pulls a sled at a constant velocity across a horizontal snow surface. If a force of 80 Newtons is being applied to the sled rope at an angle of 53 degrees to the ground, what is the force of friction between sled and snow?  


W) 80 Newtons 
X) 64 Newtons 
Y) 48 Newtons 
Z) 40 Newtons  


ANSWER: Y) 48 Newtons
## ROUND 2 A  


## TOSS-UP  


1. BIOLOGY Short Answer Diatoms have shells that are made of what material?  


ANSWER: SILICA (ACCEPT: \(\mathrm{SiO}_2\) OR SILICON DIOXIDE)  


## BONUS  


1. BIOLOGY Multiple Choice In valvular stenosis, the term "stenosis" means  


W) contraction X) narrowing Y) pause Z) relaxation  


ANSWER: X) NARROWING  


## TOSS-UP  


2. MATH Short Answer Using radian measure, the cosine of \(\pi\) (read: pi) is ANSWER: -1  


## BONUS  


2. MATH Multiple Choice Find the value of the summation from \(i = 1\) to 5 of the expression \(i^2\) .  


W) 25 X) 45 Y) 55 Z) 65  


ANSWER: Y) 55
## TOSS-UP  


3. GENERAL SCIENCE Short Answer What is the term for the day (or the instant) that the Sun's ecliptic path is at its greatest northern or southern declination?  


ANSWER: SOLSTICE  


## BONUS  


3. GENERAL SCIENCE Short Answer What is the name for a strong, steel vessel used for carrying out chemical reactions and sterilizations at high temperature and pressure?  


ANSWER: AUTOCLAVE  


## TOSS-UP  


4. EARTH SCIENCE Multiple Choice During the time it takes a low-pressure system to pass over an area, air pressure usually  


W) remains the same 
X) falls and then rises 
Y) rises and then falls 
Z) continually rises  


ANSWER: X) FALLS AND THEN RISES  


## BONUS  


4. EARTH SCIENCE Multiple Choice Which of the following sand dunes has a crescent shape?  


W) Barchan ("BAR-can") 
X) Transverse 
Y) Star dune 
Z) Longitudinal  


ANSWER: W) BARCHAN
## TOSS-UP  


5. MATH Multiple Choice An identity matrix is a square matrix in which  


W) every entry is 1 
X) all entries on the main diagonal are 1 
Y) all entries below the diagonal are 1 
Z) all entries on the diagonal are 1 and all other entries are 0  


ANSWER: Z) ALL ENTRIES ON THE DIAGONAL ARE 1 AND ALL OTHER ENTRIES ARE 0  


## BONUS  


5. MATH Multiple Choice Find the positive x-intercept of the ellipse \(4x^{2} + 9y^{2} = 36\)  


W) 3 
X) 6 
Y) 9 
Z) 2  


ANSWER: W) 3  


## TOSS-UP  


6. CHEMISTRY Multiple Choice Robert Boyle measured the volume of air at many pressures. After many trials he observed that the volume of a gas is inversely proportional to its pressure. This statement is  


W) a datum 
X) a hypothesis 
Y) a law 
Z) a theory  


ANSWER: Y) A LAW  


## BONUS  


6. CHEMISTRY Multiple Choice A bond that is formed by end-to-end overlap of atomic orbitals is a  


W) sigma bond 
X) pi bond 
Y) ionic bond 
Z) resonance bond  


ANSWER: W) SIGMA BOND
## TOSS-UP  


7. EARTH SCIENCE Short Answer What is the name of a continent believed to have been made up of lands that are known today as Africa, South America, Australia, Antarctica, and India?  


ANSWER: GONDWANALAND  


## BONUS  


7. EARTH SCIENCE Multiple Choice Burning of coal adds to the acid rain problem mainly by  


W) raising the water content of air  X) increasing the air temperature  Y) releasing carbon dioxide into the atmosphere  Z) releasing sulfur into the atmosphere  


ANSWER: Z) RELEASING SULFUR INTO THE ATMOSPHERE  


## TOSS-UP  


8. CHEMISTRY Multiple Choice The most common isotope of hydrogen has  


W) 1 neutron and 1 electron.  X) 1 proton and 1 electron.  Y) 1 proton, 1 neutron, and 1 electron.  Z) 2 protons and 2 electrons.  


ANSWER: X) 1 PROTON AND 1 ELECTRON  


## BONUS  


8. CHEMISTRY Short Answer The elements Flourine, Chlorine, Bromine, Iodine, and Antimony are called  


ANSWER: HALOGENS
## TOSS-UP  


9. ASTRONOMY Multiple Choice The Andromeda galaxy is most useful to study because  


W) it is a spiral galaxy like ours 
X) it is the closest elliptical galaxy 
Y) it is undergoing a huge collision 
Z) it is a large irregular galaxy  


ANSWER: W) IT IS A SPIRAL GALAXY LIKE OURS  


## BONUS  


9. ASTRONOMY Short Answer What periodic celestial visitors may be described as "dirty snowballs"?  


ANSWER: COMETS  


## TOSS-UP  


10. COMPUTER SCIENCE Short Answer What type of computer monitor has a single color phosphor, usually white.  


ANSWER: MONOCHROME (ALSO ACCEPT MONOCHROMATIC)  


## BONUS  


10. COMPUTER SCIENCE Short Answer On a spreadsheet, a cell reference in a formula that is intended to stay fixed or unchanged even when the formula is replicated to another location is called what?  


ANSWER: ABSOLUTE CELL REFERENCE  


## TOSS-UP  


11. BIOLOGY Short Answer Glucagon, (pronounced: "glue' ka gone") a hormone, is secreted by what organ?  


ANSWER: PANCREAS  


## BONUS  


11. BIOLOGY Short Answer Chromosomes that are not identified as sex chromosomes are called:  


ANSWER: AUTOSOMES
## TOSS-UP  


12. CHEMISTRY Short Answer What is the ratio between the density of a substance and the density of water called?  


ANSWER: SPECIFIC GRAVITY  


## BONUS  


12. CHEMISTRY Multiple Choice Which one of the following pairs of dispersed phases and dispersing media can never form a colloid?  


W) solid and gas 
X) liquid and gas 
Y) liquid and liquid 
Z) gas and gas  


ANSWER: Z) GAS AND GAS  


## TOSS-UP  


13. ASTRONOMY Multiple Choice Planetary rings are  


W) solid sheets 
X) streams of gas 
Y) orbiting swarms of particles 
Z) liquid  


ANSWER: Y) ORBITING SWARMS OF PARTICLES  


## BONUS  


13. ASTRONOMY Multiple Choice Antarctica is a good place to search for meteorites because:  


W) It is a relatively uncontaminated environment 
X) There is no other source of rocks 
Y) Weathering is very slow 
Z) all of the above  


ANSWER: Z) ALL OF THE ABOVE
## TOSS-UP  


14. PHYSICS Short Answer Replacing a wire resistor with another of the same material and length but with three times the diameter will have the effect of changing the resistance by what factor?ANSWER: NINE TIMES LESS OR 1/9 (ONE-NINETH)  


ANSWER: NINE TIMES LESS OR 1/9 (ONE- NINETH)  


## BONUS  


14. PHYSICS Multiple Choice A figure skater with arms initially extended starts spinning on the ice at 3 revolutions per second. She then pulls her arms close to her body. Which of the following results?  


W) a smaller rotational rate X) a greater rotational rate Y) a greater angular momentum Z) a smaller angular momentum  


ANSWER: X) A GREATER ROTATIONAL RATE  


## TOSS-UP  


15. EARTH SCIENCE Multiple Choice An earthquake-related hazard of lands reclaimed from the sea is  


W) fissures X) liquefaction Y) landslides Z) sinkhole development  


ANSWER: X) LIQUEFACTION  


## BONUS  


15. EARTH SCIENCE Short Answer What mineral is a principal source of iron?  


ANSWER: HEMATITE
## TOSS-UP  


16. GENERAL SCIENCE Multiple Choice Petroleum is a liquid consisting primarily of  


W) hydrocarbon compounds 
X) nitrogen 
Y) sulfur 
Z) oxygen  


ANSWER: W) HYDROCARBON COMPOUNDS  


## BONUS  


16. GENERAL SCIENCE Short Answer SI units are associated with the metric system. For what does SI stand?  


ANSWER: INTERNATIONAL SYSTEM (ACCEPT: SYSTEM INTERNATIONALE)  


## TOSS-UP  


17. ASTRONOMY Multiple Choice All of the planets rotate in the same direction as they orbit except  


W) Mercury 
X) Venus 
Y) Earth 
Z) Mars  


ANSWER: X) VENUS  


## BONUS  


17. ASTRONOMY Multiple Choice Newton stated that if a force is applied to an object in space, the resultant acceleration depends upon  


W) the size of the object 
X) the initial position of the object 
Y) the initial speed of the object 
Z) the mass of the object  


ANSWER: Z) THE MASS OF THE OBJECT
## TOSS-UP  


18. PHYSICS Multiple Choice Which state of matter is associated with the very highest of temperatures?  


W) liquid 
X) plasma 
Y) gas 
Z) solid  


ANSWER: X) PLASMA  


## BONUS  


18. PHYSICS Multiple Choice The quantity of work equal to one joule is also equivalent to which of the following?  


W) Watt 
X) Watts per second 
Y) Watts times seconds 
Z) Watts per second squared  


ANSWER: Y) WATTS TIMES SECONDS  


## TOSS-UP  


19. CHEMISTRY Multiple Choice In the periodic table, the metalloids are found  


W) vertically to the far left hand side 
X) vertically to the far right hand side 
Y) horizontally below the main body 
Z) diagonally just right of the center  


ANSWER: Z) DIAGONALLY JUST RIGHT OF THE CENTER  


## BONUS  


19. CHEMISTRY Short Answer Who proposed that electrons in an atom could have only certain energies?  


ANSWER: BOHR (ACCEPT NIELS BOHR)
## TOSS-UP  


20. COMPUTER SCIENCE Multiple Choice A computer network that is restricted to a limited geographical area and usually maintained by a single organization is called a:  


W) WAN (pron: wan) 
X) Internet 
Y) LAN (pron: lan) 
Z) none of the above  


ANSWER: Y) LAN  


## BONUS  


20. COMPUTER SCIENCE Short Answer On a network, the transferring of files from a local computer system to a remote host is called what?  


ANSWER: UPLOADING  


## TOSS-UP  


21. PHYSICS Short Answer What is the temperature (in Kelvin) of a system in thermal equilibrium with another system made up of ice and water at one atmosphere of pressure?  


ANSWER: 273 (DEGREES KELVIN) (ACCEPT 273.15)  


## BONUS  


21. PHYSICS Multiple Choice The magnetic domains in a non magnetized piece of iron are characterized by which orientation?  


W) parallel to the magnetic axis 
X) anti-parallel to the magnetic axis 
Y) random 
Z) perpendicular to the magnetic axis  


ANSWER: Y) RANDOM
## TOSS-UP  


22. COMPUTER SCIENCE Short Answer How many nibbles are there in a byte?  


ANSWER: 2  


## BONUS  


22. COMPUTER SCIENCE Multiple Choice A large wide area network created in the 1960s for the exchange of information between universities and research organizations was:  


W) MILNET (pron: MIL - NET) 
X) ARP (pron: A - R - P) 
Y) CGI (pron: C - G - I) 
Z) ARPANET (pron: ARPA - NET)  


ANSWER: Z) ARPANET  


## TOSS-UP  


23. PHYSICS Short Answer You measure a 25 Volt potential difference across a 5 Ohm resistor. What is the current flowing through it in amperes?  


ANSWER: 5  


## BONUS  


23. PHYSICS Multiple Choice For an ideal gas of a given mass, if the pressure remains the same and volume increases, the average kinetic energy of the molecules  


W) decreases 
X) stays the same 
Y) increases 
Z) not enough information  


ANSWER: Y) INCREASES
## TOSS-UP  


24. ASTRONOMY Multiple Choice The surface temperature of the Sun is approximately  


W) 60 K 
X) 6000 K 
Y) 6 million K 
Z) 60 million K  


ANSWER: X) 6000 K  


## BONUS  


24. ASTRONOMY Multiple Choice The Hubble Law is a relationship between galaxies'  


W) Redshifts and colors 
X) Distances and redshifts 
Y) Redshifts and spectral types 
Z) Colors and spectral types  


ANSWER: X) DISTANCES AND REDSHIFTS  


## TOSS-UP  


25. GENERAL SCIENCE Short Answer Which Greek letter symbolizes wavelength, decay constant, or thermal conductivity?  


ANSWER: LAMBDA  


## BONUS  


25. GENERAL SCIENCE Short Answer What is the term for the line on a map or chart joining points or places of equal temperature?  


ANSWER: ISOTHERM
## ROUND 3 A  


## TOSS-UP  


1. CHEMISTRY Multiple Choice The compound \(\mathrm{NH_3}\) (ammonia) is best classified as a  


W) strong acid 
X) strong base 
Y) weak acid 
Z) weak base  


ANSWER: Z) WEAK BASE  


## BONUS  


1. CHEMISTRY Multiple Choice The compound \(\mathrm{CH_3OH}\) , methyl alcohol, is best classified as a  


W) acid 
X) base 
Y) salt 
Z) nonelectrolyte  


ANSWER: Z) NONELECTROLYTE  


## TOSS-UP  


2. BIOLOGY Multiple Choice The chemical character of each individual amino acid is determined by  


W) the properties of the side chains 
X) whether or not the amino acid contains a carboxyl group. 
Y) whether or not the amino acid contains an amino group. 
Z) whether or not the amino acid contains a benzene ring.  


ANSWER: W) THE PROPERTIES OF THE SIDE CHAINS  


## BONUS  


2. BIOLOGY Short Answer What brain structure is the major mediator of information between the brain and the endocrine system?  


ANSWER: HYPOTHALAMUS
## TOSS-UP  


3. CHEMISTRY Multiple Choice Upon heating, a thermoplastic polymer is likely to  


W) maintain a relatively steady temperature 
X) melt 
Y) explode 
Z) splinter  


ANSWER: X) MELT  


## BONUS  


3. CHEMISTRY Short Answer A system delivers 225 Joules of heat to the surroundings while delivering 645 Joules of work. Calculate the change in the internal energy of the system.  


ANSWER: - 870 JOULES (ACCEPT: 870 JOULES LESS)  


## TOSS-UP  


4. BIOLOGY Multiple Choice The two major chemical components of the plasma membrane are  


W) carbohydrate and nucleic acid 
X) protein and water 
Y) carbohydrate and lipid 
Z) phospholipid and protein  


ANSWER: Z) PHOSPHOLIPID AND PROTEIN  


## BONUS  


4. BIOLOGY Short Answer The excretory organ in the earthworm is called the  


ANSWER: NEPHRIDIUM
## TOSS-UP  


5. PHYSICS Short Answer Which type of quantity is characterized by both magnitude and direction?  


ANSWER: VECTOR  


## BONUS  


5. PHYSICS Multiple Choice The current in a long wire creates a magnetic field in the region around the wire. How is the strength of the field related to the distance r from the wire center?  


W) field directly proportional to r X) field inversely proportional to r Y) field directly proportional to \(\mathrm{r}^2\) Z) field inversely proportional to \(\mathrm{r}^2\)  


ANSWER: X) FIELD INVERSELY PROPORTIONAL TO R  


## TOSS-UP  


6. BIOLOGY Short Answer From the interior to the exterior of the cell following an action potential, the almost immediate restoration of the resting potential of the neuron is accomplished by the out-flux of which ions?  


ANSWER: POTASSIUM  


## BONUS  


6. BIOLOGY Short Answer Diabetes Insipidus, unlike Diabetes Mellitus, is a rare disease caused by a lack of what hormone?  


ANSWER: ADH (ACCEPT: ANTIDIURETIC HORMONE)
## TOSS-UP  


7. ASTRONOMY Multiple Choice Measurements of stellar parallax allow us to directly determine a star's  


W) mass 
X) diameter 
Y) temperature 
Z) distance  


ANSWER: Z) DISTANCE  


## BONUS  


7. ASTRONOMY Multiple Choice Stars which have ejected a planetary nebula go on to become  


W) protostars 
X) supernovae 
Y) red giants 
Z) white dwarfs  


ANSWER: Z) WHITE DWARFS  


## TOSS-UP  


8. COMPUTER SCIENCE Multiple Choice A region of memory reserved to hold data that is waiting to be transferred is called a  


W) applet 
X) port 
Y) memory bank 
Z) buffer  


ANSWER: Z) BUFFER  


## BONUS  


8. COMPUTER SCIENCE Short Answer You are transmitting information at 300 baud. This means your sending at what rate?  


ANSWER: 300 BITS PER SECOND
## TOSS-UP  


9. CHEMISTRY Multiple Choice The shape of an atomic orbital is associated with  


W) the principal quantum number 
X) the angular momentum quantum number 
Y) the magnetic quantum number 
Z) the spin quantum number  


ANSWER: X) THE ANGULAR MOMENTUM QUANTUM NUMBER  


## BONUS  


9. CHEMISTRY Multiple Choice Most biochemical reactions occur in the pH range of  


W) 4 to 5 
X) 6 to 8 
Y) 9 to 11 
Z) 12 to 14  


ANSWER: X) 6 TO 8  


## TOSS-UP  


10. PHYSICS Short Answer Which form of energy is associated with an object's location in a conservative force field?  


ANSWER: POTENTIAL ENERGY  


## BONUS  


10. PHYSICS Multiple Choice Between 0 degrees and 4 degrees C, the volume coefficient of expansion for water  


W) is positive 
X) is zero 
Y) is becoming less dense 
Z) is negative  


ANSWER: Z) IS NEGATIVE
## TOSS-UP  


11. CHEMISTRY Multiple Choice Select the element with the smallest first ionization energy  


W) Rubidium 
X) Magnesium 
Y) Iodine 
Z) Arsenic  


ANSWER: W) RUBIDIUM  


## BONUS  


11. CHEMISTRY Short Answer What law states that the pressure of an ideal gas is directly proportional to its absolute temperature at constant volume and number of moles?  


ANSWER: AMONTON'S LAW  


## TOSS-UP  


12. COMPUTER SCIENCE Multiple Choice The batch file containing commands that are automatically carried out by the MS-DOS operating system when the computer is started is called  


W) AutoPlay 
X) AUTOEXEC.BAT 
Y) Starting Point 
Z) Startup.exe  


ANSWER: X) AUTOEXEC.BAT  


## BONUS  


12. COMPUTER SCIENCE Multiple Choice What is the set of technologies that enables software components to interact with one another in a networked environment, regardless of the language in which the components are created?  


W) ADSL 
X) ActiveX 
Y) ANALYSIS 
Z) Archie  


ANSWER: X) ACTIVE X
## TOSS-UP  


13. BIOLOGY Short Answer In plants, the amyloplast is a type of plastid that contains what?  


ANSWER: STARCH  


## BONUS  


13. BIOLOGY Multiple Choice Eukaryotes  


W) include bacteria and blue-green algaeX) do not include multicellular organismsY) have a nuclear membraneZ) lack membrane-bound cytoplasmic organelles  


ANSWER: Y) HAVE A NUCLEAR MEMBRANE  


## TOSS-UP  


14. PHYSICS Multiple Choice The quantity "stress" expressed in terms of the fundamental quantities (mass, length, time) is equivalent to  


W) MLT-1 (read as: M L T to the minus one power) 
X) ML-1T-2 (read as: M L to the minus one power T to the minus two power) 
Y) M2L-1T-3 (read as: M to the second L to the minus one power T to the minus three power) 
Z) a dimensionless quantity  


ANSWER: X) ML-1T-2 (read as: M L to the minus one power T to the minus two power)  


## BONUS  


14. PHYSICS Multiple Choice The quantity "strain" expressed in terms of the fundamental quantities (mass, length, time) is equivalent to:  


W) MLT-1 (read as: M L T to the minus one power) 
X) ML-1T-2 (read as: M L to the minus one power T to the minus two power) 
Y) M2L-1T-3 (read as: M to the second L to the minus one power T to the minus three power) 
Z) a dimensionless quantity  


ANSWER: Z) A DIMENSIONLESS QUANTITY
## TOSS-UP  


15. CHEMISTRY Multiple Choice One property that decreases as the intermolecular forces increase is  


W) boiling point 
X) equilibrium vapor pressure 
Y) viscosity 
Z) heat of vaporization  


ANSWER: X) EQUILIBRIUM VAPOR PRESSURE  


## BONUS  


15. CHEMISTRY Multiple Choice A bond that is the second bond formed between two atoms is a  


W) sigma bond 
X) pi bond 
Y) ionic bond 
Z) resonance bond  


ANSWER: X) PI BOND  


## TOSS-UP  


16. ASTRONOMY Short Answer Who was the first human to set foot on the moon?  


ANSWER: (NEIL) ARMSTRONG  


## BONUS  


16. ASTRONOMY Multiple Choice Not long after the death of Nicholas Copernicus, a Danish nobleman used giant instruments to make observations of the planets motions with unprecedented accuracy. This astronomer was  


W) Galileo Galilei 
X) Johannes Kepler 
Y) Isaac Newton 
Z) Tycho Brahe (PRONOUCE: TIE-KOH BRAY)  


ANSWER: Z) TYCHO BRAHE
## TOSS-UP  


17. PHYSICS Multiple Choice When current is flowing in a superconductor, which statement is not true?  


W) A battery keeps the current going. 
X) Electrical charges are moving. 
Y) The resistance is zero. 
Z) No power is given off in the form of heat  


ANSWER: W) A BATTERY KEEPS THE CURRENT GOING.  


## BONUS  


17. PHYSICS Short Answer What is the equivalent resistance of a 22, a 40, and a 32 ohm resistor connected in series?  


ANSWER: 94 OHMS  


## TOSS-UP  


18. BIOLOGY Multiple Choice A circadian rhythm is a cycle that occurs with what frequency?  


W) 60 minutes 
X) 2-hours 
Y) 12-hours 
Z) 24-hours  


ANSWER: Z) 24- HOURS  


## BONUS  


18. BIOLOGY Multiple Choice The endocardium of the heart  


W) contracts to develop a force 
X) is part of the conduction system 
Y) lines the inside of the chambers 
Z) prevents the backflow of blood  


ANSWER: Y) LINES THE INSIDE OF THE CHAMBERS
## TOSS-UP  


19. ASTRONOMY Multiple Choice The production of a planet's magnetic field requires  


W) a large planetary mass 
X) at least one moon 
Y) an atmosphere 
Z) rotation of the planet  


ANSWER: Z) ROTATION OF THE PLANET  


## BONUS  


19. ASTRONOMY Short Answer What brilliant display results as Earth passes directly through the path of a present or former comet?  


ANSWER: METEOR SHOWER (ALSO ACCEPT: METEORS AND METEOR STORM)  


## TOSS-UP  


20. MATH Multiple Choice A definite integral with one or both limits of integration being infinite is called  


W) improper integral 
X) indefinite integral 
Y) implicit integral 
Z) incident integral  


ANSWER: W) IMPROPER INTEGRAL  


## BONUS  


20. MATH Short Answer The perimeter of a rectangle is 28 centimeters. The length of one side is 8 centimeters. What is the length of the diagonal in centimeters?  


ANSWER: 10 CENTIMETERS
## TOSS-UP  


21. EARTH SCIENCE Short Answer What is the term for an area of rock or soil where pores are completely filled by groundwater?  


ANSWER: ZONE OF SATURATION  


## BONUS  


21. EARTH SCIENCE Multiple Choice The Andes Mountains of South America were formed at what kind of plate boundary?  


W) convergent 
X) divergent 
Y) hot spot 
Z) transform  


ANSWER: W) CONVERGENT  


## TOSS-UP  


22. PHYSICS Short Answer What term refers to the angle between directions to true north and magnetic north?  


ANSWER: MAGNETIC DECLINATION  


## BONUS  


22. PHYSICS Multiple Choice If heat is flowing from a table to a block of ice moving across the table, which of the following must be true?  


W) The table is cooler than the ice 
X) The ice is cooler than the table 
Y) The ice is changing phase 
Z) The ice is less massive than the table  


ANSWER: X) THE ICE IS COOLER THAN THE TABLE
## TOSS-UP  


23. MATH Short Answer A set of points that is contained on a single line is said to be  


ANSWER: COLLINEAR  


## BONUS  


23. MATH Short Answer A square circumscribes a circle of radius 1. What is the ratio of the area of the circle to the area of the square?ANSWER: \(\pi \left[ \begin{array}{l}4 \end{array} \right]\) (read: pi divided by 4)  


ANSWER: \(\pi \left[ \begin{array}{l}4 \end{array} \right]\) (read: pi divided by 4).  


## TOSS-UP  


24. CHEMISTRY Short Answer The most electronegative of the halogens is  


ANSWER: FLUORINE  


## BONUS  


24. CHEMISTRY Short Answer Who is credited with measuring the mass per charge ratio of the electron?ANSWER: THOMSON (ACCEPT J. J. THOMSON)  


ANSWER: THOMSON (ACCEPT J. J. THOMSON)  


## TOSS-UP  


25. EARTH SCIENCE Short Answer On a topographic map, what is the term for the vertical distance in elevation between one contour line and the next?ANSWER: CONTOUR INTERVAL  


ANSWER: CONTOUR INTERVAL  


## BONUS  


25. EARTH SCIENCE Multiple Choice If an ice block in a glacial outwash plain melts, which of the following is formed?  


W) pothole 
X) kettlehole 
Y) sinkhole 
Z) borehole  


ANSWER: X) KETTLEHOLE
## ROUND 4 A  


## TOSS-UP  


1. BIOLOGY Multiple Choice A molecule that relays the message inside the cell when a hormone attaches to the cell's surface is called a  


W) chaperon 
X) neurotransmitters 
Y) interleukin 
Z) second messenger  


ANSWER: Z) SECOND MESSENGER  


## BONUS  


1. BIOLOGY Multiple Choice An enzyme inhibitor whose method of action has to do with its size and shape is known as a  


W) allosteric inhibitor 
X) steric inhibitor 
Y) competitive inhibitor 
Z) non-competitive inhibitor  


ANSWER: X) STERIC INHIBITOR  


## TOSS-UP  


2. CHEMISTRY Multiple Choice The identity of an element is determined by  


W) the number of protons in its nucleus 
X) its atomic mass 
Y) the number of neutrons in its nucleus 
Z) the density of the solid  


ANSWER: W) THE NUMBER OF PROTONS IN ITS NUCLEUS  


## BONUS  


2. CHEMISTRY Multiple Choice Which of the following gases effuses most rapidly?  


W) nitrogen 
X) oxygen 
Y) hydrogen chloride 
Z) ammonia  


ANSWER: Z) AMMONIA
## TOSS-UP  


3. PHYSICS Short Answer The term for a substance that transmits no light is termed  


ANSWER: OPAQUE  


## BONUS  


3. PHYSICS Multiple Choice A steel plate has a hole drilled through it. The plate is put into a furnace and heated. What happens to the size of the inside diameter of a hole as the temperature increases?  


W) increases 
X) decreases 
Y) remains constant 
Z) becomes elliptical  


ANSWER: W) INCREASES  


## TOSS-UP  


4. BIOLOGY Short Answer The small channels that plant cells have through which molecules can pass from one cell to its neighbor are called:  


ANSWER: PLASMODESMATA  


## BONUS  


4. BIOLOGY Multiple Choice Diffusion between two flows that move in opposite directions is called  


W) directional exchange 
X) binary movement 
Y) countercurrent exchange 
Z) evaporative cooling  


ANSWER: Y) COUNTERCURRENT EXCHANGE
## TOSS-UP  


5. ASTRONOMY Multiple Choice Which of the following is located nearest to the Earth?  


W) Sun X) center of the Milky Way galaxy Y) quasars Z) Andromeda galaxy  


ANSWER: W) SUN  


## BONUS  


5. ASTRONOMY Multiple Choice Before becoming a neutron star, the star may experience a giant explosion called  


W) helium flash 
X) nova 
Y) supernova 
Z) the Big Bang  


ANSWER: Y) SUPERNOVA  


## TOSS-UP  


6. GENERAL SCIENCE Short Answer What is the other name for the Spring equinox that occurs around March 21?  


ANSWER: VERNAL (EQUINOX)  


## BONUS  


6. GENERAL SCIENCE Multiple Choice A 30 decibel sound is how many times louder than a 10 decibel sound?  


W) 3 times 
X) 2 times 
Y) 100 times 
Z) 20 times  


ANSWER: Y) 100 TIMES
## TOSS-UP  


7. MATH Short Answer The base-ten numeral 11 is written in hexadecimal notation as  


ANSWER: B  


## BONUS  


7. MATH Multiple Choice If the first derivative of a function at a point is zero, and the second derivative is negative, then the point is a  


W) local minimum 
X) inflection point 
Y) discontinuity 
Z) local maximum  


ANSWER: Z) LOCAL MAXIMUM  


## TOSS-UP  


8. COMPUTER SCIENCE Multiple Choice How many colors can GIF and JPG files support?  


W) GIF supports 256, JPG supports 512 
X) GIF supports 512, JPG supports 1.2 million 
Y) GIF supports 256, JPG supports 16.7 million 
Z) GIF supports 512, JPG supports 8.6 million  


ANSWER: Y) GIF SUPPORTS 256, JPG SUPPORTS 16.7 MILLION  


## BONUS  


8. COMPUTER SCIENCE Short Answer Information retrievals that are executed "on the fly" are called what type of database queries?  


ANSWER: AD HOC
## TOSS-UP  


9. EARTH SCIENCE Multiple Choice The cause of the mass extinctions at the end of the Paleozoic Era may have been caused by  


W) increased predators 
X) changes in the environment 
Y) the forming of coal beds 
Z) the evolution of reptiles  


ANSWER: X) CHANGES IN THE ENVIRONMENT  


## BONUS  


9. EARTH SCIENCE Multiple Choice A topography dominated by sinkholes and other features of rock dissolution is called  


W) residual 
X) lahar 
Y) klippe 
Z) karst  


ANSWER: Z) KARST  


## TOSS-UP  


10. COMPUTER SCIENCE Short Answer What does the acronym ASCII stands for?  


ANSWER: AMERICAN STANDARD CODE FOR INFORMATION INTERCHANGE  


## BONUS  


10. COMPUTER SCIENCE Multiple Choice Which one of the following is not a file format used to convert digital images into files for storage purposes?  


W) TIFF 
X) GIF 
Y) PICT 
Z) PCB  


ANSWER: PCB
## TOSS-UP  


11. ASTRONOMY Multiple Choice In the sixteenth century, Pope Gregory VIII ordered calendar reform to more precisely measure the leap year cycle. Therefore, the year 3000  


W) will be a leap year  X) will not be a leap year  Y) will cause clocks to stop  Z) will be skipped  


ANSWER: X) WILL NOT BE A LEAP YEAR  


## BONUS  


11. ASTRONOMY Multiple Choice From what do stars form?  


W) Globular clusters  X) Open clusters  Y) Planetary nebulas  Z) Interstellar clouds  


ANSWER: Z) INTERSTELLAR CLOUDS  


## TOSS-UP  


12. CHEMISTRY Multiple Choice Orbitals that have larger electron densities near the nucleus of the atom have  


W) angular momentum  X) penetration  Y) radial distribution  Z) constructive interference  


ANSWER: X) PENETRATION  


## BONUS  


12. CHEMISTRY Multiple Choice Which of the following oxides will give the most basic solution when dissolved in water?  


W) \(\mathrm{SO}_2\)  X) \(\mathrm{CO}_2\)  Y) \(\mathrm{K}_2\mathrm{O}\)  Z) \(\mathrm{P}_4\mathrm{O}_{10}\)  


ANSWER: Y) \(\mathrm{K}_2\mathrm{O}\)
## TOSS-UP  


13. BIOLOGY Multiple Choice An individual whose experiments finally disproved the theory of spontaneous generation was  


W) Aristotle 
X) Pasteur 
Y) Leeuwenhoek 
Z) Darwin  


ANSWER: X) PASTEUR  


## BONUS  


13. BIOLOGY Short Answer A glycerol molecule with two fatty acid tails and a phosphate group is called what?  


ANSWER: PHOSPHOLIPID  


## TOSS-UP  


14. GENERAL SCIENCE Short Answer What is the name for the middle section of an arthropod?  


ANSWER: THORAX  


## BONUS  


14. GENERAL SCIENCE Short Answer CFCs used in some refrigerants and solvents have been linked to depletion of the earth's protective ozone layer. What does CFC stand for?  


ANSWER: CHLOROFLUOROCARBONS
## TOSS-UP  


15. ASTRONOMY Multiple Choice The solid cores of Jupiter and Saturn are probably about the size of  


W) a small moon 
X) a large moon 
Y) the Earth 
Z) there are no solid cores  


ANSWER: Y) THE EARTH  


## BONUS  


15. ASTRONOMY Multiple Choice The observed differences in stellar spectra are caused primarily by differences in stellar  


W) chemical composition 
X) motion 
Y) location 
Z) temperature  


ANSWER: Z) TEMPERATURE  


## TOSS-UP  


16. COMPUTER SCIENCE Multiple Choice The data transfer capacity of a digital communications system is called  


W) baseband 
X) bandwidth 
Y) broadband 
Z) baseline  


ANSWER: X) BANDWIDTH  


## BONUS  


16. COMPUTER SCIENCE Multiple Choice A piece of information saved by your Web browser to a file on your disk that can be retrieved by a Web server that your browser accesses is called a  


W) comment 
X) cybertext 
Y) cookie 
Z) clickable text  


ANSWER: Y) COOKIE
## TOSS-UP  


17. BIOLOGY Multiple Choice Ligaments join  


W) bone to muscle 
X) bone to skin 
Y) bone to bone 
Z) muscle to connective tissue  


ANSWER: Y) BONE TO BONE  


## BONUS  


17. BIOLOGY Short Answer Prokaryotic cells often divide by the process of:  


ANSWER: BINARY FISSION (ACCEPT FISSION)  


## TOSS-UP  


18. GENERAL SCIENCE Short Answer What extremely abundant subatomic particles, previously believed to be massless, were found in 1998 to have mass?  


ANSWER: NEUTRINOS  


## BONUS  


18. GENERAL SCIENCE Multiple Choice One tablespoon, which is equivalent to three teaspoons, is also equivalent to  


W) 1/6 fluid ounce 
X) 1/2 fluid ounce 
Y) 1 fluid ounce 
Z) 2 fluid ounce  


ANSWER: X) 1/2 FLUID OUNCE  


## TOSS-UP  


19. COMPUTER SCIENCE Short Answer What was the first Web browser client program that employed a graphical user interface capable of supporting pages with multimedia components?  


ANSWER: MOSAIC  


## BONUS  


19. COMPUTER SCIENCE Short Answer Name two of the three primary types of lists that are available in HTML.  


ANSWER: ORDERED LISTS, UNORDERED LISTS, OR DEFINITION
## TOSS-UP  


20. EARTH SCIENCE Short Answer What fast-growing seaweed is harvested for food, iodine, and potassium?  


ANSWER: KELP  


## BONUS  


20. EARTH SCIENCE Multiple Choice The first location to feel the effects of an earthquake would be nearby  


W) a seismograph station 
X) the shadow zone 
Y) the epicenter 
Z) the equator  


ANSWER: Y) THE EPICENTER  


## TOSS-UP  


21. CHEMISTRY Short Answer The quantity of heat required to change the temperature of 1 gram of water by 1 degree Celsius is defined as its  


ANSWER: HEAT CAPACITY (ACCEPT: SPECIFIC HEAT)  


## BONUS  


21. CHEMISTRY Multiple Choice The orientation in space of an atomic orbital is associated with  


W) the principal quantum number 
X) the magnetic quantum number 
Y) the spin quantum number 
Z) the angular momentum quantum number  


ANSWER: X) THE MAGNETIC QUANTUM NUMBER
## TOSS-UP  


22. COMPUTER SCIENCE Short Answer What is the largest positive decimal value which can be represented by six binary digits?  


ANSWER: 31  


## BONUS  


22. COMPUTER SCIENCE Multiple Choice The acronym ADSL stands for:  


W) asynchronous digital subscriber line X) asymmetric digital subscriber line Y) advanced digital standard line Z) none of the above  


ANSWER: X) ASYMMETRIC DIGITAL SUBSCRIBER LINE  


## TOSS-UP  


23. BIOLOGY Short Answer The "fluid mosaic model" refers to the structure of what part of the cell?  


ANSWER: PLASMA MEMBRANE (ACCEPT CELL MEMBRANE)  


## BONUS  


23. BIOLOGY Short Answer A membrane that encloses the developing embryo in liquid is called the:  


ANSWER: AMNION  


## TOSS-UP  


24. GENERAL SCIENCE Short Answer What is the term for death related to exposure to cold weather or water?  


ANSWER: HYPOTHERMIA  


## BONUS  


24. GENERAL SCIENCE Short Answer What is the branch of mathematics concerned with the inferences that can be drawn from numerical data on the basis of probability?  


ANSWER: STATISTICS
## TOSS-UP  


25. MATH Short Answer Given two positive numbers \(a\) and \(b\) , the expression square root of \(a\) times \(b\) is called  


ANSWER: GEOMETRIC MEAN  


## BONUS  


25. MATH Short Answer A sequence of numbers whose successive numbers differ by a constant multiplier is called  


ANSWER: GEOMETRIC PROGRESSION (ACCEPT GEOMETRIC SEQUENCE)
## ROUND 5 A  


## TOSS-UP  


1. EARTH SCIENCE Multiple Choice What do Mt. Rainier and Mt. Mazama have in common?  


W) they have the same elevation X) they are volcanoes Y) they are erosional remnants of anticlines Z) they are horses  


ANSWER: X) THEY ARE VOLCANOES  


## BONUS  


1. EARTH SCIENCE Multiple Choice Diamonds are transported up from the mantle in  


W) mid-oceanic ridges 
X) kimberlite pipes 
Y) flood basalts 
Z) composite cones  


ANSWER: X) KIMBERLITE PIPES  


## TOSS-UP  


2. CHEMISTRY Short Answer What is the formula for hydrocyanic (Read: Hydro-Sigh-Ann-Ic) acid?  


ANSWER: HCN  


## BONUS  


2. CHEMISTRY Short Answer Which of the following, hydrochloric acid, sodium hydroxide, sulfuric acid, or aluminum chloride is a dehydration agent?  


ANSWER: SULFURIC ACID
## TOSS-UP  


3. GENERAL SCIENCE Short Answer What is the name for the scientific study of extinct organisms?  


ANSWER: PALEOONTOLOGY  


## BONUS  


3. GENERAL SCIENCE Short Answer What is the term for the estimating of ages of archeological specimens of biological origin by comparing the ratio of radiocarbon atoms to stable carbon atoms?  


ANSWER: CARBON DATING  


## TOSS-UP  


4. ASTRONOMY Multiple Choice The Magellanic (Pronounce: made-uh-lan-ick) Clouds are  


W) clouds of gas and dust in our galaxy X) reflection nebulae Y) irregular galaxies Z) globular clusters  


ANSWER: Y) IRREGULAR GALAXIES  


## BONUS  


4. ASTRONOMY Short Answer Which of Jupiter's satellites has sulfur compounds on its surface and volcanoes?  


ANSWER: IO (pron: eye - o)
## TOSS-UP  


5. MATH Multiple Choice Eccentric circles  


W) do not have a common center 
X) have a common center 
Y) have strange tangents 
Z) have diameter of unity  


ANSWER: W) DO NOT HAVE A COMMON CENTER  


## BONUS  


5. MATH Multiple Choice If \(\operatorname {f}(x) = x^{2}\) (read: f of x) and \(g(x) = x + 1\) , then the composite function \(f(g(x)) = ?\) (read: f of g of x equals what?)  


W) \(x^{3} + x^{2}\) X) \(x^{2} + 1\) Y) \(x^{2} + 2x + 1\) Z) \(x^{2} + x + 1\)  


ANSWER: Y) \(X^{2} + 2X + 1\)  


## TOSS-UP  


6. ASTRONOMY Short Answer What is the name of the space probe that provided a close-up look at three asteroids in 1998 as they crossed Earth's orbit?  


ANSWER: CLEMENTINE  


## BONUS  


6. ASTRONOMY Multiple Choice Most radio galaxies, when viewed in the visible part of the spectrum, appear to be  


W) spiral galaxies 
X) elliptical galaxies 
Y) irregular galaxies 
Z) barred spiral galaxies  


ANSWER: X) ELLIPTICAL GALAXIES
## TOSS-UP  


7. PHYSICS Short Answer Which form of energy is associated with an object's motion?  


ANSWER: KINETIC  


## BONUS  


7. PHYSICS Multiple Choice Which best describes the relationship between two systems in thermal equilibrium?  


W) no net energy is exchanged  X) volumes are equal  Y) masses are equal  Z) zero velocity  


ANSWER: W) NO NET ENERGY IS EXCHANGED  


## TOSS-UP  


8. COMPUTER SCIENCE Multiple Choice On a spreadsheet, the intersection of a row and a column is called a  


W) cell address  X) cell  Y) cell range  Z) current cell  


ANSWER: X) CELL  


## BONUS  


8. COMPUTER SCIENCE Short Answer What is the term for a graphical representation of the sequence of events that comprise a computer program's process?  


ANSWER: FLOWCHART
## TOSS-UP  


9. MATH Multiple Choice The name of the angle that is strictly greater than a right angle, but strictly less than a straight angle is  


W) oblique 
X) obtuse 
Y) acute 
Z) none of the above  


ANSWER: W) OBTUSE  


## BONUS  


9. MATH Short Answer Solve the equation \(|2x - 1| = 3\) (read: absolute value of the quantity 2x minus 1 equals 3)  


ANSWER: \(X = - 1\) or \(X = 2\) (both answers are required)  


## TOSS-UP  


10. COMPUTER SCIENCE Multiple Choice The process of replacing an original binary file with an encoded version that is typically smaller than the original is called:  


W) data decompression 
X) data compression 
Y) decryption 
Z) compositing  


ANSWER: X) DATA COMPRESSION  


## BONUS  


10. COMPUTER SCIENCE Multiple Choice The speed at which a modem can transmit data is  


W) BITNET 
X) Broadband 
Y) baud rate 
Z) burst speed  


ANSWER: Y) BAUD RATE
## TOSS-UP  


11. EARTH SCIENCE Short Answer What term refers to the amount of dissolved salt in seawater?  


ANSWER: SALINITY  


## BONUS  


11. EARTH SCIENCE Short Answer In which atmospheric layer is most of world's weather found?  


ANSWER: TROPOSPHERE  


## TOSS-UP  


12. MATH Short Answer A family of geometric figures (especially circles) having a common center are said to be  


ANSWER: CONCENTRIC  


## BONUS  


12. MATH Short Answer The power to which 10 has to be raised to equal a given number is called  


ANSWER: COMMON LOGARITHM (ACCEPT LOGARITHM OR BASE 10 LOGARITHM)  


## TOSS-UP  


13. ASTRONOMY Multiple Choice The first report of the use of a telescope to observe astronomical objects was made by  


W) Carl Sagan 
X) Kepler 
Y) Galileo 
Z) Ptolemy  


ANSWER: Y) GALILEO  


## BONUS  


13. ASTRONOMY Multiple Choice In what respect do Uranus and Neptune differ markedly?  


W) size 
X) temperature 
Y) atmospheric activity 
Z) chemical composition  


ANSWER: Y) ATMOSPHERIC ACTIVITY
## TOSS-UP  


14. EARTH SCIENCE Multiple Choice Agents of erosion include  


W) wind  X) water  Y) ice  Z) all of the above  


ANSWER: Z) ALL OF THE ABOVE  


## BONUS  


14. EARTH SCIENCE Short Answer When working in the field, Earth scientists can use GPS receivers to help pinpoint their location. What does "GPS" stand for?  


ANSWER: GLOBAL POSITIONING SYSTEM  


## TOSS-UP  


15. GENERAL SCIENCE Multiple Choice The average interval between successive high tides for the earth's oceans is  


W) 11 hours 24 minutes  X) 12 hours 24 minutes  Y) 23 hours 56 minutes  Z) 24 hours 4 minutes  


ANSWER: X) 12 HOURS 24 MINUTES  


## BONUS  


15. GENERAL SCIENCE Multiple Choice The two most important factors in climate are  


W) temperature and precipitation  X) precipitation and pressure  Y) humidity, clouds, and wind  Z) wavelengths of light and atmospheric particulates  


ANSWER W) TEMPERATURE AND PRECIPITATION
## TOSS-UP  


16. PHYSICS Multiple Choice Liquids and gases are both fluids. The principle characteristic that distinguishes between them is  


W) compressibility 
X) pressure 
Y) flow rate 
Z) viscosity  


ANSWER: W) COMPRESSIBILITY  


## BONUS  


16. PHYSICS Multiple Choice The absolute temperature of an ideal gas is directly proportional to which of the following properties, when taken as an average, of the molecules of that gas?  


W) speed 
X) momentum 
Y) mass 
Z) kinetic energy  


ANSWER: Z) KINETIC ENERGY  


## TOSS-UP  


17. CHEMISTRY Multiple Choice Neutralization is the reaction of  


W) an acid with a base 
X) a salt with water 
Y) an electrolyte with a nonelectrolyte 
Z) a soluble substance with water  


ANSWER: W) AN ACID WITH A BASE  


## BONUS  


17. CHEMISTRY Multiple Choice Of the following, the endothermic change is  


W) vaporization 
X) deposition 
Y) condensation 
Z) freezing  


ANSWER: W) VAPORIZATION
## TOSS-UP  


18. GENERAL SCIENCE Multiple Choice Kilowatt-hours can be directly converted to  


W) Horsepower-hours 
X) foot pounds 
Y) British Thermal Units 
Z) all of the above  


ANSWER: Z) ALL OF THE ABOVE  


## BONUS  


18. GENERAL SCIENCE Short Answer What is the branch of biology concerned with the vital functions of plants and animals, such as nutrition, respiration, reproduction, and excretion?  


ANSWER: PHYSIOLOGY  


## TOSS-UP  


19. PHYSICS Multiple Choice When we subtract a velocity vector from another velocity vector, the result is  


W) another velocity 
X) an acceleration 
Y) a displacement 
Z) a scalar quantity  


ANSWER: W) ANOTHER VELOCITY  


## BONUS  


19. PHYSICS Multiple Choice Which of the following does not fit in the same category?  


W) light wave 
X) radio wave 
Y) sound wave 
Z) X-ray  


ANSWER: Y) SOUND WAVE
## TOSS-UP  


20. ASTRONOMY Multiple Choice After first-quarter the Moon appears more than half illuminated. This phase is called  


W) three-quarter 
X) inverse crescent 
Y) gibbous 
Z) There is no name for this interval  


ANSWER: Y) GIBBOUS  


## BONUS  


20. MATH Multiple Choice The procedure of writing numbers as a decimal value between 1 and 10 time 10 raised to an integer power such as: \(2.4 * 10^4\) (read as: two point four times ten to the fourth power)is called:  


W) the scientific method 
X) mathematical precession 
Y) exponential notation 
Z) astronomical designation  


ANSWER: Y) EXPONENTIAL NOTATION  


## TOSS-UP  


21. COMPUTER SCIENCE Short Answer What converts MIDI instructions to electrical signals that can be amplified and reproduced as musical sounds through conventional audio equipment?  


ANSWER: MIDI SYNTHESIZER  


## BONUS  


21. COMPUTER SCIENCE Multiple Choice The ability to access a remote computer system on which one does not have an account, via the Internet's File Transfer Protocol is called  


W) anonymous FTP 
X) anti-aliasing FTP 
Y) anonymous remailer 
Z) anonymous posting  


ANSWER: W) ANONYMOUS FTP
## TOSS-UP  


22. CHEMISTRY Short Answer The distance between the centers of two bonded atoms is the  


ANSWER: BOND LENGTH  


## BONUS  


22. CHEMISTRY Multiple Choice The silver ion in the complex [Ag(CN)2]- (read as: A G open parentheses C N closed parentheses two, one minus) has a coordination number of  


W) 2 X) 3 Y) 4 Z) 5  


ANSWER: W) 2  


## TOSS-UP  


23. EARTH SCIENCE Short Answer What is the term for a broad, gently sloping extension of a continent?  


ANSWER: CONTINENTAL SHELF  


## BONUS  


23. EARTH SCIENCE Multiple Choice Seafloor spreading is believed to occur when plates  


W) diverge 
X) converge 
Y) slide past each other 
Z) are subducted  


ANSWER: W) DIVERGE
## TOSS-UP  


24. COMPUTER SCIENCE Short Answer What country is referred to by the domain name extension .de (read as: dot d e)?  


ANSWER: GERMANY  


## BONUS  


24. COMPUTER SCIENCE Multiple Choice The binary number 11101 equals what base ten number?  


W) 4  X) 19  Y) 29  Z) 34  


ANSWER: Y) 29  


## TOSS-UP  


25. CHEMISTRY Short Answer The dissociation of a molecular ion into daughter ions is known as what?  


ANSWER: FRAGMENTATION  


## BONUS  


25. CHEMISTRY Short Answer Which scientist originally conducted oil drop experiment which established the charge on an electron?  


ANSWER: MILLIKAN (ACCEPT ROBERT MILLIKAN)
## ROUND 6 A  


## TOSS-UP  


1. BIOLOGY Short Answer An amino acid chain that forms a flattened zigzag pattern is an example of a secondary protein structure called  


ANSWER: BETA SHEET/BETA PLEATED SHEET  


## BONUS  


1. BIOLOGY Short Answer The massive evolutionary radiation that produced many of the animal groups that we recognize today is called  


ANSWER: CAMBRIAN EXPLOSION  


## TOSS-UP  


2. GENERAL SCIENCE Multiple Choice One long ton is approximately how much heavier than a short ton?  


W) 20% X) 30% Y) 5% Z) 10%  


ANSWER: Z) 10%  


## BONUS  


2. GENERAL SCIENCE Short Answer In the US, an intense tropical depression is called a hurricane. What is the name for strong tropical depression in the Indian Oceans?  


ANSWER: CYCLONES
## TOSS-UP  


3. EARTH SCIENCE Multiple Choice The layer of soil that contains organisms and organic matter is which horizon?  


W) A horizon X) B horizon Y) C horizon Z) D horizon  


ANSWER: W) A HORIZON  


## BONUS  


3. EARTH SCIENCE Multiple Choice Small, steep-sided volcanoes made up of fragments blown out of a central opening are  


W) vents X) fissures Y) shield volcanoes Z) cinder cones  


ANSWER: Z) CINDER CONES  


## TOSS-UP  


4. COMPUTER SCIENCE Multiple Choice John Backus was the inventor of this BASIC-like compiled programming language  


W) COBOL X) FORTRAN Y) Pascal Z) UNIX  


ANSWER: X) FORTRAN  


## BONUS  


4. COMPUTER SCIENCE Multiple Choice The art and science of keeping messages secret is called  


W) cryptography X) encryption Y) decryption Z) fire wall  


ANSWER: W) CRYPTOGRAPHY
## TOSS-UP  


5. MATH Short Answer Two lines, that are not parallel to a coordinate axis are perpendicular if and only if the product of their slopes is equal to what number?ANSWER: -1  


ANSWER: - 1  


## BONUS  


5. MATH Short Answer In how many ways can 4 different books be given to 2 children so that each child gets exactly 2 books?ANSWER: 6 (WAYS)  


ANSWER: 6 (WAYS)  


## TOSS-UP  


6. EARTH SCIENCE Multiple Choice For every day of written human history, the dinosaurs existed for  


W) decades 
X) years 
Y) weeks 
Z) days  


ANSWER: W) DECADES  


## BONUS  


6. EARTH SCIENCE Multiple Choice The moon rotates once on its axis and completes one revolution every  


W) 21 days 
X) 24.5 days 
Y) 27.3 days 
Z) 30.1 days  


ANSWER: Y) 27.3 DAYS
## TOSS-UP  


7. BIOLOGY Multiple Choice Hemoglobin contains  


W) iron  X) copper  Y) calcium  Z) zinc  


ANSWER: W) IRON  


## BONUS  


7. BIOLOGY Short Answer A chain of amino acids that is wound into a single, coiled strand is an example of a secondary protein structure called  


ANSWER: ALPHA HELIX (ACCEPT HELIX)  


## TOSS-UP  


8. COMPUTER SCIENCE Multiple Choice Which of the following is not a valid integer constant?  


W) 521  X) -32.0  Y) 5,621  Z) -0  


ANSWER: X) -32.0  


## BONUS  


8. COMPUTER SCIENCE Multiple Choice What platforms does the commercial program Acrobat support to change a formatted document into a Portable Document Format (PDF)?  


W) Windows  X) Macintosh  Y) MS-DOS  Z) All of the above  


ANSWER: Z) ALL OF THE ABOVE
## TOSS-UP  


9. GENERAL SCIENCE Short Answer What is the term for the layer within the stratosphere where most of the sun's ultraviolet radiation is absorbed?  


ANSWER: OZONE LAYER  


## BONUS  


9. GENERAL SCIENCE Short Answer What is the term used to describe the stage of certain insects such as dragonflies and grasshoppers where the juvenile resembles the adult except that wings and reproductive organs are undeveloped?  


ANSWER: NYMPH  


## TOSS-UP  


10. MATH Short Answer All numbers of the form \(a + ib\) , where \(a\) and \(b\) are real numbers and \(i\) is the square root of -1 are called  


ANSWER: COMPLEX NUMBERS  


## BONUS  


10. MATH Short Answer A geometric set of figures having identical size and shape so that they may be exactly superimposed are called  


ANSWER: CONGRUENT
## TOSS-UP  


11. BIOLOGY Multiple Choice The meninges (Pronounced: meh-nin-jeez) are  


W) layers around the brain X) layers around the lungs Y) transport sites for carbon dioxide Z) bacteria that cause meningitis  


ANSWER: W) LAYERS AROUND THE BRAIN  


## BONUS  


11. BIOLOGY Multiple Choice Which of the following is NOT a characteristic of all chordates?  


W) dorsal, hollow nerve cord 
X) pharyngeal gill slits 
Y) a backbone 
Z) post anal tail  


ANSWER: Y) A BACKBONE  


## TOSS-UP  


12. GENERAL SCIENCE Short Answer When it is precisely noon Greenwich Mean Time, where is it precisely midnight?  


ANSWER: INTERNATIONAL DATE LINE (OR 180 DEGREE MERIDIAN OR 180 DEGREES LONGITUDE)  


## BONUS  


12. GENERAL SCIENCE Short Answer Named after a 19th century British scientist, what are the jerky movements of molecules resulting from random thermal motion?  


ANSWER: BROWNIAN MOTION
## TOSS-UP  


13. MATH Short Answer In a right triangle, the ratio of the length of the hypotenuse to the length of the side opposite the given angle is called  


ANSWER: COSECANT  


## BONUS  


13. MATH Short Answer In the integers, the multiplicative identity element is 1 and the additive identity element is  


ANSWER: ZERO  


## TOSS-UP  


14. ASTRONOMY Multiple Choice The age of the Earth is thought to be approximately  


W) 45,000 years X) 4.5 millions years Y) 4.5 billion years Z) 4.5 trillion years  


ANSWER: Y) 4.5 BILLION YEARS  


## BONUS  


14. ASTRONOMY Short Answer The unit invented to describe the distance to a star having a parallax of one second of arc is called what?  


ANSWER: PARSEC  


## TOSS-UP  


15. BIOLOGY Short Answer What hormone, secreted by the pineal gland, is associated with circadian rhythms?  


ANSWER: MELATONIN  


## BONUS  


15. BIOLOGY Short Answer Cytokinesis in animal cells is accomplished by contraction of a ring of filaments made from what protein?  


ANSWER: ACTIN
## TOSS-UP  


16. PHYSICS Multiple Choice What phenomenon is created by two tuning forks, side by side, emitting frequencies which differ by only a small amount?  


W) resonance 
X) interference 
Y) the Doppler effect 
Z) beats  


ANSWER: Z) BEATS  


## BONUS  


16. PHYSICS Multiple Choice The value of an object's acceleration may be characterized in equivalent words by which of the following?  


W) displacement 
X) rate of change of displacement 
Y) velocity 
Z) rate of change of velocity  


ANSWER: Z) RATE OF CHANGE OF VELOCITY  


## TOSS-UP  


17. CHEMISTRY Multiple Choice The compound \(\mathrm{HNO}_2\) is best classified as a  


W) strong acid 
X) strong base 
Y) weak acid 
Z) weak base  


ANSWER: Y) WEAK ACID  


## BONUS  


17. CHEMISTRY Multiple Choice The bonds between which two elements are most polar?  


W) Carbon and Iodine 
X) Carbon and Bromine 
Y) Carbon and Chlorine 
Z) Carbon and Flourine  


ANSWER: Z) CARBON AND FLOURINE
## TOSS-UP  


18. BIOLOGY Short Answer Who was the first person to use the term "cell" to describe the boxlike cavities he saw in a slice of cork viewed under the microscope?  


ANSWER: ROBERT HOOKE  


## BONUS  


18. BIOLOGY Short Answer Who proposed the two-kingdom classification system for plants and animals that was used up to the mid 20th century?  


ANSWER: LINNAEUS  


## TOSS-UP  


19. EARTH SCIENCE Multiple Choice What is the term for a layer of volcanic ash that has been discovered throughout a wide region?  


W) an unconformity 
X) an index fossil 
Y) a key bed 
Z) an organic remain  


ANSWER: Y) A KEY BED  


## BONUS  


19. EARTH SCIENCE Multiple Choice Boundaries at which plates move apart are called  


W) convergent 
X) stable 
Y) divergent 
Z) volcanic  


ANSWER: Y) DIVERGENT
## TOSS-UP  


20. COMPUTER SCIENCE Short Answer What is a unit of measure signifying one million cycles per second called?  


ANSWER: MEGAHERTZ  


## BONUS  


20. COMPUTER SCIENCE Short Answer What is the term for the capability to execute a program on different hardware processors and platforms.  


ANSWER: PORTABILITY  


## TOSS-UP  


21. GENERAL SCIENCE Short Answer What is the name for the scientific study of animals, including their anatomy, physiology, genetics, and behavior?  


ANSWER: ZOOLOGY  


## BONUS  


21. GENERAL SCIENCE Multiple Choice The oxygen cycle is closely linked to  


W) the hydrological cycle 
X) the hydrological and carbon cycles 
Y) the vapor compression cycle 
Z) all of the above  


ANSWER: X) THE HYDROLOGICAL AND CARBON CYCLES
## TOSS-UP  


22. ASTRONOMY Short Answer Which two planets are visible only just before sunrise or just after sunset??  


ANSWER: MERCURY AND VENUS  


## BONUS  


22. ASTRONOMY Multiple Choice The device that finally provided, in the 19th century, proof that Earth actually rotates on its axis was the  


W) telescope  X) pendulum clock  Y) Foucault (Pronounce: FOO-COH) Pendulum  Z) Fizeau (Pronounce: FIZZ-OH) Wheel  


ANSWER: Y) FOUCAULT PENDULUM  


## TOSS-UP  


23. CHEMISTRY Short Answer What type of bonding would you expect between two potassium atoms?  


ANSWER: METALLIC  


## BONUS  


23. CHEMISTRY Multiple Choice The least reactive of these elements is  


W) iron  X) platinum  Y) palladium  Z) nickel  


ANSWER: X) PLATINUM
## TOSS-UP  


24. GENERAL SCIENCE Short Answer What is the term for the study and use of pressure waves that have a frequency in excess of 20,000 Hz?  


ANSWER: ULTRASONICS  


## BONUS  


24. GENERAL SCIENCE Multiple Choice Which fuel does not need to be reformed for use in a fuel cell?  


W) Gasoline 
X) Hydrogen 
Y) Natural Gas 
Z) Methanol  


ANSWER: X) HYDROGEN  


## TOSS-UP  


25. COMPUTER SCIENCE Short Answer What is the term for a device that modulates digital signals for transmission across telephone lines to a remote computer system?  


ANSWER: MODEM  


## BONUS  


25. COMPUTER SCIENCE Short Answer What is the term for the overall intensity of the pixels in a digital image?  


ANSWER: BRIGHTNESS
## ROUND 7A  


## TOSS-UP  


1. CHEMISTRY Multiple Choice The molecule that has only a temporary dipole is  


W) HCl 
X) NaCl 
Y) \(\mathrm{Cl}_2\) Z) \(\mathrm{NH}_3\)  


ANSWER: Y) C12  


## BONUS  


1. CHEMISTRY Short Answer A complex in which the metal ion is bonded to a polydentate ligand is known as  


ANSWER: CHELATE  


## TOSS-UP  


2. ASTRONOMY Multiple Choice The composition of the Sun is believed to be mainly  


W) oxygen and nitrogen 
X) carbon and oxygen 
Y) hydrogen and helium 
Z) hydrogen and iron  


ANSWER: Y) HYDROGEN AND HELIUM  


## BONUS  


2. ASTRONOMY Multiple Choice How is the Roche (Pronounce: Roash) limit defined?  


W) the critical distance from a planet, inside of which a body can be tidally destroyed 
X) the maximum density that a body can have, depending on its composition 
Y) the maximum distance from a planet that a moon can experience synchronous rotation 
Z) the maximum mass a moon can have and still be classified as a moon  


ANSWER: W) THE CRITICAL DISTANCE FROM A PLANET, INSIDE OF WHICH A BODY CAN BE TIDALLY DESTROYED
## TOSS-UP  


3. COMPUTER SCIENCE Short Answer What does JPEG stand for? ANSWER: JOINT PHOTOGRAPHIC EXPERTS GROUP  


## BONUS  


3. COMPUTER SCIENCE Multiple Choice How many Mega Bytes Per Second is the Fast Ethernet now capable of supporting?  


W) 100  X) 1000  Y) 10000  Z) none of the above  


ANSWER: W) 100  


## TOSS-UP  


4. EARTH SCIENCE Multiple Choice Which one of the following is not a trait of minerals?  


W) have a crystal structure  X) made from living organisms  Y) solids  Z) have a definite chemical makeup  


ANSWER: X) MADE FROM LIVING ORGANISMS  


## BONUS  


4. EARTH SCIENCE Short Answer What is the term for the process of matching rocks of the same age at different locations?  


ANSWER: CORRELATION
## TOSS-UP  


5. BIOLOGY Multiple Choice Since half of each parent molecule is present in each daughter molecule, then DNA replication is said to be  


W) generational 
X) semi conservative 
Y) conservative 
Z) partially redundant  


ANSWER: X) SEMI CONSERVATIVE  


## BONUS  


5. BIOLOGY Short Answer Cristae are structural components of what organelle?  


ANSWER: MITOCHONDRION  


## TOSS-UP  


6. GENERAL SCIENCE Short Answer What is the name for chemicals, radiation, and viruses that cause or promote the development of cancer?  


ANSWER: CARCINOGENS  


## BONUS  


6. GENERAL SCIENCE Short Answer What is the term for the use of X-rays to photograph a selected plane of the human body with other planes eliminated?  


ANSWER: TOMOGRAPHY  


## TOSS-UP  


7. PHYSICS Short Answer If one's hands are being warmed by holding them to one side of a flame, the predominant form of heat transfer is what process?  


ANSWER: RADIATION  


## BONUS  


7. PHYSICS Short Answer Three resistors, with values of 3.6, and 12 Ohms, respectively, are connected in series. What is the overall resistance of this combination?  


ANSWER: 21.0 OHMS
## TOSS-UP  


8. ASTRONOMY Multiple Choice The HR diagram is a plot of  


W) luminosity versus mass X) temperature versus radius Y) luminosity versus temperature Z) temperature versus mass  


ANSWER: Y) LUMINOSITY VERSUS TEMPERATURE  


## BONUS  


8. ASTRONOMY Multiple Choice Which of the following objects has the least luminosity?  


W) Sun X) hot O-type star Y) white dwarf Z) diffuse cloud  


ANSWER: Z) DIFFUSE CLOUD  


## TOSS-UP  


9. BIOLOGY Multiple Choice Each of the following is a macronutrient except  


W) carbohydrates X) ions Y) lipids Z) water  


ANSWER: X) IONS  


## BONUS  


9. BIOLOGY Short Answer Who is the best known proponent of the inheritance of acquired characteristics?  


ANSWER: JEAN BAPTISTE LAMARCK (ACCEPT LAMARCK)
## TOSS-UP  


10. CHEMISTRY Multiple Choice The Frasch process is used to  


W) convert aluminum oxide to metallic aluminum 
X) convert copper ore to copper sulfide 
Y) mine magnesium 
Z) mine elemental sulfur  


ANSWER: Z) MINE ELEMENTAL SULFUR  


## BONUS  


10. CHEMISTRY Multiple Choice The compound that contains ions that do NOT have a noble gas electron configuration is  


W) \(\mathrm{Cs_2S}\) X) \(\mathrm{FeO}\) Y) \(\mathrm{Al_2O_3}\) Z) \(\mathrm{TiO_2}\)  


ANSWER: X) FeO  


## TOSS-UP  


11. ASTRONOMY Multiple Choice The term "blue moon" refers to  


W) halos of reflecting light surrounding the moon 
X) second occurrence of a full moon during a single month 
Y) the light spectra influencing the moon viewing 
Z) the fact that the moon is made of blue cheese  


ANSWER: X) SECOND OCCURRENCE OF A FULL MOON DURING A SINGLE MONTH  


## BONUS  


11. ASTRONOMY Multiple Choice Protostars emit most of their radiation as  


W) white light 
X) ultraviolet 
Y) red light 
Z) infrared  


ANSWER: Z) INFRARED
## TOSS-UP  


12. MATH Short Answer A numerical or constant multiplier of the variables in an algebraic polynomial is called  


ANSWER: COEFFICIENT  


## BONUS  


12. MATH Short Answer A fair die is rolled and a fair coin flipped. What is the probability that the number on the die is two and the coin comes up heads?  


ANSWER: 1/12 (READ ONE- TWELFTH)  


## TOSS-UP  


13. BIOLOGY Short Answer What brain lobe is associated with the sensory area for vision?  


ANSWER: OCCIPITAL LOBE  


## BONUS  


13. BIOLOGY Short Answer What are the clusters of endocrine cells in the pancreas called?  


ANSWER: ISLETS OF LANGERHANS
## TOSS-UP  


14. COMPUTER SCIENCE Multiple Choice What is the technique used in communications and input/output operations for transmitting a number of separate signals simultaneously over a single channel or line called?  


W) multiplexing 
X) multitasking 
Y) multipassing 
Z) multilayering  


ANSWER: W) MULTIPLEXING  


## BONUS  


14. COMPUTER SCIENCE Multiple Choice A bounded media used for interconnecting the nodes of a LAN is  


W) twisted-pair cable 
X) coaxial cable 
Y) optical fiber cable 
Z) all of the above  


ANSWER: Z) ALL OF THE ABOVE  


## TOSS-UP  


15. EARTH SCIENCE Multiple Choice The most common mineral in most sandstone is  


W) feldspar 
X) quartz 
Y) halite 
Z) calcite  


ANSWER: X) QUARTZ  


## BONUS  


15. EARTH SCIENCE Multiple Choice Which of the following occurs as glacial snow and ice melts and the water flows down into cracks in rocks?  


W) plucking 
X) striations 
Y) abrasions 
Z) till  


ANSWER: W) PLUCKING
## TOSS-UP  


16. BIOLOGY Multiple Choice The organ inside the inner ear that translates vibrations into the sound that we hear is the  


W) otolith 
X) tympanic organ 
Y) organ of Corti 
Z) Eustachian tubes  


ANSWER: Y) ORGAN OF CORTI  


## BONUS  


16. BIOLOGY Multiple Choice A polysome is  


W) one of the units of a ribosome 
X) an mRNA molecule with several ribosomes attached 
Y) an organelle that functions similarly to a ribosome during meiosis 
Z) the two units of a ribosome considered together  


ANSWER: X) AN mRNA MOLECULE WITH SEVERAL RIBOSOMES ATTACHED  


## TOSS-UP  


17. CHEMISTRY Multiple Choice In the periodic table, as the atomic number of the elements increases down a column,  


W) the atomic radius decreases 
X) the atomic mass decreases 
Y) the elements become less metallic 
Z) the ionization energy decreases  


ANSWER: Z) THE IONIZATION ENERGY DECREASES  


## BONUS  


17. CHEMISTRY Multiple Choice Under what conditions does an oxidizing agent donate electrons?  


W) only when it concurrently accepts electrons 
X) when a reducing agent is present 
Y) only at very high temperatures 
Z) during electrolysis  


ANSWER: W) ONLY WHEN IT CONCURRENTLY ACCEPTS ELECTRONS
## TOSS-UP  


18. GENERAL SCIENCE Multiple Choice Studies of populations of mice indicate overcrowding is associated with  


W) reduced milk production in nursing females 
X) lower sexual activity 
Y) more spontaneous abortions 
Z) all of the above  


ANSWER: Z) ALL OF THE ABOVE  


## BONUS  


18. GENERAL SCIENCE Short Answer What foul smelling gas is commonly emitted from volcanoes, and is produced in small amounts by catalyzed engines?  


ANSWER: HYDROGEN SULFIDE  


## TOSS-UP  


19. BIOLOGY Multiple Choice Active transport requires energy derived from  


W) building of water molecules 
X) digestion by lysosomes 
Y) lipids 
Z) ATP hydrolysis  


ANSWER: Z) ATP HYDROLYSIS  


## BONUS  


19. BIOLOGY Multiple Choice Microvilli in the small intestine  


W) increase the surface area of the intestinal lining 
X) lack a blood supply 
Y) store waste products 
Z) transport amino acids into the digestive tract  


ANSWER: W) INCREASE THE SURFACE AREA OF THE INTESTINAL LINING
## TOSS-UP  


20. MATH Short Answer The two mathematicians credited with the invention of calculus are  


ANSWER: NEWTON AND LEIBNIZ  


## BONUS  


20. MATH Multiple Choice In general, when solving two-equation, two-variable systems by matrices, if we end up with a row of all zeroes then  


W) there are infinitely many solutions X) there are no solutions Y) there are exactly two solutions Z) there is only one solution  


ANSWER: W) THERE ARE INFINITELY MANY SOLUTIONS  


## TOSS-UP  


21. GENERAL SCIENCE Short Answer What type of cloud is most convectively vigorous, producing thunderstorms, hail, and occasionally tornadoes?  


ANSWER: CUMULONIMBUS  


## BONUS  


21. GENERAL SCIENCE Short Answer What is the name for an instrument used to measure solar radiation?  


ANSWER: PYRANOMETER OR PYRAHELIOMETER  


## TOSS-UP  


22. BIOLOGY Short Answer What is the movement of molecules from an area of high concentration to an area of low concentration called?  


ANSWER: SIMPLE DIFFUSION OR DIFFUSION  


## BONUS  


22. BIOLOGY Short Answer What is the largest part of the brain?  


ANSWER: CEREBRUM (CEREBRAL HEMISPHERES)
## TOSS-UP  


23. CHEMISTRY Short Answer How many f orbitals can there be in one atom?  


ANSWER: SEVEN  


## BONUS  


23. CHEMISTRY Multiple Choice A substance whose formula does not contain OH yet which yields a basic solution when dissolved is  


W) \(\mathrm{NH_3}\) X) \(\mathrm{CO_2}\) Y) HCl Z) NaCl  


ANSWER: W) \(\mathrm{NH_3}\)  


## TOSS-UP  


24. COMPUTER SCIENCE Short Answer What is the term used to describe Internet etiquette, the evolving set of customs for getting along on the Internet?  


ANSWER: NETIQUETTE  


## BONUS  


24. COMPUTER SCIENCE Multiple Choice What is the term used to describe graphics that treats an image as a collection of small, independently controlled dots (pixels) arranged in rows and columns?  


W) vector graphics 
X) raster graphics 
Y) grid graphics 
Z) linear graphics  


ANSWER: X) RASTER GRAPHICS  


## TOSS-UP  


25. EARTH SCIENCE Short Answer What is the term for a smaller area of water usually considered to be part of a major ocean?  


ANSWER: SEA  


## BONUS  


25. EARTH SCIENCE Short Answer Ropy, smooth-surface lava is called what?  


ANSWER: PAHOE HOE ("pa-HOY-hoy)
## ROUND 8 A  


## TOSS-UP  


1. ASTRONOMY Multiple Choice The object located at the center of the Galaxy is believed to be  


W) a large cluster of stars X) an enormous emission nebula Y) a black hole Z) a massive star formation region  


ANSWER: Y) A BLACK HOLE  


## BONUS  


1. ASTRONOMY Multiple Choice Most of the craters on the Moon were created by  


W) debris flying out to the Moon from impacts on the Earth 
X) impacts of fragments of asteroids evenly and continuously over the history of the Moon 
Y) volcanic activity during the early part of the Moon's history 
Z) impacts of rocky debris during the first billion years of the Moon's history  


ANSWER: Z) IMPACTS OF ROCKY DEBRIS DURING THE FIRST BILLION YEARS OF THE MOON'S HISTORY  


## TOSS-UP  


2. CHEMISTRY Multiple Choice Alloying a metal is done to  


W) make its extraction from its ore easier 
X) convert the metal to an oxide 
Y) enhance its properties such as strength 
Z) prepare ultrapure metal samples  


ANSWER: Y) ENHANCE ITS PROPERTIES SUCH AS STRENGTH  


## BONUS  


2. CHEMISTRY Short Answer The light given off by an electric discharge through a sodium vapor is this kind of spectrum.  


ANSWER: EMISSION
## TOSS-UP  


3. BIOLOGY Multiple Choice The term "efferent" refers to what kind of neurons?  


W) association  X) internuncial  Y) motor  Z) receptor  


ANSWER: Y) MOTOR  


## BONUS  


3. BIOLOGY Short Answer What part of the brain is responsible for the coordination of skeletal muscle contraction?  


ANSWER: CEREBELLUM  


## TOSS-UP  


4. ASTRONOMY Multiple Choice The atmosphere of Venus is composed primarily of  


W) nitrogen  X) carbon dioxide  Y) oxygen  Z) hydrogen  


ANSWER: X) CARBON DIOXIDE  


## BONUS  


4. ASTRONOMY Multiple Choice Running water on Mars  


W) is present now  X) has been present throughout the history of Mars  Y) was present for most of the history of Mars, but is not present now  Z) was present for brief intervals early in the history of Mars  


ANSWER: Z) WAS PRESENT FOR BRIEF INTERVALS EARLY IN THE HISTORY OF MARS
## TOSS-UP  


5. GENERAL SCIENCE Short Answer What type of rocks include kimberlite, rhyolite, and granite?  


ANSWER: IGNEOUS  


## BONUS  


5. GENERAL SCIENCE Short Answer What is the theory of geophysical processes that explains the movements of lithospheric plates?  


ANSWER: PLATE TECTONICS  


## TOSS-UP  


6. CHEMISTRY Short Answer What term describes a solid in which the atoms, ions, or molecules are arranged in an orderly pattern?  


ANSWER: CRYSTAL (OR CRYSTAL LATTICE)  


## BONUS  


6. CHEMISTRY Multiple Choice Which of the following will be paramagnetic?  


W) \(\mathrm{V}^{5 + }\) (read as: Vanadium five plus) 
X) \(\mathrm{Ni}^{2 + }\) (read as: Nickel two plus) 
Y) \(\mathrm{Mn}^{7 + }\) (read as: Manganese seven plus) 
Z) \(\mathrm{Ti}^{4 + }\) (read as: Titanium four plus)  


ANSWER: X) \(\mathrm{Ni}^{2 + }\) (READ AS: NICKEL TWO PLUS)  


## TOSS-UP  


7. BIOLOGY Short Answer In mitosis, if a parent cell has 6 chromosomes, each daughter cell will have how many chromosomes?  


ANSWER: 6  


## BONUS  


7. BIOLOGY Multiple Choice Organisms that carry recombinant DNA in their genome are called  


W) cloned 
X) transgenic 
Y) heterophilic 
Z) polyploid  


ANSWER: X) TRANSGENIC
## TOSS-UP  


e. MATH Multiple Choice A polynomial of odd degree with real coefficients always has  


W) at least one imaginary zero 
X) at least one real zero 
Y) at least two real zeros 
Z) none of the above  


ANSWER: X) AT LEAST ONE REAL ZERO  


## BONUS  


8. MATH Multiple Choice Evaluate \(\sum_{k = 1}^{6} k^2 = ?\) (read as: summation from k equals 1 to 6 of k squared equals)  


W) 21 
X) 6 k2 
Y) 6 
Z) 91  


ANSWER: Z) 91  


## TOSS-UP  


9. CHEMISTRY Multiple Choice In a high- spin octahedral complex, the number of unpaired electrons in Fe(II) (read: Iron two) will be  


W) 0 
X) 2 
Y) 4 
Z) 6  


ANSWER: Y) 4  


## BONUS  


9. CHEMISTRY Short Answer What is the highest possible oxidation state for palladium?  


ANSWER: +4
## TOSS-UP  


10. GENERAL SCIENCE Multiple Choice Tropical forests are not found in which of the following?  


W) North America 
X) Africa 
Y) Latin America 
Z) Asia  


ANSWER: W) NORTH AMERICA  


## BONUS  


10. GENERAL SCIENCE Short Answer What term describes the formation and collapse of bubbles in a turbulent liquid?  


ANSWER: CAVITATION  


## TOSS-UP  


11. EARTH SCIENCE Short Answer Iceland spar is a pure, transparent form of what mineral?  


ANSWER: CALCITE (ACCEPT CALCIUM CARBONATE)  


## BONUS  


11. EARTH SCIENCE Multiple Choice When water that contains carbonic acid seeps into cracks in limestone, one result may be  


W) clay 
X) mechanical weathering 
Y) feldspar 
Z) hollow caves  


ANSWER: Z) HOLLOW CAVES
## TOSS-UP  


12. ASTRONOMY Multiple Choice Most stars probably formed  


W) alone 
X) in clusters 
Y) from constellations 
Z) in the nucleus of the Galaxy  


ANSWER: X) IN CLUSTERS  


## BONUS  


12. ASTRONOMY Multiple Choice Which Galilean moon has little internal activity but two great multiple-ring impact basins?  


W) Io (Pronounce: eye-oh) 
X) Europa (Pronounce: you- row-puh) 
Y) Ganymede (Pronounce: gan-ih-meed) 
Z) Callisto (Pronounce: kuh-lis-toe)  


ANSWER: Z) CALLISTO  


## TOSS-UP  


13. PHYSICS Short Answer A large spring requires a force of 150 Newtons to compress it only 0.010 meters. What is the spring constant of the spring?  


ANSWER: 15000 NEWTONS PER METER  


## BONUS  


13. PHYSICS Multiple Choice A valid unit for momentum is which of the following?  


W) \(\mathrm{kg - m / s^2}\) (read as: kilogram meter per second squared) 
X) \(\mathrm{kg / m^2}\) (read as: kilogram per meter squared) 
Y) \(\mathrm{kg - m / s}\) (read as: kilogram meter per second) 
Z) N-m (read as: Newton meters)  


ANSWER: Y) KG- M/S (READ AS: KILOGRAM METER PER SECOND)
## TOSS-UP  


14. BIOLOGY Multiple Choice Endospores are produced by  


W) gram-positive bacteria 
X) beta hemolytic streptococci 
Y) fungi 
Z) viruses  


ANSWER: W) GRAM-POSITIVE BACTERIA  


## BONUS  


14. BIOLOGY Short Answer A bony flap covering the gills of fish is called the ANSWER: OPERCULUM  


## TOSS-UP  


15. CHEMISTRY Short Answer When the external pressure is 505 kilopascals, what is the vapor pressure (in kilopascals) of water at its boiling point?  


ANSWER: 505 KILOPASCALS  


## BONUS  


15. CHEMISTRY Multiple Choice The only element among the following that forms no known compounds is  


W) radon 
X) argon 
Y) francium 
Z) einsteinium  


ANSWER: X) ARGON
## TOSS-UP  


16. MATH Multiple Choice The x-coordinate of the point at which graph of a linear equation crosses the x-axis is called the  


W) zero point 
X) maxima 
Y) minima 
Z) x-intercept  


ANSWER: Z) X- INTERCEPT  


## BONUS  


16. MATH Multiple Choice If a fair coin is flipped twice with the outcome of each flip independent of each other, then the probability that neither flip results in a head is  


W) 1/3 
X) 1/4 
Y) 1/5 
Z) 1/6  


ANSWER: X) 1/4  


## TOSS-UP  


17. ASTRONOMY Multiple Choice The granulation pattern seen on the surface of the Sun results from  


W) heating of the photosphere by solar flares 
X) the differential rotation of the Sun 
Y) convection of gas in the region under the photosphere 
Z) strong magnetic fields cooling the gas in certain regions  


ANSWER: Y) CONVECTION OF GAS IN THE REGION UNDER THE PHOTOSPHERE  


## BONUS  


17. ASTRONOMY Multiple Choice What is a planetary nebula?  


W) A type of young, medium mass star 
X) A planet surrounded by a glowing shell of gas 
Y) The disc of gas and dust surrounding a young star that will soon form a solar system 
Z) The ejected envelope of a red giant surrounding a stellar core remnant  


ANSWER: Z) THE EJECTED ENVELOPE OF A RED GIANT SURROUNDING A STELLAR CORE REMNANT
## TOSS-UP  


18. EARTH SCIENCE Multiple Choice The results of plate movement can be seen at  


W) abyssal plains 
X) ocean margins 
Y) ocean floors 
Z) plate boundaries  


ANSWER: Z) PLATE BOUNDARIES  


## BONUS  


18. EARTH SCIENCE Multiple Choice When water comes in contact with the mineral feldspar  


W) granite forms 
X) clay minerals form 
Y) carbon dioxide forms 
Z) rust forms  


ANSWER: X) CLAY MINERALS FORM  


## TOSS-UP  


19. ASTRONOMY Multiple Choice Which of the following is important in producing the greenhouse effect on Venus?  


W) slow rotation 
X) carbon dioxide 
Y) oxygen 
Z) strong magnetic field  


ANSWER: X) CARBON DIOXIDE  


## BONUS  


19. ASTRONOMY Multiple Choice How many stars are visible to the eye on a typical clear night?  


W) a few hundred 
X) about 3,000 
Y) about 1 million 
Z) 50,000  


ANSWER: X) ABOUT 3,000
## TOSS-UP  


20. BIOLOGY Multiple Choice The human large intestine is approximately how many feet in length?  


W) 2 
X) 5 
Y) 10 
Z) 20  


ANSWER: X) 5  


## BONUS  


20. BIOLOGY Multiple Choice Which of the following has the greatest total energy?  


W) cyclic AMP 
X) ADP 
Y) ATP 
Z) glucose  


ANSWER: Z) GLUCOSE  


## TOSS-UP  


21. MATH Short Answer In Euclidean geometry, the name for a line whose perpendicular distance from a curve decreases to zero as the distance from the origin increases without limit is  


ANSWER: ASYMPTOTE  


## BONUS  


21. MATH Short Answer The least common multiple of 20 and 24 is  


ANSWER: 120
## TOSS-UP  


22. EARTH SCIENCE Short Answer In which kind of rock would the skeleton of an ancient fish most likely be found?  


ANSWER: SEDIMENTARY  


## BONUS  


22. EARTH SCIENCE Multiple Choice Jamaica's white sands are made of  


W) halite  X) quartz  Y) clay  Z) coral and shell fragments  


ANSWER: Z) CORAL AND SHELL FRAGMENTS  


## TOSS-UP  


23. CHEMISTRY Short Answer What is the bond angle in a linear arrangement of electron groups in degrees?  


ANSWER: 180  


## BONUS  


23. CHEMISTRY Short Answer When a nonmetal combines with a nonmetal, what kind of bond is formed?  


ANSWER: COVALENT
## TOSS-UP  


24. MATH Short Answer The dot product of vectors \(u = [u_1, u_2]\) (read as: \(u\) equals \(u\) one comma \(u\) two) and \(v = [v_1, v_2]\) is  


ANSWER: \(u_1v_1 + u_2v_2\)  


## BONUS  


24. MATH Multiple Choice When graphing a rational function, it is important to note that  


W) the graph cannot cross a vertical asymptote 
X) the graph can cross a horizontal asymptote 
Y) a graph may have both a vertical and horizontal asymptote 
Z) all of the above  


ANSWER: Z) ALL OF THE ABOVE  


## TOSS-UP  


25. GENERAL SCIENCE Short Answer An object that is too small to be seen without a microscope is called "microscopic"; what is an object called that is visible to the unaided eye?  


ANSWER: MACROSCOPIC  


## BONUS  


25. GENERAL SCIENCE Short Answer What is the term for a glaciated trough partly submerged by the sea?  


ANSWER: FIORD
## ROUND 9 A  


## TOSS-UP  


1. GENERAL SCIENCE Short Answer What is the part of a building that serves to transmit the load to the earth or rock?  


ANSWER: FOUNDATION  


## BONUS  


1. GENERAL SCIENCE Short Answer What is the term for the spread of malignant cells from a cancer to other parts of the body?  


ANSWER: METASTASIS  


## TOSS-UP  


2. ASTRONOMY Multiple Choice With respect to the stars, which of the following spectral types is the hottest?  


W) G2 
X) A5 
Y) K9 
Z) O2  


ANSWER: Z) O2  


## BONUS  


2. ASTRONOMY Multiple Choice Which of the following colors would correspond to the hottest glowing object?  


W) red 
X) blue 
Y) green 
Z) yellow  


ANSWER: X) BLUE
## TOSS-UP  


3. BIOLOGY Short Answer What term describes the capacity of one gene to have diverse effects?  


ANSWER: PLEIOTROPY  


## BONUS  


3. BIOLOGY Multiple Choice Insulin is produced by which cells of the Pancreas?  


W) alpha 
X) beta 
Y) delta 
Z) gamma  


ANSWER: X) BETA  


## TOSS-UP  


4. ASTRONOMY Multiple Choice The ultimate triumph of gravity is a  


W) white dwarf 
X) neutron star 
Y) black hole 
Z) black dwarf  


ANSWER: Y) BLACK HOLE  


## BONUS  


4. ASTRONOMY Multiple Choice Radio waves have  


W) high energy and long wavelength 
X) low energy and long wavelength 
Y) high energy and short wavelength 
Z) low energy and short wavelength  


ANSWER: X) LOW ENERGY AND LONG WAVELENGTH
## TOSS-UP  


5. GENERAL SCIENCE Multiple Choice The biosphere includes  


W) the troposphere 
X) the hydrosphere 
Y) the lithosphere 
Z) all of the above  


ANSWER: Z) ALL OF THE ABOVE  


## BONUS  


5. GENERAL SCIENCE Multiple Choice The heat transfer from a pitched roof to a flat ceiling in an attic space is determined by  


W) the amount of insulation above the flat ceiling 
X) the amount of air circulating in the attic 
Y) the color and thermal emissivity of the roof 
Z) all of the above  


ANSWER: Z) ALL OF THE ABOVE  


## TOSS-UP  


6. MATH Multiple Choice What types of numbers are included in the set of real numbers that are not included in the set of rational numbers?  


W) whole numbers 
X) integers 
Y) irrational numbers 
Z) fractional numbers  


ANSWER: Y) IRRATIONAL NUMBERS  


## BONUS  


6. MATH Short Answer Two vectors that have a dot product of zero are called  


ANSWER: PERPENDICULAR (ACCEPT: ORTHOGONAL)
## TOSS-UP  


7. COMPUTER SCIENCE Short Answer What does the acronym SCSI (also known as "scuzzy") stand for?  


ANSWER: SMALL COMPUTER SYSTEM INTERFACE  


## BONUS  


7. COMPUTER SCIENCE Short Answer What is the system configuration utility, which is accessible at boot time, for setting up certain system options, like date and time?  


ANSWER: CMOS SETUP OR COMPLIMENTARY METAL- OXIDE SEMICONDUCTOR  


## TOSS-UP  


8. ASTRONOMY Multiple Choice A satellite that appears stationary from the ground is said to be in  


W) parallel orbit X) accelerating orbit Y) ecliptic orbit Z) geosynchronous orbit  


ANSWER: Z) GEOSYNCHRONOUS ORBIT  


## BONUS  


8. ASTRONOMY Multiple Choice The nucleus of our galaxy is composed primarily of  


W) young, hot stars 
X) old, cool stars 
Y) interstellar gas and dust 
Z) planetary nebulae  


ANSWER: X) OLD, COOL STARS
## TOSS-UP  


9. CHEMISTRY Short Answer The symbol of the element boron is  


ANSWER: B  


## BONUS  


9. CHEMISTRY Short Answer What is the net charge of the ionic compound calcium fluoride?  


ANSWER: ZERO  


## TOSS-UP  


10. GENERAL SCIENCE Multiple Choice Thin strips and patches of vegetation that surround streams are called  


W) biotic zones 
X) riparian zones 
Y) lateral zones 
Z) filtration zones  


ANSWER: X) RIPARIAN ZONES  


## BONUS  


10. GENERAL SCIENCE Short Answer What is the name for the instrument with adjustable legs used to precisely measure the diameter or the thickness of pipe or other items?  


ANSWER: CALIPER (OR CALIPERS)  


## TOSS-UP  


11. BIOLOGY Multiple Choice The difference in the appearance of the adult male and the female in many species is known as  


W) polymorphism 
X) sexual dimorphism 
Y) the dioecious condition 
Z) hermaphroditism  


ANSWER: X) SEXUAL DIMORPHISM  


## BONUS  


11. BIOLOGY Short Answer The end product of glycolysis is  


ANSWER: PYRUVATE (accept: PYRUVIC ACID)
ROUND 9 A 6
## TOSS-UP  


12. ASTRONOMY Multiple Choice Measurements of the masses of galaxies by luminosity are different than those by gravity because of  


W) dirty lenses on telescopes 
X) dark matter 
Y) luminosity is not related to mass 
Z) the presence of many bright stars  


ANSWER: X) DARK MATTER  


## BONUS  


12. ASTRONOMY Multiple Choice Kepler's third law  


W) Relates a planet's orbital period to the size of its orbit around the Sun 
X) Relates a body's mass to its gravitational attraction 
Y) Allowed him to predict when eclipses occur 
Z) Allowed him to measure the distance to nearby stars  


ANSWER: W) RELATES A PLANET'S ORBITAL PERIOD TO THE SIZE OF ITS ORBIT AROUND THE SUN  


## TOSS-UP  


13. MATH Multiple Choice The solution set of a quadratic equation has how many real roots, if the discriminant is equal to zero?  


W) one 
X) two 
Y) three 
Z) none  


ANSWER: W) ONE  


## BONUS  


13. MATH Multiple Choice The discovery by Newton and Leibniz, now called the Fundamental Theorem of Calculus, describes the  


W) connection between integration and differentiation 
X) mean value for continuous functions 
Y) existence of Riemann sums 
Z) existence of limits  


ANSWER: W) CONNECTION BETWEEN INTEGRATION AND DIFFERENTIATION
## TOSS-UP  


14. CHEMISTRY Multiple Choice As electron affinity increases across the periodic table, electronegativity  


W) remains constant 
X) always decreases 
Y) most always increases 
Z) most always decreases  


ANSWER: Y) MOST ALWAYS INCREASES  


## BONUS  


14. CHEMISTRY Multiple Choice Which of the following will be diamagnetic?  


W) \(\mathrm{Ni}^{2 + }\) (read as: Nickel two plus) 
X) \(\mathrm{Ti}^{4 + }\) (read as: Titanium four plus) 
Y) \(\mathrm{Mn}^{2 + }\) (read as: Manganese two plus) 
Z) \(\mathrm{Co}^{3 + }\) (read as: Cobalt three plus)  


ANSWER: X) \(\mathrm{Ti}^{4 + }\)  


## TOSS-UP  


15. ASTRONOMY Multiple Choice The most active regions of star formation in the galaxy are  


W) dark clouds 
X) emission nebulae 
Y) reflection nebulae 
Z) between spiral arms  


ANSWER: W) DARK CLOUDS  


## BONUS  


15. ASTRONOMY Multiple Choice The specific colors of light emitted by an atom in a hot, thin gas are caused by  


W) electrons jumping to lower energy levels 
X) the vibrations of the electrons within the atom 
Y) protons jumping from level to level in the nucleus 
Z) an electron dropping into the nucleus, producing small nuclear changes  


ANSWER: W) ELECTRONS JUMPING TO LOWER ENERGY LEVELS
## TOSS-UP  


16. GENERAL SCIENCE Short Answer What is the term for a fracture in a rock formation along which the opposite walls have been pulled apart?ANSWER: FISSURE  


ANSWER: FISSURE  


## BONUS  


16. GENERAL SCIENCE Short Answer What is the generic name for soil, loose rock, and other earthy material that overlays bedrock?ANSWER: BURDEN (ACCEPT OVERBURDEN)  


ANSWER: BURDEN (ACCEPT OVERBURDEN)  


## TOSS-UP  


17. BIOLOGY Short Answer In his experiments with plants, Mendel removed which part of the plant to prevent unwanted fertilizations?ANSWER: STAMENS  


ANSWER: STAMENS  


## BONUS  


17. BIOLOGY Multiple Choice Valves are found in the  


W) arteries and arterioles X) arterioles and capillaries Y) heart and veins Z) heart and arterioles  


ANSWER: Z) HEART AND VEINS
## TOSS-UP  


18. COMPUTER SCIENCE Multiple Choice Hard disk access time has which of the following components?  


W) transfer time 
X) seek time 
Y) rotational delay 
Z) all of the above  


ANSWER: Z) ALL OF THE ABOVE  


## BONUS  


18. COMPUTER SCIENCE Short Answer Which of the following, vacuum tubes, transistors, semi-conductors, is characteristic of the first generation of digital computers?  


ANSWER: VACUUM TUBES  


## TOSS-UP  


19. ASTRONOMY Multiple Choice Which is true of globular star clusters?  


W) They contain more stars than most galaxies 
X) They orbit the center of the galaxy 
Y) They are 10,000 light years in diameter 
Z) They are active sites of star formation  


ANSWER: X) THEY ORBIT THE CENTER OF THE GALAXY  


## BONUS  


19. ASTRONOMY Multiple Choice What is the Moon's phase at a lunar eclipse?  


W) New 
X) Full 
Y) First Quarter 
Z) Third Quarter  


ANSWER: X) FULL
## TOSS-UP  


20. CHEMISTRY Short Answer How many electrons are in the highest occupied energy level of a neutral chlorine atom?  


ANSWER: SEVEN  


## BONUS  


20. CHEMISTRY Short Answer What region of the electromagnetic spectrum is between radio waves and infrared waves?  


ANSWER: MICROWAVES  


## TOSS-UP  


21. BIOLOGY Short Answer Which element is found in greatest abundance in bone?  


ANSWER: CALCIUM  


## BONUS  


21. BIOLOGY Short Answer What chemical needs to be present to convert pepsinogen to pepsin?  


ANSWER: HCl (HYDROCHLORIC ACID)  


## TOSS-UP  


22. GENERAL SCIENCE Short Answer What is the term for the cloud-like streaks that often form to the rear of highflying aircraft?  


ANSWER: CONDENSATION TRAILS OR CONTRAILS  


## BONUS  


22. GENERAL SCIENCE Multiple Choice A volcano that erupted forty years ago, but has not erupted since is said to be  


W) inactive 
X) smoldering 
Y) dormant 
Z) active  


ANSWER: Z) ACTIVE
## TOSS-UP  


23. CHEMISTRY Short Answer At what temperature in Kelvin does liquid water have its maximum density?  


ANSWER: 277 KELVIN  


## BONUS  


23. CHEMISTRY Short Answer How many Joules are there in 100 calories?  


ANSWER: 418 JOULES (ACCEPT 418.4 JOULES)  


## TOSS-UP  


24. PHYSICS Short Answer If the area of the plates of a parallel-plate capacitor is doubled, what will happen to the capacitance?  


ANSWER: TWICE AS MUCH OR DOUBLED  


## BONUS  


24. PHYSICS Short Answer What is the principle that states that the buoyant force on floating or submerged bodies is equal to the weight of the liquid displaced?  


ANSWER: ARCHIMEDES' (PRINCIPLE)  


## TOSS-UP  


25. EARTH SCIENCE Short Answer What is now located at the site of the ancient volcano Mt. Mazama ("ma-ZAH-ma")?  


ANSWER: CRATER LAKE (OREGON) (ACCEPT A CALDERA)  


## BONUS  


25. EARTH SCIENCE Multiple Choice When anaerobic conditions prevail in a sedimentary environment and iron combines with sulfur to form pyrite, the typical color of the sediment is  


W) black 
X) red 
Y) yellow 
Z) green  


ANSWER: W) BLACK
ROUND 9 A 13