
## ROUND 5  


## TOSS-UP  


1) BIOLOGY Multiple Choice Bacteria that can only grow in the presence of oxygen are called:  


W) chemoautotrophs (PRON: chem-oh-auto-trofs)  


X) obligate anaerobes (Pron: an-air-obes)  


Y) facultative anaerobes (Pron: an-air-obes)  


Z) obligate aerobes (Pron: air-obes)  


ANSWER: Z) OBLIGATE AEROBES  


## BONUS  


1) BIOLOGY Multiple Choice Alpha keratins are relatively rich in which of the following amino acids:  


W) alanine (Pron: al-a-neen)  


X) tyrosine (Pron: tie-row-seen)  


Y) tryptophan (Pron: trip-o-fan)  


Z) cystine (Pron: sist-een)  


ANSWER: Z) CYSTINE  


## TOSS-UP  


2) CHEMISTRY Multiple Choice The number of moles of solute per kilogram of solvent best describes which of the following:  


W) normality  


X) molarity  


Y) molality  


Z) mole fraction  


ANSWER: Y) MOLALITY  


## BONUS  


2) CHEMISTRY Short Answer If an aqueous solution at \(25^{\circ}\mathrm{C}\) has a hydroxide ion concentration of \(1 \times 10^{-2}\) moles per liter, calculate both the hydrogen ion concentration in moles per liter and the pH:  


ANSWER: HYDROGEN ION CONCENTRATION \(= 1 \times 10^{- 12}\) AND \(\mathrm{pH} = 12\)  

equation[[147, 881, 920, 905]]
\[[\mathrm{H}^{+}] = 1\times 10^{-14}\mathrm{M} / [\mathrm{OH}^{-}]; = 1\times 10^{-14}\mathrm{M} / 1\times 10^{-2}; = 1\times 10^{-12}; \mathrm{pH} = -\log [\mathrm{H}^{+}] = 12.0)\]
## TOSS-UP  


3) PHYSICS Multiple Choice Which of the following units is a measure of resistance:  


W) erg  X) ohm  Y) joule  Z) volt  


ANSWER: X) OHM  


## BONUS  


3) PHYSICS Short Answer A rock with weight 650 newtons is on a ledge five meters above the ground. Relative to the ground, what is the gravitational potential energy, in joules, of the rock?  


ANSWER: 3250  


(Solution: \(\mathrm{PE} = 650 \mathrm{~N} \times 5 \mathrm{~m} = 3250 \mathrm{~J}\) )  


## TOSS-UP  


4) ASTRONOMY Short Answer What is the astronomical point in the sky that a plumb line would vertically point to?  


ANSWER: ZENITH  


## BONUS  


4) ASTRONOMY Short Answer What distant point of the Earth's orbit occurs on July \(3^{\mathrm{rd}}\) ?  


ANSWER: APHELION
## TOSS-UP  


5) MATH Short Answer Simplify the following radical into a reduced fraction: \(\sqrt{\frac{18}{50}}\)  


ANSWER: 3/5  


## BONUS  


5) MATH Short Answer What is the slope of a line which passes through the points (-1, 1) and (5, 3)?  


ANSWER: 1/3  


## TOSS-UP  


6) EARTH SCIENCE Short Answer Landscape features such as swamps, marshes, bogs, prairie potholes, and vernal pools, are collectively known as what:  


ANSWER: WETLANDS  


## BONUS  


6) EARTH SCIENCE Multiple Choice Which of the following glacial features is best used to determine which way an ancient glacier advanced and/or retreated:  


W) esker 
X) delta kame 
Y) varve 
Z) striations  


ANSWER: Z) STRIATIONS
## TOSS-UP  


7) GENERAL SCIENCE Multiple Choice The coastal redwood forest of Oregon and Northern California is an example of a:  


W) temperate woodland 
X) temperate evergreen forest 
Y) temperate rain forest 
Z) temperate deciduous forest  


ANSWER: Y) TEMPERATE RAIN FOREST  


## BONUS  


7) GENERAL SCIENCE Short Answer In meteorology, what does the symbol of an open circle typically represent?  


ANSWER: CLEAR SKIES (ACCEPT: CLEAR)  


## TOSS-UP  


8) COMPUTER SCIENCE Short Answer A type of constantly-powered nonvolatile memory that can be erased and reprogrammed in blocks instead of single bytes, is often used to hold control code in a personal computer, and is used commonly in cell phones, digital cameras and other portable devices, is called what:  


ANSWER: FLASH MEMORY (ACCEPT: FLASH)  


## BONUS  


8) COMPUTER SCIENCE Multiple Choice Which of the following is NOT a type of monitor:  


W) PDP 
X) RGB 
Y) SVGA 
Z) FTM  


ANSWER: X) RGB  


(Solution: PDP = Plasma Display Panel; FTM = Flat Tech Monitor; SVGA = Super VGA)
## TOSS-UP  


9) BIOLOGY Short Answer What is the vector for the bacterium Yersinia pestis (Pron: yur-sin-ee-ah pest-iss)?  


ANSWER: FLEA  


## BONUS  


9) BIOLOGY Multiple Choice Which of the following passive body functions consumes the most energy:  


W) breathing 
X) the sodium-potassium pump in all cells of the body 
Y) the beating of the heart 
Z) kidney filtration of plasma  


ANSWER: X) THE SODIUM-POTASSIUM PUMP IN ALL CELLS OF THE BODY  


## TOSS-UP  


10) CHEMISTRY Short Answer In a flame test for lithium, sodium, potassium, and zinc, which gives off a persistent yellow color:  


ANSWER: SODIUM  


## BONUS  


10) CHEMISTRY Short Answer To the second decimal place, what is the weight percent of a solution prepared by dissolving 10.0 grams NaCl in 100.0 grams water?  


ANSWER: 9.09  


(Solution: \(\mathrm{Wt\%} = 10.0 \mathrm{g} / 10.0 \mathrm{g} + 100.0 \mathrm{g}; = 9.09 \mathrm{Wt\%})\)
## TOSS-UP  


11) PHYSICS Multiple Choice A manual laborer moves a 40 kilogram bag of flour one meter above the ground in 5 seconds. If she does the same task in twice the time, it involves a different amount of:  


W) power 
X) work 
Y) displacement 
Z) potential energy  


ANSWER: W) POWER  


## BONUS  


11) PHYSICS Short Answer What is the potential difference, in volts, if 20 joules of work is needed to move 4 coulombs of charge in a uniform electric field?  


ANSWER: 5  


(Solution: \(\mathrm{v} = 20 / 4 = 5\) volts)  


## TOSS-UP  


12) ASTRONOMY Short Answer On the day of the summer solstice, the sun's diurnal motion will carry it around what circle?  


ANSWER: TROPIC OF CANCER (ACCEPT: \(23^{\circ}\) NORTH)  


## BONUS  


12) ASTRONOMY Short Answer In the days of Rome, the Sun passed over the celestial equator while it was traveling through the constellation Aries. What celestial phenomenon has caused the constellations of the zodiac today to be about one sign out of synchrony?  


ANSWER: PRECESSION
## TOSS-UP  


13) MATH Multiple Choice Which of the following is NOT a factor of 132:  


W) 33 
X) 12 
Y) 22 
Z) 8  


ANSWER: Z) 8  


## BONUS  


13) MATH Short Answer Solve the following equation for \(x\) : \(2x^{2} + x - 1 = 0\)  


ANSWER: \(x = \frac{1}{2}\) AND \(x = - 1\)  


## TOSS-UP  


14) EARTH SCIENCE Multiple Choice Transform boundaries are found where two lithospheric plates are:  


W) sliding next to each other in the same direction  


X) sliding past each other in the opposite direction  


Y) moving toward each other  


Z) moving apart from each other  


ANSWER: X) SLIDING PAST EACH OTHER IN THE OPPOSITE DIRECTION  


## BONUS  


14) EARTH SCIENCE Short Answer What famous German meteorologist suggested in 1915 the concept of continental drift and whose ideas at the time were dismissed by mainstream scientific circles?  


ANSWER: ALFRED WEGENER (ACCEPT: WEGENER)
## TOSS-UP  


15) GENERAL SCIENCE Short Answer What scientist coined the term 'radioactivity' to describe the phenomenon observed by Becquerel?  


ANSWER: MARIE CURIE (ACCEPT: MADAM CURIE OR MARIE SLOWDOWSKA CURIE)  


## BONUS  


15) GENERAL SCIENCE Short Answer How many pecks are in a bushel?  


ANSWER: 4  


## TOSS-UP  


16) COMPUTER SCIENCE Multiple Choice Which of the following devices can be safely attached or detached from a running computer and recognized by the operating system:  


W) USB mouse  


X) monitor  


Y) PS/2 keyboard  


Z) serial CD-ROM  


ANSWER: W) USB MOUSE  


## BONUS  


16) COMPUTER SCIENCE Multiple Choice Considering the standard printers commonly used today, which of the following can attain resolutions of up to 1400 dpi or higher:  


W) laser  


X) ink jet  


Y) dot matrix  


Z) line printer  


ANSWER: X) INK JET
## TOSS-UP  


17) BIOLOGY Short Answer What is the fluid-filled space inside the blastocyst called?  


ANSWER: BLASTOCOEL (Pron: blast- o- seal)  


## BONUS  


17) BIOLOGY Multiple Choice Which of the following is an obligate intracellular parasite:  


W) Actinomycetes (Pron: act-in-o-my-seat-ees) 
X) Vibrio (Pron: vib-ree-oh) 
Y) Chlamydia (Pron: klam-id-ee-ah) 
Z) Treponema (Pron: trep-o-neem-ah)  


ANSWER: Y) CHLAMYDIA  


## TOSS-UP  


18) CHEMISTRY Short Answer Two strands of DNA are held together in the double helix by what type of bond?  


ANSWER: HYDROGEN BOND (ACCEPT: HYDROGEN)  


## BONUS  


18) CHEMISTRY Short Answer Rounded to the nearest whole number, what is the pH of a \(1.0 \times 10^{-8}\) molar HCl solution at \(25^{\circ}\mathrm{C}\) ?  


ANSWER: 7  


(Solution: \(\mathrm{H}^{+}\) from water contributes significantly)
## TOSS-UP  


19) PHYSICS Short Answer What is the most common scientific name for the form of radiation that is emitted when relativistic electrons are forced to travel through a curved trajectory in a magnetic field?  


ANSWER: SYNCHROTRON RADIATION  


## BONUS  


19) PHYSICS Multiple Choice Ultraviolet light, incident on a zinc metal plate, will cause the plate to become positively charged because of:  


W) elastic scattering 
X) pair production 
Y) the photoelectric effect 
Z) static capacitance  


ANSWER: Y) THE PHOTOELECTRIC EFFECT  


## TOSS-UP  


20) ASTRONOMY Short Answer At what point in the moon's orbit is its velocity at minimum?  


ANSWER: APOGEE (ACCEPT: WHEN IT IS FARTHEST FROM THE EARTH)  


## BONUS  


20) ASTRONOMY Short Answer Notable because it contains the star cluster Praesepe (Pron: Prah-sep-ee), what is the faintest of the 12 zodiacal constellations?  


ANSWER: CANCER (ACCEPT: THE CRAB)
## TOSS-UP  


21) MATH Short Answer The average of 10, 14, 3, 7 and \(x\) is 0. What value is \(x\) ?  


ANSWER: - 34  


## BONUS  


21) MATH Short Answer After a discount of \(20\%\) , the price of a motorcycle was \(\) 10,000\$. What was the original price of the motorcycle?  


ANSWER: \(\) 12,500.00\$  


## TOSS-UP  


22) EARTH SCIENCE Multiple Choice A volcanic mountain on the seafloor which is flat-topped is known as a:  


W) seamount  


X) butte  


Y) guyot (Pron: gee- oh or guy- oh)  


Z) sea wall  


ANSWER: Y) GUYOT (PRON: gee- oh or guy- oh)  


## BONUS  


22) EARTH SCIENCE Short Answer On the Richter magnitude scale, a magnitude 3 signal is how many times larger than a magnitude 1 signal?  


ANSWER: 100 TIMES
## TOSS-UP  


23) BIOLOGY Multiple Choice Which of the following is NOT a roundworm:  


W) Lumbricus (Pron: Lum-bri-kuss) 
X) Ancylostoma (Pron: ANKLE-O-stow-ma) 
Y) Taenia (Pron: TAY-nee-a) 
Z) Ascaris (Pron: ask-a-ris)  


ANSWER: Y) TAENIA  


## BONUS  


23) BIOLOGY Short Answer What is the name of the nutrient storage structure found in crocuses and gladiolas where the vertical stem thickens and is covered by papery leaves?  


ANSWER: CORM  


## TOSS-UP  


24) CHEMISTRY Multiple Choice For individuals who cannot digest dairy products, they are lacking what enzyme:  


W) maltase 
X) lactase 
Y) amylase 
Z) galactase  


ANSWER: X) LACTASE  


## BONUS  


24) CHEMISTRY Multiple Choice Sephadex column chromatography separates proteins based on what property:  


W) size 
X) shape 
Y) density 
Z) charge  


ANSWER: W) SIZE
## TOSS-UP  


25) PHYSICS Short Answer That light is the source of color was strongly advanced by what scientist in 1665 A.D.?  


ANSWER: NEWTON  


## BONUS  


25) PHYSICS Short Answer What is the resistance, in ohms to the first decimal place, of an electric stove that draws 16 amps on a 120 volt line?  


ANSWER: 7.5  


(Solution: \(\mathrm{I} = \mathrm{V} / \mathrm{R}\) , \(\mathrm{R} = \mathrm{V} / \mathrm{I}\) , \(\mathrm{R} = 120 / 16 = 7.5\) ohms)