sub_title[[495, 90, 595, 107]]
## ROUND 12  

sub_title[[500, 141, 585, 159]]
## TOSS-UP  

text[[145, 175, 928, 230]]
1) PHYSICS Short Answer For two sound sources heard simultaneously, one of which vibrates at 50 hertz and the other vibrates at 60 hertz, what is the beat frequency in beats per second?  

text[[144, 245, 266, 264]]
ANSWER: 10  

sub_title[[507, 280, 577, 299]]
## BONUS  

text[[144, 315, 914, 352]]
1) PHYSICS Short Answer What is the acceleration of a bike traveling in a straight line if the bike slows from \(40 \mathrm{km / hr}\) to \(10 \mathrm{km / hr}\) in 5 seconds? Give your answer in \(\mathrm{km / hr / sec}\) .  

text[[144, 368, 264, 386]]
ANSWER: - 6  

text[[144, 402, 576, 422]]
(Solution: \(\mathrm{a} = \mathrm{v}_{2} - \mathrm{v}_{1} / \Delta \mathrm{t} = (10 - 40) / 5 = - 6 \mathrm{Km / hr / s})\)  

sub_title[[500, 473, 585, 491]]
## TOSS-UP  

text[[142, 507, 908, 527]]
2) CHEMISTRY Short Answer The formula, \(\mathrm{PV} = \mathrm{nRT}\) , is a representation of what gas law?  

text[[144, 543, 399, 561]]
ANSWER: IDEAL GAS LAW  

sub_title[[507, 579, 577, 597]]
## BONUS  

text[[141, 613, 805, 633]]
2) CHEMISTRY Multiple Choice Of the following, which is the strongest acid:  

text[[144, 649, 247, 666]]
W) sulfuric  

text[[144, 668, 270, 684]]
X) perchloric  

text[[144, 685, 291, 701]]
Y) hydrochloric  

text[[144, 703, 279, 719]]
Z) phosphoric  

text[[144, 735, 416, 754]]
ANSWER: X) PERCHLORICsub_title[[500, 90, 584, 107]]
## TOSS-UP  

text[[144, 123, 928, 160]]
3) BIOLOGY Short Answer Gel filtration column chromatography will separate proteins based primarily on what physical difference?  

text[[144, 176, 287, 194]]
ANSWER: SIZE  

sub_title[[507, 211, 577, 229]]
## BONUS  

text[[144, 245, 928, 282]]
3) BIOLOGY Multiple Choice A good transmission electron microscope has a resolving power of about:  

text[[144, 299, 310, 370]]
W) 0.5 microns  X) 50 nanometers  Y) 0.2 nanometers  Z) 0.01 angstroms  

text[[144, 386, 458, 404]]
ANSWER: Y) 0.2 NANOMETERS  

sub_title[[500, 473, 584, 490]]
## TOSS-UP  

text[[144, 507, 933, 543]]
4) ASTRONOMY Short Answer According to the Gregorian calendar, in what year AD will the next centurial leap year occur?  

text[[144, 560, 285, 577]]
ANSWER: 2400  

text[[144, 594, 684, 613]]
(Solution: Centurial years are leap years if divisible exactly by 400)  

sub_title[[507, 629, 577, 647]]
## BONUS  

text[[144, 663, 919, 717]]
4) ASTRONOMY Multiple Choice As understood by the Greek astronomer Aristarchus, horizontal parallax is to shifts of a viewer's position on different points of the Earth, as annual parallax is to shifts of a viewer's position:  

text[[144, 734, 540, 805]]
W) as the earth moves around the sun  X) as the moon moves through the lunar year  Y) as the sun moves around the earth  Z) as the celestial sphere moves about the earth  

text[[144, 821, 682, 839]]
ANSWER: W) AS THE EARTH MOVES AROUND THE SUNsub_title[[499, 88, 585, 106]]
## TOSS-UP  

text[[144, 123, 874, 160]]
5) MATH Short Answer The sine of theta is negative if the angle terminates in what two Quadrants of the Cartesian coordinate system?  

text[[144, 174, 656, 195]]
ANSWER: III AND IV (ACCEPT: 3 AND 4 OR \(3^{\mathrm{RD}}\) AND 4)  

sub_title[[507, 210, 577, 228]]
## BONUS  

text[[144, 245, 933, 300]]
5) MATH Short Answer To the nearest whole number, calculate the maximum height that could be attained for the following equation, where height at time \(t\) is given by the equation: \(y = 3t^2 - 3t + 15\)  

text[[144, 315, 266, 333]]
ANSWER: 14  

text[[144, 349, 670, 370]]
(Solution: \(y' = 6t - 3; t = 1 / 2; y = 3(.5)^2 - 3(.5) + 15; y = 14.25)\)  

sub_title[[499, 434, 585, 452]]
## TOSS-UP  

text[[144, 468, 937, 523]]
6) EARTH SCIENCE Multiple Choice Oxygen and nitrogen molecules in the atmosphere preferentially scatter light of shorter wavelengths causing the sky to appear blue owing to what type of scattering:  

text[[144, 539, 280, 611]]
W) Rayleigh 
X) Mie 
Y) Crepuscular 
Z) parallel  

text[[144, 626, 381, 644]]
ANSWER: W) RAYLEIGH  

sub_title[[507, 679, 577, 697]]
## BONUS  

text[[144, 713, 923, 750]]
6) EARTH SCIENCE Short Answer It is estimated that about 95% of all tsunamis are initiated by what event?  

text[[144, 766, 390, 784]]
ANSWER: EARTHQUAKESsub_title[[500, 90, 584, 107]]
## TOSS-UP  

text[[144, 123, 901, 178]]
7) GENERAL SCIENCE Multiple Choice A common type of distortion in CRT monitors in which horizontal and vertical lines bend outwards towards the edge of the display is called:  

text[[144, 194, 358, 266]]
W) barrel distortion 
X) pincushion distortion 
Y) spherical distortion 
Z) trapezoid distortion  

text[[144, 281, 494, 300]]
ANSWER: W) BARREL DISTORTION  

sub_title[[507, 316, 577, 334]]
## BONUS  

text[[144, 350, 897, 405]]
7) GENERAL SCIENCE Multiple Choice The largest number of individuals of a particular species that can by be maintained indefinitely in a given part of the environment is defined by what ecological term:  

text[[144, 420, 328, 492]]
W) biomic load 
X) biomass limit 
Y) cohort load 
Z) carrying capacity  

text[[144, 507, 500, 526]]
ANSWER: Z) CARRYING CAPACITY  

sub_title[[500, 560, 584, 578]]
## TOSS-UP  

text[[144, 594, 911, 630]]
8) COMPUTER SCIENCE Multiple Choice Which of the following is a network topology in which all the computers on the network are connected to a central computer:  

text[[144, 647, 234, 717]]
W) bus 
X) star 
Y) ring 
Z) mesh  

text[[144, 733, 345, 752]]
ANSWER: X) STAR  

sub_title[[507, 769, 577, 787]]
## BONUS  

text[[144, 803, 927, 857]]
8) COMPUTER SCIENCE Short Answer What term describes the number of pixels contained on a display monitor, expressed in terms of the number pixels on the horizontal axis and the number on the vertical axis?  

text[[144, 873, 368, 891]]
ANSWER: RESOLUTIONsub_title[[499, 88, 585, 106]]
## TOSS-UP  

text[[140, 123, 933, 144]]
9) PHYSICS Multiple Choice Which of the following is NOT true about the index of refraction:  

text[[143, 159, 642, 230]]
W) it has no units 
X) the refractive index for air is lower than glass 
Y) optical devices take advantage of it to improve resolution 
Z) the refractive index for oil is lower than air  

text[[142, 245, 800, 265]]
ANSWER: Z) THE REFRACTIVE INDEX FOR OIL IS LOWER THAN AIR  

sub_title[[507, 281, 577, 299]]
## BONUS  

text[[143, 315, 936, 369]]
9) PHYSICS Short Answer To the nearest whole number and in kilometers per hour, what is the speed of a frog swimming at a constant 10 kilometers per hour directly across a river that has a downstream current of 4 kilometers per hour?  

text[[143, 384, 264, 402]]
ANSWER: 11  

text[[143, 404, 574, 427]]
( Solution: speed \(= \sqrt{10^{2} + 4^{2}} = \sqrt{116} = 10.8 \mathrm{km / hr})\)  

sub_title[[500, 480, 585, 498]]
## TOSS-UP  

text[[144, 514, 910, 551]]
10) CHEMISTRY Short Answer A chemical reaction between a fat and a base that produces a soap is generally known as what type of reaction?  

text[[144, 566, 409, 585]]
ANSWER: SAPONIFICATION  

sub_title[[507, 602, 577, 620]]
## BONUS  

text[[144, 636, 836, 656]]
10) CHEMISTRY Multiple Choice Which of the following solutions are immiscible:  

text[[143, 672, 438, 743]]
W) carbon tetrachloride and octane 
X) ethanol and water 
Y) carbon tetrachloride and water 
Z) sulfuric acid and water  

text[[143, 758, 666, 777]]
ANSWER: Y) CARBON TETRACHLORIDE AND WATERsub_title[[499, 88, 585, 106]]
## TOSS-UP  

text[[143, 123, 877, 143]]
11) BIOLOGY Short Answer In what part of the chloroplast is Photosystem Two located?  

text[[144, 158, 936, 178]]
ANSWER: THYLAKOID MEMBRANE (ACCEPT: THYLAKOID STACK OR THYLAKOIDS)  

sub_title[[506, 194, 577, 211]]
## BONUS  

text[[144, 228, 912, 265]]
11) BIOLOGY Multiple Choice Which of the following vegetations is NOT properly matched with its biome:  

text[[144, 281, 580, 352]]
W) gymnosperms and boreal forest 
X) C4 plants and deserts 
Y) eucalyptus and temperate rain forest 
Z) deciduous forest and Taiga (Pronunciation: tie-ga)  

text[[144, 385, 598, 404]]
ANSWER: Z) DECIDUOUS FOREST AND TAIGA  

sub_title[[500, 455, 584, 473]]
## TOSS-UP  

text[[144, 490, 920, 526]]
12) ASTRONOMY Short Answer How far away, in parsecs, is a star with a parallax of 0.25 arc seconds?  

text[[144, 543, 256, 560]]
ANSWER: 4  

text[[144, 578, 411, 596]]
(Solution: distance \(= 1\) / parallax)  

sub_title[[506, 612, 577, 630]]
## BONUS  

text[[144, 647, 933, 700]]
12) ASTRONOMY Short Answer Assuming there was a full moon was at 11:30 PM at a given place on April \(7^{\mathrm{th}}\) of a certain year, what date would the full moon occur in the following month?  

text[[144, 714, 468, 735]]
ANSWER: MAY \(6^{\mathrm{TH}}\) (ACCEPT: \(6^{\mathrm{th}}\) )sub_title[[499, 90, 584, 107]]
## TOSS-UP  

text[[145, 123, 920, 179]]
13) MATH Multiple Choice Which of the following best describes a curve generated by a point on the circumference of a circle which rolls on the inside of a fixed circle and whose rolling circle has a diameter one-fourth of that of the fixed circle:  

text[[144, 194, 295, 266]]
W) hypercycloid 
X) epicycloid 
Y) hypocycloid 
Z) astroid  

text[[144, 281, 380, 300]]
ANSWER: Z) ASTROID  

sub_title[[507, 316, 577, 334]]
## BONUS  

text[[144, 353, 881, 390]]
13) MATH Short Answer Find the solution set of the following inequality: \(\frac{(-x + 3)}{4} > - \frac{2}{3}\)  

text[[144, 408, 300, 445]]
ANSWER: \(x< \frac{17}{3}\)  

sub_title[[500, 499, 584, 517]]
## TOSS-UP  

text[[144, 532, 921, 570]]
14) EARTH SCIENCE Multiple Choice Which of the following minerals is used as the primary ore of lead:  

text[[144, 585, 258, 656]]
W) graphite 
X) galena 
Y) bauxite 
Z) hematite  

text[[144, 672, 375, 691]]
ANSWER: X) GALENA  

sub_title[[507, 708, 577, 725]]
## BONUS  

text[[144, 742, 920, 779]]
14) EARTH SCIENCE Multiple Choice Pedogeography is a branch of science that involves the study of the geographic distribution of:  

text[[144, 794, 240, 865]]
W) fossils 
X) soils 
Y) rivers 
Z) trees  

text[[144, 881, 350, 900]]
ANSWER: X) SOILSsub_title[[499, 90, 584, 107]]
## TOSS-UP  

text[[144, 124, 933, 161]]
15) GENERAL SCIENCE Multiple Choice Operant conditioning is most notably concerned with which of the following:  

text[[144, 177, 653, 247]]
W) stimulus response mechanisms 
X) responses influenced by the consequences of the responses 
Y) Hull's postulate theorem approach to theorizing 
Z) theoretical aspects of personality such as free will  

text[[144, 263, 839, 299]]
ANSWER: X) RESPONSES INFLUENCED BY THE CONSEQUENCES OF THE RESPONSES  

sub_title[[507, 316, 577, 334]]
## BONUS  

text[[144, 350, 899, 387]]
15) GENERAL SCIENCE Multiple Choice A severe and chronic deficiency in what vitamin causes the disease known as beriberi:  

text[[144, 402, 270, 472]]
W) thiamine 
X) niacin 
Y) vitamin C 
Z) vitamin D  

text[[144, 489, 391, 507]]
ANSWER: W) THIAMINE  

sub_title[[499, 523, 584, 542]]
## TOSS-UP  

text[[144, 558, 920, 612]]
16) COMPUTER SCIENCE Multiple Choice This more recent messaging protocol, for use via the internet, allows a client to access and manipulate electronic messages on a server as though they were saved locally:  

text[[144, 627, 245, 697]]
W) MIME 
X) FTP 
Y) HTTP 
Z) IMAP  

text[[144, 714, 344, 732]]
ANSWER: Z) IMAP  

text[[144, 749, 510, 767]]
(Solution: Internet Message Access Protocol)  

sub_title[[507, 783, 577, 801]]
## BONUS  

text[[144, 818, 910, 854]]
16) COMPUTER SCIENCE Short Answer SSL, a protocol developed by Netscape to transmit private documents through the internet, stands for what:  

text[[144, 870, 483, 888]]
ANSWER: SECURE SOCKETS LAYERsub_title[[500, 90, 585, 107]]
## TOSS-UP  

text[[144, 123, 741, 160]]
17) PHYSICS Multiple Choice Which of the following is NOT a type of lepton (PRON: LEP-tawn):  

text[[144, 177, 400, 250]]
W) electron 
X) kaon (PRON: KAY-on) 
Y) neutrino 
Z) muon (PRON: MEW-on)  

text[[144, 264, 351, 283]]
ANSWER: X) KAON  

sub_title[[507, 298, 577, 317]]
## BONUS  

text[[144, 333, 940, 388]]
17) PHYSICS Short Answer If a car, starting from rest, accelerates constantly at 4 meters/sec \(^2\) for 10 seconds and then undergoes a constant negative acceleration of \(-4\) meters/sec \(^2\) for 3 seconds, how fast is the car traveling, in meters/second, at the end of the 13 seconds?  

text[[144, 402, 265, 420]]
ANSWER: 28  

text[[144, 437, 508, 457]]
(Solution: \(\mathrm{V}_{\mathrm{f}} = \mathrm{V}_{\mathrm{o}} + \mathrm{at} = 40 + (- 4)\times (3) = 28)\)  

sub_title[[500, 508, 585, 527]]
## TOSS-UP  

text[[144, 543, 923, 579]]
18) CHEMISTRY Multiple Choice Which of these organic compounds has more than two rings in its molecular structure:  

text[[144, 595, 315, 667]]
W) xylene 
X) cholesterol 
Y) tetrahydrofuran 
Z) glycine  

text[[144, 682, 433, 701]]
ANSWER: X) CHOLESTEROL  

sub_title[[507, 717, 577, 735]]
## BONUS  

text[[144, 751, 895, 788]]
18) CHEMISTRY Short Answer When ethene undergoes hydrogenation in the presence of a catalyst, what compound is formed?  

text[[144, 804, 329, 821]]
ANSWER: ETHANEsub_title[[500, 90, 585, 107]]
## TOSS-UP  

text[[144, 124, 835, 144]]
19) BIOLOGY Short Answer Apoptosis is primarily under the control of what gene?  

text[[144, 159, 281, 177]]
ANSWER: P 53  

sub_title[[507, 194, 577, 212]]
## BONUS  

text[[144, 228, 886, 265]]
19) BIOLOGY Multiple Choice Which of the following is a rare amino acid but a common constituent of collagen:  

text[[144, 281, 580, 352]]
W) tyrosine (Pron: tie-row-seen) 
X) proline 
Y) 4-hydroxyproline (Pron: 4-hydroxy-pro-leen) 
Z) 2-iodotyrosine (Pron: 2-eye-od-oh-tie-row-seen)  

text[[144, 368, 491, 386]]
ANSWER: Y) 4-HYDROXYPROLINE  

sub_title[[500, 437, 585, 456]]
## TOSS-UP  

text[[140, 472, 940, 492]]
20) MATH Multiple Choice Which of the following is considered an even trigonometric function:  

text[[144, 508, 255, 578]]
W) sine 
X) cosine 
Y) tangent 
Z) cosecant  

text[[144, 594, 365, 612]]
ANSWER: X) COSINE  

sub_title[[507, 630, 577, 647]]
## BONUS  

text[[144, 664, 880, 700]]
20) MATH Short Answer Given the following sets of points, Q (0, 0) and P (6, 5), find the distance between them:  

text[[144, 717, 434, 738]]
ANSWER: \(\sqrt{61}\) (ACCEPT: 7.81)  

text[[144, 756, 610, 779]]
(Solution: \(r^{2} = (x_{1} - 0)^{2} + (y_{1} - 0)^{2}; = (6)^{2} + (5)^{2}; = \sqrt{61}\) )sub_title[[500, 90, 584, 107]]
## TOSS-UP  

text[[144, 124, 937, 161]]
21) EARTH SCIENCE Multiple Choice Deserts lying immediately east of the Cascade and Sierra Nevada mountain ranges are examples of what type of desert:  

text[[144, 178, 281, 248]]
W) coastal 
X) continental 
Y) rainshadow 
Z) subtropical  

text[[144, 264, 428, 282]]
ANSWER: Y) RAINSHADOW  

sub_title[[507, 299, 577, 316]]
## BONUS  

text[[144, 333, 912, 387]]
21) EARTH SCIENCE Multiple Choice The mistral, a cold, dry wind that flows under the influence of gravity down the Rhone Valley in France and out onto the Mediterranean sea, is an example of what type of wind:  

text[[144, 403, 264, 473]]
W) Chinook 
X) polar 
Y) katabatic 
Z) sea breeze  

text[[144, 490, 407, 508]]
ANSWER: Y) KATABATIC  

sub_title[[500, 560, 584, 578]]
## TOSS-UP  

text[[144, 594, 936, 630]]
22) GENERAL SCIENCE Multiple Choice Aflatoxin (Pron: aff-luh-toxin) is a toxin that is most likely found in which of the following:  

text[[144, 647, 325, 717]]
W) moldy nuts 
X) barbequed meats 
Y) processed meats 
Z) raw shellfish  

text[[144, 733, 423, 751]]
ANSWER: W) MOLDY NUTS  

sub_title[[507, 769, 577, 786]]
## BONUS  

text[[144, 803, 940, 839]]
22) GENERAL SCIENCE Short Answer What is the alternate common term for the f-number in a typical camera lens?  

text[[144, 855, 561, 873]]
ANSWER: APERTURE (ACCEPT: DIAMETER)sub_title[[500, 89, 584, 107]]
## TOSS-UP  

text[[143, 123, 901, 160]]
23) PHYSICS Multiple Choice In Planck's equation \(\mathrm{E} = h\nu\) , (pronounced: E equals h new), \(h\) represents which of the following:  

text[[144, 177, 496, 247]]
W) photon energy in joules 
X) photon speed in kilometers per second 
Y) Planck's constant 
Z) the quantum energy of a single electron  

text[[144, 263, 500, 282]]
ANSWER: Y) PLANCK'S CONSTANT  

sub_title[[507, 298, 577, 316]]
## BONUS  

text[[144, 333, 904, 370]]
23) PHYSICS Multiple Choice Which of the following types of materials make the best high-temperature superconductors:  

text[[144, 386, 288, 455]]
W) metals 
X) non-metals 
Y) gasses 
Z) transuranics  

text[[144, 472, 422, 490]]
ANSWER: X) NON-METALS  

sub_title[[500, 542, 584, 560]]
## TOSS-UP  

text[[144, 576, 886, 613]]
24) CHEMISTRY Multiple Choice Which of the following is the most accurate name for a molecule of glycerol with all three hydroxyl groups esterified to fatty acids:  

text[[144, 629, 319, 700]]
W) triacylglycerol 
X) fatty glycerol 
Y) esterified lipid 
Z) triesterglyceride  

text[[144, 715, 483, 733]]
ANSWER: W) TRIACYLGLYCEROL  

sub_title[[507, 750, 577, 768]]
## BONUS  

text[[144, 785, 902, 839]]
24) CHEMISTRY Short Answer What is the general term for a cold-welding process for zinc coating of steel parts, which results in a thin, uniform zinc coating of controlled thickness?  

text[[144, 855, 819, 874]]
ANSWER: GALVANIZATION (ACCEPT: MECHANICAL GALVANIZATION)sub_title[[499, 88, 585, 106]]
## TOSS-UP  

text[[142, 123, 937, 160]]
25) BIOLOGY Short Answer Ergocalciferol (Pron: er-go-kal-sif-er-ol) and cholecalciferol (Pron: kol-kal-sif-er-ol) are names for two forms of what vitamin?  

text[[144, 176, 350, 195]]
ANSWER: VITAMIN D  

sub_title[[507, 211, 577, 229]]
## BONUS  

text[[142, 245, 927, 283]]
25) BIOLOGY Multiple Choice Which of the following plants fixes \(\mathrm{CO}_{2}\) by crusulacean (Pron: krass-you-lay-see-un) acid metabolism:  

text[[144, 298, 385, 370]]
W) sedum (Pron: see-dum) 
X) water lily 
Y) parsley 
X) tomato  

text[[144, 386, 364, 404]]
ANSWER: W) SEDUM