
## ROUND 8  


## TOSS-UP  


1) PHYSICS Short Answer What are the two components of velocity?  


ANSWER: SPEED AND DIRECTION  


## BONUS  


1) PHYSICS Multiple Choice Neutrinos are named in which of the following ways:  


W) after their successive discovery dates  
X) based on the particles they are linked with  
Y) based on the Greek letters that describe their relative energies  
Z) based on their charges and masses  


ANSWER: X) BASED ON THE PARTICLES THEY ARE LINKED WITH  


## TOSS-UP  


2) CHEMISTRY Short Answer What is the systematic name for the compound \(\mathrm{N}_2\mathrm{O}\) ?  


ANSWER: NITROUS OXIDE  


## BONUS  


2) CHEMISTRY Short Answer What is the common name for the following compound: a benzene ring with an OH group attached to carbon #1, a bromine attached to carbon #2, and a bromine attached to carbon #4  


ANSWER: 2,4- DIBROMOPHENOL
## TOSS-UP  


3) BIOLOGY Multiple Choice Transferal of immunity from breast milk to the infant is an example of:  


W) passive immunity 
X) active immunity 
Y) cell mediated immunity 
Z) paternal immunity  


ANSWER: W) PASSIVE IMMUNITY  


## BONUS  


3) BIOLOGY Multiple Choice The term pulmonic stenosis refers most specifically to:  


W) pneumonia 
X) an occluded coronary artery 
Y) a blocked pulmonary valve 
Z) hypertrophy of the pulmonary valves  


ANSWER: Y) A BLOCKED PULMONARY VALVE  


## TOSS-UP  


4) ASTRONOMY Short Answer What is the standard spectral classification letter for the Sun?  


ANSWER: G  


## BONUS  


4) ASTRONOMY Short Answer Edwin Hubble devised a system, sometimes called a tuning fork classification, to differentiate what type of celestial bodies?  


ANSWER: GALAXIES
## TOSS-UP  


5) MATH Short Answer In the graph of a curve such as the cosecant curve, the straight vertical line to which the curve moves closer and closer is called what:  


ANSWER: ASYMPTOTE  


## BONUS  


5) MATH Short Answer What is the \(10^{\mathrm{th}}\) term in the following arithmetic progression: 2, 7, 12...  


ANSWER: 47  


(Solution: \(\mathrm{a_n} = 2 + (10 - 1)5\)  


## TOSS-UP  


6) EARTH SCIENCE Multiple Choice During the last 18,000 years, nearly all coasts have experienced:  


W) submergence 
X) emergence 
Y) world wide decrease in sea level 
Z) relatively unchanging sea levels  


ANSWER: W) SUBMERGENCE  


## BONUS  


6) EARTH SCIENCE Short Answer What is the name given to a circular or horseshoe-shaped organic reef growing on a submerged volcano, with an occasional small, low, coral sand island surrounding a shallow lagoon:  


ANSWER: ATOLL
## TOSS-UP  


7) GENERAL SCIENCE Multiple Choice Which of the following do archeologists and sociologists generally believe is the most important prerequisite to development of large cultural systems:  


W) technology 
X) writing 
Y) agriculture 
Z) a monetary system  


ANSWER: Y) AGRICULTURE  


## BONUS  


7) GENERAL SCIENCE Multiple Choice Which of the following is an example of a simple fruit:  


W) sour cherry 
X) pineapple 
Y) figs 
Z) raspberries  


ANSWER: W) SOUR CHERRY  


## TOSS-UP  


8) COMPUTER SCIENCE Multiple Choice Secondary storage refers to:  


W) processor cache 
X) hard drives 
Y) system memory 
Z) a CPU  


ANSWER: X) HARD DRIVES  


## BONUS  


8) COMPUTER SCIENCE Short Answer What is the three-bit natural binary code equivalent of the decimal value \(\frac{3}{8}\) ?  


ANSWER: 0.011
## TOSS-UP  


9) PHYSICS Short Answer What color would be produced when mixing magenta and yellow pigments?  


ANSWER: RED  


## BONUS  


9) PHYSICS Short Answer What is the centripetal force required for an 8 kilogram body traveling at 2 meters per second in a perfect circle with a radius of 2 meters?  


ANSWER: 16 NEWTONS  


(Solution: \(\mathrm{CF} = \mathrm{m v}^{2} / \mathrm{r} = 8 \mathrm{x} 2^{2} / 2 = 16\) )  


## TOSS-UP  


10) CHEMISTRY Short Answer What is its characteristic geometrical arrangement of a molecule that has a hybrid orbital set of four identical \(\mathrm{sp}^{3}\) (pronounced S,P, 3)?  


ANSWER: TETRAHEDRAL  


## BONUS  


10) CHEMISTRY Short Answer Order the following 4 gases found in the Earth's atmosphere from the greatest percent by volume of dry air to the least: carbon dioxide; argon; nitrogen; oxygen  


ANSWER: NITROGEN; OXYGEN; ARGON; CARBON DIOXIDE  


(Solution: \(\mathrm{N} = 70\%\) ; \(\mathrm{O} = 21\%\) ; \(\mathrm{Ar} = 0.93\%\) ; \(\mathrm{CO}_{2} = 0.036\%\) )
## TOSS-UP  


11) BIOLOGY Multiple Choice In which of the following areas of the human body is the zygomatic arch found:  


W) hip 
X) wrist 
Y) shoulder 
Z) head  


ANSWER: Z) HEAD  


## BONUS  


11) BIOLOGY Short Answer Finger nails are mostly composed of what protein?  


ANSWER: KERATIN  


## TOSS-UP  


12) ASTRONOMY Short Answer What is the common name for the group of seven brightest stars in Ursa Major?  


ANSWER: BIG DIPPER (ACCEPT: PLOUGH)  


## BONUS  


12) ASTRONOMY Short Answer What millimeter-sized silicate metal spheres are the most abundant component of chondrites (PRON: con-drights), making up between 50-80% by volume of this type of meteorite?  


ANSWER: CHONDRULES
## TOSS-UP  


13) MATH Short Answer A plane curve that is the locus of all points in the plane equidistant from a given point best describes what geometric figure?  


ANSWER: CIRCLE  


## BONUS  


13) MATH Short Answer Name two consecutive integers where three times the second plus the first equals 91:  


ANSWER: 22 AND 23 (must be in order)  


(Solution: \(3(\mathrm{n} + 1) + \mathrm{n} = 91\) )  


## TOSS-UP  


14) EARTH SCIENCE Multiple Choice Which of the following is NOT classified as a high-level cloud:  


W) altocumulus 
X) cirrocumulus 
Y) cirrostratus 
Z) cirrus  


ANSWER: W) ALTOCOMULUS  


## BONUS  


14) EARTH SCIENCE Multiple Choice The Namib desert of southwest Africa is an example of what type of desert:  


W) continental 
X) subtropical 
Y) rainshadow 
Z) coastal  


ANSWER: Z) COASTAL
## TOSS-UP  


15) GENERAL SCIENCE Short Answer Beekeepers typically use what substance to calm bees?  


ANSWER: SMOKE  


## BONUS  


15) GENERAL SCIENCE Short Answer What common substance used by bacteriologists has a different melting point and freezing point?  


ANSWER: AGAR AGAR (ACCEPT: AGAR)  


## TOSS-UP  


16) COMPUTER SCIENCE Multiple Choice When doing a hardware setup procedure on a computer, the operator is effectively writing to:  


W) ROM 
X) RAM 
Y) C-drive 
Z) volatile memory  


ANSWER: W) ROM  


## BONUS  


16) COMPUTER SCIENCE Multiple Choice What is the name for the high-speed serial bus developed by Apple and Texas Instruments that allows for the connection of up to 63 multiple devices, supports hot-swapping, and transfers data at rates of up to 400 megabits per second:  


W) USB port 
X) ISO 9660 
Y) FireWire 
Z) Hot Port  


ANSWER: Y) FIREWIRE
## TOSS-UP  


17) PHYSICS Short Answer What is the most common term for the motion that is associated with an object that moves without rotating?  


ANSWER: TRANSLATIONAL (ACCEPT: TRANSLATIONAL MOTION)  


## BONUS  


17) PHYSICS Short Answer What is the total capacitance, in microfarads rounded to the second decimal place, for four capacitors connected in series if each capacitor is rated at 1 microfarad?  


ANSWER: 0.25  


(Solution: \(\mathrm{Ct} = 1 / \#\) of capacitors; \(1 / 4 = 0.25\) )  


## TOSS-UP  


18) CHEMISTRY Short Answer Marble statues around the world have been eaten away as a result of acid rain and the production of what aqueous acid?  


ANSWER: SULFURIC ACID (ACCEPT: \(\mathrm{H}_2\mathrm{SO}_4\) )  


## BONUS  


18) CHEMISTRY Multiple Choice The correct name for the compound \(\mathrm{CH}_3\mathrm{OCH}_3\) is:  


W) dimethyl ether 
X) ethyl ether 
Y) acetone 
Z) dimethyloxide  


ANSWER: W) DIMETHYL ETHER
## TOSS-UP  


19) BIOLOGY Short Answer Aside from the four major blood types, what blood group in the USA is of the greatest clinical importance regarding agglutination (Pron: ag-glut-i-nation) reactions?  


ANSWER: RH (ACCEPT: RH FACTOR OR RH GROUP OR RH ANTIGENS)  


## BONUS  


19) BIOLOGY Multiple Choice Multiplication is to differentiation as growth is to:  


W) molting 
X) division 
Y) apoptosis (Pron: apo-tosis) 
Z) development  


ANSWER: Z) DEVELOPMENT  


## TOSS-UP  


20) MATH Short Answer What is the formula for the volume of a right circular cone?  


ANSWER: \(\frac{1}{3}\pi r^{2}h\) (read as: one third pie r (or radius) squared h (or height))  


## BONUS  


20) MATH Short Answer To the first decimal place, what is the approximate length, in inches, of the arc that is cut off by an angle of \(\frac{\pi}{3}\) radians in a circle that has a radius of 4 inches:  


ANSWER: 4.2  


(Solution: \(\mathrm{S} = \alpha \times \mathrm{r};\frac{\pi}{3} (4) = 4.2)\)
## TOSS-UP  


21) EARTH SCIENCE Multiple Choice The now dormant volcanoes at Yellowstone National Park are examples of which of the following types of volcanoes:  


W) basaltic 
X) rhyolitic 
Y) andesitic 
Z) basaltic and andesitic  


ANSWER: X) RHYOLITIC  


## BONUS  


21) EARTH SCIENCE Multiple Choice Which of the following is classified as an intrusive igneous rock:  


W) gabbro 
X) obsidian 
Y) basalt 
Z) phyllite  


ANSWER: W) GABBRO  


## TOSS-UP  


22) GENERAL SCIENCE Short Answer In Freudian theory, what are the 3 divisions of the subconscious mind?  


ANSWER: ID, EGO, SUPEREGO  


## BONUS  


22) GENERAL SCIENCE Short Answer Classical conditioning was first studied by what Russian Nobel laureate physiologist?  


ANSWER: IVAN PAVLOV (ACCEPT: PAVLOV)
## TOSS-UP  


23) PHYSICS Short Answer Work is a product of two quantities whose SI units are what?  


ANSWER: METER AND NEWTON  


## BONUS  


23) PHYSICS Multiple Choice A 2.25 kilowatt engine is approximately the same as a:  


W) 3 horsepower engine  X) 33 horsepower engine  Y) 155 horsepower engine  Z) 366 horsepower engine  


ANSWER: W) 3 HORSEPOWER ENGINE  


(Solution: \(1 \mathrm{~hp} = 746 \mathrm{~W}\) )  


## TOSS-UP  


24) CHEMISTRY Short Answer What is the general term for a solid crystalline substance made of just one element or compound, such as halite or calcite, that are the constituents of rocks that make up the Earth?  


ANSWER: MINERAL  


## BONUS  


24) CHEMISTRY Short Answer What is the name for a long, calibrated glass tube with a tap at one end that is used vertically, with the tap at the bottom, and whose main use is as a reservoir for a chemical during titration?  


ANSWER: BURETTE
## TOSS-UP  


25) BIOLOGY Short Answer If whole blood is allowed to clot, what is the fluid that is remaining once the clot is removed?  


ANSWER: SERUM (DO NOT ACCEPT: PLASMA)  


## BONUS  


25) BIOLOGY Multiple Choice Which of the following is a monocot (Pron: mon-o-kot):  


W) Acer rubrum (Pron: ay-ser roo-brum) 
X) Quercus rubra (Pron: uer-kus roo-bra) 
Y) Triticum aestivum (Pron: Trit-e-cum A-stiv-e-um) 
Z) Echinacea angustifolia (Pron: eck-in-A-sha an-gust-ti-fowl-ia)  


ANSWER: Y) TRITICUM AESTIVUM