text[[250, 143, 744, 162]]
Icebreaker question: What is your favorite subject at school?  

sub_title[[456, 177, 541, 196]]
## TOSS-UP  

text[[115, 213, 879, 250]]
1) Physical Science – Short Answer Identify all of the following 3 compounds that are soluble in water: 1) Ammonium phosphate; 2) Lead (II) nitrate; 3) Barium sulfate.  

text[[115, 266, 329, 285]]
ANSWER: 1 AND 2 [NR]  

sub_title[[462, 301, 533, 319]]
## BONUS  

text[[115, 336, 857, 372]]
1) Physical Science – Short Answer The lower molar solubility of Iron (III) Hydroxide at a higher pH levels is a result of what phenomenon?  

text[[115, 388, 463, 407]]
ANSWER: COMMON ION EFFECT [NR]  

sub_title[[456, 460, 540, 478]]
## TOSS-UP  

text[[115, 495, 774, 514]]
2) Math – Multiple Choice Which of the following best describes a reflex angle?  

text[[115, 530, 595, 600]]
W) An angle whose measure is exactly equal to 180 degrees  
X) An angle whose measure is between 180 and 360 degrees  
Y) An angle whose measure is exactly equal to 360 degrees  
Z) An angle whose measure is greater than 360 degrees  

text[[115, 616, 840, 653]]
ANSWER: X) AN ANGLE WHOSE MEASURE IS BETWEEN 180 AND 360 DEGREES [NR]  

sub_title[[462, 669, 533, 687]]
## BONUS  

text[[115, 704, 875, 757]]
2) Math – Short Answer A 3-4-5 right triangle is constructed, and an altitude is drawn from the right angle to the hypotenuse. What is the difference in the lengths of the two sides produced by this altitude?  

text[[115, 774, 410, 793]]
ANSWER: 1.4 (ACCEPT: 7/5) [NR]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[114, 127, 879, 163]]
3) Life Science – Short Answer Parkinson’s disease is believed to be caused by a lack of what neurotransmitter in the brain?  

text[[115, 181, 360, 199]]
ANSWER: DOPAMINE [DB]  

sub_title[[463, 216, 533, 234]]
## BONUS  

text[[115, 250, 863, 287]]
3) Life Science – Short Answer Identify all of the following 3 plant groups in which the sporophyte is dominant in the alternation of generations: 1) Angiosperms; 2) Ferns; 3) Mosses.  

text[[115, 303, 328, 322]]
ANSWER: 1 AND 2 [DB]  

sub_title[[456, 372, 541, 390]]
## TOSS-UP  

text[[115, 407, 881, 444]]
4) Earth and Space – Short Answer What is the name of the certain orbits in the main asteroid belt that are free of asteroids due to Jupiter’s gravitation?  

text[[115, 460, 420, 479]]
ANSWER: KIRKWOOD GAPS [DB]  

sub_title[[463, 496, 533, 514]]
## BONUS  

text[[115, 531, 879, 567]]
4) Earth and Space – Multiple Choice Which of the following geologic structures would NOT be formed by brittle deformation of the Earth’s crust?  

text[[115, 585, 255, 655]]
W) Folds X) Normal faults Y) Reverse faults Z) Joints  

text[[115, 672, 348, 691]]
ANSWER: W) FOLDS [DB]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[114, 127, 857, 163]]
5) Math - Short Answer What theorem states that for three integers a, b, and c, there are no integer solutions to the equation \(\mathrm{a}^{\wedge}\mathrm{k} + \mathrm{b}^{\wedge}\mathrm{k} = \mathrm{c}^{\wedge}\mathrm{k}\) for \(\mathrm{k} > 2\) ?  

text[[114, 180, 508, 199]]
ANSWER: FERMAT'S LAST THEOREM [CD]  

sub_title[[463, 216, 534, 234]]
## BONUS  

text[[114, 252, 857, 287]]
5) Math - Short Answer What are the possible values of x given that the determinant of the matrix with first row 6 minus x comma 3 and second row 2 comma 4 is 0?  

text[[114, 304, 281, 322]]
ANSWER: 9/2 [CD]  

sub_title[[456, 357, 540, 375]]
## TOSS-UP  

text[[114, 393, 882, 445]]
6) Physical Science - Multiple Choice A ring and a sphere, both with the same mass and radius, are rolling down the same inclined plane. Which of the following statements is true about these objects?  

text[[114, 462, 872, 533]]
W) The ring will reach the bottom first and will have more rotational kinetic energy 
X) The sphere will reach the bottom first and will have more rotational kinetic energy 
Y) The ring will reach the bottom first while the sphere will have more rotational kinetic energy 
Z) The sphere will reach the bottom first while the ring will have more rotational kinetic energy  

text[[114, 550, 880, 586]]
ANSWER: Z) THE SPHERE WILL REACH THE BOTTOM FIRST WHILE THE RING WILL HAVE MORE ROTATIONAL KINETIC ENERGY [CD]  

sub_title[[463, 604, 534, 621]]
## BONUS  

text[[114, 640, 880, 710]]
6) Physical Science - Short Answer Two identical marbles are rolling towards each other, the left marble moving at a speed of 3 meters per second to the right and the right marble moving at 2 meters per second to the left. At what speed, in meters per second, and in what direction, is the left marble moving after the collision if they collide elastically?  

text[[114, 727, 393, 745]]
ANSWER: 2 TO THE LEFT [CD]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 880, 198]]
7) Energy - Short Answer Scientists at Argonne National Lab are studying the characteristics of a healthy gut microbiome by studying the microorganisms within. One organism, E. coli resides in the intestines of many animals. When gram staining E. coli, it will appear pink due to a thin layer of what cell wall forming substance?  

text[[115, 215, 418, 233]]
ANSWER: PEPTIDOGLYCAN [DB]  

sub_title[[463, 250, 533, 268]]
## BONUS  

text[[115, 285, 860, 338]]
7) Energy - Multiple Choice Scientists at Pacific Northwest National Lab are conducting research on the intrusive igneous activity surrounding volcanoes. What type of vertical tabular intrusion cuts across many layers of rock?  

text[[115, 355, 222, 425]]
W) Laccolith X) Dike Y) Sill Z) Stock  

text[[115, 442, 328, 461]]
ANSWER: X) DIKE [DB]  

sub_title[[456, 513, 540, 531]]
## TOSS-UP  

text[[115, 548, 825, 584]]
8) Life Science - Short Answer In humans, the appendix is an example of what type of structure that no longer seems to have a purpose in the current form of an organism?  

text[[115, 600, 358, 618]]
ANSWER: VESTIGIAL [DB]  

sub_title[[463, 636, 533, 653]]
## BONUS  

text[[115, 671, 835, 707]]
8) Life Science - Short Answer What sequence of DNA found in the promoter region of eukaryotic genes allows RNA polymerase to initiate transcription?  

text[[115, 723, 354, 741]]
ANSWER: TATA BOX [DB]sub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[114, 127, 810, 163]]
9) Earth and Space – Multiple Choice What is the distance of a star whose parallax is measured to be 0.2 arcseconds?  

text[[114, 182, 255, 252]]
W) 0.2 parsecs 
X) 0.2 light years 
Y) 5 parsecs 
Z) 5 light years  

text[[115, 269, 382, 288]]
ANSWER: Y) 5 PARSECS [NR]  

sub_title[[463, 305, 533, 322]]
## BONUS  

text[[114, 340, 857, 376]]
9) Earth and Space – Multiple Choice What type of telescope most commonly suffers from the phenomenon known as chromatic aberration?  

text[[114, 393, 308, 464]]
W) Reflecting telescope 
X) Refracting telescope 
Y) Cassegrain telescope 
Z) Radio telescope  

text[[114, 481, 520, 500]]
ANSWER: X) REFRACTING TELESCOPE [NR]  

sub_title[[456, 552, 540, 570]]
## TOSS-UP  

text[[114, 587, 867, 671]]
10) Math – Multiple Choice Jeffery is given a line segment from which he, using a compass, draws 2 circles whose center is at each endpoint of the segment and whose radius is more than half of the length of the line. With a straightedge, he then draws the line resulting from the intersections of the two circles. Which of the following best describes the figure he has produced?  

text[[114, 688, 318, 756]]
W) Parallel line 
X) Angle bisector 
Y) Equilateral triangle 
Z) Perpendicular bisector  

text[[114, 772, 540, 790]]
ANSWER: Z) PERPENDICULAR BISECTOR [NR]  

sub_title[[463, 808, 533, 825]]
## BONUS  

text[[114, 842, 792, 860]]
10) Math – Short Answer In simplest radical form, calculate the sine of 75 degrees.  

text[[114, 877, 672, 895]]
ANSWER: THE QUANTITY ROOT 6 PLUS ROOT 2 OVER 4 [NR]  

text[[114, 896, 850, 930]]
11) Physical Science – Short Answer The strength of Van der Waals intermolecular forces vary with distance to what power?sub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[115, 145, 272, 164]]
ANSWER: - 6 [CD]  

sub_title[[463, 181, 533, 199]]
## BONUS  

text[[115, 216, 875, 253]]
11) Physical Science – Multiple Choice Which of the following statements is NOT true about London Dispersion Forces?  

text[[115, 270, 643, 341]]
W) They act on all molecules  X) They act more strongly on molecules with large surface areas  Y) They act more strongly on cyclic molecules than branched ones  Z) They are caused by induced instantaneous dipoles  

text[[115, 358, 797, 394]]
ANSWER: Y) THEY ACT MORE STRONGLY ON CYCLIC MOLECULES THAN BRANCHED ONES [CD]  

sub_title[[456, 446, 540, 464]]
## TOSS-UP  

text[[115, 481, 863, 534]]
12) Energy – Short Answer Scientists at Idaho National Lab are studying magnetism. What temperature is defined to be the point at which a permanent magnet loses its ferromagnetic properties and instead becomes paramagnetic?  

text[[115, 551, 380, 570]]
ANSWER: CURIE POINT [CD]  

sub_title[[463, 587, 533, 605]]
## BONUS  

text[[115, 622, 844, 658]]
12) Energy – Multiple Choice Scientists at Lawrence Berkeley National Lab are studying dark matter. Which of the following is a candidate for the composition of dark matter?  

text[[115, 675, 238, 746]]
W) Positrons  X) WIMPs  Y) Antiprotons  Z) Neutrinos  

text[[115, 764, 348, 782]]
ANSWER: X) WIMPS [CD]sub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[115, 127, 864, 164]]
13) Life Science – Multiple Choice A polyp and medusa life stage is characteristic of which of the following taxonomic phylums?  

text[[115, 181, 225, 252]]
W) Cnidaria 
X) Nematoda 
Y) Porifera 
Z) Annelida  

text[[116, 270, 383, 288]]
ANSWER: W) CNIDARIA [DB]  

sub_title[[463, 305, 534, 323]]
## BONUS  

text[[116, 340, 848, 393]]
13) Life Science – Short Answer The formation of a cleavage furrow is indicative of cytokinesis in the eukaryotic cell. The cleavage furrow is analogous to the formation of what structure in plant cytokinesis?  

text[[116, 410, 372, 428]]
ANSWER: CELL PLATE [DB]  

sub_title[[456, 481, 540, 499]]
## TOSS-UP  

text[[115, 516, 844, 552]]
14) Earth and Space – Multiple Choice Which of the following types of weather satellites orbit parallel to Earth’s meridian lines?  

text[[115, 570, 277, 641]]
W) Polar- orbiting 
X) Geosynchronous 
Y) Diurnal 
Z) Doppler  

text[[115, 658, 451, 677]]
ANSWER: W) POLAR- ORBITING [DB]  

sub_title[[463, 694, 534, 712]]
## BONUS  

text[[115, 729, 826, 781]]
14) Earth and Space – Short Answer What is the term for the distinctively layered mats composed of slimy materials secreted by ancient cyanobacteria that provide evidence for precambrian life?  

text[[115, 799, 418, 817]]
ANSWER: STROMATOLITES [DB]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 872, 163]]
15) Math - Short Answer What are the lines of symmetry of the hyperbola with equation \(x^{\wedge}2\) over 16 minus \(y^{\wedge}2\) over \(36 = 1\) ?  

text[[115, 181, 350, 200]]
ANSWER: \(\mathbf{x} = 0\) ; \(\mathbf{y} = 0\) [CD]  

sub_title[[464, 216, 535, 234]]
## BONUS  

text[[115, 252, 880, 306]]
15) Math - Short Answer The point (2, 3) is reflected about the line \(\mathbf{y} = \mathbf{x} - 2\) , and then rotated 60 degrees counterclockwise about the origin. What is the new distance between the origin and the point after these transformations?  

text[[115, 323, 268, 341]]
ANSWER: 5 [CD]  

sub_title[[456, 393, 541, 410]]
## TOSS-UP  

text[[115, 428, 864, 464]]
16) Physical Science - Short Answer Name all of the following three particles which have a spin of zero:  

text[[144, 483, 275, 536]]
1. Neutrino 
2. Photon 
3. Higgs boson  

text[[115, 551, 328, 570]]
ANSWER: 3 ONLY [CD]  

sub_title[[464, 587, 535, 604]]
## BONUS  

text[[115, 622, 870, 677]]
16) Physical Science - Short Answer A torsional spring has a period of pi/2 seconds and a maximum angular displacement of 2pi radians. Giving your answer in terms of pi as necessary, what is the maximum angular acceleration, in radians per second squared, of the spring?  

text[[115, 694, 293, 712]]
ANSWER: 32pi [CD]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 877, 181]]
17) Energy – Multiple choice Scientists at Pacific Northwest National Lab are researching the internal igneous activity of the Laramide orogeny. Orogenesis most often occurs along which of the following types of plate boundaries?  

text[[115, 199, 240, 269]]
W) Convergent 
X) Divergent 
Y) Transform 
Z) Fault  

text[[115, 286, 419, 305]]
ANSWER: W) CONVERGENT [DB]  

sub_title[[456, 322, 528, 340]]
## BONUS  

text[[115, 357, 880, 428]]
17) Energy – Short Answer Scientists at Brookhaven National Lab are utilizing underwater nuclear reactions to study the Cherenkov radiation emitted by charged particles when they pass through mediums at speeds greater than the phase velocity of light. Identify all of the following 3 particles that do NOT have an electric charge: 1) Neutrinos; 2) Muons; 3) Electrons.  

text[[115, 445, 325, 463]]
ANSWER: 1 ONLY [DB]  

sub_title[[448, 516, 534, 535]]
## TOSS-UP  

text[[115, 551, 815, 587]]
18) Life Science – Short Answer What non-coding segments of DNA that lie between coding regions are cleaved before DNA translation?  

text[[115, 604, 341, 622]]
ANSWER: INTRONS [DB]  

sub_title[[456, 640, 528, 657]]
## BONUS  

text[[115, 675, 777, 694]]
18) Life Science – Multiple Choice Which of the following amino acids is polar?  

text[[115, 711, 260, 782]]
W) Phenylalanine 
X) Tryptophan 
Y) Serine 
Z) Valine  

text[[115, 800, 351, 818]]
ANSWER: Y) SERINE [NR]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 872, 163]]
19) Earth and Space – Short Answer What is the name of the phenomenon that explains how the rotation of an electrically conducting fluid can sustain a magnetic field?  

text[[115, 181, 420, 199]]
ANSWER: DYNAMO EFFECT [NR]  

sub_title[[463, 216, 533, 234]]
## BONUS  

text[[115, 252, 875, 288]]
19) Earth and Space – Multiple Choice The Chandrasekhar limit gives the maximum possible mass of which of the following celestial objects?  

text[[115, 305, 245, 377]]
W) White dwarf X) Neutron star Y) Red giant Z) Black hole  

text[[115, 394, 425, 412]]
ANSWER: W) WHITE DWARF [NR]  

sub_title[[456, 464, 541, 482]]
## TOSS-UP  

text[[115, 499, 840, 535]]
20) Math – Multiple Choice Given the function f of x equals 2x cubed plus 8, what is the value of f inverse of 136?  

text[[115, 553, 160, 622]]
W) 4 X) 6 Y) 8 Z) 10  

text[[115, 640, 296, 659]]
ANSWER: W) 4 [NR]  

sub_title[[463, 676, 533, 694]]
## BONUS  

text[[115, 712, 872, 747]]
20) Math – Short Answer If a sphere must have the same volume and surface area, what must the diameter of the sphere be?  

text[[115, 765, 266, 783]]
ANSWER: 6 [NR]sub_title[[455, 90, 540, 108]]
## TOSS-UP  

text[[113, 127, 841, 163]]
21) Physical Science – Multiple Choice Which of the following molecules has the lowest bond angle for the central atom?  

text[[114, 181, 270, 252]]
W) Carbon dioxide 
X) Ammonia 
Y) Water 
Z) Methane  

text[[115, 270, 306, 288]]
ANSWER: Y) WATER  

sub_title[[462, 305, 533, 323]]
## BONUS  

text[[114, 340, 871, 411]]
21) Physical Science – Short Answer A scientist is attempting to find the electric potential of a Galvanic cell by comparing the elements at the anode and cathode with gaseous hydrogen. He finds that the anode has a potential of 1.5 volts and the cathode has a potential of 0.8 volts. In volts, what is the reduction potential of hydrogen?  

text[[115, 427, 266, 446]]
ANSWER: 0 [NR]  

sub_title[[455, 499, 540, 517]]
## TOSS-UP  

text[[115, 534, 857, 587]]
22) Earth and Space – Multiple Choice Which of the following is the boundary that defines the region of space around a black hole from which nothing can escape from the black hole’s tidal forces?  

text[[115, 605, 311, 675]]
W) Singularity 
X) Schwarzschild radius 
Y) Event horizon 
Z) Hubble radius  

text[[115, 692, 439, 711]]
ANSWER: Y) EVENT HORIZON [DB]  

sub_title[[462, 728, 533, 746]]
## BONUS  

text[[115, 763, 872, 817]]
22) Earth and Space – Short Answer Identify all of the following 3 events in which one could possibly observe the Baily’s Beads effect: 1) Total solar eclipse; 2) Partial solar eclipse; 3) Annular solar eclipse.  

text[[115, 834, 327, 852]]
ANSWER: 1 AND 3 [DB]sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 863, 181]]
23) Life Science - Short Answer Sanjay the athlete is running the mile. When he is running, what viscous fluid in his knee joint reduces friction between the bones, allowing Sanjay to fluidly run his mile?  

text[[115, 198, 418, 216]]
ANSWER: SYNOVIAL FLUID [DB]  

sub_title[[463, 234, 533, 252]]
## BONUS  

text[[115, 269, 850, 306]]
23) Life Science - Short Answer Identify all of the following 3 binding sites on ribosomes that can hold tRNA molecules: 1) P site; 2) A site; 3) T site.  

text[[115, 323, 328, 341]]
ANSWER: 1 AND 2 [DB]