title[[299, 144, 697, 163]]
# Icebreaker question: What is your favorite food?  

sub_title[[456, 178, 541, 197]]
## TOSS-UP  

text[[115, 214, 844, 250]]
1) Physical Science – Short Answer A scientist measures the molar solubility of a lithium chloride salt to be 10 moles per liter. What is the Ksp of this salt?  

text[[116, 266, 286, 285]]
ANSWER: 100 [NR]  

sub_title[[462, 301, 533, 320]]
## BONUS  

text[[115, 336, 875, 389]]
1) Physical Science – Short Answer When performing an acid-base titration, there lies a point where the pH of the solution is equivalent to the pKa of the acid being titrated. What is the term used to describe this state?  

text[[115, 405, 855, 443]]
ANSWER: HALF-EQUIVALENCE POINT (DO NOT ACCEPT: EQUIVALENCE POINT) [NR]  

sub_title[[456, 495, 540, 513]]
## TOSS-UP  

text[[115, 530, 865, 566]]
2) Math – Multiple Choice Which of the following expressions can be used to find the slope of a tangent line at any value c for the function f of c equals c squared?  

text[[115, 582, 263, 652]]
W) C squared X) 2C Y) C cubed over 3 Z) 0  

text[[115, 669, 305, 688]]
ANSWER: X) 2C [NR]  

sub_title[[462, 705, 533, 723]]
## BONUS  

text[[115, 740, 870, 793]]
2) Math – Short Answer A gambler is offered to play a game where he receives two raised to the k minus one dollars if it takes k coin flips for the first tail to appear. If the price of the game should be equal to the game’s expected value, how much should it cost to play the game?  

text[[115, 809, 343, 828]]
ANSWER: INFINITY [NR]sub_title[[460, 90, 545, 108]]
## TOSS-UP  

text[[115, 124, 880, 178]]
3) Life Science - Short Answer Bill the ram is a ruminant whose diet mainly consists of grasses. In order to efficiently obtain as much nutrients from the grasses, ruminants have evolved to have a stomach that consists of how many chambers?  

text[[116, 195, 308, 213]]
ANSWER: FOUR [DB]  

sub_title[[462, 230, 533, 248]]
## BONUS  

text[[115, 265, 852, 302]]
3) Life Science - Short Answer Identify all of the following 3 animals that utilize positive pressure breathing: 1) Birds; 2) Frogs; 3) Humans.  

text[[116, 318, 327, 337]]
ANSWER: 2 ONLY [DB]  

sub_title[[456, 388, 540, 406]]
## TOSS-UP  

text[[113, 422, 870, 442]]
4) Earth and Space - Multiple Choice What term is given to the region where a river begins?  

text[[115, 459, 262, 530]]
W) Headwater 
X) Drainage basin 
Y) Tributary 
Z) Delta  

text[[115, 547, 410, 566]]
ANSWER: W) HEADWATER [DB]  

sub_title[[462, 583, 534, 601]]
## BONUS  

text[[115, 617, 863, 654]]
4) Earth and Space - Short Answer What type of pyroclastic material looks like little stones and are the size intermediate between volcanic ash and volcanic bombs?  

text[[115, 670, 518, 689]]
ANSWER: LAPILLI (ACCEPT: CINDERS) [DB]sub_title[[460, 91, 546, 108]]
## TOSS-UP  

text[[114, 124, 866, 161]]
5) Math – Short Answer What is the area between the curve and the x axis from 0 to 2 of the function y equals x?  

text[[115, 178, 267, 197]]
ANSWER: 2 [CD]  

sub_title[[462, 214, 534, 231]]
## BONUS  

text[[113, 248, 821, 268]]
5) Math – Short Answer What is the area between the curves \(y = 2x\) and \(y = x\) squared?  

text[[115, 284, 282, 303]]
ANSWER: 4/3 [CD]  

sub_title[[456, 356, 540, 373]]
## TOSS-UP  

text[[114, 390, 880, 460]]
6) Physical Science – Multiple Choice A circuit consisting of a battery in series with a resistor dissipates a power P. If a second parallel branch with the same resistance is added to this circuit, which of the following will be the new power dissipated, assuming the battery has no internal resistance?  

text[[114, 478, 175, 549]]
W) P/4 
X) P/2 
Y) P 
Z) 2P  

text[[115, 566, 301, 585]]
ANSWER: Z) 2P [CD]  

sub_title[[462, 602, 534, 620]]
## BONUS  

text[[115, 637, 857, 691]]
6) Physical Science – Short Answer Name all of the following three actions which will increase the voltage difference between the plates of a parallel-plate capacitor if the charge on each plate remains constant:  

text[[144, 708, 650, 761]]
1. Increasing the surface area of the plates of the capacitor  
2. Increasing the separation between the plates of the capacitor  
3. Adding a dielectric between the plates of the capacitor  

text[[115, 778, 327, 796]]
ANSWER: 2 ONLY [CD]sub_title[[460, 90, 545, 108]]
## TOSS-UP  

text[[115, 125, 870, 178]]
7) Energy – Short Answer Scientists at Princeton Plasma Physics Lab are researching Kuiper Belt objects and their relationship with Neptune. Along with Pluto, what Kuiper Belt objects share a 3:2 orbital resonance with Neptune?  

text[[116, 195, 350, 213]]
ANSWER: PLUTINOS [DB]  

sub_title[[462, 230, 533, 248]]
## BONUS  

text[[115, 265, 861, 319]]
7) Energy – Short Answer Scientists at Pacific Northwest National Lab are studying glacial features and how they provide evidence for past ice ages. Identify all of the following 4 glacial features that are depositional: 1) Cirques; 2) Drumlins; 3) Eskers; 4) Striations.  

text[[116, 335, 327, 353]]
ANSWER: 2 AND 3 [DB]  

sub_title[[456, 404, 540, 422]]
## TOSS-UP  

text[[115, 439, 822, 475]]
8) Life Science – Multiple Choice Which of the following statements is not true about enzymes?  

text[[115, 493, 662, 565]]
W) Enzymes can be allosterically modulated 
X) Enzymes increase the activation energy of a reaction 
Y) Enzymes are not consumed in the reaction with the substrate 
Z) Enzyme activity is dependent on the concentration of the substrate  

text[[115, 581, 880, 600]]
ANSWER: X) ENZYMES INCREASE THE ACTIVATION ENERGY OF A REACTION [NR]  

sub_title[[462, 616, 533, 634]]
## BONUS  

text[[115, 651, 816, 688]]
8) Life Science – Short Answer What taxonomic kingdom’s sexual life cycle involves producing haploid spores both sexually and asexually?  

text[[116, 704, 315, 722]]
ANSWER: FUNGI [DB]sub_title[[460, 91, 545, 108]]
## TOSS-UP  

text[[113, 124, 860, 160]]
9) Earth and Space – Multiple Choice What is the name of the cycle of 223 synodic months used to predict when eclipses will occur?  

text[[115, 178, 300, 250]]
W) Milankovitch cycle 
X) Sothic cycle 
Y) Metonic cycle 
Z) Saros cycle  

text[[115, 266, 413, 285]]
ANSWER: Z) SAROS CYCLE [NR]  

sub_title[[463, 302, 533, 320]]
## BONUS  

text[[113, 337, 875, 374]]
9) Earth and Space – Multiple Choice In the H-R diagram, in which of the following locations would the helium flash be observed?  

text[[115, 391, 275, 462]]
W) Hayashi track 
X) Subgiant branch 
Y) Instability strip 
Z) Red giant branch  

text[[115, 479, 472, 497]]
ANSWER: Z) RED GIANT BRANCH [NR]  

sub_title[[456, 550, 540, 567]]
## TOSS-UP  

text[[115, 584, 860, 620]]
10) Math – Multiple Choice What mathematical term is used to describe the situation when one correctly rejects a false null hypothesis?  

text[[115, 638, 245, 710]]
W) Type 1 error 
X) Power 
Y) P value 
Z) Type 2 error  

text[[115, 726, 350, 744]]
ANSWER: X) POWER [NR]  

sub_title[[463, 761, 533, 779]]
## BONUS  

text[[115, 797, 870, 832]]
10) Math – Short Answer Of the 8 roots of unity, what is the value of the root whose angle is between 120 and 150 degrees?  

text[[115, 849, 775, 868]]
ANSWER: NEGATIVE ROOT 2 OVER 2 PLUS ROOT 2 OVER 2 TIMES I [NR]  

text[[115, 885, 840, 921]]
11) Physical Science – Short Answer Arrange the following three atoms from smallest to largest in terms of their first ionization energy: 1) Carbon; 2) Nitrogen; 3) Oxygen.sub_title[[460, 90, 545, 108]]
## TOSS-UP  

text[[115, 125, 260, 142]]
ANSWER: 1, 3, 2  

sub_title[[462, 161, 533, 178]]
## BONUS  

text[[115, 196, 860, 231]]
11) Physical Science – Multiple Choice Which of the following sets of quantum numbers is not possible for an electron?  

text[[115, 248, 303, 319]]
W) 4, 0, negative 3, 1/2  X) 2, 1, 1, negative 1/2  Y) 1, 0, 0, negative 1/2  Z) 3, 2, 0, 1/2  

text[[115, 337, 425, 355]]
ANSWER: W) 4, 0 NEGATIVE 3, 1/2  

sub_title[[456, 408, 540, 426]]
## TOSS-UP  

text[[115, 443, 874, 514]]
12) Energy – Short Answer Scientists at Lawrence Berkeley National Lab are studying decay modes of atoms. One form of decay they are looking into is beta-minus decay, in which a neutron is converted to a proton and emits an electron and an electron antineutrino. What gauge boson mediates beta-minus decay?  

text[[115, 530, 415, 549]]
ANSWER: W MINUS BOSON [CD]  

sub_title[[462, 567, 534, 585]]
## BONUS  

text[[115, 602, 860, 638]]
12) Energy – Multiple Choice Scientists at Ames National Lab are investigating the strange quark. Which of the following hadrons must possess a strange quark?  

text[[115, 655, 228, 726]]
W) Neutron  X) Pion  Y) Kaon  Z) Antiproton  

text[[115, 743, 340, 761]]
ANSWER: Y) KAON [CD]sub_title[[460, 90, 545, 108]]
## TOSS-UP  

text[[115, 124, 833, 161]]
13) Life Science - Short Answer What central structure found in cnidarians functions in digestion and the circulation of substances throughout the body?  

text[[115, 177, 520, 197]]
ANSWER: GASTROVASCULAR CAVITY [DB]  

sub_title[[463, 212, 534, 231]]
## BONUS  

text[[115, 247, 861, 285]]
13) Life Science - Short Answer Identify all of the following 3 lake zones that would NOT be observed in a very shallow lake: 1) Littoral zone; 2) Limnetic zone; 3) Aphotic zone.  

text[[115, 301, 326, 321]]
ANSWER: 3 ONLY [DB]  

sub_title[[456, 372, 541, 390]]
## TOSS-UP  

text[[115, 407, 850, 444]]
14) Earth and Space - Short Answer What cycle, caused by continental rifts, describes the continuous opening and closing of ocean basins?  

text[[115, 460, 401, 479]]
ANSWER: WILSON CYCLE [DB]  

sub_title[[463, 495, 535, 514]]
## BONUS  

text[[115, 531, 875, 586]]
14) Earth and Space - Short Answer Karst topography is formed by the dissolution of soluble rocks. Identify all of the following 4 rocks that can form Karst landscapes: 1) Arkose; 2) Anhydrite; 3) Gypsum; 4) Limestone.  

text[[115, 601, 353, 620]]
ANSWER: 2, 3, AND 4 [DB]sub_title[[460, 91, 545, 108]]
## TOSS-UP  

text[[115, 124, 840, 160]]
15) Math – Multiple Choice Which of the following is true of the sum from n equals 1 to infinity of 1 over n?  

text[[115, 179, 383, 250]]
W) It converges to e 
X) It converges pi squared over 6 
Y) It converges to 2 
Z) It diverges  

text[[115, 266, 401, 285]]
ANSWER: Z) IT DIVERGES [CD]  

sub_title[[463, 302, 533, 320]]
## BONUS  

text[[115, 337, 867, 426]]
15) Math – Short Answer Aldric flips 100 fair coins. He correctly predicts that, on average, he will observe that 50 of these coins end up heads. However, the true result will likely not be exactly 50, and the results can instead be approximated as a normal distribution about the mean of 50. To the nearest integer, what is the standard deviation of the number of heads he will observe when flipping these coins?  

text[[115, 442, 267, 461]]
ANSWER: 5 [CD]  

sub_title[[456, 512, 541, 530]]
## TOSS-UP  

text[[115, 547, 872, 601]]
16) Physical Science – Multiple Choice When a block is placed at the top of an incline of angle 45 degrees, it just barely overcomes static friction to begin sliding down the ramp. Which of the following must be closest to the coefficient of static friction of this ramp?  

text[[115, 618, 174, 689]]
W) 0.7 
X) 1 
Y) 1.4 
Z) 1.7  

text[[115, 707, 293, 725]]
ANSWER: X) 1 [CD]  

sub_title[[463, 743, 533, 761]]
## BONUS  

text[[115, 778, 867, 831]]
16) Physical Science – Short Answer The acceleration of a body at time t is given by the function \(\mathrm{a(t) = 12t^{\wedge}2 - 8t + 3}\) . If the body has a mass of 2 kilograms, what is the impulse on the body, in kilogram meters per second, from time \(t = 1\) to \(t = 2\) ?  

text[[115, 848, 277, 866]]
ANSWER: 38 [CD]  

text[[115, 883, 844, 919]]
17) Energy – Short Answer Scientists at the Joint Genome Institute are collaborating with Lawrence Berkeley National Lab scientists to study the process of apoptosis in cancer cells.sub_title[[460, 91, 545, 108]]
## TOSS-UP  

text[[115, 125, 863, 160]]
Contrary to apoptosis, which is programmed cell death, what other form of cell death is caused by factors external to the cell?  

text[[115, 177, 350, 196]]
ANSWER: NECROSIS [DB]  

sub_title[[456, 214, 527, 231]]
## BONUS  

text[[115, 248, 866, 319]]
17) Energy – Short Answer Scientists at Pacific Northwest National Lab are researching the process of thunderstorm cloud formation and the processes that drive it. What process in clouds describes how suspended water droplets combine together to form larger droplets, eventually forming raindrops?  

text[[115, 335, 595, 355]]
ANSWER: COLLISION COALESCENCE PROCESS [DB]  

sub_title[[448, 407, 534, 425]]
## TOSS-UP  

text[[115, 442, 860, 479]]
18) Life Science – Multiple Choice Which of the following plants would most likely utilize CAM photosynthesis?  

text[[115, 496, 220, 566]]
W) Cacti 
X) Corns 
Y) Soybeans 
Z) Wheat  

text[[115, 584, 345, 602]]
ANSWER: W) CACTI [DB]  

sub_title[[456, 619, 527, 637]]
## BONUS  

text[[115, 654, 878, 691]]
18) Life Science – Short Answer What type of internal fertilization is most often seen in birds, in which the egg is laid outside of the female body?  

text[[115, 707, 361, 726]]
ANSWER: OVIPARITY [DB]sub_title[[460, 90, 546, 108]]
## TOSS-UP  

text[[115, 124, 836, 161]]
19) Earth and Space - Short Answer What is the name of the phenomenon that prevents neutron stars from collapsing into black holes?  

text[[115, 177, 880, 214]]
ANSWER: NEUTRON DEGENERACY PRESSURE (ACCEPT: DEGENERACY PRESSURE; DO NOT ACCEPT: ELECTRON DEGENERACY PRESSURE) [NR]  

sub_title[[461, 230, 534, 249]]
## BONUS  

text[[115, 265, 864, 303]]
19) Earth and Space - Multiple Choice Which of the following terms describes the wrinkle-ridge system commonly found on lunar maria?  

text[[115, 319, 243, 390]]
W) Dorsa X) Promontoria Y) Rilles Z) Rupes  

text[[115, 407, 353, 426]]
ANSWER: W) DORSA [NR]  

sub_title[[456, 478, 541, 496]]
## TOSS-UP  

text[[115, 513, 875, 550]]
20) Math - Multiple Choice At which of the following angles, in degrees, does the sine of the angle equal its cosine?  

text[[115, 567, 179, 637]]
W) 150 X) 180 Y) 225 Z) 270  

text[[115, 654, 312, 674]]
ANSWER: Y) 225 [NR]  

sub_title[[461, 690, 535, 709]]
## BONUS  

text[[113, 725, 762, 744]]
20) Math - Short Answer What is the value of the sum of the first 79 numbers?  

text[[115, 761, 296, 780]]
ANSWER: 3160 [NR]sub_title[[460, 90, 545, 108]]
## TOSS-UP  

text[[113, 123, 863, 159]]
21) Physical Science – Multiple Choice Which of the following statements is true regarding hydrogen bonding?  

text[[115, 173, 835, 239]]
W) Hydrogen bonding decreases the boiling point of a substance  
X) Hydrogen bonding forms the secondary and tertiary structures of lipids  
Y) Hydrogen bonding is an example of an induced dipole interaction  
Z) Hydrogen bonding requires hydrogen to be bonded with a strongly electronegative atom  

text[[115, 253, 876, 289]]
ANSWER: Z) HYDROGEN BONDING REQUIRES HYDROGEN TO BE BONDED WITH A STRONGLY ELECTRONEGATIVE ATOM [NR]  

sub_title[[463, 303, 533, 321]]
## BONUS  

text[[115, 336, 860, 371]]
21) Physical Science – Multiple Choice Which of the following compounds is considered a straight-chain alkene?  

text[[115, 386, 250, 452]]
W) Cyclohexane  
X) Toluene  
Y) Acetylene  
Z) Propene  

text[[115, 467, 368, 486]]
ANSWER: Z) PROPENE [NR]  

sub_title[[456, 517, 540, 535]]
## TOSS-UP  

text[[115, 549, 858, 584]]
22) Earth and Space – Multiple Choice Which of the following terms gives the measure for the largest particle size that a stream can carry?  

text[[115, 599, 242, 664]]
W) Capacity  
X) Competence  
Y) Adequacy  
Z) Capability  

text[[115, 680, 412, 698]]
ANSWER: X) COMPETENCE [DB]  

sub_title[[463, 714, 533, 731]]
## BONUS  

text[[115, 746, 866, 780]]
22) Earth and Space – Multiple Choice Which of the following depositional environments is the rock breccia most likely to form in?  

text[[115, 795, 562, 860]]
W) High-energy depositional environment such as rivers  
X) Low-energy depositional environment such as rivers  
Y) High-energy depositional environment such as deltas  
Z) Low-energy depositional environment such as deltas  

text[[115, 876, 875, 895]]
ANSWER: W) HIGH-ENERGY DEPOSITIONAL ENVIRONMENT SUCH AS RIVERS [DB]sub_title[[460, 90, 545, 108]]
## TOSS-UP  

text[[115, 124, 857, 161]]
23) Life Science – Short Answer What holes, located on the thorax and abdomen of insects such as grasshoppers, allow the insects to breathe?  

text[[115, 177, 360, 197]]
ANSWER: SPIRACLES [DB]  

sub_title[[463, 214, 533, 231]]
## BONUS  

text[[115, 248, 857, 285]]
23) Life Science – Short Answer What receptor organ located in the mammalian cochlea is responsible for the transduction of auditory signals?  

text[[115, 301, 420, 320]]
ANSWER: ORGAN OF CORTI [DB]