title[[256, 143, 740, 163]]
# Icebreaker question: What is your favorite field of science?  

sub_title[[456, 178, 541, 197]]
## TOSS-UP  

text[[115, 213, 880, 250]]
1) Physical Science – Short Answer In a voltaic battery, what part of the cell is responsible for the oxidation half-reaction?  

text[[115, 265, 325, 285]]
ANSWER: ANODE [NR]  

sub_title[[462, 301, 533, 320]]
## BONUS  

text[[115, 336, 870, 373]]
1) Physical Science – Short Answer What gas law states that the volume of a gas is inversely proportional to its pressure?  

text[[115, 388, 390, 408]]
ANSWER: BOYLE'S LAW [NR]  

sub_title[[456, 460, 541, 478]]
## TOSS-UP  

text[[115, 494, 880, 531]]
2) Math – Multiple Choice Which of the following numbers is the greatest common divisor of 20 and 68?  

text[[115, 547, 157, 616]]
W) 2 X) 4 Y) 6 Z) 8  

text[[115, 633, 293, 652]]
ANSWER: X) 4 [NR]  

sub_title[[462, 669, 533, 688]]
## BONUS  

text[[115, 704, 880, 776]]
2) Math – Short Answer Identify all of the following 3 statements that are true about triangles; 1) Their area can be calculated using Heron’s formula; 2) Triangles have exactly three sides and three vertices; 3) The Pythagorean theorem can be used to solve for a missing side in a right triangle.  

text[[115, 792, 295, 811]]
ANSWER: ALL [NR]sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 874, 164]]
3) Life Science – Short Answer What is the name for a diploid cell that forms when a haploid sperm fuses with a haploid egg?  

text[[115, 180, 335, 199]]
ANSWER: ZYGOTE [DB]  

sub_title[[462, 216, 533, 234]]
## BONUS  

text[[115, 250, 799, 287]]
3) Life Science – Multiple Choice The crossing over of genes between homologous chromosomes during meiosis occurs during which of the following stages?  

text[[115, 304, 240, 376]]
W) Prophase I 
X) Metaphase I 
Y) Anaphase I 
Z) Telophase I  

text[[115, 392, 397, 411]]
ANSWER: W) PROPHASE I [DB]  

sub_title[[456, 461, 540, 480]]
## TOSS-UP  

text[[115, 496, 860, 533]]
4) Earth and Space – Short Answer What crater-like volcanic feature typically forms after a volcano erupts and collapses?  

text[[115, 549, 348, 568]]
ANSWER: CALDERA [DB]  

sub_title[[462, 585, 533, 602]]
## BONUS  

text[[115, 619, 864, 672]]
4) Earth and Space – Short Answer In astronomy, declination in the sky is analogous to longitude on the surface of the Earth. What other measure in the sky is analogous to latitude on the surface of the Earth?  

text[[115, 689, 430, 708]]
ANSWER: RIGHT ASCENSION [DB]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[113, 127, 761, 146]]
5) Math – Short Answer In how many ways can 4 people be arranged in a line?  

text[[115, 162, 277, 181]]
ANSWER: 24 [CD]  

sub_title[[463, 199, 533, 217]]
## BONUS  

text[[115, 234, 863, 271]]
5) Math – Short Answer Two angles of a triangle are 50 degrees and 90 degrees. In degrees, What is the third angle of this triangle?  

text[[115, 287, 277, 306]]
ANSWER: 40 [CD]  

sub_title[[456, 357, 541, 375]]
## TOSS-UP  

text[[115, 393, 874, 430]]
6) Physical Science – Short Answer What quantity, whose SI base unit is the ampere, is equal to voltage divided by resistance in Ohm's Law?  

text[[115, 446, 348, 465]]
ANSWER: CURRENT [CD]  

sub_title[[463, 482, 533, 500]]
## BONUS  

text[[115, 517, 870, 571]]
6) Physical Science – Short Answer Two resistors are connected in series to a battery. If the resistors have resistances of 5 ohms and 3 ohms, what is the equivalent resistance of this circuit, in ohms, assuming the battery has no internal resistance?  

text[[115, 587, 266, 606]]
ANSWER: 8 [CD]sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 867, 181]]
7) Energy – Multiple Choice Scientists at Lawrence Livermore National Lab are studying states of matter. Which of the following states of matter has a definite volume but an indefinite shape?  

text[[115, 198, 200, 270]]
W) Solid 
X) Liquid 
Y) Gas 
Z) Plasma  

text[[115, 287, 350, 306]]
ANSWER: X) LIQUID [CD]  

sub_title[[462, 322, 533, 340]]
## BONUS  

text[[115, 357, 873, 427]]
7) Energy – Short Answer Scientists at Argonne National Lab are looking into the properties of group 17 on the Periodic table, the halogens. Identify all of the following 3 properties that characterize halogens: 1) Very reactive; 2) Nonmetallic; 3) Contain 6 valence electrons in their orbital shells.  

text[[116, 444, 328, 462]]
ANSWER: 1 AND 2 [DB]  

sub_title[[456, 514, 540, 532]]
## TOSS-UP  

text[[115, 549, 836, 585]]
8) Life science – Short Answer What biochemical reaction is responsible for joining two amino acids together by removing a water molecule?  

text[[115, 601, 510, 620]]
ANSWER: DEHYDRATION SYNTHESIS [DB]  

sub_title[[462, 636, 533, 655]]
## BONUS  

text[[115, 672, 870, 708]]
8) Life Science – Short Answer Sponges, krill, and baleen whales all gather food by utilizing what method of feeding that involves the straining of suspended particles?  

text[[115, 724, 411, 742]]
ANSWER: FILTER FEEDING [DB]  

text[[115, 900, 864, 935]]
9) Earth and Space – Multiple Choice Which of the following most accurately describes our Sun?  

text[[115, 944, 245, 960]]
NSB practice setssub_title[[456, 91, 540, 108]]
## TOSS-UP  

text[[114, 145, 285, 216]]
W) White dwarf star 
X) Red supergiant 
Y) Yellow dwarf star 
Z) Black hole  

text[[114, 234, 496, 253]]
ANSWER: Y) YELLOW DWARF STAR [NR]  

sub_title[[463, 270, 533, 288]]
## BONUS  

text[[114, 305, 867, 341]]
9) Earth and Space – Multiple Choice Which of the following pairs of astronomers created a diagram that shows the relationship between a star's absolute magnitude and its luminosity?  

text[[114, 358, 356, 429]]
W) Watson and Crick 
X) Henderson and Hasselbach 
Y) Michelson and Morley 
Z) Hertzsprung and Russell  

text[[114, 446, 558, 465]]
ANSWER: Z) HERTZSPRUNG AND RUSSELL [NR]  

sub_title[[456, 518, 540, 536]]
## TOSS-UP  

text[[114, 553, 836, 589]]
10) Math – Multiple Choice Which of the following regular polygons cannot completely tessellate a two-dimensional plane?  

text[[114, 606, 216, 677]]
W) Triangle 
X) Square 
Y) Pentagon 
Z) Hexagon  

text[[114, 694, 388, 712]]
ANSWER: Y) PENTAGON [NR]  

sub_title[[463, 712, 533, 729]]
## BONUS  

text[[114, 747, 878, 783]]
10) Math – Short Answer If it takes Edward 10 minutes to mow a lawn and Luke 8 minutes to mow a lawn, how long, in minutes, would it take to mow the lawn if they worked together?  

text[[114, 799, 545, 818]]
ANSWER: 40/9 (ACCEPT: 4 AND 4 NINTHS) [NR]  

text[[114, 835, 860, 871]]
11) Physical Science – Multiple Choice Which of the following is NOT a requirement for a body to be in equilibrium?  

text[[114, 888, 460, 958]]
W) The net force on the body must be zero 
X) The net torque on the body must be zero 
Y) The object must be stationary 
NSB practice setssub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[114, 127, 560, 146]]
Z) The rotational velocity of the object must be constant  

text[[115, 162, 617, 182]]
ANSWER: Y) THE OBJECT MUST BE STATIONARY [CD]  

sub_title[[464, 199, 533, 217]]
## BONUS  

text[[115, 234, 881, 288]]
11) Physical Science – Short Answer What is the angular acceleration, in radians per second squared, of a body with a moment of inertia of 2 kilogram meters squared when a constant torque of magnitude 80 newton meters is applied to it?  

text[[115, 304, 277, 323]]
ANSWER: 40 [CD]  

sub_title[[456, 375, 541, 393]]
## TOSS-UP  

text[[116, 410, 867, 464]]
12) Energy – Short Answer Scientists at Idaho National Lab have been investigating the role of different nitrogen isotopes on the growth of potatoes. Isotopes of the same element differ in their number of what subatomic particle?  

text[[116, 480, 362, 499]]
ANSWER: NEUTRONS [CD]  

sub_title[[464, 516, 534, 534]]
## BONUS  

text[[115, 552, 872, 588]]
12) Energy – Short Answer Scientists at Argonne National Lab are studying hydrogen atoms. How many neutrons are in the nuclei of the most common isotope of hydrogen atoms?  

text[[116, 604, 266, 623]]
ANSWER: 0 [CD]sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 866, 163]]
13) Life Science - Short Answer The fluid-mosaic model is a model that describes the fluid-like movement of proteins and glycolipids in what cell organelle?  

text[[115, 180, 850, 217]]
ANSWER: CELL MEMBRANE (ACCEPT: PLASMA MEMBRANE OR CYTOPLASMIC MEMBRANE) [DB]  

sub_title[[465, 234, 533, 252]]
## BONUS  

text[[115, 269, 830, 323]]
13) Life Science - Short Answer Identify all of the following 3 processes in cellular respiration that occur in the cytosol of the cell: 1) Krebs cycle; 2) Electron transport chain; 3) Glycolysis.  

text[[115, 340, 326, 358]]
ANSWER: 3 ONLY [DB]  

sub_title[[456, 409, 540, 427]]
## TOSS-UP  

text[[115, 445, 846, 499]]
14) Earth and Space - Multiple Choice A psychrometer, a tool consisting of two identical thermometers mounted side by side, would most likely be used to measure which of the following types of humidity?  

text[[115, 516, 217, 587]]
W) Relative X) Absolute Y) Saturated Z) Specific  

text[[115, 604, 382, 622]]
ANSWER: W) RELATIVE [DB]  

sub_title[[465, 640, 533, 658]]
## BONUS  

text[[115, 675, 866, 711]]
14) Earth and Space - Short Answer Order the following 3 eras in the Phanerozoic eon from earliest to latest: 1) Mesozoic; 2) Cenozoic; 3) Paleozoic.  

text[[115, 728, 305, 746]]
ANSWER: 3, 1, 2 [DB]  

text[[115, 871, 870, 906]]
15) Math - Short Answer Given that the surface area of a cube is 600 square meters, in cubic meters, what is the volume of the cube?  

text[[115, 922, 296, 959]]
ANSWER: 1000 [NR]  NSB practice setssub_title[[456, 90, 541, 108]]
## TOSS-UP  

sub_title[[463, 145, 535, 164]]
## BONUS  

text[[115, 180, 822, 218]]
15) Math – Short Answer What is the slope of the line perpendicular to one that passes through the points (2, -4) and (5, 8)?  

text[[115, 233, 435, 253]]
ANSWER: - 1/4 (ACCEPT: - 0.25) [NR]  

sub_title[[456, 304, 541, 322]]
## TOSS-UP  

text[[115, 339, 844, 376]]
16) Physical Science – Multiple Choice Which of the following elements is NOT a gas at room temperature?  

text[[115, 393, 215, 464]]
W) Carbon 
X) Nitrogen 
Y) Oxygen 
Z) Fluorine  

text[[115, 481, 370, 500]]
ANSWER: W) CARBON [NR]  

sub_title[[463, 517, 535, 535]]
## BONUS  

text[[115, 552, 866, 589]]
16) Physical Science – Short Answer What is the name of a property for a material that does not change regardless of the quantity of the material, such as melting point?  

text[[115, 604, 465, 623]]
ANSWER: INTENSIVE PROPERTY [NR]sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 868, 181]]
17) Energy – Short Answer Scientists at the AAAS are studying the origins of flowering plants and pollinators. When Steve the botanist observes a common daisy, in what flower organ would he most likely find the highest concentration of pollen?  

text[[115, 198, 336, 216]]
ANSWER: STAMEN [DB]  

sub_title[[456, 233, 526, 252]]
## BONUS  

text[[115, 269, 872, 322]]
17) Energy – Short Answer Scientists at Pacific Northwest National Lab are investigating the properties of regolith on the surface of Earth’s moon. In Earth’s soil profile, what soil horizon serves as the intermediate between the unweathered bedrock and the solum?  

text[[115, 340, 362, 358]]
ANSWER: C HORIZON [DB]  

sub_title[[448, 410, 533, 428]]
## TOSS-UP  

text[[115, 445, 847, 499]]
18) Life Science – Short Answer What is the name of the theory stating that all organisms develop through the natural selection of inherited variations that increase their fitness in a community?  

text[[115, 515, 700, 534]]
ANSWER: THEORY OF EVOLUTION (ACCEPT: EVOLUTION) [NR]  

sub_title[[456, 551, 526, 569]]
## BONUS  

text[[115, 586, 825, 622]]
18) Life Science – Multiple Choice The thylakoid membrane is present in which of the following organelles?  

text[[115, 640, 250, 710]]
W) Ribosome 
X) Mitochondria 
Y) Chloroplast 
Z) Nucleus  

text[[115, 728, 423, 746]]
ANSWER: Y) CHLOROPLAST [NR]sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 868, 163]]
19) Earth and Space – Short Answer What is the only planet in the solar system which has a slower rotation time than revolution time?  

text[[115, 180, 323, 199]]
ANSWER: VENUS [NR]  

sub_title[[463, 216, 534, 234]]
## BONUS  

text[[115, 251, 850, 288]]
19) Earth and Space – Multiple Choice Which of the following celestial bodies has Trojan asteroids orbiting around it?  

text[[115, 305, 211, 377]]
W) The sun 
X) Mars 
Y) Jupiter 
Z) Pluto  

text[[115, 393, 359, 412]]
ANSWER: X) JUPITER [NR]  

sub_title[[456, 464, 540, 482]]
## TOSS-UP  

text[[113, 499, 864, 536]]
20) Math – Short Answer What is the x-coordinate of the vertex of a parabola with equation \(y = x^2 + 4x - 5\) ?  

text[[115, 552, 273, 571]]
ANSWER: - 2 [CD]  

sub_title[[463, 588, 534, 606]]
## BONUS  

text[[115, 623, 876, 678]]
20) Math – Short Answer Name all of the following three statements which are true of parabolas: 1) They may have a degree of either one or two; 2) They must open either upwards or downwards; 3) Some parabolas have no vertex  

text[[115, 694, 401, 713]]
ANSWER: NONE OF THEM [CD]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[114, 127, 833, 163]]
21) Physical Science - Multiple Choice Which of the following statements is true of the gravitational force according to Newton's law of universal gravitation?  

text[[114, 181, 475, 252]]
W) It follows the inverse square law  X) It can be either attractive or repulsive  Y) It is independent of mass  Z) The gravitational constant is greater than 1  

text[[114, 269, 666, 288]]
ANSWER: W) IT FOLLOWS THE INVERSE SQUARE LAW [CD]  

sub_title[[462, 305, 533, 323]]
## BONUS  

text[[114, 340, 819, 394]]
21) Physical Science - Short Answer The gravitational force between two objects is F. Giving your answer in terms of F, what will the new gravitational force be if the distance between the objects is quadrupled and the mass of each object is doubled?  

text[[115, 410, 283, 429]]
ANSWER: F/4 [CD]  

sub_title[[456, 464, 541, 482]]
## TOSS-UP  

text[[114, 499, 785, 535]]
22) Earth and Space - Multiple Choice Which of the following minerals is NOT a metamorphic rock?  

text[[115, 553, 230, 622]]
W) Migmatite  X) Gneiss  Y) Basalt  Z) Slate  

text[[115, 640, 357, 659]]
ANSWER: Y) BASALT [DB]  

sub_title[[462, 676, 533, 694]]
## BONUS  

text[[115, 711, 852, 747]]
22) Earth and Space - Multiple Choice When comparing conditions observed during an El Niño event to normal conditions, which of the following best describes the difference?  

text[[115, 764, 448, 836]]
W) Strengthening of the west-to-east flow  X) Reversal of the west-to-east flow  Y) Strengthening of the east-to-west flow  Z) Reversal of the east-to-west flow  

text[[115, 853, 660, 871]]
ANSWER: Z) REVERSAL OF THE EAST- TO- WEST FLOW [DB]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[113, 127, 854, 164]]
23) Life Science – Multiple Choice Adipose tissue and blood are examples of which of the following types of tissues?  

text[[115, 181, 230, 252]]
W) Epithelial 
X) Nervous 
Y) Muscle 
Z) Connective  

text[[115, 270, 410, 288]]
ANSWER: Z) CONNECTIVE [DB]  

sub_title[[464, 305, 533, 322]]
## BONUS  

text[[115, 340, 848, 376]]
23) Life Science – Short Answer COVID-19, Lyme disease, and rabies are all examples of what types of disease that can be transferred to a human by other animals?  

text[[115, 393, 356, 411]]
ANSWER: ZOONOTIC [DB]