sub_title[[456, 143, 540, 161]]
## TOSS-UP  

text[[115, 178, 879, 250]]
1) Earth and Space – Short Answer Jessica the geologist is studying rocks at Yosemite National Park and observes a large rock formation with many thin layers peeling from it, like an onion. This feature was most likely formed by what type of weathering that causes layers of rock to gradually separate from a massive rock?  

text[[115, 266, 585, 285]]
ANSWER: EXFOLIATION (ACCEPT: SHEETING) [DB]  

sub_title[[462, 301, 533, 320]]
## BONUS  

text[[115, 336, 857, 372]]
1) Earth and Space – Multiple Choice Which of the following best describes shear stress in rocks?  

text[[115, 389, 758, 460]]
W) Differential stress that squeezes a rock mass like a vise  
X) Differential stress that elongates rock bodies  
Y) Differential stress that causes one part of a rock body to slide past another  
Z) Differential stress that is applied gradually, causing rocks to deform elastically  

text[[115, 476, 856, 513]]
ANSWER: Y) DIFFERENTIAL STRESS THAT CAUSES ONE PART OF A ROCK BODY TO SLIDE PAST ANOTHER [DB]  

sub_title[[456, 566, 540, 584]]
## TOSS-UP  

text[[115, 601, 878, 637]]
2) Earth and Space – Multiple Choice Which of the following satellites has the highest albedo in the solar system?  

text[[115, 654, 250, 724]]
W) Europa  
X) Earth's moon  
Y) Titan  
Z) Enceladus  

text[[115, 740, 396, 758]]
ANSWER: Z) ENCELADUS [NR]  

sub_title[[462, 776, 533, 794]]
## BONUS  

text[[115, 811, 846, 846]]
2) Earth and Space – Short Answer What is the reduced mass of a binary star system with stars of masses 4 and 6 solar masses?  

text[[115, 863, 414, 882]]
ANSWER: 2.4 (ACCEPT 12/5) [NR]  

text[[115, 899, 826, 934]]
3) Earth and Space – Short Answer What type of unconformity is demonstrated when a sedimentary rock like shale, lies over an older intrusive igneous rock like granite?  

text[[115, 944, 245, 960]]
NSB practice setssub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 144, 428, 163]]
ANSWER: NONCONFORMITY [DB]  

sub_title[[462, 180, 533, 199]]
## BONUS  

text[[115, 215, 872, 252]]
3) Earth and Space – Short Answer What type of air lifting mechanism occurs along air mass boundaries when warm air is pushed up to form large clouds?  

text[[115, 267, 720, 288]]
ANSWER: FRONTAL LIFTING (ACCEPT: FRONTAL WEDGING) [DB]  

sub_title[[456, 339, 540, 357]]
## TOSS-UP  

text[[115, 373, 872, 410]]
4) Life Science – Short Answer What natural cycle describes a person’s daily sleep and wake cycle?  

text[[115, 425, 455, 445]]
ANSWER: CIRCADIAN RHYTHM [DB]  

sub_title[[462, 461, 533, 480]]
## BONUS  

text[[115, 496, 840, 533]]
4) Life Science – Short Answer In biology, what type of behavior practices helping other individuals at a cost to oneself?  

text[[115, 549, 355, 568]]
ANSWER: ALTRUISM [DB]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[113, 127, 853, 147]]
5) Life Science – Multiple Choice Which of the following vitamins is NOT water-soluble?  

text[[115, 164, 169, 233]]
W) A 
X) B6 
Y) B12 
Z) C  

text[[115, 251, 300, 270]]
ANSWER: W) A [DB]  

sub_title[[463, 286, 533, 304]]
## BONUS  

text[[115, 321, 866, 359]]
5) Life Science – Short Answer Order the following 4 steps of glucose breakdown from first to last: 1) Oxidative phosphorylation; 2) Glycolysis; 3) Oxidation of pyruvate; 4) TCA cycle.  

text[[115, 374, 325, 394]]
ANSWER: 2, 3, 4, 1 [NR]  

sub_title[[456, 444, 541, 462]]
## TOSS-UP  

text[[115, 480, 852, 516]]
6) Life Science – Multiple Choice Which of the following types of algae contain seaweeds and is the most complex?  

text[[115, 533, 202, 604]]
W) Brown 
X) Green 
Y) Red 
Z) Golden  

text[[115, 621, 359, 640]]
ANSWER: W) BROWN [DB]  

sub_title[[463, 657, 533, 675]]
## BONUS  

text[[115, 693, 870, 728]]
6) Life Science – Short Answer What is the name of the protective bony structure that covers the breathing gills of a fish?  

text[[115, 745, 377, 764]]
ANSWER: OPERCULUM [DB]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[115, 127, 867, 163]]
7) Physical Science - Short Answer What is the name of the state when the forward rate of a reaction is equal to the reverse rate?  

text[[115, 180, 387, 199]]
ANSWER: EQUILIBRIUM [NR]  

sub_title[[464, 215, 533, 233]]
## BONUS  

text[[115, 250, 800, 286]]
7) Physical Science - Short Answer What is the molecular geometry of phosphorus pentachloride?  

text[[115, 302, 499, 321]]
ANSWER: TRIGONAL BIPYRAMIDAL [CD]  

sub_title[[456, 372, 541, 390]]
## TOSS-UP  

text[[115, 408, 881, 444]]
8) Physical Science - Short Answer What unitless quantity gives the ratio of the speed of light in a vacuum to the speed of light in a certain material?  

text[[115, 460, 476, 479]]
ANSWER: INDEX OF REFRACTION [CD]  

sub_title[[464, 495, 533, 513]]
## BONUS  

text[[115, 531, 822, 567]]
8) Physical Science - Multiple Choice Which of the following units measures the ratio between the moles of solute to the kilogram mass of the solvent?  

text[[115, 584, 275, 652]]
W) Mole fraction 
X) Molarity 
Y) Molality 
Z) Van't hoff factor  

text[[115, 670, 386, 689]]
ANSWER: Y) MOLALITY [NR]sub_title[[456, 90, 541, 108]]
## TOSS-UP  

text[[113, 127, 844, 163]]
9) Physical Science – Multiple Choice Which of the following substances would have the lowest vapor pressure at room temperature?  

text[[114, 181, 244, 252]]
W) 1-butanol  X) n-pentane  Y) 2-propanone  Z) Ethene  

text[[115, 269, 397, 288]]
ANSWER: W) 1- BUTANOL [NR]  

sub_title[[462, 305, 533, 322]]
## BONUS  

text[[113, 340, 864, 376]]
9) Physical Science – Multiple Choice What is the molecular geometry of the sulfur atom in IF5?  

text[[114, 393, 315, 464]]
W) Trigonal bipyramidal  X) See-saw  Y) Square pyramidal  Z) Octahedral  

text[[114, 481, 483, 500]]
ANSWER: Y) SQUARE PYRAMIDAL [NR]  

sub_title[[456, 552, 540, 570]]
## TOSS-UP  

text[[114, 587, 872, 623]]
10) Math – Short Answer What is the polar form of the point with rectangular coordinates (2, 2 root 3)?  

text[[114, 640, 533, 660]]
ANSWER: (4, 30 degrees) (ACCEPT: (4, pi/6) [CD])  

sub_title[[462, 676, 533, 694]]
## BONUS  

text[[115, 711, 857, 764]]
10) Math – Short Answer An ellipse is constructed on the coordinate plane with equation \(x^2 /16 + y^2 /81 = 1\) . A circle is then constructed with equation \(x^2 + y^2 = 9\) . What is the value of the area inside the ellipse but outside the circle?  

text[[115, 781, 291, 800]]
ANSWER: 27pi [CD]  

text[[115, 888, 830, 923]]
11) Math – Multiple Choice Which of the following constants is equal to the sum of the reciprocal of the factorials of the whole numbers?sub_title[[456, 91, 541, 108]]
## TOSS-UP  

text[[114, 128, 189, 199]]
W) pi 
X) e 
Y) phi 
Z) root 3  

text[[115, 216, 295, 235]]
ANSWER: X) E [NR]  

sub_title[[462, 252, 534, 270]]
## BONUS  

text[[114, 287, 869, 323]]
11) Math – Short Answer If January 1st in a given year fell on a Sunday, assuming that there is no leap day, on what day of the week would December 15th fall?  

text[[115, 340, 330, 359]]
ANSWER: FRIDAY [NR]  

sub_title[[456, 410, 541, 428]]
## TOSS-UP  

text[[115, 445, 847, 481]]
12) Math – Short Answer If the recursive sequence \(t_n\) is defined by \(t_n = 2t_{n-1} + 4\) and \(t_1 = 3\) , what is the value of \(t_4\) ?  

text[[115, 498, 277, 517]]
ANSWER: 52 [CD]  

sub_title[[462, 534, 534, 552]]
## BONUS  

text[[115, 569, 880, 657]]
12) Math – Short Answer Eddy has a beylade collection. He tells you that when he divides his beylades evenly into sets of 7 he has 2 left over, and when he divides them into sets of 13 he has 1 left over. From this information, you cannot determine his exact number of beylades, but you can determine the infinite list of solutions for how many stamps he could have. What is the difference between each solution in this list?  

text[[115, 674, 277, 693]]
ANSWER: 91 [CD]sub_title[[456, 90, 540, 108]]
## TOSS-UP  

text[[115, 127, 870, 164]]
13) Energy – Multiple Choice Scientists at Idaho National Lab are studying isotope stability. Which of the following is the most stable isotope of carbon?  

text[[115, 181, 231, 252]]
W) Carbon-11 
X) Carbon-12 
Y) Carbon-13 
Z) Carbon-14  

text[[115, 270, 391, 288]]
ANSWER: X) CARBON-12 [CD]  

sub_title[[463, 305, 533, 323]]
## BONUS  

text[[115, 340, 880, 394]]
13) Energy – Short Answer Scientists at Lawrence Berkeley National Lab are studying the mechanisms of asexual reproduction in bees. What type of asexual reproduction utilized by some bee species involves the development of the egg without being fertilized?  

text[[115, 410, 442, 428]]
ANSWER: PARTHENOGENESIS [DB]  

sub_title[[456, 481, 540, 499]]
## TOSS-UP  

text[[115, 516, 870, 569]]
14) Energy – Short Answer Scientists at Princeton Plasma Physics Lab are looking into the history of the moon by studying the craters that formed. These craters were formed during what period where there was an increased surge in debris impact rate?  

text[[115, 586, 540, 604]]
ANSWER: LATE HEAVY BOMBARDMENT [DB]  

sub_title[[463, 621, 533, 639]]
## BONUS  

text[[115, 657, 856, 710]]
14) Energy – Multiple Choice Scientists at Los Alamos National Lab are studying types of magnetism. Which of the following is indicated by the presence of paramagnetism in a molecule?  

text[[115, 728, 505, 800]]
W) The molecule possesses unpaired electrons 
X) The molecule possesses no unpaired electrons 
Y) The molecule is positively charged 
Z) The molecule is negatively charged  

text[[115, 816, 767, 835]]
ANSWER: W) THE MOLECULE POSSESSES UNPAIRED ELECTRONS [CD]