
## TOSS-UP  


1) Biology [5] – Multiple Choice In which of the following parts of the nephron can sodium NOT be reabsorbed from filtrate?  


W) Proximal Convoluted Tubule 
X) Distal Convoluted Tubule 
Y) Ascending Loop of Henle 
Z) Descending Loop of Henle  


ANSWER: Z) DESCENDING LOOP OF HENLE [VS]  


## BONUS  


1) Biology [5] – Short Answer Identify all of the following 3 techniques that could be used to visualize protein localization in live cells: 1) GFP tagging; 2) Immunofluorescence; 3) SDS-PAGE gel electrophoresis  


ANSWER: 1 ONLY [JH]  


## TOSS-UP  


2) Chemistry – Short Answer To one significant figure, what is the rate constant of a first-order reaction with a half life of 70 seconds?  


ANSWER: 0.01 [BZ, notable camper]  


## BONUS  


2) Chemistry – Short Answer Identify all of the following 3 compounds which have a HOMO with pi symmetry: 1) C2; 2) N2; 3) O2.  


ANSWER: 1 and 3 [BZ]  


## TOSS-UP  


3) Computer Science – Multiple Choice Which of the following is a valid request method in the HTTP protocol?  


W) CLEAR 
X) POST
Y) DROP 
Z) ADD  


ANSWER: X) POST  


## BONUS  


3) Computer Science [3] – Short Answer What feature, commonly used in C++, allows a programmer to define custom behavior for built-in operators such as +, -, or \* when used with objects derived from classes?  


ANSWER: Operator overloading [CH]  


## TOSS-UP  


4) Earth and Space – Multiple Choice Not all rock types fall into one of the three main categories. Which of the following best describes the rock types that migmatite is thought to be part of?  


W) Igneous and metamorphic 
X) Igneous and sedimentary 
Y) Metamorphic and sedimentary 
Z) Igneous, metamorphic, and sedimentary  


ANSWER: W) IGNEOUS AND METAMORPHIC [PB]  


## BONUS  


4) Earth and Space – Multiple Choice A type 1a supernova is observed with an apparent magnitude of +6. Which of the following is closest to the distance from Earth in light-years of the star that produced this supernova?  


W) \(10^{4}\) X) \(10^{6}\) Y) \(10^{8}\) Z) \(10^{10}\)  


ANSWER: X) \(10^{6}\) [PB]  


## TOSS-UP
5) Math – Short Answer What is the least positive integer n such that n factorial has 6 trailing zeroes?  


ANSWER: 25 [CT]  


## BONUS  


5) Math – Short Answer David decides to roll a 100 sided die until he rolls a 69. What is the expected value of the sum of all of his rolls before his first 69?  


ANSWER: 4981 [CT]  


## TOSS-UP  


6) Physics – Short Answer A charged particle is traveling in the positive Z direction. If the magnetic field is pointing in the negative Y direction, what direction should an applied electric field point so the particle feels zero net force?  


ANSWER: NEGATIVE X  


## BONUS  


6) Physics – Short Answer A uniform 2 kilogram ball is placed on a flat surface and is given an initial velocity of 3 meters per second and zero initial angular velocity. After some amount of time, it begins to roll without slipping. What is the impulse on the ball during this time?  


ANSWER: 12/7 [CH]  


## TOSS-UP  


7) Biology [4] – Short Answer Extracellular polymeric substances are secreted as the substrate for what type of cooperative colonies of prokaryotes?  


ANSWER: BIOFILMS [JH]  


## BONUS  


7) Biology [6] – Multiple Choice A deficiency in which of the following plant macronutrients is most likely to have symptoms of crinkled young leaves and terminal bud death?  


W) Potassium X) Magnesium Y) Calcium
Z) Nitrogen  


ANSWER: Y) CALCIUM [VS]  


## TOSS-UP  


8) Chemistry – Multiple Choice A tetrahedral molecule undergoes a reaction to form an octahedral molecule. If the reaction has a tetrahedral transition state, then according to Hammond's postulate which of the following must be true about the reaction?  


W) The product energy is lower than the reactant energy  X) The product energy is higher than the reactant energy  Y) The product has less valence electrons than the reactant  Z) The product has more valence electrons than the reactant  


ANSWER: W) THE PRODUCT ENERGY IS LOWER THAN THE REACTANT ENERGY [CT]  


## BONUS  


8) Chemistry – Short Answer What is the ratio of the internal energy of a monatomic ideal gas at \(300 \mathrm{~K}\) to that of a diatomic ideal gas at \(400 \mathrm{~K}\) ?  


ANSWER: 9/20 (ACCEPT: 9 to 20) [CT (i did not fucking write this question)]  


## TOSS-UP  


9) Computer Science – Short Answer Identify all of the following 3 locations that a sentinel node can be located in a doubly linked list: 1) Beginning; 2) Middle; 3) End.  


ANSWER: 1 and 3 [DJ, DSA]  


## BONUS  


9) Computer Science – Short Answer What annotation in Java is used when a child class reimplements a method already defined in its parent class?  


ANSWER: override (ACCEPT: @override) [CH]
## TOSS-UP  


10) Earth and Space – Multiple Choice In which of the following locations would the crustal geotherm likely be highest?  


W) Divergent plate boundary 
X) Continental volcanic arc 
Y) Subduction zone 
Z) Stable craton  


ANSWER: W) DIVERGENT PLATE BOUNDARY [PB]  


## BONUS  


10) Earth and Space – Multiple Choice Which of the following processes could cause reverse zoning in a crystal?  


W) Rapid cooling from exposure to air 
X) Mixing with a more primitive magma 
Y) Assimilation of crustal material 
Z) Separation of phases at a solvus line  


ANSWER: X) MIXING WITH A MORE PRIMITIVE MAGMA [PB]  


## TOSS-UP  


11) Math – Short Answer Compute the limit as x approaches infinity of the fraction with numerator \(14x^{2} + 13x - 6\) and denominator \(6x^{2} + 14x - 13\) .  


ANSWER: 7/3 [CT]  


## BONUS  


11) Math – Short Answer A certain right trapezoid has perpendicular diagonals. If the height of the trapezoid is 30 and one of the bases has length 12, what is the length of the other base?  


ANSWER: 75 [CT]  


## TOSS-UP  


12) Physics – Short Answer Peter and David are investigating a new planet they have discovered with a radius R. Peter is standing on the surface of the planet and feels a gravitational
force of G. If David has tunneled to a distance of R/2 from the planet's center, what is the gravitational force that he experiences in terms of G?  


ANSWER: G/2  


## BONUS  


12) Physics – Multiple Choice An incompressible inviscid fluid is flowing through a pipe with some radius R. Which of the following best describes the fluid's speed and pressure after the pipe constricts to a radius of \(\frac{1}{2}\mathrm{R}\) ?  


W) Increased speed, increased pressure  
X) Increased speed, decreased pressure  
Y) Decreased speed, increased pressure  
Z) Decreased speed, decreased pressure  


ANSWER: X) INCREASED SPEED, DECREASED PRESSURE  


## TOSS-UP  


13) Biology [4] – Multiple Choice In a rare event of human oogenesis, nondisjunction of all copies of chromosome 1 occurs during both meiosis I and meiosis II. How many chromosomes does the daughter cell with the most chromosomes have?  


W) 23  
X) 24  
Y) 25  
Z) 26  


ANSWER: Z) 26 [JH]  


## BONUS  


13) Biology [6] – Multiple Choice Which of the following types of organisms incorporates teichoic acid into its cell wall?  


W) Gram-positive bacteria  
X) Gram-negative bacteria  
Y) Fungi  
Z) Plants  


ANSWER: W) GRAM- POSITIVE BACTERIA [VS]
## TOSS-UP  


14) Chemistry - Short Answer David takes \(\mathrm{N}_2\mathrm{O}_5\) , dinitrogen pentoxide, and dissolves it in water then concentrates the solution he makes. He observes reddish-yellow fumes because he has made what compound?  


ANSWER: NITRIC ACID (ACCEPT: \(\mathrm{HNO}_3\) )  


## BONUS  


14) Chemistry - Multiple Choice David then further takes his nitric acid solution and attempts to oxidize some metals with it. David has a stubborn metal that he notices is resistant to oxidation with hydrochloric acid and sulfuric acid, but the metal suddenly starts to fume when he drips nitric acid onto it. Which of the following is most likely to be the identity of this stubborn metal?  


W) Chromium 
X) Copper 
Y) Silver 
Z) Gold  


ANSWER: X) COPPER  


## TOSS-UP  


15) Computer Science - Short Answer What computer hardware term describes the type of storage at the very top of the memory hierarchy, which is directly written to and accessed by the CPU when executing instructions?  


ANSWER: Registers [CH]  


## BONUS  


15) Computer Science - Multiple Choice Which of the following is not true regarding priority queues?  


W) Priority queues can be implemented using heaps. 
X) If two elements have equal priorities, they are listed by the order of the queue 
Y) The peek operation is constant time 
Z) The search operation is logarithmic time  


ANSWER: Z) The search operation is logarithmic time [DJ, DSA]
## TOSS-UP  


16) Earth and Space - Short Answer What astronomical phenomenon is responsible for the creation of an Einstein ring, a ring of light formed when two bodies lie in the same line of sight relative to Earth?  


ANSWER: GRAVITATIONAL LENSING [PB]  


## BONUS  


16) Earth and Space - Multiple Choice Which of the following describes the typical change in a star's temperature and luminosity as a result of its helium flash?  


W) Hotter and brighter 
X) Hotter and dimmer 
Y) Cooler and brighter 
Z) Cooler and dimmer  


ANSWER: X) HOTTER AND DIMMER [PB]  


## TOSS-UP  


17) Math - Short Answer A regular prism has 12 vertices. How many faces does it have?  


ANSWER: 8 [CT]  


## BONUS  


17) Math - Short Answer Given that 101 to the 2023rd power has 4055 digits, then to the nearest 5 digits, how many digits does 1001 to the 2023rd power have?  


ANSWER: 6070 [CT]  


## TOSS-UP  


18) Physics - Multiple Choice Which of the following assumptions must be made for the lens equation to be valid?  


W) The lens has an index of refraction equal to the air surrounding it
X) The lens has the same radii of curvature on both sidesY) The lens has a positive focal lengthZ) The lens is very thin compared to the lengths in the equation  


ANSWER: Z) THE LENS IS VERY THIN COMPARED TO THE LENGTHS IN THE EQUATION  


## BONUS  


18) Physics [6] – Short Answer Identify all of the following 3 statements that are true of the Pauli matrices, also called the sigma matrices: 1) They are Hermitian; 2) They are unitary; 3) They all anticommute with each other.  


ANSWER: All [CH]  


## TOSS-UP  


19) Biology [5] – Short Answer Secretion of the enzyme renin is directly induced by decreased blood flow through what specialized structure in the kidney?  


ANSWER: JUXTAGLOMERULAR APPARATUS [VS]  


## BONUS  


19) Biology [8] – Short Answer Identify all of the following four amino acids that can be turned into fumarate: 1) Tyrosine; 2) Isoleucine; 3) Proline; 4) Phenylalanine  


ANSWER: 1 AND 4 [VS]  


## TOSS-UP  


20) Chemistry – Short Answer Order the following 3 crystals in order of increasing lattice energy: 1) MgO; 2) KBr; 3) NaCl.  


ANSWER: 2, 3, 1 [CT]  


## BONUS
20) Chemistry – Short Answer Sodium fluoride has a \(\mathrm{K}_{\mathrm{sp}}\) of 0.8 in solvent X. To one significant figure, how many grams of sodium are in 1 Liter of a completely saturated solution of solvent X?  


ANSWER: 20 [CT]  


## TOSS-UP  


21) Computer Science – Multiple Choice Which of the following data types in C++ is NOT correctly paired with its memory size in bytes?  


W) Boolean; 1 byte  
X) Char; 2 bytes  
Y) Float; 4 bytes  
Z) Double; 8 bytes  


ANSWER: X) Char; 2 bytes [CH]  


## BONUS  


21) Computer Science – Short Answer Identify all of the following 3 logic gates that can be modeled by a single layer perceptron: 1) AND; 2) XOR; 3) OR.  


ANSWER: 1 and 3 [DJ, AIML]  


## TOSS-UP  


22) Earth and Space – Multiple Choice When the Salton Sea was accidentally created, its salinity quickly rose because it had no outlets for dissolved material to exit. The Salton Sea is an example of what type of lake?  


W) Eutrophic  
X) Oligotrophic  
Y) Endorheic  
Z) Exorheic  


ANSWER: Y) Endorheic [PB]  


## BONUS  


22) Earth and Space – Multiple Choice Which of the following best describes the difference between H I [H one] and H II [H two] regions?
W) H I regions have atomic hydrogen while H II regions have molecular hydrogen X) H I regions have molecular hydrogen while H II regions have atomic hydrogen Y) H I regions are ionized while H II regions are neutral Z) H II regions are ionized while H I regions are neutral  


ANSWER: Z) H II regions are ionized while H I regions are neutral [PB]  


## TOSS-UP  


23) Math - Short Answer Let T be a linear transformation from \(\mathbf{C}^2\) [C two] to \(\mathbf{R}^3\) [R three]. Assuming all vector spaces are expressed over the field R, what is the minimum possible nullity of T?  


ANSWER: 1 [CH]  


## BONUS  


23) Math - Short Answer An ant is on the number line at \(\mathbf{x} = 0\) . Every second, the ant randomly chooses whether to go to the right by one unit with probability \(2 / 3\) or go to the left by one unit with probability \(1 / 3\) . What is the probability that the ant first reaches \(\mathbf{x} = 4\) after exactly 6 seconds?  


ANSWER: 128/729 [CT]  


## TOSS-UP  


24) Physics - Multiple Choice Which of the following statements is always true of wavefunctions?  


W) A wavefunction must be continuous X) A wavefunction's derivative must be continuous Y) A wavefunction must have a finite value everywhere Z) A wavefunction must tend to 0 at infinite distances  


ANSWER: Z) A wavefunction must tend to 0 at infinite distances [CH]  


## BONUS  


24) Physics - Short Answer 3 positive point charges are placed in an arbitrary configuration in 3D space. What is the maximum number of local minima in the electric potential function?
ANSWER: 0