sub_title[[456, 90, 540, 107]]
## TOSS-UP  

text[[115, 124, 865, 160]]
1) Biology [5] – Multiple Choice In which of the following parts of the nephron can sodium NOT be reabsorbed from filtrate?  

text[[115, 178, 377, 249]]
W) Proximal Convoluted Tubule 
X) Distal Convoluted Tubule 
Y) Ascending Loop of Henle 
Z) Descending Loop of Henle  

text[[115, 265, 559, 284]]
ANSWER: Z) DESCENDING LOOP OF HENLE [VS]  

sub_title[[463, 318, 533, 336]]
## BONUS  

text[[115, 353, 876, 406]]
1) Biology [5] – Short Answer Identify all of the following 3 techniques that could be used to visualize protein localization in live cells: 1) GFP tagging; 2) Immunofluorescence; 3) SDS-PAGE gel electrophoresis  

text[[115, 422, 323, 441]]
ANSWER: 1 ONLY [JH]  

sub_title[[456, 494, 540, 512]]
## TOSS-UP  

text[[115, 529, 805, 564]]
2) Chemistry – Short Answer To one significant figure, what is the rate constant of a first-order reaction with a half life of 70 seconds?  

text[[115, 581, 418, 599]]
ANSWER: 0.01 [BZ, notable camper]  

sub_title[[463, 616, 533, 634]]
## BONUS  

text[[115, 651, 881, 687]]
2) Chemistry – Short Answer Identify all of the following 3 compounds which have a HOMO with pi symmetry: 1) C2; 2) N2; 3) O2.  

text[[115, 704, 312, 722]]
ANSWER: 1 and 3 [BZ]  

sub_title[[456, 775, 540, 792]]
## TOSS-UP  

text[[115, 810, 861, 845]]
3) Computer Science – Multiple Choice Which of the following is a valid request method in the HTTP protocol?  

text[[115, 862, 211, 897]]
W) CLEAR 
X) POSTtext[[115, 90, 196, 125]]
Y) DROP 
Z) ADD  

text[[115, 142, 285, 160]]
ANSWER: X) POST  

sub_title[[462, 177, 533, 195]]
## BONUS  

text[[115, 212, 857, 265]]
3) Computer Science [3] – Short Answer What feature, commonly used in C++, allows a programmer to define custom behavior for built-in operators such as +, -, or \* when used with objects derived from classes?  

text[[115, 282, 425, 301]]
ANSWER: Operator overloading [CH]  

sub_title[[456, 353, 540, 371]]
## TOSS-UP  

text[[115, 388, 866, 441]]
4) Earth and Space – Multiple Choice Not all rock types fall into one of the three main categories. Which of the following best describes the rock types that migmatite is thought to be part of?  

text[[115, 458, 455, 529]]
W) Igneous and metamorphic 
X) Igneous and sedimentary 
Y) Metamorphic and sedimentary 
Z) Igneous, metamorphic, and sedimentary  

text[[115, 545, 564, 564]]
ANSWER: W) IGNEOUS AND METAMORPHIC [PB]  

sub_title[[462, 581, 533, 599]]
## BONUS  

text[[115, 616, 859, 669]]
4) Earth and Space – Multiple Choice A type 1a supernova is observed with an apparent magnitude of +6. Which of the following is closest to the distance from Earth in light-years of the star that produced this supernova?  

text[[115, 686, 175, 756]]
W) \(10^{4}\) X) \(10^{6}\) Y) \(10^{8}\) Z) \(10^{10}\)  

text[[115, 774, 303, 792]]
ANSWER: X) \(10^{6}\) [PB]  

sub_title[[456, 846, 540, 863]]
## TOSS-UPtext[[113, 90, 879, 125]]
5) Math – Short Answer What is the least positive integer n such that n factorial has 6 trailing zeroes?  

text[[115, 142, 275, 161]]
ANSWER: 25 [CT]  

sub_title[[463, 178, 533, 196]]
## BONUS  

text[[115, 212, 866, 248]]
5) Math – Short Answer David decides to roll a 100 sided die until he rolls a 69. What is the expected value of the sum of all of his rolls before his first 69?  

text[[115, 265, 293, 283]]
ANSWER: 4981 [CT]  

sub_title[[456, 335, 540, 352]]
## TOSS-UP  

text[[115, 370, 863, 423]]
6) Physics – Short Answer A charged particle is traveling in the positive Z direction. If the magnetic field is pointing in the negative Y direction, what direction should an applied electric field point so the particle feels zero net force?  

text[[115, 440, 328, 457]]
ANSWER: NEGATIVE X  

sub_title[[463, 475, 533, 493]]
## BONUS  

text[[115, 510, 879, 563]]
6) Physics – Short Answer A uniform 2 kilogram ball is placed on a flat surface and is given an initial velocity of 3 meters per second and zero initial angular velocity. After some amount of time, it begins to roll without slipping. What is the impulse on the ball during this time?  

text[[115, 580, 291, 598]]
ANSWER: 12/7 [CH]  

sub_title[[456, 633, 540, 650]]
## TOSS-UP  

text[[115, 667, 879, 703]]
7) Biology [4] – Short Answer Extracellular polymeric substances are secreted as the substrate for what type of cooperative colonies of prokaryotes?  

text[[115, 720, 348, 738]]
ANSWER: BIOFILMS [JH]  

sub_title[[463, 755, 533, 773]]
## BONUS  

text[[115, 790, 879, 825]]
7) Biology [6] – Multiple Choice A deficiency in which of the following plant macronutrients is most likely to have symptoms of crinkled young leaves and terminal bud death?  

text[[115, 843, 235, 896]]
W) Potassium X) Magnesium Y) Calciumtext[[115, 90, 210, 108]]
Z) Nitrogen  

text[[115, 125, 376, 144]]
ANSWER: Y) CALCIUM [VS]  

sub_title[[456, 195, 540, 213]]
## TOSS-UP  

text[[115, 230, 835, 284]]
8) Chemistry – Multiple Choice A tetrahedral molecule undergoes a reaction to form an octahedral molecule. If the reaction has a tetrahedral transition state, then according to Hammond's postulate which of the following must be true about the reaction?  

text[[115, 300, 588, 372]]
W) The product energy is lower than the reactant energy  X) The product energy is higher than the reactant energy  Y) The product has less valence electrons than the reactant  Z) The product has more valence electrons than the reactant  

text[[115, 388, 851, 425]]
ANSWER: W) THE PRODUCT ENERGY IS LOWER THAN THE REACTANT ENERGY [CT]  

sub_title[[463, 440, 533, 459]]
## BONUS  

text[[115, 475, 857, 512]]
8) Chemistry – Short Answer What is the ratio of the internal energy of a monatomic ideal gas at \(300 \mathrm{~K}\) to that of a diatomic ideal gas at \(400 \mathrm{~K}\) ?  

text[[115, 528, 744, 548]]
ANSWER: 9/20 (ACCEPT: 9 to 20) [CT (i did not fucking write this question)]  

sub_title[[456, 599, 540, 617]]
## TOSS-UP  

text[[115, 633, 866, 671]]
9) Computer Science – Short Answer Identify all of the following 3 locations that a sentinel node can be located in a doubly linked list: 1) Beginning; 2) Middle; 3) End.  

text[[115, 686, 358, 705]]
ANSWER: 1 and 3 [DJ, DSA]  

sub_title[[463, 721, 533, 739]]
## BONUS  

text[[115, 755, 827, 792]]
9) Computer Science – Short Answer What annotation in Java is used when a child class reimplements a method already defined in its parent class?  

text[[115, 808, 509, 827]]
ANSWER: override (ACCEPT: @override) [CH]sub_title[[455, 90, 540, 107]]
## TOSS-UP  

text[[115, 123, 870, 160]]
10) Earth and Space – Multiple Choice In which of the following locations would the crustal geotherm likely be highest?  

text[[115, 178, 348, 249]]
W) Divergent plate boundary 
X) Continental volcanic arc 
Y) Subduction zone 
Z) Stable craton  

text[[115, 265, 574, 284]]
ANSWER: W) DIVERGENT PLATE BOUNDARY [PB]  

sub_title[[463, 300, 533, 318]]
## BONUS  

text[[115, 335, 875, 372]]
10) Earth and Space – Multiple Choice Which of the following processes could cause reverse zoning in a crystal?  

text[[115, 389, 440, 460]]
W) Rapid cooling from exposure to air 
X) Mixing with a more primitive magma 
Y) Assimilation of crustal material 
Z) Separation of phases at a solvus line  

text[[115, 476, 675, 495]]
ANSWER: X) MIXING WITH A MORE PRIMITIVE MAGMA [PB]  

sub_title[[455, 547, 540, 565]]
## TOSS-UP  

text[[115, 582, 840, 618]]
11) Math – Short Answer Compute the limit as x approaches infinity of the fraction with numerator \(14x^{2} + 13x - 6\) and denominator \(6x^{2} + 14x - 13\) .  

text[[115, 634, 280, 653]]
ANSWER: 7/3 [CT]  

sub_title[[463, 669, 533, 687]]
## BONUS  

text[[115, 704, 867, 740]]
11) Math – Short Answer A certain right trapezoid has perpendicular diagonals. If the height of the trapezoid is 30 and one of the bases has length 12, what is the length of the other base?  

text[[115, 756, 275, 775]]
ANSWER: 75 [CT]  

sub_title[[455, 828, 540, 845]]
## TOSS-UP  

text[[115, 862, 876, 898]]
12) Physics – Short Answer Peter and David are investigating a new planet they have discovered with a radius R. Peter is standing on the surface of the planet and feels a gravitationaltext[[115, 90, 820, 125]]
force of G. If David has tunneled to a distance of R/2 from the planet's center, what is the gravitational force that he experiences in terms of G?  

text[[115, 142, 240, 159]]
ANSWER: G/2  

sub_title[[463, 177, 533, 195]]
## BONUS  

text[[115, 212, 857, 265]]
12) Physics – Multiple Choice An incompressible inviscid fluid is flowing through a pipe with some radius R. Which of the following best describes the fluid's speed and pressure after the pipe constricts to a radius of \(\frac{1}{2}\mathrm{R}\) ?  

text[[114, 283, 428, 353]]
W) Increased speed, increased pressure  
X) Increased speed, decreased pressure  
Y) Decreased speed, increased pressure  
Z) Decreased speed, decreased pressure  

text[[115, 370, 638, 388]]
ANSWER: X) INCREASED SPEED, DECREASED PRESSURE  

sub_title[[456, 440, 541, 458]]
## TOSS-UP  

text[[115, 475, 865, 528]]
13) Biology [4] – Multiple Choice In a rare event of human oogenesis, nondisjunction of all copies of chromosome 1 occurs during both meiosis I and meiosis II. How many chromosomes does the daughter cell with the most chromosomes have?  

text[[114, 546, 168, 615]]
W) 23  
X) 24  
Y) 25  
Z) 26  

text[[115, 633, 294, 652]]
ANSWER: Z) 26 [JH]  

sub_title[[463, 669, 533, 687]]
## BONUS  

text[[115, 704, 860, 740]]
13) Biology [6] – Multiple Choice Which of the following types of organisms incorporates teichoic acid into its cell wall?  

text[[114, 757, 333, 828]]
W) Gram-positive bacteria  
X) Gram-negative bacteria  
Y) Fungi  
Z) Plants  

text[[115, 845, 545, 864]]
ANSWER: W) GRAM- POSITIVE BACTERIA [VS]sub_title[[455, 106, 540, 124]]
## TOSS-UP  

text[[115, 141, 880, 194]]
14) Chemistry - Short Answer David takes \(\mathrm{N}_2\mathrm{O}_5\) , dinitrogen pentoxide, and dissolves it in water then concentrates the solution he makes. He observes reddish-yellow fumes because he has made what compound?  

text[[115, 211, 480, 229]]
ANSWER: NITRIC ACID (ACCEPT: \(\mathrm{HNO}_3\) )  

sub_title[[462, 247, 533, 265]]
## BONUS  

text[[115, 281, 880, 368]]
14) Chemistry - Multiple Choice David then further takes his nitric acid solution and attempts to oxidize some metals with it. David has a stubborn metal that he notices is resistant to oxidation with hydrochloric acid and sulfuric acid, but the metal suddenly starts to fume when he drips nitric acid onto it. Which of the following is most likely to be the identity of this stubborn metal?  

text[[115, 386, 232, 457]]
W) Chromium 
X) Copper 
Y) Silver 
Z) Gold  

text[[115, 475, 310, 493]]
ANSWER: X) COPPER  

sub_title[[455, 546, 540, 564]]
## TOSS-UP  

text[[115, 580, 872, 633]]
15) Computer Science - Short Answer What computer hardware term describes the type of storage at the very top of the memory hierarchy, which is directly written to and accessed by the CPU when executing instructions?  

text[[115, 650, 330, 669]]
ANSWER: Registers [CH]  

sub_title[[462, 704, 533, 722]]
## BONUS  

text[[115, 739, 866, 775]]
15) Computer Science - Multiple Choice Which of the following is not true regarding priority queues?  

text[[115, 792, 752, 862]]
W) Priority queues can be implemented using heaps. 
X) If two elements have equal priorities, they are listed by the order of the queue 
Y) The peek operation is constant time 
Z) The search operation is logarithmic time  

text[[115, 880, 640, 898]]
ANSWER: Z) The search operation is logarithmic time [DJ, DSA]sub_title[[456, 142, 540, 161]]
## TOSS-UP  

text[[115, 177, 866, 231]]
16) Earth and Space - Short Answer What astronomical phenomenon is responsible for the creation of an Einstein ring, a ring of light formed when two bodies lie in the same line of sight relative to Earth?  

text[[115, 246, 497, 266]]
ANSWER: GRAVITATIONAL LENSING [PB]  

sub_title[[463, 281, 533, 300]]
## BONUS  

text[[115, 316, 881, 353]]
16) Earth and Space - Multiple Choice Which of the following describes the typical change in a star's temperature and luminosity as a result of its helium flash?  

text[[115, 369, 299, 441]]
W) Hotter and brighter 
X) Hotter and dimmer 
Y) Cooler and brighter 
Z) Cooler and dimmer  

text[[115, 458, 489, 478]]
ANSWER: X) HOTTER AND DIMMER [PB]  

sub_title[[456, 528, 540, 547]]
## TOSS-UP  

text[[115, 562, 846, 582]]
17) Math - Short Answer A regular prism has 12 vertices. How many faces does it have?  

text[[115, 598, 264, 617]]
ANSWER: 8 [CT]  

sub_title[[463, 633, 533, 652]]
## BONUS  

text[[115, 667, 850, 705]]
17) Math - Short Answer Given that 101 to the 2023rd power has 4055 digits, then to the nearest 5 digits, how many digits does 1001 to the 2023rd power have?  

text[[115, 720, 293, 739]]
ANSWER: 6070 [CT]  

sub_title[[456, 791, 540, 809]]
## TOSS-UP  

text[[115, 825, 876, 862]]
18) Physics - Multiple Choice Which of the following assumptions must be made for the lens equation to be valid?  

text[[115, 878, 658, 898]]
W) The lens has an index of refraction equal to the air surrounding ittext[[114, 90, 616, 144]]
X) The lens has the same radii of curvature on both sidesY) The lens has a positive focal lengthZ) The lens is very thin compared to the lengths in the equation  

text[[114, 159, 806, 195]]
ANSWER: Z) THE LENS IS VERY THIN COMPARED TO THE LENGTHS IN THE EQUATION  

sub_title[[463, 212, 533, 230]]
## BONUS  

text[[115, 246, 857, 300]]
18) Physics [6] – Short Answer Identify all of the following 3 statements that are true of the Pauli matrices, also called the sigma matrices: 1) They are Hermitian; 2) They are unitary; 3) They all anticommute with each other.  

text[[115, 316, 281, 335]]
ANSWER: All [CH]  

sub_title[[456, 404, 540, 422]]
## TOSS-UP  

text[[115, 440, 806, 476]]
19) Biology [5] – Short Answer Secretion of the enzyme renin is directly induced by decreased blood flow through what specialized structure in the kidney?  

text[[115, 492, 571, 511]]
ANSWER: JUXTAGLOMERULAR APPARATUS [VS]  

sub_title[[463, 546, 533, 564]]
## BONUS  

text[[115, 580, 848, 616]]
19) Biology [8] – Short Answer Identify all of the following four amino acids that can be turned into fumarate: 1) Tyrosine; 2) Isoleucine; 3) Proline; 4) Phenylalanine  

text[[115, 632, 330, 651]]
ANSWER: 1 AND 4 [VS]  

sub_title[[456, 704, 540, 722]]
## TOSS-UP  

text[[115, 738, 852, 775]]
20) Chemistry – Short Answer Order the following 3 crystals in order of increasing lattice energy: 1) MgO; 2) KBr; 3) NaCl.  

text[[115, 791, 303, 810]]
ANSWER: 2, 3, 1 [CT]  

sub_title[[463, 826, 533, 844]]
## BONUStext[[114, 89, 882, 142]]
20) Chemistry – Short Answer Sodium fluoride has a \(\mathrm{K}_{\mathrm{sp}}\) of 0.8 in solvent X. To one significant figure, how many grams of sodium are in 1 Liter of a completely saturated solution of solvent X?  

text[[115, 159, 273, 178]]
ANSWER: 20 [CT]  

sub_title[[456, 230, 540, 249]]
## TOSS-UP  

text[[114, 264, 845, 301]]
21) Computer Science – Multiple Choice Which of the following data types in C++ is NOT correctly paired with its memory size in bytes?  

text[[114, 317, 272, 390]]
W) Boolean; 1 byte  
X) Char; 2 bytes  
Y) Float; 4 bytes  
Z) Double; 8 bytes  

text[[115, 406, 387, 425]]
ANSWER: X) Char; 2 bytes [CH]  

sub_title[[463, 441, 533, 459]]
## BONUS  

text[[114, 475, 857, 512]]
21) Computer Science – Short Answer Identify all of the following 3 logic gates that can be modeled by a single layer perceptron: 1) AND; 2) XOR; 3) OR.  

text[[115, 528, 368, 547]]
ANSWER: 1 and 3 [DJ, AIML]  

sub_title[[456, 599, 540, 617]]
## TOSS-UP  

text[[114, 633, 875, 688]]
22) Earth and Space – Multiple Choice When the Salton Sea was accidentally created, its salinity quickly rose because it had no outlets for dissolved material to exit. The Salton Sea is an example of what type of lake?  

text[[114, 704, 245, 774]]
W) Eutrophic  
X) Oligotrophic  
Y) Endorheic  
Z) Exorheic  

text[[115, 792, 359, 810]]
ANSWER: Y) Endorheic [PB]  

sub_title[[463, 827, 533, 845]]
## BONUS  

text[[113, 861, 863, 898]]
22) Earth and Space – Multiple Choice Which of the following best describes the difference between H I [H one] and H II [H two] regions?text[[114, 106, 767, 179]]
W) H I regions have atomic hydrogen while H II regions have molecular hydrogen X) H I regions have molecular hydrogen while H II regions have atomic hydrogen Y) H I regions are ionized while H II regions are neutral Z) H II regions are ionized while H I regions are neutral  

text[[115, 195, 692, 214]]
ANSWER: Z) H II regions are ionized while H I regions are neutral [PB]  

sub_title[[456, 265, 540, 284]]
## TOSS-UP  

text[[114, 300, 872, 353]]
23) Math - Short Answer Let T be a linear transformation from \(\mathbf{C}^2\) [C two] to \(\mathbf{R}^3\) [R three]. Assuming all vector spaces are expressed over the field R, what is the minimum possible nullity of T?  

text[[115, 370, 266, 389]]
ANSWER: 1 [CH]  

sub_title[[463, 405, 533, 423]]
## BONUS  

text[[114, 440, 872, 510]]
23) Math - Short Answer An ant is on the number line at \(\mathbf{x} = 0\) . Every second, the ant randomly chooses whether to go to the right by one unit with probability \(2 / 3\) or go to the left by one unit with probability \(1 / 3\) . What is the probability that the ant first reaches \(\mathbf{x} = 4\) after exactly 6 seconds?  

text[[115, 528, 318, 547]]
ANSWER: 128/729 [CT]  

sub_title[[456, 599, 540, 617]]
## TOSS-UP  

text[[114, 633, 788, 669]]
24) Physics - Multiple Choice Which of the following statements is always true of wavefunctions?  

text[[114, 686, 559, 757]]
W) A wavefunction must be continuous X) A wavefunction's derivative must be continuous Y) A wavefunction must have a finite value everywhere Z) A wavefunction must tend to 0 at infinite distances  

text[[114, 774, 679, 793]]
ANSWER: Z) A wavefunction must tend to 0 at infinite distances [CH]  

sub_title[[463, 809, 533, 826]]
## BONUS  

text[[114, 844, 877, 879]]
24) Physics - Short Answer 3 positive point charges are placed in an arbitrary configuration in 3D space. What is the maximum number of local minima in the electric potential function?text[[115, 91, 222, 108]]
ANSWER: 0