
## TOSS-UP  


1) Biology [4] – Multiple Choice Which of the following best describes the trp [READ: TRIP] operon and the role of tryptophan in its regulation?  


W) Inducible, inducer 
X) Inducible, coinducer 
Y) Repressible, repressor 
Z) Repressible, corepressor  


ANSWER: Z) REPRESSIBLE, COREPRESSOR [JH]  


## BONUS  


1) Biology [6] – Short Answer Identify all of the following three biological processes that involve a recombinase enzyme: 1) Archaeal DNA repair; 2) Maturation of human B-cells; 3) Cre-Lox genetic knock-in  


ANSWER: ALL [JH]  


## TOSS-UP  


2) Chemistry – Short Answer Order the following 3 compounds in order of increasing van’t Hoff factor in water: 1) Magnesium chloride; 2) Glucose; 3) Sodium chloride.  


ANSWER: 2, 3, 1 [CT]  


## BONUS  


2) Chemistry – Short Answer Identify all of the following 4 ligands that are generally considered to be strong field ligands: 1) Chloride; 2) Fluoride; 3) Bromide; 4) Iodide.  


ANSWER: NONE [CT]  


## TOSS-UP  


3) Computer Science – Short Answer Order the following 3 steps from first to last in the compilation of human-readable code to machine code: 1) Optimization; 2) Lexing; 3) Parsing  


ANSWER: 2, 3, 1 [CH]
## BONUS  


3) Computer Science – Short Answer Identify all of the following 3 tree traversals that are considered depth first search: 1) Preorder; 2) Inorder; 3) Postorder.  


ANSWER: ALL [DJ, ORDERING TWEES!]  


## TOSS-UP  


4) Earth and Space – Short Answer Before the Sun reached the main sequence, it evolved horizontally along the H-R diagram following what path, which describes the evolution of all stars greater than roughly 0.5 solar masses?  


ANSWER: HENYEY TRACK [PB]  


## BONUS  


4) Earth and Space – Short Answer The average amount of energy radiated away from Earth at any given point is S. Assuming Earth has a perfect radiation balance, in terms of S, what is the maximum possible amount of incoming energy at that point under direct sunlight?  


ANSWER: 4S [PB]  


## TOSS-UP  


5) Math – Short Answer How many odd integers between 1 and 100 inclusive are divisible by 3?  


ANSWER: 17 [CT]  


## BONUS  


5) Math – Short Answer A sphere has a regular octahedron inscribed within it. What is the ratio of the volumes of the sphere to the octahedron?  


ANSWER: PI [CT]  


## TOSS-UP
6) Physics – Short Answer A system with a time-invariant Lagrangian satisfies the conservation of energy. This is a consequence of what theorem, which states that every differentiable symmetry of a physical system’s action has an associated conservation law?  


ANSWER: NOETHER’S THEOREM [JH]  


## BONUS  


6) Physics – Multiple Choice In accordance with the Dulong-Petit Law, the molar heat capacity of many solid elements at room temperature is around three times the universal gas constant. This observation matches the prediction of the equipartition theorem applied with how many quadratic degrees of freedom?  


W) 3 X) 4 Y) 5 Z) 6  


ANSWER: Z) 6 [JH]  


## TOSS-UP  


7) Biology – Short Answer Rank the following three components of the electron transport chain by increasing reduction potential: 1) Complex I; 2) Complex III; 3) Ubiquinone  


ANSWER: 1, 3, 2 [JH]  


## BONUS  


7) Biology – Short Answer A gene has three alleles; allele A is dominant to allele B, which is dominant to allele C. Two organisms with genotypes AB and BC produce an arbitrarily large amount of offspring, and the F1 generation breeds with themselves at random to produce an arbitrarily large amount of F2 offspring. What is the expected proportion of organisms in the F2 generation that exhibit the C phenotype?  


ANSWER: 1/16 [CT]  


## TOSS-UP  


8) Chemistry – Multiple Choice Which of the following chemical species would have the greatest nucleophilicity for an \(\mathrm{S_N2}\) reaction on a primary carbon?
W) Acetate X) Iodide Y) Hydroxide Z) Chloride  


ANSWER: X) IODIDE  


## BONUS  


8) Chemistry – Short Answer How many electrons occupy the \(t_{2g}\) orbitals of the \([CoF_6]^{3- }\) complex?  


ANSWER: 4  


## TOSS-UP  


9) Computer Science – Multiple Choice Which of the following sorting algorithms has a linear time complexity?  


W) Quick X) Radix Y) Bubble Z) Merge  


ANSWER: X) RADIX [DJ, cringe fake sorting shit]  


## BONUS  


9) Computer Science – Short Answer What phenomenon, which commonly affects CPUs running at high speeds, occurs when the clock signal running the computer is not perfectly periodic?  


ANSWER: Jitter [CH]  


## TOSS-UP  


10) Earth and Space – Short Answer The luminosity of bodies in hydrostatic equilibrium is bounded because radiation pressure cannot exceed the gravitational force on the outer layers of the star. What is the term for the theoretical limit of a star's luminosity derived from this principle?  


ANSWER: EDDINGTON LIMIT [PB]
## BONUS  


10) Earth and Space - Multiple Choice Which of the following best explains why the deposition of black carbon on glacier surfaces does not create a positive feedback loop?  


W) Black carbon stabilizes glaciers, increasing their lifetimes  


X) Aerosols act as cloud condensation nuclei, decreasing Earth's albedo  


Y) Black carbon is not created by human activity  


Z) The associated warming does not create more black carbon  


ANSWER: Z) The associated warming does not create more black carbon [PB]  


## TOSS-UP  


11) Math - Short Answer What is the circumradius of a right triangle with legs of length 7 and 24?  


ANSWER: 12.5 [CT]  


## BONUS  


11) Math - Multiple Choice Two lines are drawn in the coordinate plane: \(\mathrm{y} = \mathrm{ax} + \mathrm{b}\) and \(\mathrm{y} = \mathrm{bx} + \mathrm{a}\) . A unit circle is drawn centered at the intersection point of these two lines, and the two lines split the unit circle into four parts. Which of the following choices of a and b makes the four parts most similar to each other in area?  


W) \(\mathrm{a} = - 2\) , \(\mathrm{b} = 5\) X) \(\mathrm{a} = - 1\) , \(\mathrm{b} = 6\) Y) \(\mathrm{a} = 1\) , \(\mathrm{b} = 8\) Z) \(\mathrm{a} = 2\) , \(\mathrm{b} = 9\)  


ANSWER: X) \(\mathrm{A} = - 1\) , \(\mathrm{B} = 6\) [CT]  


## TOSS-UP  


12) Physics - Multiple Choice In their differential form, which of Maxwell's equations relates the curl of the electric field to the time derivative of the magnetic field?  


W) Ampere's Law 
X) Faraday's law 
Y) Gauss's law
Z) Gauss's law for magnetism  


ANSWER: X) FARADAY'S LAW [JH]  


## BONUS  


12) Physics – Short Answer In a one-dimensional quantum harmonic oscillator, what is the ratio of the energies of the lowest energy level to the fifth lowest energy level, where energy is defined to be zero at the bottom of the potential well?  


ANSWER: 1/9 [JH]  


## TOSS-UP  


13) Biology – Multiple Choice Which of the following statements is accurate about the several globin genes encoded in the human genome?  


W) Adult hemoglobin binds oxygen more strongly than fetal hemoglobin.  


X) The different globin genes are classified as orthologs.  


Y) A hemoglobin protein can bind up to four oxygen molecules.  


Z) Hemoglobin and oxygen exhibit negative cooperativity.  


ANSWER: Y) A HEMOGLOBIN PROTEIN CAN BIND UP TO FOUR OXYGEN MOLECULES. [JH]  


## BONUS  


13) Biology – Multiple Choice The antibiotic novobiocin is a small-molecule competitive inhibitor of the enzyme DNA gyrase. Which of the following is NOT true about novobiocin and DNA gyrase?  


W) According to Michaelis-Menten kinetics, novobiocin does not change the \(\mathrm{V}_{\mathrm{max}}\) of DNA gyrase.  


X) DNA gyrase has both nuclease and ligase domains.  


Y) Bacterial resistance to \(\beta\) - lactam antibiotics is likely unrelated with resistance to novobiocin. 
Z) Mutations in nuclear importins can confer resistance to novobiocin.  


ANSWER: Z) MUTATIONS IN NUCLEAR IMPORTINS CAN CONFER RESISTANCE TO NOVOBIOCIN. [JH]  


## TOSS-UP
14) Chemistry – Short Answer The pKa values for phosphoric acid are 2.1, 7.2, and 12.4. At what pH value is the relative concentration of \(\mathrm{HPO_4}^{2 - }\) maximized?  


ANSWER: 9.8  


## BONUS  


14) Chemistry – Multiple Choice Which of the following diatomic gas molecules would have the lowest constant volume heat capacity at 50 Kelvin?  


W) Hydrogen  X) Nitrogen  Y) Oxygen  Z) Fluorine  


ANSWER: W) HYDROGEN  


## TOSS-UP  


15) Computer Science – Multiple Choice Which of the following algorithms is an example of an asymmetric-key encryption algorithm?  


W) SHA256  X) Diffie-Hellman  Y) MD5  Z) AES  


ANSWER: X) Diffie-Hellman [CH]  


## BONUS  


15) Computer Science – Short Answer Which of the following options correctly describes a difference between stochastic gradient descent and gradient descent?  


W) SGD is more suitable for small datasets while GD performs well on extremely large datasets  X) SGD calculates gradients with batches of data while GD calculates gradients with the entire dataset  Y) SGD converges to nonglobal minima more often than GD  Z) SGD converges to a minimum much slower than GD  


ANSWER: X) SGD CALCULATES GRADIENTS WITH BATCHES OF DATA WHILE GD CALCULATES GRADIENTS WITH THE ENTIRE DATASET [DJ/CT]
## TOSS-UP  


16) Earth and Space - Short Answer When viewing text through a clear piece of calcite, it appears twice when refracted through the crystal. What term is given to the property that allows this double refraction?  


ANSWER: BIREFRINGENCE (ACCEPT: ANISOTROPY) [PB]  


## BONUS  


16) Earth and Space - Multiple Choice The Tully-Fisher relation is used to approximate the distance to a galaxy by comparing its luminosity to which of the following properties?  


W) Rotational velocity 
X) Metallicity 
Y) Age 
Z) Density  


ANSWER: W) ROTATIONAL VELOCITY [PB]  


## TOSS-UP  


17) Math - Short Answer How many positive integers have both of the following 2 properties:  


I) They have 2 digits in base 5, and 
II) They have 3 digits in base 4.  


ANSWER: 9 [CT]  


## BONUS  


17) Math - Short Answer A function f is defined as \(\mathrm{f(x) = ax^2 + 12x + 18}\) . For what value of \(a\) do \(\mathrm{f(x)}\) and \(\mathrm{f^2(x)}\) [f prime of x] share a root?  


ANSWER: 2 [CT]  


## TOSS-UP  


18) Physics - Multiple Choice Which of the following thermodynamic cycles is represented as a rectangle on a temperature-entropy graph?
W) Brayton cycle 
X) Carnot cycle 
Y) Otto cycle 
Z) Stirling cycle  


ANSWER: X) CARNOT CYCLE [JH]  


## BONUS  


18) Physics – Multiple Choice Which of the following statements is true regarding polarization and refraction between two arbitrary media, according to the Fresnel [READ: fray-NELL] equations?  


W) There always exists an angle of incidence at which reflected light is only polarized normal to the plane of incidence. 
X) There always exists an angle of incidence at which reflected light is only polarized in the plane of incidence. 
Y) There always exists an angle of incidence above which there is no reflected light. 
Z) There always exists an angle of incidence at which the reflectance and transmittance sum to two.  


ANSWER: W) THERE ALWAYS EXISTS AN ANGLE OF INCIDENCE AT WHICH REFLECTED LIGHT IS ONLY POLARIZED NORMAL TO THE PLANE OF INCIDENCE. [JH]  


## TOSS-UP  


19) Biology – Short Answer In the lateral line of fish, what gelatinous structure covers the hair cells, protecting them from damage?  


ANSWER: CUPULA [VS]  


## BONUS  


19) Biology – Short Answer Identify all of the following four cell junctions that are incorrectly matched to what cytoskeletal element they bind to: 1) Tight junctions and actin; 2) Desmosomes and intermediate filaments; 3) Hemidesmosomes and actin; 4) Adherens junctions and intermediate filaments  


ANSWER: 3 AND 4 [VS]
## TOSS-UP  


20) Chemistry - Short Answer Sometimes, half-reactions occur at a different potential from the reduction potential. What is the term for this difference between the actual and ideal potentials?  


ANSWER: OVERPOTENTIAL [CT]  


## BONUS  


20) Chemistry - Short Answer The mean free path of a gas at 1 atmosphere and \(300\mathrm{K}\) is 90 nanometers. In nanometers, what is the mean free path of the same gas at 2 atmospheres and \(900\mathrm{K}\) ?  


ANSWER: 135 [CT]  


## TOSS-UP  


21) Computer Science - Multiple Choice Which of the following data types in Java is not a primitive?  


W) float 
X) char 
Y) String 
Z) long  


ANSWER: Y) String [DJ, Java cringe]  


## BONUS  


21) Computer Science - Short Answer What type of security breach involves unauthorized code being executed in the web browser of a victim?  


ANSWER: Cross site scripting (ACCEPT: XSS) [CH]  


## TOSS-UP  


22) Earth and Space - Short Answer Antarctica's climate is isolated from the effects of subtropical ocean gyres due to the flow of what fast-flowing current surrounding the continent?
ANSWER: Antarctic Circumpolar Current (ACCEPT: ACC; ACCEPT: WEST WIND DRIFT) [PB]  


## BONUS  


22) Earth and Space – Short Answer In which of the five major Köppen classifications would soil weathering likely be most active?  


ANSWER: A [PB]  


## TOSS-UP  


23) Math – Short Answer A shelf has 10 identical left shoes and 10 identical right shoes. If David picks two shoes at random, what is the probability that he gets a pair?  


ANSWER: 10/19 [CT]  


## BONUS  


23) Math – Short Answer Colin is teaching Vedang how to do subtraction, but Vedang hasn’t learned how to borrow yet. How many different subtraction problems using nonnegative integers less than 100 can Colin give Vedang that do not involve borrowing?  


ANSWER: 3025 [CH]  


## TOSS-UP  


24) Physics – Short Answer Identify all of the following 3 statements that are true of a silicon P-N junction: 1) A depletion region is formed at the junction; 2) The diffusion and drift forces are balanced when the junction is at equilibrium; 3) This P-N junction could be used to make an LED.  


ANSWER: 1 and 2 [CH]  


## BONUS  


24) Physics – Short Answer Identify all of the following four quantities that are invariant under the Lorentz transformations: 1) Mass; 2) Energy; 3) 3-momentum; 4) 4-momentum  


ANSWER: 4 ONLY [JH]
# 1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1