
## TOSS-UP [only for connor vs. ferrum]  


0) Biology - Short Answer One difficulty with sequencing the human genome is due to the presence of many repetitive sequences including L1 and Alu elements. L1 and Alu elements are examples of what type of sequence which are mobile genetic elements that are thought to be related to early viruses?  


ANSWER: TRANSPOSONS (ACCEPT: JUMPING GENES, RETROTRANSPOSONS) [JH]  


## BONUS [only for connor vs. ferrum]  


0) Biology - Short Answer Identify all of the following three statements that are true about the spleen: 1) Most of the bilirubin produced in the body is produced in the spleen; 2) The development of immune cell self-tolerance occurs in the spleen; 3) A common symptom of sickle cell anemia is diminished spleen size.  


ANSWER: 1 ONLY [JH]  


## TOSS-UP  


1) Biology - Short Answer Bioremediation efforts such as farming oyster reefs are meant to help extract excess nitrogen from estuaries in order to recover from what process, which is commonly caused by the runoff of polluting nutrients and often results in harmful algal blooms?  


ANSWER: EUTROPHICATION [JH]  


## BONUS  


1) Biology - Multiple Choice Which of the following is NOT true about the neurons in the ventral tegmental area, which is the region of the brain commonly thought to comprise the brain's reward system?  


W) The ventral tegmental area is located in the midbrain.  


X) Nicotine binds acetylcholine receptors to primarily induce serotonin release in these neurons. 
Y) Drug withdrawal can be modeled by changes in the homeostatic levels of hormones in these neurons.  


Z) Drugs that inhibit presynaptic reuptake of dopamine in these neurons are classified as  


stimulants.  


ANSWER: X) NICOTINE BINDS ACETYLCHOLINE RECEPTORS TO PRIMARILY INDUCE SEROTONIN RELEASE IN THESE NEURONS. [JH]
## TOSS-UP  


2) Chemistry - Multiple Choice When comparing real gases to the ideal predictions, the compression factor is often used, representing the ratio of real molar volume to ideal molar volume. Which of the following best describes how the compression factor of most real gases changes as pressure increases?  


W) Increases, then decreases 
X) Decreases, then increases 
Y) Always increases 
Z) Always decreases  


ANSWER: X) Decreases, then increases  


## BONUS  


2) Chemistry - Short Answer Glass is typically used for chemistry lab equipment because it is highly resistant to many types of compounds. One exception to this is hydrofluoric acid, primarily because the glass reacts with fluorine anions to form what octahedral polyatomic ion as a product?  


ANSWER: Fluorosilicate (ACCEPT: \(\mathrm{SiF_6^{2 - }}\) ) [CH]  


## TOSS-UP  


3) Computer Science - Short Answer What protocol, which commonly runs on network port 123, is used to keep a computer's clock synchronized with other machines in the network?  


ANSWER: Network Time Protocol (ACCEPT: NTP) [CH]  


## BONUS  


3) Computer Science - Short Answer In machine language, what term refers to the sequence of bits that designates to the processor which instruction should be executed on the provided operands?  


ANSWER: Opcode [CH]  


## TOSS-UP  


4) Earth and Space - Multiple Choice Which of the following best describes the typical composition of obsidian?
W) Felsic 
X) Andesitic 
Y) Mafic 
Z) Ultramafic  


ANSWER: W) Felsic [PB]  


## BONUS  


4) Earth and Space – Multiple Choice The Lambda-CDM model is only possible if the universe fits which of the following descriptions?  


W) Homogenous and isotropic 
X) Homogenous and anisotropic 
Y) Heterogenous and isotropic 
Z) Heterogenous and anisotropic  


ANSWER: W) Homogenous and isotropic [PB]  


## TOSS-UP  


5) Math – Short Answer What is the tens digit of 11 to the 42nd power?  


ANSWER: 2 [CT]  


## BONUS  


5) Math – Short Answer Identify all of the following 3 groups that are simple groups under addition: 1) Z3; 2) Z4; 3) Z.  


ANSWER: 1 ONLY [CT]  


## TOSS-UP  


6) Physics – Short Answer How many antinodes appear in the pressure wave of a doubly-open tube resonating at its second harmonic?  


ANSWER: 2  


## BONUS
6) Physics – Multiple Choice Which of the following models of a solid treats electrons as a gas of classical charged particles constrained to periodic boundary conditions?  


W) Einstein model  
X) Debye model  
Y) Drude model  
Z) Sommerfield model  


ANSWER: Y) DRUDE MODEL [CH]  


## TOSS-UP  


7) Biology – Short Answer In yeast, mating-type switching is possible because yeast are known to carry a silenced copy of both mating factors. These extra copies of the mating factor genes are organized in what variety of condensed DNA where transcription is suppressed due to a combination of histone modifications, RNA interference, and other silencing mechanisms?  


ANSWER: HETEROCHROMATIN [JH]  


## BONUS  


7) Biology – Multiple Choice In a simplified model of the interactions between a receptor and a ligand, the steady-state equations are analogous to those of Michaelis-Menten kinetics between an enzyme and a substrate. The velocity of reaction in Michaelis-Menten kinetics best corresponds to which of the following quantities?  


W) The concentration of ligand bound to receptor  
X) The concentration of ligand bound to receptor over the total concentration of receptor  
Y) The concentration of free ligand  
Z) The concentration of free ligand over the total concentration of receptor  


ANSWER: W) THE CONCENTRATION OF LIGAND BOUND TO RECEPTOR [JH]  


## TOSS-UP  


8) Chemistry – Short Answer Upon extreme heating of potassium nitrate, potassium nitrite is formed along with the release of what compound?  


ANSWER: OXYGEN GAS (ACCEPT: \(\mathrm{O}_2\) ) [?]  


## BONUS
8) Chemistry – Short Answer Taking aromaticity into account, what is the average bond order between carbon atoms in cyclobutadiene?  


ANSWER: 5/4 [CH]  


## TOSS-UP  


9) Computer Science – Short Answer Identify all of the following 3 bash commands that are correctly matched with their purpose: 1) mkdir [make dir], creates a directory; 2) touch, deletes a file; 3) grep; searches for a string match  


ANSWER: All [CH]  


## BONUS  


9) Computer Science – Short Answer All Type-1 or context-sensitive grammars are defined as those able to be evaluated by a linear-bounded form of what theoretical computer, which consists of an infinite tape of memory and a mechanism that can read from or write to the memory tape?  


ANSWER: Turing machine [CH]  


## TOSS-UP  


10) Earth and Space – Short Answer Lines of algae are sometimes observed on the ocean surface during high winds. These lines are created by what circulation pattern, which involves circular vortices that create alternating regions of upwelling and downwelling?  


ANSWER: Langmuir circulation [PB]  


## BONUS  


10) Earth and Space – Multiple Choice Which of the following best describes the distribution of asteroids in the asteroid belt?  


W) Continuous with a peak close to the Sun 
X) Continuous with a peak further from the Sun 
Y) Separated into two distinct belts 
Z) Separated into several distinct belts  


ANSWER: Z) Separated into several distinct belts [PB]
## TOSS-UP  


11) Math - Short Answer Alice arranges 3 white marbles and 3 red marbles in a row. If she wants exactly 2 of the first 3 marbles to be white, how many different arrangements can she make?  


ANSWER: 9 [CT]  


## BONUS  


11) Math - Short Answer Two chords of length 10 and 8 are drawn in a circle such that they intersect at a point on the circle. If the chords make a 60 degree angle, what is the radius of the circle?  


ANSWER: 2 ROOT 7 [CT]  


## TOSS-UP  


12) Physics - Short Answer An electrical quadrupole is placed at the origin of a coordinate plane. At distances much farther than the length of the quadrupole, the electric field is proportional to the distance from the quadrupole raised to what power?  


ANSWER: - 4 [RE]  


## BONUS  


12) Physics - Multiple Choice A diatomic gas is adiabatically expanded from a volume of 1 cubic meter and pressure of 1 atm to a volume of \(1 \times 10^{5}\) cubic meters. What is the new pressure in atm?  


W) \(10^{-4}\) atm X) \(10^{-5}\) atm Y) \(10^{-6}\) atm Z) \(10^{-7}\) atm  


ANSWER: Z) \(10^{-7}\) atm [RE]  


## TOSS-UP
13) Biology – Multiple Choice Which of the following organelles would have the least amount of reactive oxygen species in an ordinary plant cell?  


W) Chloroplast 
X) Glyoxysome 
Y) Golgi apparatus 
Z) Mitochondria  


ANSWER: Y) GOLGI APPARATUS [JH]  


## BONUS  


13) Biology – Short Answer What disaccharide formed from two \(\alpha\) -glucose monomers is known to facilitate anhydrobiosis in many plants and also serves as the major blood sugar in many insects?  


ANSWER: TREHALOSE [JH]  


## TOSS-UP  


14) Chemistry – Short Answer When an electron is excited to the lowest excited state by incoming light, the electron may transition to a triplet state before transitioning back to the ground state. What type of photoluminescence does this process describe?  


ANSWER: Phosphorescence [CH]  


## BONUS  


14) Chemistry – Short Answer The decay of Radium-226 into Lead-206 involves only alpha and beta minus decay. Given that Radium and Lead have atomic numbers of 88 and 82 respectively, how many beta minus decays occur in this process?  


ANSWER: 4 [CH]  


## TOSS-UP  


15) Computer Science – Short Answer What data structure, commonly implemented with a dynamic array or doubly linked list, is effectively a combination of a stack and a queue, and supports constant-time insertion and deletion from both ends?  


ANSWER: Deque (ACCEPT: double ended queue, dequeue) [CH]
## BONUS  


15) Computer Science - Short Answer When implementing recursive functions, it is common for the last line of a function body to be another call to the same function. When this is the case, what type of optimization can be performed where the caller function's stack frame is popped off of the stack before beginning execution of the next function invocation?  


ANSWER: Tail call optimization (ACCEPT: Tail recursion elimination/optimization) [CH]  


## TOSS-UP  


16) Earth and Space - Short Answer Greenhouse gases absorb light in most regions of the infrared spectrum, but no major gases absorb light in the range Earth primarily radiates. What term describes the range in which this lack of absorption occurs?  


ANSWER: Atmospheric window [PB]  


## BONUS  


16) Earth and Space - Short Answer Identify all of the following three types of melting that could occur at a subduction zone: 1) Decompression; 2) Flux; 3) Friction.  


ANSWER: All [PB]  


## TOSS-UP  


17) Math - Short Answer Two teams are playing a best of 7 series, where the first team to win 4 games wins. If each team has a \(50\%\) chance of winning each game and each game is independent, what is the probability that the series ends in 4 games?  


ANSWER: 1/8 [CT]  


## BONUS  


17) Math - Short Answer A car initially at \(\mathbf{x} = 0\) starts driving in the positive \(\mathbf{x}\) direction at \(\mathbf{t} = 0\) with a speed equal to the natural log of quantity 1 plus t. How long does it take for the car to reach \(\mathbf{x} = 1\) ?  


ANSWER: e - 1 [CT]
## TOSS-UP  


18) Physics - Short Answer Two blocks with 1 kilogram mass are placed on a flat surface. One block is stationary, and the other block is sliding towards it at a speed of 2 meters per second. If the coefficient of restitution of the collision is 0.5, what is the final kinetic energy of the system in Joules?  


ANSWER: 5/4 [CH]  


## BONUS  


18) Physics - Short Answer A uniform rod with a length of 1 meter and mass of 3 kilograms is at rest. It is struck with a perpendicular impulse of 10 Newton-meters at a distance of 25 centimeters from one end. When measured in standard SI units, what is the ratio of the rod's angular momentum to its linear momentum?  


ANSWER: 3 [CH]  


## TOSS-UP  


19) Biology - Multiple Choice When performing a Western blot, Colin notes the appearance of a few bands below the expected band for his protein, though each band is very clear. Which of the following is the most likely reason why?  


W) The membrane was not blocked with milk. 
X) The secondary antibody was not specific to the primary antibody. 
Y) Insufficient amounts of SDS were added to the lysate. 
Z) Insufficient amounts of protease inhibitors were added to the lysate.  


ANSWER: Z) INSUFFICIENT AMOUNTS OF PROTEASE INHIBITORS WERE ADDED TO THE LYSATE. [JH]  


## BONUS  


19) Biology - Short Answer Order the following three events in normal human organogenesis from earliest to latest: 1) Neural crest cell migration; 2) Neural plate formation; 3) Notochord formation.  


ANSWER: 3, 2, 1 [JH]
## TOSS-UP  


20) Chemistry - Multiple Choice Alloying metals can have an effect on their strength, specifically affecting ductility, brittleness, and hardness. Compared to the primary metal constituent, which of the following best describes how interstitial and substitutional alloying affects the strength of a metal?  


W) Interstitial is weaker and substitutional is stronger 
X) Interstitial is weaker and substitutional is weaker 
Y) Interstitial is stronger and substitutional is stronger 
Z) Interstitial is stronger and substitutional is weaker  


ANSWER: Y) Interstitial is stronger and substitutional is stronger  


## BONUS  


20) Chemistry - Short Answer Order the following 3 tertiary radicals from least to most stable: 1) 1,1-dinitrobutane; 2) methylpropane; 3) 1,1-dichloropentane  


ANSWER: 2, 3, 1 [CH]  


## TOSS-UP  


21) Computer Science - Short Answer When computing the 100th Fibonacci number recursively, an algorithm stores the values for each newly computed Fibonacci number, thus saving computation on future recursive calls. What is the term for this technique common in dynamic programming where the results of subproblems are cached?  


ANSWER: MEMOIZATION [JH]  


## BONUS  


21) Computer Science - Multiple Choice In natural language processing, which of the following refers to the representations of words or phrases?  


W) Embeddings 
X) Lemmas 
Y) Segments 
Z) Tokens  


ANSWER: W) EMBEDDINGS [JH]
## TOSS-UP  


22) Earth and Space – Multiple Choice Which of the following elements would never be present in the spectrum of a type 1a supernova?  


W) Hydrogen 
X) Helium 
Y) Oxygen 
Z) Silicon  


ANSWER: W) Hydrogen [PB]  


## BONUS  


22) Earth and Space – Multiple Choice In which of the following biomes would the ratio of feldspar to clay minerals likely be highest?  


W) Savannah 
X) Taiga 
Y) Tropical rainforest 
Z) Tundra  


ANSWER: Z) Tundra [PB]  


## TOSS-UP  


23) Math – Short Answer If \(\mathrm{x} + 1 / \mathrm{x}\) equals 10, what is \(\mathrm{x}^{2} + 1 / \mathrm{x}^{2}\) ?  


ANSWER: 98 [CT]  


## BONUS  


23) Math – Short Answer An equilateral triangle and a square are both inscribed in the same circle. What is the ratio of the area of the triangle to that of the square?  


ANSWER: 3 ROOT 3 OVER 8 [CT]  


## TOSS-UP  


24) Physics – Short Answer In Mossbauer spectroscopy, a photon is emitted or absorbed from a nucleus and the resulting signal is measured. A fraction of these events, determined by the
Lamb- Mossbauer factor, are classified as “recoil- free” because they do not emit what momentum- carrying quasiparticle into the crystal lattice?  


ANSWER: Phonon [CH]  


## BONUS  


24) Physics – Short Answer Identify all of the following 3 statements that are true about the strong interaction: 1) It is governed by a SU(3) symmetry; 2) Gluons can interact with other gluons; 3) The strong interaction has a preference for chirality  


ANSWER: 1 and 2 [CH]