
## TOSS-UP  


1) BIOLOGY Short Answer Give the phenomena by which homologous chromosomes pair durin'g meiosis before crossing over?  


ANSWER: Synapsis  


## BONUS  


1) BIOLOGY Short Answer By name or number, indicate all of the following that are true concerning adenoviruses  


1) They are responsible for SARS  


2) They are responsible for respiratory tract infections of animals  


3) They are responsible for the common cold  


ANSWER: 2  


## TOSS-UP  


2) EARTH AND SPACE Multiple Choice Which of the following branches of the HR diagram would a star that has just begun helium fusion reside on?  


W) Red giant  


X) Horizontal  


Y) Asymptotic giant  


Z) Turn off  


ANSWER: X) Horizontal  


## BONUS  


2) EARTH AND SPACE Multiple Choice According to the unified model of active galaxies, which of the following viewing orientations in respect to a black hole would result in a type 2 Seyfert galaxy.  


W) Face on to the torus 
X) Angled to the torus 
Y) Edge on to the torus 
Z) Face on to the event horizon
ANSWER: Y) Edge on to the torus  


## TOSS-UP  


3) MATH Short Answer What is the distance from the point (3,4) to the line -6x+5y=12? ANSWER: 2sqrt(61)/61  


## BONUS  


3) MATH Short Answer Give the unit direction vector for the line of intersection between the planes x+2y=0 and y-z=1.  


ANSWER: i+j+k  


## TOSS-UP  


4) PHYSICS Short Answer Rank the following three interactions by order of increasing distance.  


1) Weak force  
2) Strong force  
3) Electromagnetic interaction  


ANSWER: 1, 2 3  


## BONUS  


4) PHYSICS Multiple Choice Which of the following is true about the magnitude of the residual strong force?  


W) Decreases with distance  


X) Increases with distance  


Y) Remains constant with distance  


Z) It increases then decreases  


ANSWER: Z) It increases then decreases  


## TOSS-UP  


5) CHEMISTRY Multiple Choice Which of the following two equimolar solutions will produce a pH closest to neutral when mixed?
W) Acetic acid and calcium hydroxide  


X) Acetic acid and ammonia  


Y) Hydrochloric acid and calcium hydroxide  


Z) Hydrochloric acid and ammonia  


ANSWER: X) Acetic acid and ammonia  


## BONUS  


5) CHEMISTRY Short Answer A single electron in its ground state is trapped in a 1-dimensional infinite potential well. When subjected to light with a wavelength of \(800 \mathrm{nm}\) , it enters its first excited state. Determine the wavelength of light that is required for the electron to enter its second excited state from its ground state.  


ANSWER: 300 nm  


## TOSS-UP  


6) BIOLOGY Multiple Choice Which of the following neurotransmitters is secreted significantly in the enteric nervous system to control digestion?  


W) Serotonin  


X) Glutamate  


Y) Dopamine  


Z) Norepinephrine  


ANSWER: W  


## BONUS  


6) BIOLOGY Short Answer The ependymal cells of the choroid plexus secrete what fluid?  


ANSWER: Cerebrospinal Fluid  


## TOSS-UP  


7) EARTH AND SPACE Multiple Choice Which of the following mechanisms results in cloud formation on the windward side of mountain ranges?
W) Orographic lifting  


X) Frontal wedging  


Y) Convection  


Z) Convergence lifting  


ANSWER: W) Orographic lifting  


## BONUS  


7) EARTH AND SPACE Short Answer Give the common name for all the following features of volcanoes.  


I. Cone shaped accumulations from magma flow separate from the central vent  
II. Incandescent cloud of gas and ash that rushes down the sides of the volcano  
III. Dome of granite that remains after most of the volcano has eroded away  


ANSWER: Parasitic cone, pyroclastic flow (nuee ardente), inselberg  


## TOSS-UP  


8) MATH Short Answer 5 sheep and 1 wolf are arranged in a circle. The wolf either eats the sheep on his left or right with equal probability, and keeps repeating this process with the remaining sheep. What is the probability that the last sheep to be eaten is the sheep initially located diametrically opposite the wolf?  


ANSWER: 3/8  


## BONUS  


8) MATH Short Answer Arun randomly and uniformly picks a real number in [0,10]. If the first number he picks is A, he then randomly picks a second real number B in [0,A]. What is the probability that B is less than 4?  


ANSWER: 16/25  


## TOSS-UP  


9) PHYSICS Short Answer A mass is hanging from a spring and is given a small push. Indicate all of the following choices that would increase the period of oscillation.  


1) Doubling the mass  
2) Adding another spring in parallel
3) Increasing the gravitational acceleration  


ANSWER: 1  


## BONUS  


9) PHYSICS Short Answer A 4 kg ball is rolling around at the bottom of a hollow hemispherical surface. This surface has a radius of curvature of 1 meter. What is the angular frequency of the ball if it is given a small push, to 1 significant digit? Neglect friction.  


ANSWER: 3 (rad/s)  


## TOSS-UP  


10) CHEMISTRY Short Answer Identify all of the following three molecules that have noninteger bond orders:  


I. \(C_{2}\) II. \(\mathrm{B}_{2}\mathrm{H}_{6}\) III. OF2  


ANSWER: II  


## BONUS  


10) CHEMISTRY Short Answer Compound A can undergo two parallel reactions to form B and C with rate constants \(k_{B} = 0.2 \mathrm{s}^{-1}\) and \(k_{C} = 0.5 \mathrm{s}^{-1}\) . To the nearest second, what is the half life of compound A?  


ANSWER: 1 second  


## TOSS-UP  


11) BIOLOGY Multiple Choice The pGLO plasmid is induced in the presence of what sugar?  


W) Lactose  


X) Glucose  


Y) Erythrose  


Z) Arabinose  


ANSWER: Z
## BONUS  


11) BIOLOGY Short Answer The sarcolemma is the plasma membrane of what type of human cell?  


ANSWER: Muscle Cell  


## TOSS-UP  


12) EARTH AND SPACE Short Answer How many points are needed to find the epicenter of a earthquake?  


ANSWER: 3  


## BONUS  


12) EARTH AND SPACE Short Answer What type of metamorphism occurs when hydrothermal fluids alter the chemical composition of the rock?  


ANSWER: Metasomatism  


## TOSS-UP  


13) MATH Multiple Choice Which of the following expressions is equivalent to \((\sin x - \cos x)^{\wedge}2 + (\sin x + \cos x)^{\wedge}2?\)  


W) \(1 - 2\sin (x)\)  


X) \(1 - \sin (2x)\)  


Y) 4 tan x  


Z) 2  


ANSWER: Z) 2  


## BONUS  


13) MATH Short Answer What is the x value which satisfies the condition of the Mean Value Theorem for \(\mathrm{f(x) = x^{\wedge}3}\) on the interval [0,2]?  


ANSWER: 2sqrt(3)/3
## TOSS-UP  


14) PHYSICS Short Answer Give the Gaussian surface associated with application of Gauss's Law for each of the following 3 charge distributions:  


I. Infinite charged plate 
II. Infinitely long wire 
III. Point charge  


ANSWER: I. cylinder, II. cylinder, III. sphere  


## BONUS  


14) PHYSICS Short Answer What is the resonant angular frequency of an RLC circuit consisting of a 5 H inductor, 5 F capacitor, 35 ohm resistor?  


ANSWER: 0.2  


## TOSS-UP  


15) CHEMISTRY Multiple Choice When the natural log of the equilibrium constant is graphed against 1/T for a certain reaction, the graph is linear with a positive slope and positive y-intercept. Which of the following can be concluded from the graph?  


W) The reaction is always spontaneous  


X) The reaction is never spontaneous  


Y) The reaction is spontaneous at high temperatures  


Z) The reaction is spontaneous at low temperatures  


ANSWER: W) The reaction is always spontaneous  


## BONUS  


15) CHEMISTRY Short Answer The reversible oxidation of \(\mathrm{Ce}^{3 + }\) to \(\mathrm{Ce}^{4 + }\) , with standard potential \(-1.7 \mathrm{~V}\) , is performed against a reference hydrogen electrode held at a pH of 0 with an applied potential difference that increases linearly with time. The absorbance of \(\mathrm{Ce}^{4 + }\) is monitored throughout the experiment with a spectrophotometer. Identify all of the following three statements that are true:  


I. The absorbance of the solution increases linearly with time 
II. The absorbance is maximal when the applied potential is 1.7 V
III. The pH of the solution increases  


ANSWER: None  


## TOSS-UP  


16) BIOLOGY Short Answer Which part of the limbic system is central to addiction by being the dopamine center for motivation?  


ANSWER: Nucleus Accumbens  


## BONUS  


16) BIOLOGY Short Answer By name or number, indicate all of the following that are true of heat shock.  


1) Requires calcium chloride  
2) Used to open adhesion pores  
3) Cannot be used to introduce plasmids into bacteria  


ANSWER: 12  


## TOSS-UP  


17) EARTH AND SPACE Multiple Choice By name or number, identify the period for each of the following epochs:  


I. Oligocene  
II. Pennsylvania  
III. Lopingian  


ANSWER: I. Paleogene, II. Carboniferous, III. Permian  


## BONUS  


17) EARTH AND SPACE Short Answer By name or number, indicate all of the following 3 statements which must be true of Artesian wells:  


I. Their height must be below that of the pressure surface  
II. A permeable rock layer must be located between two aquicludes  
III. They can increase the rate of cavern formation in limestone aquifers  


ANSWER: All
## TOSS-UP  


18) MATH Short Answer If John throws a stone and he models the stone's height in meters with the function \(\mathrm{h(t) = 5t^{\wedge}2 - 3t + 9}\) , what is the horizontal distance from John's position and the point of maximum height in terms of meters.  


ANSWER: 3/10  


## BONUS  


18) MATH Short Answer Find the area bounded by the \(\mathrm{y = x^{\wedge}2}\) , \(\mathrm{y = -x + 2}\) , and \(\mathrm{x = 0}\)  


ANSWER: 7/6  


## TOSS-UP  


19) PHYSICS Multiple Choice A balloon feels a buoyant force of F when submerged near the water surface. Approximately how far down must we push the balloon so that it feels a force \(\frac{1}{2}\mathrm{F}\) ?  


W) 2m  


X) 5m  


Y) 7m  


Z) 10m  


ANSWER: Z) 10m  


## BONUS  


19) PHYSICS Short Answer Suppose electrons in a conductor follow the fermi dirac distribution. Which of the following would increase the number of electrons at an energy level of 8J, where the fermi energy is 6J?  


1) Increase temperature 
2) Decrease fermi energy 
3) Increase electrical potential  


ANSWER: 1
20) CHEMISTRY Short Answer Identify all of the following three models in which the HOMO-LUMO gap increases in energy with increasing principal quantum number:  


I. Bohr hydrogen atom  
II. 1-dimensional box  
III. Spherical potential well  


ANSWER: II, III  


## BONUS  


20) CHEMISTRY Short Answer A 1 L sample of helium gas is expanded isothermally to a final volume of 8 L. It is then cooled at constant volume until its entropy is the same as its initial state. If the ratio of the initial to final temperature of the gas is \(\ln k\) , determine \(k\) .  


ANSWER: 4  


## TOSS-UP  


21) BIOLOGY Short Answer Fermentation is carried out in order to regenerate what molecule?  


ANSWER: NAD+ (DO NOT ACCEPT: NADH)  


## BONUS  


21) BIOLOGY Short Answer By name or number, indicate all of the following that are anticoagulants.  


1) Aspirin  
2) Heparin  
3) Warfarin  
4) Prostacyclin [PGI<sub>2</sub>]  


ANSWER: all  


## TOSS-UP  


22) EARTH AND SPACE Multiple Choice Which of the following characteristics is not true about extreme population II type stars?  


W) They reside in the halo  
X) They have eccentric orbits
Y) They are the oldest starsZ) They are metal rich  


ANSWER: Z) They are metal rich  


## BONUS  


22) EARTH AND SPACE Short Answer What type of focus utilizes a thin correcting lense above the secondary mirror, ultimately allowing light to escape through a hole at the bottom of the objective mirror?  


ANSWER: Schmidt-Cassegrain  


## TOSS-UP  


23) MATH Short Answer Estimate to three significant digits the following using a first order expansion: \(e^{0.02}\)  


ANSWER: 1.02  


## BONUS  


23) MATH Short Answer What is the surface integral over a closed spherical shell of radius 6 centered at the origin of the function \(\mathrm{xi} + \mathrm{yj} + \mathrm{zk}\) ?  


ANSWER: 1728pi  


## TOSS-UP  


24) PHYSICS Multiple Choice The solution to the twin paradox in special relativity can be explained by what?  


W) Time dilation  


X) Non-inertial reference frames  


Y) The equivalence principle  


Z) Gravitational waves  


ANSWER: X) Non-inertial reference frames  


## BONUS
24) PHYSICS Multiple Choice Two events A and B occur at the spacetime coordinates \((x, ct) = (4, 5)\) for event a and (9, 8) for event B. These events are:  


W) Timelike 
X) Spacelike 
Y) Lightlike 
Z) Pointlike 
ANSWER: X) Spacelike  


## TOSS-UP  


25) CHEMISTRY Short Answer Rank the following three diatomic molecules in increasing ionization energy: \(\mathrm{N}_{2}\) , \(\mathrm{O}_{2}\) , \(\mathrm{F}_{2}\) .  


ANSWER: II, III, I  


## BONUS  


25) CHEMISTRY Short Answer There exists a curious electron-rich compound C where the standard reduction potential from the \(+n\) oxidation state to the 0 oxidation state is \(n\) volts. What is the standard reduction potential of the reduction of \(\mathrm{C}^{2020 + }\) to \(\mathrm{C}^{2019 + }\) ?  


ANSWER: 4039 V