sub_title[[458, 127, 536, 144]]
## TOSS-UP  

text[[56, 161, 912, 197]]
1) Physics – Short Answer When unpolarized light strikes a material at a specific angle, the light reflected is perfectly polarized. What law in optics uses the index of refraction of the material to find the measure of this angle?  

text[[57, 213, 301, 230]]
ANSWER: BREWSTER'S LAW  

sub_title[[465, 247, 530, 264]]
## BONUS  

text[[57, 281, 901, 333]]
1) Physics – Short Answer A wave of light initially passes through a polarizer, then through an analyzer with a transmission axis at an angle of 60 degrees to the polarizer's axis. If the light has an intensity X when incident on the analyzer, what will the intensity of the light be after it passes through the analyzer, in terms of X?  

text[[57, 349, 171, 365]]
ANSWER: X/4  

sub_title[[458, 417, 536, 434]]
## TOSS-UP  

text[[56, 451, 928, 504]]
2) Chemistry – Short Answer State all of the following four gas laws that relate any of the temperature, volume, or pressure of an ideal gas and who's equations can be used to form the ideal gas law: 1) Charles' Law 2) Graham's Law 3) Gay-Lussac's Law 4) Boyle's Law  

text[[57, 520, 189, 537]]
ANSWER: 1, 3, 4  

sub_title[[465, 554, 530, 570]]
## BONUS  

text[[57, 588, 936, 656]]
2) Chemistry – Short Answer A glass bowl of mass 2.5 kilograms contains a quantity of water of mass 2 kilograms, and both are at a temperature of 15 degrees celsius. Given that the specific heat of glass is 840 J/kg\*C and the specific heat of water is 4186 J/kg\*C, how much heat input in kilojoules needed to raise the temperature of both the glass bowl and the water to 30 degrees celsius, rounded to the nearest whole number?  

text[[57, 672, 283, 689]]
ANSWER: 157 KILOJOULESsub_title[[455, 71, 540, 88]]
## TOSS-UP  

text[[55, 110, 888, 145]]
3) Biology – Short Answer How many sister chromatids are contained in a diploid human cell that is undergoing metaphase?  

text[[56, 162, 163, 179]]
ANSWER: 92  

sub_title[[464, 197, 530, 214]]
## BONUS  

text[[55, 230, 928, 266]]
3) Biology – Short Answer For each of the following four phenomena, determine whether it occurs more commonly in animal or plant cells.  

text[[65, 282, 496, 350]]
I. Lysing when immersed in a hypotonic solution  
II. Plasmolysis when immersed in a hypertonic solution  
III. Formation of a cleavage furrow during cytokinesis  
IV. Presence of centrioles in the cytoplasm  

text[[56, 366, 642, 384]]
ANSWER: ANIMAL CELL, PLANT CELL, ANIMAL CELL, ANIMAL CELL  

sub_title[[458, 434, 537, 451]]
## TOSS-UP  

text[[56, 467, 768, 487]]
4) Math – Short Answer If \(a\) and \(b\) are the zeros of \(f(x) = x^{2} + 17x + 20\), find the value of \(a^{2} + b^{2}\).  

text[[56, 503, 171, 520]]
ANSWER: 249  

sub_title[[464, 537, 530, 554]]
## BONUS  

text[[55, 570, 753, 590]]
4) Math – Short Answer Find the derivative at \(x = 4\) for the function \(f(x) = x^{3} + 23x^{2} + 56x + 4\).  

text[[56, 606, 171, 622]]
ANSWER: 288sub_title[[455, 71, 540, 88]]
## TOSS-UP  

text[[55, 110, 940, 163]]
5) Earth and Space Science – Short Answer Identify, by name or number, all of the following three that are basic laws of radiation: 1) All objects emit radiant energy; 2) Hotter objects radiate more total energy than do colder objects; 3) The hotter the radiating body, the shorter the wavelengths of maximum radiation.  

text[[57, 180, 237, 197]]
ANSWER: All or I, II, III  

sub_title[[465, 214, 530, 231]]
## BONUS  

text[[55, 248, 700, 266]]
5) Earth and Space Science – Multiple Choice Which way do isotherms generally trend?  

text[[56, 266, 191, 333]]
W) West to East 
X) East to West 
Y) North to South 
Z) South to North  

text[[57, 351, 259, 368]]
ANSWER: X) East to West  

sub_title[[458, 418, 536, 435]]
## TOSS-UP  

text[[55, 452, 904, 488]]
6) Physics – Multiple Choice Under which of the following conditions would the kinematic equations used to relate position, velocity, and acceleration not apply?  

text[[56, 504, 246, 571]]
W) Negative Position 
X) Negative Velocity 
Y) Constant Acceleration 
Z) Changing Acceleration  

text[[56, 588, 404, 605]]
ANSWER: Z) CHANGING ACCELERATION  

sub_title[[465, 622, 530, 639]]
## BONUS  

text[[56, 657, 924, 708]]
6) Physics – Multiple Choice A box sits at the top of a frictionless ramp at an angle of 30 degrees and a slope of length 25 meters. If the box begins to slide down the ramp from rest, what will its final velocity be, in meters per second to the nearest tenth, just before it slides off the ramp?  

text[[57, 725, 175, 741]]
ANSWER: 15.7sub_title[[455, 71, 541, 88]]
## TOSS-UP  

text[[55, 110, 919, 145]]
7) Chemistry – Multiple Choice If an electron has a principal quantum number of 3, which of the following is NOT a possible value for its magnetic quantum number?  

text[[56, 162, 102, 230]]
W)-2 X)0 Y)1 Z)3  

text[[56, 248, 175, 265]]
ANSWER: Z)3  

sub_title[[465, 281, 530, 298]]
## BONUS  

text[[55, 315, 870, 350]]
7) Chemistry – Multiple Choice If a certain ion has an electron configuration of \(1s^2 2s^2 2p^6 3s^2 3p^6\) , which of the following could be the identity of the ion?  

text[[56, 366, 115, 437]]
W) \(F^{+}\) X) \(N^{3 - }\) Y) \(P^{3 - }\) Z) \(N i^{2 + }\)  

text[[56, 455, 197, 473]]
ANSWER: Y) \(P^{3 - }\)  

sub_title[[458, 525, 537, 542]]
## TOSS-UP  

text[[55, 559, 916, 578]]
8) Biology – Multiple Choice At any given point, the majority of cells in the human body are in what cellular phase?  

text[[56, 594, 105, 660]]
W) \(G_{0}\) X) \(G_{1}\) Y) \(G_{2}\) Z) M  

text[[56, 679, 191, 696]]
ANSWER: W) \(G_{0}\)  

sub_title[[465, 713, 530, 730]]
## BONUS  

text[[55, 747, 691, 766]]
8) Biology – Multiple Choice Which of the following is not an example of apoptosis?  

text[[56, 782, 640, 848]]
W) Formation of an embryo's digits through the elimination of interdigital tissue 
X) Reduction of a tadpole's tail as it matures into an adult frog 
Y) Neuron death in Parkinson's disease 
Z) An organism's death due to cancer metastasis  

text[[56, 865, 636, 882]]
ANSWER: Z) AN ORGANISM'S DEATH DUE TO CANCER METASTASISsub_title[[455, 71, 540, 88]]
## TOSS-UP  

text[[55, 110, 923, 145]]
9) Math – Short Answer Let P be a point inside equilateral triangle ABC such that AB=2. Find the sum of the shortest lengths from P to all the sides of ABC  

text[[56, 162, 196, 179]]
ANSWER: Sqrt(3)  

sub_title[[464, 197, 530, 213]]
## BONUS  

text[[55, 230, 866, 248]]
9) Math – Short Answer Find the sum of the coefficients of the derivative of \(x^{\wedge}2020 + x^{\wedge}2019 + x^{\wedge}2018 + \ldots + x + 1\)  

text[[56, 265, 216, 281]]
ANSWER: 2,041,210  

sub_title[[460, 333, 536, 350]]
## TOSS-UP  

text[[56, 366, 926, 401]]
10) Earth and Space Science – Short Answer Calculate the mixing ratio if the mass of water vapor in a unit of air is 20 grams and the mass of dry air is 1000 grams.  

text[[56, 418, 163, 434]]
ANSWER: 20  

sub_title[[464, 452, 530, 469]]
## BONUS  

text[[56, 485, 924, 520]]
10) Earth and Space Science – Short Answer Calculate the relative humidity if the air’s actual water-vapor content is 5 grams and the saturation at 25 degrees celsius is 50 grams.  

text[[56, 537, 178, 553]]
ANSWER: \(10\%\)sub_title[[456, 72, 540, 88]]
## TOSS-UP  

text[[56, 161, 911, 197]]
11) Physics – Short Answer For a charge moving with a constant velocity away from a viewer’s perspective, in what direction will the magnetic force vector and magnetic field vector point, respectively?  

text[[57, 214, 368, 230]]
ANSWER: UPWARD AND LEFTWARD  

sub_title[[464, 265, 530, 282]]
## BONUS  

text[[57, 299, 921, 350]]
11) Physics – Short Answer A car is driving around a circular track of radius 50 meters with a velocity of 6 meters per second. What must be the minimum value, to the nearest hundredth, of the coefficient of friction of the track if the car needs to move without sliding?  

text[[57, 367, 175, 383]]
ANSWER: 0.07  

sub_title[[459, 435, 536, 452]]
## TOSS-UP  

text[[57, 469, 936, 504]]
12) Biology – Multiple Choice Which of the following is not true for plants that undergo crassulacean acid metabolism, also known as CAM plants?  

text[[57, 520, 710, 589]]
W) CAM plants close their stomata during the day and open their stomata during the night 
X) CAM plants synthesize and store malic acid inside vacuoles in their cells at night 
Y) CAM plants often have thick leaves and a thick plant cuticle 
Z) CAM plants are most commonly found in humid climates  

text[[57, 605, 734, 622]]
ANSWER: Z) CAM PLANTS ARE MOST COMMONLY FOUND IN HUMID CLIMATES  

sub_title[[464, 640, 530, 656]]
## BONUS  

text[[57, 673, 912, 691]]
12) Biology – Short Answer Order the following three colors of light from least to most absorption by chlorophyll \(b\) .  

text[[68, 708, 163, 757]]
I. Blue 
II. Green 
III. Red  

text[[57, 776, 199, 792]]
ANSWER: II, III, Isub_title[[455, 72, 540, 89]]
## TOSS-UP  

text[[56, 110, 914, 146]]
13) Chemistry – Short Answer What type of reaction occurs when silver nitrate is combined with a solution of sodium chloride to produce the compound silver chloride as one of its products?  

text[[57, 161, 279, 179]]
ANSWER: PRECIPITATION  

sub_title[[465, 197, 530, 214]]
## BONUS  

text[[57, 230, 940, 266]]
13) Chemistry – Short Answer Identify the element that has the characteristic of the following given atomic properties: 1) Highest Electron Affinity 2) Highest Electronegativity 3) Lowest Atomic Radius  

text[[57, 281, 462, 300]]
ANSWER: 1) CHLORINE 2) FLUORINE 3) HELIUM  

sub_title[[460, 350, 537, 367]]
## TOSS-UP  

text[[57, 383, 809, 402]]
14) Math – Short Answer What is the largest number that cannot be written as a sum of 99s and 101s?  

text[[57, 417, 181, 434]]
ANSWER: 9799  

sub_title[[465, 452, 530, 469]]
## BONUS  

text[[57, 485, 936, 521]]
14) Math – Short Answer Four students got scores of 83, 87, 92, and 98 on a paper. In how many orders can the teacher pass back the papers so that the average score of the papers that have been passed back is always an integer?  

text[[57, 536, 153, 553]]
ANSWER: 2sub_title[[455, 71, 540, 88]]
## TOSS-UP  

text[[55, 110, 848, 129]]
15) Earth and Space Science – Multiple Choice Which of the following is not a classification for meteorites?  

text[[56, 129, 225, 214]]
W) Irons  X) Stony-Irons  Y) Chondrites  Z) Stonites  ANSWER: Z) Stonites  

sub_title[[464, 231, 530, 248]]
## BONUS  

text[[55, 264, 940, 315]]
15) Earth and Space Science – Multiple Choice If the temperature of 1 star is -40 degrees celsius while the other star has a temperature of -40 degrees fahrenheit then how many times greater is the total radiation emitted from 1 star compared to the other star?  

text[[56, 316, 123, 330]]
W) 16  

text[[56, 333, 92, 347]]
X) 8  

text[[56, 350, 92, 365]]
Y) 4  

text[[56, 368, 92, 381]]
Z) 1  

text[[56, 385, 172, 400]]
ANSWER: Z) 1  

sub_title[[458, 452, 537, 469]]
## TOSS-UP  

text[[56, 485, 904, 520]]
16) Physics – Multiple Choice Which one of the following Maxwell’s equations can be used to relate the flow of an electric field through an area to the charge enclosed?  

text[[56, 537, 295, 605]]
W) Gauss’ Law for Magnetism  X) Faraday’s Law of Induction  Y) Modified Ampere’s Equation  Z) Gauss’ Law of Electric Flux  

text[[56, 621, 445, 639]]
ANSWER: Z) GAUSS’ LAW OF ELECTRIC FLUX  

sub_title[[464, 656, 530, 673]]
## BONUS  

text[[56, 690, 933, 742]]
16) Physics – Multiple Choice A charge of 2 microcoulombs is moving in the positive x direction with a velocity of 5 meters per second, with a magnetic field of strength 3 microteslas oriented at an angle of 30 degrees to the velocity of the charge. What is the magnitude of the magnetic force, in newtons exerted on the test charge?  

text[[57, 758, 234, 775]]
ANSWER: \(1.5 * 10^{- 11}\)sub_title[[455, 71, 540, 88]]
## TOSS-UP  

text[[56, 110, 901, 163]]
17) Math – Short Answer In the GammaZero committee there are 13 men and 5 women. They randomly create a subcommittee called the BetaZero committee consisting of 2 people. What is the probability that there is 1 man and 1 woman on this committee?  

text[[57, 180, 184, 197]]
ANSWER: 13/21  

sub_title[[459, 214, 524, 231]]
## BONUS  

text[[57, 247, 658, 266]]
17) Math – Short Answer What is the remainder when 2016! is divided by 2017?  

text[[57, 283, 181, 300]]
ANSWER: 2016  

sub_title[[451, 350, 530, 367]]
## TOSS-UP  

text[[57, 383, 736, 402]]
18) Chemistry – Short Answer What bonds are created by the sideway overlap of p orbitals?  

text[[57, 418, 210, 435]]
ANSWER: Pi Bonds  

sub_title[[459, 452, 524, 469]]
## BONUS  

text[[57, 485, 881, 521]]
18) Chemistry – Short Answer When solid, liquid and gas are at equilibrium what is that point called on a phase diagram?  

text[[57, 537, 231, 555]]
ANSWER: Triple Pointsub_title[[455, 71, 540, 88]]
## TOSS-UP  

text[[56, 110, 912, 146]]
19) Biology - Short Answer In which of the following three stages are distinct chromosomes observable with a light microscope?  

text[[69, 163, 203, 214]]
I. Interphase II. Metaphase III. Cytokinesis  

text[[57, 230, 157, 247]]
ANSWER: II  

sub_title[[465, 265, 530, 282]]
## BONUS  

text[[57, 299, 875, 318]]
19) Biology - Short Answer Order the following three stages of the cell cycle from shortest to longest duration.  

text[[70, 334, 219, 385]]
I. Interphase II. Prometaphase III. Anaphase  

text[[57, 401, 200, 418]]
ANSWER: III, II, I  

sub_title[[460, 469, 536, 485]]
## TOSS-UP  

text[[55, 502, 931, 538]]
20) Earth and Space Science - Short Answer What is it called when the lens acts like a prism and spreads out the colors in the light?  

text[[57, 555, 303, 572]]
ANSWER: Chromatic Aberration  

sub_title[[465, 589, 530, 606]]
## BONUS  

text[[55, 622, 797, 641]]
20) Earth and Space Science - Question Type Approximately how many years is one sunspot cycle?  

text[[57, 657, 161, 673]]
ANSWER: 11sub_title[[455, 71, 540, 88]]
## TOSS-UP  

text[[55, 110, 937, 163]]
21) Physics – Multiple Choice According to the Stefan-Boltzmann Equation, used to find the heat flow due to radiation emitted by an object, the emitted energy of an object per unit time due to radiation is proportional to its temperature raised to what power?  

text[[56, 180, 98, 250]]
W) 1  X) 2  Y) 4  Z) 16  

text[[57, 266, 177, 283]]
ANSWER: Y) 4  

sub_title[[465, 299, 530, 316]]
## BONUS  

text[[55, 332, 937, 401]]
21) Physics – Multiple Choice The end of a square aluminium rod is placed near a heat source and is at a temperature of 60 degrees celsius. Given that the thermal conductivity of aluminium is \(200 \mathrm{J / s} \cdot \mathrm{m} \cdot \mathrm{^\circ C}\) and the cross sectional area through which heat transfer occurs is \(10 \mathrm{cm} \cdot \mathrm{^\circ C}\) , what is the heat flow, in Joules per second to the nearest whole number, to a point on the rod \(15 \mathrm{cm}\) away from the end at a temperature of 55 degrees celsius?  

text[[56, 417, 99, 485]]
W) 3  X) 7  Y) 18  Z) 30  

text[[57, 503, 177, 520]]
ANSWER: X) 7  

sub_title[[460, 571, 536, 588]]
## TOSS-UP  

text[[55, 604, 928, 640]]
22) Chemistry – Short Answer a-decay(read as alpha decay) will decrease the mass number by x and the atomic number by y. Find the product of x and y.  

text[[57, 656, 154, 673]]
ANSWER: 8  

sub_title[[465, 690, 530, 707]]
## BONUS  

text[[55, 723, 886, 742]]
22) Chemistry – Short Answer What is it called when larger unstable nuclei split into smaller more stable nuclei?  

text[[57, 758, 365, 775]]
ANSWER: Fission accept Nuclear Fissionsub_title[[455, 71, 540, 88]]
## TOSS-UP  

text[[55, 110, 804, 128]]
23) Earth and Space Science - Multiple Choice Which of the following was not a part of Gondwana?  

text[[56, 128, 195, 197]]
W) South America 
X) India 
Y) Antarctica 
Z) Siberia  

text[[56, 214, 216, 231]]
ANSWER: Z) Siberia  

sub_title[[465, 248, 530, 265]]
## BONUS  

text[[55, 281, 900, 300]]
23) Earth and Space Science - Short Answer What is the distance that wind has traveled across open water called?  

text[[56, 316, 184, 332]]
ANSWER: Fetch  

sub_title[[460, 383, 536, 400]]
## TOSS-UP  

text[[55, 417, 939, 452]]
24) Biology - Short Answer Which of the following four invertebrate phyla are characterized by the inclusion of a brain in their nervous systems?  

text[[67, 469, 234, 536]]
I. Echinodermata 
II. Annelida 
III. Platyhelminthes 
IV. Tardigrada  

text[[56, 553, 211, 570]]
ANSWER: II, III, IV  

sub_title[[465, 588, 530, 604]]
## BONUS  

text[[55, 621, 936, 657]]
24) Biology - Short Answer For each of the following three examples, determine whether the response is caused by the sympathetic division or the parasympathetic division of the autonomic nervous system.  

text[[67, 673, 339, 724]]
I. Increased glycogen production 
II. Dilation of the pupils 
III. Constriction of the bronchi  

text[[56, 740, 635, 758]]
ANSWER: PARASYMPATHETIC, SYMPATHETIC, PARASYMPATHETIC  

sub_title[[460, 827, 536, 843]]
## TOSS-UP  

text[[55, 860, 641, 878]]
25) Math - Multiple Choice Which of the following is not a deficient number?  

text[[56, 895, 108, 928]]
W) 27 
X) 223title[[455, 72, 541, 88]]
# TOSS-UP  

text[[56, 112, 110, 145]]
Y) 224Z) 259  

text[[56, 162, 196, 179]]
ANSWER: Y) 224  

sub_title[[465, 198, 530, 214]]
## BONUS  

text[[56, 230, 581, 248]]
25) Math - Short Answer Find all real solutions of \(x^{3} - 4x^{2} - 4x - 5 = 0\) .  

text[[56, 264, 153, 280]]
ANSWER: 5