
## TOSS-UP  


1) Physics – Multiple Choice The decay of uranium 238, which has an atomic number of 92, to lead 206, which has an atomic number of 82, has 14 steps. Which of the following correctly gives how many steps in the decay pathway are alpha decay and beta minus decay, respectively?  


W) 6 alpha, 8 beta minus X) 7 alpha, 7 beta minus Y) 8 alpha, 6 beta minus Z) 9 alpha, 5 beta minus  


ANSWER: X) 8 ALPHA, 6 BETA MINUS  


## BONUS  


1) Physics – Short Answer A particle's displacement can be described as a function of time by \(\mathrm{r(t)} = 12\mathrm{t}^2 + 3\mathrm{t} + 2\) . Identify all of the following three statements that are true about the particle's motion: 1) It has constant acceleration; 2) It is constantly increasing in displacement; 3) It has constant jerk.  


ANSWER: 1 AND 3  


## TOSS-UP  


2) Math – Multiple Choice Which of the following could not be the measure in degrees of each interior angle in a regular polygon?  


W) 172 X) 173 Y) 174 Z) 175  


ANSWER: X) 173  


## BONUS  


2) Math – Short Answer Sean and Gideon are rolling a pair of six sided dice, with Sean rolling first. If Sean rolls a pair of dice whose top faces sum to 9, Sean wins the game. If not, Gideon rolls the dice and tries to achieve the same objective. The game continues until Sean or Gideon roll a sum of 9. What is the probability that Gideon wins the game?  


ANSWER: 8/17
## TOSS-UP  


3) Biology - Multiple Choice Which of the following is not characteristic of all chordates?  


W) Post anal tail  X) Somite derived vertebrae  Y) Pharyngeal slits  Z) Notochord  


ANSWER: X) SOMITE DERIVED VERTEBRAE  


## BONUS  


3) Biology - Short Answer Which extremely rare blood phenotype is unique in that it doesn't exhibit the H antigen and thus can donate blood to all A, AB and O patients but cannot receive blood from any of those same patients?  


ANSWER: BOMBAY PHENOTYPE  


## TOSS-UP  


4) Chemistry - Multiple Choice Which of the following substances has an activity factor of 1?  


W) Liquid water  X) Solid aluminum  Y) Liquid benzene  Z) Aqueous sodium chloride  


ANSWER: Z) AQUEOUS SODIUM CHLORIDE  


## BONUS  


4) Chemistry - Multiple Choice What is the oxidation state of carbon in formic acid?  


W)-2  X)0  Y)+2  Z)+4  


ANSWER: Y)+2
## TOSS-UP  


5) Earth and Space – Short Answer Identify all of the following three features that are concordant: 1) Sill; 2) Stock; 3) Dike.  


ANSWER: 1 ONLY  


## BONUS  


5) Earth and Space – Short Answer Some precipitation formed in clouds fall as streaks from the sky but sublimes or evaporates before it hits the ground. What term is given to this precipitation?  


ANSWER: VIRGA  


## TOSS-UP  


6) Physics – Short Answer What operator in quantum mechanics is the eigenvalue of the energy matrix, and is equivalent to the sum of kinetic and potential energy?  


ANSWER: HAMILTONIAN  


## BONUS  


6) Physics – Short Answer An RLC circuit has a resistor with resistance 2 milliohms, an inductor with an inductance of 3 millihneries, and a capacitor with a capacitance of 6 microfarads all in series. What is the time constant of the circuit in seconds?  


ANSWER: 3 SECONDS
## TOSS-UP  


7) Math – Short Answer Alex is giving \(\) 2.36\(to Gideon in quarters, nickels, dimes, and pennies. What is the absolute difference between the minimum and maximum number of coins Alex could use?  


ANSWER: 225  


## BONUS  


7) Math – Short Answer What is the units digit of \(1^{2020} + 2^{2020} + 3^{2020} + \ldots + 9^{2020}\) ?  


ANSWER: 3  


## TOSS-UP  


8) Biology – Short Answer Brushfield spots are often indicative of the aneuploidy of which chromosome?  


ANSWER: 21  


## BONUS  


8) Biology – Short Answer Identify all of the following proteins that correspond correctly to the disorder caused when they are misfolded: 1) \(\alpha\) -synuclein - Alzheimer's; 2) \(\beta\) amyloid - Parkinson's; 3) Huntington - Huntington's.  


ANSWER: 3 ONLY
## TOSS-UP  


9) Chemistry – Short Answer What is the molecular geometry and hybridization, respectively, of xenon difluoride?  


ANSWER: LINEAR; dsp<sup>3</sup>  


## BONUS  


9) Chemistry – Multiple Choice Which of the following colors would absorb the lowest energy light?  


W) Violet  X) Green  Y) Yellow  Z) Red  


ANSWER: X) GREEN  


## TOSS-UP  


10) Earth and Space – Multiple Choice Which of the following objects is not found in the instability strip?  


W) Polaris  X) Mira A  Y) Delta Scuti  Z) Sirius B  


ANSWER: Z) SIRIUS B  


## BONUS  


10) Earth and Space – Short Answer Order the following three minerals from most to least stable against chemical weathering: 1) Halite; 2) Hematite; 3) Olivine.  


ANSWER: 2, 3, 1
## TOSS-UP  


11) Physics – Multiple Choice Which of the following effects explains why the energy level of an electron in a static magnetic field is split into non-degenerate energy states?  


W) Hall effect 
X) Stark effect 
Y) Zeeman effect 
Z) Casimir effect  


ANSWER: Y) ZEEMAN EFFECT  


## BONUS  


11) Physics – Short Answer A solid disk lying in the xy plane has a mass of 10 kilograms and a radius of 4 meters. What is the moment of inertia about an axis 2 meters from the center of the disk that is parallel to the z axis in kilograms times meters squared?  


ANSWER: 120  


## TOSS-UP  


12) Math – Multiple Choice What is the maximum number of points of intersection between 4 circles and 5 lines in a plane?  


W) 60 
X) 62 
Y) 64 
Z) 66  


ANSWER: X) 62  


## BONUS  


12) Math – Short Answer For two complementary angles \(\alpha\) and \(\beta\) , if \(\sin (\alpha) + \sin (\beta) = 1 / 3\) , what is \(\sin^3 (\alpha) + \sin^3 (\beta)\) ?  


ANSWER: 13/27
## TOSS-UP  


13) Biology – Short Answer What is the most common intercalating agent used to dye DNA embedded within agarose gel following RFLP?  


ANSWER: ETHIDIUM BROMIDE  


## BONUS  


13) Biology – Short Answer In order to stabilize the tetrahedral intermediate during nucleophilic acyl substitution of a water molecule in proteases, they often possess a ring of positively charged residues to stabilize the alkoxide group. What term is given to this pocket?  


ANSWER: OXYANION HOLE  


## TOSS-UP  


14) Chemistry – Multiple Choice Which of the following solvents would serve best for the reaction between tert-butyl chloride and potassium cyanide?  


W) Acetonitrile 
X) Water 
Y) Tetrahydrofuran 
Z) Dimethyl sulfoxide  


ANSWER: X) WATER  


## BONUS  


14) Chemistry – Short Answer Identify all of the following three nickel four coordinate complexes that are tetrahedral: 1) \(\mathrm{Ni(CN)_4^{2 - }}\) ; 2) \(\mathrm{Ni(CO)_4}\) ; 3) \(\mathrm{NiCl_4^{2 - }}\) .  


ANSWER: 2 AND 3
## TOSS-UP  


15) Earth and Space – Short Answer The D1 and D2 Fraunhofer lines found in the sun are usually caused by the absorption lines of what element?  


ANSWER: SODIUM  


## BONUS  


15) Earth and Space – Multiple Choice P wave speed is proportional to which of the following?  


W) rho  X) 1/rho  Y) sqrt(rho)  Z) 1/sqrt(rho)  


ANSWER: Z) 1/sqrt(rho)  


## TOSS-UP  


16) Physics – Short Answer What is the efficiency of a heat engine operating between a hot reservoir with four times the temperature of the cold reservoir?  


ANSWER: \(75\%\)  


## BONUS  


16) Physics – Short Answer A 10 kilogram block is sliding down a ramp inclined at a 30 degree angle to the horizontal with a constant acceleration of 3 meters per second squared. Given that g equals 10 meters per second squared, what is the coefficient of kinetic friction to the nearest tenth between the block and the ramp?  


ANSWER: 0.2
## TOSS-UP  


17) Math – Short Answer What is the shortest distance between the line \(y = x + 2\) and the point (2, 3)?  


ANSWER: sqrt(2) / 2  


## BONUS  


17) Math – Short Answer A two by five rectangle lies along the positive \(x\) and \(y\) axes. A billiard ball is fired from the origin and first collides with the sides of the rectangle at the point (2,2). It is subsequently deflected at 90 degrees every time it collides with the side of the rectangle. How many more times does the billiard ball collide with the walls of the rectangle before it is collected at a vertex of the rectangle?  


ANSWER: 5  


## TOSS-UP  


18) Biology – Short Answer 2,4-Dichlorophenoxyacetic acid is an herbicide that selectively destroys eudicots because it mimics what class of plant hormones, but cannot be broken down?  


ANSWER: AUXINS  


## BONUS  


18) Biology – Short Answer Identify all of the following three statements that are true regarding neutrophils: 1) They are considered lymphocytes; 2) They are usually responsible for antibody dependent cellular cytotoxicity; 3) They rarely perform diapedesis.  


ANSWER: NONE
## TOSS-UP  


19) Chemistry – Short Answer What is the formal charge on the nitrogen atom in the isocyanate anion NCO?  


ANSWER: - 1  


## BONUS  


19) Chemistry – Short Answer A monomer can react with itself to produce a target polymer via condensation polymerization in aqueous solution. Identify all of the following three changes to the reaction system that will favor formation of the polymer: 1) Adding more dilute water; 2) Decreasing temperature; 3) Removing polymer as it is formed.  


ANSWER: 3 ONLY  


## TOSS-UP  


20) Earth and Space – Short Answer What is the most common drainage pattern that manifests in regions containing homogenous material?  


ANSWER: DENDRITIC  


## BONUS  


20) Earth and Space – Short Answer Order the following three objects in increasing mass: 1) Veela pulsar; 2) Proxima centauri; 3) Sagittarius A\*.  


ANSWER: 2, 1, 3
## TOSS-UP  


21) Physics – Short Answer A step-down transformer has a primary coil with 900 turns and a secondary coil with 18 turns. When the primary coil is connected to a battery of 100 volts, how many volts pass through the secondary coil?  


ANSWER: 2  


## BONUS  


21) Physics – Short Answer A siren is emitted from a truck moving at 98 meters per second in the negative x direction, while an observer is moving at 49 meters per second in the positive x direction, such that they are moving away from each other. Given that the speed of sound is 343 meters per second, if the frequency of the siren is 150 hertz for the truck, what is the frequency of the siren as heard by the observer in hertz?  


ANSWER: 100  


## TOSS-UP  


22) Math – Short Answer A frog is initially at the origin. It then hops one unit in the positive x direction, then two units in the negative x direction, then three units in the positive x direction, and continues like this. What is the frog’s x coordinate after the 2021st hop?  


ANSWER: 1011  


## BONUS  


22) Math – Short Answer Evaluate the integral of x times e to the power of negative x between 0 and positive infinity.  


ANSWER: 1
## TOSS-UP  


23) Biology - Short Answer To what mammalian order do even toed ungulates belong?  


ANSWER: CERTARTOIDACYLTA (ACCEPT: ARTIODACTYLA)  


## BONUS  


23) Biology - Short Answer Identify all of the following three orders of insects that undergo complete metamorphosis: 1) Hemiptera; 2) Odonata; 3) Diptera.  


ANSWER: 3 ONLY  


## TOSS-UP  


24) Chemistry - Multiple Choice For two reactions A and B, reaction A has a greater activation energy than reaction B. Which of the following is true about the rate constant of reaction A with respect to that of reaction B at low and high temperatures, respectively?  


W) Lower at all temperatures X) Higher at all temperatures Y) Lower at low temperatures and higher at high temperatures Z) Higher at low temperatures and lower at high temperatures  


ANSWER: Y) LOWER AT LOW TEMPERATURES AND HIGHER AT HIGH TEMPERATURES  


## BONUS  


24) Chemistry - Short Answer What is the IUPAC name for the major organic product formed when ethanol chloride is treated with a solution of methanol?  


ANSWER: METHYL ACETATE  


## TOSS-UP  


25) Earth and Space - Short Answer What event occurred around 27,000 years ago as a result of the weakening of the Atlantic meridional overturning circulation, causing a reversal to glacial conditions?  


ANSWER: YOUNGER DRYAS  


## BONUS  


25) Earth and Space - Short Answer Identify all of the following objects that can be found in the Oort cloud: 1) Ceres; 2) Eris; 3) Short period comets.  


ANSWER: NONE  


Lexington HS (2020- 21)