
## TOSS-UP  


1) PHYSICS Short Answer Assuming that \(\mathrm{g} = 10 \mathrm{m / s} \wedge 2\) , what is the speed of a potted plant dropped from \(20 \mathrm{m}\) tall ledge just before it hits the ground?  


ANSWER: \(20 \mathrm{m / s}\)  


## BONUS  


1) PHYSICS Short Answer If the speed of sound in a certain medium is \(360 \mathrm{m / s}\) , what is the wavelength, in meters, of a sound wave that has a frequency of \(60 \mathrm{hertz}\) ?  


ANSWER: 6  


## TOSS-UP  


2) CHEMISTRY Multiple Choice Element X has the electron configuration [Kr] 5s<sup>1</sup>. Element Y has the electron configuration [Xe] 6s<sup>2</sup>4f<sup>14</sup>5d<sup>10</sup>6p<sup>4</sup>. What would be the theoretical chemical formula for the ionic compound comprised of X and Y atoms?  


W) XY  


X) X<sub>2</sub>Y  


Y) XY<sub>2</sub>  


Z) X<sub>2</sub>Y<sub>2</sub>  


ANSWER: X) X<sub>2</sub>Y  


## BONUS  


2) CHEMISTRY Short Answer By name or number, rank the following four molecules in order of increasing lattice energy: 1) CaCl<sub>2</sub> 2) CaF<sub>2</sub> 3) LiCl 4) LiF  


ANSWER: 3, 4, 1, 2  


## TOSS-UP  


3) EARTH AND SPACE Short Answer By name or number, order the following three cloud types from earliest to latest in cloud development:
I. Cumulonimbus
II. Cumulus Humilis
III. Cumulus Congestus  


ANSWER: II III I  


## BONUS  


3) EARTH AND SPACE Multiple Choice Which of the following combinations of wavelength, \(\lambda\) (lambda), and amplitude, \(A\) , of an ocean wave would cause the wave to break?  


W) \(\mathrm{A} = 1\mathrm{m}\) \(\lambda = 9\mathrm{m}\) X) \(\mathrm{A} = 1.5\mathrm{m}\) \(\lambda = 10\mathrm{m}\) Y) \(\mathrm{A} = 2\mathrm{m}\) \(\lambda = 20\mathrm{m}\) Z) \(\mathrm{A} = 3\mathrm{m}\) \(\lambda = 25\mathrm{m}\) ANSWER: X) \(\mathrm{A} = 1.5\mathrm{m}\) \(\lambda = 10\mathrm{m}\)  


## TOSS-UP  


4) MATH Short Answer Find the derivative of \(\sec (x)\tan (x)\)  


ANSWER: \(\sec^{3}(x) + \sec (x)\tan^{2}(x)\)  


## BONUS  


4) MATH Short Answer Find the derivative of \(\mathrm{x}^{2}\)  


ANSWER: \(\mathrm{x}^{2}(\ln (x) + 1)\) ACCEPT \(\mathrm{x}^{2}\ln (x) + \mathrm{x}^{2}\)  


## TOSS-UP  


5) BIOLOGY Short Answer Identify all of the following three that are direct functions of the thyroid gland?  


I) Stimulate metabolic processes
II) Induces contractions during labor  


III) Lowers blood calcium levels  


ANSWER: I and III  


## BONUS  


5) BIOLOGY Short Answer What hormone do the S cells of the duodenum secrete to eventually lead to the release of bicarbonate in the pancreas?  


ANSWER: Secretin  


## TOSS-UP  


6) PHYSICS Short Answer Earnest Rutherford used what type of particle to prove the existence of the nucleus in an atom?  


ANSWER: Alpha particle  


## BONUS  


6) PHYSICS Short Answer Jimothy spins a ball with mass 5kg attached to a 2m-long string in a horizontal circle. If the ball is going \(16\mathrm{m / s}\) , what is the tension on the string?  


ANSWER: 20 N  


## TOSS-UP  


7) CHEMISTRY Short Answer How many electrons with both a principal quantum number of 5 and an orbital quantum number of 3 are present within a ground state electron configuration atom of lead?  


ANSWER: 14  


## BONUS  


7) CHEMISTRY Short Answer Given that the molar mass of Argon gas is \(39.9\mathrm{g / mol}\) , what is the density of Argon gas at STP to at least two significant figures?
## TOSS-UP  


8) EARTH AND SPACE Multiple Choice Which of the following can be used to describe the temperature trend from the center of the Sun to the upper limit of the chromosphere?  


W) Increase, then decreaseX) Decrease, then increaseY) Increase, then decrease, then increaseZ) Decrease, then increase, then decreaseANSWER: X) Decrease, then increase  


## BONUS  


8) EARTH AND SPACE Short Answer By name or number, order the following three forms of plagioclase in order of increasing sodium content:  


I. LabradoriteII. BytowniteIII. Albite  


ANSWER: III I II  


## TOSS-UP  


9) MATH Short Answer What is \(\lim_{x \to 1} \frac{\ln x - 1}{\ln(x)}\) (read as the limit as x approaches one of the fraction with numerator x - 1 and denominator natural log of x)  


ANSWER: 1  


## BONUS  


9) MATH Multiple Choice Find minimum value of \(\mathrm{x}^{2} + 4\mathrm{y}^{2}\) given that \(\mathrm{x} + \mathrm{y} = 5\) ;  


W) 16X) 20Y) 25Z) 32
## TOSS-UP  


10) BIOLOGY Short Answer Identify all of the following three that are functions of the pons and medulla?  


I) Transfer sensory information between the peripheral nervous system and the forebrain  


II) Coordinate large scale body movements  


III) Monitors motor commands sent by the cerebrum  


ANSWER: I and II  


## BONUS  


10) BIOLOGY Short Answer What are the group of neurons in the hypothalamus that coordinate the circadian rhythm in mammals?  


ANSWER: Suprachiasmatic nucleus (ACCEPT: SCN)  


## TOSS-UP  


11) PHYSICS Multiple Choice In terms of F, by what factor does the electrical force between two charged particles q1 and q2 change if their distance is doubled, q1 is tripled, and q2 is halved?  


W) By a factor of \(\frac{1}{2}\mathrm{F}\)  


X) By a factor of \(\frac{3}{4}\mathrm{F}\)  


Y) By a factor of \(\frac{3}{8}\mathrm{F}\)  


Z) By a factor of \(\frac{1}{4}\mathrm{F}\)  


ANSWER: Y) By a factor of \(\frac{3}{8}\mathrm{F}\)  


## BONUS
11) PHYSICS Multiple Choice Jim and Tim work at the LHC and stumble upon a decay channel where two muons and two antimuons were produced. Which of the following particles could Jim and Tim have found the decay channel for?  


W) Higgs bosonX) W plus bosonY) W minus bosonZ) Z bosonANSWER: W) Higgs boson  


## TOSS-UP  


12) CHEMISTRY Short Answer Out of the 3 following molecules, rank them in order of increasing boiling point. 1) 1-propanol, 2) iso-butane 3) butane  


ANSWER: 2, 3, 1  


## BONUS  


12) CHEMISTRY Short Answer Rank the following substances in order of increasing deviation from ideal gas behavior. 1) \(\mathrm{N}_{2} 2) \mathrm{SO}_{2} 3) \mathrm{CO}_{2} 4) \mathrm{SF}_{6}\)  


ANSWER: 1, 3, 2, 4  


## TOSS-UP  


13) EARTH AND SPACE Short Answer The flat, sediment-laden beds of predominantly red clay that cover up the majority of the ocean floor are known as what?  


ANSWER: Abyssal plains  


## BONUS  


13) EARTH AND SPACE Multiple Choice What is the primary difference between mudstone and shale?  


W) Mudstone is a sedimentary rock, while shale is metamorphic
X) Mudstone breaks into blocks, while shale splits into flat, thin layers  


Y) Mudstone contains sand-sized particles, while shale contains clay-sized particles  


Z) Mudstone forms in larger quantities than shale  


ANSWER: X) Mudstone breaks into blocks, while shale splits into flat, thin layers  


## TOSS-UP  


14) MATH Multiple Choice The graph formed by the equation \(\mathrm{r} = 3\mathrm{cos}\) theta is best described as a:  


W) Ray  


X) Line  


Y) Circle  


Z) Hyperbola  


ANSWER: Y) circle  


## BONUS  


14) MATH Short Answer Tim is hurt standing on the corner of a 4 by 5 grid. In order to heal himself, he must touch a piece of specular hematite diagonal from him. If Tim can only walk on the lines of the grid, how many ways are there for him to get the magical healing powers of specular hematite?  


ANSWER: 126  


## TOSS-UP  


15) BIOLOGY Short Answer What is the structure in the forebrain that detects odors in the nasal cavity?  


ANSWER: Olfactory Bulbs  


## BONUS
15) BIOLOGY Short Answer Name all of the following parts of a child or adult brain that develop from the hindbrain in the embryo:  


I. Pons II. Cerebrum III. Cerebellum IV. Medulla Oblongata  


ANSWER: I, III, IV (PONS, CEREBELLUM, MEDULLA OBLONGATA)  


## TOSS-UP  


16) PHYSICS Short Answer At what fraction of the speed of light to the nearest hundredth does an object have to move to have a lorentz factor of 2?  


ANSWER: 87/100  


## BONUS  


16) PHYSICS Short Answer Which principle in General Relativity states that inertial forces and gravitational forces are indistinguishable?  


ANSWER: Equivalence Principle  


## TOSS-UP  


17) CHEMISTRY Multiple Choice At which of the following conditions do most gases behave like an ideal gas?  


W) Low pressure, Low Temperature  


X) High pressure, High Temperature  


Y) Low pressure, High Temperature  


Z) High pressure, Low Temperature  


ANSWER: Y) Low pressure, High Temperature  


## BONUS
17) CHEMISTRY Question Type Given that the heat of formation for one mole of \(\mathrm{NO}_2(\mathrm{g})\) is \(+33.9 \mathrm{kJ / mol}\) and that the heat of formation for one mole of \(\mathrm{NO}(\mathrm{g})\) is \(+90.4 \mathrm{kJ / mol}\) , what is \(\Delta \mathrm{H}\) of the synthesis reaction between NO and \(\mathrm{O}_2\) that produces 1 mole of \(\mathrm{NO}_2\) ?  


ANSWER: - 113 kJ/mol  


## TOSS-UP  


18) EARTH AND SPACE Short Answer The rock containing the fossil of Danny the dinosaur is millions of years old. Which of the following radioactive isotopes would NOT be used to date the rock?  


W) carbon-14  


X) Potassium-40  


Y) uranium-235  


Z) uranium-238  


ANSWER: W) carbon-14  


## BONUS  


18) EARTH AND SPACE Multiple Choice It's Tim's week with the kids. To entertain them, he gives them a form of amphibole to play with. Which of the following forms of amphibole should Tim NOT give his kids to avoid giving them lung cancer with fibrous needles and losing custody?  


W) Actinolite  


X) Glaurophane  


Y) Anthophyllite  


Z) Hornblende  


ANSWER: W) Actinolite
19) MATH Short Answer What is the maximum number of points of intersection for two circles and one square?  


ANSWER: 10  


## BONUS  


19) MATH Short Answer What is the radius of the circle formed by the parametric equations \(x = 3 + 3 \cos t, y = 4 + 3 \sin t\) for \(0 < t < 2\pi\) (when \(t\) is of the range 0 to \(2 \mathrm{pi}\) )?  


ANSWER: 9  


## TOSS-UP  


20) BIOLOGY Multiple Choice During Meiosis, chiasmata form between chromosomes at sites of which process?  


W) Separation of Homologs  


X) Crossing Over  


Y) Independent Assortment  


Z) Sister Chromatid Cohesion  


ANSWER: X) CROSSING OVER  


## BONUS  


20) BIOLOGY Short Answer Identify all of the following three statements that are typically true for prokaryotes: 1) Circular chromosomes; 2) Long telomeres and telomerase activity; 3) Multiple origins of replication.  


ANSWER: 1 ONLY  


## TOSS-UP  


21) PHYSICS Short Answer A 0.6 m guitar string has a fundamental frequency of 300 Hz. What is the speed of the standing wave formed by plucking the guitar string in m/s?  


ANSWER: 360 m/s
## BONUS  


21) PHYSICS Multiple Choice Tim is tired of writing the entire round for DOE and places himself in a human cannon facing the ocean. What is the maximum distance that he can launch himself away from land, assuming his launch speed is \(40 \mathrm{m / s}\) and that \(\mathrm{g} = 10 \mathrm{m / s}\) ?  


ANSWER: \(160 \mathrm{m}\) (depressing)  


## TOSS-UP  


22) CHEMISTRY Short Answer Give the flame color tests of the following three elements:  


I. Sulfur  
II. Potassium  
III. Sodium  


ANSWER: I Blue II Violet III Yellow  


## BONUS  


22) CHEMISTRY Multiple Choice What is the name of the region in a phase diagram for a mixture of components where the mixture exists as two or more phases?  


W) Miscibility gap  


X) Triple point  


Y) Azetrope  


Z) Alloy gap  


ANSWER: W) Miscibility gap  


## TOSS-UP  


23) EARTH AND SPACE Short Answer What are the long, low cliffs produced at vertical displacements along dip-slip faults called?  


ANSWER: fault scarps  


## BONUS
23) EARTH AND SPACE Multiple Choice A certain air mass is rising over the Appalachian mountains. Given an environmental lapse rate of 6 C/1000ft and a wet adiabatic lapse rate of 7 C/1000 ft, what type of cloud would be formed by the air mass?  


W) Cumulonimbus 
X) Cumulus 
Y) Stratus 
Z) Altocumulus  


## TOSS-UP  


24) MATH Multiple Choice A frog swims 8 miles downstream in 2 hours. She returns upstream in 4 hours. How fast does the frog swim in still water in miles per hour?  


W) 2 
X) 3 
Y) 4 
Z) 6  


ANSWER: X) 3  


## BONUS  


24) MATH Short Answer What is the distance between (2, 7) and the graph of -3y+x=1 in simplest radical form?  


ANSWER: \(2\sqrt{10}\)  


## TOSS-UP  


25) BIOLOGY Short Answer What type of cellular junction would provide strong connections between cells and cytoskeleton?
ANSWER: Adherens Junction  


## BONUS  


25) BIOLOGY Short Answer What epidermal cells attach to sensory neurons and function in sensing touch  


ANSWER: Merkel Cells (Accept Merkel Ranvier Cells and Tactile Epithelial Cells)