sub_title[[455, 125, 541, 142]]
## TOSS-UP  

text[[57, 160, 534, 179]]
1) Math – Multiple Choice What is the derangement of 6?  

text[[56, 196, 118, 268]]
W) 513 
X) 247 
Y) 244 
Z) 265  

text[[57, 285, 205, 303]]
ANSWER: Z) 265  

sub_title[[462, 320, 535, 337]]
## BONUS  

text[[56, 354, 941, 408]]
1) Math – Multiple Choice Baranyai's Theorem states that the k vertices of the hypergraph may be partitioned into subsets of r vertices in (k-1) choose (r-1) ways. Thus, 13 vertices of a hypergraph can be partitioned into how many subsets of 5 vertices?  

text[[56, 424, 119, 496]]
W) 460 
X) 495 
Y) 515 
Z) 535  

text[[57, 513, 207, 531]]
ANSWER: X) 495  

sub_title[[456, 584, 540, 600]]
## TOSS-UP  

text[[56, 618, 644, 638]]
2) Chemistry – Short Answer Give the full electron configuration of Cu.  

text[[57, 654, 380, 672]]
ANSWER: 1s2 2s2 2p6 3s2 3p6 4s1 3d5  

sub_title[[462, 690, 535, 707]]
## BONUS  

text[[56, 724, 644, 744]]
2) Chemistry – Short Answer Give the full electron configuration of Ra.  

text[[57, 760, 717, 779]]
ANSWER: 1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 6s2 4f14 5d10 6p6 7s2sub_title[[455, 71, 540, 88]]
## TOSS-UP  

text[[56, 108, 655, 127]]
3) Biology – Short Answer What two monosaccharides make up sucrose?  

text[[56, 144, 394, 162]]
ANSWER: GLUCOSE AND FRUCTOSE  

sub_title[[462, 180, 533, 199]]
## BONUS  

text[[56, 215, 933, 251]]
3) Biology – Multiple Choice Which of the following is closest to the number of cellulose molecules that are in a microfibril?  

text[[56, 268, 112, 339]]
W) 10 
X) 35 
Y) 80 
Z) 125  

text[[56, 356, 197, 374]]
ANSWER: Y) 80  

sub_title[[455, 425, 540, 444]]
## TOSS-UP  

text[[55, 460, 936, 497]]
4) Earth and Space Science – Multiple Choice What is the term for a gently sloping layer of bedrock, usually coming off a mountain, that can form a bajada with the mountain’s eroded sediment?  

text[[56, 497, 163, 566]]
W) Pediment 
X) Mesa 
Y) Derecho 
Z) Wadi  

text[[56, 584, 280, 602]]
ANSWER: W) PEDIMENT  

sub_title[[462, 619, 533, 637]]
## BONUS  

text[[56, 654, 919, 691]]
4) Earth and Space Science – Short Answer Which of Kepler’s Laws describes a planet’s orbit as an ellipse with the sun at one focus?  

text[[56, 707, 350, 726]]
ANSWER: KEPLER’S FIRST LAWsub_title[[456, 71, 540, 89]]
## TOSS-UP  

text[[56, 108, 940, 145]]
5) Physics – Short Answer State all of the following 4 units that can be used to measure magnetic field strength: 1) Tesla 2) Gauss 3) Weber per square meter 4) Ampere-Volt  

text[[57, 161, 243, 180]]
ANSWER: 1, 2 AND 3  

sub_title[[463, 198, 533, 216]]
## BONUS  

text[[56, 233, 925, 270]]
5) Physics – Short Answer What is the net electric flux, to the nearest 100 kilovolt-meters, through a gaussian surface with a radius of 5 meters and an enclosed charge of 4.5 microcoulomb's?  

text[[57, 286, 182, 304]]
ANSWER: 500  

sub_title[[456, 356, 540, 374]]
## TOSS-UP  

text[[56, 391, 940, 428]]
6) Math – Multiple Choice 2021 independent fair coins are tossed by Ephram. What is the expected number of consecutive TT pairs?  

text[[56, 444, 121, 515]]
W) 101 X) 202 Y) 505 Z) 1010  

text[[57, 533, 206, 551]]
ANSWER: Y) 505  

sub_title[[463, 569, 533, 587]]
## BONUS  

text[[56, 604, 936, 745]]
6) Math – Multiple-Choice Three clever monkeys divide a pile of bananas. The first monkey takes some bananas from the pile, keeps three-fourths of them, and divides the rest equally between the other two. The second monkey takes some bananas from the pile, keeps one-fourth of them, and divides the rest equally between the other two. The third monkey takes the remaining bananas from the pile, keeps one-twelfth of them, and divides the rest equally between the other two. Given that the pile starts out with a positive number of bananas, each monkey receives a whole number of bananas whenever the bananas are divided, and the numbers of bananas the first, second, and third monkeys have at the end of the process are in the ratio 3:2:1, what is the least possible total for the number of bananas?  

text[[56, 761, 118, 833]]
W) 338 X) 372 Y) 408 Z) 422  

text[[57, 850, 206, 868]]
ANSWER: Y) 408sub_title[[456, 71, 541, 88]]
## TOSS-UP  

text[[55, 107, 916, 145]]
7) Chemistry – Short Answer What element in the group 1A on the periodic table has the highest ionization energy?.  

text[[57, 161, 262, 179]]
ANSWER: HYDROGEN  

sub_title[[462, 197, 533, 215]]
## BONUS  

text[[57, 232, 655, 251]]
7) Chemistry – Multiple Choice Which of the following is a colorless ion?  

text[[56, 268, 133, 338]]
W) Fe \(2+\) X) Fe \(3+\) Y) Pb \(3+\) Z) Zn \(2+\)  

text[[57, 355, 222, 373]]
ANSWER: Z) Zn \(2+\)  

sub_title[[456, 443, 541, 460]]
## TOSS-UP  

text[[55, 478, 891, 497]]
8) Biology – Multiple Choice Valine is substituted for what amino acid in the formation of a sickle-cell?  

text[[56, 514, 204, 585]]
W) Glutamic Acid X) Lysine Y) Glycine Z) Aspartic Acid  

text[[57, 602, 335, 620]]
ANSWER: W) GLUTAMIC ACID  

sub_title[[462, 620, 533, 637]]
## BONUS  

text[[56, 655, 700, 674]]
8) Biology – Multiple Choice Which of the following is an essential amino acid?  

text[[56, 691, 164, 760]]
W) Leucine X) Serine Y) Alanine Z) Glutamate  

text[[57, 778, 265, 796]]
ANSWER: W) LEUCINEsub_title[[456, 71, 540, 88]]
## TOSS-UP  

text[[55, 107, 844, 127]]
9) Earth and Space Science – Multiple Choice How many constellations are officially recognized?  

text[[56, 127, 110, 196]]
W) 77 
X) 88 
Y) 99 
Z) 101  

text[[56, 215, 198, 233]]
ANSWER: X) 88  

sub_title[[464, 251, 533, 269]]
## BONUS  

text[[55, 286, 884, 323]]
9) Earth and Space Science – Short Answer Name all of the following constellations through which the ecliptic does not pass:  

text[[85, 323, 190, 391]]
1) Draco 
2) Aquarius 
3) Leo 
4) Pisces  

text[[56, 409, 243, 427]]
ANSWER: 1) DRACO  

sub_title[[456, 480, 540, 497]]
## TOSS-UP  

text[[56, 514, 910, 551]]
10) Physics – Short Answer A ball is falling off a 150 meter high cliff at a terminal velocity of 8 meters per second. What is the net force on the ball, in newtons?  

text[[56, 568, 162, 586]]
ANSWER: 0  

sub_title[[464, 603, 533, 621]]
## BONUS  

text[[56, 638, 933, 710]]
10) Physics – Short Answer A block of mass 5 kilograms is initially sitting atop a frictionless ramp at a height of 3.2 meters. If the block slides down the ramp and, as it moves with a constant velocity after sliding down the ramp, collides into a spring with a spring constant 8 Newtons/meter, by how much is the spring compressed, in simplest radical form in meters?  

text[[56, 728, 198, 748]]
ANSWER: \(2\sqrt{10}\)sub_title[[455, 71, 540, 88]]
## TOSS-UP  

text[[55, 180, 920, 217]]
11) Math – Multiple Choice 10 friends are solving the following problem where each person will give an answer to this question and they are the only individuals answering this question.  

text[[55, 231, 914, 321]]
Your answer to this problem will be an integer 0 through 100. From all the individuals who submitted an answer to this problem, let the average answer be \(\gamma\) . Find the value of \(\left|\frac{13}{10}\gamma \right|\) If the correct answer is \(x\) and your submitted answer is \(y\) then your score will be \(|x - y|\) .  

text[[55, 336, 936, 393]]
If one of them accidentally wrote 50 then the number the remaining 9 people should each choose so that their score is minimized can be written as \(\frac{m}{n}\) . Find \(m + n\) .  

text[[55, 410, 109, 481]]
W) 25  
X) 26  
Y) 27  
Z) 28  

text[[56, 499, 197, 517]]
ANSWER: Y) 27  

sub_title[[462, 534, 534, 552]]
## BONUS  

text[[56, 569, 625, 598]]
11) Math – Short Answer Ephram has 6 Among Us Tasks to complete.  

text[[56, 598, 308, 696]]
Admin: Swipe Card  Electrical: Calibrate Distributor  Shields: Prime Shields  Weapons: Clear Asteroids  Medbay: Submit Scan  Navigation: Chart Course  

text[[56, 713, 417, 802]]
The distance from Navigation to Medbay is 1  The distance from Medbay to Weapons is 2  The distance from Weapons to Shields is 4  The distance from Shields to Electrical is 8  The distance from Electrical to Admin is 16  

text[[55, 819, 940, 855]]
His first task has to be Weapons and then he can choose to do whatever task he wants to do next then what is the maximum distance I travel to finish all my tasks exactly once?  

text[[57, 872, 173, 889]]
ANSWER: 86sub_title[[456, 71, 540, 88]]
## TOSS-UP  

sub_title[[456, 108, 540, 125]]
## TOSS-UP  

text[[56, 143, 940, 181]]
12) Chemistry – Short Answer The mole fraction of nitrogen in the air is 0.8899. Calculate the partial pressure of N2 in air when the atmospheric pressure is 760. (3 sig figs) torr?  

text[[57, 198, 217, 215]]
ANSWER: 676 torr.  

sub_title[[462, 233, 533, 251]]
## BONUS  

text[[57, 268, 907, 305]]
12) Chemistry – Short Answer A sample of gas at 15 degrees celsius and 1 atm has a volume of 3 L. What volume will this gas occupy at 45 degrees celsius and 1 atm.  

text[[57, 322, 203, 339]]
ANSWER: 3.31 Lsub_title[[456, 71, 540, 88]]
## TOSS-UP  

text[[56, 108, 912, 144]]
13) Biology – Short Answer Which organelle responsible for hydrolyzing macromolecules is not present in plant cells?  

text[[58, 161, 258, 179]]
ANSWER: LYSOSOME  

sub_title[[464, 198, 533, 216]]
## BONUS  

text[[58, 233, 677, 252]]
13) Biology – Short Answer What protein subunit makes up microfilaments?  

text[[58, 269, 212, 286]]
ANSWER: ACTIN  

sub_title[[456, 339, 540, 356]]
## TOSS-UP  

text[[56, 373, 903, 392]]
14) Earth and Space Science – Multiple Choice Arroyos are found in which one of the following biomes?  

text[[58, 393, 145, 460]]
W) Tundra X) Forest Y) Aquatic Z) Desert  

text[[58, 479, 249, 497]]
ANSWER: Z) DESERT  

sub_title[[464, 516, 534, 534]]
## BONUS  

text[[58, 551, 894, 588]]
14) Earth and Space Science – Short Answer Outwash plains form in front of melting glaciers, and carry sediment away from the glacier. What type of stream is usually predominant in outwash plains?  

text[[58, 604, 336, 621]]
ANSWER: BRAIDED STREAMSsub_title[[456, 71, 540, 88]]
## TOSS-UP  

text[[56, 108, 905, 145]]
15) Physics – Short Answer What quantity is represented by the area under the curve of a force vs position graph?  

text[[57, 161, 212, 179]]
ANSWER: WORK  

sub_title[[463, 198, 533, 216]]
## BONUS  

text[[57, 233, 936, 286]]
15) Physics – Short Answer A solid ball of mass 10 kilograms and radius 2 meters rolls without slipping down an incline of height 7 meters. What is the final linear velocity of the ball at the bottom of the ramp, in appropriate units?  

text[[57, 303, 380, 321]]
ANSWER: 10 METERS PER SECOND  

text[[57, 373, 892, 427]]
16) Energy – Short Answer Los Alamos National Lab is studying the increased predictability of complex physics of internal combustion engines and their function. Internal combustion engines, which rely on the principles of adiabatic processes, have an internal energy that is equal to the negative of what quantity?  

text[[57, 444, 211, 461]]
ANSWER: WORK  

sub_title[[463, 480, 533, 497]]
## BONUS  

text[[57, 515, 914, 550]]
16) Energy – Short Answer Calculate the COP of an ideal refrigerator that operates between temperatures of 180 and 330 Kelvin.  

text[[57, 567, 177, 585]]
ANSWER: 1.2  

sub_title[[456, 638, 540, 656]]
## TOSS-UP  

text[[56, 673, 919, 726]]
17) Energy – Multiple Choice Researchers at Jefferson National Lab have studied the lifetime of the neutral pion, which is shortened by the breaking of chiral symmetry predicted by quantum chromodynamics. What is the name for the breaking of chiral symmetry?  

text[[57, 727, 351, 812]]
W) Chiral Break 
X) Chiral Error 
Y) Chiral Anomaly 
Z) Chiral Disruption  

text[[57, 812, 350, 829]]
ANSWER: Y) CHIRAL ANOMALY  

sub_title[[463, 832, 533, 850]]
## BONUS  

text[[57, 867, 914, 937]]
17) Energy – Multiple Choice Scientists at Brookhaven National Lab, Fermi, Lawrence Berkeley National Lab, and others around the world are building new focusing and kicker magnets for the LHC, which increase the chance of potential collisions. Which of the following terms describes the rate at which the particles are made to collide?  

text[[64, 945, 210, 961]]
Lexington HS (20- 21)sub_title[[456, 72, 540, 88]]
## TOSS-UP  

text[[56, 110, 291, 181]]
W) Instantaneous Luminosity  X) Quantum Luminosity  Y) Collision Luminosity  Z) Hadron Luminosity  

text[[56, 216, 467, 233]]
ANSWER: W) INSTANTANEOUS LUMINOSITY  

sub_title[[456, 304, 540, 321]]
## TOSS-UP  

text[[56, 339, 936, 409]]
18) Energy – Multiple Choice Researchers at Los Alamos National Lab drive cars, which use heat engines to operate. When heat engines are used to produce energy through fossil fuels, the excess heat released as the output of the heat engine needs to be absorbed by the surrounding environment, raising its temperature. What is the name given to the resulting pollution type?  

text[[56, 427, 289, 497]]
W) Thermal Pollution  X) Heat Death Pollution  Y) Carbon-Capture Pollution  Z) Entropic Pollution  

text[[57, 515, 360, 532]]
ANSWER: THERMAL POLLUTION  

sub_title[[463, 532, 533, 550]]
## BONUS  

text[[57, 567, 919, 620]]
18) Energy – Short Answer Researchers at SLAC use the Fermi Gamma Ray Telescope, which orbits at 350 miles above the Earth, to search for signs of what elusive particles that allow galaxies to spin at their current velocities without falling apart?  

text[[57, 638, 290, 655]]
ANSWER: DARK MATTER