sub_title[[461, 116, 541, 133]]
## TOSS-UP  

text[[55, 148, 925, 181]]
1) Physics - Short Answer If the range of a projectile fired at a 30 degree angle to the horizontal is 15 meters, what is the maximum possible range of a projectile fired with the same initial velocity in meters?  

text[[56, 193, 186, 210]]
ANSWER: \(10\sqrt{3}\)  

sub_title[[468, 227, 534, 244]]
## BONUS  

text[[56, 259, 925, 292]]
1) Physics - Short Answer A wire with a radius of \(6\mathrm{mm}\) is carrying a current with a uniform current density. What is the ratio of the magnetic field strength at a distance of \(9\mathrm{mm}\) from the axis to that at a distance of \(2\mathrm{mm}\) from the axis?  

text[[56, 302, 154, 318]]
ANSWER: 2  

sub_title[[461, 366, 540, 382]]
## TOSS-UP  

text[[56, 397, 925, 462]]
2) Energy - Multiple Choice DOF Researchers at SI.AC National Accelerator I. ab combined cryogenic electron tomography and fluorescence imaging to produce a new convolutional technique to detect the cellular localization of proteins. They performed this method on a group of cells in metaphase for the localization of kinetochores. In which of the following locations would they find the largest amount of fluorescence?  

text[[56, 479, 430, 548]]
W) Centromeres of chromosomes  X) Minus end of the spindle  Y) Plasma membrane near connexins  Z) Ribosomes bound to signal recognition particles  

text[[56, 565, 477, 582]]
ANSWER: W) CENTROMERES OF CHROMOSOMES  

sub_title[[468, 599, 534, 615]]
## BONUS  

text[[56, 629, 946, 694]]
2) Energy - Short Answer Scientists at Lawrence Berkeley National I. ab imaged the ORF8 protein, a component of many coronaviruses that is known to be involved in disease severity and immune evasion. Identify all of the following three statements concerning coronaviruses that are true: 1) They utilize reverse transcriptase in their active replicative cycle; 2) They utilize single stranded RNA as their genome; 3) They are responsible for causing SARS.  

text[[56, 708, 210, 724]]
ANSWER: 2 AND 3sub_title[[457, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 940, 135]]
3) Chemistry - Short Answer Order the following three hydrogen emission series in increasing frequency of their alpha lines: 1) Paschen; 2) Lyman; 3) Balmer.  

text[[56, 148, 191, 164]]
ANSWER:1,3,2  

sub_title[[468, 180, 535, 196]]
## BONUS  

text[[56, 211, 940, 260]]
3) Chemistry - Short Answer Identify all of the following three organic molecules that are chiral: 1) 3-methyl 1-hexene [three methyl one hex eye-n]; 2) 1,2-dimethyl allene [All-ee-n]; 3) 2-methyl pentane [two methyl pent-ay-n] [read all names slowly].  

text[[56, 274, 210, 290]]
ANSWER:1AND2  

sub_title[[461, 337, 540, 352]]
## TOSS-UP  

text[[55, 368, 936, 401]]
4) Biology - Multiple Choice Which of the following terms best characterizes a plant species where the female and male organs are located on distinct flowers?  

text[[56, 413, 295, 476]]
W) Dioecious [dahy-ee-schuhs] X) Homosporous Y) Moncious [mon-ee-schuhs] Z) Heterosporous  

text[[56, 490, 270, 505]]
ANSWER:W)DIOFCIOUS  

sub_title[[468, 522, 535, 538]]
## BONUS  

text[[56, 553, 940, 586]]
4) Biology - Short Answer Which of the following 3 plant hormones is incorrectly matched with their function: 1) Gibberellins - increases stem elongation; 2) Auxins - participates in thigmotropism 3) Cytokinins - decreases cell division  

text[[56, 600, 206, 615]]
ANSWER:3ONLYsub_title[[458, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 916, 134]]
5) Math - Short Answer How many ways are there to paint the faces of a cube either red or green if rotations of one coloring are not considered distinct?  

text[[56, 149, 163, 164]]
ANSWER:10  

sub_title[[468, 180, 534, 196]]
## BONUS  

text[[56, 212, 944, 260]]
5) Math - Short Answer Two trains are travelling towards each other on straight, parallel tracks. One train travels at a constant speed of 10 miles per hour. The other train's speed at time \(t\) is \(10t\) miles per hour. If they are 120 miles apart from each other at time \(t = 0\) , at what time \(t\) will they meet?  

text[[56, 275, 154, 290]]
ANSWER:4  

sub_title[[461, 337, 540, 353]]
## TOSS-UP  

text[[56, 368, 741, 386]]
6) Earth and Space - Short Answer Balmer lines are strongest in which spectral class of star?  

text[[56, 400, 156, 415]]
ANSWER:A  

sub_title[[468, 431, 534, 447]]
## BONUS  

text[[56, 462, 904, 495]]
6) Earth and Space - Multiple Choice Yardangs can be observed on Mars. Which of the following best describes a yardang?  

text[[56, 505, 518, 574]]
W) An isolated patch of land surrounded by a pool of lava  X) More mechanically resistant rock protruding out of the sand  Y) An old volcanic neck with eroded surrounding rocks  Z) Fossilized coral reef  

text[[56, 592, 808, 609]]
ANSWER: X) MORE MECHANICALLY RESISTANT ROCK PROTRUDING OUT OF THE SANDsub_title[[457, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 924, 134]]
7) Physics - Short Answer Identify all of the following three objects with uniform density that have an isotropic drag coefficient: 1) Cube; 2) Sphere; 3) Cone.  

text[[56, 144, 206, 160]]
ANSWER:2 ONLY  

sub_title[[468, 177, 534, 193]]
## BONUS  

text[[55, 209, 910, 241]]
7) Physics - Short Answer What quantity is the canonically conjugate operator for the energy of a state in quantum mechanics?  

text[[56, 256, 188, 272]]
ANSWER: TIME  

sub_title[[462, 319, 541, 335]]
## TOSS-UP  

text[[56, 350, 920, 399]]
8) Energy - Multiple Choice Scientists at Brookhaven's Center for Functional Nanomaterials used spectroscopic methods to study a platinum and cerium oxide catalyst used in the water-gas shift reaction. Which of the following is a unique challenge in designing catalysts for the water-gas shift reaction?  

text[[56, 409, 325, 476]]
W)Oxygen vacancies in the catalyst X) Poisoning of the catalyst Y) Reduction of the catalyst Z) I.arge surface area of the catalyst  

text[[56, 490, 427, 506]]
ANSWER:X)POISONING OF THE CATALYST  

sub_title[[468, 525, 534, 540]]
## BONUS  

text[[56, 555, 945, 603]]
8) Energy - Multiple Choice Chemists at Pacific Northwest National Lab designed a battery with an aqueous electrolyte as well as zinc and graphite electrodes that has an operating potential between 2.3 and 2.5 volts. Which of the following explains why the aqueous electrolyte has an extremely high concentration of salt ions?  

text[[56, 614, 487, 682]]
W) To prevent the aqueous electrolyte from being oxidized X) To prevent the aqueous electrolyte from being reduced Y) To prevent the intercalation of the graphite electrode Z) To prevent the corrosion of the zinc electrode  

text[[56, 700, 750, 717]]
ANSWER:W)TO PREVENT THE AQUEOUS ELECTROLYTE FROM BEING OXIDIZEDsub_title[[459, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 936, 134]]
9) Chemistry - Multiple Choice When oxygen-17 undergoes alpha decay followed by single neutron capture, which of the following isotopes is formed?  

text[[55, 144, 171, 213]]
W) Carbon-12  X) Carbon-14  Y) Nitrogen-12  Z) Nitrogen-14  

text[[57, 230, 268, 246]]
ANSWER: X) CARBON-14  

sub_title[[469, 261, 534, 277]]
## BONUS  

text[[55, 293, 947, 356]]
9) Chemistry - Short Answer Identify all of the following three statements that are true about surface catalysis for the addition of gaseous hydrogen to an alkene to produce an alkane: 1) Cleavage of the hydrogen hydrogen bond occurs in the unbounded gas phase; 2) The rate determining step is desorption; 3) Increasing the surface area of the catalyst would increase the rate of the reaction.  

text[[57, 367, 206, 382]]
ANSWER: 3 ONIY  

sub_title[[462, 432, 540, 448]]
## TOSS-UP  

text[[55, 464, 870, 496]]
10) Biology - Short Answer When analyzing the amniotic egg of a new bird species, you would find the largest concentration of uric acid in which extraembryonic membrane?  

text[[57, 508, 250, 524]]
ANSWER: ALLANTOIS  

sub_title[[469, 558, 534, 573]]
## BONUS  

text[[55, 589, 941, 621]]
10) Biology - Short Answer Identify all of the following three groups of animals that possess amniotic eggs: 1) Frogs; 2) Salamanders; 3) Apes.  

text[[57, 633, 210, 649]]
ANSWER: 3 ONLYsub_title[[459, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 920, 134]]
11) Math - Short Answer A rhombus with side length 1 has an inscribed circle with radius \(\frac{1}{2}\) . What is the area of the rhombus?  

text[[56, 148, 167, 164]]
ANSWER:2/3  

sub_title[[468, 180, 534, 196]]
## BONUS  

text[[55, 212, 928, 245]]
11) Math - Short Answer The side lengths of a triangle are 13, 14, and 15. What is the sine of the largest angle in this triangle?  

text[[56, 260, 186, 275]]
ANSWER:12/13  

sub_title[[462, 322, 540, 338]]
## TOSS-UP  

text[[56, 353, 936, 387]]
12) Earth and Space - Short Answer Order the following 3 headland features in order from MOST to LEAST eroded: 1) Sea arch; 2) Sea stack; 3) Sea stump.  

text[[56, 402, 180, 417]]
ANSWER:321  

sub_title[[468, 435, 534, 451]]
## BONUS  

text[[56, 466, 930, 515]]
12) Earth and Space - Short Answer Give, by name or number, all of the following 3 statement concerning beaches which are true: 1) A baymouth bar connects an island to the mainland; 2) The water inside an atoll is called a lagoon; 3) Spits are a result of longshore transport  

text[[56, 530, 210, 546]]
ANSWER:2AND3sub_title[[458, 65, 545, 82]]
## TOSS-UP  

text[[55, 101, 896, 135]]
13) Physics - Multiple Choice Water is flowing through a pipe with constant velocity and pressure. Which of the following statements must be true about the pipe?  

text[[55, 144, 296, 213]]
W) The pipe is sloped upward  X) The pipe is sloped downward  Y) The pipe is horizontal  Z) The pipe is vertical  

text[[57, 230, 384, 247]]
ANSWER:Y) THE PIPE IS HORIZONTAL  

sub_title[[468, 261, 535, 277]]
## BONUS  

text[[55, 292, 947, 362]]
13) Physics - Short Answer An electron moves at 4 meters per second in a 2 tesla magnetic field. If the mass and charge of an electron are \(9 \cdot 10^{-31}\) kilograms /nine times ten to the negative thirty one/ and \(1.6 \cdot 10^{-19}\) coulombs /one times ten to the negative nineteen/ respectively, what is the radius of the electron's circular orbit in picometers and to two significant figures?  

text[[57, 371, 161, 387]]
ANSWER:11  

sub_title[[462, 435, 540, 451]]
## TOSS-UP  

text[[55, 466, 916, 500]]
14) Energy - Multiple Choice Scientists at Argonne National Lab have been studying the anti-inflammatory effects of inosine when injected into monocytes. In which of the following molecules is inosine most likely to be found?  

text[[55, 510, 140, 578]]
W) ssRNA  X) tRNA  Y) miRNA  Z) cDNA  

text[[57, 592, 211, 607]]
ANSWER: X) tRNA  

sub_title[[468, 625, 535, 641]]
## BONUS  

text[[57, 656, 933, 705]]
14) Energy - Short Answer Scientists at Lawrence Berkeley National Lab have been using helioseismology models of the sun to determine it's differential rotation. Earlier models failed to take into account the twisting and tangling of magnetic fields in the sun. What model describes these interactions of the solar magnetic fields?  

text[[57, 720, 300, 735]]
ANSWER:BABCOCK MODELsub_title[[458, 65, 544, 81]]
## TOSS-UP  

text[[56, 101, 777, 119]]
15) Chemistry - Multiple Choice Which of the following molecules has the greatest bond angle?  

text[[56, 129, 118, 200]]
W) \(\mathrm{NH}_3\) X) \(\mathrm{NF}_3\) Y) \(\mathrm{H}_2\mathrm{O}\) Z) \(\mathrm{H}_2\mathrm{S}\)  

text[[56, 215, 203, 231]]
ANSWER: W) \(\mathrm{NH}_3\)  

sub_title[[468, 246, 533, 262]]
## BONUS  

text[[56, 277, 940, 341]]
15) Chemistry - Short Answer Metals A and B form slightly soluble chlorides ACI and BCI with solubility products of 4 times \(10^{-5}\) and 6 times \(10^{-5}\) , respectively. One gram of each chloride's powder is simultaneously added to the same solution to create a saturated solution. To the nearest hundredth, what is the molarity of chloride ions in the solution at equilibrium?  

text[[56, 355, 175, 371]]
ANSWER: 0.01  

sub_title[[462, 417, 540, 433]]
## TOSS-UP  

text[[56, 448, 911, 481]]
16) Biology - Short Answer IPSPs may be triggered by the binding of GABA because GABA receptors increase the permeability of the membrane for what ion?  

text[[56, 494, 423, 510]]
ANSWER: CI (DO NOT ACCEPT: CHLORINE)  

sub_title[[468, 526, 533, 543]]
## BONUS  

text[[56, 558, 933, 606]]
16) Biology - Short Answer Identify all of the following three statements that are true of the lac operon in prokaryotes when both glucose and lactose are abundant: 1) CAP is activated; 2) RNA Polymerase is more likely to bind to the operator than without glucose; 3) The lac repressor is bound to the operator.  

text[[56, 620, 195, 636]]
ANSWER: NONEsub_title[[458, 65, 544, 81]]
## TOSS-UP  

text[[55, 102, 910, 140]]
17) Math - Short Answer A curve is defined parametrically by the equation \(x = 6t^2 - 1\) and \(y = 3t\) . What is the slope of the line tangent to the curve at the point (23, 6)?  

text[[55, 153, 168, 169]]
ANSWER: 1/8  

sub_title[[461, 185, 528, 201]]
## BONUS  

text[[55, 216, 916, 249]]
17) Math - Short Answer An infinite geometric series has second term \(\frac{1}{2}\) and fourth term \(\frac{1}{4}\) . What is the sum of this series?  

text[[55, 264, 203, 284]]
ANSWER: \(1 + \sqrt{2}\)  

sub_title[[455, 329, 534, 345]]
## TOSS-UP  

text[[55, 360, 931, 394]]
18) Earth and Space - Multiple Choice Hawaiian volcanoes are formed from a hotspot and erupt constantly. Which of the following types of lava do you expect to find in hawaii?  

text[[55, 409, 157, 477]]
W) Rhyolitic X) Andesitic Y) Basaltic Z) Komatiitic  

text[[56, 496, 254, 513]]
ANSWER: Y) BASAITIC  

sub_title[[461, 530, 528, 546]]
## BONUS  

text[[55, 561, 888, 594]]
18) Earth and Space - Short Answer What hawaiian name is given to the jet black crystallized lava drops which crystallize while in the air?  

text[[56, 610, 265, 626]]
ANSWER: PELE'S TEARSsub_title[[459, 65, 544, 81]]
## TOSS-UP  

text[[57, 101, 936, 134]]
19) Physics - Multiple Choice An electron is moving north at constant velocity when it enters a magnetic field pointing straight up. In what direction is the electron immediately accelerated?  

text[[55, 145, 125, 213]]
W) West  X) East  Y) Up  Z) Down  

text[[57, 226, 220, 242]]
ANSWER:W)WEST  

sub_title[[469, 260, 534, 276]]
## BONUS  

text[[57, 291, 940, 339]]
19) Physics - Short Answer Alex is launching an amateur rocket from his backyard with a mass of \(200\mathrm{kg}\) . The rocket consumes fuel at \(0.5\mathrm{kg / s}\) and has an exhaust gas with relative speed of \(1500\mathrm{m / s}\) . What is the initial upward acceleration of the toy rocket from Alex's backyard?  

text[[57, 354, 154, 368]]
ANSWER:0  

sub_title[[462, 416, 540, 432]]
## TOSS-UP  

text[[55, 448, 940, 496]]
20) Energy - Short Answer Rescarchers at Georgia State University used a supercomputer at Oak Ridge National Lab to develop an integrated model of the transcription preinitiation complex. What is the most common eukaryotic DNA promoter element over which the preinitiation complex forms?  

text[[57, 510, 229, 526]]
ANSWER:TATA BOX  

sub_title[[469, 543, 534, 558]]
## BONUS  

text[[57, 574, 923, 621]]
20) Energy - Short Answer Scientists at FermiLab discovered a new type of particle in the nucleus called a hyperon, which is made up of two strange quarks and one down quark. Identify all of the following three statements that are true about the hyperon: 1) It is a baryon; 2) It is positively charged; 3) It has a shorter lifetime than a free neutron.  

text[[57, 632, 210, 647]]
ANSWER:1 AND3sub_title[[457, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 896, 134]]
21) Chemistry - Short Answer When a 1 molar aqueous solution of hydrofluoric acid is electrolyzed, what gas is produced at the anode?  

text[[56, 148, 346, 165]]
ANSWER: OXYGEN (ACCEPT: \(\mathrm{O_2}\)  

sub_title[[468, 180, 534, 196]]
## BONUS  

text[[56, 211, 911, 244]]
21) Chemistry - Short Answer Order the following three aqueous solutions in increasing boiling point: 1) 0.1 molal hydrochloric acid; 2) Pure water; 3) 0.1 molal ethanol.  

text[[56, 259, 189, 275]]
ANSWER: 3, 2, 1  

sub_title[[462, 322, 540, 337]]
## TOSS-UP  

text[[56, 352, 908, 385]]
22) Biology - Short Answer During the signaling pathway for apoptosis, what iron based protein released from the mitochondria activates the caspase Ccd-9?  

text[[56, 400, 293, 415]]
ANSWER: CYTOCHROME C  

sub_title[[468, 431, 534, 447]]
## BONUS  

text[[56, 462, 943, 511]]
22) Biology - Short Answer Nitrogcnase is an cnzyme requiring high inputs of cnergy to fix nitrogen. Identify all of the following three statements are likely true about nitrogenase: 1) It requires metal cofactors to function; 2) It is found in rhizobia; 3) It is found in cyanobacteria.  

text[[56, 526, 178, 542]]
ANSWER: ALLsub_title[[457, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 724, 119]]
23) Math - Multiple Choice Which of the following functions contains no critical points?  

text[[55, 135, 201, 210]]
W) \(f(x) = x^{3} + x\) X) \(f(x) = ln(x^{2})\) Y) \(f(x) = |x|\) Z) \(f(x) = \sqrt[3]{x}\)  

text[[55, 226, 288, 245]]
ANSWER: W) \(f(x) = x^{3} + x\)  

sub_title[[468, 260, 534, 276]]
## BONUS  

text[[55, 291, 931, 323]]
23) Math - Short Answer A, B, and C are three points located on the perimeter of a circle. If major arc ABC measures \(144^{\circ}\) and major arc BCA measures \(256^{\circ}\) , what is the degree measure of major arc CAB?  

text[[55, 339, 178, 354]]
ANSWER: \(320^{\circ}\)  

sub_title[[462, 400, 541, 416]]
## TOSS-UP  

text[[55, 432, 931, 465]]
24) Earth and Space - Multiple Choice In what quadrant of the Hertzsprung russell diagram would one expect to find a white dwarf?  

text[[55, 482, 175, 550]]
W) Top left X) Top right Y) Bottom left Z) Bottom right  

text[[55, 568, 292, 585]]
ANSWER: Y) BOTTOM LEFT  

sub_title[[468, 602, 534, 618]]
## BONUS  

text[[55, 633, 880, 666]]
24) Earth and Space - Short Answer Order the following three layers of the sun from innermost to outermost: 1) Radiative Zone; 2) Photosphere; 3) Convective Zone  

text[[55, 682, 191, 698]]
ANSWER: 1, 3, 2sub_title[[459, 65, 544, 81]]
## TOSS-UP  

text[[55, 116, 820, 135]]
25) Physics - Multiple Choice What is the coefficient of restitution of a completely inelastic collision?  

text[[55, 149, 105, 212]]
W)-1 X)0 Y)0.5 Z)1  

text[[55, 227, 179, 243]]
ANSWER:X)0  

sub_title[[469, 259, 535, 275]]
## BONUS  

text[[55, 290, 936, 323]]
25) Physics - Short Answer Identify all of the following three wavelengths in meters that are resonant frequencies for a pipe open on one end and closed on the other with a length of 6 meters: 1) 4; 2) 8; 3) 16.  

text[[55, 337, 206, 353]]
ANSWER:2ONLYtext[[0, 0, 997, 997]]
# 1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1