sub_title[[462, 116, 540, 133]]
## TOSS-UP  

text[[55, 148, 900, 180]]
1) Biology - Short Answer When follicle stimulating hormone binds to Sertoli cells, they release which peptide that inhibits FSH release?  

text[[56, 195, 214, 210]]
ANSWER:INHIBIN  

sub_title[[468, 226, 534, 243]]
## BONUS  

text[[56, 258, 936, 322]]
1) Biology - Short Answer Identify all of the following three statements that are true of angiosperms: 1) The four megaspores produced from the megasporangium result in the formation of four different surviving female gametophytes; 2) The micropyle is the hole where the integuments do not protect the megasporangium; 3) Fertilization and pollination may occur months apart.  

text[[56, 336, 205, 352]]
ANSWER:2 ONLY  

sub_title[[462, 399, 540, 415]]
## TOSS-UP  

text[[56, 431, 919, 480]]
2) Earth and Space - Short Answer The lunar highlands are relatively light colored. Identify all of the following three statments which are true concerning the lunar highlands: 1) They are primarily made of basalt; 2) They are less dense than lunar maria; 3) Highlands are younger than maria.  

text[[56, 495, 205, 511]]
ANSWER:2 ONLY  

sub_title[[468, 529, 534, 545]]
## BONUS  

text[[56, 560, 884, 592]]
2) Earth and Space - Multiple Choice Wrinkle ridges are sinuous ridges found in the lunar maria with analogous formation to lobate scarps of Mercury. Which of the following best explains the formation of wrinkle ridges?  

text[[56, 610, 536, 679]]
W) The moon contracted when cooling, forming these ridges  X) The basalt contracted when cooling, forming these ridges  Y) Tidal forces from the Earth caused stress, forming these ridges  Z) Tidal forces from the Sun caused stress, forming these ridges  

text[[56, 696, 771, 713]]
ANSWER: X) THE BASALT CONTRACTED WHEN COOLING, FORMING THESE RIDGESsub_title[[459, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 944, 166]]
3) Energy - Short Answer Scientists at Argonne National Lab have been studying the ancient ceramic chips that are often found studded in carbonaceous chondrite meteorites, which are hypothesized to form in the early universe. The isotopic signature of the ceramics indicate that they were formed in the heat of flaring young stars with a nebulous cocoon around it. What general type of young protostellar object has variable brightness due to it being hidden in a stellar cocoon?  

text[[57, 175, 273, 191]]
ANSWER: T-TAURI STARS  

sub_title[[468, 209, 534, 225]]
## BONUS  

text[[57, 240, 920, 288]]
3) Energy - Short Answer Scientists at FermiLab built the Holometer to measure small fluctuations of position on the Planck scale. The Holometer uses laser interferometry to detect what hypothetical bosons by measuring twists in space and time on the Planck scale?  

text[[57, 303, 247, 319]]
ANSWER: GRAVITONS  

sub_title[[462, 366, 540, 381]]
## TOSS-UP  

text[[55, 396, 911, 430]]
4) Chemistry - Short Answer Identify all of the following three molecules that can undergo hydrogen bonding with hydrogen fluoride: 1) Methyl fluoride; 2) Water; 3) Fluorine.  

text[[57, 444, 210, 459]]
ANSWER: 1 AND 2  

sub_title[[468, 477, 534, 493]]
## BONUS  

text[[55, 508, 926, 540]]
4) Chemistry - Short Answer Order the following three functional groups in increasing electrophilicity: 1) Ketone; 2) Carboxylic acid; 3) Ester.  

text[[57, 555, 189, 570]]
ANSWER: 2, 3, 1sub_title[[459, 65, 544, 81]]
## TOSS-UP  

text[[57, 101, 890, 120]]
5) Math - Short Answer A fully connected planar graph has 45 edges. How many vertices does this graph have?  

text[[56, 133, 163, 149]]
ANSWER: 10  

sub_title[[468, 164, 534, 180]]
## BONUS  

text[[56, 195, 940, 229]]
5) Math - Short Answer A triangular piece of paper has side lengths 5, 6, and 7. Lines are drawn between the midpoints of the sides, and the triangle and cut along these lines. What is the sum of the perimeters of the four resulting triangles?  

text[[56, 243, 163, 258]]
ANSWER: 27  

sub_title[[462, 306, 541, 322]]
## TOSS-UP  

text[[56, 337, 928, 386]]
6) Physics - Multiple Choice Anka is located at one end within a cylinder that is rotating counterclockwise around its long axis, at the other end is a spherical hole. She throws a ball straight at the hoop but it misses. In an inertial reference frame the ball would've been a direct hit. Which of the following best describes what happens to the ball?  

text[[56, 396, 310, 464]]
W) It misses the hole to the left  X) It misses the hole to the right  Y) It misses the hole to the bottom  Z) It misses the hole to the top  

text[[56, 477, 472, 494]]
ANSWER: X) IT MISSES THE HOLE TO THE RIGHT  

sub_title[[468, 510, 534, 526]]
## BONUS  

text[[56, 542, 916, 575]]
6) Physics - Short Answer The Barkhausen effect is a series of minute fluctuations within what property, believed to be caused by fields of electron spins interacting in magnetic domains in combination with exchange coupling?  

text[[56, 589, 313, 605]]
ANSWER: FERROMAGNETISMsub_title[[459, 65, 544, 81]]
## TOSS-UP  

text[[57, 101, 944, 134]]
7) Biology - Short Answer When a ligand binds to a protein, it induces a conformational change in the binding site of the protein to make it more complementary to the ligand. What is this conformational change called?  

text[[57, 148, 257, 164]]
ANSWER: INDUCED FIT  

sub_title[[469, 180, 534, 196]]
## BONUS  

text[[57, 212, 946, 275]]
7) Biology - Short Answer By name or number, identify all the following three statements that the landmark study conducted by Knut Schmidt-Nielsen revealed about locomotion: 1) Flying costs more energy per meter travelled compared to running in similarly sized animals; 2) Animals with smaller body mass typically expend more energy moving compared to larger animals; 3) Flying animals tended to be the lightest compared to animals than ran or swam  

text[[57, 288, 178, 303]]
ANSWER: ALL  

sub_title[[463, 350, 540, 366]]
## TOSS-UP  

text[[57, 381, 940, 414]]
8) Earth and Space - Short Answer Tropical rainforests contain utilisols and oxisols, which contribute their metals to the formation of what clay rich soil rich in iron oxides?  

text[[57, 430, 229, 446]]
ANSWER: LATERITE  

sub_title[[469, 463, 534, 479]]
## BONUS  

text[[57, 495, 930, 528]]
8) Earth and Space - Short Answer Identify all of the following three that, when increased, increases permeability: 1) Angularity; 2) Packing; 3) Particle size  

text[[57, 544, 205, 559]]
ANSWER: 3 ONLYsub_title[[457, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 916, 150]]
9) Energy - Multiple Choice Scientists at Brookhaven national lab have been probing the vibrational structures of hydrogen and atomic helium using photoelectron spectroscopy. Which of the following wavelengths of light in meters would the scientists most likely use in their studies?  

text[[55, 160, 120, 230]]
W) \(10^{-15}\) X) \(10^{-12}\) Y) \(10^{-9}\) Z) \(10^{-6}\)  

text[[56, 246, 196, 262]]
ANSWER: Y) \(10^{-9}\)  

sub_title[[468, 277, 534, 293]]
## BONUS  

text[[55, 308, 947, 389]]
9) Energy - Short Answer Researchers at Brookhaven National Labs have been using DNA origami to make nanoscale superconducting wires. To create DNA origami, linear, single stranded DNA must be circularized and then supercoiled via topoisomerases. Identify all of the following three statements that are true of DNA topoisomerases: 1) They are found in both eukaryotes and prokaryotes; 2) The DNA polymerase holocenzyme can continue to replicate if topoisomerases are knocked out; 3) Topoisomerases bind to single stranded binding proteins to introduce tension in the lagging strand.  

text[[56, 402, 206, 418]]
ANSWER: 1 ONIY  

sub_title[[462, 465, 540, 481]]
## TOSS-UP  

text[[55, 496, 820, 513]]
10) Chemistry - Multiple Choice Which of the following statements is NOT true in chemical kinetics?  

text[[55, 529, 736, 597]]
W) The half-life of a zeroth-order reaction increases over time  X) Termolecular reactions are very rare  Y) For a reaction with negative activation energy, the rate decreases as temperature increases  Z) The free energy of a transition state is decreased by a catalyst  

text[[55, 613, 792, 630]]
ANSWER: W) THE HALF-LIFE OF A ZEROTH-ORDER REACTION INCREASES OVER TIME  

sub_title[[468, 645, 536, 661]]
## BONUS  

text[[55, 676, 896, 709]]
10) Chemistry - Short Answer Gold adopts a face-centered cubic unit cell with an edge length of 4 angstroms. In angstroms and simplest radical form, what is the atomic radius of gold?  

text[[56, 725, 166, 743]]
ANSWER: \(\sqrt{2}\)sub_title[[457, 65, 544, 81]]
## TOSS-UP  

text[[55, 103, 888, 138]]
11) Math - Short Answer Determine the distance between the focus of the parabola \(y = x^{2}\) and the point on the parabola with \(y\) -coordinate 15.  

text[[56, 152, 177, 168]]
ANSWER:61/4  

sub_title[[468, 184, 534, 201]]
## BONUS  

text[[56, 216, 936, 250]]
11) Math - Short Answer An ant stands on the point (1, 0) on the cartesian point. At each point in time, it moves either left or right by one unit with equal probability. What is the probability the ant reaches the origin before the point (3, 0)?  

text[[56, 263, 167, 279]]
ANSWER:2/3  

sub_title[[465, 325, 541, 341]]
## TOSS-UP  

text[[56, 355, 940, 375]]
12) Physics - Multiple Choice According to Wein's law, which of the following quantities is constant for a black body?  

text[[55, 390, 441, 472]]
W) \(T^{\lambda_{\mathrm{max}}}\) [Temperature to the power of lambda max] X) \(T / \lambda_{max}\) [Temperature divided by lambda max] Y) \(\lambda_{max} / T\) [Lambda max divided by Temperature ] Z) \(T\lambda_{max}\) [Temperature times lambda max]  

text[[56, 490, 210, 508]]
ANSWER:Z) \(T\lambda_{max}\)  

sub_title[[468, 526, 534, 543]]
## BONUS  

text[[56, 557, 927, 605]]
12) Physics - Short Answer When the electric field within a diode is strong enough, electrons can tunnel from the valence band to the conduction band and leave charge carriers that conduct current in the reverse direction. What is this breakdown known as?  

text[[56, 616, 325, 633]]
ANSWER:ZENER BREAKDOWNsub_title[[458, 65, 544, 81]]
## TOSS-UP  

text[[57, 101, 931, 150]]
13) Biology - Short Answer During the binding of LDL to the LDL receptor, a series of intracellular events leads to receptor mediated endocytosis of the LDL. During this process, a triskelion of what protein is present on the vesicle that maintains structural integrity?  

text[[57, 162, 239, 178]]
ANSWER:CLATHRIN  

sub_title[[468, 210, 534, 225]]
## BONUS  

text[[57, 241, 902, 274]]
13) Biology - Short Answer Identify all of the following 3 traits that distinguish Archaea from Bacteria: 1) Usage of methionine as initiator amino acid; 2) Presence of histones in DNA 3) Presence of Circular DNA.  

text[[57, 287, 210, 302]]
ANSWER:1AND2  

sub_title[[462, 347, 540, 362]]
## TOSS-UP  

text[[57, 377, 904, 410]]
14) Earth and Space - Short Answer Order the following 3 minerals in order of increasing hardness: 1) Calcite; 2) Aragonite; 3) Fluorite.  

text[[57, 426, 191, 442]]
ANSWER:1,2,3  

sub_title[[468, 460, 534, 476]]
## BONUS  

text[[57, 491, 936, 524]]
14) Earth and Space - Short Answer Identify all of the following three phenomena which are observed in each mineral: 1) Triboluminescence - diamond; 2) Birefringence - corundum; 3) Asterism - star sapphire.  

text[[57, 540, 210, 555]]
ANSWER:1AND3sub_title[[459, 65, 544, 81]]
## TOSS-UP  

text[[56, 101, 917, 149]]
15) Energy - Short Answer DOE Researchers at Pacific Northwest National Labs used a binarized neural network to model the effects of pruning on plants. They included a parameter that measures the polar transport of which hormone produced in the apical bud that is responsible for apical dominance?  

text[[56, 162, 211, 178]]
ANSWER:AUXINS  

sub_title[[468, 194, 533, 210]]
## BONUS  

text[[56, 225, 926, 289]]
15) Energy - Short Answer Researchers at Pacific Northwest National Labs have used tandem mass spectrometry to detect post translational modifications to proteins in those with glioblastoma to try and determine a proximate cause for the cancer. These modifications included acetylation which was previously limited only to histones. In histones, what amino acid is acetylated by histone acetyltransferase?  

text[[56, 302, 207, 317]]
ANSWER:LYSINE  

sub_title[[461, 364, 540, 380]]
## TOSS-UP  

text[[56, 395, 810, 413]]
16) Chemistry - Short Answer What is the molecular geometry of the central xenon atom in \(\mathrm{XeO_3F_2}\) ?  

text[[56, 427, 365, 443]]
ANSWER:TRIGONALBIPYRAMIDAL  

sub_title[[468, 459, 534, 475]]
## BONUS  

text[[56, 490, 930, 524]]
16) Chemistry - Short Answer Order the following three orbitals in increasing electronegativity in oxygen: 1) s; 2) sp; 3) sp<sup>3</sup>.  

text[[56, 537, 189, 553]]
ANSWER:3,2,1sub_title[[459, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 922, 134]]
17) Math - Multiple Choice The points A, B, C, and D lie on a line in that order. Of all line segments with these four points as endpoints, if AB is the shortest such segment, which of the following must be true?  

text[[55, 148, 195, 212]]
W)BD>AC X)BC>AB+CD Y)AC>CD Z)BC>CD  

text[[57, 227, 241, 243]]
ANSWER:W)BD>AC  

sub_title[[462, 259, 528, 275]]
## BONUS  

text[[55, 290, 784, 307]]
17) Math - Short Answer What is the image of the point (1, 2) if it is rotated \(60^{\circ}\) about the origin?  

text[[57, 323, 325, 342]]
ANSWER: \((1 / 2 - \sqrt{3}, 1 + \sqrt{3} /2)\)  

sub_title[[456, 387, 534, 403]]
## TOSS-UP  

text[[55, 418, 936, 451]]
18) Physics - Multiple Choice An object is placed at the focal point of a biconcave lens. Which of the following is true about the image that is produced?  

text[[55, 466, 262, 529]]
W) Diminished and upright X) Magnified and upright Y) Diminished and inverted Z) Magnified and inverted  

text[[57, 544, 405, 560]]
ANSWER:W) DIMINISHED AND UPRIGHT  

sub_title[[462, 576, 528, 592]]
## BONUS  

text[[55, 607, 940, 640]]
18) Physics - Multiple Choice Which of the following temperatures in degrees celsius for the cold and hot reservoirs of an ideal refrigerator, respectively, will result in the highest coefficient of performance?  

text[[55, 651, 147, 713]]
W)50,100 X)50,150 Y)100,150 Z)100,200  

text[[57, 729, 231, 745]]
ANSWER:Y)100,150sub_title[[459, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 805, 119]]
25) Biology - Short Answer At resting membrane potential, which ion has the greatest permeability?  

text[[56, 131, 365, 147]]
ANSWER: POTASSIUM (ACCEPT: K+)  

sub_title[[468, 163, 534, 179]]
## BONUS  

text[[55, 193, 870, 225]]
25) Biology - Multiple Choice Which of the following best explains the lack of disulfide bonds within the cell environment?  

text[[56, 237, 748, 300]]
W) They contain a highly oxidizing environment which precludes formation of disulfide bonds  X) They contain a highly reducing environment which precludes formation of disulfide bonds  Y) The cysteine residues are not located near each other for proteins in the cell  Z) The cysteines are all oxidized to cystin, thus not able to form disulfide bonds  

text[[56, 314, 936, 347]]
ANSWER: X) THEY CONTAIN A HIGHLY REDUCING ENVIRONMENT WHICH PRECLUDES FORMATION OF DISULFIDE BONDStext[[0, 0, 997, 997]]
# 1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1