sub_title[[461, 116, 540, 133]]
## TOSS-UP  

text[[56, 148, 942, 211]]
1) Chemistry - Short Answer In Michael additions, ketones are usually unfavorable as nucleophilic donors because their enol tautomer is unperferable. The Stork synthesis can be used to improve the ability of a ketone to act as a donor by first converting it into what functional group by treating the ketone with a secondary amine under mildly acidic conditions?  

text[[57, 226, 228, 241]]
ANSWER: ENAMINE  

sub_title[[432, 258, 570, 274]]
## VISUAL BONUS  

text[[56, 289, 946, 353]]
1) Chemistry - Short Answer Shown in the image is a cyclopropanation reaction commonly used to functionalize fullerenes. Identify all of the following three statements that are true about the reaction shown: 1) It is an example of an aromatic substitution; 2) DBU serves as a nucleophilic catalyst; 3) The driving chemical force is relief of strain induced by steric factors.  

text[[57, 368, 206, 383]]
ANSWER: 3 ONLY  

sub_title[[461, 430, 540, 446]]
## TOSS-UP  

text[[56, 462, 946, 510]]
2) Math - Short Answer Identify all of the following three statements that are true of kites: 1) The sum of the squares of the diagonals is equal to the sum of the squares of the side lengths; 2) The perimeter of a kite with diagonals of fixed lengths is minimized when it is a rhombus; 3) All kites can contain an inscribed circle.  

text[[57, 525, 210, 541]]
ANSWER: 1 AND 3  

sub_title[[468, 557, 534, 572]]
## BONUS  

text[[57, 589, 875, 610]]
2) Math - Short Answer Let \(f(n) = n^2 + n + 2021\) . Determine the number of positive divisors of \(f(2020)\) .  

text[[57, 625, 153, 640]]
ANSWER: 4sub_title[[458, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 931, 135]]
3) Earth and Space - Multiple Choice A rogue comet passes through the solar system and temporarily orbits the Sun. It has a velocity equal to twice of its escape velocity. Which of the following orbital shapes will it follow?  

text[[55, 149, 163, 217]]
W) Circular  X) Elliptical  Y) Parabolic  Z) Hyperbolic  

text[[57, 236, 248, 252]]
ANSWER: Z) Hyperbolic  

sub_title[[432, 269, 570, 285]]
## VISUAL BONUS  

text[[55, 300, 930, 366]]
3) Earth and Space - Short Answer Scientists at NASA used the Chandra Observatory and XMM newton telescopes to detect the quasar H2356-309 from behind the Sculptor wall of huge diffuse gas. They formed a spectrum of their graph with two dips corresponding to oxygen around one million kelvin. Answer the following two questions concerning this image:  

text[[83, 374, 943, 423]]
1. In what region of the electromagnetic spectrum does the spectrum correspond to?  
2. What specific portion of the intergalactic medium do the dips in the spectrum likely correspond to, composing the majority of baryonic matter between galaxies?  

text[[57, 437, 300, 453]]
ANSWER: 1) X-RAY; 2) WHIM  

sub_title[[462, 500, 540, 516]]
## TOSS-UP  

text[[55, 531, 940, 565]]
4) Physics - Short Answer Identify all of the following three statements concerning the charm quark which are true: 1) It has an electric charge of \(-2 / 3\) ; 2) It has spin \(\frac{1}{2}\) ; 3) It experiences all 4 fundamental forces.  

text[[57, 579, 210, 595]]
ANSWER: 2 AND 3  

sub_title[[432, 610, 570, 626]]
## VISUAL BONUS  

text[[55, 642, 940, 675]]
4) Physics - Short Answer Shown in the image are the IV curves for two devices in red and blue. Answer the following two questions about the image:  

text[[83, 684, 771, 717]]
1. What general class of semiconductor devices do these two IV curves depict?  
2. What specific types of this class of device do the red and blue curves depict, respectively?  

text[[55, 731, 528, 748]]
ANSWER: 1) DIODES; 2) RED IS SCHOTTKY, BLUE IS P-Nsub_title[[458, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 940, 134]]
5) Biology - Short Answer Since amino acids have two ionizable side chains, many can serve as buffers near their pKa. What is the only amino acid that can serve as a buffer at physiological pH?  

text[[57, 148, 234, 164]]
ANSWER:HISTIDINE  

sub_title[[432, 180, 570, 196]]
## VISUAL BONUS  

text[[57, 211, 910, 244]]
5) Biology - Short Answer Shown in the image is a wright-giemsa stain of a blood smear, belonging to a patient with Burkitt's Lymphoma. Answer the following two questions concerning this disease.  

text[[85, 256, 800, 291]]
1. Burkitt's lymphoma is a cancer that can be caused endemically by what virus? 
2. Which type of immune cells are likely represented by the malignant purple cells in the image?  

text[[57, 305, 682, 322]]
ANSWER:1)EPSTEIN-BARR VIRUS;2)B-CELLS(ACCEPT PLASMA CELLS)  

sub_title[[462, 368, 540, 383]]
## TOSS-UP  

text[[55, 399, 941, 448]]
6) Energy - Short Answer Scientists at Idaho National Iab are studying organic ligands that can be used to improve the efficiency of fuels. Order the following three organic ligands in increasing field splitting strength: 1) \(\mathrm{CH}_2\) ; 2) \(\mathrm{CH}_3\) ; 3) \(\mathrm{C}_2\mathrm{H}_4\) .  

text[[57, 463, 189, 479]]
ANSWER:2,3,1  

sub_title[[432, 494, 570, 510]]
## VISUAL BONUS  

text[[55, 525, 936, 558]]
6) Energy - Short Answer Shown in the image is the mechanism of action of penicillin, which Los Alamos National Lab scientists have been detailing using machine learning. Answer the following three questions concerning the image:  

text[[85, 568, 880, 631]]
1. What group of antibiotics, named after the it's namesake motif, does penicillin belong to? 
2. What enzyme does penicillin deactivate? 
3. Identify all of the following three descriptions that correctly identify penicillin: 1) Suicide inactivator; 2) Irreversible inhibitor; 3) Antiviral agent.  

text[[55, 644, 545, 661]]
ANSWER:1) \(\beta\) -LACTAMS;2)TRANSPEPTIDASE;3)1AND2sub_title[[458, 65, 545, 81]]
## TOSS-UP  

text[[55, 101, 911, 135]]
7) Chemistry - Multiple Choice Which of the following best describes the direction of electron flow in the bonding interaction between a metal center and carbonyl ligand?  

text[[55, 144, 431, 214]]
W) From ligand sigma orbital to metal d orbital  X) From metal d orbital to ligand sigma star orbital  Y) From ligand pi orbital to metal d orbital  Z) From metal d orbital to ligand pi star orbital  

text[[55, 230, 635, 248]]
ANSWER: Z) FROM METAL D ORBITAL TO LIGAND PI STAR ORBITAL  

sub_title[[468, 262, 535, 278]]
## BONUS  

text[[55, 293, 941, 342]]
7) Chemistry - Short Answer Identify all of the following three carboxylic acid derivatives that display an IR stretching band for the carbonyl group with a larger wavenumber than in methyl acetate: 1) Acetyl fluoride; 2) 2-amino methyl acetate; 3) 2-chloromethyl acetate.  

text[[55, 356, 210, 372]]
ANSWER: 1 AND 3  

sub_title[[461, 418, 540, 435]]
## TOSS-UP  

text[[55, 450, 877, 468]]
8) Math - Short Answer The sum of the square and square root of a certain number is 18. What is the number?  

text[[55, 483, 154, 498]]
ANSWER: 4  

sub_title[[468, 513, 535, 530]]
## BONUS  

text[[55, 545, 936, 577]]
8) Math - Short Answer I.ct \(P\) be a point inside square ABCD such that \(AP = 2\) \(BP = 4\) and \(CP = 5\) What is the length of \(DP\)  

text[[55, 594, 177, 612]]
ANSWER: \(\sqrt{13}\)sub_title[[459, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 930, 134]]
9) Earth and Space - Multiple Choice Which of the following rocks would you expect to find between each pillow in a pillow basal?  

text[[55, 149, 179, 212]]
W) Rhyolite  X) Hyaloclastite  Y) Ignmibrite  Z) Welded Tuff  

text[[57, 227, 315, 244]]
ANSWER: X) HYALOCLASTITE  

sub_title[[432, 259, 569, 275]]
## VISUAL BONUS  

text[[55, 290, 944, 369]]
9) Earth and Space - Short Answer Shown in the image is a new image of M87 captured by the event horizon telescope that shows the magnetic polarization of the light. Answer the following two questions about this image: 1) What technique used by the event horizon telescope combines multiple telescopes around the world to obtain a higher resolution image?; 2) The outermost layer of the jet emanating from M87 is parabolic in nature because the Kerr black hole causes what effect, predicted in General Relativity and seen in the I.ens Thirring effect to occur?  

text[[55, 384, 518, 401]]
ANSWER: 1) INTERFEROMETRY; 2) FRAME DRAGGING  

sub_title[[462, 447, 540, 463]]
## TOSS-UP  

text[[55, 479, 908, 527]]
10) Physics - Short Answer Give, by name or number, all of the following 3 statements concerning electric currents which are true: 1) Voltage reversal is when the direction of electron flow reverses; 2) AC currents experience \(100\%\) voltage reversal; 3) The inductance and capacitance in DC currents form a harmonic oscillator.  

text[[57, 542, 210, 557]]
ANSWER: 2 AND 3  

sub_title[[432, 574, 569, 589]]
## VISUAL BONUS  

text[[57, 604, 926, 637]]
10) Physics - Short Answer Shown in the image is a potential function and its corresponding wavefunctions given by the Schrodinger equation. Answer the following questions:  

text[[83, 648, 936, 715]]
1. What is the name of this system?  
2. What is the ratio of the average kinetic energy to the average potential energy of each state?  
3. The ground state of this system has nonzero energy due to the Heisenberg uncertainty principle. What is the term for this energy?  

text[[55, 731, 724, 749]]
ANSWER: 1) QUANTUM HARMONIC OSCILLATOR; 2) 1; 3) ZERO POINT ENERGYsub_title[[459, 65, 544, 81]]
## TOSS-UP  

text[[57, 101, 940, 135]]
11) Biology - Short Answer Which cell receptors that distinguish helper T cells from cytotoxic T cells are bound by HIV in order to promote viral entry?  

text[[57, 149, 179, 165]]
ANSWER:CD4  

sub_title[[432, 180, 570, 196]]
## VISUAL BONUS  

text[[57, 211, 915, 244]]
11) Biology - Short Answer Depicted in the image is a three dimensional protein folding funnel, which plots the free energy of protein folding conformations in 3D space. Answer the following three questions about this image:  

text[[85, 254, 936, 319]]
1. Which funnel, a, b, or c, would likely require the presence of a chaperone?  
2. Which funnel represents a protein that has a singular folding pathway?  
3. When a large amount of unfolded protein accumulates, the unfolded protein response regulates the production of which tag that, when attached to proteins, marks them for destruction by the proteasome?  

text[[57, 333, 340, 349]]
ANSWER:1)B2)C3)UBIQUITIN  

sub_title[[462, 396, 540, 412]]
## TOSS-UP  

text[[57, 426, 939, 475]]
12) Energy - Multiple Choice Scientists at Lawrence Livermore National Lab discovered that materials such as 1-ethyl imidazolium bis trifluoromethane sulfonyl imide can be used to increase the efficiency of carbon sequestration from the atmosphere. Which of the following states of matter do these compounds belong to?  

text[[57, 486, 325, 549]]
W) Supercritical fluid  X) I.iquid crystal  Y) Plasma  Z) High temperature superconductor  

text[[57, 564, 314, 580]]
ANSWER:X)LIQUIDCRYSTAL  

sub_title[[432, 595, 570, 611]]
## VISUAL BONUS  

text[[57, 626, 936, 675]]
12) Energy - Short Answer Depicted in the image is the X-ray diffraction scattering pattern of a magnetic rare earth icosahedral binary quasicrystal that Scientists at Ames Laboratory have been studying. The mineral, termed icosahedrite, is naturally occurring but extraterrestrial in origin. Answer the following two questions about the image:  

text[[80, 685, 860, 720]]
1. Instead of phonons, what quasiparticle, the permutable analog of phonons, are found in these crystals?  
2. How many modes of symmetry are found in this diffraction pattern?  

text[[57, 735, 285, 752]]
ANSWER:1)PHASONS;2)8sub_title[[458, 65, 544, 81]]
## TOSS-UP  

text[[56, 101, 936, 166]]
13) Chemistry - Short Answer Identify all of the following three statements that are true about nitriles: 1) The nitrogen lone pair acts as a strong nucleophile; 2) The carbon-13 NMR shift of the carbon in a nitrile is usually greater than an sp hybridized alkyne carbon; 3) An amine is produced by treating a nitrile with excess grignard reagent followed by acid work-up.  

text[[56, 180, 206, 196]]
ANSWER:2 ONLY  

sub_title[[432, 211, 570, 228]]
## VISUAL BONUS  

text[[56, 242, 891, 276]]
13) Chemistry - Short Answer Shown in the image is the reaction of a diester using catalytic amounts of sodium ethoxide. Answer the following three questions about this reaction:  

text[[85, 285, 803, 337]]
1. What is the name of this general class of reactions between esters under basic conditions?  
2. What is the specific name for the version of the general class of reactions shown in the image?  
3. By letter, which of the labeled products is the major product of this reaction?  

text[[56, 353, 710, 371]]
ANSWER:1)CLAISEN CONDENSATION;2)DIECKMANN CONDENSATION;3)Y  

sub_title[[462, 417, 540, 433]]
## TOSS-UP  

text[[56, 448, 924, 481]]
14) Math - Short Answer An urn contains 12 red balls and 15 blue balls. Kira takes out 6 balls once at a time. What is the expected number of red balls she draws?  

text[[56, 496, 168, 512]]
ANSWER:8/3  

sub_title[[468, 528, 535, 544]]
## BONUS  

text[[56, 560, 860, 581]]
14) Math - Short Answer Find all the critical points on the graph of the function \(f(x,y) = x^3 + y^3 - 3xy\)  

text[[56, 595, 233, 611]]
ANSWER: (0, 0), (1, 1)sub_title[[459, 65, 544, 81]]
## TOSS-UP  

text[[57, 101, 928, 134]]
15) Earth and Space - Short Answer The twinkling of stars is caused by different air densities in the atmosphere which refracts starlight in slightly different ways. What is the term for this phenomena?  

text[[57, 148, 280, 163]]
ANSWER:SCINTILLATION  

sub_title[[432, 180, 570, 196]]
## VISUAL BONUS  

text[[57, 212, 900, 245]]
15) Earth and Space - Short Answer Shown is a picture of a "thunder egg." Answer the following three questions concerning the thunder egg:  

text[[85, 259, 691, 306]]
1. The insides of a thunder egg are filled with what form of silica?  
2. Thunder eggs are associated with what type of lava?  
3. What process do volcanic glassy volcanic rocks undergo to form thunder eggs?  

text[[57, 321, 599, 338]]
ANSWER:1) CHALCEDONY:2) RHYOLITIC:3) DEVITRIFICATION  

sub_title[[462, 384, 540, 400]]
## TOSS-UP  

text[[57, 415, 901, 448]]
16) Physics - Short Answer What term is given to the thickness of the incomplete expulsion of magnetic fields in a superconductor, observed in the Miessner effect?  

text[[57, 462, 411, 478]]
ANSWER:IONDONPENETRATIONDEPTH  

sub_title[[432, 494, 570, 510]]
## VISUAL BONUS  

text[[57, 525, 940, 589]]
16) Physics - Short Answer Shown in the diagram is a circuit diagram for an incomplete circuit. A motor with a certain resistance is to be placed between the leads marked in red. Given \(R_{1} = 2\Omega\) , \(R_{2} = 3\Omega\) , \(R_{3} = 6\Omega\) , and the potential difference across the battery is \(6\mathrm{V}\) , answer the following two questions: 1) In ohms, what should be the resistance of the motor in order to maximize the power delivered to the motor? 2) In watts, what is this maximum power?  

text[[57, 604, 278, 620]]
ANSWER:1)1.2Ω2)1.2Wsub_title[[459, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 890, 134]]
17) Biology - Short Answer While mammalian blood is red because it contains hemoglobin, hemolymph is blue because it contains what oxygen binding protein?  

text[[57, 148, 266, 164]]
ANSWER: HEMOCYANIN  

sub_title[[462, 180, 528, 196]]
## BONUS  

text[[57, 212, 914, 260]]
17) Biology - Short Answer Identify all of the following three agents, that when added to isolated mitochondria with phosphate and ADP, would increase the rate of oxygen consumption: 1) 2,4 Dinitrophenol, an uncoupling agent; 2) Cyanide, a cytochrome c oxidase inhibitor; 3) Oligomycin, an ATP synthase inhibitor.  

text[[57, 275, 206, 290]]
ANSWER: 1 ONLY  

sub_title[[456, 337, 534, 352]]
## TOSS-UP  

text[[57, 369, 902, 416]]
18) Energy - Short Answer Scientists at Argonne National Lab have been studying the cytoskeletal structure of red blood cells and observed the presence of a pentagonal protein bound to ankyrin and glycophorin in the plasma membrane. What is the likely identity of this protein?  

text[[57, 428, 230, 444]]
ANSWER: SPECTRIN  

sub_title[[425, 461, 563, 477]]
## VISUAL BONUS  

text[[57, 492, 933, 540]]
18) Energy - Short Answer Scientists at Oak Ridge National Lab are using the Spallation Neutron Source to probe the structural properties of various materials. Shown in the image are four allotropes of an element on the periodic table. Answer the following three questions about the image shown:  

text[[85, 551, 550, 598]]
1. What element are these four structures allotropes of?  
2. By letter, give the name of each allotrope shown.  
3. By letter, identity which allotrope is kinetically most stable.  

text[[55, 612, 752, 630]]
ANSWER: 1) PHOSPHORUS; 2) A IS WHITE, B IS BLACK, C IS VIOLET, D IS RED; 3) Dsub_title[[457, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 832, 134]]
19) Chemistry - Multiple Choice David treats a sample of bromobenzene with butyllithium followed by catecholborane. Which of the following reactions is David most likely preparing for?  

text[[55, 145, 333, 213]]
W) Aryne elimination-addition  X) Hydroboration oxidation  Y) Nucleophilic aromatic substitution  Z) Suzuki coupling  

text[[57, 230, 328, 247]]
ANSWER: Z) SUZUKI COUPLING  

sub_title[[468, 262, 534, 278]]
## BONUS  

text[[55, 293, 930, 342]]
19) Chemistry - Short Answer Identify all of the following three statements that are true regarding triplet carbenes: 1) Most triplet carbenes are characterized as having sp3 hybridization; 2) Triplet carbenes can be formed via alpha elimination; 3) Unlike singlet carbenes, triplet carbenes undergo concerted cyclopropanation of alkenes.  

text[[57, 352, 195, 367]]
ANSWER: NONE  

sub_title[[462, 417, 540, 433]]
## TOSS-UP  

text[[55, 448, 941, 466]]
20) Math - Short Answer Suppose \(n\) is an integer with 5 divisors. What is the least number of divisors \(n - 1\) can have?  

text[[57, 480, 154, 495]]
ANSWER: 4  

sub_title[[432, 511, 570, 528]]
## VISUAL BONUS  

text[[55, 543, 936, 575]]
20) Math - Short Answer Shown in the image is a 3 by 3 matrix. Answer the following two questions about the matrix shown: 1) Is the matrix shown invertible? 2) What is the dimension of the kernel of the matrix shown?  

text[[57, 590, 226, 605]]
ANSWER: 1) NO, 2) 1sub_title[[459, 66, 544, 81]]
## TOSS-UP  

text[[55, 101, 900, 119]]
21) Earth and Space - Multiple Choice Which of the following is associated with high concentrations of helium 3?  

text[[55, 134, 227, 197]]
W) Abyssal Hills  X) Lagoons  Y) Seamounts  Z) Hydrothermal Vents  

text[[57, 212, 380, 228]]
ANSWER: Z) HYDROTHERMAL VENTS  

sub_title[[468, 243, 534, 259]]
## BONUS  

text[[55, 274, 610, 291]]
21) Earth and Space - Short Answer Answer the following two questions:  

text[[83, 306, 877, 400]]
1. What rare earth element commonly forms \(+2\) ions instead of \(+3\) ions, causing anomalies relative to other lanthanides?  
2. Identify all of the following three elements which one would expect to be concentrated into olivine?  a. Zirconium  b. Cobalt  c. Nickel  

text[[57, 415, 341, 431]]
ANSWER: 1) EUROPIUM; 2) b and c  

sub_title[[461, 479, 540, 494]]
## TOSS-UP  

text[[55, 510, 941, 558]]
22) Physics - Short Answer Lagrangian mechanics is a formulation of classical mechanics based upon what principle which is defined to be the integral of the Lagrangian between 2 different times t1 and t2 and is also the founding principle behind Newtonian and Hamiltonian mechanics?  

text[[57, 573, 395, 589]]
ANSWER: PRINCIPLE OF LEAST ACTION  

sub_title[[432, 604, 569, 620]]
## VISUAL BONUS  

text[[55, 636, 918, 683]]
22) Physics - Short Answer Shown in the image is a Feynman diagram of a certain interaction. Answer the following two questions: 1) What interaction is being displayed?; 2) This diagram depicts the only proposed elastic scattering mechanism of which particle?  

text[[55, 699, 458, 714]]
ANSWER: 1) NEUTRAL CURRENT; 2) NEUTRINOsub_title[[459, 66, 544, 81]]
## TOSS-UP  

text[[55, 102, 904, 134]]
23) Biology - Multiple Choice The oxygen evolving, or water splitting complex in plants requires the presence of which of the following transition metal cofactors?  

text[[55, 149, 180, 212]]
W) Nickel X) Molybdenum Y) Magnesium Z) Manganese  

text[[57, 227, 280, 243]]
ANSWER: Z) MANGANESE  

sub_title[[432, 257, 569, 273]]
## VISUAL BONUS  

text[[55, 288, 941, 368]]
23) Biology - Short Answer Shown in the image are the two graphs showing the photosynthetic rate of a C3 and C4 plants against the leaf temperature at normal and high CO concentration. Answer the following three questions about this diagram: 1) Which color, blue or red, depicts the C4 plant?; 2) What process at high temperatures is responsible for the tapering off of the photosynthetic rate after 40 degrees celsius for the red curve; 3) Which plant type, C3 or C4, has a higher water use efficiency?  

text[[55, 382, 468, 399]]
ANSWER: 1) BLUE; 2) PHOTORESPIRATION; 3) C4  

sub_title[[462, 446, 540, 461]]
## TOSS-UP  

text[[55, 477, 926, 525]]
24) Energy - Multiple Choice Researchers at Los Alamos National Laboratory are working on a vaccine for HIV. HIV was first treated with AZT, a reverse transcriptase inhibitor initially developed against retrovirus-based cancers. AZT is best described by as a:  

text[[55, 540, 279, 602]]
W) Nucleoside analog X) Noncompetitive antagonist Y) Competitive agonist Z) Allosteric inhibitor  

text[[57, 617, 365, 633]]
ANSWER: W) NUCLEOSIDE ANALOG  

sub_title[[432, 648, 569, 664]]
## VISUAL BONUS  

text[[55, 680, 926, 728]]
24) Energy - Short Answer Scientists at Los Alamos National Lab discovered a ferromagnetic uranium-based alloy with strong thermoelectric properties, exemplified by having a high anomalous Nernst conductivity. The image shows a diagram representing various effects in the alloy. Answer the following three questions about the diagram in the image:  

text[[83, 738, 928, 802]]
1. While diagram B represents the anomalous Nernst effect, diagram A represents what effect? 
2. The high anomalous Nernst conductivity is due to a large occurrence of what relativistic effect in the alloy? 
3. The Nernst effect is also used in RTG's. The Perseverance Mars rover is powered by an RTG that utilizes which isotope?  

text[[55, 817, 638, 834]]
ANSWER: 1) SEEBECK; 2) SPIN-ORBIT COUPLING; 3) PLUTONIUM-238sub_title[[458, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 926, 149]]
25) Chemistry - Short Answer For Raman active rotational transitions in a molecule, the molecule must display what property characterized by the magnitude of the induced dipole moment depending on the direction of the electric field relative to the molecule?  

text[[57, 164, 257, 180]]
ANSWER: ANISOTROPY  

sub_title[[432, 196, 569, 212]]
## VISUAL BONUS  

text[[55, 227, 940, 275]]
25) Chemistry - Short Answer Shown in the image is Vashka's complex, which can be reacted with oxygen gas to form an octahedral complex. Answer the following three questions about Vashka's complex, knowing that free neutral iridium is d7 in its ground-state:  

text[[85, 285, 710, 337]]
1. What is the total valence electron count of Vashka's complex?  
2. What is the hapticity of the dioxygen ligand in its adduct with Vashka's complex?  
3. How many unpaired electrons does iridium have in Vashka's complex?  

text[[57, 354, 260, 370]]
ANSWER: 1) 16; 2) 2; 3) 0text[[0, 0, 997, 997]]
# 1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1