sub_title[[462, 115, 541, 132]]
## TOSS-UP  

text[[55, 147, 904, 180]]
1) Chemistry - Short Answer Order the following three substituents on benzene in increased activation of the ring towards electrophilic aromatic substitution: 1) Nitro; 2) Methoxy; 3) Fluoride.  

text[[56, 195, 191, 210]]
ANSWER:1,3,2  

sub_title[[468, 226, 535, 242]]
## BONUS  

text[[56, 258, 936, 291]]
1) Chemistry - Short Answer Order the following three functional groups in terms of increasing ease of hydrogenation: 1) Nitro; 2) Alkene; 3) Phenyl.  

text[[56, 305, 189, 320]]
ANSWER:3,2,1  

sub_title[[462, 367, 541, 383]]
## TOSS-UP  

text[[56, 399, 691, 420]]
2) Math - Short Answer I.ct \(f(x) = x^{5}\) . What is the fourth derivative of \(f\) at \(x = 5\)  

text[[56, 435, 173, 450]]
ANSWER:600  

sub_title[[468, 466, 535, 483]]
## BONUS  

text[[56, 498, 946, 547]]
2) Math - Short Answer A frog is trapped on a number line at the number 2. At each point in time, it can jump one unit in either the positive or negative direction with equal probability. If the frog lands on 0, the frog will be able to escape, but if the frog lands on 5, it will be trapped forever. What is the probability the frog escapes?  

text[[56, 561, 168, 576]]
ANSWER:3/5sub_title[[457, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 933, 150]]
3) Earth and Space - Multiple Choice The Red clump, Blue loop, and Horizontal branch can all be synonymous terms for the period of a star's evolution for different mass stars. During this transition in the star's life, which of the following best describes what is happening?  

text[[55, 165, 409, 228]]
W) Ignition of hydrogen around the helium core  X) Ignition of helium around a carbon core  Y) Ignition of helium in the degenerate core  Z) Ignition of carbon in the core  

text[[55, 242, 590, 259]]
ANSWER: Y) IGNITION OF HELIUM IN THE DEGENERATE CORE  

sub_title[[468, 274, 533, 290]]
## BONUS  

text[[55, 306, 920, 354]]
3) Earth and Space - Short Answer Identify all of the following three statements concerning spectroscopy which are true: 1) Sodium double D lines are an example of the Zeeman effect; 2) Some Fraunhofer lines are telluric lines; 3) A calcium doublet is observed in the Sun's spectrum.  

text[[56, 369, 178, 384]]
ANSWER: A.I.I.  

sub_title[[461, 431, 540, 447]]
## TOSS-UP  

text[[55, 462, 936, 495]]
4) Physics - Short Answer A gas is expanding from an initial volume to a final volume at the same temperature. Which sequence of steps will allow the gas to perform the most work?  

text[[55, 505, 444, 574]]
W) Isobaric expansion followed by isochoric cooling  X) Isochoric cooling followed by isobaric expansion  Y) Isothermal expansion  Z) Adiabatic expansion  

text[[55, 587, 684, 604]]
ANSWER: W) ISOBARIC EXPANSION FOLLOWED BY ISOCHORIC COOLING  

sub_title[[468, 621, 534, 637]]
## BONUS  

text[[55, 653, 936, 686]]
4) Physics - Multiple Choice For an electric field described by the vector function \(\mathbf{xy}^2\mathbf{i} - \mathbf{xy}^2\mathbf{k}\) , what is the charge density in terms of the permittivity of free space \(\epsilon_0\) [epsilon naught] at the point \(< 3,6, - 2>\) ?  

text[[55, 696, 116, 765]]
W) 6e0  X) 12e0  Y) 18e0  Z) 24e0  

text[[56, 782, 202, 799]]
ANSWER: X) 12e0sub_title[[459, 65, 544, 81]]
## TOSS-UP  

text[[57, 101, 920, 134]]
5) Biology - Short Answer SNARE proteins interact with which proteins on the vesicle that triggers a conformational change in the v-SNARE and t-SNARE complex that leads to membrane fusion?  

text[[57, 146, 555, 162]]
ANSWER: SYNAPTOTAGMINS (ACCEPT: SYNAPTOBREVIN)  

sub_title[[468, 194, 534, 210]]
## BONUS  

text[[55, 225, 946, 290]]
5) Biology - Short Answer The knife-clasp phenomena describes a relatively fluid motion that only occurs after a small period of high resistance. It is a hallmark of spasticity, a subset of disorders characterized by abnormally high muscle tone. What general name is given to a group of disorders characterized by abnormally high muscle tone, often seen when a joint is moved at high speeds?  

text[[57, 302, 258, 318]]
ANSWER: HYPERTONIA  

sub_title[[462, 365, 540, 380]]
## TOSS-UP  

text[[55, 395, 894, 444]]
6) Fnergy - Short Answer Scientists at Brookhaven National Lab have been studying quark matter in the 5-D Kaluza-Klein cosmological model by using the Finstcin Field equations to model some of this matter. As quantum numbers approach infinity, what classic law in mechanics do the Einstein Field equations approximate?  

text[[57, 455, 393, 470]]
ANSWER: NEWTON'S IAW OF GRAVITY  

sub_title[[468, 488, 534, 504]]
## BONUS  

text[[55, 519, 933, 583]]
6) Energy - Short Answer Scientists at Princeton Plasma Physics Laboratory have been studying the See-saw mechanism, a proposed addition to the standard model that would account for the masses of neutrinos. Identify all of the following three statements that are true of neutrinos: 1) All are observed to be left handed; 2) Sterile neutrinos only interact via gravity; 3) The electron neutrino has a larger mass than the mu neutrino.  

text[[57, 598, 178, 612]]
ANSWER: ALI.sub_title[[459, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 750, 119]]
7) Chemistry - Short Answer What nuclide is produced by the nuclear decay of beryllium-7?  

text[[57, 133, 236, 149]]
ANSWER:LITHIUM-7  

sub_title[[468, 164, 534, 180]]
## BONUS  

text[[55, 195, 947, 244]]
7) Chemistry - Multiple Choice The 'H-NMR signal of a proton \(\mathrm{H}_{\mathrm{A}}\) is only split by a single proton \(\mathrm{H}_{\mathrm{B}}\) and a single proton \(\mathrm{H}_{\mathrm{C}}\) that are NOT chemically equivalent to each other and have different coupling constants. Which of the following best describes the signal of \(\mathrm{H}_{\mathrm{A}}\) ?  

text[[55, 259, 405, 322]]
W) Three peaks with intensities of 1 to 2 to 1  X) Three peaks with equivalent intensities  Y) Four peaks with intensities of 1 to 3 to 3 to 1  Z) Four peaks with equivalent intensities  

text[[55, 337, 559, 353]]
ANSWER:Z) FOUR PEAKS WITH EQUIVALENT INTENSITIES  

sub_title[[462, 399, 540, 415]]
## TOSS-UP  

text[[55, 431, 668, 448]]
8) Math - Short Answer How many complete bipartite graphs exist with 5 nodes?  

text[[57, 463, 163, 478]]
ANSWER:16  

sub_title[[468, 494, 534, 510]]
## BONUS  

text[[55, 526, 936, 559]]
8) Math - Short Answer Let A be a symmetric matrix. Identify all of the following that are necessarily true about A: 1) A has eigenvectors that are pairwise orthogonal, 2) A is diagonalizable, 3) A is invertible.  

text[[57, 573, 210, 588]]
ANSWER:1 AND 2sub_title[[459, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 920, 150]]
9) Earth and Space – Short Answer A similar phenomenon to El Nino is known as Atlantic Nino which operates between Brazil and West Africa. Identify all of the following three statements which are true concerning Atlantic Nino during positive Atlantic Nino: 1) Weakened Atlantic hurricanes; 2) Stronger trade winds; 3) It is weaker than ENSO.  

text[[56, 165, 178, 180]]
ANSWER:ALL  

sub_title[[468, 196, 534, 212]]
## BONUS  

text[[56, 227, 940, 260]]
9) Earth and Space – Short Answer Identify all of the following 3 statements which are true concerning cockpit karst: 1) They commonly occur in the tropics 2) The landscape is weakly jointed 3) Cockpits are gently sloped  

text[[56, 275, 206, 290]]
ANSWER:1 ONLY  

sub_title[[462, 337, 540, 352]]
## TOSS-UP  

text[[55, 368, 940, 401]]
10) Physics – Multiple Choice A system of neutrons reaches thermal equilibrium at a temperature \(T\) . If the value of \(T\) is doubled, by what factor does the de Broglie wavelength of a neutron in the system change?  

text[[56, 410, 108, 494]]
W) \(\frac{1}{2}\) X) \(\frac{\sqrt{2}}{2}\) Y) \(\sqrt{2}\) Z) 2  

text[[56, 512, 192, 536]]
ANSWER: X) \(\frac{\sqrt{2}}{2}\)  

sub_title[[468, 553, 534, 568]]
## BONUS  

text[[56, 583, 940, 647]]
10) Physics – Short Answer A gamma ray is scattered by an electron at an angle of 36.9 degrees. The scattered light is then scattered by a second electron at an angle of 53.1 degrees so that the wavelength of the final scattered light is twice that of the initial gamma ray. If the Compton wavelength of an electron is 2.4 picometers, what was the wavelength of the initial gamma ray in picometers to two significant figures?  

text[[56, 662, 168, 677]]
ANSWER:1.4sub_title[[458, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 925, 134]]
11) Biology - Multiple Choice If a given pulmonary artery to a group of alveoli has reduced partial pressure of oxygen, which of the following is most likely to occur?  

text[[55, 149, 390, 217]]
W) Vasoconstriction and Bronchoconstriction  X) Vasodilation and Bronchoconstriction  Y) Vasoconstriction and Bronchodilation  Z) Vasodilation and Bronchodilation  

text[[55, 236, 620, 252]]
ANSWER: W) VASOCONSTRICTION AND BRONCHOCONSTRICTION  

sub_title[[468, 269, 534, 285]]
## BONUS  

text[[55, 300, 946, 348]]
11) Biology - Short Answer Consider a short day plant with a critical period of 10 hours. Identify all of the following three treatments that would cause it to flower: 1) 12 hours of darkness followed by a flash of light followed by 12 hours of darkness; 2) 24 hours of darkness with a light flashed at the 15 hour mark; 3) Continuous darkness.  

text[[55, 363, 210, 378]]
ANSWER: 2 AND 3  

sub_title[[462, 410, 540, 426]]
## TOSS-UP  

text[[55, 441, 937, 490]]
12) Energy - Short Answer Scientists at Brookhaven National I. ab used DNA self-assembly to produce arrays of Jospchson junctions to produce nano superconductors. As part of the self-assembly procedure, aromatic base pairs within DNA assemble on top of each other using what non-covalent attractive interaction?  

text[[55, 504, 520, 521]]
ANSWER: PI STACKING (ACCEPT: PI PI STACKING)  

sub_title[[468, 536, 534, 552]]
## BONUS  

text[[55, 568, 930, 615]]
12) Energy - Short Answer Scientists at Brookhaven National Laboratory are studying the implications of "secondary ice" and possible impacts on global climate change with reflection of shortwave radiation from small ice particles. This process is similar to what type of precipitation, where supercooled small water droplets with rapid desublimation?  

text[[55, 630, 190, 645]]
ANSWER: RIMEsub_title[[458, 65, 544, 81]]
## TOSS-UP  

text[[57, 101, 927, 149]]
13) Chemistry - Short Answer In the synthesis of octahedral hydride complexes from square planar coordinatively unsaturated complexes, treatment of the reactant complex with hydrogen gas is an example of what type of mechanistic step in organometallic chemistry?  

text[[57, 164, 605, 181]]
ANSWER: OXIDATIVE ADDITION (DO NOT ACCEPT: ADDITION)  

sub_title[[468, 195, 534, 211]]
## BONUS  

text[[57, 226, 944, 275]]
13) Chemistry - Short Answer A monatomic ideal gas with a volume of \(20~\mathrm{L}\) undergoes isochoric heating from \(100\mathrm{K}\) to \(400\mathrm{K}\) . It then undergoes isothermal compression until its entropy is the same as its initial entropy. To two significant figures and in liters, what is the final volume of the gas?  

text[[57, 290, 167, 305]]
ANSWER: 2.5  

sub_title[[462, 352, 540, 368]]
## TOSS-UP  

text[[57, 385, 936, 421]]
14) Math - Short Answer What is the coefficient of the \(ab^2 c^2\) term in the expansion of \((a + 2b + c)^5\) [the quantity a plus two b plus c, to the fifth power]?  

text[[57, 435, 172, 450]]
ANSWER: 120  

sub_title[[468, 466, 534, 482]]
## BONUS  

text[[57, 499, 899, 534]]
14) Math - Short Answer Determine the number of trailing zeros when the expression \(43^{21} - 1\) is evaluated and converted to base 7.  

text[[57, 550, 154, 565]]
ANSWER: 2sub_title[[459, 65, 544, 81]]
## TOSS-UP  

text[[57, 101, 833, 120]]
15) Earth and Space - Multiple Choice Which of the following best explains the origin of the Encke gap?  

text[[56, 133, 863, 197]]
W) A 2:1 orbital resonance with the moon Tethys removes particles from the Encke gap  X) Shepherd satellites aren't present near the Encke gap resulting in a lack of control of particles in that region  Y) Very strong forward scattering of the regions near the Encke gap clear the gap of any particles  Z) A small moon orbits in the Encke gap  

text[[56, 211, 538, 228]]
ANSWER: Z) A SMALL MOON ORBITS IN THE ENCKE GAP  

sub_title[[468, 243, 534, 259]]
## BONUS  

text[[56, 274, 934, 323]]
15) Earth and Space - Short Answer Identify all of the following three statements that are true concerning the Atlantic Meridional Overturning Circulation, or AMOC: 1) It acts as an heat pump; 2) It acts as a carbon sink; 3) It has increased in intensity over the last 100 years.  

text[[56, 337, 210, 352]]
ANSWER: 1 AND 2  

sub_title[[462, 399, 540, 415]]
## TOSS-UP  

text[[56, 431, 941, 464]]
16) Physics - Short Answer When the distance of separation between an electron and an electron-hole in an exciton pair is doubled, by what factor does the force of attraction in the pair change?  

text[[56, 478, 158, 494]]
ANSWER: 1/4  

sub_title[[468, 510, 534, 526]]
## BONUS  

text[[56, 541, 934, 589]]
16) Physics - Short Answer A three-dimensional cubic potential well has a ground-state with energy 2 electron volts. What is the maximum number of electrons that can exist in the well such that all energy states below 8 electron volts are completely filled?  

text[[56, 604, 163, 619]]
ANSWER: 20sub_title[[458, 65, 544, 81]]
## TOSS-UP  

text[[57, 101, 937, 134]]
17) Biology - Short Answer Under the influence of curare, Gideon's muscles undergo flaccid paralysis. This is because curare is an antagonist for which specific receptor of a neurotransmitter?  

text[[57, 148, 490, 164]]
ANSWER: NICOTINIC ACETYLCHOLINE RECEPTOR  

sub_title[[462, 180, 528, 196]]
## BONUS  

text[[57, 211, 933, 260]]
17) Biology - Short Answer When a photoreceptor that is connected in the OFF-pathway is illuminated by light, identify all of the following three statements that are true of the cell: 1) Transducin activates guanylyl cyclase; 2) Bipolar cell is depolarized; 3) Glutamate acts as an inhibitory neurotransmitter on the ganglion cells.  

text[[57, 272, 206, 288]]
ANSWER: 2 ONLY  

sub_title[[456, 335, 534, 351]]
## TOSS-UP  

text[[55, 366, 920, 446]]
18) Energy - Short Answer Scientists at Lawrence Berkeley National Laboratory have been studying the kinetics of polylhistidine tagging during electrosonication of lipid bilayers. To obtain a purified protein, you tag it with a polylhistidine tag at the C terminus and run an affinity chromatography using a nickel embedded resin matrix as your stationary phase. In order to clute the protein, which of the following molecules should you add that competes with the polylhistidine for the nickel?  

text[[55, 461, 157, 528]]
W) Pyrrole X) Imidazole Y) Guanidine Z) Phenol  

text[[57, 547, 268, 563]]
ANSWER: X) IMIDAZOLF  

sub_title[[462, 581, 528, 597]]
## BONUS  

text[[55, 612, 944, 677]]
18) Energy - Short Answer Scientists at Ames National Laboratory developed a new chemical pathway to break down polystyrene into styrene monomers using green chemistry. Order the following three steps in a pathway to break down the resulting styrene monomers into benzene: 1) Treatment with alkaline calcium oxide; 2) Hydrogenation under high pressures over raney nickel; 3) Treatment with acidified potassium dichromate.  

text[[57, 690, 189, 705]]
ANSWER: 2, 3, 1sub_title[[457, 65, 544, 81]]
## TOSS-UP  

text[[58, 101, 855, 120]]
19) Chemistry - Multiple Choice Which of the following statements is NOT true about the Wittig reaction?  

text[[56, 133, 460, 135]]
W) The main chemical driving force is the production of gas  

text[[56, 138, 296, 152]]
X) The reaction is stereoselective  

text[[56, 154, 460, 168]]
Y) The reaction proceeds through a cyclic intermediate  

text[[56, 180, 430, 194]]
Z) The reaction forms a carbon-carbon sigma bond  

text[[56, 210, 753, 226]]
ANSWER: W) THE MAIN CHEMICAL DRIVING FORCE IS THE PRODUCTION OF GAS  

sub_title[[468, 243, 534, 258]]
## BONUS  

text[[56, 274, 940, 307]]
19) Chemistry - Multiple Choice In the exothermic reaction between methyl chloride and sodium hydroxide, which of the following best describes the relationship between the carbon chloride and carbon-oxygen bonds in the transition state?  

text[[56, 317, 515, 386]]
W) Carbon chloride bond is shorter than carbon-oxygen bond  X) Carbon chloride bond is longer than carbon-oxygen bond  Y) Carbon chloride bond is as long as the carbon-oxygen bond  Z) Carbon oxygen bond is not formed in the transition state  

text[[56, 401, 780, 419]]
ANSWER: W) CARBON CHLORIDE BOND IS SHORTER THAN CARBON-OXYGEN BOND  

sub_title[[462, 465, 540, 481]]
## TOSS-UP  

text[[56, 496, 939, 561]]
20) Math - Short Answer Kevin writes a string of one hundred 1s on a blackboard. Between every pair of 1s, he inserts either an addition, subtraction, multiplication, or division sign. He then evaluates the resulting expression using proper order of operations. What is the difference between the largest and smallest number he could receive at the end of this process?  

text[[56, 576, 172, 592]]
ANSWER: 198  

sub_title[[468, 607, 534, 623]]
## BONUS  

text[[56, 639, 910, 671]]
20) Math - Short Answer In triangle ABC, let the angle bisector of A intersect BC at D. If angle DBA equals angle DAC and \(\mathrm{BC} = 10\) , what is the area of the triangle?  

text[[56, 686, 162, 701]]
ANSWER: 25sub_title[[459, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 928, 134]]
21) Earth and Space - Multiple Choice Which of the following condenses at the highest temperature according to the condensation sequence?  

text[[55, 149, 157, 211]]
W) Troilite  X) Iron oxide  Y) Feldspar  Z) Silica  

text[[57, 227, 273, 243]]
ANSWER: X) IRON OXIDE  

sub_title[[468, 259, 535, 275]]
## BONUS  

text[[55, 290, 931, 323]]
21) Earth and Space - Short Answer Identify all of the following three stars that would be classified as population I: 1) Type II cepheids; 2) RR Lyrae; 3) T-tauri.  

text[[57, 338, 206, 353]]
ANSWER: 3 ONLY  

sub_title[[462, 399, 540, 415]]
## TOSS-UP  

text[[55, 432, 916, 465]]
22) Physics - Short Answer The EPR paradox was resolved by which theorem that separated quantum physics with local hidden variables?  

text[[57, 480, 296, 496]]
ANSWER: BELL'S THEOREM  

sub_title[[468, 511, 535, 527]]
## BONUS  

text[[55, 543, 940, 590]]
22) Physics - Short Answer In a four dimensional universe, a tidally locked satellite orbiting the Earth moves to twice its original distance from the Earth's surface. By what factor does the magnitude of the tidal force acting on the Earth and satellite change?  

text[[57, 605, 178, 621]]
ANSWER: 1/16sub_title[[457, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 875, 134]]
23) Biology - Short Answer MPTP can often cause Parkinson's-like symptoms because it is clearly linked to the destruction of neurons within what structure of the brain?  

text[[57, 148, 315, 164]]
ANSWER:SUBSTANTIA NIGRA  

sub_title[[468, 180, 533, 196]]
## BONUS  

text[[55, 212, 940, 260]]
23) Biology - Short Answer You decide to perform a size exclusion chromatography experiment on a protein mixture obtained from sheared cell culture. Order the following three proteins in order of their elution: 1) Titin; 2) Glutathione; 3) Pepsinogen.  

text[[57, 272, 191, 288]]
ANSWER:1,3,2  

sub_title[[461, 336, 540, 351]]
## TOSS-UP  

text[[55, 366, 902, 430]]
24) Energy - Multiple Choice Scientists at Argonne National Lab have been studying the effects of high particulate matter on human lung health. High particulate matter can often trigger Asthma like symptoms as by warranting inflammation in the airways. Albuterol is commonly used as a treatment for Asthma because it acts as an agonist for which of the following types of receptors?  

text[[55, 445, 258, 508]]
W) \(\beta\) - adrenergic receptors X) Muscarinic receptors Y) \(\alpha\) adrenergic receptors Z) AMPA receptors  

text[[55, 523, 416, 540]]
ANSWER:W) \(\beta\) -ADRENERGIC RECEPTORS  

sub_title[[468, 555, 533, 571]]
## BONUS  

text[[55, 586, 928, 619]]
24) Energy - Short Answer Scientists at Princeton Plasma Physics Laboratory ran simulations on the entropy of black holes under the assumption that naked singularities may exist. This is prohibited by what hypothesis?  

text[[55, 633, 444, 649]]
ANSWER:COSMIC CENSORSHIP HYPOTHESISsub_title[[457, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 931, 134]]
25) Chemistry - Short Answer Order the following three carboxylic acid derivatives by increasing reduction potential: 1) Amide; 2) Ester; 3) Acid chloride.  

text[[56, 149, 190, 164]]
ANSWER: 1, 2, 3  

sub_title[[468, 180, 534, 197]]
## BONUS  

text[[56, 212, 920, 259]]
25) Chemistry - Short Answer Identify all of the following three changes that will increase the maximum absorption wavelength of an aqueous solution of \(\mathrm{CoCl_2}\) : 1) Addition of a suitable oxidizing agent; 2) Addition of excess HCl; 3) Addition of excess sodium nitrite.  

text[[56, 274, 205, 290]]
ANSWER: 2 ONLYtext[[0, 0, 997, 997]]
# 1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1