title[[324, 153, 677, 203]]
# LOST DE7 

text[[404, 230, 595, 257]]
April, 2021text[[7, 10, 163, 37]]
Bonus 1: 

image[[370, 26, 570, 333]]sub_title[[5, 9, 163, 37]]
Bonus 2: 

image[[0, 40, 555, 310]]
 

image[[666, 43, 980, 305]]text[[5, 8, 164, 35]]
Bonus 5: 

image[[167, 33, 816, 370]]image[[179, 45, 835, 377]]image[[192, 25, 975, 393]]image[[201, 20, 740, 380]]image[[200, 30, 923, 368]]text[[5, 9, 201, 40]]
Bonus 13: 

equation[[5, 85, 999, 312]]
\[F^{\mu \nu} = \begin{bmatrix} 0 & -E_x / c & -E_y / c & -E_z / c \\ E_x / c & 0 & -B_z & B_y \\ E_y / c & B_z & 0 & -B_x \\ E_z / c & -B_y & B_x & 0 \end{bmatrix}\]sub_title[[7, 9, 185, 36]]
Bonus 14: 

image[[28, 82, 498, 270]]
 

image[[531, 81, 928, 250]]
 

image_caption[[666, 250, 820, 263]]
<center>Right ascension (J2000)</center>text[[5, 9, 189, 37]]
Bonus 15: 

image[[245, 0, 625, 405]]
 

text[[637, 145, 864, 175]]
Orange = Cu²⁺ 

text[[637, 203, 827, 231]]
Purple = La 

text[[637, 260, 827, 287]]
Green = O²⁻image[[241, 10, 920, 395]]image[[219, 48, 710, 383]]text[[6, 8, 197, 40]]
Bonus 21: 

equation[[161, 85, 250, 167]]
\[ \frac{\overline{d_z^2}}{\overline{d_{xz} d_{yz}}} \]

equation[[251, 188, 320, 218]]
\[ \overline{d_{xy}} \]

equation[[251, 310, 350, 390]]
\[ \frac{\overline{d_{xy}}}{\overline{d_{xz}}} \frac{\overline{d_{yz}}}{\overline{d_{yz}}} \]

equation[[540, 26, 633, 72]]
\[ \frac{\overline{d_{yz}}}{\overline{d_{xz}}} \]

equation[[537, 161, 686, 250]]
\[ \frac{\overline{d_z^2}}{\overline{d_{xy} d_{xz^2-y^2}}} \]

equation[[775, 161, 880, 250]]
\[ \frac{\overline{d_{xy}}}{\overline{d_{xy} d_{xz^2}}} \]

equation[[775, 344, 880, 390]]
\[ \frac{\overline{d_{xz}}}{\overline{d_{yz}}} \]image[[215, 20, 735, 384]]image[[186, 33, 816, 361]]image[[204, 0, 900, 400]]text[[0, 0, 997, 997]]
# 1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1