sub_title[[461, 116, 540, 132]]
## TOSS-UP  

text[[55, 148, 945, 196]]
1) Chemistry - Short Answer Identify all of the following three statements that are true about tin (IV) chloride [Tin four chloride] under standard conditions: 1) It is soluble in benzene; 2) It has a higher melting point than tin (II) chloride [Tin two chloride]; 3) It spontaneously disproportionates.  

text[[57, 211, 206, 226]]
ANSWER:1ONLY  

sub_title[[468, 242, 535, 258]]
## BONUS  

text[[57, 273, 933, 322]]
1) Chemistry - Short Answer Identify all of the following three state functions that have a more positive change when water freezes at 10 degrees celsius than when water freezes at 0 degrees celsius: 1) Enthalpy; 2) Entropy; 3) Gibbs free energy.  

text[[57, 336, 206, 351]]
ANSWER:3ONLY  

sub_title[[461, 398, 540, 414]]
## TOSS-UP  

text[[57, 430, 918, 448]]
2) Math - Short Answer How many lattice points with positive integer coordinates lie on the line \(5x + 7y = 210?\)  

text[[57, 463, 154, 478]]
ANSWER:4  

sub_title[[468, 494, 535, 509]]
## BONUS  

text[[57, 525, 944, 558]]
2) Math - Short Answer A hexagon has side length 2. A triangle is formed by three points chosen along the perimeter of the hexagon. What is the maximum possible area of this triangle?  

text[[57, 574, 177, 591]]
ANSWER: \(3\sqrt{3}\)sub_title[[459, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 725, 119]]
3) Earth and Space - Short Answer What type of frontal lifting causes rainshadow deserts?  

text[[57, 135, 338, 150]]
ANSWER: OROGRAPHIC LIFTING  

sub_title[[468, 168, 534, 184]]
## BONUS  

text[[55, 199, 904, 232]]
3) Earth and Space - Short Answer Give, by name or number, all of the following 3 types of clouds which are NOT associated with warm fronts: 1) Altocumulus; 2) Altostratus; 3) Stratocumulus  

text[[57, 248, 195, 264]]
ANSWER: NONE  

sub_title[[462, 313, 540, 328]]
## TOSS-UP  

text[[55, 344, 940, 377]]
4) Physics - Short Answer The force on a box with mass 5 kg initially at rest increases linearly from 0 to 50 newtons in 4 seconds. What is the speed of the box after the 4 seconds in meters per second?  

text[[57, 388, 163, 403]]
ANSWER: 20  

sub_title[[468, 420, 534, 436]]
## BONUS  

text[[55, 451, 925, 484]]
4) Physics - Short Answer A force of 18 N hangs from 3 springs in parallel, with spring constants 20, 30 and 40 N/m. What is the net displacement of the system to the nearest hundredth and in meters?  

text[[57, 499, 177, 515]]
ANSWER: 1.95sub_title[[459, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 884, 120]]
5) Biology - Short Answer Which type of glial cells are specialized for secreting cerebrospinal fluid in the brain?  

text[[57, 133, 316, 149]]
ANSWER:EPENDYMALCELLS  

sub_title[[468, 165, 534, 181]]
## BONUS  

text[[57, 196, 933, 229]]
5) Biology - Short Answer Whereas efferent arterioles coming from cortical nephrons give rise to peritubular capillaries, the efferent arterioles from juxtaglomerular nephrons give rise to long looping capillaries known by what name?  

text[[57, 243, 252, 258]]
ANSWER: VASA RECTA  

sub_title[[462, 306, 540, 322]]
## TOSS-UP  

text[[57, 337, 933, 386]]
6) Energy - Short Answer Scientists at Savannah River National Lab used heated sulfur vapor to sequester mercury from contaminated soils. The scientists isolated what gaseous sulfur compound that is then oxidized in the Claus process to produce the heated sulfur vapor required to sequester mercury?  

text[[57, 400, 325, 415]]
ANSWER: HYDROGEN SUI.FIDE  

sub_title[[468, 431, 534, 447]]
## BONUS  

text[[57, 462, 928, 511]]
6) Energy - Short Answer Researchers from the Chemical Separations Group at Oak Ridge National I ab developed a new imaging method to map the variation in structure of molecules in complex environments. What type of vibrational spectroscopy did the researchers use to analyze the resulting inelastic scattering?  

text[[57, 526, 211, 541]]
ANSWER: RAMANsub_title[[458, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 933, 149]]
7) Chemistry - Multiple Choice In the reaction between methyl magnesium bromide and benzaldehyde in the absence of proton sources followed by an acidic workup, which of the following functional groups is produced as the major product?  

text[[56, 165, 219, 233]]
W) Primary alcohol  X) Secondary alcohol  Y) Tertiary alcohol  Z) Ketone  

text[[56, 251, 366, 268]]
ANSWER: X) SECONDARY ALCOHOL  

sub_title[[468, 284, 534, 300]]
## BONUS  

text[[55, 316, 937, 364]]
7) Chemistry - Short Answer The wavelength of light required to excite an electron in hydrogen from the ground-state to the first excited state is 120 nanometers. In nanometers, what wavelength of light is required to ionize an electron from the third excited state?  

text[[56, 379, 181, 394]]
ANSWER: 1440  

sub_title[[463, 440, 541, 457]]
## TOSS-UP  

text[[55, 473, 936, 505]]
8) Math - Short Answer The point (5, 7) is reflected through the point (-2, 3). What are the coordinates of the image of this transformation?  

text[[56, 520, 197, 537]]
ANSWER: (-9, -1)  

sub_title[[468, 552, 534, 568]]
## BONUS  

text[[55, 585, 914, 606]]
8) Math - Short Answer If x is a real number that satisfies \(9^{x} + 2 \cdot 3^{x + 1} = 27\) , compute the sum of all values of x.  

text[[56, 620, 152, 635]]
ANSWER: 1sub_title[[459, 65, 544, 81]]
## TOSS-UP  

text[[55, 101, 900, 119]]
9) Earth and Space - Short Answer The Saros cycle measures the occurrences and patterns of what celestial event?  

text[[56, 133, 226, 149]]
ANSWER: ECLIPSES  

sub_title[[468, 165, 534, 181]]
## BONUS  

text[[56, 196, 936, 229]]
9) Earth and Space - Short Answer Order the following three types of volcanic eruptions from least to most eruptive: 1) Plinian; 2) Vesuvian; 3) Strombolian.  

text[[56, 244, 189, 260]]
ANSWER: 3, 2, 1  

sub_title[[462, 308, 540, 324]]
## TOSS-UP  

text[[56, 340, 933, 373]]
10) Physics - Short Answer If one quadruples the turns per unit length, by what factor is the inductance per unit length changed?  

text[[56, 388, 163, 404]]
ANSWER: 16  

sub_title[[468, 419, 534, 435]]
## BONUS  

text[[56, 450, 944, 483]]
10) Physics - Short Answer You measure a loudspeaker from 6 meters away to be 55 dB. How many decibels loud would it be 60 meters from the loudspeaker?  

text[[56, 498, 163, 514]]
ANSWER: 35sub_title[[459, 65, 544, 81]]
## TOSS-UP  

text[[56, 101, 888, 149]]
11) Biology - Short Answer Chickens use the Z-W system of sex determination. Knowing this, identify all of the following three chromosomes that can be found in the male gamete: 1) X chromosome; 2) Z chromosome; 3) W chromosome.  

text[[56, 162, 210, 178]]
ANSWER:2ONLY  

sub_title[[468, 195, 534, 210]]
## BONUS  

text[[56, 225, 941, 274]]
11) Biology - Short Answer The large regions of homology between tissue plasma activator, fibronectin, and epidermal growth factor are attributed to what process via which meiotic recombination produces new combinations of coding DNA to produce new and novel proteins?  

text[[56, 287, 304, 303]]
ANSWER:EXON SHUFFLING  

sub_title[[462, 365, 540, 380]]
## TOSS-UP  

text[[56, 395, 934, 460]]
12) Energy - Multiple Choice Scientists at Argonne National I ab have been studying the dormancy of plant buds and their vernalization treatment to force them to flower. They designed a transgenic version of the plant that produced seeds that were extremely prone to germinate, even in unfavorable conditions. The levels of which of the following hormones were likely altered?  

text[[56, 475, 263, 540]]
W) Abscisic acid [ab-si-sic] X) Ethylene Y) Strigolactones Z) Jasmonates  

text[[56, 554, 300, 570]]
ANSWER:W)ABSCISICACID  

sub_title[[468, 586, 534, 601]]
## BONUS  

text[[56, 616, 936, 650]]
12) Energy - Multiple Choice Scientists at Fermilab developed an ultra pure copper cylinder to serve as an ultra sensitive detector for dark matter. What percentage of the energy in the universe is composed of dark matter?  

text[[56, 664, 117, 731]]
W) \(5\%\) X) \(25\%\) Y) \(85\%\) Z) \(99\%\)  

text[[56, 745, 202, 761]]
ANSWER:X) \(25\%\)sub_title[[458, 65, 544, 82]]
## TOSS-UP  

text[[55, 101, 916, 135]]
13) Chemistry - Multiple Choice Which of the following elements releases the most energy upon the addition of an electron in the gas phase?  

text[[55, 145, 171, 214]]
W) Phosphorus X) Sulfur Y) Nitrogen Z) Oxygen  

text[[57, 230, 238, 247]]
ANSWER: X) SULFUR  

sub_title[[469, 261, 534, 277]]
## BONUS  

text[[57, 292, 944, 357]]
13) Chemistry - Short Answer In an aqueous solution, the distance between a sodium ion and water molecule is 100 picometers, and the potential energy of the interaction between the ion and molecule is E joules. In terms of E, what is the potential energy of the interaction between a magnesium ion and water molecule separated by a distance of 200 picometers?  

text[[57, 371, 178, 387]]
ANSWER: 0.5E  

sub_title[[462, 433, 540, 449]]
## TOSS-UP  

text[[55, 464, 944, 498]]
14) Math - Short Answer A magic hat contains a standard deck of cards. How many cards must you draw from the deck to guarantee that you have at least one of each face card?  

text[[57, 512, 163, 529]]
ANSWER: 49  

sub_title[[469, 544, 534, 560]]
## BONUS  

text[[57, 575, 577, 593]]
14) Math - Short Answer Convert the base 9 numeral 5242 to base 3.  

text[[57, 607, 216, 623]]
ANSWER: 12021102sub_title[[458, 65, 544, 81]]
## TOSS-UP  

text[[55, 102, 933, 134]]
23) Biology - Short Answer 5-hydroxytryptamine reuptake inhibitors are used to treat depression because they increase the concentration of which neurotransmitters?  

text[[57, 147, 251, 162]]
ANSWER: SEROTONIN  

sub_title[[468, 179, 534, 195]]
## BONUS  

text[[57, 210, 928, 258]]
23) Biology - Short Answer Daniel the marine basket weaver is studying a living fossil. He notices that it has the following 3 characteristics. 1) Trochophore Larvae; 2) Octa-Plated Shell; 3) Strong gripping foot. What excretory organ system does this animal most likely possess?  

text[[57, 270, 308, 286]]
ANSWER: METANEPHIRIDIUM  

sub_title[[462, 347, 540, 362]]
## TOSS-UP  

text[[57, 378, 891, 411]]
24) Energy - Short Answer Researchers at the Joint Genome Institute are studying plants that can perform CAM photosynthesis. This pathway is characterized by the storage of carbon dioxide as what acid through the night?  

text[[57, 424, 251, 440]]
ANSWER: MALIC ACID  

sub_title[[468, 456, 534, 472]]
## BONUS  

text[[57, 488, 933, 551]]
24) Energy - Short Answer Researchers at Lawrence Berkeley National Lab have been using atomic force microscopy to study cellular structures. They used this to freeze the electron transport chain and identify the instantaneous processes occurring at that moment in time. Order the following three elements of the electron transport chain in increasing electronegativity: 1) Cytochrome a; 2) FMN; 3) NADH.  

text[[57, 566, 188, 581]]
ANSWER:3,2,1  

sub_title[[462, 630, 540, 645]]
## TOSS-UP  

text[[57, 661, 927, 678]]
25) Chemistry - Short Answer In the dichromate anion, how many distinct chromium oxygen bond lengths are there?  

text[[57, 692, 153, 707]]
ANSWER:2  

sub_title[[468, 725, 534, 740]]
## BONUS  

text[[57, 756, 939, 835]]
25) Chemistry - Short Answer A gas phase reaction mechanism has the following two steps: Step 1 is the rapid equilibrium of 2A yields B; Step 2 is slow of B yields C read slowly. Identify all of the following three statements that are true about this reaction: 1) The transition state for step 1 is higher in energy than in step 2; 2) The rate of formation of C is directly proportional to the concentration of A squared; 3) The spontaneity of the reaction increases as temperature increases.  

text[[57, 850, 268, 885]]
ANSWER:2 ONLY  © LOST ROUND 4 (Nat. RR4)text[[0, 0, 997, 997]]