sub_title[[458, 113, 537, 130]]
## TOSS-UP  

text[[57, 147, 933, 167]]
1) Chemistry – Multiple Choice Which of the following polyprotic acids is a strong acid only in its first dissociation step?  

text[[56, 183, 198, 250]]
W) Carbonic acid 
X) Phosphoric acid 
Y) Sulfurous acid 
Z) Sulfuric acid  

text[[57, 267, 301, 285]]
ANSWER: Z) SULFURIC ACID  

sub_title[[464, 301, 530, 318]]
## BONUS  

text[[57, 335, 936, 354]]
1) Chemistry – Multiple Choice Which of the following best describes the hybridizations of the carbon atoms in ethylene?  

text[[56, 370, 290, 437]]
W) Both are sp 
X) One is sp and the other is sp² 
Y) Both are sp² 
Z) Both are sp³  

text[[57, 454, 283, 472]]
ANSWER: Y) BOTH ARE sp²  

sub_title[[458, 523, 537, 540]]
## TOSS-UP  

text[[55, 556, 783, 575]]
2) Biology – Multiple Choice Which of the following is not an example of countercurrent exchange?  

text[[56, 591, 455, 660]]
W) Water flowing over a fish's gills 
X) Movement of the filtrate through the Loop of Henle 
Y) Warm arteries being adjacent to cooler veins 
Z) Gas exchange inside the alveoli  

text[[56, 676, 450, 694]]
ANSWER: Z) GAS EXCHANGE IN THE ALVEOLI  

sub_title[[464, 711, 530, 728]]
## BONUS  

text[[56, 744, 912, 779]]
2) Biology – Short Answer Giving your answer in millivolts, what is the equilibrium potential for sodium ions inside a neuron at \(37^{\circ}\mathrm{C}\) if the intracellular concentration is 5 millimolar and the extracellular concentration is 50 millimolar?  

text[[57, 795, 203, 812]]
ANSWER: \(+61\mathrm{mV}\)  

text[[57, 830, 446, 848]]
[Solution: (Nernst Equation) \(\mathrm{E} = 61 / \mathrm{Z}\) (log \((\mathrm{C}_{\mathrm{out}} / \mathrm{C}_{\mathrm{in}})\) ]sub_title[[460, 62, 535, 79]]
## TOSSUP  

text[[56, 96, 846, 115]]
3) Math – Short Answer Giving your answer in terms of x, what is the derivative of \(cos^3 (x)\) with respect to x?  

text[[56, 131, 255, 149]]
ANSWER: \(- 3 \sin (x) \cos^2 (x)\)  

sub_title[[465, 167, 530, 184]]
## BONUS  

text[[55, 202, 920, 237]]
3) Math– Short Answer Given that \(\sin (2x) = 0.2\) , representing your answer as a fraction with a rationalized denominator evaluate \(\cos (x) + \sin (x)\) .  

text[[56, 251, 188, 270]]
ANSWER: \(\sqrt{30} /5\)  

sub_title[[459, 322, 536, 339]]
## TOSS-UP  

text[[55, 356, 692, 375]]
4) Physics – Multiple Choice Which of the following particles is a type of gauge boson?  

text[[56, 391, 177, 457]]
W) Higgs boson 
X) Photon 
Y) Muon 
Z) Tau  

text[[56, 475, 241, 492]]
ANSWER: X) PHOTON  

sub_title[[465, 510, 530, 527]]
## BONUS  

text[[55, 544, 870, 578]]
4) Physics– Short Answer Which of the four fundamental forces has two carrier particles, and what are these two particles?  

text[[56, 594, 510, 611]]
ANSWER: WEAK NUCLEAR FORCE; W AND Z BOSONSsub_title[[459, 62, 537, 78]]
## TOSS-UP  

text[[56, 96, 940, 132]]
5) Earth and Space – Short Answer When pyrite chemically weathers, it produces sulfuric acid, which dissolves ore metals and can precipitate them into areas of higher concentrations. This is an example of what process?  

text[[57, 148, 377, 165]]
ANSWER: SECONDARY ENRICHMENT  

sub_title[[465, 182, 530, 199]]
## BONUS  

text[[56, 216, 940, 251]]
5) Earth and Space – Short Answer What is the term for the region of seawater where the density increases drastically with depth?  

text[[57, 268, 258, 285]]
ANSWER: PYCNOCLINE  

sub_title[[459, 336, 537, 352]]
## TOSS-UP  

text[[56, 369, 899, 404]]
6) Chemistry – Short Answer What is the name for additives that reduce the viscosity of a material and make it more flexible?  

text[[57, 420, 267, 437]]
ANSWER: PLASTICIZERS  

sub_title[[465, 455, 530, 472]]
## BONUS  

text[[56, 489, 624, 507]]
6) Chemistry – Short Answer What are the three most stable oxides of carbon?  

text[[56, 523, 860, 559]]
ANSWER: CO (ACCEPT: CARBON MONOXIDE), CO₂ (ACCEPT: CARBON DIOXIDE), C₃O₂ (ACCEPT: TRICARBON DIOXIDE, CARBON SUBOXIDE)sub_title[[459, 63, 537, 79]]
## TOSS-UP  

text[[56, 97, 861, 133]]
7) Biology – Multiple Choice What effect would you most likely expect from a mutation preventing a cell from expressing caspases?  

text[[56, 149, 450, 216]]
W) Inability for the cell to bind to vesicles  
X) Creation of a cancerous cell  
Y) Increased ability to detoxify poisons  
Z) Decreased permeability of the phospholipid bilayer  

text[[56, 233, 465, 250]]
ANSWER: X) CREATION OF A CANCEROUS CELL  

sub_title[[464, 267, 530, 284]]
## BONUS  

text[[56, 301, 905, 336]]
7) Biology – Multiple Choice Increasing the fluidity of the cell membrane can be accomplished in all of the following ways except:  

text[[56, 353, 470, 420]]
W) Increasing the amount of unsaturated phospholipids  
X) Increasing the length of the phospholipid tails  
Y) Increasing the amount of cholesterol in the membrane  
Z) Increasing the temperature of the membrane  

text[[56, 437, 647, 454]]
ANSWER: X) INCREASING THE LENGTH OF THE PHOSPHOLIPID TAILS  

sub_title[[461, 505, 535, 523]]
## TOSSUP  

text[[56, 540, 880, 575]]
8) Math – Multiple Choice Given that a function f(x) is continuous on the closed interval from a to b, which of the following can not be implied about the function on that interval?  

text[[56, 592, 702, 659]]
W) The function is differentiable  
X) There exists f(c) if c is greater than a but less than b  
Y) For some c, where c is greater than a but less than b, the limit as x approaches c is f(c)  
Z) There exists an absolute maximum and an absolute minimum  

text[[56, 676, 476, 693]]
ANSWER: W) THE FUNCTION IS DIFFERENTIABLE  

sub_title[[464, 710, 530, 727]]
## BONUS  

text[[56, 744, 807, 762]]
8) Math– Short Answer What is the average value of 3sin(2x) on the closed interval from 0 to pi over 2?  

text[[56, 778, 157, 796]]
ANSWER: \(\frac{6}{\pi}\)sub_title[[459, 63, 536, 79]]
## TOSS-UP  

text[[55, 97, 941, 148]]
9) Physics – Multiple Choice If a car weighing 5 kilograms that is moving at 14 meters per second on a frictionless surface elastically collides with a 2 kilogram stationary car what is the resultant final velocity of both objects in meters per second?  

text[[56, 166, 101, 234]]
W) 4 
X) 10 
Y) 7 
Z) 11  

text[[57, 251, 186, 268]]
ANSWER: X) 10  

sub_title[[465, 285, 530, 302]]
## BONUS  

text[[56, 319, 936, 387]]
9) Physics – Short Answer Suddenly and without warning, pineapples begin falling from the sky. If you measure the pineapples to hit the ground at 10 meters per second, assuming gravitational acceleration is 10 meters per second squared, how far up in the atmosphere, in meters, were the pineapples spontaneously generated? Assume the pineapples are initially at rest immediately after being generated.  

text[[57, 420, 153, 437]]
ANSWER: 5  

sub_title[[459, 473, 536, 489]]
## TOSS-UP  

text[[57, 505, 817, 524]]
10) Earth and Space – Multiple Choice Which of the following pairs of tectonic plates are NOT adjacent?  

text[[56, 540, 413, 608]]
W) Juan de Fuca Plate and North American Plate 
X) Nazca Plate and Cocos Plate 
Y) South American Plate and Scotia Plate 
Z) Antarctic Plate and Cocos Plate  

text[[56, 625, 497, 642]]
ANSWER: Z) ANTARCTIC PLATE AND COCOS PLATE  

sub_title[[465, 659, 530, 676]]
## BONUS  

text[[56, 693, 904, 727]]
10) Earth and Space – Short Answer What is the term for a narrow band of strong air currents several miles above the Earth?  

text[[57, 744, 251, 761]]
ANSWER: JET STREAMsub_title[[459, 63, 537, 78]]
## TOSS-UP  

text[[56, 96, 677, 115]]
11) Chemistry – Short Answer What is the highest occupied molecular orbital of \(F_{2}^{-}\) ?  

text[[55, 132, 295, 214]]
W) \(\sigma_{2p}\) [sigma 2-p bonding] 
X) \(\pi_{2p}\) [pi 2-p bonding] 
Y) \(\sigma_{2p}^{*}\) [sigma 2-p antibonding] 
Z) \(\pi_{2p}^{*}\) [pi 2-p antibonding]  

text[[56, 231, 194, 250]]
ANSWER: Y) \(\sigma_{2p}^{*}\)  

sub_title[[468, 270, 530, 286]]
## BONUS  

text[[56, 303, 910, 338]]
11) Chemistry – Short Answer What is the name for the nitrogen hydride that is a powerful reducing agent, commonly used in rocket fuel, and a colorless, pungent liquid at standard temperature and pressure?  

text[[56, 354, 598, 371]]
ANSWER: HYDRAZINE (ACCEPT: DINITROGEN TETRAHYDRIDE)  

sub_title[[459, 421, 537, 438]]
## TOSS-UP  

text[[56, 455, 917, 489]]
12) Biology – Multiple Choice A plant is placed so that light shines from the west. In what direction would you expect indoleacetic acid to accumulate?  

text[[56, 507, 128, 574]]
W) North 
X) South 
Y) East 
Z) West  

text[[57, 592, 212, 608]]
ANSWER: Y) EAST  

sub_title[[466, 627, 530, 643]]
## BONUS  

text[[56, 660, 715, 679]]
12) Biology – Multiple Choice Which of the following is not a characteristic of a monocot?  

text[[56, 696, 388, 762]]
W) Presence of lateral meristems 
X) Scattered vascular bundles inside the stem 
Y) Parallel arrangement of veins in the leaves 
Z) Floral parts in multiples of 3  

text[[56, 779, 482, 796]]
ANSWER: W) PRESENCE OF LATERAL MERISTEMSsub_title[[460, 62, 535, 79]]
## TOSSUP  

text[[56, 96, 775, 116]]
13) Math – Multiple Choice Which of the following is equivalent to \(\cos (\frac{\pi}{3}) \cos (\frac{\pi}{6}) + \sin (\frac{\pi}{3}) \sin (\frac{\pi}{6})\) ?  

text[[56, 116, 97, 130]]
W) 1  

text[[56, 133, 97, 147]]
X) 0  

text[[56, 150, 108, 165]]
Y) \(1 / 2\)  

text[[56, 165, 100, 184]]
Z) \(\frac{\sqrt{3}}{2}\)  

text[[56, 198, 184, 219]]
ANSWER: Z) \(\frac{\sqrt{3}}{2}\)  

sub_title[[465, 236, 530, 253]]
## BONUS  

text[[56, 270, 477, 288]]
13) Math–Short Answer How many digits does \(2^{32}\) have?  

text[[56, 306, 163, 322]]
ANSWER: 10  

sub_title[[460, 357, 536, 373]]
## TOSSUP  

text[[56, 390, 939, 442]]
14) Physics – Short Answer A 10 kilogram block is attached to a light cord that is wrapped around the pulley of an electric motor. Giving your answer in watts, at what rate is the motor doing work when it is pulling the block upward with an instantaneous speed of 3 meters per second and an upward acceleration of 2 meters per second squared?  

text[[56, 459, 172, 475]]
ANSWER: 360  

sub_title[[465, 493, 530, 510]]
## BONUS  

text[[56, 526, 930, 578]]
14) Physics – Short Answer Let G [big G] represent the universal gravitational constant. What is the kinetic energy of a satellite of mass m [little m] that orbits the Earth, of mass M [big m], in a circular orbit of radius R? Express your answer in terms of the given variables.  

text[[56, 594, 696, 612]]
ANSWER: THE FRACTION WITH NUMERATOR GMm AND DENOMINATOR 2Rsub_title[[459, 63, 536, 79]]
## TOSS-UP  

text[[56, 97, 935, 148]]
15) Earth and Space – Short Answer What wind erosion mechanism, often coupled with abrasion, leads to the formation of hamadas and blowouts and is defined as the process by which loose particles on the Earth’s surface are eroded by wind turbulence?  

text[[57, 166, 245, 182]]
ANSWER: DEFLATION  

sub_title[[465, 200, 530, 216]]
## BONUS  

text[[56, 234, 937, 268]]
15) Earth and Space – Short Answer What is the term for submerged, flat-topped seamounts that were originally above sea level until plate movement brought them apart from their source of magma?  

text[[57, 285, 217, 301]]
ANSWER: GUYOTS  

sub_title[[459, 353, 536, 369]]
## TOSS-UP  

text[[57, 386, 925, 404]]
16) Chemistry – Multiple Choice Which of the following elements’ most common ion is NOT isoelectronic with xenon?  

text[[56, 421, 155, 488]]
W) Cesium 
X) Tellurium 
Y) Strontium 
Z) Iodine  

text[[57, 506, 272, 522]]
ANSWER: Y) STRONTIUM  

sub_title[[465, 558, 530, 574]]
## BONUS  

text[[56, 592, 933, 626]]
16) Chemistry – Multiple Choice According to hard soft acid base theory, which of the following pairs of acids and bases are predicted to react most quickly and form the strongest bonds?  

text[[57, 643, 306, 710]]
W) Hydronium and iodide 
X) Silver(I) and hydroxide 
Y) Boron trifluoride and ammonia 
Z) Borane and chloride  

text[[57, 728, 490, 744]]
ANSWER: Y) BORON TRIFLUORIDE AND AMMONIAsub_title[[459, 62, 536, 78]]
## TOSS-UP  

text[[56, 96, 936, 131]]
17) Biology – Short Answer What specific enzyme is responsible for replacing the RNA primers with DNA in prokaryotic replication?  

text[[56, 148, 448, 165]]
ANSWER: DNA POLYMERASE I (ACCEPT: Pol I)  

sub_title[[468, 199, 530, 216]]
## BONUS  

text[[56, 233, 933, 302]]
17) Biology – Short Answer In Drosophila, vestigial wings and sepia eyes are both autosomal recessive traits. A dihybrid testcross yields the following frequencies of phenotypes: 475 individuals with both wild traits, 403 individuals with vestigial wings and sepia eyes, 56 individuals with wild eyes and vestigial wings, and 66 individuals with wild wings and sepia eyes. What is the map distance between the wing and eye loci in centimorgans?  

text[[56, 319, 176, 335]]
ANSWER: 12.2  

sub_title[[462, 387, 533, 403]]
## TOSSUP  

text[[57, 420, 399, 437]]
18) Math – Short Answer What is 10 choose 3?  

text[[56, 455, 171, 471]]
ANSWER: 120  

sub_title[[465, 489, 530, 506]]
## BONUS  

text[[56, 523, 919, 558]]
18) Math – Short Answer How many trailing zeros are there in the number of ways to arrange 21 people in a line from a group of 75?  

text[[56, 575, 153, 590]]
ANSWER: 6sub_title[[459, 63, 536, 78]]
## TOSS-UP  

text[[57, 97, 714, 114]]
19) Physics – Multiple Choice Which of these statements about inelastic collisions is false?  

text[[56, 132, 585, 200]]
W) Momentum is conserved  
X) The Coefficient of Restitution is less than 1  
Y) Objects can stick to each other if the Coefficient of Restitution is zero  
Z) Mechanical Energy is Conserved  

text[[56, 217, 495, 233]]
ANSWER: Z) MECHANICAL ENERGY IS CONSERVED  

sub_title[[466, 251, 530, 267]]
## BONUS  

text[[56, 285, 918, 335]]
19) Physics – Short Answer Two objects of the same mass m are traveling on a flat surface, with Object 1 traveling at 5 meters per second to the right and Object 2 traveling at 10 meters per second to the left prior to the collision. The two objects collide elastically. What is the post collision velocity of object 2 in meters per second?  

text[[56, 353, 153, 368]]
ANSWER: 5  

sub_title[[459, 404, 536, 420]]
## TOSS-UP  

text[[56, 438, 888, 472]]
20) Earth and Space – Short Answer What astronomical law states that galaxies recede at rates proportional to their distance from the observer?  

text[[56, 489, 277, 505]]
ANSWER: HUBBLE'S LAW  

sub_title[[466, 523, 530, 540]]
## BONUS  

text[[55, 557, 899, 575]]
20) Earth and Space – Multiple Choice Which of the following statements is NOT true about the Sun’s photosphere?  

text[[56, 592, 570, 659]]
W) The photosphere is estimated to be around 100 kilometers thick  
X) It is covered in convection cells called granules  
Y) Approximately 99% of the Sun’s surface atoms are hydrogen atoms  
Z) The photosphere’s average temperature is about 6000 Kelvin  

text[[56, 676, 847, 694]]
ANSWER: Y) APPROXIMATELY 99% OF THE SUN’S SURFACE ATOMS ARE HYDROGEN ATOMS