
## TOSS-UP  


1) Biology – Multiple Choice Which of the following amino acids absorbs ultraviolet light the best?  


W) Histidine  X) Tyrosine  Y) Tryptophan  Z) Isoleucine  


ANSWER: Y) TRYPTOPHAN  


## BONUS  


1) Biology – Short Answer What is the name of the muscular valve that controls the flow of bile and pancreatic juices into the duodenum?  


ANSWER: SPHINCTER OF ODDI (ACCEPT: HEPATOPANCREATIC SPHINCTER OR GLISSON'S SPHINCTER)  


## TOSS-UP  


2) Math – Multiple Choice Which of the following statements is the logical negation of the claim: “For all i in the naturals, there exists j in the naturals such that i is less than j”?  


W) For all i in the naturals, there exists j in the naturals such that i is greater than j  X) For all i in the naturals, there exists j in the naturals such that i is greater than or equal to j  Y) There exists i in the naturals such that, for all j in the naturals, i is greater than j  Z) There exists i in the naturals such that, for all j in the naturals, i is greater than or equal to j  


ANSWER: Z) THERE EXISTS i IN THE NATURALS SUCH THAT, FOR ALL j IN THE NATURALS, i IS GREATER THAN OR EQUAL TO j  


## BONUS  


2) Math – Short Answer Consider the column vector \(\mathbf{v}_1\) with entries 1, 2, 2 and the column vector \(\mathbf{v}_2\) with entries 2, 0, 0. Let w equal the span of \(\mathbf{v}_1\) and \(\mathbf{v}_2\) . If \(\mathbf{v}_1\) is one vector in some orthogonal basis of w, find a possible value for another vector in that basis using the Gram-Schmidt process.  


ANSWER: THE COLUMN VECTOR WITH ENTRIES 16/9, - 4/9, - 4/9 (ACCEPT: THE MATRIX WITH FIRST ROW 16/9 SECOND ROW - 4/9 THIRD ROW - 4/9)
## TOSS-UP  


3) Chemistry – Multiple Choice Which of the following substrates can sodium borohydride not reduce?  


W) acid chlorides 
X) aldehydes 
Y) ketones 
Z) amines  


ANSWER: Z) AMINES  


## BONUS  


3) Chemistry – Short Answer Identify which of the following three compounds are strong bases in water. 
1) \(\mathrm{Mg(OH)_2}\) [magnesium hydroxide] 2) \(\mathrm{NaH}\) [sodium hydride] 3) Grignard reagent  


ANSWER: 1, 2, AND 3  


## TOSS-UP  


4) Physics – Multiple Choice For a Uranium – 234 isotope that undergoes decay chains becoming a stable nuclide of lead with the neutron count of 124, how many alpha decay steps have occurred in this nuclear transformation? There is a total of 11 steps.  


W) Eight 
X) Seven 
Y) Six 
Z) Five  


ANSWER: Y) SEVEN  


## BONUS  


4) Physics – Multiple Choice Which of the following statements is not true of a damped harmonic oscillator system?  


W) If the system is underdamped it will reach the equilibrium position faster than if it were critically damped 
X) If the system is overdamped it will reach the equilibrium position slower than if it were critically damped 
Y) If the system is underdamped it will oscillate around the equilibrium position after reaching it 
Z) If the system is overdamped it will oscillate around the equilibrium position after reaching it  


ANSWER: Z) IF THE SYSTEM IS OVERDAMPED IT WILL OSCILLATE AROUND THE EQUILIBRIUM POSITION AFTER REACHING IT
## TOSS-UP  


5) Biology – Multiple Choice Which of the following best describes oxidative deamination?  


W) Conversion of an amino acid to a carboxylic acid and ammonia  X) Conversion of an amino acid to a keto acid and ammonia  Y) Conversion of the amine group of an amino acid to a carboxylic acid  Z) Conversion of the amine group of an amino acid to a keto acid  


ANSWER: X) CONVERSION OF AN AMINO ACID TO A KETO ACID AND AMMONIA  


## BONUS  


5) Biology – Multiple Choice Which of the following Cas9 domains is incorrectly matched with its function?  


W) RuvC: Cleaves the non-target DNA strand  X) HNH: Cleaves the target DNA strand  Y) PAM interacting domain: Initiation of cleavage activity  Z) Rec1: Binding guide RNA  


ANSWER: Y) PAM INTERACTING DOMAIN: INITIATION OF CLEAVAGE ACTIVITY  


## TOSS-UP  


6) Chemistry – Multiple Choice Which of the following rules predicts that lone pair orbitals should have higher s-character and, more generally, states that hybrid orbitals of greater p-character tend to be directed at more electronegative substituents?  


W) Bent's rule  X) Woodward-Hoffman rules  Y) Wade's rules  Z) Tolman's rule  


ANSWER: W) BENT'S RULE  


## BONUS  


6) Chemistry – Multiple Choice Which of the following reactions is most exothermic?  


W) \(\mathrm{N}_2\mathrm{H}_4\rightarrow \mathrm{N}_2 + 2\mathrm{H}_2\) X) \(3\mathrm{N}_2\mathrm{H}_4\rightarrow 4\mathrm{NH}_3 + \mathrm{N}_2\) Y) \(4\mathrm{NH}_3 + \mathrm{N}_2\mathrm{H}_4\rightarrow 3\mathrm{N}_2 + 8\mathrm{H}_2\) Z) \(\mathrm{N}_2\mathrm{H}_4 + 2\mathrm{H}_2\mathrm{O}\rightarrow 2\mathrm{NH}_3 + \mathrm{H}_2\mathrm{O}_2\)  


ANSWER: X) \(3\mathrm{N}_2\mathrm{H}_4\rightarrow 4\mathrm{NH}_3 + \mathrm{N}_2\)
## TOSS-UP  


7) Earth and Space – Multiple Choice What makes Type Ia supernovae different from Ib, Ic, and type II supernovae?  


W) Type Ia supernovae only involve one star  X) Type Ia supernovae do not originate from stellar core collapses  Y) Type Ia supernovae make up the vast majority of all supernovae  Z) Type Ia are not as luminous  


ANSWER: X) TYPE Ia SUPERNOVAE DO NOT ORIGINATE FROM STELLAR CORE COLLAPSES  


## BONUS  


7) Earth and Space – Multiple Choice In what region of the Hertzsprung-Russell diagram can RR Lyrae and Cepheid variables be found?  


W) Main sequence  X) Hayashi track  Y) Instability strip  Z) Red-giant branch  


ANSWER: Y) INSTABILITY STRIP  


## TOSS-UP  


8) Physics – Multiple Choice A sound source is at rest at point X. Bob stands at a point a distance r from X. Bob moves so that he is now a distance 2r from X. The intensity of the sound at this new point assuming everything else stays constant is how many times the intensity of the sound at the original point?  


W) 1  X) ½  Y) ¼  Z) ½  


ANSWER: Y) ¼  


## BONUS  


8) Physics – Short Answer The adiabatic constant of an ideal gas is 1.5, and the molecular mass of the gas is 30 g/mol. Assume that the universal gas constant is approximated to 8 J/mol K. If the temperature of the gas is 127 degrees Celsius, what is the speed of sound through the gas in meters per second and to one significant digit?  


ANSWER: 400 m/s
## TOSS-UP  


9) Math – Multiple Choice Which of the following shapes have eccentricity values of 0 and 1, respectively?  


W) Parabola and hyperbola  
X) Parabola and ellipse  
Y) Circle and ellipse  
Z) Circle and parabola  


ANSWER: Z) CIRCLE AND PARABOLA  


## BONUS  


9) Math – Short Answer Find the volume of the tetrahedron bounded by the equation \(3x + 3y + 2z = 6\) and the coordinate planes.  


ANSWER: 2  


## TOSS-UP  


10) Biology – Short Answer What compound enables the body to absorb cobalamin and is the product of the parietal cells?  


ANSWER: INTRINSIC FACTORS  


## BONUS  


10) Biology – Multiple Choice Which of the following causes a right shift in the Oxygen-Hemoglobin Dissociation Curve?  


W) Higher pH  
X) Lower Temperature  
Y) Higher concentrations of 2,3-BPG  
Z) Lower partial pressure of Carbon Dioxide  


ANSWER: Y) HIGHER CONCENTRATIONS OF 2,3-BPG
## TOSS-UP  


11) Chemistry – Multiple Choice Which of the following is not a reason that correctly explains the stability of benzene?  


W) Benzene has alternating single and double bonds, exchanging in fast equilibrium around the ring to make it undetectable by NMR  


X) Benzene has no unpaired pi electrons in the antibonding orbitals  


Y) Benzene has overlapping \(p\) orbitals in one continuous system  


Z) Benzene has 6 pi electrons in the ring, which is a Huckel number  


ANSWER: W) BENZENE HAS ALTERNATING SINGLE AND DOUBLE BONDS, EXCHANGING IN FAST EQUILIBRIUM AROUND THE RING TO MAKE IT UNDETECTABLE BY NMR  


## BONUS  


11) Chemistry – Multiple Choice Which of the following concepts can be used to explain the weak acid property of hydrofluoric acid?  


W) London Dispersion Forces  


X) Ion pairs  


Y) Ionic bonding  


Z) Induced dipole-dipole moment  


ANSWER: X) ION PAIRS  


## TOSS-UP  


12) Earth and Space – Multiple Choice Which of the following describes a lake that has layers that intermix at least once a year?  


W) Amicitc  


X) Holomictic  


Y) Meromictic  


Z) Unimictic  


ANSWER: X) HOLOMICTIC  


## BONUS  


12) Earth and Space – Multiple Choice Which of the following is not true of manganese nodules?  


W) They must remain buried under sediment to grow  


X) They are classified as hydrogenous sediment  


Y) They are of economic interest because they contain valuable metals  


Z) They grow at the rate of 1- 10 millimeters per million years  


ANSWER: W) THEY MUST REMAIN BURIED UNDER SEDIMENT TO GROW
## TOSS-UP  


13) Physics – Short Answer For a lens of focal length 20 cm, what will be the image distance, in centimeters, for an object 30 cm from the lens? Assume the thickness of the lens is negligible.  


ANSWER: 60  


## BONUS  


13) Physics – Short Answer What is the term for self-reinforcing waves that maintain their shape while traveling at constant speed?  


ANSWER: SOLITON [accept SOLITARY WAVE]  


## TOSS-UP  


14) Math – Short Answer Let A be a set of 3 distinct elements and B be a set of 5 distinct elements. How many distinct functions exist that map A to B?  


ANSWER: 125  


## BONUS  


14) Math – Multiple Choice Consider a probability measure \(\mathrm{Pr} / \mathrm{P - R} /\) on a sample space S. Which of the following statements is not true as a direct result of Kolmogorov's axioms?  


W) For all events E in S, \(\mathrm{Pr}(\mathrm{E}) = 0\) if and only if E is the empty set  


X) For all events E in S, \(\mathrm{Pr}(\mathrm{E}) \geq 0\)  


Y) \(\mathrm{Pr}(\mathrm{S}) = 1\)  


Z) For all disjoint events \(\mathrm{E}_{1}\) and \(\mathrm{E}_{2}\) in S, \(\mathrm{Pr}(\mathrm{E}_{1} \cup \mathrm{E}_{2}) = \mathrm{Pr}(\mathrm{E}_{1}) + \mathrm{Pr}(\mathrm{E}_{2})\)  


ANSWER: W) FOR ALL EVENTS E IN S, \(\mathrm{Pr}(\mathrm{E}) = 0\) IF AND ONLY IF E IS THE EMPTY SET
## TOSS-UP  


15) Biology – Multiple Choice Which of the following is true of cardiac muscle?  


W) It is multipennate  X) It contains Nissl Bodies  Y) It is fusiform  Z) It contains Intercalated Disks  


ANSWER: Z) IT CONTAINS INTERCALATED DISKS  


## BONUS  


15) Biology – Multiple Choice Which of the following proteins is NOT associated with the M line of a sarcomere?  


W) Myomesin  X) Obscurin  Y) Dystrophin  Z) M-protein  


ANSWER: X) OBSCURIN  


## TOSS-UP  


16) Earth and Space – Multiple Choice What is the standard concentration, in milligrams per liter, of nitrate that is suitable for drinking water?  


W) 100  X) 10  Y) 1  Z) 0.1  


ANSWER: X) 10  


## BONUS  


16) Earth and Space – Multiple Choice Which of the following corallivores, when overpopulated, have massive damaging effects on coral reefs?  


W) Triton  X) Crown of Thorns Starfish  Y) Diadema  Z) Pencil urchins  


ANSWER: X) CROWN OF THORNS STARFISH
## TOSS-UP  


17) Earth and Space – Multiple Choice Rayleigh and Love waves differ from P and S waves in which way?  


W) They travel faster 
X) They are compression waves 
Y) They are surface waves 
Z) They do not dissipate quickly  


ANSWER: Y) They are surface waves  


## BONUS  


17) Earth and Space – Short Answer Select all of the following that are more abundant in river water than in ocean water: 
1) Silica; 
2) Calcium; 
3) Bicarbonate.  


ANSWER: ALL [accept 1, 2, 3]  


## TOSS-UP  


18) Math – Multiple Choice Which of the following quadric surfaces corresponds to the equation \(-3x^{2} + 2y^{2} - z = 0\) ?  


W) Cylinder 
X) Elliptic paraboloid 
Y) Hyperbolic paraboloid 
Z) Hyperboloid of one sheet  


ANSWER: Y) HYPERBOLIC PARABOLOID  


## BONUS  


18) Math – Short Answer By name or number, identify all of the following three subgraphs that a finite planar graph cannot contain according to Kuratowski’s theorem: 1) \(\mathrm{K}_{3,3}\) [K-sub-3-3]; 2) \(\mathrm{K}_{3,5}\) [K-sub-3-5]; 3) \(\mathrm{K}_{5}\) [K-sub-5].  


ANSWER: 1 AND 3
## TOSS-UP  


19) Physics- Multiple Choice Suppose there is a wire carrying a current going to the top of the page. Point A is on the page and to the left of the current. What is the direction of the current at point A?  


W) Into page  X) Out of page  Y) Top of page  Z) Bottom of page  


ANSWER: X) OUT OF PAGE  


## BONUS  


19) Physics- Short Answer What is the equivalent capacitance of a circuit with a 5V battery and 2 capacitors, each with a capacitance of 1F, connected in parallel?  


ANSWER: 2  


## TOSS-UP  


20) Chemistry - Short Answer What type of reaction would occur if the potential to the right of the species is higher than the potential on the left on a Latimer diagram?  


ANSWER: DISPROPORTIONATION (ACCEPT: DISMUTATION; DO NOT ACCEPT: REDOX)  


## BONUS  


20) Chemistry - Multiple Choice In thermodynamics, which of the following will the Gibbs Free energy be equal to in a system at constant temperature and pressure?  


W) maximum expansion work  X) maximum non-expansion work  Y) minimum heat transfer  Z) internal energy  


ANSWER: X) MAXIMUM NON- EXPANSION WORK