
## TOSS-UP  


1) Physics – Multiple Choice Which of the following best explains why the interference pattern predicted in Young’s double slit experiment differed slightly from the actual empirical observation?  


W) The particle like nature of light interfering 
X) The superposition of photons on the interference pattern 
Y) Rays were theoretically treated as parallel 
Z) Diffraction around slit openings  


ANSWER: Y) RAYS WERE THEORETICALLY TREATED AS PARALLEL  


## BONUS  


1) Physics – Short Answer A 10 kilogram block is suspended from a roof by three massless ropes: one is at 30 degrees above the horizontal and to the left of the block; a second is directly vertical; and a third is 60 degrees above the horizontal and to the right of the block. If the tension in the vertical rope is 20 newtons, then expressing your answer in simplest radical form, what is the tension in the third, rightmost rope?  


ANSWER: \(40\sqrt{3}\)  


## TOSS-UP  


2) Earth and Space – Multiple Choice What mechanism most likely forms malachite?  


W) Magmatic Differentiation 
X) Hydrothermal Enrichment 
Y) Placer Deposition 
Z) Secondary Replacement  


ANSWER: X) HYDROTHERMAL ENRICHMENT  


## BONUS  


2) Earth and Space – Short Answer Name all of the following 3 statements concerning hydrothermal enrichment that are true: 1) Sedimentary Exhalative deposits are fluvial; 2) Skarn is formed with calcalkaline fluids; 3) Porphyries are found near Mid ocean ridges.  


ANSWER: 2 ONLY
## TOSS-UP  


3) Chemistry - Short Answer What is the molecular geometry of acetylene?  


ANSWER: LINEAR  


## BONUS  


3) Chemistry - Short Answer Identify all of the following three coordination complexes that exhibit paramagnetism: 1) \(\mathrm{Ni(CO)_4}\) ; 2) \(\mathrm{[Fe(SCN)_6]^{3 - }}\) ; 3) \(\mathrm{[PtCl_4]^{2 - }}\) .  


ANSWER: 2 AND 3  


## TOSS-UP  


4) Math - Short Answer Given that \(f(x) = x^{3} + x + 1\) , find the slope of the tangent line of f inverse of x at \(x = 1\) .  


ANSWER: 1  


## BONUS  


4) Math - Short Answer Going up to the \(x^{\wedge}2\) term, what is the Maclaurin series approximation of e-squared?  


ANSWER: 5
## TOSS-UP  


5) Biology - Short Answer What is the name of the central cavity of sponges?  


ANSWER: SPONGOCOEL  


## BONUS  


5) Biology - Short Answer What is the name of the head side of the tapeworm?  


ANSWER: SCOLEX  


## TOSS-UP  


6) Earth and Space - Multiple Choice Which of the following is NOT a reason why there is no Ekman transport in the atmospheric circulation cells, while it is found in surface ocean currents?  


W) Circulation cells are driven by pressure gradient force  


X) Ocean waves are driven by prevailing winds  


Y) Friction has a significantly larger effect in oceans compared to circulation cells  


Z) Coriolis has a small, but meaningful contribution to both fluid phenomena  


ANSWER: W) CIRCULATION CELLS ARE DRIVEN BY PRESSURE GRADIENT FORCE  


## BONUS  


6) Earth and Space - Short Answer What atmospheric phenomenon causes the distinctive Sargassum Seaweed to coalesce into large linear swaths?  


ANSWER: LANGMUIR CIRCULATION
## TOSS-UP  


7) Chemistry – Multiple Choice Given that the \(\mathrm{pK}_{\mathrm{a}}\) of acetylene is 25, the \(\mathrm{pK}_{\mathrm{a}}\) of ammonia is 37, and the \(\mathrm{pK}_{\mathrm{a}}\) of water is 15.7, which of the following bases could be used to deprotonate acetylene?  


W) Ammonia X) Sodium amide Y) Water Z) Sodium hydroxide  


ANSWER: X) SODIUM AMIDE  


## BONUS  


7) Chemistry – Short Answer Identify all of the following three statements that are true of the hydride anion: 1) It is larger than the fluoride anion; 2) It can act as a strong base on its own; 3) It can act as a strong nucleophile on its own.  


ANSWER: 1 AND 2  


## TOSS-UP  


8) Math – Short Answer How many terminal zeroes does 2020! have?  


ANSWER: 503  


## BONUS  


8) Math – Short Answer In the 2020 Summer Olympics, a total of X athletes will participate. These X athletes can be divided into 3, 4, 5, and 7 rows without a remainder. If there are less than 2020 athletes competing and the value of X is such that it yields the minimum number of athletes remaining when they are divided into 13 rows, what is X?  


ANSWER: 1,680
## TOSS-UP  


9) Chemistry – Short Answer What effect is exemplified by the role of the sulfur atom in sulfur mustard during intramolecular \(\mathrm{S}_\mathrm{N}2\) reactions and is defined as the interaction of an electron pair with an adjacent reaction center?  


ANSWER: ANCHIMERIC ASSISTANCE [ACCEPT NEIGHBORING GROUP PARTICIPATION OR NGP]  


## BONUS  


9) Chemistry – Short Answer Identify the HOMO of each of the following 3 molecules in their most common state as singlet, doublet, or triplet, respectively: 1) \(\mathrm{O}_2^{2 - }\) ; 2) \(\mathrm{O}_2\) ; 3) \(\mathrm{O}_2^+\) .  


ANSWER: SINGLET, TRIPLET, DOUBLET  


## TOSS-UP  


10) Biology – Multiple Choice Which of the following groups of cnidarians do not possess a medusa stage?  


W) Anthozoans 
X) Scyphozoans 
Y) Cubozoans 
Z) Hydrozoans  


ANSWER: W) ANTHOZOANS  


## BONUS  


10) Biology – Short Answer What is the name for a group of cephalopods with external shells?  


ANSWER: NAUTILUSES
## TOSS-UP  


11) Physics – Multiple Choice According to BCS theory, superconductivity is caused by the interaction between what two particles?  


W) Electron and electron hole 
X) Electron hole and phonon 
Y) Phonon and exciton 
Z) Electron and phonon  


ANSWER: Z) ELECTRON AND PHONON  


## BONUS  


11) Physics – Short Answer A one dimensional box contains 64 particles. If the number of particles in the box is halved while the length of the box is doubled, by what factor will the zero point energy and the highest occupied energy state change by, respectively?  


ANSWER: Zero point energy: \(1 / 4\) , Highest energy state: 1/16  


## TOSS-UP  


12) Earth and Space – Short Answer The ability for carbonates to form varies with depth. What is the name for the ocean depth found near the mixed layer below which the rate of calcite dissolution increases dramatically due to a pressure effect?  


ANSWER: LYSOCLINE  


## BONUS  


12) Earth and Space – Short Answer Name all of the following gemstone-mineral pairs which are correctly paired together: 1) Peridot and olivine; 2) Opal and Quartz; 3) Ruby and Corundum.  


ANSWER: ALL
## TOSS-UP  


13) Chemistry – Short Answer What is the oxidation number of the central carbon of isopropanol?  


ANSWER: 0  


## BONUS  


13) Chemistry – Short Answer The \(\mathrm{Mn}^{2 + } / \mathrm{Mn}(\mathrm{s})\) couple has a standard reduction potential of -1.2 volts, while the \(\mathrm{Mn}^{3 + } / \mathrm{Mn}(\mathrm{s})\) couple has a standard reduction potential of +1.5 volts. What is the standard reduction potential of the \(\mathrm{Mn}^{2 + } / \mathrm{Mn}^{3 + }\) couple?  


ANSWER: - 0.3 volts  


## TOSS-UP  


14) Math – Short Answer What is the sum of the first 12 perfect cubes?  


ANSWER: 6,084  


## BONUS  


14) Math – Short Answer Solve for x in the equation x(x-1)(x-2)-(x-1)^3 = -1  


ANSWER: 2
## TOSS-UP  


15) Biology – Short Answer What is the term for a crown of ciliated tentacles that function in feeding, are found in a namesake major clade of Bilateria?  


ANSWER: LOPHOPHORE  


## BONUS  


15) Biology – Short Answer What is the name of the individual units of tapeworm that come after the scolex?  


ANSWER: PROGLOTTIDS  


## TOSS-UP  


16) Physics – Short Answer Identify all of the following three particles that follow Fermi-Dirac statistics: 1) Muon; 2) Gluon; 3) Neutron.  


ANSWER: 1 AND 3  


## BONUS  


16) Physics – Short Answer Identify all of the following three statements that are true about work in an isothermal process: 1) The amount of work done in an irreversible process is always greater than in a reversible process; 2) The amount of work done in an isothermal process is equal in magnitude to the change in heat; 3) Free expansion is an irreversible process and does no work.  


ANSWER: 2 AND 3
## TOSS-UP  


17) Earth and Space – Short Answer Order the following 3 stages of a star’s life from first to last: 1) White Dwarf; 2) Red Giant; 3) Yellow Dwarf.  


ANSWER: 3, 2, 1  


## BONUS  


17) Earth and Space – Short Answer What specific type of proton proton chain sequence is the most energetic and helium 3 directly captures a proton to form helium 4 in the last step?  


ANSWER: PROTON PROTON CHAIN 4 (ACCEPT: P- P IV BRANCH OR HEP BRANCH)  


## TOSS-UP  


18) Chemistry – Multiple Choice Which of the following compounds is nonaromatic?  


W) \(\mathrm{C}_{8}\mathrm{H}_{8}^{+}\) X) \(\mathrm{C}_{8}\mathrm{H}_{8}\) Y) \(\mathrm{C}_{8}\mathrm{H}_{8}^{-}\) Z) \(\mathrm{C}_{18}\mathrm{H}_{18}\)  


ANSWER: X) \(\mathrm{C}_{8}\mathrm{H}_{8}\)  


## BONUS  


18) Chemistry – Multiple Choice Which of the following crown ethers is best for sequestering the \(\mathrm{Mg}^{2 + }\) cation?  


W) 12- crown- 4 X) 15- crown- 5 Y) 18- crown- 6 Z) 21- crown- 7  


ANSWER: W) 12- CROWN- 4
## TOSS-UP  


19) Math – Short Answer What is the remainder when \(4^{2020}\) is divided by 3?  


ANSWER: 1  


## BONUS  


19) Math – Multiple Choice Which of the following powers of 10 is closest to \(4^{300}\) ?  


W) 175  X) 180  Y) 185  Z) 190  


ANSWER: X) 180  


## TOSS-UP  


20) Chemistry – Multiple Choice Which of the following nuclides would decay via electron capture?  


W) Carbon 11  X) Boron 11  Y) Nitrogen 12  Z) Nitrogen 15  


ANSWER: W) CARBON 11  


## BONUS  


20) Chemistry – Multiple Choice Which of the following is used to remove the BOC protecting group from amines?  


W) Carbamic acid  X) Methanimidic acid  Y) Tetra-n-butylammonium fluoride  Z) Trifluoroacetic acid  


ANSWER: Z) TRIFLUOROACETIC ACID